llvm/circt

lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
lib/Dialect/Comb/CombFolds.cpp
lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp
lib/Dialect/FIRRTL/FIRRTLDialect.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
lib/Dialect/FIRRTL/Transforms/InferResets.cpp
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
lib/Scheduling/TestPasses.cpp
lib/Support/BackedgeBuilder.cpp

Fix the warnings build with release mode on circt.
This can happen when you build llvm and circt with CMake option
-DLLVM_ENABLE_ASSERTIONS=OFF 
-DCMAKE_BUILD_TYPE=Release 
fix it by placing the temporary variable in the assert function
or with the attribute maybe_unused.
```shell
cd circt
mkdir llvm/build && cd llvm/build
cmake -G Ninja ../llvm \
-DLLVM_ENABLE_PROJECTS="mlir" \
-DLLVM_TARGETS_TO_BUILD="host" \
-DLLVM_ENABLE_ASSERTIONS=OFF \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON  \
-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_ENABLE_LLD=ON
ninja
ninja check-mlir
cd circt
mkdir build && cd build
cmake -G Ninja .. \
-DMLIR_DIR=$PWD/../llvm/build/lib/cmake/mlir \
-DLLVM_DIR=$PWD/../llvm/build/lib/cmake/llvm \
-DLLVM_ENABLE_ASSERTIONS=OFF \ …
```

[NFC] Fix warnings when build the release type.

---

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
test/Conversion/SCFToCalyx/convert_memory.mlir
test/Conversion/SCFToCalyx/convert_pipeline.mlir

Currently doing some work on figuring out how to hook up Calyx with the cosimulation infrastructure in CIRCT-HLS. For this, i need to determine the set of ports which specifies an external memory connection. While this is possible via. a purely string-based approach, i'd like to be a bit safer and actually add some tagging information in SCFToCalyx to help resolve the ports that constitutes the interface.
This initial commit just adds the attributes to the component ports in SCFToCalyx, and does not intrude into the Calyx library itself.
If there's interest, i can follow up with a commit which integrates this notion of external memory interfaces into the Calyx ComponentOp
1. add a verifier that these memory interfaces are fully, and correctly, specified and
2. add ODS getters for the …

[Calyx] Add attributes for external memory interfaces

---

lib/Dialect/FIRRTL/Import/FIRParserAsserts.cpp
test/Dialect/FIRRTL/SFCTests/complex-asserts.fir
test/Dialect/FIRRTL/SFCTests/complex-assumes.fir
test/Dialect/FIRRTL/parse-basic.fir

When parsing printf-encoded assertions, the condition of the surrounding `when` has to be inverted in order to go from the fail-when-true polarity of the printf to the fail-when-false polarity of the assert. Predicate modifiers (currently just `trueOrIsX`) are formulated with respect to the assertion predicate, i.e., on the fail-when-false polarity. So a `trueOrIsX` modifier is supposed to add an additional pass case to the assertion if the condition is `X`. The parser currently applies predicate modifiers on the fail-when-true polarity, which is wrong. Move the predicate inversion upwards so it occurs before modifiers are applied.
Fixes #2653.

[FIRParser] Flip assert predicate before applying modifiers

---

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
test/Dialect/FIRRTL/emit-metadata.mlir

When there are no memories, we are not emitting the metadata file
describing them.  This changes the firtool to always emit the metadata
when instructed, printing just an empty array `[]` when there are no
memories.

[FIRRTL][Metadata] Print empty seq_mems.json files

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

This commit handles the NonLocalAnnotations on Bundle fields during LowerTypes.
1. Update the NLA instance path to the new leaf symbol generated after Lowering
2. If multiple Bundle fields share the same NLA, then create new NLAs for each of the fields, and fixup the annotations.
3. Drop the Nonlocal DontTouch annotations, and delete the corresponding NLAs. 
When a Non-local annotation is attached to a bundle subfield, the NLA instance path contains a reference to the bundle symbol, for example, 
```mlir
firrtl.nla @nla [#hw.innerNameRef<@A::@test>, #hw.innerNameRef<@B::@test>, #hw.innerNameRef<@Z::@b>]
...
firrtl.module @Z() {
%bundle = firrtl.wire sym @b {
annotations = [#firrtl<"subAnno<fieldID = 2, {circt.nonlocal = @nla, class =\"test\" }>">]
}: !firrtl.bundle<valid: uint<1>, ready: …
```

[FIRRTL] Handle NonLocalAnnotations on Bundle fields during LowerTypes

---

include/circt/Dialect/SV/SVStatements.td
lib/Dialect/SV/SVOps.cpp

Thing is that:
note: `parser` and `printer` fields are deprecated and will be removed, please use the `hasCustomAssemblyFormat` field instead
def CaseZOp : SVOp<"casez", [SingleBlock, NoTerminator, NoRegionArguments,
------
Add CaseZOp::print, CaseZOp::parse function.

[NFC] Fix deprecated warnings after bump llvm

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/dedup.mlir

When deduplicating two modules, the names of fields in bundle types may
change, which means we have to go and fix partial connect operations to
make sure that the proper fields remain connected.  There was a spelling
mistake in this piece of code which caused the expander to think that
the LHS and RHS types of the partial connect were unchanged, and not fix
up the partial connect.  This would typically cause fields which used to
be connected to become unconnected.

[FIRRTL][Dedup] Fix partial connect expansion

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp

When two modules are deduped and they have the same port types, we do
not need to fixup any references to these modules.  This hoists an early
`continue` when the types are unchanged out of a nested for-loop, which
makes more sense and should be slightly more efficient.

[FIRRTL][Dedup] Move early break outside of for-loop [NFC]

---

frontends/PyCDE/setup.py

The replacement was not working as expected on Windows, leading to
CMake errors during configuration.

[PyCDE] Update setup.py Python3_EXECUTABLE path.

---

lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp
test/Dialect/FIRRTL/dedup.mlir

When creating an `inner_sym` for ops, Dedup was using the "name" attribute of
the op as a base.  For many ops, it is possible that the attribute is an empty
string, which should not be used to create a symbol.  This change makes Dedupe
use `inner_sym` as the symbol base when the name is empty.  This does not
change the behaviour for ports: they must have a non-empty name.

[FIRRTL][Dedup] Fix creation of symbols with empty name

---

include/circt/Dialect/FIRRTL/FIRRTLDialect.h
include/circt/Dialect/FIRRTL/FIRRTLDialect.td

FIRRTL heavily uses some attributes defined in the HW dialect, and it is
causing a crash when a pass creates these attributes without the dialect
being loaded first.

[FIRRTL] Add `HWDialect` to the `dependentDialects`

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/SFCTests/data-taps-nlas.fir
test/Dialect/FIRRTL/grand-central-taps.mlir

The Grand Central data/mem taps pass used guess which concrete instance of a wire or port a data/mem tap referred to, because the taps were local annotations (i.e., they did not mention a concrete instance that they applied to). Since we now *do* have support for non-local annotations, and passes like deduplication make ample use of them, the GCT pass should consider the additional path information provided by NLAs when generating the data tap wiring. This commit makes GCT leverage the path information in NLAs.
A concrete example would be a design with two instances:
```
module Top:
inst foo of Foo
inst bar of Foo
```
If the instance port `foo.a` is targeted as a reference data tap, the GCT pass would up until now consider `Top.foo.a` and `Top.bar.a` as possible paths to that port, …

[FIRRTL] Honor NLAs in GCT data tap paths

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

The `LowerToHW` conversion uses the `tryEliminatingConnectsToValue` function to try and eliminate unnecessary connects to a value and replace all value uses with the connected value instead. This is used to avoid unnecessary `*.output` temporary wires when generating the `hw.output` lowering. That function only considers `ConnectOp` though, and any `StrictConnectOp` are left untouched. This commit extends the elimination to also consider `StrictConnectOp`, such that the lowered HW design contains fewer temporary wires.

[FIRRTLToHW] Consider strictconnect for elimination

---

include/circt/Dialect/FIRRTL/FIRParser.h
lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir
test/Dialect/FIRRTL/SFCTests/data-taps-nlas.fir
test/Dialect/FIRRTL/SFCTests/signal-mappings.fir
test/Dialect/FIRRTL/SFCTests/width-spec-errors.fir
test/firtool/name-preservation.fir
tools/firtool/firtool.cpp

Change end-to-end FIRRTL compilation behavior to preserve all wires that
exist in CHIRRTL.  This is accomplished by creating a "shadow wire" that
is assigned the value of the actual wire and marked "don't touch".
This is done to enable better debug-ability of Chisel designs by, with a
future change to Chisel to convert any named Scala val to a wire,
enabling users to always have references to named things they define in
Chisel.
This has the effect of changing the compilation of the following:
```scala
circuit Foo:
module Foo:
output b: UInt<1>
wire x: UInt<1>
x <= a
b <= x
```
To produce:
```verilog
module Foo(	
input  a,
output b);
wire x;	
assign x = a;
assign b = a;
endmodule
```
With the change that @jackkoenig shows in [this Chisel …

[FIRRTL] Preserve All Wires

---

lib/Dialect/LLHD/IR/LLHDOps.cpp
test/Dialect/LLHD/Canonicalization/extract.mlir

When indexing a signal-array with SigArrayGetOp that was created by a shrOp, an assertion is thrown when the bitwidth of the shift amount type and the index type do not match. We can also allow this canonicalization when the bitwidths do not match.

[LLHD] Fix SigArrayGetOp canonicalization

---

test/Dialect/Handshake/errors.mlir

Bump LLVM.
Remove a now uneeded verification of a Handshake interface where a
confined value was being manually verified.  This is now handled
automatically by LLVM/MLIR so the test was removed (to avoid duplicating
testing of LLVM/MLIR infrastructure).

Bump LLVM, Remove Duplicate Handshake Verification

---

lib/Dialect/FIRRTL/Transforms/RemoveUnusedPorts.cpp
test/Dialect/FIRRTL/remove-unused-ports.mlir
test/firtool/firtool.fir

This commit handles strictconnect in RemoveUnusedPorts pass.
Normal connect ops are probably canonicalized into strict connects
at the time of RemoveUnusedPorts so it is necessary to handle 
strictconnects. 
This also adds an e2e test for RemoveUnusedPorts pass.

[FIRRTL][RemoveUnusedPorts] Support strictconnect

---

lib/Dialect/HW/HWTypes.cpp
test/Dialect/HW/parameters.mlir

#1928 related. Small change, but fairly impactful in allowing us to build generic hardware modules. Without this, `comb` and `seq` operations cannot accept `hw.int` types.
Verilog emission seems to work out-of-the box for both `comb` and `seq` operations.

[HW] Allow hw::IntType in hw::isHWIntegerType

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

Change FIRRTL to HW lowering behavior for subaccess (which is
represented as a multi-bit mux) to return the zeroth element on an
out-of-bounds read.  Previously, this would return an X (the Verilog
out-of-bounds read behavior).  This change is made to align CIRCT with
SFC behavior around out-of-bounds subaccess lowering.
This is done to fix situations like the following:
```scala
circuit Bar:
module Bar:
input index: UInt<4>
input vec: UInt<8>[10]
output out: UInt<8>
out <= vec[index]
```
Without this patch, CIRCT produced:
```verilog
module Bar(
input  [3:0] index,
input  [7:0] vec_0, vec_1, vec_2, vec_3, vec_4, vec_5, vec_6, vec_7, vec_8, vec_9,
output [7:0] out);
wire [9:0][7:0] _GEN = {{vec_9}, {vec_8}, {vec_7}, {vec_6}, …
```

[LowerToHW] Guard out-of-bounds multi-bit mux

---

tools/circt-reduce/Reduction.cpp

Extend `circt-reducer` with some additional mechanism to appropriately remove `firrtl.nla` ops when instances, modules, or ports are modified or removed. Currently this is very FIRRTL-specific, but I hope to make this more general-purpose in the future. With this fix the reducer becomes more useful on FIRRTL inputs that make heavy use of non-local annotations and non-local anchors, which is very likely if they use some form of deduplication or proper multiple instantiation.

[reduce] Make reducer NLA aware

---

lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp
test/Dialect/FIRRTL/annotations.fir

The annotation parser was mistakenly getting confused when a wire (or
instance) inside a module had the same name as the module itself, and
would create a reference to the module instead of an innerRef to the
wire.
This was not that it was mistakenly targeting the Module, but it
was a bug in the NLA creation logic that used `targetName == moduleName`
as a sentinal value to insert a module reference.  Instead we use
`targetName == ""` as a sentinal value.

[FIRTL][Annotations] Fix issue when module name matches inner name

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/parse-name-preservation.fir

This updates the FIRRTL parser to properly expand connects when an
aggregate contains an analog so that we emit an `attach` instead of a
`connect` for the analog element.  This issue happens only when the
`NamePreservation` flag is enabled.

[FIRRTL] Properly handle analog types w/ NamePreservation option

---

include/circt/Dialect/HW/HWOps.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/HW/HWOps.cpp
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp

Add a `flip(PortDirection)` function which reverses a port direction. Also turn `PortDirection` into an `enum class` to avoid polluting the HW namespace. Most uses of the enum already have a `PortDirection::` prefix, so the change is fairly minimal and just enforces and already established practice.

[HW] Add port dir flip function, make `PortDirection` an enum class; NFC

---

test/Dialect/FIRRTL/parse-name-preservation.fir

This adds some basic tests for NamePreservation.  This addresses some of
the post commit comments left in
https://github.com/llvm/circt/pull/2723.

[FIRRTL] Add more tests for NamePreservation

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

Change LowerToHW module extraction to not extract verification
blackboxes which are instantiated inside the test harness.
This also sneaks in some utilities for computing whether a module is in the DUT or the TestHarness and uses them to simplify existing logic.

[LowerToHW] Don't extract TestHarness verif bboxes

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp

The dedup pass uses the module's name to implement the MustDedup
functionality. Unfortunately, it was grabbing the module name right after
deleting the module.

[FIRRTL][Dedup] Get a module's name before deleting it

---

include/circt/Dialect/FIRRTL/FIRRTLOps.h
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp

`std::lower_bound` does not necessarily return `end()` when the searched for
element is not found: it can return an element `>` the searched for element.
For this reason it is necessary to check for equivalence after checking that an
element was found.
This was causing a crash in several SiFive cores although I have not been able
to reduce it to a simple test case yet.  The cause of the crash appears to be
that the `it->op` is an invalid op address. It is unclear to me how an invalid
op made it into the `opSymNames` list in the first place, but maybe someone
more familiar with the code can figure it out.

[FIRRTL][LowerTypes] Fix std::lower_bound usage

---

lib/Dialect/FIRRTL/Transforms/WireDFT.cpp

`signal` is a mutable reference to an element in a `DenseMap`.  This
function can cause the DenseMap to grow in size and invalidate the
reference. We solve this problem by copying the pointer value into a
local.

[FIRRTL][WireDFT] Fix invalidated reference from growing DenseMap

---

lib/Dialect/LLHD/Transforms/ProcessLoweringPass.cpp
test/Dialect/LLHD/Transforms/processLowering.mlir
test/Dialect/LLHD/Transforms/processLoweringErrors.mlir

Canonicalization merges similar basic blocks and selects differing values via block arguments. This also includes values of LLHD signal type. The block-argument-to-mux pass then transforms them to muxes that need to be considered in process lowering.

[LLHD] Process Lowering: support muxed signals

---

include/circt/Dialect/FIRRTL/FIRRTLOps.h
include/circt/Dialect/Handshake/Visitor.h
lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
test/Conversion/HandshakeToFIRRTL/test_signed_ops.mlir

This PR adds support for signed operations by casting unsigned operands to signed ones, if needed. 
Closes #2728 as it solves the issues of all the existing operations.  
Note: I decided to template the parameter that indicate signedness of certain operands as this is statically known for each call to the helper functions.

[HandshakeToFIRRTL]: Add support for signed ops

---

include/circt/Dialect/HW/HWOps.h
include/circt/Dialect/HW/HWStructure.td
lib/Dialect/HW/HWOps.cpp

Add the `modifyPorts` function to `HWModuleOp`, `HWModuleExternOp`, and `HWModuleGeneratedOp`, plus convenience wrappers `insertPorts` and `erasePorts`. This function performs insertion and removal of input and output ports in one go, and updates the type and name attributes accordingly. Very handy when a pass actually needs to modify the interface of a module. Block arguments are left untouched at the moment, as the expectation is that the user will have to do some special handling of those anyway while they are updating the module body. Maybe in the future these functions could support an opt-in "please take care of the block args for me" option.

[HW] Add port modification for module-like ops

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/firtool/firtool-errors.mlir
tools/firtool/firtool.cpp

This adds early returns with signalPassFailure when failure bubbles up
in the LowerToHW pass. In order to catch such failures and exit before
the ExportVerilog passes, the firtool pass manager is split into two
pipelines. The first pipeline handles the main lowering passes, and
only if those succeed, the second pipeline handles ExportVerilog.

[FIRRTL] Add signalPassFailure to LowerToHW and exit early.

---

lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
test/Dialect/FIRRTL/emit-omir.mlir

NLAs are used by EmitOMIR to print the instance path to memories and
modules. When an OMIR annotation does not have an NLA, a new absolute
NLA is created for it.  As a part of this, the pass assumes that NLAs
used by any OMIR node is rooted at the top module.  Dedup notably will
create NLAs for OMIR annotations which are not rooted at the root
module, and as a result the final OMIR JSON file will include only part
of the path to the memories or instances.
This changes the metadata emission to stop assuming that NLAs are rooted
at the top module, and instead use the existing NLA as a way to
disambiguate the path to the memory when creating a new absolute NLA.
The pass already will remove any "temporary" NLAs created for metadata
emission.

[FIRRTL][OMIR] Don't assume NLA's have an absolute path

---

include/circt/Dialect/FIRRTL/FIRRTLStatements.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
lib/Dialect/FIRRTL/Export/FIREmitter.cpp
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
lib/Dialect/FIRRTL/Transforms/LowerCHIRRTL.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/emit-basic.mlir
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/lower-chirrtl.mlir
test/Dialect/FIRRTL/lower-types.mlir
test/Dialect/FIRRTL/parse-basic.fir

Let the parser keep invalids of aggregate type.  Teach LowerTypes about StrictConnect and have it generate them when possible.

[FIRRTL]  Don't lower types for invalid durring parsing.

---

docs/FIRRTLAnnotations.md
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/SV/Transforms/HWExportModuleHierarchy.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Conversion/FIRRTLToHW/module-hierarchy-file.mlir
test/Dialect/SV/hw-export-module-hierarchy.mlir

From the FIRRTL flow we need to be able to specify multiple output files
for the module hierarchy.  To do this, this change switches the
`firrtl.moduleHierarchyFile` to have an array of files instead of a
single file.
The FIRRTL flow needs to be able to output a module hierarchy file for
the testharness (top level module) and the DUT module. When these two
modules are the same, we would end up only outputing a single hierarchy
file.  Unfortunately, the SiFive build system is really hard coded to
expect both files (for now) so we had to add the ability to generate the
same file twice.

[HW][ExportModuleHierarchy] Allow multiple output files per module

---

include/circt/Dialect/LLHD/IR/SignalOps.td
lib/Conversion/HWToLLHD/HWToLLHD.cpp
lib/Dialect/LLHD/IR/LLHDOps.cpp
test/Dialect/LLHD/IR/inst-errors.mlir
test/Dialect/LLHD/IR/signal-errors.mlir
test/Dialect/LLHD/IR/signal.mlir

The output operation allows a more SSA friendly way to create signals with a single driver. This is especially useful when converting between HW and LLHD as it simplifies canonicalization patterns and analyses.
See issue #1009
For example, in the already existing HW to LLHD pass and a LLHD to HW promotion pass I'm currently experimenting with it allows to bridge between the dialects by using this `llhd.output` for the HW -> LLHD direction and `llhd.prb` for the LLHD -> HW direction. After the conversion is complete they can be folded as such:
```mlir
%sig = llhd.output %arg0 after <0ns, 0d, 0e>
%0 = llhd.prb %sig  // can then be folded to %arg0
```
```mlir
%0 = llhd.prb %arg0
%sig = llhd.output %0 after <0ns, 0d, 0e>
```
In the second pattern,  `%sig` cannot be set equivalent to `%arg0` …

[LLHD] Add output operation

---

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
test/Dialect/FIRRTL/inliner.mlir

When inlining a module, we copy all the operations along with their
annotations into another module.  When the copied operations have
non-local annotations attached to them, it doesn't make sense to copy
the annotation when the NLA's namepath does not match match the current
module path, and the annotation could never be considered active.
In addition to the above, inlining can make a non-local annotation turn
in to a local annotation as it inlines modules.  This change fixes a bug
where we copy an annotation which should never be active according to
the instance path, and simulatiously change it to a local annotation,
causing the annotation to proliferate to all places the operation is
cloned.
To fix this, the change keeps a stack of the current instance path as it
recursively inlines …

[FIRRTL][Inliner] Filter non-local annos by the instance path

---

docs/RationaleHW.md
include/circt/Dialect/HW/HWAttributes.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/HW/HWAttributes.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Dialect/HW/parameters.mlir

This is a unary expression that calculates the ceiling of log base 2 of its
argument. Following the Verilog spec, clog2(0) is 0.
This is useful for calculating things such as the minimum bitwidth needed
to address a memory of a given size.

[HW] Add clog2 parameter expression

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-basic.fir

This is a small regression from dd873d9824f6. When an analog is inside a
bundle which is `is invalid`ated, we need to ensure that we don't
connect the analog value.

[FIRParser] Don't bulk connect bundles with analog in them

---

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
test/Conversion/SCFToCalyx/convert_memory.mlir

Fixes https://github.com/llvm/circt/issues/2660

[Calyx] SCFToCalyx generates zero-width memref address ports for memrefs with size 1 dims

---

lib/Dialect/FIRRTL/Transforms/InferReadWrite.cpp
test/Dialect/FIRRTL/inferRW.mlir

This commit fixes an issue with `InferReadWrite`, where it was not considering
`StrictConnectOp` along with `ConnectOp`.
After #2615, `ConnectOp` patterns were replaced with `StrictConnectOp`, and
the `InferReadWrite` pass was not identifying the mutually exclusive read
and write enables anymore.
Also generate `StrictConnectOp` instead of the `ConnectOp` and fix the lit tests.

[InferReadWrite] Identify StrictConnectOp patterns along with ConnectOp

---

include/circt/Support/LLVM.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

There is an issue during module processing where we needed to know if
the module was instantiated underneath the DUT, and the answer to this
question depended on if we found the DUT module yet.
The typical way we have been handling this is to move this logic into a
post-pass, after we have found the DUT.  I don't think that this is the
first time this has burned us, so to make it safe we would need to
remove the DUT from the CircuitLoweringState to make sure no one used it
before it was populated.
Instead, this change finds the DUT in a pre-pass, so it is available
while processing each module.   We were already doing a pre-pass of the
circuit to look for NLAs, so I just stuck it in there. This let me
remove a post-pass to set the testbench directory.
This also changes the DUT to be a …

[FIRRTL][LowerToHW] Find the DUT in a prepass

---

include/circt/Dialect/FIRRTL/InstanceGraph.h
lib/Dialect/FIRRTL/InstanceGraph.cpp

This adds a missing implementation of `addModule()` to the
InstanceGraph.  This is useful for users who want to keep the graph up
to date.  The signature has been changed to take a `FModuleLike` instead
of a `Operation *`.  This code is not tested by this commit.

[FIRRTL][InstanceGraph] Add missing implementation of `addModule()`

---

lib/Dialect/LLHD/Simulator/Engine.cpp
lib/Dialect/LLHD/Simulator/State.cpp
lib/Dialect/LLHD/Simulator/State.h
lib/Dialect/LLHD/Simulator/Trace.cpp

Change the dump method in struct Time, Signal to
toString, toHexString method.
follow the refactor link in [2673](https://github.com/llvm/circt/pull/2673)
will split into several patches.  
Since the dump() function in LLVM/MLIR will get an ostream output
and `void dump()` with return type `void` .

[NFC] Rename dump method with toString method

---

include/circt/Dialect/HW/HWStructure.td
lib/Dialect/HW/HWOps.cpp

Instead of building a `SymbolTable` for each verify call, use
`SymbolUserOpInterface` to be fed the symbol table. Fixes #2794.

[HW] GlobalRefOp performance enhancement

---

lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/CMakeLists.txt
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.anno.json
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir
test/Dialect/FIRRTL/blackbox-reader.mlir
test/Dialect/FIRRTL/grand-central.mlir
tools/firtool/firtool.cpp

Change Grand Central Views to modify existing black boxes which are
instantiated in a companion so that they will be written to the Grand
Central extraction directory.  This is done to match SFC behavior around
where black boxes are written.
To implement this, I added the following functionality:
Add functionality to BlackBoxReader such that it will use the
"output_file" information on an external module when determining where
to put the black box.  The policy is as follows:
1. If the output file is a file (NOT a directory), then this file is
where the black will written.
2. If the output file is a directory, then this becomes a lowest
priority fallback for setting the directory.
This policy may require tweaking, but it gets CIRCT to match the Scala
FIRRTL Compiler (SFC) in tests and …

[FIRRTL] Put Grand Central Black Boxes in Correct Directories

---

include/circt/Dialect/FIRRTL/FIRRTLUtils.h
lib/Dialect/FIRRTL/CMakeLists.txt
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/parse-locations.fir
test/firtool/connect.fir
test/firtool/firtool.fir

(This probably needs to be aligned with some other PRs currently opened, and hasn't really been tested fully)
This change starts resolving partial connects at firrtl parse time to
remove them from the IR, with the eventual goal of removing partial
connects entirely.
There are places in the code where partial connects were used to as a
way to truncate sources in a connect.  A helper was added to
automatically insert pads or truncates where needed so that the sizes of
operands match for connect ops.  Most of these places could generate a
strict connect instead of a regular connect, but I decided to save the
test churn for a follow up commit.
The way this code is written has an eye towards eventually making strict
connect ops the *only* connect operations in the IR.  When potentially …

[FIRParser] Expand and remove partial connects at parse time

---

include/circt/Support/LoweringOptions.h
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
lib/Support/LoweringOptions.cpp
test/Conversion/ExportVerilog/max-terms.mlir

If an expression has more than the maximum number of terms, and we are
able to drop a wire or hoist it and drop a wire, we do so. The intent
is to remove the burden of spilling expressions larger than the
maximum token limit of some simulators by guessing what's "too large"
and doing it before ExportVerilog. Better algorithms and heuristics
for deciding to drop a wire can be added to shouldSpillWire.
The current implementation of prepareHWModule makes the phase ordering
of this a little interesting: we need to know it is "too large" before
we break the expression up into a binary tree. We also need to move
this addition, the splitting, and other canonicalizations to later in
prepareHWModule. If the spill happens while we are working on a
non-procedural region, we we can just proceed to …

[PrepareForEmission] Add max expression size before creating a wire.

---

include/circt/Support/LoweringOptions.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Support/LoweringOptions.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

The `Comb` dialect arithmetic op result has the same bit-width as the input operands.
Some lint tools can complain that the assignment results in loss in bits.
This commit has a lowering option to add an explicit cast, to avoid such lint errors.
For example, the following code snippet can generate an error, 
` width 18 is less than RHS: '(_GEN_7 * _GEN_8)' width 36 in assignment` 
```
wire [17:0] _GEN_7 = ...
wire [17:0] _GEN_8 =  ...
wire [17:0] reg_out = _GEN_7 * _GEN_8 ;
```
The `lowering-option=explicitBitcastAddMul` makes the cast explicit.
```
wire [17:0] _GEN_7 = ...
wire [17:0] _GEN_8 =  ...
wire [17:0] reg_out = 18'(_GEN_7 * _GEN_8 );
```

[ExportVerilog] Add explicit bitcast for width mismatch LINT errors

---

CMakeLists.txt
integration_test/Dialect/Handshake/dot.mlir
integration_test/Dialect/Handshake/matmul.mlir
integration_test/ESI/primitives/primitive_tb.sv
integration_test/circt-rtl-sim/circt-rtl-sim-iverilog.sv
integration_test/lit.cfg.py
integration_test/lit.site.cfg.py.in
tools/circt-rtl-sim/circt-rtl-sim.py.in

If questa or vivado are not found, `iverilog` is used to run
supported tests. Tests which cannot be executed using this simulator
can be disabled by adding `// DISABLED: iverilog`.
Icarus verilog tests can be disabled altogether by passing
`-DIVERILOG_DISABLE=ON` to cmake, similarly to other simulators.
resolves llvm/circt#879

[Tests] Added Icarus Verilog test harness

---

.github/workflows/trackLLVMChanges.yml
README.md

This PR adds a workflow which runs around 3AM Pacific Time and bisects the LLVM repo, starting at the current commit in the CIRCT submodule through the most recent commit on `main`. The workflow fails if _any_ MLIR commits break CIRCT. The workflow has a step that clearly displays [the error encountered](https://github.com/llvm/circt/runs/5699113248?check_suite_focus=true#step:7:263) and [the first breaking commit](https://github.com/llvm/circt/runs/5699113248?check_suite_focus=true#step:7:13). Note, this means that having the workflow "fail" on this PR is **correct** (it will only run on PRs which change this workflow). Hopefully this will make it easier to stay on top of updating LLVM.
Currently, I just provide a badge in the Readme but we can incrementally improve this by adding better …

Track LLVM commits

---

include/circt/Dialect/Moore/MIRExpressions.td
include/circt/Dialect/Moore/MIROps.h
include/circt/Dialect/Moore/MooreTypes.td
include/circt/Dialect/Moore/MooreTypesImpl.td
lib/Conversion/MooreToCore/MooreToCore.cpp
lib/Dialect/Moore/CMakeLists.txt
lib/Dialect/Moore/MIROps.cpp
test/Conversion/MooreToCore/basic.mlir
test/Dialect/Moore/basic.mlir

As a first step towards bringing the Moore IRs into the CIRCT project, add a `ConcatOp` to the Moore dialect which represents a concatenation expression. The intention is to make this MLIR op precisely capture the semantics specified in the SystemVerilog standard. The documentation for the op points at the relevant pieces of the standard.
This op will allow Moore to start emitting `moore.mir.concat` instead of directly doing the lowering to LLHD/Comb, which is a great starting point to move the code generation logic from the Rust code into CIRCT.

[Moore] Add concat expression

---

lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
test/Dialect/FIRRTL/emit-omir.mlir

This previously just used the name of the circuit op, but this is not
always the desired root. When a DUT is marked, this should be pointing
to the DUT directly. Fortunately, we have a new attribute that tracks
the DUT module name we can just use.

[FIRRTL] Use the new dutModuleName attribute for root of port target.

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

It was previously possible for LowerTypes to generate duplicate
symbols for different ports inside addArg. The logic that decides to
create the 'newSym' attribute previously checked whether the old
symbol was null, and if not, if it was empty. But the logic for
setting the 'sym' string in the first place was missing the empty
check. Because we create empty symbols by default in some cases, this
was leading to incorrect behavior, where the suffix was concatenated
to an empty string. If multiple lowered bundle types had the same
suffix, this could create duplicates.
Fortunately the solution is simple, we just need to include the empty
check in both places. To make this more clear, the logic is pulled out
into a shared variable that can be checked in both places.

[FIRRTL] Fix port symbol creation logic edge case in LowerTypes.

---

include/circt/Support/ValueMapper.h
lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
lib/Support/CMakeLists.txt
lib/Support/ValueMapper.cpp

This commit extracts the ValueMapper class from HandshakeToHW to a separate support file.
The ValueMapper facilitates the definition and connection of SSA def-use chains between two location - a 'from' location (defining use-def chains) and a 'to' location (where new operations are created based on the 'from' location). An optional type transformation function may be provided to transform output types.
The mapper works for both SSACFG and GraphRegions, with the latter implemented through leveraging a BackedgeBuilder.

[Support] Extract ValueMapper to separate support file

---

include/circt/Dialect/Moore/MIRExpressions.td
lib/Conversion/MooreToCore/MooreToCore.cpp
test/Conversion/MooreToCore/basic.mlir
test/Dialect/Moore/basic.mlir

Add the logical and arithmetic left/right shift operations. `comb.shl` and the right-shift variants only support amount values with the same type as the value to be shifted. I'm not sure why this restriction was put in place and whether it could be lifted to reduce the number of operations we have to emit to adjust the integer bitwidth (also why isn't it the log2?).

[Moore] Add shift expressions

---

lib/Dialect/SV/Transforms/PrettifyVerilog.cpp
test/Dialect/FIRRTL/SFCTests/invalid-interpretations.fir
test/Dialect/SV/prettify-verilog.mlir

Change PrettifyVerilog to choose wires with good names over SSA values
without names or with less good names.  This is done specifically to
cause Verilog emitted to use Chisel "val names" (which are represented
as dead wires at this point in the compiler) instead of their
underscore-named counterparts.
Fixes #2808.
FYI: @jackkoenig
Consider the following circuit where `node x` was a `val x = a | b` in Chisel:
```scala
circuit Foo:
module Foo:
input b: UInt<1>
output out: UInt<1>
node x = or(a, b)
out <= x
```
Without this PR, CIRCT produces:
```verilog
module Foo(
input  a, b,
output out);
wire x;
wire _x = a | b;
assign x = _x;
assign out = _x;
endmodule
```
With this PR:
```verilog
module Foo(
input  a, b, …
```

[SV] Use Better Named Wires When Possible

---

include/circt/Dialect/HW/HWAttributes.h
lib/Dialect/HW/HWAttributes.cpp
lib/Dialect/HW/HWOps.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Dialect/HW/errors.mlir
test/Dialect/HW/parameters.mlir

To extend the capabilities of parametric modules, this commit introduces support for `hw.instance`'iating `hw.module`s with parametric input/output types. Upon instantiation (and `hw.instance` verification), module types are resolved based on the set of provided parameters to the `hw.instance` op.
The brunt of the work for supporting this is added through two new functions:
- resolveParametricType: Based on a set of parameters, a parametric type is resolved to its actual type. For now, only parametric `!hw.int` types are supported, but #2703 will add support for parametric array types.
- evaluateParamAttr: Based on a set of parameters, a parametric expression is evaluated through use of the existing ParamExprAttr canonicalizers.

[HW] Support hw.instance of modules with parametric in/out types

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

If the else block of an `IfOp` consists of a single `IfOp` and
possibly multiple expressions, the block is printed as an
`else if` and the intermediate wires are hoisted to the scope
of the parent `if` block.

[ExportVerilog] Printed nested `else`-`if` ops as `else if`

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
include/circt/Dialect/FIRRTL/FIRRTLStructure.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
lib/Dialect/FIRRTL/Transforms/RemoveUnusedPorts.cpp
lib/Dialect/HW/HWOps.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Conversion/FIRRTLToHW/module-hierarchy-file.mlir
test/Conversion/FIRRTLToHW/zero-width.mlir
test/Dialect/FIRRTL/SFCTests/constantProp.mlir
test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/annotations.fir
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/imconstprop.mlir
test/Dialect/FIRRTL/inliner.mlir
test/Dialect/FIRRTL/lower-types.mlir
test/Dialect/FIRRTL/omir.fir
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/parse-locations.fir
test/Dialect/FIRRTL/remove-unused-ports.mlir
test/circt-reduce/port-pruner.mlir
test/firtool/firtool.fir

`firrtl` and `hw` modules can now be annotated with MLIR visibility attributes.
The FIR parser sets the visibility of all non-main modules to private if the
main module is defined, otherwise all modules remain public.
Transformations were altered to inspect the visibility attribute instead of
checking whether a module matches the main of a circuit.

[FIRRTL][HW] Added module visibility attributes

---

include/circt-c/Dialect/Moore.h
lib/CAPI/Dialect/Moore.cpp

A first step to have proper support of the Moore types in the C API. This focusses on the functions to create types and some SBV type functions needed to support the already existing moore operations in the external moore frontend compiler.

[Moore] Add types to C API

---

frontends/PyCDE/src/CMakeLists.txt
frontends/PyCDE/src/pycde/constructs.py
frontends/PyCDE/src/pycde/system.py
frontends/PyCDE/test/systolic_array.py

Plumbs through the new `msft.systolic.array` to PyCDE. Specifying the PE result type could be inferred, but I think that would require upstream MLIR Python bindings modifications.

[PyCDE] Add SystolicArray construct

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

Change the --lowering-options=explicitBitcastAddMul option to not be
gated on a subexpression being in an assign.  This is needed (according
to Spyglass...) anytime an addition or multiplication shows up.
This is a less clever approach than https://github.com/llvm/circt/pull/2825.  This simply extends @prithayan's work in https://github.com/llvm/circt/pull/2756, but uses this _anytime an addition or multiplication shows up_.  Spyglass is overzealous and seems to think that `(4-bit * 4-bit)` is 8-bit even though the Verilog spec seems to indicate that the the use of parentheses makes this self-determined and the width is the max of the two operands.
This is a janky circumvention of all this by always using explicit width …

[ExportVerilog] explicitBitcastAddMul all add/mul

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp

The "MustDedup" annotation causes some user-directed error checking, and
I decided to use the circuit op for the error messages.  I think that
this was a mistake; this causes the entire circuit operation to be
dumped.  This change it to print the error message using the circuit's
location without emitting the op.

[FIRRTL][Dedup] Don't dump the circuit on errors

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/dedup.mlir

When deduping modules, dedup ignores the names of fields in bundles.
After deduping two modules, the result type of an InstanceOp can change
when the field names of the bundle change. The connect op verifier
insists that the names of two connect bundles match, so we have to
"legalize connects" by walking instance results and potentially
decomposing a bulk connect to multiple connects.
There was a problem in dedup where it would "legalize connects"
immediately after deduping two modules. This would cause the body of the
parent module of the deduped module to change, which could block the
deduplication of the parent module.
This problem could be solved by a couple different options, such as
expanding connects in the parser or trying to make dedup smart enough to
see through these structural …

[FIRRTL][Dedup] Delay fixup of connects

---

frontends/PyCDE/src/pycde/constructs.py
frontends/PyCDE/test/systolic_array.py
include/circt-c/Dialect/MSFT.h
lib/Bindings/Python/MSFTModule.cpp
lib/CAPI/Dialect/MSFT.cpp

To simplify the ownership model, MLIR core python bindings don't support
building a block before the operation. So we build a dummy operation
first, build the block, construct the array, move the block, then delete
the dummy op. The core MLIR C API doesn't have a region editing API, so
we need to add a specialized one in the MSFT C API.

[PyCDE] Infer the result type of a SystolicArray PE

---

.github/workflows/nightlyIntegrationTests.yml

Fixes https://github.com/llvm/circt/issues/2843
CI: https://github.com/llvm/circt/actions/runs/2092757865

[CI] Only build host backend in integration test

---

tools/firtool/firtool.cpp

In a recent refactoring, firtool was split into two pass managers, so
we could stop before the "export" passes if any of the "lower" passes
failed. However, this neglected to include adding the
FirtoolPassInstrumentation to the "export" pass manager. This closes
https://github.com/llvm/circt/issues/2854.

[firtool] verbose-pass-execution should print the final passes.

---

lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/test.mlir

The FIRRTL spec specifies that reset value of a register must be the
same width or smaller than the register.  We recently increased the
strictness of this check in https://github.com/llvm/circt/pull/2741.  It turns out that SFC does not implement
this kind of error checking, and by not allowing implicit truncation we
are failing to build some cores which build fine on SFC.  This reverts
the strict width checking.

[FIRRTL] Relax reg reset width checking

---

lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
test/Dialect/SV/hw-memsim.mlir

The `HWMemSimImpl` pass currently generates SystemVerilog that some tools cannot parse properly in cases where the memory data width is not a multiple of the random value bit width (32). In those cases the randomization produces:
reg [33:0] _RANDOM;
_RANDOM = {{`RANDOM}[1:0], {`RANDOM}};
Some tools do not recognize ``` {`RANDOM}[1:0] ``` as a primary expression and mistake it for being part of the concatenation, only to then complain that this isn't proper concatenation syntax.
This commit changes the randomization code to put the part-select after the overall concatenation, in the hope that most tools will have an easier time identifying `{...}[1:0]` as a primary expression if it appears as the right-hand side of an assignment. This now produces:
reg [33:0] _RANDOM;
_RANDOM = {{`RANDOM}, …

[HWMemSimImpl] Fix randomization of wide memories

---

lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
test/Dialect/SV/hw-memsim.mlir
test/firtool/memory.fir

Instead of assembling a randomized word value in a separate variable and then storing that to every memory location, this commit extends `HWMemSimImpl` to generate new random values on-the-fly for every memory location as it iterates over them. As a result the initialization code becomes shorter and the memory is fully randomized.
This is a follow-up to #2859.

[HWMemSimImpl] Randomize each memory word separately

---

lib/Dialect/FIRRTL/Transforms/InferResets.cpp
test/Dialect/FIRRTL/infer-resets-errors.mlir
test/Dialect/FIRRTL/infer-resets.mlir

When tracing resets through the design, the `InferResets` pass always uses the ID of the first vector element if it encounters a vector type. This is done to ensure that connections to an element of a vector affects the type inference of all the other elements too, since the pass can only pick a single reset type for the entire vector instead of individual types for each vector element.
This is problematic since it assumes that all vectors have at least one element, which may not be the case in practice. If such a vector is encountered, the field IDs get out of sync in weird ways if the vector is embedded in a bundle: when the bundle is asked to resolve a field ID to one of its fields, it treats the zero-length vector as actually having zero elements, such that forcibly asking for the …

[InferResets] Fix inference for zero-length vectors

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

Removed the `IfOp` inversion with empty then blocks in `EmitVerilog` since the canonicalizer performs the transformation already.

[ExportVerilog] Removed redundant sv::IfOp inversion

---

include/circt/Dialect/HW/HWTypes.h
include/circt/Dialect/HW/HWTypesImpl.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/HW/HWAttributes.cpp
lib/Dialect/HW/HWTypes.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Dialect/HW/errors.mlir
test/Dialect/HW/parameters.mlir

This commit adds support for having parametric hw.array types. This is allowed for both the dimension as well as the inner type.
One small thing; i found it necessary to remove the "multidimensional array error message" (i.e. `hw.array<1x2xi3>`) due to difficulties with writing a parser for an n-ary, 'x' delimited list which also supports attributes as dimensions.
Since we nevertheless do not support multidimensional arrays in sv emission, i opted for a simpler parser that assumes a single dimension, an 'x', and a single inner type.

[HW] Support parametric `hw.array`s

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/HW/hw-ranges.mlir

In an or expression, the canonicalizer now identifies operands
which constrain a value 'x' to specific numeric intervals:
- x < n
- n < x < m
- x == n
Overlapping intervals are collapsed and the number of tests
is lowered whenever possible. Most importantly, the following
patterns are now simplified:
- or(x == 0, x == 1, x == n) -> or(x < n + 1)
- or(x == n, x == n + 1, ..., x = m) -> or(and(n - 1 < x, x < m))

[HW] Canonicalized integer interval tests

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/Comb/canonicalization.mlir

If there were multiple extracts for a value, each one would be visited at least once, durring which it would scan all the others.

[NFC] Change Canonicalization pattern to avoid exponential behavior

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
include/circt/Dialect/FIRRTL/FIRRTLStatements.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp
lib/Dialect/FIRRTL/Transforms/InferReadWrite.cpp
lib/Dialect/FIRRTL/Transforms/RemoveResets.cpp
lib/Dialect/FIRRTL/Transforms/RemoveUnusedPorts.cpp

This PR introduces `FConnectLike` interface to wrap ConnectOp and StrictConnectOp.
`FConnectLike` interface provides `src` and `dest` methods. This will reduce code duplication related to StrictConnectOp.

[FIRRTL][NFC] Introduce FConnectLike interface  

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/HW/hw-ranges.mlir

This commit fixes a bug of the canonicalizer when
the interval is the same as the integer domain.
Fox example, let `a` be an i2 integer, then we can
canonicalize in the following way:
```
(a==0) or (a==1) or (a==2) or (a==3) ==> true
```

[Comb] Fix an edge case of the interval canonicalizer

---

lib/Dialect/FIRRTL/Import/FIRParserAsserts.cpp
test/Dialect/FIRRTL/parse-basic.fir

In SFC, these `chisel3_builtin` asserts default to the `ifElseFatal`
format.  We previously thought that we could emit these in a simpler
format, but it is missing the wrapper which checks `ASSERT_VERBOSE_CONDITION`.
This macro is used to prevent assertions from triggering when the test
bench is reseting.  Without guarding the assertion on this value, we are
getting some spurious failures when the first reset has run.

[FIRParser] Default chisel3 asserts to `ifElseFatal`

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

This is cherry-picked from https://github.com/llvm/circt/pull/2611
This commit allows struct_extract ops to be inlined even when they have multiple uses. It will make the output more readable.
For the following IR:
```mlir
hw.module @Foo(%a: !hw.struct<v: i1>) -> (b: i1, c: i1) {
%0 = hw.struct_extract %a["v"] : !hw.struct<v: i1>
hw.output %0, %0 : i1, i1
}
```
Before:
```verilog
wire _GEN = a.v;      // bar.fir:7:12
assign b = _GEN;      // bar.fir:2:10
assign c = _GEN;      // bar.fir:2:10
```
After:
```verilog
assign b = a.v;       // bar.fir:2:10, :7:12
assign c = a.v;       // bar.fir:2:10, :7:12
```

[ExportVerilog] Inline StructExtract

---

include/circt/Support/LoweringOptions.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Support/LoweringOptions.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Conversion/ExportVerilog/line-length.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir

This is somewhat involved, and complicates ExportVerilog
significantly. Since we have developed a solution to handle this
problem in #2795, we can remove this code, and address this scenario
in PrepareForEmission.
It is also important to remove this code because it has bugs. I
believe they could have been resolved with #2773, but ultimately it is
better to do this in PrepareForEmission.
If the new logic doesn't cause a spill when the old logic would have,
the worst case is the expression remains inline. This might cause
Verilator to complain. But the previous logic could potentially drop
wires in illegal places, and it is best to remove that.

[ExportVerilog] Remove max token limit and spilling in ExportVerilog.

---

lib/Dialect/FIRRTL/Transforms/RemoveInvalid.cpp
test/Dialect/FIRRTL/SFCTests/invalid-interpretations.fir
test/firtool/firtool.fir

This changes the `RemoveResets` pass to be called `RemoveInvalid`.  It then extends this pass to, after invalid reset initializers are converted to reset-less registers, re-walks each module to convert invalids to constant zero ops.  (Invalid bundles are ignored.)  This is done to incorrectly spotty application of the "invalid is zero" interpretation that was applied during canonicalization.
This is done for SFC-exactness, e.g., to fix #2782.

[FIRRTL] s/RemoveResets/RemoveInvalid/ and Make All Invalids Zero

---

lib/Analysis/TestPasses.cpp
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/LLHD/IR/LLHDOps.cpp
lib/Scheduling/TestPasses.cpp
test/Dialect/LLHD/Canonicalization/probeCSE.mlir

This isn't a full bump, since there are a lot of other large changes in LLVM. I bumped the submodule pointer to the commit just before https://github.com/llvm/llvm-project/commit/36d3efea15e6202edd64b05de38d8379e2baddb2, which removes a couple includes from `mlir/Pass/Pass.h` and consequently causes hundreds of compiler errors in circt due to missing names.
This PR contains fixes for several other issues that came up with the bump; please see my individual commits for the explanations and pointers to related commits in upstream llvm.
However, I am still hitting one more test failure that I'm not sure how to resolve. One of the LLHD tests, [probeCSE.mlir](https://github.com/llvm/circt/blob/cb5d02799c94d27f106df3447a3ba65c89407071/test/Dialect/LLHD/Canonicalization/probeCSE.mlir), is …

Update LLVM to 3d4ca8a8c

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp

This should actually fix the Windows build error, unlike https://github.com/llvm/circt/pull/2894.
In a recent commit, 654d5e96c84c80274f04ddd1a5984adc547b5cec, that
bumped the LLVM submodule, LLVM changed the SHA256 hasher to return
std::array<uint8_t, 32> instead of StringRefs. This causes MSVC to
report an error when compiling the printHash() debugging function, where
we now have an invalid reinterpret_cast.
This commit fixes the issue by performing the correct type conversions
from std::array to ArrayRef, which is now done without an explicit cast.
I manually ran a Windows build at https://github.com/llvm/circt/runs/6018882415?check_suite_focus=true, and it passed.

[FIRRTL][Dedup] Fix incorrect string cast in printHash().

---

lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp
test/Dialect/FIRRTL/check-comb-cycles.mlir

This is a follow-up of c4917d7, which replaces ConnectOp with FConnectLike with CheckCombCycles.

[FIRRTL][CheckCombCycles] Use FConnectLike

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/FIRRTL/FIRRTLOps.h
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/InferReadWrite.cpp
lib/Dialect/FIRRTL/Transforms/LowerCHIRRTL.cpp
lib/Dialect/FIRRTL/Transforms/PrefixModules.cpp
test/firtool/prefixMemory.fir

Add a `prefix` attribute to memory, to prevent memories with different prefix from getting deduped.
The `PrefixModules` pass can prefix the name for a `MemOp`. This prefix should not be ignored
when memories with same properties are deduped in `LowerToHW`.
This commit adds the `prefix` attribute to the `FirMemory`, such that it should also be considered
when merging all the memories.
In the absence of the prefix attribute it is ignored.
We can consider to make the attribute as a dedup domain id, instead of a prefix string.

[FIRRTL] Donot dedup memories with unique Prefix

---

.github/workflows/nightlyIntegrationTests.yml

If some configurations fail, we still want to test the others.

[CI] Update nightly workflow to not fail fast.

---

test/firtool/memory.fir
tools/firtool/firtool.cpp

Added a separate flag to dump the IR with `sv` ops, replacing `--ir-hw`.
From this point onwards, `--ir-hw` will dump IR in HW form, while `--ir-sv`
will include constructs (such as registers) expanded into SytemVerilog form.

[firtool] Add --ir-sv flag

---

include/circt/Conversion/ExportVerilog.h
include/circt/Conversion/Passes.h
include/circt/Dialect/Handshake/CMakeLists.txt
include/circt/Dialect/Handshake/HandshakeOps.h
include/circt/Dialect/Handshake/HandshakeOps.td
include/circt/Dialect/SV/CMakeLists.txt
include/circt/Dialect/SV/SVOps.h
include/circt/Dialect/SV/SVTypeDecl.td
include/circt/Transforms/Passes.h
include/circt/Transforms/Passes.td
integration_test/EmitVerilog/sv-interfaces.mlir
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/PassDetail.h
lib/Dialect/Handshake/CMakeLists.txt
lib/Dialect/Handshake/HandshakeDialect.cpp
lib/Dialect/Handshake/HandshakeOps.cpp
lib/Dialect/Handshake/Transforms/Analysis.cpp
lib/Dialect/SV/SVDialect.cpp
lib/Dialect/SV/SVOps.cpp
lib/Transforms/PassDetail.h
test/Conversion/ExportVerilog/name-legalize.mlir
test/Conversion/ExportVerilog/sv-interfaces.mlir
test/Dialect/ESI/connectivity.mlir
test/Dialect/ESI/errors.mlir
test/Dialect/ESI/lowering.mlir
test/Dialect/ESI/wrapif-lowering.mlir
test/Dialect/FIRRTL/errors.mlir
test/Dialect/Handshake/errors.mlir
test/Dialect/SV/interfaces.mlir

This fixes the remaining issues with the LLVM bump and gets us to the latest version of LLVM (as of a few hours ago). First of all, huge amount of thanks to @youngar, who helped me work through a lot of the changes here.
The first change is not too major and involved adding in some `#include`s, since https://github.com/llvm/llvm-project/commit/36d3efea15e6202edd64b05de38d8379e2baddb2 removed them from `mlir/Pass/Pass.h`.
The second change is a lot more substantial, and it affects the **SV** dialect's `ModportDirectionAttr` and the **Handshake** dialect's `BufferTypeEnum`. This includes changes to the assembly format parsers and printers such that you must not put quotes around `input`, `output`, or `inout` in `sv.interface.modport` ops.
```mlir
sv.interface @myinterface { …
```

Update LLVM to 1aa4f0bb

---

lib/Dialect/FIRRTL/Transforms/InferReadWrite.cpp
test/Dialect/FIRRTL/inferRW.mlir

Set the GroupID for MemOp from InferReadWrite pass.
It was not being set properly after 3c6d90d1e6003914485211d527253ef7770df372

[FIRRTL] Set the GroupID at InferReadWrite pass.

---

lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
test/Dialect/SV/hw-memsim.mlir
test/firtool/memory.fir

Fix a bug in the verbatim Verilog created by HWMemSimImpl for
randomizing memories.  This previously relied on an invalid Verilog
construct (bit select out of a concatenation).  This is changed to be
legal by using a temporary register.
E.g., memory randomization now looks like:
```verilog
`ifndef SYNTHESIS
`ifdef RANDOMIZE_MEM_INIT
reg [63:0] _RANDOM_MEM;
integer initvar;
`endif
`ifdef RANDOMIZE_REG_INIT
reg [31:0] _RANDOM;
`endif
initial begin
`INIT_RANDOM_PROLOG_
`ifdef RANDOMIZE_MEM_INIT
for (initvar = 0; initvar < 16; initvar = initvar + 1) begin
_RANDOM_MEM = {{`RANDOM}, {`RANDOM}};
Memory[initvar] = _RANDOM_MEM[32:0];
end
`endif
`ifdef RANDOMIZE_REG_INIT
_RANDOM = {`RANDOM};
_GEN = _RANDOM[0];
_GEN_0 = _RANDOM[4:1]; …
```

[SV] Fix HWMemSimImpl Bad Randomization Verilog

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/dedup-errors.mlir

A user can add an annotation "MustDedup" which lists modules which they expect to dedup, and emits an error message when that fails.  The error message produced by a dedup failure doesn't give any hint as to why deduplication failed.  This can be very annoying to debug, and usually involves `diff`ing the FIRRTL IR modules.
This change adds a diagnostic comparison of two modules, looking for the first difference between them which would have blocked deduplication.  This comparison ignores differences in port names and bundle element names the same way that the structural hasher does.

[FIRRTL][Dedup] enhance error messages for dedup failures

---

lib/Dialect/FIRRTL/Transforms/RemoveUnusedPorts.cpp
test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/remove-unused-ports.mlir
test/firtool/firtool.fir

Extend FIRRTL's RemoveUnusedPorts pass to also remove ports when a port
is never used by any instantiation.  While seemingly uncommon, this can
happen frequently for certain Chisel utility modules which have
auxiliary ports which are very rarely used, e.g., for Queues or
Arbiters.
Fixes #2850.
This fixes up around 1k lint warnings stemming from fields which are not used in Chisel utility modules, specifically with Chisel's Queue "count" field.

[FIRRTL] Remove Unused Instance Ports

---

tools/firtool/firtool.cpp

This commit adds CSE after hw canonicalization to clean up values
created by canonicalization. Even though it will increase complie time slightly, 
I believe it is very beneficial to run CSE again in terms of verilog qualify. 
I have seen 20% simulation speed up for large designs. 
This also closes https://github.com/llvm/circt/issues/2449

[firtool] Rerun CSE after canonicalization in HW/SV pipeline

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-basic.fir

When the LHS and RHS of a partial connect were the same types, we would
emit a regular connect, but we forgot to check if there were any
analog types inside the bundle. When this is the case, we have to recurse
on the bundle elements and attach the analog fields together.

[FIRParser] Fix partial connect expansion with analog in bundles

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/grand-central-taps.mlir

Fix a bug in the GrandCentralTaps pass where data or mem taps that had
no ports would result in external module instantiations in the final
design that had no corresponding implementation.  Change the
GrandCentralTaps pass to delete these modules and their instantiations.
This can arise more frequently due to a recent change to the Grand
Central Chisel API where zero-width taps are now allowed in the API,
generate a tap module, but generate no actual taps.
An alternative implementation would be to generate empty modules which
are cleaned up later.  This seemed wasteful.

[FIRRTL] Delete GCT taps that have no ports

---

include/circt/Dialect/SV/SVStatements.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/SV/SVOps.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

This is a follow-up to https://github.com/llvm/circt/pull/2913 to implement custom parser for case op. Also DefaultValuedAttr is used instead of OptionalValuedAttr.

[SV] Add custom parser for case op for validation qualifier

---

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
test/Dialect/FIRRTL/inliner.mlir

A memory operation has a name attribute which is used for both the name
of the generated module and all instances of that module.  The
ModuleInliner pass is supposed to prefix the name of instance but not
the name of the module.  This change stops prefixing the memory, which
corrects the name of the module, but gives the incorrect instance name.
The assumption here is that its more important to get the name of the
memory module correct than the instance.

[FIRRTL][ModuleInliner] Don't prefix memory names

---

include/circt/Conversion/Passes.td
include/circt/Dialect/HW/HWMiscOps.td
include/circt/Support/BackedgeBuilder.h
lib/Support/BackedgeBuilder.cpp
lib/Support/CMakeLists.txt

Replace the registered op in `hw` with an always registered op. As suggested by @River707.
https://discourse.llvm.org/t/constructing-backedges/61941/2

[Support] Backedges: Use always registered `builtin.unrealized_conversion_cast`

---

include/circt/Dialect/SV/SVInOutOps.td
lib/Dialect/SV/SVOps.cpp
test/Dialect/SV/basic.mlir

The previous verifier required sv.wire to exist in the top-level body
of a hw.module. This relaxes the verifier to allow wires in any
non-procedural region.

[SV] Allow sv.wire in any non-procedural region.

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Dialect/FIRRTL/grand-central.mlir

Fix Grand Central to properly handle views/interfaces that are
instantiated in the test harness and not in the DUT.  Specifically,
interfaces and companions are not extracted via binds if they are only
instantiated in the testharness (and a DUT is known via a
MarkDUTAnnotation).
This is handling some weird corner cases around Grand Central and whether or not things are extracted and to what locations. If a DUT exists, indicated via a `MarkDUTAnnotation`, then any interface/companion which is instantiated outside of the DUT (e.g., in the test harness) should not be extracted. If no DUT exists then everything is extracted normally.  For interfaces which are in the test harness, they should be output in the test directory.

[FIRRTL] Grand Central Testharness Fixes

---

include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp
test/Dialect/FIRRTL/check-comb-cycles-short.mlir

This commit adds `print-simple-cycle` option to print a simple cycle (enabled by default).
With that option, CheckCombCycle pass prints signal names contained
in a cycle (in the order of a cycle path) instead of dumping all
operations in the scc. It is useful for chisel users to debug their
chisel code since the cycle is actually a counterexample. Previous
error message (i.e. dumping all operations in SCC) is intentionally
kept to test the cycle dectection algorithm.
Example:
```scala
; Location is random
circuit hasloops :
module hasloops :
input clk : Clock @[Bar.scala 33:38]
input a : UInt<1> @[Bar.scala 33:38]
input b : UInt<1> @[Bar.scala 33:38]
output c : UInt<1> @[Bar.scala 33:38]
output d : UInt<1> @[Bar.scala 33:38]
wire y : UInt<1> @[Bar.scala 33:38]
wire z : UInt<1> @[Bar.scala …
```

[FIRRTL] [CheckCombCycle] Print a cycle while dumping signal names 

---

include/circt/Scheduling/Algorithms.h
lib/Scheduling/LPSchedulers.cpp
lib/Scheduling/SimplexSchedulers.cpp

The `lastOp` determines the algorithms' objective, so make sure it's actually registered in the given problem.

[Scheduling] Add consistency check.

---

include/circt/Dialect/Calyx/CalyxPrimitives.td
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Dialect/Calyx/CalyxOps.cpp
lib/Dialect/Calyx/Export/CalyxEmitter.cpp
test/Conversion/SCFToCalyx/convert_pipeline.mlir
test/Dialect/Calyx/emit.mlir
test/Dialect/Calyx/round-trip.mlir

This aligns the textual IR format, the emitter, and any locations
these ops were constructed in code to the result order defined by the
native  Calyx compiler. This is required for these ops to be able to
round-trip through the native compiler.

[Calyx] Update MultPipeOp and DivPipeOp format to round-trip.

---

include/circt/Dialect/Calyx/CalyxPrimitives.td
lib/Dialect/Calyx/CalyxOps.cpp
lib/Dialect/Calyx/Export/CalyxEmitter.cpp
test/Dialect/Calyx/emit.mlir
test/Dialect/Calyx/round-trip.mlir

This is a core Calyx primitive, and semantically is roughly the same
as sv.wire. Add support for it as a UnaryLibraryOp.

[Calyx] Add WireLibOp to represent a wire in Calyx's core library.

---

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
test/Dialect/FIRRTL/emit-metadata.mlir

This commit adds a unique groupID to each Testharness memory to prevent their
Dedup. This commit is a temporary fix to match SFC behavior. 
Currently, the memory dedup happens during the metadata emission, because that
is the first pass that requires the name of the final memory module. The plan
is to create a new Memory lowering pass, and move all the memory transformations to it.

[FIRRTL] Do not dedup testharness memories

---

test/circt-reduce/node-symbol-remover.mlir
tools/circt-reduce/Reduction.cpp

This commit adds a new reduction named NodeSymbolRemover to
remove symbols on node operations. This reduction is intended to
clean up symbols created by name preservation.
close #2963

[reduce] Add NodeSymbolRemover reduction

---

include/circt/Dialect/HW/ModuleImplementation.h
include/circt/Dialect/Handshake/Visitor.h
lib/Conversion/AffineToStaticLogic/AffineToStaticLogic.cpp
lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Dialect/FSM/FSMOps.cpp
lib/Dialect/HW/HWOps.cpp
lib/Dialect/HW/ModuleImplementation.cpp
lib/Dialect/Handshake/HandshakeOps.cpp
lib/Dialect/MSFT/MSFTOps.cpp
lib/Dialect/StaticLogic/StaticLogicOps.cpp
tools/circt-opt/circt-opt.cpp
tools/handshake-runner/Simulation.cpp

* Func argument source locators are no longer needed https://github.com/llvm/llvm-project/commit/31c8abc3f1cd9aa7787b2bce82abeb744a594f5e
* Some rearranging means we need to make our dialect dependencies explicit https://github.com/llvm/llvm-project/commit/eda6f907d2581a956aec511ae1d13adc3f97d3ad

WIP - Bump llvm.

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/annotations.fir
test/Dialect/FIRRTL/grand-central-signal-mappings.mlir
tools/firtool/firtool.cpp

Update the Grand Central (GCT) Signal Mappings pass to emit SiFive JSON configuration information necessary for downstream tests to work.  Concretely, this produces a filelist and some extra information about external modules in the design.
An example of output would be:
```json
{
"vendor": {
"vcs": {
"vsrcs": [
"/Users/schuylere/repos/github.com/llvm/circt/build/grandcentral/signaldriving/Simple/mfc/driving/signal_driver_signal_mappings.sv",
"/Users/schuylere/repos/github.com/llvm/circt/build/grandcentral/signaldriving/Simple/mfc/driving/signal_driver.sv"
]
},
"verilator": {
"error": [
"force statement is not supported in verilator"
]
}
},
"remove_vsrcs": [],
"vsrcs": [],
"load_jsons": [
"ExternalModule.json"
]
}
```

[FIRRTL] Omnibus fixes for Grand Central Signal Mappings

---

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
test/firtool/memoryMetadata.fir
test/firtool/prefixMemory.fir

This change ensures the testharness memories are not deduped, irrespective of the `GroupID` assigned to them.
It ignores the `GroupID` assigned to a testharness memory by `PrefixModules` pass, which is currently the only pass that assigns the `GroupID`.

[FIRRTL] Do not dedup testharness memory irrespective of Prefix

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/FIRRTL/FIRRTLOps.h
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
lib/Dialect/FIRRTL/Transforms/PrefixModules.cpp
test/Dialect/FIRRTL/inferRW.mlir
test/Dialect/FIRRTL/lower-types.mlir
test/firtool/prefixMemory.fir

Make the `GroupID` memory attribute as unsigned int, instead of signed. 
It is being used to distinguish memories that should not be Deduped.
`PrefixModules` pass assigns unique id for each prefix.
`CreateSifiveMetadata` pass assigns unique id for each memory under 
the testharness hierarchy.
This should fix some issues with the commit https://github.com/llvm/circt/commit/0926c4abb66f66ab3dfed2926f2e22181d39fc1a

[FIRRTL] Make GroupID memory attribute unsigned. NFC

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/dedup-errors.mlir

When two modules marked with MustDedup are not deduped with each other,
but they are deduped with something else, we end up trying to compare
the body of a module which was deleted.  This change makes us look up
the module they were actually deduped with to compare the modules.

[FIRRTL][Dedup] Fix MustDedup crash

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/FlattenMemory.cpp
test/Dialect/FIRRTL/flatten-memory.mlir
tools/firtool/firtool.cpp

The `LowerMemory` pass currently just flatten aggregate datatypes into a
single uint.  I want to separate the logic which lowers memories into
`hw.generatorModule`s out into a different pass, and I want to use the
name `LowerMemory` for that.

[FIRRTL] Rename `LowerMemory` to `FlattenMemory`

---

docs/FIRRTLAnnotations.md

This adds some documentation for the `AddSeqMemPortAnnotation` and
`AddSeqMemPortsFileAnnotation` annotations.  The pass which implements
the required feature will be coming.

[FIRRTL] Add documentation for `AddSeqMemPort` annotations

---

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
test/Dialect/FIRRTL/emit-metadata.mlir

Currently, when passed `--repl-seq-mem-file=mem.conf` and there are no memories, we will not emit the `mem.conf` metadata. This changes that behaviour to create an empty file, which is the same as SFC behaviour.  Some tooling expects this file to be created even if it is empty.  We made a similar change for `seq_mems.json` and previously decided we didn't need to have the same behaviour for this file.
@richardxia please confirm this is actually needed :)

[FIRRTL] print mem.conf even if there are no memories

---

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
test/Dialect/FIRRTL/inliner.mlir

Modules with both flatten+inline were only (inline+flatten)'d at first instantation site (not at all sites), and sometimes modules themselves were not flattened.
* Code now behaves more as if we walked and flattened all annotated modules first, and then performed inlining.
* Regression test added (non-exhaustive regarding the ways this could happen)
* Circuits may now be larger in some cases when there are multiple instances of flatten+inline modules, but that appears the intended behavior and I can't say how common this is.
Fix lingering InlineAnnotation on modules (and rework how/when FlattenAnnotation is removed, as part of above task)
* Module visibility changes some guarantees, as we assumed inline modules were dead (+removed) after inlining occurred.  Now that they can linger, be …

[FIRRTL][ModuleInliner] fix flatten+inline into multiple instance sites, annotation cleanup

---

lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp
test/Dialect/FIRRTL/check-comb-cycles-short.mlir

This is a follow-up onto https://github.com/llvm/circt/pull/2942
This commit tries improving an error message produced by recovering
a full cycle. Previously it didn't recurse into instance's internal so
the message is less verbose than SFC.
For example, the following IR contains a cycle through two instances 
`thru2` and `thru1`.
```scala
circuit hasloops :
module thru2 :
input in : UInt<1>  @[Bar.scala 33:38]
output out : UInt<1> @[Bar.scala 33:38]
out <= in @[Bar.scala 33:38]
module thru1 :
input in : UInt<1> @[Bar.scala 33:38]
output out : UInt<1> @[Bar.scala 33:38]
out <= in @[Bar.scala 33:38]
inst inner of thru2 @[Bar.scala 33:38]
inner.in <= in
out <= inner.out
module hasloops :
input clk : Clock
input a : UInt<1>
input b : UInt<1>
output c : UInt<1>
output d : UInt<1>
wire y : …
```

[FIRRTL] [CheckCombCycles] Improve error message by reconstructing a full cycle

---

include/circt/Conversion/StandardToHandshake.h
include/circt/Dialect/Handshake/HandshakePasses.h
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
lib/Dialect/Handshake/Transforms/Materialization.cpp

This change makes the lowering infrastructure used to lower `func::FuncOp` bodies available for other usages. As discussed in #2951 the lowering of the region is not dependent on the operation holding it. 
The newly added `lowerRegion` function expects a sub-type of `HandshakeLowering` which might have overridden member functions. The members are declared `virtual` to allow for such overriding without re-implementing the `lowerRegion` function. 
**Limitation**: Using this in a rewrite that changes the types of the entry block's `BlockArgument`s might cause problems due to `lowerRegion` not having access to the changed `Value`s and types. 
I'm sorry that this PR got this large, but there was a lot to restructure for this "simple" change.
Fixes #2951

[StandardToHandshake] enable reuse by exposing region lowering

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

This commit adds an extra initialization for async registers so
that they are set to initial values if reset signal is enabled at
an initial randomization phase. This matches SFC's behaviour.
For the following fir, 
```
circuit AsyncShift:  
module AsyncShift:
input reset : AsyncReset
output io : { flip d : UInt<1>, q : UInt<1>}
reg sync_0 : UInt<1>, clock with :
reset => (reset, UInt<1>("h0")) 
reg sync_1 : UInt<1>, clock with :
reset => (reset, UInt<1>("h0")) 
node _sync_2_T = bits(io.d, 0, 0) 
sync_1 <= _sync_2_T 
sync_0 <= sync_1 
io.q <= sync_0
```
We will get:
```verilog
`INIT_RANDOM_PROLOG_      // foo.fir:7:5
`ifdef RANDOMIZE_REG_INIT // foo.fir:7:5
_RANDOM = {`RANDOM};    // foo.fir:7:5
sync_0 = _RANDOM[0];    // foo.fir:7:5
sync_1 = _RANDOM[1];    // …
```

[FIRRTL][LowerToHW] Insert extra initialization for async regs

---

include/circt/Dialect/HW/HWTypes.td
include/circt/Dialect/MSFT/MSFT.td
include/circt/Dialect/MSFT/MSFTOps.h
include/circt/Dialect/MSFT/MSFTPDOps.td
integration_test/Bindings/Python/dialects/msft.py
lib/Bindings/Python/circt/dialects/_msft_ops_ext.py
lib/Dialect/MSFT/DeviceDB.cpp
lib/Dialect/MSFT/MSFTOps.cpp
lib/Dialect/MSFT/MSFTPasses.cpp
test/Dialect/MSFT/dynamic_instance.mlir
test/Dialect/MSFT/opt-errors.mlir

Create an instance hierarchy root operation. Require dynamic instances
to nest inside of it and only represent a single level of the hierarchy.
Results in a tree which better models the instance hierarchy.

[MSFT] Make dynamic instances hierarchical

---

frontends/PyCDE/src/pycde/devicedb.py
frontends/PyCDE/src/pycde/instance.py
frontends/PyCDE/src/pycde/system.py
frontends/PyCDE/test/instances.py
lib/Bindings/Python/circt/dialects/_msft_ops_ext.py
lib/Bindings/Python/circt/support.py

Previously, PlacementDB.get_instance_at would return a raw CIRCT op. It
now resolves it back to a Python Instance object. Also deletes the
coord-based instance lookup since it was untested and unused.

[PyCDE] Teach PlacementDB how to resolve to `Instance`s

---

frontends/PyCDE/src/pycde/instance.py
frontends/PyCDE/src/pycde/system.py
frontends/PyCDE/test/instances.py
include/circt/Dialect/MSFT/MSFTPDOps.td
integration_test/Bindings/Python/dialects/msft.py
lib/Bindings/Python/circt/dialects/_msft_ops_ext.py

If the instance caches got cleared, lazily rebuild them on queries. Thus
far, we've gotten away with this since we were in a "fire and forget"
type situation, but lowering the high-level constructs won't be.

[PyCDE] Adds support for rebuilding the instance cache

---

include/circt/Dialect/Handshake/HandshakeOps.td
lib/Dialect/Handshake/HandshakeOps.cpp

The previously used `ArrayRef<Value>` can be implicity converted to `ValueRanges`, but the other way is not as simple.

[Handshake] Make builders more flexible by using ValueRange

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

When the ReadInOutOp accessing a register or a wire was after the use of the read value, a temporary wire was emitted.  This patch instead moves both the definition of the read operation and the read itself to the top of the module, ensuring the order is correct and no temporaries are needed.
As a result, the verilog representation of a large design is 0.6% shorter, with thousands of temporaries eliminated.

[SV] Avoid temporary wires when ReadInOutOp is after use

---

lib/Dialect/Handshake/HandshakeOps.cpp
test/Dialect/Handshake/func.mlir

This PR introduces parsing for optional visibility information of `handshake::FuncOp`s.
I added a new test called `func.mlir` as there are no other tests that simply round-trip on operations in the `test/Dialect/Handshake` folder.

[Handshake] Add optional visibility parsing for `FuncOp`

---

docs/FIRRTLAnnotations.md
include/circt/Dialect/FIRRTL/AnnotationDetails.h
include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp
test/Dialect/FIRRTL/inject-dut-hierarchy-errors.mlir
test/Dialect/FIRRTL/inject-dut-hierarchy.mlir
tools/firtool/firtool.cpp

Add a pass that adds a level of hierarchy (indicated by an
InjectDUTHierarchyAnnotation) above the DUT (as indicated by a
MarkDUTAnnotation).
Add an option to enable the InjectDUTHierarchy pass from a command-line
option in firtool.

[FIRRTL] Add InjectDUTHierarchy Pass

---

include/circt/Dialect/HW/HWStructure.td
test/Dialect/HW/errors.mlir

The `HWInstanceOp` has a redundant check that the SymbolRef it has is a
valid HW module operation. This change keeps the more efficient of the
two methods, and removes the slower one.

[HW] Remove InstanceOp's constaint on the symbol

---

include/circt/Dialect/HW/HW.td
include/circt/Dialect/HW/HWAttributesNaming.td
include/circt/Dialect/HW/HWSymCache.h
include/circt/Dialect/SV/SV.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/HW/HWAttributes.cpp

InnerNameRef now relies on a symbol constrained to a single nested reference.
It implements the SubElementAttrInterface trait so it can be scanned for references.
The constructor requiring a context argument was removed.

[HW] InnerNameRef backed by a symbol

---

include/circt/Dialect/HW/HWStructure.td
lib/Dialect/HW/HWOps.cpp
unittests/Dialect/HW/CMakeLists.txt
unittests/Dialect/HW/HWModuleTest.cpp

Added `HWModuleOp::addOutputs` which takes a list of port name-value pairs and inserts the outputs into the port list and the output op.

[HW] Added a helper method to HWModuleOp to insert new outputs

---

lib/Dialect/FIRRTL/Export/FIREmitter.cpp
test/Dialect/FIRRTL/emit-basic.mlir

Noticed while working on #3027.
This has conflicts/ordering problems with that PR, I'll update/resolve as needed.

FIREmitter: give strictconnect same invalid treatment, add test

---

include/circt/Dialect/SV/SVExpressions.td
include/circt/Dialect/SV/SVStatements.td
include/circt/Dialect/SV/SVVisitors.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/SV/SVOps.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir
test/Conversion/ExportVerilog/verilog-basic.mlir
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/SV/basic.mlir
test/Dialect/SV/cse.mlir

Replaced verbatim expressions with an explicit `MacroRefExprOp` to refer to macros in `sv`.

[SV] Added `macro.ref` to reference macros.

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp

When testing #3025, this bug was exposed (DenseMap resizing breaking refs).
Resolve it the same way as `FIRStmtParser::emitPartialConnect`,
by copying locally after ensuring the field is created if needed.

FIRParser: fix ref invalidation in connectDebugInfo,emitPartialConnect

---

docs/RationaleFIRRTL.md
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/connect-errors.fir
test/Dialect/FIRRTL/parse-name-preservation.fir

* Now we reject these invalid connect's in the parser (see test, from docs)
* verifier rejects `firrtl.connect`'s with these as well
This helps better match SFC behavior, and is useful for when `firrtl.partialconnect` is dropped.
In particular before this types could be "equivalent" but not "weakly equivalent", which is unexpected.
The name-preservation taps on non-passive types will be more verbose, connecting components individually.
This is because the name-preservation wire is made with a passive type, which this change makes illegal (to bulk connect to the original wire's non-passive type).

[FIRRTL] check flip orientation in connect operations

---

test/circt-reduce/commandline.mlir
test/firtool/commandline.mlir
test/llhd-sim/commandline.mlir
tools/circt-reduce/circt-reduce.cpp
tools/firtool/firtool.cpp
tools/llhd-sim/llhd-sim.cpp

Slightly improve `--help` output for a few tools by grouping the options for each tool explicitly and hiding unrelated options.
In the default build configuration, the output change is not significantly different for `circt-reduce` and `firtool` (I'll post the output below).  `llhd-sim` does have a number of low-level flags hidden, which I believe are not useful but this should be vetted.
Tests are extended, and in the case of `llhd-sim`, added, to check for this new output.
When building CIRCT against LLVM built as shared libraries (or library), as preferred by packagers of LLVM in e.g., most Linux distributions, this change greatly improves the usability of these tools (200 -> 38 options, or so, for circt-reduce, IIRC).
That was the original motivation, as I wanted to see what options …

circt-reduce,firtool,llhd-sim: cleanup --help output, put options in category

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/dedup-errors.mlir

When a module is not deduplicated due to a NoDedup annotation, the
equivalence checker would compare the module bodies, missing the fact
that the annotation was what blocked deduplication.
This also fixes a bug when the NoDedup and MustDedup annotation pointed
at the same module.  We didn't record the presence of the module when it
was marked NoDedup which caused the MustDedup annotation to claim that
the referenced module did not exist.

[FIRRTL][Dedup] Improve error when module is both NoDedup and MustDedup

---

include/circt/Dialect/FSM/FSMOps.td
lib/Dialect/FSM/FSMOps.cpp
test/Dialect/FSM/basics.mlir
test/Dialect/FSM/errors.mlir

Previously, the first state in the machine was assumed to be the initial state - I believe being explicit here is important to ensure the machine behaves as intended. Also modified "default" state to "initial" state (seems to be more consistent with literature). It should be mentioned that I'm doing this to detach some of the "hardware-like" assumptions of the FSM dialect (another example is the implicit priority encoding of the list of transitions). I'd like to see it be more broadly applicable so that we can do interesting things such as DFA/NFA optimizations, equivalence, etc..

[FSM] Make initial state explicit

---

include/circt/Dialect/FSM/FSMOps.td
lib/Dialect/FSM/FSMOps.cpp
test/Dialect/FSM/canonicalize.mlir

Since we currently only allow a single initial state for the state machine, it is a reasonable assumption that any unreasonable states may be pruned as part of canonicalization.
Depends on #3019

[FSM] Canonicalize away unreachable states

---

include/circt/Dialect/FSM/FSMOps.td
lib/Dialect/FSM/FSMOps.cpp
test/Dialect/FSM/basics.mlir

Guard and action regions are now optional. This is already stated in the dialect rationale, but was not implemented.

[FSM] Make transition guard and action regions optional

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/disallow-local-vars.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir

This commit removes conditions of `isExpressionUnableToInline` regarding
users in different blocks. As discussed in https://github.com/llvm/circt/issues/2962, it should be safe to 
remove the restriction today.

[ExportVerilog] Make `isExpressionUnableToInline` more liberal

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-errors.fir

Also print more specific error in the case of no modules at all.
Fixes #2971.

FIRParser: don't crash if no main module, print error

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/Comb/canonicalization.mlir

This implements following canonicalizers which improve SiFive's internal designs. 
```
eq(replicate(v), 0) ==> v == 0
eq(replicate(v), -1) ===> v == -1
neq(replicate(v), 0) ==> v != 0
neq(replicate(v), -1) ===> v != -1
```
Close #3036

[CombFolds] Add a canonicalizer for andr, orr + replicate

---

include/circt/Dialect/Handshake/HandshakeOps.td
lib/Dialect/Handshake/HandshakeOps.cpp
test/Dialect/Handshake/errors.mlir
test/Dialect/Handshake/tuple-ops.mlir

This PR introduces the operations described in #3037.
Note that I plan to add lowerings to FIRRTL and support for the `handshake-runner` in subsequent patches, as they are not directly related to the introduction of these operations.

[Handshake] Add tuple pack and unpack operations

---

lib/Dialect/Calyx/CalyxOps.cpp
test/Dialect/Calyx/errors.mlir
test/Dialect/Calyx/round-trip.mlir

The verification ensures that:
- At most one continuous assignment exists for any given value
- A continuously assigned wire has no assignments inside groups.

[Calyx] Verify continuously assigned values

---

docs/VerilogGeneration.md
lib/Support/LoweringOptions.cpp

Assuming we want to advertise the option for use, add it to docs and the `--help` output to aid discoverability.
Will conflict with #3046, where I just now included similar additions for that option as well :).
Writing it up, it does seem like a `None` option would make sense (or at least a person reading docs might ask "but what if I don't want location information" is my thinking)? I think that is what `--strip-debug-info` does.  Anyway that can wait :).  For now lets document what's available now! :+1:

locationStyleInfo: add doc blurb, add to cl::opt help

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Fixes #3043.
(see that issue for example/crasher details)

FIRRTLFolds: don't crash on vector's connected to wire w/invalid

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Conversion/FIRRTLToHW/module-hierarchy-file.mlir
test/Dialect/SV/hw-extract-test-code.mlir

We don't have to extract assertions from  modules in testbench since
it already separated from DUT. This commit adds`firrtl.extract.do_not_extract` 
attribue to modules on LowerToHW if they are located in testbench. 
And in SVExtractTestCode, we skip extractions if that attribute appears.
This change will hopefully improve simulation performance by reducing overheads 
of module instantiation.

[LowerToHW][SVExtractTestCode] Don't extract assertions from testbench

---

docs/VerilogGeneration.md
include/circt/Support/LoweringOptions.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Support/LoweringOptions.cpp
test/Conversion/ExportVerilog/port-decl-sharing.mlir

Currently we group ports by direction+type and only print that part (e.g., `input [3:0]`) once per group.
For compatibility reasons, it may be useful to always print this information for each port.
Add a new lowering option "noPortGrouping" to control this.
```verilog
module Foo(     // dummy:1:1
input        a,
b,
input  [4:0] c,
d,
output       a_0,
b_1,
output [4:0] c_2,
d_3);
```
```verilog
module Foo(     // dummy:1:1
input        a,
input        b,
input  [4:0] c,
input  [4:0] d,
output       a_0,
output       b_1,
output [4:0] c_2,
output [4:0] d_3);
```
Not sure "port grouping" is quite right, it's more about whether we have multiple ports per declaration :sweat_smile: .  Suggestions welcome, or I'll revisit tomorrow :).

ExportVerilog: Add lowering option to always print port direction/type

---

tools/firtool/firtool.cpp

This commit moves the `ExtractInstances` pass before the `GCT` passes.
`GCT` passes can embed the instance paths into `Verbatim` ops, which can later be updated 
by the `ExtractInstances` pass, causing incorrect instance paths being generated into the verilog.

[FIRRTL] Move ExtractInstances pass before GCT

---

include/circt/Dialect/FIRRTL/FIRRTLAttributes.td

This type constraint was missing an error message, causing the error
message to seem very cryptic.

[FIRRTL] Add error message to AnnotationArray type constraint

---

lib/Dialect/FIRRTL/FIRRTLOps.cpp

The helper accidentally inserted the block arguments in the reverse
order that it was supposed to. This was happening because each block
argument was inserted one at a time, causing us to have to increase the
insertion index by 1 every time we insert an argument.

[FIRRTL] Fix module port insertion helper

---

include/circt/Dialect/FIRRTL/FIRRTLStructure.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/test.mlir

This adds a FMemModule operation, which is an external module used for
FIRRTL SRAMs.  It is almost exactly the same, except it doesn't support
FExtModule's parameterization, does not have  a `defname`, and it
contains required attributes for memory metadata. It was convenient to
not use FExtModules with a bunch of extra attributes stored on it to
make sure that the attributes were properly checked.
The set of attributes stored on the memory are those needed to create all
the metadata files.  The types used for the attributes were generally
the same as those used by the memory generator schema. It might make
sense to revisit the types and use signless integer types in the future.

[FIRRTL] Add FMemModule operation

---

include/circt/Dialect/SV/SVStatements.td
lib/Dialect/SV/SVOps.cpp

This commit adds a builder to sv::CaseOp which takes a validation qualifier as
an argument. This is separated from https://github.com/llvm/circt/pull/3024.

[SV] Add a builder to CaseOp which takes a validation qualifier

---

test/firtool/firtool.mlir
tools/firtool/firtool.cpp

This works similarly to output-omir: if specified, the final MLIR is
written into this file. This is useful to get the final MLIR output
alongside some other output, especially split-verilog.
This would close https://github.com/llvm/circt/issues/2946.

[FIRRTL] Add output-mlir option to firtool.

---

lib/Dialect/FIRRTL/Transforms/InferResets.cpp
test/Dialect/FIRRTL/infer-resets.mlir

When the FullAsyncResetTransform replaces the reset of a register it
replaces all other connections to the register with a `mux(reset,
resetValue, originalValue)`.  The transform did not properly take into
account the implicit self connection of every register, `r <= r`.  This
caused problems when the value was connected inside of a When block, and
the old reset value would become gated on the When op's condition.  The
original reset value needed to have higher priority than the original
conditions. This change adds an explicit self-connect to the register
which is properly muxed with the reset.
An alternative way of handling this is to move the
`FullAsyncResetTransform` after ExpandWhens, or to make the implicit
self connect of registers explicit in the parser.
Input:
```firrtl
reg r : …
```

[FIRRTL][FullAsyncResetTransform] Preseve synchronous reset value

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/AddSeqMemPorts.cpp
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
test/Dialect/FIRRTL/add-seqmem-ports-errors.mlir
test/Dialect/FIRRTL/add-seqmem-ports.mlir
tools/firtool/firtool.cpp

This adds a new FIRRTL transformation which looks for
AddSeqMemPortsAnnotation and attaches the extra port specified to all
SRAMs under the DUT.  The extra ports are always of type `UInt<>` with a
user specified width.  The extra ports are wired up through the top of
the DUT and tied off to 0 in the testharness.
This pass requires that memories have been lowered to modules, and will
emit an error if it finds a regular mem op in the module.  This is
because it is not possible to add arbitrary ports to a memop that don't
match the schema of a memory r/w/rw port.

[FIRRTL] Add AddSeqMemPorts pass

---

lib/Dialect/FIRRTL/FIRRTLInstanceGraph.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp
lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp

This fixes a couple places that have the baked in assumption that there
are only 2 module types.  This can be merged before the new `FMemModuleOp`
is actually merged.

[FIRRTL] Fix some passes to work with the new FMemModuleOp

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir

This adds the ability to lower FIRRTL memory modules to external module
black boxes.  This lowering is almost the same as FIRRTL external
modules, but without having to worry about parameterization or defname.

[FIRRTL][LowerToHW] Lower `firrtl.memmodule` to `hw.module.ext`

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

ExportVerilog may end up spilling temporary declarations for
expressions that are already going to be assigned to an inout. Try to
anticipate this in PrepareForEmission, and rewrite the uses of the
expression to read from the inout when possible.

[ExportVerilog] Try to re-use existing inouts when possible.

---

include/circt/Dialect/FSM/CMakeLists.txt
include/circt/Dialect/FSM/FSMGraph.h
include/circt/Dialect/FSM/FSMPasses.h
include/circt/Dialect/FSM/Passes.td
include/circt/InitAllPasses.h
lib/Dialect/FSM/CMakeLists.txt
lib/Dialect/FSM/FSMGraph.cpp
lib/Dialect/FSM/Transforms/CMakeLists.txt
lib/Dialect/FSM/Transforms/PassDetails.h
lib/Dialect/FSM/Transforms/PrintFSMGraph.cpp
test/Dialect/FSM/print-graph.mlir
tools/circt-opt/CMakeLists.txt

Initial implementation of LLVM graph traits for the `fsm.machine` operation. This will probably be a fairly critical piece of code for building further transformations, visualizations, ... upon.
Example `dot` output of the included `print-graph.mlir` test:

[FSM] Implement graph traits for `fsm.machine`

---

lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

We should identify the clocks to be same even if the clock is passed via different wires, This should prevent creating multiple write ports for combmem. We should consider to revert this change once we stop creating anoymous wires at FlattenMemory.

[FIRRTL] Track clock values of memory ports precisely

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir

This commit changes to reuse existing wires as placeholder of output ports 
when output ports are uniquely assigned to a wire.  
Example
```scala
circuit Foo:
extmodule Bar:
output sink: UInt<3>
module Foo:
output c: UInt<3>
wire foo: UInt<3>
inst bar of Bar
foo <= bar.sink
c <= foo
```
After:
```verilog
wire [2:0] foo; 
Bar bar ( 
.sink (foo)
);
assign c = foo;  
```
Before:
```verilog
wire [2:0] _bar_sink; // foo.fir:7:5
wire [2:0] foo;       // foo.fir:6:5
assign foo = _bar_sink;   
Bar bar (     // foo.fir:7:5
.sink (_bar_sink)
);
assign c = foo;  
```

[PrepareForEmission] Reuse wires for output ports

---

include/circt/Support/Namespace.h
lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
test/Dialect/FIRRTL/SFCTests/emit-omir.fir
test/Dialect/FIRRTL/emit-metadata.mlir
test/firtool/memoryLowering.fir
test/firtool/memoryMetadata.fir
test/firtool/prefixMemory.fir
tools/firtool/firtool.cpp

This changes the memory-related metadata emitted by this pass to be
created from FMemModules instead of MemOps.  The memories will have
already been lowered into modules.  The pass can be simplified because
it no longer has to worry about deduplicating the memories itself.

[FIRRTL][CreateSiFiveMetadata] Base metadata on FMemModules

---

lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp
test/Dialect/FIRRTL/extract-instances.mlir

Extend the `ExtractInstances` pass such that it marks instances of the new `FMemModuleOp` as to be extracted. This then allows the pass to cover the functionality of the original `ExtractSeqMems` pass on the Scala side of things.
Fixes #3092.

[FIRRTL] Extract memory instances

---

include/circt/Dialect/Calyx/CalyxPasses.h
include/circt/Dialect/Calyx/CalyxPasses.td
lib/Dialect/Calyx/Transforms/CMakeLists.txt
lib/Dialect/Calyx/Transforms/GICM.cpp
test/Dialect/Calyx/gicm.mlir

The assumption here is that any operation which is not a special group operation (`calyx.group_done,calyx.group_go,calyx.assign`) is some form of combinational computation that can be lifted to the wire scope.
The pattern is added as a separate pass, but could be added as a canonicalization of `GroupOp`s.
I'd be in favor of adding this as a canonicalization of `GroupOp`s. GICM does not mean that we suddenly get unwanted sharing of `comb` operation results (e.g. as seen in the test, an identical `comb` operation is emitted twice in the wire scope - CSE is not part of `comb` canonicalizers, which i presume is due to fan-out reasons).
The downside to doing GICM during canonicalization is that it might obscure the IR a slight bit, since `comb` operations are no longer inside the groups where …

[Calyx] Add group-invariant code motion pass

---

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
test/Dialect/FIRRTL/emit-metadata.mlir
test/firtool/prefixMemory.fir

Update metadata emission to use symbols, instead of embedding the module names.

[FIRRTL] Use symbols for metadata emission

---

lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp
test/Dialect/FIRRTL/extract-instances.mlir

Fix an issue in the `ExtractInstances` pass where certain diamond-shaped instantiation arrangements can lead to instances with identical symbol after extraction.
With this change, the pass uses `ModuleNamespace::newName` to ensure the instance symbol is unique within the module it is being extracted to. Fixing this also requires fixing an issue where a black box in a multiply instantiated parent would not properly filter its non-local annotations to only contain the ones that go through the parent instance it was pulled out of.
Fixes #3089.

[FIRRTL] Uniquify extracted instance symbols

---

include/circt/Support/LoweringOptions.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

This commit changes ExportVerilog to emit extra bitcast to toplevel sub op 
to surpass (false-positive) lint warning when `explicitBitcastAddMul` option is enabled.

[ExportVerilog] Add extra bitcast to toplevel sub op

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

This PR changes to lower node ops with symbols into read_inout ops of wires.
Considering the concept of the current name preservation, "nodes become wires 
if they have names", it would be nice to use existing named wires as much as possible. 
This change basically disables optimizations across named nodes at comb levels, 
so we can prevent canonicalizers from duplicating expressions. 
This change reduces 30% temporary wires and 50% lint warnings related to dead wires 
in the large design while improving the simulation performance as well.
e2e example:
```scala
circuit Foo:
module Foo:
input data : UInt<1>[4]
output z : UInt<4>
node cat_lo = cat(data[1], data[0]);
node cat_hi = cat(data[3], data[2]);
node v = cat(cat_hi, cat_lo);
z <= v
```
After:
```verilog
assign cat_lo = {data_1, …
```

[LowerToHW] Lower node op with a symbol into read_inout op

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/SFCTests/data-taps.fir

Handle MemTap annotation on Memories that are excluded from `MemToRegOfVec` transformation.
This fixes an issue with the commit https://github.com/llvm/circt/commit/26276bfc85df9c0864730182f34ccf73e14c1f19 which updated this pass to only work on registers that were generated by `MemToRegOfVec` transformation. The assumption here was that every MemOp, should either be lowered to registers by `MemToRegOfVec` or to `FMemModuleOp` by `LowerMemory`. So, the GCT pass shouldn't expect to see a `MemOp`. 
But yesterday's commit https://github.com/llvm/circt/commit/b92396367a74d542a5ed51d745c4fbc27b6ad877, updated the `MemToRegOfVec` to exclude testbench memories and made the incorrect assumption that testbench memories wouldn't have memtap annotations. 
Finally this commit fixes that assumption …

[FIRRTL] Handle memTap on Memories excluded from MemToReg (#3102)

---

include/circt/Dialect/Calyx/Calyx.td
include/circt/Dialect/Calyx/CalyxInterfaces.td
include/circt/Dialect/Calyx/CalyxPrimitives.td
include/circt/Dialect/Calyx/CalyxStructure.td
lib/Dialect/Calyx/CalyxOps.cpp
test/Dialect/Calyx/errors.mlir

Previously, cells were instantiated with `FlatSymbolRefAttr`s but didn't actually use these in a symbol table context.
This commit changes the `CellOpInterface` to expect implementing operations to be symbol-defining operations. A side-effect of this is that we now implicitly check for duplicate instance names (something which was possible beforehand).

[Calyx] Make cell operations symbol-defining

---

include/circt/Dialect/FIRRTL/FIRRTLStructure.td
include/circt/Dialect/FIRRTL/NLATable.h
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/NLATable.cpp
lib/Dialect/FIRRTL/Transforms/Dedup.cpp

Add a few utilities to the `NLATable` analysis, and use the analysis for `Dedup` pass, instead of using the `NLAMap`. 
This is a first step towards removing the NLA breadcrumbs on `InstanceOps`.

[FIRRTL] Use NLATable analysis for Dedup Pass

---

lib/Dialect/FIRRTL/Transforms/AddSeqMemPorts.cpp

The `AddSeqMemPorts` pass has a check during execution that it doesn't
see any MemOps, since they should have been converted to behavioural
implementations or blackboxed.  This was a very simple check added just
to catch any phase-ordering problems in the FIRRTL pipeline.  We have
since revised the lowering of memories to let some memories to be
handled by the HW memory generator, and so some mem ops can still be
around and it isn't an error. There was no test to update when removing
this check.

[FIRRTL][AddSeqMemPorts] Don't error if there are still MemOps

---

lib/Dialect/FIRRTL/Transforms/MemToRegOfVec.cpp
test/Dialect/FIRRTL/mem-to-reg-of-vec.mlir
test/firtool/chirrtl.fir
test/firtool/memory.fir
test/firtool/phase-ordering.fir

This commit makes sure that the `MemToRegOfVec` transformation must run only if the annotation
`"sifive.enterprise.firrtl.ConvertMemToRegOfVecAnnotation$"` is present on the `Circuit` op.
Earlier, the assumption was that the transformation can always run by default, but in order to match SFC behavior this check is necessary.
Add the check and update all the lit tests accordingly.

[FIRRTL] Guard the MemToReg transformation with the annotation

---

lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
test/Conversion/HandshakeToFIRRTL/test_buffer.mlir
test/Conversion/HandshakeToFIRRTL/test_buffer_fifo.mlir
test/Conversion/HandshakeToFIRRTL/test_tuple_type.mlir

This commit introduces lowering for tuple types by transforming them to BundleTypes.
Some of this work was part of #3054 but as this grew bigger than expected, I decided to split this into separate PRs.

[HandshakeToFIRRTL] Add support for tuple types

---

include/circt/Support/LoweringOptions.h
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
lib/Support/LoweringOptions.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

This adds another heuristic to shouldSpillWire, this time to check if
the number of operands in a single expression inside a concat. If this
exceeds a configurable limit, a wire is spilled. This is to work
around Verilator #3405.
Large expressions inside a concat is worst case O(n^2) in a certain
Verilator optimization, and can effectively hang Verilator on large
designs. Verilator 4.224+ works around this by having a hard limit on
its recursion. Here we break large expressions inside concats
according to a configurable limit to work around the same issue.
See https://github.com/verilator/verilator/issues/3405.

[PrepareForEmission] Spill wires for largish expressions in concat.

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

This fixes the difference between SFC and MFC in async initializations.
MFC with the PR:
```
initial begin	// foo.fir:7:5
`INIT_RANDOM_PROLOG_	// foo.fir:7:5
`ifdef RANDOMIZE_REG_INIT	// foo.fir:7:5
_RANDOM = {`RANDOM};	// foo.fir:7:5
sync_0 = _RANDOM[0];	// foo.fir:7:5
`endif
`ifdef RANDOMIZE	// foo.fir:7:5
if (reset)	// foo.fir:7:5
sync_0 = 1'h0;	// foo.fir:7:5, :8:24
`endif
end // initial
```
SFC:
```
initial begin
`ifdef RANDOMIZE
`ifdef INIT_RANDOM
`INIT_RANDOM
`endif
`ifndef VERILATOR
`ifdef RANDOMIZE_DELAY
#`RANDOMIZE_DELAY begin end
`else
#0.002 begin end
`endif
`endif
`ifdef RANDOMIZE_REG_INIT
_RAND_0 = {1{`RANDOM}};
sync_0 = _RAND_0[0:0];
`endif // RANDOMIZE_REG_INIT
if (reset) begin
sync_0 = 1'h0;
end
`endif // RANDOMIZE
end // initial
```

[LowerToHW] Wrap aynsc reset initiliazation by ifdef

---

include/circt/Dialect/Handshake/HandshakeOps.td
include/circt/Dialect/Handshake/Visitor.h
integration_test/Dialect/Handshake/tuple_packing.mlir
lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
test/Conversion/HandshakeToFIRRTL/test_pack_unpack.mlir

This PR introduces lowerings of the operations working on tuples, related to #3037.
`TupleTypes` are transformed to `BundleTypes` with element names `field0`, ..., `field[N-1]`.
The pack and unpack operations connect the separated values with the ones encapsulated in the bundle while having similar control logic as `ForkOp` and `JoinOp`.

[HandshakeToFIRRTL] Add support for PackOp and UnpackOp

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp

Use NLATable analysis in LowerTypes and GrandCentral.
This is a continuation of https://github.com/llvm/circt/pull/2874, and shares the analysis commit with it.

[FIRRTL] Use NLATable analysis in LowerTypes and GrandCentral

---

include/circt/Dialect/HW/HWSymCache.h
include/circt/Dialect/MSFT/ExportTcl.h
include/circt/Support/SymCache.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/HW/Transforms/HWSpecialize.cpp
lib/Dialect/MSFT/CMakeLists.txt
lib/Dialect/MSFT/MSFTPasses.cpp
lib/Dialect/SV/SVOps.cpp
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
lib/Support/CMakeLists.txt
lib/Support/SymCache.cpp

To allow for using symbol caches for things other than that in `HW`, SymCache has been made generic.
Considering its current use/implementation (`HWSymCache`), `InnerRefAttr` getter/setters have been lifted to the `HWSymCache` specialization, while keeping the underlying `addDefinition/getDefinition/lookup` logic generic.
The cache class hierarchy starts with a `SymbolCacheBase`. The intention of having a non-templated type for read-only access to the cache is to be able to provide a symbol cache to other tools which might need to do efficient read-only lookup. In a follow-up commit, i intend to introduce a new class `SymUniquer` which, given a `SymbolCacheBase`, can generate unique names given an input base name - this will replace some custom logic in `SCFToCalyx` (and is probably …

[HW,Support] Make symbol cache generic and move it to Support

---

docs/RationaleHW.md

This was implemented a long time ago, but never documented. Since it
has stabilized, it is important to bring the docs up to date. This
discusses the IR, System Verilog output, canonicalization, and open
issues.

[Docs] Fill in "Type declarations" section of HW rationale.

---

include/circt/Dialect/Seq/CMakeLists.txt
include/circt/Dialect/Seq/Seq.td
include/circt/Dialect/Seq/SeqDialect.h
include/circt/Dialect/Seq/SeqPasses.h
include/circt/Dialect/Seq/SeqPasses.td
include/circt/InitAllPasses.h
lib/CAPI/Dialect/CMakeLists.txt
lib/CAPI/Dialect/Seq.cpp
lib/Dialect/Seq/CMakeLists.txt
lib/Dialect/Seq/Transforms/CMakeLists.txt
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
lib/Dialect/Seq/Transforms/PassDetails.h
tools/circt-opt/CMakeLists.txt

Moved the definiton of `Seq` passes to a separate `SeqPasses.h`, similarly to other dialects.
Exposed the `createSeqLowerToSV` function to be used by other clients.

[Seq] Moved pass definition to a separate header

---

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
test/Conversion/SCFToCalyx/convert_pipeline.mlir

This is a hot fix for memref::StoreOps to be used unconditionally in a pipeline stage. I'm not really convinced this is the best approach, however I'm also hesitant to commit to any large-scale changes before we separate {SCF, StaticLogic}ToCalyx conversions.
Closes #3112, #3111.

[SCFToCalyx] Add special case for pipeline stages with side effects only.

---

include/circt/Dialect/Handshake/HandshakeOps.td
lib/Dialect/Handshake/HandshakeOps.cpp
test/Dialect/Handshake/errors.mlir

This patch adds the `SymbolUserOpInterface` to the `InstanceOp` which is used to enforce type equality of the operation and the `FuncOp` it calls.
The code is based on the same verifier for `mlir::func::CallOp`.

[Handshake] Add type equality checks to InstanceOp

---

lib/Dialect/Handshake/HandshakeOps.cpp

This member function was declared but not defined.

[Handshake] Add missing InstanceOp::getModuleType definition

---

include/circt/Dialect/FIRRTL/FIRRTLOps.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

This commit sets the Combinational memory wrapper module name and file location, instead of the generic `FIRRTLMem_0_2_0_8_16_1_1_1_0_1_0_aa` formatted name and default file location.
Use the name associated with `firrtl.mem` to derive the wrapper module name, after appending it with `_combMem`.
This ensures the correct module prefix is used for the wrapper module. (For example `SiFive` prefix for DUT modules and not otherwise).
For memories outside the DUT, set the output file directory to the TestBench directory if available. 
This change requires to add the `MemOp` to the `FirMemory`, such that the memory dedup can be done in `LowerToHW`.
Use a map `memoryNameMap` to get the correct `HWModuleGeneratedOp`  names for deduped memories.

[FIRRTL] Set name and file location for Comb memory wrapper module

---

include/circt/Dialect/MSFT/MSFTAttributes.h
include/circt/Dialect/MSFT/MSFTAttributes.td
include/circt/Dialect/MSFT/MSFTPDOps.td
lib/Dialect/MSFT/ExportQuartusTcl.cpp
lib/Dialect/MSFT/MSFTAttributes.cpp
lib/Dialect/MSFT/MSFTOps.cpp
lib/Dialect/MSFT/MSFTPasses.cpp
test/Dialect/MSFT/attributes.mlir
test/Dialect/MSFT/dynamic_instance.mlir

`PDRegPhysLocationOp` takes a type and a list of physical locations. The
list of physical locations must equal the bit width of the type. The
physical locations are each optional.

[MSFT] Add an op to place all the bits in a register

---

include/circt/Dialect/Calyx/CalyxLoweringUtils.h
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Conversion/StaticLogicToCalyx/CMakeLists.txt
lib/Conversion/StaticLogicToCalyx/StaticLogicToCalyx.cpp

The two lowering conversions use a similar interface for the `while` control flow. This attempts to use this knowledge to have a single class for both, rather than perform runtime casts. 
This also begins cleaning up mentions of SCF in StaticLogicToCalyx, and pipelines in SCFToCalyx.

[SCFToCalyx] [StaticLogicToCalyx] Pull out while-operation interface.

---

lib/Dialect/FIRRTL/FIRRTLUtils.cpp
lib/Dialect/FIRRTL/Transforms/FlattenMemory.cpp
lib/Dialect/FIRRTL/Transforms/LowerCHIRRTL.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-chirrtl.mlir
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/parse-locations.fir
test/Dialect/FIRRTL/parse-name-preservation.fir
test/firtool/connect.fir
test/firtool/optimizations.fir

* Replace "mkConnect" helpers, moving to emitConnect
* (mkConnect's aren't quite the same as emitConnect--they are happy to connect things of different types, where emitConnect will pad/etc as needed)
* Simplify code that conditionally called mkConnect vs emitConnect, let emitConnect handle things (LowerTypes, LowerCHIRRTL)
* Fix small bug in emitConnect preventing creation of strictconnect's after padding performed
* (type equality check was done on types before the pad/etc) (first commit)
* Update tests
* Fix unnecessary check for analogtype nested within types strictconnect'd -- verifier rejects these
Follow-up to previous connect-related PR's.

[FIRRTL] create more strictconnect's (mkConnect -> emitConnect, enable strictconnect gen in emitConnect)

---

include/circt/Dialect/HW/HWAttributes.h
lib/Dialect/HW/HWAttributes.cpp
lib/Dialect/HW/Transforms/HWSpecialize.cpp
test/Conversion/ExportVerilog/verilog-basic.mlir
test/Dialect/HW/specialize.mlir

This removes the requirement that parameters passed to a module instance must evaluate to constants. This allows a parametric module to instantiate nested parametric modules using its own parameters.
This change required reworking the HWSpecialize pass, where parametric modules defer specialization of instantiated parametric modules until after the parent modules themselves are specialized.

[HW] Relax parameter evaluation to allow resolution to passed in parameters

---

include/circt/Dialect/Calyx/CalyxHelpers.h
include/circt/Dialect/Calyx/CalyxLoweringUtils.h
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Conversion/StaticLogicToCalyx/StaticLogicToCalyx.cpp
lib/Dialect/Calyx/CMakeLists.txt
lib/Dialect/Calyx/Transforms/CalyxHelpers.cpp
lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp

Note that some of these may be more appropriate as static helper functions in lowering utils. However, I've made them public for now. Many of the classes are pretty intertwined (component state, lowering state, ...), so I'm trying to tackle some of the smaller pieces to make this transition easier.

[SCFToCalyx] [StaticLogicToCalyx] Pull out utility functions.

---

include/circt/Dialect/HW/HWSymCache.h
include/circt/Support/Namespace.h
include/circt/Support/SymCache.h
lib/Dialect/HW/Transforms/HWSpecialize.cpp

Continuing from the work in #3137, instead of introducing a new class for generating unique names, it might be better to simply have a way to initialize a namespace from a `SymbolCache`.
To do so, this PR introduces an iterator interface to the base `SymbolCache` class which iterates over pairs of `{mlir::Attribute, mlir::Operation*}`.
Given this interface, it's now possible to range-loop over any given cache and use the values for namespace initialization.

[Support] Add iterator interface to SymbolCache

---

include/circt/Dialect/FIRRTL/NLATable.h
lib/Dialect/FIRRTL/NLATable.cpp

This commit adds utilities to NLATable analysis, 
1. For getting the NLAs that an instance participates in.
2. Remove an NLA from the Module.
3. Remove a set of NLAs from the Module.

[FIRRTL] Add utilities to NLATable analysis. NFC.

---

CMakeLists.txt
cmake/modules/GenVersionFile.cmake

This PR disables version generation by default since it creates unnecessary warnings in out-of-tree builds.

[CMake] Make version generation opt-in

---

include/circt/Dialect/FIRRTL/Passes.h
lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp
test/Dialect/FIRRTL/SFCTests/signal-mappings.fir
test/Dialect/FIRRTL/SFCTests/subcircuit-flow/flow.test
test/Dialect/FIRRTL/SFCTests/subcircuit-flow/inline.json
test/Dialect/FIRRTL/SFCTests/subcircuit-flow/lit.local.cfg
test/Dialect/FIRRTL/SFCTests/subcircuit-flow/main.fir
test/Dialect/FIRRTL/SFCTests/subcircuit-flow/subCircuit.json
test/Dialect/FIRRTL/SFCTests/subcircuit-flow/subcircuit.fir
test/Dialect/FIRRTL/annotations.fir
test/Dialect/FIRRTL/grand-central-signal-mappings.mlir
tools/firtool/firtool.cpp

This is handled with a two-step flow:
* main.fir + subCircuit.json --(firtool)--> (normal output) + sigdrive.json (new)
* subcircuit.fir + sigdrive.json --(firtool)--> (normal output)
The new test in 'subcircuit-flow' demonstrates this in action.
There are many limitations, this is meant to just be enough to
support some specific existing use cases only.
----
Notes:
* Forced input ports now have an additional wire added to distance
the driven value from its uses (at instantiation points).
The goal is to ensure an 'assign' is created between the wire
used elsewhere and the wire bound to the driven port.
The single wire previously created was apparently insufficient.
These wires are now given names and symbols, which may be unneeded.
* Mappings are generated using `module.name` XMR's, which …

[FIRRTL] basic support for subcircuit signal driving flows

---

test/Dialect/FIRRTL/SFCTests/emit-omir.fir
tools/firtool/firtool.cpp

Due some hasty changes when we realized that `MemToRegOfVec` transform
should not lower all memories, we started blackboxing seq mems which
we shouldn't be.  We need to make sure that the `LowerMemory` pass is
gated on the `repl-seq-mem` flag in firtool, which will allow SRAMs to
be lowered to generated memory modules instead of blackboxes.

[firtool] Only blackbox SRAMs when `-repl-seq-mem` is specified

---

docs/Passes.md

When we generate a markdown file, and it is not included in any other
markdown file, the website generator will assume that the MD file should
be a top-level page.  Since the MD files generated for passes are
fragments, we end up with some bad top-level pages and untitled entries
in the sidebar.
see https://circt.llvm.org/docs/HWPasses/ for an example.

Fix website generation for pass documentation

---

include/circt/Dialect/FIRRTL/FIRRTLStructure.td
include/circt/Dialect/FIRRTL/NLATable.h
lib/Dialect/FIRRTL/FIRRTLOps.cpp

This commit adds the following utilities
1. Check if an NLA contains an innerSym reference.
2. Get the NLAs that an InstanceOp participates in.
3. Add an NLA to a Module.

[FIRRTL] Add Utilities to NLA and NLATable. NFC.

---

include/circt/Dialect/FIRRTL/CMakeLists.txt

The attribute defs documentation are generated by and included in the
FIRRTL dialect documentation.  This second  markdown file fragment
becomes a top-level page on the website, which has no title and an
empty box on the sidebar.
See https://circt.llvm.org/docs/Dialects/FIRRTLAttributes/ for the page this is creating.

[FIRRTL] Stop double-generating attribute docs

---

docs/RationaleFIRRTL.md
include/circt/Dialect/FIRRTL/FIRRTLStructure.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/SFCTests/dedup-errors.fir
test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/annotations.fir
test/Dialect/FIRRTL/annotations.mlir
test/Dialect/FIRRTL/dedup.mlir
test/Dialect/FIRRTL/emit-omir.mlir
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/extract-instances.mlir
test/Dialect/FIRRTL/grand-central-taps.mlir
test/Dialect/FIRRTL/grand-central.mlir
test/Dialect/FIRRTL/inject-dut-hierarchy.mlir
test/Dialect/FIRRTL/inliner.mlir
test/Dialect/FIRRTL/lower-memory.mlir
test/Dialect/FIRRTL/lower-types.mlir
test/Dialect/FIRRTL/prefix-modules.mlir
test/Dialect/FIRRTL/print-nla-table.mlir
test/Dialect/FIRRTL/test.mlir

Printing the namepath array as a regular attribute means we have a lot
of  overhead to write out all the `hw.innerRefAttr`s.  This changes the
NLA operation printer to print the namepath array without the name of
the of the attributes.
```mlir
// Before:
firrtl.nla @nla_1 [#hw.innerNameRef<@Foo::@bar>, #hw.innerNameRef<@Bar::@b>]
// After:
firrtl.nla @nla_1 [@Foo::@bar, @Bar::@b]
```
If anyone has any other suggestions for the printed format, I would love to bike-shed on this. We could choose something similar to the annotation target strings: `Foo/bar:Bar/b`

[FIRRTL] Simplify NonLocalAnchor namepath printing

---

include/circt/Dialect/FIRRTL/FIRRTLUtils.h
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/HWRename.fir
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir
test/Dialect/FIRRTL/annotations.mlir
test/Dialect/FIRRTL/grand-central.mlir

Building on #3141, this changes Grand Central (GCT) Views to, during the `AnnotationLowering` pass, add don't touch wire taps on the anything that is marked as a Grand Central XMR.  This effectively unblocks optimizations around the actually tapped thing to enable things like port removal.
Additionally, this incorporates a commit from #3154 to sink constants into the GCT Views mappings file when possible. This PR adds a small change to also remove the symbol on tapped wire (which is now safe because the only possible user of the tap is GCT Views). This has the effect of removing the tap if it becomes unnecessary due to constant propagation.
This closes #3154 as this is a much better approach.
Starting from the following FIRRTL file where we want to tap `w` to an SV interface member called …

[FIRRTL] Change Grand Central Views to use Wire Taps and Sink Constants

---

docs/RationaleFIRRTL.md

In markdown files, we are marking FIRRTL code blocks as Scala code. This
provides decent looking syntax highlighting on github, but it looks
pretty bad when rendered on our webpage.  This commit changes the format
specifier to `firrtl`.  Since hardly any formatter understands FIRRTL
code, this effectively means that there will be no syntax highlighting.
This works well if you have tree sitter FIRRTL and MarkDown grammars
installed.

[FIRRTL] Stop using `scala` for `firrtl` code blocks in markdown

---

include/circt/Dialect/FIRRTL/NLATable.h
lib/Dialect/FIRRTL/NLATable.cpp
lib/Dialect/FIRRTL/Transforms/PrefixModules.cpp

This commit fixes an issue with `PrefixModules` pass when it was not updating the `NLATable` with the new prefixed modules. 
It is critical to keep the `NLATable` analysis updated, when new Modules are added and NLAs are renamed.

[FIRRTL] Use NLATable analysis to update modules in PrefixModules pass.

---

lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp
test/Dialect/FIRRTL/extract-instances.mlir

This commit updates the `ExtractInstances` pass to use the `NLATable` analysis. 
It also removes the updates to `circt.nonlocal` breadcrumbs on the `InstanceOp`. 
The changes to the NLA Utilities are part of another PR: https://github.com/llvm/circt/pull/3196. 
The changes to the NLA verifier, will also be committed separately.

[FIRRTL] Update ExtractInstances pass to use NLATable analysis

---

lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp
test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/annotations-errors.fir
test/Dialect/FIRRTL/annotations.fir
test/Dialect/FIRRTL/annotations.mlir
test/Dialect/FIRRTL/dedup.mlir
test/Dialect/FIRRTL/lower-memory.mlir
test/Dialect/FIRRTL/prefix-modules.mlir

This commit removes the NLA breadcrumbs from the InstanceOps. This is part of the changes to port the passes to use NLATable analysis instead of depending on the circt.nonlocal annotations on the InstanceOps.

[FIRRTL] Remove NLA breadcrumbs from InstanceOps

---

integration_test/Dialect/Handshake/buffer_initial_values.mlir
lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
test/Conversion/HandshakeToFIRRTL/test_buffer.mlir

This patch adds the initial values to the names of the buffer modules to create different modules for different initial values.
If added a new integration test as this bug mainly appears when the generated verilog is simulated.
Fixes #3180

[HandshakeToFIRRTL] Add initial values to buffer module names

---

include/circt/Dialect/FIRRTL/Passes.td
test/Dialect/FIRRTL/SFCTests/emit-omir.fir
test/Dialect/FIRRTL/mem-to-reg-of-vec.mlir
tools/firtool/firtool.cpp

This adds the `firrtl-` prefix to the beginning of the command line
option for this pass, so that we keep our dialect passes namespaced.
I found the use of capital letters in the command line option to be a
unconventional, so I spread it out to the significantly longer
`firrtl-mem-to-reg-of-vec`.  In the future maybe we can think about
renaming this pass.

[FIRRTL] rename `mem-to-regOfVec` to `firrtl-mem-to-reg-of-vec`

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Conversion/FIRRTLToHW/module-hierarchy-file.mlir
test/Dialect/SV/hw-extract-test-code.mlir

This adds "// VCS coverage exclude_file" comment to modules under testbench to
make coverage accurate. The comment is added to extracted modules at ETC and
modules under testbench (ref https://github.com/llvm/circt/pull/3058).

[SVExtractTestCode][LowerToHW] Add coverage exclusion flag to testbench modules

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/SFCTests/data-taps-nlas.fir
test/Dialect/FIRRTL/annotations.mlir
test/Dialect/FIRRTL/grand-central-taps.mlir

Instead of directly referring to module ports or internal signals, this commit changes the GCT data taps pass to create an auxiliary "tap wire" inside the module. The wire is connected such that it "observes" the current value of the port (input or output) or internal signal, and all symbol references generated by GCT are with respect to this wire.
This has two distinct advantages:
1.  It removes a major source of symbols on module ports, which block port optimizations almost entirely.
2.  It offers a "receptacle" for IMConstProp to propagate constants into. This can lead to the tap wire being disconnected from the port if the port is only driven to a constant externally, which allows for the port to be removed.

[FIRRTL] Use tap wires for GCT data taps

---

lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
test/Dialect/SV/hw-memsim.mlir

Memories should be excluded from coverage. This PR adds VCS pragma to exclude 
generated memory modules from coverage at HWMemSimImpl.

[HWMemSimImpl] Exclude generated memory modules from coverage

---

include/circt/Dialect/SV/SVStatements.td
include/circt/Dialect/SV/SVVisitors.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/verilog-basic.mlir
test/Dialect/SV/basic.mlir

Since graph regions don't have explicit output order, we add a region which outputs statements in order but is still a graph region.  This let's macros which might attach to subsequent operations on expansion or other side-effecting code to be properly sequenced.

Add an op to constrain output statements in graph regions

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/Import/FIRParserAsserts.cpp
lib/Dialect/SV/SVOps.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/SV/canonicalization.mlir

Generally, don't invert guarding `when` conditions for Cover's.
This occurs in two places that this change addresses:
1) Guarding `when` for cover is not inverted when parsing printf-in-when into verification op:
```
when foo:
printf("cover:*",...)
```
Means 'foo' is the predicate for the coverage,
don't invert it like with other verif ops.
2) For concurrent verif ops, we use `enable -> pred` as predicate (`assert(!enable | pred)`).  For CoverOp's, instead combine enable and pred (`enable & pred`).
---
These changes can be observed in the tests:
parse-basic.fir: Demonstrates (1)
lower-to-hw.mlir: Demonstrates (2)

[FIRRTL] fix cover predicate inversion

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp

The `Dedup` pass keeps the `NLATable` in sync with any changes to Module names and NLA updates.
Hence the NLATable analysis is preserved by the pass.

[FIRRTL] Dedup pass preserves the NLATable analysis. NFC.

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Fixes #2514.
In general, these range checks will work at larger-than-needed `commonWidth`, FWIW, but that's unnecessary/overkill for normal case.  Address the zero-width on both sides issue (`commonWidth==0`) by ensuring we compare at 1-bit or wider since various AP(S)Int comparisons don't work nicely with zero-bits (and our getMin/getMax return 1-bit values).
(This also removes one need for `orSelf` variants of the extension, as we'd be requesting an extension of the min/max 1-bit values to the common zero width.)
Add exhaustive test for this being folded as expected and not crashing.

[FIRRTL] Fix folds of zero-width values with zero-width constants

---

include/circt/Support/APInt.h
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Support/APInt.cpp

APInt's extending and truncating functions have been relaxed to allow
the desired width to be the same as the input width.  Since this change
the following functions have been deprecated and can be replaced with
their simpler counterparts:
```
truncOrSelf -> trunc
zextOrSelf -> zext
sextOrSelf -> sext
```
See https://reviews.llvm.org/D125556 for relaxing the restrictions.
See https://reviews.llvm.org/D125558 for the deprecation.
Fixes #3201.

[FIRRTL] Fix uses of deprecated APInt functions

---

lib/Dialect/FIRRTL/Transforms/SFCCompat.cpp

When the a RegResetOp is driven by an invalid value, it is replaced
with a RegOp and the original op erased. This has been the case for a
while. However, recently, new code was added below this, which works
with a reference to the original op. This could lead to a
use-after-free, so in the case a replacement happened, skip over the
newly added code.
I wasn't able to quickly write a small reproducer of this behavior,
but it is quite evident when running the existing sfc-compat.mlir
tests that cover this codepath under valgrind.
Before:
==2456108== ERROR SUMMARY: 54 errors from 7 contexts (suppressed: 0 from 0)
After:
==2466205== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

[FIRRTL] Fix use-after-free in SFCCompat register handling.

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-basic.fir

We recently removed usages of the deprecated function `sextOrSelf`.
This function allowed you to extend an APInt to a smaller width than it
currently is, becoming a noop.  The replacement function does not allow
doing this, and asserts.  During the cleanup I missed that we had to
guard this usage of `sext` to check the initial bitwidth before
attempting to sign-extend.
See: https://github.com/llvm/circt/pull/3202

[FIRParser] Fix bug extending an APInt to a smaller width

---

include/circt/Dialect/HW/HWAttributes.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/HW/HWAttributes.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Dialect/HW/parameters.mlir

Adds a `ParamExprAttr` opcode for string concatenation. Has a
simplification which merges adjacent strings. Includes ExportVerilog
support.

[HW] [ExportVerilog] Add parameter concat expression

---

lib/Bindings/Python/circt/dialects/_hw_ops_ext.py
lib/Bindings/Python/circt/dialects/_msft_ops_ext.py
test/Dialect/FIRRTL/canonicalization.mlir
test/Dialect/FIRRTL/imconstprop.mlir
test/Dialect/FIRRTL/prefix-modules.mlir

* https://reviews.llvm.org/D124717 changed optional attribute handling in the Python API
* https://reviews.llvm.org/D125604 catches misspelled FileCheck directives

[llvm] bump

---

lib/Conversion/AffineToStaticLogic/AffineToStaticLogic.cpp
test/Conversion/AffineToStaticLogic/loops.mlir

The loop bound computation previously relied on methods that attempted
to retrieve constant bounds, which would assert if the bounds were
non-constant (i.e. AffineMaps). This switches to use the same upstream
helpers that are used when lowering Affine loops to SCF loops, which
generate constant or dynamic Values using the Arithmetic dialect.
This fixes https://github.com/llvm/circt/issues/3127.

[AffineToStaticLogic] Generalize loop bound computation.

---

include/circt/Dialect/Calyx/CalyxPrimitives.td
lib/Conversion/CalyxToHW/CalyxToHW.cpp
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Conversion/StaticLogicToCalyx/StaticLogicToCalyx.cpp
lib/Dialect/Calyx/CalyxOps.cpp
lib/Dialect/Calyx/Export/CalyxEmitter.cpp
test/Conversion/SCFToCalyx/convert_simple.mlir
test/Dialect/Calyx/emit.mlir
test/Dialect/Calyx/export-errors.mlir
test/Dialect/Calyx/round-trip.mlir

Adds support both at the front- and back-end level to ensure that all signed `arith` division/modulo operators work end-to-end.
Notably, this also changes the semantics of the `DivLibPipe` operator in that it no longer provides both a quotient and remainder result. This change aligns the Calyx operators to better fit within an MLIR/CIRCT up/downstream context (`arith` and `comb` operators), but breaks compatibility with the div primitive in the native calyx compiler. A note has been added in the Calyx emitter to indicate of this.
Opted not to add support in StaticLogicToCalyx for the new operations since i assume the existing code duplication will be cleaned up in the near future, with `SCFToCalyx` taking precedence for the shared logic.

[SCFToCalyx, Calyx, CalyxToHW] Add support for signed div and rem

---

lib/Dialect/Calyx/CalyxOps.cpp

This allows embedding `calyx.enable` operations into regions defined by operations not in the Calyx dialect.
Discussion in https://github.com/llvm/circt/pull/3138.

[Calyx] Relax `calyx.enable` verifier

---

.github/workflows/buildAndTest.yml
utils/build-llvm.sh

Code compiled with Clang cannot be linked with GCC due to incompatibilities related to lambda closure capture lists.
This patch builds and caches LLVM with Clang to be used with the Clang Release build and with GCC to be used with the GCC Debug build of CIRCT.
The ABI issue and a potential fix is being tracked here: https://github.com/itanium-cxx-abi/cxx-abi/issues/141

[CI] Build and cache seprate Clang and GCC builds of LLVM

---

include/circt/Dialect/Calyx/CalyxLoweringUtils.h
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Conversion/StaticLogicToCalyx/StaticLogicToCalyx.cpp
lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp

This provides ProgramLoweringStateInterface and ComponentLoweringStateInterface to pull the heavy lifting. 
The (1) cyclic dependency between the component and program states and (2) generalized loop interface being used in `Scheduleable` has made this quite a cumbersome task.
Also pulls out PartialLoweringPattern, ModuleOpConversion classes.

[SCFToCalyx] [StaticLogicToCalyx] Continue separation of the conversions.

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp

As noted in https://github.com/llvm/circt/pull/3202, there are a few
APInt functions we can use which simplify the code and better convey the
intent.  Thanks Will Dietz!

[FIRRTL] Clean up APInt usage in some folds

---

lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp
test/Dialect/FIRRTL/lower-memory.mlir

This commit fixes an issue with lowering unmasked RW memories.
If a memory has a single bit mask, then the mask bit can be removed and combined with the write enable.
But if the memory is a ReadWrite memory, then the enable port is used for both read and write enable. For such a ReadWrite memory we cannot combine the write mask with the enable, it has to be combined with the Write Mode.
Such that if the mask bit is disabled, then the write should be disabled.

[FIRRTL] Fix bug in unmasked RW memory lowering

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp

This commit deletes the code from GCT Taps pass, that was updating the NLA breadcrumbs. 
This is no longer required because the NLATable analysis replaced the breadcrumbs..

[FIRRTL] Remove Update of breadcrumbs from GCT Taps Pass. NFC.

---

include/circt/Dialect/Calyx/CalyxLoweringUtils.h
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Conversion/StaticLogicToCalyx/StaticLogicToCalyx.cpp
lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp

As pointed out by @mortbopet [here](https://github.com/llvm/circt/pull/3263#issuecomment-1145625237), we can place the heavy loading on a function rather than the entire class. This reduces some template bloating.
Continued work in #2988.

[SCFToCalyx] [StaticLogicToCalyx] Reduce templating in interfaces.

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp
test/Dialect/FIRRTL/canonicalization.mlir
test/firtool/memory.fir
test/firtool/name-preservation.fir

When a wire has a single write and the write dominates all reads, we can convert the wire to a node.  Wires and nodes are identically treated, except the connect indirection, so we can convert to a more convenient form.
This also strengthens constant propagation through nodes.

[FIRRTL] Cannonicalize wires to nodes

---

include/circt/Dialect/Calyx/CalyxLoweringUtils.h
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Conversion/StaticLogicToCalyx/StaticLogicToCalyx.cpp
lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp

This is pretty straightforward - adds an additional interface for scheduling information so that block-related scheduling may be shared across the two conversions.
Continued work on #2988.

[SCFToCalyx] [StaticLogicToCalyx] Share more passes.

---

lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
lib/Dialect/Handshake/HandshakeOps.cpp
test/Conversion/StandardToHandshake/test_extmemory.mlir
test/Dialect/Handshake/errors.mlir

This PR ensures that all memrefs are connected to memory by initializing the `memRefOps` map with an empty vector for all block arguments. The map is later on used to produce `ExternalMemrefOps`. 
Fixes #3256

[StandardToHandshake] Always emit `extmemory`, even when unused

---

frontends/PyCDE/src/pycde/__init__.py
frontends/PyCDE/src/pycde/constructs.py
frontends/PyCDE/src/pycde/support.py
frontends/PyCDE/src/pycde/value.py

The `Value` constructor will try its best to infer a type. Basically
works only on lists, but that's worth it given how much lists are used.

[PyCDE] Type inference

---

lib/Dialect/FIRRTL/Import/FIRParserAsserts.cpp
test/Dialect/FIRRTL/parse-basic.fir

The assertion parsing framework would parse the label from
`cover:my-label:` as the message.  This was a mistake in part of the
logic to handle missing labels in such cases as `cover:my message`,
where it would always use label as a message if the message was empty.
Now, it uses the colon to disambiguate the two cases.
As a follow up we should check if it is actually legal to have a missing
label.

[FIRRTL] Properly parse printf assertions with no message

---

frontends/PyCDE/src/pycde/support.py
frontends/PyCDE/src/pycde/value.py
frontends/PyCDE/test/muxing.py
lib/Bindings/Python/circt/dialects/_hw_ops_ext.py

- Add `cycles` argument to `reg` to add `cycles` registers of delay.
- Treat `tuple`s just like `list`s.
- Slice `ArrayValue`s.
- Get bit from `BitVectorValue` with `Value` in addition to python int or slices.
- Adds `slice` method to get constant-sized slices.
- Ignores `functools.py` when finding the user location.

[PyCDE] Syntactic sugar to support new subdesign

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/Comb/canonicalization.mlir

Currently sv.namehint is not propagate well at comb canonicalizer. To improve the situation, this PR replaces uses of `PatternRewriter::replaceOp` with its wrapper `replaceOpAndCopyName` to propagate sv.namehint attributes more aggressively.

[CombFolds] Propagate sv.namehint attribute more aggressively

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

This PR makes FIRRTL canonicalizers propagate "name" attribute when we replace operations. 
Currently, MLIR doesn't have good mechanism to propagate optional attributes easily, I added wrappers for `PatternRewriter::replaceOp, replaceOpWithNewOp`.

[FIRRTLFolds] Propagate name attributes more aggresively

---

.github/workflows/buildAndTest.yml

Since we are now compiling separate LLVMs for GCC and clang, we should parallelize the CIRCT builds as well. Ditching the prebuild-and-cache-llvm step since that broke and nobody noticed.

[CI] Run the test builds in parallel

---

include/circt/Dialect/FIRRTL/FIRRTLAttributes.td
include/circt/Dialect/HW/HWAttributes.td
include/circt/Dialect/SV/SVAttributes.td

This PR aims to improve the generated documentation for some attribute
definitions and constraints. Some missing tablegen fields create empty
markdown headings with no content.  The focus of this change is just
getting anything in these fields, without much focus on creating high
quality content. Somewhat confusingly, the `summary` field of attribute
constraints is used as the "name" of the constraint in many locations.
See https://circt.llvm.org/docs/Dialects/FIRRTL/#attribute-constraint-definition for what the problem looks like.

Improve documentation of attributes

---

test/Dialect/FIRRTL/dedup.mlir

This just adds another test to make sure that we are recursively merging
operations with regions. I'm adding this test to make sure that this
doesn't regress from future refactorings.

[FIRRTL][Dedup] Add test for merging when blocks

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/max-terms.mlir

This is separated from https://github.com/llvm/circt/pull/3292.
If it is necessary to spill an expression at PrepareForEmission and the expression has
a namehint,  it would be better to use the name.

[PrepareForEmission] Use namehint for spilled expression

---

include/circt/Support/LoweringOptions.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Support/LoweringOptions.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

Unfortunately spyglass infers bitwidth of sub expression incorrectly even when they are not toplevel. This PR will surpass the lint warnings.  
This revert https://github.com/llvm/circt/pull/3094 and adds explicit bitcast for every sub expression when `explicitBitcastAddMul` option is true.

[ExportVerilog] Add explicit bitcast for sub expressions 

---

tools/firtool/firtool.cpp

Middle-end passes might introduce operations with interesting names so this
commit adds another instance of DropNamesPass so that we can clean up them.

[firtool] Rerun DropNamesPass after running middle-end passes

---

docs/VerilogGeneration.md

Old link was lib/Translation/... now it's lib/Conversion/...

[docs] NFC - Fix broken link to ExportVerilog.cpp

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

This commit fixes an issue with lowering unmasked RW memories.
If a memory has a single bit mask, then the mask bit can be removed and
combined with the write enable. But if the memory is a ReadWrite memory,
then the enable port is used for both read and write enable. For such a
ReadWrite memory we cannot combine the write mask with the enable, it has
to be combined with the Write Mode. This ensures that if the mask bit is
disabled, then the write should be disabled, but not the read.

[LowerToHW] Fix bug with unmasked RW memory lowering

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/grand-central-taps.mlir

This commit updates the GrandCentralTaps to handle `HierPathOp` ending in modules.
TODO:

[FIRRTL] Update GCT Taps to handle HierPathOp ending in Module

---

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
test/Dialect/FIRRTL/inliner.mlir

This commit updates the `ModuleInliner` to not rely on `circt.nonlocal` breadcrumbs and `NLATable` analysis.
`ModuleInliner` uses a `MutableNLA` data structure to keep track of the updates that are required on the `HierPathOp`s without actually updating the `HierPathOp` until the end of the pass.
So, the algorithm has an invalid IR, while the pass is running, and the IR is updated only at the end.
This kind of algorithm doesn't work well with the `NLATable`, since the analysis expects the IR to be valid when the `NLATable` is queried. 
For example if we query the `NLATable` to get the `HierPathOp`s that an `InstanceOp` participates in, `NLATable` will lookup the `namepath` of a `HierPathOp`, but this does not work if the `HierPathOp` is invalid!
So, this PR updates the `ModuleInliner` to …

[FIRRTL] Fix ModuleInliner to not rely on nonlocal BreadCrumbs

---

include/circt/Dialect/MSFT/ExportTcl.h
include/circt/Dialect/MSFT/MSFTOpInterfaces.h
include/circt/Dialect/MSFT/MSFTOpInterfaces.td
include/circt/Dialect/MSFT/MSFTPDOps.td
lib/Dialect/MSFT/ExportQuartusTcl.cpp
lib/Dialect/MSFT/MSFTPasses.cpp
test/Dialect/MSFT/dynamic_instance.mlir

Some designs instantiate the same module more than once. Per-instance
data should be different, so we need a way to specify an "instance" of
the top level.

[MSFT] Support for multiple top levels of same module

---

frontends/PyCDE/src/pycde/value.py

Barring that I'm missing something obvious here, i don't see a reason for not allowing multiple or no result values from operations. One could argue why go through the trouble of wrapping return values if an op doesn't have any. However, `wrap_opviews_with_values` is doing double duty of both wrapping op results values, but also overriding the constructor of op classes such that construction is forwarded through their `create` methods. This cleans up the API in not having to say `OpClass.create(...)` for some (unwrapped) operations and `OpClass(...)`for wrapped operations.

[PyCDE] Allow multiple or no results from op create methods

---

include/circt/Dialect/SV/CMakeLists.txt
include/circt/Dialect/SV/SVAttributes.h
include/circt/Dialect/SV/SVTypeDecl.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/SV/SVAttributes.cpp
lib/Dialect/SV/SVOps.cpp

`StructAttr` is being deprecated, replace it with `AttrDef` in `SVTypeDecl`. 
This change updates the `ModportStruct` type, and its members.

[SV] Replace StructAttrs with AttrDefs. NFC.

---

lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp
test/Dialect/FIRRTL/grand-central-signal-mappings.mlir

Update GrandCentral SignalMapping to handle HierPathOp ending on Module.
This commit just removes the assert, no special handling logic is required.

[FIRRTL] Update GrandCentral SignalMapping to handle HierPathOp ending on Module

---

lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
test/Dialect/FIRRTL/emit-omir.mlir

Change the EmitOMIR pass to remove no hierpath ops.  It cannot safely do
this without computing the uses of a hierpath.  While the pass could be
updated to do this, it would be cleaner to handle hierpath removal with
a common DCE pass.
This change is made to support new NLA-style paths.  With this new
style, multiple NLAs may share the same hierpath ending at a module and
it is thereby unsafe for NLAs to decide to delete a hierpath without
checking for users.
Remove internal NLA breadcrumbs that are unnecessarily generated in
EmitOMIR.  These are entirely unused by internal EmitOMIR analyses and
serve no purpose other than to be removed by the pass later.

[FIRRTL] Update EmitOMIR for New NLA Style

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/dedup.mlir

This change updates the dedup pass to handle non-local annotations that
use a hierarchical path which ends at the parent module instead of the
annotation target.  The main change needed is to track a list of
operations which reference the path operation, as multiple operations
can now share a single path.  A follow up commit will change dedup to
produce the new style of path when it changes a local annotation into a
non-local one.

[FIRRTL] Update Dedup to handle HierPathOp ending on Module

---

include/circt/Dialect/SV/SVAttributes.td
include/circt/Dialect/SV/SVInOutOps.td
include/circt/Dialect/Seq/Seq.td
lib/Conversion/CalyxToHW/CalyxToHW.cpp
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/SV/SVOps.cpp
lib/Dialect/Seq/SeqOps.cpp
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir
test/Dialect/SV/basic.mlir
test/Dialect/Seq/compreg.mlir

Verilog attributes (SV 2017, section 5.12) support for regs and wires. Just like comments on modules, we're adding this support only where we need it since we'll have to reason about it in transformations.

[ExportVerilog] Verilog attribute support for sv.reg and sv.wire

---

lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp
test/Dialect/FIRRTL/inject-dut-hierarchy.mlir

Update the InjectDUTHierarchy pass to work for both old-style
NLAs (where an NLA that targets a port/component ends in a
hw::InnerRefAttr) and new-style NLAs (where an NLA that targets a
port/component ends in a module/FlatSymbolRefAttr).

[FIRRTL] Update InjectDUTHierarchy for new NLAs

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/dedup.mlir

This is a PR to another open PR that depends on another PR ;).  Once #3309 is merged into `main`, I will merge this into #3300.
This commit changes the hierarchical paths produced by dedup to end at the module.  It is able to re-use the `hierpaths` created across all merged operations in a module.

[FIRRTL] add dedup support for "Make all NLAs end in a Modules"

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

This commit fixes a (potential) bug that namehints of variadic ops are copied to all lowered sub expressions. 
For example, 
```mlir
hw.module @namehint_variadic(%a: i3) -> (b: i3) {
%0 = comb.add %a, %a, %a, %a, %a { sv.namehint = "bar" } : i3
hw.output %0 : i3
}
```
`circt-opt -export-verilog`  currently transforms  IR above into:
```mlir
hw.module @namehint_variadic(%a: i3) -> (b: i3) {
%0 = comb.add %a, %a {sv.namehint = "bar"} : i3
%1 = comb.add %a, %a {sv.namehint = "bar"} : i3
%2 = comb.add %a, %1 {sv.namehint = "bar"} : i3
%3 = comb.add %0, %2 {sv.namehint = "bar"} : i3
hw.output %3 : i3
}
```
Copying sv.namehint to all sub expression sounds weird even though it doesn't cause any bug (since namehints created here are not used at all). With this PR, the IR is transformed to: …

[PrepareForEmission] Don't copy namehint to all sub expressions

---

include/circt/Dialect/FIRRTL/FIRRTLOps.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/FIRRTLFolds.cpp

Add a `BackedgeBuilder` to `FIRRTLLowering` which can be used to directly materialize values that violate def-before-use ordering. To simplify usage, a new `setBackedgeLowering` function creates a backedge with the desired type and memorizes it as the lowering for the original value. A later call to `setLowering` for the original value will resolve the backedge.
As a first use of the backedge builder, materialize the input values for instances directly through a backedge if the port is trivially assigned by a single `StrictConnectOp`. This does away with temporary wires in most cases and is a useful preparation for handling non-FIRRTL types during lowering.

[LowerToHW] Add BackedgeBuilder, directly materialize inst inputs

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

A situation can occur where a named declaration has its name re-named,
in which case the hw.verilogName is used to indicate the new
name. However, it is possible for collectNames to see a certain
expression that it wants to emit into a temporary, and decides to give
it a generated name that collides with another declaration's generated
hw.verilogName. This can happen if the expression is visited before
the declaration, and results in the declaration receiving a different
unique name, which doesn't match the assigned hw.verilogName.
This isn't a huge problem for local emission, but non-local things
like binds have to be able to trust the hw.verilogName attribute
holds the final name.
The change in this patch splits collectNames to loop over the IR
twice. First collecting names from …

[ExportVerilog] Collect names from declarations before expressions.

---

include/circt-c/Dialect/SV.h
integration_test/Bindings/Python/dialects/seq.py
integration_test/Bindings/Python/dialects/sv.py
lib/Bindings/Python/CIRCTModule.cpp
lib/Bindings/Python/CMakeLists.txt
lib/Bindings/Python/DialectModules.h
lib/Bindings/Python/SVModule.cpp
lib/Bindings/Python/circt/dialects/_seq_ops_ext.py
lib/Bindings/Python/circt/dialects/_sv_ops_ext.py
lib/Bindings/Python/circt/dialects/sv.py
lib/CAPI/Dialect/SV.cpp
lib/Dialect/Seq/SeqOps.cpp

Lots of boilerplate which should _really_ be autogenerated. Added support for SystemVerilog attributes to the python bindings for the SV and Seq dialects.

[Python] Add support for SV attributes

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
lib/Dialect/FIRRTL/CHIRRTLDialect.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp
lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp
lib/Dialect/FIRRTL/Transforms/MemToRegOfVec.cpp
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/SFCTests/async-reset.fir
test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/SFCTests/remove-reset.fir
test/Dialect/FIRRTL/annotations.fir
test/Dialect/FIRRTL/drop-name.mlir
test/Dialect/FIRRTL/extract-instances-inject-dut-hier.mlir
test/Dialect/FIRRTL/imconstprop.mlir
test/Dialect/FIRRTL/inliner.mlir
test/Dialect/FIRRTL/lower-chirrtl.mlir
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/parse-locations.fir
test/Dialect/FIRRTL/parse-name-preservation.fir
test/circt-reduce/memory-stubber.mlir
test/firtool/firtool.fir
test/firtool/prefixMemory.fir

This commit changes a default value of namekind from interesting name to droppable name.
This is more comfortable in the situation where we want to create a dummy unnamed wire with for example
`builder.create<WireOp>(result.type())`. Previously a dummy wire created by this had `interesting_name` because default namekind was `interesting`. This commit also changes IR representation.

[FIRRTL] Make droppable_name default

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/annotations.fir

These require adding a symbol to the instance,
if one isn't otherwise already warranted.
Fixes #3340.
This was addressed for memory ports in #2792.

[FIRParser] Handle annotations on instance ports properly.

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp

After erasing the operation, be sure to skip to next iteration.
Otherwise, the code below will try to use the free'd value.
(e.g., L636's invocation of getNumPorts)
Caught by sanitizer.

[FIRRTL] GrandCentralTaps: Fix use-after-free

---

lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp
test/Dialect/FIRRTL/lower-memory.mlir

This commit fixes the `namepath` of a `HierPathOp` that is used by a non-local 
annotation on the `MemOp` being lowered.
The non-local annotation is now applied on the `InstanceOp` for the lowered
`firrtl.memmodule`. 
(An alternate approach could be to apply the non-local annotation on the 
`firrtl.memmodule` instead of the instance.)
Update the hierarchy to end on the wrapper memory module, inside which
the `firrtl.memmodule` is being instantiated. This might require adding
the `InnerSym` on the `InstanceOp` that instantiates the wrapper memory
module.
This ensures that the generated `HierPathOp` maintains the new format of 
ending on a module.

[FIRRTL] Update LowerMemory to handle HierPathOp ending in Module

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/dedup.mlir

For some designs, the DedupPass would cause a segmentation fault, since
it removes elements from the `instanceGraph` while iterating over it.
Using `make_early_inc_range` makes this mutate-while-iterate operation
safe.
Fixes #3360.

[FIRRTL] Fix mutate-while-iterate bug in Dedup

---

docs/FIRRTLAnnotations.md
docs/RationaleComb.md
docs/RationaleHW.md

In addition to these changes, I noticed that the two pictures in the folded-vs-unfolded-modules table (at the bottom of [this section](https://circt.llvm.org/docs/FIRRTLAnnotations/#targets)) aren't displaying on the website. I'm not completely sure what the right fix is for that. The diagrams can be found here:
https://circt.llvm.org/includes/img/firrtl-folded-module.png
https://circt.llvm.org/includes/img/firrtl-unfolded-module.png
However, the page is trying to find them at these URLs:
https://circt.llvm.org/docs/FIRRTLAnnotations/includes/img/firrtl-folded-module.png
https://circt.llvm.org/docs/FIRRTLAnnotations/includes/img/firrtl-unfolded-module.png
The images are rendered properly when opening the markdown document in GitHub. I'm not totally sure how the website is set up, but if …

[Docs] Fix a few typos

---

lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/annotations.fir
test/Dialect/FIRRTL/annotations.mlir
test/Dialect/FIRRTL/dedup.mlir
test/Dialect/FIRRTL/print-nla-table.mlir
test/Dialect/FIRRTL/test.mlir

This is the final piece of work towards making annotations not block
optimizations.  This PR switches annotation creation to stop attaching
symbols to non-local annotation targets. As much as possible, passes
have already been updated to handle the new style of HierPath used for
non-local annotations.

[FIRRTL] Make all NLAs end in a Module

---

lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/annotations.fir
test/Dialect/FIRRTL/annotations.mlir
test/Dialect/FIRRTL/dedup.mlir
test/Dialect/FIRRTL/lower-types.mlir
test/Dialect/FIRRTL/print-nla-table.mlir
test/Dialect/FIRRTL/test.mlir

Fix a bug in LowerTypes where it would only update hierarchical paths
that are involved in a non-local annotation (NLAs).  This is done in
preparation for more widespread use of hierarchical paths (e.g., by
sv::VerbatimOp) and in preparation for enabling hierarchical paths to
end at the module and not on the final operation.
It follows that this changes the lowering for a hierarchical path
targeting a component/port to generate one new hierarchical path _for
every_ ground type regardless of whether or not the hierarchical path is
used by a non-local annotation.  Previously, new hierarchical paths
would only be generated when used by non-local annotations.
This works by simplifying the way that annotations are updated in
LowerTypes.  Previously, this would update hierarchical paths when …

[FIRRTL] Fix LowerTypes for non-NLA hierpaths

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/PortDelete.fir
test/Dialect/FIRRTL/annotations.mlir

Modify both Grand Central (GCT) Views and Taps annotation lowering to
not add DontTouchAnnotations (inner symbols) to anything that is tapped.
This enables anything that is viewed/tapped to no longer block
optimizations, e.g., constant folding.
Note: I believe this is entirely safe to merge on its own as https://github.com/llvm/circt/commit/d7366a63c30cc436536198b2ac874bbc1e50d4eb makes it so that anything with an Annotation will not get deleted. I.e., adding the `DontTouchAnnotation` here is completely unnecessary.

[FIRRTL] Stop Adding DontTouch to GCT Views/Taps

---

lib/Dialect/FIRRTL/CHIRRTLDialect.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp

This fixes double-space emission after namekind.
```
circuit top:
module top:
input in: UInt<1>
node a = in
```
```mlir
firrtl.module @top(in %in: !firrtl.uint<1>) {
%a = firrtl.node interesting_name %in  : !firrtl.uint<1>
}
```
There are still double-space after `%in` but this is different issue.

[FIRRTL] Fix double spaces after NameKind printer, NFC

---

include/circt/Conversion/StandardToHandshake.h
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp

This PR exposes a missing piece of the lowering step from standard to handshake for reuse.

[StandardToHandshake] Expose `removeBasicBlocks`

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/IMDCE.cpp
lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/imdce.mlir
test/firtool/chirrtl.fir
test/firtool/firtool.fir
test/firtool/memory.fir
test/firtool/memoryMetadata.fir
tools/firtool/firtool.cpp

This pass performs inter-module liveness anaysis and delete dead code
aggressively. A value is considered as alive if it is connected to a port
of public modules or a value with a symbol. We first populate alive values
into a set, and then propagate the liveness by looking at their dataflow.
The framework is almost same as IMCP except that lattice has two states 
(`knownAlive`, `assumedDead`) and direction of propagation is opposite.

[FIRRTL] Add inter-module DCE

---

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
test/Dialect/FIRRTL/inliner.mlir

This commit filters the `HierPathOp`s that participate in an instance based on where it is being inlined at.
If an `InstanceOp`  `@InlinedMod::@inst1` is being inlined to replace InstanceOp `@ParentMod::@inst2`, then only the `HierPathOps` that participate in both `@inst1` and `@inst2` are valid after inlining. 
If a `HierPathOp` begins at `@InlinedMod::@inst1`, then it implicitly participates at all places, where `@InelinedMod` is instantiated.   
This commit fixes a crash with the `ModuleInliner`, whenever an `InnerRef` is renamed without checking if it occurs in the current path. This triggers an assert when the `InnerRef` is renamed twice.

[FIRRTL][ModuleInliner] Check if nla in current path before renaming.

---

lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp

Don't create entries while reading from the map (`map[key2] = map[key1]`),
as sometimes this requires the map to grow which invalidates pointers to entries.
Workaround by ensuring (possibly new) entries exist before copying the vectors over.
Found with help of Address Sanitizer.

ExtractInstances: fix memory safety issue re:DenseMap

---

include/circt/Dialect/FSM/FSMOps.td
lib/Dialect/FSM/FSMOps.cpp
test/Dialect/FSM/basics.mlir
test/Dialect/FSM/errors.mlir
test/Dialect/FSM/print-graph.mlir

There is currently no rationale for explicitly annotating the type that states (a state register) should be inferred as for a machine op. Annotating it upon constructing the machine op is therefore just an extra burden on the front-end, and may also be a premature constraint.
As i see it, default behaviour should just be to infer a state type via. e.g. ceil_log2(# states) when lowering to hardware. If some other behaviour is needed, then this should be lowering specific.

[FSM] Remove statetype from MachineOp

---

frontends/PyCDE/src/pycde/module.py
frontends/PyCDE/src/pycde/system.py

This is a step on the way to untangling logic in module.py to be specific to `MSFTModuleOp`.
Classes can now supply callbacks for generation and creation, which allows for creating, generating modules that aren't necessarily  `MSFTModule(Extern)Op`s.
This commit will make a bit more sense through a later PR which adds support for FSM `MachineOp`s. This support is achieved solely through setting the new `create_cb,generator_cb` with no other changes required.

[PyCDE] Make module creation, generation generic

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/HWRename.fir
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir
test/Dialect/FIRRTL/grand-central.mlir

Modify the Grand Central (GCT) Views pass to generate SV
Verbatim-encoded XMRs that are as short as possible.  Do this with a
naive lowest-common ancestor (LCA) computation the prunes the XMR path
to start at the GCT View parent module (the module where the mapping
module containing the XMRs is instantiated).
Previously, the full non-local annotation (NLA) hierarchical path would
be blindly used under the assumption that this path was what the user
wanted.  This was problematic as the Chisel API will always generate an
absolute path starting from the FIRRTL circuit's main module instead of
a path starting from where the GCT API is used.

[FIRRTL] Use Minimal XMRs in GCT Views

---

frontends/PyCDE/src/pycde/ndarray.py
frontends/PyCDE/test/test_ndarray.py

This is required to match systemverilog semantics.
As an example, previously, the following:
```python
m = NDArray((3, 3), dtype=types.i32)
for i in range(3):
for j in range(3):
m[i][j] = types.i32(i * 3 + j)
```
would emit:
```
assign matrix_wire = {
{{{32'h0}, {32'h1}, {32'h2}}},
{{{32'h3}, {32'h4}, {32'h5}}}, 
{{{32'h6}, {32'h7}, {32'h8}}}
};
```
where expected behaviour is instead:
```
assign matrix_wire = {
{{{32'h8}, {32'h7}, {32'h6}}}, 
{{{32'h5}, {32'h4}, {32'h3}}}, 
{{{32'h2}, {32'h1}, {32'h0}}}};
```

[PyCDE] Flip NDArray before conversion

---

lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp

This is a follow-up to https://github.com/llvm/circt/pull/3344. Interesting names should be only created by parsers.

[FIRRTL] Set droppable names to temporary wires

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h
include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
include/circt/Dialect/FIRRTL/FIRRTLStructure.td
lib/Dialect/FIRRTL/CMakeLists.txt
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/InnerSymbolTable.cpp

InnerRef's are expensive to verify presently, as the InnerSymbol
portion requires walking the target operation (FModuleLike).
HierPathOps are chains of these, and so were especially
problematic in this regard.
This is a similar problem to verifying Symbol (SymbolTable) users,
and is solved in a similar way.
The primary components of the new approach:
**1. Drive verification from the top of InnerRef resolution scope**
Only walk the relevant IR once, parallelizing where makes sense.
**2. Introduce an interface for verifying InnerRef's**
Operations using InnerRef's can implement the interface
to opt-in to this new verification.
For (1), a new trait "InnerRefNamespace" is added to mark Operations
in which InnerRef's are resolved.  For now this is only added to CircuitOp.
For (2), introduce …

[FIRRTL] rework innerref verification, starting with HierPathOp.

---

lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
test/Dialect/FIRRTL/emit-omir.mlir

Restore behavior for deleting the HierPath's added in this pass.
They're known to be dead and sometimes are invalid, causing
breakage during circuit verification.
While we cannot delete incoming HierPath's attached to operations in
input IR without a more careful analysis of all possible users, any NLA
explicitly created in this pass can be reasoned about and removed at the
end for cleaner (and valid) IR.
Fixes assertion failure on a real design.
The invalid NLA encountered is when the target is in the root module,
and so we end up making a one-element (InnerRef) NLA.

[FIRRTL] EmitOMIR: Drop temporary HierPath's that may be invalid

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp

We modify the instance graph as dedup runs and have had some issues with
iterator invalidation. This change copies the module list into a
separate array so we don't have to worry about instance graph updates.
This is not the most efficient solution and in the future we should find
something better.  See https://github.com/llvm/circt/issues/3387 for
more information.

[FIRRTL][Dedup] Pre-calculate the post-order of modules

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/SFCTests/data-taps-nlas.fir
test/Dialect/FIRRTL/grand-central-taps.mlir

Change the Grand Central (GCT) Data/Mem Taps pass to use relative XMRs
for taps that involve non-local annotations (NLAs).  Previously, NLA
paths were used as-is and did not factor into existing XMR minimization
code.  Change this by adding NLA path information to the existing
InstanceOp array used by minimization code.
This is done to fix issues where a user creates a Data/Mem Tap at a
specific point in the hierarchy and they wind up with an XMR that goes
_above_ this point in the design.  This creates problems for designs
that expect the XMR to be compartmentalized, but where the Chisel API
produces NLA paths that are absolute.

[FIRRTL] Use relative XMRs in GCT Data/Mem Taps

---

frontends/PyCDE/src/CMakeLists.txt
frontends/PyCDE/src/pycde/testing.py
frontends/PyCDE/test/muxing.py
frontends/PyCDE/test/pycde_values.py
frontends/PyCDE/test/syntactic_sugar.py
frontends/PyCDE/test/test_ndarray.py
frontends/PyCDE/test/test_ndarray_errors.py

Tests can now use the `@testmodule` to reduce boilerplate such as system instantiation, generation, and printing.
In case of wrapping a function, `@testmodule` accepts kwargs which are passed to the function as arguments.
Also reorders some checks to come before the code-under-test, as opposed to after, in an attempt to align test case style with the remainder of CIRCT.

[PyCDE] Add `@testmodule` to reduce test boilerplate

---

include/circt/Dialect/FIRRTL/FIRRTLOps.h
include/circt/Dialect/FIRRTL/NLATable.h
include/circt/Dialect/FIRRTL/Namespace.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp
lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp

Add a helper utility to get the `inner_sym` attribute from any operation.
This commit removes any direct access to the `inner_sym` attribute, and instead uses a helper utility to get the `inner_sym` name of an operation.
This utility will be required to get the `inner_sym` name, when the `inner_sym` attribute is a complex `Attribute` instead of a  `StringAttr`. This also reduces the number of changes required for a followup `InnerSymAttr` PR.

[FIRRTL] Add helper utility to get InnerSym name. NFC.

---

test/Dialect/FIRRTL/emit-omir.mlir

In a few cases the variables were re-defined instead of checking
that the produced output matches an earlier matched name.
In two cases, drop use of a variable as the symbol name is known
(since it's given in the input IR) and should match.

[FIRRTL] touchup EmitOMIR test so symbol names are checked

---

frontends/PyCDE/src/pycde/__init__.py
frontends/PyCDE/src/pycde/module.py
frontends/PyCDE/src/pycde/pycde_types.py
frontends/PyCDE/src/pycde/value.py
frontends/PyCDE/test/compreg.py
frontends/PyCDE/test/good_example.py

Add a `Clock` input port type. Allow a `with` on that port to enter a 'clocking block', which the `Value.reg` function recognizes and uses as the `clk` input. Implicitly enter a clocking block when a module has exactly one `Clock` port.
Whether or not this should be considered syntactic sugar (and implemented in Python as this PR does) or should be represented in the IR is debatable. For now, this is easier but we may consider an IR representation later on.

[PyCDE] Clock inputs and clocking blocks

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/SFCTests/data-taps-nlas.fir

Fix a bug in Grand Central (GCT) Data/Mem Taps pass where Data Taps
could be produced with invalid XMRs.  An exhaustive test case is added
that checks all permutations of upwards and downwards XMRs including
corner cases where the tap module is a leaf and the root.
Fixes #3414.

[FIRRTL] Fix bug in GCT Taps XMRs

---

include/circt/Conversion/ExportVerilog.h
include/circt/Conversion/Passes.td
include/circt/Support/LoweringOptions.h
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
lib/Support/LoweringOptions.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Conversion/ExportVerilog/prepare-for-emission.mlir

This PR adds a pass to run only PrepareForEmission for testing purpose. Currently prepare is tested as integration tests with 
ExportVerilog. However, considering that PrepareForEmission performs a lot of IR mutations to legalize IRs, it would be more comfortable to test IR mutations to make ExportVerilog less monolithic.

[PrepareForEmission] Add a pass to run only PrepareForEmission

---

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
test/Dialect/FIRRTL/imconstprop.mlir

This breaks two tests, which arguably were wrong before, though might have matched SFC.
This makes all registers and wires start in an invalid state (rather than invalid for reg and wire and unknown for regreset).
This doesn't necessarily make sense, possibly all regs should start unknown and all wires invalid?

Treat regreset the same in its initial lattice value as reg

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/Comb/canonicalization.mlir

Enables the `or` operator to simplify expressions with duplicate arguments. Currently, this is only possible if the duplicates are at the end, i.e. `or(x, y, a, a)` becomes `or(x, y, a)` but `or(x, y, y, a)` does not become `or(x, y, a)`

Allow arbitrary order of idempotent or operations 

---

include/circt/Dialect/FSM/FSMOps.td
lib/Dialect/FSM/FSMOps.cpp
test/Dialect/FSM/basics.mlir
test/Dialect/FSM/errors.mlir

This was enforcing unintended ops which shows up when generating FSM IR from a frontend. Previously, `SingleBlockImplicitTerminator<"OutputOp">` required an OutputOp to be in both the output and transition regions, where it really only made sense for the output region.
It's a similar story for the TransitionOp and `SingleBlockImplicitTerminator<"ReturnOp">`.
This, and other small fixes, have been moved to FSMOps.cpp

[FSM] Remove SingleBlockImplicitTerminator from StateOp, TransitionOp

---

include/circt-c/Dialect/MSFT.h
include/circt/Dialect/MSFT/MSFTAttributes.td
integration_test/Bindings/Python/dialects/msft.py
lib/Bindings/Python/MSFTModule.cpp
lib/CAPI/Dialect/MSFT.cpp
test/Dialect/MSFT/attributes.mlir

An 'AppID' is intended to make browsing the instance hierarchy easier.
Instead of having to reason about instance names, users can specify an
'AppID' consisting of a (name, index) pair and browse the hierarchy that
way. Said browsing also looks through the instance hierarchy (with
several rules about transparency) to mask implementation details at
various levels of the hierarchy.
This commit adds an `AppID` attribute and exposes it through Python.

[MSFT] AppID attribute

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h
include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
include/circt/Dialect/FIRRTL/InnerSymbolTable.h
lib/Dialect/FIRRTL/InnerSymbolTable.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp

Improvements to InnerSymbolTable.
* Move it and related classes out of Op Interfaces and to a dedicated header
* Provide method for obtaining inner symbol for an operation, nowhere outside these classes should muck with grabbing that attribute manually (if possible).
* Make classes non-copyable, fix copy
* Add helpers for creating InnerRef's to operations with inner symbols.
InnerRef helpers are not quite what we really need to simplify our passes, yet--  often passes want something like `getInnerRefAndInnerSymAsNeeded(Operation *op)` which usually leverages `ModuleNamespace`(s), and the sort of names assigned when not already present varies across passes (but may not be critical).
Finding a better way to unify these things, cleanly would be good.

[FIRRTL] InnerSymbolTable: move to own header, add helpers

---

include/circt/Dialect/MSFT/MSFTOps.td
include/circt/Dialect/MSFT/MSFTPasses.td
lib/Dialect/MSFT/MSFTOps.cpp
lib/Dialect/MSFT/MSFTPasses.cpp
test/Dialect/MSFT/module_instance.mlir
test/Dialect/MSFT/opt-errors.mlir

Introduces a pass to discover AppIDs and annotate modules with the AppID
base names for all of the AppIDs they recursively contain. Will be used
to efficiently implement instance hierarchy browsing be AppID.

[MSFT] Pass to discover AppIDs

---

lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp
test/Dialect/FIRRTL/grand-central-signal-mappings.mlir

We use buffer wires to break the verilog net when using force
statements.  So far we have only seen a need to do this for input ports,
but the same situation can happen with output ports.  When we are
forcing the value of an output port, we need to insert a wire inside the
module between it and submodule ports, so that the submodule's output
port is not also forced.

[FIRRTL][GCSM] Use buffer wires for forced output ports

---

include/circt/Dialect/FIRRTL/AnnotationDetails.h

Also, squelch warnings about these being unused.

[FIRRTL] AnnotationDetails.h: be consistent, prefer constexpr [NFC]

---

include/circt/Dialect/FIRRTL/CHIRRTL.td
include/circt/Dialect/FIRRTL/FIRRTLAttributes.td
include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
include/circt/Dialect/FIRRTL/FIRRTLOps.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/CHIRRTLDialect.cpp
lib/Dialect/FIRRTL/FIRRTLAttributes.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp
lib/Dialect/FIRRTL/Transforms/LowerCHIRRTL.cpp
lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
lib/Dialect/HW/HWAttributes.cpp
test/Dialect/FIRRTL/grand-central-taps.mlir
tools/circt-reduce/Reduction.cpp

This PR creates a new `Attribute` for `inner_sym`, and replaces the `SymbolNameAttr` with `InnerSymAttr`.
The `InnerSymAttr` contains a single field `StringAttr` for the `inner_sym` name. 
The plan is to extend the `InnerSymAttr` to specify symbols per field of an aggregate type, and also specify `public`/`private` visibility for each symbol.
Most of the changes in this PR is to just move the `StringAttr` `inner_sym` to the new `InnerSymAttr`.

[FIRRTL] Replace SymbolNameAttr with a new InnerSymAttr

---

include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp

Add statistics for
1. number of raw annotations processed
2. number of additional annotations processed
3. number of unhandled annotations (included in above counts)
4. total number of annotations (=1+2)
Preserve implementation and interface to annotation handling registry.

[FIRRTL] LowerAnnnos: Add a few statistics

---

lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/MemToRegOfVec.cpp
test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/annotations.fir
test/Dialect/FIRRTL/lower-types.mlir
test/Dialect/FIRRTL/mem-to-reg-of-vec.mlir

Modify existing places in the codebase that create `SubAnnotationAttr` to instead add a `circt.fieldID` member to annotations.  This is done as prerequisite work for removing `SubAnnotationAttr`.  This is viewed as being too heavy handed of a solution in favor of the simpler approach of just adding a field to existing annotations.
This requires and is rebased on top of #3427.

[FIRRTL] Switch to exclusive generation of circt.fieldID

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp

Avoid many copies of field objects as they're not tiny (contain a SmallString, for example).  While visiting, touchup an isa check to use `isa_and_nonnull`.
From commit:
These contain SmallVector's, don't copy them around unnecessarily.
On my machine, sizeof(FlatBundleFieldEntry) = 72.
Also avoid copy when iterating through renames.

[FIRRTL][LowerTypes] avoid non-trivial copies, use const ref; touchup isa check

---

lib/Dialect/FIRRTL/Transforms/MemToRegOfVec.cpp

These objects aren't trivial, for example contain SmallVector.
On my machine, sizeof(FirMemory) = 184.

[FIRRTL][MemToRegOfVec] avoid unnecessary copies, use const ref. NFC.

---

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp

No need to copy these, and let's not since they include a SmallVector.
On my machine, sizeof(AnnoPathValue) = 88.

[FIRRTL][LowerAnnotations] avoid non-trivial copies, use const ref. NFC.

---

include/circt/Dialect/FIRRTL/FIRRTLAttributes.td
lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp
lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/FlattenMemory.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
tools/circt-reduce/Reduction.cpp

This is the final piece of the puzzle to removing `SubAnnotationAttr`. This does two things:
1. All logic that uses `SubAnnotationAttr` is modified to remove it. (Human-in-the-loop constant folding...)
2. `SubAnnotationAttr` is removed.
3. `AnnotationArrayAttr` is redefined in terms of a `TypeArrayAttr<DictionaryAttr>`.

[FIRRTL] Remove SubAnnotationAttr

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/DropName.cpp
lib/Dialect/FIRRTL/Transforms/PassDetails.h
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir
test/Dialect/FIRRTL/SFCTests/async-reset.fir
test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/SFCTests/invalid-reg-pass.fir
test/Dialect/FIRRTL/SFCTests/remove-reset.fir
test/Dialect/FIRRTL/annotations.fir
test/Dialect/FIRRTL/drop-name.mlir
test/Dialect/FIRRTL/parse-basic.fir
test/firtool/firtool.fir
test/firtool/memory.fir
test/firtool/name-preservation.fir
test/firtool/prefixMemory.fir
tools/firtool/firtool.cpp

This change moves more logic related to name preservation into the
DropNames pass.  The parser no longer determines if names should be
droppable at parse time, it always creates wires and registers with
`interesting_name`s.
The drop names pass used to unconditionally mark all operation as
"droppable_name"s when run.  The `DropNames` pass now takes a parameter
if it should preserve everything, nothing, or only things with meaningful
names.
I think that there is a problem with our current naming of "name
preservation": it is not about whether the "name" is preserved or
dropped, it describes whether a wire or register should be preserved or
dropped.  For this reason I think it makes more sense to refer to it as
"value preservation". As the first step toward moving the focus , I
changed the …

[FIRRTL] Move all name preservation logic into the drop names pass

---

frontends/PyCDE/src/pycde/__init__.py
frontends/PyCDE/src/pycde/instance.py
frontends/PyCDE/src/pycde/module.py
frontends/PyCDE/src/pycde/system.py
frontends/PyCDE/src/pycde/value.py
frontends/PyCDE/test/compreg.py
frontends/PyCDE/test/errors.py
frontends/PyCDE/test/instances.py
frontends/PyCDE/test/polynomial.py
lib/Bindings/Python/circt/dialects/_msft_ops_ext.py

Expose AppIDs through PyCDE and allow them to be added to any Operation with a `sym_name` attribute. Add arguments to set the appid on instances and registers as shortcuts. Adds AppID-based accessors to the `Instance` hierarchy.

[PyCDE] Expose AppIDs: add them via Value, shortcuts for regs/instances, accessors in `Instance`s

---

include/circt/Support/LoweringOptions.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/ExportVerilogInternals.h
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
lib/Support/LoweringOptions.cpp
test/Conversion/ExportVerilog/prepare-for-emission.mlir

This PR adds an option to perform verilog expression legalization at
PrepareForEmission via IR mutation. This means temporary wires are
explicitly spilled to wire ops instead of implicilty being spilled at
emission. Once ExportVerilog simplification is completed, this feature
shoiuld be enabled by default.
This is the first and second part of https://discourse.llvm.org/t/exportverilog-simplification-for-pretty-printing-output-verilog/63363#plan-3.

[ExportVerilog] Add an option to legalize IR at PrepareForEmission

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Conversion/ExportVerilog/sv-interfaces.mlir
test/Dialect/FIRRTL/grand-central.mlir

Fix a bug in the Grand Central (GCT) Views pass where a view of a
zero-width component would create an XMR.  Change the GCT View pass to
not create the XMR. Change ExportVerilog to emit a comment.
Fixes #3460.

[FIRRTL] Fix GCT Views for Zero-width

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/grand-central-taps.mlir

Fix a bug in the Grand Central (GCT) Taps pass where XMRs would be
generated for zero-width data taps.  This then avoids a crash in
LowerToHW where the zero-width, tapped components could _not_ be removed
as they were the targets of XMRs and preventing full lowering of the
FIRRTL IR.  This commit changes the pass to generate no XMRs and this
then enables LowerToHW to correctly remove the zero-width ports on the
data tap module.
Fixes #3458.

[FIRRTL] Fix GCT Taps for Zero-width

---

include/circt/Dialect/SV/SVInOutOps.td
include/circt/Dialect/SV/SVVisitors.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/SV/SVOps.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

As we talked in the last ODM, we need an operation `sv.logic` 
to represent a temporary in a procedural region. 
This implements sv.logic op which represent "logic" variable in SV spec.
Implementation is almost identical to sv.wire and sv.reg except that 
sv.logic is allowed to be defined in procedural and non-procedural
region. If sv.logic is defined in a procedural region, "automatic" keyword is
added to its declaration in emission.

[SV] Add sv.logic op

---

include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp

Add statistics for the Grand Central (GCT) Views pass.
This is perhaps a bit overkill, but is everything that came to mind for this pass. Example output:
```
GrandCentral
(S)  1 num-views-created       - Number of top-level SystemVerilog interfaces that were created
(S)  5 num-interfaces-created  - Number of SystemVerilog interfaces that were created
(S) 22 num-xmrs-created        - Number of SystemVerilog XMRs added
(S) 26 num-annotations-removed - Number of annotations removed
```

[FIRRTL] Add statistics for GCT Views Pass

---

include/circt/Dialect/FSM/FSMOps.td
test/Dialect/FSM/basics.mlir
test/Dialect/FSM/errors.mlir
test/Dialect/FSM/print-graph.mlir

States are now described as a symbol (using @) instead of the previously used string notation.

[FSM] Make state names SymbolNameAttrs

---

include/circt/Transforms/Passes.h
include/circt/Transforms/Passes.td
lib/Transforms/CMakeLists.txt
lib/Transforms/StripDebugInfoWithPred.cpp
test/Transforms/strip-debuginfo-pred.mlir
test/firtool/firtool.fir
tools/firtool/CMakeLists.txt
tools/firtool/firtool.cpp

This implements `-strip-fir-debug-info` option to drop source locators of fir files
just before ExportVerilog emission. The pass `StripDebugInfoWithPred` is similar to [StripDebugInfo
](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Transforms/StripDebugInfo.cpp) pass, but `StripDebugInfoWithPred` selectively strips locations using given predicate.

[Transform] [FIRTOOL] Add an pass to strip file locators with "fir" suffix

---

include/circt/Dialect/FIRRTL/FIRRTLAttributes.td
lib/Dialect/FIRRTL/FIRRTLAttributes.cpp
test/Dialect/FIRRTL/test.mlir

This PR updates the `InnerSymAttr` to add per field inner symbols.
`InnerSymAttr` defines the properties of the `inner_sym` attribute. It specifies the symbol
name and symbol visibility for each field ID.
For any ground types, there are no subfields and the field ID is 0. For aggregate types, a
unique field ID is assigned to each field by visiting them in a depth-first pre-order.
The custom assembly format ensures that there is no change for the default case.
If a symbol for any field other than `fieldID=0` is specified, then the format is like this:
`%w = firrtl.wire sym [<@w,2,public>,<@x,1,private>,<@syh,4,public>] : !firrtl.bundle<a: uint<1>, b: uint<1>, c: uint<1>, d: uint<1>>`
This also adds the capability to specify the visibility of each symbol.
Some followup work pending:
1. …

[FIRRTL] InnerSymAttr: Add per field inner symbol

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/SFCTests/data-taps.fir
test/Dialect/FIRRTL/grand-central-taps.mlir

Change Grand Central (GCT) Data/Mem Taps pass to use constants for data
taps when trivially obvious.  This has the result of _not_ emitting an
XMR when a wire is trivially driven by a constant.

[FIRRTL] Sink Constants in GCT Taps

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Dialect/FIRRTL/grand-central.mlir

Change Grand Central (GCT) Views pass to sink trivial constants into
sv::VerbatimOp XMRs inside the mappings module.  This has the benefit of
not needing to add a symbol to the viewed component if it is a constant
which enables this to be deleted and avoids lint warnings related to
unused wires/registers.
This is reviving logic that used to exist in https://github.com/llvm/circt/pull/3154.

[FIRRTL] Sink Constants into GCT Views XMRs

---

include/circt/Dialect/HW/HWVisitors.h
include/circt/Dialect/SV/SVOps.h
include/circt/Dialect/SV/SVStatements.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/HW/HWOps.cpp
lib/Dialect/SV/SVOps.cpp
lib/Dialect/SV/Transforms/HWLegalizeModules.cpp
test/Conversion/ExportVerilog/hw-typedecls.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir
test/Dialect/SV/errors.mlir

This commit adds support in `sv.case` for switching on enum values. In doing so, a fair bit of refactoring is done to `CasePattern`s to more cleanly handle the different cases of bit, enum, and default patterns.
Since `hw.enum` doesn't yet include any notion of value encoding, the `sv.case` operation exclusively works on either an enum or bit pattern.
Furthermore, only a single case value can be compared in a case statement (as opposed to `case A, B : ...`). I think this is a good starting point - if support is needed in the future, it will not be complicated to add.
```mlir
hw.module @AnFSM(%clock : i1) {
%reg = sv.reg : !hw.inout<!hw.enum<A, B, C>>
%reg_read = sv.read_inout %reg : !hw.inout<!hw.enum<A, B, C>>
%A = hw.enum.constant A : !hw.enum<A, B, C>
%B = hw.enum.constant B : …
```

[SV] Add support for `sv.case` with `hw.enum`

---

include/circt/Dialect/FIRRTL/FIRRTLAttributes.td
include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h
include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
lib/Dialect/FIRRTL/FIRRTLAttributes.cpp
lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp
test/Dialect/FIRRTL/errors.mlir

Add the verifier for InnerSymAttr.
The verifier checks that, 
1. All the `fieldID`s specified are unique.
2. All the inner sym names are unique.
3. The `fieldID` is valid.
4. For ops with zero or multiple results, only the `fieldID=0` can have an inner sym.

[FIRRTL] Add InnerSymAttr verifier

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

During LowerTypes we take ports of bundle type, with fields annotated
with DontTouch, and exchange the annotation for a symbol on the port.
This was broken when the DontTouch was not the last annotation applied
to the port, as subsequent annotations would overwrite the `needsSym`
local variable.
Fixes #3504

[FIRRTL][LowerTypes] Fix DontTouch application on ports

---

test/firtool/print-before.fir
tools/firtool/firtool.cpp

From commit message:
----
Ensure the passes we use are registered before parsing the command line
options, so that options such as `--mlir-print-ir-before=` work.
Add test.
It would be better if we didn't have to worry about this,
("did we remember to register all the passes" / early loading)
but in the meantime these options are very helpful for debugging
large designs.
This may pull in more than strictly needed,
Debug binary went 135M -> 140M after this change.
----
I've been sitting on this for a bit, because this might be a pain to maintain (and loses some niceness re:lazy loading?), and either wanted a clean way to ensure that doesn't happen or to add our own variants that don't require this (although printing error message at command-line parse time requires some knowledge of what …

firtool: register passes to fix use of `--mlir-print-ir-{before,after}` options

---

lib/Dialect/FIRRTL/Transforms/DropName.cpp

[FIRRTL] DropNames: fix stat, only drop if not already droppable

---

include/circt/Dialect/SV/SVTypeDecl.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Conversion/ExportVerilog/sv-interfaces.mlir
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/grand-central.mlir

We need to add a comment `// VCS coverage exclude_file"` to all Grand
Central modules and interfaces.  When we needed something like this
previously, it was handled by adding a `comment` attribute onto
`hw.module` and handled in lower to HW.
To support these new targets, we had to:
1. Add a comment attribute to SV interfaces.  To accomplish this, I used
an optional string attribute.  I switched the printed format to print
the attribute dictionary after the symbol name, which I think is more
common across all our operations.
2. Update `ExportVerilog` to print this attribute.  The `emitComment`
function can recognize null attributes and skip a comment.
3. Propagate a `comment` attribute on FIRRTL modules in `LowerToHW` to HW
modules.  This was not added to the ODS arguments, similar to the …

[FIRRTL][SV] Add comment attribute to GC interfaces and modules

---

include/circt/Dialect/HW/HWDialect.td
include/circt/Dialect/HW/HWMiscOps.td
include/circt/Dialect/HW/HWStructure.td
include/circt/Dialect/HW/HWTypeDecls.td
include/circt/Dialect/MSFT/MSFTOpInterfaces.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/LegalizeNames.cpp
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Conversion/HWToLLHD/HWToLLHD.cpp
lib/Conversion/LLHDToLLVM/LLHDToLLVM.cpp
lib/Dialect/Calyx/Export/CalyxEmitter.cpp
lib/Dialect/Comb/CombFolds.cpp
lib/Dialect/ESI/ESIPasses.cpp
lib/Dialect/HW/HWOps.cpp
lib/Dialect/HW/Transforms/HWSpecialize.cpp
lib/Dialect/MSFT/ExportQuartusTcl.cpp
lib/Dialect/MSFT/MSFTPasses.cpp
lib/Dialect/SV/Transforms/GeneratorCallout.cpp
lib/Dialect/SV/Transforms/HWExportModuleHierarchy.cpp
lib/Dialect/SV/Transforms/HWLegalizeModules.cpp
lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
lib/Dialect/SV/Transforms/HWStubExternalModules.cpp
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
unittests/Dialect/HW/HWModuleTest.cpp

We cannot directly switch to prefixed only because of the use of duck-typing in `HWOpInterfaces.td` and `SVOps.cpp`. This means we need to generate both the prefixed and non-prefixed accessors until all dialects that make use of HWInstanceLike have switched. This includes HW, SV, FIRRTL, MSFT.

[HW] Adopt prefixed accessors

---

include/circt/Support/Namespace.h
lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp

Tweak behavior to match comment "2." (_<n>_<suffix>).
Insist on underscore separation instead of leaving up to caller.
Minor comment touchup.

Namespace: add underscore before the suffix

---

lib/Bindings/Python/setup.py

It seems the python setup is trying to locate llvm's root CMakeLists.txt and cannot find it under `circt/llvm/`. (It seems it is under `circt/llvm/llvm`).

Updating default llvm path in lib/Bindings/Python

---

include/circt/Dialect/Seq/Seq.td
integration_test/Dialect/Seq/registers.mlir
lib/Dialect/Seq/SeqOps.cpp
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Dialect/Seq/firreg-errors.mlir
test/Dialect/Seq/firreg.mlir

The `seq.firreg` introduced in this PR captures all information required to represent FIRRTL registers and lower them in a separate pass to SV equivalently to the code emitted prior to this change.

[Seq] Add a seq register to represent FIRRTL registers

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

This commit disables bypass canonicalizations of wire op and node op if name preservation
is enabled. In the name preservation mode, users want to preserve def-uses so the bypass canonicalization 
is problematic in terms of debuggability. 
Note that this PR will reopen the issue https://github.com/llvm/circt/issues/3319 but it will be fixed by folders in https://github.com/llvm/circt/pull/3535. 
Close https://github.com/llvm/circt/issues/3148

[FIRRTL] Disable bypass canonicalizations when name preservation

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

This PR adds folders for AndOp and OrOp to handle the cases when lhs is constant.
IMCP uses folders but it is not guranteed that rhs is always constant, hence
it is necessary to add commutative folders.
This fixes https://github.com/llvm/circt/issues/3319 on top of https://github.com/llvm/circt/pull/3534

[FIRRTL] Add AndOp/OrOp commutative folders

---

lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
test/Dialect/SV/hw-memsim.mlir

Make `addPipelineStages` try to reuse the always block of the previous pipeline. This requires checking if the clocks match, and that all the values that we'd stick into this block are accessible at the block location.
Does not change functionality, just produces slightly shorter IR.

[HWMemSimImpl] Merge pipeline regs into single always block

---

include/circt/Dialect/MSFT/MSFTOps.td
lib/Dialect/MSFT/MSFTOps.cpp
test/Dialect/ESI/services.mlir

Allows ESI connect services pass to execute on msft modules.

[MSFT] Implement `HWMutableModuleLike` in `msft.module`

---

lib/Dialect/MSFT/MSFTPasses.cpp
test/Dialect/MSFT/module_instance.mlir

Makes some parsers happier (like `iverilog`).

[MSFT] Add default value to __INST_HIER parameter

---

include/circt/Conversion/FIRRTLToHW.h
include/circt/Conversion/Passes.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/emit-chisel-asserts-as-sva.mlir
test/Dialect/FIRRTL/SFCTests/complex-asserts.fir
tools/firtool/firtool.cpp

This commit adds an option `emit-chisel-asserts-as-sva` to emit chisel
asserts as sva assertions at LowerToHW. Other implementation idea is 
to create a pass to convert `format` attribute from `ifElseFatal` to `sva` 
but for now, i implemented it as an option of LowerToHW.

[LowerToHW][FIRTOOL] Add an option to emit chisel asserts as sva

---

lib/Dialect/SV/Transforms/PrettifyVerilog.cpp
test/Dialect/SV/prettify-verilog.mlir

If a register or a wire is updated with struct inject or array concat:
```
%reg = seq.firreg %clk, %b, ...
%a = hw.struct_inject %reg["a"], %valA
%b = hw.struct_inject %reg["b"], %valB
```
Instead of emitting structure constructs:
```
sv.bpassign %reg, hw.struct_inject ...
```
Which lower to:
```
reg <= { a: ..., b: ... }
```
This patch updates individual subfields:
```
%fieldA = sv.struct_field_inout %reg["a"]
%sv.passign %fieldA, %valA
%fieldB = sv.struct_field_inout %reg["B"]
%sv.passign %fieldB, %valB
```
Which lowers to:
```
reg.a <= valA;
reg.b <= valB;
```

[SV][PrettifyVerilog] Lowered struct inject/array concat to `sv.passign` of individual fields/elements

---

lib/Dialect/SV/Transforms/PrettifyVerilog.cpp

This fixes a bug in https://github.com/llvm/circt/commit/61fb54e41bf23c6fbd787decc53e5705b0f691bf. 
PrettifyVerilog frees same operations twice when operations are
stored to `toDelete` and erased by `sinkOrCloneOpToUses`. This fixes
the issue by storing operations into `toDelete` within sinkOrCloneOpToUses
as well.

[PrettifyVerilog] Fix double free

---

include/circt/Conversion/ExportSystemC.h
include/circt/Conversion/Passes.h
include/circt/Conversion/Passes.td
lib/Conversion/CMakeLists.txt
lib/Conversion/ExportSystemC/CMakeLists.txt
lib/Conversion/ExportSystemC/ExportSystemC.cpp
tools/circt-opt/CMakeLists.txt

Depends on #3520
This adds the very basic conversion pass registration code for ExportSystemC to emit SystemC code.

[SystemC] Add ExportSystemC skeleton

---

lib/Dialect/FIRRTL/Transforms/FlattenMemory.cpp
test/Dialect/FIRRTL/flatten-memory.mlir

This commit fixes a crash in `FlattenMemory` pass on a memory with zero bit wide data.
Ignore any aggregate memory with zero bits data during FlattenMemory pass.
This aggregate memory will be handled during LowerTypes.

[FIRRTL][FlattenMemory] Ignore memory with zero bit data

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/errors.mlir
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

Adjust `FIRRTLLowering::handleUnloweredOp` to apply a consistent lowering to operations from dialects other than FIRRTL. This used to be a very specific snippet of code that allowed `hw.output` and the `unrealized_conversion_cast` inserted after block args to be passed through.
With this change, `handleUnloweredOp` will check if an operation comes from outside of FIRRTL. If it does we replace all operands with a potentially lowered value, and record the results as identity lowerings. As a result, we no longer have to have special treatment of the `unrealized_conversion_cast` inserted after block args.
This is a first step towards foreign type support, and will cause `LowerToHW` to do the right thing for operations from other dialects that are present in the module (operand updating and …

[LowerToHW] Generalize handling of non-FIRRTL ops

---

include/circt/Analysis/ControlFlowLoopAnalysis.h
lib/Analysis/CMakeLists.txt
lib/Analysis/ControlFlowLoopAnalysis.cpp
lib/Analysis/TestPasses.cpp
lib/Conversion/StandardToHandshake/CMakeLists.txt
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
test/Analysis/cf-loop-analysis.mlir
test/Conversion/StandardToHandshake/errors.mlir

This PR factors out the top level loop analysis used in `StandardToHandshake` and adds tests for it. 
It might make sense to keep this as part of the `StandardToHandshake` conversion, but then we have to add another place for test passes. 
Note that Polygeist implements something similar (https://github.com/llvm/Polygeist/blob/main/lib/polygeist/Passes/LoopRestructure.cpp), but it cannot be ported easily due to a ton of issues caused by casts.

[Analysis][StandardToHandshake] Introduce a loop analysis for the CF dialect

---

tools/firtool/firtool.cpp

This adds an option to firtool to specify the optimizations at a large
granularity, with two `release` and `debug`. Right now, this just
customizes the value preservation flag. The use of a hook allows these
options to compose sensibly with the finer grained options, s the last
command line option specified overrides previous settings.

[firtool] Add optimization option `-O [debug|release]`

---

test/CAPI/CMakeLists.txt
test/CMakeLists.txt
test/handshake-runner/simple_loop.mlir
tools/handshake-runner/CMakeLists.txt
tools/llhd-sim/CMakeLists.txt

Cull unnecessary dependences. Reduces the number of files which need to
be compiled for check-circt by ~20%. Compiles and links fine on my machine,
but we've had linking issues in the past, so this may be bumpy.

[CMake] Reduce number of deps

---

frontends/PyCDE/src/pycde/fsm.py
frontends/PyCDE/test/test_fsm.py

Generate a FSM from a dictionary of states and their transitions.
E.g.:
```
{
"a": [
("c", "go"),
"b",
],
"b": [],
"c": []
}
```
creates an FSM with 3 states (a, b, c). 'b' and 'c' have no outgoing transitions, and 'a' has two outgoing transitions (priority encoded). The first transition ("c", "go") transitions to 'c' whenever an input port 'go' is asserted. The second transition is a default transition to 'b'.
Any state and guard referenced within the dictionary will automatically be created as a state operation and top-level input, respectively.

[PyCDE] Add shorthand FSM builder function

---

include/circt-c/Dialect/SV.h
include/circt/Dialect/SV/SVAttributes.h
include/circt/Dialect/SV/SVAttributes.td
integration_test/Bindings/Python/dialects/seq.py
lib/Bindings/Python/SVModule.cpp
lib/CAPI/Dialect/SV.cpp
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/SV/SVAttributes.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir

This PR proposes `emitAsComments` functionality for SV attributes.
Unfortunately, some of vendor specific pragmas are not strictly valid
SV attributes. For example, `(* cadence map_to_mux *)` is not valid SV
attribute  hence vendor compilers recognize comments as some sort of
attributes. Therefore, this (draft) PR proposes a way to emit SV
attributes as comments.
Example:
```mlir
%0 = sv.wire {sv.attributes = #sv.attributes<[#sv.attribute<"foo bar">], emitAsComments>} : i1
==>
/* foo bar */
wire GEN;
```

[SV] Create SVAttributesAttr and `emitAsComments` flag

---

include/circt/Dialect/ESI/CMakeLists.txt
include/circt/Dialect/ESI/ESI.td
include/circt/Dialect/ESI/ESIInterfaces.td
include/circt/Dialect/ESI/ESIOps.h
include/circt/Dialect/ESI/ESIOps.td
include/circt/Dialect/ESI/ESIPorts.td
lib/Dialect/ESI/CMakeLists.txt
lib/Dialect/ESI/ESIDialect.cpp
lib/Dialect/ESI/ESIOps.cpp
lib/Dialect/ESI/ESIPasses.cpp
test/Dialect/ESI/connectivity.mlir
test/Dialect/ESI/lowering.mlir

`none` typed channels imply channels which carry no data, but still transaction/handshake semantics. A new interface `ChannelOpInterface` is introduced to factor out logic for determining whether an operation carries data semantics.

[ESI] Support `none`-typed channels

---

lib/Conversion/LLHDToLLVM/LLHDToLLVM.cpp
test/Conversion/LLHDToLLVM/signal-init-error.mlir
test/Conversion/LLHDToLLVM/signal-init.mlir

Currently, `LLHDToLLVM` accepts a very limited number of expressions for the `llhd.sig` init value. In particular, it fails when first partially lowering only the HW operations in the following IR
```mlir
llhd.entity @snitch_tb () -> () {
llhd.inst "i_snitch" @snitch.param1() -> () : () -> ()
}
llhd.entity @snitch.param1 () -> () {
%c0_i5_17 = hw.constant 0 : i5
%c0_i5_18 = hw.constant 0 : i5
%21 = hw.array_create %c0_i5_17, %c0_i5_18 : i5
%22 = llhd.sig "gpr_raddr" %21 : !hw.array<2xi5>
}
```
to
```mlir
llhd.entity @snitch_tb () -> () {
llhd.inst "i_snitch" @snitch.param1() -> () : () -> ()
}
llhd.entity @snitch.param1 () -> () {
%0 = llvm.mlir.constant(0 : i5) : i5
%1 = llvm.mlir.undef : !llvm.array<2 x i5>
%2 = llvm.insertvalue %0, %1[0 : i32] : !llvm.array<2 x i5>
%3 = …
```

[LLHDToLLVM] Generalize signal init expression support

---

lib/Conversion/LLHDToLLVM/LLHDToLLVM.cpp
test/Conversion/LLHDToLLVM/convert_bitwise.mlir

Moore often emits concats of the same value which are canonicalized to replicate ops, i.e., canonicalizing before running LLHDToLLVM is not possible because it would fail due to the missing conversion pattern.

[LLHDToLLVM] Add lowering support for comb.replicate

---

lib/Conversion/LLHDToLLVM/CMakeLists.txt
lib/Conversion/LLHDToLLVM/LLHDToLLVM.cpp

Because LLHD uses operations from the cf dialect calling canonicalize creates, e.g., arith.select when control flow can be simplified. Canonicalization patterns of arith might then modify this further to arith.extui or similar. To be able to continue using the cf operations and benefit from all the control flow simplification canonicalizations, we need to add support for lowering arith operations to LLVM.

[LLHDToLLVM] Populate ArithToLLVM conversion patterns

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/HW/HWOpInterfaces.td
include/circt/Dialect/HW/HWStructure.td
include/circt/Dialect/MSFT/MSFTOps.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/HW/HWOps.cpp

Added a method to fetch the referenced op of any instance-like ops.

[HW] Add `getReferencedModule` to `HWInstanceLike`

---

include/circt/Dialect/Calyx/CalyxLoweringUtils.h
include/circt/Dialect/Calyx/CalyxOps.h
include/circt/Dialect/Calyx/CalyxStructure.td
lib/Conversion/CalyxToHW/CalyxToHW.cpp
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Conversion/StaticLogicToCalyx/StaticLogicToCalyx.cpp
lib/Dialect/Calyx/CalyxOps.cpp
lib/Dialect/Calyx/Export/CalyxEmitter.cpp
lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp
test/Conversion/CalyxToFSM/lower-if.mlir
test/Conversion/CalyxToFSM/lower-seq.mlir
test/Conversion/CalyxToFSM/lower-while.mlir
test/Conversion/CalyxToHW/basic.mlir
test/Conversion/CalyxToHW/primitives.mlir
test/Conversion/SCFToCalyx/cider_source_location.mlir
test/Conversion/SCFToCalyx/convert_controlflow.mlir
test/Conversion/SCFToCalyx/convert_memory.mlir
test/Conversion/SCFToCalyx/convert_simple.mlir
test/Conversion/StaticLogicToCalyx/convert_pipeline.mlir
test/Dialect/Calyx/canonicalization.mlir
test/Dialect/Calyx/clk-insertion.mlir
test/Dialect/Calyx/compile-control.mlir
test/Dialect/Calyx/emit.mlir
test/Dialect/Calyx/errors.mlir
test/Dialect/Calyx/export-errors.mlir
test/Dialect/Calyx/gicm.mlir
test/Dialect/Calyx/go-insertion.mlir
test/Dialect/Calyx/remove-groups.mlir
test/Dialect/Calyx/round-trip.mlir

Based on discussion about removing calyx.program in #3565. Allows the calyx dialect to integrate better with other dialects.

[Calyx] Replace calyx.program with module attribute calyx.entrypoint

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h
include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
include/circt/Dialect/FIRRTL/FIRRTLStructure.td
include/circt/Dialect/FIRRTL/InnerSymbolTable.h
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/InnerSymbolTable.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/imdce.mlir
test/Dialect/FIRRTL/remove-unused-ports.mlir

Primarily: Flesh out IST to understand all the places that have inner symbols.
This is done by adding a new "InnerSymTarget" class that represents entities that inner symbols may name (can also be used for query), and updating IST and friends to use this.
FWIW, representation of per-field symbols on ports is accommodated but will need some small changes when that happens.
Since they contain entities with inner symbols that are expected to be resolved, now require all FModuleLike constructs to have the IST trait (and add a static_assert to ensure this isn't missed in the future).
Update existing users to the changed IST interface.
Finally, fixup some tests that newly fail now that symbols on ports are considered in InnerSymbolTable construction as well.

[FIRRTL] Extend InnerSymbolTable for ports, per-field syms on operations

---

include/circt/Dialect/HW/InstanceGraphBase.h
lib/Analysis/CMakeLists.txt
lib/Analysis/TestPasses.cpp
lib/Dialect/HW/InstanceGraphBase.cpp
test/Analysis/infer-top-level.mlir

This commit adds support for inferring a top-level module in an InstanceGraph.
The implementation is based on a topological sort of the instance graph. Through this, error messages will be generated in case of a cycle in the instance graph or when multiple candidate top modules are found.

[HW] Add top module inference to InstanceGraph

---

include/circt/Conversion/CalyxToFSM.h
include/circt/Conversion/Passes.td
lib/Conversion/CalyxToFSM/CMakeLists.txt
lib/Conversion/CalyxToFSM/MaterializeFSM.cpp
test/Conversion/CalyxToFSM/materialize-errors.mlir
test/Conversion/CalyxToFSM/materialize-fsm.mlir

(continuation of #3214)
In materializing a Calyx control FSM we:
* Gather up all of the `calyx.group`s referenced in the FSM
* Create an in- and output for each group, representing `done` (FSM input) and `go` (FSM output) signals
* Iterate over all states in the FSM and
* replace `calyx.enable`s with an `fsm.output` bitvector asserting the corresponding `go` outputs
* Extend the guards of all transitions from the state with a conjunction of the `done` signals of the enabled groups in the given state.
After FSM materialization, the FSM no longer contains any referenced to Calyx groups, and can be safely outlined.
The materialization does not consider how to materialize static groups. However, this should be fairly easy to implement/hook into when iterating over states and detecting …

[CalyxToFSM] Add FSM materialization pass

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/ExportVerilogInternals.h
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/prepare-for-emission.mlir

This commit changes PrepareForEmission to use `inferStructuralNameForTemporary` 
function to infer names of temporary wires. `inferStructuralNameForTemporary` is moved 
to`ExportVerilogInternals.h` so that we can use it from PrepareForEmission as well.

[PrepareForEmission] Use inferStructuralNameForTemporary

---

docs/Dialects/SSP/RationaleSSP.md
include/circt/Dialect/SSP/SSP.td
include/circt/Dialect/SSP/SSPAttributes.h
include/circt/Dialect/SSP/SSPAttributes.td
include/circt/Dialect/SSP/SSPOps.h
include/circt/Dialect/SSP/SSPOps.td
lib/Dialect/SSP/SSPAttributes.cpp
lib/Dialect/SSP/SSPOps.cpp
test/Dialect/SSP/errors.mlir

This follow-up PR to #3558 adds the "mostly boring" operations of the SSP dialect; the `OperationOp` requires lots of custom printing/parsing/verification code and will be added in the next PR. Also, the attributes representing scheduling properties (latency, start time, etc.) are still excluded here as well.

[SSP] Define first batch of operations.

---

docs/Dialects/SystemC/RationaleSystemC.md
include/circt/Dialect/SystemC/CMakeLists.txt
include/circt/Dialect/SystemC/SystemC.td
include/circt/Dialect/SystemC/SystemCAttributes.h
include/circt/Dialect/SystemC/SystemCAttributesImpl.td
include/circt/Dialect/SystemC/SystemCDialect.td
include/circt/Dialect/SystemC/SystemCOps.h
include/circt/Dialect/SystemC/SystemCStatements.td
include/circt/Dialect/SystemC/SystemCStructure.td
lib/Conversion/HWToSystemC/CMakeLists.txt
lib/Conversion/HWToSystemC/HWToSystemC.cpp
lib/Dialect/SystemC/CMakeLists.txt
lib/Dialect/SystemC/SystemCAttributes.cpp
lib/Dialect/SystemC/SystemCDialect.cpp
lib/Dialect/SystemC/SystemCOps.cpp
test/Conversion/HWToSystemC/errors.mlir
test/Conversion/HWToSystemC/structure.mlir
test/Dialect/SystemC/module-attributes.mlir
test/Dialect/SystemC/module-error.mlir
test/Dialect/SystemC/structure.mlir

Includes the `systemc.module` and `systemc.alias` operation definitions as well as a basic lowering from HW. The lowering will be extended in another PR once other necessary operations such as `systemc.func` and `systemc.method` are added.

[SystemC] Add SCModuleOp and AliasOp

---

frontends/PyCDE/src/pycde/dialects/hwarith.py
frontends/PyCDE/src/pycde/pycde_types.py
frontends/PyCDE/src/pycde/system.py
frontends/PyCDE/src/pycde/testing.py
frontends/PyCDE/src/pycde/value.py
frontends/PyCDE/test/errors.py
frontends/PyCDE/test/test_hwarith.py
lib/Bindings/Python/circt/dialects/_hwarith_ops_ext.py

This commit adds support for infix operations on PyCDE bit vector values. Arithmetic operators are implemented through `hwarith` operation, logic operators through `comb`.

[PyCDE] Add infix operator support

---

include/circt/Dialect/ESI/cosim/CMakeLists.txt
lib/Dialect/ESI/cosim/cosim_dpi_server/CMakeLists.txt

The EsiCosimCapnp library never gets linked into any MLIR code. It is
used exclusively to build the DPI shared library. As such, it can get
compiled with exceptions.
Should fix #3474 .

[ESI] [Capnp] Compile library with exceptions

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Fix the issue that FoldResetMux incorrectly deletes reg with annotations.

[FIRRTLFolds] Don't remove reg with annotations in FoldResetMux

---

lib/Dialect/MSFT/MSFTPasses.cpp
tools/circt-reduce/Reduction.cpp

Not great that this is necessary, but checking the underlying operation makes the warnings go away.
(Cast check from `Operation *` instead of `FModuleLike`/`HWModuleLike`).
In MSFTPasses used `static_cast` to get the `Operation *` because apparently `getOperation()` isn't const :disappointed: .
Fixes #3615.

Fix -Wreturn-stack-address warnings

---

docs/Dialects/ESI/cosim.md
include/circt/Dialect/ESI/ESIOps.td
include/circt/Dialect/ESI/ESIPrimitives.sv
include/circt/Dialect/ESI/cosim/Cosim_Endpoint.sv
integration_test/Bindings/Python/dialects/seq.py
integration_test/Dialect/Seq/registers.mlir
integration_test/ESI/cosim/basic.mlir
integration_test/ESI/cosim/cosim_only.sv
integration_test/ESI/cosim/loopback.mlir
integration_test/ESI/primitives/primitive_tb.sv
integration_test/ESI/supplements/integers.sv
integration_test/ESI/system/basic.mlir
integration_test/EmitVerilog/basic.mlir
integration_test/EmitVerilog/exampleCodeGen.fir
integration_test/EmitVerilog/sv-interfaces.mlir
integration_test/circt-rtl-sim/circt-rtl-sim-ieee-sim.sv
integration_test/circt-rtl-sim/circt-rtl-sim-iverilog.sv
integration_test/circt-rtl-sim/circt-rtl-sim-verilator.sv
lib/Bindings/Python/circt/esi.py
lib/Dialect/ESI/ESIOps.cpp
lib/Dialect/ESI/ESIPasses.cpp
test/Dialect/ESI/connectivity.mlir
test/Dialect/ESI/cosim.mlir
test/Dialect/ESI/cosim_structs.mlir
test/Dialect/ESI/errors.mlir
test/Dialect/ESI/lowering.mlir
test/Dialect/ESI/wrapif-lowering.mlir
tools/circt-rtl-sim/driver.cpp.in
tools/circt-rtl-sim/driver.sv.in

Rst seems more common, but the integration tests and ESI use 'rstn'. Switch to the more common 'rst'. Mostly affects ESI, but the integration test driver affects the other integration tests as well.

[ESI] [Integration tests] [Tests] Switch from 'rstn' to 'rst'

---

frontends/PyCDE/src/pycde/esi.py
include/circt/Dialect/ESI/ESIInterfaces.td
include/circt/Dialect/ESI/ESIOps.td
include/circt/Dialect/ESI/ESIPorts.td
include/circt/Dialect/ESI/ESIServices.td
lib/Bindings/Python/circt/esi.py
lib/CAPI/Dialect/ESI.cpp
lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
lib/Dialect/ESI/ESIDialect.cpp
lib/Dialect/ESI/ESIFolds.cpp
lib/Dialect/ESI/ESIOps.cpp
lib/Dialect/ESI/ESIPasses.cpp
lib/Dialect/ESI/ESIServices.cpp
lib/Dialect/ESI/ESITranslations.cpp
lib/Dialect/ESI/capnp/Schema.cpp

Update the ESI class names to standard naming conventions. Mechanical search and replace.

[ESI][NFC] Rename Ops and Types to include those suffixes

---

include/circt/Dialect/SystemC/SystemCDialect.td
include/circt/Dialect/SystemC/SystemCStatements.td
include/circt/Dialect/SystemC/SystemCStructure.td
include/circt/Dialect/SystemC/SystemCTypes.h
include/circt/Dialect/SystemC/SystemCTypes.td
include/circt/Dialect/SystemC/SystemCTypesImpl.td
lib/Conversion/HWToSystemC/HWToSystemC.cpp
lib/Dialect/SystemC/CMakeLists.txt
lib/Dialect/SystemC/SystemCOps.cpp
lib/Dialect/SystemC/SystemCTypes.cpp
test/Conversion/HWToSystemC/errors.mlir
test/Conversion/HWToSystemC/structure.mlir
test/Dialect/SystemC/module-error.mlir
test/Dialect/SystemC/structure.mlir

Depends on #3614
I left two TODOs in `HWToSystemC`: I think name uniquing makes a good PR on its own implementing some utilities. Checking the graph region for invalid dominance is currently left to the verifier afterwards, but should eventually be dealt with in the lowering. However, it is likely not necessary to get a first demo running and thus I'd like to tackle that at a later point.

[SystemC] Add SCFuncOp, MethodOp, and ThreadOp

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir

This PR implements an optimization to delete attach op if there is only a 
single source value (usually port or wire). The optimization happens in the lowering 
of instance op. If an instance result has an analog type and its user is only attach, then we try eliminating the attach op. If there is a single source value in the attached values, we use that value as a lowering result of instance port result.   
SFC implementation is  https://github.com/chipsalliance/firrtl/blob/c7403e80f965aa3c6f65b176dbb56dbb905cbb31/src/main/scala/firrtl/passes/VerilogPrep.scala#L46-L79

[LowerToHW] Delete attach op if there is single source

---

include/circt/Dialect/ESI/ESIPasses.td
lib/Dialect/ESI/ESIPasses.cpp
test/Dialect/ESI/cosim.mlir

Do this in a pass which creates a VerbatimOp block. More consistent with
how other parts of CIRCT generate aux files.

[ESI] Creating capnp generation pass

---

lib/Dialect/HW/HWAttributes.cpp

There were no changes necessary for CIRCT.
This will be updated daily and, on Friday, converted to a non-draft and merged.

Bump LLVM to top-of-tree

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

In LowerToHW we have a hashtable which maps every FIRRTL value to its
lowered HW value.  Some "no-op" casts, such as `asClock`, are removed
during lowering, so their result value is actually mapped to its
operand's lowered value.
For instance input ports, we lower them using backedges to take
advantage of the graph structure of the HW dialect and eliminate some
extra wires.  The port's value is mapped to the backedge, until we find
the connect operation driving it, at which point the backedge is
replaced with its true value, and the lowering table is updated.
We can have a situation where an input port is lowered to point to a
backedge, and a no-op cast of the port is also lowered to point to the
backedge.  When the backedge is replaced, the lowering table is only
updated for the input …

[FIRRTL][LowerToHW] Fix issue with backedges not being replaced

---

docs/Dialects/HWArith/RationaleHWArith.md
include/circt/Dialect/HWArith/CMakeLists.txt
include/circt/Dialect/HWArith/HWArithDialect.h
include/circt/Dialect/HWArith/HWArithOps.h
include/circt/Dialect/HWArith/HWArithOps.td
include/circt/Dialect/HWArith/HWArithTypes.h
lib/Conversion/HWArithToHW/HWArithToHW.cpp
lib/Dialect/HWArith/CMakeLists.txt
lib/Dialect/HWArith/HWArithDialect.cpp
lib/Dialect/HWArith/HWArithOps.cpp
test/Conversion/HWArithToHW/test_basic.mlir
test/Dialect/HWArith/basic.mlir

This PR adds the missing comparison operator (https://github.com/llvm/circt/issues/3549) as well as implements the lowering to `comb`. I can also split this PR into two separate ones, if preferred.

[HWArith][HWArithToHW] Implement ICmp

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h
include/circt/Dialect/FIRRTL/InnerSymbolTable.h
lib/Dialect/FIRRTL/InnerSymbolTable.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/errors.mlir

Split construction into verification paths.
Do verification as part of circuit-level inner symbol verification, which is building all the IST's already (and is required to be parent of any IST).
Add some tests for duplicate symbol errors.
Fixes #3531.

[FIRRTL][IST] Verify inner symbols are unique.

---

.github/workflows/uploadBinaries.yml

In order to be easily usable with Chisel soon, CIRCT should provide pre-built binaries at least for macOS and Linux. Currently pre-built Linux binaries are manually uploaded whenever a new build is made. This PR adds a Github Actions script that builds and uploads macOS and Linux binaries whenever a release (or pre-release) is made (requested in #2842). The build from scratch takes approximately 2 hours.
The generated binaries are not fully static but are portable enough to run on base versions of macOS and Ubuntu/other Linuxes. The dynamic linking ends up looking like this:
Linux:
```
$ ldd firtool
linux-vdso.so.1 (0x00007ffc10fd1000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f19d67c3000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f19d6441000) …
```

Github Actions: automatically build and upload binaries on release 

---

docs/Charter.md
docs/Dialects/Comb/RationaleComb.md
docs/Dialects/HW/RationaleHW.md
docs/Dialects/SV/RationaleSV.md
docs/GettingStarted.md

Seems like these links were not updated when the corresponding files were moved into separate subfolders.

[Docs] Fix hw, comb and sv dialect links

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/max-terms.mlir

This fixes a bug that sv.wire is created in a procedural region when `hoistNonSideEffectExpr` returns true but hoists the op one level up. Fixes https://github.com/llvm/circt/issues/3547.

[PrepareForEmission] Don't spill wires in procedural regions

---

include/circt/Conversion/Passes.td
lib/Conversion/FIRRTLToHW/CMakeLists.txt
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/firtool/firtool.fir
test/firtool/memory.fir
tools/firtool/CMakeLists.txt
tools/firtool/firtool.cpp

In `LowerToHW`, FIRRTL registers are lowered to the Seq register.
Complete connects to the registers are mapped to the `next` value. Partial updates, for either bundles or arrays, use functional-style `hw.struct_inject` or `hw.array_concat` operations to update individual fields. Registers with no connects or no connects to some of their fields or indices set their next value to themselves. The self-parallel-assignment is then eliminated in `PrettifyVerilog`. Partial updates are also simplified before Verilog emission.
Random initialisation is now delegated to the lowering of the FIR registers in the `Seq` dialect.

 [SV][Seq][FIRRTL] Lowered FIRRTL registers to `seq.firreg` 

---

lib/Conversion/HWArithToHW/CMakeLists.txt
lib/Conversion/HWArithToHW/HWArithToHW.cpp
test/Conversion/HWArithToHW/test_basic.mlir

Fixes #3635. Adds signature conversion for `hw::HWModuleOp,hw:HWExternalModuleOp` (`mlir::populateFunctionOpInterfaceTypeConversionPattern` unfortunately can't be provided an interface, i.e. `HWModuleLike`) as well as conversions for 'other' operations which we expect to be mixed in with `hwarith` operations.
Let me know if I've missed any ops for the `ArgResOpConversion` pattern. Any operation which we expect to be used in conjunction with the `ui/si` types of the `hwarith` operations must (unfortunately) be explicitly mentioned.

[HWArithToHW] Add type conversions for 'other' ops

---

include/circt/Dialect/HW/HWAttributesNaming.td
lib/Dialect/HW/HWAttributes.cpp

Walk the FlatSymbolRefAttr, not the StringAttr.
cc @nandor , hopefully this fixes RAUW of symbols not updating references within InnerRefAttr's?

[HW][FIRRTL] Fix InnerRefAttr's subelement walk/replace.

---

docs/Dialects/SSP/RationaleSSP.md
include/circt/Dialect/SSP/Utilities.h
lib/Dialect/SSP/CMakeLists.txt
lib/Scheduling/CMakeLists.txt
lib/Scheduling/TestPasses.cpp
test/Dialect/SSP/roundtrip.mlir

This PR adds the missing pieces to link the SSP dialect to the scheduling infra.
NB: It's debatable whether the `-ssp-roundtrip` pass should live with the other scheduling test passes. I mostly put it in there because SSP doesn't have the pass boilerplate yet. However, my current plan is to rework all of this anyways, and replace the test passes with a (public) `-schedule` pass to operate on SSP IR.

[SSP] Add SSP <-> circt::scheduling conversion utilities.

---

include/circt/Dialect/Calyx/Calyx.td
include/circt/Dialect/Calyx/CalyxOps.h
include/circt/Dialect/Calyx/CalyxStructure.td
lib/Dialect/Calyx/CalyxOps.cpp
lib/Dialect/Calyx/Export/CalyxEmitter.cpp
lib/Dialect/HW/HWAttributes.cpp
test/Dialect/Calyx/emit-custom-primitives.mlir
test/Dialect/Calyx/errors.mlir
test/Dialect/Calyx/round-trip.mlir

Attempt to solve #2923, using the hw.module.extern operation to represent primitives as suggested. There are two known issues with this implementation currently:
1. Requires a modification to the HWModuleExtern Op to allow it to be used within a Calyx Program Op. Currently this is done by just removing the requirement that HWModuleExtern Ops must have a ModuleOp as a parent. Let me know if there is a better way to handle this issue.
2. HWModuleExtern does not natively support attributes per port in the same way Calyx ComponentOp does. These attributes will be required in the future to fully support external primitives. Please let me know what the correct course of action is here. The two paths I have considered are modifying HWModuleExtern to support these per port attributes or …

[Calyx] Add calyx primitive operation using hw.module.extern

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h
include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
include/circt/Dialect/FIRRTL/InnerSymbolTable.h
include/circt/Dialect/FIRRTL/Namespace.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/InnerSymbolTable.cpp
lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp
lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/imconstprop-aggregate.mlir
test/Dialect/FIRRTL/imconstprop.mlir
test/Dialect/FIRRTL/remove-unused-ports.mlir

This PR updates ports to use `InnerSymAttr` for inner symbols instead of `StringAttr`.
`InnerSymAttr` makes it possible to add symbols per field.
This PR also updates the default symbol to `null` instead of an empty string name.
Before this PR, empty string was used to represent a port with no symbols, 
` portSyms = ["", "@sym1"]`
But this PR updates it to use `null` attribute instead:
` portSyms = [<<NULL ATTRIBUTE>>, [#firrtl<innerSym@sym1>]`
I am not sure if it is a good idea to add `null` attribute instead of the empty string in the IR.

[FIRRTL] Update port symbols to InnerSymAttr

---

frontends/PyCDE/src/pycde/behavioral.py
frontends/PyCDE/src/pycde/system.py
frontends/PyCDE/test/behavioral.py

The `Else` global object was holding on to refs after __exit__. This
shouldn't have been a global object reference to begin with.
Fixes #3660 .

[PyCDE] Fix liveOperations bug

---

include/circt/Dialect/HW/HWAggregates.td
lib/Dialect/HW/HWOps.cpp

The verifier ensures that the types of the constituent fields match.

[HW] Added verifier for `hw.struct_create`

---

include/circt-c/Dialect/ESI.h
include/circt/Dialect/ESI/ESIServices.h
include/circt/Dialect/ESI/ESIServices.td
integration_test/Bindings/Python/dialects/esi.py
lib/Bindings/Python/ESIModule.cpp
lib/CAPI/Dialect/ESI.cpp
lib/Dialect/ESI/ESIServices.cpp

Enables writing service generators in Python. Also switches to
string-base 'impl_types' (from Attributes) since Attributes are tied to
a context whereas Passes are not. Simplifies things by not having to
create a registry for each context.

[ESI] Make service generators registerable in Python

---

lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp

PrintF ops must be added to a name table to allow them to be targeted by annotations.

[FIRRTL] Allow annotations to be placed on PrintF ops

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

Allowed array indexing to be inlined in nested contexts.

[ExportVerilog] Inline array element accesses

---

include/circt/Dialect/HW/HWAggregates.td
lib/Dialect/HW/HWOps.cpp
test/Dialect/HW/canonicalization.mlir

This commit adds a batch of canonicalizers to the ops working with arrays and structures.
- Simplified chains of inject ops into struct creates if all fields set
- Eliminated injects which are overwritten by other injects
- Canonicalized concatenation of array creates into a single array create
- Converted slices of concatenations into concatenations of slices
- Pushed array gets into slices and concatenations
- Merged a slice of a slice into a single slice
- Converted single-element slices to an array creation with a single element
- Simplified slices of array creates

[HW] Added canonicalizers for aggregate operations

---

include/circt/Dialect/FIRRTL/FIRRTLUtils.h
include/circt/Support/FieldRef.h
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
lib/Dialect/FIRRTL/Transforms/SFCCompat.cpp
test/Dialect/FIRRTL/sfc-compat.mlir

This adds support for aggregate typed registers to the SFC compat pass.
SFC Compat looks at the values which are connected to registers; if they
are all invalid the reset can be removed, and resets for async registers
require a constant reset value.
Previously, this used the function `getModuleScopedDriver` which only
handles ground types.  This creates a function `walkDrivers` which
performs a similar operation, but applies a call back when it finds
which fields of the aggregate is driven by some other value. Since the 
source value and the the destination value might both be aggregates, the 
callback uses FieldRefs to indicate the field.
As a follow up it might make sense to replace uses of
`getModuleScopedDriver` with `walkDrivers`.

[FIRRTL][SFCCompat] Add support for aggregates

---

include/circt/Dialect/FIRRTL/CHIRRTL.td
include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h
include/circt/Dialect/FIRRTL/FIRRTLStatements.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
lib/Dialect/FIRRTL/CHIRRTLDialect.cpp
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/AddSeqMemPorts.cpp
lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
lib/Dialect/FIRRTL/Transforms/FlattenMemory.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
lib/Dialect/FIRRTL/Transforms/InferReadWrite.cpp
lib/Dialect/FIRRTL/Transforms/InferResets.cpp
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/MergeConnections.cpp
tools/circt-reduce/Reduction.cpp

Leave FIRRTLType parent, for including non-base types in the future.
(split off from #3653)

[FIRRTL] Organize all existing types under FIRRTLBaseType.

---

integration_test/lit.cfg.py

If multiple ieee-sims are found, only the last one should be used. As substitution considers the first match, all other substitution entries need to be dropped.

[IntegrationTest] Ensure correct ieee-sim selection

---

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
test/Dialect/FIRRTL/imdce.mlir

This PR makes IMDCE propagate constant output ports to caller sides before
actually performing dataflow analysis so that we can eliminate constant output ports.

[IMDCE] Forward constant output ports to caller sides

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/dedup-errors.mlir

When printing the error message for deduplication failure, the error
printed for a stack of error messages is quite large and hard to read.
This makes an incremental improvement to the stack of error messages.
The most important improvement is that it prints as a single diagnostic
with a single `error:` emitted.
Before:
```
design.fir:1:1: error: module "Top0" not deduplicated with "Top1"
circuit Top :
^
design.scala:135:24: note: first instance targets module "Mid0"
design.scala:135:24: note: second instance targets module "Mid1"
design.fir:4395809:10: error: module "Mid0" not deduplicated with "MId1"
module Mid0:
^
design.scala:64:9: note: first operation has attribute 'message' with value "Assertion failed: 0"
design.scala:64:9: note: second operation has value "Assertion failed: 1" …
```

[FIRRTL][Dedup] Simplify printing of dedup failure of instances

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h
include/circt/Dialect/FIRRTL/FIRRTLStatements.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/errors.mlir

Add `firrtl.ref<T>` as new FIRRTLType, first type that's not a base type (see #3666).
Part of XMR effort, see #3566 for details and motivation.
----
BaseType:
Existing FIRRTL operations are closed under FIRRTLBaseType, keeping this new type separate makes it straightforward to ensure it's not used in unexpected ways or places.  Only a few places are allowed to use non-base types such as module ports.
FIRRTLBaseType's describe circuit entities and their types, where as "RefType" captures data-flow (to a remote value), and should not be used in most places.  Can't use it as a register's type, so on.  This approach also avoids the need to give "hopefully conservatively correct" answers to FIRRTLType helper methods querying, e.g., bitwidth and whether it is a ground or passive type-- as any …

[FIRRTL] Add RefType, first non-base type.

---

frontends/PyCDE/src/pycde/behavioral.py
frontends/PyCDE/src/pycde/module.py
frontends/PyCDE/src/pycde/support.py
frontends/PyCDE/src/pycde/value.py

Using `__new__` to redirect construction to a specialized class had too
many side-effects. Trying to get around them led to convoluted code.
Move back to a function-based dispatch method.

[PyCDE][NFC] Value: revert fancy __new__ dispatch method

---

include/circt/Dialect/MSFT/MSFTConstructs.td
include/circt/Dialect/MSFT/MSFTOps.td
lib/Dialect/MSFT/MSFTOps.cpp
test/Dialect/MSFT/constructs.mlir
test/Dialect/MSFT/opt-errors.mlir

The `msft.hlc.linear` operation defines a linear datapath. It serves as a container for `hw`, `comb` and `msft` operations, with the following restrictions:
- Not graph-like - only SSA def-use chains are allowed.
- `seq` ops are not allowed.
- Exactly one port must be an `i1` signal tagged with a `msft.clock` `UnitAttr`. This signal will be required during lowering.

[MSFT] Introduce `LinearOp`

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

This commit first fixes incorrect inlining issue( https://github.com/llvm/circt/issues/3603) of automatic logic by restricting `isExpressionEmittedInlineIntoProceduralDeclaration` for read inout op. More specifically, a read from wire is fine but we have to be more careful about reg and logic because they can be assigned with blocking assignments. This PR changes   `isExpressionEmittedInlineIntoProceduralDeclaration` to check users of reg or logic and ensure that there is no blocking assignment.

[ExportVerilog] Fix incorrect inlining of automatic logic 

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir

This implements a mechanism to inline blocking assignments into automatic logic declarations in the new emission mode. 
We can inline blocking assignment into automatic logic declrations if:
1. There exists a single blocking assignment which dominates all users of logic reads.
2. The source value of the assign can be inlined into the declaration. This is checked by  `isExpressionEmittedInlineIntoProceduralDeclaration`. 
Depends on https://github.com/llvm/circt/pull/3691

[ExportVerilog] Inline logic assignments into decl in new emission mode

---

lib/Dialect/FIRRTL/Import/FIRLexer.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Import/FIRTokenKinds.def
test/Dialect/FIRRTL/parse-errors.fir
test/Dialect/FIRRTL/parse-version.fir

Firrtl spec 1.1.0 added version identifiers to the fir file.  Update the parse to parse these.  Currently nothing is done with the version after parsing.

[FIRRTL] Support optional version in fir files

---

frontends/PyCDE/src/pycde/module.py
frontends/PyCDE/src/pycde/system.py
frontends/PyCDE/test/test_import_hw_modules.py
lib/Bindings/Python/circt/dialects/_hw_ops_ext.py

This can be used to load HW modules from an MLIR file on disk, and
insert them into a fresh System.

[PyCDE] Add new API to import existing HW modules into a System.

---

frontends/PyCDE/src/pycde/fsm.py

Fixes an issue in PyCDE gen_fsm helper that causes all transitions to use the last guard. Fix captures the intended guard_port name at lamba creation time.

[PyCDE] Capture guard_port name at lamba creation time

---

lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp

Handle `InstanceOp` in `InnerSymbol` verifier when verifying uniqueness of field sensitive symbols. Because the inner symbol on `InstanceOp` is not associated with any result, the inner symbol cannot be associated with any field other than `fieldID=0`.

[FIRRTL] Ignore InstanceOp in field sensitive symbol verifier

---

lib/Dialect/ESI/ESIPasses.cpp
test/Dialect/ESI/lowering.mlir

This basic support for none-typed channels, and a simple test. But
upon using none-typed channels for a more complex Handshake circuit,
it became apparent that the ESI lowering for none-typed ports was
missing a couple special cases. This includes a reduced test case and
the fixes I found necessary.

[ESI] Fixes for handling none-typed channels in ports.

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/RandomizeRegisterInit.cpp
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Dialect/FIRRTL/SFCTests/remove-reset.fir
test/firtool/firtool.fir
test/firtool/phase-ordering.fir
test/firtool/register-randomization.fir
tools/firtool/firtool.cpp

This adds a pass that collects all registers in each module, computes
how many bits of random data should be used to initialize them, and
saves this information for each module and register. In FirRegLower,
this is used to create one large random register per module, and
select out the appropriate bits for each register in the initial
block. This ensures the same large random register is created, and the
same bits are always selected for the same register, regardless of
optimizations that may remove registers.

[FIRRTL] Set the parameters for register randomization early.

---

integration_test/Dialect/Handshake/conditional_modification/conditional_modification.mlir
integration_test/Dialect/Handshake/conditional_modification/conditional_modification.py
integration_test/Dialect/Handshake/helper.py
integration_test/Dialect/Handshake/lit.local.cfg.py
integration_test/Dialect/Handshake/tuple_packing/tuple_packing.mlir
integration_test/Dialect/Handshake/tuple_packing/tuple_packing.py

This patch adds additional functionality to handshakes COCOTB helper. 
Pushing the task pipelining transformations into a stable state will require additional test, and this lays the foundation for that.

[Handshake] Extend cocotb helper and add new tests

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp

Make these more like other expressions.
~NoSideEffects seems to be used to mean something like "only modifies state reachable through operands", so I think is fitting here.~
EDIT: NoSideEffects is used to see if an op can be deleted if its result is unused.  This is not the same as what I suggested above, but I think is still appropriate for these ops.
Type inference is especially used by InferResets to update the result type after inferring the operand type (and to propagate changed types).  Implement this so these operations are updated properly without special handling on those paths.
Result naming came along by using `FIRRTLExprOp` (`HasCustomSSAName`), can drop if this is not desired but doesn't seem problematic and neater to include.
Keep type constraints although not needed in …

[FIRRTL][RefOps] NoSideEffects, InferTypeOpInterface, asm result names

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR.mlir

The `LowerXMRPass`  replaces every `RefResolveOp` with a verbatim expr op encoding the corresponding XMR.
The pass also removes every value of `RefType` and its uses from the circuit.
This is a dataflow analysis over a very constrained `RefType`. Domain of the dataflow analysis is the set of all `RefSendOp`.
Essentially every `RefType` value must be mapped to one and only one `RefSendOp`.
The analysis propagates the reachable `RefSendOp` to every value of `RefType` across modules.
The `RefResolveOp` is the final leaf into which the dataflow must flow into.
Due to the downward only reference constraint on XMRs, the post order traversal ensures that the `RefSendOp` will be encountered before any user of the `RefType` value. The pass fails and errors out if every "live" `RefType` value is …

[FIRRTL] Lower RefType Operations to XMR

---

frontends/PyCDE/pyproject.toml
frontends/PyCDE/src/pycde/testing.py
frontends/PyCDE/test/cocotb_testbench.py

No more custom makefile generation and 'make' commands - this is handled by cocotb-test.
Eventually, we expect support for driving cocotb from within python to be included in a future cocotb release. The support in `cocotb-test` is currently identical to the (unreleased) support in upstream `cocotb`. Hence, we use `cocotb-test` since they publish a pypi package that can be easily downloaded.

[PyCDE] Use cocotb-test as test driver

---

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
test/Dialect/FIRRTL/imdce.mlir

Note: when deleting dead ports, IMDCE introduces temporary wires
for the ports (inside the module) and at points of instantiation.
These are invalid for ref type, which isn't ideal, but they will be erased.
In one case this is not temporary, which this checks for,
the case where an output ref port is alive but not used by instantiators.
I'm not sure this can be constructed presently, given limitations
on uses and use-count of ref ports.

 [FIRRTL][IMDCE] Test deleting code w/ref's. Avoid temp ref wire. 

---

lib/CAPI/Dialect/CMakeLists.txt

The CIRCTCAPIMSFT library depends on MSFTTransforms, and is currently
failing to link when creating shared libraries.
```
ld: tools/circt/lib/CAPI/Dialect/CMakeFiles/obj.CIRCTCAPIMSFT.dir/MSFT.cpp.o: in function `operator()':
/circt/build-release/tools/circt/include/circt/Dialect/MSFT/MSFTPasses.h.inc:373: undefined reference to `circt::msft::createDiscoverAppIDsPass()'
ld: /circt/build-release/tools/circt/include/circt/Dialect/MSFT/MSFTPasses.h.inc:383: undefined reference to `circt::msft::createExportTclPass()'
ld: /circt/build-release/tools/circt/include/circt/Dialect/MSFT/MSFTPasses.h.inc:393: undefined reference to `circt::msft::createLowerConstructsPass()'
ld: /circt/build-release/tools/circt/include/circt/Dialect/MSFT/MSFTPasses.h.inc:403: undefined reference to …
```

[MSFT][CAPI] Fix library dependencies

---

.github/workflows/uploadBinaries.yml

While trying to use the Mac firtool pre-built binary on a larger design I noticed that it sometimes throws bogus errors, for example saying that a value is not fully initialized when in fact it is, while the Linux prebuilt binary works just fine on the same file. I did some testing and determined that these errors appear in the Mac CIRCT build if using gcc instead of clang. I'm not sure what the cause is -- I looked at the build logs using gcc and noticed there were warnings about weak symbol visibility during linking, but I'm not sure what these warnings really mean.
This PR switches the Mac build to use clang instead of gcc. Firtool now looks like this:
```
$ otool -L firtool
firtool:
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0) …
```

[Github Actions] Fix macOS build by switching to clang

---

.github/workflows/buildAndTest.yml

Has been silently failing for some time, pointed at non-existent
directory to find the compilation database.
While visiting, let clang-tidy operate in parallel as it can take
a small but non-trivial amount of time to process each file.

[CI] Fix invocation of clang-tidy.

---

include/circt/Dialect/FIRRTL/Passes.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/Transforms/RandomizeRegisterInit.cpp
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/firtool/register-randomization.fir
tools/firtool/firtool.cpp

This now tracks when randomized registers exceed a threshold, and
splits them up into multiple registers. This is intended to work
around register size limits in simulators that may be exceeded by
using a single large register to hold all of the random bits for each
module.

[FIRRTL] Extend register randomization to split up large registers.

---

integration_test/Target/ExportSystemC/basic.mlir
lib/Target/ExportSystemC/CMakeLists.txt
lib/Target/ExportSystemC/EmissionPrinter.cpp
lib/Target/ExportSystemC/EmissionPrinter.h
lib/Target/ExportSystemC/ExportSystemC.cpp
lib/Target/ExportSystemC/Patterns/HWEmissionPatterns.cpp
lib/Target/ExportSystemC/Patterns/HWEmissionPatterns.h
lib/Target/ExportSystemC/Patterns/SystemCEmissionPatterns.cpp
lib/Target/ExportSystemC/RegisterAllEmitters.h
test/Target/ExportSystemC/basic.mlir
test/Target/ExportSystemC/errors.mlir

Add emission patterns for `!systemc.in`, `!systemc.out`, `!systemc.inout`, and HW integers which map to different unsigned types in SystemC depending on the bit-width. I couldn't find any information on the max bit-width of each SystemC type in the IEEE spec, but it becomes clear what they are doing when reading the SystemC implementation (so I couldn't link a spec section in the emission pattern).
Also improves the error reporting in the emission printer a bit.

[ExportSystemC] Integer and port type emission

---

include/circt/Conversion/Passes.td
integration_test/Target/ExportSystemC/basic.mlir
lib/Conversion/HWToSystemC/CMakeLists.txt
lib/Conversion/HWToSystemC/HWToSystemC.cpp
lib/Conversion/PassDetail.h
lib/Target/ExportSystemC/CMakeLists.txt
lib/Target/ExportSystemC/EmissionPattern.h
lib/Target/ExportSystemC/EmissionPatternSupport.h
lib/Target/ExportSystemC/EmissionPrinter.h
lib/Target/ExportSystemC/ExportSystemC.cpp
lib/Target/ExportSystemC/Patterns/EmitCEmissionPatterns.cpp
lib/Target/ExportSystemC/Patterns/EmitCEmissionPatterns.h
lib/Target/ExportSystemC/Patterns/SystemCEmissionPatterns.h
lib/Target/ExportSystemC/RegisterAllEmitters.h
test/Conversion/HWToSystemC/structure.mlir
test/Target/ExportSystemC/basic.mlir

Use the emitc.include operation to add includes during lowering or transformations instead of hardcoding them in the printer. Add basic support in HWToSystemC and ExportSystemC.

[SystemC] Don't hardcode includes

---

integration_test/Dialect/Handshake/lit.local.cfg.py
integration_test/Dialect/Handshake/tp_memory/tp_memory.mlir
integration_test/Dialect/Handshake/tp_memory/tp_memory.py
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
test/Conversion/StandardToHandshake/test22.mlir
test/Conversion/StandardToHandshake/test23.mlir
test/Conversion/StandardToHandshake/test24.mlir
test/Conversion/StandardToHandshake/test25.mlir
test/Conversion/StandardToHandshake/test26.mlir
test/Conversion/StandardToHandshake/test_call.mlir
test/Conversion/StandardToHandshake/test_feedforward.mlir

This commit fixes a faulty guard mux input order in the feed-forward task pipelining transformation.
Instead of wrongly assuming a given relation between the mux input order and the cmerge inputs, it has to be checked for each case separately.
The provided test was affected by this faulty ordering and thus didn't terminate.

[StandardToHandshake] Fix mux input order

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/errors.mlir

This PR relaxes the downward only constraint on the RefType flow. After this change, 
- Modules can have input ports of `RefType`
- Instance ops can connect RefType input/output ports to module input/output ports according to connect semantics.
- There is no constraint to where a `ref.resolve` can occur relative to `ref.send` in the instance hierarchy
There are no additional verifiers added to constraint the `RefType` flow, but the LowerXMR pass must error out, if multiply instantiated modules with `RefType ` ports are encountered.

[FIRRTL][RefOps] Remove downward-only constraint from RefType

---

lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp
lib/Dialect/FIRRTL/Import/FIRAnnotations.h
lib/Dialect/FIRRTL/Import/FIRParser.cpp

Since we switched to using LowerAnnotations exclusively, we no longer
attach annotations to the IR while its being generated.  This lets
us remove the `targetMap` and associated logic for attaching annotations
to FIRRTL entities from the parser.
This also changes the "raw annotation" parsing path to append all
annotations to a SmallVector instead of recording them in the
`targetMap` using the "rawAnnotations" key.

[FIRParser] Remove more old annotation handling code

---

include/circt/Dialect/Pipeline/Pipeline.h
include/circt/Dialect/Pipeline/Pipeline.td
lib/Dialect/Pipeline/CMakeLists.txt
lib/Dialect/Pipeline/PipelineOps.cpp
test/Dialect/Pipeline/errors.mlir
test/Dialect/Pipeline/round-trip.mlir

The `pipeline.rtp` operation represents a retimeable pipeline.
The pipeline contains a single block representing a graph region. Pipeline stages are represented by `pipeline.rt.register` operations. Semantics of values crossing register boundaries are defined by lowering passes.
The pipeline representation is centered around providing latency insensitive values (valid signals between stages). Such signals can either be removed (in the feedforward, statically scheduled case), used to control stalling (feedback, statically scheduled case) or in conjunction with handshake signals for dynamically scheduled pipelines.
Alongside this, some old, unused code (StandardToStaticLogic) is pruned to remove a maintenance burden associated with this change.
A typical flow would go like this:
An untimed …

[Pipeline] Add retimeable pipeline operation

---

lib/Dialect/FIRRTL/Transforms/InferReadWrite.cpp
test/Dialect/FIRRTL/inferRW.mlir

The `InferRW` pass transforms a memory with read and write ports to a single 
ReadWrite port memory, if it can prove that the read and write enable are
mutually exclusive. The algorithm checks if any of the terms in the `And`
expression tree of read and write enable is a complement of each other, to
infer if the read and write enable are trivially mutually exclusive.
The `RWmode` of the ReadWrite memory is set to `1` to use the memory in
write mode and `0` for read mode. 
This PR sets the `RWmode` to the term in the `And` expression tree of
the write enable, which proves the mutual exclusion, instead of
setting it to the write enable. This is done to ensure equivalence with the
`firrtl` compiler.
For example, if, `write enable = A && B`, `read enable = C && ~B`
implies `RWmode = B`.

 [FIRRTL][InferRW] Set RWmode to the complement term in Write enable 

---

integration_test/Dialect/FSM/simple/top.mlir
integration_test/Dialect/FSM/variable/top.mlir
lib/Conversion/FSMToSV/FSMToSV.cpp
test/Conversion/FSMToSV/test_basic.mlir

... also emits the FSM typedefs in a separate file to avoid polluting all generated files with FSM typedefs.

[FSMToSV] Share typescope between FSMs

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/sv-always-wire.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir

Previously if a temporary wire is required for a constant, localparam op is created. However sometimes we truly want to have wires for constants, for example when we want to create wires for sensitivity lists. In such cases the output verilog looks weird because we create an additional temporary wire for localparam. Therefore this PR stops creating a localparam op for constants in the first place.

[PrepareForEmission] Don't create localparam as a temporary wire

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR-error.mlir
test/Dialect/FIRRTL/lowerXMR-errors.mlir
test/Dialect/FIRRTL/lowerXMR.mlir

This PR updates the `LowerXMR`  to remove the `RefType` constraint of downward only reference.
The algorithm now requires a second pass over the modules, to propagate the reference from top to bottom. The first pass propagates the `ref.send` from bottom to top.

[FIRRTL][RefOps] LowerXMR: Handle upward references

---

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
test/Dialect/FIRRTL/imdce.mlir
test/firtool/firtool.fir

This PR backports #3378 and #3688 into sifive-1.5 branch to address SiFive internal use cases. #3688 implements empty module removal for IMDCE and #3378 is a minor improvement to propagate constants within IMDCE.

[FIRRTL] Backport IMDCE updates to sifive 1.5

---

include/circt/Dialect/FIRRTL/FIRRTLInstanceGraph.h
lib/Dialect/FIRRTL/FIRRTLInstanceGraph.cpp

Add helper to replace an old `InstanceOp` with a new `InstanceOp` to keep the InstancePathCache updated.

[FIRRTL] Keep InstancePathCache updated

---

include/circt/Dialect/ESI/ESIServices.td
lib/Dialect/ESI/ESIPasses.cpp
lib/Dialect/ESI/ESIServices.cpp
test/Dialect/ESI/services_collateral.mlir

Matches more closely what the software API builder is going to produce.
Take information out of "top_levels" section as it is now redundant. Also
adds capnp information (if compiled in) to types in modules section.

[ESI][Services.json] Add "modules" section

---

lib/Dialect/SV/Transforms/PrettifyVerilog.cpp
test/Dialect/SV/prettify-verilog.mlir

Removing self-assignments leaves registers unassigned, resulting in errors in verification tools. This change preserves them.

[PrettifyVerilog] No longer remove self-assignments to whole names

---

lib/Dialect/FIRRTL/Transforms/FlattenMemory.cpp
test/Dialect/FIRRTL/flatten-memory.mlir

The `FlattenMemory` pass "flattens" the aggregate data of memory into a `UInt`, and inserts appropriate bitcasts to access the data. This commit fixes a divide by zero crash in the pass.
Update the pass to ignore a memory under the following conditions
1. If the data field is ground type.
2. If the aggregate data field has a single element.
3. If the total width of the data field is zero or unknown.

 [FIRRTL][FlattenMemory] Ignore zero width and trivial data memory 

---

lib/Dialect/ESI/ESIPasses.cpp

The StringRef is backed by the schema object, which goes out of scope
immediately.  Give the json a std::string so it has its own copy.
Caught by asan (and valgrind).
(on lit test "Dialect/ESI/services_collateral.mlir")

[ESI] Fix use-after-free.

---

include/circt/Conversion/StandardToHandshake.h
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp

This PR ensures that the last part of the `std-to-handshake` pass is exposed as well.

[StandardToHandshake] Expose post dataflow converison

---

.github/workflows/buildAndTest.yml
.github/workflows/buildAndTestWindows.yml

In two places, we create very large cache objects containing both the `build` and `install` directories for LLVM.
We generally don't seem to need the `build` directory, other than for grabbing `lit`.
Try trimming the cached paths to `install` and just the `lit` entry point (actually implementation is in LLVM's source).
If lit breaks, maybe we can just grab it from the PyPi package: https://pypi.org/project/lit/ .
Hopefully this helps improve CI performance by evicting cache entries less often.
cc #3761 .

[CI] Try to trim cached LLVM builds

---

include/circt/Support/LoweringOptions.h
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
lib/Support/LoweringOptions.cpp
test/Conversion/ExportVerilog/variadic-operand-splitting.mlir

Add a command line option and PrepareForEmission functionality to split
variadic arguments whose operands are composed of many terms.  This is
done to enable large product-of-sum or sum-of-product terms from growing
so large (during inline emission) that they cause poor simulator
performance.  Specifically, this fixes a 10x increase in Verilog
compilation time for Synopsys VCS for an internal design.

[firtool][HW] Add variadic operation splitting

---

lib/Analysis/DependenceAnalysis.cpp
test/Conversion/HWToLLVM/convert_aggregates.mlir
test/Conversion/LLHDToLLVM/convert_signals.mlir
test/Conversion/LLHDToLLVM/signal-init.mlir
test/Dialect/FIRRTL/expand-whens.mlir
tools/handshake-runner/Simulation.cpp

1. Rename `getEnclosingAffineForAndIfOps` to `getEnclosingAffineOps`: The utility was extended to also support affine.parallel ops) The commit: https://github.com/llvm/llvm-project/commit/26fedf92c3122ff51fb27f434a8c5b5a47da8f94
2. Update lit tests to make DefaultValueAttr, not optional! https://github.com/llvm/llvm-project/commit/af3ed4a2a760580e9f0e04c7320edafc575d02b8
3. Move `hasValue` to `has_value`

Bump LLVM to  1bcf21c

---

test/firtool/firtool.mlir
tools/firtool/CMakeLists.txt
tools/firtool/firtool.cpp

Upstream MLIR has recently introduced bytecode serialization support: [commit](https://github.com/llvm/llvm-project/commit/f3acb54c1b7b7721cea5c07f64194151dddd3c4b) , [RFC](https://discourse.llvm.org/t/rfc-a-binary-serialization-format-for-mlir/63518).
This PR bumps LLVM to include the new bytecode support and adds support for it to firtool.
`circt-opt` already knows how to handle this, and can emit it via `-emit-bytecode` flag.
firtool modifications:
* Support emitting bytecode via new `-emit-bytecode` flag.
* Use the `-f` flag to force printing to terminal.
*  Support reading bytecode -- MLIR parser handles this for us, but also autodetect if ends with ".mlirbc" or if has the requisite magic bytes (`mlir::isBytecode`).  (maybe we could detect FIR > 1.1.0 this way as well in the …

[FIRRTL][firtool] Add support for reading/writing bytecode

---

tools/firtool/firtool.cpp

Towards aggregate preservation, this PR disables CheckCombCycles for now when aggregate preservation is enabled.

[FIRTOOL] Skip CheckCombCycles pass when aggregate preservation is enabled

---

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
test/Dialect/FIRRTL/inliner.mlir

This PR adds support to handle inlining of RefType ops. Temporary wires of
RefType that are created to replace ports of inlined modules, must be removed.
As a post-processing step, the pass iterates over all the `RefType` wires, which
were added during the inlining transformation. Then replaces all the uses of the
wire with its driver, and marks the wire for removal. Some of the uses of the
wire need to be moved to ensure the driver dominates the uses.

[FIRRTL] ModuleInliner: Add support for RefType

---

tools/firtool/firtool.cpp

This commit adds the `LowerXMR` pass to the firtool pipeline and enables it by default. This is required since the `LowerToHW` pass cannot handle `RefType`, so all ops and ports of `RefType` must be removed.

[firtool] Enable LowerXMR by default

---

lib/Conversion/FSMToSV/FSMToSV.cpp
test/Conversion/FSMToSV/test_basic.mlir

This fixes an error where constant operations would get lifted to the enclosing region (e.g. through canonicalization) due to the "lack" of `IsolatedFromAbove` trait in the `fsm.machine`.
This commit will copy any constants defined within the enclosing scope, fixing the immediate issue.

[FSMToSV] Copy constants into `fsm.machine`

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/disallow-local-vars.mlir
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir

This PR fixes the issue https://github.com/llvm/circt/issues/3786 by allowing read_inout to be inlined for bit-select op. 
There is a contradiction between `isExpressionAlwaysInline` and `isOkToBitselectFrom`: `isExpressionAlwaysInline` requires read_inout op to be always inlined, on the other hand  `isOkToBitselectFrom` disallows read op to be inlined for bit-select op. This contradiction causes the bug that temporary wires disappears with the new ExportVerilog emission mode. 
It is syntactically correct to inline read op as defined in the SV spec:

[ExportVerilog] Inline read inout op used by bitselect

---

include/circt/Dialect/SystemC/SystemCStatements.td
include/circt/Dialect/SystemC/SystemCStructure.td
include/circt/Dialect/SystemC/SystemCTypes.td
include/circt/Dialect/SystemC/SystemCTypesImpl.td
test/Dialect/SystemC/module-error.mlir

Instead of defining a custom type for void functions, we can reuse the builtin function type and define a ODS constraint to limit the function type to have zero inputs and results.

[SystemC] Replace func_handle with builtin function type

---

docs/Dialects/Comb/RationaleComb.md
include/circt/Dialect/Comb/Combinational.td
lib/Conversion/CalyxToHW/CalyxToHW.cpp
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Conversion/FSMToSV/FSMToSV.cpp
lib/Conversion/HWArithToHW/HWArithToHW.cpp
lib/Conversion/MooreToCore/MooreToCore.cpp
lib/Dialect/Calyx/Transforms/CompileControl.cpp
lib/Dialect/Calyx/Transforms/PassDetails.h
lib/Dialect/Comb/CombFolds.cpp
lib/Dialect/Comb/CombOps.cpp
lib/Dialect/ESI/capnp/Schema.cpp
lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
test/Conversion/FIRRTLToHW/emit-chisel-asserts-as-sva.mlir
test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Conversion/FIRRTLToHW/zero-width.mlir
test/firtool/firtool.fir

Comb exists in a place where it might or might not need to deal with Verilog or VHDL weirdness.  Some transformations which are desirable might not be semantic preserving with respect to concepts such as 'x'.  This is overly strong for a number of languages.  An "bin" flag is added to most operations to allow flagging the comb operation as only requiring binary semantics.  Frontends by construction, or by analysis can enable this flag to enable richer comb-level optimizations.

[COMB] Add flag to assert binary behavior.

---

integration_test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/HWRename.fir
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/PortDelete.fir
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir
test/Dialect/FIRRTL/SFCTests/data-taps.fir
test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/SFCTests/emit-omir.fir
test/Dialect/FIRRTL/SFCTests/signal-mappings.fir
test/Dialect/FIRRTL/SFCTests/subcircuit-flow/flow.test
test/firtool/chirrtl.fir
test/firtool/memoryLowering.fir
test/firtool/memoryMetadata.fir
test/firtool/print-before.fir
tools/firtool/firtool.cpp

We have many flags which control whether or not we run a specific pass,
such as `--lower-types`.  Most of these flags should never be used by
regular firtool users; they are only really useful for circumventing a
crash in a pass and can often lead to other crashes.  This moves most of
the pass options to be of the form `--disable-mypass`, and makes them
hidden by default.  The descriptions of these options were made
uniform, at the cost of a less detailed description.
The `GrandCentral` pass was enabled by default. Since its behavior is
controlled by annotations, it should always run.
This also did a small sweep to make sure that all our option
descriptions begin with a capital letter.

[firtool] Reorganize pass controlling options

---

integration_test/Bindings/Python/dialects/hw.py
lib/Dialect/FIRRTL/FIRRTLAttributes.cpp
lib/Dialect/HW/HWAttributes.cpp
test/Dialect/HW/errors.mlir

Support round-trip'ing of these, format like:
< "NAME" : T > : T
< "NAME" : T = attr > : T
When printing, don't include attr type as well.
(Previously: #hw.param.decl<"DEFAULT": ui32 = 0 : ui32> : ui32)
These parse methods aren't expected to ever be encountered directly,
but are triggered when using bitcode support.
In the future we can implement hooks to define our own custom
encoding/decoding which will be faster/smaller but for now
the fallback encoding uses the raw assembly.

{HW,FIRRTL}::ParamDeclAttr: Implement "raw" parse, touchup print.

---

lib/Dialect/FIRRTL/Transforms/WireDFT.cpp
test/Dialect/FIRRTL/wire-dft-errors.mlir
test/Dialect/FIRRTL/wire-dft.mlir

Still only wire to clock gates within the DUT, however, if the enable signal
originates outside the DUT handle this and wire it in.
This is not expected to be common/usual, but handle it if requested.
Also detect few other error cases:
* clockgates instantiated in and out the DUT
* enable signal can't reach DUT
(unlikely to happen in practice, but not much more to check)
Fixes #3784.

[FIRRTL][WireDFT] Handle wiring in enable from outside DUT.

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-errors.fir

Also don't allow indentation on the version header/preamble.

[FIRRTL] Touchup version parsing, insist newline before circuit.

---

include/circt/Dialect/SystemC/SystemCStructure.td
include/circt/Dialect/SystemC/SystemCTypes.h
include/circt/Dialect/SystemC/SystemCTypes.td
include/circt/Dialect/SystemC/SystemCTypesImpl.td
integration_test/Target/ExportSystemC/basic.mlir
lib/Dialect/SystemC/SystemCOps.cpp
lib/Dialect/SystemC/SystemCTypes.cpp
lib/Target/ExportSystemC/Patterns/SystemCEmissionPatterns.cpp
test/Dialect/SystemC/module-error.mlir
test/Dialect/SystemC/structure.mlir
test/Target/ExportSystemC/basic.mlir

The plan is to use the more modern constructor that does not take the instance name as a string argument for initialization. This means we only have to connect the ports in the SC_CTOR (in a later PR).

[ExportSystemC] Add InstanceDeclOp emission pattern

---

include/circt/Dialect/SystemC/SystemCStructure.td
lib/Conversion/HWToSystemC/HWToSystemC.cpp
lib/Dialect/SystemC/SystemCOps.cpp
test/Dialect/SystemC/module-error.mlir
test/Dialect/SystemC/structure.mlir

Add an operation to model a C++ destructor that is required to deallocate objects such as a verilated model stored as a pointer that is allocated in the SC_CTOR body.
Also adds a helper function to get the body block more easily and one to the SC_MODULE to get the destructor inside or lazily create one if it does not exist yet. The same helpers are added for the Ctor operation.
Additionally, switch to `attr-dict-with-keyword` to have the attributes before the region for `ctor`, `func`, and `cpp.destructor`.

[SystemC] Add DestructorOp and some helper functions

---

include/circt/Dialect/SystemC/SystemC.td
include/circt/Dialect/SystemC/SystemCExpressions.td
include/circt/Dialect/SystemC/SystemCOps.h
include/circt/Dialect/SystemC/SystemCStatements.td
lib/Dialect/SystemC/CMakeLists.txt
test/Dialect/SystemC/structure.mlir
test/circt-opt/commandline.mlir
tools/circt-opt/CMakeLists.txt
tools/circt-opt/circt-opt.cpp

Also adds a dependency on the EmitC dialect to reuse the pointer and opaque types.

[SystemC] Add NewOp and DeleteOp

---

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp

Add a new utility `addPortsToModule` to add ports to a module and all its instances. This does not connect the new port to anything. Also update all the caches, where the old instance can occur.

[FIRRTL] Add helper to add ports to a module

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/disallow-local-vars.mlir

This PR fixes an issue that logic op is not hoisted to non-procedural region with disallowLocalVariables.
This also improves `rewriteSideEffectingExpr` to handle logic op as well as reg op to reduce the number of 
temporary registers.

[PrepareForEmission] Hoist LogicOp when disallowLocalVariable is enabled

---

include/circt/Dialect/SV/SVExpressions.td
include/circt/Dialect/SV/SVVisitors.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/FIRRTL/Transforms/RandomizeRegisterInit.cpp
lib/Dialect/SV/SVOps.cpp
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir
test/Conversion/ExportVerilog/verilog-basic.mlir
test/Dialect/SV/basic.mlir
test/Dialect/SV/cse.mlir
test/Dialect/Seq/firreg.mlir
test/firtool/register-randomization.fir

Lower-seq-firrtl-to-sv  now doesn't generate temporary registers to hold the random values, rather, it generates local temporaries.  This greatly reduces the number of registers in modules.

[FIRRTL] Improved code generation for register initialization

---

.github/workflows/uploadBinaries.yml

Release binaries produced by the uploadBinaries action now build with a specified version computed using the tag of the release that caused the job to run.

[Github actions] Include release tag version in automated release build

---

lib/Dialect/Calyx/CalyxOps.cpp

This fixes an issue where the PrimitiveOp would have no port attributes in the Calyx CellInterface. It now grabs all the calyx attributes attached to the HWModuleExternOp that is referenced by the PrimitiveOp. This has no effect on emission but allows Calyx MLIR passes to work properly with PrimitiveOps.

Fix Calyx PrimitiveOp attributes

---

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp

Add a helper `borePortsOnPath` to add ports along a sequence of `InstanceOps`. It connects all the ports to each other and forwards a given value from the source module. 
`instancePath` specifies a path from a source module through the `lcaModule` till a target module. Source module is the
module referenced by the first instance on the path  and target module is the referenced target module of the last instance in the instancePath.
If the `lcaModule` is the source module, then we only need to drill input ports starting from the `lcaModule` till the end of `instancePath`. For all other cases, we start to drill output ports from the source module  till the  `lcaModule`, and then input ports from `lcaModule` till the end of  `instancePath`.
This utility is required in …

[FIRRTL] Add ports to a sequence of InstanceOps via an LCA

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/SFCTests/data-taps.fir

In GrandCentral DataTapsAnnotations, there are DataTapModuleSignalKeys which tap signals based on a string `internalPath`. These are typically used on extmodules with the promise that the `internalPath` exists somewhere in the implementation of the extmodule. Generators that cannot distinguish between they are constructing Grand Central annotations on modules or extmodules in their emitted FIRRTL use these unsafe `internalPath`s on actual modules.
This is a patch fix for something we can better implement once GrandCentral is migrated to using RefOps.
Reiterating that this is not great, we could definitely check that the `internalPath` does actually correspond to an op or port. This is a patch solution supporting a use case that will ultimately be replaced by exposing RefOps in the FIRRTL …

[FIRRTL] Support GC internalPath on Modules

---

include/circt/Dialect/SV/SVAttributes.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/firtool/firtool.fir
test/firtool/memory.fir

This PR is a follow up of https://github.com/llvm/circt/pull/3404 to replace verbatim uses with SV attributes.
Fix https://github.com/llvm/circt/issues/3828 by eliminating verbatim from multbitmux lowerings.

[LowerToHW] Use SV attributes to annotate multibit mux pragmas

---

include/circt/Dialect/HW/HWAggregates.td
lib/Dialect/HW/HWOps.cpp
test/Dialect/HW/canonicalization.mlir

Add a `getUniformElement()` helper function to `ArrayCreateOp` which checks if all elements of the created array are identical and returns that uniform value. Add a folder for `ArrayGetOp` that simply forwards this uniform value if it exists.
Fixes #3841.
The following FIRRTL:
```
circuit Foo :
module Foo :
input in0 : UInt<1>
input in1 : UInt<1>
input address : UInt<2>
output out : UInt<1>
node idStall = or(in0, in1)
wire sourceStall : UInt<1>[4]
sourceStall[0] <= idStall
sourceStall[1] <= idStall
sourceStall[2] <= idStall
sourceStall[3] <= idStall
out <= sourceStall[address]
```
Now expands to:
```systemverilog
module Foo(
input        in0,
in1,
input  [1:0] address,
output       out);
wire _GEN;
/* synopsys infer_mux_override */
assign _GEN = in0 | in1;
assign out = _GEN;
endmodule
```

[HW] Canonicalize array get on uniform arrays

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/FIRRTL/FIRRTLStructure.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
lib/Dialect/FIRRTL/Transforms/RemoveUnusedPorts.cpp
tools/circt-reduce/Reduction.cpp

Upstream MLIR removed an overload of `eraseArguments()` in [27e8ee208cb2142514ee2e3ab342dafaf6374f9e](https://github.com/llvm/llvm-project/commit/27e8ee208cb2142514ee2e3ab342dafaf6374f9e) (https://reviews.llvm.org/D132896), stating that the overload isn't useful because we should probably be using BitVector in most cases.
This mostly affected code in the FIRRTL dialect that used SmallVector for holding the list of port indices to delete, which indeed can be replaced with a BitVector.
One thing to be careful about is that while `push_back()` is still defined on BitVector, it has different behavior than `SmallVector<unsigned>::push_back()`, in that the former only allows you to push back a boolean 0 or 1 to the end of the bit vector, while the latter pushes back an integer index. …

[FIRRTL] Use BitVector over ArrayRef/SmallVector for eraseArguments.

---

integration_test/Dialect/Handshake/buffer_init_none/buffer_init_none.mlir
integration_test/Dialect/Handshake/buffer_init_none/buffer_init_none.py
integration_test/Dialect/Handshake/lit.local.cfg.py
lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
test/Conversion/HandshakeToFIRRTL/test_buffer.mlir

Add support to initialize NoneType buffers with tokens. The provided array indicates that the buffer is initialized, but its values are ignored.
I do not like the ignoring of the `initValue` array, but adding a unit attr or something will just increase the different cases we have to support. If you have a good suggestion, please let me know.

[Handshake][HandshakeToFIRRTL] NoneType buffer initialization

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Dialect/FIRRTL/grand-central.mlir

This commit generates verbatim embedded cross-module-reference based on `RefResolveOp`. If the `AugmentedGroundType` annotation can be traced to a `RefType` value, then just use the `verbatim` `Value` substitution instead of the symbols substitution. 
This updates the indices used in the verbatim text, for the value starting at 0 and following indices for symbols. 
Added lit tests, for the `RefType` value, constant value and symbols.

[FIRRTL][GrandCentral] Generate verbatim for RefType Values

---

include/circt/Dialect/ESI/ESIServices.td
lib/Dialect/ESI/ESIOps.cpp
lib/Dialect/ESI/ESIServices.cpp
test/Dialect/ESI/services.mlir
test/Dialect/ESI/services_collateral.mlir

Previously, inout channels were listed as separate input and output ports. This change combines them. To implement this change we refactor some code to base cosim implementation and json service descriptions on (partial) pairs.

[ESI][Bugfix] Combine inout channels in service description

---

include/circt/Dialect/HW/HWOps.h
include/circt/Support/BackedgeBuilder.h
lib/Conversion/CalyxToHW/CalyxToHW.cpp
lib/Dialect/HW/HWOps.cpp

This reverts commit c4e272064d76e75dab7de7d32c5857e01418b5d8. (https://github.com/llvm/circt/pull/3844)
This commit is causing nondeterministic crashes in the test/Conversion/CalyxToHW/basic.mlir test.
This test crashes with about 75% probability on my machine, which is an x86 MacBook running the latest macOS, 12 (Monterey), and with the Apple-provided clang (`Apple clang version 13.1.6 (clang-1316.0.21.2.5)`). When it crashes, I get a stack trace like the following:
```
FAIL: CIRCT :: Conversion/CalyxToHW/basic.mlir (10 of 427)
******************** TEST 'CIRCT :: Conversion/CalyxToHW/basic.mlir' FAILED ********************
Script:
--
: 'RUN: at line 1';   /Users/richardx/git/circt/build/bin/circt-opt /Users/richardx/git/circt/test/Conversion/CalyxToHW/basic.mlir -lower-calyx-to-hw | …
```

Revert "[HW] Address new HWModule builder review comments (#3844)"

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

This PR improves name propagations at FIRRTL canonicalizations. Previsouly useful names (i.e. names without prefix "\_") might not be propagated because of the existence of useless names (i.e. names with prefix "\_"). This PR overwrites useless names if we can find useful names.

[FIRRTLFolds] Improve name propagations

---

include/circt/Support/LoweringOptions.h
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
lib/Support/LoweringOptions.cpp
test/Conversion/ExportVerilog/prepare-for-emission.mlir

Some LINT tool dislikes expression being inlined into instance ports. This PR adds an option to force wires for
input ports. 
Example:
```mlir
hw.module.extern @MyExtModule(%in: i8)
hw.module @MoveInstances(%a_in: i8) -> (){
%0 = comb.add %a_in, %a_in : i8
hw.instance "xyz3" @MyExtModule(in: %0: i8) -> ()
}
```
w/o PR:
```verilog
MyExtModule xyz3 (    // foo.mlir:12:3
.in (a_in + a_in)   // foo.mlir:11:8
);
```
w/ PR and option:
```verilog
wire [7:0] _xyz3_in;  // foo.mlir:12:3
assign _xyz3_in = a_in + a_in;        // foo.mlir:11:8, :12:3
MyExtModule xyz3 (    // foo.mlir:12:3
.in (_xyz3_in)      // foo.mlir:12:3
);
```
CC: @rsetaluri

[PrepareForEmission] Add an option to anchor wiers for input ports

---

include/circt/Dialect/Handshake/HandshakeOps.td
integration_test/Dialect/Handshake/buffer_init_none/buffer_init_none.mlir
lib/Dialect/Handshake/HandshakeOps.cpp
test/Conversion/HandshakeToFIRRTL/test_extmemory.mlir
test/Conversion/HandshakeToFIRRTL/test_join.mlir
test/Conversion/HandshakeToFIRRTL/test_load.mlir
test/Conversion/HandshakeToFIRRTL/test_naming.mlir
test/Dialect/Handshake/join.mlir

Limiting JoinOp's input types to only none seems to be an arbitrary limitation. In fact, the documentation did even show an example of a different input type, but still assumed that all have the same.
There is no use of this in CIRCT directly, but my downstream work does require this.

[Handshake] Change join to accept all input types

---

include/circt/Dialect/Handshake/HandshakeOps.td
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
lib/Dialect/Handshake/HandshakeOps.cpp
test/Conversion/HandshakeToFIRRTL/test_func.mlir
test/Dialect/Handshake/add-ids.mlir
test/Dialect/Handshake/func.mlir

The ctrl in- and outputs are mandatory for DHLS style usage, but in general, they aren't required for well-formed handshaked circuits.
This PR doesn't touch `StartOp` or `EndOp` as they are only used in `std-to-handshake`.

[Handshake] Relax the ctrl in/output requirement

---

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp

When inlining an instance, we create wires to replace its ports and results.
Currently we do this for RefType ports as well, with post-processing to forward their driver through the temporary wire and removing it.  This avoids leaving the wire around for the verifier, which is important as wires cannot be of RefType (non-base type).
In upcoming LLVM bump including introduction of `TypedValue`, types are checked more aggressively and this strategy no longer works.
Instead, emit placeholder values using `BackedgeBuilder` which are resolved and removed similarly.

[FIRRTL][Inliner] Don't create temporary wires of RefType, use Backedge placeholders

---

include/circt/Dialect/SystemC/SystemCStatements.td
include/circt/Dialect/SystemC/SystemCTypes.td
lib/Dialect/SystemC/SystemCOps.cpp
test/Dialect/SystemC/module-error.mlir
test/Dialect/SystemC/structure.mlir

Add an operation to bind the ports of a submodule to a channel or port in the instantiating module. Currently, the in, inout, and out port types and signals are the only supported channels.

[SystemC] Add BindPortOp

---

include/circt/Conversion/Passes.td
include/circt/Dialect/HW/HWOps.h
lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
lib/Dialect/HW/HWOps.cpp
lib/Support/BackedgeBuilder.cpp
test/Conversion/HandshakeToHW/test_simple_loop.mlir

This commit provides the infrastructure used to generate handshake module internals. This initial commit contains implementations of fork and join components, which follow directly from their `HandshakeToFIRRTL` implementation. Any other op in the `test_simple_loop.mlir` test is implemented as an external module. Once this commit is merged, implementations for these will be pushed in followup commits.

[HandshakeToHW] Initial elaboration of module internals

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/prepare-for-emission.mlir

This commit fixes an assertion failure in PrepareForEmission that wrongly tries creating temporary wires for inout operations. In the first place, inout operations are *always inline operations* therefore we might not have to legailze OoO uses of inout operations. But it would be more reasonable to keep the invariance that "after PrepareForEmission, operations in the toplevel module are sorted in the def-use order".
Fix https://github.com/llvm/circt/issues/3831

[PrepareForEmission] Reorder inout ops before legalizing OoO uses

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/grand-central-taps.mlir

This commit adds aggregate support to GrandCentralTaps. 
An annotation "sifive.enterprise.grandcentral.ReferenceDataTapKey.source" might have
field id in aggregate preservation mode if its annotated declaration is not lowered into ground types.
On the other hand, if the annotation target to external module ports, it is guaranteed that ports have 
ground types. The diff added here should be eventually replaced by RefType Implemenation

[FIRRTL] Support aggregate in GrandCentralTaps

---

include/circt/Dialect/Comb/CombOps.h
include/circt/Dialect/Comb/Combinational.td
include/circt/Dialect/HW/HWTypes.h
include/circt/Dialect/HW/HWTypes.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/Comb/CombFolds.cpp
lib/Dialect/Comb/CombOps.cpp
lib/Dialect/HW/HWOps.cpp

This fixes a latent bug in the definition of HWIntegerType that was uncovered when I tried to bump LLVM, where the [new `TypedValue`](https://github.com/llvm/llvm-project/commit/688c51a5acc53b456014e53663051476d825e896) performs a runtime type check in an assertion that fails because of this bug.
I'm going to copy and paste the long commit message I wrote for one of my commits, since I think it explains the problem and the fix, but the tl;dr is:
- HWIntegerType's C++ is now defined to be a union of either an `mlir::IntegerType` or a `circt::hw::IntType`.
- Code that previously assumed that you could get an `mlir::IntegerType` from most of the Ops in Comb now require an explicit cast.
- Code that previously assumed that you could get an `mlir::IntegerType` from most of the Ops in Comb is …

[HW][Comb] Fix HWIntegerType to account for parameterized hw::IntTypes

---

include/circt/Dialect/SystemC/SystemCStatements.td
lib/Conversion/HWToSystemC/HWToSystemC.cpp
test/Conversion/HWToSystemC/structure.mlir

* Merged the `hw.output` operation lowering with the module lowering because it allows for easier code in the instance lowering pattern and there is likely no benefit in a separate lowering pattern as there is exactly one output operation per hw module and it only ever occurs in combination with such a module.
* Added a convenience builder for the `systemc.instance.decl` operation.
* Replaced the usage of `scModule.getOutputPorts()` with a for-loop over all arguments that materializes a list of the output ports because of #3810. I couldn't immediately find a fix for that and didn't want to block this PR on it.
* Default behavior is to insert a signal for each port of each instance and bind the port to it. Then write to that signal or read from it in the update function depending on the …

[HWToSystemC] Add support for lowering hw.instance operations

---

include/circt/Dialect/SystemC/SystemCStatements.td
integration_test/Target/ExportSystemC/basic.mlir
lib/Dialect/SystemC/SystemCOps.cpp
lib/Target/ExportSystemC/Patterns/SystemCEmissionPatterns.cpp
test/Dialect/SystemC/module-error.mlir
test/Dialect/SystemC/structure.mlir
test/Target/ExportSystemC/basic.mlir

Add an operation to model C++ level variable declarations and one to assign to them. This also includes the emission patterns for ExportSystemC. Note that the variable op implements custom parser, printer, and verifier because the single optional operand makes it difficult to use the predefined constraints to check for type equality and infer the type from the result type.

[SystemC] Add VariableOp and AssignOp

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/prepare-for-emission.mlir

Reverts llvm/circt#3865 since it caused runtime regression. Essentially the PR preformed O(D^2) bubble sorts on inout operations where D is the depth of inout chains. I assumed practically it would be fast enough, but seems wrong.

Revert "[PrepareForEmission] Reorder inout ops before legalizing OoO uses"

---

integration_test/Target/ExportSystemC/basic.mlir
lib/Target/ExportSystemC/Patterns/HWEmissionPatterns.cpp
lib/Target/ExportSystemC/Patterns/SystemCEmissionPatterns.cpp
test/Target/ExportSystemC/basic.mlir

Change the emission of the bulitin integer types to map to native C integers and map the dedicated systemc types to the corresponding C++ classes.

[ExportSystemC] Add systemc type emission

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/SFCTests/constant-data-taps.fir
test/Dialect/FIRRTL/SFCTests/data-taps-more-xmrs.fir
test/Dialect/FIRRTL/SFCTests/data-taps-xmr.fir
test/Dialect/FIRRTL/annotations.mlir

This  PR lowers the new `GrandCentralTaps` directly to the `RefOps` in the
`LowerAnnotations` pass. This encodes the cross-module-reference explicitly
in the IR using `RefTypes`.
The new `DataTaps` format specifies the source of the XMR and the wire that
reads the XMR.
Given the annotation, the `LowerAnnotations` pass overview,
1. Get the lowest-common-ancestor(lca) between the `source` and the `wireName`:
a. LCA is searched from the unique path from top to source and wireName.	
2. Insert a `ref.send` to get the `RefType` corresponding to the `source` value.
3. Drill ports of `RefType` from the `source` through the lca, till the `wireName`. 
4. Insert a `ref.resolve` to assign the `RefType` value to the `wireName`.
```mlir
{class = "sifive.enterprise.grandcentral.DataTapsAnnotation",
keys …
```

[FIRRTL] Lower GrandCentralTaps to RefOps

---

include/circt/Dialect/HW/HWOpInterfaces.td
include/circt/Dialect/HW/HWStructure.td
lib/Dialect/HW/HWOps.cpp
lib/Dialect/MSFT/MSFTOps.cpp

This is a useful piece of generic functionality to be able to add
output values to modules implementing the interface. It is
complementary to the modifyPorts methods that update the module
boundary with new Types. After adding new outputs, it will usually be
necessary to specify which Values should appear on those outputs, and
this additional method makes it possible to do generically. The
default implementation is a no-op, so HWModuleExtern and
HWModuleGenerated will not need to do anything. The implementation on
HWModule overrides this default with the existing behavior.
Closes https://github.com/llvm/circt/issues/3791

[HW] Expose `appendOutputs` in the HWMutableModuleLike interface.

---

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/annotations.mlir

These are not guaranteed (AFAIK) to be unique per-user/op/etc. currently (indeed lots of benefits were had by dropping innersym leaf component so they could be shared), so don't create new HierPathOp per NLA.
Sharing NLA's should be safe as long as they're only modified as a result of a hierarchy change (e.g., inlining) which impacts all uses in the same way.  Code that tries to mutate a HierPathOp without considering other users (or clean up a HierPathOp under assumption it's private to the op) would break, but is already wrong.
I previously thought this would be good to do via pass (not sure would work as canonicalizer--esp re:updating symbol users) but all "original" HierPathOp's are created here so just handle it as we create them with a simple cache on instance path.  I'm not sure …

[FIRRTL][LowerAnnotations] Reuse HierPathOp's

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp

See 6657b714cbb2205bb4dabcd5f0b23e3b51b0dfae for previous similar touchups.
Don't love the extra code but avoids the warning
(which generally we really don't want to disable or ignore).

[FIRRTL][GCT] Fix -Wreturn-stack-address casting warning (NFC)

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp

Follow-up to #3863 to address symbol visibility on HierPathOp's, from when they're created to how they're propagated/modified in passes.
Dedup propagates visibility when modifying existing NLA, will create as private if promoting local to non-local.
Inliner copies visibility when doing its `writeBack`s.
EmitOMIR does create HierPathOp's but they're temporary and are deleted before pass completion so leaving that alone.

[FIRRTL] HierPathOp: create with private vis, propagate vis in passes

---

lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
test/Conversion/HandshakeToHW/test_simple_loop.mlir

Another batch of patterns! This cleans up significantly compared to the FIRRTL lowering, in that most shared logic are factored out through the `buildUnitRateLogic` and `buildJoinLogic` functions.

[HandshakeToHW] Add `arith` and mux patterns

---

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/annotations.mlir

This reverts commit 3afe5abf03ef1ebe14ec0531243d2e6b317963ae.
This caused failures in passes such as EmitOMIR or LowerToHW regarding missing HierPathOp's. :thinking: 
Unbreak for now, more investigation needed.

Revert "[FIRRTL][LowerAnnotations] Reuse HierPathOp's instead of always new. (#3863)"

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp

This fixes issues https://github.com/llvm/circt/issues/3885 and https://github.com/llvm/circt/issues/3856. 
"automatic logic" must be located at beginning of statements, hence PrepareForEmission is moving the ops to valid insertion points. The issue here was that previously insertion points were identified by IR traversal, therefore if it took O(N^2) to perform legalization in the worst case. This PR fixes the issue by caching and managing the insertion point reasonably.

[ExportVerilog] Fix regression caused by finding logic op insertion points

---

lib/Dialect/FIRRTL/FIRRTLTypes.cpp
test/Dialect/FIRRTL/errors.mlir

Remove the restriction of only `Ground` type from RefTypes. This is required for enabling GrandCentral to use `RefType` and also enable aggregate preservation.

[FIRRTL] Allow RefType of aggregate type

---

include/circt/Dialect/FIRRTL/CHIRRTL.td
include/circt/Dialect/FIRRTL/CHIRRTLVisitors.h
include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
lib/Dialect/FIRRTL/CHIRRTLDialect.cpp
lib/Dialect/FIRRTL/Export/FIREmitter.cpp
lib/Dialect/FIRRTL/Transforms/LowerCHIRRTL.cpp

Add a new debug port of `RefType` to chirrtl. The base type of the debug port must be a vector type of the memory's elements with the memory's depth number of elements.

[CHIRRTL] Add a new MemoryDebugPortOp

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/errors.mlir

Add a Debug kind of memory port. The Debug port must be of `RefType`. The `RefType` must be a vector of the memory data type, with memory depth number of elements.

[FIRRTL] Add a debug kind of port to MemOp

---

include/circt/Dialect/Handshake/HandshakeOps.td
include/circt/Dialect/Handshake/Visitor.h
integration_test/handshake-runner/sync.mlir
lib/Dialect/Handshake/HandshakeExecutableOps.cpp
test/Dialect/Handshake/sync.mlir

This PR introduces a new `SyncOp` as described in #3881
The lowering basically combines both a join and a fork logic for the control signals, while simply connecting the data wires. 
It might make sense to split this PR into one introducing the op, and the other with the lowering to FIRRTL.

[Handshake] Add sync op

---

include/circt/Dialect/Pipeline/CMakeLists.txt
include/circt/Dialect/Pipeline/Pipeline.td
include/circt/Dialect/Pipeline/PipelinePasses.h
include/circt/Dialect/Pipeline/PipelinePasses.td
include/circt/InitAllPasses.h
lib/Dialect/Pipeline/CMakeLists.txt
lib/Dialect/Pipeline/PipelineOps.cpp
lib/Dialect/Pipeline/Transforms/CMakeLists.txt
lib/Dialect/Pipeline/Transforms/ExplicitRegs.cpp
lib/Dialect/Pipeline/Transforms/PassDetails.h
lib/Support/BackedgeBuilder.cpp
test/Dialect/Pipeline/Transforms/explicit-regs.mlir
tools/circt-opt/CMakeLists.txt

This commit adds an intermediate transformation to the Pipeline dialect which is responsible for converting `pipeline.stage` to `pipeline.stage.register` operations. The purpose of this transformation is to 'fix' where registers needs to be placed in the pipeline, after all stages have been defined and placed.
In short, the transformation will scan through the pipeline (in order, top to bottom) and insert `pipeline.stage.register` operations in place of `pipeline.stage` operations. Any operand used in any operation will be analyzed to determine if it originates in between the last seen stage and the operation itself. If not, this means that the operand crossed a pipeline stage, and as such, the value will be routed through the predecessor stage (`routeThroughStage`).

[Pipeline] Add pipeline stage register materialization pass

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

array_get has constrait that the width of `index` must be `clog(size)`. We have to extend or truncate the index value if necessary

[LowerToHW] Fix width mismatch in subaccess lowering

---

lib/Dialect/FIRRTL/Transforms/FlattenMemory.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/MemToRegOfVec.cpp
test/Dialect/FIRRTL/mem-to-reg-of-vec.mlir

This commit updates the memory lowering passes to handle the memory debug port.
The `MemToRegOfVec` pass lowers the debug ports to a RefType of the register. The pass connects the debug ports to a `RefSend` of the register. This ensures that any `MemTap` of the memory can be lowered to a cross-module-reference of the memory register.
The `FlattenMemory` cannot flatten a memory with any Debug port.
The `LowerTypes` cannot handle debug port in memories with aggregate data type.

[FIRRTL] Lower Memory debug port to Ref of Register

---

include/circt/Dialect/Seq/Seq.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/firtool/register-randomization.fir
tools/firtool/firtool.cpp

Register lowering is very sensitive to mux structure, so clean this up prior.

[FIRTOOL] Run canonicalization prior to seq lowering.

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR.mlir

This commit lowers the debug ports of `firrtl.mem` to cross-module-reference of the memory register. The memory is yet to be lowered to the register, so the pass uses a string to encode the internal path to the memory. This same mechanism can be used to encode internal paths into external modules.
The lowering also ensures a `RefType` of vectors is lowered to appropriate indexed xmr accesses.

[FIRRTL][LowerXMR] Handle debug ports on Memory

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/SFCTests/mem-taps.fir

This PR generates debug ports on the memory with the `MemTap` annotation. The debug port is a `RefType` handle of the memory register. The cross-module-reference for the memory is then encoded in the IR using `RefType` connections from the memory debug port to the target wire.
This implementation assumes that the target wire and the memory have the same datatype.

[FIRRTL][MemTap] Lower Memtap annotations to RefType connections

---

lib/Dialect/FIRRTL/Export/FIREmitter.cpp

Quiet compiler warning about missed case.

FIREmitter: explicitly handle new Debug port type with diagnostic.

---

include/circt/Dialect/SV/SVTypeDecl.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Conversion/ExportVerilog/sv-interfaces.mlir
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/grand-central.mlir

We need to add a comment `// VCS coverage exclude_file"` to all Grand Central modules and interfaces.  When we needed something like this previousl, it was previously handled by adding a `comment` attribute onto `hw.module` and handled in lower to HW.
To support these new targets, we have to:
1. Add a comment attribute to SV interfaces.  To accomplish this, I used an optional string attribute.  I switched the printed format to print the attribute dictionary after the symbol name, which I think is more common across all our operations.
2. Update ExportVerilog to print this attribute.  The `emitComment` function can recognize null attributes and skip a comment.
3. Propagate a "comment" attribute on FIRRTL modules in LowerToHW to HW modules.  This was not added to the ODS arguments, similar …

Backport: [FIRRTL][SV] Add comment attribute to GC interfaces and modules

---

frontends/PyCDE/src/pycde/esi.py
integration_test/Bindings/Python/dialects/esi.py
lib/Dialect/ESI/ESIServices.cpp
test/Dialect/ESI/services.mlir

Previously toServer inputs were being passed into the port req block via block args, which needlessly complicates things. Change that.

[ESI][NFC][Services] In service implement reqs, avoid args

---

test/firtool/register-randomization.fir

This removes large register tests from register-randomization.fir. The tests originally checked that large registers which violates VCS limitations were properly split into small registers (#3748). However improved version of register randomization (#3802) doesn't create a large size of register in the first place, so it's not required to have the tests now. 
This test has caused a regression for `check-circt` since >15000 lines of verilog are emitted in each test.

[FIRRTL] Remove large registers from register-randomization.fir

---

include/circt/Scheduling/Algorithms.h
lib/Scheduling/CMakeLists.txt
lib/Scheduling/CPSATSchedulers.cpp
lib/Scheduling/TestPasses.cpp
test/Scheduling/or-tools/shared-operators-problems.mlir

This a WIP implementation of a scheduler for the `SharedOperatorsProblem` using a CP-SAT solver, through OR-Tools.
The formulation/model is the [Resource Constrained Project Scheduling Problem](https://python-mip.readthedocs.io/en/latest/examples.html#:~:text=The%20Resource%2DConstrained%20Project%20Scheduling,required%20amount%20of%20different%20resources.) (but I do not use the formulation from that link). 
The current implementation is closely modeled on the [OR-Tools example](https://github.com/google/or-tools/blob/stable/examples/python/rcpsp_sat.py). That example is slightly more general (I think) than applies to CIRCT, namely it allows for multiple "recipes" for satisfying a task/op. Thus, the implementation needed to differ non-trivially. Since I am not a …

[Scheduling] Add CPSAT scheduler (via OR-Tools) for `SharedOperatorsProblem`

---

lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
tools/hlstool/hlstool.cpp

Follows from `HandshakeToFIRRTL` - correctness is not guaranteed. Following this work will be focus on getting the low-level plumbing to work (ESI, lowering `none`-types, ...).

[HandshakeToHW] Add `seq` buffer lowering

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/prepare-for-emission.mlir

This fixes a bug that "always inline" operation is not legalized for the last user. Previously `lowerAlwaysInlineOperation` skipped moving the op for the last user but it caused a bug. If the last user is placed before the op, it causes an error in out-of-order resolution. This fixes the bug by removing the condition `lowerAlwaysInlineOperation` and avoiding processing same operations twice to prevent infinte loops.

[PrepareForEmission] Fix "always inline" operation legalization

---

lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/SFCTests/dedup-errors.fir
test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/annotations.mlir
test/Dialect/FIRRTL/dedup.mlir
test/Dialect/FIRRTL/emit-omir.mlir
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/extract-instances.mlir
test/Dialect/FIRRTL/grand-central-signal-mappings.mlir
test/Dialect/FIRRTL/grand-central-taps.mlir
test/Dialect/FIRRTL/grand-central.mlir
test/Dialect/FIRRTL/inject-dut-hierarchy.mlir
test/Dialect/FIRRTL/inliner.mlir
test/Dialect/FIRRTL/lower-memory.mlir
test/Dialect/FIRRTL/lower-types.mlir
test/Dialect/FIRRTL/mem-to-reg-of-vec.mlir
test/Dialect/FIRRTL/omir.mlir
test/Dialect/FIRRTL/prefix-modules.mlir
test/Dialect/FIRRTL/print-nla-table.mlir
test/Dialect/FIRRTL/test.mlir

Tidy up visibility printing for hierpath's.
Before:
```
firrtl.hierpath @nla_361 [@Top::@inst, ...] {sym_visibility = "private"}
```
After:
```
firrtl.hierpath private @nla_361 [@Top::@inst, ...]
```
Update tests (first those required, rest for consistency).
Follow-up to #3871 .

[FIRRTL] Print/parse visibility for HierPathOp explicitly

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR.mlir

Ignore any `RefType` of zero width, and donot emit any XMR.

[FIRRTL][LowerXMR] Donot emit 0-width XMR

---

lib/Dialect/FIRRTL/FIRRTLOps.cpp

Implement the getMemPortKindFromType using static constants, to improve code readability. 
This addresses the feedback on https://github.com/llvm/circt/pull/3908

[FIRRTL] Refactor getMemPortKindFromType. NFC.

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types-aggregate.mlir

Chisel produces bunch of single element vectors. In terms of verilog quality, we can produce more simpler verilog when we lower singleton vector into scalar.

[LowerTypes] Lower size 1 vector even when 1d vector preservation.

---

lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp

There is a good reason we build the more expensive fork logic for the outputs of a `SyncOp`. Thus, we should explain it in a comment.

[HandshakeToFIRRTL][NFC] Add comment to sink lowering

---

integration_test/Dialect/Handshake/buffer_init_none/buffer_init_none.mlir
integration_test/Dialect/Handshake/buffer_initial_values/buffer_initial_values.mlir
integration_test/Dialect/Handshake/conditional_modification/conditional_modification.mlir
integration_test/Dialect/Handshake/dot/dot.mlir
integration_test/Dialect/Handshake/matmul/matmul.mlir
integration_test/Dialect/Handshake/max/max.mlir
integration_test/Dialect/Handshake/multiple_loops/multiple_loops.mlir
integration_test/Dialect/Handshake/nested_diamonds/nested_diamonds.mlir
integration_test/Dialect/Handshake/nested_loops/nested_loops.mlir
integration_test/Dialect/Handshake/sync_op/sync_op.mlir
integration_test/Dialect/Handshake/task_pipelining/task_pipelining.mlir
integration_test/Dialect/Handshake/tp_memory/tp_memory.mlir
integration_test/Dialect/Handshake/tuple_input/tuple_input.mlir
integration_test/Dialect/Handshake/tuple_packing/tuple_packing.mlir

Changing the flag from `--dynamic` to `--dynamic-firrtl` was overlooked.

[hlstool][lit] Change outdated flags in integration tests

---

include/circt/Dialect/Handshake/HandshakePasses.h
include/circt/Dialect/Handshake/HandshakePasses.td
integration_test/Dialect/Handshake/conditional_modification/conditional_modification.mlir
integration_test/Dialect/Handshake/multiple_loops/multiple_loops.mlir
integration_test/Dialect/Handshake/nested_diamonds/nested_diamonds.mlir
integration_test/Dialect/Handshake/nested_loops/nested_loops.mlir
integration_test/Dialect/Handshake/task_pipelining/task_pipelining.mlir
integration_test/Dialect/Handshake/tp_memory/tp_memory.mlir
lib/Dialect/Handshake/Transforms/CMakeLists.txt
lib/Dialect/Handshake/Transforms/LockFunctions.cpp
test/Dialect/Handshake/errors-lock-functions.mlir
test/Dialect/Handshake/test-lock-functions.mlir
test/Dialect/Handshake/test-lock-region.mlir

This PR introduces a handshake pass that adds a lock mechanism for functions.
Such a mechanism ensures that there is only one active control token in a function at each point in time.
An additional "RUN" directive/command was added to the integration tests that otherwise require a task-pipelining transformation. These test runs disable task-pipelining in favor of locking but should still yield the same results (albeit with lower throughput).

[Handshake] Add pass that locks functions

---

lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
test/Conversion/HandshakeToHW/test_sync.mlir

Main side effect of this is to reduce the size of the generated IR without having to run the canonicalizer. This, in turn, is easier to write a test against and reason about.

[HandshakeToHW] Cache RTLBuilder constants

---

lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp

This fixes a lifetime bug around `ifCache`. Previously an address where `op` points at might be invalidated by reallocation of `ifCache` since we recursively construct `IfOp`. This commit fixes the memory corruption by not saving the address before the recursion.

[LowerSeqToSV] Fix memory corruption

---

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/annotations.mlir

This commit removes the assumption that the `parent` is always the lowest common ancestor module for a `GrandCentralView` annotation. Instead, compute the lca, between the source and the companion. 
The only assumption being made here is that the source module and the component module have a unique path.   The component and source must be specified as non-local path if there exists multiple paths.

[FIRRTL][GrandCentral] Donot assume parent is LCA

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR.mlir

Update `LowerXMR` to generate temporary 0-width wires, for 0-width `RefType`. The 0-width wire will be eliminated by `LowerToHW`.
This updates the last fix, https://github.com/llvm/circt/pull/3944, that just ignored the zero width `RefResolve`, this creates a problem when the result of the `RefResolve` is used by other operations.
Instead of dealing with all the users of the result of `RefResolve`, `LowerXMR` replaces them with a zero-width wire and relies on `LowerToHW` to eliminate them.

[FIRRTL][LowerXMR] Handle 0-width XMRs

---

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
test/Dialect/FIRRTL/infer-widths.mlir

Handle the memory debug ports in `InferWidths` pass.
The debug port must be a `firrtl.ref` of a `firrtl.vector` of the data type.

[FIRRTL] InferWidths of memory debug port

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

This PR changes subaccess lowering compatible with multibit mux. Specifically mux pragmas and extra mux for out-of-bounds read are added to the lowering result of subaccess.

[LowerToHW] Align subacess lowerings with multibit mux

---

include/circt/Conversion/StandardToHandshake.h
integration_test/Dialect/Handshake/conditional_modification/conditional_modification.mlir
integration_test/Dialect/Handshake/multiple_loops/multiple_loops.mlir
integration_test/Dialect/Handshake/nested_diamonds/nested_diamonds.mlir
integration_test/Dialect/Handshake/nested_loops/nested_loops.mlir
integration_test/Dialect/Handshake/task_pipelining/task_pipelining.mlir
integration_test/Dialect/Handshake/tp_memory/tp_memory.mlir
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
tools/hlstool/hlstool.cpp

This PR adds a flag to `hlstool` that allows selecting the kind of parallelism to support. Currently, these options are "pipelining", "locking", and "none".

[hlstool] Add DHLS parallelism selection

---

lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp
test/Dialect/FIRRTL/check-comb-cycles.mlir

CheckCombCycles should handle register self initialization connects properly. It should not error out on self initialization of individual fields of an aggregate kind of register.

[FIRRTL][CheckCombCycles] Ignore register self initialization connects

---

lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/lower-types-errors.mlir
test/Dialect/FIRRTL/lower-types.mlir

Reverts llvm/circt#3891, until have better fix for #3968 .
Conflicts in this way are not quite invalid FIRRTL per spec ($ vs _) and it seems to be expected to "work" in some designs.  FWIW SFC has tests for handling this sort of lowering conflict specifically.  Neither compiler does what the spec says re:"$" however which would avoid the conflict here.
These duplicate names will be resolved/legalized before verilog emission.
They should not be trusted until that point (similarly wires and regs and other namable things), and the way the conflicts are resolved should not be relied upon (at best implementation-defined behavior).
This sort of conflict is likely a problem if occurs on public/top module or extmodule-- that is, where used in contexts where the lowered names need to be reliably …

Revert "[FIRRTL] Verify FModuleLike's have unique port names."

---

integration_test/Dialect/Handshake/mix_std_hs/kernel.mlir
integration_test/Dialect/Handshake/mix_std_hs/lit.local.cfg.py
integration_test/Dialect/Handshake/mix_std_hs/mix_std_hs.mlir
integration_test/Dialect/Handshake/mix_std_hs/mix_std_hs.py
lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
test/Conversion/HandshakeToFIRRTL/test_func.mlir
test/Conversion/HandshakeToFIRRTL/test_instance.mlir

This PR adds support for external handshake functions to the `HandshakeToFIRRTL` lowering. 
As the port for external memories depends on its usages, we cannot lower external functions that consume memory references.

[HandshakeToFIRRTL] Add support for external function

---

include/circt/Dialect/Handshake/HandshakeOps.td
lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
test/Conversion/HandshakeToHW/test_extmemory.mlir

External memories are... tricky... to handle in the pattern rewrite infrastructure due to the need for rewriting the single top-level memref argument to both new in- and output ports of the module (HW doesn't contain flip types, like FIRRTL).
That will, therefore, require a more specialized lowering of external memories. As an intermediate step, load and store ops can be elaborated, the external memory emitted as an external module, and the top-level `memref` argument as an `esi.channel<memref>`.
A follow-up commit will then implement lowering of the `extmemory` + top-level `memref` by elaborating the ports required for that `memref` and performing the required plumbing.

[HandshakeToHW] Add load,store conversion + dummy ext memory lowering

---

test/circt-as-dis/commandline-as.mlir
test/circt-as-dis/commandline-dis.mlir
test/hlstool/commandline.mlir
tools/circt-as/circt-as.cpp
tools/circt-dis/circt-dis.cpp
tools/hlstool/hlstool.cpp

Similar to changes made for other tools in #2979.
Primarily motivated to avoid huge option lists in certain build configurations (see linked PR).
Add "commandline" tests for these as well, as for other utilities.
Verifies they at least run and that loosely speaking the output and options are what we expect.
Some tools want to hide the MLIR options as well and more explicitly manage categories + options, as in c468158ee3ec6278df911b7970103b29cd3fb2ab , but for now starting with what is done for `firtool`.

hlstool,circt-{as,dis}: gather options into category, hide unrelated options

---

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/annotations.mlir
test/Dialect/FIRRTL/grand-central-taps.mlir
test/Dialect/FIRRTL/grand-central.mlir
tools/circt-opt/circt-opt.cpp
tools/firtool/firtool.cpp

We create and manage many thousands of HierPathOp's unnecessarily.
Fix this by addressing the primary location they're added to the IR: LowerAnnotations, by using a simple cache to avoid emitting duplicate ops.
This reduces the count from thousands to tens on even small-ish designs.
Modify GC and GCT passes to stop deleting HierPathOp's as they don't know if they're still used.  Indeed, in our tests we were deleting these ops despite them still being alive (breadcrumbs).
Add SymbolDCE to the pipeline to do this cleanup instead, thanks to various recent changes using private visibility in many places, particularly the HierPathOp's themselves (#3871).
Previously this was done in #3863, which was reverted due to breakage with passes deleting HP's under assumption their use case was only …

[FIRRTL] Reuse HierPathOp's when creating in LA, fix GC(T) cleanup, add SymbolDCE to pipeline

---

lib/Dialect/SV/SVOps.cpp
test/Dialect/SV/canonicalization.mlir
test/firtool/memory.fir

Add a missing canonicalizer to erase empty if-else block.

[SV] Erase empty if-else block

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

This  PR handles operations with aggregate type operands, that cannot be lowered. Some operations can be `opaque` to the `LowerTypes` algorithm. The `opaque` ops will not be lowered, and can continue to have aggregate type operands after the lowering.
The `ref.send` is such an example of an `opaque` op.
The problem is that, even though the `opaque` op is not being lowered, its inputs can be lowered. So, it is required to re-construct the aggregate type input from the lowered elements in order to maintain a valid IR.
This PR, uses `BitCastOp` of `CatPrimOp` of the individual elements to create the original aggregate type input.
This transformation will also be used for registers that are selectively lowered.

 [FIRRTL][LowerTypes] Lower aggregate type operand

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/ref.mlir

Add a new op to extract individual elements from a `RefType` of `Bundle` or `Vector` base type.
This op will be generated by `LowerTypes`, when the output debug port of `RefType` of a `MemOp` is not lowered but all its subsequent users and the `ref.resolve` ops are all lowered to the individual elements.
The `RefSubOp` can be used to index into both `Bundles` and `Vector` with an index. The index must be valid with respect to the base type.
```
%0 = firrtl.ref.sub %b1[1] : !firrtl.ref<bundle<a: uint<1>, b: uint<2>>>
```

[FIRRTL][RefType] Add a new RefSub Op

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR.mlir

Lower the `RefSubOp` to generate cross-module-reference into a `MemOp`.
They are used to generate verbatim encoded sub indexed reference to the register corresponding to the memory.
The register does not exist in the IR yet, and will be generated by `HWMemSimImpl`.
This commit is part of https://github.com/llvm/circt/pull/3990

[FIRRTL][LowerXMR] Lower RefSubOp to memory XMR

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

For https://github.com/llvm/circt/issues/3853, this commit improves emission of XMR to inline XMR references into bound instance ports. 
For the example in #3853, the difference of w/ and w/o the PR:
```verilog
<   wire struct packed {logic x; logic y; } _TopXMRAsserts_inst0_a;
<   wire                                    _TopXMRAsserts_inst0_b;
38,39d35
<   assign _TopXMRAsserts_inst0_a = middle.bottom.O;
<   assign _TopXMRAsserts_inst0_b = middle.bottom.I.x;
44,45c40,41
<       .a (_TopXMRAsserts_inst0_a),
<       .b (_TopXMRAsserts_inst0_b)
---
>       .a (middle.bottom.O),
>       .b (middle.bottom.I.x)
57,58c53,54
<   .a (_TopXMRAsserts_inst0_a),
<   .b (_TopXMRAsserts_inst0_b)
---
>   .a (middle.bottom.O),
>   .b (middle.bottom.I.x)
```
CC: @rsetaluri

[ExportVerilog] Improve XMR emission when used as bound inputs

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/SFCTests/mem-taps-reg.fir
test/Dialect/FIRRTL/lower-types.mlir

This PR lowers the `RefType` of aggregate values, to the `RefType` of the individual elements.
A new `RefSubOp` is added to handle the lowering and access individual elements of the `RefType`.
A `ref.send` and `ref.resolve` of aggregate type is lowered to the `ref.send`/`ref.resolve` of the individual aggregate elements. 
The `RefSubOp` is in general used temporarily in `LowerTypes` and then replaced by the corresponding definitions.
Only a debug port from a `MemOp` can introduce `RefSendOp` in the IR. Because the debug port output from the `MemOp` will not be lowered, but all its users will be lowered.

[FIRRTL][RefType] Lower RefType in LowerTypes 

---

.github/workflows/nightlyIntegrationTests.yml

GCC debug binaries are just too large and have been causing disk space issues intermittently. Just disable them for now as it is a longer effort to cut down on the amount of stuff we build. Fixes #3328 .

[CI] Disable gcc/debug on nightly tests

---

include/circt/Dialect/HW/HWOps.h
lib/Dialect/ESI/ESIServices.cpp
lib/Dialect/HW/HWOps.cpp
lib/Dialect/MSFT/MSFTOps.cpp

Assuming this is a bug and not a feature - `modifyModulePorts` currently only modifies the top-level I/O of a module, but does not change the block arguments of the module body. This leaves performing module body block arguments up to the caller (what was currently being done by the `ESIConnectServicesPass` pass).
Fixed by adding/removing block arguments if a `Block*` is provided to `modifyModulePorts`.

[HW] Also modify HWModule block args if adding/removing inputs

---

include/circt/Dialect/ESI/ESIInterfaces.td
include/circt/Dialect/ESI/ESIOps.td
include/circt/Dialect/ESI/ESIPorts.td
include/circt/Dialect/ESI/ESIStdServices.td
include/circt/Dialect/HW/HWOps.h
lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
lib/Dialect/ESI/ESIPasses.cpp
lib/Dialect/ESI/ESIServices.cpp
lib/Dialect/ESI/ESIStdServices.cpp
lib/Dialect/HW/HWOps.cpp
test/Conversion/HandshakeToHW/test_cmerge.mlir
test/Conversion/HandshakeToHW/test_cond_br.mlir
test/Conversion/HandshakeToHW/test_constant.mlir
test/Conversion/HandshakeToHW/test_extmemory.mlir
test/Conversion/HandshakeToHW/test_fork.mlir
test/Conversion/HandshakeToHW/test_join.mlir
test/Conversion/HandshakeToHW/test_simple_loop.mlir
test/Conversion/HandshakeToHW/test_source.mlir
test/Conversion/HandshakeToHW/test_sync.mlir
test/Dialect/ESI/connectivity.mlir
test/Dialect/ESI/lowering.mlir
test/Dialect/ESI/services.mlir

Lots of special-case logic removed - `i0` is working as intended, feels good...!

[ESI] Use `i0` instead of `none`

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/annotations.mlir

This commit adds a `firrtl.transforms.NoDedupAnnotation` annotation to the datatap sink module, to ensure they are not deduped.
Datatap sink modules will have input `RefType` ports, and `LowerXMR` should be able to statically resolve each `RefType` to a single `ref.send`, otherwise the pass will fail to generate the XMR strings. If the sink modules are deduped, then the input ref port cannot be resolved statically to a single `ref.send`. Hence it is required to block their dedup.

[FIRRTL][LowerAnnotation] Mark the DataTap sink as NoDedup

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/SFCTests/constant-data-taps.fir
test/Dialect/FIRRTL/SFCTests/data-taps-more-xmrs.fir
test/Dialect/FIRRTL/SFCTests/data-taps-xmr.fir
test/Dialect/FIRRTL/SFCTests/mem-taps-reg.fir
test/Dialect/FIRRTL/SFCTests/mem-taps.fir
test/Dialect/FIRRTL/annotations.mlir

Update the GrandCentral attribute `wireName` to `sink`.

[FIRRTL][GrandCentral] Update attribute wireName to sink

---

include/circt/Dialect/HW/HWAggregates.td
lib/Dialect/HW/HWOps.cpp
test/Dialect/HW/canonicalization.mlir

Leverages the same logic used for folding `hw.struct_extract`, fixes #4008.

[HW] Add `hw.struct_explode` canonicalizer

---

integration_test/Dialect/Handshake/helper.py

This commit ensures that the handshake integration tests feed their inputs at line-rate. Before that change, there was an additional clock cycle delay when the consumer wasn't immediately ready to consume.

[Handshake][lit] Ensure line rate transfer

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/SFCTests/mem-taps-reg.fir
test/Dialect/FIRRTL/SFCTests/mem-taps.fir

This commit reverts the changes to MemTap annotation introduced in https://github.com/llvm/circt/pull/4006.
MemTap sink should be an array attribute instead of a string attribute.
``"sink": "~Top|Top>memTap"``  instead of  `` 
"sink":[  "~Top|Top>memTap[0]",  "~Top|Top>memTap[1]", ...] 
``

[FIRRTL][GrandCentral] Revert MemTap sink to array attribute

---

docs/Dialects/FIRRTL/RationaleFIRRTL.md
include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h
include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
include/circt/Dialect/FIRRTL/FIRRTLStatements.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp
lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/AddSeqMemPorts.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
lib/Dialect/FIRRTL/Transforms/InferResets.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/errors.mlir

In order to support partial lowerings involving the FIRRTL dialect, and to mix in foreign operations and types, we need a way to pass foreign types through FIRRTL modules, instances, and trivial connects.
This commit extends `FModuleLike`, `InstanceOp`, and `StrictConnectOp` to also accept foreign, non-FIRRTL types for ports and connections to those ports. It also adapts the `LowerToHW` pass to simply pass through foreign-typed values when they appear in module and instance ports. This requires adding special case handling in a few places since we cannot create an `InOutType` and therefore `WireOp` around arbitrary foreign types, so we generally have to immediately materialize foreign values.
This lowering can be quite usefully combined with the builtin `unrealized_conversion_cast` to …

[FIRRTL] Allow foreign types in module/instance ports

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

For larger or nested conditionals, comments help more easily understand what's going on.

[ExportVerilog] emit comments on `else and `endif for readability

---

docs/Dialects/FIRRTL/FIRRTLAnnotations.md
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code-error.mlir
test/Dialect/SV/hw-extract-test-code.mlir

If a module has only inputs after extraction, it can and should be moved to the test code area. Such modules are marked to be output into the test code path.
Closes https://github.com/llvm/circt/issues/2351.

[SV] Update ExtractTestCode to extract input only modules.

---

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
test/Dialect/FIRRTL/infer-widths.mlir

The `InferWidths` pass should ignore any foreign types that might be present in the IR. These types cannot contribute any width constraints and don't participate in the width inference process in general, so this commit makes the pass ignore such types more explicitly.
Also add support for `UnrealizedConversionCastOp`. In case such a cast has a result of uninferred width, the pass would now assign a width to it as with any other operation. The applicability of this in practice is fairly limited since width inference can only affect the FIRRTL-typed results of the cast, but it can't propagate any information through the cast. However, in some applications a partial dialect lowering might be sensitive to the source type of the cast and do the right thing based on what width was assigned, …

[FIRRTL][InferWidths] Exclude foreign types, add conversion cast support

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

Adjust the `lowerProducer` function such that it properly passes through foreign types like it passes through any non-bundle type.

[FIRRTL][LowerTypes] Pass through foreign types in lowerProducer

---

lib/Dialect/FIRRTL/Transforms/InferResets.cpp
test/Dialect/FIRRTL/infer-resets.mlir

Make the `InferResets` pass properly ignore foreign types which by definition don't contribute to the resets being inferred. Before this change the pass would abort on various `cast<FIRRTLType>()` calls. These all become `dyn_cast<FIRRTLType>()` now with graceful handling of the non-FIRRTL type case, which makes the pass more robust.

[FIRRTL][InferResets] Don't abort on foreign types

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp

Been annoyed by this assert being thrown for a long time. If unsupported operations is fed to the ExportVerilog pass (may happen if some other lowering pass wasn't run or export verilog is missing an implementation for lowering some op), a very unhelpful assert would be thrown stating `value expected a name but doesn't have one` - telling us nothing about which op actually violated the condition.
Modifies this to actually printing the op + an error message indicating the most likely cause for tripping this assert.

[ExportVerilog] Improve error message for emitting unsupported ops

---

include/circt/Dialect/SV/SVPasses.h
include/circt/Dialect/SV/SVPasses.td
lib/Dialect/SV/Transforms/CMakeLists.txt
lib/Dialect/SV/Transforms/SVTraceIVerilog.cpp
test/Dialect/SV/sv-trace-iverilog.mlir

Adds a macro to HWModules which enables tracing for iverilog (see https://docs.cocotb.org/en/stable/simulator_support.html#waveforms).

[SV] Add iverilog trace instrumentation pass

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

Currently, ExportVerilog will crash on trying to emit a  `hw.struct_explode` operation. Fixed by lowering the op to a set of `hw.struct_extract` ops during prepareForEmission, which has clear emission semantics.

[ExportVerilog] Handle `hw.struct_explode`

---

include/circt/Dialect/Handshake/HandshakeOps.h
include/circt/Dialect/Handshake/HandshakeOps.td
include/circt/Dialect/Handshake/HandshakePasses.h
include/circt/Dialect/Handshake/HandshakePasses.td
lib/Dialect/Handshake/HandshakeOps.cpp
lib/Dialect/Handshake/Transforms/CMakeLists.txt
lib/Dialect/Handshake/Transforms/LowerExtmemToHW.cpp
lib/Dialect/Handshake/Transforms/PassDetails.h
test/Dialect/Handshake/lower-extmem.mlir

This is intended to be a lowering used on the path of transforming Handshake to hardware. The transformation materializes the top-level `memref` to a new set of in- and output arguments, and plumbs this to the in- and output values of the `handshake.extmem` operation which referenced the memref. This is essentially what is was done by `HandshakeToFIRRTL`/`HandshakeToHW` but moved as a preprocessing step, lowering away the "high-level" semantics associated with the `memref` argument/`handshake.extmem` operation.
Another motivation for doing so is to create a more natural interface for external users to interact with:
- Store ports now have a single handshake'd output port with combined addr+data.
- Load ports now only requires a single handshake'd data input. This input is then forked into …

[Handshake] Add `handshake.extmem` lowering pass

---

docs/VerilogGeneration.md
include/circt/Support/LoweringOptions.h
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
lib/Support/LoweringOptions.cpp
test/Conversion/ExportVerilog/prepare-for-emission.mlir

This PR improves namehints heuristic and add a heuristic to spill wires for mux. Namehint heuristic is modified to spill wires for namehints that doesn't have "\_" prefix regardless of term sizes. For expressions with "\_" prefix, if the term is greater than a threshold, the expression is spilled to a wire. Also this PR adds a heuristic option to spill all mux.

[PrepareForEmission] Improve namehints heuristic and add mux heuristic

---

.github/workflows/buildAndTestWindows.yml

Fixes #4028 .
Tests still are not run, as they do not work on Windows (see #376).

[CI] Fix llvm-lit path for Windows build.

---

include/circt/Conversion/ExportVerilog.h
include/circt/Conversion/Passes.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
lib/Conversion/PassDetail.h
test/firtool/verbose-pass-executions.fir

Add simple test that helps CI check this in the future, crashes without the revert.
LoweringOptions as a PassOption crashes when printing (parsing from a pipeline probably doesn't work either), because it doesn't know how to handle it.
Specializing `cl::parser` might do the trick, or manually specifying our existing `LoweringOptionsParser` (unclear how to do this with ODS), or changing how these options reach the pass?
Regardless, revert until this is sorted.

Revert "[NFC] Make prepareforemission an embedded pass...", breaks -verbose-pass-executions

---

lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
lib/Conversion/HandshakeToHW/HandshakeToHW.cpp

Windows builder is currently complaining and failing:
```
[363/501] Building CXX object lib\Conversion\HandshakeToFIRRTL\CMakeFiles\obj.CIRCTHandshakeToFIRRTL.dir\HandshakeToFIRRTL.cpp.obj
D:\a\circt\circt\lib\Conversion\HandshakeToFIRRTL\HandshakeToFIRRTL.cpp(583): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
[364/501] Building CXX object lib\Conversion\HandshakeToHW\CMakeFiles\obj.CIRCTHandshakeToHW.dir\HandshakeToHW.cpp.obj
FAILED: lib/Conversion/HandshakeToHW/CMakeFiles/obj.CIRCTHandshakeToHW.dir/HandshakeToHW.cpp.obj 
C:\PROGRA~2\MICROS~2\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DGTEST_HAS_RTTI=0 -DUNICODE -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE …
```

[Handshake][NFC] Touchups to address error/warnings.

---

include/circt/Dialect/Handshake/HandshakeOps.td
lib/Dialect/Handshake/HandshakeOps.cpp
test/Dialect/Handshake/call.mlir
test/Dialect/Handshake/errors.mlir

This commit drops the outdated control signal requirement from `InstanceOp`.

[Handshake] Drop ctrl requirement from InstanceOp

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp

Small cleanup In StmtEmitter:
* `blockDeclarationInsertPoint` is only written, never used
* `blockDeclarationIndentLevel` is used but is same as normal indent (likely because we aren't inserting to different point anymore)

[ExportVerilog][NFC] Remove blockDeclaration* tracking as unused.

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp

Another unused cursor we no longer need to maintain (thanks for great cleanup/simplification work)!
Now only cursor is for retroactively adding 'begin' when emitting blocks of statements (see `StmtEmitter::emitBlockAsStatement`).
(Would've included in #4046 if had noticed then :+1: .)

[ExportVerilog][NFC] Drop another unused tracking cursor.

---

include/circt/Dialect/HW/HWAggregates.td
lib/Dialect/HW/HWOps.cpp
test/Dialect/HW/canonicalization.mlir

This PR adds a folder for array slice op to fold slice op which extracts entire inputs.

[HW] Add a folder for array slice op

---

lib/Dialect/SV/SVOps.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

Currently part select inout operations are restricted to integer types. This PR extends index part selects operators to arrays.

[SV] Allow packed arrays for index part select inout

---

test/Analysis/dependence-analysis.mlir
test/Analysis/scheduling-analysis.mlir

Needed for upcoming LLVM change.
(PR for CI check, peeled off of #4058).

[Analysis][NFC] Update tests to be more flexible re:result names.

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/dedup-errors.mlir

Update few error messages when `Dedup` fails for must dedup modules.
Check for mismatch in number of ports, and add special message for `RefType` ports.

[FIRRTL][Dedup] Update few error messages

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/decl-align.mlir

Before emitting a block of statements, we scan for all declarations (wires, regs, ...) and calculate the max width of the types and names so we can align the types and names neatly across declarations.
Previously declarations were (generally) gathered and emitted at the top, but now occur throughout (new emission mode).
There's a bug with how this works presently:
When emitting nested blocks of statements (always, etc.) the newly calculated widths override the existing ones-- resulting in wires/regs after the block being aligned using the widths from declarations within the block-- instead of using widths calculated for, and from, the declarations outside the block.
To fix this, simply save the widths and restore them after the block.
These declarations are sometimes a bit far apart for …

[ExportVerilog] Fix use of wrong decl alignment after emitting a block.

---

include/circt/Conversion/HandshakeToHW.h
include/circt/Dialect/Handshake/HandshakePasses.td
lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
lib/Dialect/Handshake/Transforms/CMakeLists.txt
lib/Dialect/Handshake/Transforms/LowerExtmemToHW.cpp
lib/Dialect/Handshake/Transforms/PassDetails.h
lib/Dialect/Handshake/Transforms/PassHelpers.cpp
test/Dialect/ESI/services.mlir
test/Dialect/Handshake/lower-extmem-esi.mlir
test/Dialect/Handshake/lower-extmem.mlir

This turned out to be a bit more complicated than I had expected (assumptions placed on the hardware interface of the module, this pass still need high-level memory info, index types are used for memory in Handshake, ESI strictly requires clog2(memory size) for address signals). I'm sure there's a more principled way of doing this, but that was not what flowed out of the fingers.
A wrapper is created which instantiates an `esi.mem.ram` service for each `memref` argument of the original handshake function. This wrapper also instantiates an external module which is a stand-in for the module that will be created during `HandshakeToHW`. The load- and store ports of the to-be-lowered instance are plumbed up with esi service requests.
Given a handshake function as follows, with 1 load and 1 …

[Handshake+ESI] Generate ESI memory service wrapper duing extmem lowering

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/firtool/firtool.fir

Improve critical path through muxes and array indexes by not adding an out-of-bounds mux, but rather extend the arrays to power of two.

[FIRRTL] Implement out-of-bounds as array extension

---

lib/Dialect/Handshake/Transforms/LowerExtmemToHW.cpp

ValueRange is like ArrayRef, keep ranges alive w/OwningArrayRef.
Caught by asan.

[Handshake] Fix stack-use-after-scope, keep ranges of values alive.

---

include/circt/Dialect/SV/SVPasses.h
include/circt/Dialect/SV/SVPasses.td
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/firtool/extract-test-code.fir
tools/firtool/firtool.cpp

These new additions are both fairly significant departures from past behavior, so add an ability to disable them. They remain enabled by default. The new flags are plumbed out to firtool flags so they can be disabled from firtool, and a test is added that this behavior can be controlled from firtool.

[SV] Add feature flags to new SVExtractTestCode features.

---

include/circt/Dialect/Seq/Seq.td
lib/Dialect/Seq/SeqOps.cpp
test/Dialect/Seq/canonicalization.mlir

Introduce additional folders and canonicalizers for the `FirRegOp` that deal with registers that have a constant clock or reset value. The FIRRTL spec states that the value of a register before the first clock edge is undefined (unless reset through an async reset), which allows us to pick a convenient value in the cases where a register is provably never clocked or never reset.
This also moves the canonicalizer for self-referential registers into the folder since it does not need to create arbitrary operations.

[Seq] Add const-clock and const-reset folders for FirRegOp

---

CMakeLists.txt

When we build CIRCT as a standalone project (not a unified build), we build gtest from scratch for our unit tests.  This is currently hard-coded to link against pthreads, which does not work on Windows. We can use the built in `Threads::Threads` cmake library which is more portable.  This fixes the unit test linking on Windows.

Link gtest against portable threading lib

---

.github/workflows/buildAndTestWindows.yml

Building with debug symbols makes it much easier to debug a crash in CI, which is sometimes necessary when you don't have access to a Windows machine to reproduce on.

Build CIRCT on Windows with debug symbols

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

This PR changes the way of lowering of subindex. Currently a subindex operation is lowered into an array index inout operation but this PR exchanges the order (e.g. `read_inout(array_index_inout a[i])` -> `array_get(read_inout a)[i]`).
Previously when we lower subindex operations used as source values, we dereference the inout operations with read_inout. Alternatively this PR lowers a source value subindex into an array_get operation. This modification invokes a lot of optimizations at SV/Comb/HW since usually dataflow analysis is blocked by inout operations. This PR solves https://github.com/llvm/circt/issues/4001 by not creating problematic IR in the first place.
Example:
```mlir
firrtl.module @LowerReadArrayInoutIntoArrayGet(in %a: !firrtl.uint<10>, out %b: !firrtl.uint<10>) {
%r = …
```

[LowerToHW] Lower source subindex into array_get instead of read_inout and array_index

---

lib/Dialect/LLHD/Simulator/Engine.cpp

This code is tripping ASAN warnings. Taking a suggestion from @youngar in the linked issue, it seems like there is a helper in LLVM to do what we want here. If I drop that suggestion in, the tests still pass and the ASAN warnings are fixed. I haven't thought about it deeply, but this seems to make sense. The comment suggested some concerns about handling big endian systems, which LoadIntFromMemory appears to already take into account.
Closes https://github.com/llvm/circt/issues/1071.

[LLHD] Update signal buffer loading to use LoadIntFromMemory helper.

---

include/circt/Dialect/Calyx/CalyxStructure.td
include/circt/Dialect/Comb/Combinational.td
include/circt/Dialect/ESI/ESIOps.td
include/circt/Dialect/ESI/ESIPorts.td
include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLStatements.td
include/circt/Dialect/HW/HWAggregates.td
include/circt/Dialect/HW/HWMiscOps.td
include/circt/Dialect/HW/HWStructure.td
include/circt/Dialect/HWArith/HWArithOps.td
include/circt/Dialect/Handshake/HandshakeOps.td
include/circt/Dialect/LLHD/IR/ExtractOps.td
include/circt/Dialect/LLHD/IR/ValueOps.td
include/circt/Dialect/MSFT/MSFTConstructs.td
include/circt/Dialect/MSFT/MSFTOps.td
include/circt/Dialect/Moore/MIRExpressions.td
include/circt/Dialect/Pipeline/Pipeline.td
include/circt/Dialect/SV/SVExpressions.td
include/circt/Dialect/SV/SVInOutOps.td
include/circt/Dialect/SV/SVStatements.td
include/circt/Dialect/SV/SVTypeDecl.td
include/circt/Dialect/Seq/Seq.td
include/circt/Dialect/SystemC/SystemCExpressions.td

Draft PR for bumping LLVM to top-of-tree.
This is scheduled to be merged on Friday 2022-10-14.
A new Conditionally Speculatable Interface was
added (https://reviews.llvm.org/D135505).  This required the following changes:
- Replace all usages of NoSideEffect with Pure.
- Replace usages of RecursiveSideEffects with RecursiveMemoryEffects and
RecursivelySpeculatable.

[llvm] Bump LLVM to top-of-tree

---

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code.mlir

This was raised on the issue that originally landed the inlining feature, but we weren't able to find an example of this in the wild. Of course, it has turned up: some modules only have inputs, feed test code, and thus meet the criteria for inlining. But they also might have internal signals that are not extracted, and form cycles in the SSA graph. The test case is the most trivial example, but more complex structures also hit the same bug and are fixed in the same way.
The solution is to use the same helpers that the main extraction logic uses to deal with comb cycles. These can be dropped in to the little inlining helper as-is and resolve the issue.

[SV] Fix SVExtractTestCode to handle inlining cycles.

---

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code.mlir

When we decide we can extract an instance, we must remove results of the instance from  the set of inputs to the extracted instance. Previously, we only removed one result at a time, as we iterated over the set of inputs. This is problematic when instances have multiple results, and all of them feed the test code. Because we add the instance to the test code set the first time we encounter one result and decide the instance should be extracted, the next iterations that visit the same instance do nothing, since we've already marked it for extraction.
The solution is simple: as soon as we've proved we can extract an instance, remove all of its results from the set of inputs to the extracted instance.

[SV] Fix SVExtractTestCode to extract all results of instances.

---

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code.mlir

We previously switched from eagerly erasing ops to clean up to lazily doing so after all IR mutations to fix a bug. This is important for any instances we extract and their forward dataflow, but as part of that change we also made the erasure of test code roots themselves lazy (the assert, assume, and cover statements). This causes issues in case any module with test code gets inlined later; the test code roots are revisited, extracted again, and duplicated. This is illegal, because some test code may include side effects, like printing to the console.
The solution is simple: make sure to eagerly erase all test code roots, and remove them from the set of ops to erase lazily, if they were reachable from an instance that is being extracted. The latter change is to prevent doubly erasing the …

[SV] Fix SVExtractTestCode to not duplicate when inlining.

---

lib/Conversion/LLHDToLLVM/LLHDToLLVM.cpp
lib/Dialect/LLHD/Simulator/State.cpp

Fixes some incorrect code since dividing by 64 and ceiling may override the buffer since the allocation is not rounded up to a 64 bit boundary.
I could not reproduce #4108 locally, but looking at the stack trace there, this should fix it. Can you confirm @dtzSiFive?

[llhd-sim] Fix: reference binding to misaligned address

---

lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp

This commit uses the NULL  `Node` to denote `GraphTraits::child_end` to `CheckCombCycles`. This avoids the unnecessary objects constructed by `SCCIterator` to indicate the end of iteration.
This saves >35% runtime on large designs.

[FIRRTL][CheckCombCycles] Use special class for End Iterator

---

include/circt/Dialect/FIRRTL/AnnotationDetails.h
include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/ResolveTraces.cpp
test/Dialect/FIRRTL/SFCTests/trace-api.fir
test/Dialect/FIRRTL/annotations.mlir
test/Dialect/FIRRTL/resolve-traces.mlir
tools/firtool/firtool.cpp

Add the ResolveTraces pass that implements Chisel's [Trace API](https://www.chisel-lang.org/api/latest/chisel3/experimental/Trace$.html).  This
pass updates TraceNameAnnotations with a "target" field indicating the
current FIRRTL Target value of the thing the Annotation is attached to.
The pass then writes these Annotations to a JSON verbatim blob outside
the circuit that will be written to a file derived from the Circuit
name.  The original Annotations are removed.
This API works by enabling users to attach "traces" to their Chisel
design to enable them to recover the final target in the compiled
Verilog.  This is intended to the be the low-level basis on top of which
Chsiel users can build their own tools that require information about
the final locations of things in Verilog, e.g., …

[FIRRTL] Add TraceNames Pass to Implement Chisel's Trace API

---

.github/workflows/buildAndTestWindows.yml

These debug symbols take up too much memory and prevent us from running in the CI container.  I enabled debug symbols a couple days ago, and the issue has surfaced once LLVM was bumped.  This still builds CIRCT in RelWithDebInfo mode.

[Windows] Don't build LLVM with debug symbols

---

lib/Dialect/Seq/SeqOps.cpp
test/Dialect/Seq/canonicalization.mlir

This PR implements a canonicalization to replace uninitialized aggregate registers with constant zeros. 
This fixes lint warnings with aggregate preservation builds. Eventually the canonicalization should be moved to a folder once aggregate constant is added.

[Seq] Replace uninitialized aggregate registers with constant zeros

---

lib/Dialect/Calyx/CalyxOps.cpp

When adding CombComponents, I missed this issue where the builder adds a ControlOp no matter if it is building a CombComponent or a regular Component. This change only has an effect when a CombComponent is built within circt, imported mlir works fine.

[Calyx] Fix CombComponent Builder

---

lib/Dialect/Calyx/CalyxOps.cpp
test/Dialect/Calyx/emit-comb-component.mlir
test/Dialect/Calyx/round-trip.mlir

The CalyxCell verifier was still accidentally pointing to ComponentOp as a parent instead of ComponentInterface. This prevented CalyxCells from actually being used properly in CombComponents. I also improved tests to make sure that CombComponents are usable in practice.

[Calyx] Fix CalyxCell verifier and improve tests

---

include/circt/Dialect/HW/CustomDirectiveImpl.h
include/circt/Dialect/HW/HWOps.h
include/circt/Dialect/HW/HWStructure.td
include/circt/Dialect/HW/InstanceImplementation.h
lib/Dialect/HW/CMakeLists.txt
lib/Dialect/HW/CustomDirectiveImpl.cpp
lib/Dialect/HW/HWOps.cpp
lib/Dialect/HW/InstanceImplementation.cpp
lib/Dialect/SystemC/SystemCOps.cpp

Move implementation code of the InstanceOp to a new InstanceImplementation file such that it can be included and reused in other dialects that need to implement a similar instance operation. It tries to extract code parts in a way that basic checks like same length of operand and argNames arrays, matching types, etc. are performed in a way that it does not need to know about the module or instance operations and thus are also applicable in more generic cases. However, it also provides functions that require the instantiated module to be a HW module and thus allow for more code reuse for instance operations that can only refer to those.
Useful custom directives for table-gen assembly formats are collected in a separate file that should only be included in cpp files, while the …

[HW] Refactor InstanceOp implementation to enable code reuse

---

include/circt/Dialect/SystemC/SystemCOps.h
include/circt/Dialect/SystemC/SystemCStructure.td
lib/Dialect/HW/InstanceImplementation.cpp
lib/Dialect/SystemC/SystemCOps.cpp
test/Dialect/HW/errors.mlir
test/Dialect/SystemC/module-error.mlir
test/Dialect/SystemC/structure.mlir

This operation instantiates a hw module that is or will be verilated and allows to generate the necessary interoperability layer to talk to the verilated module in various contexts, i.e., in a SystemC module, a Verilog module, inside a CIRCT based simulator, etc. Having a separate instance operation avoids transformations performed on the regular hw instance such as inlining, etc. and allows to add more attributes to specify the configuration under which the instantiated module was verilated.

[SystemC] Add interop.verilated operation

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-typedecls.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir

This commit adds include guards to a `hw.type_scope` when emitted.
```mlir
hw.type_scope @_other_scope {
hw.typedecl @foo, "_other_scope_foo" : i2
}
```
emits as
```sv
`ifndef _TYPESCOPE__other_scope
`define _TYPESCOPE__other_scope
typedef logic [1:0] _other_scope_foo;
`endif // _TYPESCOPE__other_scope
```
There's no attribute to disable this - I didn't see the need for that, but if someone has an example of where such guards on the emitted typedefs would break stuff, then an attribute could obviously be added.
I considered the alternative of making the include guards and guard definition a part of the IR and require the source generator (in our case `FSMToSV`)  to ensure scoping of the typescope:
```mlir
sv.ifdef "_fsm_enum_typedefs" {
sv.verbatim "`define _fsm_enum_typedefs" …
```

[ExportVerilog] Emit `hw.type_scope` with include guards

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/dedup.mlir

Limit locations from .fir files when deduplicating modules.  These locations add little value.  This has the unfortunate side-effect of embedding special handling of location data based on filename string, but I don't see a better way right now.
End-to-end performance increase on a large core: 15%
Memory reduction on a large core: 50%

[FIRRTL] limit useless locs in dedup

---

include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h
lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Dialect/FIRRTL/blackbox-reader.mlir

Change BlackBoxReader pass to ignore a TestBenchDirAnnotation if no MarkDUTAnnotation exists.  This comes up for some internal designs where the former exists, but the latter does not.
The first commit is ~NFC and just factors out DUT-finding logic from GCT to make it usable in BlackBoxReader.

[FIRRTL] Ignore TestBenchDirAnno if no DUT in BlackBoxReader

---

lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
test/Conversion/StandardToHandshake/errors.mlir

Converts a crash to an error. Should have already been checked - unshaped/singleton memrefs are already banned as top-level args and this is just an oversight. Follow-up work will determine whether to actually support this.

[StdToHandshake] Error on unshaped unidimensional arrays

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

When emitting IfOp, we recursively look for another IfOp in the else branch so we can emit a nicer `else if`.
While doing this, reset the set of operations contributing to location information to those for the active IfOp and its condition.
The final `else` will have the information for the last IfOp processed.
(also ensures the "hoisted" IfOp is included in the set, which it isn't currently)

[ExportVerilog] Don't combine location info across if/elseif chains.

---

include/circt/Dialect/Comb/Combinational.td
lib/Dialect/Comb/CombFolds.cpp
test/Dialect/HW/canonicalization.mlir

Array create operations which build arrays from muxes with identical conditions are turned into muxes of arrays.
An inverse transformation scalarizes the muxes if their array arguments are uniform.

[HW][Comb] Canonicalize muxes of arrays

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp

[ExportVerilog] Drop ForceEmitMultiUse precedence sentinel.

---

docs/VerilogGeneration.md
include/circt/Support/LoweringOptions.h
include/circt/Support/LoweringOptionsParser.h
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
lib/Support/LoweringOptions.cpp
test/Conversion/ExportVerilog/prepare-for-emission.mlir

This PR moves `spillAllMux` option to normal lowering options. At SiFive, inlining mux was positively accepted by designers to improve readability and interestingly it also increased simulation performance. Hence the option is changed from the category "heuristic" to a normal option. In addition to that, the place where spilling happens is also changed. This change makes `reuseExistingInout` applicable to mux spilling as well.

[PrepareForEmission, LoweringOptions] Change spillAllMux to normal option

---

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
test/Dialect/FIRRTL/imconstprop.mlir

`firrtl.verbatim.expr` result must be marked as over-defined, otherwise it will be  dropped!
Fixes https://github.com/llvm/circt/issues/4157

[FIRRTL][IMConstProp] Mark Verbatim Expr as overdefined

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/annotations.mlir

This fixes a bug in GrandCentralTaps, which crashes when the source of the tap has unknown width.
The pass adds `AsUIntPrimOp` cast when tap source and sink types donot match for ResetTypes. This cast should not be used for unknown widths kind of mismatch.
Fixes https://github.com/llvm/circt/issues/4158

[FIRRTL][GrandCentralTaps] Handle Unknown source widths

---

include/circt/Dialect/SystemC/SystemC.td
include/circt/Dialect/SystemC/SystemCStatements.td
include/circt/Dialect/SystemC/SystemCStructure.td
integration_test/Target/ExportSystemC/func.mlir
lib/Dialect/SystemC/SystemCOps.cpp
lib/Target/ExportSystemC/EmissionPrinter.cpp
lib/Target/ExportSystemC/Patterns/SystemCEmissionPatterns.cpp
test/Dialect/SystemC/func-invalid.mlir
test/Dialect/SystemC/func.mlir
test/Dialect/SystemC/module-error.mlir
test/Target/ExportSystemC/func.mlir

Emit functions from the func dialect as regular C functions. This is useful for interop when we, e.g., want to wrap some C++ code in a C function such that a caller which does not support C++ can still call that code.
`call_indirect` is also especially useful for calling member functions accessed by `systemc.cpp.member_access`.

[ExportSystemC] Support operations from func dialect

---

include/circt/Dialect/Seq/SeqPasses.h
include/circt/Dialect/Seq/SeqPasses.td
lib/Dialect/Seq/SeqTypes.cpp
lib/Dialect/Seq/Transforms/CMakeLists.txt
lib/Dialect/Seq/Transforms/LowerSeqHLMem.cpp
test/Dialect/Seq/lower-hlmem.mlir

This commit adds a fallback/default pattern for lowering `seq.hlmem` operations. The implementation is based on the ESI ram service lowering, and provides a behavioral lowering. The intention of this lowering is to provide a pattern that will almost guarantee to synthesize on FPGAs - QoR not guaranteed. "Better"/target-specific patterns can be added by adding patterns with higher benefit - which will match with higher priority.
Read ports with arbitrary (N) latency are realized by performing a combinational read, and registering the read value N times.
Write ports are only supported for latency == 1.

[Seq] Add behavioral `seq.hlmem` lowering

---

include/circt/Dialect/FIRRTL/FIRRTLStructure.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/errors.mlir

Checks constraints are checked before running the verifier, in particular that SymbolTable is checked before assuming we can build it.
Fixes #4174.
See: https://mlir.llvm.org/docs/OpDefinitions/#verification-ordering .

[FIRRTL] Move CircuitOp verify to verifyRegions.

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/SV/hw-memsim.mlir

This fixes an issue that mux pragmas cause a complication failure when the array size is 1. Ideally such array/memory should be canonicalized in the first place though

[LowerToHW, HWMemSimImpl] Remove mux pragmas when size is 1

---

lib/Dialect/HW/HWOps.cpp
test/Dialect/HW/canonicalization.mlir

If a concat operation merges consecutive slices or elements, the arguments are concatenated for readability.

[HW] Concatenate slice ops in array_concat

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp

Appease clang-tidy.
The recursion warnings are legitimate as the entire emission is very recursive, sometimes on the IR.
Used begin/end lint disable to ensure lambdas (common w/`TypeSwitch) don't trigger the warnings, I'm not sure if this is supposed to be necessary.

[ExportVerilog][NFC] Appease clang-tidy

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir
test/Dialect/FIRRTL/grand-central.mlir

Change Grand Central (GCT) View behavior that determines which output
directories are used for blackboxes which are instantiated by both
inside and outside the View's companion module.  Previously, if in both
then the blackbox was placed in the View's directory.  This is changed
to not modify the output directory of the blackbox.  Only blackboxes
which are _exclusively_ instantiated by the View are moved.
Change modules to also have the above behavior.  Previously, module
submodules were not moved.
This moves closer to SFC behavior.  In the SFC, modules instantiated
exclusively in the View are moved.  Modules instantiated in both are
copied in both output directories.
This includes a preliminary commit, intended to land separately, that moves a WireDFT utility to make it more widely …

[FIRRTL] Fix GCT output dir for mod/extmod

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/ExportVerilogInternals.h
lib/Conversion/ExportVerilog/PruneZeroValuedLogic.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Conversion/ExportVerilog/pruning.mlir

This commit adds additional patterns for pruning operations that may be contained within a cone of zero-valued logic. Any operation which generates an `i0` result that is used by an operation that may legally use `i0` valued logic (output, indexing operations), values is replaced by an `i0` constant.

[ExportVerilog] Add more zero-valued logic pruning patterns

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir

Previously, the zero-width constant value had only been handled through a special case in `hw.array_get`. However, an i0 value may also be used elsewhere where emission is delegated all the way through to the `hw.constant` op. This commit adds the required special case handling, and a test for `sv.array_index_inout`.

[ExportVerilog] Fix zero-width `hw.constant` emission

---

lib/Conversion/FSMToSV/FSMToSV.cpp
test/Conversion/FSMToSV/test_basic.mlir

... emitting these as sv `wire`s will clash with some synthesizers restrictions on 4 state logic.

[FSMToSV] Emit fsm enum values as regs

---

lib/Conversion/ExportVerilog/PruneZeroValuedLogic.cpp
test/Conversion/ExportVerilog/pruning.mlir

This implements i0 value legalizations for concat/parity/icmp (ref: https://github.com/llvm/circt/pull/3935#issuecomment-1259835432). These operations can have i0 values as an operand but we cannot  just remove them since they produce non-i0 values. 
1. concat -> Filter non-i0 values
2. `partiy 0:i0` -> `0: i1`
3. ` icmp pred 0:i0, 0:i0` -> Calculate the result with `applyCmpPredicateToEqualOperands`

[PruneZeroValuedLogic] Legalize concat/parity/icmp

---

include/circt/Dialect/SystemC/SystemCStatements.td
integration_test/Target/ExportSystemC/basic.mlir
lib/Target/ExportSystemC/Patterns/SystemCEmissionPatterns.cpp
test/Dialect/SystemC/structure.mlir
test/Target/ExportSystemC/basic.mlir

This convenience macro is not part of the standard but heavily used. Thus I think it makes sense to add support for it here.
https://github.com/accellera-official/systemc/blob/master/RELEASENOTES#L281

[SystemC] SC_NAMED support for signals

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

This PR fixes invalid emission of i0 values contained in structs. Currently i0 value in struct types are emitted as `logic` but 
`logic` is 1bit width value so it causes width missmatches in many cases. This fixes that issue by just eliding the field entirely and emit them as comments. 
Fixes https://github.com/llvm/circt/issues/4203 and https://github.com/llvm/circt/issues/2504

[ExportVerilog] Fix i0 value emission of struct operations

---

include/circt/Dialect/SystemC/SystemCStatements.td
integration_test/Target/ExportSystemC/basic.mlir
lib/Conversion/HWToSystemC/HWToSystemC.cpp
lib/Dialect/SystemC/SystemCOps.cpp
lib/Target/ExportSystemC/Patterns/SystemCEmissionPatterns.cpp
test/Conversion/HWToSystemC/structure.mlir
test/Dialect/SystemC/canonicalize.mlir
test/Dialect/SystemC/module-error.mlir
test/Dialect/SystemC/structure.mlir
test/Target/ExportSystemC/basic.mlir

Properly registering the sensitivities is important for emitting a correct SystemC module. This PR adds the operation to represent this in the IR, the emission pattern for it, and also adjusts the lowering from HW.
Useful specialized events such as `pos()` and `neg()` on boolean input channels are not supported yet, but can easily be added.

[SystemC] Add SensitiveOp to register sensitivity events for unspawned processes

---

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code.mlir

Notably, when inlining the body of a module, any instances in the body should be added to the new parent module in the instance graph. The instances in the old body are already being removed from the instance graph when we remove the old module. This fixes an issue where instances that were inlined appeared to have no uses, and were erroneously moved to the testbench.
This also makes sure to add modules created to hold extracted test code to the instance graph. This bookeeping is important so the above can work, and find the newly created module during inlining.
Finally, this makes sure not to duplicate instances that have been extracted when their parent module is inlined.

[SV] Fix SVExtractTestCode to keep the instance graph up to date.

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
include/circt/Dialect/FIRRTL/FIRRTLStructure.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp

Add `insertPorts` and `erasePorts` interface methods to `FModuleLike`.  This makes the utility common to `FModuleOp`, `FExtModuleOp` and `FMemModuleOp`.

[FIRRTL] Add insert/delete ports to FModuleLike interface

---

include/circt/Dialect/SSP/PropertyBase.td
include/circt/Dialect/SSP/SSPAttributes.td

Allow properties to specifically override the converter expressions used to convert between the C++ problem model and MLIR attribute worlds.

[SSP] Reduce code duplication in property definitions.

---

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp

Update the `FModuleOp` input of `addPortsToModule` to `FModuleLike`. This ensures that new ports can be added to extern modules also.

[FIRRTL] Update addPortsToModule to work with FModuleLike

---

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code.mlir

If the instance has an inner symbol attribute, something is referring to it non-locally. Without further analysis or updates, we can't safely move such instances.
This adopts the same conservative approach we already have in place
for inlining: if we see a symbol, just skip it.

[SV] Update SVExtractTestCode to not extract instances with syms.
