llvm/circt

include/circt/Dialect/HW/HWOps.h
include/circt/Dialect/SV/SVStatements.td
lib/Dialect/HW/HWOps.cpp
lib/Dialect/SV/SVOps.cpp
test/Dialect/SV/canonicalization.mlir

This PR implements a canonicalizer to merge neighboring procedural assignments, e.g:
```
a[0] <= b[1]
a[1] <= b[2]
a[2] <= b[3]
->
a[2:0] <= b[3:1]
```
For a procedural assignment, we first check the next operation is the same kind of an assignment. If so, we check both of dest values are array indexing inout operations that point at neighboring elements.

[SV] Implement a canonicalizer to merge neighboring procedural assignments

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Dialect/FIRRTL/grand-central.mlir

Fix the behavior of Grand Central (GCT) Views directory placement for modules which are instantiated in the GCT View Companion module and also in the testbench, but not the DUT (as indicated by a MarkDUTAnnotation). Previously, the check would only move modules exclusively instantiated under the companion.  This would cause modules instantiated in the testbench (above the DUT) to wind up in the DUT directory and cause problems for downstream physical design tooling that wants to only see design Verilog in the DUT directory.
This PR leaves in old tests that were added/updated in https://github.com/llvm/circt/pull/4180. This is intentional to indicate that there is no functionality change to existing tests. The large tests …

[FIRRTL] Fix GCT View Directory Behavior for DUT

---

unittests/Support/PrettyPrinterTest.cpp

Maybe this: https://developercommunity.visualstudio.com/t/c2017-illegal-escape-sequence-when-using-in-a-raw/919371 .
Anyway, simplify test so no raw string needed.
Windows build: https://github.com/llvm/circt/actions/runs/3374258722/jobs/5599694000 .

PrettyPrinterTest: fix raw string for MSVC.

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/canonicalization.mlir
test/Dialect/FIRRTL/lower-types.mlir

Add support for directly making aggregates rather than having to use a wire.  Also support constant aggregates.  Add canonicalization to transform aggregate wires with field-wise writes to single writes.

[FIRRTL] Add Aggregate creation ops and aggregate constants

---

lib/Support/PrettyPrinterHelpers.cpp

Don't make folks count these out :).
Per review feedback: https://github.com/llvm/circt/pull/4192#discussion_r1011004597 .
Also, tweak comparison against character count to use them all not `N-1`, modulo that NFCI.

[PrettyPrinter] constexpr instead of giant array literal.

---

include/circt/Dialect/SV/SVStatements.td
include/circt/Dialect/SV/SVVisitors.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/verilog-basic.mlir
test/Dialect/SV/basic.mlir

Add a new operation to the SystemVerilog Dialect: ReadMemOp.  This
operation exists to model both "$readmemb" and "$readmemh".  These
operations cause a specific memory to be loaded with the contents of a
file.
These operations do not (yet) model the ability of their Verilog
counterparts to load part of a memory.
Add emission of the SystemVerilog Dialect's ReadMemOp.  This emits as
either "$readmemb" or "$readmemh" depending on a mandatory enum used to
build the operation.

[SV][ExportVerilog] Add ReadMemOp to model $readmemb, $readmemh

---

include/circt/Support/PrettyPrinterHelpers.h
unittests/Support/PrettyPrinterTest.cpp

Useful for ExportVerilog and generally making it easier to track "box" scopes and ensure they're closed.

[PrettyPrinter] Add scopedBox helper, to replace previous scoped helpers.

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td

Don't create many attributes (even empty ones) just to throw
them away.  Also, cache the single entry if creating any,
save cost of repeatedly uniquing in `Attribute::get`.
This is significant when there are thousands of ports
(and if this is done thousands of times).
On one design, improves speed of LowerAnnotations 720s -> 640s.
There's still some copying/array-fill going on that could be tightened,
(especially in case where array is all valid or empty, and/or the caller
already has a suitable `SmallVector<>`.)
but this gets this code from appearing constantly in sampled stacks.
Tweak `setPortSymbolAttr` to use `fixupPortSymsArray` and set the
attribute directly to avoid copying the array it just created.

[FIRRTL] Significantly improve performance setting port syms.

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Dialect/FIRRTL/grand-central.mlir

Get the interface name directly from the `InterfaceOp`, instead of deriving from the string. This ensures renamed interface names are correctly used in the  `VerbatimOp`.
Fixes https://github.com/llvm/circt/issues/4234

[FIRRTL][GrandCentral]  Get the correct Subinterface name

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLDialect.cpp
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

This PR moves the aggregate creation when all arguments are constants from a canonicalization to a folder, and adds folders of subindex and subfield of constants.

[FIRRTL] Add folds for aggregate constants and subaccesses

---

lib/Conversion/HWArithToHW/HWArithToHW.cpp

This commit propagates attributes from source ops to the "main" generated comb operations. Furthermore, tries to create meaningful names for bit extractions and width extensions.
Fixes #4225.

[HWArith] Propagate (and improve) sv.namehints in HW lowering

---

include/circt/Conversion/FIRRTLToHW.h
include/circt/Conversion/Passes.td
include/circt/Dialect/SV/SVPasses.h
include/circt/Dialect/SV/SVPasses.td
include/circt/Dialect/Seq/SeqPasses.h
include/circt/Dialect/Seq/SeqPasses.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/SV/hw-memsim.mlir
test/Dialect/Seq/firreg.mlir
test/firtool/memory.fir
tools/firtool/firtool.cpp

Primarily introduce `firtool` options `--disable-{reg,mem,all}-randomization`.
Fixes #4202 .

Add options for controlling emission of randomization code.

---

test/Dialect/FIRRTL/grand-central-errors.mlir
test/Dialect/FIRRTL/grand-central.mlir

Convert existing Grand Central (GCT) Views tests from the old Annotation-style to the new RefType style.  The old style is no longer generated by LowerAnnotations.  This commit is done in preparation to remove old Annotation-style handling code paths from the GrandCentral pass.
Remove all tests which are no longer necessary given that reference types are now used or that are redundant with more comprehensive tests.
For more information, I am trying to entirely remove the legacy Annotation code path from the GrandCentral pass. Very precisely, this makes [this code path](https://github.com/llvm/circt/blob/11a95bfacba90067940351fa042251875e7fac41/lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp#L1410-L1496) non-load-bearing. I'm …

[FIRRTL] Cleanup GCT Views Tests to RefType, NFC

---

docs/Dialects/Seq/RationaleSeq.md

* Drop mention of `randomized`.
* Fixup operand printing, "clock" and "sym" keywords, etc.

[docs][Seq] Fixup seq.firreg documentation to reflect current op.

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp

The DenseMap can get reassigned during assignment, so avoid any stale iterator reads.
This commit fixes a bug and an invalid memory read due to DenseMap reallocation by copying the value to a temporary before inserting it back to the DenseMap.

[FIRRTL][LowerXMR] Copy DenseMap to temporary before insertion

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/SFCTests/data-taps.fir
test/Dialect/FIRRTL/SFCTests/emit-omir.fir
test/Dialect/FIRRTL/simplify-mems.mlir
test/firtool/prefixMemory.fir

Added the following canonicalizers:
- Removed memory ports whose enable flags are constant 0.
- Converted write-only read-write ports to write ports.
- Removed write-only or read-only memories.
The transformation respects the `DontTouch` annotation placed on memories and does not change annotated ports.

[FIRRTL][MemOp] Removed unused ports from memories

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp

Use `InstanceGraph` to get the `referencedModule`. This is more efficient than querying on the `InstanceOp`.

[FIRRTL][LowerXMR] Use InstanceGraph to get referencedModule

---

test/Conversion/ExportVerilog/verilog-basic.mlir

Don't define same inner symbol twice, fix crash when pointing firtool at this file.
cc #4267 .

[NFC] verilog-basic.mlir: Fix duplicate definition of symbol in test case.

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
lib/Dialect/FIRRTL/Transforms/DropName.cpp

Currently DropName pass creates a tremendous number of name kind attributes which require unnecessary interning. This PR changes to reuse a namekind attribute.

[DropNames] Reuse a droppable name attribute, nfc

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

The operand order of VectorCreateOp is the opposite to ArrayCreateOp. We have to invert the order while lowering.

[LowerToHW] Fix the operand order of VectorCreateOp lowering

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

I don't believe this patter is triggering, but these are the remaining firrtl canonicalizers which are picking concrete values for invalid (incorrectly).

Remove invalids from canonicalizers. They are always wrong.

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp
test/Dialect/FIRRTL/SFCTests/data-taps-more-xmrs.fir
test/Dialect/FIRRTL/SFCTests/data-taps-xmr.fir
test/Dialect/FIRRTL/SFCTests/mem-taps-reg.fir
test/Dialect/FIRRTL/SFCTests/mem-taps.fir
test/Dialect/FIRRTL/canonicalization.mlir
test/Dialect/FIRRTL/simplify-mems.mlir
test/firtool/name-preservation.fir

Wire and Nodes are semantically equivlent and differ on only being SSA or connect.  SSA is nicer, so we prefer to move wires into this form when we can.

[FIRRTL] Convert Wires To Nodes when dominance allows

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Dialect/FIRRTL/grand-central-errors.mlir

Remove code paths inside the Grand Central (GCT) Views pass associated with old-style Annotation-encoded paths.  Support for RefTypes landed previously and LowerAnnotations no longer emits the old-style.
Improve the check that the discovered Annotations match the new format and not the old-style.  Add tests that these error messages work.

[FIRRTL] Remove Annotation-style GCT Views

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
lib/Dialect/SV/SVOps.cpp
test/Dialect/HW/canonicalization.mlir
test/firtool/memory.fir

This implements a name hint propagation to a wire op canonicalization. 
```
%foo = sv.wire
%0 = comb.add ....
sv.assign %foo, %0
...
```
will be converted into
```
%0 = comb.add {sv.namehint = "foo"}
...
```
This also improves wire spilling logic by allowing expressions used only procedural assignments.

[SV][Prepare] Improve a namehint propagation and spilling logic

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
test/Dialect/FIRRTL/canonicalization.mlir

Fix a bug introduced in cc220a1e where a register canonicalizer would erroneously RAUW to its assignments.  Change this to only do the rewrite if the register is undriven.

[FIRRTL] Fix RegResetWithOneReset Canonicalizer

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Dialect/FIRRTL/annotations.mlir

Change Grand Central (GCT) Views Annotation application logic to always
create a dummy node to store the value of something that is a field of
an interface.  This makes logic during the actual GCT pass simpler (and
easier to check) as this now guarantees that the pass will always see a
node with a DontTouchAnnotation, even for designs where the view is
composed of things inside the companion module.
Relax an overly aggressive check in the Grand Central (GCT) Views pass
which was incorrectly asserting that the source of a SystemVerilog
Interface's field had to be a node of a RefResolveOp or ConstantOp.
This can actually be anything and it will still work.
Fixes #4277 (introduced in 2d3a040f43053d10d195980626ed321a653a89f4). …

[FIRRTL] Guarantee NodeOp in GCT View

---

lib/Dialect/Handshake/HandshakeOps.cpp

Looks like ValueRange stores address of Value,
so just construct in-place for the replaceOp call.
Fixes #4282.

[Handshake] Fix ValueRange lifetime issue.

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/dedup.mlir

When we merge two modules, sometimes we have to add more context to a non-local annotation.  When this happens, we create a new hierarchical path operation and update all annotations to use the new path.  In order for us to find all annotations which need to be updated, we store a mapping, `targetMap`, from each HierPathOp to the annotations that reference them.  This fixes a bug where we were not keeping the `targetMap` updated when we copy a non-local annotation when deduping operations. This is a regression from
46e9b214329de820368ecf2956bd0c3aff43cf36, where we stopped updating the target map.  See
https://github.com/llvm/circt/commit/46e9b214329de820368ecf2956bd0c3aff43cf36#diff-d0c16a1337e2a6200ae0f4c763fadb7ddaa3f8b389130aa04cd1e61ff2fba7eaL896 for the exact line that was removed.

[FIRRTL][Dedup] Fix cloning annotations for more context

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

This implements a lowering of aggregate constant op. Currently we only support 1d vector until we have hw constant aggregat.

[LowerToHW] Support 1d vector aggregate constant

---

lib/Dialect/ESI/capnp/Schema.cpp
lib/Dialect/ESI/cosim/cosim_dpi_server/DpiEntryPoints.cpp
tools/circt-rtl-sim/circt-rtl-sim.py.in
tools/circt-rtl-sim/driver.cpp.in

We were passing in CFLAGS improperly. Also add fix some asserts in the ESI capnp decoder modules to support `i0`.

[RTL-SIM] Fix trace debug output in Verilator driver

---

docs/Dialects/SSP/RationaleSSP.md
include/circt/Dialect/SSP/SSPAttributes.td
include/circt/Dialect/SSP/SSPOps.td
include/circt/Dialect/SSP/Utilities.h
lib/Dialect/SSP/SSPOps.cpp
test/Dialect/SSP/errors.mlir
test/Dialect/SSP/roundtrip.mlir
test/Dialect/SSP/standalone-lib.mlir

Motivated by: https://github.com/llvm/circt/pull/4216#issuecomment-1298244329
Draft status because I have to think about potential problems/benefits of allowing named operator libraries inside an ssp.instance`.

[SSP] Allow standalone use of `OperatorLibraryOp`.

---

lib/Dialect/ESI/ESIPasses.cpp
lib/Dialect/ESI/ESIServices.cpp
test/Dialect/ESI/services_collateral.mlir

A "BSP" is a service provider which implements any and all service declarations. It is intended to live at the top of a service hierarchy to provide board-level services (e.g. host connectivity). Add support for BSPs in the service metadata output.

[ESI] Support BSPs in service metadata emission

---

include/circt/Support/Version.h
tools/circt-as/circt-as.cpp
tools/circt-dis/circt-dis.cpp
tools/circt-lsp-server/circt-lsp-server.cpp
tools/circt-opt/circt-opt.cpp
tools/circt-reduce/circt-reduce.cpp
tools/circt-translate/circt-translate.cpp
tools/firtool/firtool.cpp
tools/handshake-runner/handshake-runner.cpp
tools/hlstool/hlstool.cpp
tools/llhd-sim/llhd-sim.cpp

Change all existing CIRCT tools to use a CIRCT-specific bug report message.  Previously a crash would tell people to file a bug on LLVM which isn't correct.
Example new output:
```
Assertion failed: (false), function main, file firtool.cpp, line 1075.
PLEASE submit a bug report to https://github.com/llvm/circt and include the crash backtrace.
Stack dump:
0.      Program arguments: firtool Foo.fir
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  firtool                  0x000000011014bd2d llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 61
1  firtool                  0x000000011014c2ab PrintStackTraceSignalHandler(void*) + …
```

[tools] Change tools to use CIRCT-specific bug msg

---

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
test/Dialect/FIRRTL/annotations.mlir

Add WiringProblem infrastructure and enable its use in
LowerAnnotations.  This defines an array of WiringProblems that a user
can add to during LowerAnnotations.  Each WiringProblem is a request for
a source Value to be connected to a sink Value in the design using
RefType ports.  LowerAnnotations is then changed to solve all
WiringProblems are bore RefType bores through the design.
This is done in preparation for switching Grand Central Taps and Views
to using this infrastructure instead of its current poorly performing
algorithm that bores ports one at a time.
Change Grand Central (GCT) Views annotation application to construct
WiringProblems.  This causes LowerAnnotations to efficiently bore
RefType ports as opposed to the current approach of boring ports
one-at-a-time.
Signed-off-by: …

[FIRRTL] Add WiringProblem Solver to LowerAnnotations, use for GrandCentral Views

---

include/circt/Dialect/FIRRTL/AnnotationDetails.h
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/PrefixModules.cpp
test/Dialect/FIRRTL/grand-central-errors.mlir
test/Dialect/FIRRTL/grand-central.mlir

Get rid of the Grand Central "Parent" Annotation.  This is no longer necessary now that the SV Interface is instantiated inside the companion module.  Keeping track of the parent of this companion is unnecessary.

[FIRRTL] Remove Grand Central Parent Annotation

---

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code.mlir

We already skip over extracting from already bound instances to prevent binds under binds. And we already do not inline or extract instances that have an inner ref. But sometimes we extract test code from a module that contains a bound instance sibling to the newly bound test code instances, and then inline an instance of that module.
In that case, the bind needs to be updated. To support this, the BindTable is pre-populated with already bound instances, and the existing logic to update binds during inlining fixes them up.

[SV] Update SVExtractTestCode to handle already bound instances.

---

include/circt/Dialect/Seq/SeqPasses.h
lib/Dialect/Seq/Transforms/LowerSeqHLMem.cpp
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
lib/Dialect/Seq/Transforms/PassDetails.h
tools/firtool/firtool.cpp

This applies a new pass generation method(ref:https://github.com/llvm/circt/issues/3962) to seq dialect passes, that automatically defines a struct of options (e.g. `LowerSeqFIRRTLToSVOptions`) and creates a pass constructor to take the option.

[Seq] Use a new pass generation mechanism

---

include/circt/Dialect/SSP/SSPAttributes.td
include/circt/Dialect/SSP/Utilities.h
lib/Scheduling/TestPasses.cpp
test/Dialect/SSP/roundtrip.mlir

This PR adds the missing dialect attribute definitions for the `ChainingProblem`'s properties. I had to model the payload as a `FloatAttr` (and use custom wrap/unwrap expressions) instead of a plain `float` value due to lack of support in the generic attribute parser.

[SSP] Define ChainingProblem's properties.

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

This supports i0 value operand of verification statements. Following the implementation of printf, we use i1 value as a result.

[LowerToHW] Lower i0 operand in printf-encoded assertions to i1

---

docs/Dialects/FIRRTL/FIRRTLAnnotations.md

API doc links to chisel-lang.org no longer work, and are not redirected to their new home due to (I believe) hosting limitations.
As a temporary-maybe-permanent workaround, link to their new home including specific third-party host and pinned Scala version.

[docs][NFC] Fix dead chisel-lang API links "temporarily".

---

lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir
test/Dialect/FIRRTL/annotations.mlir

Change the connect utility lambda used during WiringProblem solving to connect sources to sinks to (manually) canonicalize unused wire sinks to nodes.  This cleans up a pattern that is necessarily emitted during Grand Central View Annotation handling where the final sink is created as a wire (as it does not yet have any driver until the WiringProblem it creates is solved).  Later, the Grand Central View pass expects to only see nodes and not wires.  By doing the canonicalization inside the WiringProblem solver, this avoids needing to rely on a wire2node canonicalization which may or may not be run.
Put differently, this gets Grand Central views to work with --disable-opt.

[FIRRTL] Change Wires to Nodes in WiringProblems

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp
test/Dialect/FIRRTL/SFCTests/data-taps-more-xmrs.fir
test/Dialect/FIRRTL/SFCTests/data-taps-xmr.fir
test/Dialect/FIRRTL/SFCTests/mem-taps-reg.fir
test/Dialect/FIRRTL/SFCTests/mem-taps.fir
test/Dialect/FIRRTL/canonicalization.mlir
test/Dialect/FIRRTL/simplify-mems.mlir
test/firtool/name-preservation.fir

This reverts commit 5ef429e31b015dca88b1c1e6c3058a9d10e0e0c3. Test failures should be fixed by  https://github.com/llvm/circt/pull/4312

Revert "[FIRRTL] Convert Wires To Nodes when dominance allows (#4253)"

---

include/circt/Dialect/SV/SVTypeDecl.td
lib/Dialect/SV/SVOps.cpp
test/Conversion/ExportVerilog/name-legalize.mlir
test/Dialect/ESI/connectivity.mlir
test/Dialect/ESI/cosim_structs.mlir
test/Dialect/ESI/lowering.mlir
test/Dialect/ESI/wrapif-lowering.mlir
test/Dialect/FIRRTL/grand-central.mlir
test/Dialect/SV/interfaces.mlir

1. Verify that sv.interface.instance ops have a nonempty name.
2. Implement the HasCustomSSAName op interface for sv.interface.instance, so that the name attribute can be round tripped properly as the result's ssa name (parsing the name worked, printing the name would fall back to the attr-dict format).
Fixes: https://github.com/llvm/circt/issues/4134

[SV] Verify that sv.interface.instance ops have a nonempty name

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td

Fix a bug in the MultibitMuxOp ODS specification where it would accept something of any type.  This should only accept something of UIntType.

[FIRRTL] Require MultibitMuxOp Index is Unsigned

---

lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp
test/Dialect/FIRRTL/check-comb-cycles.mlir

This commit detects loops because of input port bouncing.
Fixes https://github.com/llvm/circt/issues/4327

[FIRRTL][CheckCombCycles] Detect input port self loops

---

include/circt/Dialect/SSP/SSPOps.td
include/circt/Dialect/SSP/Utilities.h
include/circt/Scheduling/Problems.h
lib/Scheduling/TestPasses.cpp
test/Dialect/SSP/roundtrip.mlir
test/Dialect/SSP/standalone-lib.mlir

This PR restores the feature parity between the scheduling infra's `Problem` class and the SSP dialect, and is important for roundtripping instances without [weird restrictions](https://github.com/llvm/circt/pull/4222#issuecomment-1310514507).
- On the `Problem` side, I added optional name attributes for the instance, operator library and operations.
- On the `ssp` side, I made the instance name symbol optional.
I plan to extend the DOT export and error messages to use these names in follow-up PRs.

[Scheduling][SSP] Restore feature parity between infra and dialect.

---

include/circt/Support/PrettyPrinterHelpers.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Conversion/ExportVerilog/line-length.mlir
test/Conversion/ExportVerilog/no-wrap.mlir
test/Conversion/ExportVerilog/pretty.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir
test/Dialect/FIRRTL/SFCTests/complex-asserts.fir
test/Dialect/FIRRTL/SFCTests/complex-assumes.fir

Builds on top of the pretty-printing code in #4192 .
Produces much more readable in many cases (IMHO) especially with complex expressions and statements containing non-trivial expressions.
Can see before/after differences here: https://dtzsifive.github.io/circt-pp-results/ (pages may change as things develop, output not final, etc.).  Also, [chipyard](https://gist.githubusercontent.com/dtzSiFive/edde310272aff78182b2e3235c2ba6fd/) which has things like `if` statements.
Not everything is possible, but there are a lot of decisions/stylistic choices (to be) made, if you're interested please take a look / give it a go and let me know what you think so we can iterate towards our preferred output.
Testing / feedback on specifics or in general is greatly appreciated!
Fixes #4181.
Fixes #4182. …

[ExportVerilog] Use pretty-printer for improved output formatting.

---

include/circt/Dialect/HW/HWPasses.h
include/circt/Dialect/HW/Passes.td
lib/Dialect/HW/Transforms/CMakeLists.txt
lib/Dialect/HW/Transforms/FlattenIO.cpp
test/Dialect/HW/flatten-io.mlir

My specific usecase for this is to be able to correctly lower ESI ports that are nested within a struct - may or may not end up using it, depending on how that work fleshes out. However, I assume this is generally useful (FIRRTL has an equivalent pass `--firrtl-lower-types`), hence the PR.
Not super happy about how legalization of the signature conversion is implemented (nested structs complicate things...), but I was unable to come up with a better approach than what is in this PR. See code comment for more info on the whats/whys of this.

[HW] Add pass for flattening structs in module in/out ports

---

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
test/Dialect/FIRRTL/emit-metadata.mlir

This annotation is only used in CreateSiFiveMetadata. After that pass consumes it, it can and should be dropped. Some downstream passes have to conservatively skip modules with annotations, so removing this annotation as soon as possible enables later transformations.

[FIRRTL] Remove ScalaClassAnnotation after consuming it.

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Dialect/FIRRTL/grand-central.mlir

This commit ensures that, if a companion module has two exactly same view annotations, then only one interface is generated.
This can occur when companions are deduped, and the corresponding View annotations are added as nonlocal after dedup.
If all the elements of the interface are exactly the same, then the companion must generate only one of the interfaces.
This commit still ensures that only a single instance of the companion exists. If multiple instances of the companion exist then GrandCentral will fail. This only handles the case when the parent module instantiating the companion is also deduped, thus ensuring only a single instance of the companion exists.

[GrandCentral] Ignore deduped Companion views

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/simplify-mems.mlir

Instead of introducing bundle types after `LowerTypes`, the individual fields of memory ports are optimised away. This improves the quality of emitted SystemVerilog and silences linter warnings.

[FIRRTL] Improve folding of ports

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp

Fixes a memory corruption bug in https://github.com/llvm/circt/commit/be883a20c8a954959ce84ec83f1bbbc2e3fdd383

[FIRRTL][GrandCentral] Fix mem corruption

---

lib/Dialect/FIRRTL/Import/FIRLexer.cpp
test/Dialect/FIRRTL/parse-errors.fir

The latter triggers an assertion failure and is not handled presently, the former may cause failures in CIRCT or later in pipeline.
The character `’` presently becomes "\342\200\231" (which seems like a correct encoding).
With assertions disabled, "\u2019" becomes  "\362019".

[FIRRTL] Reject string literals with non-7bit-ASCII or \{u,U}.

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/annotations.mlir

Remove the `NoDedup` annotation from DataTap sink modules.

[FIRRTL][GrandCentralTaps] Don't add NoDedup annotation to Tap sinks

---

include/circt/Dialect/SV/SVInOutOps.td
include/circt/Dialect/SV/SVVisitors.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/ExportVerilogInternals.h
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir
test/Dialect/SV/basic.mlir

Add a new hierarchical reference op that uses a symbol to refer to a
hw::GlobalRefOp that encodes the path to something in the circuit.  This
exists to complement the more restrictive XMROp which is a very direct
translation of a Verilog hierarchical reference that only uses strings.
The XMRRefOp may include an optional string that can be used to append some string to the resolved XMR.  This is a mechanism to got inside an external module boundary.
Add XMRRefOp emission to ExportVerilog.  Test that this works when
inlined into instances and bound instances.

[SV][ExportVerilog] Add XMRRefOp, Add ExportVerilog Emissions

---

lib/Dialect/Handshake/HandshakeOps.cpp

A couple of the Handshake ops had use-after-free bugs in their canonicalization patterns. We were calling `eraseOp()` on the root op within an `updateRootInPlace()` call. This is illegal because `updateRootInPlace()` must only update the root op in-place, not erase the op altogether.
These were fixed by moving the `eraseOp()` call after the `updateRootInPlace()` call.

[Handshake] Fix use-after-free bugs in canonicalization patterns.

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/InnerSymbolDCE.cpp
test/Dialect/FIRRTL/inner-symbol-dce.mlir
tools/firtool/firtool.cpp

Add a new pass, InnerSymbolDCE, that can be used to remove unused inner
symbols from FIRRTL Dialect.
This is the first patch in an incomplete series that will enable Grand Central views or taps to _not_ block constant propagation / dead wire removal.  This is the first piece in that.  Inner Symbol DCE is necessary because there needs to be a mechanism for a "soft" don't touch (private inner symbol) that can be referenced from an annotation.  Once the annotation is removed, then this pass can be used to DCE the symbols and enable removal of the operation.
This currently uses a non-standard attribute, `inner_sym_visibility`.  This will be added to the builder of ops that can have an inner symbol in the aforementioned incomplete …

[FIRRTL] Add Inner Symbol DCE Pass

---

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
test/Dialect/FIRRTL/imdce.mlir
test/firtool/firtool-errors.mlir

This PR changes IMDCE to generate warnings if empty modules are not erased for several reasons (symbol, annotation, module visibility ..)

[IMDCE] Generate warnings if empty modules are kept

---

test/circt-reduce/test/annotation-remover.mlir

The reducer will keep reducing as long as the interesting behaviour is present, using a test script that will tells us that a reduction was valid (ie behaviour is still present).
The  test script for annotation-remover will grep for an expected pattern, returning true (continue reducing) as long as the expected pattern is missing. Once the expected pattern is detected, the script returns false, indicating that the interesting behaviour is missing.  We want circt-reduce to dump the IR with the expected pattern, but we actually cause circt-reduce to discard that version of the IR and backtrack.
This is obviously not correct behaviour, but it was masked by the fact that the target pattern had a typo, so it was never detected. This allowed circt-reduce to continue until all reduction …

Fix error in reducer test for annotation-remover

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/canonicalization.mlir
test/Dialect/FIRRTL/test.mlir

Using flattened arrays for nested types in firrtl aggregate constants just makes everything harder.  Using nesting which matches types make IMCP and canonicalization easier.

[FIRRTL] Use nested array for aggregate constants

---

docs/Passes.md
include/circt/Dialect/SSP/CMakeLists.txt
include/circt/Dialect/SSP/SSPPasses.h
include/circt/Dialect/SSP/SSPPasses.td
include/circt/InitAllPasses.h
include/circt/Scheduling/Utilities.h
lib/Dialect/SSP/CMakeLists.txt
lib/Dialect/SSP/Transforms/CMakeLists.txt
lib/Dialect/SSP/Transforms/PassDetails.h
lib/Dialect/SSP/Transforms/PrintInstance.cpp
lib/Scheduling/Utilities.cpp
test/Dialect/SSP/Transforms/print-instance.mlir
tools/circt-opt/CMakeLists.txt

This PR adds a simple DOT printer pass (using the existing utility in the scheduling infra) in order to set up the pass boilerplate for the SSP dialect.

[SSP] Set up pass boilerplate.

---

include/circt/Dialect/SSP/SSPPasses.h
include/circt/Dialect/SSP/SSPPasses.td
lib/Dialect/SSP/Transforms/CMakeLists.txt
lib/Dialect/SSP/Transforms/Print.cpp
test/Dialect/SSP/Transforms/print.mlir

All passes on the SSP dialect will operate on instances, so drop that distinction from the printer pass' name.

[SSP] Rename DOT printer pass, NFC.

---

include/circt/Dialect/Calyx/CalyxLoweringUtils.h
lib/Conversion/PipelineToCalyx/PipelineToCalyx.cpp
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp

Leaving this as a draft since this is a WIP.
@mortbopet, I am encountering an issue with the bump where the SCFToCalyx converter will loop forever. I've done a bit of investigating, and I think I understand the problem, but I believe it's going to require a pretty substantial change to the SCFToCalyx converter's structure.
I git bisected the LLVM changes and identified https://github.com/llvm/llvm-project/commit/2fea658a74196a9c9128be34c5bc306eba7a025e as the commit that causes the SCFToCalyx converter to loop indefinitely. In that commit, the `GreedyPatternRewriter` was changed such that when `updateRootInPlace()` is called on an op, at the very end it will push that op back onto the worklist. The rationale is that the pattern rewriter will modify that root op, and as long as the pattern …

Bump llvm 2022-11-22

---

include/circt/Dialect/SSP/SSPPasses.h
include/circt/Dialect/SSP/SSPPasses.td
lib/Dialect/SSP/Transforms/CMakeLists.txt
lib/Dialect/SSP/Transforms/Roundtrip.cpp
lib/Scheduling/CMakeLists.txt
lib/Scheduling/TestPasses.cpp
test/Dialect/SSP/roundtrip.mlir
test/Dialect/SSP/standalone-lib.mlir

This PR adds the `-ssp-roundtrip` pass, which
- loads a problem instance from the SSP IR, 
- optionally checks and verifies the problem, 
- and saves it again as SSP IR.
`-ssp-roundtrip` and `-ssp-schedule` are quite similar at the moment. However, the schedule pass will pivot away from doing a complete roundtrip in the near future, so both passes are needed.
The new pass supersedes the one in the scheduling infra's test passes. In fact, this PR is the first step to remove the `CIRCTSchedulingTestPasses` library, as the scheduler tests will be done via the `-ssp-schedule` pass once the test case migration is complete.

[SSP] Add pass to roundtrip via the scheduling infra.

---

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
test/Dialect/FIRRTL/imconstprop-aggregate.mlir

https://github.com/llvm/circt/commit/fa2adf8109b3128cc8cb10e2b0f52a3f90502802 changed IMCP not to mark aggregate as overdefined in the initialization. That caused incorrect optimization so this PR marks aggregate as overdefined. 
Close #4369

[FIRRTL][IMCP] Mark aggregate as overdefined

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir.anno.json

Small fix for insertion point for ops inserted to index into extmodule port.  Insert after the instance not before.
Add test.

[GrandCentral] Fix insertion point for external module source

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR.mlir

This commit ensures that zero-width RefType values are ignored and symbols are not added for 0-width ports.
Without this commit, zero-width RefType values were being replaced with a constant, but it was still adding an unused symbol on zero-width ports.

[FIRRTL][LowerXMR] Ignore 0-width RefType values

---

lib/Scheduling/SimplexSchedulers.cpp
test/Scheduling/modulo-problems.mlir

If resource-constrained minimum feasible II is not calculated before solving the problem, one of two problems can occur:
1. II is incremented by 1 each step, and the scheduler assumes that this will work. This leads to the operation attempting to try to enter the MRT when it is not open.
2. An oversubscribed solution is incorrectly produced
I think calculating the resII before starting the algorithm avoids these pitfalls, at least in the test case I am providing.

[Scheduling] Calculate resII before solving ModuloProblem

---

lib/Dialect/FIRRTL/Transforms/MergeConnections.cpp
test/Dialect/FIRRTL/merge-connections.mlir
tools/firtool/firtool.cpp

This PR improves MergeConnections to use vectorcreate and bundle create op instead of bitcasting to aggregates.

[MergeConnections] Use vector/bundle create and enable aggressive merging by default

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
test/Dialect/FIRRTL/SFCTests/data-taps-xmr.fir

These are dummy ops acting as in-IR users so updates via RAUW maintain the real reference, their operand.
NodeOp is not suited for this use, as it requires
passive and base (non-ref) type operands.
Wiring problem solver now strips these when found
while connecting values.
Included test crashes without this change.
--
Issue occurs with multiple internalPath's taps that target the same instance, as each tap erases the instance causing stale source values (instance port) in the accumulated WiringProblem's.

[GCT][LowerAnnos] Use no-op cast to avoid erasing sources.

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/ExportVerilogInternals.h
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/prepare-for-emission.mlir

Before, PrepareForEmission would check the disallowMuxInlining option before checking isExpressionEmittedInline. In this case, we might choose to spill muxes into generated wires that are themselves trivially assigned to an output, wire, or reg.
Instead, this change sinks the disallowMuxInlining check into isExpressionEmittedInline, after we check if the expression is part of an output or assignment. This way, muxes are allowed to be inlined directly into an assignment we are going to generate anyway, avoiding unnecessary generated wires. Muxes will still be spilled to wires otherwise, when requested.

[ExportVerilog] Sink mux inlining check to isExpressionEmittedInline.

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/Comb/canonicalization.mlir

This PR implements a canonicalizer to merge array operations in concat operands. 
In chisel, it's quite common to concatenate vector elements to form integer. With aggregate preservation, 
they are bit-compatible in HW/SV level. For example, 
```scala
circuit Foo:
module Foo:
input a: UInt<1>[3]
output b: UInt<3>
b <= cat(a[2],cat(a[1], a[0]))
```
is transformed into
```
assign b = a;
```
with aggregate preservation. Previously this was `assign b = {a[2'h2], a[2'h1], a[2'h0]};`

[CombFolds] Handle array operations in flattenConcat

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Previous code did not match its comment which is how it was noticed. Upon inspection it also did nothing since comparisons always return i0. (test introduced with it passes without the code change,
commit: 1a742d10abd0690fb64df89897535c2ff3142bf6)
Zero-width operands will be treated as "constant" zero later in this function, so zero-width+zero-width and zero-width+constant fold presently.
Replace the check with a new one that folds any binary op with zero-width result into zero.
There are folds involving one operand being zero-width that are missing, future work.

[FIRRTL] Fold binary ops returning zero-width, replace impossible check.

---

lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp
test/Dialect/FIRRTL/SFCTests/subcircuit-flow/flow.test
test/Dialect/FIRRTL/SFCTests/subcircuit-flow/subCircuit.json
test/Dialect/FIRRTL/SFCTests/subcircuit-flow/subcircuit.fir

Buffer wires are inserted when ports are forced via signal driving,
and inner symbols were used to ensure they were preserved.
However now that we have InnerSymDCE (#3120), that is insufficient
and the wires were being removed, causing issues due to the forced ports
also driving anything directly bound to the instance ports.
Extend the subcircuit flow test to check for these wires to ensure
they are preserved all the way to verilog.
Buffer wires (second wire anyway) for input ports were added in #3153, output ports in #3431.

[GCSM] Fix buffer wire preservation, add test.

---

include/circt-c/Dialect/FIRRTL.h
lib/CAPI/Dialect/CMakeLists.txt
lib/CAPI/Dialect/FIRRTL.cpp

This add FIRRTL to CAPI. It is used for JVM Binding which can be used via JNA/JNI/[Panama](https://openjdk.org/projects/panama/)

Register FIRRTL to CAPI

---

unittests/CMakeLists.txt

These warnings are verbose and we can't fix them, so don't generate warnings about them.

unittests: Squelch -Wsuggest-override errors in LLVM's gtest.

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/pretty.mlir

Tighten up output a bit.
(and don't indent the contents)

[ExportVerilog] Tweak braced list formatting, less whitespace.

---

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
test/Dialect/FIRRTL/imdce.mlir

Previously when an instance result was marked as alive, the liveness was propagate to its module port. This is unnecessary when the port is input port. 
For the example below, it was unable to remove module `Bar` because instance result `Bar.a` is marked as alive.  
```
circuit Foo :
module Bar: 
module Foo :
input a : UInt<1>
output b : UInt<2>
inst bar of Bar
bar.a <= a
b <= bar.a
```
w/ PR:
```verilog
module Foo(
input  a,
output b);
assign b = a;
endmodule
```
w/o PR:
```verilog
module Bar(
input a);
endmodule
module Foo(
input  a,
output b);
Bar bar (
.a (a)
);
assign b = a;
endmodule
```

[IMDCE] Improve liveness propagation of input ports

---

include/circt/Support/PrettyPrinter.h
test/Conversion/ExportVerilog/pretty.mlir
unittests/Support/PrettyPrinterTest.cpp

Allows lines to have their base indent start past the margin limit, while still targeting that for breaks.
Produces nicer outputs for giant expressions, such as very large mux chains.
Not tied to any user-facing option, but can be set when constructing PrettyPrinter instances.
Current default value is 8191.
Add test for mux chain, demonstrating and checking that base indent can start past margin.
Previously the indent would cap at margin.

[PrettyPrinter] Enable maxStartingIndent feature, default to high value. 

---

lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
test/Dialect/FIRRTL/emit-omir.mlir

This adds support for OMIR that targets fields. Tracker is updated to hold a fieldID, which behaves like it does in Annotations: defaults to 0 to mean the whole entity, and greater than zero to index into a field of the entity. When constructing output OMIR, if the tracker has a fieldID, the type of the entity being targeted is used to append the appropritate output field. For vectors, this is an index, and for bundles, this is a named field. If we don't know how to easily extract the type of a targeted entity, an error is raised. The common cases of Wires, Registers, Nodes, and Ports are supported.

[EmitOMIR] Support fieldID for OMIR targetting fields.

---

include/circt/Conversion/StandardToHandshake.h
include/circt/Dialect/Handshake/HandshakeCanonicalization.td
include/circt/Dialect/Handshake/HandshakeInterfaces.td
include/circt/Dialect/Handshake/HandshakeOps.h
include/circt/Dialect/Handshake/HandshakeOps.td
include/circt/Dialect/Handshake/HandshakePasses.h
lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
lib/Dialect/Handshake/HandshakeOps.cpp
lib/Dialect/Handshake/Transforms/Analysis.cpp
lib/Dialect/Handshake/Transforms/Buffers.cpp
lib/Dialect/Handshake/Transforms/LockFunctions.cpp
lib/Dialect/Handshake/Transforms/LowerExtmemToHW.cpp
lib/Dialect/Handshake/Transforms/Materialization.cpp
test/Dialect/Handshake/errors.mlir

This commit overhauls Handshake operations by
- removing the majority of custom builders
- re-enabling default operation builders in most cases,
- deleting redundant operation operands,
- deleting the `sost` namespace, whose functionality is moved to an interface (`SOSTInterface`) instead,
- and refactoring the way `ControlInterface` determines whether an operation is a control operation, without relying on a redundant operation attribute. 
In addition, the commit adds verification logic as well as return type inference logic for a number of Handshake operations, improving reliability and reducing redundancy.
The commit also refactors the merge insertion step in `StandardToHandshake` to use backedges instead of initially invalid merge-like operations. Operation builders that were used …

[Handshake] Cleanup Handshake operations builders

---

tools/hlstool/hlstool.cpp

The `InitAllPasses.h` header file includes all the generated pass header files, e.g. `"circt/Dialect/SystemC/Passes.h.inc"`.  To make sure this header file is generated properly before we try to include it, we have to depend on the associated transform library.  Since hlstool does not depend on every single transform library, this causes the build to occasionally fail.  To fix this, we need to only include header files belonging to the dialects we are actually depending on.
This error can be seen in the following build:
https://github.com/llvm/circt/actions/runs/3657570236/jobs/6181309548

[hlstool] Remove header to fix flaky build

---

lib/Dialect/FIRRTL/Import/FIRParserAsserts.cpp
test/Dialect/FIRRTL/parse-basic.fir

Similar to current `assert` and `assume` parsing; parse `printf`s for magic strings to emit `cover` statements.

[FIRRTL] Support for cover statements

---

CMakeLists.txt

PR #4409 disabled this for our unittests themselves, but these warnings are still emitted when building llvm_gtest_main in the non-unified build scenario where we have our own build rule.
Would be nice to remove all this.

[NFC] Disable -Wno-suggest-override for llvm_gtest_main as well.

---

frontends/PyCDE/src/pycde/constructs.py
frontends/PyCDE/src/pycde/value.py
frontends/PyCDE/test/test_constructs.py

- Wires with names no longer automatically construct NamedWires.
- Respect the given name in backedges and after assignment.
- Assign to slices and indexes.

[PyCDE] Wire construct improvements

---

include/circt/Dialect/Calyx/CalyxStructure.td
include/circt/Dialect/FSM/FSMOps.td
include/circt/Dialect/HW/HWStructure.td
include/circt/Dialect/Handshake/HandshakeOps.td
include/circt/Dialect/LLHD/IR/StructureOps.td
include/circt/Dialect/MSFT/MSFTOps.td
include/circt/Dialect/SystemC/SystemCStructure.td
lib/Conversion/ExportVerilog/CMakeLists.txt
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/HWToLLHD/HWToLLHD.cpp
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
lib/Dialect/Calyx/CalyxOps.cpp
lib/Dialect/FSM/FSMOps.cpp
lib/Dialect/HW/HWOps.cpp
lib/Dialect/Handshake/HandshakeOps.cpp
lib/Dialect/LLHD/IR/LLHDOps.cpp
lib/Dialect/LLHD/Transforms/ProcessLoweringPass.cpp
lib/Dialect/MSFT/MSFTOps.cpp
lib/Dialect/SystemC/SystemCOps.cpp

This picks up some major changes to FunctionOpInterface from https://github.com/llvm/llvm-project/commit/53406427cdf4290986d1a48ea0d582ad195bff15.
This generally follows the upstream changes approach to the same:
* Ensure all FunctionOpInterface ops declare function_type, arg_attrs, and res_attrs in ODS.
* Use the ODS-generated methods to get the names of the above attributes, since they were removed from mlir::function_interface_impl.
* Incorporate some minor changes to mlir::function_interface_impl.

Bump LLVM to 53406427cdf4290986d1a48ea0d582ad195bff15.

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
include/circt/Dialect/FIRRTL/FIRRTLStructure.td
include/circt/Dialect/FSM/FSMOps.td
include/circt/Dialect/HW/HWOpInterfaces.td
include/circt/Dialect/HW/HWStructure.td
include/circt/Dialect/MSFT/MSFTOps.td
include/circt/Dialect/SystemC/SystemCStructure.td
lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp
lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/InnerSymbolTable.cpp
lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp

Move the getNumPorts function from the FModuleLike op interface to the HWModuleLike op interface.
This is one of a series of commits working towards https://github.com/llvm/circt/pull/4384.

[FIRRTL][HW] Move getNumPorts to HWModuleLike

---

include/circt/Dialect/HW/HWTypes.td
include/circt/Dialect/SV/SVInOutOps.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir
test/Dialect/SV/basic.mlir

Change the XMRRefOp to use a HierPathOp instead of a GlobalRefOp.  This is done as the latter is intended to replace the former (and has a lot of benefits like not having to use "breadcrumbs" everywhere).
Depends on:
- https://github.com/llvm/circt/pull/4394
- https://github.com/llvm/circt/pull/4384
- https://github.com/llvm/circt/pull/4413
- https://github.com/llvm/circt/pull/4417

[HW][ExportVerilog] Use HierPathOp in XMRRefOp

---

include/circt/Dialect/FIRRTL/FIRRTLUtils.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR.mlir

Change the LowerXMR pass to emit XMRRefOps instead of VerbatimExprOps. This is done to enable later inlining of these operations into their usage sites, e.g., directly into a bind.
As this has to bridge between FIRRTL and SV, this uses an unrealized conversion cast to enable usage of an InOut type from FIRRTL.  This is already correctly handled by LowerToHW.
This depends on:
- https://github.com/llvm/circt/pull/4394
- https://github.com/llvm/circt/pull/4384
- https://github.com/llvm/circt/pull/4413
- https://github.com/llvm/circt/pull/4417
- https://github.com/llvm/circt/pull/4421
This PR needs more work, but this is a demo of this working. 
Input with ref types:
```mlir
firrtl.circuit "Foo" {
firrtl.module @Bar(out …
```

[FIRRTL] Change LowerXMR to create XMRRefOps

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-errors.fir

Fixes #3799.
Zero-width constants have already been supported in the IR
since aa1c294e99db3c673b9c0d6e0f49e2869f042f14 .
Error language is preserved with "zero bit", closer to spec text.

[FIRRTL] Support zero-width literals.

---

lib/Dialect/FIRRTL/Transforms/WireDFT.cpp
test/Dialect/FIRRTL/wire-dft-errors.mlir

Avoid generating invalid or corrupt IR based on assumptions about the structure of the clock gate modules,
and instead check for required structure.
Port name is not checked presently to avoid rejecting circuits that would previously work.
Fixes #4447.
Fixes #4448.

[WireDFT] harden a bit, check clock gate modules.

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/annotations.mlir

This fixes a bug in the `GrandCentral` `DataTaps`, which was ignoring the `fieldIdx` of a `wireTarget`, while constructing the source internal path. This resulted in a `ref.send` of an aggregate type, and `firtool` crashed with a mismatch in types after `lower-annotations`. 
The internal path is just a verbatim string, and the type of the `ref.source` is the same as the sink type, which must consider the subfield correctly.

[FIRRTL][GrandCentralTaps] Handle sink subfield for internal path

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td

Don't "extend" if types are the same, pad inserted is spurious and will be dropped immediately anyway.
Let ConnectSameType handle these, no need to cleanup the pad.
This pattern (ConnectExtension) runs first, and reordering these avoids the pad but tightening the pattern seems better.

[FIRRTL] Don't insert same-width pad for connect -> strictconnect.

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/imconstprop-crashers.mlir

Fixes #4456.
Fix is good AFAIK, but test is incomplete-- does not fail (by folding) before this change which should be addressed before landing this.
Fixes reproducer in linked issue (and test2.fir/test3.fir).

[FIRRTL] Fix folding cat(SInt<0>,x), return needs to be unsigned.

---

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/HWRename.fir
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir
test/Dialect/FIRRTL/SFCTests/data-taps-more-xmrs.fir
test/Dialect/FIRRTL/SFCTests/data-taps-xmr.fir
test/Dialect/FIRRTL/annotations.mlir

Change WiringProblem solving to bore _real_ ports (non-RefType ports)
when creating input ports.  With this commit, WiringProblems will be
solved by boring output RefType ports from source to LCA and real input
ports to the sink.  This is done because "upwards" XMRs may have tricky
semantics in that they should necessarily block deduplication (as any
upwards reference may cause a single ref.resolve to refer to more than
one thing).
CC: @dtzSiFive
Note: the second commit is entirely test churn. This was a surprisingly trivial change to `WiringProblem`s. This works because the `connect` lambda inside `LowerAnnotations::solveWiringProblem` will create `RefResolveOp`/`RefSendOp` when it sees incompatible types.

[FIRRTL] Bore real input ports in WiringProblems

---

include/circt/Dialect/FSM/FSMOps.td
include/circt/Dialect/HW/HWStructure.td
include/circt/Dialect/Interop/Interop.td
include/circt/Dialect/SystemC/SystemCStructure.td
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
lib/Dialect/MSFT/DeviceDB.cpp
lib/Dialect/Moore/MooreTypes.cpp
tools/circt-reduce/Tester.cpp

This is NFC. The only change is related to the transition from llvm::None to std::nullopt, so I cleaned up the warnings that I saw.
This LLVM commit includes a few additions to the MLIR Python API that will be good to build on top of.

Bump LLVM to afb2ed80cb1639236a3aa15f2c9ff96dbb45c3d0.

---

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp

Just found some typos while reading this project.
- neet -> need
- compliment -> complement
More of the same typo corrections in the submodule LLVM have been submitted to the upstream repository. https://reviews.llvm.org/D138668

Correct typos in `ExpandWhens.cpp`

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR.mlir

Preparation for cleaning up hierpath ops in HW, now that they're not all removed during lowering.
These particular hierpath's are unlikely to end up dead, but let's not keep symbols alive unnecessarily.

[LowerXMR] Emit hierpathop's as private, so they can be removed if unused

---

lib/Scheduling/SimplexSchedulers.cpp
test/Scheduling/modulo-problems.mlir

This PR fixes #4375 and improves the quality of solutions found by the `ModuloSimplexScheduler`.
- e779cc5f162aed257303a719c8e35103c79eb0b6 was just a simple bug that caused wrong solutions with oversubscribed operator types to be returned.
- f09ae330c485afe9562b0b16f169f79e39516dcc is the main fix. This modulo scheduler works by iteratively fixing resource-limited operations to specific time steps, which are baked into the simplex tableau. In the paper, this done as a modulo decomposition, making the value dependent on the II-parameter. I believe the intention was to automatically shift ops to keep them in the same MRT slot whenever the II changes, but I didn't get that to work properly in all cases. Instead, I now just fix operations to absolute time steps (same as for the non-cyclic …

[Scheduling] Overhaul simplex-based modulo scheduler.

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

This caused a failure on an internal core so revert it for now.

Revert "[LowerToHW] Lower aggregate constant"

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

Fix a bug where attributes which may have been added to an InstanceOp before LowerTypes would not be preserved on the InstanceOp after LowerTypes.  Concretely, this fixes an issue wehre a "hw.output_file" was placed on an instance and LowerTypes then drops it.

[FIRRTL] Fix InstanceOp Unknown Attribute Copying

---

.github/workflows/uploadBinaries.yml

clang-11 on Ubuntu currently produces a very broken LLVM.
(see LLVM issue 59622)

[CI] uploadBinaries.yml: Temporarily change 20.04 compiler to 12.

---

.github/workflows/uploadBinaries.yml

Enable the binary workflow to be run manually, but only upload binaries if it's a tag.  I am not sure what happens if they're already present, so probably best to use this wisely.
While visiting, run the basic lit tests for LLVM/MLIR before bundling them for others (and sometimes ourselves) to use.
Partly to avoid increased pressure on the cache from binaries/components built to run the tests that we don't presently, but also because I'm not sure the cached LLVM will likely ever be a cache hit since we release and update LLVM at about the same frequency.  Maybe if we did do more frequent releases, or ever promoted a pre-release to a an actual one, that would be useful?
cc #4473.

[CI] uploadBinaries: allow workflow_dispatch, test what we publish, drop cache

---

include/circt/Dialect/ESI/ESIPasses.h
include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/LLHD/IR/SignalOps.td
include/circt/Support/PrettyPrinter.h
tools/circt-reduce/Tester.h
tools/handshake-runner/Simulation.cpp

Add some headers and scope some variables.
Drop a use of `.value()` was done for llvm::Optional when it was deprecated, but also remove an instance hidden in tablegen on `std::optional` following upstream changes doing similar due to availability and exception semantics.
For example, see: https://github.com/llvm/llvm-project/commit/30199d11d27460e8c96a81c493526c32dbea428d .
Commits are normally the sort to just be pushed and touch different parts of the code, so I plan to merge via "rebase/merge", once CI confirms all is well.

[NFC] small touchups before LLVM bump

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

This adds extra guards for headers to avoid redefinition of macros. For example, 
```
`ifdef PRINTF_COND
`define PRINTF_COND_ (`PRINTF_COND)
`else  // PRINTF_COND
`define PRINTF_COND_ 1
`endif // PRINTF_COND 
```
is modified to be emitted with additional ifndef guard:
```
`ifdef PRINTF_COND_
`ifdef PRINTF_COND
`define PRINTF_COND_ (`PRINTF_COND)
`else  // PRINTF_COND
`define PRINTF_COND_ 1
`endif // PRINTF_COND 
`endif
```

[LowerToHW] Add extra guards to header macros

---

include/circt/Conversion/StandardToHandshake.h
include/circt/Dialect/Handshake/HandshakeOps.h
include/circt/Dialect/Handshake/HandshakeOps.td
include/circt/Dialect/Handshake/Visitor.h
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
lib/Dialect/Handshake/HandshakeExecutableOps.cpp
lib/Dialect/Handshake/HandshakeOps.cpp
test/Conversion/StandardToHandshake/arith-ops.mlir
test/Conversion/StandardToHandshake/call.mlir
test/Conversion/StandardToHandshake/disable-task-pipelining.mlir
test/Conversion/StandardToHandshake/external-memory.mlir
test/Conversion/StandardToHandshake/func.mlir
test/Conversion/StandardToHandshake/memref.mlir
test/Conversion/StandardToHandshake/source-constants.mlir
test/Conversion/StandardToHandshake/task-pipelining.mlir

This commit removes the `StartOp`, `EndOp`, and `TerminatorOp` from the entire codebase, since they were used exclusively as intermediate operations during `std-to-handshake` conversion and have caused issues in the past. `StartOp`'s purpose is achieved through a new field (`startCtrl`) in the `HandshakeLowering` class, while `TerminatorOp` and `EndOp`'s purpose is obtained by keeping `cf`-level terminators in the IR for longer than before.
Unit tests on the conversion pass are modified manually (as to yield a smaller diff, since rerunning `FileCheck` would change SSA value names and modify almost all lines) to reflect the fact that an additional `MergeOp` is created by the pass for the control-only network in the entry block of each function (this has no impact on circuit behavior, and …

[StandardToHandshake] Remove intermediate conversion ops

---

lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Dialect/Seq/firreg.mlir

This commit changes initialization of array/struct registers. Previously an aggregate register was initialized with a single concat op with bitcast. Verilator creates a large number of local variables in verilated code, which caused stack-overflow while simulation execution.
For example, 
```
circuit Foo:
module Foo:
input a: UInt<32>[2]
output b: UInt<32>[2]
reg r : UInt<32>[2], clock
r <= a
b <= r
```
`$ firtool tmp.fir -preserve-aggregate=1d-vec -preserve-public-types=false`
before:
```verilog
_RANDOM_0 = `RANDOM;
_RANDOM_1 = `RANDOM;
r = /*cast(bit[1:0][31:0])*/{_RANDOM_0, _RANDOM_1};
```
after:
```verilog
_RANDOM_0 = `RANDOM;
_RANDOM_1 = `RANDOM;
r[1'h0] = _RANDOM_0;
r[1'h1] = _RANDOM_1;
```

[LowerSeqToSV] Initialize register element individually

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

Previously `isExpressionEmittedInline` could return false for dead expressions which caused assertion failures in ExportVerilog. Dead expressions will not be emitted anyway so it makes sense to regard them as valid syntax.

[ExportVerilog] Regard dead expressions as inlinable

---

include/circt/Dialect/SV/SVExpressions.td
test/Dialect/SV/canonicalization.mlir

SampledOp has read-only semantics and therefore it has to have Pure trait to align with ReadInoutOp.

[SV] Mark SampledOp Pure

---

docs/Dialects/Seq/RationaleSeq.md
include/circt/Dialect/Seq/SeqOps.td
lib/Dialect/Seq/SeqOps.cpp
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Dialect/Seq/compreg-errors.mlir
test/Dialect/Seq/compreg.mlir

Introduces `compreg.ce` which is identical to the existing `compreg` but includes a `clockEnable` signal to enable/disable reading the input. This op makes it easier to create SV with the behavioral syntax rather than the structural mux that we currently construct. Could be lowered into the structural mux if that is desired.

[Seq] Create new clock enabled register op

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/prepare-for-emission.mlir

PrepareForEmission has to handle `twoState` flags while variadic op lowering. This PR clones `twoState` flags to decomposed operations. Fix https://github.com/llvm/circt/issues/4489

[PrepareForEmission] Handle twoState flags in variadic op lowerings

---

include/circt/Conversion/FIRRTLToHW.h
include/circt/Conversion/Passes.td
include/circt/Dialect/SV/SVPasses.h
include/circt/Dialect/SV/SVPasses.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/SV/hw-memsim.mlir
test/firtool/chirrtl.fir
test/firtool/firtool.fir
test/firtool/memory.fir
tools/firtool/firtool.cpp

This PR deprecates `strip-mux-pragmas` flag and add `add-mux-pragmas` flag. Mux pragmas will not be emitted by default. `strip-mux-pragmas` is not deleted for now so that we can deploy a new version of firtool more smoothly.

[firtool] Strip mux pragmas by default, NFC

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/Comb/canonicalization.mlir

This PR backports two mux canonicalizations (#4403 and #4405) implemented in SiFive 1.24 into SiFive 1.22 branch.

Backport mux canonicalizations into SiFive 1.22

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/Comb/canonicalization.mlir

On the second thought, the canonicalizers are too strong as a backport at this time.
Reverts llvm/circt#4492

Revert "Backport mux canonicalizations into SiFive 1.22"

---

lib/Dialect/FIRRTL/FIRRTLUtils.cpp

Use `FNamableOp` to handle `NodeOp` and get their name in `getDeclName`.

[FIRRTL] Handle Nodes in getDeclName. NFC.

---

lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/SFCTests/mem-taps.fir

HWMemSimImpl creates unpacked array registers for memory storage. However with aggregate preservation mode, FIRRTL vector is lowered into packed arrays so there is a type mismatch. This PR adds a workaround to force type lowering of reftype operations. 
w/o PR:
```verilog
reg  [7:0] Memory[0:7];
...
wire [7:0][7:0] memTap;
assign memTap = Top.dut.rf_ext.Memory;
```
w/ PR:
```verilog
wire [7:0][7:0] memTap;
assign memTap =
{{Top.dut.rf_ext.Memory[7]},
{Top.dut.rf_ext.Memory[6]},
{Top.dut.rf_ext.Memory[5]},
{Top.dut.rf_ext.Memory[4]},
{Top.dut.rf_ext.Memory[3]},
{Top.dut.rf_ext.Memory[2]},
{Top.dut.rf_ext.Memory[1]},
{Top.dut.rf_ext.Memory[0]}};
```

[LowerTypes] Force type lowering of ref type operations to fix memtap type mismatch

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

Bitcast is generally not allowed to be inlined but we can inline
if its user is (array)concat since they don't require type information.

[ExportVerilog] Inline bitcast op when only used by concat

---

lib/Dialect/Seq/SeqOps.cpp
test/Dialect/Seq/canonicalization.mlir

For reset-less 1d array registers, replace an unitialized elemenent with constant zero. For example, let `r` be a 2xi1 register and its next value be `{foo, r[0]}`. `r[0]` is connected to itself so will never be initialized. If we don't enable aggregate preservation, `r_0` is relpaced with `0`. Hence this canonicalization replaces 0th element of the next value with zero to match the behaivor.

[Seq] Replace unitialized array elements of firreg with constant zero

---

.github/workflows/uploadBinaries.yml

Statistics are useful, e.g. for metrics.
Insignificant impact on binary size (locally: +200K for a 11M binary) and negligible performance impact.

[CI] Enable statistics when building binaries for releases.

---

lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp
test/Dialect/FIRRTL/check-comb-cycles.mlir

Refactor the implementation to avoid redundant traversal of the IR. 
This records the output ports that are reachable from any Value, to enable
discovery of existing paths between ports of a module.
Runtime of the old `CheckCombCycles` pass for an internal design(p650mc) = 106  sec
Runtime of the new pass = 30 sec

[FIRRTL][CheckCombLoops] Fix performance regression.

---

tools/firtool/firtool.cpp

Switch to the new CheckCombLoops pass, and move it after ExpandWhens.

[FIRRTL][CheckCombLoops] Switch to the new pass checkCombLoops instead of checkCombCycles

---

lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp
test/Dialect/FIRRTL/check-comb-cycles.mlir

Fix a bug in `CheckCombLoops` pass, it was not handling paths between ground type and aggregates.

[FIRRTL][CheckCombLoops] Handle scalar to Aggregate paths

---

frontends/PyCDE/integration_test/esi_test.py
frontends/PyCDE/src/pycde/constructs.py
frontends/PyCDE/src/pycde/pycde_types.py
frontends/PyCDE/src/pycde/support.py
frontends/PyCDE/src/pycde/value.py
frontends/PyCDE/test/errors.py
frontends/PyCDE/test/test_hwarith.py
lib/Bindings/Python/circt/dialects/_hwarith_ops_ext.py

Introduce separate class hierarchies for signless integers (which PyCDE calls 'Bits') and signed/unsigned ints since they are fundamentally different things. Certain operations only make sense on bits and certain others only make sense on ints. Also, there are two different dialects for each (comb vs hwarith) so this change reduces edge cases.

[PyCDE] Separate BitVectors into Integers vs. Bits

---

test/firtool/include-dirs-annotations.fir
test/firtool/include-dirs.fir
tools/firtool/firtool.cpp

Support specifying one or more include directories that are searched to find files:
* When printing diagnostics, allowing for nicer caret messages
* When opening files via SourceManager as "includes", which means this option can be used for annotation files (+OMIR).
Add basic tests for both.

[firtool] Add include directory flag

---

lib/Dialect/FIRRTL/Import/FIRLexer.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/firtool/annotation-error.fir

The inline annotation location is invalid if none are specified, and since the error isn't in inline annotations just point to circuit.
Would be nice to point into the file itself, or mention it, but that will require reworking how these files are loaded/passed around.
For now, let's not crash.
This is the same as we do for OMIR annotation files and their error reporting.
Fixes #4538.

[FIRRTL] Use circuit location for annotation file parse errors.

---

include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
lib/Dialect/FIRRTL/FIRRTLTypes.cpp

Use a flag genStorageClass to let us continue to use a custom storage class.

[FIRRTL] Move FVectorType to ODS

---

frontends/PyCDE/src/behavioral.py
frontends/PyCDE/src/constructs.py
frontends/PyCDE/src/esi.py
frontends/PyCDE/src/module.py
frontends/PyCDE/src/ndarray.py
frontends/PyCDE/src/pycde_types.py
frontends/PyCDE/src/support.py
frontends/PyCDE/src/value.py
frontends/PyCDE/test/esi.py

Renaming the very generic `Value` class name to `Signal`. It's a bit of a stretch for things like `InOutSignal` and `ChannelSignal`, but I think it's better for consistency's sake to use the same suffix for all `Value`s.

[PyCDE] Value -> Signal

---

lib/Dialect/FIRRTL/Transforms/AddSeqMemPorts.cpp
test/Dialect/FIRRTL/add-seqmem-ports.mlir

Change the AddSeqMemPorts pass to mark ports created on the DUT (or the
top module) with DontTouchAnnotations.  This is done to avoid having
these ports be deleted.  This is currently a problem for output ports
that the pass creates and bores upwards.  The final instance port of the
DUT does not have a user which causes all the ports (except the one on
the memory) to be deletion candidates.
An end-to-end example showing the problem is the following circuit:
```firrtl
circuit TestHarness : %[[
{
"class":"sifive.enterprise.firrtl.MarkDUTAnnotation",
"target":"TestHarness.DUTModule"
},
{
"class":"sifive.enterprise.firrtl.AddSeqMemPortsFileAnnotation",
"filename":"SeqMems.txt"
},
{ …
```

[FIRRTL] Mark DUT AddSeqMemPorts ports dontTouch

---

include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp

Convert all fieldID-related functions which are not already in the FieldIDTypeInterface to use uint64_t for its type.  Previously, this was a mix of unsigned for bundles and size_t for vectors (due to reasons that vectors can sometimes be representing very large memories with more than 2^32 elements whereas this is rare for bundles).

[FIRRTL] Change FIRRTL fieldID fns to use uint64_t

---

lib/Dialect/LLHD/CMakeLists.txt

Ref: https://github.com/llvm/circt/pull/4547#issuecomment-1387495752
@maerhart Would you mind reviewing this PR?

[CMake] Fix option `CIRCT_LLHD_SIM_ENABLED`

---

include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
lib/Dialect/FIRRTL/FIRRTLTypes.cpp

- Make WidthQualifiedTrait a type trait, renaming it to WidthQualifiedTypeTrait.
- Rather than have users implement getWidth(), have users implement getWidthOrSentinel().
- enshrine the idea that `widthOrSentinel : int32_t` is the most primitive format for widths of types.
- this means that if a type has an attribute called widthOrSentinel, then it can use this trait for free
- Remove WidthQualifiedType and WidthTypeStorage
- In AnalogType, rename the widthBase attribute to widthOrSentinel
- Make IntType use WidthQualifiedTypeTrait
- changeWidth(int32_t width) had to be removed from WidthQualifiedTypeTrait to support this
- Verify the widthOrSentinel value in a type verifier, rather than in the builder
- Add a verifier for AnalogType
- Let FIRRTLImplType take a baseCppClass parameter
- …

[FIRRTL] Move SIntType and UIntType to ODS

---

test/firtool/include-dirs.fir
tools/firtool/firtool.cpp

Support long-form version of option for readability.
Include usage in description to workaround `cl::value_desc` not seeming to work for the alias.

[firtool] Add --include-dir option, -I as alias.

---

.github/workflows/nightlyIntegrationTests.yml
.github/workflows/shortIntegrationTests.yml

Bump to v11.3 = v11.2 + OR-Tools v9.5 (https://github.com/circt/images/pull/26)

[CI] Bump integration test images.

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir
test/Conversion/ExportVerilog/verilog-basic.mlir

Previously expressions feed into bound instances are anchored by wires so that we can remotely get names of wires while bindfile emission.  Since https://github.com/llvm/circt/pull/4573 changes name legalizations and we can get local names by inspecting IR, we can get valid emission by justing using `emitExpression`.

[ExportVerilog] Inline expressions into bound instances

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp

This PR fixes a race condition in LowerTypes with aggregate preservation mode. In the instance op lowering, linkage of referenced module is checked, however it is not allowed to read attributes from different threads.

[LowerTypes] Fix a race condition

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

This backports #4469 to sifive 1.22 branch.

Backport "[LowerToHW] Add extra guards to header macros (#4469)" to sifive 1.22

---

lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp
test/Dialect/FIRRTL/extract-instances.mlir

Change the ExtractInstances pass to always create an ExtractSeqMems file if the appropriate annotation is passed in.  This is done to align with the SFC implementation of this pass (and to pass an internal unit test).
This uses the same strategy as for CreateSiFiveMetadata where a dummy verbatim is always created.  This simplifies later logic.  This could be improved in the future to only generate the dummy verbatim when necessary (which would remove a now mandatory 1-newline offset that is added to every ExtractSeqMems file created.

[FIRRTL] Always create ExtractSeqMems extract file

---

test/Dialect/SystemC/func-invalid.mlir

This is required for the upstream change: ("Make FunctionOpInterface inherit SymbolOpInterface" https://reviews.llvm.org/D140199)
The visibility is now inherited from FunctionOpInterface .
Fixes the failure in https://github.com/llvm/circt/pull/4563

[SystemC] Make func private in lit test. NFC

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/InstantiateCompanionOnly.fir
test/Dialect/FIRRTL/SFCTests/data-taps-no-ref-type.fir
tools/firtool/firtool.cpp

This includes two hack options to help make Grand Central collateral (Views and Taps) more synthesizable. The options to `firtool` are:
1. `-grand-central-instantiate-companion`
2. `-lower-annotations-no-ref-type-ports`
(1) will change the Grand Central pass to never instantiate the companion module under a bind. (Previously this would only happen if the user didn't request extraction via an annotation.) Additionally, this will _not print any SystemVerilog interface_. From the perspective of a synthesis tool, the interface is a dead wire and should be dropped. This avoids problems where a tool may not accept interfaces.
(2) changes how the `LowerAnnotations` pass resolves wiring problems to always create real ports. Previously, this would create real ports along the LCA to sink path, but …

[firtool][FIRRTL] Make Grand Central Collateral Synthesizable

---

include/circt/Dialect/Calyx/CalyxPasses.h
include/circt/Dialect/Calyx/CalyxPasses.td
lib/Dialect/Calyx/Transforms/CMakeLists.txt
lib/Dialect/Calyx/Transforms/RemoveCombGroups.cpp
test/Dialect/Calyx/remove-comb-groups.mlir

Committing an old piece of code I had lying around. The pass is modeled after the native calyx compiler implementation.
... as far as i know, this is the only missing piece to actually do Calyx-to-HW in CIRCT, through the FSM flow...

[Calyx] Add 'remove comb groups' pass

---

integration_test/Dialect/Calyx/loop.mlir
lib/Conversion/CalyxToFSM/CalyxToFSM.cpp

+fix a stray printout.
The intention with this test is to
1. have a place to point people towards to show how and in which order to use the different calyx passes.
2. Show where work needs to be placed next - specifically, this highlights that #3601 is up next.
Depends on https://github.com/llvm/circt/pull/4522

[Calyx] Add SCF -> Calyx -> FSM integration test

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

This fixes a bug in `isExpressionEmittedInline` introduced by 1c38d707a3cc4e84631f7218a4a62e450143f0d8. 1c38d707a3cc4e84631f7218a4a62e450143f0d8 allowed single-use expressions to be inlined into instance ports, but some expressions are forbidden to be inlined into input ports. We have to check validity with `isExpressionUnableToInline`.

[ExportVerilog] Don't regard input ports as assignment patterns

---

.gitignore

I believe "TAGS" is the default output for `etags`

Add TAGS to gitignore

---

lib/Conversion/HWToLLVM/HWToLLVM.cpp
test/Conversion/HWToLLVM/convert_aggregates.mlir

The originally related commits were pushed with zvc framework (**PR#4040** closed), and now split out and push separately.
convert struct_explode op to llvm extractvalue op, to eject every element in the struct.
pattern: struct_extract(input) => struct_extract(input, structElements_index(index))
Fix: move the original single struct_explode test to convert_aggregates.mlir file.

[HW] Add support for struct_explodeOp in HWToLLVM

---

frontends/PyCDE/src/support.py
frontends/PyCDE/src/system.py
frontends/PyCDE/src/types.py
frontends/PyCDE/src/value.py
frontends/PyCDE/test/pycde_types.py

Allows users to define structs as Python classes and use instances of that class in generators:
```py
class ExStruct(Struct):
a: Bits(4)
b: UInt(32)
def get_b(self):
return self.b
class TestStruct(Module):
inp1 = Input(ExStruct)
out2 = Output(ExStruct)
@generator
def build(self):
... = self.inp1.get_b()
self.out2 = ExStruct(a=..., b=...)
```

[PyCDE] Class based struct definitions

---

frontends/PyCDE/src/CMakeLists.txt
frontends/PyCDE/src/__init__.py
frontends/PyCDE/src/behavioral.py
frontends/PyCDE/src/common.py
frontends/PyCDE/src/constructs.py
frontends/PyCDE/src/devicedb.py
frontends/PyCDE/src/dialects/comb.py
frontends/PyCDE/src/dialects/esi.py
frontends/PyCDE/src/dialects/fsm.py
frontends/PyCDE/src/dialects/hw.py
frontends/PyCDE/src/dialects/hwarith.py
frontends/PyCDE/src/dialects/msft.py
frontends/PyCDE/src/dialects/seq.py
frontends/PyCDE/src/dialects/sv.py
frontends/PyCDE/src/esi.py
frontends/PyCDE/src/esi_api.py
frontends/PyCDE/src/fsm.py
frontends/PyCDE/src/instance.py
frontends/PyCDE/src/module.py
frontends/PyCDE/src/ndarray.py
frontends/PyCDE/src/signals.py
frontends/PyCDE/src/support.py
frontends/PyCDE/src/system.py
frontends/PyCDE/src/testing.py
frontends/PyCDE/src/types.py
frontends/PyCDE/test/errors.py
frontends/PyCDE/test/esi.py
frontends/PyCDE/test/muxing.py
frontends/PyCDE/test/pycde_types.py
frontends/PyCDE/test/pycde_values.py

Improve bad code:
- Cleanup imports.
- Complete the `Value` to `Signal` rename.
- Clarify argument and return types. Allows for removal of defensive code.

[PyCDE][NFC] Cleanups and renames

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/InstantiateCompanionOnly.fir

When we added the flag to directly instantiate companions, we also stopped generating interfaces.  This flag skipped generating the interface metadata file, which caused issues for flows which still expected it to be generated.  This commit changes the logic to skip adding interfaces to the worklist instead of an early break, which causes us to still generate the metadata, but with no entries.

[FIRRTL][GC] Always generate the scope yaml file

---

include/circt/Dialect/MSFT/MSFTOps.td
lib/Dialect/HW/HWOps.cpp
lib/Dialect/MSFT/MSFTOps.cpp
test/Dialect/HW/basic.mlir

When we create the PortInfo object for a module, if the port is a HW::InOutType, we strip it and set the isInOut field to true.  When we create a module from a PortInfo object we respect this field while constructing the function type, but were not respecting the isInOut when creating the block arguments.
This change starts respecting the `isInOut` field of port info when constructing the block argument types.  This also adds a verifier that the function type of the module matches the block argument types.

[HW][MSFT] Fix creating modules with InOut typed ports

---

include/circt/Dialect/Calyx/CalyxLoweringUtils.h
include/circt/Dialect/HW/HWAttributesNaming.td
include/circt/Dialect/SV/SV.td
lib/Conversion/PipelineToCalyx/PipelineToCalyx.cpp
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp
lib/Dialect/FIRRTL/Transforms/InnerSymbolDCE.cpp

This deals with two issues:
SubElementInterfaces went away and became a core construct: https://github.com/llvm/llvm-project/commit/03d136cf5f3f10b618b7e17f897ebf6019518dcc
It seems most of the APIs we used are already supported, and InnerSymbolDCE needed to change. Since the new `walk` API includes the attribute itself, InnerSymbolDCE can be simplified slightly.
I would hope this change is covered by tests. The InnerSymbolDCE change is: https://github.com/llvm/circt/blob/main/test/Dialect/FIRRTL/inner-symbol-dce.mlir
A new assertion was added to GreedyPatternRewriteDriver as part of a refactoring change, which doesn't support our use-case: https://github.com/llvm/llvm-project/commit/977cddb95eac67a6dc6680a7d0fadee81114de11
I just changed the rewrite pattern in question to just do a …

Bump LLVM to 95e49f5a74c9e79778a62cc58b15875613cf9e59.

---

frontends/PyCDE/src/module.py
frontends/PyCDE/src/signals.py
frontends/PyCDE/src/support.py
frontends/PyCDE/src/types.py
frontends/PyCDE/test/test_misc_errors.py

Instead of calling `_obj_to_value` from the support library, use some OOP to leverage the `Type` system to do it. The `_obj_to_value` function dates back to when we were using raw `ir.Types` and not extending them. Now that we have a proper type hierarchy (and can rely on it being used), this change is possible.

[PyCDE][NFC] Create signals from Python objects through Types

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

This PR reimplements #4451 revered by #4465. The bug was that `getOrCreateAggregateConstantAttribute` re-used IntegerAttribute used by firrtl.aggregateconstant op. In FIRRTL dialect, integer attrs are APSIntAttr, which aren't compatible with normal integer attributes. https://github.com/llvm/circt/pull/4608/commits/103e595556b09e64916b241bd016a2b99f56b48b includes a fix to explicitly convert APSIntAttr into normal integer attrs.

[LowerToHW] Lower aggregate constant

---

include/circt/Dialect/HW/HWAttributesNaming.td

No longer implement the SubElementAttrInterface interface, so this method is no longer used.

[HW][NFC] InnerRef: Remove unused method definition

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
lib/Dialect/SV/Transforms/PrettifyVerilog.cpp
test/Conversion/ExportVerilog/sv-always-wire.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir

This commit fixes bugs in spilling logic regarding expressions used in sensitivity list.
* PrettifyVerilog is changed to check lowering options so that CSEd expressions are not cloned into users when `exprInEventControl` is enabled.
* There was a duplicated logic in isExpressionUnableToInline and PrepareForEmission so the logic was unified into isExpressionUnableToInline.
Fix https://github.com/llvm/circt/issues/4620
```verilog
; with --lowering-options=exprInEventControl
always @(posedge clock or posedge ~rst_n) begin
if (~rst_n)
r <= 1'h0;
else
r <= d;
; w/o --lowering-options=exprInEventControl
wire _GEN = ~rst_n;
always @(posedge clock or posedge _GEN) begin
if (_GEN)
r <= 1'h0;
else
r <= d;
```

[ExportVerilog][PrettifyVerilog] Fix exprInEventControl

---

test/firtool/print-before.fir
tools/firtool/firtool.cpp

With the recent change to how port location information is handled, the upstream pass StripDebugInfo no longer leaves the IR in a valid state, as it does not update the debug information stored in module ops.  To fix this problem, we just have to use the local version of this pass, StripDebugInfoWithPred and tell it to remove all locations.
Closes #4631.

[firtool] Use CIRCT's StripDebInfo pass instead of upstream

---

docs/Dialects/FIRRTL/FIRRTLAnnotations.md
docs/Dialects/FIRRTL/RationaleFIRRTL.md
include/circt/Dialect/Calyx/CalyxStructure.td
include/circt/Dialect/FIRRTL/CHIRRTL.td
include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/FIRRTL/FIRRTLStatements.td
include/circt/Dialect/FIRRTL/FIRRTLStructure.td
include/circt/Dialect/SV/SVExpressions.td
include/circt/Dialect/SV/SVInOutOps.td
include/circt/Dialect/SV/SVTypeDecl.td
lib/Dialect/ESI/ESIOps.cpp
lib/Dialect/FIRRTL/CHIRRTLDialect.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/parse-basic.fir
test/circt-as-dis/basic-firrtl.mlir

In FIRRTL, we unconditionally print a space before printing optional attribute dictionaries. However, the majority of the time, the attr dict is elided, so that we end up with a double-space in our output. It turns out, the underlying utility in MLIR, `printOptionalAttrDict`, will print a leading space if it has to print the attr dict, so it's pointless for us to be outputting one ourselves. This PR removes the extra whitespace for a number of ops.
A large number of ops use a custom directive to print the attributes. To suppress leading whitespace in this case, we can use an empty literal (``) in the asm format.
Modified Ops:
- `firrtl.circuit`
- `firrtl.module`
- `firrtl.wire`
- `firrtl.mem`
- `firrtl.node`
- `firrtl.printf`
- `firrtl.reg`
- `firrtl.regreset`
- `firrtl.instance`
- …

[FIRRTL] Remove extra whitespace around optional attr dicts

---

include/circt/Dialect/ESI/ESI.td
include/circt/Dialect/ESI/ESIStructure.td
include/circt/Dialect/MSFT/MSFTOps.td
lib/Dialect/ESI/ESIOps.cpp
test/Dialect/ESI/structure.mlir
test/Dialect/ESI/structure_errors.mlir

A module containing only ESI channels and modules with only ESI ports. All non-local connectivity is done through ESI services. If this module is the top level in the design, then the design's actual top level ports are defined by a BSP.
Useful on its own for simulation and BSPs which don't define a top-level.

[ESI] Introduce ESI pure module op

---

integration_test/ESI/cosim/loopback.mlir
integration_test/ESI/cosim/loopback.py
tools/esi/esi-cosim-runner.py.in

Adds the '--exec' flag to tell this util to run the file instead of
parsing it and constructing a python script. Also removes unused
functionality SOURCES: and ARGS:. If `--exec` is used, the program's
first two args are the cosim port number and the path to the schema. If
the specified test application ends in '.py', it'll run the python
script with the python interpreter.

[ESI][Cosim Runner] Add support for running binaries

---

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code.mlir

Fix case where port is named "" (`_GEN`), teach to grab name from instance.
Add test based on case found in the wild.

[SV][ETC] Name port after instance result name, as well.

---

test/firtool/include-dirs.fir

Test that resolving using relative include directories works, and check behavior re:search order (relative to working directory is searched first, specified paths after).

[firtool][NFC] Test relative path searching for includes.

---

include/circt/Dialect/FIRRTL/FIRRTLFieldSource.h
include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/CMakeLists.txt
lib/Dialect/FIRRTL/FIRRTLFieldSource.cpp
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/PrintFIRRTLFieldSource.cpp

This analysis maps values back to their definitions (operations which produce a new value) and provides an indexing path in the original definition to produce the current value.
Subaccesses produce a -1 (wildcard) in the path.
The analysis provides the user with a stable summary node for each value which is suitable to use in other data-structures.
```
wire a : firrtl.vector<bundle<f1: uint, f2: uint>, 4> => definition, is a root (empty path)
v = subindex(a, 2) => derived from a with path {2}
w = subfield(v, f2) => derived from a with path {2, 1}
```

[FIRRTL] Simple points-to like analysis

---

include/circt/Dialect/SV/SVGenerate.td

- removed MaxSizedRegion, it's now defined in `mlir/include/mlir/IR/OpBase.td` via https://reviews.llvm.org/D143253

Bump llvm to 78056e2f2d9510d2ace42fe7e9eb60e5abe8a3e7

---

include/circt/Dialect/FIRRTL/FIRRTLOps.h
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp
test/Dialect/FIRRTL/simplify-mems.mlir

After memories are flattened, subsequent passes can render certain bits of their outputs unused.
This PR introduces a canonicalizer which identifies the bits of a memory output that are used (by looking through `BitsPrimOp` oeprations). Afterwards, the memory is narrowed and write inputs are built by concatenating the chunks of the selected inputs.

[FIRRTL][MemOp] Removed unused bits from memories

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types-aggregate.mlir

This changes LowerTypes to look up module visibilities. module.isPublic() cannot be used because of a race condition https://github.com/llvm/circt/pull/4582

[LowerTypes] Track public modules and force lowering properly

---

include/circt/Dialect/ESI/ESIStructure.td
lib/Dialect/ESI/ESIOps.cpp
test/Dialect/ESI/structure.mlir
test/Dialect/ESI/structure_errors.mlir

These ops are intended to be produced by service implementation generators to translate service requests into top-level ports when lowering into an RTL level module.

[ESI] Introduce `pure_module.input` and `pure_module.output`

---

lib/Dialect/HW/HWOps.cpp
test/Dialect/HW/canonicalization.mlir

This implements canonicalizer to sink constant index to inner array create. 
```
array_get(const, array_get sel, (array_create a, b, c, d)) --> 
array_get sel, (array_create (array_get const a), (array_get const b), (array_get const c), (array_get c d))
```
Though this might increase the size of IR we can reduce the size of a temporary created by array create op.

[HW] Add a canonicalization to swap constant index and unknown index of array gets

---

lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
test/Dialect/FIRRTL/annotations.mlir

This changes LowerAnnotations to make the module visility public. DUT interface is intended to be exposed to users/costomers and its ports are dontTouched so it's reasonable to mark the module public

[LowerAnnotations] Make DUT module public

---

lib/Dialect/Calyx/CalyxOps.cpp

This llvm bump [commit](https://github.com/llvm/circt/commit/88c5572224dcc4a631c22a197f2d2714bad33a30#diff-bbfc48ed5eafd91f51b04a279d09004575d95b14c830dbff851af86fc2169c94) broke building CombComponentOps using the `buildComponentLike` function. This PR fixes the issue by deciding to call a different `getFunctionTypeAttrName` function based on whether we are building a comb or regular component.

Fix Combinational Component Builder

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/errors.mlir

Casting bits to non-passive types is problematic re:flow, so limit the result to passive types.
Tweak BitCast's verifier to no longer reject non-passive inputs.

[FIRRTL] Limit BitCast to passive output, fix non-passive input.

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir
test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir

Ensure DontTouched ports have symbols on them to model "don't touch", consume the annotation.
This will cause zero-width dontTouch'd ports to produce an error, emit more specific error in this case.

[LowerToHW] Handle port dontTouch, add inner sym.

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/simplify-mems.mlir

This pass replaces single-address memories with one register. The write ports are ordered and implemented through muxes. The transformation is enabled only when all writes are driven by the same clock.
Fixes #4579

[MemOp] Replace single-address memories with registers

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/Comb/canonicalization.mlir
test/firtool/memory.fir

This commit propgates bin flags through icmp and varidic op canonicalizer.
* `icmp bin eq 1, %x` => `icmp bin eq 1, %x`
* `and bin (and bin %x, %y), %z` => `and bin %x, %y, %z`
*  `icmp bin eq(replicate(v, n), c)` => `icmp bin eq(v, c)`
*  `icmp bin eq x, 0` => `xor bin x, 1`
and etc.

[CombFolds] Propapate bin flags through icmp and variadic op canonicalizer

---

include/circt/Dialect/Arc/Arc.td
include/circt/Dialect/Arc/CMakeLists.txt
include/circt/Dialect/Arc/Dialect.h
include/circt/Dialect/Arc/Dialect.td
include/circt/Dialect/Arc/Ops.h
include/circt/Dialect/Arc/Ops.td
include/circt/Dialect/CMakeLists.txt
include/circt/InitAllDialects.h
lib/Dialect/Arc/CMakeLists.txt
lib/Dialect/Arc/Dialect.cpp
lib/Dialect/Arc/Ops.cpp
lib/Dialect/CMakeLists.txt
test/Dialect/Arc/basic-errors.mlir
test/Dialect/Arc/basic.mlir
test/circt-opt/commandline.mlir
tools/circt-opt/CMakeLists.txt

Add the `Arc` dialect which is useful for capturing a canonical representation of the state transfer in a circuit. It does this by introducing function-like arc definitions (`arc.define`) and call-like arc invocations (`arc.state`). The state op represents a transfer function, given by the arc definition, and zero or more registers, as specified by its latency attribute.

[Arc] Add dialect

---

lib/Dialect/Handshake/HandshakeOps.cpp
test/Dialect/Handshake/canonicalization.mlir

This fixes a bug in the `EliminateCBranchIntoMuxPattern` canonicalization pattern where a `cond_br` operation would get deleted despite still having uses. Below is an example `handshake.func` which would trigger the bug.
```mlir
handshake.func @cbranch_into_mux_elim(%arg0 : i1, %arg1 : index, %arg2 : i32, %arg3: none) -> (i32, i32, none) {
%trueResult, %falseResult = cond_br %arg0, %arg2 : i32
%0 = mux %arg1 [%trueResult, %falseResult] : index, i32
%1 = arith.addi %trueResult, %trueResult : i32 
handshake.return %0, %1, %arg3 : i32, i32, none
}
```
Here the `cond_br` would get deleted despite `%trueResult` still being used by `arith.addi`. 
The above example is added to Handshake canonicalization tests.

[Handshake] Fix incorrect operation deletion in EliminateCBranchIntoMux canonicalization pattern

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/Comb/canonicalization.mlir

ExtractOp has a canonicalizer which uses computeKnownBits.  This canonicalizer is very expensive.  Disalbing this to mitigate #4688 until performance is addressed.

[COMB] disable one folder for 25% end-to-end perf improvement.

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir

Walk back error introduced in #4675, reduce to warning.
This is apparently used, continue to remove despite the annotation, but issue warning.

[LowerToHW] Reduce dontTouch+zero-width error to warning.

---

.github/workflows/uploadBinaries.yml

* Disable ZSTD so that MacOS binaries do not dynamically link against libzstd
* Use install target and package that to have include and lib directories (in addition to the bin directory)
* Upload artifacts to the Github Actions page when this workflow is triggered so that the artifacts can be checked
Related to https://github.com/llvm/circt/issues/4669, doesn't fix all issues but it demonstrably fixes some.
You can see examples of the binaries created on a tag here https://github.com/jackkoenig/circt/releases/tag/v0.2.0, and just for branches when you trigger workflow dispatch here: https://github.com/jackkoenig/circt/actions/runs/4240453857

Improve MacOS published binaries and flow

---

lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
test/Dialect/FIRRTL/legacy-wiring-errors.mlir
test/Dialect/FIRRTL/legacy-wiring.mlir

Loosen the wiring check: types must be FIRRTL types, and either identical or type-equivalent.
Fixes #4651.

[LowerAnnotations] Allow wiring type-equivalent types.

---

include/circt/Support/LoweringOptions.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Support/LoweringOptions.cpp
test/Conversion/ExportVerilog/disallow-array-index-inlining.mlir

Add an option to disallow the inlining of expressions into the index of array get and slice operations. This affects output as follows:
// disallowArrayIndexInlining = false
assign y = a[b * (b + 4'h2)];
// disallowArrayIndexInlining = true
wire [3:0] TMP = b * (b + 4'h2);
assign y = a[TMP];
We have seen Vivado produce incorrect synthesis results for some of these inlined index expressions. This flag is intended as a workaround. Off by default.

[ExportVerilog] Add disallowArrayIndexInlining option

---

.github/workflows/uploadBinaries.yml

This is needed in order to run git describe --tag

Unshallow CIRCT clone in uploadBinaries workflow

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir

[LowerToHW] Use port locations for diagnostics, don't dump module.

---

frontends/PyCDE/src/common.py
frontends/PyCDE/src/signals.py
frontends/PyCDE/src/types.py
frontends/PyCDE/test/test_esi.py
frontends/PyCDE/test/test_esi_errors.py
include/circt-c/Dialect/ESI.h
lib/Bindings/Python/ESIModule.cpp
lib/Bindings/Python/dialects/esi.py
lib/CAPI/Dialect/ESI.cpp

- Plumbing through signaling and adding it as an optional argument on Channel ports.
- Teach wrap/unwrap how to operate on FIFO0 signaling.

[PyCDE] Expose signaling and FIFO0

---

.github/workflows/uploadWheels.yml
lib/Bindings/Python/CMakeLists.txt
lib/Bindings/Python/pyproject.toml
lib/Bindings/Python/setup.py
lib/Transforms/CMakeLists.txt

The workflow uses cibuildwheel to build the wheels, and uploads them to GitHub. They're added to the artifacts for manual runs, and added to the release assets when triggered by a release.
Currently, manylinux wheels are built for CPython 3.7 and 3.10.
This also updates the packaging scripts to include setuptools_scm to take version numbers from Git tags.

[CI] Add a workflow for building and uploading Python wheels.

---

frontends/PyCDE/src/esi.py
frontends/PyCDE/test/test_esi.py
include/circt/Dialect/ESI/ESIStructure.td
lib/Dialect/ESI/ESIPasses.cpp
test/Dialect/ESI/structure.mlir

Some low-level BSPs instantiate the top-level module with parameters. We don't care about said parameters' values but they need to be present in the resulting module nonetheless.

[ESI] Add parameters to PureModule lowering

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Add the pattern mux(cond, 0, 1) -> ~cond
Fixes https://github.com/llvm/circt/issues/4717

[FIRRTLFolds] Add a mux canonicalize pattern

---

frontends/PyCDE/src/esi.py
frontends/PyCDE/src/module.py
frontends/PyCDE/test/test_esi.py
lib/Bindings/Python/dialects/_msft_ops_ext.py
lib/Dialect/MSFT/Transforms/MSFTToHW.cpp

Adds a 'Attribute' python attribute which can be used to set (CIRCT) attributes on modules. Use that mechanism to expose the "FlattenStructPorts" ESI attribute.

[PyCDE] Set dialect attributes on modules, expose flatten dialect attr

---

include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
lib/Dialect/FIRRTL/FIRRTLTypes.cpp

Drop custom storage class too, not needed just to parameterize over a type.
We use these elsewhere to handle computing recursive properties and stashing information about them in the stored type pointer (bundle/vector), but for reference types this isn't needed as references don't have these properties.
For RefTypes, we (already) query the underlying base type for those if needed, and since only one level of references allowed no reason to cache their recursive calculation as we should only need to go one layer into the reference.

[FIRRTL][NFCI] Move RefType to ODS

---

include/circt/Support/Passes.h
tools/firtool/firtool.cpp

This PR moves FirtoolPassInstrumentation to a support header and rename FirtoolPassInstrumentation to VerbosePassInstrumentation. 
This subsumes https://github.com/llvm/circt/pull/3931/. Calling `isa<firrtl::CircuitOp>` caused circular deps between firrtl and support so this PR instead used template arguments to filter operation types.

[Support] Move FirtoolPassInstrumentation to a support header, NFC

---

frontends/PyCDE/src/esi.py
frontends/PyCDE/src/module.py
include/circt/Dialect/ESI/ESIDialect.h
lib/Dialect/ESI/ESIPasses.cpp
test/Dialect/ESI/lowering.mlir

Some external modules use unusual port naming conventions. Since we want
to avoid users needing to write wrappers, provide some flexibility in naming
convention.

[ESI] Add more flexibility to port names during lowering

---

include/circt-c/Dialect/SV.h
include/circt/Dialect/SV/SVAttributes.h
include/circt/Dialect/SV/SVAttributes.td
integration_test/Bindings/Python/dialects/seq.py
lib/Bindings/Python/SVModule.cpp
lib/CAPI/Dialect/SV.cpp
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/SV/SVAttributes.cpp
lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Conversion/ExportVerilog/pretty.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir
test/Dialect/SV/hw-cleanup.mlir

Move the `emitAsComments` flag from `SVAttributesAttr` (plural) to `SVAttributeAttr` (singular). Then remove `SVAttributesAttr` (plural) since it only contains a single array field after `emitAsComments` is gone.
Add add, remove, and read-modify-write functions to deal with SV attributes on operations more conveniently. Also enforce deduplicated SV attributes where easily possible. The new functions now allow for easy addition and removal of individual SV attributes.
Adapt ExportVerilog to handle the fact that emission as comments is now a per-attribute option. The emission code now can emit multiple `/*...*/` and `(*...*)` groups if needed, but tries to pack as many consecutive attributes with the same `emitAsComment` flag into one group.

[SV] Move emitAsComment to SVAttributeAttr; remove SVAttributesAttr

---

.github/workflows/buildAndTest.yml

GCC+debug consumes too much memory. This swaps gcc and clang build mode.
CI: https://github.com/llvm/circt/actions/runs/4306635035 
Close https://github.com/llvm/circt/issues/4740

[CI] Swap build mode of gcc and clang

---

lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp

This fixes nondeterminism caused by iteration over DenseMap. Instead use MapVector to guarantee determinism.

[ExtractInstances] Fix nondeterminism with MapVector.

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/simplify-mems.mlir

My initial understanding of memory latencies was incorrect and I wrongly inserted pipelining after the resulting register. However, it is the address and enable signals that must be pipelined. For these memories, the address is always 0 and the enable signal can be discarded, allowing the read ports to be folded to the resulting register.
Fixes #4734

Remove pipelining from simplified single-address memory reads

---

docs/VerilogGeneration.md
include/circt/Support/LoweringOptions.h
include/circt/Support/LoweringOptionsParser.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Support/LoweringOptions.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir
test/Conversion/ExportVerilog/verilog-basic.mlir
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir
test/Dialect/FIRRTL/SFCTests/load-memory-from-file.fir

When emitting instances as binds, we leave a comment where the instance was originally located, indicating that it is now located elsewhere as a bind. This comment, apparently, isn't helpful, and causes some trouble too. The comment includes a summary of what was bound, which can cause some textual differences between verilog code that differs only in how it is bound to a view. This PR removes the comment.
This PR adds a lowering-option, "emitBindComments", which preserves the original behaviour, but it is off by default.

[ExportVerilog] Remove comments for instances emitted as binds

---

include/circt/Dialect/Arc/Ops.td
lib/Dialect/Arc/Ops.cpp
test/Dialect/Arc/basic-errors.mlir
test/Dialect/Arc/basic.mlir

Arcs are assumed pure everywhere, but it's not properly verified yet. This adds a region verifier to check that all operations in the body have the pure trait.
Also, it removes the pure trait from the stateOp. While it is fine to have it for the case where latency is 0, it is a problem for higher latencies because of 2 reasons:
* They are converted to fields in the datastructure that is exposed to the user and can be read from. If the user want's to observe a state and that state has no users in the design (maybe because they were optimized away), the state will also be optimized away and the user has no read-access to it anymore.
* Even if we separate above concern to another operation (e.g. use the tap op for that), the output of the state op will still not be the same for the same …

[Arc] Verify that arc bodies are pure

---

include/circt/Dialect/LLHD/IR/SignalOps.td
test/Dialect/LLHD/IR/signal-errors.mlir

LLHDToLLVM crashes when `llhd.sig` is in a op other than `entity` or `proc`. As there is no need to use it in another function we can verify it as such.

[LLHD] Only permit signal creation in entity and proc ops

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
tools/firtool/firtool.cpp
tools/hlstool/hlstool.cpp

- use lowerTypes to scalarize public ports before running vb-to-bv. This lets vb-to-bv lower all types, without considering whether a module or extmodule is public.
- Add a memory preservation option to lower types. This option lets us use lowerTypes to scalarize the ports of public module without modifying memories.
- Perform  flatten-memories after vb-to-bv. The vb-to-bv pass cannot reshape memories that have been flattened.

[FIRRTL] Correct memory lowering behaviour for vb-to-bv conversion

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
test/Dialect/FIRRTL/canonicalization.mlir

https://github.com/llvm/circt/commit/c4447004c344e5a3391a1d7546565197a7dd324f causes a width mismatch when false value is not UInt<1>. This commit adds a check for type equivalence.

[FIRRTLFolds] Fix width mismatch

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/Transforms/InferResets.cpp
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp

Ensure code continues to work for anything that's FConnectLike, without having to add it to each of these locations.
Code with behavior very specific to ConnectOp and/or StrictConnectOp are left unmodified, but if all that matters is source => destination then use FConnectLike.
Prefer `getDest()` (and `getSrc()`) over hardcoding operand numbers.

[FIRRTL][NFCI] Use FConnectLike to abstract over connection types.

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR-errors.mlir

1) Don't dereference op after checking if it's null.
(shame compiler doesn't see through this enough to warn!)
2) Handle ref.sub coming from port not op.
Add tests.
This shouldn't be reachable presently, but may in the near future (and good to be robust anyway).

[FIRRTL][LowerXMR] Don't crash if encounter unexpected ref.sub.

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

1) Collapse a trivial ref.resolve of an ref.send:
ref.resolve(ref.send(x)) -> x
2) Hoist ref.sub through ref.send:
ref.sub(ref.send(x), idx) -> ref.send(sub{field,index}(x, idx))
(split into a pattern for each)
Add tests for each and their combination.
Fixes #4693.

[FIRRTL] Canonicalizers: simplify resolve-of-send and hoist ref.sub out of ref.send.

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR.mlir

InstanceOp is "special" in that the inner symbol targets the instance itself and its results cannot have symbols.
Fixes #4559.

[FIRRTL][LowerXMR] Fix XMR to instance port/result.

---

lib/Conversion/HWToLLVM/HWToLLVM.cpp
test/Conversion/HWToLLVM/convert_aggregates.mlir

We should use the adaptors provided by the pattern rewrite system properly.

[HWToLLVM] Remove unnecessary target materializations

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/SV/SVExpressions.td
include/circt/Dialect/SV/SVInOutOps.td
include/circt/Dialect/SV/SVTypeDecl.td
include/circt/Support/CustomDirectiveImpl.h
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/SV/CMakeLists.txt
lib/Dialect/SV/SVOps.cpp
lib/Support/CMakeLists.txt
lib/Support/CustomDirectiveImpl.cpp

The FIRRTL and SV dialects have an almost interchangeable implementation of the `ImplicitSSAName` directive, which they apply to the `attr-dict` of the operation. To facilitate adding ops in other dialects that want to use a similar scheme, factor the commonalities of these directives out into the `CIRCTSupport` library.
The SystemC dialect uses a slightly different approach: it also uses a `ImplicitSSAName` directive, but that one is defined in the HW dialect and is applied to the `$name` of the op instead of the `attr-dict`. The benefit is that TableGen automatically generates the list of attrs to be elided (since `$name` is explicitly covered in the assembly format), and printing the name in case it mismatches with the SSA name is handled outside of the generic `attr-dict` printer. We …

[Support][NFC] Factor out ImplicitSSAName directive

---

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
test/Dialect/FIRRTL/SFCTests/directories.fir
test/Dialect/FIRRTL/emit-metadata.mlir
test/firtool/memoryMetadata.fir

Remove the "tb_seq_mems.json" metadata file as this has not been used for a long time.  This was previously a metadata file that would list memory information about the test harness.
Fix bugs in how memory metadata files are generated for situations where no DUT is specified and when a DUT is specified, but a memory is instantiated in both the DUT and the Testbench.
Previously, if no DUT was specified then all memory instances would be placed in "tb_seq_mems.json".  Now, all instances will be placed in "seq_mems.json".
Previously, if a memory was instantiated in both the DUT and the Testbench, then it would wind up with all instances placed in "seq_mems.json", including the one from the Testbench.  Change this to put the memory module in both the "tb_seq_mems.json" and "seq_mems.json", …

[FIRRTL] Fix Mem Metadata DUT/No-DUT Logic

---

lib/Dialect/FIRRTL/Transforms/MemToRegOfVec.cpp
test/Dialect/FIRRTL/SFCTests/directories.fir
test/Dialect/FIRRTL/SFCTests/directories.fir.memtoregofvec.anno.json

Change the MemToRegOfVec pass to work on all memories (which match its filtering criteria) if there is no DUT specified with a "MarkDUTAnnotation".  This brings this pass in agreement with other passes which treat a DUT-less design as if the top module was the DUT.
This is currently stacked on #4768 as this touches a lot of the same "directories.fir" test.

[FIRRTL] Fix MemToRegOfVec DUT/No DUT Behavior

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLUtils.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/Export/FIREmitter.cpp
lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp
lib/Dialect/FIRRTL/FIRRTLFieldSource.cpp
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp
lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp
lib/Dialect/FIRRTL/Transforms/FlattenMemory.cpp
lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
lib/Dialect/FIRRTL/Transforms/InferReadWrite.cpp
lib/Dialect/FIRRTL/Transforms/InferResets.cpp
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
lib/Dialect/FIRRTL/Transforms/MemToRegOfVec.cpp
lib/Dialect/FIRRTL/Transforms/WireDFT.cpp

Add FIRRTLValue, FIRRTLBaseValue conveniences, use a little.
Narrow SubindexOp/SubaccesOp to FVectorType input, as required.
Mostly remove redundant casting thanks to TypedValue being added
a while back to, e.g., generated accessors via ODS, as well
as no need to cast to FIRRTLType and /then/ do a classof/isa check.
Few cases where we did a dyn_cast followed by a cast, or an isa
and then a cast-- don't check twice.
Generally, prefer pushing up to interfaces implicit requirements/expectations
on Value's or Type's passed around.
(if a function blindly does a cast<FooType>, better to ask for a TypedValue<FooType>).
More work could be done here.  Tackled as preparation for some type
changes and implicit type expectations make that more difficult.

[FIRRTL][NFCI] Cleanup some casting/types, leverage TypedValue a bit.

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

This fixes a crash in isDuplicatableExpression when array index is a port or read of a port.

[ExportVerilog] Fix crash in `isDuplicatableExpression`

---

lib/Dialect/FIRRTL/Transforms/MemToRegOfVec.cpp

Drop ModuleNamespace entirely, previously fixed it to be per-thread and such but it's not needed so just drop it.

[FIRRTL] MemToRegOfVec: Fix threading issue, performance improvement.

---

lib/Dialect/FIRRTL/FIRRTLOps.cpp

Virtually NFC, cleanup a common pattern with a helper function.
Replace instances of:
```c++
if (badness) {
if (loc)
emitError(*loc, ...) << ...;
return {};
}
```
with:
```c++
if (badness)
return emitInferRetTypeError(loc, ..., ...);
```  
The produced errors should all be identical, with the exception that mux errors previously attached notes (without location) for the true/false types, which are now printed in the original error.
Many, but not all, errors are covered in tests (for example, the mentioned mux errors).

[FIRRTL] Refactor errors emitted during return type inference.

---

lib/Dialect/FIRRTL/Transforms/RegisterOptimizer.cpp
test/Dialect/FIRRTL/register-optimizer.mlir

There is a bug that implicit ext/trunc of reg reset's reset values is not handled in RegisterOpt pass which caused width mismatch error in many designs. This fixes the issue by inserting pad/tail/trunc op accordingly.

[RegisterOpt] Add implicit ext/trunc

---

include/circt/Dialect/HW/HWOpInterfaces.td

Touchup method descriptions to match behavior.
cc #4789.

[HW][NFC] InnerSymbolOpInterface: fixup method descriptions to match what they do.

---

include/circt/Dialect/HW/HWOpInterfaces.td

Add method for setting all inner symbols at once, using the provided InnerSymAttr, not just the top-most.
In default implementation, if empty, remove the inner symbol attribute on the operation.
cc #4789.

[HW][InnerSym] Add InnerSymbolOpInterface::setInnerSymbolAttr

---

include/circt/Dialect/HW/HWTypes.td
lib/Dialect/HW/HWAttributes.cpp

Add method to generate a new InnerSymAttr with the specified field's inner symbol removed .
cc #4789 .

[HW] Add InnerSymAttr::erase.

---

include/circt/Dialect/Arc/CMakeLists.txt
include/circt/Dialect/Arc/Passes.h
include/circt/Dialect/Arc/Passes.td
include/circt/InitAllPasses.h
lib/Dialect/Arc/CMakeLists.txt
lib/Dialect/Arc/Transforms/CMakeLists.txt
lib/Dialect/Arc/Transforms/Dedup.cpp
lib/Dialect/Arc/Transforms/PassDetails.h
test/Dialect/Arc/dedup.mlir
tools/circt-opt/CMakeLists.txt

Add the `Dedup` pass which deduplicates arcs with identical definitions. If arcs differ only by constant values, the pass outlines the constants such that the arcs can be deduplicated.
Identical arcs are surprisingly common since splitting modules along the fundamental state elements yields a finer-grained subdivision than the modules themselves, which has the potential to uncover additional redundancies.

[Arc] Add deduplication pass

---

include/circt/Dialect/Arc/Passes.h
include/circt/Dialect/Arc/Passes.td
lib/Dialect/Arc/Transforms/CMakeLists.txt
lib/Dialect/Arc/Transforms/InlineModules.cpp
test/Dialect/Arc/inline-modules.mlir

Add the `InlineModules` pass which forcefully inlines all private HW modules. This essentially collapses the entire module hierarchy of a design and leaves a single module where the `arc.state` ops form a state transfer graph that is convenient to analyze and transform.
After outlining combinational logic and registers into arcs through the `ConvertToArcs` pass, module bodies become fairly lightweight. Since arc definitions now fulfill the purpose of code reuse by allowing a single definition to be called multiple times, the module hierarchy degenerates into a purely cosmetic construct. At that point it is beneficial to fully flatten the module hierarchy to simplify further analysis and optimization of state transfer arcs.

[Arc] Add module force-inlining pass

---

test/CMakeLists.txt
test/arcilator/arcilator.mlir
test/lit.cfg.py
tools/CMakeLists.txt
tools/arcilator/CMakeLists.txt
tools/arcilator/arcilator.cpp

Add the `arcilator` convenience tool to make experimenting with the dialect easier. The intended pass sequence performs the full conversion from a circuit cut along port boundaries (through modules) to a circuit cut along the state elements (through arcs). The tool simply executes this pass pipeline.

[Arc] Add arcilator convenience tool

---

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
test/Dialect/FIRRTL/infer-widths-errors.mlir

Fix an issue in `InferWidths` where analog values attached to each other would not produce proper errors if the widths are unsatisfiable. For example, the following is unsatisfiable but successfully infers to an incorrect width:
```
firrtl.module @AnalogWidths(
in %a: !firrtl.analog,
out %b: !firrtl.analog<2>,
out %c: !firrtl.analog<1>
) {
firrtl.attach %a, %b : !firrtl.analog, !firrtl.analog<2>
firrtl.attach %a, %c : !firrtl.analog, !firrtl.analog<1>
}
```
The `AttachOp` imposes a `lhs >= rhs` *and* `lhs <= rhs` constraint, which is supposed to devolve into `lhs == rhs`. However, `InferWidths` ignores upper bound constraints like `expr <= 42` since the original Scala implementation used to violate upper bounds in obscure and wild ways (see #1088).
This commit adds an optional upper bound …

[FIRRTL][InferWidths] Honor upper bounds on AttachOp

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/verilog-basic.mlir

Currently the `lowerAlwaysInlineOperation` function will happily move ops right in front of their user, which is problematic if the user is an assign op. If the assign immediately follows its wire declaration, `ExportVerilog` would happily emit the expression inline. However, `lowerAlwaysInlineOperation` inserts operations in between the declaration and the assignment, such that the conservative inlining in `ExportVerilog` can no longer to its thing. This leads to unfortunate output Verilog:
wire foo;
assign foo = a + b;
The IR here probably initially looked like:
%0 = comb.add %a, %b
%foo = sv.wire
sv.assign %foo, %0
But `lowerAlwaysInlineOperation` would then pull the addition down:
%foo = sv.wire
%0 = comb.add %a, %b
sv.assign %foo, %0
Which can no longer be inlined at the declaration …

[ExportVerilog] Avoid splitting wire decl and assign in expr inlining

---

test/Dialect/FIRRTL/SFCTests/dedup.fir
test/Dialect/FIRRTL/SFCTests/emit-metadata.fir
test/firtool/chirrtl.fir
test/firtool/memoryLowering.fir
test/firtool/memoryMetadataRenameFail.fir
tools/firtool/firtool.cpp

This PR removes many hidden developer options from firtool.  These options were more useful when we would regularly have crashes in specific passes and a developer would want to temporarilly bypass the pass.  Now that we are much more stable, these options don't add any utility, and we risk that a user may find and start using one of these options.
This change also:
- removes the unused `emit-metadata` flag
- stops predicating the dedup pass on `--disable-opt`, which allows us to disable optimization and run the dedup pass.
- restores the original intent of the test in `chirrtl.fir`, which was to make sure that optimizations were not affecting enable inferrence of CHIRRTL read ports.

[firtool] Remove many unsued CL options

---

lib/Dialect/HW/HWDialect.cpp
test/Dialect/HW/inline.mlir

This PR adds the following ops to the list of inlinable ops in the HW dialect:
- `AggregateConstantOp`
- `EnumConstantOp`
- `StructExplodeOp`
- `StructExtractOp`
~~(I was unsure whether `ParamValueOp` should be inlinable as well.)~~ I think `ParamValueOp` doesn't make sense outside of an `hw.module` op, so I didn't include it here.

[HW] Allow inlining of all constant and aggregate ops.

---

lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp

This fixes nondeterminism caused by iteration over DenseMap. Instead use MapVector to guarantee determinism.

Backport "[ExtractInstances] Fix nondeterminism with MapVector. (#4749)" to sifive 1.5

---

lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp

This fixes nondeterminism caused by iteration over DenseMap. Instead use MapVector to guarantee determinism.

Backport "[ExtractInstances] Fix nondeterminism with MapVector. (#4749)" to SiFive 1.22

---

include/circt/Dialect/HW/CustomDirectiveImpl.h
include/circt/Dialect/SV/SVExpressions.td
include/circt/Dialect/SV/SVInOutOps.td
include/circt/Dialect/SV/SVTypeDecl.td
include/circt/Dialect/SystemC/SystemCStructure.td
include/circt/Support/CustomDirectiveImpl.h
lib/Dialect/SV/SVOps.cpp
lib/Dialect/SystemC/CMakeLists.txt
lib/Dialect/SystemC/SystemCOps.cpp
lib/Support/CustomDirectiveImpl.cpp
test/Conversion/ExportVerilog/name-legalize.mlir
test/Conversion/ExportVerilog/pretty.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir
test/Conversion/ExportVerilog/sv-interfaces.mlir
test/Dialect/HW/basic.mlir
test/Dialect/SV/basic.mlir
test/Dialect/SV/errors.mlir
test/Dialect/SystemC/structure.mlir

Move the `{parse,print}ImplicitSSAName` directive currently used by the SystemC dialect into the support library and make the SV dialect use it as well. This directive works on a `StringAttr` instead of the entire attribute dictionary of the operation, which has a few advantages:
- Name is an explicit ODS attribute on the operation
- Name gets automatically elided in attr-dict printing (TableGen elides all ODS-defined attributes)
- The fact that the "name" attribute has a specific meaning is exposed in ODS more explicitly, and the assembly format makes this more apparent by having a dedicated `name <ATTR>` portion.
NFC besides the change in assembly format.

[Support] Add `ImplicitSSAName` directive for string attributes

---

include/circt/Dialect/HW/HWMiscOps.td
include/circt/Dialect/HW/HWOps.h
include/circt/Support/BuilderUtils.h
lib/Conversion/CalyxToHW/CalyxToHW.cpp
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/LegalizeNames.cpp
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
lib/Dialect/HW/CMakeLists.txt
lib/Dialect/HW/HWOps.cpp
test/Dialect/HW/basic.mlir
test/Dialect/HW/canonicalization.mlir

Add the `hw.wire` operation to the HW dialect. A wire offers the ability to assign a human-readable name or an inner symbol to an edge in the SSA graph, for human consumption or remote references through a symbol.
This fills a representational gap where language frontends like FIRRTL have to resort to `sv.wire` if they need any of the naming or symbol reference capabilities of a wire, but in doing so they also have to buy into the SV-specific quirks and connect semantics of `sv.wire`, which are annoying to analyze. Almost all uses in FIRRTL don't care about the connect semantics though. The new `hw.wire` op allows for expressing a wire without the connect semantics, leveraging the graph-ness of the HW dialect, which makes analysis a lot easier and will allow frontends to significantly …

[HW] Add hw.wire operation

---

lib/Conversion/ExportVerilog/LegalizeNames.cpp
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/prepare-for-emission.mlir
test/Conversion/ExportVerilog/verilog-basic.mlir

Add support for the new `hw.wire` op to ExportVerilog. More specifically this commit makes LegalizeNames consider `hw.wire` during name legalization, and it adds a lowering from `hw.wire` to `sv.wire` to the PrepareForEmission pre-pass. The rationale behind implementing HW wire emission as a lowering in the pre-pass instead of direct support in ExportVerilog is that it makes finding a location for the wire declaration and its assignment an IR problem instead of something done ad-hoc during emission, which makes it a lot easier to solve because we can reason about order based on the ops instead of text snippets.

[ExportVerilog] Add hw.wire emission support

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/firtool/name-preservation.fir

Lower `firrtl.node` ops to the new `hw.wire` which is pretty much a one-to-one lowering.

[FIRRTLToHW] Lower FIRRTL node to HW wire

---

include/circt/Dialect/Arc/Passes.h
include/circt/Dialect/Arc/Passes.td
lib/Dialect/Arc/Transforms/CMakeLists.txt
lib/Dialect/Arc/Transforms/SplitLoops.cpp
test/Dialect/Arc/split-loops-errors.mlir
test/Dialect/Arc/split-loops.mlir
tools/arcilator/arcilator.cpp

Add the `SplitLoops` pass which splits arcs with multiple results into arcs with just one result. This is intended to break "false" loops among `arc.state` ops. Grouping combinational ops into arcs may introduce loops between the arcs even though the combinational ops had no loops themselves. Ideally we'd be more clever about the splitting and only separate the arc outputs that actually cause these loops, implementing this is a bit more involved than the current solution though. Reducing arcs to one output suffices for now.

[Arc] Add loop splitting pass

---

include/circt/Dialect/Arc/Passes.h
include/circt/Dialect/Arc/Passes.td
lib/Dialect/Arc/Transforms/CMakeLists.txt
lib/Dialect/Arc/Transforms/SinkInputs.cpp
test/Dialect/Arc/sink-inputs.mlir
tools/arcilator/arcilator.cpp

Add the `SinkInputs` pass which sinks constants into arc definitions where possible. The arc conversion pass keeps constants out of arcs to increase the chance of discovering arcs that only differ by constant values, at the cost of additional arc arguments. The `SinkInputs` pass is intended to run after deduplication, to simplify arc inputs that are set to the same constant at all arc call sites.

[Arc] Add constant sinking pass

---

include/circt/Dialect/Arc/Arc.td
include/circt/Dialect/Arc/Dialect.td
include/circt/Dialect/Arc/Ops.h
include/circt/Dialect/Arc/Ops.td
include/circt/Dialect/Arc/Passes.h
include/circt/Dialect/Arc/Passes.td
include/circt/Dialect/Arc/Types.h
include/circt/Dialect/Arc/Types.td
lib/Conversion/ConvertToArcs/ConvertToArcs.cpp
lib/Dialect/Arc/CMakeLists.txt
lib/Dialect/Arc/Dialect.cpp
lib/Dialect/Arc/Ops.cpp
lib/Dialect/Arc/Transforms/CMakeLists.txt
lib/Dialect/Arc/Transforms/InferMemories.cpp
lib/Dialect/Arc/Transforms/PassDetails.h
lib/Dialect/Arc/Transforms/StripSV.cpp
lib/Dialect/Arc/Types.cpp
test/Dialect/Arc/infer-memories.mlir
test/Dialect/Arc/strip-sv.mlir
tools/arcilator/arcilator.cpp

Many CIRCT frontends don't generate clean HW representations of their inputs, but instead intersperse SV dialect operations to explicitly materialize named wires. Add a makeshift `StripSV` pass to remove some of the trivial SV dialect ops (wires just for the sake of naming) and to replace `seq.firreg` with `seq.compreg` throughout the input. At a later point we'll want to introduce a "register" op interface such that passes can inquire about a register op's semantics in a uniform manner.
Similarly, the Seq dialect lacks a memory construct. The FIRRTL pipeline lowers its `firrtl.mem` ops into HW generator ops. Add a `InferMemories` pass that converts this generator op into a proper `arc.memory` op with associated `arc.memory_read` and `arc.memory_write` operations.
**Do a rebase merge, not …

[Arc] Add makeshift input preprocessing

---

include/circt/Dialect/Arc/Passes.h
include/circt/Dialect/Arc/Passes.td
lib/Dialect/Arc/Transforms/CMakeLists.txt
lib/Dialect/Arc/Transforms/SimplifyVariadicOps.cpp
test/Dialect/Arc/simplify-variadic-ops.mlir

Add the `SimplifyVariadicOps` pass which takes the common combinational operations and converts them from their variadic representation into a chain of binary operations. The pass reorders the variadic operands such that they appear in the order in which their definitions appear in the basic block. The binary operations are then inserted as soon as both their operands become available. This distributes the operations through the block and reduces the lifetimes of the original op's operands.

[Arc] Add variadic op simplification pass

---

include/circt/Dialect/Arc/Passes.h
include/circt/Dialect/Arc/Passes.td
lib/Dialect/Arc/Transforms/CMakeLists.txt
lib/Dialect/Arc/Transforms/RemoveUnusedArcArguments.cpp
test/Dialect/Arc/remove-unused-arc-arguments.mlir
tools/arcilator/arcilator.cpp

Add the `RemoveUnusedArcArguments` pass that does exactly what it says.

[Arc] Add pass to remove unused arc arguments

---

include/circt/Dialect/Arc/Ops.td
include/circt/Dialect/Arc/Passes.h
include/circt/Dialect/Arc/Passes.td
lib/Dialect/Arc/Ops.cpp
lib/Dialect/Arc/Transforms/CMakeLists.txt
lib/Dialect/Arc/Transforms/LowerLUT.cpp
test/Dialect/Arc/basic-error.mlir
test/Dialect/Arc/basic.mlir
test/Dialect/Arc/lower-lut.mlir

Add the `arc.lut` op which groups combinational ops in its body for later conversion into a simple lookup table. Also add the `LowerLUT` pass, which precomputes that lookup table and converts `arc.lut` into a pure Comb and HW dialect representation.

[Arc] Add lookup table op and lowering pass

---

include/circt/Dialect/Arc/Passes.h
include/circt/Dialect/Arc/Passes.td
lib/Dialect/Arc/Transforms/CMakeLists.txt
lib/Dialect/Arc/Transforms/InlineArcs.cpp
test/Dialect/Arc/inline-arcs.mlir

Add a pass that inlines all arcs with only one use or with a trivial number of operations in the body (<=3). This provides quite a bit of speed-up (~14%) and a significant reduction of stack ops (4.7x) in some initial experiments

[Arc] Add simple arc inlining pass

---

include/circt/Dialect/FIRRTL/FIRRTLStructure.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp

Don't ignore parameters builder argument, add support for specifying internalPaths during building (as they're documented as required for ref-type ports on extmodules).
Effectively NFC.

[FIRRTL] F{Ext,Int}Module: build with parameters, internalPaths.

---

include/circt/Dialect/Arc/Ops.td
include/circt/Dialect/Arc/Passes.h
include/circt/Dialect/Arc/Passes.td
lib/Dialect/Arc/Transforms/AddTaps.cpp
lib/Dialect/Arc/Transforms/CMakeLists.txt
test/Dialect/Arc/add-taps.mlir
tools/arcilator/arcilator.cpp

Add an `arc.tap` operation that allows us to assign a name to an arbitrary SSA value such that it remains observable after any subsequent transformations. Also add an `AddTaps` pass which adds an `arc.tap` op to every module port and every wire, making them observable even after transformations have completely flattened the original hierarchy.

[Arc] Add tap op to observe ports/wires and AddTaps pass

---

include/circt/Conversion/SCFToCalyx.h
integration_test/Dialect/Calyx/custom_port_name.mlir
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp

If `func::FuncOP` argument attributes/results have the `"calyx.port_name"` Attribute, use it to set `calyx::PortInfo` port name.
With this, the port name gets propagated all the way down to Verilog.
Before:
```verilog
module f0(
input  [63:0] in0,
input  [31:0] in1,
input  [31:0] in2,
...
```
After:
```verilog
module f0(
input  [63:0] b0_host,
input  [31:0] b0_dimensions,
input  [31:0] b0_dim_0_min,
...
```

[SCFToCalyx] Read "calyx.port_name" Attribute from FuncOp arguments/results

---

lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp
test/Dialect/FIRRTL/check-comb-cycles.mlir

* Fixup cases with trailing or leading arrows.
* Fix printing starting value twice, misrepresenting cycle (#4781).
* Walk cycle until a name is found and start from there, improving diagnostic and ensuring the begin/end are named.
* If nothing can be named, say so explicitly instead empty path and emit note pointing to add location for starting val.
* Avoid printing module name for every named signal
* mymodule.a <- mymodule.b.c <- mymodule.d is now: mymodule.{a <- b.c <- d} They always start with same module name, compress a bit.
* Use '...' to describe paths not named, only once until next name.
A future improvement would be to improve printing names for values that alias a number of sources-- presently we (non-deterministically) pick the first of the computed alias set, this could be …

[FIRRTL][CheckCombLoops] Improve loop reporting diagnostics.

---

lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
test/Dialect/SV/hw-memsim.mlir

If the read latency is 1, Vivado issues a warning since the behaviour under a collision is undefined. This change forces write_first behaviour by adding the appropriate annotation.

[HWMemSimSimpl] Add rw_addr_collision = yes to memories with registered read addresses

---

tools/circt-reduce/Reduction.cpp
tools/circt-reduce/circt-reduce.cpp

Fix a source of crash in `circt-reduce` where the tool would try to apply a reduction to a parent operation *and* some of its nested child operations at the same time. Add a set to keep track of which operations were already affected by a reduction on their parent, and skip those.
Also fix poor scaling behaviour in `computeTransitiveModuleSize` which made the FIRRTL module externalizer and instance stubber very slow. The new simplified implementation doesn't produce reduction estimates as accurately, but it is a lot faster and seems sufficient in most cases.
Implements parts of #4100.

[reduce] Fix crash on nested ops; fix poor scaling of module op counting

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
lib/Conversion/PipelineToCalyx/PipelineToCalyx.cpp
lib/Conversion/PipelineToHW/PipelineToHW.cpp
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/InferResets.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/VBToBV.cpp
lib/Dialect/HW/Transforms/HWSpecialize.cpp
lib/Dialect/Handshake/HandshakeOps.cpp
lib/Dialect/Handshake/Transforms/PassHelpers.cpp
lib/Dialect/Interop/InteropOps.cpp
lib/Dialect/Pipeline/Transforms/ExplicitRegs.cpp
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
tools/circt-reduce/Reduction.cpp

Replace `auto &it : llvm::enumerate(...)` with `auto it : llvm::enumerate(...)` in preparation for this llvm change https://github.com/llvm/llvm-project/commit/a0a76804c4b56058ba3dcd7374bcaec2fec3978e. Based on the suggestions from this commit https://github.com/llvm/llvm-project/commit/8c258fda1f9b33fc847cfff9c2ee33ce4615ff0b

Do not use non-const lvalue-refs with enumerate

---

docs/VerilogGeneration.md

This PR adds a section `Recommended LoweringOptions by Target` to verilog generation doc.
As Chisel upstream officially switched to use MFC, there will be more new users to try CIRCT and
it would be nice to describe the list of lowering options categorized by targets.

[Docs] Add recommended LoweringOptions by target

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Conversion/ExportVerilog/name-legalize.mlir
test/Conversion/ExportVerilog/no-wrap.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir

Implement https://github.com/llvm/circt/issues/4156. Maybe this could be problematic in some tools but VCS and Verilator are fine with this style. Spec seems OK with this style too: SV Spec 23.3.2.2
w/ PR:
```verilog
module Foo(
output a
);
Bar bar (
.a (a),
.b (/* unused */)
);
endmodule
```
w/o PR:
```verilog
module Foo(
output a
);
wire _bar_b;
Bar bar (
.a (a),
.b (_bar_b)
);
endmodule
```

[ExportVerilog] Remove unused output port wires

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

This is simple and only considers identity on mux conditions.  A more complete solution would look for complex conditions which are guaranteed by the mux cond assumption.
closes #4871

[FIRRTL] prune duplicate conditions from mux trees

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Rearrange constants in concatination strings to enable constant merging.
bypass double inversions.

[FIRRTL] Merge constants in concatinations and drop double inversion

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Add canonicalizers for `SubfieldOp`, `SubindexOp`, and `SubaccessOp` on an `InvalidValueOp` input, replacing the subaccess with an `InvalidValueOp` of the field type.

[FIRRTL] Add canonicalizers for subaccesses on invalid values

---

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp

While chasing different bug, noticed this code does not handle annotations on the modules themselves, and updates the port annotations for every operation in the module that has any annotations, fix.

[FIRRTL][ModuleInliner] Update anno's on mod's, update ports 1x.

---

lib/Conversion/CalyxToHW/CalyxToHW.cpp
test/Conversion/CalyxToHW/basic.mlir
test/Conversion/CalyxToHW/primitives.mlir
test/Dialect/Calyx/errors.mlir

According to the Calyx [specification](https://docs.calyxir.org/lang/ref.html#guards), guarded assignments to the same destination will not be driven simultaneously.
Therefore, the following Calyx IR is valid:
```llvm
calyx.assign %out = %cond0 ? %val0 : i32
calyx.assign %out = %cond1 ? %val1 : i32
```
This can happen when there is more than one calyx group assigning to the same destination.
Support this by creating a chain of `comb::MuxOp`.
When none of the guards are active, assign 0s to the destination.
This will allow other passes down to HW, and also the synthesizer, to perform optimizations on the mux chain.
Also use `seq::CompRegClockEnabledOp` instead of `seq::CompRegOp` to store the value of the register when converting a `calyx.register`, with the `clockEn` signal driven by the …

[CalyxToHW] Support multiple guarded assigns to the same destination

---

include/circt/Dialect/Arc/Ops.td
include/circt/Dialect/Arc/Passes.h
include/circt/Dialect/Arc/Passes.td
include/circt/Dialect/Arc/Types.td
lib/Dialect/Arc/Ops.cpp
lib/Dialect/Arc/Transforms/CMakeLists.txt
lib/Dialect/Arc/Transforms/LowerState.cpp
test/Dialect/Arc/basic-errors.mlir
test/Dialect/Arc/lower-state.mlir
test/arcilator/arcilator.mlir
tools/arcilator/arcilator.cpp

Add the `LowerState` pass and accompanying operations to convert a design from a pure state transfer graph composed of arcs to a more procedural read-modify-write representation. After this transformation the design is a significant step down the path of becoming a software model.
The `LowerState` pass proceeds as follows:
- Group all `arc.state` ops according to their clock into `arc.clock_tree`s. Operations that are on direct input-to-output passthrough or on state-to-output paths are grouped into a `arc.passthrough` op.
- Introduce an explicit state storage allocation op for every state op, memory op, as well as every input and output port of the root module.
- Replace the root `hw.module` with a `arc.model` which no longer has any input and output ports, but a storage pointer argument …

[Arc] Add state lowering pass

---

.github/workflows/uploadFirrtlBinaries.yml

This changes workflow "Upload Binaries" to "Upload Firtool Binaries" which substantially reduces the size of the binary distribution. There may be other things we want to include in distributions or maybe we want multiple binary uploads, but I'm opening this draft PR to get discussion started so we can weigh the benefits.
This reduces the size of the uploaded tarball from ~73 MiB to 3.7 MiB for Ubuntu 18.04 (and similar for the rest), the uncompressed reduction is from 258 MiB to 12 MiB.
Selfishly, as a maintainer of Chisel, I would like to distribute firtool separately since it is the only thing needed by Chisel users, but I am also totally open to finding a better compromise, like possibly having separate firtool and circt distributions.
~Also TODO I want to cache the LLVM build, if we …

Enhance Upload Firtool Binaries

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/SFCTests/data-taps-xmr.fir
test/Dialect/FIRRTL/SFCTests/mem-taps-reg.fir
test/Dialect/FIRRTL/SFCTests/mem-taps.fir

Lower `firrtl.wire` ops to `hw.wire` instead of `sv.wire`. The change is fairly mechanical: instead of creating an `sv.wire` and setting it as the FIRRTL wire's lowering, we create an `hw.wire` with an initial Z value as the lowering. Subsequent connects then pick up the change in `lowerConnect` and replace the Z with updated values accordingly. Subaccesses are also fully supported. The Z value prevails if the connects don't fully assign the entire wire.
The bulk of changes in the tests are just replacing `sv.wire` and the corresponding `sv.assign` with just the `hw.wire`. A few new tests also specifically check for subaccess connects to wires.

[FIRRTLToHW] Lower FIRRTL wires to HW wires

---

.github/workflows/uploadFirrtlBinaries.yml
.github/workflows/uploadFirrtlReleaseArtifacts.yml

While GitHub does provide source bundles, those bundles don't include LLVM and thus cannot be used for building from source.
My current use case for this is to build an `aarch64` firtool for use on M1 macs (for example, using the dev container [here](https://github.com/chipsalliance/chisel/blob/5be1fbc0e319ffc939b2cb64fb460e1b416d7e64/.devcontainer/Dockerfile#L63-L73)). Currently, GitHub doesn't seem to offer `aarch64` runners to build a release binary. As a workaround for my devcontainer, I do a `git` checkout which takes a really long time to clone `llvm`. Grabbing a packaged bundle of sources will make this much faster.

Upload full sources with release

---

include/circt/Dialect/Arc/Ops.td
include/circt/Dialect/Arc/Passes.h
include/circt/Dialect/Arc/Passes.td
lib/Dialect/Arc/Transforms/AllocateState.cpp
lib/Dialect/Arc/Transforms/CMakeLists.txt
lib/Dialect/Arc/Transforms/LegalizeStateUpdate.cpp
lib/Dialect/Arc/Transforms/PrintStateInfo.cpp
test/Dialect/Arc/allocate-state.mlir
test/Dialect/Arc/basic.mlir
test/Dialect/Arc/legalize-state-update.mlir
test/Dialect/Arc/print-state-info-errors.mlir
test/Dialect/Arc/print-state-info.mlir
test/arcilator/arcilator.mlir
tools/arcilator/arcilator.cpp

Add three passes that implement state allocation. The passes take the abstract state allocation ops, compute a memory layout for the overall state of the model, and replace the allocation ops with simple pointer getter ops that access the allocated piece of memory. The passes operate as follows:
- `LegalizeStateUpdate` detects read-after-write hazards and introduces temporary storage locations that allow the read and write ops to occur without infringing on each other.
- `AllocateState` computes the overall memory layout and replaces allocation ops with simple accessor ops.
- `PrintStateInfo` emits the memory layout as a JSON file. This allows other tools to reason about the exact memory layout of the design.
State update legalization is still lacking proper handling of memory reads and …

[Arc] Add state allocation passes

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/InferResets.cpp
test/Dialect/FIRRTL/infer-resets.mlir
test/Dialect/FIRRTL/ref.mlir

Per Reference Types FIRRTL proposal.
Primarily loosening the restriction, this is only really reachable AFAIK via GCT (see #4815 which builds on this).

 [FIRRTL] RefSendOp: support non-passive input, return ref-of-passive

---

include/circt/Dialect/Arc/Passes.td
lib/Dialect/Arc/Transforms/LowerState.cpp
test/Dialect/Arc/lower-state.mlir

Simple implementation to support resets as a foundation for optimizations (e.g., group states with the same reset into one if-statement).

[Arc] LowerState: support enable and reset operands

---

include/circt/Dialect/Arc/Ops.td
lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp
lib/Dialect/Arc/Ops.cpp
lib/Dialect/Arc/Transforms/SinkInputs.cpp
test/Conversion/ArcToLLVM/lower-arc-to-llvm.mlir
test/Dialect/Arc/basic-errors.mlir
test/Dialect/Arc/basic.mlir
test/Dialect/Arc/sink-inputs.mlir

Add a call operation that can only call arcs (`arc.define`) and is thus pure, i.e., it can be used inside an `arc.define`. Otherwise, the semantics are the same as for `arc.state` with latency 0. Going forward, there are 3 options for latency 0 state ops:
1. Only allow `arc.call` inside `arc.define` and use `arc.state lat 0` in HWModules such that there is support for changing the latency in for passes that want to do so (otherwise an `arc.call` has to be changed to a `arc.state`, which is also not a big overhead)
2. Add a canonicalizer to convert `arc.state lat 0` to `arc.call`, i.e., both are allowed in HWModules. This probably complicates the IR more than it benefits it.
3. Verify `arc.state` to have a latency > 0. I.e., `arc.call` is the only way to call an arc with latency 0.

[Arc] Add pure CallOp

---

include/circt/Dialect/FIRRTL/FIRRTLUtils.h
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/InferResets.cpp

Use to simplify some cast chains involving getBaseType.

[FIRRTLUtils] Add more getBaseType helpers to reduce boilerplate.

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/parse-errors.fir

These are now supported as of #4801.
Add basic parse test, drop negative test.

[FIRRTL] Don't reject probes of non-passive.

---

lib/Dialect/Calyx/Export/CalyxEmitter.cpp

Before the pass was ignoring when I gave ports the attribute `{calyx.stable = true}`, so this commit allows `@stable` to be emitted.
Are there any others missing attributes that should be added @rachitnigam ?

[ToCalyxTranslation] Add 'stable' port attribute in translation

---

lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Dialect/Seq/firreg.mlir

This PR fixes two issues:
* Async reset registers are not initialized with "disable-register-randomization": https://github.com/llvm/circt/issues/4835
* Remove `RANDOMIZE` ifdef guard around async register initialization
Close #4835.

[LowerSeqToSV] Tweak register initialization

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Add folders for aggregate create operations: 
```
vector_create(%foo[0], %foo[1]) -> %foo : vec<uint<2>, 2>
bundle_create(%foo["a"], %foo["b"]) -> %foo : bundle<a:uint<1>, b:uint<1>>
```

[FIRRTL] Add folders for bundle/vector create

---

lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp
test/Dialect/FIRRTL/inject-dut-hierarchy.mlir

[FIRRTL][InjectDUT] Fix w/references, use emitConnect.

---

docs/Dialects/FIRRTL/FIRRTLAnnotations.md
include/circt/Dialect/FIRRTL/AnnotationDetails.h
include/circt/Dialect/FIRRTL/FIRParser.h
include/circt/Dialect/FIRRTL/FIRRTLEnums.td
include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
include/circt/Dialect/FIRRTL/FIRRTLStructure.td
include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp
lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/annotations.mlir
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/lower-types-aggregate.mlir
test/firtool/convention.fir
tools/circt-reduce/Reduction.cpp
tools/firtool/firtool.cpp
tools/hlstool/hlstool.cpp

The convention attribute give us module-by-module control over how a module's ports should be lowered. When a module uses the "scalarized" convention, its ports are guaranteed be fully scalarized in the output verilog. When a module uses the "internal" convention, then it's ports will be lowered according to the configured aggregate preservation mode.
A module's convention is internal by default, but can be set using a new annotation, or through the firtool command line options `--scalarize-top-module` and `--scalarize-ext-modules`.
Enabling both `--scalarize-top-module` and `--scalarize-ext-modules` together (which is the default) should be a drop-in replacement of the older `--preserve-public-types` option, which has been removed.
- FIRRTL Dialect
- add new `convention` attribute to …

[FIRRTL] Add a convention attribute to modules

---

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code.mlir

We previously extracted instances that only feed the test code. This change enhances that logic to also extract instances that may feed other instances, which transitively only feed the test code. This also works for instances that potentially feed each other, cyclicly, and otherwise only feed the test code.

[ETC] Enhance instance extraction to extract dependent instances.

---

tools/firtool/firtool.cpp

This reduces entire execution time by 2~3%.

[firtool] Move 1st DropName to after CSE. Delete 2nd DropName pass.

---

include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
include/circt/Dialect/FIRRTL/FIRRTLUtils.h
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
test/Dialect/FIRRTL/SFCTests/data-taps-flip.fir
test/Dialect/FIRRTL/annotations.mlir
test/Dialect/FIRRTL/dedup-errors.mlir
test/Dialect/FIRRTL/dedup.mlir
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/expand-whens-errors.mlir
test/Dialect/FIRRTL/expand-whens.mlir
test/Dialect/FIRRTL/grand-central-errors.mlir
test/Dialect/FIRRTL/grand-central.mlir
test/Dialect/FIRRTL/imconstprop.mlir
test/Dialect/FIRRTL/imdce-nyi.mlir
test/Dialect/FIRRTL/imdce.mlir
test/Dialect/FIRRTL/infer-resets-errors.mlir
test/Dialect/FIRRTL/infer-resets.mlir
test/Dialect/FIRRTL/infer-widths.mlir
test/Dialect/FIRRTL/inferRW.mlir
test/Dialect/FIRRTL/inliner-nyi.mlir
test/Dialect/FIRRTL/inliner.mlir
test/Dialect/FIRRTL/lower-chirrtl.mlir
test/Dialect/FIRRTL/lower-types.mlir
test/Dialect/FIRRTL/lowerXMR-errors.mlir
test/Dialect/FIRRTL/lowerXMR.mlir
test/Dialect/FIRRTL/mem-to-reg-of-vec.mlir
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/ref.mlir
test/Dialect/FIRRTL/vb-to-bv.mlir

On the path to supporting forcing declarations, we want to be able to differentiate whether a reference is read-only or if it can be used with forcing.
To this end, extend `firrtl.ref` with a bit indicating the reference kind.
Default kind is `probe` which is basically what `firrtl.ref` is for today: read-only view of the data, and produced by `ref.send`.
Nothing presently will create the forceable (rwprobe) variant yet.

[FIRRTL] Split firrtl.ref into firrtl.probe, firrtl.rwprobe .

---

include/circt/Scheduling/Algorithms.h
lib/Scheduling/SimplexSchedulers.cpp
test/Scheduling/modulo-simplex-errors.mlir

Validate that the given `lastOp` is the unique sink node in the dependence graph.
Fixes #4785.

[Scheduling][ModuloSimplexScheduler] Improve `lastOp` validation.

---

lib/Dialect/HW/InnerSymbolTable.cpp

A line is printed for every encountered symbol + its target, often from IST's constructed in parallel producing a lot of essentially unreadable debug information that rarely is useful.
Given IST's use in verification, this also means `-debug` quickly becomes very noisy (between passes or when printing IR).
Drop for now, can add a dump() and/or PrintISTPass in the future.

[HW][IST] Drop debug printing from InnerSymbolTable.

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/dedup.mlir

When we determine if two modules can be merged we ignore the names of fields in bundle types.  When we merge two modules with different bundle field names, this results in the type of instance results changing.  We used to run a procedure to fix up subfield and connect operations on instance results, but this missed some other operations which work with bundle types. We now convert from the new type back to the old type using an intermediate wire.

[FIRRTL][Dedup] Change port renaming strategy

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/parse-errors.fir

Went back and forth on this in spec.
Let's allow it, to support unused references or to resolve the reference after parsing.

[FIRRTL][FIRParser] Relax 'ref' statement requirement.

---

lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp
test/Dialect/FIRRTL/annotations-errors.mlir

Annotations on references don't have defined behavior, and pose problems beyond that.
Reject if found to be the target of an annotation.
Add tests for annotation target instance port that doesn't exist,
instance port of reference type, and directly ref type port.

[FIRRTL] Do not consider references valid annotation targets.

---

tools/arcilator/CMakeLists.txt
tools/arcilator/arcilator-header-cpp.py
tools/arcilator/arcilator-runtime.h

Add utilities to allow C++ to link against and drive a software model generated from the arc dialect.
The `arcilator-header-cpp.py` utility accepts the state JSON file generated by the `PrintStateInfo` pass and converts it into a C++ header that makes the lowered LLVM model feel close to Verilator output. The mapping is not perfect: there is no `eval` function, but dedicated clock and passthrough functions to be called instead. The commonalities of the generated C++ header are collected in `arcilator-runtime.h`.
The utilities and headers aren't installed yet properly.

[Arc] Add simple runtime helpers

---

include/circt/Dialect/Arc/Ops.td
lib/Dialect/Arc/Ops.cpp
test/Dialect/Arc/basic-errors.mlir
test/Dialect/Arc/basic.mlir
test/Dialect/Arc/canonicalizers.mlir

The `arc.clock_domain` operation is a dataflow equivalent of the `arc.clock_tree` operation. It is useful to isolate clocks before lowering state where the region still has to be a graph and arbitrary outputs have to be supported. Several transformations will benefit from an earlier isolation of clocks as they can often only be applied within a single clock domain (e.g., cannot pack differently clocked arcs inside the same vector for vectorization) and, as a result, don't have to check the clock operand manually anymore.
The plan is to implement the clock isolation transformation that is now part of LowerState as a separate pass on the dataflow representation and then let LowerState only lower the clock domains to the corresponding control flow based constructs. The plan is also to adjust …

[Arc] Add clock_domain operation

---

include/circt/Dialect/FIRRTL/FIRRTLAttributes.td
include/circt/Dialect/FIRRTL/FIRRTLOps.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp

No need to carry `BoolAttr`s in `MemoryInitAttr`. Replace them with plain old booleans.

[FIRRTL] Replace BoolAttr with bool in MemoryInitAttr; NFC

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
lib/Dialect/FIRRTL/Export/FIREmitter.cpp
lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp
lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/FIRRTL/Transforms/FlattenMemory.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
lib/Dialect/FIRRTL/Transforms/InferReadWrite.cpp
lib/Dialect/FIRRTL/Transforms/InferResets.cpp
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
lib/Dialect/FIRRTL/Transforms/LowerIntrinsics.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
lib/Dialect/FIRRTL/Transforms/MemToRegOfVec.cpp
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
lib/Dialect/FIRRTL/Transforms/RegisterOptimizer.cpp
lib/Dialect/FIRRTL/Transforms/RemoveUnusedPorts.cpp
tools/circt-reduce/Reduction.cpp

Be explicit about the result used, instead of implicit conversion to Value for single-result declarations.
In preparation for making these optionally have more than one result.

[FIRRTL][NFC] Use getResult() for primary Value of declaration ops.

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp

Easier to build, let result type inference handle. Works better when inference computes type of other results.

[FIRRTL][NFC] NodeOp: don't require type, get from input.

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h
include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/InferResets.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/RegisterOptimizer.cpp
lib/Dialect/FIRRTL/Transforms/SFCCompat.cpp
test/Dialect/FIRRTL/canonicalization.mlir
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/infer-resets.mlir
test/Dialect/FIRRTL/ref.mlir

Add ability to get rwprobe references as optional result on supported FIRRTL declarations.
Declarations also track whether they're "forceable" for inspection in analyses/transforms/canonicalizers.
These are not yet produced outside manually crafted IR.
Pass-specific support added separately.

[FIRRTL] Add optional forceable ref result to FIRRTL decls.

---

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
test/Dialect/FIRRTL/inliner.mlir

This fixes a bug with updating the NLA, when modules are recursively inlined to a single parent.
The NLA was being  updated with respect to a temporary and stale parent, the `retop` must be
called with the original parent.
Fixes #4920, #4915

[ModuleInliner] Retop with correct recursive parent

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h
include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Add canonicalizer to forceable declarations demoting to non-forceable if rwprobe ref result is unused.
Add method to `Forceable` for rewriting the op to add/remove forceability.

[FIRRTL][FIRRTLFolds] Drop forceable if unused.

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/HW/HWOpInterfaces.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/HW/HWOpInterfaces.cpp
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/test.mlir

* Which result, if any, do inner symbols target?
* Are per-field symbols sensible for this operation kind?
No longer need to know this information in the verifier or passes, query through the interface.
Fixes per-field inner symbol support on forceable declarations.
Fixes #4873 .

[HW][FIRRTL] Let ops specify inner symbol behavior.

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h
include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp

Drop interface method for this until a good design there is found.
Not using the rewriter may cause crashes or other behavior, so fixing this for now
and can find how/if to put this back on the Forceable interface in the future.

[FIRRTL] Fix replaceWithNewForceability to use PatternRewriter.

---

include/circt/Dialect/SV/SVStatements.td
include/circt/Dialect/SV/SVVisitors.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/LegalizeNames.cpp
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
lib/Dialect/SV/SVOps.cpp
lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir
test/Dialect/SV/hw-memsim.mlir
test/Dialect/Seq/firreg.mlir
test/firtool/register-randomization.fir

This introduces SV for operation e.g:
```mlir
sv.for %i = %c0_i2 to %c-1_i2 step %c1_i2 : i2 {
%RANDOM = sv.macro.ref.se< "RANDOM"> : i32
%index = sv.array_index_inout %_RANDOM[%i] : !hw.inout<uarray<3xi32>>, i2
sv.bpassign %index, %RANDOM : i32
}
```
which corresponds to:
```verilog
for (logic [1:0] i = 2'h0; i < 2'h3; i = i + 2'h1) begin
_RANDOM[i] = `RANDOM;
end
```
For the simplicity, sv.for has single induction block argument (`%i` in the example above). This PR changes HWMemSimImp and LowerSeqToSV to replace verbatim for loop with sv.for operation.

[SV] Introduce SV for op

---

integration_test/Dialect/Handshake/sync_backedge/sync_backedge.mlir

Fixes an integration test failure introduced in https://github.com/llvm/circt/pull/4929

[handshake] Fix cmerge integration test

---

lib/Dialect/FIRRTL/Transforms/InferResets.cpp
test/Dialect/FIRRTL/infer-resets.mlir

Be sure forceable references are considered.
May not reject designs that should (inference fails w/o refs), but start by being sure valid designs work.

[FIRRTL][InferResets] Infer through forceable ref.

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR.mlir

Support read of a rwprobe, add test.

[FIRRTL][LowerXMR] Treat forceable ref result as ref origin.

---

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp
test/Dialect/FIRRTL/expand-whens.mlir

These operations work like the other "verification" statements (assert/assume/cover), and the "when" conditions containing them should be mixed into their predicate operand.

[FIRRTL][ExpandWhens] And in conditions to force*/release* ops.

---

lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

Still reject this in the input, but as long as we require fully splitting up references we need a way to (temporarily) represent a sub-element of a `rwprobe`.
Allow this for now.
This is okay as long as the entire reference "chain" is "lowered"/expanded.

[FIRRTL] Allow ref.sub of rwprobe while allowing LowerTypes of forceables.

---

lib/Dialect/FIRRTL/FIRRTLTypes.cpp
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

Until we can control enum width in HW, we use an integer tag for complex enums.  We do not use tagged unions as verilog tool support for them is beyond atrocious.

[FIRRTL] Lower complex enum to hw

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR.mlir

Presently, we replace ref.resolve's with `sv.xmr.ref` operations that are cast to the referenced FIRRTL type.
Add support for force/release in a similar manner.
For force/release, don't replace but keep these around for lowering to HW in LowerToHW (#4992).  Instead, replace the "destination" reference operand similarly with a `sv.xmr.ref` cast to the reference (rwprobe) type.

[FIRRTL][LowerXMR] force/release handling. 

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-basic.fir

With the IR pieces in place, add parsing support instead of faking it.
* Parse RWProbe into firrtl.rwprobe<T> .
* Add `rwprobe()` support leveraging `Forceable`.
Eagerly create declarations with the rwprobe ref result enabled,
to ensure it's available if it's needed.
Cleanup any declarations not forced (most of them) after parsing.

[FIRRTL][FIRParser] Parse RWProbe<T> and rwprobe().

---

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
test/Dialect/FIRRTL/imdce.mlir

Recently we've changed the modeling of InvalidValueOp to have side-effect so it's necessary to handle invalid values specially.

[FIRRTL][IMDCE] Remove dead Invalid Value op

---

docs/Dialects/HW/RationaleHW.md
include/circt/Dialect/HW/HWTypesImpl.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/FSMToSV/FSMToSV.cpp
lib/Dialect/HW/HWTypes.cpp
test/Conversion/ExportVerilog/hw-typedecls.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir
test/Conversion/FSMToSV/test_basic.mlir
tools/circt-rtl-sim/circt-rtl-sim.py.in

Let hw.enum be defined as a size based on it's contents, rather than implicitly by the verilog default size.

[HW] Size enums to the number of tags

---

include/circt/Dialect/Arc/ArcDialect.td
include/circt/Dialect/Arc/ArcOps.td
lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp
lib/Dialect/Arc/ArcDialect.cpp
lib/Dialect/Arc/ArcFolds.cpp
lib/Dialect/Arc/CMakeLists.txt
lib/Dialect/Arc/Transforms/LowerState.cpp
test/Conversion/ArcToLLVM/lower-arc-to-llvm.mlir
test/Dialect/Arc/basic-errors.mlir
test/Dialect/Arc/basic.mlir
test/Dialect/Arc/canonicalizers.mlir
test/Dialect/Arc/infer-memories.mlir
test/Dialect/Arc/lower-state.mlir

Make the enables of the MemoryReadPortOp, MemoryWritePortOp, and MemoryWriteOp optional. Its absence means a constant true enable. Add folders to remove the operand when it is constant true as well as remove the entire operation when the enable is constant false as the writes do not ever happen in this case and the read returns an undefined value.

[Arc] Memory ops: optional enables and folders

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
lib/Dialect/FIRRTL/FIRRTLTypes.cpp

This operation already has a helper `getFieldName` which returns a `StringRef`, but during lowering to the HW dialect it's helpful to get the value as a `StringAttr`.

[FIRRTL] Add `getFieldNameAttr` helper to SubTagOp

---

lib/Dialect/FIRRTL/FIRRTLUtils.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

The tag field of complex enumerations was being lowered to an integer type, but using a SV enumeration to represent the tag values is a lot cleaner.  Now that enumerations default to using the smallest storage needed, this can be fixed.

[FIRRTL] Lower complex enums to use hw enums for the tag

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

Teach ExportVerilog how to output union types with proper padding. Does not include union operation support. When those are implemented, the field names will be different depending on padding.
Tested with Questa.

[ExportVerilog] Union type output support

---

docs/PyCDE/compiling.md

[PyCDE] [Docs] Mention to add upstream remote to fetch tags when building wheels

---

include/circt/Dialect/Handshake/HandshakeOps.td
lib/Dialect/Handshake/HandshakeOps.cpp
test/Dialect/Handshake/errors.mlir

This commit removes the `InferTypeOpInterface` from `ControlMergeOp` because it no longer made sense w.r.t. the variable type of the index result introduced in #4929. Additionally, when parsing a control_merge with an index type different than `index`, it would raise an error because of the mismatch between the parsed and inferred types. Example code that would trigger it below.
```mlir
handshake.func @test(%arg1: i32, %arg2: i32) {
%result, %index = control_merge %arg1, %arg2 : i32, i64
return
}
```
The commit also adds a custom builder for `ControlMergeOp` (that was previously auto-generated by `InferTypeOpInterface`) to allow creating the operation without explicitly providing return types. The builder defaults to an `Index` type for the op's second result.

[Handshake] Remove cmerge return type inference

---

include/circt/Dialect/Arc/ArcPasses.td
lib/Dialect/Arc/Transforms/StripSV.cpp
test/Dialect/Arc/strip-sv.mlir

* `Comb` and `HW` dialects were not listed as dependent dialects which can lead to a crash when they are built.
* the outputs of instances of external modules are silently replaces with zero values, I think it would be helpful to emit a warning to make it clear to the user that something 'slightly risky' has been done by the compiler
* Also add an option to turn the ext module replacement functionality off as it can be helpful for debugging to see what kind of external modules and instances are used by the design and are still present after module inlining. At some point we want to add proper support for these external modules, e.g., doing blackbox simulation using another simulator via the interop dialect, etc. I guess we also want a proper MLIR operation to represent plusargs at some …

[Arc] StripSV: fix dialect dependencies, option and warning for replacing external module instances

---

lib/Dialect/HW/HWOps.cpp

EnumConstantOp has a declared custom builder in ODS that was never implemented. It is a useful builder, so this commit adds the missing implementation.

[HW] implement missing EnumConstantOp builder

---

include/circt/Dialect/HW/HWMiscOps.td
test/Dialect/HW/basic.mlir

There is currently no way to compare the value of two enumerations as an expression.  There is an `icmp` operation, but it only accepts IntegerTypes, and it would complicate things to allow enums to be used everywhere an integer is allowed.  The other way to compare enumerations is using case statements, but it can't be used as an expression.
This PR adds an equality comparison operator for enumeration types. Theoretically we should be able to support other types of comparisons, such as `<`, since enumeration members are ordered. Since all I care about is equality, this does not support those other kinds of comparisons.  
It would also make sense to me to add a more generic equality operation which could support comparison of structs, unions, and arrays as well as enumerations.
I elected …

[HW] Add an enum comparison operation

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/dedup-errors.mlir

Since Chisel always emits FIRRTL with integer constants encoded in radix 16, it is helpful to report deduplication errors in the same base, as it makes the it easier to compare the error message to the FIRRTL IR.

[FIRRTL][Dedup] Print integer constants as hexadecimal

---

include/circt/Dialect/FIRRTL/FIRRTLStatements.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/test.mlir

This commit adds a match statement operation to the FIRRTL dialect. Match is used as an eliminator for enumeration types.  It enforces exaustive case handling on all enumeration variants.

[FIRRTL] Add `MatchOp` statement

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/test.mlir

This adds an `IsTagOp` which tests the active variant of an enumeration for a specific tag and returns 1 if they match, 0 otherwise.  This op will be used to lower match statements in to a mux-like format.  This op should only be used internally in the compiler, and there are no plans to expose this operation in the FIRRTL frontend language.

[FIRRTL] Add `IsTagOp` to test enumeration variant

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/LowerMatches.cpp
test/Dialect/FIRRTL/lower-matches.fir
tools/firtool/firtool.cpp

The lower matches pass transform match statements into when statements. This allows them to be handled by ExpandWhens, including all the fun things it does such as initialization checking.  When lowering to when statements, the final case handled by the match is transformed in to the "default" branch and the enumeration tag for this case is not explicitly checked anymore.
The new pass was inserted in to the firtool pipeline right before ExpandWhens runs.
To pass flow checking, we needed to handle teach the `foldFlow` function what to do when the block argument belonged to a match statement. Although the flow should always be `source`, it is returning the accumulated flow in case we relax the restriction that enumeration types are always passive.

[FIRRTL] Add LowerMatches pass

---

include/circt/Dialect/Seq/SeqPasses.h
include/circt/Dialect/Seq/SeqPasses.td
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Dialect/Seq/compreg.mlir

`always_ff` blocks do not allow registers to be set in initial blocks. This PR adds an option to emit register assignments from within always blocks to bypass the restriction.

[Seq] Add an option to lower `seq.compreg` to `always` blocks

---

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/FIRRTL/imdce.mlir
test/Dialect/FIRRTL/inliner.mlir
test/Dialect/SV/hw-extract-test-code.mlir

Do backport to 1.34.0
* [IMDCE] Propagate instance livenesss in a context-sensitive way 
* [ETC] Enhance instance extraction to extract dependent instances. (#4910)
* [FIRRTL][IMDCE] Remove dead Invalid Value op (#4996) 
* [ModuleInliner] Rework instance rename code, fix issue as w/PR4882.

Backport to Firtool 1.34.1

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

* Bug that did drop_front and drop_begin, instead of just one.
* Don't crash if operand list is empty.
Also test behavior folding these to aggregateconstantop's.

[FIRRTLFolds] Fix crashes in bundle/vector create folders.

---

include/circt/Dialect/Handshake/HandshakeOps.td
include/circt/Dialect/Handshake/Visitor.h
integration_test/Dialect/Handshake/helper.py
integration_test/Dialect/Handshake/max/max.mlir
lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
lib/Dialect/Handshake/HandshakeOps.cpp
test/Conversion/HandshakeToFIRRTL/test_select.mlir
test/Conversion/HandshakeToHW/test_select.mlir
test/Conversion/StandardToHandshake/arith-ops.mlir

I introduced `handshake.select` back in the day to distinguish it from `handshake.mux`. What i somehow failed to realize is that `handshake.select` has always lowered to a unit-rate actor, which completely removes the need for the operation. The fix all along seems to just lower it to a comb/firrtl mux with unit rate semantics.
Furthermore, looks like there was a bug in the lowerings, wherein the operands of `arith.select` in standard to handshake was being swapped (hence the change in max.mlir, which was actually incorrect before).
Handshake to FIRRTL is... eghh... could have done a "nicer" implementation which factors out the join logic, but i can't be bothered - this pass is supposed to be deprecated, anyways, and i can't wait for the day when it is removed.

[Handshake] Remove handshake.select

---

include/circt/Support/ConversionPatterns.h
lib/Conversion/HWArithToHW/HWArithToHW.cpp
lib/Dialect/ESI/Passes/ESILowerTypes.cpp
lib/Support/CMakeLists.txt
lib/Support/ConversionPatterns.cpp

This `ConversionPattern` is used in two places and is likely generally useful. Move it into the support lib.
Fixes #4899 as a side-effect.

[NFC][Support] Factor out TypeConversionPattern into support lib

---

docs/Dialects/FIRRTL/FIRRTLAnnotations.md
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code.mlir

These don't actually belong in the testbench directory; they are still part of the design. So for now, simply leave them in the directory they were initially declared.

[ETC] Don't relocate instances that were only in extracted test code.

---

docs/Dialects/FIRRTL/FIRRTLAnnotations.md
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code.mlir

These don't actually belong in the testbench directory; they are still part of the design. So for now, simply leave them in the directory they were initially declared.

[ETC] Don't relocate instances that were only in extracted test code (#5064)

---

lib/Dialect/Arc/Transforms/LowerState.cpp
test/Dialect/Arc/lower-state.mlir

Fix the worklist that materializes values in clock trees to do a proper depth-first traversal of the operands, instead of trying to push the operands onto the worklist all at once. Doing the latter would lead to issues where all operands of an operation would be pushed onto the worklist, but then one of those operands might also depend on some of those operands:
%0 = comb.and %x, %y
%1 = comb.or %0, %y
arc.state @foo(%0, %1)
This would push `%0` and `%1` onto the worklist, but then when trying to materialize `%1` the pass would falsely detect a combination loop when it tries to materialize `%0` and sees that it's already in the worklist.
This fix now collects all nested operands of an operation and tracks them alongside the operation, but then only processes the operands one-by-one such …

[Arc][LowerState] Fix combinational loop false positives

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/LowerIntrinsics.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/basic.mlir
test/Dialect/FIRRTL/canonicalization.mlir
test/Dialect/FIRRTL/lower-intrinsics.mlir

Add a new `firrtl.int.clock_gate` operation to represent clock gates. This new op is intended to eventually replace the magic `EICG_wrapper` extmodule that some passes in the firtool pipeline are sensitive to (mainly `WireDFT` and `ExtractInstances`).
This commit merely adds the op, canonicalization, basic round-tripping tests, and the required snippets in `LowerIntrinsics`. It does not add any handling of the intrinsic to the pipeline yet.
As a drive-by improvement it also makes the `UInt1Type` in `FIRRTLTypes.td` a `BuildableType` and requiring an inferred width. This allows `UInt1Type`s to be omitted from assembly formats. The `mux` gets a shiny new `UInt1OrUnsizedType` to continue accepting uninferred widths for the condition.

[FIRRTL] Add clock gate intrinsic

---

include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
test/Dialect/FIRRTL/infer-widths.mlir

This adds support for enum types and the subtag operation to InferWidths.  It constrains all widths inside enum types to be exactly identical. The subtag op's result size is constrained to match the payload size of the matching tag of the input enumeration value.

[FIRRTL][InferWidths] Support enum types

---

include/circt/Dialect/HW/HWVisitors.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

This adds support for `hw::UnionCreateOp` to ExportVerilog.  It works by emitting a bit concatenation and assigning it to a wire with a union type.  Each union member may have a prepadding, which is decided by the member's offset size, and a postpadding to ensure that each union element is the same size. The resulting bitconcat is `{prepadding, data, postpadding}`.  If there is no padding for a particular member, then bitconcat will not be used.
The following example has no offsets, but the member `a` requires post-padding of `1` bit.
```mlir
hw.module @unionCreate(%in: i1) -> (out: !hw.union<a: i1, b: i2>) {
%0 = hw.union_create "a", %in : !hw.union<a: i1, b: i2>
hw.output %0 : !hw.union<a: i1, b: i2>
}
```
```verilog
module unionCreate(
input …
```

[ExportVerilog] Add support for UnionCreate op.

---

tools/firtool/firtool.cpp

Force targets should not be "lowered", this is needed to avoid issues.
See https://github.com/llvm/circt/pull/5051 .

[FIRRTL] firtool: Run merge-cnxns regardless of agg preserv.

---

include/circt/Dialect/OM/OMTypes.td
test/Dialect/OM/round-trip.mlir

This is an opaque type that indicates a value is a reference to a hardware entity. This allows values in OM dialect's type system to include references in parameters, fields, etc.

[OM] Add a Reference type.

---

include/circt/Dialect/OM/OMAttributes.h
include/circt/Dialect/OM/OMAttributes.td
include/circt/Dialect/OM/OMDialect.td
include/circt/Dialect/OM/OMTypes.td
lib/Dialect/OM/CMakeLists.txt
lib/Dialect/OM/OMAttributes.cpp
lib/Dialect/OM/OMDialect.cpp
test/Dialect/OM/round-trip.mlir

This is a wrapper around a hw.innerNameRef with !om.ref type. This is needed because the OM dialect constant ops need typed attributes, so a hw.innerNameRef can't be used directly. That is really what we want to capture, so this simply wraps the HW dialect attribute and provides a type so it can work in the OM dialect type system.
Note that this does not encode hierarchical paths. This can be accomplished in a variety of ways if necessary, but for now simply referencing an inner symbol should be sufficient for many use cases. If hierarchical paths are needed, the instance graph can be elaborated and this information combined with the inner symbol references.
Depends on https://github.com/llvm/circt/pull/5083

[OM] Add Reference attribute.

---

include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
lib/Dialect/FIRRTL/FIRRTLTypes.cpp

Needed for putting RefType in aggregates.  There are no fields within a reference regardless of base type, implement as if "ground" type.

[FIRRTL] RefType: Implement FieldIDTypeInterface.

---

include/circt/Dialect/Seq/SeqOps.td
lib/Dialect/Seq/SeqOps.cpp
test/Dialect/Seq/canonicalization.mlir
test/Dialect/Seq/round-trip.mlir

Add a `seq.clock_gate` operation that represents a safe, glitchless gating of a clock. It isn't totally clear to me which dialect this op best fits into, but given that it interacts with clocks and contains an internal storage element to avoid glitching, Seq seems like a good fit.
This commit merely adds the op, canonicalizations, and basic tests. It isn't used or lowered yet. I imagine that the `LowerSeqToSV` pass would be able to lower this clock gate either to an extmodule or to an inline simulation model later.

[Seq] Add clock gate operation

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

This adds support for FEnumCreateOp in LowerToHW.  It performs type lowering on the output type of the op, and then reflects on it to create the appropriate HW value.
This relies on another PR to add `FIRRTLVisitor` support for `FEnumCreate`.

[FIRRTL][LowerToHW] Support FEnumCreateOp

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

When no padding is required for UnionCreate, we spill to a wire and we emit the RHS expression directly as the RHS of an assignment.  The RHS of an assignment does not need parenthesis around it. This PR switches the precedence of that case from `Selection` to `LowestPrecedence` to elide it.
As an example, we used to emit:
```verilog
assign out = (in + in);
```
but we now emit:
```verilog
assign out = in + in;
```

[ExportVerilog] Remove uneeded parenthesis around UnionCreate

---

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp

Before this change, an error on a port used the location of the defining module, instead of the location of the port, as this code was written before block arguments had locations associated with them.  We now emit good port locations from Chisel, and reliably preserve them throughout the pipeline, so it makes sense to use the port's location to emit the error.
This also changes how we emit errors for regular operations.  Since this error message is expected to be user facing, it is better if we do not dump the IR for the operation.

[FIRRTL][ExpandWhens] Use port locs when emitting init errors

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

Gate these on not SYNTHESIS, don't worry about VERILATOR.
Verilator does support these as of [4.218 (2022-01-17)](https://verilator.org/guide/latest/changes.html#verilator-4-218-2022-01-17), but behavior isn't quite per spec.
SYNTHESIS is more relevant concern.

[LowerToHW] Gate force/release on ifndef SYNTHESIS, not VERILATOR.

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

Don't lower these as much as possible.
Keep the always-lower-(non-rw-)probe behavior
to workaround the memtaps / 4479 issue.
Also, if we need to lower the source operand,
re-construct/materialize it (like "Source Materialization").
This does of course mean rwprobe'ing something means it needs to be okay to preserve as an aggregate.

[LowerTypes] Preserve rwprobes, forceable.

---

docs/Dialects/FIRRTL/FIRRTLAnnotations.md
include/circt/Dialect/FIRRTL/AnnotationDetails.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/annotations-errors.mlir
test/firtool/sv-attr.fir

This PR adds support for AttributeAnnotation. LowerAnnotation pass lowers
these annotations into`sv.attribute` dialect attributes. LowerToHW is also modified to move these attritutes.
SFC implementation: https://github.com/chipsalliance/firrtl/pull/1643

[FIRRTL] Support AttributeAnnotation

---

include/circt/Dialect/ESI/ESITypes.h
include/circt/Dialect/ESI/cosim/APIUtilities.h
lib/Dialect/ESI/CMakeLists.txt
lib/Dialect/ESI/ESITranslations.cpp
lib/Dialect/ESI/ESITypes.cpp
lib/Dialect/ESI/Passes/ESIEmitCollateral.cpp
lib/Dialect/ESI/Passes/ESILowerToHW.cpp
lib/Dialect/ESI/capnp/ESICapnp.h
lib/Dialect/ESI/capnp/Schema.cpp
lib/Dialect/ESI/cosim/APIUtilities.cpp

... to prepare for the C++ API; refactors the `TypeSchema` to remove any (...most) capnp related functionality in favor of a more general `ESICosimType` class.

[ESI] Refactor ESI cosim API type emission

---

frontends/PyCDE/src/system.py
include/circt/Dialect/ESI/ESIPasses.h
include/circt/Dialect/ESI/ESIPasses.td
integration_test/ESI/cosim/loopback.mlir
lib/Dialect/ESI/CMakeLists.txt
lib/Dialect/ESI/Passes/ESICleanMetadata.cpp
lib/Dialect/ESI/Passes/ESIEmitCollateral.cpp
test/Dialect/ESI/services_collateral.mlir

Moves metadata cleaning from the `esi-emit-collateral` pass to a separate pass.

[ESI] Add clean metadata pass

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
test/Dialect/FIRRTL/const.mlir
test/Dialect/FIRRTL/errors.mlir

This disallows register types from being const. Register reset values are allowed to be const or contain const members.
In order to efficiently check if a type is const or contains const members, containsConst has been added to RecursiveTypeProperties.

[FIRRTL] Register const updates

---

lib/Dialect/Arc/Transforms/LowerState.cpp
test/Dialect/Arc/lower-state.mlir

Applies @maerhart's fix for LowerState memory read materialization, and uses a comb mux to lower memory read ports instead of control flow (for data-flow conditions it's best to use Mux to avoid problems with backends that might have worse performance with control flow, and a later pass can transform muxes into SCF blocks if desired).
@fabianschuiki

[Arc] LowerState: fix memory read materialization

---

include/circt/Dialect/SV/SVPasses.h
include/circt/Dialect/SV/SVPasses.td
lib/Dialect/SV/Transforms/HWMemSimImpl.cpp

Remove the `-mem` suffix in the `ignore-read-enable-mem` option of the `HWMemSimImpl` pass. "Read enable" should be unambiguous already. Note that this does not change the corresponding firtool flag, so no breaking change of CLI flags happens here (except for direct circt-opt invocations).

[HWMemSimImpl] Remove "mem" from "ignore-read-enable-mem" flag

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLOps.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/Vectorization.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/lower-types.mlir
test/Dialect/FIRRTL/vectorization.mlir
tools/firtool/firtool.cpp

This PR introduces element-wise operations, `firrrtl.elementwise_or, firrtl.elementwise_and` and `firrtl.elementwise_xor` to represent logical operations over 1d vector types. 
* FIRRTLOps -- type inference is added.
* Vectorization pass -- canonicalizer `vector_create (a[0] or b[0], a[1] or b[1], a[2] or b[2], ...)` -> `elementwise_or a, b` is added. 
* LowerToHW -- `elementwise_or a, b` -> `bitcast(comb.or (bitcast a), (bitcast b))`
Example:
```scala
circuit Foo:
module Foo:
input a: UInt<3>[2]
input b: UInt<3>[2]
output c: UInt<3>[2][3]
c[0][0] <= or(a[0], b[0])
c[0][1] <= or(a[1], b[1])
c[1][0] <= and(a[0], b[0])
c[1][1] <= and(a[1], b[1])
c[2][0] <= xor(a[0], b[0])
c[2][1] <= xor(a[1], b[1])
```
```mlir
firrtl.module @Foo(in %a: !firrtl.vector<uint<3>, 2>, in %b: …
```

[FIRRTL] Introduce element-wise operations

---

docs/GettingStarted.md
docs/PythonBindings.md

The current link to PyCDE in https://circt.llvm.org/docs/PythonBindings/ leads to https://circt.llvm.org/PyCDE, which is broken. The correct one is "docs/PyCDE". 
While checking for this, I found that a few more links/images are broken, and building "docs/" using doxygen 1.9.6 does not work. I spent some time fighting it (replacing abs_top_src with hardcoded paths) and still could get similar pages as in the current docs website.
Am I doing something wrong with doxygen? I want to learn more about CIRCT and was checking docs.

[docs] Fix broken docs links in PyCDE and diagrams on Getting Started page

---

lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/test.mlir

The printer for enumcreate was accidentally printing the tag string instead of the input SSA value.  This fixes the problem while also adding some CHECK lines in the basic IR test for the enumeration related operations.

[FIRRTL] Fix enumcreate printed form

---

tools/firtool/firtool.cpp

Inferwidths does not directly support match statements, but it does support the operations it lowers to, `isTag` and `subtag`.

[firtool] Run LowerMatches before InferWidths

---

include/circt/Conversion/ExportVerilog.h
include/circt/Conversion/Passes.td
lib/Conversion/ExportVerilog/CMakeLists.txt
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/LegalizeAnonEnums.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Conversion/ExportVerilog/hw-enums.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir

Our Verilog output for anonymous enumeration is highly problematic:
every time we write out the type, the variants or members of the
enumeration enter the global namespace.  This makes it impossible to
have multiple declarations share the same enumeration type.
This adds walk of all operations in the ModuleOp to find and replace all
enumeration types used with typedefs.  The typedefs are automatically
injected into a typescope with the name "Enums".
Here is an example of what that looks like:
```verilog
ifndef _TYPESCOPE_Enums
`define _TYPESCOPE_Enums
typedef enum bit [0:0] {enum0_A, enum0_B} enum0;
`endif // _TYPESCOPE_Enums
module EnumCmp(
input  enum0 test,
output       result
)
assign result = test == enum0_A;
endmodule
```
This also adds support for 0 width typedecls, which allow us …

[ExportVerilog] Transform anonymous enumerations in to typedefs

---

include/circt/Dialect/Handshake/HandshakeOps.td
lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
test/Conversion/HandshakeToHW/test_instance.mlir

+adds missing "hasClock" attribute from `InstanceOp`.
+always sets the insertion point for the `SubModuleBuilder` (some funk was happening where, sometimes, the insertion point of it would be inside the `hw.module` from which the `handshake.func` was converted from.

[HandshakeToHW] Add `handshake.instance` lowering

---

include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/HW/HWTypeInterfaces.td
lib/Dialect/FIRRTL/FIRRTLTypes.cpp

This function does not appear to be used anywhere. I am motivated to remove it as I don't know what value to return for union-like types.

[HW] Remove `getGroundFields` from `FieldIDTypeInterface`

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
lib/Dialect/FIRRTL/FIRRTLTypes.cpp

Split out queries that are reasonable for all FIRRTLType's, leave the rest in FIRRTLBaseType.
Notably:
* RefType is not passive, nor ground.
* isPassive() and getPassiveType() only on FIRRTLBaseType.
* isConst is supported on all FIRRTLType's.
Note that RTP is not stored for all types, but make these properties and basic
predicates using them, part of all FIRRTLType's.

[FIRRTL] Hoist common type-property methods up to FIRRTLType.

---

lib/Dialect/FIRRTL/Transforms/LowerMatches.cpp
test/Dialect/FIRRTL/lower-matches.fir

This fixes two bugs in LowerMatches.
The first is when the match has no case statements, we would underflow an integer and crash assuming too many regions.  This was fixed by just deleting the match statement when there are no cases.
The second bug comes from a single case statement.  The code assumed that we would be inserting in to the `else` block of a WhenOp, and that it could replace the current block with the case's block.  This is not actually true when there is a single case, where the current block and insertion point is at the MatchOp.  We fix this by splicing the case's block in to the current insertion point.

[FIRRTL][LowerMatches] Fix matches with 0 and 1 variants

---

test/Dialect/Arc/Reduction/pattern-registration.mlir
test/Dialect/Arc/Reduction/state-elimination.mlir
test/Dialect/FIRRTL/Reduction/annotation-remover.mlir
test/Dialect/FIRRTL/Reduction/connect-source-operand-forward.mlir
test/Dialect/FIRRTL/Reduction/memory-stubber.mlir
test/Dialect/FIRRTL/Reduction/node-symbol-remover.mlir
test/Dialect/FIRRTL/Reduction/pattern-registration.mlir
test/Dialect/FIRRTL/Reduction/port-pruner.mlir
test/Dialect/HW/Reduction/hw-constantifier.mlir
test/Dialect/HW/Reduction/hw-module-externalizer.mlir
test/Dialect/HW/Reduction/hw-operand-forwarder.mlir
test/Dialect/HW/Reduction/pattern-registration.mlir
test/circt-reduce/canonicalize-reduction.mlir
test/circt-reduce/cse-reduction.mlir
test/circt-reduce/operation-pruner.mlir

Don't make assumptions beyond /usr/bin/env regarding the location of various common utilities.
Fixes tests on NixOS.

[circt-reduce] Fix tests for portability again, prefer /usr/bin/env.

---

lib/Dialect/FIRRTL/Transforms/InferResets.cpp
test/Dialect/FIRRTL/infer-resets.mlir

Use same types for both sides, avoid uneven indexing.
Add test that crashes without this change.

[FIRRTL][InferResets] Fix inference through ref.sub.

---

include/circt/Dialect/Arc/ArcOps.td
include/circt/Dialect/Arc/ArcPasses.h
include/circt/Dialect/Arc/ArcPasses.td
include/circt/Support/LLVM.h
lib/Dialect/Arc/ArcOps.cpp
lib/Dialect/Arc/Transforms/CMakeLists.txt
lib/Dialect/Arc/Transforms/InlineArcs.cpp
lib/Dialect/Arc/Transforms/LatencyRetiming.cpp
lib/Dialect/Arc/Transforms/SplitLoops.cpp
test/Dialect/Arc/latency-retiming.mlir

Currently, the latency attribute on the `arc.state` operations is not really used except for differentiating between 0 and 1 latency. This pass collapses sequences of `arc.state` operations that form a shift register into one state operation. It also aggregates the latencies of isolated fan-in trees. It's still very simple in its current form, but can be easily extended in the future. Since we don't have a proper benchmark running yet to assess performance, I gathered some statistics instead by ignoring the name attributes on the states (basically assuming that the user tells arcilator that they are only interested in the inputs and outputs, but not observing internal state and thus no taps are inserted). I don't add it to arcilator for now since we don't have a way to remove the name …

[Arc] Add LatencyRetiming pass

---

include/circt/Dialect/Arc/ArcOps.td
lib/Dialect/Arc/ArcFolds.cpp
test/Dialect/Arc/canonicalizers.mlir

* Since `arc.storage.get` does not access the storage, but just adds a constant to the pointer (like getelementpointer), it does not have to be constrained to a memory read.
* Add a canonicalizer to collapse sequences of such ops.

[Arc] Add StorageGetOp canonicalizer

---

include/circt/Dialect/Arc/ArcOps.td
include/circt/Dialect/Arc/ArcPasses.td
lib/Dialect/Arc/ArcDialect.cpp
lib/Dialect/Arc/Transforms/InlineArcs.cpp
test/Dialect/Arc/inline-arcs.mlir

InlineArcs only considers `arc.state` operations at the moment. This adds support to also inline `arc.call` sites. While the callgraph of the state ops is entirely flat as they can only occur in a `hw.module` and there is no hierarchy of such modules, the callgraph including `arc.call` operations form a DAG. Arcs are not allowed to have recursions, but as this is not properly verified, this pass checks for that and leaves the recursive structure as is. In order to perform the least amount of calls to the inlining utility, this pass is extended to traverse the callgraph bottom-up. This way calls are inlined before they potentially get duplicated by inlining in multiple call-sites. Would be nice to have something like `InstanceGraph` for arcs to use the llvm graph iterators.
Additionally, …

[Arc] Generalize InlineArcs pass

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/LowerOpenAggs.cpp
test/Dialect/FIRRTL/lower-open-aggs-errors.mlir
test/Dialect/FIRRTL/lower-open-aggs.mlir
tools/firtool/firtool.cpp

Immediately after parsing (cc #5128), "lower" the open aggregates containing mixed hardware into their hardware-only "projections", pulling out the non-hw elements (refs) and rewriting all opensub* ops accordingly.

[FIRRTL] Add LowerOpenAggs pass.

---

lib/Dialect/SV/SVDialect.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

`$` can be used in the middle of the identifier so `isValidVerilogCharacter` should return `true` for `$`.

[ExportVerilog] Allow `$` to be in the identifier

---

include/circt/Dialect/Arc/ArcInterfaces.td
include/circt/Dialect/Arc/ArcOps.td
lib/Dialect/Arc/ArcOps.cpp
lib/Dialect/Arc/CMakeLists.txt
lib/Dialect/Arc/Transforms/Dedup.cpp
test/Dialect/Arc/dedup.mlir

Currently, the Dedup pass only considers StateOp as call operations to arcs because this was the only legal way to call an arc until recently. Because there is no additional check that no other operation calls an arc, the pass fails because it potentially dedups an arc that is called by a CallOp which is not updated accordingly. This generalizes to operations that implement the CallOpMutableInterface. It is assumed that all operations that can call an arc, implement this interface.

[Arc] Dedup: generalize to CallOpInterface

---

lib/Conversion/HWArithToHW/HWArithToHW.cpp

I'd like to bring back this method which has been removed in #4898, as our OoT-flow has other `ui`/`si` ops that we need to convert alongside the `hwarith` patterns.

[HWArithToHW] Restore access to HWArith-specific patterns.

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/FinalizeIR.cpp
test/firtool/firtool.mlir
tools/firtool/firtool.cpp

There may be several files generated during any given run of firtool, represented as sv.verbatim ops with output_file attributes. This information isn't needed in the final MLIR that is emitted, so erase those from the MLIR right before emitting it.

[firtool] Erase extra verbatim files before printing final MLIR.

---

include/circt/Dialect/FIRRTL/FIRRTLTypes.h
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
test/Dialect/FIRRTL/connect-errors.mlir

Enumerations can only be connected when all variants, compared in order, have the same name and type, modulo uninferred widths.  They do not, like bundle and array types, allow for implicit truncation or extension of the ground fields.  The original logic had a couple of bugs:
1. It was not comparing the variant name.
2. It was comparing the dest to the dest (instead of the src).
3. It was allowing implicit truncs/exts in the variant types.
This change fixes these problems and adds two tests.

[FIRRTL] Fix connect verifier for enums

---

include/circt/Dialect/Arc/ArcOps.td
include/circt/Dialect/Arc/ArcPasses.td
include/circt/Dialect/Arc/ArcTypes.td
lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp
lib/Dialect/Arc/ArcFolds.cpp
lib/Dialect/Arc/ArcOps.cpp
lib/Dialect/Arc/ArcTypes.cpp
lib/Dialect/Arc/Transforms/AllocateState.cpp
lib/Dialect/Arc/Transforms/CMakeLists.txt
lib/Dialect/Arc/Transforms/InferMemories.cpp
lib/Dialect/Arc/Transforms/LegalizeStateUpdate.cpp
lib/Dialect/Arc/Transforms/LowerState.cpp
lib/Dialect/Arc/Transforms/PassDetails.h
lib/Dialect/Arc/Transforms/StripSV.cpp
test/Conversion/ArcToLLVM/lower-arc-to-llvm.mlir
test/Dialect/Arc/allocate-state.mlir
test/Dialect/Arc/basic-errors.mlir
test/Dialect/Arc/basic.mlir
test/Dialect/Arc/canonicalizers.mlir
test/Dialect/Arc/infer-memories.mlir
test/Dialect/Arc/isolate-clocks.mlir
test/Dialect/Arc/legalize-state-update-error.mlir
test/Dialect/Arc/legalize-state-update.mlir
test/Dialect/Arc/lower-state.mlir
test/Dialect/Arc/print-state-info.mlir
test/Dialect/Arc/strip-sv.mlir

* Remove the optional enable and clock operands from `arc.memory_read_port` making it a combinatorial read port. Latencies can be added using the `arc.state` operation.
* Adjust InferMemories accordingly
* Make `arc.memory_read_port` pure to allow it to be moved into `arc.define` ops. This means the memory value has to be passed via argument. This will be considered to pass the whole memory as a value (like `hw.array`) at this stage of the lowering. The LegalizeStateUpdates pass should make it easy to switch to pointer semantics for memories.
* Remove top-level `sv.macro.decl` ops in StripSV (sorry for this unrelated change, but it's just 4 lines :) )
* Remove the optional stride parameter from the `!arc.memory` type and add a member function to conveniently compute the stride on-demand. …

[Arc] MemoryReadPortOp: remove enable and clock operand, make it pure

---

CMakeLists.txt
tools/circt-lec/CMakeLists.txt

Add the z3 include directories as system includes, not normal includes, to the circt-lec tool.  Including the z3 headers this way will prevent clang from putting out warnings on code in the z3 headers.
Also, remove some intermediate variables (`CIRCT_LEC_{INCLUDES,LIBS,SOURCES}`).

[circt-lec] Clean up z3 includes

---

include/circt/Dialect/FIRRTL/Passes.td
include/circt/Dialect/SV/SVStatements.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR.mlir
test/firtool/export-ref.fir
tools/firtool/firtool.cpp

This implements the [proposed lowering of ref ports in the firrtl abi spec](https://github.com/chipsalliance/firrtl-spec/pull/103).
During the `LowerXMR` pass, for each public output ref port,  an `hw.exportableRef` op is created to track the ref. This op is a symbolic namepath for the ref. During the `ExportVerilog` pass, `sv.macro.decl` and `sv.macro.def` ops are created with the fully resolved namepath based on the legalized verilog names.
Although the semantics are fairly firrtl specific, the exportable-ref op is part of the `hw` dialect since it needs to hang around until `ExportVerilog`.

[FIRRTL] Export named references as macros to Verilog files

---

include/circt/Dialect/Arc/ArcOps.td
lib/Dialect/Arc/ArcFolds.cpp
lib/Dialect/Arc/ArcOps.cpp
lib/Dialect/Arc/Transforms/InferMemories.cpp
lib/Dialect/Arc/Transforms/LowerState.cpp
test/Dialect/Arc/basic-errors.mlir
test/Dialect/Arc/basic.mlir
test/Dialect/Arc/canonicalizers.mlir
test/Dialect/Arc/infer-memories.mlir
test/Dialect/Arc/isolate-clocks.mlir
test/Dialect/Arc/lower-state.mlir

The `arc.state` operation computes the fan-in of the register(s) it represents inside an arc which allows a simpler IR structure because only one operation is required to represent this instead calls + state operations making it easier to iterate the predecessor registers, etc. There are the exceptions of the enable and reset operands though. While the reset is mostly the reset signal provided by the root module input (like for the clock operand) and thus not really an issue to represent as an operand, the enable operand typically requires a call operation as predecessor to compute the fan-in. As discussed last week, it might be nice to also compute this fan-in inside the arc that already computes the data inputs plus adding a unit attribute on the state operation to indicate that that is …

[Arc] Change MemoryWritePortOp to also take an arc

---

include/circt/Dialect/Arc/ArcOps.td
include/circt/Dialect/Arc/ArcPasses.h
include/circt/Dialect/Arc/ArcPasses.td
lib/Dialect/Arc/ArcFolds.cpp
lib/Dialect/Arc/ArcOps.cpp
lib/Dialect/Arc/Transforms/ArcCanonicalizer.cpp
lib/Dialect/Arc/Transforms/CMakeLists.txt
lib/Dialect/Arc/Transforms/InferMemories.cpp
lib/Dialect/Arc/Transforms/LowerState.cpp
test/Dialect/Arc/arc-canonicalizer.mlir
test/Dialect/Arc/basic-errors.mlir
test/Dialect/Arc/basic.mlir
test/Dialect/Arc/canonicalizers.mlir
test/Dialect/Arc/infer-memories.mlir
test/Dialect/Arc/isolate-clocks.mlir
test/Dialect/Arc/lower-state.mlir

Add a pass that allows us to implement canonicalization patterns that require a symbol cache to work efficiently (as regular canonicalization patterns don't get one provided). But also allows us to add canonicalizations to operations from other dialects that are simulation specific and thus not desirable to be added to that other dialect directly.

[Arc] Add ArcCanonicalizer pass

---

test/arcilator/arcilator.mlir
tools/arcilator/CMakeLists.txt
tools/arcilator/arcilator.cpp

To print debug info in MLIR output, the AsmPrinter CLI option mlir-print-debuginfo could be used. However, for printing debug info in the LLVM output, a pass to add the necessary DILocation attributes as to be called first. To make this process easy to use and uniform no matter whether MLIR or LLVM is printed, a print-debug-info CLI option is added

[arcilator] Convenience flag for printing debug info

---

lib/Dialect/Arc/Transforms/ArcCanonicalizer.cpp
test/Dialect/Arc/arc-canonicalizer.mlir
tools/arcilator/arcilator.cpp

On the HW/Comb level, the `comb.concat` operation is basically considered free. However, in simulation it is quite expensive. Instead of concatenating integers of the same width, we can do the AND/OR directly and do a reduction on the smaller result integer, effectively cutting the number of assembly instructions produced to almost half.

[Arc] Simulation specific optimization for comb.icmp

---

include/circt/Dialect/OM/Evaluator/Evaluator.h
lib/Dialect/OM/CMakeLists.txt
lib/Dialect/OM/Evaluator/CMakeLists.txt
lib/Dialect/OM/Evaluator/Evaluator.cpp
unittests/Dialect/CMakeLists.txt
unittests/Dialect/OM/CMakeLists.txt
unittests/Dialect/OM/Evaluator/CMakeLists.txt
unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp

The Evaluator is responsible for evaluating the object model according to the semantics defined by the rationale. It can be constructed from an IR module, and Objects can be instantiated by supplying a Class name and actual parameters.
Under the hood, it implements the small expression grammar outlined in the rationale document. The entire grammar defined so far is implemented in this initial version. Instantiations are currently evaluated eagerly, which precludes cycles.
Objects are defined using a variant that is either a pointer to a simple Object struct, or an typed Attribute for primitives. The fields of an Object struct are stored in a simple map.
This is sufficient for an initial implementation, but lots of opportunities exist to improve the evaluator, Object representation, and …

[OM] Add initial implementation of Evaluator.

---

include/circt/Dialect/FIRRTL/CMakeLists.txt
include/circt/Dialect/FIRRTL/FIRRTLEnums.td
include/circt/Dialect/FIRRTL/FIRRTLTypeInterfaces.h
include/circt/Dialect/FIRRTL/FIRRTLTypeInterfaces.td
include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
lib/Dialect/FIRRTL/CMakeLists.txt
lib/Dialect/FIRRTL/FIRRTLTypeInterfaces.cpp

Phases separate the values in a firrtl program into two worlds, the property
world and the hardware world. Eventually, a firrtl program will be compiled
into two artifacts:
1. The hardware design (verilog)
2. The metadata (om dialect mlir bytecode)
The property phased values will be erased from the hardware design and only
exist in the metadata artifact, while the hardware phased values will be erased
from the metadata and only exist in the hardware design.

[FIRRTL] Add a type interface for querying phase compatibility

---

lib/Dialect/FIRRTL/Export/FIREmitter.cpp
test/Dialect/FIRRTL/emit-basic.mlir

Support exporting these types + ops, especially `ref.sub`.  Allows exporting `refs-in-aggs.mlir` file.
Added basic test.

[FIREmitter] Support Open aggregates, RefSubOp

---

include/circt/Dialect/FIRRTL/FIRRTLTypes.h
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
test/Dialect/FIRRTL/connect-errors.fir
test/Dialect/FIRRTL/connect-errors.mlir
test/Dialect/FIRRTL/connect.mlir

Addresses #5209 
I can also update `areTypesWeaklyEquivalent`, although `const` types were introduced into the firrtl spec in the same version that removed partial connection, so I suppose I can leave it. Or I can remove all of the const logic it has to clean things up.

[FIRRTL] Handle flips in const connections

---

include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/test.mlir

Add a new StringType to FIRRTL. Strings are used as metadata properties. Although string has an explicit phase, that phase must not be hardware (must be property phased). Ports with string types are input/output properties.

Add StringType to FIRRTL dialect

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLOps.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
test/Dialect/FIRRTL/const.mlir
test/Dialect/FIRRTL/errors.mlir

This commit adds a ConstCastOp for casting away constness from types. This op and const types will be dropped early in the firrtl pipeline in a followup commit.
Verification has been added to other casting ops to ensure that type constness is taken into account.

[FIRRTL] Const handling in cast ops

---

include/circt/Dialect/FIRRTL/AnnotationDetails.h
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/WireDFT.cpp
test/Dialect/FIRRTL/wire-dft-errors.mlir
test/Dialect/FIRRTL/wire-dft.mlir

If a signal is annotated as the clock divider bypass signal, wire it to clock gates that have the expected port.
Like `test_en` wiring the port number is hardcoded, but unlike test_en this ignores the "bypass" port if that port doesn't match the expected bypass port name/dir/type.
Warning is emitted if looks compatible but name doesn't match and bypass signal annotation is found.

[WireDFT] Add support for wiring optional clock div bypass signal.

---

include/circt/Dialect/FIRRTL/AnnotationDetails.h
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/WireDFT.cpp
test/Dialect/FIRRTL/wire-dft-errors.mlir
test/Dialect/FIRRTL/wire-dft.mlir

Backport this change to 1.34.x .

(1.34.3 backport) [WireDFT] Add support for wiring optional clock div bypass signal. (#5219)

---

include/circt/Dialect/DC/DCOps.td
test/Dialect/DC/roundtrip.mlir

Looks like we're going to have to introduce a possibility for non-determinism in DC to make it generally applicable.
`dc.merge` will non-deterministically select one of the incoming tokens and emit an output (`dc.value<i1>`) stating which token was selected.

[DC] Add merge operation

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/pretty.mlir

Fixes https://github.com/llvm/circt/issues/5231 .

[ExportVerilog] Fix formatting involving macro definition.

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/parse-errors.fir

For use w/deferred linking or the new ABI, ref statements are not required.  However, if they're present they must cover all ref ports on the module.
cc #4909.

[FIRRTL] Reject ref statements for some ports but not all.

---

include/circt/Dialect/OM/OMAttributes.td
include/circt/Dialect/OM/OMTypes.td
lib/Dialect/OM/OMAttributes.cpp
test/Dialect/OM/round-trip.mlir

Add a flat symbol reference attribute to OM dialect. This is required in addition to the `InnerRefAttr` to store reference to modules.
This PR adds  the `Attribute`, the corresponding `Type` and a lit test.
We can bikeshed on the Attribute name, `symRef`.

[OM] Add a symbol reference attribute

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
test/Dialect/SV/hw-memsim.mlir

Added a separate macro to bypass synthesis and enable initial blocks setting memories lowered through `HWMemSimImpl`.

[HW][SV] Allow control of initial blocks setting memories

---

integration_test/Target/ExportSystemC/basic.mlir
integration_test/Target/ExportSystemC/func.mlir

If CXX compiler is not clang (or not same clang as clang-tidy used), build flags may not be appropriate (or valid) for use by clang-tidy.
Workaround by adding trailing '--'.
Fixes #5236.
See upstream
https://github.com/llvm/llvm-project/commit/626849c71e85d546a004cc91866beab610222194 .

[SystemC] integration tests: avoid compile_commands.json in clang-tidy.

---

include/circt-c/Dialect/OM.h
lib/CAPI/Dialect/CMakeLists.txt
lib/CAPI/Dialect/OM.cpp
test/CAPI/CMakeLists.txt
test/CAPI/om.c
test/CMakeLists.txt
test/lit.cfg.py

This adds the usual CAPI structure and dialect registration boilerplate, as well as CAPIs around the Evaluator library.
The APIs are intended to be as minimal and straightforward as possible, simply wrapping and unwrapping the C++ structures when possible.
One slight divergence is in the ObjectValue type, which is a std::variant between an Object shared pointer or an Attribute. The normal approach of casting to and from a void pointer does not work with std::variant, so a different representation of ObjectValue is used instead. The discriminated union is simply represented as a struct which only over has one field set. It might be possible to save some space using a struct with a C union and a flag, but the simplicity of the current approach seemed reasonable.
Another minor detail worth …

[OM] Add initial CAPI for OM dialect Evaluator.

---

include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
lib/Firtool/Firtool.cpp
test/Dialect/FIRRTL/emit-metadata-errors.mlir
test/Dialect/FIRRTL/emit-metadata.mlir

Make the `CreateSiFiveMetadata` a `mlir::ModuleOp` pass. 
This is required to generate `om` operations (https://github.com/llvm/circt/pull/5224). The `om::ClassOp` must have  `mlir::ModuleOp` as the parent.
This PR updates the Pass infrastructure and also the lit tests.

[FIRRTL] Make emit-metadata a mlir::ModuleOp pass

---

integration_test/Bindings/Python/dialects/om.py
lib/Bindings/Python/CIRCTModule.cpp
lib/Bindings/Python/CMakeLists.txt
lib/Bindings/Python/DialectModules.h
lib/Bindings/Python/OMModule.cpp
lib/Bindings/Python/dialects/OMOps.td
lib/Bindings/Python/dialects/om.py

This adds the usual Python API structure and dialect registration boilerplate, as well as Python APIs around the Evaluator library.
The C++ implementations with pybind are intended to be as minimal and straightforward as possible, simply wrapping the CAPI.
In order to provide a handy user-facing API, a couple of the C++ implementations are wrapped in pure Python to provide a nicer interface:
The Evaluator constructor is wrapped in Python to also set up a logger and diagnostic handler that uses the logger. This allows the CAPI and C++ implementation to avoid dealing with Diagnostics. The CAPI simply returns null on failure, and the C++ implementation simply throws a Python error in this case. The pure Python diagnostic handler ensure the error and any notes are logged before the error is …

[OM] Add initial Python API for OM dialect evaluator.

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-basic.fir

[FIRParser] Support keywords and literal identifiers as static ref exprs.

---

lib/Dialect/FIRRTL/Transforms/PrefixModules.cpp
test/Dialect/FIRRTL/prefix-modules.mlir

Required to unblock the build of internal cores with additional constraints.

[PrefixModules] Rename references from the module body

---

.github/workflows/buildAndTest.yml
.github/workflows/buildAndTestWindows.yml
.github/workflows/trackLLVMChanges.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands

[CI] Migrate from set-output to using environment files.

---

.github/workflows/buildAndTest.yml
.github/workflows/buildAndTestWindows.yml
.github/workflows/nightlyIntegrationTests.yml
.github/workflows/shortIntegrationTests.yml
.github/workflows/trackLLVMChanges.yml
.github/workflows/uploadFirrtlReleaseArtifacts.yml

Node12 -> Node16, primarily.
See: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ .
Appears safe, both have some improvements we may enjoy, such as zstd for Windows cache.

[CI] Update github actions for checkout, cache: v2 -> v3

---

lib/Conversion/ExportVerilog/CMakeLists.txt
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/verif.mlir

Add support for emitting the assert, assume, and cover ops from the `verif` dialect, and property and sequence expressions from the `ltl` dialect directly in ExportVerilog. In the future we may want to build up AST-like ops in the SV dialect for this, simplify ExportVerilog, and add a lowering from Verif/LTL to SV separately. Doing so would allow us to do more involved conversions and leverage more syntactic sugar upon emission, and would declutter ExportVerilog. In their current form the LTL and Verif dialects are simple enough to emit directly though, so this is what this commit does for now.
The new `verif` assert-like ops can be used either in a procedural region, where they will emit as immediate `assert(x)` when possible, or a graph region like a module, where they will emit as …

[ExportVerilog] Add LTL and Verif dialect support

---

integration_test/Dialect/Handshake/buffer_init_none/buffer_init_none.mlir
integration_test/Dialect/Handshake/buffer_initial_values/buffer_initial_values.mlir
integration_test/Dialect/Handshake/conditional_modification/conditional_modification.mlir
integration_test/Dialect/Handshake/dot/dot.mlir
integration_test/Dialect/Handshake/lit.local.cfg.py
integration_test/Dialect/Handshake/matmul/matmul.mlir
integration_test/Dialect/Handshake/max/max.mlir
integration_test/Dialect/Handshake/mix_std_hs/mix_std_hs.mlir
integration_test/Dialect/Handshake/multiple_loops/multiple_loops.mlir
integration_test/Dialect/Handshake/nested_diamonds/nested_diamonds.mlir
integration_test/Dialect/Handshake/nested_loops/nested_loops.mlir
integration_test/Dialect/Handshake/sync_backedge/sync_backedge.mlir
integration_test/Dialect/Handshake/sync_op/sync_op.mlir
integration_test/Dialect/Handshake/task_pipelining/task_pipelining.mlir
integration_test/Dialect/Handshake/tp_memory/tp_memory.mlir
integration_test/Dialect/Handshake/tuple_input/tuple_input.mlir
integration_test/Dialect/Handshake/tuple_packing/tuple_packing.mlir
tools/CMakeLists.txt
tools/circt-cocotb-driver/CMakeLists.txt
tools/circt-cocotb-driver/circt-cocotb-driver.py.in

Turns out the cocotb driver is useful for things other than handshake... moves the cocotb driver to a separate tool folder, and modifies handshake tests accordingly.

Move cocotb driver to separate tool

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/Transforms/DropName.cpp
lib/Firtool/Firtool.cpp
test/Dialect/FIRRTL/canonicalization.mlir
test/Dialect/FIRRTL/drop-name.mlir

Lots of _T_ and _WIRE were appearing in the output.  These are quite useless.  We filter these out at all name preservation levels.  This also allows putting other names which start with '_' as droppable.
Also reorder a pass to increase parallelism [NFCI]

[FIRRTL] Tweak naming

---

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp

We need to make sure that we do not doubly process drivers when a wire is driven in both the `then` and `else` block, so we were removing the driver from the `else` block's driver map.  Since we are using MapVectors to record drivers, which is needed for deterministic error messages, deleting a single driver from the `else` block's driver map scaled linearly with the number of drivers.  Instead of removing it from the `else` block's driver map, just check if it was also in the `then` block's driver map.

[FIRRTL][ExpandWhens] Fix performance with large blocks

---

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp

We don't mark overdefined if there exists an operand with unknown state. This was required to get optimal results, but it also means that we have to try folding every time operand state was changed. It could cause regressions for operations with large number of operands. Actually in the internal designs there are operations with 65536 operands which caused regression in IMCP. This PR fixes the issue by just giving up such operations, especially when there are more than 128 operands since the success rate of folder should be much less. Maybe we can improve by specializing a folder for IMCP so that we don't have to get all operand lattice states.

[IMCP] Mark overdefined for the operations with large number of operands

---

include/circt/Dialect/HW/HWTypes.td
lib/Dialect/FIRRTL/FIRRTLUtils.cpp

`firrtl::getOrAddInnerSym` was returning an `InnerSymAttr` with empty symbol name, if the name hint and the operation name were both empty. Add the checks to ensure empty symbol name attributes are not created.

[FIRRTL] Donot create empty InnerSym name

---

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp

`ModuleInliner ` was creating an illegal empty inner sym name, if the instance op name is empty. Use `getOrAddInnerSym` instead to add legal inner sym.

[FIRRTL][ModuleInliner] Donot create empty inner sym

---

docs/Dialects/Pipeline/RationalePipeline.md
docs/Dialects/Pipeline/_index.md
include/circt/Dialect/Pipeline/Pipeline.td
include/circt/Dialect/Pipeline/PipelinePasses.h
include/circt/Dialect/Pipeline/PipelinePasses.td
lib/Conversion/PipelineToHW/PipelineToHW.cpp
lib/Dialect/Pipeline/PipelineOps.cpp
lib/Dialect/Pipeline/Transforms/CMakeLists.txt
lib/Dialect/Pipeline/Transforms/ExplicitRegs.cpp
lib/Dialect/Pipeline/Transforms/ScheduleLinearPipeline.cpp
lib/Dialect/Pipeline/Transforms/StageSeparatorToStage.cpp
test/Conversion/PipelineToHW/test_basic.mlir
test/Dialect/Pipeline/Transforms/explicit-regs.mlir
test/Dialect/Pipeline/Transforms/schedule-linear-pipeline.mlir
test/Dialect/Pipeline/Transforms/ss-to-stages.mlir
test/Dialect/Pipeline/errors.mlir
test/Dialect/Pipeline/round-trip.mlir

This PR adds a new operation, `pipeline.stage` to the `Pipeline` dialect. This operation is used to make stages explicit - that is, a region-defining operation with inputs and outputs (much like the `loopschedule.pipeline.stage`). The motivation for this is that once a `pipeline.pipeline` has had registers materialized, a representational change to make the stages explicit allows for much cleaner RTL lowering whenever stages are _not_ to be lowered to hardware directly inline in the parent `hw.module`.
I see this as sort of the best-of-both worlds wrt. the earlier pipeline IR design discussions. I felt like i had to introduce this representation given that lowering the current `pipeline.stage.regs` to outlined modules felt extremely clunky, whereas stepping through this representation …

[Pipeline] Add `pipeline.stage` op and rename others accordingly

---

include/circt/Dialect/OM/OMOps.td
lib/Dialect/OM/OMOps.cpp
unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp

Add convenient builders to `om::ClassOp` that given the parameter names, and field names and types, will create the body of the `ClassOp` with all the `ClassFieldOp` initialized.
Pasting a use case here, 
```cpp
StringRef paramNames[] = {"name",           "depth",        "width",
"maskBits",       "readPorts",    "writePorts",
"readwritePorts", "writeLatency", "readLatency"};
mlir::Type classFieldTypes[] = {
om::SymbolRefType::get(context),
mlir::IntegerType::get(context, 64, IntegerType::Unsigned),
mlir::IntegerType::get(context, 32, IntegerType::Unsigned),
mlir::IntegerType::get(context, 32, IntegerType::Unsigned),
mlir::IntegerType::get(context, 32, IntegerType::Unsigned),
mlir::IntegerType::get(context, 32, IntegerType::Unsigned),
mlir::IntegerType::get(context, 32, …
```

[OM] Add ClassOp builders

---

include/circt/Dialect/Verif/VerifOps.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/LegalizeNames.cpp
test/Conversion/ExportVerilog/verif.mlir
test/Dialect/Verif/basic.mlir

Allow `verif.{assert,assume,cover}` ops to carry a label that gets picked up by `LegalizeNames` and is properly emitted. All the machinery is already there, this just makes "label" part of the verif op semantics and ensures that `LegalizeNames` does the right thing.

[Verif] Add assert/assume/cover labels

---

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp

The `solveExpr` implementation of `InferWidths` was recursive and causing stack overflow issues on some designs. 
This PR implements an iterative version of the algorithm.
Co-authored-by: Schuyler Eldridge <schuyler.eldridge@sifive.com>

[FIRRTL][InferWidths] Make solveExpr Iterative

---

lib/Reduce/GenericReductions.cpp

* Don't delete terminators because they are typically verified to be present and can usually not be removed without removing the whole block.
* Cache the user map instead of traversing the whole module again for each matched operation. This means that not all operations that could have been removed are actually removed in one iteration, but doing multiple iterations with this faster implementation is usually a lot faster than doing one more thorough iteration (there might be some corner cases where it's slightly slower, but probably not relevant in practice).
No unit test because it's only a performance optimization and the result should stay the same when performed until convergence.
Reduces the original file of #5307 with size 23672972 to size 2208 in 33 sec when only including the …

[Reducer] Speed up OperationPruner

---

include/circt/Conversion/Passes.td
include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLStatements.td
include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
lib/Conversion/FIRRTLToHW/CMakeLists.txt
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Conversion/PassDetail.h
lib/Dialect/FIRRTL/Transforms/LowerIntrinsics.cpp
test/Conversion/FIRRTLToHW/intrinsics-errors.mlir
test/Conversion/FIRRTLToHW/intrinsics.mlir
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/lower-intrinsics.mlir
test/firtool/verif.fir

Add intrinsics to the FIRRTL dialect that lower directly to operations in the Verif and LTL dialects. This allows FIRRTL inputs to express temporal assert, assume, and cover operations without requiring native support for them in the FIRRTL spec.
This commit does the following:
- Add `firrtl.int.ltl.*` and `firrtl.int.verif.*` operations to `FIRRTLExpressions.td` and `FIRRTLStatements.td`
- Add intrinsic lowering support to `LowerIntrinsics`
- Add visitor support
- In LowerToHW, map the intrinsics to the corresponding `verif.*` and `ltl.*` operations.
- Since there are no opaque user-defined FIRRTL types yet, the intrinsics operate on `UInt<1>` where the LTL ops would operate on concrete `!ltl.sequence` and `!ltl.property` types. The LowerToHW change also includes a final `fixupLTLOps` …

[FIRRTL] Add Verif/LTL intrinsics

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp

Fixes an issue with emission when symbols are used with `om`.

[OM] Bypass constant ops referencing symbols in `ExportVerilog`

---

include/circt/Transforms/Passes.h
include/circt/Transforms/Passes.td
lib/Transforms/CMakeLists.txt
lib/Transforms/MapArithToComb.cpp
lib/Transforms/PassDetail.h
test/Transforms/map-arith-to-comb.mlir

Adds a pass which does a simple `arith` to `comb` mapping. The intention of this pass is mainly to get code out of Handshake (and wherever else we do some ad-hoc, simple arith-to-comb mapping/HLS), thus allowing integration testing of DC flows (refresher: handshake-to-dc lowers handshake ops to a combination of `dc` and `arith`).
This **does not** intend to be the definitive lowering/HLS pass of `arith` operations (hence the name "map" instead of e.g. "lower"). See it more as a temporary pass to provide this kind of functionality until we have an operator library + library mapping pass.
Currently, this pass strictly does operation mapping. If needed, `index`-type conversion could also be moved to this pass (e.g. setting `index` type width as a parameter of the pass).

[MapArith] Introduce `--map-arith-to-comb` pass

---

lib/Dialect/FIRRTL/FIRRTLTypes.cpp
lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp

Previously `visitConnectLike` traversed all elements in the connections, which could cause regressions when the connection is bulk connection. This PR improves lattice elements propagation by propagating only subelements affected. For `circt/perf/regress/chipyard.TestHarness.RocketSmall1Medium1Big1_BoomMedium1Large1Mega1.top.v.hi.fir` the IMPCP runtime changed from 60 sec to 4 sec.
Fix https://github.com/llvm/circt/issues/5187

[IMCP] Speed up the bulk connection propagation, NFCI

---

lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
test/Dialect/FIRRTL/const.mlir
test/Dialect/FIRRTL/drop-const.mlir
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/lower-matches.mlir

This pr ties up loose ends regarding enums and const.
MatchOp now takes const into account.
Non-const enums cannot contain const in their elements.
Verifier tests for enums have been added.

Enum const support

---

include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
test/Dialect/FIRRTL/imdce-nyi.mlir
test/Dialect/FIRRTL/imdce.mlir
test/Dialect/FIRRTL/omir.mlir
tools/firtool/firtool.cpp

This PR backports several IMDCE improvements to delete dead instances associated with OMIRTrackers.

Backport IMDCE improvements into firtool 1.37

---

include/circt/Dialect/SV/SVPasses.h
include/circt/Dialect/SV/SVPasses.td
include/circt/Firtool/Firtool.h
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
lib/Firtool/Firtool.cpp
test/Dialect/SV/hw-extract-test-code.mlir

This commit extends ETC to extract registers on top of https://github.com/llvm/circt/pull/5294. As firreg registers introduce cycles in dataflow by nature, this commit changes extraction mechanism so that we can find and extract maximum subset of testcode. Previously we were tracking dataflow until it reaches least fixedpoint of verification parts, but instead we can first compute least fixepoint of design parts and substract it from entire modules.

[ETC] Extract registers and instances if not in design

---

lib/Bindings/Python/OMModule.cpp

This switches to use the `data()` API, which is how the upstream Python bindings do it. Using `begin().base()` is
implementation-specific and doesn't work on Windows.
This should fix https://github.com/llvm/circt/issues/5336.

[OM] Use standard API for getting the base pointer from a vector.

---

lib/Conversion/CalyxToFSM/CalyxToFSM.cpp
test/Conversion/CalyxToFSM/lower-if.mlir
test/Conversion/CalyxToFSM/lower-seq.mlir
test/Conversion/CalyxToFSM/lower-while.mlir

I found this problem while learning circt during this time, and I have solved it.You can see it [here](https://github.com/llvm/circt/issues/5296).The names of the state machines generated in the calyx-to-fsm pass are all called control. This leads to a problem when designing with multiple components, where components may instantiate the state machines of other components.

[Calyx to FSM]Fix the bug when calyx multi-component design lower to fsm.

---

lib/Bindings/Python/setup.py

We are using C++17, and a recent addition to the Python bindings for the OM dialect relies on a C++17 feature. For this to compile with pybind11, we need to ensure we set the -mmacosx-version-min flag to at least version 10.14, which is where support for these C++17 features became available. By default, CMake was detecting an older version, so explicitly set this when building the wheel.

[Python] Add CMake for MacOS C++17 compatibility in wheel build.

---

docs/Dialects/FIRRTL/FIRRTLAnnotations.md

As of 5e6d68af872235203bd93e469746f91df8391020  we no longer emit the tb_seq_mems.json file. Remove mention of it from the docs.

Update FIRRTLAnnotations.md to remove reference to tb_seq_mems.json [NFC]

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLDialect.cpp
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/test.mlir

This add an operation to create a constant of string type, as well as a fold to StringAttr and a StringType materializer.

[FIRRTL] Add StringConstantOp

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/Comb/canonicalization.mlir

Due to attempts to prevent logic duplication, the generic canonicalizers do not catch this case which is in general beneficial. A separate canonicalizer is added.

[Comb] Canonicalize a + c1 + c2 into a + (c1 + c2)

---

lib/Dialect/Comb/CombFolds.cpp
lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Dialect/FIRRTL/imcp-locations.mlir

Previously we created a chain of FusedLocations that had metadata point to previous, instead append to it.
Leverage (and fix interaction with) `FusedLoc::get` behavior that decomposes/flattens (and unique's)  locs in child FusedLoc's if metadata matches (or doesn't exist, as here).
Add basic test.

[Comb][FIRRTL][Seq] Fix fusing locations to append not add as metadata.

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Fix for https://github.com/llvm/circt/issues/5351

[FIRRTL] Donot rename InstanceOp

---

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp

On one design (-Odebug), ETC was taking 600s / 1100s total, after this change only takes ~20s.
Just drop the `remove` entirely, as it'll avoid re-slicing through the same operation again (minor) and more to the point AFAICT we add the "rootOp" removed here back to the result sets in the end anyway.
Removing an element from SetVector does not scale well.

[SV][ETC] Fix perf bug removing from a SetVector of slice results.

---

lib/Analysis/DependenceAnalysis.cpp
test/Analysis/dependence-analysis.mlir

This my attempt at fixing #5284 and #4814.

[DependenceAnalysis] Check memref dependencies on each loop nest

---

include/circt/Dialect/Arc/ArcPasses.td
lib/Dialect/Arc/Transforms/InlineModules.cpp
lib/Dialect/Arc/Transforms/LowerState.cpp
lib/Dialect/Arc/Transforms/StripSV.cpp
test/Dialect/Arc/inline-modules.mlir
test/Dialect/Arc/lower-state.mlir
test/Dialect/Arc/strip-sv.mlir

Preserve instances of external modules in the arcilator pipeline rather than removing them and replacing their outputs with zero. The inputs of the extmodule act like outputs of the overall circuit, and the outputs of the extmodule act like inputs of the overall circuit. During state lowering, create write-only states for extmodule inputs (like taps) that just capture whatever the circuit applies to the extmodule, and create read-only states for extmodule outputs that the circuit only reads. This allows the user of the software model to treat extmodule ports like regular ports of the circuit and read/write the corresponding states.
Remove the extmodule stubbing in `StripSV`, since the default behavior of the read/write-only states is to be reset to zero. So if the user of the model does …

[Arc] Preserve extern modules as internal inputs/outputs

---

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code.mlir

Fix #5356. There is an edge case that ETC wrongly erase an extracted operation which is still used by (dead) module instances. This issue can be fixed by appropriately updating `opsToErase` based on `opsAiive`. `inlineInputOnly` is reordered since it depends on `opsToErase`.

[ETC] Don't erase operations used by dead module instances

---

include/circt/Dialect/FIRRTL/FIRRTLStatements.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
test/Dialect/FIRRTL/test.mlir

This adds a new statement to FIRRTL to assign a property to a property sink.  We stop allowing properties to be connected with a ConnectOp. This new operation enforces that the parent operation is a FModuleOp, and that it has static single connects, which is a good limitation to keep from using this operation inside a WhenOp.

[FIRRTL] Add property assign op instead of using connect

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-errors.fir

Don't leave to verifier, better diagnostic this way.

[FIRRTL] Explicitly reject rwprobe of types containing const.

---

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp

No known issues here but keep these up-to-date,
may be important if the operation* is re-used.
Give common expression a name while visiting.

[FIRRTL][IMDCE] Remove dead operation from live set.

---

include/circt/Dialect/FIRRTL/FIRRTLStatements.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/errors.mlir

This adds verifiers which:
1. check that a source is not a destination.
2. check that a sink if not driven more than once.

[FIRRTL] Improve PropAssignOp verifiers

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
test/Dialect/FIRRTL/canonicalization.mlir
test/Dialect/FIRRTL/errors.mlir

Per spec, need to allow define'ing refs into destinations that are less inferred than their sources.  Add an explicit ref.cast operation to express the change, keep define requiring identical types.
Future PR's will hook this up to parsing and add needed pass support.

[FIRRTL] Add RefCastOp for reset/width/const differences in refs.

---

include/circt/Dialect/FIRRTL/FIRRTLUtils.h
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
test/Dialect/FIRRTL/infer-widths.mlir

No property types have inferrable widths, so we need to teach InferWidths to gracefully ignore them. InferWidths assumes that every type is convertible to a base type by `getBaseType(FIRRTLType)`.  This function will now return null when the type is not convertible to a base type, which includes property types. Inferwidths now checks to see if the conversion to a base type was successful.

[FIRRTL][InferWidths] Skip over property types

---

include/circt/Dialect/Pipeline/Pipeline.td
lib/Dialect/Pipeline/PipelineOps.cpp
lib/Dialect/Pipeline/Transforms/ScheduleLinearPipeline.cpp
test/Dialect/Pipeline/round-trip.mlir

This signal is intended to connect to all stages within the pipeline, and is used to stall the entirety of the pipeline. It is lowering defined how stages choose to use this signal, although in the common case, a `stall` signal would typically connect to the clock-enable input of the stage-separating registers.
Future PRs will implement hardware lowerings - blocked by #5234.

[Pipeline] Add optional `stall` signal to pipelines

---

docs/Dialects/Pipeline/RationalePipeline.md
include/circt/Dialect/Pipeline/Pipeline.td
lib/Conversion/PipelineToHW/PipelineToHW.cpp
lib/Dialect/Pipeline/PipelineOps.cpp
lib/Dialect/Pipeline/Transforms/ExplicitRegs.cpp
test/Conversion/PipelineToHW/test_inline.mlir
test/Conversion/PipelineToHW/test_outlined.mlir
test/Dialect/Pipeline/Transforms/explicit-regs.mlir
test/Dialect/Pipeline/errors.mlir
test/Dialect/Pipeline/round-trip.mlir

The `pipeline.latency` operation represents an operation for wrapping multi-cycle operations. The operation declares a single block wherein any operation may be placed within. The operation is not `IsolatedFromAbove` meaning that the operation can reference values defined outside of the operation (subject to the materialization phase of the parent pipeline).
This commit includes changes to the register materialization pass (differentiating between `regs` and `pass` inputs to stages) and pipeline HW lowering. Currently, `pipeline.latency` operations are just inlined into the current insertion point.
an example pipeline:
```mlir
^bb1:
...
%out = pipeline.latency 2 -> (i32) {
%dl1 = seq.compreg %in : i32
%dl2 = seq.compreg %dl1 : i32
pipeline.latency.return %dl2 : i32
}
pipeline.stage ^bb2 …
```

[Pipeline] Add `pipeline.latency` operation

---

include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/intrinsics.mlir

Lower the `firrtl.int.clock_gate` intrinsic to a `seq.clock_gate` op.

[LowerToHW] Lower clock gate intrinsic to Seq dialect

---

lib/Dialect/FIRRTL/FIRRTLUtils.cpp
test/Dialect/FIRRTL/imconstprop.mlir

IMCP uses a helper `walkGroundTypes` to iterate over all the leaf elements of a FIRRTLType.  This change makes `walkGroundTypes` skip over property types.  In the future we will probably want to augment IMCP to perform constant propagation on property types.

[FIRRTL][IMCP] Skip over non-base types

---

include/circt/Dialect/FIRRTL/FIRRTLUtils.h
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp

This changes InferWidths to use a common pattern to filter out foreign and property types.  The `getBaseType(FIRRTLType)` function now takes a `Type` and returns null if it is not a `FIRRTLType`.  `declVars` and all three constrain functions now use `getBaseType` and a null-check to skip over foreign and property types.  This changes the behavior of `maximumOfTypes` and `unifyTypes`, but this is not a testable code path.

[FIRRTL][InferWidths] Handle foreign and prop types uniformly

---

lib/Dialect/FIRRTL/FIRRTLTypes.cpp
lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp
test/Dialect/FIRRTL/check-comb-cycles.mlir

This change adds support for property types to CheckCombLoops.  Right now property types show up as regular ports on instances and modules, and are assigned the through the PropAssignOp, which implements the ConnectLike interface. Module ports, instance ports, and connect like operations had to be updated to support FIRRTLTypes instead of just FIRRTLBaseTypes.

[FIRRTL][CheckCombLoops] Support property types

---

include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
test/Dialect/FIRRTL/test.mlir

This adds a new type to the FIRRTL dialect, BigInt.  A BigInt is a signed integer of arbitrary length.

[FIRRTL] Add BigInt property type

---

lib/Dialect/FIRRTL/Import/FIRLexer.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Import/FIRTokenKinds.def
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/parse-errors.fir

Add parsing support for FIRRTL 3.0.0 radix-specified integer literals. These are a replacement for string-encoded integer literals.  E.g., the following is the new syntax:
connect foo, UInt(0b101010)
And the following is the old syntax:
connect foo, UInt("b101010")
Gate this parsing support on being in a circuit which is marked as being 3.0.0 or later.

[FIRRTL] Add v2.4.0 Radix-specified Integer Literals

---

include/circt/Dialect/FIRRTL/FIRRTLStatements.td
lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/parse-errors.fir

Better support literal and literal/const-derived sources to "force", and use ref.cast to accommodate supported differences.
This is not required by the current FIRRTL spec, but makes using it a bit easier.
Also this handles various const scenarios re:aggregates, current code seems primarily to get ground types/literals accepted.

[FIRRTL] Support const "source" in forces, insert refcast as needed.

---

lib/Dialect/FIRRTL/FIRRTLUtils.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/parse-errors.fir

Teach emitConnect to insert ref.cast as needed.

[FIRRTL][FIRParser] Support define of non-identical refs via ref.cast.

---

include/circt/Dialect/Seq/SeqPasses.h
include/circt/Dialect/Seq/SeqPasses.td
include/circt/Firtool/Firtool.h
lib/Dialect/Seq/Transforms/CMakeLists.txt
lib/Dialect/Seq/Transforms/ExternalizeClockGate.cpp
lib/Firtool/Firtool.cpp
test/Dialect/Seq/externalize-clock-gate.mlir
test/firtool/clock-gate.fir

Add the `ExternalizeClockGate` pass which converts all `seq.clock_gate` ops in a design into instances of a `hw.module.extern`. The name and ports of the extern module can be configured through pass options. In case the module has no test enable port, the conversion adds a `comb.or` to fold the enable and test enable operands of the `seq.clock_gate` into a single enable port.

[Seq] Add clock gate conversion to extern module

---

include/circt/Dialect/FIRRTL/FIRRTLUtils.h

Now that `getBaseType` handles all types, there is no need for `getBaseTypeOrNull`.

[FIRRTL] Remove `getBaseTypeOrNull`

---

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
test/Dialect/FIRRTL/infer-widths-errors.mlir

Fix upperBoundSolution being set from bool indicating if cycle, instead of the value solved for (.first instead of .second).
Tweak how/when upper bound constraint is solved.
Fixes #5002.
Fixes #5391.

[FIRRTL][InferWidths] Fix back-prop, fix ref equality, fix upper bound.

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/ExtractClasses.cpp
test/Dialect/FIRRTL/extract-classes.mlir

Modules with input or output properties are converted to OM classes. The input properties become parameters, and the output properties become fields. The ops directly connected to output properties are moved over. As needed, this can be extended to move over whole dataflow slices, or adapted to work with ops besides connects.
The property ports and operations are removed from the FIRRTL modules, so after this pass runs, the modules only contain RTL.
This only handles the simplest cases: output properties driven from input properties and constants. Handling instances of property-containing modules will come in a future addition. This includes fixing up instantiations of mutated modules to match their declaration.
The OM type system is open, so this produces legal IR, but not IR that is …

[FIRRTL] Initial pass to extract OM classes from FIRRTL modules.

---

include/circt/Dialect/FIRRTL/FIRRTLTypes.td

This commit adds ODS class `FIRRTLPrimitiveType` which inherits FIRRTLDialectType to reduce boilerplate. At the same time, tweak summary to make it more consistent
This is a preparation commit for introducing type alias.

[FIRRTL] Introduce a helper ODS class for type declaration, NFC

---

include/circt/Dialect/HW/HWTypes.h
test/Conversion/ExportVerilog/hw-typedecls.mlir

This fixes a small bug that alias-aware type casts are not recursively applied.

[HW] Fix type casts for nested type alias

---

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
test/Dialect/FIRRTL/infer-widths-errors.mlir
test/Dialect/FIRRTL/infer-widths.mlir

Fix #5408.
Unfix #5391.
This partially reverts commit 6c013204bdc32e836d204bec40d2edb47ddcd05d.

[FIRRTL][InferWidths] Restore back-prop constraint for strictconnect.

---

include/circt-c/Dialect/OM.h
include/circt/Dialect/OM/Evaluator/Evaluator.h
integration_test/Bindings/Python/dialects/om.py
lib/Bindings/Python/OMModule.cpp
lib/Bindings/Python/dialects/om.py
lib/CAPI/Dialect/OM.cpp
lib/Dialect/OM/Evaluator/Evaluator.cpp
test/CAPI/om.c
unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp

Add the API to get the field names and iterate over an object.

[OM] Get the field names from an Object

---

include/circt/Dialect/Comb/Combinational.td
lib/Dialect/Comb/CombOps.cpp
test/Dialect/Comb/errors.mlir

ExportVerilog support in follow-up PR.

[Comb] Truth table operation

---

include/circt-c/Dialect/OM.h
integration_test/Bindings/Python/dialects/om.py
lib/Bindings/Python/OMModule.cpp
lib/Bindings/Python/dialects/om.py
lib/Bindings/Python/support.py
lib/CAPI/Dialect/OM.cpp

Converted the reference attribute and inner name ref chain to a Python tuple for OM object evaluation.

[OM] Expose ReferenceAttr to Python

---

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp

I've found that 0xFFF is not enough to always produce unique strings for constraints I'm debugging, bump a bit from 4096 to 65536 for now (still keeping it short but more bits to lower chance of collision).
Also add the result of `getFieldName()` to the debug printing for each variable to make it easier, especially for blockarguments, to match each to its origin.

[FIRRTL][InferWidths] Tweak debug printing to show names and more bits.

---

lib/Dialect/FIRRTL/Transforms/ExtractClasses.cpp
test/Dialect/FIRRTL/extract-classes.mlir

After classes are extracted from FIRRTL modules, the property ports of the module are removed. This patch extends the pass to also update instances of mutated modules, so their instantiations remain correct. It also removes modules that only existed for properties.

[FIRRTL] Clean up instances in ExtractClasses.

---

include/circt/Dialect/Pipeline/Pipeline.h
lib/Dialect/Pipeline/PipelineOps.cpp
lib/Dialect/Pipeline/Transforms/ExplicitRegs.cpp
test/Dialect/Pipeline/Transforms/explicit-regs.mlir
test/Dialect/Pipeline/errors.mlir

Adds a bunch more verification to the `pipeline.scheduled` and `pipeline.latency` ops, as well as fixing the register materialization pass:
* The register materialization pass has now been modified to  accomodate arbitrarily nested operations within each stage, which is a superset of the support required for `pipeline.latency`, in case operations in the inner body of the `pipeline.latency` op references values defined outside of its stage.

[Pipeline] Add verifiers and fix register materialization pass

---

include/circt/Dialect/Pipeline/Pipeline.td
include/circt/Dialect/Pipeline/PipelineInterfaces.td
lib/Conversion/PipelineToHW/PipelineToHW.cpp
lib/Dialect/Pipeline/PipelineOps.cpp
lib/Dialect/Pipeline/Transforms/ExplicitRegs.cpp
lib/Dialect/Pipeline/Transforms/ScheduleLinearPipeline.cpp
test/Conversion/PipelineToHW/test_inline.mlir
test/Conversion/PipelineToHW/test_outlined.mlir
test/Dialect/Pipeline/Transforms/explicit-regs.mlir

`ext` inputs are inputs which are accessible in any pipeline stage, and which will never be registered during register materialization. If you imagine a pipeline as signals going from left to right with registers in between, `ext` inputs are inputs that hook in from the top or bottom, into any pipeline stage.
In hardware (outlined) lowering, the external inputs are only provided to stages which actually reference them:
```mlir
hw.module @testSingleWithExt(%arg0: i32, %ext1: i32, %clk: i1, %rst: i1) -> (out0: i32, out1: i32) {
%0:2 = pipeline.scheduled(%arg0, %arg0) ext (%ext1 : i32) clock %clk reset %rst : (i32, i32) -> (i32, i32) {
^bb0(%a0: i32, %a1 : i32, %ext0: i32):
%true = hw.constant true
%1 = comb.sub %a0, %a0 : i32
pipeline.stage ^bb1 regs(%1 : i32) enable %true
^bb1(%6: i32):
// …
```

[Pipeline] Add "ext" inputs to pipelines

---

lib/Reduce/CMakeLists.txt

Primary motivation is to fix header-gen dependence (before this change, this includes header before they're gen'd) but since this uses both `firrtl::` and `hw::` bits link too.

[Reduce] Add missing build deps on HW/FIRRTL dialects.

---

lib/Bindings/Python/dialects/om.py

Absolute paths break PyCDE (and theoretically any other lib which embeds CIRCT in its own namespace).

[Python] Fix import path

---

docs/PyCDE/basics.md
frontends/PyCDE/src/module.py
frontends/PyCDE/test/test_polynomial.py

External modules with parameters were being instantiated without the parameters.

[PyCDE] Fix parameterized extern mods

---

include/circt/Dialect/Comb/CMakeLists.txt
include/circt/Dialect/Comb/CombPasses.h
include/circt/Dialect/Comb/Passes.td
include/circt/InitAllPasses.h
lib/Dialect/Comb/CMakeLists.txt
lib/Dialect/Comb/Transforms/CMakeLists.txt
lib/Dialect/Comb/Transforms/LowerComb.cpp
lib/Dialect/Comb/Transforms/PassDetails.h
tools/circt-opt/CMakeLists.txt

Some operations in the comb dialect (e.g. `comb.truth_table`) are not directly supported by ExportVerilog. They need to be lowered into ops which are supported. There are many ways to lower these ops so we do this in a separate pass. This also allows the lowered form to participate in optimizations like the comb canonicalizers. This change is just to introduce the pass boilerplate. It currently doesn't do anything.

[Comb] Lower comb pass boilerplate

---

lib/Dialect/FIRRTL/FIRRTLUtils.cpp
test/Dialect/FIRRTL/infer-widths-errors.mlir

This adds support for enumeration types to `getFieldName`, which is commonly used to print the access path to a field in an aggregate.  This function is used to report error messages in InferWidths.
Fixes #5324

[FIRRTL] Support EnumTypes in error messages

---

include/circt/Conversion/Passes.td
lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp
lib/Conversion/MooreToCore/CMakeLists.txt
lib/Dialect/Arc/Transforms/CMakeLists.txt
lib/Dialect/Calyx/CMakeLists.txt
lib/Dialect/LLHD/Transforms/CMakeLists.txt
lib/Dialect/MSFT/Transforms/MSFTLowerConstructs.cpp
lib/Dialect/Seq/SeqOps.cpp
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
lib/Transforms/CMakeLists.txt
lib/Transforms/MapArithToComb.cpp
test/Conversion/ArcToLLVM/lower-arc-to-llvm.mlir
tools/arcilator/CMakeLists.txt
tools/arcilator/arcilator.cpp
tools/circt-opt/CMakeLists.txt
tools/circt-opt/circt-opt.cpp
tools/handshake-runner/CMakeLists.txt
tools/handshake-runner/handshake-runner.cpp
tools/llhd-sim/llhd-sim.cpp

PTECH-747: llvm bump on circt. Found 2 errors.

---

docs/Dialects/Seq/RationaleSeq.md
include/circt/Dialect/Seq/SeqOps.td
lib/Dialect/Seq/SeqOps.cpp
test/Dialect/Seq/errors.mlir
test/Dialect/Seq/round-trip.mlir

The `seq.fifo` operation intends to capture the semantics of a FIFO which eventually map to some form of on-chip resources. By having a FIFO abstraction, we provide an abstraction that can be targeted for target-specialized implementations, as well as default behavioral lowerings (based on `seq.hlmem`).
The `seq.fifo` in- and output values consists of:
- **Inputs**:
- clock, reset
- input data
- read/write enable
- **Outputs**:
- output data
- full, almost full, empty, almost empty flags
To start with, the FIFO operation is configurable with the following parameters:
1. Depth (cycles)
2. Differing in- and output widths (e.g. write `i32`, read 2x`i16`).
3. Almost empty/full thresholds (optional). If not provided, these will
be asserted when the FIFO is empty/full.
Generally speaking, …

[Seq] Add `seq.fifo` ODS and rationale

---

lib/Dialect/Arc/CMakeLists.txt
lib/Dialect/FIRRTL/CMakeLists.txt
lib/Dialect/HW/CMakeLists.txt

I've heard from someone who ported CIRCT main to work with mlir-16 that the LLVM cmake checks complain that there are cpp files not included in any library. I'm not sure if that's caused by changes in the LLVM cmake config since then or if generally all cpp files in that directory should be marked optional when there are multiple libraries declared in a CMakeLists.txt.
Could someone with more CMake knowledge take a look if that change makes sense?

[CMake] Make cmake config more reliable?

---

include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
test/Dialect/FIRRTL/test.mlir

This commit adds minimal changes BaseTypeAliasType for base type alias.
Implement mlir parser/printer, storage and methods for FIRRTLBaseType and FieldIDTypeInterface.
Add a very simple round trip test since several changes are still required to use type alias in operations.
This doesn't include `RecursiveProperty` changes and `FIRRTLBaseType::getAnonnymousType` which requires more broader changes.

[FIRRTL] Add BaseTypeAliasType

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

Fix https://github.com/llvm/circt/issues/5424. We use `'` to emit packed constant arrays but some tools dislike it. Maybe we can create a lowering option for it, but I think it's  simpler to just remove `'` globally.

[ExportVerilog] Remove array literal

---

lib/Dialect/FIRRTL/Transforms/InferResets.cpp
test/Dialect/FIRRTL/infer-resets.mlir

Update these as operations that cannot have types inferred from inputs, drop (incomplete) code handling while propagating through SSA use/def graph.  In order to support updating in this way, we'd need to walk the source/dest type and update modulo the const structure present on each.
Luckily don't need to, this portion is for flowing through operations not explicitly handled as part of the traced network. ConstCast is handled this way, and so its destination type can be fixed up using `updateReset()` earlier in the function.
Fix reset inference of const-cast involving aggregates, add test.
Fixes #5333.

[FIRRTL][InferResets] Fix reset inference through const cast.

---

.github/workflows/buildAndTestWindows.yml

We mostly just want the installed copy of LLVM,
so extract the single build file required and nuke the build directory before proceeding.
The build directory is not used after this point,
so we can reclaim the disk space it uses.

[CI][Win] Reduce peak disk usage after LLVM rebuild.

---

include/circt/Dialect/Seq/CMakeLists.txt
include/circt/Dialect/Seq/SeqAttributes.h
include/circt/Dialect/Seq/SeqAttributes.td
include/circt/Dialect/Seq/SeqDialect.td
include/circt/Dialect/Seq/SeqOps.h
include/circt/Dialect/Seq/SeqOps.td
include/circt/Dialect/Seq/SeqTypes.td
lib/Dialect/Seq/CMakeLists.txt
lib/Dialect/Seq/SeqAttributes.cpp
lib/Dialect/Seq/SeqDialect.cpp
lib/Dialect/Seq/SeqOps.cpp
test/Dialect/Seq/canonicalization.mlir
test/Dialect/Seq/firmem.mlir

Add a new `FirMemOp` to the Seq dialect to capture the semantics of FIRRTL memories at the HW level. The intent behind this change is the same as for `FirRegOp`, which captures the specifics of FIRRTL registers but within the type system and abstraction level of the HW dialect.
Memories are represented as a declaration with the `seq.firmem` which returns a value representing the memory itself. This value is of type `!seq.firmem<12 x 42, mask 2>` which represents an opaque handle to the memory; it encodes the depth (`12`) and width (`42`) of the memory, plus an optional mask if the memory is to support masked writes.
Memory ports are represented as separate operations:
- `seq.firmem.read_port`
- `seq.firmem.write_port`
- `seq.firmem.read_write_port`
These operations take the memory itself …

[Seq] Add FirMem op

---

include/circt/Dialect/FIRRTL/FIRParser.h
lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/firtool/locators-diagnostics.fir
tools/firtool/firtool.cpp

Exploring optionally including input file locators as well as `@info` locators, here's a POC.  WDYT?
Inject a quick-n-dirty diagnostic handler that finds ".fir" locators and attaches each to in-flight diagnostic as notes before passing on to normal handler (`SourceMgrDiagnosticHandler` variant).
(EDIT: Updated to just attach all file-line-col locations as notes)
Add option to firtool (and FIRParser) to control handling of info locators, with option of attaching a fused location with the info and source file locations.
------
```firrtl
circuit Error:
module Error:
output xa: UInt<1>
output ya: UInt<1>
wire x : { boop: { foo: { a: UInt<1>, b: UInt<2>}, bar: { a: UInt<1> }}} @[path/to/Foo.scala 273:69]
wire y : { boop: { foo: { a: UInt<1>, b: UInt<2>}, bar: { a: UInt<1> }}} ; (no locator)
; …
```

[FIRRTL] Options for using both @info and .fir, attach .fir as notes.

---

lib/Dialect/Seq/SeqOps.cpp

The canonicalizer no longer accesses the op after it has been erased.

[Seq] Fix FirMemReadWriteOp::canonicalize

---

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code.mlir

Fix #5465. This fixes an issue that constants used by both designs and testcode.

[SVExtractTestCode] Clone constants even when used by designs as well

---

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code.mlir

Fix #5459. Use namehints and name attributes on module boundary as port names of extracted modules. Also improve instance op logic a bit to avoid unnecessary linear search.

[ETC] Use name/namehint as a port name

---

lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Dialect/Seq/clock-gate.mlir

... for those times when you don't want to externalize a clock gate. My immediate use for this is to not have to worry about placing clock gate modules into output/search folders when running integration tests for ops that use clock gates. Obviously, the clock gate externalization pass can be run prior to SV lowering to skip this. Secondly, i prefer that all ops have _some_ way of reaching emission without having to worry about external collateral.
The implementation exports as the following `sv`:
```sv
module cg1(
input  clk,
enable,
output gclk
);
reg cg_en_latch;
always @(edge clk or edge enable) begin
if (~clk)
cg_en_latch <= enable;
end
assign gclk = clk & cg_en_latch;
endmodule
module cg2(
input  clk,
enable,
test_enable,
output gclk
);
wire _GEN = enable | test_enable;
reg …
```

[SeqToSV] Add `clock_gate` lowering

---

include/circt/Conversion/Passes.td
include/circt/Dialect/Pipeline/Pipeline.td
include/circt/Dialect/Pipeline/PipelineInterfaces.td
integration_test/Dialect/Pipeline/simple/simple.mlir
integration_test/Dialect/Pipeline/simple/simple.py
lib/Conversion/PipelineToHW/PipelineToHW.cpp
lib/Dialect/Pipeline/PipelineOps.cpp
lib/Dialect/Pipeline/Transforms/ExplicitRegs.cpp
lib/Dialect/Pipeline/Transforms/ScheduleLinearPipeline.cpp
test/Conversion/PipelineToHW/test_ce.mlir
test/Conversion/PipelineToHW/test_inline.mlir
test/Conversion/PipelineToHW/test_outlined.mlir
test/Dialect/Pipeline/Transforms/explicit-regs.mlir
test/Dialect/Pipeline/Transforms/schedule-linear-pipeline.mlir
test/Dialect/Pipeline/errors.mlir
test/Dialect/Pipeline/round-trip.mlir

This commit adds an explicit 'go' signal to the pipeline abstraction. This signal is used to indicate when the pipeline should start. The signal will propagate through each stage as the stage valid signal. As a result of this, each stage now has a `s#_valid : i1` signal as the last value in its block argument list. This value can be used within each stage for any operations which requires access to the pipeline control circuitry.
Given that pipeline stage validity is now explicit within the block arguments of a stage, a `pipeline.stage` operation no longer has an `enable` signal. As a small 'bugfix' here, a `seq.clock_gate` is emitted to gate the pipeline stage separating registers on the pipeline stage valid signal.

[Pipeline] add 'go' signal to pipeline

---

include/circt/Dialect/Seq/SeqPasses.h
include/circt/Dialect/Seq/SeqPasses.td
lib/Dialect/Seq/Transforms/CMakeLists.txt
lib/Dialect/Seq/Transforms/LowerFirMem.cpp
lib/Dialect/Seq/Transforms/LowerSeqHLMem.cpp
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
lib/Dialect/Seq/Transforms/PassDetails.h
lib/Firtool/Firtool.cpp
test/Dialect/Seq/lower-firmem.mlir

Add the `LowerFirMem` pass which lowers `seq.firmem` ops to a corresponding `hw.module.generated` op. The pass intends to reflect what `LowerToHW` does in `lowerMemoryDecls`: it collects a list of memory ops in the design, distills them down into memory parameters, deduplicates those parameters, creates one `hw.module.generated` op for each unique memory config, and replaces the memory ops with instances of this generated module.
The `LowerFirMem` pass is intended as an intermediate solution to allow `seq.firmem` to be lowered through `HWMemSimImpl` without changing the latter's implementation. Existing tools that have passes operating on `hw.module.generated`-style memories can simply run the `LowerFirMem` pass and have the new `seq.firmem` work with their existing pipeline.
A few …

[Seq] Lower FirMemOp to HWModuleGeneratedOp

---

include/circt-c/Dialect/CHIRRTL.h
include/circt-c/Dialect/FIRRTL.h
lib/CAPI/Dialect/CHIRRTL.cpp
lib/CAPI/Dialect/CMakeLists.txt
lib/CAPI/Dialect/FIRRTL.cpp

This PR adds C API for FIRRTL and CHIRRTL dialects, which allows foreign languages to construct FIRRTL through MLIR C API.

[FIRRTL][CHIRRTL] Add dialect C API

---

lib/Dialect/FIRRTL/Transforms/ExtractClasses.cpp
test/Dialect/FIRRTL/extract-classes.mlir

This finished support for handling InstanceOps with properties by converting them into ObjectOps. The existing traversal that builds up fields on ClassOps is maintained, but a special case is added for when the property comes from an InstanceOp.
Using a cache to allow re-use, ObjectOps are created, and ObjectFieldOps are created to extract their outputs. Some bookeeping is necessary to ensure the relevant property ops feeding the instance are cloned, the IRMapping is kept up to date, and the right property ops are cleaned up. Otherwise, the rest of the pass is unchanged.

[FIRRTL] Support instances of property modules in ExtractClasses.

---

include/circt-c/Dialect/CHIRRTL.h
include/circt-c/Dialect/FIRRTL.h
lib/CAPI/Dialect/CHIRRTL.cpp
lib/CAPI/Dialect/FIRRTL.cpp

Based on #5472:
- Make C API names more consistent with other dialects.
- Change some string types to `MlirIdentifier`.

[FIRRTL][CHIRRTL] C API rename and change some types

---

.github/workflows/uploadFirrtlReleaseArtifacts.yml

* Add Windows (firtool.exe)
* Remove Ubuntu 18.04 (runner is deprecated)
* Name archives based on OS and architecture
* linux-x64, macos-x64, linux-x64
* Windows uses .zip, Linux and MacOS use .tar.gz
* Add sha256 hashes for archives
I tried to keep the build flows as similar as possible, which included making the cmake commands work across Linux/Mac (using bash) and Windows (using powershell). Windows _does_ have bash and it is called out as the shell on a few build steps, but `./utils/find-vs.ps1` is written in powershell and is needed to set up the Visual Studio environment needed to build firtool so I had to keep the cmake steps as powershell.
You can see what the new artifacts look like here https://github.com/jackkoenig/circt/releases/tag/firtool-1.44.0-jack (at time of opening this …

Add support for Windows and revamp FIRRTL release artifacts

---

include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/test.mlir

Add two new property-aggregate types: `firrtl.list` and `firrtl.map`.
Ops to create values of these types and parser support will follow.

[FIRRTL][Properties] Add List<T>, Map<K, V> types.

---

integration_test/circt-lec/hw.mlir
lib/LogicalEquivalence/Solver.cpp

Currently the solver of the equivalence check creates a separate _not equal_ constraint for each output of the processed module(s). Consequently, the constraint system becomes unsatisfiable as soon as at least one of the outputs is equivalent, causing the equivalence check for the entire module to pass. This PR changes the constraints to make them unsatisfiable iff all outputs are equivalent, by solving for the disjunction of the _not equal_ expressions.
This also adds a test case, checking that two non-equivalent circuits do not pass the comparison. This turned out to be more complicated than I was expecting. When checking the output of `circt-opt` for `c1 != c2` the test will still fail, because it produces a non-zero exit code for non-equivalent circuits. The best thing I could come up …

[circt-lec] Fixed equivalence check for multiple outputs

---

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
test/Dialect/FIRRTL/emit-metadata.mlir
test/firtool/memoryMetadata.fir
test/firtool/memoryMetadata.fir.anno.json
test/firtool/prefixMemory.fir

Use symbols to emit memory metadata, this ensures that the instance names respect any renaming due to `ForceNameAnnotation`. Since memory instance cannot be renamed, use it as verbatim, this ensures that the pre-extract paths for seq mems are used.
Fixes https://github.com/llvm/circt/issues/5469
For reference, the previous change related to ExtractSeqMems, https://github.com/llvm/circt/pull/3123

[FIRRTL][CreateSifiveMetadata] Use symbols for memory metadata

---

lib/Dialect/FIRRTL/Export/FIREmitter.cpp
test/Dialect/FIRRTL/emit-basic.mlir

Update the FIRRTL exporter to properly escape literal identifiers.

[FIRRTL] Export literal identifiers correctly

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/Comb/CombFolds.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

This adds SV attributes support for comb mux op. Mux canonicalization is disabled if there is SV attribute on the op. SV spec 11-1 defines SV attributes syntax for mux.

[Comb][ExportVerilog] Support SV attributes for MuxOp

---

.github/workflows/buildAndTest.yml
.github/workflows/buildAndTestWindows.yml
.github/workflows/nightlyIntegrationTests.yml
.github/workflows/shortIntegrationTests.yml
.github/workflows/trackLLVMChanges.yml
.github/workflows/uploadFirrtlReleaseArtifacts.yml

I would like this change on any firtool branches that may have longer term support, especially if they are used by Chisel, and Chisel 3.6.0 uses firtool 1.37.0.
This is just backporting some enhancements to 1.37:
* https://github.com/llvm/circt/pull/5268
* https://github.com/llvm/circt/pull/5470
Basically using v3 of some Github actions APIs and:
* Add Windows (firtool.exe)
* Remove Ubuntu 18.04 (runner is deprecated)
* Name archives based on OS and architecture
* linux-x64, macos-x64, linux-x64
* Windows uses .zip, Linux and MacOS use .tar.gz
* Add sha256 hashes for archives

[firtool 1.37] Enhanced Firtool Release Artifacts

---

include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/parse-errors.fir

Add verifiers for both MLIR and FIR + tests.
Fixes #5494 .

[FIRRTL] Verify OpenAggs, fix agg-of-properties.

---

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp

This change removes some cached information related to how module ports relate to instance results.
`resultPortToInstanceResultMapping`: This tracks a mapping from a block argument to all instance results that it corresponds to.  We can instead use the instance graph to go from a module to all instances of that module, and grab the instance result we are interested in.  There is a small difference in that instead of visiting only marked instances, we now visit every instance.  This is a NFC but it could be slower if there are many unreachable modules in the hierarchy with dead instances, but that is very uncommon and currently illegal in the FIRRTL spec.
`lazyLiveInputPorts`: This tracks which ports of an instance should be marked live if the instance op should be marked live. This …

[FIRRTL][IMDCE] Remove some cached state

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir

When we lower input ports on instances, if there are zero or multiple writers to the input port, we create a wire and use that as the operand to the new instance operation.  There was a change to this code to use `hw::WireOps`, which have their input value as an operand.  Since `hw::WireOp`'s cannot have multiple writers, the code is now "the last writer wins".  The wire's input is updated  when processing connect-like operations - we will replace the previous writer to the wire.
We already have a helper in this code to gracefully handle this situation called `createBackedge`.  A backedge is a placeholder for a value which will be determined later.  We can use a backedge as an operand to the lowered instance op, and when we find the connect operation driving a value to the old instance …

[LowerFIRRTLToHW] Create less wires with instance ports

---

test/Dialect/FIRRTL/imdce.mlir

This adds a test to show the behaviour when a dead module instantiates a child module, and uses its output port, that the dead module should not demand the child's port and keep it alive. Technically FIRRTL does not allow dead modules in the circuit, but this pass already supports this.

[FIRRTL][IMDCE] Add test for dead output ports, NFC

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp

This changes LowerFIRRTLToHW to use backedges instead of temporary wire operations.  The temporary wires were guaranteed to be optimized away. Now we slightly more gracefully handle the, technically illegal, cases of these wires having no value driven to them.  This change is NFC in the FIRRTL pipeline where these invariants have already been verified. We can remove the infrastructure for creating these temporary wires, as it is not used anymore.

[LowerFIRRTLToHW] Use backedges over temporary wires, NFC

---

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
test/Dialect/FIRRTL/imdce.mlir

As pointed out in https://github.com/llvm/circt/pull/5512, if there was an unreachable module from the toplevel, IMDCE could leave unrealized conversion casts which are intended only for dummy values. Even though it won't practically happen, it would be reasonable to perform such DCE in IMDCE.

[IMDCE] Delete unreachable modules

---

lib/Dialect/Arc/Transforms/GroupResetsAndEnables.cpp

This fixes a dominance issue that can occur in GroupResetsAndEnables. Unfortunately I haven't been able to reduce the test case from a larger design (tried using circt-reduce).
There are two fixes:
* It should not fail if it can't get a ClockTreeOp, but instead should just return that nothing was changed.
* It should use `definition->getUsers()` to check for dominance, since `definition` is the operation that will actually be moved. If it generates multiple results, the place it is being moved to must dominate all those results, not just the operand used in the block.

[Arc] Fix dominance issue in GroupResetsAndEnables

---

.github/workflows/uploadFirrtlReleaseArtifacts.yml
include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Greatly reduces the number of ops in real designs
```
wc -l foo.mlir foo5.mlir 
2247057 foo.mlir
2057784 foo5.mlir
```

[FIRRTL] Canonicalize reductions looking through casts of various forms

---

lib/Dialect/HW/InstanceGraphBase.cpp

In large designs, it takes non-negligible amount of time to construct instance graphs (especially before dedup in firtool pipeline) since it was visiting entire circuits twice sequentially. This PR removes an unnecessary walk, and make instance operations accumlation parallel. It reduced graph construction time by 40% in large designs. (3~4% reduction in the entire execution time)
Before:
```
50.1090 (  1.6%)   50.1090 (  6.1%)    LowerFIRRTLAnnotations
17.6776 (  0.6%)   17.6776 (  2.2%)      (A) circt::firrtl::InstanceGraph
16.6704 (  0.5%)   16.6704 (  2.0%)    LowerIntrinsics
16.6657 (  0.5%)   16.6657 (  2.0%)      (A) circt::firrtl::InstanceGraph
```
After:
```
38.6719 (  1.2%)   38.6719 (  5.1%)    LowerFIRRTLAnnotations
9.4730 (  0.3%)    9.4730 (  1.2%)      (A) …
```

[InstanceGraph] Speed up instance graph constructions, NFCI

---

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp

In the preprocess there seems to be an unintended use of `walk`.  Currently we walk the entire circuit three times in the pre-process. A walk in the post-order doesn't return early even when `skip()` was returned (see mlir/IR/Visitor.h https://github.com/llvm/llvm-project/blob/ecfc2328ea8a1180170827d300674d0cf75a20d0/mlir/include/mlir/IR/Visitors.h#L280-L281). I think pre-order was actually intended behaivior there. This commit just replaces walks with `getOps`. With this commit InferWidth should visit the entire IR only once.

[InferWidths] Remove expensive walks, NFC

---

include/circt/Dialect/FIRRTL/FIREmitter.h
include/circt/Dialect/FIRRTL/FIRParser.h
lib/CAPI/ExportFIRRTL/ExportFIRRTL.cpp
lib/Dialect/FIRRTL/Export/FIREmitter.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/emit-basic.mlir

Change the FIRRTL emitter to use v3.0.0 of the FIRRTL specification.
Logic for emitting an older version of the spec is still preserved.  There
is no option for choosing the spec version from the command line right
now.

[FIRRTL] Change emitter to v3.0.0

---

frontends/PyCDE/src/common.py
frontends/PyCDE/src/fsm.py
frontends/PyCDE/src/module.py
frontends/PyCDE/test/test_fsm.py
frontends/PyCDE/test/test_fsm_errors.py
lib/Bindings/Python/dialects/_fsm_ops_ext.py

Long delayed, this should fix #5488. It also removes the shorthand syntax.

[PyCDE] Upgrade FSMs to new module style

---

include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
lib/Dialect/FIRRTL/FIRRTLTypes.cpp

This adds `anonymousType` to type storages and define `getAnonymousType` to provide a convenient way to get structural information. Also add `containsTypeAlias` to recursive type prop.

[FIRRTL] Add containTypeAlias to type storage and define `getAnonymousType`

---

include/circt/Dialect/Pipeline/PipelineOps.td
lib/Conversion/PipelineToHW/PipelineToHW.cpp
lib/Dialect/Pipeline/PipelineOps.cpp
lib/Dialect/Pipeline/Transforms/ExplicitRegs.cpp
lib/Dialect/Pipeline/Transforms/ScheduleLinearPipeline.cpp
test/Conversion/PipelineToHW/test_ce.mlir
test/Conversion/PipelineToHW/test_clockgates.mlir
test/Conversion/PipelineToHW/test_inline.mlir
test/Conversion/PipelineToHW/test_outlined.mlir
test/Dialect/Pipeline/Transforms/explicit-regs.mlir
test/Dialect/Pipeline/errors.mlir
test/Dialect/Pipeline/round-trip.mlir

Also changes to that the `clock-gate-regs` options actually implements clock gates instead of a `seq.comp_reg.ce` operation. To cover all cases, i think there needs to be three kinds of gating implementations - clock gate, clock enable (`seq.compreg.ce`) and input muxing. The first and last are what we have now.

[Pipeline] Add per-register clock gating

---

lib/Dialect/FIRRTL/Transforms/InferResets.cpp

Async reset annotations are currently gathered sequentially. We can instead parallelize the accumulation and construct a global map later. This improvement leads to 10% reduction in InferReset(1% of the entire execution time).

[InferReset] Parallelize the annotations accumulation, NFC

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
lib/Dialect/FIRRTL/Export/FIREmitter.cpp
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
test/Dialect/FIRRTL/SFCTests/width-spec-errors.fir
test/Dialect/FIRRTL/emit-basic.mlir
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/infer-resets.mlir
test/Dialect/FIRRTL/infer-widths.mlir
test/Dialect/FIRRTL/legacy-wiring.mlir
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/parse-locations.fir
test/Dialect/FIRRTL/parse-version.fir

Unclear what this models/means, and instead of doubling down on workarounds lets drop this until we sort out
what this is and how it should work.
Fixes #5391.
(dropping the introduced back-propagation behavior)
This partially reverts commit 63d94ea003dcd0ed6c2f3da5580728569f2b346d.
Keep the parts of #5047 that aren't related to this op, such as use of emitConnect throughout code.
StrictConnect still keeps the restriction regarding passive types added in that commit, but now requires the operands to be sized as well.
We now need logic to emit ConstCast before a "connect", which is added (under existing/modified tests).

[FIRRTL] Remove UninferredWidthCastOp for now.

---

include/circt/Dialect/HW/HWOpInterfaces.h
include/circt/Dialect/HW/HWOpInterfaces.td
lib/Conversion/PipelineToHW/PipelineToHW.cpp

... based on a name-to-index `DenseMap` built from the `hw::ModulePortInfo` struct. Needed in various places, and not willing to wait for https://github.com/llvm/circt/pull/5350.

[Support] Add a 'by-name' lookup for HWModuleLike ops

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/Comb/canonicalization.mlir

Fixes https://github.com/llvm/circt/issues/5531.
TLDR: `narrowOperationWidth()` copies attributes to a `comb.concat` operation, which is optimized away in a later step.
The fix is simple: do not copy the attributes to the intermediate `comb.concat` op but instead to the width narrowed operation.

[Comb][Canonicalize] keep attributes during op width narrowing

---

include/circt/Dialect/Pipeline/PipelineOps.td
lib/Conversion/PipelineToHW/PipelineToHW.cpp
lib/Dialect/Pipeline/PipelineOps.cpp
lib/Dialect/Pipeline/Transforms/ScheduleLinearPipeline.cpp

Also renames the data output field of the op to avoid aliasing with the built-in `getResultTypes()` that is the reason this bug went unnoticed.

[Pipeline] Fix `ScheduledPipelineOp` builder

---

lib/Dialect/Seq/SeqOps.cpp
test/Dialect/Seq/canonicalization.mlir

This adds a folder for clock gates which removes clock gates that are transitively enable'd by other clock gates in a clock gate hierarchy.

[Seq] Canonicalize transitive clock gates

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
test/Dialect/FIRRTL/canonicalization.mlir

This fixes a bug that `andr(pad(x:sint, n))` is canonicalized into `0`.

[FIRRTLFolds] Fix `andr(pad(x:sint, n)) -> andr(x)` canonicalization

---

tools/arcilator/arcilator-header-cpp.py

Since the default depth is -1 and the script checks `depth > 0`, currently the header generator does not generate any values below the top-level hierarchy by default. This update allows arbitrarily deep hierarchy generation when the depth is -1 (I think this was probably the intended behavior). Alternatively, we could set the default depth to some large value.
cc @fabianschuiki

[Arc] Fix header generation when depth is -1

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp

This avoids stack overflow when parsing deeply nested whens. This PR creates a bump allocator in the module context and allocate subparser with it.

[FIRParser] Allocate subParser on heap

---

include/circt/Dialect/FIRRTL/FIRRTLOps.h
include/circt/Dialect/FIRRTL/FIRRTLStatements.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Support/CustomDirectiveImpl.h
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
lib/Support/CustomDirectiveImpl.cpp
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/test.mlir

This PR modifies strictconnect's verifier/parser/printer to allow different (but structurally equivalent) types as operands. In mlir textual format, print src type only when dest type != src type so there is no change in tests.

[FIRRTL] Allow strictconnect to have different but structurally equivalent types

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR-errors.mlir
test/Dialect/FIRRTL/lowerXMR.mlir

Implementation:
Extend the refSend list node to support recording indexing
along the resolution path, in addition to its current sole
use of tracking symbols of instances along the path.
When resolving, gather these indexing operations and generate
the appropriate string suffixes for each to narrow the origin
reference accordingly.
MemTap now use this for creating the right indexing suffix (under test).
Notes:
This is not the more general support needed once we support
input probes (and more complicated flow of probes through
the design) but build on existing requirements/assumptions
here and throughout compiler to get this working for the
more straightforward cases.
Known limitations:
Indexing through an input probe will cause resolution error.
* Given input probes are rejected during …

[FIRRTL][LowerXMR] Support ref.sub. 

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/parse-errors.fir

Chase to defining op, and (re-)index using ref.sub's.

[FIRRTL][FIRParser] Parse rwprobe to element of aggregate.

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR.mlir

Extend zero-width-ref pruning to handle Forceable  + force/release ops,
and test nothing breaks if ref.sub to a zero-width value.
Fixes #5552 .

[FIRRTL][LowerXMR] Include forceable + force/release ops in zero-width handling.

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/Seq/Transforms/LowerFirMem.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-memories.mlir
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/SFCTests/load-memory-from-file.fir
test/Dialect/Seq/lower-firmem.mlir
test/firtool/chirrtl.fir
test/firtool/prefixMemory.fir

Make `LowerToHW` emit `seq.firmem` operations for memories instead of emitting generator ops. These memory ops are then lowered to generator ops later in the firtool pipeline through the Seq `LowerFirMem` pass, which is already in place.
The main change is replacing the generator op creation in `LowerToHW` with code that constructs the FirMem and associated ports, which is conceptually simpler.
This commit also outlines memory lowering tests into a separate `lower-to-hw-memories.mlir` file and combines it with a few more test cases.
The only change to firtool Verilog output should be a loss of the `_combMem` suffix on memories.
**Follow-up work:** Once this lands, `seq.firmem` and `seq.hlmem` can be collapsed into a unified `seq.mem`. Passes like HWMemSimImpl (and at least one …

[FIRRTLToHW] Lower memories to seq.firmem

---

integration_test/Dialect/Pipeline/simple/simple.mlir
lib/Conversion/PipelineToHW/PipelineToHW.cpp
test/Conversion/PipelineToHW/test_clockgates.mlir
test/Conversion/PipelineToHW/test_inline.mlir
test/Conversion/PipelineToHW/test_outlined.mlir

Will emit `CompRegOp` instead of `CompRegClockEnabledOp`s for pipelines without stall signals.
In cases where a register has hierarchical clock gates specified (as in `test_clockgates.mlir`) but the `"clock-gate-regs"` option for `lower-pipeline-to-hw` is **NOT** set, then these hierarchical clock gates will be ignored.

[PipelineToHW] Don't CE pipeline regs in non-stallable pipelines

---

lib/Dialect/Seq/Transforms/LowerFirMem.cpp
test/Dialect/Seq/lower-firmem.mlir

Currently the `LowerFirMem` pass inserts `HWModuleGeneratedOp`s all the way at the top of the file. This is problematic since passes like FIRRTL's `LowerToHW` will produce an SV preamble with macro definitions that the memories want to rely on. Inserting the memory modules at the top of the file puts them before the macro definitions that they rely on.
This commit changes the insertion point of memory modules, making them appear as late as possible in the IR, basically just before the first module that instantiates the memory. This ensures that the memory modules are always placed after that preamble and makes their location more logical within the IR.

[LowerFirMem] Insert memory modules before first user

---

lib/Dialect/Pipeline/PipelineOps.cpp
test/Dialect/Pipeline/Transforms/schedule-linear-pipeline.mlir

This is a fix for #5584.  `ScheduledPipelineOp::build` is changed to add operands in the same order that `PipelineOps.td` expects.

Fix ordering of operands in ScheduledPipelineOp::build

---

include/circt/Dialect/HW/HWTypes.td
include/circt/Dialect/SV/SVExpressions.td
include/circt/Dialect/SV/SVTypes.td
test/Conversion/ExportVerilog/sv-dialect.mlir

Closes #5576.
Moving this since in the (near) future the verif dialect and HW module parameterization will be using string types.

[HW][SV] Move string type from SV to HW

---

lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
test/Dialect/FIRRTL/emit-omir-errors.mlir

Current behavior is to silently use the first we happen to discover.
Reachable by putting OMIRTracker on an aggregate, which LowerTypes will clone out to the lowered elements (?).
Presently, in practice, we tend to resolve these trackers to the first element of the aggregate.

[FIRRTL][OMIR] Detect and error if tracker resolution is ambiguous.

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types-issue-5592.mlir

[FIRRTL][LowerTypes] Don't silently drop symbols on type-lowered mem's.

---

integration_test/Bindings/Python/support/conversion.py
lib/Bindings/Python/support.py

This codepath assumes when the input attribute is not an Attribute, it has a value member. This is the case for things like StringAttr, but not for ArrayAttr. This popped up because upstream MLIR has been working to return downcasted concrete Attribute subclasses in more situations, so APIs that previously returned an Attribute might now return an ArrayAttr. A simpler testcase also reveals the issue. I've updated this path to also ensure that a value member exists before using it, and otherwise fall back to the generic code path.

[Python] Ensure attribute_to_var only accesses value when legal.

---

lib/Dialect/FIRRTL/FIRRTLTypes.cpp

This PR adds `getAsKey` methods to type storages. Close https://github.com/llvm/circt/issues/5568

[FIRRTL] Add `getAsKey` to type storages, NFC

---

include/circt/Dialect/OM/OMOps.td
lib/Dialect/OM/OMOps.cpp
test/Dialect/OM/errors.mlir
test/Dialect/OM/round-trip.mlir

An external class is to a class what an external module is to a module. It captures just the types of the external class parameters, and fields, but no computation. This will be useful for linking together OM dialect IR.

[OM] Add external class declaration.

---

include/circt/Dialect/ESI/ESIServices.td
include/circt/Dialect/HW/HWTypes.td
include/circt/Dialect/MSFT/MSFTPDOps.td

Drop the HWInnerRefAttr wrapper, use InnerRefAttr directly.
Bit of source code archaeology suggests this was added to workaround build problems re:ODS[1], which no longer appears to be the case.
[1] https://github.com/llvm/circt/pull/3005#discussion_r862374300

[HW][ESI][MSFT][NFCI] HWInnerRefAttr -> InnerRefAttr.

---

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp

ModuleNamespace is used for tracking used and generating new `inner_sym`s.  This code is mistakenly using it to generate unique `name`s for wires and ports.  It does not matter if the port has a unique name, as it will be legalized later in the pipeline.

[FIRRTL][GrandCentral] Stop using ModuleNamespace for unique names

---

include/circt/Dialect/FIRRTL/FIRRTLUtils.h
lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
lib/Dialect/FIRRTL/Transforms/AddSeqMemPorts.cpp
lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp
lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp
lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
lib/Dialect/FIRRTL/Transforms/ResolveTraces.cpp
test/Dialect/FIRRTL/add-seqmem-ports.mlir
test/Dialect/FIRRTL/annotations.mlir
test/Dialect/FIRRTL/dedup.mlir
test/Dialect/FIRRTL/emit-metadata.mlir
test/Dialect/FIRRTL/emit-omir.mlir
test/Dialect/FIRRTL/lower-memory.mlir
test/Dialect/FIRRTL/lowerXMR.mlir
test/firtool/prefixMemory.fir

While they can be useful sometimes, as step towards making these
opaque handles instead of strings drop the notion of them
having "useful" names from API.
Still do the namespace bit to ensure unique, for now.

[FIRRTL][Utils] Drop support for hinting at symbol names. 

---

.github/workflows/uploadWheels.yml

Proposed workaround for `git fetch` unshallowing not working on a tag.
I'm attempting to test this on a fork.
h/t @richardxia for the suggested fix.

[Python] Fix wheel publishing

---

include/circt/Dialect/Pipeline/PipelineOps.td
lib/Conversion/PipelineToHW/PipelineToHW.cpp
lib/Dialect/Pipeline/PipelineOps.cpp
test/Conversion/PipelineToHW/test_ce.mlir
test/Conversion/PipelineToHW/test_clockgates.mlir
test/Conversion/PipelineToHW/test_inline.mlir
test/Conversion/PipelineToHW/test_outlined.mlir
test/Dialect/Pipeline/round-trip.mlir

Reflected in HW lowering, and used by e.g. the register materialization pass to carry register names through multiple stages.
Still a draft since i want to get peoples opinion on the HW lowering before i change tests, e.g. things like whether there should be a `_reg` suffix on stage module outputs which are driven by registers (and likewise e.g. `_reg_in` for stage inputs that arrive from a prior stage that was a registered output).
Example lowering:
```mlir
hw.module @testNaming(%go: i1, %clk: i1, %rst: i1) -> (out: i1) {
%0:2 = pipeline.scheduled "MyPipeline"(%a0 : i1 = %go) clock(%c = %clk) reset(%r = %rst) go(%g = %go) -> (out: i1) {
// The register will be named after the namehint on the source operation.
%add = comb.add %a0, %a0 : i1
pipeline.stage ^bb1 regs("myNamed" = %add : i1, …
```

[Pipeline] Allow explicitly named registers and passthroughs

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/prepare-for-emission.mlir

Do not try to resolve use-before-def on LTL expressions by spilling them to a wire. LTL expressions are always emitted inline, so just leave them be in the IR and have ExportVerilog emit them as they are.
Fixes #5613.

[ExportVerilog] Fix crash when spilling LTL expr to wire

---

.github/workflows/uploadWheels.yml

This change splits the python wheel upload into 2 stages (separate jobs). In the first stage, wheels are built and uploaded simply as artifacts through the native GitHub actions upload-artifact action. This stage runs on the desired matrix of configurations (manylinux, macos, etc.) and on all event triggers. In the second stage, the corresponding wheels are downloaded (download-artifact) and uploaded to PyPI. This stage only runs on ubuntu and only for tags or nightly build (i.e. skipping workflow_dispatch).
The reason for this change is documented in #5420.

[CI] Split wheel upload into stages

---

lib/Dialect/FIRRTL/Transforms/InferReadWrite.cpp

Not creating symbols, unnecessary work.

[FIRRTL][InferRW] Drop unnecessary ModuleNamespace usage.

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types-sym-errors.mlir
test/Dialect/FIRRTL/lower-types.mlir

Only error if their target is not included in lowered output.
Partiton inner symbols to the lowered fields, error if any symbols target fieldID's not present in lowered form.
(e.g., fieldID == 0).

[FIRRTL][LowerTypes] Support per-field inner symbols.

---

include/circt/Dialect/Calyx/CalyxLoweringUtils.h
lib/Conversion/LoopScheduleToCalyx/LoopScheduleToCalyx.cpp
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Dialect/Calyx/Export/CalyxEmitter.cpp
lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp
test/Conversion/SCFToCalyx/convert_controlflow.mlir
test/Conversion/SCFToCalyx/convert_memory.mlir
test/Dialect/Calyx/emit-seq-memory.mlir

Switches SCFToCalyx from using combinational read memories to sequential read memories. Sequential reads are much more realistic for hardware, so the plan is to eventually deprecate combinational read memories in the native Calyx compiler. Unfortunately, the same change cannot be made in LoopScheduleToCalyx yet as it requires further changes to how we build the pipeline. A PR for those fixed to LoopScheduleToCalyx is in the works.

[SCFToCalyx] Use sequential memories

---

include/circt/Dialect/FIRRTL/FIRRTLTypes.h
unittests/Dialect/FIRRTL/TypesTest.cpp

This fixes a bug that type_cast doesn't work well if a request type isTypeInterface.

[FIRRTL] Fix type cast to look through type alias for type interfaces

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

These cannot be strictconnect'd.
Fixes #5650.

[FIRRTL][Folds] Fix AggOneShot to avoid non-passive aggregates.

---

include/circt/Dialect/HW/HWOpInterfaces.td
include/circt/Dialect/MSFT/MSFTOps.td
lib/Conversion/HandshakeToDC/HandshakeToDC.cpp
lib/Dialect/ESI/ESIServices.cpp
lib/Dialect/MSFT/MSFTOps.cpp
lib/Dialect/MSFT/Transforms/MSFTPartition.cpp
lib/Dialect/MSFT/Transforms/PassCommon.cpp

HWMutableModuleLike inherits from HWModuleLike now, so non-mutating functions can move back.  Also make MSFTExternalModuleOp HWModuleLike.  It was very close before.

[NFC]  Move functions from HWMutableModuleLike to HWModuleLike

---

include/circt/Dialect/FIRRTL/FIRRTLEnums.td
include/circt/Dialect/FIRRTL/FIRRTLStatements.td
include/circt/Dialect/FIRRTL/FIRRTLStructure.td
include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/errors.mlir

Add operations to represent FIRRTL optional groups. The FIRRTL spec discussion of this feature is here: https://github.com/chipsalliance/firrtl-spec/pull/108
This just adds the operations and nothing else. More will follow...

[FIRRTL] Add GroupDeclOp and GroupOp

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

Update the LowerTypes pass to support lowering aggregate declarations inside group definitions.

[FIRRTL] Add Groups to LowerTypes

---

include/circt/Dialect/HW/ModuleImplementation.h
include/circt/Support/ParsingUtils.h
lib/Dialect/HW/ModuleImplementation.cpp

The 'getPortNameAttr' functionality is generic. Move it into a new support header and rename it.

[HW][Support][NFC] Move generic module parsing func into support

---

frontends/PyCDE/src/signals.py
frontends/PyCDE/test/test_hwarith.py

[PyCDE] Add implemented of comparison operators

---

include/circt/Dialect/Seq/SeqPasses.h
include/circt/Dialect/Seq/SeqPasses.td
integration_test/Dialect/Seq/fifo/fifo.mlir
integration_test/Dialect/Seq/fifo/fifo.py
integration_test/Dialect/Seq/lit.local.cfg.py
lib/Dialect/Seq/Transforms/CMakeLists.txt
lib/Dialect/Seq/Transforms/LowerSeqFIFO.cpp
test/Dialect/Seq/lower-fifo.mlir

Lowers to a fairly standard fifo implementation. Will add more target-optimized implementations after this baseline is checked in.
For reference, the following:
```mlir
hw.module @fifo(%clk : i1, %rst : i1, %inp : i32, %rdEn : i1, %wrEn : i1) -> (out: i32, empty: i1, full: i1, almost_empty : i1, almost_full : i1) {
%out, %full, %empty, %almostFull, %almostEmpty = seq.fifo depth 4 almost_full 2 almost_empty 1 in %inp rdEn %rdEn wrEn %wrEn clk %clk rst %rst : i32
hw.output %out, %empty, %full, %almostEmpty, %almostFull : i32, i1, i1, i1, i1
}
```
exports as
```sv
module fifo(
input         clk,
rst,
input  [31:0] inp,
input         rdEn,
wrEn,
output [31:0] out,
output        empty,
full,
almost_empty,
almost_full
);
wire [1:0]  fifo_rd_addr_next;
wire [1:0]  fifo_wr_addr_next;
wire [2:0] …
```

[Seq] Add FIFO lowering

---

lib/Dialect/FIRRTL/Transforms/LowerOpenAggs.cpp
test/Dialect/FIRRTL/lower-open-aggs.mlir

The previous approach worked for ref-only-agg interiors that weren't under the root, but would miss the first level.
Instead of using hwOnlyAggMap to record lack of hardware equivalent (std::nullopt), populate nonHWValues for fields that map to nothing.
Removes need to propagate "maps to nothing" through indexing operations.

[FIRRTL][LOA] Fix handling of ref-only-agg interior element.

---

docs/Dialects/Seq/RationaleSeq.md
include/circt/Dialect/Seq/SeqOps.td
lib/Dialect/Seq/SeqOps.cpp
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Dialect/Seq/firreg.mlir
test/Dialect/Seq/round-trip.mlir

[Seq] Add a preset value to allow fir registers to be preset

---

frontends/PyCDE/src/__init__.py
frontends/PyCDE/src/signals.py
frontends/PyCDE/test/test_pycde_values.py

- Add and/or reduce for BitsSignal
- Add and reduce for ArraySignal
- Import Reset to pycde

[PyCDE] Add or/and reduce

---

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code.mlir

Close https://github.com/llvm/circt/issues/5665. This commit fixes a bug that bound instances are accidentally erased. When inlining input only modules it's necessary to clone bind statements for bound instances in the module. Previously single bind op is shared by multiple instances, as a result ExportVerilog only emits a bind statement for one of them.

[SVExtractTestCode] Fix a bug that instance inlining doesn't update inner symbols and clone sv.bind

---

.github/workflows/nightlyIntegrationTests.yml

Let's see if this helps with issues running out of space (#5621).

[CI] Use LLVM_USE_SPLIT_DWARF to reduce time and space.

---

lib/Bindings/Python/dialects/CombOps.td
lib/Bindings/Python/dialects/ESIOps.td
lib/Bindings/Python/dialects/FSMOps.td
lib/Bindings/Python/dialects/HWArithOps.td
lib/Bindings/Python/dialects/HWOps.td
lib/Bindings/Python/dialects/MSFTOps.td
lib/Bindings/Python/dialects/OMOps.td
lib/Bindings/Python/dialects/SVOps.td
lib/Bindings/Python/dialects/SeqOps.td

Seems like this is just removed in https://reviews.llvm.org/D154469.
Doing the same here.

[Python] Remove tablegen file that was deleted upstream.

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

`isa<.*Type>` in LowerTypes seems to be not updated. This fixes LowerTypes to use type alias aware utils.

[LowerTypes] Replace isa with type_isa and type switch, NFC

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/prepare-for-emission.mlir

Fix a bug where an assertion could fire in ExportVerilog due incomplete
wire creation in PrepareForEmission.  This bug occurss if an always inline
operation was duplicated, but its operand is not always inline.  This
creates a situation where, if you were to run PrepareForEmission _again_,
it would create a wire (and no assertion would fire).
Change the logic when recursing through operands of an always inline
operation to create this wire.
Fixes #5605.
This PR does some NFC monkeying with `PrepareForEmission`. The first two commits do this NFC monkeying. The third commit makes the change and adds tests. For the purposes of PR review, only the last commit matters.

[ExportVerilog] Use wire for inlined op operand

---

include/circt/Dialect/FIRRTL/FIRRTLUtils.h
include/circt/Support/Namespace.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

Lower `firrtl.alias` to `hw.typealias`. 
Create a global `hw.type_scope` and add the `hw.typedecl`s corresponding to all
the `firrtl.alias`s across  the `firrtl.module`s. 
This PR adds a pre-scan to the `LowerToHW` pass to lower all the `firrtl.alias`
types for all the modules, sequentially. This ensures that name conflict
resolution and declaration order of `typedecl` are deterministic. The
sequential pass records all the alias types and their corresponding lowering,
which is accessed during the parallel phase.

[TypeAlias] Add LowerToHW support for lowering TypeAlias

---

include/circt/Dialect/FIRRTL/FIRRTLStatements.td
include/circt/Dialect/FIRRTL/FIRRTLStructure.td
lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
lib/Dialect/FIRRTL/Transforms/ExtractClasses.cpp
test/Dialect/FIRRTL/annotations-errors.mlir
test/Dialect/FIRRTL/errors.mlir

Add a class op to the FIRRTL dialect. Classes are a properties-only module-like thing. Classes can have input and output port, like a module, but these ports can only hold properties.

[FIRRTL] Add ClassOp

---

include/circt/Dialect/Ibis/IbisOps.td
include/circt/Dialect/Ibis/IbisPasses.h
include/circt/Dialect/Ibis/IbisPasses.td
include/circt/InitAllPasses.h
lib/Dialect/Ibis/CMakeLists.txt
lib/Dialect/Ibis/IbisOps.cpp
lib/Dialect/Ibis/Transforms/CMakeLists.txt
lib/Dialect/Ibis/Transforms/IbisCallPrep.cpp
lib/Dialect/Ibis/Transforms/PassDetails.h
test/Dialect/Ibis/structure.mlir
tools/circt-opt/CMakeLists.txt

Lowering the Ibis control flow starts with converting all calls to the DC dialect's values with one struct representing the packed arguments.
In the interest of having small PRs, this only implements narrowing the arguments to one struct. Part 2 will then wrap them in DC values.

[Ibis] Call preparation pass -- part 1

---

lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
test/Dialect/SV/hw-memsim.mlir

Fix an inconsistency between the handling of read ports and read-write ports when running HWMemSimImpl with the "ignore-read-enable" option (firtool option "-ignore-read-enable-mem").  After #5700, this would cause the enable line of a read-write read port to have no effect. I.e., the memory would always read even if not enabled.  Change this to align with the behavior of read ports where the memory always returns the last read address.
Input:
```
circuit Foo:
module Foo:
input r: {addr: UInt<3>, en: UInt<1> clk: Clock, flip data: UInt<32>}
input rw: {addr: UInt<3>, en: UInt<1> clk: Clock, flip rdata: UInt<32>, wmode: UInt<1>, wdata: UInt<32>, wmask: UInt<1>}
mem memory:
data-type => UInt<32>
depth => 8
reader => r
readwriter => rw
read-latency => 1
write-latency => 1
read-under-write => …
```

[HW] Consistent HWMemSimImpl ignore-read-enable

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp

In the FIRParser, the parseModule function is responsible for parsing all kinds of modules (int, ext, and normal). This PR breaks that code into multiple functions, trading some code duplication for readability. This will make it easier to parse classes, another module-like declaration which are being added to FIRRTL.
Also adds some additional error checking for types and group indentation.

[FIRRTL] Refactor parseModule into multiple functions

---

lib/Dialect/FIRRTL/FIRRTLReductions.cpp

Add the DropNames pass to circt-reduce with the option to drop all names. This has the benefit of letting canonicalizers/folders go ham.  This was observed as a missed opportunity on a recent reduction that left many connections like the following:
node b = a
node c = b
node d = c
Dropping names causes all of these to get folded away and dramatically reduced the final, already very small, reduced design (by 50%).

[circt-reduce] Add DropNames Preserving None Pass

---

include/circt/Dialect/DC/DCOps.td
include/circt/Dialect/DC/DCTypes.td
integration_test/Dialect/DC/max/max.mlir
lib/Conversion/DCToHW/DCToHW.cpp
lib/Conversion/HandshakeToDC/HandshakeToDC.cpp
lib/Dialect/DC/DCOps.cpp
test/Conversion/DCToHW/basic.mlir
test/Conversion/HandshakeToDC/basic.mlir
test/Dialect/DC/canonicalization.mlir
test/Dialect/DC/roundtrip.mlir

- accepting multiple types is data semantics encroaching the control-only land of DC.

[DC] `dc.value` should only take one type

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp

Added here: 53b1c077d661af3409786db8363ddf3656137937 .

[FIRRTL][NFC] Fix accidental substitution, pohwist -> portlist.

---

docs/Dialects/DC/RationaleDC.md
include/circt/Dialect/DC/DCDialect.td
include/circt/Dialect/DC/DCOps.h
include/circt/Dialect/DC/DCOps.td
lib/Conversion/DCToHW/DCToHW.cpp
lib/Dialect/DC/CMakeLists.txt
lib/Dialect/DC/DCOps.cpp
test/Conversion/DCToHW/basic.mlir
test/Dialect/DC/roundtrip.mlir

Much needed cast operations to/from ESI.
Given that `dc.value`s have unnamed fields (which i think is a good descision) `dc.value`s with multiple types will be converted to a `hw.struct` with an inferred name, in this case `field#`. In most cases, this won't be compatible with the structs used in an input/output ESI channel. To address this, source materializations (esi -> dc) are automatically handled by an inserted `hw.bitcast`. Target materializations (and result type inference, dc -> esi) can be directed by specifying a forced type in the `dc.to_esi` op.

[DC] Add cast to/from ESI ops

---

include/circt-c/Dialect/HW.h
integration_test/Bindings/Python/dialects/hw.py
lib/Bindings/Python/HWModule.cpp
lib/CAPI/Dialect/HW.cpp

These binding are very shallow and only support the use case of a single InnerSymProperties with a fieldID of 0.  Current use cases only require this limited functionality, and in the future we will probably be changing the underlying attributes, so it doesn't make sense to expose it all now.

[HW] Add InnerSymAttr python bindings

---

lib/Dialect/FIRRTL/FIRRTLReductions.cpp

Allow the FIRRTLOperandForwarder to work on operations with one operand. This enables some cleanup of things like:
node a = not(b)
To produce:
node a = b

[circt-reduce] OperandForwarder One Operand

---

lib/Dialect/FIRRTL/FIRRTLReductions.cpp
test/Dialect/FIRRTL/Reduction/pattern-registration.mlir
test/Dialect/FIRRTL/Reduction/trivial.mlir
test/circt-reduce/name-sanitizer.mlir

Add two new pseudo-reduction patterns:
- module-name-sanitizer
- module-internal-name-sanitizer
These are not true reductions as they only do cleanup of the circuit.
However, they make a number of modifications which are typically made by a
circt-reduce user before sharing the result of a circt-reduce run:
- All internal names are converted to generic names
- All modules are replaced with metasyntactic names
These have the lowest priority, are one-shot, and will accept a larger
circuit result (even though they should almost always produce a smaller
output).

[circt-reduce] Add FIRRTL name sanitization

---

include/circt/Dialect/HW/HWMiscOps.td

This allows the generated Python bindings to generate a useful constructor, which is impossible otherwise.

[HW] Allow default builders for hw.wire.

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/parse-errors.fir

Gate 3.1.0 features on that version, pull `String` as well since it doesn't make a lot of sense to leave behind w/o PropAssign.
"class" is kept ungated.

[FIRRTL][FIRParser] Gate properties on 3.1.0+.

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR.mlir

Continue to handle everything else in a single walk.
Walking the ref dataflow directly would eliminate the need for this iteration, but finding the "roots" requires an IR walk anyway so just handle everything we can during a single walk and for any ref.sub's encountered handle them separately.
The outer iteration loop is bounded by the number of ref.sub's chained through `backedges` to storage (`ref.define` to storage (ports/instance results)), which is expected to be very small in practice, at worst O(ports).

[LowerXMR] iterate to handle ref.sub .

---

include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
lib/Dialect/FIRRTL/Export/FIREmitter.cpp
test/Dialect/FIRRTL/emit-basic.mlir

This adds missing support for string and integer typed properties, as well as propassign, and constant string and integer expressions.

[FIREmitter] support property types and expressions

---

include/circt/Dialect/HW/HWTypes.td
lib/Dialect/HW/HWAttributes.cpp

Until standardize on a dedicated type, fix this.

[HW][InnerSym] Use uint64_t for method names involving FieldID.

---

lib/Dialect/Calyx/Transforms/CompileControl.cpp
lib/Dialect/ESI/ESIOps.cpp
lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
lib/Dialect/SV/Transforms/HWExportModuleHierarchy.cpp
lib/Dialect/SV/Transforms/SVTraceIVerilog.cpp

Let AnalysisManager provide cached copy if available,
and be open to it being preserved across passes.
Also unnecessary copying of SymbolTable (DenseMap).

[Calyx][ESI[FIRRTL][SV] Use getAnalysis for SymbolTable and others.

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/Comb/canonicalization.mlir

This implements a canonicalizer 
`or(mux(c_1, a, 0), mux(c_2, a, 0), ..., mux(c_n, a, 0)) -> mux(or(c_1, c_2, .., c_n), a, 0)`

[CombFolds] Optimize OrOp whose operands are mux of the same value and a zero.

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-errors.fir

Keywords cannot be used for type alias name. Reject them during parsing.
In practice, only built-in types are a problem if used as type alias name, but it seems reasonable to reject any firrtl keyword.
For example, this must be rejected.
```
circuit Top:
type Clock = UInt<32>
module Top:
input in : Clock
```

[FirParser][Typealias] Reject keyword as type alias name

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

[LowerToHW] Wires used for output ports should get their symbols.

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/FIRRTL/SFCTests/complex-asserts.fir
test/Dialect/SV/hw-extract-test-code.mlir

This PR adds two commits to 1.37 release branch.
* https://github.com/llvm/circt/pull/5679
* https://github.com/llvm/circt/pull/5561

Backport ETC and UNROnly fixes to firtool 1.37

---

lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
test/Dialect/FIRRTL/emit-omir.mlir

Since EmitOMIR is a firrtl::CircuitOp pass, don't attempt to acccess or modify or insert into the operation above the one the pass is running on.

[FIRRTL][EmitOMIR] Don't insert above pass level.

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/ExtractClasses.cpp
test/Dialect/FIRRTL/classes.mlir
test/Dialect/FIRRTL/errors.mlir

ObjectOp is a declaration of an object in firrtl, which in turn is an instance of a class. ObjectOp has a single return value, of type ClassType, which represents the instantiated object. Objects are moduel-like, in that they have input and output ports, but unlike modules, are not exploded into their ports.

[FIRRTL] Add ObjectOp

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/verif.mlir

Fix an issue in `ExportVerilog` where `ExprEmitter`s and `PropertyEmitter`s would not properly use a token buffer passed in as a constructor argument. The emitters have a local buffer of tokens that is used by default if no external one is provided. However, parts of the emitters failed to use `buffer.tokens` to access either the externally provided or the local buffer, and instead would always use the local `tokens` buffer. This caused parentheses and end tokens to be lost if an external buffer was provided, since the emitter would modify the unused local `tokens` buffer.
This fixes the issue by properly using `buffer.tokens` everywhere and renaming `tokens` to `localTokens` to make misuse more obvious.
Fixes #5763.

[ExportVerilog] Fix Expr/PropertyEmitter token buffer crash

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
lib/Dialect/FIRRTL/Export/FIREmitter.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/emit-basic.mlir
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/test.mlir

Since Integer is already an MLIR type, this change renames BigIntType to FIntegerType, and BigIntConstantOp to FIntegerConstantOp.

[FIRRTL] Rename BigIntType to FIntegerType

---

.github/workflows/uploadFirrtlReleaseArtifacts.yml

This PR does to refactors/cleanups of the `firtool` release CI workflow.  These are organized into two commits:
1. The build matrix is no longer hard-coded.  Instead, this is dynamically created by passing a JSON description of the build matrix (technically matrices as there is a "build_config" dimension and a "runner" dimension).  This is done to enable programmability of the build matrix.
2. The CI workflow is switched to use a unified build.
This is the first part of a larger change to this workflow to enable more cross-repo CI/CD pipelines.  Specifically, I want to automate the CI/CD flow for bumping `firtool` internally at SiFive and externally on Chisel. The first piece of this is having a nightly binary build of `firtool`. I am constrained in that Docker cannot be a solution here. …

[CI] firtool release cleanup

---

.github/workflows/uploadFirrtlReleaseArtifacts.yml

Add a nightly scheduled build of `firtool`. This is intended for other projects to consume to do top-of-tree testing.
Add options to control the manually run workflow dispatch build. This enables building any of `[linux, macos, windows]` builds and with an optional to disable testing. I've been using this to test the build. The UI that GitHub gives you is shown below:
This is stacked on #5741 until that lands.
Once the nightly build is running, any user can grab this through the GitHub API, substituting `$TOKEN` for a GitHub personal or app token. The following script will grab the latest nightly and extract it.
```shell
ARTIFACT_NAME=firrtl-bin-linux-x64.tar.gz
ARTIFACT_ID=$(
curl -L \
-H "Accept: application/vnd.github+json" \
-H "Authorization: Bearer $TOKEN" \
-H …
```

[ci] Add nightly `firtool` release build, options to workflow_dispatch

---

lib/Dialect/HW/HWAttributes.cpp
test/Dialect/HW/errors.mlir

There is no `parseKeyword` which takes a list of alternatives, so we have to emit the error ourselves.  This could be fixed with some better upstream functionality.
Fixes #5597

[HW] InnerSymProperties: emit error when visibility is invalid

---

.github/workflows/shortIntegrationTests.yml

The ccache action by default uses the current date and time as part of the key for caching. The main problem with this is that it can create too many different cache entries, and can eject entries we don't want to be ejected.  There isn't a reason to keep more than one copy of this cache around, so using a consistent key will cause it to eject itself.  I put the name of the job in the key so that we can identify which entries belong to what jobs when we examine the cache.  This change also updates to a newer version of the ccache action.

[CI] Use a consistent key for ccache caching in Short Integration Tests

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir
test/Dialect/FIRRTL/SFCTests/data-taps-xmr.fir
test/Dialect/FIRRTL/SFCTests/data-taps.fir
test/Dialect/FIRRTL/SFCTests/mem-taps-reg.fir
test/Dialect/FIRRTL/lowerXMR.mlir
test/firtool/export-ref.fir

Reading a value shouldn't cause it to be blocked,
there are other mechanisms for that.
Split dataflow for read-only probes into dedicated nodes.
Try to name through indexing operations,
fallback to current strategy of "name".
Append "_probe" so if/when there's a conflict
it's clear what's going on (vs "_0").

[FIRRTL][LowerXMR] Always insert nodes for probes, don't block opts.

---

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
lib/Dialect/FIRRTL/Transforms/ResolveTraces.cpp
test/Dialect/FIRRTL/SFCTests/trace-api.fir
test/Dialect/FIRRTL/resolve-traces.mlir

Change the ResolveTraces pass to use symbols instead of hard-coded names. Previously, the pass used hard-coded names derived from the hierpath op symbols (which was mega-jank! I'm sorry!).  Correct all this by using symbols with substitutions.
Update the end-to-end test to use a test case which uncovered this error (because it uses an instance path).  Update the pass unit tests to use the new format.

[FIRRTL] Use symbols in ResolveTraces verbatims

---

include/circt/Conversion/Passes.td
include/circt/Dialect/Verif/VerifDialect.td
include/circt/Dialect/Verif/VerifOps.td
lib/Conversion/VerifToSV/VerifToSV.cpp
lib/Dialect/Verif/VerifDialect.cpp
lib/Dialect/Verif/VerifOps.cpp
test/Conversion/VerifToSV/verif-to-sv.mlir
test/Dialect/Verif/basic.mlir
test/Dialect/Verif/canonicalization.mlir

Add the `verif.has_been_reset` operation to detect if a circuit has been properly reset. Useful to disable assertions before and during reset.
The result of `verif.has_been_reset` reads as 0 immediately after simulation startup and after each power-cycle in a power-aware simulation. The result remains 0 before and during reset and only switches to 1 after the reset is deasserted again.
This is a useful utility to disable the evaluation of assertions and other verification constructs in the IR before the circuit being tested has been properly reset. Verification failures due to uninitialized or randomized initial state can thus be prevented.
Using the result of `verif.has_been_reset` to enable verification is more powerful and proper than just disabling verification during reset. The …

[Verif] Add has_been_reset op

---

.clang-tidy

Conflicts with coding standard re:static methods,
see upstream's similar change:
4c9f1584ce2c373dc571068af5fd65f2e16d05d2 .

[NFC] .clang-tidy: Disable misc-use-anonymous-namespace .

---

lib/Dialect/Seq/Transforms/LowerSeqFIFO.cpp
test/Dialect/Seq/lower-fifo.mlir

Includes #5756 with fix for the non-determinism
(reliance on arg evaluation order)
to get this working on GCC as well as clang.

[Seq][LowerFIFO] Fix non-determinism, enable test.

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
include/circt/Dialect/Verif/VerifOps.h
include/circt/Dialect/Verif/VerifOps.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/Transforms/LowerIntrinsics.cpp
test/Conversion/FIRRTLToHW/intrinsics-errors.mlir
test/Conversion/FIRRTLToHW/intrinsics.mlir
test/Dialect/FIRRTL/canonicalization.mlir
test/Dialect/FIRRTL/lower-intrinsics.mlir
test/firtool/has_been_reset.fir

Add the `circt.has_been_reset` FIRRTL intrinsic. More specifically:
- Add the `firrtl::HasBeenResetIntrinsicOp`
- Add support for the op in the FIRRTL visitor
- Add support for the op in `LowerIntrinsics`
- Lower the op to `verif::HasBeenResetOp`, inferring the sync/async-ness from the reset's FIRRTL type
- Add tests for `LowerIntrinsics`, `LowerToHW`, and the canonicalizer
- Add a firtool end-to-end test to check that this interacts properly with the `InferResets` pass

[FIRRTL] Add has_been_reset intrinsic

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/Export/FIREmitter.cpp
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp
lib/Dialect/FIRRTL/Transforms/InferReadWrite.cpp
lib/Dialect/FIRRTL/Transforms/InferResets.cpp
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/VBToBV.cpp
lib/Dialect/FIRRTL/Transforms/Vectorization.cpp
test/Dialect/FIRRTL/parse-basic.fir
test/firtool/firtool.fir

This PR introduces `BaseTypeAliasOr` helper struct to create a type which accepts both type aliases and a specified type. 
Unfortunately this PR makes it hard to use `TypedValue<Foo>` which is returned by standard ODS generated getters since now the type will become `TypedValue<BaseTypeAliasOr<Foo>>`.

[FIRRTL] Relax ODS defined FIRRTL base subtypes to allow type aliases

---

include/circt/Dialect/Ibis/Ibis.td
include/circt/Dialect/Ibis/IbisDialect.td
include/circt/Dialect/Ibis/IbisInterfaces.td
include/circt/Dialect/Ibis/IbisOps.td
include/circt/Dialect/Ibis/IbisTypes.h
include/circt/Dialect/Ibis/IbisTypes.td
lib/Dialect/Ibis/IbisDialect.cpp
lib/Dialect/Ibis/IbisOps.cpp
lib/Dialect/Ibis/IbisTypes.cpp
test/Dialect/Ibis/errors.mlir
test/Dialect/Ibis/round-trip.mlir
test/Dialect/Ibis/structure.mlir

Since port reads/writes are now done at a classref-based level, this also means that there's no reason to have specific instance reads/writes.
A bit of an outstanding question - `ibis.container` was isolated from above, which i still think is the right descision. However, we need to be able to grab `%this` somehow...
Some options:
1. Add a block argument to containers, e.g. `ibis.container @D(%parent)` wherein %parent is implied to be %this of the class
2. Disallow IsolatedFromAbove (what's currently done).

[Ibis] Add instance/port references and related ops

---

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
test/Dialect/FIRRTL/infer-widths-errors.mlir

Don't crash if encounter non-base type on instance op with uninferred widths.

[FIRRTL][InferWidths] Fix handling of non-base ports in instances.

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/LowerGroups.cpp
test/Dialect/FIRRTL/lower-groups.mlir

Add the LowerGroups pass that converts FIRRTL optional groups to bound
modules.
This is a re-opening of #5536 as I pushed to `main` and screwed up the PR from GitHub's perspective.

[FIRRTL] Add LowerGroups Pass

---

include/circt-c/Dialect/FIRRTL.h
lib/CAPI/Dialect/FIRRTL.cpp

[FIRRTL][CAPI] Add a new function to get `ParamDeclAttr`

---

include/circt/Dialect/HW/HWAttributes.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Import/FIRLexer.cpp
lib/Dialect/FIRRTL/Import/FIRLexer.h
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Import/FIRTokenKinds.def
test/Dialect/FIRRTL/parse-basic.fir
test/firtool/verbatim-parameter.fir

Currently, FIRRTL params values wrapped in 'single-quotes' are emitted as string in the verilog output, but they should be emitted verbatim.
This PR corrects this behaviour in the FIRParser, by emitting hw::ParamVerbatimAttr instead of StringAttr for raw/verbatim string params.
Summary of changes:
- Rename "raw string" to "verbatim string" in the FIRRTL parser and lexer.
- Add new builder for ParamVerbatimAttr that sets the type to NoneType.
- Update the FIRRTL parser to emit a hw::ParamVerbatimAttr of type NoneType.
Fixes: #4584

[FIRRTL][HW] Add verbatim literal support

---

include/circt/Dialect/Ibis/IbisInterfaces.td
include/circt/Dialect/Ibis/IbisOps.h
include/circt/Dialect/Ibis/IbisOps.td
include/circt/Dialect/Ibis/IbisTypes.h
include/circt/Dialect/Ibis/IbisTypes.td
lib/Dialect/Ibis/IbisOps.cpp
lib/Dialect/Ibis/IbisTypes.cpp
test/Dialect/Ibis/errors.mlir
test/Dialect/Ibis/round-trip.mlir
test/Dialect/Ibis/structure.mlir

- Adds an `ibis.this` operation to define the current scope.
- Renames `!ibis.classref` to `!ibis.scoperef` since this type must now be able to support both classes and containers
- Adds a `ScopeOpInterface`
- `ibis.get_parent_of_ref` now takes an explicit type to cast the parent ref to. In most `class` cases, this will be an opaque type, but for `container`s these will reference the explicit parent type. The obvious benefit of this is that you're able to perform `get_port` on resolved `scoperef` types.

[Ibis] Add `ibis.this`

---

lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/errors.mlir

[FIRRTL] Reject unsupported port symbols on instance + class ops.

---

include/circt/Dialect/OM/OMOps.td
include/circt/Dialect/OM/OMTypes.td
lib/Dialect/OM/OMOps.cpp
test/Dialect/OM/errors.mlir
test/Dialect/OM/round-trip.mlir

This PR adds the op to create lists of objects.
The Python bindings are not yet implemented as further discussion of the in-memory representation is required.

[OM] Add `om.list_create` to create lists of objects

---

include/circt/Dialect/Pipeline/PipelineOps.h
include/circt/Dialect/Pipeline/PipelineOps.td
include/circt/Dialect/Pipeline/PipelinePasses.td
integration_test/Dialect/Pipeline/simple/simple.mlir
integration_test/Dialect/Pipeline/stall/stallTest.mlir
lib/Conversion/PipelineToHW/PipelineToHW.cpp
lib/Dialect/Pipeline/PipelineOps.cpp
lib/Dialect/Pipeline/Transforms/ExplicitRegs.cpp
lib/Dialect/Pipeline/Transforms/ScheduleLinearPipeline.cpp
test/Conversion/PipelineToHW/test_inline.mlir
test/Conversion/PipelineToHW/test_outlined.mlir
test/Dialect/Pipeline/Transforms/explicit-regs.mlir

Instead, remove `IsolatedFromAbove` from the pipeline, and define any used value defined outside of the pipeline as an external input. The motiviation for this is to reduce the headache introduced by having to explicitly modify the `ext` input list of a pipeline if more external inputs are to be added into a pipeline (or hoisted out of).

[Pipeline] Remove `ext` input from pipelines

---

include/circt/Dialect/Seq/SeqOps.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Conversion/PipelineToHW/PipelineToHW.cpp
lib/Dialect/Seq/SeqOps.cpp
lib/Dialect/Seq/Transforms/ExternalizeClockGate.cpp
test/Dialect/Seq/externalize-clock-gate.mlir
test/Dialect/Seq/round-trip.mlir

The inner symbol of a clock gate translates to an inner symbol on the instance it lowers to. Also slightly adjusted the lowering to cache constants and produce more readable test output.

[Seq] Add an inner symbol to permit references to clock gates

---

test/firtool/spec/refs/define-flip-to-passive.fir
test/firtool/spec/refs/define-subelement.fir
test/firtool/spec/refs/define.fir
test/firtool/spec/refs/endpoints.fir
test/firtool/spec/refs/ext.fir
test/firtool/spec/refs/force_and_release.fir
test/firtool/spec/refs/force_initial.fir
test/firtool/spec/refs/force_nonpassive.fir
test/firtool/spec/refs/forwarding_refs_upwards.fir
test/firtool/spec/refs/forwarding_refs_upwards_narrow.fir
test/firtool/spec/refs/in_ref_context.fir
test/firtool/spec/refs/inference_reset_bad.fir
test/firtool/spec/refs/inference_reset_good.fir
test/firtool/spec/refs/inference_works.fir
test/firtool/spec/refs/invalid_in.fir
test/firtool/spec/refs/nested_refproducer.fir
test/firtool/spec/refs/nosubaccess.fir
test/firtool/spec/refs/probe_export_simple.fir
test/firtool/spec/refs/read.fir
test/firtool/spec/refs/read_subelement.fir
test/firtool/spec/refs/read_subelement_add.fir
test/firtool/spec/refs/unused_in.fir
test/firtool/spec/refs/uturn.fir
test/firtool/spec/refs/when_c_force_initial.fir

Examples tweaked as-needed to make full examples,
portion from spec are marked as well as any modifications.
See comments in each, a few are modified to only test the demonstrated feature or to workaround spec issues (notably can't express non-const node with literal initializer).
Check these are parsed and make it through the pipeline, with and without aggregate preservation options.
Test invalid or unsupported examples are appropriately rejected.
Ensure the examples from spec are under test.

[FIRRTL][NFC] Add fir tests relating to probes, from spec.

---

lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/errors.mlir

Two changes:
1) The ODS generated verifier checks that the operation has a valid `targetRef` attribute, so there is no need to check it ourselves in the verifier.  This is currently an untestable code-path.
2) When the target is invalid, it prints as `<invalid target>`.  It makes more sense to print the original InnerRefAttr for this case. This change adds a test case for this.

[FIRRTL] Clean up RWProbe's verifier

---

docs/Dialects/FIRRTL/FIRRTLAnnotations.md
include/circt/Dialect/FIRRTL/AnnotationDetails.h
lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
test/Dialect/FIRRTL/dedup-errors.mlir
test/Dialect/FIRRTL/dedup.mlir

This implements `DedupGroupAnnotation` as described by @jackkoenig in this comment https://github.com/chipsalliance/firrtl-spec/pull/116#issuecomment-1613923683

[FIRRTL] add DedupGroupAnnotation

---

.github/workflows/nightlyIntegrationTests.yml

With our custom ccache stuff, cache hits don't update the ccache. This
is problematic since a the ccache might have a high miss rate. Switching
back to the ccache action as I'm assuming it's smarter than that.

[CI] Switch back to ccache action for nightlies

---

include/circt/Conversion/Passes.td
lib/Conversion/PipelineToHW/PipelineToHW.cpp

Fixing a TSAN issue due to concurrent additions (and removals) to the top-level mlir::ModuleOp symbol table, whilst the pass is running at a hw::HWModuleOp granularity.
fixes #5815

[PipelineToHW] Fix `PipelineToHW` TSAN issue

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp

Fixes #5816 .
Lowering of operations in body is still done in parallel.
Type aliases are used by the port lowering code (`tryEliminatingConnectsToValue`), but should already be populated for all ports+operations before call to `lowerPortsAndMoveBody`.

[FIRRTL][LowerToHW] Fix race by processing ports before parallel, fix failure path.

---

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp

Group many arguments, give this a bit of structure, automatically perform fixups.

[FIRRTL][Inliner][NFC] Cleanup with some scoped state structs.

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
include/circt/Support/LLVM.h
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/classes.mlir
test/Dialect/FIRRTL/errors.mlir

This op indexes into objects (values of type ClassType).

[FIRRTL] Add ObjectSubfieldOp

---

lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/errors.mlir

This mostly matters because our passes like to assume this sort of thing, so explicitly verify it.

[FIRRTL] RWProbeOp: Add requirement+verify def before use.

---

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h
include/circt/Dialect/FIRRTL/FIRRTLUtils.h
include/circt/Dialect/FIRRTL/Namespace.h
include/circt/Dialect/HW/InnerSymbolNamespace.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp
lib/Dialect/FIRRTL/FIRRTLReductions.cpp
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/AddSeqMemPorts.cpp
lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp
lib/Dialect/FIRRTL/Transforms/FlattenMemory.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp
lib/Dialect/FIRRTL/Transforms/LowerGroups.cpp
lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp
lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
lib/Dialect/FIRRTL/Transforms/ResolveTraces.cpp
lib/Dialect/SV/Transforms/HWExportModuleHierarchy.cpp
lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp

Combine identical "ModuleNamespaces" into a new common one
for anything with inner symbols.
First step towards dropping use of a "Namespace" for generating
inner symbols entirely, once other pieces are in place.
Also sets the stage for moving the utility functions that help
create inner symbols and inner refs out of FIRRTL.
NFCI.

[FIRRTL][HW] Replace ModuleNamespace with InnerSymbol one. 

---

CMakeLists.txt
cmake/modules/AddCIRCT.cmake
tools/arcilator/CMakeLists.txt
tools/circt-as/CMakeLists.txt
tools/circt-dis/CMakeLists.txt
tools/circt-lec/CMakeLists.txt
tools/circt-lsp-server/CMakeLists.txt
tools/circt-opt/CMakeLists.txt
tools/circt-reduce/CMakeLists.txt
tools/circt-translate/CMakeLists.txt
tools/firtool/CMakeLists.txt
tools/hlstool/CMakeLists.txt
tools/llhd-sim/CMakeLists.txt
tools/om-linker/CMakeLists.txt

Right now we use `add_llvm_tool()` to add tools, which is equivalent to `llvm_add_tool(LLVM ${ARGV})`. This puts packagers of CIRCT in the somewhat awkward situation of needing to use `LLVM_TOOLS_INSTALL_DIR` to specify where CIRCT tools should be placed in the install tree.
CIRCT is not LLVM.
This patch adds a specialization of `llvm_add_tool()`. This is the same approach used by MLIR and LLVM itself.

[CMake] Implement add_circt_tool()

---

.github/workflows/nightlyIntegrationTests.yml
.github/workflows/shortIntegrationTests.yml

Short integration tests are filling the cache. Hopefully not appending the timestamp will replace rather than add new ones. Also attempt to enable sharing cache between nightly and short.

[CI] Attempt to fix nightly cache evictions

---

integration_test/Bindings/Python/dialects/hw.py
lib/Bindings/Python/support.py

InnerSymAttr cannot be directly representable in python value so just cast it into a string in a similar way as we have handled InnerRef, om.ListAttr or om.ReferenceAttr.

[Python] Handle inner symbols in attribute_to_var

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/infer-widths.mlir
test/Dialect/FIRRTL/inliner.mlir
test/Dialect/FIRRTL/lowerXMR.mlir
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/parse-errors.fir

Rework RWProbeOp to explicitly track result type,
don't "infer" from target type argument (removed).
This is a better fit for this op, particualrly in that no
useful "inference" is performed that way.
(not inferring through symbol target)
Teach InferWidths about the type constraint,
getting inner symbol analysis for resolution.
Loosen parsing, but still only use RWProbeOp
for ports.
With these changes, it's nearly possible to remove
"Forceable" entirely in favor of the one mechanism.

[FIRRTL] RWProbeOp: support width inference.

---

include/circt/Dialect/FIRRTL/FIRParser.h
lib/CAPI/ExportFIRRTL/ExportFIRRTL.cpp
test/CAPI/CMakeLists.txt
test/CAPI/firrtl.c
test/CMakeLists.txt
test/lit.cfg.py

Commit 172afc3277003468cc5fde3029e0f3f9421b9447 added a new argument `FIRVersion version` to the `mlirExportFIRRTL` function, but didn't update its declaration. It breaks the compile for this function.
This PR removed that argument to fix the problem, since `FIRVersion` does not have a CAPI yet, and added a simple test to prevent regression.

[FIRRTL][CAPI] Fix undefined reference for `mlirExportFIRRTL`

---

.github/workflows/unifiedBuildTestAndInstall.yml
.github/workflows/uploadFirrtlReleaseArtifacts.yml

Finish the reusable build/test/install workflow that was initially added here: https://github.com/llvm/circt/commit/534005523312cdde298c03d2d0d53acec8b03b15
Use this for the `firtool` release flow.
This does not make any major modifications to the `firtool` release workflow. I.e., there are a number of now unnecessary things added to the build matrix which can be removed. I'd like to do this in a follow-up.

[ci] Finish, use reusable workflow for build/test/install

---

include/circt/Dialect/FIRRTL/FIRParser.h
lib/Dialect/FIRRTL/Export/FIREmitter.cpp
test/CAPI/firrtl.c

Match behavior of `mlirExportFIRRTL`.

[FIRRTL][Emitter] Sync to use "latest", and bump that to 3.1.0.

---

integration_test/Dialect/Calyx/custom_port_name.mlir
integration_test/Dialect/Calyx/memory_loop.mlir
integration_test/Dialect/Calyx/simple_arith.mlir
lib/Conversion/LoopScheduleToCalyx/CMakeLists.txt
tools/hlstool/CMakeLists.txt
tools/hlstool/hlstool.cpp

Fixes #5844. Attempting to add a simple `scf` to `hw` lowering flow using `calyx` to `hlstool`. Once this lands, I can work on adding the `affine` to `loopschedule` to `calyx` flow as well.

Add Calyx flow to `hlstool`

---

include/circt-c/Dialect/OM.h
include/circt/Dialect/OM/Evaluator/Evaluator.h
integration_test/Bindings/Python/dialects/om.py
lib/Bindings/Python/OMModule.cpp
lib/Bindings/Python/dialects/om.py
lib/CAPI/Dialect/OM.cpp
lib/Dialect/OM/Evaluator/Evaluator.cpp
test/CAPI/om.c
unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp

This is a PR for new representation of Evaluator and list_create support.
`std::variant` has been used as runtime representation of Evaluator but it's difficult to use it as
data structure for more structured values such as list or map. So this PR instead introduces a base class `EvaluatorValue ` and derived classes, `AttributeValue`, `ListValue` and `ObjectValue`, as runtime representation of values.
Also terminology `ObjectValue` is changed to `EvaluatorValue` since runtime values will not be limited to Object.
Python and C bindings are changed accordingly.

[OM] Change evaluator value representation and evaluate ListCreateOp.

---

include/circt/Dialect/OM/OMTypes.td
lib/Dialect/OM/OMTypes.cpp
test/Dialect/OM/errors.mlir
test/Dialect/OM/round-trip.mlir

This commit adds `!om.map<key, element>` type and restrict a key type to be either integer or string.

[OM] Add map types
