include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-memories.mlir
Instead, a constant X is materialized to drive the dummy port of the `seq` memory. A subsequent PR should consider whether these memories can be removed altogether.
=> [LowerToHW] Avoid creating undriven wires for 0-width seq mems

include/circt/Dialect/FIRRTL/FIRParser.h, lib/CAPI/ExportFIRRTL/ExportFIRRTL.cpp, lib/Dialect/FIRRTL/Export/FIREmitter.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-errors.fir
changes:
- `FIRVersion`:
- compress FIRVersion into a 64bit value (when padded), and pass it around by value.
- add comparison operators and remove `FIRVersion::compare`
- make min, default, latestVersion constexpr values, not functions
- minor cleanup to operator<<: it doesn't need to be marked static, it is implicitly inline because it is templated.
- `FIRParser`:
- pass FIRVersion to subparsers by value
- add new `requireFeature` helper, to ease boilerplate for checking the FIRRTL language version
- use `requireFeature` and the new FIRVersion comparison operators throughout the parser
=> [FIRRTL] Clean up FIRVersion checking

.github/workflows/unifiedBuildTestAndInstall.yml, .github/workflows/uploadReleaseArtifacts.yml
Closes #5814.
Skip this on Windows since LLVM doesn't support `BUILD_SHARED_LIBS=ON` on Windows. (ref: https://github.com/llvm/llvm-project/blob/706e875da3a21f2d6ba612ca991dbdbccb339327/llvm/CMakeLists.txt#L767-L775)
You can preview the artifacts on https://github.com/SpriteOvO/circt/releases/tag/firtool-0.00.5, uploaded by https://github.com/SpriteOvO/circt/actions/runs/5839650661.
=> [CI] Upload full shared libs installation for Linux and macOS

include/circt/Dialect/Calyx/CalyxPrimitives.td, lib/Conversion/CalyxToHW/CalyxToHW.cpp, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Dialect/Calyx/CalyxOps.cpp, lib/Dialect/Calyx/Export/CalyxEmitter.cpp, test/Conversion/SCFToCalyx/convert_simple.mlir, test/Dialect/Calyx/emit-comb-component.mlir
Implements lowering for `arith.select` using Calyx's `std_mux` primitive.
=> [Calyx] Support lowering of `arith.select`

.vscode/Unified.code-workspace.example.jsonc, docs/GettingStarted.md
I've added some simple instructions on how to use the existing `.code-workspace` file to configure VS code in the "Getting Started" docs. Additionally, I've updated that workspace file to disable LLHDSim since that doesn't work out of the box.
=> Update docs to add configuration for VS code

include/circt/Dialect/FIRRTL/FIRRTLAttributes.td, include/circt/Dialect/FIRRTL/FIRRTLStructure.td, lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp, test/Dialect/FIRRTL/SFCTests/data-taps-xmr.fir, test/Dialect/FIRRTL/annotations.mlir, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/lower-types-errors.mlir, test/Dialect/FIRRTL/lower-types-sym-errors.mlir, test/Dialect/FIRRTL/lowerXMR.mlir, test/Dialect/FIRRTL/parse-basic.fir
We need to support having paths for some ref-type ports but not others (ABI + GCT's internalPath mechanism) so change to have entry per port, with empty entries for non-ref and ref ports that should use ABI.
Add verifier for internalPaths, drop entirely if all entries are empty.
Fixes #5859 .
=> [FIRRTL] Rework internal paths array, cover all ports, maintain.

include/circt/Dialect/FIRRTL/FIRParser.h
GCC defines function-like macros major(x) and minor(x), for extracting information from device IDs. These macros conflict with, and cause compilation errors in, FIRVersion's constructor. This commit changes FIRVersion to initialize it's major and minor fields using brace-initialization, so that the initialization isn't mistaken for a macro invocation.
Tested in [godbolt](https://godbolt.org/z/n4e89EEaa).
Cc: @mortbopet
Fixes: #5868
=> [FIRRTL] Skirt around the GCC major/minor macros

include/circt/Dialect/FIRRTL/FIRRTLStructure.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp, test/Dialect/FIRRTL/inliner.mlir
Uses of classes are not always discoverable, this PR makes two changes to prevent the firtool pass pipeline from removing classes that appear dead.
=> [FIRRTL] Keep classes around

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir, test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
Tested on a large internal core, no new errors produced.
=> [LowerToHW] Emit errors instead of producing undriven wires

lib/Dialect/FIRRTL/FIRRTLTypes.cpp
Shouldn't have reference types but compute it anyway.
In particular, accurately set whether there's an uninferred reset.
=> [FIRRTL][NFC] Compute all bits for recursive type props in enums.

.github/workflows/uploadReleaseArtifacts.yml
Reference: https://github.com/llvm/circt/pull/5832#issuecomment-1682420644
I had named it as `circt-full-shared-libs-{os}-{arch}.tar.gz`, meaning `circt-full` with CMake option `BUILD_SHARED_LIBS` enabled. So the `-libs` suffix comes from the CMake option.
But I noticed that this is	 a bit confusing, on the other hand, `-libs` means that it only provides libraries, but it actually provides executables, libraries and headers.
In the future, we may want to upload `circt-full-static` as well, and this naming seems more reasonable to me.
=> [CI] Upload `circt-full-shared` without `-libs` suffix

lib/Dialect/FIRRTL/FIRRTLUtils.cpp, test/Dialect/FIRRTL/parse-basic.fir
Fixes #5322.
cc #5884 and #5886.
=> [FIRRTL] Fix parsing connection between enum of uninferred width.

include/circt/Dialect/ESI/ESIStructure.td, include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td, include/circt/Dialect/FIRRTL/FIRRTLStructure.td, include/circt/Dialect/HW/HWOpInterfaces.td, include/circt/Dialect/HW/HWStructure.td, include/circt/Dialect/MSFT/MSFTOps.td, include/circt/Support/InstanceGraphInterface.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/ESI/ESIOps.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/AddSeqMemPorts.cpp, lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp, lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, lib/Dialect/FIRRTL/Transforms/Dedup.cpp, lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp, lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp, lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp, lib/Dialect/FIRRTL/Transforms/InnerSymbolDCE.cpp, lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp, lib/Dialect/FIRRTL/Transforms/MemToRegOfVec.cpp, lib/Dialect/HW/HWOps.cpp, lib/Dialect/HW/InnerSymbolTable.cpp, lib/Dialect/MSFT/MSFTOps.cpp
HWModuleLike provides almost no value to firrtl and is a a relic of instancegraph.  Remove it and move required functionality.
=> [NFC] Make FIRRTL modules not implement hwmodulelike

.github/workflows/uploadReleaseArtifacts.yml
Use less resource intensive options for building nightly releases of CIRCT
full.  The GitHub runners will run out of disk space if using
"relwithdebinfo" and/or "asserts=on".  Use "release" and "asserts=off".
For context, nightlies are building shared libs and running out of disk space with the options provided: https://github.com/llvm/circt/actions/workflows/uploadReleaseArtifacts.yml (Original link was wrong.)
=> [ci] Use release/asserts=off for nightly shared

include/circt/Support/PrettyPrinter.h, include/circt/Support/PrettyPrinterHelpers.h, lib/Support/PrettyPrinter.cpp, unittests/Support/PrettyPrinterTest.cpp
This PR adds a `Callback` token to `PrettyPrinter`. It can be used to register a callback `std::function ` object, corresponding to any interesting event in the stream.
The `CallbackToken` is pushed along with the other tokens, and the `std::function` is invoked, only after the last token is printed to the stream. This enables the callback to record the location of the last printed token in the stream.
The callback is a `void()` function, it is the responsibility of the user, to capture the necessary data structures and manage the allocation. This enables the callback to be used for any generic purpose.
The unit tests demonstrate a use case of recording the stream location information for various tokens.
=> [PrettyPrinter] Add a callback token to record events

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/test.mlir
Test creation of lists with elements of primitive, aggregate, and object/class types.
Parser support will be added separately.
=> [FIRRTL] Add ListCreateOp.

include/circt/Dialect/Seq/SeqOps.td, lib/Dialect/Seq/SeqOps.cpp, lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp, test/Dialect/Seq/canonicalization.mlir, test/Dialect/Seq/clock-mux.mlir, test/Dialect/Seq/round-trip.mlir
As part of the introduction of a clock type (#5851), this PR adds a clock multiplexer which later will operate on `seq.clock`.
=> [Seq] Add a clock multiplexer op

.github/workflows/unifiedBuildTestAndInstall.yml
Enable sccache-based caching for the unified build/test/install GitHub Workflow.  Use sccache as opposed to ccache because the former supports Windows (as suggested by the hendrikmuhs/ccache-action documentation).
Disable caching for Windows non-release builds as there is a bug involving cmake and sccache.
This commit is the last piece necessary to begin replacing existing build/test GitHub workflows used in CIRCT.
Examples of caching working:
- Windows `relwithdebinfo` _skipping_ the caching step: https://github.com/llvm/circt/actions/runs/5909543298/job/16030240784#step:6:3 (This job was intentionally killed during the "Configure CIRCT" step as it doesn't need to finish to show the skip logic working.)
- Linux `relwithdebinfo` cache hit: …
=> [ci] Cache unified build/test/install

include/circt/Dialect/HW/InnerSymbolTable.h, lib/Dialect/FIRRTL/Transforms/Dedup.cpp, test/Dialect/FIRRTL/dedup-errors.mlir, test/Dialect/FIRRTL/dedup.mlir
This change adds support for InnerRefAtts to dedup, by allowing two modules to dedup if the inner reference is targeting the same thing.
=> [FIRRTL][Dedup] Handle deduplication of InnerRefAttrs

include/circt/Dialect/FIRRTL/CHIRRTL.td, include/circt/Dialect/FIRRTL/FIRRTLEnums.td
These enumerations were being generated into the global namespace.  This change sets the `cppNamespace` field of all FIRRTL enumerations.
=> [FIRRTL] Put ODS enumerations in the FIRRTL namespace

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h, include/circt/Dialect/HW/InnerSymbolNamespace.h
It is a common pattern for passes to have a map from a modules to an InnerSymbolNamespace.  This captures the pattern for reuse in a InnerSymbolNamespaceCollection.
=> [FIRRTL][HW] Add InnerSymbolNamespaceCollection

include/circt/Dialect/HW/InnerSymbolTable.h
This switches to non-explicit constructors in cases where it would not lead to automatic conversions. This helps write shorter code to when creating new InnerSymTargets.
=> [FIRRTL] Add InnerSymTarget non-explicit constructors

include/circt/Support/LLVM.h, include/circt/Types.td
DistinctAttr does not have proper upstream exposure through OpBase.td as type constraint, so we have to declare it ourselves.  This should be a temporary workaround.
=> Add DistinctAttr type constraints

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h, lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, test/Dialect/FIRRTL/SFCTests/dedup.fir, test/Dialect/FIRRTL/omir.mlir
This change takes a common pattern in LowerAnnotations, which avoids creating
duplicate HierPathOps by maintaining a cache, and moves it into a dedicated
class for easier re-use.  Since the HierPathCache maintains an insertion point
instead of always inserting to the top of the circuit's block, HierPathOps are
now in reverse order after LowerAnnotations and EmitOMIR.
=> [FIRRTL] Add HierPathCache to reuse HierPathOps

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes.mlir
Builds on #5890, #5892.
Relevant commit: https://github.com/llvm/circt/commit/2a08e68f2681c0e742b06c4b28c3b9e69fb080ef .
1) **Altered the legality predicate of operations to recursively inspect the types for FIRRTL dialect**.  This seems right for now but maybe isn't always?  This doesn't help conversions occur for the included tests but it is needed to reject incomplete conversions I ran into while developing this.
2) Really unsure how recursive type conversion should work -- this may be a little redundant/overkill.
3) What are the no-op OM type conversions for? They don't appear to be necessary for our tests, at least not for Lists.  I implemented it anyway in case it helps.
=> [FIRRTL][LowerClasses] Conversion support for Lists.

test/Dialect/OM/round-trip.mlir
Add a test to demonstrate `om.constant` already supports boolean.
=> [OM][NFC] Lit test for bool type

include/circt/Dialect/HW/HWOpInterfaces.h, include/circt/Dialect/HW/HWPasses.h, include/circt/Dialect/HW/HWStructure.td, include/circt/Dialect/HW/Passes.td, lib/Dialect/HW/InnerSymbolTable.cpp, lib/Dialect/HW/Transforms/CMakeLists.txt, lib/Dialect/HW/Transforms/VerifyInnerRefNamespace.cpp, lib/Firtool/Firtool.cpp, test/Dialect/HW/verify-irn.mlir, tools/firtool/firtool.cpp
Until have proper container op to put the trait on, add a dummy struct we can classof to classify IRN-like, and add a simple pass that drives verification on these if they aren't self-verifying.
Add verification pass to pipeline, basic test for duplicate inner symbols and invalid InnerRef user.
cc #3526 (nearly fixes), #4453.
cc #5716 .
=> [HW][IRN/IST] Make hw modules IST's, add verif pass.

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, lib/Firtool/Firtool.cpp
This adds the LowerClasses pass right before LowerToHW.  With this change, we can get a lowering of FIRRTL with properties right through the pipeline with Verilog output.
=> [firtool] Add LowerClasses for processing OMIR

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, test/Dialect/FIRRTL/test.mlir
This operation is meant to read in an encoded OM target string, with a pass later resolving the string target to a real target and validating the contents. This new operation purposefully does not contain much in the way of verification.
=> [FIRRTL] Add UnresolvedPathOp

include/circt/Dialect/FIRRTL/FIRRTLEnums.td
This adds OMIR path kind attribute for use in Path operations.  We will have to keep track of which kind of path was specified by the user throughout the pipeline, as it is not information which can be reconstructed later.
=> [FIRRTL] Add enumeration for OM path kinds

include/circt/Dialect/FIRRTL/FIRRTLUtils.h, include/circt/Dialect/HW/HWMiscOps.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLUtils.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
This change ensures that when lowering InnerSymbol operations, we copy the existing inner symbol to the target, as well as properly adding a symbol on fieldID 0 when required.  This fixes an assumption of symbol name uniqueness, and they are now uniqued in the module's symbol namespace. A side effect of this change is that the used symbol names are always of the form `@sym_1`. This also fixes a bug where an InnerSymAttr was assumed to target field ID 0, and could result in an inccorect lowering of the DontTouch annotation.
=> [FIRRTL][LowerToHW] Copy InnerSymAttrs to lowered ops

lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp, lib/Dialect/FIRRTL/Transforms/PrefixModules.cpp, test/Dialect/FIRRTL/SFCTests/ExtractSeqMems/Compose.fir, test/Dialect/FIRRTL/prefix-modules.mlir
Fixes an issue where a prefix may not be applied to modules created by grouping, see discussion in https://github.com/llvm/circt/pull/4596.
Note that this backport was tricky because the code in `PrefixModules.cpp` had changed quite a bit in the meantime, please check this carefully @seldridge.
=> Backport "[FIRRTL] Prefix for Seq Mem Group Extract (#4596)" to sifive-1.5

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/test.mlir
The PathOp is being re-worked to remotely reference hardware objects using (possibly non-local) annotations.  The hardware target recieves an annotation with class `circt.tracker` and an identifier.  The Path operation tracks the original target kind and the target identifier. It is legal to optimize away the hardware target, which will leave the Path op with a dangling identifier reference. A later pass will lower this FIRRTL PathOp to an OM specific Path operation, which will not use annotations.  See the example in FIRRTLExpressions.td for what this looks like in FIRRTL.
=> [FIRRTL] re-work PathOp to use annotations

include/circt/Dialect/Seq/SeqOps.td, include/circt/Dialect/Seq/SeqTypes.td, lib/Conversion/SeqToSV/SeqToSV.cpp, lib/Dialect/Seq/SeqOps.cpp, test/Dialect/Seq/canonicalization.mlir, test/Dialect/Seq/clock-type.mlir
The clock type will be used to carry the clock signal in a design. This PR allows it to be placed on module ports and wires, without forcing its use on all ops. Subsequent PRs will switch `seq` ops over to use it and generate it from FIRRTL.
Added `from_clock` and `to_clock` ops to allow the types to be introduced into the design and to permit black-boxes while intrinsics are developed to cover most use cases.
=> [Seq] Introduce a clock type

include/circt/Dialect/Seq/SeqOps.td, lib/Conversion/SeqToSV/SeqToSV.cpp, test/Dialect/Seq/dividers.mlir, test/Dialect/Seq/round-trip.mlir
The op lowers to a blocking assignment to ensure determinism. It is needed as `FIRRTL` cannot capture this behaviour.
=> [Seq] Added seq.clock_div to divide a clock by powers of two

include/circt/Dialect/OM/CMakeLists.txt, include/circt/Dialect/OM/OMDialect.h, include/circt/Dialect/OM/OMDialect.td, include/circt/Dialect/OM/OMEnums.td, lib/Dialect/OM/OMDialect.cpp
This attribute encodes the different kinds of targets used by OMIR.  These will be used by the Path operation.
=> [OM] Add TargetKind attribute for path operations

lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Import/FIRTokenKinds.def, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir
This adds parsing for path operations in to unresolved paths.
=> [FIRRTL] Add path op parsing

include/circt/Dialect/Pipeline/PipelineOps.td, lib/Dialect/Pipeline/PipelineOps.cpp, lib/Dialect/Pipeline/Transforms/ExplicitRegs.cpp, test/Dialect/Pipeline/Transforms/explicit-regs.mlir, test/Dialect/Pipeline/round-trip.mlir
Detect `sv.namehint` or OpAsmOpInterface's when routing values, and use these as the basis for register/passthrough names.
e.g.:
```mlir
hw.module @testNaming(%myArg : i32, %go : i1, %clk : i1, %rst : i1) -> (out: i32) {
%out:2 = pipeline.scheduled(%A : i32 = %myArg) clock(%c = %clk) reset(%r = %rst) go(%g = %go) -> (out: i32) {
%res = pipeline.latency 2 -> (i32) {
%d = comb.add %A, %A : i32
pipeline.latency.return %d : i32
}  {"sv.namehint" = "foo"}
pipeline.stage ^bb1
^bb1(%s1_valid : i1):
pipeline.stage ^bb2
^bb2(%s2_valid : i1):
%0 = comb.add %A, %res  {"sv.namehint" = "bar"} : i32
pipeline.stage ^bb3
^bb3(%s3_valid : i1):
pipeline.return %0 : i32
}
hw.output %out#0 : i32
}
```
eventually results in the following RTL:
```sv
module testNaming_p0(
input  [31:0] A,
input         enable, …
```
=> [Pipeline] Propagate names in `-pipeline-explicit-regs`

include/circt/Dialect/Ibis/IbisPasses.h, include/circt/Dialect/Ibis/IbisPasses.td, lib/Dialect/Ibis/Transforms/CMakeLists.txt, lib/Dialect/Ibis/Transforms/IbisTunneling.cpp, test/Dialect/Ibis/Transforms/scoperef_tunneling.mlir, test/Dialect/Ibis/Transforms/tunneling_errors.mlir
Tunnels relative `get_port` ops through the module hierarchy, based on `ibis.path` ops. The result of this pass is that various new in- and output ports of `!ibis.portref<...>` type are created. After this pass, `get_port` ops should only exist at the same scope of container instantiations.
=> [Ibis] Add tunneling pass

lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp, test/Dialect/FIRRTL/annotations-errors.mlir
Some operations don't have a value/type named when they are the target of an annotation or symbol.  Don't crash when attempting to resolve index or field accesses through refs to these.
Fixes #5947.
=> [FIRRTL] Fix crash resolving annotations through operations w/o "type".

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes.mlir
Maps to an i1 for now, since OM has no numeric types (integer or bool).
cc #5905 .
=> [FIRRTL][LowerClasses] Bool support.

lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp, test/Dialect/FIRRTL/extract-instances.mlir
When instances are grouped after extraction, the group module would inherit the appropriate prefix from the DUT, but any hierarchical paths pointing to it would not include the prefix. Fix this by using the same name for the module and the hierarchical path.
Fixes #5961.
=> [ExtractInstances] Fix module prefix not being applied to NLA

.github/workflows/buildAndTestWindows.yml
Change the GitHub Action that checks that the "main" branch isn't broken for Windows builds to use the Unified Build/Test/Install Action.
This switches from a cached LLVM to an sccache'd unified build.
- cache miss: https://github.com/llvm/circt/actions/runs/5972348937
- cache hit: https://github.com/llvm/circt/actions/runs/5977226743
=> [ci] Change Windows PR Action to use Unified B/T/I

include/circt/Dialect/FIRRTL/Passes.td, include/circt/Dialect/OM/OMOps.td, lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, lib/Dialect/OM/OMOps.cpp, lib/Firtool/Firtool.cpp
This PR has two changes which together are needed to have OM path operations work correctly. 
---
[OM] Class ops should not be symbol tables
Currently OM class operations are symbol tables and fields are symbols, which
is used to facilitate the lookup of fields.  The ObjectFieldOp verifier needs
to verify that it is accessing a legal field of the class, and does this by
first looking up the class in the MLIRModuleOp, and then the field in the
ClassOp.  This double lookup strategy is problematic because it does not follow
the normal rules of symbol resolution as defined by the SymbolTable.  This
means that anything that examines symbol uses (e.g. SymbolDCE) will be
incorrect.  We have faced this kind of problem before, which is why we invented
InnerSymbolTables and InnerSymbols.
This is …
=> [OM] Fix symbol resolution for classes and path operations

lib/Dialect/HW/HWOps.cpp, test/Dialect/FIRRTL/test.mlir
This changes the HierPathVerifier to support single-element paths which point to modules.  HierPathOps already support single-length paths to InnerSymbols, and we just needed to copy the logic to skip checking that the module matches the expected module name when the path is a single element.  Missing support is most likely a bug in the initial implementation, as the error message printed a null attribute.
=> [HW] HierPathOp: support single-element path to modules

include/circt/Dialect/OM/OMAttributes.td, lib/Dialect/OM/OMAttributes.cpp
This attribute represents a value of Path type, and can be used with the OM constant operation. For now it holds a string encoding of the path, but this will probably change in the near future.
=> [OM] Add dedicated path attribute

include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
Appears that multi-line strings get rendered differently, so just use `summary = "...";` for the one-line summary.
=> [FIRRTL][NFC] Split text for types out from summary if long, tweak.

lib/Dialect/FIRRTL/FIRRTLUtils.cpp
When an `InnerSymbolTarget` targets a field, `target.isOpOnly()` returns false. `getOrAddInnerSym` was mistakenly using this function to determine if the target was a port or a regular operation, causing it to treat all targets with fieldIDs as port targets.  This crashes when casting the target operation to a module op.  This changes `getOrAddInnerSym` to use `!target.isPort()` instead of `target.isOpOnly()` to check if the target is a port.
=> [FIRRTL] getOrAddInnerSym: fix bug when targeting a field

docs/Dialects/Ibis/RationaleIbis.md, docs/Dialects/Ibis/_index.md, include/circt/Dialect/Ibis/IbisPasses.h, include/circt/Dialect/Ibis/IbisPasses.td, lib/Dialect/Ibis/Transforms/CMakeLists.txt, lib/Dialect/Ibis/Transforms/IbisPortrefLowering.cpp, test/Dialect/Ibis/Transforms/portref_lowering.mlir
We do this by analyzing how a portref is used inside a container, and then creating an in- or output port based on that. That is:
- write to `portref<in portref<in, T>>` becomes `out T` i.e this container wants to write to an input of another container, hence it will produce an output value that will drive that input port.
- read from `portref<in portref<out, T>>` becomes `in T` i.e. this container wants to read from an output of another container, hence it will have an input port that will be driven by that output port.
- write to `portref<out portref<out, T>>` becomes `out T` i.e. a port reference inside the module will be driven by a value from the outside.
- read from `portref<out portref<in, T>>` becomes `in T` i.e. a port reference inside the module will be driven by a value from …
=> [Ibis] Add portref lowering pass

include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td, include/circt/Dialect/HW/HWTypeInterfaces.td, lib/Dialect/FIRRTL/FIRRTLTypes.cpp
Demonstrate using RefTypes.
Arguably should be a trait that adds the FieldIDTypeInterface trait and these methods, but simpler to do this by describing this as an "Interface" in ODS (and using interface inheritance is a bit clearer).
=> [HW][FIRRTL][NFC] Add AtomicFieldIDTypeInterface for no-field types.

lib/Conversion/ExportVerilog/ExportVerilog.cpp
Remove computation of instance port list, which is not used.
=> [NFC][ExportVerilog] Remove deadcode.

include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td, lib/Dialect/FIRRTL/Transforms/LowerOpenAggs.cpp, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/lower-open-aggs-errors.mlir, test/Dialect/FIRRTL/lower-open-aggs.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir
Similar to how RefTypes work, support properties in openbundles and immediately remove them into separate storage (ports).
=> [FIRRTL] Support properties in aggregates, remove immediately.

include/circt/Dialect/Ibis/IbisOps.td, lib/Dialect/Ibis/IbisOps.cpp, test/Dialect/Ibis/errors.mlir, test/Dialect/Ibis/round-trip.mlir
This PR adds a member variable defining operation (`ibis.var`) and a member variable dereferencing operation (`ibis.get_var`). `ibis.get_var` works by taking an ibis `scoperef` value alongside a symbol for the member variable name, and generates a `memref`-typed value. This value can then be used by `memref` ops to perform load/stores.
=> [Ibis] Add member variable ops

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h, lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, test/Dialect/FIRRTL/SFCTests/mem-taps.fir
Add logic for lowering Grand Central (GCT) memory taps to real ports.  Do
this by creating one port per memory item.  This is incredibly expensive.
However, this is the only way to actual synthesize this.
I reordered the `applyGCTMemTaps` function in https://github.com/llvm/circt/commit/e82e8263896890350484c9005467a4674d6d74aa to make this patch more straightforward.
=> [FIRRTL] Support noRefTypePorts in applyGCTMemTaps

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes-errors.mlir, test/Dialect/FIRRTL/lower-classes.mlir
This implements Map type lowerings. Currently reject non-string or integer key types in type converter.
=> [FIRRTL][LowerClasses] Lower map types and map.create

include/circt/Dialect/Arc/ArcDialect.td, include/circt/Dialect/Calyx/Calyx.td, include/circt/Dialect/Comb/Comb.td, include/circt/Dialect/DC/DCDialect.td, include/circt/Dialect/ESI/ESIDialect.td, include/circt/Dialect/FIRRTL/CHIRRTL.td, include/circt/Dialect/FIRRTL/FIRRTLDialect.td, include/circt/Dialect/FSM/FSM.td, include/circt/Dialect/HW/HWDialect.td, include/circt/Dialect/HWArith/HWArithDialect.td, include/circt/Dialect/Handshake/Handshake.td, include/circt/Dialect/Ibis/IbisDialect.td, include/circt/Dialect/Interop/Interop.td, include/circt/Dialect/LLHD/IR/LLHD.td, include/circt/Dialect/LTL/LTLDialect.td, include/circt/Dialect/LoopSchedule/LoopSchedule.td, include/circt/Dialect/MSFT/MSFT.td, include/circt/Dialect/Moore/MooreDialect.td, include/circt/Dialect/OM/OMDialect.td, include/circt/Dialect/Pipeline/PipelineDialect.td, include/circt/Dialect/SSP/SSP.td, include/circt/Dialect/SV/SVDialect.td, include/circt/Dialect/Seq/SeqDialect.td, include/circt/Dialect/SystemC/SystemCDialect.td, include/circt/Dialect/Verif/VerifDialect.td
Upstream switched the default, opt-out each dialect so we can update LLVM and start migrating dialects over individually.
cc #5273.
=> [NFC] Explicitly opt-out of default use of MLIR properties for attributes for now.

include/circt/Dialect/HW/HWStructure.td, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/HW/HWOps.cpp
Remove the usage of `getValue` since it recomputes the port list for every port. This is very expensive when there are huge number of ports.
=> [ExportVerilog] Remove getValue for InstanceOp

include/circt/Dialect/HW/HWOpInterfaces.td, lib/Conversion/ExportVerilog/LegalizeNames.cpp, test/Conversion/ExportVerilog/verilog-basic.mlir
Update the attribute for all the ports and set it together, instead of updating each individually.
This also fixes a bug with `LegalizeNames`, that was ignoring `verilogName` attribute when renaming ports.
Fixes: https://github.com/llvm/circt/issues/5986
=> [LegalizeNames] Update all port attributes together

include/circt/Dialect/Pipeline/PipelineOps.td
This fixes 2 problems with `pipeline.LatencyOp`:
1) `skipDefaultBuilders` is, but there was no corresponding C++ implementation of `LatencyOp::build`.
2) There is no way to specify the result type of a `pipeline.LatencyOp`
The fix is to enable the default builders to be generated.
=> Enable default builders for pipeline.LatencyOp

include/circt/Dialect/Ibis/IbisOps.td, test/Dialect/Ibis/round-trip.mlir
The `ibis.schedule` operation defines a block wherein a group of operations can be placed wherein a limited number of Ibis threads can execute at once. The operation is isolated from above and has no return types. References to external values should be performed through SSA dominance and memrefs.
=> [Ibis] Add ibis.schedule op

include/circt/Dialect/Pipeline/PipelineOps.td, integration_test/Dialect/Ibis/end_to_end.mlir, integration_test/Dialect/Pipeline/simple/simple.mlir, integration_test/Dialect/Pipeline/stall/stallTest.mlir, lib/Dialect/Pipeline/PipelineOps.cpp, test/Conversion/PipelineToHW/test_ce.mlir, test/Conversion/PipelineToHW/test_clockgates.mlir, test/Conversion/PipelineToHW/test_inline.mlir, test/Conversion/PipelineToHW/test_outlined.mlir, test/Dialect/Pipeline/Transforms/explicit-regs.mlir, test/Dialect/Pipeline/errors.mlir, test/Dialect/Pipeline/round-trip.mlir
Be a little bit more strict about naming here - the `i1` block argument of any given stage represents the stage **enable** signal - stage **valid** is reserved for the **output** signal/register of a stage, that is fed to its successor stage (as the successor stage enable signal).
=> [Pipeline] valid -> enable

include/circt/Dialect/FIRRTL/FIRParser.h, test/CAPI/firrtl.c, test/Dialect/FIRRTL/emit-basic.mlir
Give cover for emitter support for not-yet-released features, for testing purposes.
cc https://github.com/chipsalliance/chisel/pull/3517 .
Broken off from #5959 .
=> [FIRRTL] Bump latest to 3.2.0 for use in emitter / round-trip.

include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, lib/Dialect/FIRRTL/Export/FIREmitter.cpp, test/Dialect/FIRRTL/emit-basic.mlir
Only support emitting the unresolved (equivalent of FIRRTL textual form) path operation for now.
=> [FIRRTL] Add Path + List ops to visitor/emitter

include/circt/Dialect/ESI/cosim/CosimDpi.capnp, include/circt/Dialect/ESI/cosim/dpi.h, integration_test/Dialect/ESI/cosim/lowlevel_cosim_only.sv, lib/Dialect/ESI/cosim/Cosim_DpiPkg.sv, lib/Dialect/ESI/cosim/Cosim_MMIO.sv, lib/Dialect/ESI/cosim/cosim_dpi_server/DpiEntryPoints.cpp
Some platforms only support 32 bit MMIO, so in accordance with the least common denominator rule...
=> [ESI][Cosim] Reducing MMIO data widths to 32 bit

lib/Dialect/HW/HWOps.cpp, test/Conversion/HWToLLVM/convert_aggregates.mlir, test/Dialect/HW/canonicalization.mlir
Fold `hw.struct_extract` operations of `hw.aggregate_constant` to the constant value of their respective field.
This breaks a test in HWtoLLVM, which checks correct conversion of the `extract(constant)` pattern. Since dialect conversion inevitably performs a fold on the input operations before converting, the extract operation will always end up as  `hw.constant`. There does not appear to be a dedicated test for converting constants, so I opted to just keep it in and adapt the expected output.
=> [HW] Fold extracts of constant structs

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/parse-basic.fir
- Implement InstanceGraphInstanceOpInterface for object op
- Needed so that objects and classes will be tracked in the instance-graph
- InstanceOpInterface requires that we start tracking a name for each object
- In the IR printed format, the object's name is inferred from the name of it's result
- Switch to a custom asm format string
-  use the ImplicitSSAName custom directive to print/parse the attributes
- add a custom directive for printing a class's interface
- Drop the className attribute from the op
- we don't need it because classes don't let themselves be erased by symbol-dce anymore.
- this lets us use ImplicitSSAName without always printing an attribute dict.
=> [FIRRTL] Implement InstanceGraphInstanceOpInterface for ObjectOp

lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/LowerOpenAggs.cpp, test/Dialect/FIRRTL/lower-open-aggs-errors.mlir, test/Dialect/FIRRTL/lower-open-aggs.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir
Add support for parsing and lowering open aggregate wires. This currently works in a `firtool` pipeline so long as you run IMCP. I'm thinking about how to make it such that this optimization is not required for correctness (in `LowerClasses`). Currently `LowerClasses` will error out if the wires aren't removed.
There is fortunately already checking from `firrtl.propassign` that there are not multiple drivers.
Full example:
```
FIRRTL version 4.0.0
circuit Foo :
module Foo :
output a : { b : Integer, c: UInt<1>}[1]
wire d : { e : Integer, f: UInt<1> }[1]
invalidate d[0].f
propassign d[0].e, Integer(1)
propassign a[0].b, d[0].e
connect d[0].f, UInt<1>(0)
connect a[0].c, d[0].f
```
Produces with this patch (`firtool -ir-hw`):
```mlir
module {
hw.module @Foo() -> (a_0_c: i1) {
%false = …
```
=> [FIRRTL] Parse and lower Open Aggregates Wires

include/circt/Dialect/HW/PortConverter.h, lib/Dialect/HW/PortConverter.cpp, test/Dialect/SV/EliminateInOutPorts/hw-eliminate-inout-ports.mlir
Fixes a bug where an inout input was being eliminated which resulted in the block argument list shifting, but input->output replacements were not being updated correctly.
Fixed by keeping to-be-output values as temporary operations instead of an in-memory array of values. By doing so, any value replacements performed by other patterns will also affect the temporary output operations. ... that pattern should maybe be factored out and given a name - seems like a generic thing where we want to store a value for later use, but that value may be replaced at any point in time.
=> [SV] Fix --hw-eliminate-inout-ports

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp, test/Dialect/FIRRTL/imdce.mlir
This is the usual "can this be deleted" behavior observed elsewhere.
=> [FIRRTL][IMDCE] Declarations with annotations should not be removed.

include/circt/Dialect/Arc/ArcOps.h, include/circt/Dialect/Arc/ArcOps.td, lib/Conversion/SeqToSV/FirMemLowering.cpp, lib/Dialect/Arc/ArcTypes.cpp, lib/Dialect/Arc/CMakeLists.txt, lib/Dialect/Arc/Transforms/LowerState.cpp, test/Conversion/ConvertToArcs/convert-to-arcs.mlir, test/Dialect/Arc/Reduction/state-elimination.mlir, test/Dialect/Arc/arc-canonicalizer.mlir, test/Dialect/Arc/basic-errors.mlir, test/Dialect/Arc/basic.mlir, test/Dialect/Arc/canonicalizers.mlir, test/Dialect/Arc/dedup.mlir, test/Dialect/Arc/infer-memories.mlir, test/Dialect/Arc/infer-state-properties.mlir, test/Dialect/Arc/inline-arcs.mlir, test/Dialect/Arc/isolate-clocks.mlir, test/Dialect/Arc/latency-retiming.mlir, test/Dialect/Arc/lower-state.mlir, test/Dialect/Arc/split-loops-errors.mlir, test/Dialect/Arc/split-loops.mlir, test/Dialect/Seq/lower-firmem.mlir, test/arcilator/arcilator.mlir
This PR enforces the use of the clock type in some `arc` ops.
Part of #5851
=> [ARC][Seq] Switch arc over to use seq.clock

integration_test/Dialect/ESI/runtime/basic.mlir.py, integration_test/Dialect/ESI/runtime/basic_mmio.sv, integration_test/Dialect/ESI/runtime/basic_mmio.sv.py, integration_test/Dialect/ESI/runtime/lit.local.cfg.py, lib/Dialect/ESI/CMakeLists.txt, lib/Dialect/ESI/runtime/CMakeLists.txt, lib/Dialect/ESI/runtime/cpp/include/esi/Accelerator.h, lib/Dialect/ESI/runtime/cpp/include/esi/StdServices.h, lib/Dialect/ESI/runtime/cpp/include/esi/backends/Cosim.h, lib/Dialect/ESI/runtime/cpp/lib/Accelerator.cpp, lib/Dialect/ESI/runtime/cpp/lib/StdServices.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp, lib/Dialect/ESI/runtime/cpp/tools/esiquery.cpp, lib/Dialect/ESI/runtime/python/esi/esiaccel.cpp
Service C++ interface, Python wrapping, and cosim support for MMIO. Also adds the basic service framework.
=> [ESI][Runtime] MMIO service support

include/circt/Dialect/HW/HWOps.h, include/circt/Dialect/HW/InstanceImplementation.h, include/circt/Dialect/SV/SVStatements.td, lib/Dialect/HW/HWOps.cpp, lib/Dialect/HW/InstanceImplementation.cpp, lib/Dialect/MSFT/MSFTOps.cpp, lib/Dialect/MSFT/Transforms/MSFTPartition.cpp, lib/Dialect/MSFT/Transforms/MSFTToHW.cpp, lib/Dialect/MSFT/Transforms/PassCommon.cpp, lib/Dialect/MSFT/Transforms/PassDetails.h
This accepts slightly different operations in a couple places (more permissive), but I don't think this is a problem for any of the pipelines.
=> [NFC] Replace isAnyModule with an isa test.

include/circt/Dialect/Seq/SeqOps.td, integration_test/Dialect/Seq/registers.mlir, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Conversion/SeqToSV/FirMemLowering.cpp, lib/Dialect/FIRRTL/FIRRTLUtils.cpp, lib/Dialect/Seq/SeqOps.cpp, test/Conversion/FIRRTLToHW/emit-chisel-asserts-as-sva.mlir, test/Conversion/FIRRTLToHW/intrinsics.mlir, test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/Arc/strip-sv.mlir, test/Dialect/SV/hw-extract-test-code.mlir, test/Dialect/Seq/canonicalization.mlir, test/Dialect/Seq/firmem.mlir, test/Dialect/Seq/firreg-errors.mlir, test/Dialect/Seq/firreg.mlir, test/Dialect/Seq/lower-firmem.mlir, test/Dialect/Seq/round-trip.mlir, test/firtool/has_been_reset.fir
This PR forces the use of the clock type with `seq.firreg` and `seq.firmem`.
The new `firtool` version was tested on a large internal core.
Part of #5851
=> [FIRRTL][Seq] Lower `firrtl.clock` to `seq.clock`

include/circt/Support/InstanceGraph.h, lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp, lib/Dialect/FIRRTL/Transforms/LegacyWiring.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, lib/Support/InstanceGraph.cpp, unittests/Dialect/HW/CMakeLists.txt, unittests/Dialect/HW/GraphFixture.cpp, unittests/Dialect/HW/GraphFixture.h, unittests/Dialect/HW/InstanceGraphTest.cpp, unittests/Dialect/HW/InstancePathTest.cpp
This PR adds a light wrapper on top of instance path. With this wrapper, a subsequent PR should be able to de-duplicate instance paths to save on memory usage and provide quick comparison operators.
HW enumeration was also fixed and a new unit test codifies behaviour.
=> [InstanceGraph] Add a wrapper for instance paths and fix HW enumeration

lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp, test/firtool/blackbox-directories.fir
Fix a bug in FIRRTL's BlackBoxReader pass that could manifest if multiple
blackbox inline or blackbox path annotations wanted to write to the same
file.  Previously, the first annotation would win and all remaining
annotations would be skipped.  However, each of these annotations may have
different "output directory priority" and the first one that is found may
write to the wrong directory.
Concretely, these annotations can cause writes to any of the main output
directory (where "DUT" files go), the verification extracted directory,
the Grand Central directory, or the testbench directory.  The main output
directory is the "highest" priority and the testbench directory is the
"lowest" priority.  If a blackbox is in both, then it should be written to
the one with higher priority.
Change the …
=> [FIRRTL] Handle duplicate BlackBoxAnnos

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes-errors.mlir, test/Dialect/FIRRTL/lower-classes.mlir
This PR handles the conversion of "reading from an output port" to "reading from a field", by converting firrtl.object.subfield ops to om.object.field ops.
In order to convert object subfield ops from FIRRTL to OM, we need to convert the port index (as encoded in FIRRTL), to a symbol (as encoded in OM).  To do this, we can use the original input object's class type. However, by the time we are converting object subfield ops, the object has already been converted to an om.object, which no longer has this information. So, as we convert each class, we build a table from om class name back to its original firrtl class type, and make use of it in the converter for object subfield ops.
=> [FIRRTL] LowerClasses: support ObjectSubfieldOp

lib/Dialect/OM/Transforms/LinkModules.cpp, test/Dialect/OM/link-modules.mlir
Ignore top-level classes in the OM linker. This is a convenience that allows us to link the output of firtool without stripping any IR out. Perhaps a warning is better? What do you think?
=> [OM][LinkModules] Ignore top-level definitions we don't care about

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes.mlir
Property wires are added in some scenarios for convenience. This would be a good canonicalization pattern to have, but canonicalization shouldn't be needed for correctness. So, this pass explicitly handles wires of properties, by simply finding the single assignment to the wire, using that value instead of the wire, and removing the assignment.
Closes https://github.com/llvm/circt/issues/6051.
=> [FIRRTL] Update LowerClasses to handle property wires.

include/circt/Conversion/CFToHandshake.h, include/circt/Conversion/Passes.td, include/circt/Transforms/Passes.h, include/circt/Transforms/Passes.td, lib/Conversion/CFToHandshake/CMakeLists.txt, lib/Transforms/CMakeLists.txt, lib/Transforms/InsertMergeBlocks.cpp, lib/Transforms/MaximizeSSA.cpp
SSA maximization and merge block insertion are generally applicable transformations and so shouldn't be nested within CFToHandshake.
=> [Transforms] Move generally applicable passes to transforms

include/circt/Dialect/FIRRTL/FIRRTLStatements.td, include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/lowerXMR.mlir
Added basic placeholders for `sv.xmr.ref`, `firrtl.xmr.ref` and `firrtl.xmr.deref`, to the FIRRTL stages of the pipeline. This avoids the use of an unrealized conversion cast and leaves the lowering and type reconciliation to the later `LowerToHW` pass.
=> [FIRRTL] Replace the unrealized conversion cast in `LowerXMR` with an XMR op

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, test/Dialect/FIRRTL/SFCTests/constantProp.mlir
Insert all materialized constants above marker,
and handle them explicitly.
Don't rely on ConstantLike to avoid deleting the constants we inserted, and don't assume the materializeConstant only inserts a single operation.
Still check for ConstantLike to avoid folding/materializing constant operations that may have names on them.
=> [FIRRTL][IMCP] Separate materialized constants.

lib/Dialect/FIRRTL/FIRRTLDialect.cpp, lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, test/Dialect/FIRRTL/imconstprop.mlir, test/firtool/export-ref.fir
Fixes #6076.
Fixes leaving dead property wires around if they're constant-prop'd through.
Tweak export-ref test to demonstrate somewhat that this now enables a probe of a constant in a module to be hoisted to a probe of the constant at the boundary, allow for more cleanup -- in particular prevents modules with probed constants being preserved just for that reason. (The test adds a dontTouch to avoid this to check the exported macro)
=> [FIRRTL] Improve IMCP for non-hw; support mat'izing refs of constants.

include/circt/Dialect/Ibis/IbisOps.td, include/circt/Support/ParsingUtils.h, lib/Dialect/Ibis/IbisOps.cpp, lib/Support/CMakeLists.txt, lib/Support/ParsingUtils.cpp, test/Dialect/Ibis/errors.mlir, test/Dialect/Ibis/round-trip.mlir
The `ibis.block` operation defines a block wherein a group of operations are expected to be statically scheduleable. The operation is not isolated from above to facilitate ease of construction. However, once a program has been constructed and lowered to a sufficient level, the user may run `--ibis-argify-blocks` to effectively isolate the block from above, by converting SSA values referenced through dominanes into arguments of the block
The block may contain additional attributes to specify constraints on the block further down the compilation pipeline.
This operation subsumes the `ibis.schedule` in that `ibis.schedule` has the same semantics as if we attach some scheduling constraint attribute to the block.
=> [Ibis] Introduce `ibis.block` instead of `ibis.schedule`

include/circt/Dialect/Ibis/IbisOps.td, include/circt/Dialect/Ibis/IbisPasses.h, include/circt/Dialect/Ibis/IbisPasses.td, include/circt/Support/ParsingUtils.h, lib/Dialect/Ibis/IbisOps.cpp, lib/Dialect/Ibis/Transforms/CMakeLists.txt, lib/Dialect/Ibis/Transforms/IbisArgifyBlocksPass.cpp, lib/Support/CMakeLists.txt, lib/Support/ParsingUtils.cpp, test/Dialect/Ibis/Transforms/argify_blocks.mlir, test/Dialect/Ibis/errors.mlir, test/Dialect/Ibis/round-trip.mlir
Analyses `ibis.block` operations and converts any SSA value defined outside the `ibis.block` to a block argument.
=> [Ibis] Add `--ibis-argify-blocks` pass

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, test/Dialect/FIRRTL/imconstprop.mlir
This is the behavior used for wires, align.
GrandCentral makes use of many of these sorts of nodes.
Fixes #6096.
=> [FIRRTL][IMCP] Propagate through nodes with annotations, but keep.

include/circt/Dialect/OM/OMOps.td, include/circt/Dialect/OM/OMTypes.td, test/Dialect/OM/round-trip.mlir
The AnyType is used to represent any valid OM type, without needing to declare it. The AnyType cast can cast any value to AnyType. This is useful when dealing with values opaquely in a limited way.
=> [OM] Add AnyType and AnyType cast.

include/circt/Dialect/FIRRTL/FIRRTLTypes.h, include/circt/Dialect/FIRRTL/FIRRTLTypes.td, include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td, lib/Dialect/FIRRTL/Export/FIREmitter.cpp, lib/Dialect/FIRRTL/FIRRTLTypes.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Import/FIRTokenKinds.def, test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir, test/Dialect/FIRRTL/test.mlir
This is conceptually similar to Class type, but represents a reference to any class. It is opaque, like a void pointer, so it can be passed around but not "deferenced". For example, accessing a subfield of the referred to object is illegal.
=> [FIRRTL] Add AnyRef type, parser, emitter, and printed form.

include/circt/Dialect/ESI/ESIChannels.td, include/circt/Dialect/ESI/ESITypes.h, lib/Dialect/ESI/ESIOps.cpp, lib/Dialect/ESI/ESITypes.cpp, test/Dialect/ESI/bundles.mlir, test/Dialect/ESI/bundles_errors.mlir
A channel bundle (sometimes referred to as just "bundle") is a set of channels of associated signals, along with per-channel names and directions. The prototypical example for a bundle is a request-response channel pair.
=> [ESI] Channel bundle type and pack/unpack ops

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
FIRRTLFolds eliminates a single connection but it's only legal when the connection is in the same block as declaration.
=> [FIRRTLFolds] Make sure single connection is in the same block

include/circt/Dialect/FIRRTL/FIRRTLUtils.h, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/FIRRTLUtils.cpp, lib/Dialect/FIRRTL/Transforms/Dedup.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp, test/Dialect/FIRRTL/errors.mlir
Don't do this by default, as code reasonably expects the returned FieldRef has expected type if indexed to the specified fieldID, however when this is used for producing names just walk through the cast operations to find the originating declaration.
=> [FIRRTL] Optionally look through casts for fieldref chasing.

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLTypes.td, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/test.mlir
In situations where an object is instantiated and passed to a sink that expects any reference, we need to cast away the object's type to AnyRef type. This adds an operation to accomplish this, and inserts it when necessary in the parser.
=> [FIRRTL] Add AnyRef cast operation, and insert during parsing.

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes.mlir
The FIRRTL AnyRef type is converted to an OM Any type, and FIRRTL AnyRef casts are converted to OM Any casts. This is a straightforward conversion of the same concepts into the OM dialect.
=> [FIRRTL] Update LowerClasses to handle AnyRef and AnyRef cast.

include/circt/Dialect/SV/SVInOutOps.td, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/SV/SVOps.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir
Named the optional operand `init `instead of `reset` - i think that is more apt, to ensure that users don't mix the semantics of this operand with an actual (a)synchronous reset assignment.
=> [SV] Add optional `init` operand to `sv.reg`

lib/Dialect/OM/Evaluator/Evaluator.cpp, unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp
These casts are introduced in situations where the type of a value needs to be opaque. In the Evaluator, we just need to see through the cast to the actual value, and evaluate that.
=> [OM] Handle AnyType casts in Evaluator.

include/circt/Dialect/OM/OMPasses.h, include/circt/Dialect/OM/OMPasses.td, lib/Dialect/OM/Transforms/CMakeLists.txt, lib/Dialect/OM/Transforms/FreezePaths.cpp, test/Dialect/FIRRTL/lower-classes.mlir, test/Dialect/OM/freeze-paths-errors.mlir, test/Dialect/OM/freeze-paths.mlir, tools/firtool/CMakeLists.txt, tools/firtool/firtool.cpp
This adds the FreezePaths pass which performs the final lowering of path
operations after ExportVerilog.  This prepares the OMIR be split from the
hardware by transforming the dynamic hardware references in to frozen
attributes.
=> [OM][firtool] Add FreezePaths pass 

.github/workflows/uploadWheels.yml
See https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon
Because github doesn't provide an apple silicon runner, we cross-compile from the intel macOS runner but skip running the tests.
=> [CI] Use macOS universal wheels for M-series, add Python 3.9 and 3.11 support

include/circt/Dialect/FIRRTL/FIRRTLEnums.td, include/circt/Dialect/OM/OMEnums.td, lib/Dialect/FIRRTL/Transforms/ResolvePaths.cpp, lib/Dialect/OM/Transforms/FreezePaths.cpp, test/Dialect/FIRRTL/resolve-paths.mlir, test/Dialect/OM/freeze-paths.mlir
This path kind was mistakenly left out.  Upstream code for this path kind can be found [here]( https://github.com/chipsalliance/chisel/blob/e80de64571d47c90050893f066cf288b6acda505/core/src/main/scala/chisel3/properties/Path.scala#L19).
=> Add OMInstanceTarget path kind

include/circt/Dialect/Arc/ArcOps.td, lib/Dialect/Arc/ArcOps.cpp, test/Dialect/Arc/basic-errors.mlir, test/Dialect/Arc/basic.mlir, tools/circt-opt/CMakeLists.txt, tools/circt-opt/circt-opt.cpp
Hardware designs commonly have a considerable amount of duplicated logic for parallel execution (e.g., multiple cores). This logic can be collected and vectorized. This operation allows us to separate the concerns of finding logic to vectorize, applying a cost model on whether it is actually worth vectorizing the found set of operations (since gather, scatter, shuffling might be more expensive than what we save from vectorizing), and performing the actual vectorization to SIMD registers or pack them within a scalar register.
=> [Arc] Introduce vectorize operation

lib/Dialect/Pipeline/Transforms/ExplicitRegs.cpp, test/Dialect/Pipeline/Transforms/explicit-regs.mlir
The order of pass and reg operands was incorrect in between the order that block arguments were added to a stage, and the order that said block arguments were used to replace backedges within a block. Up until now, we were just lucky that our existing tests didn't actually infer any interleaving of pass and reg values flowing through the pipeline.
=> [Pipeline] Fix issue in ExplicitRegs

include/circt/Dialect/Ibis/IbisOps.td, include/circt/Dialect/Ibis/IbisPasses.h, include/circt/Dialect/Ibis/IbisPasses.td, lib/Dialect/Ibis/IbisOps.cpp, lib/Dialect/Ibis/Transforms/CMakeLists.txt, lib/Dialect/Ibis/Transforms/IbisCallPrep.cpp, lib/Dialect/Ibis/Transforms/IbisReblockPass.cpp, test/Dialect/Ibis/Transforms/argify_blocks.mlir, test/Dialect/Ibis/Transforms/reblock.mlir, test/Dialect/Ibis/Transforms/structure.mlir, test/Dialect/Ibis/errors.mlir, test/Dialect/Ibis/round-trip.mlir
Recreates `ibis.block` operations from a CFG. Any `ibis.block.attributes` operations at the parent operation will be added to the resulting blocks.
The IR is expected to be in maximal SSA form prior to this pass, given that the pass will only inspect the terminator operation of a block for any values that are generated within the block. Maximum SSA form thus ensures that any value defined within the block is never used outside of the block.
It is expected that `ibis.call` operations have been isolated into their own basic blocks before this pass is run. This implies that all operations within a block (except for the terminator operation) can be statically scheduled with each other.
Also adds changes to the Ibis method op to make it more "imperative". This is under the assumption that we …
=>  [Ibis] Add ibis reblock pass 

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir
=> [FIRRTL][Parser] Wires of non-agg non-hw should have droppable names.

lib/Dialect/FIRRTL/Transforms/Dedup.cpp, test/Dialect/FIRRTL/dedup.mlir
Don't dedup extmodule's that happen to have same signature -- if defname isn't present the module's expected verilog name is its module name and may have a different implementation.
Fixes:
```firrtl
circuit Dedup:
extmodule E1:
output x : UInt<1>
extmodule E2:
output x : UInt<1>
module Dedup:
inst e1 of E1
inst e2 of E2
```
becoming two instances of `E1` (or `E2`?).
=> [FIRRTL][Dedup] An extmodule without defname is unique.

lib/Dialect/FIRRTL/Transforms/Dedup.cpp, test/Dialect/FIRRTL/dedup-errors.mlir, test/Dialect/FIRRTL/dedup-locations.mlir, test/Dialect/FIRRTL/dedup.mlir
Don't dedup away modules marked for non-private visibility,
or otherwise can't have their symbols dropped even if unused.
This also prevents dedup of class operations, which is important
as we don't currently support rewriting all uses of that symbol
in instance types.
Fixes https://github.com/llvm/circt/issues/6061.
=> [FIRRTL][Dedup] Skip modules with syms we can't drop, classes. 

include/circt/Dialect/Arc/ArcDialect.td, lib/Dialect/Arc/Transforms/CMakeLists.txt, lib/Dialect/Arc/Transforms/LegalizeStateUpdate.cpp, lib/Dialect/Arc/Transforms/StripSV.cpp, test/Dialect/Arc/Reduction/pattern-registration.mlir, test/Dialect/Arc/legalize-state-update.mlir
Rewrite the access analysis used in the `LegalizeStateUpdate` pass.
This pass is a known performance bottleneck in arcilator and causes poor scaling to larger state spaces: on the `boom-small` benchmark in `circt/arc-tests`, the analysis runs for >130s, which accounts for >95% of the overall arcilator runtime.
This PR replaces the MLIR dataflow framework implementation of the analysis with a custom one. The analysis requires only very sparse traversal of the operations, which is a lot easier to implement with a custom graph of nodes. On `boom-small` the new implementation takes <200ms to complete.
=> [Arc] Improve performance of state update legalization

include/circt/Dialect/Arc/ArcOps.td, include/circt/Dialect/Arc/ArcPasses.h, include/circt/Dialect/Arc/ArcPasses.td, include/circt/Dialect/Arc/CMakeLists.txt, lib/Dialect/Arc/ArcOps.cpp, lib/Dialect/Arc/Transforms/CMakeLists.txt, lib/Dialect/Arc/Transforms/LowerVectorizations.cpp, test/Dialect/Arc/lower-vectorizations-boundary.mlir, test/Dialect/Arc/lower-vectorizations-full.mlir, test/Dialect/Arc/lower-vectorizations-inline-body.mlir
Adds a pass to lower  operations. Currently, only lowering the boundary and inlining the op body is supported. Lowering of the body will be added in a separate commit since that is a bit more complex.
=> [Arc] Add LowerVectorizations pass

include/circt/Dialect/Arc/ArcPasses.td, lib/Dialect/Arc/Transforms/LowerState.cpp, test/Dialect/Arc/lower-state.mlir, test/arcilator/arcilator.mlir
Make the `LowerState` pass allow operations to remain in the top-level `arc.model` op after state lowering. This is necessary for lowering the model op into an `eval` function in the future. Make use of this new flexibility by inserting logic into the model that detects edges on the clocks of the `arc.clock_tree` ops. The clock trees no longer trigger on the clock itself, but are given an "enable" signal that indicates whether a clock edge has been observed.
In the future, we'll want to schedule the ops in the `arc.model` and lower it to a separate `eval` function, instead of throwing it away. In doing so the user will no longer have to manually call clock functions, but can call a singular `eval` function instead. A centralized function that performs model execution will also allow us to …
=> [Arc] Allow top-level logic in LowerState; detect clock edges

include/circt/Dialect/Handshake/Handshake.td, include/circt/Dialect/Handshake/HandshakeInterfaces.td, include/circt/Dialect/Handshake/HandshakeOps.h, include/circt/Dialect/Handshake/HandshakeOps.td, test/Dialect/Handshake/errors.mlir
... by requiring that handshake ops are nested within an operation that inherits the `FineGrainedDataflowRegionOpInterface`. This is somewhat of a half-way solution, seeing as there isn't support for `HasParent` with an interface upstream. I've raised the issue and suggested a fix here https://github.com/llvm/llvm-project/pull/66196 but we'll see how long that takes to resolve.
Until then, added a `HasParentInterface` which does the same thing, albeit with a cryptic error message about which interface the parent op lacked (note: the whole issue here is that there isn't any name literal being generated for op interfaces).
I'll be monitoring the upstream stuff, and changing this over until then. For now, the motivation for adding this into circt is to unblock me in using handshake outside …
=> [Handshake] Allow handshake ops to be used outside of a `handshake.func`

include/circt/Dialect/Pipeline/PipelineDialect.td, include/circt/Dialect/Pipeline/PipelineOps.h, include/circt/Dialect/Pipeline/PipelineOps.td, include/circt/Dialect/Seq/SeqAttributes.td, include/circt/Dialect/Seq/SeqOps.td, integration_test/Dialect/Ibis/end_to_end.mlir, integration_test/Dialect/Pipeline/nonstallable/test1/nonstallable_test1.mlir, integration_test/Dialect/Pipeline/nonstallable/test2/nonstallable_test2.mlir, integration_test/Dialect/Pipeline/simple/simple.mlir, integration_test/Dialect/Pipeline/stall/stallTest.mlir, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Conversion/SeqToSV/SeqToSV.cpp, lib/Dialect/Pipeline/PipelineOps.cpp, lib/Dialect/Seq/SeqDialect.cpp, lib/Dialect/Seq/SeqOps.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Conversion/PipelineToHW/test_basic.mlir, test/Conversion/PipelineToHW/test_ce.mlir, test/Conversion/PipelineToHW/test_clockgates.mlir, test/Dialect/Pipeline/Transforms/explicit-regs.mlir, test/Dialect/Pipeline/Transforms/schedule-linear-pipeline.mlir, test/Dialect/Pipeline/errors.mlir, test/Dialect/Pipeline/round-trip.mlir, test/Dialect/Seq/canonicalization.mlir, test/Dialect/Seq/clock-gate.mlir, test/Dialect/Seq/clock-type.mlir, test/Dialect/Seq/externalize-clock-gate.mlir, test/Dialect/Seq/round-trip.mlir
This PR restricts the clock gate op to solely use the clock type.
Uses in other dialects, especially Pipeline, were adjusted.
To maintain canonicalization behaviour, a clock constant op along with an attribute is also introduced to represent constant clocks and to fold ops to them.
=> [Seq] Convert `seq.clock_gate` to use the clock type exclusively

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir
This already is supported for propassign (object -> anyref), allow in List/Map expressions as well.
These types continue to be invariant w.r.t their type parameters once created, add test that propassign rejects.
=> [FIRRTL][FIRParser] Add AnyRef cast as-needed for agg prop expr's.

include/circt/Dialect/Calyx/CalyxHelpers.h, include/circt/Dialect/Calyx/CalyxLoweringUtils.h, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Dialect/Calyx/Transforms/CalyxHelpers.cpp, lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp, test/Conversion/SCFToCalyx/convert_func.mlir
Here's a few things about this PR.
* I set the sym_name property of func.func during the lower.
If you don't do this, it will crash the program when creating `calyx.instance` because `func.func` and `calyx.component` have the same `sym_name` attribute. There are two identical names in the symbol table .So the name of func.func during lower is "func_" + `sym_name`.If there's a better way to name it, let me know .
*  Code using scf-to-calyx may not convert to the calyx native compiler.
This is because when creating calyx.invoke you can't get the specific names of the input and output ports (they can't be parsed in the pass).I apologize for this, to get the name of the port you have to go through parser.
* Currently I have not added integration tests
I noticed that calyx-to-hw doesn't appear …
=> [scf-to-calyx]Support for function call

include/circt/Firtool/Firtool.h, lib/Firtool/CMakeLists.txt, lib/Firtool/Firtool.cpp, tools/firtool/firtool.cpp
Context: https://github.com/llvm/circt/pull/6036#issuecomment-1711922222
=> [Firtool] Move the remaining pass additions into lib

include/circt/Dialect/Ibis/IbisOps.td, include/circt/Dialect/Ibis/IbisPasses.h, include/circt/Dialect/Ibis/IbisPasses.td, lib/Dialect/Ibis/IbisOps.cpp, lib/Dialect/Ibis/Transforms/CMakeLists.txt, lib/Dialect/Ibis/Transforms/IbisInlineSBlocksPass.cpp, lib/Dialect/Ibis/Transforms/IbisReblockPass.cpp, test/Dialect/Ibis/Transforms/argify_blocks.mlir, test/Dialect/Ibis/Transforms/inline_sblocks.mlir, test/Dialect/Ibis/Transforms/reblock.mlir, test/Dialect/Ibis/round-trip.mlir
Inlines `ibis.sblock` operations, by creating begin and end marker operations to denote the block scope. Attributes from the block will be placed upon the begin marker.
Similarly, the reblocking pass has been refactored to accommodate this change.
=> [Ibis] Add `ibis.sblock` inlining operations and passes

include/circt-c/Dialect/HW.h, integration_test/Bindings/Python/dialects/hw.py, lib/Bindings/Python/HWModule.cpp, lib/CAPI/Dialect/HW.cpp
`argNames` and `resultNames` attributes were removed from HWModule (https://github.com/llvm/circt/pull/6095) in the presence of ModuleType but downstream python tools are relying these attributes for name look up. However currently there is no CAPI/Python API for ModuleType to query names of ports so this PR adds CAPI and bindings respectively in the same way to port types.
=> [HW][Python] Add name getters for ModuleType

include/circt-c/Dialect/OM.h, integration_test/Bindings/Python/dialects/om.py, lib/Bindings/Python/OMModule.cpp, lib/Bindings/Python/dialects/om.py, lib/Bindings/Python/support.py, lib/CAPI/Dialect/OM.cpp, test/CAPI/om.c, unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp
Implement the python bindings for the `om.integer` attribute. Also ensure all tests use `om::IntegerAttr` instead of `mlir::IntegerAttr`.
=> [OM] Python bindings for om integer

include/circt/Dialect/Ibis/IbisOps.td, lib/Dialect/Ibis/IbisOps.cpp, test/Dialect/Ibis/errors.mlir, test/Dialect/Ibis/round-trip.mlir
The prior motivation for a single return value was to enforce... well, exactly that. However, this is nothing but a pain, requiring the user to tupel/struct-ify return values at a high level. This is a trivial transformation that can be done down the line. Allowing multiple return values, however, allows this op to play much more nicely with other passes and code that expects function-like operations (and terminators of said ops) to -generally speaking - accept multiple return values.
=> [Ibis] Allow multiple return values for `ibis.method`

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/complex-locations.mlir
Adds suppport for CallSiteLoc and NameLoc locations in export verilog. I tried to do this without refactoring the whole location printing infra too much, although some refactoring was due. Location printing has been modified such that:
1. There is a top-level dispatch function which dispatches `Location` printing to location type-specific print functions
2. No more passing around of `std::string`s. Instead, location emitter functions take a `llvm::raw_string_ostream`.
3. `FileLineColLoc` locations are still uniqued and printed in a sorted manner, as before. However, any other non `FileLineColLoc`-typed location will be printed without any custom uniquing (apart from set uniquing).
Location printing is still inline, i.e. without newlines. I can easily imagine that this can become a bit …
=> [ExportVerilog] Support CallSiteLoc and NameLoc emission

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp, test/Dialect/FIRRTL/imdce.mlir
This is a minimal change to keep all objects alive, as well as their ports (object subfield ops), as well as all writes to their ports (propassigns to object subfields). By marking objects as live, liveness should propagate through object subfield ops (which are handled the same as other subfield ops), and then through the propassigns (which are connect-like), back to the value being driven.
Class ops are ignored by this pass, so their bodies should not be cleaned up, and empty classes should be kept around.
The ObjectOp is not Pure, this prevents object ops from being deleted, even if they have no uses.
=> [FIRRTL][IMDCE] Mark all objects as alive

lib/Conversion/ExportVerilog/ExportVerilog.cpp
The `NameCollector` is only used to compute declaration word and type string length such that we can format declarations nicely. Currently it also asserts a weird invariant that `PrepareForEmission` must uphold, but then it never actually relies on that invariant. And for some reason the `NameCollector` also collects names in else branches of `IfOp`s, but not in then branches.
Push `NameCollector` more into the best-effort cosmetics direction it's already going by removing that assert and not visiting else branches. Either we visit both branches of an if, or none at all. And since if blocks introduce a separate scope with a separate place for decls, the visition is not necessary. (It would just potentially add whitespace to the if's surrounding scope's decl stack, to account for decls …
=> [ExportVerilog] Remove useless assert from NameCollector

.github/workflows/uploadWheels.yml
See https://github.com/llvm/circt/issues/6153
The universal macos wheels are failing, I will follow up in that issue to look for a resolution, but for now we should revert to building the standard wheel.
=> [CI] Hotfix macosx python wheel

lib/Dialect/HW/InstanceImplementation.cpp
Previously, `instance_like_impl::verifyReferencedModule` and `instance_like_impl::getReferencedModule` had different semantics for where the referenced module is located;
`getReferencedModule` uses the nearest parent `ModuleOp` as the target symbol table, whereas `verifyReferencedModule` uses the nearest (i.e. any) parent symbol table. As a result, `verifyReferencedModule` fails if the `hw.instance` op is nested within another symbol table operation.
e.g. the following would fail:
```mlir
module {
hw.module.extern @Foo()
ibis.container @C {
%this = ibis.this @C
hw.instance "foo" @Foo() -> ()
}
}
```
=> [HW] Align instance_like_impl verification with `getReferencedModule`

lib/Conversion/ExportVerilog/ExportVerilog.cpp
Way too many interleaved functions for them to be free functions - refactor as a class.
=> [NFC][ExportVerilog] Move location emission functions to class

include/circt/Conversion/CFToHandshake.h, include/circt/Dialect/Handshake/HandshakeOps.td, lib/Conversion/CFToHandshake/CFToHandshake.cpp
A couple of minor refactors - more will come - to allow for using `CFToHandshake` on things other than just `func.func` as the source operation and `handshake.func` as the target operation.
=> [CFToHandshake] Refactor towards genericness

include/circt/Dialect/Ibis/IbisOps.h, include/circt/Dialect/Ibis/IbisOps.td, lib/Dialect/Ibis/IbisOps.cpp, test/Dialect/Ibis/round-trip.mlir
Ibis dataflow methods share the same interface as an `ibis.method` but without imperative CFG-based control flow. Instead, this method implements a graph region, and control flow is expected to be defined by dataflow operations.
=> [Ibis] Add `ibis.method.df` operation

integration_test/Bindings/Python/dialects/hw.py, lib/Dialect/HW/HWTypes.cpp
`ModuleType::getInputTypes` returns inout types for inout ports but `getInputType` doesn't wrap with inout. This is inconsistent and python API `module_type.input_types` returns a wrong type for this.
=> [HW] Fix ModuleType::getInputType to return InOutType for InOut port

lib/Dialect/HW/HWTypes.cpp, test/Dialect/HW/types.mlir
Change `parseKeyword` to `parseKeywordOrString` in `StructType`, such that struct field names that aren't valid keywords in MLIR can still be used. They now print as quoted strings instead of crashing any MLIR tool trying to read the type back in.
=> [HW] Allow for quoted struct field names

.github/workflows/uploadWheels.yml
We were having problems with the universal MacOS wheels, so we reverted back to just building the x86 wheels. But this still fails, because these options are telling cibuildwheel to build for the universal architecture on MacOS, which is not enabled.
cc @leonardt
=> [Python] Remove CI options that only applied to MacOS universal.

include/circt/Dialect/Ibis/IbisOps.td, include/circt/Dialect/Ibis/IbisPasses.h, include/circt/Dialect/Ibis/IbisPasses.td, lib/Dialect/Ibis/Transforms/CMakeLists.txt, lib/Dialect/Ibis/Transforms/IbisConvertCFToHandshake.cpp, lib/Dialect/Ibis/Transforms/PassDetails.h, test/Dialect/Ibis/Transforms/cf_to_handshake.mlir
Converts an `ibis.method` into an `ibis.method.df` by converting controlflow using `cf` to `handshake` dialect conversion applied to the `ibis.method` body region.
=> [Ibis] Add Ibis CF to Handshake conversion

.github/workflows/uploadWheels.yml, lib/Bindings/Python/pyproject.toml
The wheel version string has been broken for python>=3.8. It seems
recent version of setuptools_scm has changed something, so
downgrade the version for now.
Also this commit removes python 3.7 supports since it caused some version conflicts.
Testing here: https://github.com/llvm/circt/actions/runs/6272413564
=> [Python] Downgrade setuptools_scm, drop python 3.7 as EOL

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, include/circt/Firtool/Firtool.h, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/HoistPassthrough.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/HWRename.fir, test/Dialect/FIRRTL/hoist-passthrough.mlir, test/firtool/extract-test-code.fir, test/firtool/passthrough-flips.fir, test/firtool/passthrough.fir
Basic driver analysis to detect must-driven values and hoist/rematerialize them using equivalent driver at instantiation site.
End-to-end example included for testing `-disable-opt` demonstrates why this is desirable -- here's a before/after diff:
```patch
--- /proc/self/fd/11	2023-09-12 15:22:35.254920380 -0500
+++ /proc/self/fd/12	2023-09-12 15:22:35.254920380 -0500
@@ -1,39 +1,10 @@
-// Generated by CIRCT firtool-1.54.0-30-g7bb1650e3
-module Child(
-  input  [4:0] x,
-  output [4:0] y
-);
-
-  assign y = x;
-endmodule
-
-module Mid(
-  input  [4:0] x,
-  output [4:0] y
-);
-
-  Child c (
-    .x (x),
-    .y (y)
-  );
-endmodule
-
+// Generated by CIRCT firtool-1.54.0-29-gc3332a678
module HWMultiLevel(
input  [4:0] x,
x2,
output [4:0] y
);
-  wire [4:0] _m2_y;
-  wire [4:0] _m_y;
- …
```
=> [FIRRTL][HoistPassthrough] Add pass to hoist must-driven output ports.

lib/Dialect/FIRRTL/Transforms/DropConst.cpp
This pass doesn't require it but mark it preserved as passes before/after might (presently they do).
=> [FIRRTL][DropConst] Mark InstanceGraph preserved.

lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/SFCTests/ExtractSeqMems/Compose.fir, test/Dialect/FIRRTL/SFCTests/dedup.fir, test/firtool/blackbox-directories.fir, test/firtool/memoryMetadata.fir, test/firtool/prefixMemory.fir
Deprecate the "-dedup" option.  Make this a no-op and always run FIRRTL deduplication.  It would be exceedingly rare for a user to actually not want dedup and it is a bit of a footgun that firtool requires users to specify it.
Treat this option as deprecated in 1.57.0 and remove it in 1.58.0. This makes things simpler as 1.57.0 will not require any atomic updates to projects which use firtool.
=> [firtool] Deprecate -dedup option

include/circt/Dialect/Pipeline/PipelineOps.td, integration_test/Dialect/Ibis/end_to_end.mlir, integration_test/Dialect/Pipeline/nonstallable/test1/nonstallable_test1.mlir, integration_test/Dialect/Pipeline/nonstallable/test2/nonstallable_test2.mlir, integration_test/Dialect/Pipeline/simple/simple.mlir, integration_test/Dialect/Pipeline/stall/stallTest.mlir, lib/Conversion/PipelineToHW/PipelineToHW.cpp, lib/Dialect/Pipeline/PipelineOps.cpp, lib/Dialect/Pipeline/Transforms/ExplicitRegs.cpp, test/Conversion/PipelineToHW/test_basic.mlir, test/Conversion/PipelineToHW/test_ce.mlir, test/Conversion/PipelineToHW/test_clockgates.mlir, test/Dialect/Pipeline/Transforms/explicit-regs.mlir, test/Dialect/Pipeline/Transforms/schedule-linear-pipeline.mlir, test/Dialect/Pipeline/errors.mlir, test/Dialect/Pipeline/round-trip.mlir
This also simplifies the stage enable signals, seeing as the entry enable signal will now always be the last argument of any mlir block inside the pipeline.
=> [Pipeline] Remove internal clock, reset,stall signals.

lib/Dialect/Ibis/Transforms/IbisContainersToHW.cpp
The containers-to-hw passes requires each output port to be written exactly once.  Extend the error message to contain the port name and the actual number of writes.
=> [Ibis] Print offending port name and use count on containers-to-hw error

docs/Dialects/SV/RationaleSV.md, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/MSFT/ExportQuartusTcl.cpp, test/Conversion/ExportVerilog/verilog-basic.mlir
Support format specifiers on Verbatim*Op substitutions. The first one only applies to hierpaths: the separation character.
=> [ExportVerilog] Format specifiers: hierpath separation character

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/GroupSink.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/group-sink.mlir
Add a new pass, GroupSink/firrtl-group-sink, which will sink operations that are only used by optional groups into optional groups.
=> [FIRRTL] Add GroupSink pass

include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h, lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp, lib/Dialect/FIRRTL/Transforms/RemoveUnusedPorts.cpp, test/Dialect/FIRRTL/canonicalization.mlir, test/Dialect/FIRRTL/imconstprop.mlir, test/Dialect/FIRRTL/imdce.mlir, test/Dialect/FIRRTL/remove-unused-ports.mlir
Add member functions to Annotation and AnnotationSet that can be used to
query if a specific Annotation or if all Annotations can be
removed/deleted.  There are certain "weak" annotations used by Object
Model which can be safely deleted because their downstream consumers will
_NOT_ error if they no longer exist.
As an aside, the whole notion of a removable annotation is somewhat
tenuous as a compiler could legally drop a removable annotation.  The
actual semantics of a removable annotation are best effort.
Switch from a static method to annotation member functions to determine of
a port with annotations can be deleted by IMDCE.
Modify the following passes to allow removal of weakly annotated things:
- Connect canonicalization (`canonicalizeSingleSetConnect`)
- IMCP
- IMDCE
- …
=> [FIRRTL] Cause "weak" OMIR Annotations to not block optimizations

include/circt/Dialect/Ibis/IbisPasses.h, include/circt/Dialect/Ibis/IbisPasses.td, lib/Dialect/Ibis/Transforms/IbisPortrefLowering.cpp, lib/Dialect/Ibis/Transforms/IbisTunneling.cpp, test/Dialect/Ibis/Transforms/path_end_to_end.mlir, test/Dialect/Ibis/Transforms/portref_lowering.mlir, test/Dialect/Ibis/Transforms/scoperef_tunneling.mlir
Tunneling did not work in case the same port was requested for multiple tunneling purposes (e.g. both reading and writing to an input port of an instance). Will this happen often/ever? probably not. But now it's supported - and i count it as an error, since the logic previously made multiple distinct accesses alias.
PortRef lowering did not work in case input ports were "forwarded" through modules. To support this, these forwarded ports will now create intermediate input ports within a module. By doing so, we allow the lowering patterns to recurse, since the intermediate port now looks like any other input port that is provided as a port reference. These input ports are then trivially removed by running `ibis-clean-selfdrivers` (which anyways is a prerequisite before running …
=> [Ibis] Fix issues in Tunneling and PortRef lowering

include/circt-c/Dialect/OM.h, include/circt/Dialect/OM/Evaluator/Evaluator.h, integration_test/Bindings/Python/dialects/om.py, lib/Bindings/Python/OMModule.cpp, lib/CAPI/Dialect/OM.cpp
This fixes an issue with the `Object` returned by `Evaluator::instantiate`, that was not "hashable".
In Python, a "hashable" object is an object that has a hash value that remains constant throughout its lifetime and can be compared to other objects. User-defined classes need to implement the `__hash__()` and `__eq__()` methods, to be hashable.
The `__hash__()` method should return an integer that represents the object's hash value, and the `__eq__()` method should define the object's equality with other objects.
This PR ensures the correct equality and hash methods are called on the underlying data-structures and not on the wrapper pointers.
Without this change, the test in `integration_tests` would create 3 entries in the dictionary.
=> [OM][Bindings] Make Python Evaluator Object hashable

include/circt/Dialect/FIRRTL/FIRRTLUtils.h, include/circt/Dialect/FIRRTL/FieldRefCache.h, lib/Dialect/FIRRTL/CMakeLists.txt, lib/Dialect/FIRRTL/FIRRTLUtils.cpp, lib/Dialect/FIRRTL/FieldRefCache.cpp, lib/Dialect/FIRRTL/Transforms/HoistPassthrough.cpp
As suggested in review to avoid worst-case behavior causing
many repeated walks of same indexing chain (in part or whole).
Pull into small helper class for possible re-use in transforms
or a simple analysis wrapper.
Refactor `getFieldFromFromValue` to be bother simpler and to share code with `FieldRefCache`'s version.
=> [FIRRTL] Simplify getFieldRefFromValue, add+use FieldRefCache.

lib/Conversion/SeqToSV/FirMemLowering.cpp, test/Dialect/Seq/lower-firmem.mlir
`FirMemLowering`  is creating incorrect width mask, when the optional mask input is missing from the memory access ops. 
Instead of creating a one bit mask for the optional mask input, it must be of appropriate mask width as determined by the `firmem`.
Fixes https://github.com/llvm/circt/issues/6213
=> [Seq][FirMemLowering] Create correct width constant for missing mask input

lib/Dialect/Ibis/Transforms/IbisInlineSBlocksPass.cpp, lib/Dialect/Ibis/Transforms/IbisPassPipelines.cpp, lib/Dialect/Ibis/Transforms/IbisReblockPass.cpp, test/Dialect/Ibis/Transforms/inline_sblocks.mlir, test/Dialect/Ibis/Transforms/reblock.mlir, test/ibistool/high_level.mlir
e.g. any MLIR block which contains ops should be moved into ibis `sblocks`. The `ibis.sblock.inline.begin/end` ops are only intended to delimit a scope of operations which has block constraints on them. However, this pass was always intended to also work on non-delimited ops. In the end, the result of the pass should be that the IR consists strictly of terminators (control flow) and `ibis.sblock` ops.
=> [Ibis] Reblock should also create blocks around non-delimited ops

lib/Dialect/FIRRTL/Transforms/LowerOpenAggs.cpp
Don't walk indexing operations multiple times, re-use FieldRef calculations.
=> [FIRRTL][LOA][NFCI] Use FieldRefCache.

include/circt/Dialect/FIRRTL/FIRParser.h, lib/CAPI/ExportFIRRTL/ExportFIRRTL.cpp, lib/Dialect/FIRRTL/Export/FIREmitter.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/CAPI/firrtl.c, test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir
Change the gating of new FIRRTL features from 3.2.0 to 3.3.0.  Simplify
this through the use of a new `nextFIRVersion`.
Change the name of the constexpr `latestFIRVersion` to `exportFIRVersion`
as this is not the "latest" version, but the version that is used when
exporting FIRRTL.  This will avoid confusion about what this is.
=> [FIRRTL] Bump FIRRTL version to 3.3.0 for parsing

tools/arcilator/arcilator.cpp
Minor update that moves LegalizeStateUpdate earlier in the pass pipeline. This is useful for tools that might want to replace the normal backend with a custom one (useful for export-cpp). Right before StateAlloc the Arc representation contains all the operations for a simulator, but hasn't yet allocated the exact state representation -- but the state needs be to legalized first. Thanks!
=> [Arc] Move LegalizeStateUpdate before StateAlloc

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir, test/firtool/groups.fir
=> [FIRRTL][Parser] Update groups version check to 3.2.0.

include/circt/Dialect/HW/HWTypesImpl.td, lib/Dialect/HW/HWTypes.cpp, test/Dialect/HW/errors.mlir
`hw.struct_extract`, `hw.struct_inject` and `hw.union_extract` refer to their respective field by name. However, field names of structs and union types are currently not enforced to be unique. This can cause ambiguities, e.g.:
```
hw.module @extract(in %a: i8, in %b: i8, out o: i8) {
%0 = hw.struct_create (%a, %b) : !hw.struct<foo: i8, foo: i8>
%1 = hw.struct_extract %0["foo"] :  !hw.struct<foo: i8, foo: i8>
hw.output %1 : i8
}
> circt-opt ... --canonicalize
hw.module @extract(in %a : i8, in %b : i8, out o : i8) {
hw.output %a : i8
}
``` 
This PR prevents the creation of HW aggregate types with duplicate field names.
As @seldridge pointed out to me, the FIRRTL dialect refers to subfields by index rather than by name. I've prepared a follow-up commit adopting this for StructExtract and …
=> [HW] Disallow duplicate field names in HW aggregate types

include/circt/Dialect/Ibis/IbisInterfaces.td, include/circt/Dialect/Ibis/IbisOps.td, include/circt/Dialect/Ibis/IbisPasses.td, lib/Dialect/Ibis/IbisOps.cpp, lib/Dialect/Ibis/Transforms/IbisArgifyBlocksPass.cpp, lib/Dialect/Ibis/Transforms/IbisPassPipelines.cpp, lib/Dialect/Ibis/Transforms/IbisPrepareScheduling.cpp, test/Dialect/Ibis/Transforms/argify_blocks.mlir, test/Dialect/Ibis/Transforms/prepare_scheduling.mlir, test/ibistool/high_level.mlir
Post-argification it makes a lot of sense to have an IsolatedFromAbove block:
1. for pass scheduling purposes (eg. prepare-scheduling pass)
2. To ensure that constants aren't being pulled out of `ibis.sblock`s during canonicalization (which makes things harder post-handshake conversion, when we expect argification to persist)
=> [Ibis] Add ibis.sblock.isolated

include/circt/Dialect/Ibis/IbisOps.h, include/circt/Dialect/Ibis/IbisOps.td, include/circt/Dialect/Ibis/IbisPasses.h, include/circt/Dialect/Ibis/IbisPasses.td, lib/Dialect/Ibis/CMakeLists.txt, lib/Dialect/Ibis/IbisOps.cpp, lib/Dialect/Ibis/Transforms/CMakeLists.txt, lib/Dialect/Ibis/Transforms/IbisConvertHandshakeToDC.cpp, lib/Dialect/Ibis/Transforms/IbisPassPipelines.cpp, test/Dialect/Ibis/Transforms/cf_to_handshake.mlir, test/Dialect/Ibis/Transforms/handshake_to_dc.mlir, test/ibistool/high_level.mlir, tools/ibistool/ibistool.cpp
Adds an Ibis-based handshake-to-DC conversion, using the handshake-to-DC conversion library. To facilitate this, a new block is introduced, which has a DC interface (`ibis.sblock.dc`).
=> [Ibis] Add handshake to DC conversion

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/ProbeDCE.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/input-probe-n-turn.mlir, test/Dialect/FIRRTL/input-probe-u-turn-dedup.mlir, test/Dialect/FIRRTL/parse-errors.fir, test/Dialect/FIRRTL/probe-dce-errors.mlir, test/Dialect/FIRRTL/probe-dce.mlir, test/firtool/spec/refs/endpoints.fir, test/firtool/spec/refs/in_ref_context.fir, test/firtool/spec/refs/invalid_in.fir, test/firtool/spec/refs/unused_in.fir, test/firtool/spec/refs/uturn.fir
Add and enable support for input probes.
Per spec, all uses (XMR read/force/release) of a probe must resolve to below the point of use in the hierarchy.
With this PR this is now supported in majority of cases.
The main exception to full support, with test demonstrating, is "n-turns" where a module uses an input probe (that resolves below that point) by sending it out and it comes back in equivalently driven in all instantiation contexts.
In this PR:
* Input probes enabled in parser
* Pass added to run after "de-squiggling" to drop all input probes, diagnosing when this is not possible (illegal input).
* Test cases involving input probes from spec now work.
=> [FIRRTL] Input probe support.

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir, test/Conversion/ExportVerilog/pretty.mlir
We currently blindly align the types and names of declarations, which causes excessively large types like structs to ruin the alignment of declarations. Instead, introduce an upper bound above which a type does not contribute towards the `maxTypeWidth` count. This means that excessively large types are just emitted without alignment, without other declarations being forced to follow the same alignment. This change is purely cosmetic.
Also tweak the code that emits the spacing around declarations to work by specifying a target column up to which spaces should be filled, and then filling in those spaces, or a minimum of 1. This makes it harder to get the alignment off by 1 just because some type or decl word was empty and didn't need a trailing space.
=> [ExportVerilog] Bound type size considered for decl alignment

include/circt/Dialect/Ibis/IbisPasses.h, include/circt/Dialect/Ibis/IbisPasses.td, lib/Dialect/Ibis/Transforms/CMakeLists.txt, lib/Dialect/Ibis/Transforms/IbisMethodsToContainers.cpp, test/Dialect/Ibis/Transforms/methods_to_containers.mlir
Dataflow methods can be converted to containers - which allows us to leverage all of the existing infrastructure for e.g. tunneling and outlining.
=> [Ibis] Add methods-to-containers pass

lib/Firtool/Firtool.cpp, test/firtool/register-optimization.fir
This PR adds extra IMCP just after register optimization pass.
We separated register optimization from IMCP to avoid changing
observable behaivor of hardward in IMCP but the separation started
to craete phase-ordering problem regarding IMCP and reg optimization pass.
This commit for now adds one more IMCP after register optimization
to fix one particular regression reported internally
=> [Firtool] Rerun IMCP after register optimizations

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLTypes.h, include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/FIRRTLTypes.cpp, lib/Dialect/FIRRTL/FIRRTLUtils.cpp, lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/expand-whens-errors.mlir, test/Dialect/FIRRTL/expand-whens.mlir
Objects can be classified as either local or remote. A local object is an actual firrtl.object declaration in the current scope. A remote object would be a class-typed port (of either the current module/class, or an instance/object).
For local objects, we are obligated to initialize their input ports. Sink-flow remote objects must be initialized by assigning to the entire thing, at the root.
This PR does a few things:
1) implement Field IDs for ClassType
2) implement FieldRef and field name utilities for objects
3) make expand-whens an interface pass that runs on FModuleLike operations, so that we can run it on class bodies in addition to modules.
4) In expand-whens, add support for flow checking of objects
=> [FIRRTL][ExpandWhens] Support flow checking for local and remote objects

integration_test/lit.cfg.py
`ibistool` was missing in the tool list in the integration test making it crash, so I simply added it in. Now the tests run without a problem.
=> [Ibis] Added missing ibistool to integration test

tools/om-linker/CMakeLists.txt, tools/om-linker/om-linker.cpp
We expect to run this tool on post-export IR, so load the appropriate dialects in the context.
=> [OM] Load post-export dialects in om-linker.

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes.mlir
While lowering an ExtModule, if it has a defname set, use that for the lowered ExtClass name. This is needed to ensure the lowered ExtClass lines up with the lowered Class.
This also plumbs around the SymbolTable, so we can use it to efficiently look up the referenced module while lowering instances, and check that for a defname when we build the name of the class for the object instance.
=> [FIRRTL] Update LowerClasses to use the defname for ExtModules.

include/circt/Dialect/Arc/ArcPasses.h, include/circt/Dialect/Arc/ArcPasses.td, lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp, lib/Dialect/Arc/Transforms/CMakeLists.txt, lib/Dialect/Arc/Transforms/LowerArcsToFuncs.cpp, test/Conversion/ArcToLLVM/lower-arc-to-llvm.mlir, test/Dialect/Arc/lower-arcs-to-funcs.mlir, tools/arcilator/arcilator.cpp
This splits out the parts of the LowerArcToLLVM pass that lower arc definitions to functions into a separate pass. This allows general function calls to be added by other passes in the pipeline before fully lowering to LLVM. Thanks!
=> [Arc] Add LowerArcsToFuncs pass

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
Remove canonicalizations related invalid values in RegOp since interpretation is context-dependent and it's unsafe to optimize before SFCCompat.
=> [FIRRTLFolds] Remove InvalidValue canonicalization

include/circt/Dialect/Arc/ArcPasses.td, lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp, lib/Dialect/Arc/Transforms/LegalizeStateUpdate.cpp, lib/Dialect/Arc/Transforms/LowerClocksToFuncs.cpp, test/Dialect/Arc/lower-clocks-to-funcs.mlir, test/arcilator/arcilator.mlir, tools/arcilator/arcilator-header-cpp.py
Lower `arc.model` operations to an eval function similar to what Verilator creates. Instead of requiring the user to explicitly call the clock and passthrough functions, the eval function will check which clock inputs toggled and then call the appropriate clock function. Since all clocks are now called from one central point, `LegalizeStateUpdate` can ensure that clock edges happening at the same time will both see the state values before the edge. This was impossible up until now, since the user had to call one clock function before the other, which would cause the state changes of the first clock to fully propagate before the second was called.
This is an important step forward to make Arc useful for simulating complex, multi-clock designs. There are still a few remaining issues around …
=> [Arc] Lower models into eval functions

lib/Dialect/OM/Transforms/FreezePaths.cpp, test/Dialect/OM/freeze-paths-errors.mlir, test/Dialect/OM/freeze-paths.mlir
The current logic doesn't support freezing paths with multiple public modules. In the current setup, multiple public modules are allowed, so this updates the instance graph traversal to allow rooting paths at the nearest public module.
=> [OM] Update FreezePaths to root paths at the nearest public module.

include/circt/Dialect/OM/OMTypes.td
This adds more path types which will be used for greater safety in OMIR. This change splits regular paths in to BasePathType and PathType, where the BasePathType is only capable of representing paths through the instance hierarchy, without being able to target hardware components such as wires and registers. In the future, all paths can only be created relative to some base path. This also adds a FrozenBasePathType and FrozenPathType, which will be used to represent lowered paths which no longer depend on the hardware hiearchy being present in the IR.
=> [OM] Add more path types

include/circt/Dialect/OM/Evaluator/Evaluator.h, integration_test/Bindings/Python/dialects/om.py, lib/CAPI/Dialect/OM.cpp, lib/Dialect/OM/Evaluator/Evaluator.cpp, unittests/Dialect/OM/Evaluator/CMakeLists.txt, unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp
This commit adds support for graph regions for evaluator.
`ReferenceValue`, a new subclass of `EvaluatorValue`, is added to behave as pointers. `ReferenceValue` can be used as alias to different values and is created for `class.object.field` operation because `class.object.field` can access fields across class hierarchies and the fields might not be initilized yet. `RefenceValue` is not exposed to outside of evaluator implemenation. `EvaluatorValue::finalize` shrinks intermidiate `RefenceValue` in the evaluator value.
Evaluation algorithm is changed to worklist-based iteration. `instantiae` method first traverses the whole IR including sub-class, and create partially evaluaed values for all values and add these values to the worklist. After that we evaluate values until there is no …
=> [OM] Evaluator: Support graph regions

include/circt/Dialect/SV/SVInOutOps.td, test/Conversion/ExportVerilog/prepare-for-emission.mlir
Having an `sv.xmr.ref` op inside a procedural block such as `sv.alwayscomb` triggers an assertion in `PrepareForEmission`. The pass would identify the ref op as having side-effects and then go ahead and try to pull it outside the procedural block. Doing so would create a `sv.reg` op with multiple nested inout types, which breaks.
Fix the issue by marking the `sv.xmr.ref` op as pure. Taking a reference to something does not have a side-effect. It's accessing what's behind the reference that has side-effects.
=> [SV] Mark sv.xmr.ref op as pure

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir, test/firtool/spec/refs/force_nonpassive.fir
Keep forceable for now-- it's needed for uninferred resets presently, and has slightly better (if not ideal) behavior when attempting to rwprobe a non-passive aggregate.
Note: force_nonpassive.fir doesn't work with symbols, check.
We can't rwprobe() an aggregate that /must/ be lowered.  Forceable tries to allow this, but when using symbols this is just rejected.
Probably this should not be allowed.
=> [FIRRTL][FIRParser] Prefer RWProbe op as much as possible.

lib/Dialect/FIRRTL/Transforms/MergeConnections.cpp, test/Dialect/FIRRTL/merge-connections.mlir
Previously: #5780.
Fixes #6259.
(along with #5835 for the specific FIRRTL input)
=> [FIRRTL][MergeConnections] Reject non-passive aggregates.

include/circt/Dialect/FIRRTL/FIRRTLUtils.h, lib/Dialect/FIRRTL/FIRRTLUtils.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp
Keep FIRRTL-only for now due to dependence on dialect-specific mechanism to get port number from block argument.
(HW has this but don't want FModuleLike dep in HW)
=> [FIRRTL][NFC] Move FieldRef -> InnerSymTarget to utility.

docs/Dialects/Seq/RationaleSeq.md, frontends/PyCDE/test/test_constructs.py, include/circt/Dialect/Seq/SeqOps.td, integration_test/Bindings/Python/dialects/seq.py, lib/Bindings/Python/dialects/_seq_ops_ext.py, lib/Conversion/DCToHW/DCToHW.cpp, lib/Conversion/FSMToSV/FSMToSV.cpp, lib/Conversion/HandshakeToHW/HandshakeToHW.cpp, lib/Conversion/PipelineToHW/PipelineToHW.cpp, lib/Conversion/SeqToSV/SeqToSV.cpp, lib/Dialect/Arc/Transforms/InferMemories.cpp, lib/Dialect/Arc/Transforms/StripSV.cpp, lib/Dialect/Seq/SeqOps.cpp, test/Conversion/CalyxToHW/basic.mlir, test/Conversion/ConvertToArcs/convert-to-arcs.mlir, test/Conversion/DCToHW/basic.mlir, test/Conversion/FSMToSV/test_basic.mlir, test/Conversion/HandshakeToHW/test_buffer.mlir, test/Conversion/HandshakeToHW/test_cmerge.mlir, test/Conversion/HandshakeToHW/test_fork.mlir, test/Conversion/HandshakeToHW/test_pack_unpack.mlir, test/Conversion/HandshakeToHW/test_sync.mlir, test/Conversion/PipelineToHW/test_basic.mlir, test/Conversion/PipelineToHW/test_ce.mlir, test/Conversion/PipelineToHW/test_clockgates.mlir, test/Dialect/ESI/services.mlir, test/Dialect/Seq/compreg-errors.mlir, test/Dialect/Seq/compreg.mlir, test/Dialect/Seq/lower-fifo.mlir
In doing so, also opt to move to a keyword style assembly format, rather than a flat list of operands. This is needed to resolve the now two distinct, optional, operands that can occur in the assembly format (reset operands and the power-on operand). To avoid making things too complicated, a keyword is required for either group, e.g.
> `seq.compreg %in %clk reset %rst, %rstValue powerOn %po`
+some related cleanups in places where the default generated builder was being used (without good reason).
=> [Seq] Add optional power-on value to `compreg` ops

include/circt/Conversion/Passes.td, include/circt/Conversion/PipelineToHW.h, lib/Conversion/PipelineToHW/PipelineToHW.cpp, test/Conversion/PipelineToHW/test_poweron.mlir
```mlir
hw.module @testPowerOn(in %arg0: i32, in %arg1: i32, in %go: i1, in %clk: !seq.clock, in %rst: i1, out out0: i32, out out1: i1) {
%0:2 = pipeline.scheduled(%a0 : i32 = %arg0, %a1 : i32 = %arg1) clock(%clk) reset(%rst) go(%go) entryEn(%s0_enable) -> (out: i32){
%1 = comb.sub %a0,%a1 : i32
pipeline.stage ^bb1 regs(%1 : i32, %a0 : i32)
^bb1(%6: i32, %7: i32, %s1_enable : i1):  // pred: ^bb1
%8 = comb.add %6, %7 : i32
pipeline.return %8 : i32
}
hw.output %0#0, %0#1 : i32, i1
}
```
generates the following SystemVerilog, provided the `poweron` option is enabled (`0` assigned to the stage enable register).
```sv
module testPowerOn(
input  [31:0] arg0,
arg1,
input         go,
clk,
rst,
output [31:0] out0,
output        out1
);
reg [31:0] p0_stage0_reg0;
reg [31:0] p0_stage0_reg1; …
```
=> [PipelineToHW] Add optional power-on values to control registers

include/circt-c/Dialect/OM.h, include/circt/Dialect/OM/Evaluator/Evaluator.h, integration_test/Bindings/Python/dialects/om.py, lib/Bindings/Python/OMModule.cpp, lib/Bindings/Python/dialects/om.py, lib/CAPI/Dialect/OM.cpp, lib/Dialect/OM/Evaluator/Evaluator.cpp
Add the debug locations to the evaluator value, which will be used to generate `info` fields of the object model output json.
=> [OM] Add location info to EvaluatorValue

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, include/circt/Firtool/Firtool.h, lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Companion.fir, test/Dialect/FIRRTL/grand-central-errors.mlir
Instead of the `--instantiate-companion-only` flag, Grand Central now takes a `--grand-central-companion-mode` flag which specifies the handling of companion objects. The modes are:
* `bind`, the original behaviour
* `instantiate`, which creates explicit instances
* `drop` which removes companions and companion-only sub-hierarchies from the design
=> [FIRRTL][GrandCentral] Add a mode to drop companion modules

tools/circt-opt/CMakeLists.txt
This commit adds support for MLIR plugins to circt-opt.
=> [circt-opt] Export symbols for MLIR plugins

include/circt/Dialect/OM/OMAttributes.h, include/circt/Dialect/OM/OMAttributes.td, include/circt/Dialect/OM/OMOps.h, include/circt/Dialect/OM/OMOps.td, include/circt/Dialect/OM/OMUtils.h, integration_test/Bindings/Python/dialects/om.py, lib/Bindings/Python/OMModule.cpp, lib/Bindings/Python/dialects/om.py, lib/CAPI/Dialect/OM.cpp, lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, lib/Dialect/OM/CMakeLists.txt, lib/Dialect/OM/Evaluator/Evaluator.cpp, lib/Dialect/OM/OMAttributes.cpp, lib/Dialect/OM/OMOps.cpp, lib/Dialect/OM/OMUtils.cpp, lib/Dialect/OM/Transforms/FreezePaths.cpp, test/Dialect/FIRRTL/lower-classes.mlir, test/Dialect/OM/errors.mlir, test/Dialect/OM/freeze-paths-errors.mlir, test/Dialect/OM/freeze-paths.mlir, test/Dialect/OM/round-trip.mlir
This PR does an overhaul of how path related operations work in the OM dialect.
When OM classes are created from FIRRTL, a base path is now fed through the class hieararchy.  All paths to hardware objects are now created relative to the base path.  The `path` op has been renamed to `path_create`, and now takes a basepath SSA parameter, which means that it is impossible to create a path which is not relative to some base.
A second set of operations to create "frozen paths" have been added.  In FreezePaths, we lower all path operations to hard-coded strings, which allows us to remove the hardware from the OM IR and still be valid.  These operations have been changed to return `FrozenPathType`, which is to make sure that people don't try to inter-mix the two kinds of path types.  The …
=> [OM] Overhaul of path operations

include/circt/Support/Namespace.h, test/Dialect/SV/hw-export-module-hierarchy.mlir
Previously Namespace::newName could return empty string for empty string. This is a problematic behaivor since primary use cases of Namespace is symbol generation but empty string cannot be used a symbol.
For example HWExportModuleHierarchy crashed with an instance with an empty name.
This commit fixes the issue by pre-registering empty string in a constructor of Namespace.
=> [Namespace] Return an empty string for empty string.

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, include/circt/Firtool/Firtool.h, lib/Dialect/FIRRTL/Transforms/DropName.cpp, test/Dialect/FIRRTL/drop-name.mlir
This commit adds `strip` option to drop name pass. Even though there is `none` option but `none` option does keep existing names. `strip` explicitly strips all names to remove variable names form Chisel.
=> [FIRRTL] Add strip option to DropName

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
firrtl.instance with lowerToBind is lowered into bound instance and symbols are created for the instances. There was a bug that symbols were generated by instance names, not by an appropriate helper so there could have been name collisions (for exmaple. This commit fixes the issue by using inner symbol generation helper.
=> [LowerToHW] Fix symbol creation for empty names

lib/Dialect/HW/HWTypes.cpp, lib/Dialect/SV/Transforms/SVExtractTestCode.cpp, test/Dialect/SV/hw-extract-test-code.mlir
Update ETC to add non-empty and unique port names. The name itself is not important, but this exposes a bug in inconsistent port names with the `hw.instance` and the `ModuleType`. 
This is a temporary fix, to unblock downstream tools, while the actual bug is fixed.
=> [ExtractTestCode] Specify non-empty unqiue port names

include/circt/Dialect/FIRRTL/FIRRTLStatements.td, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
RecursiveMemoryEffects and RecursivelySpeculatable traits provides automatically derivation of side-effects of operations but these effects are computed by recursive IR walk. This is problematic for firrtl.when since when operations are often deeply nested, which prevents us from running canonicalizers before ExpandWhens. This PR just removes these traits and add caonincalizers for whens manually.
=> [FIRRTL] Remove RecursiveMemoryEffects and RecursivelySpeculatable from When op, add canonicalizers

lib/Dialect/HW/HWOps.cpp, lib/Dialect/HW/ModuleImplementation.cpp, test/Dialect/Comb/canonicalization.mlir, test/Dialect/DC/roundtrip.mlir, test/Dialect/HW/basic.mlir, test/Dialect/SV/hw-extract-test-code.mlir
Treat blockargs like other values and let the asm name hint interface compute names for them.  If the port name is a legal ssa name, it will be used, otherwise the legalization will compute a new name based on the port name.  This has stable round-tripping after the first round, which is consistent with other ops which provide ssa name hints.
=> [HW] round trip ModuleType non-ssa values

lib/Dialect/HW/InstanceImplementation.cpp
by using the required symbol table collection to resolve the module name.  The symbol table collection is required for this function explicitly for this lookup, it just wasn't being used
=> Fix performance regression in verifiers 

include/circt/Dialect/MSFT/MSFTOpInterfaces.h, include/circt/Dialect/MSFT/MSFTOpInterfaces.td, include/circt/Dialect/MSFT/MSFTPDOps.td, lib/Dialect/MSFT/ExportQuartusTcl.cpp, lib/Dialect/MSFT/MSFTOpInterfaces.cpp, lib/Dialect/MSFT/MSFTOps.cpp, lib/Dialect/MSFT/Transforms/MSFTLowerInstances.cpp, test/Dialect/MSFT/dynamic_instance.mlir
Adds a new operation to the MSFT dialect which specifies a multicycle path constraint in between two symbols.
This implementation does not opt in to the whole dynamic instance hierarchy specification of MSFT; do we want to do that? Would have to require some thinking about what it means that a PD constraint refrences two dynamic instances, wherein `msft.instance.dynamic` currently expects all nested pd constraints to reference the parent instance exclusively. To this, i don't think it will be needed in our immediate usecase, anyways (assuming we're going to use `hw.path.to_this` which itself will generate the `hw.hierpath` and _not_ use the dynamic instance hierarchy support in MSFT).
Also splits `DynInstDataOpInterface` into a two interfaces; one base interface (anything that pertains to …
=> [MSFT] Add multicycle path op

include/circt/Dialect/ESI/ESIPasses.h, include/circt/Dialect/ESI/ESIPasses.td, lib/Dialect/ESI/CMakeLists.txt, lib/Dialect/ESI/Passes/ESIBuildManifest.cpp, test/Dialect/ESI/manifest.mlir
An ESI system manifest is intended to describe the parts of a particular accelerator which may be relevant to software. A compressed version of it will be embedded in accelerators. It will eventually replace the services metadata json.
This first PR only outputs types on cosim ports.
=> [ESI] Start of system manifest: types

lib/Target/DebugInfo/EmitHGLDD.cpp, test/Target/DebugInfo/emit-hgldd.mlir
If an instance's Verilog name differs from the debug info instance name, add an additional `hdl_obj_name` field to the HGLDD output. Currently, the only way to trigger this is to have an instance name be a Verilog keyword, such that name legalization appens a `_N` suffix. In the future, with inlining and artificial levels of hierarchy, there are likely going to be more ways of how a DI instance name can differ from the Verilog hierarchy.
=> [Debug] Include Verilog instance names in HGLDD output

include/circt-c/Firtool/Firtool.h, include/circt/Firtool/Firtool.h, lib/CAPI/Firtool/Firtool.cpp, lib/Firtool/Firtool.cpp, tools/firtool/firtool.cpp
I noticed this while trying to bind Firtool APIs, not sure if there was some historical reason for this.
=> firtoolPopulateCHIRRTLToLowFIRRTL doesn't need a module

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/intrinsics.mlir
Change LowerToHW to not emit an uninitialized register in the SYNTHESIS-defined path when lowering a "firrtl.int.plusargs.value".  This is done to avoid a lint warning related to uninitialized registers.
Fixes #6307.
=> [LowerToHW] Avoid uninit plusargs.value reg

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir
It's necessary to use renamed field names. Fix #6316
=> [ExportVerilog] Fix struct inject op emisson

include/circt-c/Dialect/OM.h, include/circt/Dialect/OM/Evaluator/Evaluator.h, integration_test/Bindings/Python/dialects/om.py, lib/Bindings/Python/OMModule.cpp, lib/Bindings/Python/dialects/om.py, lib/CAPI/Dialect/OM.cpp, lib/Dialect/OM/Evaluator/Evaluator.cpp
This change adds evaluator support for frozen paths.
Two new EvaluatorValues have been added, one for BasePaths, which represent fragments of paths through the instance hiearchy, and one for Paths, which represent a full path to a hardware component.
When the evaluator instantiates an OM class, it is expected that it will usually have to pass in an empty basepath, which signifies that the class is at the top of the hierarchy. To facilitate this, we exposed the ability to create an empty basepath value in the python API.
Path values can be transformed in to strings, where in they are printed as FIRRTL style target paths. In the future, we may want a richer API. Deleted paths are represented as Path values with the targetKind attribute nulled out, which is handled specially in the string …
=> [OM] Add evaluator support for paths

lib/Dialect/ESI/ESIServices.cpp
I read the documentation on `walk` and it indicates that it is safe to delete the op in the function. So I think the of the bug fixed in https://github.com/llvm/circt/commit/3a2151c0f064125c7777e1b06fba869d887bda1a was just a missing `else`.
Confirmed with LLVM memory sanitizers.
=> [ESI] Fix operation deletion in services connecting

lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp, test/Dialect/FIRRTL/extract-instances.mlir
In the case we need need to make a new NLA for an instance that has moved past the module at which the old NLA was rooted, use the new instance's inner symbol name. This code path used the original inner symbol in the old NLA, but this would get out of sync if the new instance needed to get a new symbol in the namespace. Similar logic exists later in this method, but seems to have been missed here.
=> [FIRRTL] Update ExtractInstances to use the new instance symbol.

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
This PR factors out some of LowerAnnotation helpers to a header and introduces registerAnnotationRecord method so that downstream user can extend the table. 
Fixes #4933.
=> [FIRRTL] LowerAnnotations: Allow annotationRecords to be extended externally 

lib/Analysis/CMakeLists.txt, lib/Analysis/DebugInfo.cpp, lib/Target/DebugInfo/CMakeLists.txt, lib/Target/DebugInfo/TranslateRegistration.cpp, test/Analysis/debug-info.mlir, test/Target/DebugInfo/emit-hgldd.mlir
When traversing the IR in the `DebugInfo` analysis, consider `dbg.variable` operations when populating the scope of local names for a module. The current implementation is fairly straightforward, but as the debug dialect evolves and we begin to track module inlining and outlining, this analysis will become more involved and do more of the heavy lifting necessary to extract a clean debug hierarchy from the IR.
=> [Debug] Honor dbg dialect ops in DebugInfo analysis

include/circt-c/Dialect/ESI.h, include/circt/Dialect/ESI/ESIAppID.td, include/circt/Dialect/ESI/ESIOps.h, include/circt/Dialect/ESI/ESIServices.td, integration_test/Bindings/Python/dialects/esi.py, lib/Bindings/Python/ESIModule.cpp, lib/CAPI/Dialect/ESI.cpp, lib/Dialect/ESI/ESIServices.cpp, lib/Dialect/Handshake/Transforms/LowerExtmemToHW.cpp, test/Dialect/ESI/errors.mlir, test/Dialect/ESI/services.mlir, test/Dialect/Handshake/lower-extmem-esi.mlir
This makes for far more sensible hierarchies. Also makes the index field of AppIDs optional.
=> [ESI] Service requests now track AppIDs rather than instance hierarchy

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/MaterializeDebugInfo.cpp, lib/Dialect/FIRRTL/Transforms/PassDetails.h, test/Dialect/FIRRTL/materialize-debug-info.mlir, tools/firtool/firtool.cpp
Add the `MaterializeDebugInfo` pass, which creates debug ops to track FIRRTL-level ports, nodes, wires, registers, and instances throughout the pipeline. This is a fairly simple first attempt at tracking higher-level source language information through the compilation using the debug dialect.
Also add the `-g` option to firtool, which causes this pass to run very early on in the pipeline where all the high-level information is still available. Enabling this option will currently cause `ExportVerilog` to fail because of the additional operations in the IR -- to be rectified by a later PR.
=> [FIRRTL] Add debug info materialization pass

include/circt/Firtool/Firtool.h, lib/Firtool/Firtool.cpp, tools/firtool/firtool.cpp
Move the `-g` option from `firtool` the tool to `Firtool` the library. See discussion in #6309.
=> [firtool] Move -g option into firtool library

include/circt/Dialect/ESI/AppID.h, include/circt/Dialect/ESI/ESIInterfaces.td, include/circt/Dialect/ESI/ESIManifest.td, include/circt/Dialect/ESI/ESIServices.td, lib/Dialect/ESI/AppID.cpp
Some ops have an AppID as an inherent attribute. This (along with the `getAppID` function) covers those cases.
=> [ESI] Add `HasAppID` op interface

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Dialect/FIRRTL/lower-types.mlir
Fixes #6124.
The lowering for `bitcast` is initially introduced in PR #1949, for aggregate type
```scala
class MyTest extends Bundle {
val a0 = UInt(8.W)
val a1 = UInt(8.W)
val a2 = UInt(8.W)
val a3 = UInt(8.W)
val a4 = UInt(8.W)
}
```
it will be lowered to
fir
```mlir
%8 = firrtl.subfield %ram_MPORT_0[data] : !firrtl.bundle<addr: uint<1>, en: uint<1>, clk: clock, data: bundle<a0: uint<8>, a1: uint<8>, a2: uint<8>, a3: uint<8>, a4: uint<8>>, mask: bundle<a0: uint<1>, a1: uint<1>, a2: uint<1>, a3: uint<1>, a4: uint<1>>>
%9 = firrtl.subfield %ram_MPORT[data] : !firrtl.bundle<addr: uint<1>, en: uint<1>, clk: clock, data: uint<40>, mask: uint<5>>
%10 = firrtl.subfield %8[a0] : !firrtl.bundle<a0: uint<8>, a1: uint<8>, a2: uint<8>, a3: uint<8>, a4: uint<8>>
%11 = firrtl.subfield %8[a1] : …
```
=> [FIRRTL][LowerTypes] Keep the order of bundle fields in lowered `cat`

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/Lint.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Companion.fir, test/Dialect/FIRRTL/lint.mlir
This PR adds a new pass called `Lint` to the `FIRRTL` pipeline, that checks for asserts that are guaranteed to fail a simulation.
If the assert is enabled and the predicate is either a constant false or a reset, the pass emits an error on the assert.
The intention is that the pass can later be extended to include more checks.
=> [FIRRTL] Add a new pass to detect static asserts

include/circt/Dialect/FIRRTL/FIRRTLUtils.h, lib/Dialect/FIRRTL/FIRRTLUtils.cpp, lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
Add an argument to the callback of `walkGroundTypes` to indicate if the ground type is flipped.
This is required for dataflow analysis of connections of flipped aggregate fields, demonstrated in https://github.com/llvm/circt/pull/5647
=> [FIRRTL] Add bool isFlip argument to walkGroundTypes callback

include/circt/Analysis/DebugAnalysis.h, lib/Analysis/CMakeLists.txt, lib/Analysis/DebugAnalysis.cpp, lib/Analysis/TestPasses.cpp, lib/Target/DebugInfo/CMakeLists.txt, lib/Target/DebugInfo/TranslateRegistration.cpp, test/Analysis/debug-analysis.mlir
Add the `DebugAnalysis` which marks values and operations that only feed into debug info. This will later allow ExportVerilog to skip expressions and statements that are exclusively used by debug ops and are irrelevant for synthesis and simulation.
The analysis is fairly straightforward at the moment. In the future, we may want to be more clever about what we mark as debug-only. For example, certain debug info output formats may allow us to emit entire expressions and state machines, such that those can be stripped from the Verilog output. In that case, we'd want to look through expressions, wires, and registers when marking ops as debug-only. But some other formats may only allow us to point at named signals in the Verilog, such that any expression or register has to remain in Verilog, …
=> [Debug] Add debug-only value/op analysis

cmake/modules/AddCIRCT.cmake
One unforeseen consequence of https://github.com/llvm/circt/pull/6340 was that the "install-" targets (which used to be provided by MLIR) went away. This re-adds those targets without adding the libraries themselves to MLIR's export set.
=> [CMake] Re-add install targets for CIRCT libraries

lib/Dialect/OM/Transforms/FreezePaths.cpp, test/Dialect/OM/freeze-paths.mlir
Paths can be used to create lists, and when paths are frozen the list create ops will have the unfrozen type. This adds a simple rewrite to replace lists of paths with lists of the corresponding frozen path type.
=> [OM] Convert list create ops for lists of paths in FreezePaths.

include/circt-c/Dialect/MSFT.h, lib/Bindings/Python/MSFTModule.cpp
I ran into issues trying to make bindings to the C API and including the MSFT dialect header, and it seems it accidentally includes a C++ header. There's also an issue with an `enum` tag not being used when referring to `CirctMSFTDirection` which I fixed.
=> [CAPI][MSFT]: Remove include of C++ header in C-API

lib/Dialect/Ibis/Transforms/IbisContainersToHW.cpp, test/Dialect/Ibis/Transforms/containers_to_hw.mlir
Any operation which the dialect conversion framework so much as touches must be legalized. In general, when you're just trying to lower a few ops, you need to mark all other ops as legal.
=> [Ibis] Mark all not-illegal ops as legal

include/circt-c/Dialect/OM.h, integration_test/Bindings/Python/dialects/om.py, lib/Bindings/Python/OMModule.cpp, lib/Bindings/Python/dialects/om.py, lib/CAPI/Dialect/OM.cpp
In order to use the types in Python with isinstance, etc., we need to provide the mlir_type_subclass bindings. This adds the C API boilerplate and binds the types.
=> [OM] Add Python bindings for path types.

lib/Dialect/Arc/ArcTypes.cpp, lib/Dialect/Arc/Transforms/AllocateState.cpp, test/Dialect/Arc/allocate-state.mlir
This is a fix for an issue introduced by llvm/llvm-project@a21abc782a8e1cb718a10c471a3b634f3102fc1c via b895069. The alignment in LLVM was changed from 8 to 16 bytes but in Arc we still allocated memory according to the old alignment, thus leading to overlapping memory accesses (a store to a HW memory could modify the state of a register stored after it in memory).
=> [Arc] Align >=128-bit integers to 16 bytes

lib/Conversion/ArcToLLVM/CMakeLists.txt, lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp, test/Conversion/ArcToLLVM/lower-arc-to-llvm.mlir
Recently, arc operations where updated to use the `!seq.clock` type instead of `i1` values. However, if there are clock gates present that aren't explicitly represented using the clock gate operation, or some other arithmetic is performed on clocks, the lowering will fail because `!seq.clock` arguments and conversion operations would fail to legalize.
This commit adds conversion patterns for the `to_clock` and `from_clock` operations and the clock type itself.
Should we introduce a new `SeqToLLVM` conversion pass for this simple conversion or is it fine like that for now?
=> [Arc] Support lowering of seq clock type and conversion operations

include/circt/Dialect/Ibis/IbisDialect.td, include/circt/Dialect/Ibis/IbisInterfaces.td, include/circt/Dialect/Ibis/IbisOps.h, include/circt/Dialect/Ibis/IbisOps.td, lib/Dialect/Ibis/IbisOps.cpp, lib/Dialect/Ibis/Transforms/IbisCallPrep.cpp, lib/Dialect/Ibis/Transforms/IbisCleanSelfdrivers.cpp, lib/Dialect/Ibis/Transforms/IbisContainerize.cpp, lib/Dialect/Ibis/Transforms/IbisContainersToHW.cpp, lib/Dialect/Ibis/Transforms/IbisConvertCFToHandshake.cpp, lib/Dialect/Ibis/Transforms/IbisConvertHandshakeToDC.cpp, lib/Dialect/Ibis/Transforms/IbisMethodsToContainers.cpp, lib/Dialect/Ibis/Transforms/IbisPortrefLowering.cpp, lib/Dialect/Ibis/Transforms/IbisTunneling.cpp, test/Dialect/Ibis/Transforms/argify_blocks.mlir, test/Dialect/Ibis/Transforms/inline_sblocks.mlir, test/Dialect/Ibis/Transforms/structure.mlir, test/Dialect/Ibis/errors.mlir, test/Dialect/Ibis/inner_ref_errors.mlir, test/Dialect/Ibis/round-trip.mlir
- Symbol-defining operations nested within `ibis.class` and `ibis.container` ops are now declared as `InnerSymbol`s.
- `ibis.class` is now an `NestedSymbolTable`s.
- `ibis.method` can no longer inherit from `FunctionLike` since that interface is built around an assumption of the function inheriting from `Symbol`.
- Containers are NOT `InnerSymbolTable`s yet - we cannot yet support nested symbol tables; see #6330; given that `ibis.container` needs to be able to still be able to be placed inside an `ibis.class` op.
Given the latter point, this is not a perfect implementation. As such, some parts of the implementation is still underperformant (e.g. `ScopeOpInterface::lookupInnerSym` which essentially does a scan of `InnerSymbol` ops inside the scope to facilitate symbol-lookup-like …
=> [Ibis] Refactor to use inner symbols

lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/HW/HWTypes.cpp, test/Conversion/ExportVerilog/verilog-basic.mlir
Refactored `emitDims` to support both styles of printing dims.
=> [ExportVerilog] Support parameterized length unpacked arrays

lib/Conversion/CombToArith/CombToArith.cpp, test/Conversion/CombToArith/comb-to-arith.mlir
As discussed during the last ODM, we expect shift operations in comb to produce defined values (matching the SV and VHDL behavior) even if the shift amount matches or exceeds the width of the LHS operand. In contrast, the shift operations in LLVM IR produce undefined values (poison) in this case. When converting from CIRCT MLIR to LLVM IR we lower to the MLIR arith dialect as an intermediate step. Currently, the semantics of the arith shift operations are not fully specified (see [[1]](https://discourse.llvm.org/t/rfc-define-precise-arith-semantics/65507),[[2]](https://discourse.llvm.org/t/rfc-arithmetic-vs-llvm-dialect/72477/7)). As a result we cannot safely convert comb shifts to arith shifts directly. This PR changes the conversion patterns for shift operations, which should result in …
=> [CombToArith] Explicitly handle wide shifts to avoid UB

include/circt-c/Dialect/HW.h, include/circt/Dialect/HW/HWAggregates.td, include/circt/Dialect/HW/HWTypesImpl.td, lib/Bindings/Python/HWModule.cpp, lib/Bindings/Python/dialects/hw.py, lib/CAPI/Dialect/HW.cpp, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/HWToLLVM/HWToLLVM.cpp, lib/Dialect/HW/HWOps.cpp, lib/Dialect/HW/HWTypes.cpp, lib/Dialect/SV/Transforms/PrettifyVerilog.cpp, test/Dialect/HW/errors.mlir
This PR changes the HW StructExtract, StructInject, UnionCreate and UnionExtract ops to reference their accessed field by the respective aggregate type's field index instead of the field name. This allows us to access the field's FieldInfo struct directly instead of having to traverse the array to find the matching name.
This change should mostly stay under the hood. The op printers and parsers still use the field name, and builder interfaces are added for backward compatibility.
=> [HW] Reference struct/union fields by index

include/circt/Dialect/HW/HWAttributes.h, include/circt/Dialect/HW/HWTypesImpl.td, lib/Dialect/HW/HWAttributes.cpp, lib/Dialect/HW/HWOps.cpp, lib/Dialect/HW/HWTypes.cpp
Have the instance op builder try to resolve any parametric types in the module. If it fails, fallback to the parameterized module types and don't print an error message.
=> [HW] Resolve parametric types in the InstanceOp builder

lib/Dialect/Arc/Transforms/AddTaps.cpp, test/Conversion/ConvertToArcs/convert-to-arcs.mlir, test/Dialect/Arc/add-taps.mlir
`hw.wire` is not pure, but would end up in arcs that don't allow side-effecting ops. I assume there is no use of `hw.wire` operations anymore once they are tapped, right?
=> [Arc] Remove hw.wire once it is tapped

integration_test/Bindings/Python/dialects/comb.py, lib/Bindings/Python/dialects/comb.py
With a recent change upstream to the new `register_operation` decorators, we accidentally broke the Python class hierarchy for comb ops. Before this change, we would wrap the class generated by `register_operation`. This meant the added `create` methods were present on those classes, but when an operation was returned via Python bindings methods, it would not be a subclass of our final wrapped class; it would be the class returned by `register_operation`, and `isinstance` would not work as expected.
With this change, we first wrap the class with our decorator, then wrap it with `register_operation`. This way, when operations are returned from the Python bindings, the returned operation is a subclass of our final wrapped class, and `isinstance` works as expected.
A somewhat hacky but …
=> [Comb] Update Python binding decorators to wrap in the right order.

lib/Dialect/Arc/Transforms/InlineArcs.cpp
In a previous change we generalized the inliner to also be able to inline arcs into other arcs (see `arc.call` operation). There we also migrated our custom implementation to use the MLIR InliningUtils instead. However, it turned out that it performs poorly because of a lot of block splicing.
Note that the old pass traversed the call-graph bottom-up (inline arcs that don't have other calls inside first), while the current implementation processes arcs in the order in which they appear in the IR. However, the way it is implemented makes it easy to pre-compute any other ordering and pass it to the inliner.
Also, I slightly changed the way single-use and trivial arcs are counted in the statistics (now it just collects the statistics on the initial state of the IR instead of taking into …
=> [Arc] Fix InlineArcs pass performance

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir, test/Conversion/ExportVerilog/verilog-basic.mlir
Make the `ExprEmitter` track whether the current expressions is being emitted into an assignment-like context. Fix the emission of struct and array aggregates to only use `'{...}` assignment patterns when the expression is in such an assignment-like context. These patterns cannot be used otherwise.
For packed arrays and structs, pick `'{...}` assignment patterns or `{...}` concatenation based on whether they are printed in an assignment-like context or not.
For unpacked arrays (and later unpacked structs), properly emit an error if they are being printed outside an assignment-like context. Unpacked values cannot be created inline arbitrarily. Instead, the `PrepareForEmission` pass has to spill them into a separate variable to artificially construct an assignment-like context (the …
=> [ExportVerilog] Make ExprEmitter sensitive to assignment-like context

lib/Dialect/HW/HWOps.cpp, test/Dialect/HW/errors.mlir
Make sure the provided constant attribute's dimensions match the return type. Essentially a copy of the FIRRTL AggregateConstantOp verifier.
=> [HW] Verify dimensions for hw.aggregate_constant ops

.github/workflows/uploadWheels.yml
The macos-latest tag has been migrated to macos-12, and the version of cibuildwheel we use doesn't run with the version of Python included in macos-12 (Python 3.12). Note that this has no bearing on the versions of Python we build the wheels for; this is the cibuildwheel Python code that is running on the runner's default Python to set up the build for the version of Python the wheel is targeting.
To amend this, I am locking to MacOS tag to a specific version, and updating the cibuildhweel version.
Fixes https://github.com/llvm/circt/issues/6385.
=> [CI] Update Python wheel action for MacOS.

docs/Dialects/FIRRTL/FIRRTLAnnotations.md, include/circt/Dialect/FIRRTL/FIRRTLStructure.td, lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp, lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp
Fixes a few comment typos, plus some mis-named FIRRTL annotations in the annotation documentation.
=> [Docs] Fix documentation typos, NFC

lib/Dialect/OM/OMAttributes.cpp, test/Dialect/OM/round-trip.mlir
While testing some OM IR using the bytecode format, I noticed the bytecode parser barfed on the #om.path attribute:
```
loc("#om<path[mod1>inst1, mod2>inst2]>":1:4):
error: unbalanced '[' character in pretty dialect name
error reading inputs
```
I think the way we are using `>` here doesn't play nicely with the fact that attributes are serialized in bytecode in their printed form by default. We can define our own encoding, but for now, using a different separator fixes the issue. I also added a round-trip test for the PathAttr's printed form.
=> [OM] Tweak PathAttr syntax to be more amenable to bytecode.

include/circt/Dialect/OM/OMTypes.h, include/circt/Dialect/OM/OMTypes.td, lib/Dialect/OM/OMTypes.cpp, test/Dialect/OM/round-trip.mlir
This type wasn't needed after all. We may eventually want some form of this, but there is no immediate need. Removing this for now reduces maintainence burden until we are sure what we want.
=> [OM] Remove enum type.

lib/Dialect/SV/Transforms/HWLegalizeModules.cpp, test/Dialect/SV/hw-legalize-modules-packed-arrays.mlir
This PR refactors HWLegalizeModules to something more like existing lower types passes in order to support more complex patterns such as array concatenations. Several new tests are also added.
Fix https://github.com/llvm/circt/issues/5355.
=> [HWLegalizeModules] Lower types-like packed array handling (#5355)

integration_test/Dialect/ESI/runtime/loopback.mlir.py, lib/Dialect/ESI/ESIOps.cpp, lib/Dialect/ESI/runtime/CMakeLists.txt, lib/Dialect/ESI/runtime/cpp/include/esi/Accelerator.h, lib/Dialect/ESI/runtime/cpp/include/esi/Design.h, lib/Dialect/ESI/runtime/cpp/include/esi/Manifest.h, lib/Dialect/ESI/runtime/cpp/include/esi/StdServices.h, lib/Dialect/ESI/runtime/cpp/include/esi/Types.h, lib/Dialect/ESI/runtime/cpp/include/esi/Utils.h, lib/Dialect/ESI/runtime/cpp/include/esi/backends/Cosim.h, lib/Dialect/ESI/runtime/cpp/include/esi/backends/Trace.h, lib/Dialect/ESI/runtime/cpp/lib/Accelerator.cpp, lib/Dialect/ESI/runtime/cpp/lib/Design.cpp, lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp, lib/Dialect/ESI/runtime/cpp/lib/StdServices.cpp, lib/Dialect/ESI/runtime/cpp/lib/Utils.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Trace.cpp, lib/Dialect/ESI/runtime/python/esi/esiCppAccel.cpp, lib/Dialect/ESI/runtime/python/esi/esiCppAccel.pyi, test/Dialect/ESI/manifest.mlir
Create ports in the design hierarchy and wire them up to the correct service. Patch is a bit larger than it probably should be since it includes some not-unrelated NFC refactoring and `TraceAccelerator` support for writing to trace files.
=> [ESI][Runtime] Wire up services and ports into the design tree

include/circt/Dialect/Seq/SeqOps.td, include/circt/Dialect/Seq/SeqPasses.h, include/circt/Dialect/Seq/SeqPasses.td, lib/Conversion/PipelineToHW/PipelineToHW.cpp, lib/Dialect/Seq/SeqOps.cpp, lib/Dialect/Seq/Transforms/CMakeLists.txt, lib/Dialect/Seq/Transforms/LowerSeqShiftReg.cpp, test/Dialect/Seq/shiftreg.mlir
Adds a shift register operation to the seq dialect. The operation has an interface similar to a `seq.compreg.ce` operation, with an additional `size` to specify the number of stages.
Included is a default lowering to `seq.compreg.ce` operations. The main intention of introducing this operation is to be able to emit shift registers using target-specific resources.
I don't see a reason to add a non-clock-enabled shift reg operation in addition to this. If users need a non-clock-enabled shift register, it should suffice to emit a shift register with constant 1 clock-enable, whereafter (if lowered to e.g. `seq.compreg.ce`), the lowered primitive should have a canonicalization that considers the constant clock enable signal.
**Q**: Do we want an inner_sym on the op? And if so, which of the …
=> [Seq] Add shiftreg op

lib/Dialect/Comb/CombFolds.cpp, test/Dialect/Calyx/remove-comb-groups.mlir, test/Dialect/Comb/canonicalization.mlir, test/Dialect/Seq/hw-memsim.mlir
This is probably the most conservative implementation of this, but should suffice for the current requirements to this change. For any comb operation that has a canonicalizer, guard canonicalization on whether any operands are define outside of the current block. This still allows for (constant) folding, which (to me) still should be a safe thing to do across blocks - if that was not the case, then that would be a strange abstraction (i'd expect an op to be `IsolatedFromAbove` if it wants to prevent constant folding).
=> [Comb] Disallow canonicalization across MLIR blocks

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/GroupMerge.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/group-merge.mlir
Add a pass that merges optional groups which reference the same
declaration.  This exposes additional optimization opportunities and
produces better Verilog output for groups.
Add this pass to `firtool`.
Fixes #6228.
Input:
```
FIRRTL version 3.3.0
circuit Foo: %[[
{"class":"firrtl.transforms.DontTouchAnnotation", "target":"~Foo|Foo>A_a"},
{"class":"firrtl.transforms.DontTouchAnnotation", "target":"~Foo|Foo>A_b"},
{"class":"firrtl.transforms.DontTouchAnnotation", "target":"~Foo|Foo>A_B_a"},
{"class":"firrtl.transforms.DontTouchAnnotation", "target":"~Foo|Foo>A_B_b"}
]]
declgroup A, bind:
declgroup B, bind:
module Foo:
input b: UInt<1>
group A:
node A_a = a
group B:
node A_B_a = A_a
group A:
node A_b = b
group B:
node A_B_b = A_b
```
Old output (without this PR):
``` …
```
=> [FIRRTL] Add GroupMerge pass

include/circt-c/Dialect/FIRRTL.h, lib/CAPI/Dialect/FIRRTL.cpp
This PR adds FIRRTL C-API functions for property type, which are necessary for chipsalliance/chisel#3626.
I found that the port direction enum can be reused in the `FIRRTLClassElement` struct, so I renamed the enum and enumerations for that purpose. Since Chisel is probably the only user for now, I think the API breaking change might not be a big deal?
=> [FIRRTL][CAPI] Add functions for property types

include/circt/Dialect/Seq/SeqPasses.h, include/circt/Dialect/Seq/SeqPasses.td, lib/Dialect/Seq/Transforms/HWMemSimImpl.cpp, lib/Firtool/Firtool.cpp, test/Dialect/Seq/hw-memsim.mlir
`HWMemSimImpl` can now output 0 when read ports are disabled, which better matches FPGA behaviour. This squashes warnings emitted by downstream synthesis tools.
=> [HWMemSimImpl] Add a mode to set disabled outputs to zero

include/circt/Dialect/HW/HWOpInterfaces.h, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/HW/HWOpInterfaces.cpp
Pull the `getPortVerilogName` helper out of `ExportVerilog` and move it into the `hw::PortInfo` struct as `getVerilogName`. This allows other passes that run after Verilog emission to query a port's Verilog name without duplicating that piece of code.
=> [HW] Move getPortVerilogName helper into HW PortInfo; NFC

include/circt/Firtool/Firtool.h, lib/Firtool/Firtool.cpp
Fuilly remove deprecated -dedup option.
Land this after `firtool 1.57.0` is cut.
=> [firtool] Remove -dedup option

lib/Target/DebugInfo/EmitHGLDD.cpp, test/Target/DebugInfo/emit-hgldd.mlir
Extend `EmitHGLDD` to properly represent combinational expressions in the emitted HGLDD debug info file. This is a first prototype to experiment with recreating higher-level source language values from the low-level signals that survived all the way through Verilog emission.
Instead of just checking if `dbg.variable` ops directly point at something in the MLIR that has a public Verilog name, the emitter now looks through expressions, `dbg.struct`s, and `dbg.array`s, and builds up the equivalent expression in HGLDD. As a result, the emitted debug info file now contains enough for a debugger to reconstruct many of the interesting source language values from the values that are actually present in the output Verilog.
At a later point we might want to move some of the expression graph …
=> [Debug] Add expression support to HGLDD emission

include/circt-c/Firtool/Firtool.h, lib/CAPI/Firtool/Firtool.cpp
Option was removed in cac97104a042e7ebfa06ed24b82c0137d0e5d7e3
=> [Firtool][CAPI] Remove dedup option from C API

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Dialect/FIRRTL/lower-types.mlir
LowerTypes was crashing when lowering `unrealized_conversion_cast` from other dialects.
This PR fixes the crash and ignores the cast op from other dialects instead of lowering them.
=> [FIRRTL][LowerType] Handle unrealized_conversion_cast of other dialects

include/circt/Dialect/ESI/ESIChannels.td, integration_test/Dialect/ESI/cosim/cosim_only.sv, integration_test/Dialect/ESI/cosim/loopback.py, lib/Dialect/ESI/ESIPasses.cpp, lib/Dialect/ESI/ESIServices.cpp, lib/Dialect/ESI/Passes/ESILowerToHW.cpp, lib/Dialect/ESI/runtime/cosim/Cosim_Endpoint.sv, tools/esi/esi_cosim.py.in
Rather than identifying cosim endpoints by "%m", have them specified entirely upstream. The easiest way to ensure uniqueness then is to only allow cosim endpoints at the top level. This solves a number of issues, and also makes cosim look a lot more like other ESI services.
=> [ESI] Cosim: punt endpoint naming to users

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
This commit allows users to propagate attributes on modules to HW dialects. External passes hooked by pass plugin might want to control the passes based on annotation values but currently unhandled annotations or unknown attributes are not attached to lowered hw modules.
=> [LowerToHW] Pass through attributes on FModuleOp

lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/canonicalization.mlir, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/expand-whens-errors.mlir, test/Dialect/FIRRTL/grand-central.mlir, test/Dialect/FIRRTL/infer-resets-errors.mlir, test/Dialect/FIRRTL/inliner.mlir, test/Dialect/FIRRTL/lower-open-aggs.mlir, test/Dialect/FIRRTL/lower-types-errors.mlir, test/Dialect/FIRRTL/lowerXMR-errors.mlir, test/Dialect/FIRRTL/lowerXMR.mlir, test/Dialect/FIRRTL/parse-errors.fir, test/Dialect/FIRRTL/probe-dce-errors.mlir, test/Dialect/FIRRTL/test.mlir
Add verifier for public modules not having input-oriented probes.
Fixes #6432.
Previously: https://github.com/llvm/circt/pull/6121/files#r1334831540 .
=> [FIRRTL] Verify public FModuleLike's don't have input probes.

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td, include/circt/Dialect/FIRRTL/FIRRTLOps.h, include/circt/Support/InstanceGraph.h, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/FIRRTLReductions.cpp, lib/Dialect/FIRRTL/Transforms/AddSeqMemPorts.cpp, lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp, lib/Dialect/FIRRTL/Transforms/Dedup.cpp, lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp, lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp, lib/Dialect/FIRRTL/Transforms/InferResets.cpp, lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp, lib/Dialect/FIRRTL/Transforms/PrefixModules.cpp, lib/Dialect/FIRRTL/Transforms/ResolvePaths.cpp, lib/Dialect/HW/HWReductions.cpp, lib/Dialect/Ibis/Transforms/IbisTunneling.cpp, lib/LogicalEquivalence/LogicExporter.cpp
The instance graph is transitioning towards supporting multiple possible targets for instance operations. As a consequence, it can no longer assume that there are instance operations with a single target and it will expose a generic interface returning a list of targets.
This PR removes the lookup helper from the graph and instead provides the users (`firrtl::InstanceOp` in particular) with helpers to fetch the unique referenced instance.
=> [InstanceGraph] Remove the module lookup helper

lib/Dialect/Comb/CombFolds.cpp, test/Dialect/Comb/canonicalization.mlir
This is my first time working on the Comb dialect, so this might not be the most optimal fold implementation. This could be generalized to apply to ands and ors of more than 2 values, but I wasn't sure how to hook this up into the `m_Complement` matcher on line 776 (for `AndOp`). That would also have an average complexity of `O(n^2)` which isn't ideal.
=> [Comb]: Canonicalize and(x,y) and or(x,y) when x and y are defined by opposite comparisons

integration_test/Bindings/Python/dialects/esi_appid.py, lib/Dialect/ESI/AppID.cpp, lib/Dialect/ESI/Passes/ESIAppIDHier.cpp, test/Dialect/ESI/appid_hier.mlir
Don't call the callback on non-appid ops. Also, simplify some code sorting AppIDs merely to be deterministic.
=> [ESI] Fix AppID index walk

include/circt-c/Firtool/Firtool.h, include/circt/Dialect/SV/SVPasses.h, include/circt/Firtool/Firtool.h, lib/CAPI/Firtool/Firtool.cpp, lib/Dialect/SV/Transforms/HWExportModuleHierarchy.cpp, lib/Firtool/Firtool.cpp, tools/firtool/firtool.cpp
Move firtool pipeline configuration over to the same mechanism the rest of llvm and mlir use.  Export this via the CAPI.  Add a couple examples of methods to change options to the CAPI.  Interested parties are encouraged to finish out the set of functions.
Since the CAPI has no tests, this breaks nothing.
As an aside, the configuration space of the firrtl pipeline is WAY too big.
=> [FIRTOOL] Make firtool options behave like the rest of llvm.

include/circt/Dialect/HW/HWStructure.td, lib/Dialect/HW/HWOps.cpp, test/Dialect/HW/errors.mlir, test/Dialect/HW/round-trip.mlir
This PR introduces an op to represent instance alternatives in the HW dialect.
It brings in the definition and the syntax of the op. Subsequent changes will implement a FIRRTL source op and adjust the pipeline to handle then.
=> [HW] Introduce the `hw.instance_choice` op

include/circt/Dialect/HW/HWPasses.h, include/circt/Dialect/HW/Passes.td, lib/Dialect/HW/Transforms/FlattenIO.cpp, test/Dialect/HW/flatten-io.mlir
There was a bug in `FlattenIO`, it was crashing for instances of `hwModuleExternOp`.
If an instance op is flattened before the corresponding module op, then it results in an inconsistent IR.
Fix this issue, by using an explicit `InstanceOp` builder that doesn't rely on the module op.
=> [HW][FlattenIO] Fix extern module instances

lib/Conversion/ExportVerilog/CMakeLists.txt, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/ExportVerilog/PrepareForEmission.cpp
Skip debug dialect ops in `ExportVerilog` and `PrepareForEmission` since those operations and values are only used for debug info emission and cannot be materialized directly in the Verilog output. This allows for the IR to retain debug operations purely for the purpose of documenting how Verilog values map back to the source language.
This fixes an issue where enabling debug info in firtool via the `-g` option causes Verilog emission to fail due to the presence of `dbg.*` operations.
Ideally we'll use the `DebugAnalysis` in the future to skip entire expression trees, operations, values, and block arguments if they are only consumed by debug operations. Doing so isn't as trivial as skipping ops marked as debug-only by the analysis though, since that also skips def-before-use legalization …
=> [ExportVerilog] Skip debug dialect ops

include/circt/Dialect/ESI/ESIManifest.td, include/circt/Dialect/ESI/ESIServices.h, lib/CAPI/Dialect/ESI.cpp, lib/Dialect/ESI/ESIOps.cpp, lib/Dialect/ESI/ESIServices.cpp
Build them before calling the generator then let the generator modify it. Ensures that it is always present even if the generator ignores it. Also, fix a bug in the printer/parser.
=> [ESI][Manifest] Make service records required

integration_test/Dialect/ESI/runtime/loopback.mlir, lib/Dialect/ESI/runtime/cpp/include/esi/Accelerator.h, lib/Dialect/ESI/runtime/cpp/include/esi/backends/Cosim.h, lib/Dialect/ESI/runtime/cpp/include/esi/backends/Trace.h, lib/Dialect/ESI/runtime/cpp/lib/Accelerator.cpp, lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Trace.cpp
If createService returns null, it means either that service hasn't been
connected up externally or we do not have an implementation for it.
Either way, just ignore it and let it error when/if the user tries to
access it.
Also, pass the implementation name to createService to make it easier to
check compat.
=> [ESI][Runtime] When a service cannot be created, ignore it

lib/Dialect/HW/HWOps.cpp
Instead of using `getPortLoc(i)` which is implemented in terms of `getAllPortLocs()[i]`, just gather the locations once for populating the returned information.
On this test case, Debug build:
```
circuit Test: %[[
{ "class": "firrtl.transforms.DontTouchAnnotation", "target": "~Test|Test>x" }
]]
module Test:
input x : { y : UInt<1>[65536] }
```
LowerToHW: 12.1s -> 5.3s
VerifyInnerRefNamespace (x3): 11s -> 2.6s
ExportVerilog: 57.8s -> 16.8s
Overall: 127s -> 51.8s
=> [HW] Fix getPortList to avoid n^2 location gathering.

lib/Firtool/Firtool.cpp
Fix a missing linkage between a firtool command line option getting populate in FirtoolOptions.  This was manifesting as valgrind failures in the nightly regression.
Fixes https://github.com/llvm/circt/actions/runs/7032216458/job/19135500303
Fixes #6458
=> [firtool] Fix missing option setter

include/circt/Dialect/ESI/ESIManifest.td, include/circt/Dialect/ESI/ESIServices.td, lib/Dialect/ESI/ESIOps.cpp, lib/Dialect/ESI/ESIServices.cpp, test/Dialect/ESI/manifest.mlir, test/Dialect/ESI/services.mlir
Make the std service (if any) show up in the manifest. Allows the runtime to instantiate special support for std services.
=> [ESI] Add std service name to manifest

include/circt-c/Firtool/Firtool.h, include/circt/Firtool/Firtool.h, lib/CAPI/Firtool/Firtool.cpp, lib/Firtool/Firtool.cpp, test/CAPI/CMakeLists.txt, test/CAPI/firtool.c, test/CMakeLists.txt, test/lit.cfg.py
This PR is based on ~PR #6435~ the `main` branch. Appreciate @darthscsi's work on rewriting the part of options for Firtool-bin.
Based on the description in that PR
> Interested parties are encouraged to finish out the set of functions.
So I'm trying to finish the rest work.
I proposed two solutions, but @darthscsi was probably too busy to comment any further on this. So I implemented them both as 2 PRs to further preview how they look and then we can compare and discuss which one is better.
---
This is the first solution, which manually implements the setter functions for all options without using macros. The second solution is #6439.
This PR also added a simple test for Firtool-lib C-API.
---
@darthscsi Would you mind making some constructive comments on this? And I'd love to hear if …
=> [FIRRTL][CAPI] Add the rest of setters for options

include/circt/Target/DebugInfo.h, lib/Target/DebugInfo/EmitHGLDD.cpp, lib/Target/DebugInfo/TranslateRegistration.cpp, tools/firtool/firtool.cpp
Add an option to HGLDD file emission to only consider location information in the IR if the corresponding file exists on disk. This can help filter out placeholder filenames such as `<stdin>` or `<unknown>`. Also add a corresponding `--hgldd-only-existing-file-locs` option to firtool.
=> [Debug] Add option to only mention existing files in HGLDD

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/PassiveWires.cpp, test/Dialect/FIRRTL/passive-wire.mlir
This pass converts wires with flips in their types to wires with passive types.  This expands connects to resolve flips effects on data flow.  After expansion, flips carry no more information and can be removed from wires (as wires have duplex flow).
=> [FIRRTL] Passive Wires pass

.clang-tidy
The warning is too verbose and the header setup of CIRCT does not line up with it.
=> [NFC] Disable -misc-include-cleaner

include/circt/Dialect/Pipeline/PipelineOps.td
ArrayRef<BlockArgument> makes the elements 'const' unnecessarily, causing issues with upcoming LLVM bump, due to http://llvm.org/PR72765 .
There's no BlockArgumentRange, so use Block's typedef (=MutableArrayRef).
=> [Pipeline] Use Block::BlockArgListType to avoid const.

lib/Dialect/FIRRTL/Transforms/WireDFT.cpp, test/Dialect/FIRRTL/wire-dft.mlir
Extend WireDFT to support wiring the test-enable signal to ClockGateIntrinsicOp's in same manner it does extmodules magically matched as the test-enable wiring targets.
=> [FIRRTL][WireDFT] Wire test-en to ClockGateIntrinsic.

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir
Parse explicitly for rwprobe case for better handling and to avoid creating spurious indexing operations.
Instance results are supported by inserting a forceable bounce wire.  The wire replaces the instance port entirely (including its unbundled entry) locally, and is connected to/from the instance result.
Wires are created for entire result (port) only, and will be re-used by repeated rwprobe's to the result in part or whole. This means the entire port must be forceable and will go through the bounce wire.
Annotations will continue to resolve as they do today, not to the inserted bounce wire.
Indexing parsing based on code from #5809, thanks @youngar!
=> [FIRRTL][Parser] Improve rwprobe parsing, support inst results.

include/circt/Dialect/HW/HWPasses.h, include/circt/Dialect/HW/Passes.td, lib/Dialect/HW/Transforms/FlattenIO.cpp, test/Dialect/HW/flatten-io.mlir
Fix a bug in `FlattenIO`, it was incorrectly reordering the input and output port name attributes of a module.
=> [FlattenIO] Fix module input and output port name order.

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, include/circt/Firtool/Firtool.h, lib/Dialect/FIRRTL/Transforms/LowerIntrinsics.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/lower-intrinsics.mlir
Add the `--fixup-eicg-wrapper` option to firtool and the LowerIntrinsics pass. Setting the option will treat `EICG_wrapper` modules like an intrinsic and replace them with the `firrtl.int.clock_gate` operation.
In the long run, Chisel/FIRRTL designs will directly emit the clock gate intrinsic, and `EICG_wrapper` extmodules will be gone. However until we get there, this option provides an incremental path towards deprecating the `EICG_wrapper` pattern. It allows us to switch the CIRCT side of the flow over to the intrinsic without having to make changes to Chisel in lockstep. Once all relevant existing designs work with this switch enabled, Chisel projects can opt into emitting clock gates directly, and can gradually upgrade. At that point we can make firtool emit deprecation warnings for …
=> [firtool] Add option to treat EICG_wrapper as intrinsic

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td, include/circt/Dialect/FSM/FSMOps.td, include/circt/Dialect/HW/HWOpInterfaces.td, include/circt/Dialect/HW/HWStructure.td, include/circt/Dialect/Ibis/IbisOps.td, include/circt/Dialect/SystemC/SystemCStatements.td, include/circt/Support/InstanceGraphInterface.td, lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, lib/Dialect/HW/HWOps.cpp, lib/Dialect/MSFT/Transforms/PassCommon.cpp, lib/Support/InstanceGraph.cpp, test/Dialect/FIRRTL/errors.mlir, test/Dialect/HW/verify-irn.mlir
This PR introduces accessors for instance-like ops that allow multiple modules to be referenced and represented in the instance graph. Single-target users were adjusted to refer to one of their attributes instead of relying on the interface accessor.
=> [InstancePath] Add accessors to allow ops to reference multiple targets

lib/Target/DebugInfo/EmitHGLDD.cpp
Make paths emitted into HGLDD companion files relative to the file itself, or emit absolute paths. For example, the `foo/bar/hello.dd` companion file to `foo/bar/hello.sv` will now refer to the SV file as `hello.sv`, and to a `src/input.scala` file as `../../src/input.scala`. If paths cannot be made relative, for example because the output directory contains `../` components that cannot be handled, the paths are made absolute.
This fixes an issue where beforehand a tool consuming the HGLDD file would have to know the working directory in which `firtool` was run to create the HGLDD file. Now the files are self-contained, and paths are anchored at the HGLDD file itself.
=> [Debug] Make paths in HGLDD files relative

docs/Dialects/Debug.md, include/circt/Analysis/DebugInfo.h, include/circt/Dialect/Debug/DebugOps.td, include/circt/Dialect/Debug/DebugTypes.td, lib/Analysis/DebugInfo.cpp, lib/Dialect/FIRRTL/Transforms/MaterializeDebugInfo.cpp, lib/Target/DebugInfo/DumpDebugInfo.cpp, test/Analysis/debug-info.mlir, test/Dialect/Debug/basic.mlir
Add the `dbg.scope` operation to the debug dialect. The op creates an additional level of hierarchy in the DI, a "scope", which can be used to group variables and other scopes.
Operations such as `hw.module` introduce an implicit scope. All debug operations within a module are added to that implicit scope, unless they have an explicit `scope` operand. Providing an explicit scope can be used to represent inlined modules.
Scopes in DI do not necessarily have to correspond to levels of a module hierarchy. They can also be used to model things like control flow scopes, call stacks, and other source-language concepts.
This commit also introduces an optional `scope` operand on `dbg.variable`. The `DebugInfo` analysis, which traverses the IR and builds up a canonical representation of the DI, …
=> [Debug] Add scope op

lib/Conversion/CombToArith/CombToArith.cpp, test/Conversion/CombToArith/comb-to-arith.mlir
A `comb.concat` operation with only a single operand would cause an `arith.extui` to be emitted with the same operand and result type. This trips the verifier of `extui`. Add a special case to that conversion to simply remove the `comb.concat` if it only has one operand.
The canonicalizer would usually delete these degenerate concats, which is why we haven't seen this issue earlier.
Also slightly tweak the lowering to produce a shift and or op for the least significant operand of the concat, which is already in the right spot.
=> [CombToArith] Fix lowering of concat with single operand

include/circt/Dialect/Arc/ArcPasses.h, include/circt/Dialect/Arc/ArcPasses.td, lib/Dialect/Arc/Transforms/InferStateProperties.cpp, tools/arcilator/arcilator.cpp
Enable the `InferStateProperties` pass in the arcilator pipeline and make its enable and reset signal detection individually controllable. The enable portion is already supported by the rest of the arcilator pipeline and can produce 20%-35% speedup on the cores in arc-tests.Turn on enable detection by default.
The reset portion is not fully supported yet and causes the simulation to misbehave. It is disabled by default.
As a minor refactoring this removes the `constructor` field from the pass definition, such that the constructor and plumbing for options gets generated automatically. As a side effect, the constructor is now called `arc::createInferStateProperties` instead of the previous `arc::createInferStatePropertiesPass`. (Thanks @uenoku for the pointer.)
Shoutout to @maerhart and …
=> [Arc] Partially enable reset/enable detection

include/circt/Dialect/Arc/ArcOps.td, include/circt/Dialect/Arc/ArcTypes.td, lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp, lib/Dialect/Arc/ArcTypes.cpp, test/Conversion/ArcToLLVM/lower-arc-to-llvm.mlir, test/Dialect/Arc/basic-errors.mlir
Allow `!arc.state` to carry HW structs and arrays. The state only has to be able to compute the bit width of the inner type, but it does not care what exactly this type is.
Rework the Arc-to-LLVM lowering to do the entire lowering in one full conversion, instead of two separate ones. There is no real need for the split, and combining all patterns into one large conversion allows all Arc types to be directly converted to LLVM types. Previously, after the first partial conversion the IR would be in a strange in-between state of mixing Arc types into LLVM operations (for example, loads and stores of HW struct/array types).
=> [Arc] Add support for struct and array states

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, include/circt/Dialect/FIRRTL/FIRRTLStructure.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/round-trip.mlir
This PR introduces FIRRTL-level instance choices, along with a representation for the options based on which they make decisions. The names of the ops are provisional and subject to change.
=> [FIRRTL] Add options and instance choices

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp, test/Dialect/SV/hw-extract-test-code.mlir
Modules generated by ETC are currently marked as public but it should be private. This change allows the compiler to freely rename and reorder ports or names on them.
=> [SVExtractTestCode] Privatize generated modules

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/SpecializeOption.cpp, test/Dialect/FIRRTL/specialize-option-errors.mlir, test/Dialect/FIRRTL/specialize-option-omit.mlir, test/Dialect/FIRRTL/specialize-option.mlir
The `SpecializeOptions` pass eliminates instance choices and replaces them with instances targeting the modules associated with a case provided through the options.
=> [FIRRTL] Add a pass to specialize instance choices

lib/Target/DebugInfo/EmitHGLDD.cpp, test/Target/DebugInfo/emit-hgldd.mlir
Emit inline levels of hierarchy in the DI, introduced by the new `dbg.scope` operation, as inline module definitions. This is explicitly supported in HGLDD in order to represent inlined modules in the debug info as if they were still present. Language frontends may also choose to emit additional scope ops to represent lexical scopes, call stacks, and other source language constructs in the debug info. HGLDD will accurately represent these.
=> [Debug] Add inline scope support to HGLDD emission

include/circt/Dialect/FIRRTL/FIRRTLIntrinsics.h, lib/Dialect/FIRRTL/CMakeLists.txt, lib/Dialect/FIRRTL/FIRRTLIntrinsics.cpp, lib/Dialect/FIRRTL/Transforms/LowerIntrinsics.cpp
This PR wraps most of the functionality of `LowerIntrinsics` into a re-usable utility class and converts the lowering functions into classes more similar to conversion patterns.
This is done in order to allow other tools tools to re-use the `IntrinsicLowerings` to handle their own intrinsics.
=> [FIRRTL] Framework for intrinsic lowering

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
The `LowerToHW` logic that was moving the symbol from the port to the wire was incorrectly assuming that all the output ports are ordered after the input ports, this resulted in the port index mapping being incorrect. 
This was causing the incorrect port symbol being moved to a temporary wire.
Fix the port index calculation logic.
=> [LowerToHW] Fix output port index mapping

lib/Dialect/OM/Transforms/FreezePaths.cpp, test/Dialect/OM/freeze-paths.mlir
We added a type replacer and used it to update the type of list create ops previously, but a similar issue shows up if there are lists of paths in block arguments. This factors out some helpers added previously for list create ops, so the same logic and conversion can be used in block arguments.
=> [OM] Use type replacer to handle block arguments.

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp, test/Dialect/FIRRTL/inliner.mlir
If a `HierPathOp` has a root module that is flattened and inlined, then donot
retop the root module, this results in incorrect `HierPathOp` that as stale
symbols. 
This commit fixes the issue.
=>  [ModuleInliner] Donot retop a HierPathOp if flattening the root

integration_test/Dialect/ESI/runtime/loopback.mlir, integration_test/Dialect/ESI/runtime/loopback.mlir.py, lib/Dialect/ESI/runtime/CMakeLists.txt, lib/Dialect/ESI/runtime/cpp/include/esi/Types.h, lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp, lib/Dialect/ESI/runtime/python/esi/accelerator.py, lib/Dialect/ESI/runtime/python/esi/esiCppAccel.cpp, lib/Dialect/ESI/runtime/python/esi/esiCppAccel.pyi, lib/Dialect/ESI/runtime/python/esi/types.py
- Mirror the C++ design and type hierarchy.
- Add [de-]serialization support to/from Python objects.
- Add support for `void` type.
=> [ESI][Runtime] Add type serialization support to Python bindings

.github/workflows/unifiedBuildTestAndInstall.yml, .github/workflows/uploadReleaseArtifacts.yml
Give write permissions to jobs that upload release assets.
Set the `release-tag` explicitly so the upload action knows where to upload on manual runs (on a tag).  When triggered by a release this isn't needed but doesn't hurt.
Bump the upload-release-assets action v2 -> v3: https://github.com/AButler/upload-release-assets/releases/tag/v3.0
(This is needed for the `release-tag` support, also fixes a warning about node version).
=> [CI] Fix release asset upload job permissions, support manual runs.

.github/workflows/uploadReleaseArtifacts.yml
=> [CI] Bump runner for windows release artifacts 2019 -> 2022.

.github/workflows/uploadReleaseArtifacts.yml
One use case is manually pointing this at some revision to get artifacts for testing.  This now requires specifying this option if asserts and debug are desired.
When re-running a release tag job, this allows not doing this, and using the default configuration even on manual runs.
=> [CI] Add option to control whether workflow_dispatch has asserts+debug.

lib/Dialect/FIRRTL/Transforms/LowerSignatures.cpp, test/Dialect/FIRRTL/lower-signatures.mlir
Dummy internal paths must be added to expanded ports.
=> [FIRRTL] Fix the lowering of internal paths in LowerSignatures

include/circt/Dialect/FIRRTL/FIRRTLOps.h, include/circt/Support/Naming.h, lib/Conversion/SeqToSV/SeqToSV.cpp, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/FIRRTLUtils.cpp, lib/Dialect/FIRRTL/Transforms/DropName.cpp, lib/Dialect/FIRRTL/Transforms/MaterializeDebugInfo.cpp, lib/Dialect/HW/HWOps.cpp, lib/Support/CMakeLists.txt, lib/Support/Naming.cpp, test/Dialect/HW/canonicalization.mlir
As a general rule, when an op which does not actually materialize to a `SV` wire is erased, its name should be propagated around in the IR if it is good.
Fixes #6553
=> [HW][Seq] Select the better name when dropping wires and casts

lib/CAPI/Dialect/CMakeLists.txt
When the conversion from FSM to SV was added to the CAPI, an include of the circt/Conversion/Passes.h header was included for the pass registration function. But nothing guarantees the generated header that is included by Passes.h actually exists.
We have seen intermittent failures from it not existing, for example: https://github.com/llvm/circt/actions/runs/7474242994/job/20339994666
This adds a DEPENDS on the target that generates the missing header, so it will be available.
=> [FSM] Add CAPI dependency on conversion pass header generation.

include/circt/Dialect/Arc/ArcOps.td, test/Conversion/ConvertToArcs/convert-to-arcs-names.mlir, test/Conversion/ConvertToArcs/convert-to-arcs.mlir, test/Dialect/Arc/Reduction/state-elimination.mlir, test/Dialect/Arc/arc-canonicalizer.mlir, test/Dialect/Arc/basic-errors.mlir, test/Dialect/Arc/basic.mlir, test/Dialect/Arc/canonicalizers.mlir, test/Dialect/Arc/infer-memories.mlir, test/Dialect/Arc/infer-state-properties.mlir, test/Dialect/Arc/inline-arcs.mlir, test/Dialect/Arc/isolate-clocks.mlir, test/Dialect/Arc/latency-retiming.mlir, test/Dialect/Arc/lower-state.mlir
I was asked a few times what the `lat` means in the assembly format. I think spelling out latency should make it easier to understand what this attribute means.
Maybe we want to rename `arc.state` to something more meaningful at some point as well.
**Stacked PR: Only review top commit**
=> [Arc] StateOp: latency instead of lat in assembly format

lib/Dialect/Arc/Transforms/Dedup.cpp
Using [rr](https://rr-project.org/), I reproduced the crash described in https://github.com/llvm/circt/issues/5307.
I tried my hand at a fix, but bear in mind I have no idea what I'm doing, and I'm not sure if my analysis is correct, even less so the "fix". Any feedback is greatly appreciated.
```
arc.define @Queue_arc_5_split_0(%arg0: i4, %arg1: i1) -> i4 {
%c0_i4 = hw.constant 0 : i4
arc.output %c0_i4 : i4
}
arc.define @Queue_arc_5_split_4_0(%arg0: i4, %arg1: i1) -> i4 {
%0 = arc.call @Queue_arc_5_split_0(%arg0, %arg1) : (i4, i1) -> i4
arc.output %0 : i4
}
arc.define @TLMonitor_arc_2_12(%arg0: i1, %arg1: i4, %arg2: i4, %arg3: i1) -> i4 {
%0 = arc.call @Queue_arc_5_split_4_0(%arg2, %arg3) : (i4, i1) -> i4
arc.output %0 : i4
}
arc.define @TLMonitor_arc_2_13(%arg0: i1, %arg1: i4, %arg2: …
```
=> [Arc] Dedup: Fix use after free

include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td, include/circt/Dialect/FIRRTL/FIRRTLUtils.h, lib/Dialect/FIRRTL/FIRRTLTypes.cpp, lib/Dialect/FIRRTL/Transforms/DropConst.cpp, lib/Dialect/FIRRTL/Transforms/VBToBV.cpp, test/Dialect/FIRRTL/round-trip.mlir
Add support for representing an optional layer in each probe type.  This only handles storage and MLIR printing/parsing.
I'll be breaking this work up into a bunch of small pieces. This is the first.
=> [FIRRTL] Add Layer Association to Probes

docs/Dialects/FIRRTL/FIRRTLAnnotations.md
There is broken image src's paths in FIRRTLAnnotations.md. I saw them while reading the docs and corrected them.
=> broken image src's fixed

frontends/PyCDE/integration_test/esi_ram.py, frontends/PyCDE/integration_test/esi_test.py, frontends/PyCDE/integration_test/lit.cfg.py, frontends/PyCDE/src/bsp/cosim.py, lib/Dialect/ESI/CMakeLists.txt, lib/Dialect/ESI/runtime/cosim/driver.cpp, lib/Dialect/ESI/runtime/cosim/esi-cosim.py, lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp
The 'esi-cosim' script starts a simulation, waits for it to start, then executes the 'inner' command. When the specified command exits, it kills the simulation. Very helpful for debugging designs via ESI cosimulation.
Only supports Verilator currently.
=> [ESI][Runtime] Add a utility to wrap a command with a cosimulation

.github/workflows/buildAndTest.yml, .github/workflows/shortIntegrationTests.yml
Self-hosted runners were disabled in our repo, so none of our builds are being picked up. Going back to the slow ones (with less disk space) while we figure out the situation.
=> [Builds] Revert back to small runners

include/circt/Dialect/ESI/ESIStdServices.td, lib/Dialect/ESI/ESIStdServices.cpp, test/Dialect/ESI/services.mlir
Currently, can only request a single 32-bit register. In the future, we'll add the ability to request structs of config/status registers.
=> [ESI] Introduce MMIO std service

include/circt/Dialect/ESI/ESIManifest.td, include/circt/Dialect/ESI/ESIPasses.h, include/circt/Dialect/Seq/SeqOps.td, lib/Dialect/ESI/ESIAttributes.cpp, lib/Dialect/ESI/Passes/ESIBuildManifest.cpp, lib/Dialect/ESI/Passes/ESILowerToHW.cpp, test/Dialect/ESI/manifest.mlir
Since ESI hardware embeds the manifest, lower the zlib-compressed version of it to a module to be instantiated by a BSP.
=> [ESI] Lower manifest op to a ROM

lib/Dialect/FIRRTL/Transforms/LowerSignatures.cpp, test/Dialect/FIRRTL/lower-signatures.mlir
LowerSignatures creates anonymous bound wires as a place holder but these didn't get proper names from ports.
=> [FIRRTL] [LowerSignatures] Naming bounce wires properly

frontends/PyCDE/src/common.py, frontends/PyCDE/src/esi.py, frontends/PyCDE/src/module.py, frontends/PyCDE/src/system.py
Fix warning about holding on to MLIR ops. Service generator instances get held through a C++/Python interaction barrier, unlike regular instances. So the member variable `inst` (which points to the MLIR instance operation) has to be cleared before attempting to clear the live operations.
=> [PyCDE] Fix service generator warning

lib/Dialect/Comb/CombFolds.cpp, test/CAPI/firtool.c
This fixes O(N^2) compile time regression in OrOp(and other logical operations) canonicalizers. Currently tryFlattenOperands flattens operands by only one level, e.g:
Or(a, Or(b, Or(c, d)))
->
Or(a, b, Or(c, d))
->
Or(a, b, c, d)
Problematically this canonicalizer visits operands until a first operand we can flatten every time so this is problematic when chains is really long. This PR fixes the issue by flattening all operands recursively from a root all at once. Also flatteing is moved to a start of canonicalizations so that other canonicalizations are only applied to root operations. This PR should be essentially NFC but there are several differences in verilog files since canonicalizations are applied in a different order and are not canonical. 
Benchmark for one of the largest …
=> [CombFolds] Flatten operands all at once

include/circt/Dialect/Calyx/CalyxLoweringUtils.h, lib/Conversion/AffineToLoopSchedule/AffineToLoopSchedule.cpp, lib/Conversion/CFToHandshake/CFToHandshake.cpp, lib/Conversion/HWToLLHD/HWToLLHD.cpp, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Conversion/SeqToSV/SeqToSV.cpp, lib/Dialect/Arc/Transforms/ArcCanonicalizer.cpp, lib/Dialect/Arc/Transforms/GroupResetsAndEnables.cpp, lib/Dialect/Arc/Transforms/LatencyRetiming.cpp, lib/Dialect/Comb/CombFolds.cpp, lib/Dialect/Comb/Transforms/LowerComb.cpp, lib/Dialect/ESI/Passes/ESILowerPhysical.cpp, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, lib/Dialect/HW/ConversionPatterns.cpp, lib/Dialect/HW/HWModuleOpInterface.cpp, lib/Dialect/HW/HWOps.cpp, lib/Dialect/HW/Transforms/HWSpecialize.cpp, lib/Dialect/Handshake/HandshakeOps.cpp, lib/Dialect/Ibis/Transforms/IbisCallPrep.cpp, lib/Dialect/SV/SVOps.cpp, lib/Dialect/Seq/SeqOps.cpp, lib/Transforms/InsertMergeBlocks.cpp, lib/Transforms/MaximizeSSA.cpp, test/Dialect/LoopSchedule/errors.mlir
This is also doing a simple find-and-replace due to https://github.com/llvm/llvm-project/pull/78260
=> bump llvm submodule to tip of main (103fa3250c46)

frontends/PyCDE/integration_test/esi_ram.py, frontends/PyCDE/src/CMakeLists.txt, frontends/PyCDE/src/bsp/Makefile.xrt.mk, frontends/PyCDE/src/bsp/xrt.py, frontends/PyCDE/src/bsp/xrt_package.tcl, frontends/PyCDE/src/system.py, lib/Dialect/ESI/runtime/CMakeLists.txt, lib/Dialect/ESI/runtime/cpp/include/esi/backends/Xrt.h, lib/Dialect/ESI/runtime/cpp/lib/backends/Xrt.cpp
Xilinx Runtime Shell (XRT) support for exposing the MMIO header and manifest over MMIO. XRT is the platform used by Azure's NP instances which have access to attached U250 FPGAs. Works in both hw_emu and real hardware.
=> [ESI] XRT support for MMIO based manifest fetching

frontends/PyCDE/integration_test/esi_ram.py, frontends/PyCDE/integration_test/test_software/esi_ram.py, frontends/PyCDE/src/module.py, frontends/PyCDE/test/test_esi.py, lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp, lib/Dialect/ESI/runtime/cpp/tools/esiquery.cpp, lib/Dialect/ESI/runtime/python/esi/esiCppAccel.cpp, lib/Dialect/ESI/runtime/python/esi/esiCppAccel.pyi
Users can either explicitly specify metadata or it can be automatically generated.
=> [PyCDE] Add ESI metadata to modules

include/circt/Dialect/FIRRTL/FIRRTLIntrinsics.td, include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, include/circt/Dialect/Seq/SeqOps.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Conversion/SeqToSV/SeqToSV.cpp, lib/Dialect/FIRRTL/Transforms/LowerIntrinsics.cpp, lib/Dialect/Seq/SeqOps.cpp, test/Conversion/FIRRTLToHW/intrinsics.mlir, test/Dialect/FIRRTL/lower-intrinsics.mlir, test/Dialect/Seq/canonicalization.mlir, test/Dialect/Seq/clock-inv.mlir, test/Dialect/Seq/round-trip.mlir, test/firtool/clocking.fir
The clock inverter ops provides an explicit representation for the negation of the clock signal, without having to rely on clock casts and wire-level operations. 
At the FIRRTL level, it is useful for the represenation of JTAG-related hardware, which often relies on registers triggered on the negative clock edge, represented by wiring an inverted clock to the registers.
The inverter is not suitable for clock buffers, as double inversion can be optimized away by the compiler.
=> [Seq][FIRRTL] Add a representation for clock inverters

lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp
Clear 'dutModuleNames' and 'dutPrefix' along with the other members before running the pass.
Not doing so most likely caused the spurious CI failure in https://github.com/llvm/circt/actions/runs/7615901959/job/20741468888 where the "Plop" prefix got carried inadvertently. But I have no idea how this pass works, so take it with a grain of salt.
=> [FIRRTL][ExtractInstances] Clear entire state on pass invocation

lib/Dialect/FIRRTL/Transforms/Dedup.cpp, lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/firtool/classes-dedupe.fir
This adds initial support for Dedup to handle deduping classes and objects. For the most part, this amounts to ensuring core functionality is implemented in terms of the FModuleLike and FInstanceLike interfaces, which classes and objects implement, respectively.
There are a couple places where some specific logic is added for objects, similar to the specific logic that was already there for instance ops.
Finally, a small change related to paths is needed in LowerClasses. There is some logic there that confirms a hierarchical path's root module is contained within the path's owning module. In the case of deduping hierarchical paths, an extra layer of hierarchy is added to hierpath ops, which breaks this logic. A new condition is added, and if the owning module is anywhere in the …
=> [FIRRTL] Initial support for classes and objects in Dedup.

lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp, test/Dialect/FIRRTL/check-comb-cycles.mlir
Casts should be cast like, but foriegn ops are ignored.  Combinatorial cycles are only defined for FIRRTL.
A refinement of https://github.com/llvm/circt/commit/176926b814eee0665ebb952046d0710f79b67669 which doesn't break the semantics of cast.
=> [FIRRTL]  CheckCombCycles ignores foriegn ops.

lib/Dialect/FIRRTL/Export/FIREmitter.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir
This adds support to parse and emit layer-associated probes to bring CIRCT more into compliance with the FIRRTL spec around probes.
This is currently stacked on #6551.
=> [FIRRTL] Add parser/emitter support for layer-associated probes

include/circt/Dialect/HW/HWInstanceImplementation.h, include/circt/Dialect/HW/HWOpInterfaces.td, include/circt/Dialect/SystemC/SystemCStructure.td, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/HW/HWInstanceImplementation.cpp, lib/Dialect/SystemC/SystemCOps.cpp, lib/LogicalEquivalence/LogicExporter.cpp, lib/Target/DebugInfo/EmitHGLDD.cpp
Since it is only used in ExportVerilog, there is no need to expose it to all dialects.
=> [HW] Remove the cache-based lookup method from HWInstanceLike

lib/Dialect/FIRRTL/Import/FIRParserAsserts.cpp, test/Dialect/FIRRTL/parse-basic.fir
Prefer intrinsic over verbatim verilog.
=> [FIRRTL] Use isX intrinsic for trueOrIsX verif statements.

include/circt/Dialect/HW/HWOpInterfaces.td, include/circt/Dialect/HW/HWStructure.td, lib/Dialect/ESI/AppID.cpp, lib/Dialect/HW/HWReductions.cpp, lib/Dialect/OM/Transforms/FreezePaths.cpp
This PR removes the assumption that instance-like ops have a single reference target in order for https://github.com/llvm/circt/pull/6624 to also make instance choices instance-like ops.
Some shortcuts are taken, instances where passes do not trivially support multiple targets are stubbed out to be implemented later, once the choice op is actually materialized and present in the pipeline.
=> [HW] Make HWInstanceLike agnostic of the number of targets

include/circt/Dialect/ESI/ESIChannels.td, include/circt/Dialect/ESI/ESIManifest.td, include/circt/Dialect/ESI/ESIOps.h, include/circt/Dialect/ESI/ESIServices.td, integration_test/Bindings/Python/dialects/esi.py, integration_test/Dialect/ESI/cosim/loopback.mlir, integration_test/Dialect/ESI/runtime/loopback.mlir, lib/Bindings/Python/dialects/esi.py, lib/Dialect/ESI/ESIOps.cpp, lib/Dialect/ESI/ESIServices.cpp, lib/Dialect/ESI/ESIStdServices.cpp, lib/Dialect/ESI/Passes/ESIBuildManifest.cpp, lib/Dialect/ESI/runtime/cpp/include/esi/Ports.h, lib/Dialect/ESI/runtime/cpp/include/esi/Services.h, lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Trace.cpp, lib/Dialect/Handshake/Transforms/LowerExtmemToHW.cpp, test/Dialect/ESI/appid_hier.mlir, test/Dialect/ESI/errors.mlir, test/Dialect/ESI/manifest.mlir, test/Dialect/ESI/services.mlir, test/Dialect/Handshake/lower-extmem-esi.mlir
Having a direction on the service ports which just reversed the bundle directions was far too complicated. Standardize on the service always packing the bundle and sending it to the client. Standardizing that way has the additional benefit that this was already the canonical form which all the service generators saw. Remove all to_client verbiage from the IR.
=> [ESI] Simplify services by standardizing on `to_client` ports

frontends/PyCDE/integration_test/esi_ram.py, frontends/PyCDE/integration_test/esi_test.py, frontends/PyCDE/src/esi.py, frontends/PyCDE/src/signals.py, frontends/PyCDE/src/types.py, frontends/PyCDE/test/test_esi.py, frontends/PyCDE/test/test_esi_servicegens.py
Turns out the default style PyCDE selected was the non-canonical one -- to_server -- instead of to_client.
=> [PyCDE] Adapt to new to_client style services

CMakeLists.txt
=> CMake: Fetch slang via git to workaround version check bug.

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Dialect/FIRRTL/errors.mlir
Miscellaneous fixes to get layer-associated probes working.
This primarily makes it so that you can use a probe in a layerblock to define something outside it.  Checks are added along the lines of what is suggested in https://github.com/llvm/circt/pull/6551#issuecomment-1881401430 to do verification of layers. There are only two types of checks that are needed to verify symbols:
1. Module ports are verified that any layer-associated probe points at a defined layer.
2. Ref Cast ops are verified that they cast to a legal destination.
3. Wires are verified that they cast to a defined layer.
There are a lot of other checks that could be added, but are unnecessary. E.g., refsend and refsub don't need to be checked because the only way to get a probe referring to an undefined destination is …
=> [FIRRTL] Prerequisites for Layer-Associated Probes

include/circt/Conversion/ExportVerilog.h, include/circt/Conversion/Passes.td, include/circt/Dialect/HW/HWStructure.td, include/circt/Dialect/HW/HWVisitors.h, include/circt/Dialect/SV/SVPasses.h, integration_test/EmitVerilog/instance-choice.mlir, integration_test/lit.cfg.py, integration_test/lit.site.cfg.py.in, lib/Conversion/ExportVerilog/CMakeLists.txt, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/ExportVerilog/ExportVerilogInternals.h, lib/Conversion/ExportVerilog/HWLowerInstanceChoices.cpp, lib/Conversion/ExportVerilog/PrepareForEmission.cpp, lib/LogicalEquivalence/LogicExporter.cpp, test/Conversion/ExportVerilog/hw-lower-instance-choices.mlir, test/Conversion/ExportVerilog/instance-choice.mlir, tools/firtool/firtool.cpp
This PR sketches the lowering of instance choices to SystemVerilog, emitting the placeholder macros and producing the output for the default branches.
The emission of the alternatives will be done in a follow-up PR. 
An integration test is also built out to verify the correctness of the behaviour of the ops and to verify the correctness of the file list and macro definition groups involved.
SV code is emitted directly instead of building IR for it at the moment as regular instance operations cannot use a symbolic (macro) reference to name the target module.
Upon further thought, the details of the lowerings will not be included in the FIRRTL ABI: the ABI will pin down the ordering in which files emitted by the compiler will be consumed, however their contents which implement instance …
=> [HW] Lower hw.instance_choice to SV

lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/layers.mlir
When checking the ops under a layerblock:
- When checking if an operand refers to a value defined outside the layerblock, we need to check if the layerblock is an ancestor of the value's definition, not the more strict "direct parent of definition" check. This check better handles blocks (such as when ops) nested under a layerblock.
- When checking if an operand is valid, we shouldn't early-return, which would disables all remaining verification for the child op.
- Explicitly allow ref.define op to define destinations outside the layerblock op. It is the only connect-like op that is allowed to do so.
- Use WalkResult::interrupt() to signal failure.
=> Fix some issues in the LayerBlockOp verifier

lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/layers-errors.mlir, test/Dialect/FIRRTL/layers.mlir
This PR updates the logic which checks for layer compatibility when casting, resolving, or defining refs.
We consider the layers which must be enabled for the hardware object to exist. This is the set of layers which are either enabled by the parent module, or required by any parent layerblocks. We call these the ambient layers of a definition. 
For example:
```firrtl
module Foo enablelayer A:
layerblock B:
layerblock C:
wire w : UInt<1>
```
At the definition site of `w`, the ambient layers are  `A`, `B`, and `B.C`. We also call these the required layers of `w`, because `w` will not exist unless all these layers are enabled.
Probe wires, or wires containing probes, have not only ambient layer requirements, but also explicit layer requirements, which are written in the wire's type.
For …
=> [FIRRTL] Use set-based logic to test for layer compatibility

lib/Dialect/FIRRTL/FIRRTLIntrinsics.cpp
Conversions weren't actually counted, fix.
=> [FIRRTL] Intrinsics: Fix mistakenly preserved analyses.

include/circt/Dialect/OM/OMOpInterfaces.td, include/circt/Dialect/OM/OMOps.td, lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, lib/Dialect/OM/Evaluator/Evaluator.cpp, lib/Dialect/OM/OMOps.cpp
Since 5fb4cf5fd3a3dcaa05b43e340120ce9c3a75f597, ClassLikes are not SymbolTables, due to the usual reasons that led to us inventing InnerSymbolTables. However, that change left the Symbol trait on ClassFieldLikes, which is not legal. We need to fix this, and stop using Symbols in illegal locations.
This change removes the Symbol trait, and includes some minor juggling so the current implementation can continue working with minimal changes.
This renames the attribute name from sym_name to name and adds an interface method to ClassFieldLike called getNameAttr. Together, these changes align the accessor for this field to match the previous getNameAttr accessor on Symbols.
This also updates a couple call sites that directly called getSymNameAttr to use getNameAttr like the other call sites. …
=> [OM] Remove Symbol trait from ClassFieldLikes.

include/circt/Dialect/Calyx/CalyxControl.td
During the Calyx control lowering, in an intermediate state, we have fsm.machine ops embedded within the calyx.control op. fsm.machine defines a Symbol, so this is illegal unless calyx.control is a SymbolTable.
We consistently hit issues when we try to nest SymbolTables, but I don't think those will actually bite us in the Calyx lowering pipeline. Since no one is actively maintaining this, I'm proposing to add SymbolTable to ControlOp until we have a reason to change this, so the IR is legal during the Calyx lowering.
Fixes https://github.com/llvm/circt/issues/6667.
=> [Calyx] Make ControlOp a SymbolTable.

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, lib/Dialect/FIRRTL/FIRRTLInstanceImplementation.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp, lib/Dialect/FIRRTL/Transforms/LowerSignatures.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, lib/Dialect/FIRRTL/Transforms/SpecializeOption.cpp, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/layers-errors.mlir, test/Dialect/FIRRTL/parse-basic.fir
The enabled layers of a module act as requirements on the instance op--the module may only be instantiated where the enabled layer set is in the ambient layer set.
This PR adds verification for this rule.
Changes:
- Start tracking the required layers on instance ops.
- Verify the ambient layers of instance ops.
- Verify that the layers attribute on instance ops agrees with the referenced module.
- Update places where we create instance ops to pass the layers.
=> Track instance layers

.github/workflows/uploadReleaseArtifacts.yml
shared build seems to require a specific version of glibc and causes a build failure of downstream tools. This PR adds `-static` tarball to the artifact.
Tested here: https://github.com/llvm/circt/actions/runs/7357240622
=> [CI] Add statically linked CIRCT full build to ReleaseArtifact CI

docs/Dialects/FIRRTL/FIRRTLIntrinsics.md, lib/Dialect/FIRRTL/Transforms/LowerIntrinsics.cpp, test/Dialect/FIRRTL/lower-intrinsics.mlir, test/firtool/chisel_assert.fir
Provide intrinsics to capture what today is encoded via printf + when/stop/verif-op pattern matching and XML + JSON parameters.
Compared to assert/assume/cover FIRRTL (textual/in-the-spec) ops, these allow specifying labels that are more than identifiers and have optional compilation guards.
These map to current FIRRTL ops directly, including the various special behaviors that means in practice today (as encoded in LowerToHW):
* Assert implies companion assume emission.  Hence `chisel_assert_assume`.
* If the guard `USE_UNR_ONLY_CONSTRAINTS` is present, this companion assume is different, see: https://github.com/llvm/circt/pull/5561 .
There is no "assert" because `firrtl.assert` "concurrent" (SVA) forms always "imply" a "companion assume" and presently there is no FIRRTL dialect encoding …
=> [FIRRTL] chisel_{assert_assume,assume,cover,ifelsefatal} intrinsics.

include/circt/Conversion/ImportVerilog.h, lib/Conversion/ImportVerilog/ImportVerilog.cpp, test/circt-verilog/include/other.sv, test/circt-verilog/preprocess-errors.sv, test/circt-verilog/preprocess.sv, tools/circt-verilog/circt-verilog.cpp
Add the `ImportVerilogOptions` struct to capture various options that can be passed to the Slang Verilog frontend. This covers things like include search directories, macro definitions, top modules, time scales, and other settings commonly found in Verilog tools. The struct is inspired by `slang::driver::Driver::Options`, but we intentionally create our own struct such that no Slang headers leak through into CIRCT space.
Add corresponding command line options to `circt-verilog`, and use them to populate an `ImportVerilogOptions` struct that can be passed to `ImportVerilog`.
Add `importVerilog` and `preprocessVerilog` functions to `ImportVerilog` and add corresponding options to `circt-verilog` that call the respective import function. This commit only implements preprocessing.
This commit …
=> [ImportVerilog] Add import options and Verilog preprocessing

include/circt/Dialect/FIRRTL/FIRRTLStatements.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/layers-errors.mlir, test/Dialect/FIRRTL/layers.mlir
Allow propassign ops to appear under layerblocks, but explicitly do not allow properties to be captured under, or escape out of, a layerblock.
=> Allow propassign under layerblocks

include/circt/Dialect/Seq/SeqOps.td, lib/Dialect/Seq/SeqOps.cpp
These are used in contexts that are not SymbolTables, so these cannot be Symbols. It appears that nothing actually needs the Symbol functionality, and all we need here is the string name. This removes the Symbol trait and renames the attribute to just name.
If anything needs to reference HLMemOps symbolically, these can become InnerSymbols, but again, I didn't see anything about that in the codebase.
Fixes https://github.com/llvm/circt/issues/6661.
=> [Seq] Remove Symbol trait from HLMemOp.

lib/Dialect/FIRRTL/Transforms/InferResets.cpp, test/Dialect/FIRRTL/infer-resets-errors.mlir
The FullAsynchronousResetAnnotation is used to mark an asynchronous signal in a module to be used as the reset for all registers that do not already have an async reset in this module and below in the hierarchy. There was no error checking that this annotation was attached to an asynchronous reset typed signal, and the pass would accidentally try to wire whatever signal was annotated.  In some cases, this could lead to a connecting the signal to an async typed port, which would become a type checking error in the verifier. This changes InferResets to verify that the FART annotated signal is in fact asynchronous.
Fixes https://github.com/llvm/circt/issues/6635
=> [FIRRTL] InferResets: verify that FART annotation is on async resets

frontends/PyCDE/src/fsm.py, include/circt/Dialect/FSM/FSMOps.td, lib/Dialect/FSM/FSMOps.cpp
These are used in contexts that are not SymbolTables, so these cannot be Symbols. It appears that nothing actually needs the Symbol functionality, and all we need here is the string name. This removes the Symbol trait and renames the attribute to just `name`.
=> [FSM] Remove Symbol trait from InstanceOp and HWInstanceOp.

test/Conversion/ExportVerilog/sv-dialect.mlir, test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Companion.fir, test/Dialect/FIRRTL/SFCTests/directories.fir, test/Dialect/FIRRTL/canonicalization.mlir, test/Dialect/FIRRTL/lower-open-aggs.mlir, test/Dialect/FIRRTL/lower-signatures.mlir, test/Dialect/FIRRTL/lowerXMR.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/remove-unused-ports.mlir, test/Dialect/HW/flatten-io.mlir, test/Dialect/LLHD/IR/entity.mlir, test/Dialect/LTL/canonicalization.mlir, test/Dialect/Seq/clock-type.mlir, test/firtool/firtool.mlir
Mostly just fix the typos and lowerXMR, lower-open-aggs.mlir, and sv-dialect.mlir needed the check line tweaked to pass.
Found via the (TIL) LLVM utility `llvm/utils/filecheck_lint/filecheck_lint.py`.
Hopefully coming to a CI near you soon :wink: .
=> Tree-wide test fixes for FileCheck directive typos

include/circt/Dialect/FIRRTL/FIRRTLIntrinsics.h, lib/Dialect/FIRRTL/FIRRTLIntrinsics.cpp, lib/Dialect/FIRRTL/Transforms/LowerIntrinsics.cpp, test/Dialect/FIRRTL/lower-intrinsics-errors.mlir, test/Dialect/FIRRTL/lower-intrinsics.mlir
Accept `EICG_wrapper` extmodules without `test_en` port in `LowerIntrinsics`, and simply leave the `test_en` unconnected in that case. Also reject `EICG_wrapper` modules and instances if they have annotations attached, as we currently have no mechanism to carry them over onto the intrinsic. (Only if `--fixup-eicg-wrapper` is passed to firtool.)
=> [LowerIntrinsics] Accept EICG_wrapper without test_en, reject annos

include/circt/Firtool/Firtool.h, lib/Firtool/Firtool.cpp
A hidden command-line argument is added to re-enable the pass on possible backports or during the next release.
=> [WireDFT] Disable the pass by default

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Conversion/FIRRTLToHW/zero-width.mlir
Fix an error if a 0-bit was shifted right by any amount and this made it all the way to LowerToHW (and wasn't canonicalized away earlier).  FIRRTL semantics interpret this case as a 1-bit zero.  Insert the 1-bit zero if we ever see this.
Fixes #6652.
=> [LowerToHW] Fix shr(0-bit, n) lowering

lib/Conversion/ImportVerilog/ImportVerilog.cpp, test/circt-verilog/preprocess-multiple-files.sv
Make `ImportVerilog` honor the `singleUnit` option by either adding all source files to a single preprocessor (single unit), or creating a fresh preprocessor for every single file (multiple units).
Fixes #6680.
=> [ImportVerilog] Fix single unit preprocessor option

integration_test/lit.cfg.py, integration_test/lit.site.cfg.py.in
Not used yet, but make this available for future use.
=> Make circt-verilog available to integration tests.

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes.mlir
The previous logic would create classes for any FIRRTL modules that had property ports. However, if some intermediate modules had property ports, but their parents did not, we would not convert their parents, which would break pass invariants and lead to failed assertions.
This adds logic to also convert any FIRRTL modules that instantiate FIRRTL modules that will be converted. This upholds the pass invariants, and makes it robust in case property ports are used in part of the hierarchy but not exported from the top-level module of the circuit.
=> [LowerClasses] Lower classes that instantiate properties.

include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td, lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, test/Dialect/FIRRTL/lower-layers.mlir, test/firtool/lower-layers.fir, test/firtool/lower-layers2.fir
Start supporting layer-associated probes in the `LowerLayers` pass.
This is stacked on prerequisite work.
This currently uses a non-standard FIRRTL ABI for layer-colored probe emission. It uses "groups_" as a prefix. We'll circle back and clean this up along with other emission that is incorrect for FIRRTL 4.0.0 in later work.
=> [FIRRTL] Add layer-associated Probes to LowerLayers pass

lib/Conversion/ExportVerilog/PrepareForEmission.cpp, test/Conversion/ExportVerilog/prepare-for-emission.mlir
When I tried lowering the output of test example in #6649 to SV it crashed in PrepareForEmission. The issue can be reduced to:
```
%false = hw.constant false
%0 = comb.or %false, %1 : i1
%reg = sv.reg init %false : !hw.inout<i1>
%1 = sv.read_inout %reg : !hw.inout<i1>
```
The presence of an initial value prevents the register and `ReadInOutOp` from being moved to the top of the module. The pass then attempts to create a temporary wire to remove the backedge on `%1`. This fails because the value is already an InOut type.
This PR changes `isMovableDeclaration` to allow operations to be lifted if all their operands are constant expressions, which in most cases should avoid the backedge for the `ReadInOutOp`. While this may technically break dominance, it should not cause a problem during …
=> [ExportVerilog] Fix crash on `sv.reg` with initial value

include/circt/Dialect/HW/HWStructure.td, integration_test/EmitVerilog/instance-choice.mlir, lib/Dialect/HW/HWOps.cpp, test/Conversion/ExportVerilog/hw-lower-instance-choices.mlir, test/Conversion/ExportVerilog/instance-choice.mlir, test/Dialect/HW/errors.mlir, test/Dialect/HW/round-trip.mlir, test/Dialect/HW/verify-irn.mlir
Also renamed `targetNames` to `caseNames` to better match the FIRRTL-level terminology
=> [HW] Encode the option group name in instance choice ops

include/circt/Dialect/HW/HWStructure.td, include/circt/Dialect/HW/ModuleImplementation.h, lib/Bindings/Python/dialects/hw.py, lib/Dialect/HW/HWOps.cpp, lib/Dialect/HW/ModuleImplementation.cpp, lib/Dialect/HW/Transforms/FlattenIO.cpp, lib/Transforms/StripDebugInfoWithPred.cpp
On modules we keep an array attribute `port_locs` for port location information.  On regular HWModules specifically, which have a body block, we copy the input port location to the entry block arguments, for error messages and such. This is violating the "single source of truth" principle for input port location info, so we added a verifier that ensured the block argument locations were always kept in sync with the port location attributes. This lead to another problem: if you print our IR in the generalized format and try to read it back in, by default with `-mlir-print-debug-info` printing turned off, it will end up throwing away the location on the blocks. When the IR is read back in, the block arguments will have new location information corresponding to the intermediate file, while …
=> [HW] HWModule: store input port locations only on block args

lib/Dialect/FIRRTL/Import/FIRParser.cpp
These currently default to calling emitError(), which uses the current token's location. In some cases, the current token may have been consumed by the time we wish to check versions and potentially emit errors. This allows users to supply an SMLoc if necessary, and otherwise defaults to the previous behavior.
None of our current parsing actually consumes a token before checking versions, but I would like to add a version check to an existing parser that will come after it has consumed the token where the error message should point.
=> [FIRRTL] Add parser version APIs that accept an SMLoc, NFC.

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
This is currently always defining the inferReturnTypes method from InferTypeOpInterface on all FIRRTLExprOps in ODS. However, some simpler operations might want implement this method using the SameOperandsAndResultTypes trait, for example.
This factors out that declaration into a TableGen variable that subclasses can override as neeeded. This would be used, for example, in https://github.com/llvm/circt/pull/6691/files.
=> [FIRRTL] Provide a way to override inferReturnTypes in FIRRTLExprOp.

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLOps.h, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/round-trip.mlir
This op adds two FIntegerType operands to produce an FIntegerType result. This defines the usual fold and result type inference hooks required on BinaryPrimOp, but doesn't add any folders yet.
=> [FIRRTL] Add integer addition property op.

include/circt/Dialect/OM/OMOpInterfaces.h, include/circt/Dialect/OM/OMOpInterfaces.td
As we start adding integer binary arithmetic expressions, this will
allow us to abstract over these ops in the evaluator. The interfaces
defines accessors for each operand and the result, which can be
trivially implemented by a shared helper in ODS. The interface also
defines one method to be used in the evaluator, which is to actually
evaluate the integer arithmetic operation. APSInts for each operand
are passed to the interface method, and an APSInt representing the
result or a failure must be returned.
=> [OM] Add OpInterface for IntegerBinaryArithmeticOp.

frontends/PyCDE/src/bsp/cosim.py, frontends/PyCDE/src/common.py, frontends/PyCDE/src/esi.py, frontends/PyCDE/src/fsm.py, frontends/PyCDE/src/module.py, frontends/PyCDE/test/test_instances.py
Specify fget in the port class itself to that users still have access to the port's properties through the class variable instead of replacing the port itself. As a result, we only have to store a list of ports.
=> [PyCDE] Refactor Input/Output ports to extend property

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Import/FIRTokenKinds.def, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir
This adds parser support for IntegerAddOp by defining the primitive expression keyword. This is only supported in FIRRTL version 4.0.0 and up.
=> [FIRRTL] Add integer addition parser support.

lib/Conversion/ImportVerilog/CMakeLists.txt
ImportVerilog.cpp depends on header files which are generated during the build of the `slang_slang` target. Not having this dependeny in CMake [can cause clean builds to fail](https://github.com/llvm/circt/actions/runs/7846969281/job/21414887555):
```
FAILED: lib/Conversion/ImportVerilog/CMakeFiles/obj.CIRCTImportVerilog.dir/ImportVerilog.cpp.o 
/usr/bin/g++ -D_DEBUG -D_GLIBCXX_ASSERTIONS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/__w/circt/circt/llvm/install/include -I/__w/circt/circt/include -I/__w/circt/circt/build/include -I/__w/circt/circt/build/_deps/slang-src/source/../include -I/__w/circt/circt/build/_deps/slang-build/source -I/__w/circt/circt/build/_deps/slang-src/source/../external -I/__w/circt/circt/build/_deps/unordered_dense-src/include …
```
=> [CMake] Make ImportVerilog compile-time depend on slang

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Conversion/FIRRTLToHW/zero-width.mlir, test/Dialect/FIRRTL/canonicalization.mlir, test/Dialect/FIRRTL/infer-widths.mlir, test/Dialect/FIRRTL/parse-basic.fir
Major change in FIRRTL 4.0.0.
Partial revert of https://github.com/llvm/circt/pull/6683 (test is kept).
See the added tests for the new behavior. Basically the width of static right shift (`shr`) for `UInts` now has a minimum width of 0 instead of 1 beginning in FIRRTL 4.0.0. When parsing FIRRTL versions < 4.0.0, the parser will insert a `pad(_, 1)` around any `shr` on a `UInt`. For arguments whose width is greater than the target size of the `pad`, it is a no-op, so this effectively just ensures that any `shr` on a `UInt` gets the old behavior of minimum width == 1.
=> [FIRRTL] Change min width of shr for UInt to 0

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes.mlir
When lowering object instantiations, we need to get the source from a propassign to pass that Value to the newly created OM dialect object op. However, in some cases, like when passing references to objects down the hierarchy, we have already converted the source Value to an OM dialect object op. This means the typed getSrc accessor will fail, as it expects the source Value to be a FIRRTLType.
The IR is in the desired state at this point, so instead we can simply use the untyped getSrcMutable accessor to get the corresponding OpOperand, and get the Value from there. This avoids errors when the pass has knowingly put the IR into a state that won't pass the verifier.
=> [FIRRTL] Use untyped propassign source accessor in LowerClasses.

include/circt/Dialect/OM/OMOps.td, lib/Dialect/OM/OMOps.cpp, test/Dialect/OM/round-trip.mlir
This op adds two OMIntegerType operands to produce an OMIntegerType result. This defines the evaluateIntegerOperation interface method in terms of APSInt +.
=> [OM] Add integer addition op.

lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, test/Dialect/FIRRTL/lower-layers.mlir
Fix a bug in the LowerLayers pass where operations with inner symbols inside layerblocks would not have their HierPathOp users updated when these operations were moved into new modules.  Fix this by recording a mapping of modifications to InnerRefAttrs and then applying these to HierPathOps after all modules are processed.
Fixes #6717.
=> [FIRRTL] Update HierPathOps in LowerLayers

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes.mlir
This is a straightforward 1:1 conversion from FIRRTL IntegerAddOp to OM IntegerAddOp, using the converted operand types from the OpAdaptor.
=> [FIRRTL] Add integer addition conversion to LowerClasses.

include/circt/Dialect/OM/Evaluator/Evaluator.h, lib/Dialect/OM/Evaluator/Evaluator.cpp, unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp
This adds support for the Evaluator to evaluate integer binary arithmetic. This is defined in terms of the IntegerBinaryArithmeticOp interface, so the Evaluator can generically handle all ops that implement this interface in terms of the interface methods.
At a high level, getOrCreateValue will create a partially evaluated value for the result of this op. Once the operands are fully evaluated, they are passed to the evaluateIntegerOperation interface method, and if successful, the result is used for the evaluator value.
Because these are the first kind of operation using AttributeValues that doesn't necessarily make the Attribute immediately available, the AttributeValue has been extended to support construction in a partially evaluated state to be filled in later.
The tests show example …
=> [OM] Support integer binary arithmetic in the Evaluator.

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, test/Dialect/FIRRTL/emit-metadata.mlir
Fixes a crash when compiling a [Chisel read only memory ](https://scastie.scala-lang.org/GRNH6zh0TT6mgIq77mfyLw) with a `LoadMemoryFromFile` annotation using the `--repl-seq-mem` option.
The FMemoryModuleOp's `maskBits` attribute is set to zero in this case. While the result of the division is not used, it can still cause a trap.
=> [FIRRTL] Prevent divison by zero in CreateSiFiveMetadata

include/circt/Conversion/ImportVerilog.h, include/circt/InitAllTranslations.h, lib/Conversion/ImportVerilog/ImportVerilog.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/errors.sv
Add an `--import-verilog` translation target for `circt-translate`. This facilitates writing single-file test cases that don't require configuration of the Slang language frontend.
Actually run the Slang elaboration and compilation from within `ImportContext::importVerilog`. This will essentially do the full frontend work to ingest Verilog, but the part that translates from the Slang AST to CIRCT IR ops is still left to be filled in. The import will always produce an empty MLIR module for now. However, reporting of syntax or other errors on the Verilog side is already covered and can be tested for.
=> [ImportVerilog] Add translation, run Slang compilation

lib/Dialect/FIRRTL/FIRRTLUtils.cpp, test/Dialect/FIRRTL/inject-dut-hierarchy.mlir
We have a centralized emitConnect helper that knows how to create the right kind of connections for various special, non-base types, like RefType and AnalogType. This adds another special case for PropertyType, which emits a PropAssignOp.
This is used in various places, but the pass where I noticed this was missing is InjectDUTHierarchy, so I've added a test there similar to the test for RefType.
=> [FIRRTL] Support PropertyType in emitConnect.

include/circt/Dialect/Sim/SimOps.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Conversion/SimToSV/CMakeLists.txt, lib/Conversion/SimToSV/SimToSV.cpp, lib/Dialect/Sim/CMakeLists.txt, lib/Firtool/Firtool.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Conversion/SimToSV/stop.mlir, test/Dialect/Sim/round-trip.mlir, test/firtool/stop.fir
This PR introduces wrapper operations to act as intermediaries in the lowering of FIRRTL to SV. The `sim.finish` and the `sim.fatal` ops capture the clocks and conditions, lowering to an always block and an if statement gated behind the `SYNTHESIS` flag. The `STOP_COND_` condition, which is tied to the FIRRTL ABI, is resolved in `LowerToHW`.
This change is beneficial for Arc and an internal SiFive tool by providing an trivially analyzable representation for stop conditions.
=> [Sim] Introduce wrappers on top of `sv.finish`/`sv.fatal`

include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/PassDetails.h, test/Dialect/FIRRTL/blackbox-reader.mlir
This PR ports over the black box reader to use the emit dialect for representing & outputting files.
=> [Emit] Emit black boxes through `emit` ops

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/CMakeLists.txt, lib/Conversion/ImportVerilog/ImportVerilog.cpp, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, lib/Conversion/ImportVerilog/Structure.cpp, lib/Dialect/Moore/MooreOps.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/errors.sv, test/Dialect/Moore/basic.mlir, test/Dialect/Moore/errors.mlir
Extend the `ImportVerilog` conversion to support empty SystemVerilog module definitions and instances of such modules.
To do this, add a `ImportVerilogInternals.h` header that defines a `Context` helper struct to aid in the conversion. Similar to other parsers and translations, the context has a builder, tracks operations, and offers entry points to convert different nodes of the Slang AST, and handles diagnostics and location conversion.
An annoying quirk of Slang is the fact that the top-level declarations in an SV file are reordered and rearranged. All instantiable nodes, such as modules, programs, or interfaces, are moved into a separate list of top-level instances which is unordered. To allow for better testing with FileCheck and to produce more predictable output, the helper …
=> [ImportVerilog] Convert empty modules and instances

lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, test/Dialect/FIRRTL/lower-layers.mlir, test/firtool/layers.fir, test/firtool/lower-layers.fir, test/firtool/lower-layers2.fir
- Layer module name: move into helper.
- Layer instance name:
- don't put the parent module name in the instance name,
- lowercase each part of the instance name, not just the first word.
- Layer file name: move into helper.
- Captured port names: don't prefix the port name with an underscore.
=> [FIRRTL][LowerLayers] Clean up names of artifacts generated by layers

include/circt/Dialect/Ibis/IbisInterfaces.td, include/circt/Dialect/Ibis/IbisOps.h, include/circt/Dialect/Ibis/IbisOps.td, lib/Dialect/Ibis/IbisOps.cpp, lib/Dialect/Ibis/Transforms/IbisCleanSelfdrivers.cpp, lib/Dialect/Ibis/Transforms/IbisContainerize.cpp, lib/Dialect/Ibis/Transforms/IbisContainersToHW.cpp, lib/Dialect/Ibis/Transforms/IbisMethodsToContainers.cpp, test/Dialect/Ibis/Transforms/clean_selfdrivers.mlir, test/Dialect/Ibis/Transforms/containerize.mlir, test/Dialect/Ibis/Transforms/containers_to_hw.mlir, test/Dialect/Ibis/Transforms/methods_to_containers.mlir, test/Dialect/Ibis/Transforms/path_end_to_end.mlir, test/Dialect/Ibis/Transforms/portref_lowering.mlir, test/Dialect/Ibis/Transforms/scoperef_tunneling.mlir, test/Dialect/Ibis/Transforms/tunneling_errors.mlir, test/Dialect/Ibis/canonicalization.mlir, test/Dialect/Ibis/errors.mlir, test/Dialect/Ibis/round-trip.mlir
In order to not abuse symbol tables, create an OuterContainerOp for top-level containers, and InnerContainerOp for nested containers. The former has a symbol and is an InnerSymbolTable. The latter has an InnerSymbol.
Fixes #6658.
=> [Ibis] Split ContainerOp in two

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir, test/firtool/chisel_assert.fir, test/firtool/instchoice.fir, test/firtool/layers.fir, test/firtool/lower-layers2.fir
The "public" nature of the main module is not optional, require it to be explicitly specified.
cc https://github.com/chipsalliance/firrtl-spec/pull/185 .
=> [FIRRTL][FIRParser] Enforce 4.0.0 main module must be public.

include/circt/Dialect/FIRRTL/Passes.td, include/circt/Dialect/SV/SVPasses.td, lib/Dialect/FIRRTL/Transforms/AddSeqMemPorts.cpp, lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp, lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp, lib/Dialect/FIRRTL/Transforms/ResolveTraces.cpp, lib/Dialect/SV/Transforms/CMakeLists.txt, lib/Dialect/SV/Transforms/HWExportModuleHierarchy.cpp, lib/Dialect/SV/Transforms/PassDetail.h, test/Dialect/FIRRTL/add-seqmem-ports.mlir, test/Dialect/FIRRTL/emit-metadata.mlir, test/Dialect/FIRRTL/emit-omir.mlir, test/Dialect/FIRRTL/lowerXMR.mlir, test/Dialect/FIRRTL/resolve-traces.mlir
Port over FIRRTL passes to emit metadata using `emit::FileOp`.
This PR re-uses the `sv::Verbatim` to format in the presence of SV symbols.
=> [Emit] Use FileOp to emit metadata

lib/Target/DebugInfo/EmitHGLDD.cpp, test/Target/DebugInfo/emit-hgldd.mlir
The `EmitHGLDD` translation currently emits instance output ports as XMR `<instName>.<portName>`. This is not valid HGLDD. Remove this special handling of instances. Instead if a value cannot be emitted as HGLDD, try to follow the value's use as input to a wire or assignment and use the destination name instead.
Also fix an issue where ops with a single result and `hw.verilogName` attribute would be emitted as signal references with that Verilog name. This code path would trigger for instances with a single output port, causing the instance name to be used for the signal reference. Limit that code path to only trigger on Comb dialect ops.
Fixes #6735.
=> [HGLDD] Fix instance output port emission

lib/Target/DebugInfo/EmitHGLDD.cpp, test/Target/DebugInfo/emit-hgldd.mlir
Ensure the object and variable names emitted by the `EmitHGLDD` translation are unique and don't collide with any known Verilog keywords.
Refactor the emission code by pulling most of the shared emission state into a `GlobalState` struct that is created by the `Emitter` and is shared by each `FileEmitter`.
Move the `objectNamespace` that is used to uniquify object names into the new global emitter state, and use `sv::legalizeName` to uniquify module names instead of `Namespace`. This avoids keyword collisions. Also add a per-module `moduleNamespace` that is prepopulated with the global `objectNamespace`, and use it to uniquify variable and instance names.
Fixes #6749.
=> [HGLDD] Uniquify object names during emission

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/CMakeLists.txt, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, lib/Conversion/ImportVerilog/Structure.cpp, lib/Conversion/ImportVerilog/Types.cpp, lib/Dialect/Moore/CMakeLists.txt, lib/Dialect/Moore/MooreOps.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/errors.sv, test/Conversion/ImportVerilog/types-errors.sv, test/Conversion/ImportVerilog/types.sv, test/Dialect/Moore/basic.mlir
Implement the conversion from SystemVerilog types in Slang's AST to the corresponding MLIR types in the Moore dialect. To facilitate testing, add a basic `moore.variable` op and convert module-level variable declarations to this new op. This requires converting the variable's type. We may choose to have variables return a special lvalue or pointer wrapper type in the future once such a need arises to clearly demarcate variable reading and assignment.
Since we don't support expressions yet, variables with an initializer expression cause an error for the time being.
=> [ImportVerilog] Add type conversion and basic variables

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp, lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/grand-central-errors.mlir, test/Dialect/FIRRTL/lower-layers-errors.mlir, test/Dialect/FIRRTL/lower-layers.mlir, test/firtool/lower-layers-directories.fir
Change the LowerLayers pass to put generated modules inside the testbench directory if one is specified and a DUT is present.  This is a stopgap measure that keeps layers aligned with existing CIRCT compilation of FIRRTL.  This is intended to be replaced with a better FIRRTL ABI based on filelists in the future.
This is currently missing handling of instances instantiated by the layer. Those need to also get moved to the testbench area. I'll mark this non-draft once it's fully working.
=> [FIRRTL] Put layer collateral in testbench dir

include/circt/Dialect/Emit/CMakeLists.txt, include/circt/Dialect/Emit/EmitOpInterfaces.h, include/circt/Dialect/Emit/EmitOpInterfaces.td, include/circt/Dialect/Emit/EmitOps.td, include/circt/Dialect/HW/HWOps.h, include/circt/Dialect/HW/HWStructure.td, include/circt/Dialect/Seq/SeqPasses.td, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/Emit/CMakeLists.txt, lib/Dialect/Emit/EmitOpInterfaces.cpp, lib/Dialect/Emit/EmitOps.cpp, lib/Dialect/Seq/Transforms/CMakeLists.txt, lib/Dialect/Seq/Transforms/HWMemSimImpl.cpp, test/Conversion/ExportVerilog/emit.mlir
This PR introduces a minimal implementation of file-to-operation references. Presently, only modules can be referenced and each module can be referenced by a single file once. As an example, the `HWMemSimImpl` pass is ported over.
Subsequent PRs will rely on this mechanism to phase out the `output_file` attribute.
=> [Emit] Introduce `emit.ref` to pull ops into file bodies

lib/Dialect/Calyx/Export/CalyxEmitter.cpp, test/Dialect/Calyx/emit-seq-memory.mlir, test/Dialect/Calyx/emit.mlir
Updates memory import locations to be correct for the current calyx native compiler `main`.
=> [Calyx] Fix memory import locations

include/circt/Dialect/Arc/ArcOps.td, include/circt/Dialect/Arc/ArcTypes.h, include/circt/Dialect/Arc/ArcTypes.td, lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp, lib/Dialect/Arc/ArcOps.cpp, lib/Dialect/Arc/Transforms/LowerState.cpp, test/Dialect/Arc/Export/info-gathering-errors.mlir, test/Dialect/Arc/Export/serialize-state-info.mlir, test/Dialect/Arc/allocate-state.mlir, test/Dialect/Arc/basic-errors.mlir, test/Dialect/Arc/basic.mlir, test/Dialect/Arc/canonicalizers.mlir, test/Dialect/Arc/group-resets-and-enables.mlir, test/Dialect/Arc/legalize-state-update-error.mlir, test/Dialect/Arc/legalize-state-update.mlir, test/Dialect/Arc/lower-clocks-to-funcs-errors.mlir, test/Dialect/Arc/lower-clocks-to-funcs.mlir, test/Dialect/Arc/lower-sim-err.mlir, test/Dialect/Arc/lower-sim.mlir, test/Dialect/Arc/lower-state.mlir, test/Dialect/Arc/sim-errors.mlir, test/arcilator/arcilator.mlir
This introduces a couple new operations to drive simulation from within an MLIR program, next to the models themselves. This can be lowered by Arcilator to create LLVM functions that run the simulation. `arc.sim.emit` can be used to print values during the simulation. The semantics of this operation are to send a value to the simulation driver, but for now in practice this amounts to being lowered into a libc print to stdout.
=> [arcilator] Introduce simulation orchestration subdialect

lib/Dialect/FIRRTL/Import/FIRParser.cpp
We already store a mapping from class name to ClassOp when we parse the ClassOp signatures, in case the class name is referenced in any ClassOp port types. This re-uses the same data structure when parsing an ObjectOp to a) ensure the class exists, and b) construct the ObjectOp using the ClassOp.
The previous implementation would look up the ClassOp symbol in the circuit, but this would simply scan the circuit body again and again. This change makes a significant difference for performance, on the order of 90% overall parsing time reduction for large designs with many objects.
=> [FIRRTL] Use the class map in ObjectOp parser.

include/circt-c/Dialect/Emit.h, integration_test/Bindings/Python/dialects/emit.py, lib/Bindings/Python/CIRCTModule.cpp, lib/Bindings/Python/CMakeLists.txt, lib/Bindings/Python/dialects/EmitOps.td, lib/Bindings/Python/dialects/emit.py, lib/CAPI/Dialect/CMakeLists.txt, lib/CAPI/Dialect/Emit.cpp
Add the emit dialect to the C-API and to Python.  This is both missing and is necessary for downstream Python tooling to not break.
=> [capi][python] Add Emit Dialect

include/circt/Dialect/SV/SVAttributes.td, include/circt/Dialect/SV/SVStatements.td, lib/Dialect/SV/SVOps.cpp, test/Conversion/ExportVerilog/decl-align.mlir, test/Conversion/ExportVerilog/disallow-local-vars.mlir, test/Conversion/ExportVerilog/emit.mlir, test/Conversion/ExportVerilog/hw-lower-instance-choices.mlir, test/Conversion/ExportVerilog/max-terms.mlir, test/Conversion/ExportVerilog/name-legalize.mlir, test/Conversion/ExportVerilog/pretty.mlir, test/Conversion/ExportVerilog/sv-dialect.mlir, test/Conversion/ExportVerilog/verilog-basic.mlir, test/Conversion/FIRRTLToHW/emit-chisel-asserts-as-sva.mlir, test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Conversion/SimToSV/plusargs.mlir, test/Conversion/SimToSV/stop.mlir, test/Dialect/Arc/inline-modules.mlir, test/Dialect/Arc/strip-sv.mlir, test/Dialect/SV/basic.mlir, test/Dialect/SV/canonicalization.mlir, test/Dialect/SV/errors.mlir, test/Dialect/SV/hw-cleanup.mlir, test/Dialect/SV/hw-extract-test-code.mlir, test/Dialect/SV/prettify-verilog.mlir, test/Dialect/Seq/firreg.mlir, test/Dialect/Seq/hw-memsim.mlir, test/firtool/plusargs.fir, test/firtool/split-verilog.mlir, test/firtool/stop.fir
Macro identifiers now use a proper symbol to handle references. The verifiers are not yet enabled as more intrusive pipeline changes are required, to be done in follow-ups.
=> [SV] Use a symbol in macro identifiers

lib/Dialect/FIRRTL/Transforms/Dedup.cpp, test/firtool/classes-dedupe.fir
In https://github.com/llvm/circt/pull/6582, initial support for classes and objects was added in Dedup. However, since classes and objects are new constructs, not every possibility was handled in the initial implementation.
This specifically handles the case where references to objects are passed through class ports, and the class type of such objects has changed because their classes deduped.
In the final fixup pass through the instance graph, if we find a class, we check if it has any reference ports that need to be updated, and if so update them. When this happens, we also update an objects of the class to reflect the newly updated class type.
Fixes https://github.com/llvm/circt/issues/6603.
=> [FIRRTL] Handle reference ports when Classes dedup.

include/circt-c/Dialect/OM.h, integration_test/Bindings/Python/dialects/om.py, lib/Bindings/Python/OMModule.cpp, lib/CAPI/Dialect/OM.cpp
In some OM dialect constructs, it is possible to receive EvaluatorValue::Reference values. In the Python bindings, where we are converting an EvaluatorValue to a Python value, we need to dereference the Reference, to get at the underlying EvaluatorValue that was set during evaluation.
This adds the necessary C APIs, and updates the Python bindings to use them. If we encounter a Reference, we dereference it and recursively call the converter function.
A Python test was added using an example IR from the Evaluator unit tests, which delays evaluation and introduces references.
=> [OM] Add C API and Python bindings for EvaluatorValue::Reference.

lib/Firtool/Firtool.cpp
This moves LowerIntrinsic to preprocess transforms.
=> [FIRTOOL] Move LowerIntrinsic to preprocess

lib/Dialect/Arc/Transforms/CMakeLists.txt, lib/Dialect/Arc/Transforms/StripSV.cpp, tools/arcilator/CMakeLists.txt, tools/arcilator/arcilator.cpp
This PR enables the arcilator tool to run on IR containing Emit dialect nodes. However, they are simply discarded. It is mainly intended to allow lowering of designs containing blackboxed stubs, notably the plusargreader in rocket-chip. Obviously, this is just a stopgap solution until we can feed them to ImportVerilog. :wink:
=> [arcilator] Strip Emit dialect operations

lib/Dialect/OM/Evaluator/Evaluator.cpp, unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp
Most interesting arithmetic on APSInt asserts that both operands are the same bitwidth, but the IntegerAttrs that we are working with may have used the smallest necessary bitwidth to represent the number they hold, and won't necessarily match.
This extends the smaller operand if necessary. This is safe to do, even for operands like the RHS of a shift right, because it will zero or sign extend without adding "significant bits" in the APSInt representation. So if we had a shift right amount that previously fit in 64 bits, and we had to extend it beyond 64 bits, we are still able to truncate to 64 bits when performing the shift.
=> [OM] Extend APSInts as necessary before performing arithmetic.

CMakeLists.txt
These targets are useful for downstream projects that want to install
all CIRCT libraries. The CMake commands follow how similar targets are
set up in upstream MLIR.
=> [CMake] Add CMake targets to install all CIRCT libraries.

lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/errors.mlir
Fix an issue in the parser of the `firrtl.constant` op, which would truncate the sign bit of negative constants without reporting an error. This would for example accept -2 as a valid 1-bit constant, truncating the `...11111110` bit pattern to `0`.
=> [FIRRTL] Fix sign bit truncation in constant parser

lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp, test/Dialect/FIRRTL/lower-memory.mlir
Instead of just dedup-ing the external memory module, we include the memory wrapper module in the dedup calculation.
Resolves #6445.
Diff in `circt-opt -firrtl-lower-memory test/Dialect/FIRRTL/lower-memory.mlir` after this change:
```diff
--- main
+++ dedup-lower-memory-modules
@@ -75,7 +75,7 @@
firrtl.circuit "Dedup" {
firrtl.module @Dedup() {
%mem0_W0_addr, %mem0_W0_en, %mem0_W0_clk, %mem0_W0_data = firrtl.instance mem0 @mem0(in W0_addr: !firrtl.uint<4>, in W0_en: !firrtl.uint<1>, in W0_clk: !firrtl.clock, in W0_data: !firrtl.uint<42>)
-      %mem1_W0_addr, %mem1_W0_en, %mem1_W0_clk, %mem1_W0_data = firrtl.instance mem1 @mem1(in W0_addr: !firrtl.uint<4>, in W0_en: !firrtl.uint<1>, in W0_clk: !firrtl.clock, in W0_data: !firrtl.uint<42>)
+      %mem1_W0_addr, %mem1_W0_en, %mem1_W0_clk, …
```
=> [FIRRTL] Dedup memory wrapper modules in LowerMemory

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes.mlir
We have an existing check that paths are in the same owning module as the entity they target. This is absolutely required for hierarchical references to compose with basepaths. However, we have legacy flows that extract entities out of their owning module, and we want to be able to target those things. This works around these conflicting requirements by skipping the owning module check for local targets only. This is safe because we still check such local targets are only instantiated once, so there is no ambiguity even though they are not instantiated within the owning module.
=> [FIRRTL] Don't enforce owning module for local ref in LowerClasses.

tools/arcilator/arcilator.cpp
Yet another tiny PR:
Add `VerbosePassInstrumentation` to the second pass manager of the arcilator tool to include its statistics in the `--verbose-pass-executions` output.
=> [NFC][arcilator] Reenable instrumentation for ArcToLLVM passes.

include/circt/Conversion/Passes.td, include/circt/Dialect/Emit/EmitOps.td, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/ExportVerilog/ExportVerilogInternals.h, lib/Conversion/FIRRTLToHW/CMakeLists.txt, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Conversion/PassDetail.h, lib/Dialect/Emit/EmitOps.cpp, test/Conversion/ExportVerilog/emit-fragment-errors.mlir, test/Conversion/ExportVerilog/emit-fragment.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
Instead of using the replicated op mechanism, fragments of SV code which must precede certain modules are grouped into fragment ops. Modules which rely on them reference them through a `emit.fragment` attribute. The fragments are printed through ExportVerilog.
Subsequent PRs will fully replace replicated ops using fragments.
=> [Emit] Group file header ops into `emit.fragment`

lib/Dialect/FIRRTL/Transforms/InferReadWrite.cpp, test/Dialect/FIRRTL/inferRW.mlir
The read-write port of a memory has an input enable `en` signal and a write-mode `wmode` signal. The `en` signal enables the port for either read/write mode. The `wmode` is enabled to set the memory in the write mode and disabled to read from the memory.
This PR removes the dependency of `wmode` on the `en` signal of a read-write port of a memory.
The `wmode` signal matters only if the `en` is enabled, hence traverse the expression tree for the `wmode` and replace `en` with a constant `1`.
=> [InferRW] Remove dependence of write-mode on enable for memory

lib/Dialect/FIRRTL/Transforms/InferReadWrite.cpp, test/Dialect/FIRRTL/inferRW.mlir
This fixes a bug in InferReadWrite, the builder was not respecting dominance when updating the IR.
Ensure that the builder creates the constant at the start of the module, instead of at the memory op.
The bug was introduced in #6818
=> [InferReadWrite] Set builder insertion point to ensure dominance

include/circt/Dialect/SMT/SMTOps.h, include/circt/Dialect/SMT/SMTOps.td, include/circt/Dialect/SMT/SMTTypes.td, lib/Dialect/SMT/CMakeLists.txt, lib/Dialect/SMT/SMTOps.cpp, test/Dialect/SMT/basic.mlir, test/Dialect/SMT/core-errors.mlir, test/Dialect/SMT/cse-test.mlir
The `declare_const` operation could be pure if `fresh` is not specified. If `fresh` maybe an allocate side-effect could work? I think tablegen does not have the traits to specify this so fine-grained, we'd need to fall back to C++, so I'd leave it to another PR. Also to have it as the sole focus. There might be some corner cases to think about, e.g., what if there are `declare_const` with the same identifier, but different sort/type. The lack of such traits and optimizations makes it behave like SMT-LIB, though.
=> [SMT] Add declare_const, assert, solver, and check operations

include/circt/Dialect/SMT/SMTBitVectorOps.td, include/circt/Dialect/SMT/SMTOps.td, lib/Dialect/SMT/SMTOps.cpp, test/Dialect/SMT/basic.mlir, test/Dialect/SMT/bitvectors.mlir, test/Dialect/SMT/core-errors.mlir
Unfortunately, I had to write a custom parser for the `eq` and `distinct` operations to only specify one of the operands types (`eq %a, %b : !smt.bool` vs. `eq %a, %b : !smt.bool, !smt.bool`). Let me know if there's a feature for that in tablegen in case I missed something.
=> [SMT] Add comparison operations

include/circt/Dialect/SMT/SMTBitVectorOps.td, include/circt/Dialect/SMT/SMTTypes.td, lib/Dialect/SMT/SMTOps.cpp, lib/Dialect/SMT/SMTTypes.cpp, test/Dialect/SMT/bitvector-errors.mlir, test/Dialect/SMT/bitvectors.mlir
The last few operations to be able to fully lower comb (except `comb.mux` for which we need more boolean operators to use `ite`, and `comb.parity`).
=> [SMT] Add concat, extract, repeat operations

include/circt/Conversion/Passes.h, include/circt/Conversion/Passes.td, include/circt/Conversion/VerifToSMT.h, include/circt/Dialect/SMT/SMTOps.td, include/circt/Dialect/Verif/VerifOps.td, lib/CAPI/Conversion/CMakeLists.txt, lib/Conversion/CMakeLists.txt, lib/Conversion/HWToSMT/HWToSMT.cpp, lib/Conversion/VerifToSMT/CMakeLists.txt, lib/Conversion/VerifToSMT/VerifToSMT.cpp, lib/Dialect/Verif/VerifOps.cpp, test/Conversion/VerifToSMT/verif-to-smt-errors.mlir, test/Conversion/VerifToSMT/verif-to-smt.mlir, test/Dialect/Verif/basic.mlir, test/Dialect/Verif/errors.mlir, tools/circt-opt/CMakeLists.txt
Add a first implementation of a LEC operation. This has to be refined as we go forward, e.g., to support reporting of counter-examples. An operation to express a LEC statement explicitly in the IR at the CIRCT Core level allows us to state the general intent to perform LEC without committing to one specific approach/backend yet.
This PR also already adds one such lowering (constructing a simple miter circuit encoded in SMT). A followup PR will introduce a separate pass that takes two `hw.module`s and transforms them into one `verif.lec` operation.
=> [Verif] Add LEC operation

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp, test/Dialect/SV/hw-extract-test-code.mlir
This ensures that the extracted modules have the same fragments included as the original modules.
=> [Emit] Copy fragments into modules created by ExtractTestCode

include/circt/Analysis/SchedulingAnalysis.h, include/circt/Conversion/HWToBTOR2.h, lib/Analysis/SchedulingAnalysis.cpp, lib/Analysis/TestPasses.cpp, lib/Dialect/Pipeline/Transforms/ScheduleLinearPipeline.cpp
`using namespace` generally should not be in headers as it can lead to _interesting_ aliasing problems, especially w.r.t. `namespace mlir` and `namespace llvm`.
=> [NFC] Move 'using namespace' out of headers.

include/circt/Conversion/Passes.td, include/circt/Dialect/HW/HWTypeDecls.td, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/FSMToSV/CMakeLists.txt, lib/Conversion/FSMToSV/FSMToSV.cpp, test/Conversion/FSMToSV/test_basic.mlir
Instead of relying on replicated ops, the pass now directly sets up its file structure using `emit` ops. As a side effect, the type scope file is no longer included in the default file list as that one is only going to include SV files generated from `hw.module`.
=> [FSM][Emit] Convert the FSMToSV pass to use `emit` ops

include/circt/Conversion/Passes.td, lib/Conversion/SeqToSV/CMakeLists.txt, lib/Conversion/SeqToSV/SeqToSV.cpp, test/Dialect/Seq/firreg.mlir
The verbatims and SV macros are grouped into fragments now. As a beneficial side effect, a module is prefixed with fragments in its file only when it is actually using the fragments, reducing output size.
=> [Emit][Seq] Emit random init headers using fragments

lib/Dialect/HW/InnerSymbolTable.cpp
When an IRN has a huge number of top-level operations that need inner ref verification, the current code scaled poorly as the amount of per-op verification work is tiny (handful of hashtable lookups) compared to the overhead and atomic access of failableParallelForEach.
Scan through the operations sequentially as a pre-pass and directly verify operations with no regions, only using parallelization for verifying recursive walks of modules.
=> [HW][IST] Verify simple inner-ref-user ops sequentially, perf fix.

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLStatements.td
These are expressions not statements, they have return values.
=> [FIRRTL][NFC] Move xmr.ref and xmr.deref into expressions.

lib/Conversion/ImportVerilog/CMakeLists.txt, lib/Conversion/ImportVerilog/ImportVerilog.cpp, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, lib/Conversion/ImportVerilog/Statements.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/errors.sv
Extend the `ImportVerilog` conversion to support `if` statements and `for`, `repeat`, `while`, `do ... while`, and `forever` loops. Lower them to `scf.if` and `scf.while` ops for now. In the future, since Verilog has `break`, `continue`, and `return` statements, we may have to switch to a different dialect or defined these ops in the Moore dialect.
=> [ImportVerilog] Add if and loop statements

docs/Dialects/FIRRTL/FIRRTLAnnotations.md, lib/Dialect/FIRRTL/FIRRTLIntrinsics.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, test/Dialect/FIRRTL/lower-intrinsics.mlir
Documentation indicates this was intended to be removed once FIRRTL language supports intrinsics, and we have intmodule's now.
=> [FIRRTL] Remove support for circt.Intrinsic annotation.

include/circt/Dialect/FIRRTL/FIRRTLStructure.td, lib/Dialect/FIRRTL/Export/FIREmitter.cpp, lib/Dialect/FIRRTL/FIRRTLIntrinsics.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/parse-errors.fir
It's mandatory in the FIRRTL spec and only an error if it's missing, so directly require this.
Add test for this and invalid intrinsic name.
=> [FIRRTL] Make "intrinsic" name of intmodule mandatory.

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, test/Conversion/ImportVerilog/basic.sv
Add support for pre and post increment and decrement expressions, like `x++` and `--x`, as well as assign expressions, like `a += 5`. Slang represents these assignments as `Assign(a, Add(LValueRef, 5))` in the AST. The `LValueRef` node contextually refers to the parent assignment's left-hand side. To deal with this, also add a corresponding lvalue stack to the conversion context. Assignments push and pop their lvalues onto and off of this stack.
These expressions require a mechanism in the IR to express _when_ a variable is read. To capture this, add a new `moore.read_lvalue` op. It currently looks like an identity operation with a `MemRead` side effect. Further down the road, we may want to introduce a proper reference type for variables, ports, nets, and other things, and have …
=> [ImportVerilog] Add assign and pre/post increment/decrement expressions

include/circt/Dialect/SMT/SMTArrayOps.td, include/circt/Dialect/SMT/SMTOps.td, include/circt/Dialect/SMT/SMTTypes.h, include/circt/Dialect/SMT/SMTTypes.td, lib/Conversion/VerifToSMT/VerifToSMT.cpp, lib/Dialect/SMT/SMTOps.cpp, lib/Dialect/SMT/SMTTypes.cpp, test/Conversion/VerifToSMT/verif-to-smt.mlir, test/Dialect/SMT/basic.mlir, test/Dialect/SMT/core-errors.mlir, test/Dialect/SMT/cse-test.mlir, unittests/Dialect/SMT/CMakeLists.txt, unittests/Dialect/SMT/TypeTest.cpp
Recursive functions are not (yet) supported and would require their own operations.
=> [SMT] Add function application operation, function and uninterpreted sort types

include/circt/Dialect/SV/SVPasses.td, lib/Dialect/SV/CMakeLists.txt, lib/Dialect/SV/Transforms/CMakeLists.txt, lib/Dialect/SV/Transforms/PassDetail.h, lib/Dialect/SV/Transforms/SVExtractTestCode.cpp, test/Dialect/SV/hw-extract-test-code.mlir, test/firtool/extract-test-code.fir
Fix a bug where SVExtractTestCode was not extracting asserts, assumes, and covers from the verif dialect.  This resulted in unexpected end-to-end "failures" from Chisel where Chisel asserts, assumes, and covers were not extracted and left in the design.
Fixes #6864.
=> [SV][Verif] Extract verif ops in SVExtractTestCode

lib/Dialect/FIRRTL/Import/FIRParser.cpp
roughly triples modules parsing performance on large designs.  This is about a 2x speedup for overall parsing stage.
=> [FIRRTL] Cache a symbol table instead of doing linear lookups every instance.

CMakeLists.txt, include/circt/Dialect/SMT/SMTVisitors.h, include/circt/InitAllTranslations.h, include/circt/Target/ExportSMTLIB.h, integration_test/Target/ExportSMTLIB/basic.mlir, integration_test/lit.cfg.py, integration_test/lit.site.cfg.py.in, lib/Target/CMakeLists.txt, lib/Target/ExportSMTLIB/CMakeLists.txt, lib/Target/ExportSMTLIB/ExportSMTLIB.cpp, test/Target/ExportSMTLIB/array.mlir, test/Target/ExportSMTLIB/bitvector.mlir, test/Target/ExportSMTLIB/core-errors.mlir, test/Target/ExportSMTLIB/core.mlir, test/Target/ExportSMTLIB/integer.mlir
Quantifier patterns and other attributes are not yet supported, but will be added in a future PR since this one is already quite big. Feel free to let me know if I should split it up
=> [SMT] Add SMT-LIB export translation

include/circt/Dialect/FIRRTL/FIRRTLIntrinsics.td, include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/round-trip.mlir
Add generic intrinsic operation to FIRRTL.  Not used anywhere, just adding to the IR to build on.
Re-use module parameter printing/parsing for use as custom printer on the op.
Bit of context:
This is intended to have a FIRRTL textual equivalent that allows intrinsics to be used as expressions or statements, as a replacement for instances of intmodule's in the future, for ergonomic but primarily practical reasons that limit intrinsic use today.
The op is generic so that intrinsics may be parsed without the parser knowing details of supported intrinsics while still having sufficient type information to produce IR and good diagnostics during parsing (return value in particular).
Operands and results are required to be passive (and base) as that's all that is supported today (crashes at …
=> [FIRRTL] Add generic intrinsic op.

include/circt/Dialect/FIRRTL/FIRRTLAttributes.h, include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td, include/circt/Dialect/FIRRTL/FIRRTLStructure.td, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Conversion/HandshakeToHW/HandshakeToHW.cpp, lib/Dialect/FIRRTL/FIRRTLAttributes.cpp, lib/Dialect/FIRRTL/FIRRTLInstanceImplementation.cpp, lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/Dedup.cpp, lib/Dialect/FIRRTL/Transforms/InferResets.cpp, test/Dialect/FIRRTL/errors.mlir
APInt requires an allocation to start large values.  Using apint for port directions requires copying the apint when inspecting port directions, thus introducing huge amount of copies throughout the code.  On large designs just this allocation overhead amounted to over 25% of the time spent (plus copy times).  DenseArrays are less space efficient (by 8x as used), but can be accessed by reference, removing these allocations.
Overall improvement is about 35% - 40%.
=> [FIRRTL] Change Port Direction attribute from an APInt to a DenseArray.

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, include/circt/Firtool/Firtool.h, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/CreateCompanionAssume.cpp, lib/Firtool/Firtool.cpp, test/Conversion/FIRRTLToHW/emit-chisel-asserts-as-sva.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/SFCTests/complex-asserts.fir, test/Dialect/FIRRTL/create-companion-assume.mlir, test/Dialect/FIRRTL/lower-intrinsics.mlir, test/firtool/chisel_assert.fir
This PR separates UNROnlyAssume generation from AssertOp lowering into a dedicate op.
This commit adds:
* LowerToHW support for `UnclockedPredicateIntrinsicOp` (added in https://github.com/llvm/circt/pull/6867).
* CreateCompanionAssume pass which explicitly introduces companion assumes to the IR. Normal assume and UnclockedPredicateIntrinsicOp are used based on the guard's content.
The commit is intended not to change semantics of generated verilog. This commit should only introduces cosmetic changes regarding guards(because now they are reused).
=> [FIRRTL] Add CreateCompanionAssume pass; Decouple UNROnlyAssume generation from AssertOp lowering

docs/Dialects/FIRRTL/FIRRTLIntrinsics.md, lib/Dialect/FIRRTL/Transforms/LowerIntrinsics.cpp, test/Dialect/FIRRTL/lower-intrinsics.mlir, test/firtool/chisel_assert.fir
As we moved companion assume generation to a pass, having `AssertAssume` would not be necessary anymore. We still need assert instrinsic so this PR just renames the intrinsic to `assert`
=> [FIRRTL] Deprecate AssertAssume intrinsic and rename it to Assert

lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp, test/firtool/blackbox-directories.fir
When determining which directory to place a blackbox into, make two changes to get this working correctly with layers:
1. Never change a directory if one is already specified.
2. Treat any bound instance as not under the DUT.
Taken together, this preserves both the original behavior of grand central blackbox extraction and causes blackboxes instantiated under layers to be placed in the testbench directory.
Fixes #6880.
Note: that this intentionally does _not_ test what happens when something is inside a Grand Central View. I'm going to go out on a limb and not specify this and state that we probably don't want to support it. Grand Central Views are planned to be fully replaced with layers making this question irrelevant.
=> [FIRRTL] Treat blackboxes in layers as "testbench"

lib/Conversion/ExportVerilog/ExportVerilog.cpp
Getting all the ports to lookup one attribute is very expensive.  Mainly from GetAllPortLocs requiring several lookups and allocations.  Just avoid doing this by not using the summary functions and looking up individual ports directly (as should generally be done to avoid the overly broad expensive functions).  Granted that getPort goes through the summary functions isn't obvious or ideal.  It should be fixed.
=> [NFC] Massive Export Verilog Speedup

include/circt-c/Firtool/Firtool.h, include/circt/Conversion/FIRRTLToHW.h, include/circt/Conversion/Passes.td, include/circt/Firtool/Firtool.h, lib/CAPI/Firtool/Firtool.cpp, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Conversion/PassDetail.h, lib/Firtool/Firtool.cpp, test/Conversion/FIRRTLToHW/emit-chisel-asserts-as-sva.mlir, test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir, test/Dialect/FIRRTL/SFCTests/complex-asserts.fir
This commits replaces `--emit-chisel-asserts-as-sva` with an option with more fine grained control.
Specifically an option `--verification-flavor={none, if-else-fatal, immediate, sva}` is added. `none` is the option for the current behaviour that uses per-op configuration (which must be deprecated once after `has_been_reset` is properly used for assertions that are expected to be disabled while pre-resets). 
Close https://github.com/llvm/circt/issues/6543
=> [LowerToHW] Emission Option for verification flavors

include/circt/Dialect/HW/HWTypes.h, include/circt/Dialect/HW/HWTypesImpl.td, lib/CAPI/Dialect/FIRRTL.cpp, lib/Dialect/HW/HWOps.cpp, lib/Dialect/HW/HWTypes.cpp
Use custom storage for ModuleType to cache input/output <-> index mappings.  Speeds up many things in small ways.
=> [NFC] Cache common lookups in ModuleType

include/circt/Dialect/Pipeline/PipelineOps.td, test/Dialect/Pipeline/canonicalization.mlir
Pipelines may be side-effectful - remove `Pure` trait to prevent such pipelines from being DCE'd during canonicalization.
=> [Pipeline] Remove `Pure` trait from Pipeline operations

include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
FPGAProbeIntrinsicOp is not an expression (not pure and no results!), mlir::UnrealizedConversionCast is only sometimes expression-like (and FIRRTLVisitor is for visiting FIRRTL-dialect operations only), and GenericIntrinsicOp is neither expression nor statement so just add a special visitor for it.
Update passes using visitors to reflect these changes.
=> [FIRRTL] Fixup visit ops miscategorized.

include/circt/Dialect/SMT/SMTAttributes.td, include/circt/Dialect/SMT/SMTBitVectorOps.td, lib/Dialect/SMT/SMTAttributes.cpp, test/Dialect/SMT/bitvectors.mlir, unittests/Dialect/SMT/AttributeTest.cpp
Some minor changes to the construction of BitVector attributes in the SMT dialect:
- Fix parsing of `smt.bv.constant #smt.bv<-1> : !smt.bv<1>` which currently trips the width check due to `odsParser.parseInteger` creating an unnecessarily wide `APInt`. The new logic is copy-pasted from the FIRRTL ConstantOp parser. See #6794.  
- Change the type of the attribute builder's `value` argument from `unsigned` to `uint64_t` matching the signature of the `APInt` constructor, to allow values up to 64 bits and avoid architecture dependent behavior.
- Prevent left-shifts wider than (or equal to) the shifted operand's number of bits in the width checking logic to avoid undefined behavior.
=> [SMT] Minor width related fixes for BitVectorAttr

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
When we have a firrtl printf operation with `SInt` operands, it gets lowered something like this:
```verilog
//FIRRTL version 3.3.0
//circuit Test :
// module Test :
//    input clock : Clock
//    input reset : UInt<1>
//    input a : SInt<8>
//    node int = SInt<8>(-0h10)
//
//    printf(clock, UInt<1>(0h1), "int : %d %d\n", int, add(a, int)) : printf_1
[...]
input [7:0] a
[...]
$fwrite(32'h80000002, "int : %d %d\n", 8'hF0, {a[7], a} - 9'h10);
[...]
```
As far as verilog is concerned, the operands to `$fwrite` are unsigned, which means that we get inconvenient printing for negative decimals. This patch wraps signed operands of `firrtl.printf` in `$signed()` during lowering. This is realized as `sv.system "signed" ...` for now. In the next step, we could introduce a separate …
=> [LowerToHW] Wrap signed operands of `PrintFOp` in sv `$signed()`

include/circt-c/Dialect/FIRRTL.h, lib/CAPI/Dialect/FIRRTL.cpp, test/CAPI/firrtl.c
We are building `firrtl.constant` IRs from Chisel through MLIR, `mlirIntegerAttrGet` is used to construct constants, however it only accepts a `int64_t` value as an argument, so constants larger than 64 bits are not possible to be constructed at the moment.
Upstream report: https://github.com/llvm/llvm-project/issues/84190#issuecomment-2035552035
Refer to @mikeurbach's PR #6787, I propose to likewise add a string hack to workaround this problem. Using this new added C-API `firrtlAttrGetIntegerFromString`, users (e.g. Chisel) could construct a `MlirIntegerAttr` from a big int string.
=> [FIRRTL][CAPI] Allow constructing integers larger than 64 bits

lib/Dialect/FIRRTL/Export/FIREmitter.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Import/FIRTokenKinds.def, test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir
Add parsing and emitter support for FIRRTL intrinsic.
Refactor parameter parsing on (ext/int)modules as these use same syntax.
Snippet from parse-basic.fir without FileCheck directives:
```firrtl
circuit GenericIntrinsics:
public module GenericIntrinsics:
input data : UInt<32>
input c : UInt<1>
; Statements
intrinsic(circt_verif_assert, c)
intrinsic(circt_fpga_probe, data, clock)
; Expressions
node n = intrinsic(circt_plusargs_value<FORMAT = "foo"> : { found : UInt<1>, result : UInt<5> })
node n2 = intrinsic(circt_plusargs_test<FORMAT = "bar"> : UInt<3>)
; Statement with unused return value.
intrinsic(circt_clock_gate : Clock, clock, c)
; Nesting, statement and expression forms.
intrinsic(circt_verif_assert, intrinsic(circt_isX: UInt<1>, data))
```
And somewhat …
=> [FIRRTL] Generic intrinsic parsing/emitter support

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, test/Dialect/FIRRTL/SFCTests/directories.fir, test/Dialect/FIRRTL/emit-metadata.mlir
Update the object model generated by the CreateSiFiveMetadata pass to generate `firrtl` dialect, instead of `om` dialect.
Ensure all `firrtl.class` associated with the metadata are instantiated inside a top level `firrtl.class` `SiFive_Metadata` , which is instantiated inside the top level `firrtl.module`.  This is required for ensuring that subsequent passes can lower it correctly.
Generate all the hierarchical paths to the memory and associate them with the path operation for the memory metadata.
=>  [CreateSiFiveMetadata] Generate firrtl.class instead of om.class 

include/circt/Dialect/Ibis/IbisOps.td, integration_test/Dialect/Ibis/end_to_end.mlir, lib/Dialect/Ibis/Transforms/IbisCleanSelfdrivers.cpp, lib/Dialect/Ibis/Transforms/IbisContainersToHW.cpp, lib/Dialect/Ibis/Transforms/IbisMethodsToContainers.cpp, lib/Dialect/Ibis/Transforms/IbisPortrefLowering.cpp, lib/Dialect/Ibis/Transforms/IbisTunneling.cpp, test/Dialect/Ibis/Transforms/clean_selfdrivers.mlir, test/Dialect/Ibis/Transforms/containerize.mlir, test/Dialect/Ibis/Transforms/containers_to_hw.mlir, test/Dialect/Ibis/Transforms/methods_to_containers.mlir, test/Dialect/Ibis/Transforms/path_end_to_end.mlir, test/Dialect/Ibis/Transforms/portref_lowering.mlir, test/Dialect/Ibis/Transforms/scoperef_tunneling.mlir, test/Dialect/Ibis/Transforms/tunneling_errors.mlir, test/Dialect/Ibis/canonicalization.mlir, test/Dialect/Ibis/errors.mlir, test/Dialect/Ibis/inner_ref_errors.mlir, test/Dialect/Ibis/round-trip.mlir, test/ibistool/output_format.mlir
Port symbols now have no effect on the eventual port name of a module. This also implies that multiple ports can have the same namehint, and will be uniqued when lowering `ibis.container` to `hw.module` (see new test in `containers_to_hw.mlir`).
=> [Ibis] Divorce port name (hints) from port symbol names

docs/Dialects/FIRRTL/FIRRTLIntrinsics.md
In the only supported mechanism for using intrinsics, the name must be an identifier so just document that.
Periods are nice, we can adjust the FIRRTL grammar / syntax to allow this in the future if we miss them.
This does not modify the code internally that looks for the dot syntax.
=> [FIRRTL][NFC] Use underscores in documentation.

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td, include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLTypes.td, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Dialect/FIRRTL/canonicalization.mlir, test/Dialect/FIRRTL/infer-widths-errors.mlir, test/Dialect/FIRRTL/infer-widths.mlir
Support parsing mux with selector of zero-width, per spec.
Fix use as mux selector "back-propagating" (acts as-if connected to from a 1-bit source).
Canonicalize narrower selectors to full width for lowering and analysis simplicity.
Fixes #5444.
=> [FIRRTL] no back-prop for width of mux selectors, support narrower

lib/Dialect/FIRRTL/Transforms/InferResets.cpp, lib/Dialect/FIRRTL/Transforms/SFCCompat.cpp, test/Dialect/FIRRTL/infer-resets.mlir, test/firtool/async-reset-anno.fir, test/firtool/async-reset.fir
If you have an initial value for a Register that includes `DontCare` for some of the fields, those fields will be excluded from the Full Async Reset Transform. While `InferResets` and `SFCCompat` separately do the right thing, `InferResets` runs before `SFCCompat` and removes the FART annotation. 
This PR adds additional handling for the FART annotation by letting `InferResets` pass through annotation
=> Update annotation handling to fix partial field reset behavior

lib/Dialect/FIRRTL/Transforms/ResolvePaths.cpp, test/Dialect/FIRRTL/resolve-paths.mlir
We would previously error if paths are contained in multiply instantiated modules, because there is no unique path in this case. However, we could expand out the path into multiple unique paths in this case, but this is only safe to do if the path is already used in a list where multiple paths are acceptable.
This relaxes the requirement and implements the path expansion in this scenario. When we hit a multiply instantiated module, we expand out all the instance paths to that module from the owning module, and create multiple annotations and resolved paths.
=> [FIRRTL] Disambiguate paths when possible in ResolvePaths.

include/circt/Conversion/SMTToZ3LLVM.h, integration_test/Dialect/SMT/basic.mlir, lib/Conversion/SMTToZ3LLVM/LowerSMTToZ3LLVM.cpp, test/Conversion/SMTToZ3LLVM/smt-to-z3-llvm.mlir
Only the quantifier operations are still missing.
=> [SMTToLLVM] Add support for most expressions

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Expressions.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/errors.sv, test/Dialect/Moore/basic.mlir
`moore.replicate` is the extended op for `moore.concate`. 
`moore.extract` represents a single bit or range bits selection, and it can receive a variable as its operand. And for the range bits selection, it has three `RangeSelectionKind`, `Simple`, `IndexedUp`, and `IndexedDown`. Respective example, 
simple_vec[7:4], up_vec[3+:1]/up_vec[3*variable+:1], down_vec[3-:1]/down_vec[3*variable-:1]. 
For the simple_vec, the variable won't as its operands, and for the up_vec and down_vec, the LHS could be non-constant(like 3*variable), but RHS must be a constant, and it represents the width. 
These limitations are defined by SV IEEE 1800-2017 § 11.5.1 and § 11.5.2.
=> [ImportVerilog] Add replicate and extract operations.

lib/Conversion/ImportVerilog/Statements.cpp, test/Conversion/ImportVerilog/basic.sv
Use `scf.if` and `moore.or` to implement the selection logic for case statements. For example, if a default case exists, it will perform an OR operation on all the results above, to determine whether the default statement needs to be executed. If the result of the operation is zero, the default statement will be executed.
However, this still leaves some issues, according to the "IEEE Standard 1800-2017 for SystemVerilog", which mentions that "During the linear search, if one of the Case_item_expressions matches the case_expression, then the statement associated with that case_item should be executed, and the linear search shall terminate." I want to know how we can implement this short-circuit logic?
=> [ImportVerilog] Add case statement.

lib/Conversion/ImportVerilog/Structure.cpp, test/Conversion/ImportVerilog/basic.sv
When declaring a variable with an initial value, like `bit b = 1'b1;`, or `logic [3:0] l1; logic [1:0] l2 = l1[3:2];`. These all will trigger an error: 'moore.variable' op failed to verify that initial value and variable types match.
=> [ImportVerilog] Fix the types mismatch for variable declarations.

include/circt-c/Dialect/FIRRTL.h, lib/CAPI/Dialect/FIRRTL.cpp, test/CAPI/firrtl.c
Used for building `firrtl.mem` from external programs.
https://github.com/llvm/circt/blob/db973f13193728d082cb8bd8873ae524575291e0/lib/Dialect/FIRRTL/FIRRTLOps.cpp#L2982
=> [FIRRTL][CAPI] Add function for getting mask type

include/circt/Dialect/DC/DCOps.td, lib/Conversion/HandshakeToDC/HandshakeToDC.cpp, test/Conversion/HandshakeToDC/basic.mlir
Constant-like unit-rate operations didn't have any output tokens assigned. Fixed s.t. constant-like operations (with no inputs) are emitted using a `dc.source`.
=> [HandshakeToDC] Fix constant unit-rate op lowering

lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
Aim to lower `moore` elementary operators into `comb` or `hw`, excluding `assignments` and `variable declarations`. The latter needs to analyze the entire IR to map variables and their values. And `moore` without `mux(?  :)`, which is substituted by `scf.if`.
The elementary operators include `unary, binary, relational, shift, constant, concatenation, extract, and conversion` operations.
The `moore.extract` operation receives a variable as its operand, but `comb.extract` does not. I asked @fabianschuiki for help. He taught me maybe I could use `comb.shr` to bring a variable down to bit position 0, and then capture the correct number of bits from 0 with `comb.extract`.
=> [MooreToCore] Lower moore operators into comb or hw.

lib/Dialect/FIRRTL/Transforms/LowerIntmodules.cpp, test/Dialect/FIRRTL/lower-intmodules-eicg.mlir
Currently `DedupGroup` is added to almost every module including `EICG_wrapper`. However EICG_wrapper later becomes intrinsic when a compiler option `fixup-eicg-wrapper` is given. This causes a compilation error since annotation is added to an intrinsic. The right fix is to use to EICG intrinsic in the first place but there are still a few things to migrate ( ExtractInstances).  Since dropping DedupGroup annotation on EICG_wrapper is practically safe this PR removes the annotation with a warning.
=> [FIRRTL] Don't fail compilation when Dedup group annotation is on EICG_wrapper

lib/Conversion/HWArithToHW/HWArithToHW.cpp, lib/Dialect/HW/Transforms/FlattenIO.cpp, lib/Transforms/FlattenMemRefs.cpp
According to https://github.com/llvm/llvm-project/commit/6008cd40b7bbdc66555550c2e38648d5ce99cc78:
> This is invalid rewriter API usage: ops that were replaced/erased should not be accessed
I probably did not catch all invalid rewriter API usages since I have only checked `replaceOpWithNewOp` usages.
In general, one can create similar invalid API usages with `eraseOp` and `replaceOp`.
=> Fix invalid rewriter API usages

include/circt/Dialect/Arc/ArcPasses.h, include/circt/Dialect/Arc/ArcPasses.td, include/circt/Dialect/HW/HWPasses.h, include/circt/Dialect/HW/Passes.td, lib/Dialect/Arc/Transforms/CMakeLists.txt, lib/Dialect/HW/Transforms/CMakeLists.txt, lib/Dialect/HW/Transforms/FlattenModules.cpp, test/Dialect/HW/flatten-modules.mlir, tools/arcilator/CMakeLists.txt, tools/arcilator/arcilator.cpp
This PR moves the `arc::inlineModulesPass` to the HW dialect, all while renaming it to something more suitable for what it actually does, as per @fabianschuiki 's recommendation.
=> [HW] Moved and renamed arc/inlineModules to hw/flattenModules

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir
=> [ExportVerilog] Ensure DivS/ModS are signed regardless of context.

include/circt-c/Firtool/Firtool.h, include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, include/circt/Firtool/Firtool.h, lib/CAPI/Firtool/Firtool.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/SFCTests/mem-taps-reg.fir, test/Dialect/FIRRTL/SFCTests/mem-taps.fir, test/Dialect/FIRRTL/annotations.mlir, test/Dialect/FIRRTL/legacy-wiring-errors.mlir, test/Dialect/FIRRTL/legacy-wiring.mlir
Add option to allow this for compatibility.
Add statistic to count ports added to public modules, as an interesting bit of information but particularly to track how many are still being added when updating a code base to avoid this.
=> [FIRRTL] Error if asked to add a port to a public module.

docs/Dialects/FIRRTL/FIRRTLAnnotations.md, include/circt/Dialect/FIRRTL/AnnotationDetails.h, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir, test/Dialect/FIRRTL/emit-metadata.mlir
We've rejected this during LowerAnnotations since we've had LowerAnnotations, so it's safe to say this is thoroughly dead.
The internal source of this was removed in January.
=> [FIRRTL] Drop dead ScalaClassAnnotation.

include/circt/Dialect/FIRRTL/FIRRTLEnums.td, test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/round-trip.mlir
Add an "inline" convention to layers by adding this to the existing enumeration.  By the nature of how the parser works, this automatically adds support to parse this attribute without modifications to the parser.
This does not add any support for this in the FIRRTL pipeline.
=> [FIRRTL] Add inline convention to layers

lib/Dialect/Arc/Transforms/ArcCanonicalizer.cpp, test/Dialect/Arc/arc-canonicalizer.mlir, test/arcilator/compreg.mlir
Arcilator currently does not support non-zero reset values for compreg. This change canonicalizes reset values to a mux on the input, as it currently makes no difference for simulation purposes, and sidesteps the reset value limitations.
=> [Arc] Hoist reset value in CompReg when lowering for simulation

include/circt/Conversion/LTLToCore.h, include/circt/Conversion/Passes.h, include/circt/Conversion/Passes.td, lib/CAPI/Conversion/CMakeLists.txt, lib/Conversion/CMakeLists.txt, lib/Conversion/LTLToCore/CMakeLists.txt, lib/Conversion/LTLToCore/LTLToCore.cpp, lib/Conversion/PassDetail.h, test/Conversion/LTLToCore/assertproperty.mlir, tools/circt-opt/CMakeLists.txt
In order to support the `btor2` emission in Chisel, we need to have a good way to encode property assertions, as this should hopefully at some point be the default for formal verification.
This PR is a factored out version of #6649 that introduces a lowering pass for `ltl` and `verif` operations that are generated by the use of `AssertProperty` in Chisel, and encodes them using operations from the core dialects. This would allow for this assertion type to be used for Bounded Model Checking and is a first step for supported more SVA constructs in the formal backend.
=> [LTL to Core] Add lowering for AssertProperty operations

docs/Dialects/Comb/RationaleComb.md
Be explicit that divide by zero is undefined and show examples of how different semantics for source or target languages can be achieved.
=> [NFCI] Document division and the rational for the handling of divide by zero

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
Transmute these annotations to simple (temporary) attributes on modules.
This causes the desired behavior for hashing and since this must match, when deduplicating no work is needed.
Presently, as annotations, each module dedup'd into the group walks all annotations and "adds context" (makes them non-local) and interns a new annotation array with those annotations. At the end of the pass, all dedupGroup annotations are removed.
This causes a lot of unnecessary symbols, hierpaths, annotations, and arrays of annotations as well as some quadratic behavior.
DedupGroup annotations are commonly on every single module, so for those designs large dedup groups scaled poorly.
Instead, drop these annotations immediately and add as a simple named attribute indicating the group.
Drop the (temporary) …
=> [FIRRTL][Dedup] Alter dedup group handling, avoid exponential behavior.

integration_test/arcilator/JIT/div-by-zero.mlir, lib/Conversion/CombToArith/CombToArith.cpp, test/Conversion/CombToArith/comb-to-arith.mlir
=> [CombToArith] Fix coarsening of division by zero UB

lib/Conversion/DCToHW/DCToHW.cpp, lib/Conversion/HandshakeToDC/HandshakeToDC.cpp, test/Conversion/DCToHW/basic.mlir, test/Conversion/HandshakeToDC/basic.mlir
Modelled after the Handshake lowering, however, becomes trivial with a 2-input merge.
=> [DC] Add merge lowering

include/circt/Dialect/Handshake/HandshakeOps.td, include/circt/Dialect/Handshake/HandshakePasses.h, include/circt/Dialect/Handshake/HandshakePasses.td, lib/Conversion/HandshakeToDC/HandshakeToDC.cpp, lib/Dialect/Handshake/Transforms/CMakeLists.txt, lib/Dialect/Handshake/Transforms/SplitMerges.cpp, test/Conversion/HandshakeToDC/basic.mlir, test/Dialect/Handshake/split-merge.mlir
This pass decomposes the (rather complex) semantics of a >2 input cmerge operation into a series of 2-input cmerge operations + supporting logic. This simpler structure is better suited for `dc` lowering, which only supports lowering 2-input control merge operations.  
Also decomposes >2 input `handshake.merge` operations into 2-input merges.
In pictures:
=> [Handshake] Add merge decomposition pattern

include/circt-c/Dialect/Moore.h
Minor nitty remainder after https://github.com/llvm/circt/commit/a36c25834981f062ca930daa50fe045b2c4df0aa and 282bdb85b2d87833cf92efefb9a2cddb456edee9 @maerhart.
=> [CAPI][Moore] Remove deprecated types

lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
These are not understood in a non-local way, reject them.
Docs say this annotation cannot be used on a module instantiated multiple times (apparently) so non-local should never be needed.
=> [FIRRTL][LowerAnnotations] Reject non-local fullasyncreset anno's.

.clang-tidy
Add the [google-global-names-in-headers](https://clang.llvm.org/extra/clang-tidy/checks/google/global-names-in-headers.html) rule to the list of clang-tidy checks to prevent namespace pollution.
This is intended to flag global using-directives in header files during PR checks. Collisions between the `llvm` and the `mlir` namespace have caused obscure build failures on Windows in the past. #6844 should have removed all existing occurrences in the CIRCT code base.
=> [NFC][clang-tidy] Disallow global 'using' directives in headers

lib/Dialect/FIRRTL/Transforms/SFCCompat.cpp, test/firtool/async-reset-anno.fir, test/firtool/async-reset.fir
Fix test and extend to cover non-port case:
* Fix async-reset-anno test to fail with its backing change reverted, as-is the passes weren't run and the FileCheck command was wrong for the "did it remove the annotation" check.
* Extend async-reset-anno.fir and async-reset.fir tests to cover use of the fullasyncreset annotation on non-ports, which presently fails.
Fix handling of non-port fullasyncreset in SFCCompat (including annotation removal)
* Modify SFCCompat to look for (and remove) fullasyncreset annotations anywhere, not limited to ports.
cc #6912 .
=> [FIRRTL][SFCCompat] Fix tests and handling of fullasyncreset on non-port.

lib/Conversion/ImportVerilog/Statements.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/errors.sv, test/Dialect/Moore/basic.mlir
If we don't collect the local temporary variables, it triggers the following error:
For example:
```
module Temporary();
int x, y, z;
automatic int a;
a = x + 1;
y = a;
a = a + 1;
z = a;
end
endmodule
```
```cpp
Temporary.sv:5:5: error: unknown name `a`
a = x + 1;
```
=> [ImportVerilog] Fix unknown name caused by local variables.

lib/Firtool/Firtool.cpp, tools/firtool/firtool.cpp
In order to support multi-module designs in the formal backend, we need to inline the modules before converting them to btor2. 
This is a naive approach but will work just fine for now.
=> [firtool] Add FlattenModulesPass to the btor2 emission pipeline

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h, include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h, lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp, lib/Dialect/FIRRTL/Transforms/LegacyWiring.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, lib/Dialect/FIRRTL/Transforms/ResolveTraces.cpp
This changes AnnoTargets to use LLVM style casts instead of "trailing" member functions. The LLVM style casts are now usable with AnnoTargets with improvements to the upstream framework.  The current style of cast used with AnnoTargets will no longer be supported by TypeSwitch, so this PR switches to the recommended idiom.
=> [FIRRTL] AnnoTarget: use LLVM style casts

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/firtool/unr-only.fir
Add FIR -> SV test for "unclocked_assert" since we care about ensuring it has a specific shape re:output.
Test extracted from #7010.
=> [FIRRTL] Don't prefix an empty label for unclocked assume.

.github/workflows/shortIntegrationTests.yml, CMakeLists.txt, cmake/modules/AddCIRCT.cmake, lib/CAPI/Conversion/CMakeLists.txt, lib/CAPI/Dialect/CMakeLists.txt, lib/CAPI/ExportFIRRTL/CMakeLists.txt, lib/CAPI/ExportVerilog/CMakeLists.txt, lib/CAPI/Firtool/CMakeLists.txt
Add a `circt-capi` target that depends on all C API libraries. Introduce a new `add_circt_public_c_api_library` CMake function that wraps around the MLIR equivalent, but also adds a dependency from `circt-capi`. Make at least the short integration tests CI job build the `circt-capi` target to ensure it has a bit of CI coverage.
=> [CAPI] Add circt-capi target and build it in CI

integration_test/circt-lec/comb.mlir, lib/Conversion/HWToSMT/HWToSMT.cpp
For single bit module outputs the circt-lec  pipeline initially inserts an unrealized conversion cast to `i1`. At a later stage the `i1` value gets converted to `!smt.bv<1>`. This works fine if the original value also was of type  `!smt.bv<1>`, since the casting chain of   `!smt.bv<1>` -> `i1` ->  `!smt.bv<1>` can be reconciled.
However, some SMT operations (e.g. `EqOp`) produce results of type `!smt.bool`. In this case the indirection via `i1` prevents the required conversion to `!smt.bv<1>`  from being materialized.
This PR adds a dedicated target materialization for conversions to  `!smt.bv<1>`  from `i1`  values that are the result of an unrealized conversion cast from `!smt.bool`.
=> [HWToSMT][circt-lec] Resolve transitive !smt.bool -> i1 -> !smt.bv<1> casts.

include/circt-c/Dialect/Arc.h, lib/CAPI/Dialect/Arc.cpp, lib/CAPI/Dialect/CMakeLists.txt, test/CAPI/CMakeLists.txt, test/CAPI/arc.c
This PR doesn't add full API coverage for Arc types and such, but it's enough to allow Arc to be used for cross language projects such as the CIRCT bindings for Rust through the melior crate.
=> [ARC][CAPI] Add basic C API for initializing ARC

docs/Dialects/Moore.md, include/circt-c/Dialect/Moore.h, include/circt/Dialect/Moore/MooreOps.td, include/circt/Dialect/Moore/MooreTypes.h, include/circt/Dialect/Moore/MooreTypes.td, lib/CAPI/Dialect/Moore.cpp, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/Statements.cpp, lib/Conversion/ImportVerilog/Types.cpp, lib/Conversion/MooreToCore/MooreToCore.cpp, lib/Dialect/Moore/MooreOps.cpp, lib/Dialect/Moore/MooreTypes.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/types.sv, test/Conversion/MooreToCore/basic.mlir, test/Dialect/Moore/basic.mlir, test/Dialect/Moore/canonicalizers.mlir, test/Dialect/Moore/errors.mlir, test/Dialect/Moore/types-errors.mlir, test/Dialect/Moore/types.mlir, unittests/Dialect/Moore/TypesTest.cpp
The core type most SystemVerilog expressions are interested in and operate on is a "simple bit vector type". These are individual integer atoms like `bit` or `logic`, integral types like `int`, or packed arrays with a single dimension and an integer atom inner type, like `bit [42:0]`. So in a nutshell, simple bit vector types are MLIR's `i42` in the two-valued (`bit`) case, or the four-valued equivalent (`logic`).
Up until this point, the Moore dialect reflected this pattern by providing an `IntType` for the integer atoms like `bit` and `int`, and using the `PackedRangeDim` for single dimension vectors of `bit`. A `SimpleBitVectorType` helper struct would then summarize the _actual_ bit vector that was expressed by the packed range and integer atom. This makes working with the types in …
=> [Moore] Make simple bit vectors a proper MLIR type

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, test/Dialect/FIRRTL/expand-whens.mlir
This PR corrects when expansions for `[Assert, Assume, Cover]Poperty` by creating an `implies` statement between the condition of the when and the property itself.
Basically in the case of the following:
```
when(cond): 
AssertProperty(prop)
```
is currently being expanded to simply  
```
AssertProperty(prop)
```
which is wrong, so this PR makes so that it gets expanded to
```
AssertProperty(cond implies prop)
```
=> [FIRRTL] Add condition expansion for ExpandWhens on Property intrinsics

include/circt/Dialect/OM/OMOps.td, integration_test/Bindings/Python/dialects/om.py
This adds `IsolatedFromAbove` to OMClassOp and OMClassExternOp. It should make local verification run parallelly.
=> [OM] Add IsolatedFromAbove to OMClass

cmake/modules/AddCIRCT.cmake
Use our install macro, in same way that `add_circt_library` works.
Ensures CAPI bits have same installation logic as other libraries.
=> cmake: circt install directory for CAPI

lib/Dialect/ESI/runtime/CMakeLists.txt, lib/Dialect/ESI/runtime/python/esiaccel/utils.py
There is no good way to use the binaries included with the wheel. Essentially, they are built with the old `std::basic_string` but modern software uses `std::__cxx11::basic_string`. There is now way to change this behavior (AFAICT) in manylinux2014. Newer manylinux images have a way, but we need compatiblity back to glibc 2.17, which none of them provide.
=> [ESI][Runtime] Remove C++ includes from wheels

include/circt/Dialect/OM/OMOps.td, include/circt/Dialect/OM/OMPasses.h, include/circt/Dialect/OM/OMPasses.td, lib/Dialect/OM/OMOps.cpp, lib/Dialect/OM/Transforms/CMakeLists.txt, lib/Dialect/OM/Transforms/VerifyObjectFields.cpp, lib/Firtool/Firtool.cpp, test/Dialect/OM/errors.mlir
Verification for OM object fields performs global analysis on a symbol table op. This cannot be done efficiently today within symbol table verification without nested symbol tables. So this PR separates the verifier into a dedicated pass and run the verification at several times in the pipeline.
=> [OM] Separates OM object fields verifier to a dedicated pass

include/circt/Dialect/SV/SVStatements.td, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/ExportVerilog/ExportVerilogInternals.h, lib/Conversion/ExportVerilog/LegalizeNames.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir
Introduce an op to specific a list of names which Export Verilog should never use anywhere. Applies to module names, port names, reg/wire/logic names, etc.
=> [SV] Add `sv.reserve_names` op to disallow names

lib/Dialect/ESI/runtime/CMakeLists.txt
Since nlohmann_json is a pretty common dependency, if that target already exists, don't re-download it and run its CMakeLists. This is helpful when the ESI runtime is being itself fetched through cmake `FetchContent`.
=> [ESI][Runtime] Don't pull down JSON dependency if already defined

integration_test/circt-lec/comb.mlir, lib/Conversion/CombToSMT/CombToSMT.cpp, lib/Tools/circt-lec/ConstructLEC.cpp, test/Conversion/CombToSMT/comb-to-smt.mlir
This adapts the conversion pass to match the recently agreed upon definition for division by zero. Integration tests for circt-lec are added to check the behavior. Note that two syntactically equivalent modules are not considered equivalent if they aren't guaranteed to deterministically produce the same outputs. Alternatively, we could consider two undefined output values equivalent by modeling each value as a pair of a boolean and the bit-vector where the boolean determines if the value is undefined, then two outputs are equivalent if either the boolean is true or the boolean is false and the bitvectors match. There are probably use-cases for both, so maybe we'd want a flag to let the user decide.
=> [CombToSMT] Make result of div-by-zero undefined

include/circt/Dialect/Moore/MooreTypes.h, include/circt/Dialect/Moore/MooreTypes.td, lib/Dialect/Moore/MooreTypes.cpp
Replace the C++ definition of `IntType` with a corresponding table-gen definition in `MooreTypes.td`.
=> [Moore] Move IntType definition into ODS

lib/Dialect/FIRRTL/FIRRTLIntrinsics.cpp, test/firtool/firtool.fir
If the new op's result doesn't match, insert a wire + connect (if valid) to handle the mismatch.
For intrinsics that lower to ops with return type inference, the inferred type may be different than the declared type (e.g., `UInt` vs `UInt<1>`).
=> [FIRRTL][Intrinsics] source materialization for inferred types.

include/circt/Dialect/SV/SVStatements.td, include/circt/Dialect/SV/SVVisitors.h, lib/Dialect/SV/SVOps.cpp, test/Dialect/SV/basic.mlir, test/Dialect/SV/errors.mlir
This PR adds an op `sv.func.dpi.import` for "emitting" DPI import statement. `sv.func.dpi.import` doesn't declare function but it takes a function symbol to emit import statement. This design is similar to what `sv.macro.ref/def` does and it enables us to decouple function declaration and emission. 
```
// CHECK-LABEL: import "DPI-C" linkage_name = function void function_declare1(
// CHECK-NEXT:    input [1:0] in_0,
// CHECK-NEXT:                out_0,
// CHECK-NEXT:                in_1,
// CHECK-NEXT:    output out_1
// CHECK-NEXT: );
sv.func.dpi.import linkage "linkage_name" @function_declare1
```
=> [SV] Add DPI import op

lib/Dialect/SV/SVOps.cpp
=> [SV][Folds] Fix ForOp canonicalizer to use rewriter.

lib/Dialect/HW/HWOps.cpp
=> [HW] Fix pattern returning success() without changing.

lib/Dialect/Comb/CombFolds.cpp
=> [Comb] Fix MuxRewriter to eraseOperand in rewriter-aware way.

lib/Dialect/LLHD/IR/LLHDOps.cpp
=> [LLHD] Fix operand assignments not going through rewriter.

test/Dialect/Ibis/Transforms/scoperef_tunneling.mlir, test/Scheduling/problems.mlir, test/firtool/convention.fir
Only one actual typo in this PR, others are slight alterations so lint is clean and could be added as a CI check moving forward.
Don't want to bend too far to appease a lint tool, but would be great to have this flagged on PR's.
=> FileCheck directive fixup, now filecheck_lint-clean.

include/circt-c/Dialect/Moore.h, include/circt/Dialect/Moore/MooreTypes.h, include/circt/Dialect/Moore/MooreTypes.td, lib/CAPI/Dialect/Moore.cpp, lib/Conversion/ImportVerilog/Types.cpp, lib/Dialect/Moore/MooreTypes.cpp, test/Conversion/ImportVerilog/types.sv, test/Dialect/Moore/types.mlir, unittests/Dialect/Moore/TypesTest.cpp
Coalesce SystemVerilog's `shortreal`, `real`, and `realtime` types into a single `!moore.real` type understood to be 64 bits wide, and move the definition from C++ land into `MooreTypes.td`. Once ImportVerilog actually supports expressions on real values we may want to revisit this type and either replace it with the standard `f32` and `f64` types, or create dedicated types for `shortreal`, `real`, and `realtime`.
=> [Moore] Simplify and move RealType definition into ODS

integration_test/Dialect/ESI/runtime/loopback.mlir.py, lib/Dialect/ESI/runtime/CMakeLists.txt, lib/Dialect/ESI/runtime/cosim/CMakeLists.txt, lib/Dialect/ESI/runtime/cosim/cosim_dpi_server/DpiEntryPoints.cpp, lib/Dialect/ESI/runtime/cosim/include/cosim/CapnpThreads.h, lib/Dialect/ESI/runtime/cosim/include/cosim/Endpoint.h, lib/Dialect/ESI/runtime/cosim/lib/CapnpThreads.cpp, lib/Dialect/ESI/runtime/cosim/lib/Client.cpp, lib/Dialect/ESI/runtime/cosim/lib/Endpoint.cpp, lib/Dialect/ESI/runtime/cosim/lib/Server.cpp, lib/Dialect/ESI/runtime/cpp/include/esi/Common.h, lib/Dialect/ESI/runtime/cpp/include/esi/backends/Cosim.h, lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp
Previously, the cosim backend only supported single threaded workloads since the RPC calls would happen in the client calling thread. Now, spin up a "capnp" thread to do all of the RPC interactions.
=> [ESI][Runtime] Refactor cosim backend to be thread safe

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
=> [FIRRTL] Fix width of attribute in MuxPadSel canonicalizations.

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
Two of these caught by -DMLIR_ENABLE_EXPENSIVE_PATTERN_API_CHECKS=ON.
Others by inspection.
cc #7047.
=> [FIRRTL][Folds] Fix patterns to use rewriter for RAUW

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-errors.fir
https://github.com/chipsalliance/firrtl-spec/pull/210
Should not merge until/if they're removed from spec, but it's ready when we are.
Follow-on "eventually" would be dropping them from our IR / rejecting on all versions.
=> [FIRRTL] Reject intrinsic modules >= 4.0.0

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp
InstanceOp::getPortList is a foot-gun that walks entire circuits. We could rewrite it with instance graph version but apparently there is no user so just delete it.
=> [FIRRTL] Remove unused and expensive API, NFC

lib/Dialect/FIRRTL/Transforms/LowerMatches.cpp, lib/Dialect/FIRRTL/Transforms/MemToRegOfVec.cpp
LowerMatchesPass and MemOfVec should preserve analysis if nothing happens.
=> [FIRRTL] Preserve all analysis if nothing happens

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
Now that invalid is better defined, we can start propagating it when we can preserver semantics.  This means not breaking the one-op-is-one-consistent-value (e.g. not duplicating).  The only bit mutating op which is touched by this change is not, which is a pure all-bits inversion, which should be safe (tm).
=> [FIRRTL] Limited invalid propagation.

lib/Conversion/ImportVerilog/Expressions.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/errors.sv
Use `==` to compare the left-hand expression with expressions and use `<=`, `>=` to compare the left-hand expression with ranges.
Then, according to the IEEE 1800-2017 § 11.4.13 "Set membership operator", "The return value is effectively the or reduction of all the comparisons in the set with the expression on the left-hand side.", It will perform `or` operation on all comparison results above, and the result of `or` is the result of set membership operator.
=> [ImportVerilog] Support set membership operator.

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes.mlir
`LowerClass` creates an object for a corresponding instance only if the instantiated module has property ports. 
But a class can be created for a corresponding module based on other conditions like, if the module is  public, or instantiates other classes.
This results in un-instantiated classes that donot correspond to the module hierarchy.
This change ensures that if a class is created for a module, the object is also created from the corresponding instance.
Thus the module hierarchy is also preserved in the `om` IR.
Downstream tools parsing the  IR can assume a single top level class which is required for object model evaluation.
=> [LowerClasses] Ensure classes are instantiated by an object.

include/circt-c/Dialect/Moore.h, include/circt/Dialect/Moore/MooreTypes.h, include/circt/Dialect/Moore/MooreTypes.td, lib/CAPI/Dialect/Moore.cpp, lib/Conversion/ImportVerilog/Types.cpp, lib/Conversion/MooreToCore/MooreToCore.cpp, lib/Dialect/Moore/MooreTypes.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/types.sv, test/Dialect/Moore/basic.mlir, test/Dialect/Moore/types-errors.mlir, test/Dialect/Moore/types.mlir, unittests/Dialect/Moore/TypesTest.cpp
Move the definitions of all array types from C++ land into `MooreTypes.td`. This removes a significant amount of redundant code and simplifies the dialect's type system.
Replace packed and unpacked ranges (`T [4:3]` or `T [2:4]`) with a new type that discards the directionality and offset of the range. This information is no longer needed at the IR level. Any meaning that the offsets have can be encoded in the corresponding ops. Both ranges are now represented as `array<2 x T>` and `array<3 x T>`, respectively.
Combine unpacked ranges (`T foo [6:2]`) and unpacked arrays (`T foo [42]`) into a single `uarray<N x T>` type.
=> [Moore] Move array types into ODS

include/circt/Dialect/Moore/MooreOps.td, include/circt/Dialect/Moore/MooreTypes.h, lib/Dialect/Moore/MooreOps.cpp, lib/Dialect/Moore/MooreTypes.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/types.sv, test/Conversion/MooreToCore/basic.mlir, test/Dialect/Moore/basic.mlir, test/Dialect/Moore/types-errors.mlir, test/Dialect/Moore/types.mlir
Operations defined through TableGen will use a version of type parsing and printing that strips away the dialect prefix in case this does not lead to ambiguities. If an op specifies a type like `UnpackedType`, the generated parser and printer will call `UnpackedType::parse` and `UnpackedType::print` in order to parse and print that type. This method usually prints the type without any dialect prefixes, and often also without the type name itself (as it is obvious given the type).
Add an implementation for `parse` and `print` to `UnpackedType` which performs this stripped printing. This makes the assembly more compact and in-line with what MLIR would generate by default if a TableGen-specified op would use a TableGen-specified type.
This makes the integer flavor of `IntType` look exactly …
=> [Moore] Support stripped type parsing and printing

include/circt/Dialect/Moore/MooreTypes.h, include/circt/Dialect/Moore/MooreTypes.td, lib/Conversion/ImportVerilog/Types.cpp, lib/Dialect/Moore/MooreTypes.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/types.sv, test/Dialect/Moore/types-errors.mlir, test/Dialect/Moore/types.mlir, unittests/Dialect/Moore/TypesTest.cpp
Move the definitions of packed and unpacked struct types from C++ land into `MooreTypes.td`. This removes a significant amount of complexity.
With all types moved into the TableGen file, a lot of redundant code can finally be removed and the parsing/printing can be streamlined significantly.
This change also drops the `StructKind` enum which was used to discern structs, unions, and tagged unions, although the ImportVerilog conversion never generated anything besides structs. Once we add support for unions in the future, the intention is to define new types in ODS for the unions and reuse the `StructMember`.
=> [Moore] Move struct types into ODS

include/circt/Dialect/Arc/ArcPasses.h, include/circt/Dialect/Arc/ArcPasses.td, lib/Dialect/Arc/Transforms/CMakeLists.txt, lib/Dialect/Arc/Transforms/FindInitialVectors.cpp, test/Dialect/Arc/find-initial-vectors.mlir
=> [Arc] Initial SLP support

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp
There has been a lifetime bug that caused an UAF crash. Heaps allocated by DenseMap could be invalided when DenseMap size grows.
=> [FIRRTL][LowerClass] Pre-allocate namespaces before capturing references

include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
Add missing operations to FIRRTLVisitor.
=> [FIRRTL] Visitor: Add missing ops, fix GenericIntrinsicOp visit.

lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp
Create these constants as unsigned of unknown width, instead of s64.
This way when connecting to the address, we don't emit a connnect between s64 and something like u3
(requiring casts/trim/etc).
=> [FIRRTL] Generate memportaccess op index as UInt.

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, lib/Dialect/FIRRTL/Transforms/ResolvePaths.cpp, test/Dialect/FIRRTL/resolve-paths-errors.mlir, test/Dialect/FIRRTL/resolve-paths.mlir
This turns the multiple-instantiation error into a warning in ResolvePaths and LowerClasses. In real designs coming from Chisel today, we are not yet able to enforce single instantiation. This was never a requirement of the original way that we handled hierarchical paths in EmitOMIR, so this removes the requirement for now. Adding it back is tracked in https://github.com/llvm/circt/issues/7128.
With this change, the ResolvePaths logic was simplified to stop trying to disambiguate paths in some cases, and instead allow the annotations to simply convey the user's requested local or hierarchical path. In LowerClasses, if there are multiple instances, this means we have ambiguity. In practice, this logic will produce the same outputs as EmitOMIR, once we fix …
=> [FIRRTL] Simplify path handling in ResolvePaths and LowerClasses.

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, lib/Dialect/FIRRTL/Transforms/ResolvePaths.cpp, test/Dialect/FIRRTL/lower-classes.mlir, test/Dialect/FIRRTL/resolve-paths-errors.mlir, test/Dialect/FIRRTL/resolve-paths.mlir
We stated in a comment that we copy the leading part of the hierarchical path from the owning module to the start of the annotation's NLA. But we never actually did that, so this adds (back) that logic.
Fixes https://github.com/llvm/circt/issues/7125.
=> [FIRRTL] Actually copy the leading part of the path in LowerClasses.

include/circt/Dialect/Moore/MooreDialect.td, include/circt/Dialect/Moore/MooreOps.h, include/circt/Dialect/Moore/MooreOps.td, include/circt/Dialect/Moore/MooreTypes.td, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, lib/Conversion/ImportVerilog/Structure.cpp, lib/Conversion/ImportVerilog/Types.cpp, lib/Dialect/Moore/CMakeLists.txt, lib/Dialect/Moore/MooreDialect.cpp, lib/Dialect/Moore/MooreOps.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/errors.sv, test/Dialect/Moore/basic.mlir, test/Dialect/Moore/errors.mlir
Add module types and support for ports to the `moore.module` and `moore.instance` operations. Also add a `moore.output` operation as a terminator for modules, similar to the HW dialect. Extend ImportVerilog to generate ports.
The ports on SVModuleOp follow a similar strategy as in HWModuleOp: all input, inout, and ref ports are passed to the module as inputs and are carried inside the module as block arguments, while output ports are assigned by the OutputOp terminator. The Moore dialect reuses the `hw::ModuleType` but does not use the `inout` direction. Instead, inout ports will be represented as inputs with a `net<T>` wrapper type, while ref ports will be wrapped as `ref<T>`.
Instances work identically to the HW dialect: input, inout, and ref port connections are carried as operands, …
=> [Moore] Add module and instance port support

lib/Dialect/FIRRTL/Transforms/DropConst.cpp
Before, DropConst on FIRRTL w/300k extmodule's took 221s. Now it's < 1s.
=> [FIRRTL][DropConst] Fix performance with many extmodule's.

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Dialect/Moore/MooreOps.cpp, test/Conversion/ImportVerilog/basic.sv, test/Dialect/Moore/basic.mlir, test/Dialect/Moore/errors.mlir
Handle conditional operator `?:`.
Use `scf.if` to control the selection of expressions, and return the selected value through `scf.yield`.
=> [ImportVerilog] Add conditional operator.

.github/workflows/buildAndTest.yml, .github/workflows/uploadReleaseArtifacts.yml
This might fix a new breakage on the gcc build complaining about DCMAKE_BUILD_TYPE
Should fix:
```
CMake Error at CMakeLists.txt:88 (message):
No build type selected.  You need to pass -DCMAKE_BUILD_TYPE=<type> in
order to configure LLVM.
Available options are:
* -DCMAKE_BUILD_TYPE=Release - For an optimized build with no assertions or debug info.
* -DCMAKE_BUILD_TYPE=Debug - For an unoptimized build with assertions and debug info.
* -DCMAKE_BUILD_TYPE=RelWithDebInfo - For an optimized build with no assertions but with debug info.
* -DCMAKE_BUILD_TYPE=MinSizeRel - For a build optimized for size instead of speed.
```
=> Capitalize Mode in github workflow.  

include/circt/Conversion/ExportVerilog.h, include/circt/Conversion/Passes.td, include/circt/Dialect/Emit/EmitOpInterfaces.h, include/circt/Dialect/Emit/EmitOpInterfaces.td, include/circt/Dialect/HW/HWOpInterfaces.h, include/circt/Dialect/HW/HWOpInterfaces.td, include/circt/Dialect/HW/HWStructure.td, include/circt/Dialect/SV/SVStatements.td, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/ExportVerilog/ExportVerilogInternals.h, lib/Conversion/ExportVerilog/LegalizeNames.cpp, lib/Conversion/ExportVerilog/PrepareForEmission.cpp, lib/Conversion/ExportVerilog/PruneZeroValuedLogic.cpp, lib/Conversion/PassDetail.h, lib/Dialect/Emit/EmitOps.cpp, test/Conversion/ExportVerilog/prepare-for-emission.mlir
This is separated from https://github.com/llvm/circt/pull/6977. This changes pre-passes for ExportVerilog to run on HWEmittableModuleLike instead of HWModuleOp. https://github.com/llvm/circt/pull/6977 is going to add a support for SV func op and legalization needs to be ran on SV func as well. 
HWEmittableModuleLike is a new interface that inherits Emittable+HWModuleLike. I considered to use a trait but we cannot use a trait for pass scheduling so an interface is used.
=> [ExportVerilog][HW] Introduce HWEmittableModuleLike interface and use it for Prepare, NFC

lib/Dialect/FIRRTL/Transforms/InferResets.cpp, test/Dialect/FIRRTL/infer-resets.mlir
Trace reset networks through nodes.
This seems like it was always reasonable to do but is now much more reachable with wire-to-node conversion happening.
=> [FIRRTL][InferResets] Learn how to trace through nodes.

include/circt/Dialect/Moore/MooreOps.td, include/circt/Dialect/Moore/MooreTypes.td, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, lib/Conversion/ImportVerilog/Statements.cpp, lib/Conversion/ImportVerilog/Structure.cpp, lib/Dialect/Moore/MooreOps.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/types.sv, test/Dialect/Moore/basic.mlir, test/Dialect/Moore/errors.mlir
Add a wrapper type(`moore::RefType`) to work for `VariableOp/NetOp`, `ReadOp`, and `AssignOpBase`, and it can wrap any SystemVerilog types. We added `RefType` in order to introduce `Mem2Reg` into `moore` to eliminate the local temporary variables. Meanwhile, we added a new op named `moore.extract_ref` which is the copy of `moore.extract` that explicitly works on the ref type. And `moore.concat_ref` is the copy of `moore.concat`. Later, we will tweak `union/struct` ops like `moore.struct_create` in order to support the `ref` type.
`moore.variable/moore.net` will return a result with `ref<T>`, it's similar to `memref.alloca`.
Change `moore::ReadLValueOp` to `moore::ReadOp`, it's similar to `memref.load`.  Initially, we need `moore.read_lvalue` only to service for assigmen operations(like …
=> [Moore] Introduce RefType and tweak the related ops.

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLTypes.td, lib/Dialect/FIRRTL/Transforms/InferResets.cpp, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/infer-resets.mlir
Simplification follows as no longer need forceable.
=> [FIRRTL] Support abstract reset in RWProbeOp

lib/Dialect/Handshake/HandshakeOps.cpp
=> [Handshake] Fix canonicalizer not going through rewriter for RAUW.

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, test/Dialect/FIRRTL/SFCTests/data-taps-flip.fir
Taps (using probes) support a non-passive source with a passive sink (by their nature), but the hidden option to avoid probes does not.
Detect this specifically and fix by using passive type for wiring from source.
This allows taps of non-ground (non-passive) that work with probes to also work with this option.
=> [FIRRTL] Emulate tap-as-passive for no-ref-ports option.

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, test/Dialect/FIRRTL/emit-metadata.mlir
Add the instance path to the DUT module to the `SiFive_Metadata` class.
This instance path is required to ensure proper hierarchy paths can be generated from the OMIR with respect to the DUT.
This commit creates a list of paths, to handle multiple DUTs even though the current designs will have a unique DUT.
=> [FIRRTL][Metadata] Add the path to the DUT, in the SiFive metadata class.

include/circt/Dialect/Moore/MooreOps.h, include/circt/Dialect/Moore/MooreOps.td, lib/Dialect/Moore/CMakeLists.txt, lib/Dialect/Moore/MooreOps.cpp, test/Dialect/Moore/mem2reg.mlir, tools/circt-opt/circt-opt.cpp, tools/circt-verilog/CMakeLists.txt, tools/circt-verilog/circt-verilog.cpp
```
module Foo;
int x, y;
int a;
a = x + 1;
y = a;
end
endmodule
```
```cpp
/home/phoenix/work/HDLBits/test01.sv:2:7: error: all variables: %0 = "moore.variable"() <{name = "x"}> : () -> !moore.i32
int x, y;
^
/home/phoenix/work/HDLBits/test01.sv:2:10: error: all variables: %1 = "moore.variable"() <{name = "y"}> : () -> !moore.i32
int x, y;
^
/home/phoenix/work/HDLBits/test01.sv:4:9: error: all variables: %2 = "moore.variable"() <{name = "a"}> : () -> !moore.i32
int a;
^
/home/phoenix/work/HDLBits/test01.sv:4:9: error: local varialbes: %2 = "moore.variable"() <{name = "a"}> : () -> !moore.i32
int a;
^
/home/phoenix/work/HDLBits/test01.sv:5:5: error: blocking assignments: %2 = "moore.variable"() <{name = "a"}> : () -> !moore.i32
a = x + 1;
^ …
```
=> [Moore] Introduce Mem2Reg to eliminate local variables

include/circt/Dialect/Moore/CMakeLists.txt, include/circt/Dialect/Moore/MoorePasses.h, include/circt/Dialect/Moore/MoorePasses.td, include/circt/InitAllPasses.h, lib/Dialect/Moore/CMakeLists.txt, lib/Dialect/Moore/Transforms/CMakeLists.txt, lib/Dialect/Moore/Transforms/PassDetail.h, lib/Dialect/Moore/Transforms/SimplifyProcedures.cpp, test/Dialect/Moore/simplify-procedures.mlir, tools/circt-opt/CMakeLists.txt
Cause we intend to entirely inline the `always_comb` body into the module body(`moore.module`). Due to the difference way between continuous and blocking assignments, we decided to create a new pass named `SimplifyProcedures` to insert a local "shadow" variable in always blocks for every module-level/global variable that the process modifies. Quote @fabianschuiki 's example:
```
module Foo;
int a;
int x, y, z;
a = 1;
x = a;
a += 1;
y = a;
a += 1;
z = a;
end
endmodule
```
```
module Foo;
int a;
int x, y, z;
int local_a = a;
local_a = 1; a = local_a;
x = local_a;
local_a += 1; a = local_a;
y = local_a;
local_a += 1; a = local_a;
z = local_a;
end
endmodule
```
=> [Moore] Add the SimplifyProcedures pass.

include/circt/Conversion/Passes.td, lib/Conversion/ExportVerilog/PrepareForEmission.cpp
ODS InterfacePass generates `canScheduleOn` method with a specified interface in a header file and currently we import every pass declaration through PassesDetail.h. Gcc/clang seem to compile when there is an unknown interface class but MSVC emits an error. So this PR avoids `InterfacePass` in ODS and manually implements `canScheduleOn` in PrepareForEmission. 
Windows CI: https://github.com/llvm/circt/actions/runs/9497120978
=> [ExportVerilog] Avoid using interface pass for PrepareForEmission, NFCI

docs/Dialects/FIRRTL/FIRRTLIntrinsics.md, include/circt/Dialect/FIRRTL/FIRRTLIntrinsics.td, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir, test/Conversion/SimToSV/dpi.mlir, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/lower-dpi.mlir, test/Dialect/FIRRTL/lower-intrinsics.mlir, test/firtool/dpi.fir
This PR modifies ExportVerilog to emit two state types (`bit` in general) for DPI import op. Furthermore, for specific bit width (8, 16, 32 and 64) it emits C-types (byte, shortint, int and longint). 
This PR also rejects small integer types other than 8, 16, 32 and 64 bit width since  otherwise we have to use`bit` but they are passed by references in DPI. So this PR defines the ABI as "small integers are passed by values, and larger integers are passed by references.
=> [FIRRTL][ExportVerilog] Emit integers on DPI function as two state C-compatible types and clarify ABI

lib/Dialect/FIRRTL/Transforms/LowerDPI.cpp
The [lower-dpi-error.mlir](https://github.com/llvm/circt/pull/7139/files#diff-b9efcb02f7785b4bd52265c695cc5f2a6b00750101ea9abcd346e8bc161cd6db) test added in #7139 crashes on my local macOS debug build. This appears to be caused by [an invalid access in the lowering loop](https://github.com/llvm/circt/pull/7139/files#diff-8897e1920c98c76b3006af5bfe97e5313243e455253463acb99ffa55b924ef96R137). The iterator stored in `inputTypes` references the operand range of the first call op. However, after calling `lowerCall(firstDPICallop);` this op has been deleted. Deferring op erasure until after the current batch of call operations has been checked and lowered has fixed the problem for me.
Close https://github.com/llvm/circt/issues/7169
=> [LowerDPI] Defer deletion of call ops to prevent inavlid access.

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h, include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp, test/Dialect/FIRRTL/check-comb-cycles.mlir
Add a new `CombDataflow` op interface to `FIRRTL`. 
This interface is used for specifying the combinational dataflow that exists
in the results and operands of an operation. Any operation that doesn't
implement this interface is assumed to have a  combinational dependence
from each operand to each result. 
Only `FIRRTL` register and memory ops implement this interface, but it can be used in other
dialects that intend to use the `CheckCombCycles` pass.
=>  [FIRRTL] Add a new op interface for combinational loop detection.

include/circt/Conversion/Passes.td, lib/Conversion/ExportVerilog/ApplyLoweringOptions.cpp
Side-step an issue that prevents transitioning the inclusion of TableGen defined passes to the new(er) style, see #7168 #3962.
Currently, in the generated constructor for `TestApplyLoweringOptionBase` the formal parameter is shadowing the `options` member. This won't compile if we try to include it:
```
TestApplyLoweringOptionBase(const TestApplyLoweringOptionOptions &options) : TestApplyLoweringOptionBase() {
options = options.options;
}
```
Arguably, this could be fixed in upstream by at least picking a less obvious formal parameter name. But I think this tiny change isn't hurting us.
=> [NFC][ExportVerilog] Rename generated `options` member.

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/CMakeLists.txt, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, lib/Conversion/ImportVerilog/Statements.cpp, lib/Conversion/ImportVerilog/TimingControls.cpp, test/Conversion/ImportVerilog/basic.sv
The `moore.wait_event`(EventOp) is aimed at handling event control, the delay control like #1ns will be implemented at another PR. And something like `@(posedge clk) a <= b + c;` will be handled by `Value visit(const slang::ast::AssignmentExpression &expr){...}`, so there are no error tests.
Thanks for the code review in advance! :smiley:
=> [Moore] Add evenOp to handle event controls.

include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, test/Dialect/FIRRTL/expand-whens.mlir
This adds `StmtExprVisitor` struct for visitor to handle operations with an optional result. Currently `GenericIntrinsicOp `and `DPICallIntrinsicOp` are added.
Besides that `ExpandWhens` is modified to handle DPI intrinsic.
=> [FIRRTL][ExpandWhens] Add StmtExprVisitor to Visitor and Support DPI intrinsic in ExpandWhens

include/circt/Conversion/Passes.td, lib/Conversion/SimToSV/SimToSV.cpp, test/Conversion/SimToSV/dpi.mlir
Previously DPICallLowering called `rewriter.replaceAllUsesWith` for individual
results but it seems that is not equivalent to `replaceOp`. 
This also adds missing dialect dependency to seq
Close #7191
=> [SimToSV] Fix DPICall lowering to use `replaceOp`

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir
This PR fixes an issue that `emitAsTwoStateType` flag was not propagated for aggregate types.
This PR also fixes a bug that ctypes (int/shortint etc) are used as an inner type of packed types (e.g. `int [2:0]` is invalid) according to SV spec 6.8.
=> [ExportVerilog] Fix two state type emission of aggregate types

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h, include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td, include/circt/Dialect/HW/HWOpInterfaces.h, include/circt/Dialect/HW/HWOpInterfaces.td, lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp
Move the `CombDataFlow` op interface from `FIRRTL` to `HW` dialect.
The op interface is better suited to reside in the `HW` dialect, along with other interfaces like the `HWModuleLike`.
This makes it more convenient for non-`FIRRTL` dialects to implement ops using this interface, without introducing a new dependence on the `FIRRTL` dialect, assuming  `HW` dependence already exists.
=> [HW] Move the CombDataFlow op interface from FIRRTL to HW

.github/workflows/garbageCollectCICache.yml, utils/delete-cache.sh
This PR adds a CI job that deletes caches created by short integrations tests. Almost 10GB is used by short integrations test and I think it's sufficient to have keep most recent ones. By doing that we should be able to keep cache for nightly-integration tests. This PR adds CI job that calls `gh cache delete $id` for results of `gh cache list -k ccache-short-clang-Release-ON-ON`.   
```bash
$ gh cache list -k ccache-short-clang-Release-ON-ON -L 50
Showing 27 of 27 caches in llvm/circt
ID     KEY                                         SIZE        CREATED               ACCESSED
66695  ccache-short-clang-Release-ON-ON-2024-0...  360.61 MiB  about 10 minutes ago  about 10 minutes ago
66694  ccache-short-clang-Release-ON-ON-2024-0...  360.33 MiB  about 15 minutes ago  about 15 minutes ago …
```
=> [CI] Add a job to remove cache created by short integrations tests

include/circt/Dialect/Moore/MoorePasses.td, lib/Dialect/Moore/Transforms/SimplifyProcedures.cpp, test/Dialect/Moore/simplify-procedures.mlir
Cause every variable/net has been used by other ops. We must first read it. For example:
```
module foo(input clk, en, cin);
reg q;
always@(posedge clk) begin
if(en) begin
q <= cin;
end
end
endmodule      
```
```
moore.module @foo(in %clk : !moore.l1, in %en : !moore.l1, in %cin : !moore.l1) {
%clk_0 = moore.net name "clk" wire : <l1>
%en_1 = moore.net name "en" wire : <l1>
%cin_2 = moore.net name "cin" wire : <l1>
%q = moore.variable : <l1>
moore.procedure always {
%0 = moore.read %clk_0 : l1
moore.wait_event posedge %0 : l1
%1 = moore.read %en_1 : l1
%2 = moore.conversion %1 : !moore.l1 -> i1
scf.if %2 {
%3 = moore.read %cin_2 : l1
moore.nonblocking_assign %q, %3 : l1
}
}
moore.assign %clk_0, %clk : l1
moore.assign %en_1, %en : l1
moore.assign %cin_2, %cin : l1
moore.output
}
``` …
=> [Moore] Fix the stacking fault caused by cast and remove unused headers

lib/Dialect/FIRRTL/Transforms/SpecializeLayers.cpp, test/Dialect/FIRRTL/specialize-layers.mlir
This pass processes all modules and layers in parallel, and since this
could result in the operation being deleted, could lead to crash when
two side-by-side ops are removed at the same time and try to modify each
other's next and previous pointers.  This changes the pass to handle the
part of the specialization which can delete the operation in serial.
=> [FIRRTL] SpecializeLayers: fix race condition

include/circt/Dialect/HW/HWTypesImpl.td, lib/Dialect/HW/HWTypes.cpp
* Port some of customAssemblyFormat to declarative assembly-format. HW uses unconventional printer so we still need to use custom directive though. 
* Use TypeBuilderWithInferredContext 
* Make banner consistent with others
=> [HW] Clean up HWTypes, NFC

README.md
The build flow which attempted to build CIRCT against LLVM head was deleted a long time ago, and our README should not be referencing it.
=> README.md: remove link to dead build

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp
This fixes a race condition was introduced for now by removing pallallesim
=> [LowerClass] Run path tracking sequentially

frontends/PyCDE/integration_test/test_software/esi_ram.py, frontends/PyCDE/integration_test/test_software/esi_test.py, integration_test/Dialect/ESI/runtime/loopback.mlir.py, lib/Dialect/ESI/runtime/cosim/CMakeLists.txt, lib/Dialect/ESI/runtime/cosim/cosim_dpi_server/DpiEntryPoints.cpp, lib/Dialect/ESI/runtime/cosim/lib/RpcServer.cpp, lib/Dialect/ESI/runtime/cpp/include/esi/Ports.h, lib/Dialect/ESI/runtime/cpp/include/esi/Services.h, lib/Dialect/ESI/runtime/cpp/lib/Accelerator.cpp, lib/Dialect/ESI/runtime/cpp/lib/Ports.cpp, lib/Dialect/ESI/runtime/cpp/lib/Services.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Trace.cpp, lib/Dialect/ESI/runtime/cpp/tools/esitester.cpp, lib/Dialect/ESI/runtime/python/esiaccel/esiCppAccel.cpp, lib/Dialect/ESI/runtime/python/esiaccel/types.py
We've switched from a polling 'pull' method to a callback-based 'push'
mechanism for read ports. Polling (via std::futures) is built on top of
the push mechanism.
The read-ordering problem has also been fixed by using std::futures
exclusively for polling schemes. They also allow for poll-wait-notify
schemes without any changes on our part.
=> [ESI Runtime] Read ports now invoke callbacks

include/circt/Dialect/FIRRTL/FIRRTLStatements.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, test/Dialect/FIRRTL/expand-whens.mlir, test/firtool/layers.fir
Behavior is same as-if the contained operations were not under a layer.
Some layer-related passes such as LayerMerge (for completeness) and LowerLayers (for correctness) now explicitly require ExpandWhen's to execute first.
The FIRRTL specification does not yet permit this.
=> [FIRRTL] Allow layers under when and match.

lib/Dialect/ESI/runtime/CMakeLists.txt, lib/Dialect/ESI/runtime/cosim/CMakeLists.txt, lib/Dialect/ESI/runtime/cosim/cosim_dpi_server/CMakeLists.txt, utils/get-grpc.sh
- Rename C++ library to ESICppRuntime.
- Create new ESIRuntime target which builds everything.
- Modify gRPC install to not include libz. (Avoids cmake warnings.)
=> [ESI Runtime] Rename cmake targets, create full build one

include/circt/Dialect/Moore/MooreTypes.td, unittests/Dialect/Moore/TypesTest.cpp
Add `getDomain()` and `getBitSize()` for `RefType`, now can directly get the domain and size of its nested type.
=> [Moore] Add extra class declaration for RefType.

lib/Conversion/ImportVerilog/Structure.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/errors.sv
Support loop generate constructs and conditional generate constructs.
Because `genvar` only exists in the declaration and the variable exists as a parameter in GenerateBlock, genvar can be skipped.
=> [ImportVerilog] Support Generate constructs

lib/Conversion/SeqToSV/CMakeLists.txt, lib/Dialect/Seq/CMakeLists.txt
Seq currently depends on SV according to CMake, which seems to be unnecessary (modulo a fix to the SVToSeq CMakeLists) and means adding certain dependencies will introduce unwanted cycles.
=> [NFC][Seq] Remove unnecessary dependency of Seq on SV

lib/Conversion/HWToBTOR2/CMakeLists.txt, lib/Dialect/SV/CMakeLists.txt, tools/om-linker/CMakeLists.txt
Same situation as #7247, SV depends on Verif but that seems to be unnecessary as long as om-linker and HWToBTOR2 CMakeLists are updated to link in Verif
=> [NFC][SV] Remove unnecessary dependency of SV on Verif

include/circt/Dialect/Moore/MoorePasses.h, include/circt/Dialect/Moore/MoorePasses.td, lib/Dialect/Moore/Transforms/CMakeLists.txt, lib/Dialect/Moore/Transforms/LowerConcatRef.cpp, lib/Dialect/Moore/Transforms/SimplifyProcedures.cpp, test/Dialect/Moore/lower-concatref.mlir, test/Dialect/Moore/simplify-procedures.mlir, tools/circt-verilog/CMakeLists.txt, tools/circt-verilog/circt-verilog.cpp
Assignments like `{a, b} = c` are very tricky to handle directly. So we introduce a new Moore-to-Moore pass called `LowerConcatRef`. Which is used to disassemble the `moore.concat_ref`. And it runs before MooreToCore and guarantees never to see `moore.concat_ref` on the LHS of an assignment. For example:
```
{a, b} = c;
// becomes
a = c[9001:42];
b = c[41:0];
```
=> [Moore] Add LowerConcatRef pass to handle concat_ref.

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes.mlir, test/firtool/classes-dedupe.fir
We already had logic to detect if the owning module was in the middle of a hierarchical path, and build up the prefix just to the owning module in this case. However, we still used the entire original hierarchical path in the new path, which caused the prefix to the owning module to be duplicated. This is fixed by not only setting the moduleName to the owning module, but also trimming the prefix to the owning module in the original path.
=> [FIRRTL] Ensure hierpath considers owning module in LowerClasses.

docs/Dialects/FIRRTL/FIRRTLIntrinsics.md, include/circt/Dialect/FIRRTL/FIRRTLIntrinsics.td, lib/Dialect/FIRRTL/FIRRTLIntrinsics.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/LowerDPI.cpp, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/lower-dpi.mlir, test/Dialect/FIRRTL/lower-intrinsics.mlir, test/firtool/dpi.fir
Fix https://github.com/llvm/circt/issues/7226. This adds support for specifying input and output names. This uses `;` separated string list following the same design as `guard` parameter of assert intrinsic.
=> [FIRRTL] Add input and output names to DPI intrinsic

lib/Dialect/ESI/runtime/CMakeLists.txt, lib/Dialect/ESI/runtime/cosim_dpi_server/CMakeLists.txt, lib/Dialect/ESI/runtime/cpp/include/esi/backends/Cosim.h, lib/Dialect/ESI/runtime/cpp/lib/Accelerator.cpp, lib/Dialect/ESI/runtime/python/esiaccel/esiCppAccel.cpp
If a backend isn't found in the registry, try to load it dynamically from some standard places. Note that if one doesn't want to keep the plugin shared lib in one of those places, one can LD_PRELOAD it.
Linux support only. Windows coming.
=> [ESI Runtime] Load backends as plugins

frontends/PyCDE/src/pycde/signals.py, frontends/PyCDE/test/test_muxing.py
Previously, PyCDE was somewhat more loose on indexes into arrays/bitvectors. Now that we have the pad_or_truncate convenience method, lets be a bit more restrictive.
=> [PyCDE] Restrict slicing index widths to clog2(len)

lib/Dialect/FIRRTL/Transforms/InferResets.cpp, test/Dialect/FIRRTL/infer-resets.mlir
As @youngar explains well, a node was being deleted when it had references.  Just route the node through the bounce wire instead of trying to replace it.
Closes #7225
=> [FIRRTL] Fix use-after-free in InferReset

include/circt/Dialect/Moore/MooreOps.td, lib/Dialect/Moore/MooreOps.cpp, test/Dialect/Moore/canonicalizers.mlir, tools/circt-verilog/circt-verilog.cpp
The canonicalization for VariableOp is aimed at merging the "easy use" of the variable and its value(continuous assignment) into a new op called `assigned_variable`. Don't handle `blocking_assign` and `nonBlocking_assign` due to the dominance. 
The "easy use" is assigning a value to a variable with the whole bit-width, in other words, exclude the bits slice, concatenation operator, etc.
=> [Moore] Add AssignedVarOp and canonicalization for VariableOp.

frontends/PyCDE/integration_test/esitester.py, frontends/PyCDE/integration_test/test_software/esi_test.py, frontends/PyCDE/src/pycde/bsp/common.py, frontends/PyCDE/src/pycde/bsp/xrt.py, frontends/PyCDE/src/pycde/esi.py, frontends/PyCDE/test/test_esi.py, frontends/PyCDE/test/test_xrt.py, lib/Dialect/ESI/ESIStdServices.cpp, lib/Dialect/ESI/Passes/ESILowerToHW.cpp, lib/Dialect/ESI/runtime/cpp/include/esi/Accelerator.h, lib/Dialect/ESI/runtime/cpp/include/esi/Services.h, lib/Dialect/ESI/runtime/cpp/lib/Services.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Xrt.cpp, test/Dialect/ESI/manifest.mlir, test/Dialect/ESI/services.mlir
Since MMIO will be used to transmit things like pointers, we should probably make it 64-bit data. This seemingly simple change had a bunch of ripple effects.
=> [ESI] Make MMIO data 64-bit

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, include/circt/Dialect/FIRRTL/FIRRTLIntrinsics.td, include/circt/Dialect/HW/HWOpInterfaces.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp, test/Dialect/FIRRTL/check-comb-loops.mlir
This PR removes default implementation of CombDataFlow which indicate an op was sequential. Also implement it for DPI intrinsic.
Close https://github.com/llvm/circt/issues/7229
=> [FIRRTL][HW] Change default implementation of CombDataFlow and add it to DPI intrinsic 

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp, test/Dialect/FIRRTL/inliner.mlir
This PR basically reverts https://github.com/llvm/circt/commit/4cf7bc9a300f9e05ddfc264e99526b4b88d5f93f to add a prefix to MemOp instances. Previously we changed to remove prefix since it broke prefixes created in PrefixModules. However https://github.com/llvm/circt/pull/4952 added `prefix` attribute to MemOp so we don't need the workaround anymore. This makes output verilog a lot more LEC friendly. I checked the PR doesn't break prefixes added by PrefixModules on internal designs.
```scala
//> using repository "sonatype-s01:snapshots"
//> using scala "2.13.12"
//> using dep "org.chipsalliance::chisel:7.0.0-M1+76-03ef61f3-SNAPSHOT"
//> using plugin "org.chipsalliance:::chisel-plugin:7.0.0-M1+76-03ef61f3-SNAPSHOT"
//> using options "-unchecked", "-deprecation", "-language:reflectiveCalls", …
```
=> [FIRRTL][ModuleInliner] Add a prefix to memory instances

include/circt/Dialect/ESI/ESIPasses.h, include/circt/Dialect/ESI/ESIPasses.td, lib/Dialect/ESI/CMakeLists.txt, lib/Dialect/ESI/Passes/ESIVerifyConnections.cpp, test/Dialect/ESI/errors.mlir
New pass to verify that channels and bundles are used the appropriate number of times. The wrap/unwrap, pack/unpack operations already have these checks, but when a channel/bundle is produced by a module (or some other op), it is not checked. A pass is the best way I could figure out how to implement the check.
Closes #7286.
=> [ESI] Add verify connections pass

include/circt/Dialect/HW/HWStructure.td, test/Conversion/HWToSV/test_trigger.mlir
Make the variadic  `inputs` argument of the `hw.triggered` operation optional in the declarative assembly format.  Without this change the generated parser fails on nullary instances due to the empty/missing type list.
=> [NFC][HW] Fix parsing of nullary `hw.triggered` ops

lib/Conversion/ImportVerilog/Expressions.cpp, test/Conversion/ImportVerilog/basic.sv
For example:
```
byte by;
logic [7:0] b;
assign by = b[7-:8];
```
Now:
```
%by = moore.variable : <i8>
%b = moore.variable : <l8>
%0 = moore.read %b : l8
%1 = moore.constant 7 : i32
%2 = moore.constant 7 : i32
%3 = moore.sub %1, %2 : i32
%4 = moore.extract %0 from %3 : l8, i32 -> l8              // low bit is "0"
%5 = moore.conversion %4 : !moore.l8 -> !moore.i8
moore.assign %by, %5 : i8
```
----
Previous:
```
%by = moore.variable : <i8>
%b = moore.variable : <l8>
%0 = moore.read %b : l8
%1 = moore.constant 7 : i32
%2 = moore.extract %0 from %1 : l8, i32 -> l8              // low bit is "7";
%3 = moore.conversion %2 : !moore.l8 -> !moore.i8
moore.assign %by, %3 : i8
```
=> [ImportVerilog] Distinguish the index up or down on the range selection.

lib/Conversion/ImportVerilog/Statements.cpp, test/Conversion/ImportVerilog/errors.sv
Because the return of `convertRvalueExpression()` can return `{}`. For example, when we handle the `x`/`z` value, it will emit an error and return `{}`, so we must estimate whether the return of `convertRvalueExpression()` is `{}`. Otherwise, it will cause a segmentation fault.
=> [ImportVerilog] Fix the segmentation fault caused by the case statement.

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp, test/Dialect/SV/hw-extract-test-code.mlir
This fixes a bug that clocked verif ops remain in designs.
=> [SV][Verif] Extract clocked verif ops in ExtractTestCode pass

frontends/PyCDE/src/pycde/esi.py, frontends/PyCDE/test/test_esi_servicegens.py, include/circt-c/Dialect/ESI.h, integration_test/Bindings/Python/dialects/esi.py, lib/Bindings/Python/ESIModule.cpp, lib/CAPI/Dialect/ESI.cpp
Call to add a record to the manifest about a particular client. Required plumbing through the record op to python.
=> [PyCDE][ESI] Manifest: add record about client

include/circt/Dialect/Verif/VerifDialect.td, include/circt/Dialect/Verif/VerifOps.h, include/circt/Dialect/Verif/VerifOps.td, lib/Dialect/Verif/CMakeLists.txt, lib/Dialect/Verif/VerifOps.cpp, test/Dialect/Verif/basic.mlir, test/Dialect/Verif/errors.mlir
This PR adds a `verif.bmc` op to encode bounded model checking problems. This op has three regions - the circuit to be checked (also necessarily containing a property to verify) and init and loop regions that allow clocks to be controlled as desired (to allow designs with multiple clocks to be checked down the line). These regions are allowed some extra state arguments, as is likely necessary for specifying clock interleavings (e.g. to say which clock's turn it is to be toggled next).
=> [Verif] Add `verif.bmc` operation

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, include/circt/Dialect/FIRRTL/FIRRTLDialect.td, include/circt/Dialect/FIRRTL/FIRRTLOps.h, lib/Dialect/FIRRTL/CMakeLists.txt, test/Dialect/FIRRTL/errors.mlir
Required for lowering inline layers to sv.ifdefs.
=> Allow firrtl hardware ops under sv.ifdef

frontends/PyCDE/integration_test/esi_test.py, frontends/PyCDE/integration_test/test_software/esi_test.py, frontends/PyCDE/src/pycde/bsp/common.py, frontends/PyCDE/src/pycde/esi.py, frontends/PyCDE/src/pycde/support.py, frontends/PyCDE/src/pycde/types.py, frontends/PyCDE/test/test_esi.py, frontends/PyCDE/test/test_xrt.py, lib/Dialect/ESI/ESIStdServices.cpp, test/Dialect/ESI/services.mlir
Implements a channel-based MMIO read service generator. Changes the offset type on the MMIO std service to `ui32` from `i32`.
=> [ESI] MMIO read service implementation in PyCDE

frontends/PyCDE/integration_test/esi_test.py, frontends/PyCDE/src/CMakeLists.txt, frontends/PyCDE/src/pycde/bsp/xrt.py, frontends/PyCDE/src/pycde/esi.py, frontends/PyCDE/src/pycde/signals.py, frontends/PyCDE/src/pycde/system.py, frontends/PyCDE/test/test_esi.py, lib/Dialect/ESI/CMakeLists.txt
Adds a channel buffer to an ESI channel. Since the channel buffer lowers to a SystemVerilog primitive, we need to copy the ESI primitives file into the output dir.
=> [ESI][PyCDE] ChannelSignal: add `buffer` method

.github/workflows/unifiedBuildTestAndInstall.yml, .github/workflows/uploadReleaseArtifacts.yml
macos-11 runners are no longer available: https://github.com/actions/runner-images?tab=readme-ov-file#available-images
According to this blog post from January, they were planned to be phased out by June 2024 (incidentally the previous firtool release was June 5th): https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available.
=> [CI] Drop macos-11 runners, use macos-12 in uploadReleaseArtifacts

include/circt/Dialect/LLHD/IR/SignalOps.td, lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir, test/Dialect/LLHD/IR/signal-errors.mlir
Lowering as the follow:
`moore.variable` ---> `llhd.sig`
`moore.read`      ---> `llhd.prb`
`moore.assign`   ---> `llhd.drv`
And I remove the trait(`ParentOneOf<["llhd::EntityOp", "llhd::ProcOp"]>`) of `LLHD_SigOp`.
=> [MooreToCore] Lower var, read, and assign into LLHD.

include/circt/InitAllPasses.h, include/circt/Tools/CMakeLists.txt, include/circt/Tools/circt-bmc/CMakeLists.txt, include/circt/Tools/circt-bmc/Passes.h, include/circt/Tools/circt-bmc/Passes.td, lib/Tools/CMakeLists.txt, lib/Tools/circt-bmc/CMakeLists.txt, lib/Tools/circt-bmc/ExternalizeRegisters.cpp, test/Tools/circt-bmc/externalise-registers.mlir, test/Tools/circt-bmc/externalize-registers-errors.mlir, test/Tools/circt-bmc/externalize-registers.mlir, tools/circt-opt/CMakeLists.txt
This PR adds a pass (pass itself written by @maerhart, I'm just PRing as part of the splitting of #7259) that extracts `seq.compreg`s within modules, and replaces them with additional inputs and outputs such that register states are fed as module outputs, then fed back in as inputs. This simplifies model checking as the state can be provided directly as an input to a function checking the design, rather than having to walk the IR to calculate the state.
=> [circt-bmc] Add ExternaliseRegisters Pass

include/circt/Dialect/Sim/SimOps.td, lib/Dialect/Sim/SimOps.cpp, test/Dialect/Sim/format-strings.mlir, test/Dialect/Sim/sim-errors.mlir
Provide an interface to get the flat format string for `sim.fmt.concat` operations and opportunistically flatten during canonicalization.
CC #7292
=> [Sim] Flatten format string concatenations in canonicalizer

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp
This was originally added to avoid a use-after-free. However, it got removed as part of f4920aa. It seems this is still required, even when we process PathTrackers sequentially. I confirmed there was a use-after-free without this change, which is fixed after adding this back.
Closes https://github.com/llvm/circt/issues/7327.
=> Reland "[FIRRTL][LowerClass] Pre-allocate namespaces before capturing refs (#7102)".

frontends/PyCDE/src/pycde/signals.py, frontends/PyCDE/test/test_esi.py
Add 'transform' method to ChannelSignals to enable simple data manipulations without worrying about signaling.
=> [PyCDE] Simple transforms on channels

frontends/PyCDE/src/pycde/signals.py, frontends/PyCDE/src/pycde/types.py, frontends/PyCDE/test/test_esi.py, frontends/PyCDE/test/test_esi_errors.py
Coerce a two-channel, bidirectional bundle to a different two-channel, bidirectional bundle type. Transform functions can be provided to transform the individual channels for situations where the types do not match.
=> [PyCDE] Bundles: coerce method

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir, test/Conversion/SimToSV/dpi.mlir, test/firtool/dpi.fir
This commit adds "context" property to DPI import statements to enable us to call exported functions from DPI functions. Ideally it's better to create an attribute to specify the property "context" or "pure" but "context" by default should be ok for now.
=> [ExportVerilog] Add "context" to imported DPI functions

lib/Conversion/ImportVerilog/Expressions.cpp, test/Conversion/ImportVerilog/basic.sv
Fix an issue where ImportVerilog would currently crash if an unbased, unsized literal like `'0` is used to initialize or assign to a packed struct. Instead, the integer literal should be constructed and then converted to the packed aggregate type. In a later pass, this conversion can be lowered to a more careful `moore.struct_create`.
=> [ImportVerilog] Fix unbased unsized literals of packed aggregate type

lib/Conversion/ImportVerilog/ImportVerilogInternals.h, lib/Conversion/ImportVerilog/Structure.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/errors.sv
Add handling for package definitions and accept empty packages for the time being. Later on we'll want to support parameters, variables, functions, and other things that can appear in packages. These require a mechanism to refer to things outside of an `SVModuleOp` though, which does not yet exist.
=> [ImportVerilog] Accept empty packages

include/circt/Dialect/HW/HWTypes.td, include/circt/Dialect/HW/HWTypesImpl.td, include/circt/Dialect/SV/SVExpressions.td, include/circt/Dialect/SV/SVVisitors.h, lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir
This commit adds unpacked array create op that will be lowered into array literal
`'{..}`.
Since array literal must be used in assignment-like context,`unpacked_array_create` is always spilled to a temporary wire.
The operand ordering follows HW array representation. This is currently tricky since we emit unpacked types slightly differently (`downTo`) but the correct ordering is emitted in ExportVeriliog.
=> [SV] Add UnpackedArrayCreateOp

lib/Conversion/ImportVerilog/Expressions.cpp, test/Conversion/ImportVerilog/basic.sv
Handle calls to the `$signed` and `$unsigned` system tasks by simply passing through the argument. The casting is handled by Slang during type checking and is materialized as a type conversion node in the AST. The call itself has no function after that.
The `visitCall` function is going to be the place to add handling for other system calls in the future. IEEE 1800-2017 section 20 defines a fairly substantial list of builtin system tasks. Most of these will want to have a dedicated `moore.builtin.*` op in the future.
=> [ImportVerilog] Handle $signed/$unsigned system tasks

lib/Dialect/FIRRTL/Export/FIREmitter.cpp, lib/Dialect/FIRRTL/Import/FIRLexer.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Import/FIRTokenKinds.def, test/Dialect/FIRRTL/SFCTests/dedup.fir, test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir, test/firtool/annotation-openaggs-error.fir, test/firtool/annotation-openaggs.fir, test/firtool/import-ref.fir, test/firtool/lower-layers2.fir, test/firtool/phase-ordering.fir
Due to historical circumstances, the SFC parser for FIRRTL treated commas (`,`) as whitespace. This behavior was carried over into the CIRCT implementation of `firtool`.
This behavior is utterly bizarre. 
Moreover, the FIRRTL spec has indicated comma tokens (`,`) for at least every version since last year. 
This PR removes this quirk and properly tokenizes commas, requiring them in the places dictated by the FIRRTL spec.
The impact of this PR should be low, but it may break code (in CIRCT, in Chisel, and elsewhere) in places where FIRRTL was being emitted with a loose interpretation, or where the spec was ambiguous.
Changes:
* Update several tests which were leaning into the "commas-are-whitespace" behavior.
* Removed `','` from the list of "horizontal whitespace" and added an explicit …
=> [FIRRTL][FIRParser] Tokenize Commas

lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/ImportVerilog.cpp, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, lib/Conversion/ImportVerilog/Structure.cpp, test/Conversion/ImportVerilog/basic.sv
Add support for enum variants in expressions. Until now, ImportVerilog would emit a "unknown name" diagnostic when an enum variant is used in an expression. This is due to the lowering of named value expressions simply checking whether an MLIR value is present in the `valueSymbols` table for the referenced symbol name. This works for variables which create dedicated declarations, but not for enum variants which potentially live outside the current module's scope.
Instead, ImportVerilog will now check if the named value is a constant, for example a parameter or an enum variant, and materialize that constant directly as a `moore.constant` op. This will also be able to deal with parameters declared inside of packages, for which the table of value symbols of the current module does not …
=> [ImportVerilog] Allow enum variants in expressions

lib/Dialect/FIRRTL/Transforms/AssignOutputDirs.cpp, test/Dialect/FIRRTL/assign-output-dirs.mlir
When making a directory absolute, the remove_dots helper canonicalizes away any trailing slash. Add the slash back on, which ensures that we interpret the path as a directory correctly.
This fixes a bug where a path, when LCA'd with itself, drops the last segment.
An example of the problem: given a path foo/bar/, if we (accidentally) drop the trailing slash, foo/bar is interpreted as a file called bar in a directory called foo. When we LCA foo/bar with itself, the common parent directory is determined to be foo/. By retaining the trailing slash, we can ensure that the correct LCA path foo/bar/ is computed.
Fixes: #7347
=> [FIRRTL] AssignOutputDirs: Ensure absolute dirs end with trailing slash

lib/Dialect/ESI/runtime/CMakeLists.txt
Avoids having to use vcpkg on Windows for non-cosim builds.
=> [ESI Runtime] If zlib not found, use FetchContent

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
In LowerToHW we copy the name from FIRRTL ops to the lowered HW ops.  We often call `createOrFold` when creating the HW ops, which can mean that there is no operation to copy the name to.  We were not properly detecting this scenario, which could cause us to try to copy the name to a null operation.  Most ops were already covered under a guard in a generic code path, but div-like and subaccess-like operations needed to be guarded.  Some of these problem are impossible to test right now as we require folders to be implemented for some operations.
=> [FIRRTL] LowerToHW: guard against folded operations

test/firtool/specialize-layers-1.fir
Existing test passsed with or without specialization.
Check disable and enable.
=> [firtool][test] Check layer specialization options work.

lib/Conversion/ImportVerilog/CMakeLists.txt, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/ImportVerilog.cpp, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, lib/Conversion/ImportVerilog/Statements.cpp, lib/Conversion/ImportVerilog/Structure.cpp, test/Conversion/ImportVerilog/basic.sv
Add basic support for function definitions and calls to such functions.
Input function arguments are currently passed into the function by value, while output, inout, ref, and const ref arguments are passed by reference at the moment. Later on we may want to be more faithful to the SV spec and make output and inout arguments also pass by value.
Calls to void functions are slightly strange in that they don't really have a result value, but the `convertExpression` function really wants a valid `Value` to return. To work around this, these calls generate an additional `!moore.void` value using `unrealized_conversion_cast`, which gets deleted again by the statement conversion code.
=> [ImportVerilog] Add basic function support

include/circt/Dialect/FIRRTL/FIRRTLStatements.td, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/canonicalization.mlir, test/Dialect/FIRRTL/check-comb-loops.mlir, test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/expand-whens.mlir, test/Dialect/FIRRTL/lower-types.mlir, test/Dialect/FIRRTL/lowerXMR.mlir, test/Dialect/FIRRTL/parse-basic.fir
With addition of probe colors, no longer can infer the rwprobe type so make it explicit and update tests and verify accordingly.
Fixes #7370.
=> [FIRRTL] Support layer-colored probes in force, force_initial.

lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/ExportVerilog/PrepareForEmission.cpp, lib/Dialect/SV/Transforms/PrettifyVerilog.cpp, test/Conversion/ExportVerilog/sv-always-wire.mlir, test/Conversion/ExportVerilog/verif.mlir
This follows up https://github.com/llvm/circt/pull/7302 regarding wire spilling for disable conditions. This PR changes to spill wires wires only when allowExprInEventControl is false. Also it changes not to produce unnecessary temporary wires, for example when `disable` is a port.
=> [PrepareForEmission][Prettify] Extend allowExprInClock to handle new verif ops

.github/workflows/buildAndTest.yml
Correctly detect that clang-tidy found problems, by looking at its status-code, not whether it produced any fixups.
=> [CI] Report failure of clang-tidy

lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/Structure.cpp
Avoid accessing an erased operation in ImportVerilog. Also removed an unused `getInputMutable`.
Note that I don't really know what is happening here. I cannot judge how safe this erasure is. E.g., can we guarantee that `refOp` is not still in use somewhere else?
=> [ImportVerilog] Fix use after free

lib/Transforms/StripDebugInfoWithPred.cpp, test/Transforms/strip-debuginfo-pred.mlir
This PR changes to use a different `FusedLoc::get` to avoid a bug https://github.com/llvm/llvm-project/issues/99626.
=> [StringDebugInfoPred] Workaround FusedLoc bytecode issue

include/circt/Dialect/Seq/SeqAttributes.td, test/Dialect/Seq/clock-type.mlir
The 3rd argument of `EnumAttr` is used as an attribute mnemonic so it must not contain a whitespace.
Close https://github.com/llvm/circt/issues/7376.
=> [Seq] Fix ClockConstAttr definition to pass roundstrip test

frontends/PyCDE/src/pycde/signals.py, frontends/PyCDE/src/pycde/types.py, frontends/PyCDE/test/test_esi.py, include/circt-c/Dialect/ESI.h, include/circt/Dialect/ESI/ESIChannels.td, lib/Bindings/Python/ESIModule.cpp, lib/Bindings/Python/dialects/esi.py, lib/CAPI/Dialect/ESI.cpp, lib/Dialect/ESI/ESIOps.cpp, lib/Dialect/ESI/Passes/ESILowerPorts.cpp, test/Dialect/ESI/connectivity.mlir, test/Dialect/ESI/lowering.mlir
The control signaling is (for valid/ready and FIFO) orthogonal to the number of cycles data is delayed. Separate it out.
=> [ESI] Separate data delay from signaling standard

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/Structure.cpp, lib/Conversion/MooreToCore/MooreToCore.cpp, lib/Dialect/Moore/Transforms/LowerConcatRef.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/MooreToCore/basic.mlir, test/Dialect/Moore/basic.mlir, test/Dialect/Moore/lower-concatref.mlir
We divide the extract into a dynamic named `moore.dyn_extract` and a constant extract named `moore.extract`, the former has a variable as its low bit like `arr[x]`, but the latter has a constant value as its low bit like `arr[1]`.
=> [Moore] Distinguish the dynamic and constant extract.

lib/Conversion/ImportVerilog/Expressions.cpp, test/Conversion/ImportVerilog/basic.sv
Remove the 64 bit limitation on SV integer constants and allow for arbitrary Slang `SVInt`s to be converted to MLIR `APInt`s.
=> [ImportVerilog] Support large integer constants

lib/Conversion/ImportVerilog/Statements.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/errors.sv
Add support for variables declared inside the for loop initializer, such as `for (int x = 0; ...)`. This is pretty straightforward, since Slang already creates corresponding variable declaration AST nodes in the surrounding scope. The only change needed is removing an error diagnostic.
=> [ImportVerilog] Support for loop variables

test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/parse-basic.fir
Minor tweaks to the FIRRTL/IR so that it's legal
enough to survive `--parse-only`.
"OMDeleted" -> "OMDeleted:"
Fixup intrinsic signature.
=> [FIRRTL] Touchup {parse,emit}-basic.fir for `--parse-only`.

lib/Conversion/ExportVerilog/PrepareForEmission.cpp, test/Conversion/ExportVerilog/disallow-local-vars.mlir
Fix https://github.com/llvm/circt/issues/7399
=> [PrepareForEmission] Hoist registers in a procedural region with `disallowLocalVariables`

include/circt/Dialect/SSP/Utilities.h, include/circt/Scheduling/Problems.h, lib/Analysis/SchedulingAnalysis.cpp, lib/Conversion/AffineToLoopSchedule/AffineToLoopSchedule.cpp, lib/Dialect/Pipeline/Transforms/ScheduleLinearPipeline.cpp
Removes the `DEFINE_COMMON_MEMBERS` macro from the definitions of the built-in scheduling problems to address #6517. Inheriting the base class' constructors keeps the boilerplate code small, but unfortunately I still have to declare the default constructor as protected in each class in order to prevent user code from creating problem instances without the `containingOp`.
A useful side-effect of exposing the constructor is that is now possible to create problem instances on the heap.
=> [Scheduling] Replace macro use in problem definitions

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/Types.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/types.sv
Support for String Types, String Literals.
=> [ImportVerilog] Support for String Types, String Literals

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_controlflow.mlir
This  PR tries to add support for `scf.if` during lowering to Calyx, as mentioned in [this issue](https://github.com/llvm/circt/issues/4843) #4843 
Currently this PR is still in early stages and contains some issues, but I believe that some guidance would help ensure I'm on the right track!
To add support for `scf.if`, I think we need:
- The structure for `if` op lowering;
- Basic block analysis fir Then/Else region;
- Proper handling block arguments and yield values
- I'm not sure if my overall approach is on the right track in general, I'd appreciate any insights or suggestions!
- I'm trying to debug/step in the code I'm writing but somehow this newly created `goupOp` is empty and only has `void` in the body, as [in this line](https://github.com/jiahanxie353/circt/blob/c8ff29c4305e2b62ef …
=> Support `scf.if` Op Lowering to Calyx

lib/Bindings/Python/OMModule.cpp, lib/Bindings/Python/dialects/om.py
Internally, primitive OM EvaluatorValues are represented as TypedAttributes. This is great internally, but when we pass these from C++ out to Python, we have to use a very inefficient method to pull the Python value out of the attribute.
This updates how primitives are handled at the Python <> C++ interface to directly construct the appropriate Python values and return them. Similarly, for top-level inputs to the Evaluator, Python values are directly accepted and converted to Attributes internally.
On large designs, this was shown to decrease single threaded CPU time to process large amounts of OM data by roughly 70%. There is no difference in the output.
=> [OM] Pass Python values back and forth, not Attributes.

docs/Dialects/Seq/RationaleSeq.md
These docs give an example of a SV lowering of a firreg without a reset, but then the SV snippet has a reset in it, which is a bit confusing.
=> [docs] Remove confusing reset in Seq docs SV example

lib/Dialect/FIRRTL/Transforms/Dedup.cpp, test/Dialect/FIRRTL/dedup-errors.mlir
Primary change is to only generate and populate mappings for sources of values, and not each value themselves.
Values are identified using these base numberings plus an appropriate offset.
The main benefit of this is to greatly reduce the number of entries in the `indices` map.
When handling operations with many block arguments (module-like's with many ports) or with many results (instances of those module-like's) this greatly reduces the pressure on the `indices` map.  For these designs, dedup now runs dramatically faster and uses significantly less memory.
Also separates location of the value impl, such that if a Value's impl is storage inline into an Operation or Block such that there is aliasing, the two are given different numbers (and especially the numbering isn't changed).
On a …
=> [FIRRTL][Dedup] Rework hashing for perf and bug fixes.

include/circt/Dialect/Moore/MooreOps.td, include/circt/Dialect/Moore/MooreTypes.td, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Dialect/Moore/MooreOps.cpp, test/Conversion/ImportVerilog/basic.sv, test/Dialect/Moore/basic.mlir
Add support for assignment patterns like `'{42, 9001}` in rvalue position. These are roughly SystemVerilog's equivalent of `struct_create` and `array_create`. This commit also adds an `array_create` op to support assignment patterns for arrays.
=> [ImportVerilog] Add rvalue assignment pattern support

lib/Bindings/Python/OMModule.cpp
Add a missing conversion for OM to Python conversion where only OM integers and not arbitrary MLIR integers would be converted to Python. This could result in failures in Python scripts that needed to consume OM.
This fixes a bug introduced in: 17c036f87c4c9e103160b207e18ad595911945e8
=> [OM] Add IntegerAttr -> Python int conversion

include/circt/Support/FVInt.h, lib/Support/CMakeLists.txt, lib/Support/FVInt.cpp, unittests/Support/CMakeLists.txt, unittests/Support/FVIntTest.cpp
Add the `FVInt` class to CIRCT's support library. This class can represent arbitrary precision integers where each bit can be one of the four values 0, 1, X, and Z. The name intends to suggest a *four-valued APInt*, with the option to also introduce a *nine-valued NVInt* in the future.
Internally, `FVInt` uses two `APInt`s to store its data: `value` stores whether a bit is 0/X or 1/Z, and `unknown` stores whether a bit is known (0 or 1) or unknown (X or Z). Together they allocate 2 bits of storage for each of the `FVInt`'s digits, which allows for four different values per digit. This representation as `value` and `unknown` makes many of the logical and arithmetic operations pretty straightforward to implement. Most four-valued operations can be trivially implemented by performing the …
=> [Support] Add FVInt, a four-valued arbitrary precision integer

integration_test/Bindings/Python/dialects/om.py, lib/Bindings/Python/OMModule.cpp
Add integration test for bool constants that fails without this change.
=> [Python][OM] Handle BoolAttr's before IntegerAttr's.

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/ImportVerilog.cpp, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, lib/Conversion/ImportVerilog/Statements.cpp, lib/Conversion/ImportVerilog/Structure.cpp, lib/Dialect/Moore/Transforms/SimplifyProcedures.cpp, test/Conversion/ImportVerilog/basic.sv, test/Dialect/Moore/basic.mlir, test/Dialect/Moore/lower-concatref.mlir, test/Dialect/Moore/mem2reg.mlir, test/Dialect/Moore/simplify-procedures.mlir
Instead of using the SCF dialect and its `scf.if` and `scf.while` operations for control flow, switch over to the CF dialect and its `cf.br` and `cf.cond_br`. This allows us to support SystemVerilog's `continue`, `break`, and `return` statements which don't map well to the Structured Control Flow dialect.
=> [ImportVerilog] Switch from SCF to CF dialect for control flow

lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/annotations-errors.mlir, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/lower-classes.mlir, test/Dialect/FIRRTL/lower-intmodules.mlir, test/Dialect/FIRRTL/lower-intrinsics-errors.mlir
Add tests for new errors and existing error (changed).
Op errors should remember to make sense when read prefixed with "mydialect.opname op ".
=> [FIRRTL] Verify main module is a module, and is public.

lib/Dialect/Ibis/Transforms/IbisContainersToHW.cpp, test/Dialect/Ibis/Transforms/containers_to_hw.mlir
The ibis.design op will be removed after the IbisContainersToHW pass, and there may be ibis.component's inside the design that have the same name as the design; we want that name to persist, and not be falsely considered a duplicate.
=> [Ibis] Don't include design name in namespace in IbisContainersToHW

lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/layers.mlir
RWProbe conservatively means a write to the target, so check that the target is indeed writeable from where the rwprobe is.
=> [FIRRTL] Verify RWProbeOp target has layer requirements.

include/circt/Dialect/FIRRTL/FIRRTLStructure.td
Before:
```mlir
firrtl.layer @A  inline
```
After:
```mlir
firrtl.layer @A inline
```
=> [FIRRTL] Tweak printing of layers to avoid extra space.

include/circt/Firtool/Firtool.h, lib/Firtool/Firtool.cpp
**Renamed and replaced shouldReplicateSequentialMemories to shouldReplaceSequentialMemories per issue #7384**
**MLIR Tests**:
[0/1] Running the MLIR regression tests
Testing Time: 53.62s
Total Discovered Tests: 2877
Unsupported      :  506 (17.59%)
Passed           : 2370 (82.38%)
Expectedly Failed:    1 (0.03%)
**CIRCT Tests**:
[0/1] Running the CIRCT regression tests
Testing Time: 12.50s
Total Discovered Tests: 824
Unsupported      :  21 (2.55%)
Passed           : 797 (96.72%)
Expectedly Failed:   6 (0.73%)
**CIRCT integration tests**:
[1/2] Running the CIRCT integration tests
Testing Time: 15.29s
Total Discovered Tests: 98
Unsupported      : 63 (64.29%)
Passed           : 34 (34.69%)
Expectedly Failed:  1 (1.02%)
=> Replaced 'replicate' to correctly named 'replace' flags

lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp
Precompute a symbol table inside LowerLayers in order to do SymbolRefAttr -> LayerOp lookups.  This is expected to fix an intermittent crash as well as improve performance.
Fixes #7434.
h/t @youngar for the fix suggestion.
=> [FIRRTL] Cache symbol table in LowerLayers

docs/VerilogGeneration.md, include/circt/Support/LoweringOptions.h, lib/Conversion/ExportVerilog/PrepareForEmission.cpp, lib/Support/LoweringOptions.cpp, test/Conversion/ExportVerilog/fixup-empty-modules.mlir
This commit adds a new lowering option to sanitize empty modules by creating a dummy wire in it.
=> [ExportVerilog] Add a lowering option to fix up empty modules

lib/Conversion/SimToSV/SimToSV.cpp, test/Conversion/SimToSV/dpi.mlir, test/firtool/dpi.fir
This adds include guards `__CIRCT_DPI_IMPORT_*` to DPI import statements generated in SimToSV. 
Fix https://github.com/llvm/circt/issues/7458.
=> [SimToSV] Add include guards to DPI import

integration_test/Dialect/ESI/runtime/loopback.mlir.py, lib/Dialect/ESI/runtime/cpp/include/esi/Accelerator.h, lib/Dialect/ESI/runtime/cpp/include/esi/Design.h, lib/Dialect/ESI/runtime/cpp/include/esi/Manifest.h, lib/Dialect/ESI/runtime/cpp/include/esi/Ports.h, lib/Dialect/ESI/runtime/cpp/include/esi/backends/Trace.h, lib/Dialect/ESI/runtime/cpp/include/esi/backends/Xrt.h, lib/Dialect/ESI/runtime/cpp/lib/Accelerator.cpp, lib/Dialect/ESI/runtime/cpp/lib/Design.cpp, lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp, lib/Dialect/ESI/runtime/cpp/lib/Ports.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Trace.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Xrt.cpp, lib/Dialect/ESI/runtime/cpp/tools/esiquery.cpp, lib/Dialect/ESI/runtime/cpp/tools/esitester.cpp, lib/Dialect/ESI/runtime/python/esiaccel/esiCppAccel.cpp
Add a poll method to ports, a master poll method to the Accelerator, and the ability to poll from the service thread. Also, only spin up the service thread if it's requested.
The service thread polling (in particular) required some ownership changes: Accelerator objects now belong to the AcceleratorConnection so that the ports aren't destructed before the service thread gets shutdown (which causes an invalid memory access). This particular binding isn't ideal, is brittle, and will be an issue for anything doing the polling. Resolving #7457 should mitigate this issue.
Backends are now _required_ to call `disconnect` in their destructor.
=> [ESI][Runtime] Poll method and optional service thread polling

include/circt/Dialect/Moore/CMakeLists.txt, include/circt/Dialect/Moore/Moore.td, include/circt/Dialect/Moore/MooreAttributes.h, include/circt/Dialect/Moore/MooreAttributes.td, include/circt/Dialect/Moore/MooreDialect.td, include/circt/Support/FVInt.h, lib/Dialect/Moore/CMakeLists.txt, lib/Dialect/Moore/MooreAttributes.cpp, lib/Dialect/Moore/MooreDialect.cpp, lib/Support/FVInt.cpp, test/Dialect/Moore/attrs-error.mlir, test/Dialect/Moore/attrs.mlir
Add the `FVIntegerAttr`, an attribute containing an `FVInt` value. This allows four-valued integer constants to be used as attributes on operations and for constant folding to occur on such values. In contrast to the builtin `IntegerAttr`, `FVIntegerAttr` does not have a type yet. The type can be added later as soon as we have a concrete use case.
I expect us to eventually move `FVIntegerAttr` into the HW dialect once we are happy with its design. Other parts of CIRCT will eventually want to reason about four-valued integers as well.
The parsing and printing of the attribute tries to make the `FVInt` read like a plain old `APInt` when there are no X or Z bits present. Otherwise it falls back to printing as hexadecimal or binary number. To distinguish the different representations and to …
=> [Moore] Add FVIntegerAttr

include/circt/Dialect/Moore/MooreAttributes.td, include/circt/Dialect/Moore/MooreOps.h, include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/MooreToCore/MooreToCore.cpp, lib/Dialect/Moore/MooreOps.cpp, lib/Support/FVInt.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/errors.sv, test/Conversion/MooreToCore/basic.mlir, test/Dialect/Moore/attrs-error.mlir, test/Dialect/Moore/attrs.mlir, test/Dialect/Moore/basic.mlir, test/Dialect/Moore/errors.mlir
Extend Moore's `ConstantOp` to use the new `FVIntegerAttr`, which now allows us to materialize four-valued integer constants in the IR. Also adjust ImportVerilog to finally properly captured integer literals with X and Z bits.
With this change, `circt-verilog` is now capable of fully parsing the Snitch RISC-V core used as a benchmark in the original LLHD paper at PLDI 2020, and to produce a corresponding blob of IR.
Examples of the extended op:
moore.constant 0 : i32
moore.constant 2 : i2
moore.constant -2 : i2
moore.constant h123456789ABCDEF0 : i64
moore.constant h123456789ABCDEF0XZ : l72
moore.constant b1010 : i8
moore.constant b1010XZ : l8
=> [Moore] Support four-valued integers in ConstantOp

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
Don't always zext to size_t.
Use smaller integer sizes for ValueId and add to hash together.
Small performance win.
=> [FIRRTL][Dedup] Reduce size of integer data hashed.

lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp
Broken off from #7369 .
Only functional change is w.r.t. a hypothetical FModuleLike that isn't supported in the `TypeSwitch` would now produce a diagnostic instead of an assert or skip.
=> [FIRRTL][LowerLayers] Plumb support for errors.

lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
The lowering pattern of these two operations crashed when used on aggregate types. This PR adds type conversions for array and struct types and fixes the two lowering patterns by adding support for these types
=> [MooreToCore] Fix conversion and dyn_extract operation lowering

docs/Dialects/FIRRTL/FIRRTLAnnotations.md, include/circt/Dialect/FIRRTL/AnnotationDetails.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/InferResets.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, lib/Dialect/FIRRTL/Transforms/SFCCompat.cpp, test/Dialect/FIRRTL/annotations.mlir, test/Dialect/FIRRTL/infer-resets-errors.mlir, test/Dialect/FIRRTL/infer-resets.mlir, test/firtool/async-reset-anno.fir, test/firtool/async-reset.fir
The FullAsyncResetAnnotation is deprecated and replaced by FullResetAnnotation which includes a resetType argument that must be 'sync' or 'async'.  IgnoreFullAsyncResetAnnotation is deprecated and replaced by ExcludeFromFullResetAnnotation. The new annotations are in package circt.
The behavior of FullResetAnnotation with resetType = 'async' is identical to that of the old FullAsyncResetAnnotation. The behavior of FullResetAnnotation with resetType = 'sync' is very similar, except the type of the reset wired through will be UInt<1>, and any registers with an existing reset at all (both sync or async) will be left unchanged (resetType = 'async' will add async resets to registers with existing sync resets).
=> [FIRRTL][InferResets] Generalize FART to support sync reset

include/circt/Conversion/Passes.td, lib/Conversion/MooreToCore/CMakeLists.txt, lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
* Add a first lowering of ProcedureOp and EventOp
* Add support for blocking and non-blocking assigns
* Convert RefType to hw::InOutType instead of just the element type
@hailongSun2000 @fabianschuiki Would it make sense to take the `moore.ref` value as operand for the EventOp directly instead of the read value?
=> [MooreToCore] Support ProcedureOp and sequential assign operations

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
This adds a canonicalization to optimize multibit_mux whose index has narrow width. Close https://github.com/llvm/circt/issues/7361
=> [FIRRTL] Canonicalize multibit_mux with narrow index

lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/layers.mlir
Fix issues with verification of subfield, subindex, and subaccess
operations which appear in a layer block.  These operations are allowed to
occur in a layer block even if they capture non-passive operands.
This requires reworking layer block verification to no longer check for
operations using non-passive operands.  The spec requires that no
operation in a layer block _drives_ a value declared outside the layer
block.  However, this is exceedingly difficult to verify due to the fact
that non-passive destinations in ConnectLike operations can be
source-to-destination, destination-to-source, or bi-directional.  If the
verifier sees this, just allow it.  The FIRRTL pass pipeline will later
canonicalize away flips (i.e., make all types passive) which will then
allow the verifier to check …
=> [FIRRTL] Fix sub-* op in layer block verifier

include/circt-c/Dialect/OM.h, integration_test/Bindings/Python/dialects/om.py, lib/Bindings/Python/OMModule.cpp, lib/Bindings/Python/dialects/om.py, lib/CAPI/Dialect/OM.cpp
We want to expose this type through the Python bindings for isinstance queries, etc., so add the necessary boilerplate.
=> [OM] Add AnyType C API and Python bindings.

include/circt-c/Dialect/OM.h, integration_test/Bindings/Python/dialects/om.py, lib/Bindings/Python/OMModule.cpp, lib/Bindings/Python/dialects/om.py, lib/CAPI/Dialect/OM.cpp
We want to expose this type through the Python bindings for isinstance queries, etc., so add the necessary boilerplate.
=> [OM] Add ListType C API and Python bindings.

docs/Dialects/HWArith/RationaleHWArith.md, include/circt/Dialect/HWArith/HWArithOps.td, test/Conversion/HWArithToHW/test_basic.mlir, test/Dialect/HWArith/basic.mlir
As discussed in #7406. Resolves #7406.
=> [HWArith] Make `hwarith.icmp` result an `i1`

include/circt/Dialect/Moore/MooreOps.td, lib/Dialect/Moore/MooreOps.cpp, test/Dialect/Moore/canonicalizers.mlir
Change the `AssignedVariableOp` to directly return type `T` instead of the `ref<T>`. This removes the implied allocation and assignment, and makes this op behave essentially like `hw.wire`.
The canonicalizers for `VariableOp` and `NetOp` can now replace all reads from the old variable or net with the value of `AssignedVariableOp` directly, since there is no more `ref<T>` type involved. This also allows us to fully eliminate unnamed variables and nets that have a unique continuous assignment.
Also add canonicalizers that remove `AssignedVariableOp` if they shadow an input or output port of the same name, or if there are multiple such variables with the same name in a chain.
At a later stage we may want to replace `AssignedVariableOp` entirely with `dbg.variable`.
=> [Moore] Add more AssignedVariableOp canonicalizations

include/circt/Dialect/Moore/MooreDialect.td, include/circt/Dialect/Moore/MooreOps.td, lib/Dialect/Moore/MooreDialect.cpp, lib/Dialect/Moore/MooreOps.cpp, test/Conversion/MooreToCore/basic.mlir, test/Dialect/Moore/canonicalizers.mlir
Implement the `materializeConstant` function for the Moore dialect and mark the `ConstantOp` as a `ConstantLike` operation. This now allows us to write constant folders for various operations. As a first example, add a constant folder for `ConversionOp` that directly applies domain conversions (e.g., `i42` to `l42` or vice versa) to constants.
=> [Moore] Add constant materialization, fold constant conversions
