llvm/circt

lib/Dialect/FIRRTL/LowerToRTL.cpp
test/firrtl/lower-to-rtl.mlir
test/rtl/basic.mlir

Implement lowerings from various FIRRTL nodes to rtl.concat

---

include/circt/Dialect/RTL/Combinatorial.td
include/circt/Dialect/RTL/Visitors.h
lib/EmitVerilog/EmitVerilog.cpp
test/rtl/basic.mlir

initial implemtation of rtl::{andr,orr,xorr} operations

---

include/circt/Dialect/FIRRTL/Types.h

This fixes issues with Variadic operations and ODS type constraints.

[llvm] Update version to get 6b9a7062

---

include/circt/Dialect/RTL/Combinatorial.td
lib/Dialect/FIRRTL/LowerToRTL.cpp

made rtl/add variadic; final part of #10

made rtl/add variadic; final part of #10

---

include/circt/Dialect/RTL/Combinatorial.td
lib/EmitVerilog/EmitVerilog.cpp
test/EmitVerilog/verilog-rtl-dialect.mlir
test/rtl/bitwise.mlir

* made `mul` variadic
* added test
* removed unnecessary parenthesis around variadic Verilog emitter

fixes #10; made mul variadic

---

include/circt/Dialect/RTL/Combinatorial.td
lib/Dialect/RTL/Ops.cpp
test/rtl/canonicalization.mlir

RTL variadic folds

---

include/circt/Dialect/LLHD/IR/ArithmeticOps.td
include/circt/Dialect/LLHD/IR/BitwiseOps.td
include/circt/Dialect/LLHD/IR/ExtractOps.td
include/circt/Dialect/LLHD/IR/InsertOps.td
include/circt/Dialect/LLHD/IR/LLHD.td
include/circt/Dialect/LLHD/IR/MemoryOps.td
include/circt/Dialect/LLHD/IR/ValueOps.td
lib/Dialect/LLHD/IR/LLHDOps.cpp
test/Dialect/LLHD/IR/arithmetic.mlir
test/Dialect/LLHD/IR/array.mlir
test/Dialect/LLHD/IR/bitwise.mlir
test/Dialect/LLHD/IR/extract.mlir
test/Dialect/LLHD/IR/insert.mlir
test/Dialect/LLHD/IR/memory.mlir
test/Dialect/LLHD/IR/signal.mlir
test/Dialect/LLHD/IR/tuple.mlir

Finalize replacement of vectors with LLHD array type started in an earlier PR.

[LLHD] Replace vectors with LLHD array type

---

README.md
docs/circt-logo.svg

Added CIRCT logo in SVG and embedded it into README.md

added circt logo

---

test/rtl/basic.mlir
test/rtl/bitwise.mlir
test/rtl/canonicalization.mlir

This fixes pattern matching issues from #59

[RTL] Fix RTL test pattern matching

---

.github/workflows/buildAndTest.yml

We've made some changes to v2 in the past to make it faster than v1, so this should make things faster.

Update actions/cache to v2

---

lib/Conversion/StandardToHandshake/StandardToHandshake.cpp

This PR replaces the usage of `dyn_cast` for type comparison with `isa`.

[StandardToHandshake] Use isa instead of dyn_cast for conditions

---

lib/Dialect/RTL/Ops.cpp
test/rtl/canonicalization.mlir

Remove `(` , `)` around zero this is simply returning zero.

[rtl] [Obvious] Fix comment.

---

lib/Dialect/RTL/Ops.cpp
test/rtl/canonicalization.mlir

This should finish off the constant folding cases.

[RTL] Add `xor`, `or`, `add`, `mul` constant folding.

---

lib/Conversion/HandshakeToFIRRTL/CMakeLists.txt
lib/Conversion/StandardToHandshake/CMakeLists.txt
lib/Conversion/StandardToStaticLogic/CMakeLists.txt
lib/Dialect/Handshake/CMakeLists.txt
lib/Dialect/LLHD/Transforms/CMakeLists.txt
lib/Dialect/StaticLogic/CMakeLists.txt
tools/circt-opt/CMakeLists.txt
tools/circt-translate/CMakeLists.txt
tools/firtool/CMakeLists.txt

Update llvm to upstream 43ce35f

---

.github/workflows/buildAndTest.yml

My last PR broke the workflow for push triggers. Sorry about the noise.

Fixing workflow breakage for push triggers

---

lib/Dialect/RTL/Ops.cpp

I believe this is along the lines of what you're looking for.

[RTL] Factor out more of the flattening case in canonicalization pass.

---

lib/Dialect/RTL/Ops.cpp
test/rtl/errors.mlir
test/rtl/modules.mlir

Rather than confining them to FIRRTL circuits. Also add some error messages and a test.

[RTL] Allow RTL.Instances to be in any SymbolTable region

---

include/circt/Conversion/FIRRTLToLLHD/FIRRTLToLLHD.h
lib/Conversion/FIRRTLToLLHD/FIRRTLToLLHD.cpp
tools/circt-opt/circt-opt.cpp

Fix syntax regression introduced in #113. Fixes #135.

[LLHD] Fix syntax regression

---

lib/Dialect/RTL/Dialect.cpp

Remove a redundant condition produced by #146 .

[RTL] Remove redundant condition

---

lib/Conversion/StandardToHandshake/StandardToHandshake.cpp

This is a quick PR to address #115 . I'm not sure how to actually invoke a call to `dotPrint`. If you show me how, I can properly determine that this works.

[StandardToHandshake] Remove ostream.

---

include/circt/Dialect/RTL/Structure.td
lib/Dialect/RTL/Ops.cpp
test/rtl/modules.mlir

This was relatively easy. The harder part is going to be figuring out how output (to SystemVerilog) arbitrary types non-intrusively.

[RTL] Allow AnyType on RTL modules

---

include/circt/Dialect/FIRRTL/OpExpressions.td
lib/Dialect/FIRRTL/Ops.cpp
test/FIRParser/basic.fir

Signed tail is output from FIRRTL, support it

---

.gitignore

This is a file that unfortunately pops up on macOS

Add ".DS_Store" to .gitignore

---

test/verilator/errors1.sv

[Verilator] Use 'not' instead of '|| true'

---

CMakeLists.txt

Thanks @stephenneuendorffer for the hint.

`ninja install` will now install binaries as well

---

include/circt/Dialect/Handshake/HandshakeOps.td
lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
lib/Dialect/Handshake/HandshakeOps.cpp
test/Conversion/HandshakeToFIRRTL/test_mux.mlir
test/Dialect/Handshake/errors.mlir

This is part of https://github.com/llvm/circt/issues/178.

[Handshake] Update MuxOp lowering to use primitive FIRRTL ops

---

.vscode/Unified.code-workspace.example.jsonc

Suggested by @stellaraccident, these might improve build performance.

[VSCode] Add some more flags to the example workspace

---

CMakeLists.txt
include/circt/Dialect/ESI/cosim/Cosim_DpiPkg.sv
include/circt/Dialect/ESI/cosim/Cosim_Endpoint.sv

This is the fourth in a series to merge #213 -- RTL. Adds the SystemVerilog code which will interface with the DPI library.

[ESI] [Cosim DPI] RTL

---

lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
test/Conversion/HandshakeToFIRRTL/test_conditional_branch.mlir

[Handshake] rewrite ConditionalBranchOp lowering with FIRRTL primitives

---

include/circt/Dialect/Handshake/HandshakeOps.td
lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
test/Conversion/HandshakeToFIRRTL/test_cmerge.mlir

[Handshake] Update ControlMergeOp lowering to use primitive FIRRTL ops

---

.github/workflows/buildAndTest.yml
.github/workflows/nightlyIntegrationTests.yml
utils/build-llvm.sh

[LLVM] Creates llvm build script to avoid replication

---

.github/workflows/nightlyIntegrationTests.yml

v2 adds the psutil python package which is required to timeouts in lit.

Switching to v2 image for nightlies

---

README.md

Adds badges of professionalism

---

include/circt/Dialect/FIRRTL/OpStructure.td
include/circt/Dialect/RTL/Structure.td
test/EmitVerilog/verilog-basic.fir
test/EmitVerilog/verilog-errors.mlir
test/FIRParser/locations.fir
test/firrtl/lower-to-rtl-module.mlir
test/firrtl/lower-types.mlir
test/rtl/errors.mlir

There are still some failures in the tests I haven't been able to fix, I would appreciate it if someone was able to take a look.

[WIP] Update LLVM

---

include/circt/Dialect/ESI/ESIOps.td
include/circt/Dialect/ESI/ESIPasses.td
lib/Dialect/ESI/ESIPasses.cpp

Based on @mikeurbach's post-merge comments.

[ESI] Lowering code cleanup

---

include/circt/Dialect/ESI/ESIPorts.td
lib/Dialect/ESI/ESIOps.cpp
test/esi/connectivity.mlir
test/esi/errors.mlir

This'll be useful in lowering to RTL/SV.

[ESI] Ops to inter-operate with SV interfaces

---

lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
test/Conversion/HandshakeToFIRRTL/test_buffer.mlir
test/Conversion/HandshakeToFIRRTL/test_cmerge.mlir

See the two individual commit messages for the issues and the reasoning. I found these issues while testing the new lowering for ControlMergeOp with the LowerToRTL pass.

Handshake firrtl bugs

---

include/circt/Dialect/SV/TypeDecl.td
lib/Dialect/SV/Ops.cpp
test/sv/interfaces.mlir

- Adds a read signal op and an assign signal op.
- Cleans up types (enabled by the recent MLIR update).
- Adds a convenience method.

[SV] [Interfaces] Read and assign ops

---

lib/Dialect/ESI/ESIPasses.cpp
test/esi/lowering.mlir
test/esi/wrapif-lowering.mlir

Final lowering pass! After all 3 passes, there aren't _any_ ESI constructs at all! Finally!

[ESI] Lower `esi.(un)wrap.iface` to `esi.(un)wrap.vr`

---

include/circt/Dialect/RTL/Combinatorial.td
lib/Dialect/RTL/Ops.cpp
test/Dialect/RTL/canonicalization.mlir

Towards #252, this PR adds folders for unary reduction ops (andr, orr, xorr).

[RTL] Add folders for reduction ops

---

docs/CommandGuide/handshake-runner.md
docs/Dialects/Handshake.md

This PR intended to add documentation for the handshake dialect and handshake-runner.

Add documentation for Handshake dialect

---

tools/circt-rtl-sim/circt-rtl-sim.py

[circt-rtl-sim] Add option to launch the GUI

---

lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Conversion/FIRRTLToRTL/lower-to-rtl.mlir

[FIRRTL] Fix zero-width head and tail ops and their lowering

---

lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp

[HandshakeToFIRRTL] factor out buildJoinLogic() method

---

lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
test/Conversion/HandshakeToFIRRTL/test_store.mlir

The implementation is a simple combinational circuit that waits for
all inputs to be valid and all outputs to be ready.

[HandshakeToFIRRTL] Implement lowering of StoreOp.

---

README.md

[README] Correct a grammar mistake

---

include/circt/Dialect/SV/SVStatements.td
include/circt/Dialect/SV/SVVisitors.h
lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp
lib/Dialect/SV/SVOps.cpp
lib/Translation/ExportVerilog/ExportVerilog.cpp
test/Conversion/FIRRTLToRTL/lower-to-rtl.mlir
test/Dialect/SV/basic.mlir
test/ExportVerilog/sv-dialect.mlir

Always merging is another patch, but one forthcoming.
Fixes #440

Always_ff support with explicit resets and reset style (sync/async)

---

lib/Translation/ExportVerilog/ExportVerilog.cpp

The SV 2017 spec defines a level above Unary (Table 11-2) for `()`,
`[]`, `::`, and `.`. This is important to represent as SystemVerilog (or
perhaps just the Verilator parser) does not allow grouping with `()` at
that level.

[ExportVerilog] Add new precedence level

---

include/circt/Dialect/SV/SVStatements.td
test/Conversion/FIRRTLToRTL/lower-to-rtl.mlir
test/Dialect/SV/basic.mlir
test/ExportVerilog/sv-dialect.mlir

Make alwaysff reset blocks more clear.

Alwaysff syntax improvement

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
test/Conversion/FIRRTLToRTL/lower-to-rtl-module-errors.mlir
test/Conversion/FIRRTLToRTL/lower-to-rtl-module.mlir
test/Dialect/FIRRTL/errors.mlir

Transform simple firrtl bundles into rtl structs and add cast operation for fir bundles to rtl structs

Transform simple firrtl bundles into rtl structs and add cast operation for fir bundles to rtl structs

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp
lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp
lib/Dialect/FIRRTL/FIRRTLDialect.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Translation/ExportVerilog/ExportVerilogFIRRTL.cpp
test/Conversion/FIRRTLToRTL/lower-to-rtl.mlir
test/Conversion/HandshakeToFIRRTL/test_memory.mlir
test/Dialect/FIRRTL/lower-types.mlir
test/Dialect/FIRRTL/parse-basic.fir
test/ExportVerilog/verilog-basic.fir

Not looking for a review here, I just want to run all tests (and clang-tidy, etc.) and for there to be a record of how this was fixed. Will merge after this passes.

Reapply Reverted PR #488

---

lib/Dialect/ESI/cosim/cosim_dpi_server/DpiEntryPoints.cpp

When the `COSIM_DEBUG_FILE` environment variable is set, log to the file specified there. Example log:
```
[ep:    1 to:  sim] 00 00 00 00  01 00 00 00    31 00 00 00  00 00 00 00
[ep:    1 to: host] 00 00 00 00  01 00 00 00    89 01 00 00  00 00 00 00
[ep:    1 to:  sim] 00 00 00 00  01 00 00 00    31 00 00 00  00 00 00 00
[ep:    1 to: host] 00 00 00 00  01 00 00 00    ba 01 00 00  00 00 00 00
[ep:    1 to:  sim] 00 00 00 00  01 00 00 00    2c 00 00 00  00 00 00 00
[ep:    1 to: host] 00 00 00 00  01 00 00 00    e6 01 00 00  00 00 00 00
[ep:    1 to:  sim] 00 00 00 00  01 00 00 00    30 00 00 00  00 00 00 00
[ep:    1 to: host] 00 00 00 00  01 00 00 00    16 02 00 00  00 00 00 00
```

[ESI] [Cosim] Dump capnp messages to log file

---

include/circt/Dialect/RTL/RTLAggregates.td
include/circt/Dialect/RTL/RTLVisitors.h
lib/Dialect/RTL/RTLOps.cpp
lib/Translation/ExportVerilog/ExportVerilog.cpp
test/Dialect/RTL/basic.mlir
test/ExportVerilog/rtl-dialect.mlir

Adds `ArrayConcatOp` to merge two arrays.

[RTL] Array concatenation operation

---

lib/Dialect/ESI/capnp/Schema.cpp
tools/esi/esi-cosim-runner.py.in

These changes support the next PR -- list encoding support. Breaking them out to reduce review load.

[ESI] [Cosim] Improvements to gasket utility classes

---

include/circt/Dialect/RTL/RTLDialect.h
include/circt/Dialect/RTL/RTLOps.h
lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp
lib/Dialect/ESI/ESIPasses.cpp
lib/Dialect/ESI/capnp/Schema.cpp
lib/Translation/ExportVerilog/ExportVerilog.cpp

[RTL/Comb] Remove the Comb namespace import in RTL

---

include/circt/Dialect/ESI/ESI.td
include/circt/Dialect/ESI/ESITypes.h
include/circt/Dialect/ESI/ESITypes.td
lib/Dialect/ESI/ESITypes.cpp
test/Dialect/ESI/connectivity.mlir

Just an RTL struct wrapped with a name.

[ESI] Add a named struct type

---

lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp
test/Conversion/FIRRTLToRTL/lower-to-rtl.mlir

Connect was using alwaysff, partialconnect wasn't.
close: #631

use alwaysff for partialconnect

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

[FIRRTL] Handle invalidvalue of struct type in LowerTypes

---

CMakeLists.txt
integration_test/EmitVerilog/standards.mlir
integration_test/lit.cfg.py
integration_test/lit.site.cfg.py.in

Cmdline for questa lint checks for standard versions.
Search for quartus.

Intel tools for integration tests

---

docs/RationaleRTL-SV.md
include/circt/Dialect/Comb/CombVisitors.h
include/circt/Dialect/Comb/Combinational.td
include/circt/Dialect/RTL/RTLAggregates.td
include/circt/Dialect/RTL/RTLDialect.h
include/circt/Dialect/RTL/RTLVisitors.h
integration_test/EmitVerilog/basic.mlir
integration_test/EmitVerilog/lint.mlir
integration_test/EmitVerilog/sv-interfaces.mlir
lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp
lib/Dialect/Comb/CombDialect.cpp
lib/Dialect/Comb/CombFolds.cpp
lib/Dialect/Comb/CombOps.cpp
lib/Dialect/ESI/capnp/Schema.cpp
lib/Dialect/RTL/RTLDialect.cpp
lib/Dialect/RTL/RTLOps.cpp
lib/Translation/ExportVerilog/ExportVerilog.cpp
test/Conversion/FIRRTLToRTL/lower-to-rtl.mlir
test/Conversion/FIRRTLToRTL/zero-width.mlir
test/Dialect/RTL/basic.mlir
test/Dialect/RTL/canonicalization.mlir
test/Dialect/RTL/errors.mlir
test/Dialect/SV/rtl-cleanup.mlir
test/ExportVerilog/rtl-dialect.mlir
test/ExportVerilog/sv-dialect.mlir
test/ExportVerilog/sv-interfaces.mlir
test/firtool/firtool.fir

Move `comb.constant` to `rtl.constant`. 
Will close #665

[RTL] [Comb] Move comb.constant to rtl

---

lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp
test/Conversion/FIRRTLToRTL/lower-to-rtl.mlir

[LowerToRTL] Handle register reset values narrower than register

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

Fixes #480.
Add lowering of FIRRTL Dialect memories with readwrite ports during the LowerTypes pass. This is accomplished by splitting each readwrite port into one read and one write port. The lowering of aggregate memories into ground type memories proceeds unaffected.
Starting with the following readwrite memory:
```scala
circuit Foo:
module Foo:
input rwEn: UInt<1>
input rwMode: UInt<1>
input rwAddr: UInt<4>
input rwMask: UInt<1>
input rwDataIn: UInt<8>
output rwDataOut: UInt<8>
mem memory:
data-type => UInt<8>
depth => 16
readwriter => rw
read-latency => 0
write-latency => 1
read-under-write => undefined
memory.rw.clk <= clock
memory.rw.en <= rwEn
memory.rw.addr <= rwAddr
memory.rw.wmode <= rwMode
memory.rw.wmask <= rwMask
memory.rw.wdata <= rwDataIn
rwDataOut <= …
```

Lower ReadWrite Ports during LowerTypes

---

include/circt-c/Dialect/Comb.h
include/circt-c/Dialect/RTL.h
lib/CAPI/Dialect/CMakeLists.txt
lib/CAPI/Dialect/Comb.cpp
lib/CAPI/Dialect/RTL.cpp
test/CAPI/CMakeLists.txt

This exposes the Comb dialect and exposes some RTL-specific API

Bind more API to C

---

include/circt/Dialect/SV/SVStatements.td
test/Dialect/SV/basic.mlir
test/Dialect/SV/canonicalization.mlir
test/Dialect/SV/errors.mlir
test/ExportVerilog/sv-dialect.mlir
test/ExportVerilog/sv-interfaces.mlir

This PR is follow up of #719
This PR annotates `ProceduralOp` trait to `if/fatal/casez/finish` ops.
Almost all changes are test changes.
I'll separate patch for IfDefProceduralOp because it causes lots of changes

[SV] Verify if/fatal/casez/finish are in procedural regions

---

lib/Translation/ExportVerilog/ExportVerilog.cpp
test/ExportVerilog/rtl-dialect.mlir

closes #750 
Pending test case

out-of-block uses shouldn't always force temporaries

---

include/circt/Dialect/FIRRTL/FIRRTLStatements.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Canonicalize partial connects which are doing truncation to separate truncation and connect

Canonicalize partial connects

---

include/circt/Dialect/SV/SVStatements.td
test/Dialect/SV/errors.mlir
test/ExportVerilog/sv-dialect.mlir

[SV] Verify behavioral constructs are in procedural regions

---

include/circt/Dialect/Comb/Comb.td
include/circt/Dialect/SV/SV.td
integration_test/Bindings/Python/import.py
lib/Bindings/Python/CIRCTModule.cpp
lib/Bindings/Python/CMakeLists.txt
lib/Bindings/Python/CombOps.td
lib/Bindings/Python/SVOps.td
lib/Bindings/Python/circt/dialects/comb.py
lib/Bindings/Python/circt/dialects/sv.py

This adds the bindings and just checks that the dialects can be
imported in the integration test. Full integration test is coming, but
I have some small improvements to land first.

[Python] Add bindings for Comb and SV dialects.

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/RTL/RTLStructure.td
lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/BlackboxMemory.cpp
lib/Dialect/RTL/RTLOps.cpp
lib/Translation/ExportVerilog/ExportVerilog.cpp
test/Dialect/RTL/errors.mlir

Better handling of generated modules in export verilog.

update module builders to take optional attributes.  

---

docs/RationaleSeq.md

[Seq] Proposal for dialect and `reg` op

---

include/circt/Dialect/FIRRTL/Canonicalization.td
include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

closes #900
Will add other cases

Canonicalize mux trees

---

integration_test/Bindings/Python/dialects/msft.py
lib/Bindings/Python/CIRCTModule.cpp
lib/Bindings/Python/CMakeLists.txt
lib/Bindings/Python/DialectModules.h
lib/Bindings/Python/MSFTModule.cpp

No functionality -- purely mechanical addition.

[MSFT] [Python] Python bindings infrastructure for MSFT dialect

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp

[FIRRTL] Fix use-after-free in connect canonicalization

---

.github/workflows/buildAndTest.yml

Updated the github workflow caching to be based on the actual workflow content
as mention in the issue #922

Updated the workflow file and key

---

docs/GettingStarted.md

Changes "Please create a PRs..." to "Please create a PR...".
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

[docs] Fix minor typo in getting started guide

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

[FIRRTL][LowerTypes] Recursively visit WhenOps

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp

This fixes a data race in LowerTypes.  While lowering InstanceOps, the
port names were read from the ModuleOp and used while flattenning bundle
typed results, while another thread modified the ModuleOp's port names.
This was a race condition which lead to to instance results not
correctly being replaced with flattened results, or dropping too many
characters from the fron of a bundle field name.
The port name was not required to flatten the bundle, and was later
stripped from the flattened bundle. This change stops using the port
name while flattening the instance results, and an empty string was used
instead.

[FIRRTL][LowerTypes] Don't read port names when lowering InstanceOps

---

integration_test/Bindings/Python/dialects/esi.py
lib/Bindings/Python/circt/esi.py

This method hides some of the ugliness from the users.

[ESI] [Python] Refactor "System" to make users subclass it

---

integration_test/Dialect/Handshake/loop.mlir
integration_test/Dialect/Handshake/mac.mlir
integration_test/Dialect/Handshake/memory.mlir
tools/circt-rtl-sim/circt-rtl-sim.py.in
tools/esi/esi-cosim-runner.py.in

Some simulators don't like being run in parallel in the same directory. Also, reset the handshake tests to include all IEEE simulators.

[circt-rtl-sim] Run each simulation in its own directory

---

tools/firtool/firtool.cpp

Run the `CheckWidths` pass when lowering to the RTL dialect to ensure there are no uninferred widths that will cause the lowering to fail. Add a `--infer-widths` option that runs the `InferWidths` pass.
Fixes #1032.

[firtool] Run CheckWidths pass, add option for InferWidths

---

tools/firtool/firtool.cpp

Add the `--parser-timing` option to firtool. If present, the time taken to parse the FIRRTL or MLIR input is emitted alongside any other potential statistics. Fixes #608.
For example, `firtool test/ExportVerilog/rtl-dialect.mlir -verilog --pass-timing --parser-timing` produces the following output:
```
MLIR Parser Execution Time: 0.0135 seconds
===-------------------------------------------------------------------------===
... Pass execution timing report ...
===-------------------------------------------------------------------------===
Total Execution Time: 0.0497 seconds
---User Time---   ---Wall Time---  --- Name ---
0.0026 (  4.7%)     0.0026 (  5.1%)  LowerFIRRTLToRTL
0.0055 ( 10.2%)     0.0011 (  2.2%)  'rtl.module' Pipeline
0.0055 ( 10.2%)     0.0011 (  2.2%)    RTLCleanup
0.0035 …
```

[FIRRTL] Add parser-timing firtool option

---

.github/workflows/buildAndTest.yml

If this CI build passes, we're good to go. If anyone sees three green checks, please merge as I will be away from my desk.
Fixes #1047 ... hopefully.

[CI] Upgrade to Ubuntu 20.04 docker image

---

lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp

The stack allocated vector values was allocated inside a for loop and a
reference to it was stored in to an SmallVector.  Asan picked up the
invalid dangling reference. The SmallVector was changed to hold (own)
the child-vector instead of keeping a reference.

[HandshakeToFIRRTL] Fix use of stack allocated vector.

---

lib/Translation/ExportVerilog/ExportVerilog.cpp

Previously, the location was used to emit any errors. By passing an
Operation pointer, we still have the ability to do that, but it opens
up other possibillities. Specifically, we can use the Operation as an
anchor to lookup symbols, which is looking like it will be necessary
in order to emit types that reference type declarations.

[ExportVerilog] Pass an Operation to print type instead of Location.

---

include/circt/Dialect/FIRRTL/FIRRTLOps.h

Suggestion for Fixing two minors typos

[FIRRTL] fix small typos in comments

---

integration_test/Bindings/Python/dialects/seq.py
lib/Bindings/Python/circt/dialects/_seq_ops_ext.py

This adds support for incrementally building a CompRegOp.

[Python] Add NamedValueBuilder for CompRegOp.

---

lib/Dialect/ESI/CMakeLists.txt
lib/Dialect/LLHD/IR/CMakeLists.txt
lib/Dialect/LLHD/Transforms/CMakeLists.txt

New Python API call required for upcoming PR.

Update LLVM to 95cefacfe1c1fe920f22b749f17f630925bd6094

---

integration_test/Bindings/Python/DesignEntry/connect.py
integration_test/Bindings/Python/DesignEntry/polynomial.py
lib/Bindings/Python/circt/design_entry.py
lib/Bindings/Python/circt/dialects/_hw_ops_ext.py
lib/Bindings/Python/circt/support.py

Also make the 'connect.py' test work since it tests the 'connect' function
which I've changed.

[Py] Clean up and merge some code

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Surprisingly, this comes up fairly often out of chisel.

[FIRRTL] bit reductions on one bit values are identity functions

---

tools/firtool/firtool.cpp

Move the width inference pass up in the pipeline such that it runs before the canonicalization passes. This is useful since width inference itself does not depend on canonicalization, but in turn enables a lot of canonicalization patterns to run.
This is basically @darthscsi's https://github.com/llvm/circt/tree/dev/darthscsi/default.inferwidth branch, but without making width inference run by default.

[firtool] Move width inference before canonicalization

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Add a canonicalizer for `mux` operations that pads operands to the multiplexer's result width if that width is known. This unlocks most of the folds defined on the multiplexer which require the operands to have the same width as the mux itself for them to be valid. This is also aligns muxes with the Scala implementation, where they imply a padding operation to the result type. See the discussion in #929 where @seldridge suggested to add this canonicalization to line up with SFC.

[FIRRTL] Canonicalize mux by padding operands to same width

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

[FIRRTL] canonicalize RegResetOp to RegOp

---

include/circt/Dialect/HW/HWAggregates.td
lib/Dialect/HW/HWOps.cpp
test/Dialect/HW/basic.mlir
test/ExportVerilog/hw-dialect.mlir

[HW] Remove parentheses from array_create.

---

frontends/PyCDE/src/pycde/__init__.py
frontends/PyCDE/src/pycde/system.py
frontends/PyCDE/test/polynomial.py

Looks kind of like the ESI system. A bunch of the convenience stuff should
probably be moved into pycde at some point.

[PyCDE] Create 'System' to provide nicer interface to users

---

include/circt/Dialect/Comb/Combinational.td
lib/Dialect/Comb/CombFolds.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/HW/canonicalization.mlir

Towards #820, this PR adds folders for DivU/DivS/ModU/ModS. 
The folding calculation relies on functions of `APInt` so let me correct if the semantics is different.

[HW] Add folders for div/mod

---

frontends/PyCDE/src/pycde/module.py
frontends/PyCDE/test/polynomial.py

To represent a `hw.module.extern`. Creates a generator to output the extern mod and the instance.

[PyCDE] Add @externmodule annotation

---

frontends/PyCDE/src/pycde/module.py
frontends/PyCDE/test/errors.py
frontends/PyCDE/test/generator_options.py
frontends/PyCDE/test/polynomial.py
lib/Bindings/Python/circt/support.py

Is was _really_ bothering me that module instantiation was mixed with parameter resolution. It makes the user code kinda nasty (based on my experience with the internal project). This is a pretty massive refactoring, but it allows for parameterization before
instantiation. I'm happier with it.

[PyCDE] Declare parameterized modules in functions

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

[FIRRTL] Handle AsPassivePrimOp in LowerTypes

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Check for `DontTouch` annotation in FIRRTL `canonicalize`.

Dont canonicalize registers with DontTouch

---

frontends/PyCDE/src/pycde/module.py
frontends/PyCDE/src/pycde/support.py
frontends/PyCDE/src/pycde/system.py
frontends/PyCDE/src/pycde/types.py
frontends/PyCDE/test/polynomial.py
lib/Bindings/Python/circt/dialects/_comb_ops_ext.py
lib/Bindings/Python/circt/dialects/_hw_ops_ext.py
lib/Bindings/Python/circt/support.py

Enables subscripting result array and struct values:
```
a = ModuleWithArrayAndStructResults(clk=clk)
array1_idx0 = a.array1[0]
struct1_foo a.struct1["foo"]
```
Not testing this since a bug in the generator is blocking expansion of the `polynomial.py` test.
Most (if not all) seemingly unrelated changes were bugs which were blocking this change or necessary since this change broke stuff which wasn't general enough.

[PyCDE] Support result array/struct subscripting + misc. related improvements

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/annotations-errors.fir
test/Dialect/FIRRTL/annotations.fir
test/Dialect/FIRRTL/lower-types.mlir
test/Dialect/FIRRTL/test.mlir

[FIRRTL] Store port annotations as result attributes for InstanceOp

---

lib/Translation/ExportVerilog/ExportVerilog.cpp

Keep the legalized names between perpare and emit

[ExportVerilog] Prepare all modules before emitting them.  

---

docs/RationaleFIRRTL.md
lib/Dialect/FIRRTL/Import/FIRLexer.cpp
lib/Dialect/FIRRTL/Import/FIRLexer.h
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Import/FIRTokenKinds.def
test/Dialect/FIRRTL/parse-basic.fir

Decided to tackle this as I'm familiarizing myself with the project. Please let me know of any needed changes.
Closes #781 and #874.

[FIRParser] Parse RawString ExtModule Parameters

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/Comb/canonicalization.mlir

Canonicalize nested muxes when the conds are similar.

[Comb] Canonicalize mux(cond,a, mux(cond, b, c)) into mux(cond, a, c)

---

include/circt/Dialect/SV/CMakeLists.txt
include/circt/Dialect/SV/SV.td
include/circt/Dialect/SV/SVAttributes.h
include/circt/Dialect/SV/SVAttributes.td
lib/Dialect/SV/SVAttributes.cpp
lib/Dialect/SV/SVDialect.cpp

Separating out the boilerplate from #1383 .

[SV] [NFC] Adding boilerplate for attributes

---

include/circt/Dialect/SV/SVStatements.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Translation/ExportVerilog/ExportVerilog.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir
test/Dialect/SV/prettify-verilog.mlir
test/firtool/split-verilog.mlir

IfDefOp and IfDefProceduralOp should exist in non-procedural and procedural regions, respectively, and maintain that property for their body.

[SV] Strengthen checks on ifdef regions.

---

lib/Dialect/Comb/CombFolds.cpp

Probably uncontroversial :). Will merge this after CI passes..

[Comb] return sucess() after rewriting MuxOp successfully

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Translation/ExportVerilog/ExportVerilog.cpp

Switch existing usages of llvm::parallel* methods to provide parallelism
within a pass to use the newer mlir::parallel* methods.  The MLIR
variants avoid the need for explicitly checking if parallelism is
allowed by the context.
There is no upstream equivalent of llvm::parallelTransformReduce, so the
one usage of that in LowerToHW remains in place.

Use mlir::parallel*, not llvm::parallel*, NFC

---

CMakeLists.txt

See [this thread](https://llvm.discourse.group/t/rfc-update-c-standard-from-14-to-17/3951).

Upgrade C++ standard to C++17

---

include/circt/Dialect/ESI/ESIOps.td
include/circt/Dialect/ESI/ESIPorts.td
include/circt/Dialect/FIRRTL/FIRRTLStructure.td
include/circt/Dialect/HW/HWAggregates.td
include/circt/Dialect/HW/HWStructure.td
include/circt/Dialect/Handshake/HandshakeOps.td
include/circt/Dialect/LLHD/IR/LLHD.td
include/circt/Dialect/Seq/Seq.td
lib/Dialect/ESI/ESIOps.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/HW/HWOps.cpp
lib/Dialect/Handshake/HandshakeOps.cpp
lib/Dialect/LLHD/IR/LLHDOps.cpp
lib/Dialect/Seq/SeqOps.cpp

Closes #1412, if I didn't miss any :)

Replace `print` with `print$cppClass`.

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp

The llvm::SourceMgr class lazily builds a line table, and isn't
internally synchronized.  This can cause crashes with threaded
parsing.  This fixes Issue #1513.

[FIRParser] Fix a race populating SourceMgr line table

---

include/circt-c/Dialect/ESI.h
lib/Bindings/Python/ESIModule.cpp
lib/CAPI/Dialect/ESI.cpp

Necessary to avoid linking issues on Windows.

[ESI] [Python] Move functionality through the C API

---

frontends/PyCDE/src/pycde/module.py
lib/Conversion/LLHDToLLVM/LLHDToLLVM.cpp
lib/Dialect/SV/Transforms/HWCleanup.cpp
test/CAPI/ir.c
test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir
test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir
test/Conversion/LLHDToLLVM/convert_signals.mlir
test/Conversion/LLHDToLLVM/convert_simple.mlir
test/Conversion/LLHDToLLVM/convert_wait.mlir
test/circt-opt/commandline.mlir
tools/firtool/firtool.cpp
tools/llhd-sim/llhd-sim.cpp

This upgrade is gonna take some digging. I got it to compile but it fails a bunch of tests. I managed to fix several.
Updated list:
```
Failed Tests (1):
CIRCT :: Dialect/SV/hw-cleanup.mlir
```
On the upside, none of the integration tests fail!

[llvm] Update submodule to latest

---

frontends/PyCDE/src/pycde/value.py
frontends/PyCDE/test/syntactic_sugar.py

- Provide a `name` property on `Value`
- Register naming
- Array get indexes
- Struct fields

[PyCDE] Value naming enhancements

---

include/circt-c/Dialect/MSFT.h
include/circt/Dialect/MSFT/MSFTDialect.h
integration_test/Bindings/Python/dialects/msft.py
lib/Bindings/Python/MSFTModule.cpp
lib/CAPI/Dialect/MSFT.cpp
lib/Dialect/MSFT/CMakeLists.txt
lib/Dialect/MSFT/MSFTDialect.cpp

Given a root module and an instance path, find the corresponding instance from
the instance hierarchy. Return 'None' if the path wasn't found.

[MSFT] [Python] Add a function to get an instance

---

lib/Scheduling/SimplexSchedulers.cpp

Second part of a patch series that adds a heuristic scheduler for the (resource-constrained) `SharedPipelinedOperatorsProblem`. This implements the tableau transformations necessary to fix an operation's start time to a certain value.

[Scheduling] [2/3] Add scheduler for shared pipelined operators problem: Tableau transformations.

---

frontends/PyCDE/src/pycde/__init__.py
frontends/PyCDE/src/pycde/appid.py
frontends/PyCDE/src/pycde/attributes.py
frontends/PyCDE/src/pycde/instance.py
frontends/PyCDE/src/pycde/system.py
frontends/PyCDE/test/instances.py

- Adds AppID and AppIDIndex
- Introduces attributes, which is just a thin layer around MLIR attributes
- Misc fixes

[PyCDE] Adds 'AppID' and attributes

---

frontends/PyCDE/pyproject.toml
frontends/PyCDE/setup.py

The resulting wheel is 167MB, but that's not as large as I expected.

[PyCDE] Setup.py to compile Python wheel

---

include/circt/Dialect/Calyx/CalyxPrimitives.td

Add helper functions to access MemoryOp ports (#1635).

[Calyx] Add helper functions to access MemoryOp ports (#1635)

---

include/circt/Dialect/Calyx/CalyxStructure.td
lib/Dialect/Calyx/CalyxOps.cpp
test/Dialect/Calyx/errors.mlir

Picking some low-hanging fruit. Closes #1520.
There's a TODO left for when the `CellInterface` is complete.
Feel free to nit the error messages, I imagine there's better wording.

[Calyx] Add verifier for AssignOp.

---

lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/firtool/firtool.fir
test/firtool/firtool.fir.anno.1.json
test/firtool/firtool.fir.anno.json
tools/firtool/firtool.cpp

A build flow might have multiple annotation files.  Allow passing them all.

[FIRTOOL] Allow multiple annotation files

---

include/circt/Dialect/Calyx/CalyxControl.td
lib/Dialect/Calyx/CalyxOps.cpp
lib/Dialect/Calyx/Export/CalyxEmitter.cpp
test/Dialect/Calyx/emit.mlir
test/Dialect/Calyx/round-trip.mlir

[Calyx] Add ParOp.

---

include/circt/Dialect/Calyx/Calyx.td
include/circt/Dialect/Calyx/CalyxStructure.td
include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/HW/HWMiscOps.td
include/circt/Dialect/HW/HWStructure.td
include/circt/Dialect/Handshake/HandshakeOps.td
include/circt/Dialect/SV/SVExpressions.td
include/circt/Dialect/SV/SVInOutOps.td
lib/CAPI/Dialect/HW.cpp
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Conversion/LLHDToLLVM/LLHDToLLVM.cpp
lib/Dialect/Calyx/CalyxOps.cpp
lib/Dialect/ESI/ESIDialect.cpp
lib/Dialect/ESI/ESIOps.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
lib/Dialect/HW/HWOps.cpp
lib/Dialect/Handshake/HandshakeOps.cpp
lib/Dialect/LLHD/IR/LLHDOps.cpp
lib/Dialect/MSFT/MSFTDialect.cpp
lib/Dialect/SV/SVOps.cpp
lib/Dialect/SV/Transforms/HWLegalizeNames.cpp
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
lib/Dialect/Seq/SeqOps.cpp
lib/Translation/ExportVerilog/ExportVerilog.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir
test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir
test/Dialect/Calyx/errors.mlir

Update to 6a75041a1614af1ca787af5a18ea9ddbe4dd5c16. This breaks stuff which I don't have time to fix right now, so it will fail the CI check. Anyone who wants to fix can push to this branch.

Update LLVM submodule

---

lib/Dialect/Calyx/CalyxOps.cpp
lib/Dialect/Calyx/Export/CalyxEmitter.cpp
test/Dialect/Calyx/compile-control.mlir
test/Dialect/Calyx/emit.mlir
test/Dialect/Calyx/errors.mlir
test/Dialect/Calyx/go-insertion.mlir
test/Dialect/Calyx/remove-groups.mlir
test/Dialect/Calyx/round-trip.mlir

Closes #1696.
Also tidies up a few nits.

[Calyx] Verify the component does something.

---

include/circt/Dialect/Calyx/CalyxInterfaces.td

A few utility functions to make life easier. Tested locally.

[Calyx] Add various convenience functions to Cell interface

---

lib/Conversion/LLHDToLLVM/CMakeLists.txt
lib/Conversion/LLHDToLLVM/LLHDToLLVM.cpp

Priming the CI pumps while I try to get this going locally.

Update LLVM to 704a395

---

include/circt/Dialect/Seq/Seq.td
lib/Bindings/Python/circt/dialects/_seq_ops_ext.py
lib/Dialect/Seq/SeqOps.cpp
lib/Dialect/Seq/SeqPasses.cpp

Mirror the semantics of `sv.reg`.

[Seq] [CompRegOp] Make 'name' non-optional but allow it to be empty

---

docs/FIRRTLAnnotations.md

[Docs] Fix typo in Doc [NFC]

---

include/circt/Dialect/MSFT/MSFTOps.td
include/circt/Dialect/MSFT/MSFTPasses.td
lib/Dialect/MSFT/CMakeLists.txt
lib/Dialect/MSFT/MSFTOps.cpp
lib/Dialect/MSFT/MSFTPasses.cpp
test/Dialect/MSFT/module_instance.mlir

[MSFT] Lower `MSFTModuleOp`s to `HWModuleOp`s

---

include/circt/Dialect/Calyx/CalyxControl.td
lib/Dialect/Calyx/Export/CalyxEmitter.cpp
test/Dialect/Calyx/emit.mlir

[Calyx] [NFC] Emitter now emits `ElseRegion`.

---

frontends/PyCDE/src/pycde/module.py

When instantiating two parameterized extern modules, both map to the same module which causes generation to fail if port types are not the same between the two parameterizations.
Minimal example demonstrating problem:
```
@module
class MyModule:
clk = Input(types.i1)
data_in = Input(dim(6))
@generator
def construct(mod):
inst_a = ExternMod(DW=2)(
clk=mod.clk,
data_in=mod.data_in[0:2]
)
inst_b = ExternMod(DW=4)(
clk=mod.clk,
data_in=mod.data_in[2:6]
)
return {}
@externmodule
def ExternMod(DW: int):
class Mod:
clk = Input(types.i1)
data_in = Input(dim(DW))
return Mod
```
Multiple parameterizations of the same extern module will still map to the same pycde module object. The module object tracks a single `extern_mod` variable which is ultimately used for all parameterizations. One solution …

[PyCDE] An update for parameterized extern modules

---

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp

[FIRRTL] Move pass into anonymous namespace, NFC

---

docs/FIRRTLAnnotations.md
include/circt/Dialect/FIRRTL/InstanceGraph.h
include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
include/circt/Dialect/HW/CMakeLists.txt
include/circt/Dialect/HW/HWAttributes.td
include/circt/Dialect/HW/HWDialect.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/EmitMetadata.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/HW/CMakeLists.txt
lib/Dialect/HW/HWAttributes.cpp
lib/Dialect/HW/HWDialect.cpp
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
lib/Translation/ExportVerilog/ExportVerilog.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/emit-metadata-errors.mlir
test/Dialect/FIRRTL/emit-metadata.mlir
test/Dialect/FIRRTL/grand-central.mlir
test/Dialect/HW/basic.mlir
test/Dialect/SV/hw-extract-test-code.mlir
test/ExportVerilog/output-file.mlir
test/ExportVerilog/verilog-basic.mlir
test/firtool/split-verilog.mlir
tools/firtool/firtool.cpp

This add a single pass to handle our metadata needs.  Only review the last two commits!

[FIRRTL] add all-in-one metadata pass 

---

test/firtool/memory.fir

Add a `firtool` test for memory.

[IntegrationTest] Add memory firtool test. NFC.

---

include/circt/Scheduling/Problems.h
lib/Scheduling/Problems.cpp

This PR switches from *component*-specific checkers/verifiers, e.g. `checkOperation(op)` or `verifyDependence(dep)`
to *property*-specifc methods, such as `checkLatency(opr)` or `verifyStartTime(op)`. In addition, the client API methods, `check()` and `verify()`, are now virtual and expected to be refined by subclasses (e.g. if the modelled problem introduces new properties that need to be validated as well).
This new design gives the concrete classes more control over what needs to be checked/verified (and it which order!), and thus prevents redundant checks as well as needless iteration over problem components.
~~(Based on #1886 -- will rebase and mark ready once the `ModuloProblem` definition lands.)~~

[Scheduling] Refactor validation framework.

---

tools/handshake-runner/Simulation.cpp

This commit refactors the handshake-runner to be based on a visitor pattern rather than manually checking for the type of each possible operation. The commit also takes a step towards reducing the code duplication between executing a mlir::FuncOp and handshake::FuncOp.
More opportunities for cleanup and refactoring exists, however, this commit focuses only on the visitor refactoring to keep it as brief as possible.

[Handshake] Refactor handshake runner to be visitor based

---

.github/workflows/buildAndTest.yml
frontends/PyCDE/src/pycde/instance.py
integration_test/Bindings/Python/dialects/rtl.py
integration_test/lit.cfg.py
lib/Bindings/Python/circt/dialects/_hw_ops_ext.py

This is required by the yapf tool we use to enforce formatting.

[Python][CI] Fix formatting check by using an image with toml.

---

lib/Dialect/FIRRTL/Transforms/InferResets.cpp

InferResets is using a `unique_ptr<SymbolTable>()` which was improperly
free'd causing a memory leak.  The `release` call just releases ownship
from the `unique_ptr` but does not free the memory.
Instead of directly fixing this problem, this switches the pass to use the
`InstanceGraph`.  Since this pass does not change the hiearchy it can always
mark this analysis as preserved.  This has the benefit of sharing the analysis
between passes instead of calculating a new `SymbolTable`.

[FIRRTL][InferResets] Use instance graph

---

include/circt/Dialect/Calyx/CalyxControl.td
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Dialect/Calyx/CalyxOps.cpp

Adds builders for `SeqOp` and `ParOp` that add the body for you already. First part of #1884.

[Calyx] [SCFToCalyx] Add simplified builders for `SeqOp` and `ParOp`.

---

include/circt-c/Dialect/MSFT.h
include/circt/Dialect/MSFT/DeviceDB.h
include/circt/Dialect/MSFT/PlacementDB.h
integration_test/Bindings/Python/dialects/msft.py
lib/Bindings/Python/MSFTModule.cpp
lib/CAPI/Dialect/MSFT.cpp
lib/Dialect/MSFT/DeviceDB.cpp
lib/Dialect/MSFT/PlacementDB.cpp

Just checks validity of placements for now.

[MSFT] Use a DeviceDB to seed a PlacementDB

---

lib/Dialect/FIRRTL/Transforms/LowerCHIRRTL.cpp
test/Dialect/FIRRTL/lower-chirrtl.mlir

Fix a bug in LowerCHIRRTL where memory address port connections were
unconditionally lowered using a connect operator.  Change this to use a
partial connect operator if the RHS source is larger than the memory
port.

[FIRRTL] PartialConnect Larger CHIRRTL Addr Ports

---

.github/workflows/buildAndTest.yml
lib/Analysis/DependenceAnalysis.cpp

This PR moves sanity checks(clang-format, clang-tidy, python-format) to the beginning of CI as a new job.
Will close #1524

[CI] Add a sanity check job  

---

docs/ESI/cosim.md
docs/ESI/notes.md
docs/ESI/services.md
docs/ESI/software_api.md
docs/ESI/types.md
docs/RationaleESI.md

Porting and updating pre-CIRCT documentation which I wrote in early
2020. Nearly all of it is future work -- I'm putting it there so people
can see where I mean ESI to go.

[ESI] Adding project documentation

---

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
test/Conversion/SCFToCalyx/convert_simple.mlir

Adds a conversion from `MulIOp` to Calyx's `MultPipe`.

[SCFToCalyx] Add conversion for MulIOp.

---

test/Conversion/HandshakeToFIRRTL/test_buffer.mlir
test/Conversion/HandshakeToFIRRTL/test_cmerge.mlir
test/Conversion/HandshakeToFIRRTL/test_conditional_branch.mlir
test/Conversion/HandshakeToFIRRTL/test_constant.mlir
test/Conversion/HandshakeToFIRRTL/test_fork.mlir
test/Conversion/HandshakeToFIRRTL/test_index_cast.mlir
test/Conversion/HandshakeToFIRRTL/test_load.mlir
test/Conversion/HandshakeToFIRRTL/test_memory.mlir
test/Conversion/HandshakeToFIRRTL/test_merge.mlir
test/Conversion/HandshakeToFIRRTL/test_mux.mlir
test/Conversion/HandshakeToFIRRTL/test_store.mlir

... because it's starting to get a bit tedious to fix all of these tests when doing changes to Handshake signal naming!

[Handshake][NFC] Use more pattern matching in tests

---

include/circt/Conversion/AffineToStaticLogic.h
include/circt/Conversion/Passes.h
include/circt/Conversion/Passes.td
lib/Analysis/DependenceAnalysis.cpp
lib/Conversion/AffineToStaticLogic/AffineToStaticLogic.cpp
lib/Conversion/AffineToStaticLogic/CMakeLists.txt
lib/Conversion/CMakeLists.txt
lib/Conversion/PassDetail.h
test/Conversion/AffineToStaticLogic/loops.mlir
tools/circt-opt/CMakeLists.txt

Tested here: https://github.com/llvm/circt/actions/runs/1454494637

Staticlogic conversion revert

---

include/circt/Dialect/StaticLogic/StaticLogic.td
lib/Dialect/StaticLogic/StaticLogicOps.cpp
test/Dialect/StaticLogic/errors.mlir
test/Dialect/StaticLogic/round-trip.mlir

For now, the pipeline is expected to be created after it has been
fully scheduled. Make the II required to reflect this, and add
documentation about this restriction, with a link to an open issue for
discussion.

[StaticLogic] Make II required; document the current restrictions.

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

Revert "[FIRRTL/LowerToHW] Reuse random bits in register initialization"

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/ExportVerilogInternals.h

Add a flag to `SharedEmitterState` that indicates whether processing currently occurs in a parallel region. Parts of the emission code that have to rely on sequential execution can then assert on this flag to make sure they actually are executed in a sequential region.
This requires adding a reference from the current `VerilogEmitterState` to the global `SharedEmitterState`, which tracks various aspects of the emission, including the parallelization flag. Thanks to C++ being an archaic language, this also means moving the entire `SharedEmitterState` declaration up in the file.
This is only intended to provide a safety feature, and should not change functionality at all. Most diff lines are due to code moving about.

[ExportVerilog] Add parallelization assertion; NFC

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/Comb/canonicalization.mlir

Fix an issue introduced in 3664712 where ult comparisons against a constant of the shape `0b111..111000..000` would be converted to an extract operation. The fold is based on the observation that in an icmp `x < cst`, where `cst` has this shape of a bunch of leading ones followed by all zeros, all values for `x` for which the comparison would return a 0 are the values that have all the upper bits set (those that are a one in the constant). Therefore the comparison is equivalent to checking if those upper bits are not all ones. The implementation in 3664712 erroneously checked the lower bits of the number.

[CombFolds] Fix issue in icmp ult/ugt extract fold

---

lib/Scheduling/SimplexSchedulers.cpp

This PR contains preparations to support more than one objective (row) in the simplex tableau.
This is an NFC in the sense that the different variants still minimize the start time of the `lastOp` given by the user.

[Scheduling] Prepare multi-objective support in simplex scheduler.

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Will close https://github.com/llvm/circt/issues/2291

[FIRRTL/FIRRTLFolds] Fix a bug in getConstant

---

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp

This commit changes the worklist data structure from a stack to a queue.
This enables us to avoid the unnecessary computation involving invalid values canonicalizations. This PR will fix the regression shown on https://github.com/llvm/circt/issues/2295

[FIRRTL/IMConstantProp] Change worklist data structure to queue

---

include/circt/Dialect/MSFT/MSFTAttributes.td
integration_test/Bindings/Python/dialects/msft.py
lib/Bindings/Python/MSFTModule.cpp
lib/Dialect/MSFT/ExportQuartusTcl.cpp
test/Dialect/MSFT/location.mlir

This adds a new FF primitive type in both ODS and the Python
bindings.

[MSFT] Add new PrimitiveType for flip-flop devices.

---

include/circt/Conversion/Passes.td
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp

This strategy simply combines the cycles and all strategies, using sequential buffers to break cycles, and transparent FIFO buffers on all other channels.

[Handshake] Add new buffering strategy allFIFO

---

lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp

The `EmitOMIR` pass has two places where the entire contents of a `FModuleOp` are walked just to find a single instance by name.
This PR adds a lookup table for instances by parent module and name, which is constructed during the initial, unavoidable walk of the IR that the pass has to perform anyway. The other walks are then removed in favor of a lookup into this table.
This also restructures the removal of temporary NLAs to have better scaling by building a set of instance ops with NLA participation and a set of all NLA symbol names to be removed, and then walking the set of instance ops and removing annotations referring NLAs in the second set.
Fixes a significant scaling problem in EmitOMIR.

[FIRRTL] Avoid inefficient module walks in EmitOMIR

---

frontends/PyCDE/src/pycde/module.py
frontends/PyCDE/src/pycde/support.py
frontends/PyCDE/src/pycde/system.py
frontends/PyCDE/test/design_partition.py
include/circt/Dialect/MSFT/MSFTOps.td
include/circt/Dialect/MSFT/MSFTPasses.td
lib/Bindings/Python/circt/dialects/_msft_ops_ext.py
lib/Dialect/MSFT/MSFTPasses.cpp
test/Dialect/MSFT/partition.mlir

Partial progress towards #2365.

[MSFT] Design partition support, part 1

---

lib/Dialect/MSFT/MSFTPasses.cpp

Another step towards #2365: sorting. If we `partition` modules in partial order by the use DAG, we only have to run through a partition pass once.
Since I don't think there's any way to test this on its own, I'll wait to merge until I've completed the "bubbling" pass since that's where we'll need it.

[MSFT] Sort modules based on partial order in instance DAG

---

lib/Dialect/Comb/CombFolds.cpp

The function `extractOperandFromFullyAssociative` will replace (and
free) the `subExpr` operation.  We need to know what the underlying
operation kind was, so we cache that information before replacing the
operation.

[CombFolds] Fix use-after-free in Mux folder

---

frontends/PyCDE/test/design_partition.py
include/circt/Dialect/MSFT/MSFTOps.td
lib/Dialect/MSFT/MSFTOps.cpp
lib/Dialect/MSFT/MSFTPasses.cpp
test/Dialect/MSFT/partition.mlir

One more step towards #2365. This PR adds the "bubble up" entities pass.

[MSFT] Design partition support, part 3

---

include/circt/Dialect/FIRRTL/InstanceGraph.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/InstanceGraph.cpp

Get files in the correct directory.

[FIRRTL] handle testbench dir annotation in combination with dut annotation

---

lib/Dialect/MSFT/MSFTPasses.cpp
test/Dialect/MSFT/partition.mlir

Move utility methods into new super class. Create a "framework" method
for updating instances.

[MSFT] [NFC] Refactor design partition pass to share code with the future clean up pass

---

include/circt/Dialect/FIRRTL/FIRRTLStructure.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/PrefixModules.cpp

Add helper utilities for updating the NLA.

[FIRRTL] Add utilities for updating NLA. NFC.

---

lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp
test/Dialect/FIRRTL/annotations.fir

The `circt.nonlocal` anchor was being populated with incorrect attribute. 
The attribute should be the `NonLocalAnchor` symbol.

[FIRRTL] Add the proper NLA anchor

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/canonicalization.mlir
test/Dialect/FIRRTL/lower-types.mlir

Revert "[FIRRTL] Add multibit_mux op and lowerings"

---

.github/workflows/nightlyIntegrationTests.yml
.github/workflows/shortIntegrationTests.yml

[`v10`](https://github.com/circt/images/releases/tag/v10) contains OR-Tools.

[CI] Use most recent integration test image.

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
test/Dialect/FIRRTL/grand-central-taps.mlir

Fix a bug in the GrandCentralTaps pass where non-local
annotations (NLAs) that are consumed by the pass do not remove their
global NLA and NLA path information left on each pass.  This fixes a bug
where the pass puts the IR in an invalid state with invalid NLAs.
I tested this by rebasing on top of #2461 and #2435 and an internal design didn't crash the NLA verifier added in #2461.
Note: this PR doesn't actually handle the NLAs, it just augments the existing behavior (removing NLA leaves) by garbage collecting the NLA operation and paths associated with consumed NLAs.  Currently, GCT Chisel APIs use absolute paths for data taps, but not for mem taps.  This patch tries to prefetch by cleaning up both flavors of NLAs (one that …

[FIRRTL] Garbage Collect Dead NLAs in GCT Taps

---

.github/workflows/nightlyIntegrationTests.yml
.github/workflows/shortIntegrationTests.yml

This reverts commit d2ff58a59cdcb0e925c47fe76c6afe3505e7c034.
See #2479.

Revert "[CI] Use most recent integration test image. (#2474)"

---

lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp

This changes the `getName(op)` function to return a `StringAttr` instead
of a `StringRef`, which saves the creation of an attribute.

[FIRRTL][LowerAnnotations] Fetch the StringAttr name of ops

---

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
test/Dialect/FIRRTL/inliner.mlir

Fix a bug in FIRRTL's ModuleInliner pass where non-local
annotations (NLAs) were not updated after inlining/flattening.  Correct
this behavior by rewriting NLAs after modules are inlined.
Additionally, rewrite NLAs which are made local by inlining/flattening.
TODO:
This is a commit necessary to get #2461 to not error on internal designs.
Each of the four figures below corresponds to one of the test cases in this PR.  This should help clarify exactly what manipulations are happening.  Blue arrows represent the module hierarchy.  Red arrows represent non-local annotations.  Each figure shows the circuit before (left) and after (right) running the `ModuleInliner`.

[FIRRTL] Update NLAs in Module Inliner

---

test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir
test/Dialect/FIRRTL/annotations.mlir
test/Dialect/FIRRTL/grand-central-errors.mlir
test/Dialect/FIRRTL/prefix-modules.mlir
test/Dialect/FIRRTL/test.mlir

Fix the missing symbols in lit tests for NonLocalAnchors.

[FIRRTL][Lit Tests] Fix lit tests, add missing symbols. NFC.

---

.github/workflows/buildAndTest.yml

[CI] Use lld, and bump circt-ci-build image for that.

---

include/circt/Scheduling/Utilities.h
lib/Scheduling/ASAPScheduler.cpp
lib/Scheduling/CMakeLists.txt
lib/Scheduling/Utilities.cpp

[Scheduling] Pull out utility for handling operations in topological order.

---

include/circt/Dialect/HW/HWAggregates.td
lib/Dialect/HW/HWOps.cpp
test/Dialect/HW/canonicalization.mlir

An array_get of an array_create with a constant index can just be the array_create operand at the constant index.

[HW] ArrayGetOp folder

---

lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
test/Dialect/FIRRTL/emit-omir.mlir

This commit fixes the target instance path according to the Extract Test Code logic.
1. If any target absolute path refers to a signal inside the Design Under Test, 
then truncate the absolute path to be rooted at the DUT module.
2. Special case for `dutInstance` , it should always be relative to the test bench. 
(SFC implementation in TestHarnessOMPhase.scala)
3. Add test cases for the above

[FIRRTL][OMIR] Fix target instance path

---

frontends/PyCDE/src/pycde/system.py
frontends/PyCDE/test/design_partition.py
lib/CAPI/Dialect/CMakeLists.txt
lib/CAPI/Dialect/MSFT.cpp

Register the canonicalizer pass and add `cleanup` call in PyCDE.

[MSFT] [PyCDE] Register the canonicalizer pass

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

This reverts commit 9e18fcb49071c0f0f265c64b20f8e730a2ef66f6.

Revert "[FIRRTL] Remove NLAs dropped by DontTouch (#2612)"

---

include/circt/Dialect/MSFT/CMakeLists.txt
include/circt/Dialect/MSFT/MSFT.td
include/circt/Dialect/MSFT/MSFTOpInterfaces.h
include/circt/Dialect/MSFT/MSFTOpInterfaces.td
include/circt/Dialect/MSFT/MSFTOps.h
include/circt/Dialect/MSFT/MSFTOps.td
lib/Dialect/MSFT/CMakeLists.txt
lib/Dialect/MSFT/MSFTOpInterfaces.cpp
lib/Dialect/MSFT/MSFTOps.cpp
lib/Dialect/MSFT/MSFTPasses.cpp

Interface for anything which needs to refer to a GlobalRefOp.

[MSFT] Introduce InstanceSpecific op interface

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp

Fix a large performance issue in Grand Central (Views/Interfaces) that
made this the dominant transform in large designs.  An expensive
algorithm was being used to find the lone instance of a module.  Change
this to use functions provided by the InstanceGraph.
On an internal design, this speeds up Grand Central by ~3x, gets it comparable to other transforms like `BlackBoxReader`, and should fix the scaling issues that Grand Central was facing.

[FIRRTL] Fix Grand Central Performance Issue

---

include/circt/Scheduling/Algorithms.h
lib/Scheduling/LPSchedulers.cpp
lib/Scheduling/TestPasses.cpp
test/Scheduling/or-tools/cyclic-problems.mlir

Quick'n'dirty formulation of the `CyclicProblem` as an integer linear program.

[Scheduling] Add an ILP-based solver for the CyclicProblem.

---

include/circt/Dialect/Comb/CombOps.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/Calyx/Transforms/CompileControl.cpp
lib/Dialect/Comb/CombFolds.cpp
lib/Dialect/Comb/CombOps.cpp
lib/Dialect/SV/SVOps.cpp
test/Dialect/Comb/canonicalization.mlir
test/Dialect/FIRRTL/SFCTests/complex-asserts.fir
test/Dialect/FIRRTL/SFCTests/complex-assumes.fir

[Comb] Canonicalize using De Morgan's laws

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/dedup.mlir

ExtModule deduping has an optimized version of NLA fixup where it
assumes that the ExtModule is the last element of the NLA, since there
can be no wires or other instances inside the body.  This function was
assuming that the NLA was a module reference and would accidentally take
port references and change them into a module references.
Properly managing port references in NLAs involves tracking the merging
or renaming of port symbols between the two modules.  Since this is a
bit tricky, the best thing to do is use the same NLA fixup code used on
regular modules.
This change also makes some port annotation tests stronger by using
different names between the two deduped modules: no code-changes were
required for this.

[FIRRTL][Dedup] Fix issue with NLAs on ExtModule ports

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/dedup.mlir

When hashing port types, the hasher was ignoring the `portType`
attribute of the operation, and using the block argument instead.  In
other words, it didn't make sense to hash the type twice.
This is a huge problem for `extmodules`, which do not have block
arguments, only a `portTypes` attribute. This changes the hasher
to use the `portTypes` attribute instead of hashing the block argument
types.

[FIRRTL][Dedup] Include port types in ext module hashing

---

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp
test/Dialect/FIRRTL/expand-whens-locations.mlir

This improves the location tracking while lowering the When operations
into Mux, Connect, and other operations.

[FIRRTL][ExpandWhens] Improve location tracking while lowering

---

lib/Dialect/LLHD/IR/LLHDOps.cpp
test/Dialect/LLHD/IR/inst-errors.mlir
test/Dialect/LLHD/IR/inst.mlir

[LLHD] Allow instantiation of hw.module

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp

Also fixed Dedup to handle StrictConnect.
Fixes #2763

[FIRRTL] Emitted PartialConnect instead of Connect for mismatched types

---

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
test/Dialect/FIRRTL/inliner.mlir

When a module is inlined into a parent module, the inlined body may
define symbols that have to be changed to not collide with existing
symbols in the parent module. When this happens, the code will find all
NLAs referencing this symbol and update the symbol referenced.
When a module is inlined into two locations, it is important that only the
NLAs referring to each location are updated with the renamed symbol at
that location.  There was a bug where we would update the symbol of all
NLAs to use the same symbol, one renaming overwriting the other.
This would cause a verifier error after the module InlinerPass:
```
'firrtl.nla' op  operation with symbol: #hw.innerNameRef<@ModuleName::@target> does not contain a reference to the NonLocalAnchor
```
This fixes the change by only updating the …

[FIRRTL][Inliner] Fix NLA filtering on symbol collision

---

include/circt/Dialect/LLHD/Simulator/State.h
lib/Dialect/LLHD/Simulator/Engine.cpp
lib/Dialect/LLHD/Simulator/State.cpp
lib/Dialect/LLHD/Simulator/Trace.cpp

Start the refactor of struct -> class type. 
And will cleanup a class at a time, after that will finish most part of [link_code](https://github.com/llvm/circt/pull/2673) .
To suit class type, turn the data members into private, add
get method, and remove unused method. Extra work needed for other
structs.

[LLHD] Refactor struct Time with class Time. 

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Conversion/ExportVerilog/hw-typedecls.mlir
test/Conversion/ExportVerilog/name-legalize.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir
test/Conversion/ExportVerilog/verilog-basic.mlir
test/Dialect/FIRRTL/SFCTests/data-taps-nlas.fir
test/Dialect/FIRRTL/SFCTests/data-taps.fir
test/Dialect/FIRRTL/SFCTests/signal-mappings.fir
test/firtool/firtool.fir

[ExportVerilog] Make module portlist one name per line, more like humans often do.

---

tools/firtool/firtool.cpp

This commit makes firtool  emit logs about parsing if
verbose-pass-executions option is enabled. Currently I just hard-coded
the logging messages to keep the implementation simple.
Example:
```
[firtool] Running fir parser
[firtool] -- Done in 0.056 sec
[firtool] ...
```
close https://github.com/llvm/circt/issues/2696

[firtool] Print parsing time with verbose-pass-executions option

---

include/circt/Dialect/LLHD/Simulator/State.h
lib/Dialect/LLHD/Simulator/Engine.cpp
lib/Dialect/LLHD/Simulator/State.cpp
lib/Dialect/LLHD/Simulator/Trace.cpp
lib/Dialect/LLHD/Simulator/signals-runtime-wrappers.cpp

Refactor struct Signal with the class type, add with basic class methods.
updateWhenChanged method can speed up compare to std::memcpy method.

[llhd] Refactor struct Signal with class Signal 

---

include/circt/Dialect/SV/SVOps.h
include/circt/Dialect/SV/SVStatements.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/SV/SVOps.cpp
lib/Dialect/SV/Transforms/HWLegalizeModules.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir
test/Dialect/SV/canonicalization.mlir

support x and z in case bit strings.  Also don't encode the default case with all z as that is a legal value for a case condition.

Improve SV Case handling

---

lib/Dialect/FIRRTL/Transforms/MergeConnections.cpp
test/Dialect/FIRRTL/merge-connections.mlir

MergeConnection pass should handle strict connects. Since MergeConnection pass will run in the last part of the pipeline, it should be fine to only look at strict connects.

[FIRRTL] [MergeConnection] Use StrictConnect

---

include/circt/Dialect/FIRRTL/FIRRTLStructure.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/inliner.mlir

Do lookups with a symbol table.

[NFC,FIRRTL] Use a symbol uses verifier for nla verification

---

lib/Dialect/FIRRTL/Transforms/RemoveInvalid.cpp
test/Dialect/FIRRTL/remove-invalid.mlir

This is a follow-up of cb5d0279 to replace aggregate invalid values
with zero constant.

[RemoveInvalid] Support Aggregate

---

docs/FIRRTLAnnotations.md
lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
test/Dialect/FIRRTL/emit-metadata.mlir

Fix the Retime module annotation.

[FIRRTL] Fix RetimeModule Annotation. NFC.

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp

I broke the [Windows build](https://github.com/llvm/circt/runs/6015600867?check_suite_focus=true) in https://github.com/llvm/circt/pull/2886, due to some type casting that MVSC doesn't like.
In that LLVM submodule bump, LLVM changed the SHA256 hashers to return
std::array<uint8_t, 32> instead of StringRefs. I attempted to avoid
dealing with this in FIRRTL's Dedup pass by explicitly converting the
array back into a string, but the way the casts were being done was
causing issues with MSVC.
Changing the code to work directly with the std::array is more direct
and efficient, and obviates the issues with casting.
This adds a custom implementation for the DenseMapInfo trait
specifically for std::array<uint8_t, 32>, which allows us to directly
use the SHA256 hash results as map keys.
I should …

[FIRRTL][Dedup] Directly use SHA256 byte array instead of converting to string.

---

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code.mlir

Change Extract Test Code (ETC) behavior to not perform extraction if the
module is already going to be otherwise extracted via a bind.  This
fixes an issue where certain simulators are unhappy if you bind into a
bound instance.
Fixes #2910.

[SV] Skip extraction of bound instances

---

include/circt/Dialect/HW/HWSymCache.h
lib/Dialect/MSFT/MSFTPasses.cpp

This commit adds a new way of populating the symbol cache by walking over all operations nested directly within the regions of a provided op. By doing so, the symbol cache can easily be primed by e.g., providing a `ModuleOp` which will add definitions for all `HWModuleOps` nested within.
I decided against using SymbolTable::walkSymbolTables here to ensure that only the regions nested directly below `top` are visited.

[HW] Add region-level definition initializer

---

include/circt/Dialect/SV/SVStatements.td
lib/Dialect/SV/SVOps.cpp
test/Dialect/SV/canonicalization.mlir

This PR implements trivial canonicalization to erase empty ifdefprocedural op.

[SV] Canonicalize empty IfDefProcedural op

---

frontends/PyCDE/src/pycde/constructs.py
frontends/PyCDE/src/pycde/module.py
frontends/PyCDE/src/pycde/pycde_types.py
frontends/PyCDE/src/pycde/support.py
frontends/PyCDE/src/pycde/value.py
frontends/PyCDE/test/systolic_array.py

Switching from dispatch functions to __new__. Also, moving `ValueOpView`
from a class to a function which returns a Value.

[PyCDE][NFC] Cleaning up Values and Types with __new__

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

Handle zero bit memory data fields correctly when flattening aggregate memory data.

[FIRRTL] Handle zero bit Memory data fields 

---

lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp
test/Dialect/FIRRTL/grand-central-signal-mappings.mlir

Fix a bug in Grand Central (GCT) signal mappings where a 0-width target
would crash compilation when either compiling the main circuit or the
subcircuit.  Avoid the issue entirely by dropping targets with a zero
width inside the GCT signal mappings pass.  This is done to work around
an issue with some SiFive designs where this pattern is used.

[FIRRTL] Drop GCT Signal Mapping 0-width targets

---

tools/firtool/firtool.cpp

Close https://github.com/llvm/circt/issues/2960

[firtool] Apply CLI options to `exportPm`

---

include/circt/Dialect/HW/ModuleImplementation.h
include/circt/Dialect/Handshake/Visitor.h
lib/Conversion/AffineToStaticLogic/AffineToStaticLogic.cpp
lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Dialect/FSM/FSMOps.cpp
lib/Dialect/HW/HWOps.cpp
lib/Dialect/HW/ModuleImplementation.cpp
lib/Dialect/Handshake/HandshakeOps.cpp
lib/Dialect/MSFT/MSFTOps.cpp
lib/Dialect/StaticLogic/StaticLogicOps.cpp
tools/circt-opt/circt-opt.cpp
tools/handshake-runner/Simulation.cpp

Revert "WIP - Bump llvm."

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-mem.mlir
test/Dialect/FIRRTL/lower-types.mlir
tools/firtool/firtool.cpp

Create a new pass to flatten the aggregate memory instead of doing it in `LowerTypes`

[FIRRTL] Add a memory lowering pass

---

lib/Dialect/Handshake/HandshakeOps.cpp

These are two very small changes and I would commit such things directly (when the CI is fine with them). 
I just wanted to ask if it is preferred to keep these different changes in separate commits or if I should squash them.

[Handshake] Improve handshake builders

---

include/circt/Dialect/HW/HWStructure.td
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/HW/HWOps.cpp
test/Dialect/HW/errors.mlir

[HW] HWModuleGeneratedOp use SymbolUserOpInterface; LowerToHW use instanceGraph

---

lib/Dialect/FIRRTL/Transforms/SFCCompat.cpp
test/Dialect/FIRRTL/sfc-compat.mlir

Add SFC CheckResets logic to the SFCCompat pass.  This checks that no
async reset initial value is a non-constant when looking through wires,
nodes, connects, and casts.  An error and pass failure is generated if
this fails.

[FIRRTL] Add CheckResets Behavior to SFCCompat

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp
test/Dialect/FIRRTL/lower-memory-errors.mlir
test/Dialect/FIRRTL/lower-memory.mlir
tools/firtool/firtool.cpp

This adds a pass to lower memory ops into instance of the new
FMemModuleOps.

[FIRRTL] Add LowerMemory pass

---

lib/Dialect/FIRRTL/Transforms/PrefixModules.cpp
test/Dialect/FIRRTL/prefix-modules.mlir

This adds the ability to prefix and potentially duplicate the FIRRTL
memory modules.  When the new memory lowering pipeline takes over, we
can remove the `mem.group` attribute which PrefixModules is using to
prevent later deduplication of memories.

[FIRRTL][PrefixModules] Prefix and duplicate FMemModule ops

---

lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp
test/Dialect/FIRRTL/lower-memory.mlir

~This PR depends on another PR, you can ignore the first commit.~
Dependent PR has been merged.
When the SFC lowers memories to ext modules, they also create a wrapper
module which just instantiates the external module.  MFC did not create
this wrapper module, since the extra level of abstraction did not seem
necessary. We have found that to be a drop in replacement for SFC, we
need these wrapper modules so that Module and Instance paths are all
identical. This commit adds wrapper modules following the style of the
SFC.
This commit also fixes how non-local annotations are handled by this
pass.  When the memory operation has a non-local annotation attached, we
need to move the annotation over to the new module, update the NLA to
point to the module instead of the instance, and put an NLA …

[FIRRTL][LowerMemory] Create wrapper module 

---

lib/Dialect/FIRRTL/Transforms/InferResets.cpp
test/Dialect/FIRRTL/infer-resets.mlir

0-length vectors may never see a (useless) connect to invalid, so if we are having a problem with an undriven net, check if it's a useless 0-length vector backed net and force it to "sync"

Handle 0-length vectors in inferreset without connects to invalid

---

lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp
test/Dialect/FIRRTL/lower-memory.mlir

This changing the memory op lowering to store all annotations that were
attached to the MemOp on the new instance op, instead of on the new
memory module op.  This is needed because OMIR trackers distinguish
their type based on the operation they are attached to.

[FIRRTL][LowerMemory] Store MemOp annotations on the instance

---

docs/RationaleHW.md
lib/Dialect/HW/HWAttributes.cpp
test/Dialect/HW/parameters.mlir

Maybe I need simplify the code like
```
if (auto rhs = operands[1].dyn_cast<IntegerAttr>()) {
if (rhs.getValue().isZero())
return operands[0];
}
```
to sth like
```
if ( check_simplify(operands, [](auto cst) { return cst.isZero();}))
return operands[0];
```
or we can change in some function before.
what to hear some more advice.

[HW Params] Implement common factor elimination for SHR, DIV and MOD.

---

lib/Dialect/FIRRTL/Transforms/LowerCHIRRTL.cpp
test/Dialect/FIRRTL/lower-chirrtl.mlir

Sequential memory read ports have enable inference which sets the enable
high at the location the address is written to.  We missed that this enable
inference is only active when the address is something with a name.
This adds a more complicated check to turn on enable inference for ports
which verifies that the value used is a port, wire, reg, regreset, or
node.
h/t @fabianschuiki  thanks for pointing out this issue!

[FIRRTL][LowerCHIRRTL] Fix enable inference for aggregates

---

include/circt/Dialect/FIRRTL/NLATable.h
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp

Use NLATable analysis instead of relying on NLA breadcrumbs.

[FIRRTL] Update ModuleInliner to use NLATable analysis

---

include/circt/Dialect/HW/HWStructure.td
include/circt/Dialect/HW/HWSymCache.h
include/circt/Dialect/HW/HWTypes.h
include/circt/Dialect/HW/HWTypesImpl.td
include/circt/Dialect/MSFT/ExportTcl.h
include/circt/Dialect/SV/SVOps.h
include/circt/Dialect/SV/SVStatements.td
include/circt/Dialect/SV/SVTypeDecl.td
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/ExportVerilogInternals.h
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp
lib/Dialect/HW/HWOps.cpp
lib/Dialect/HW/HWTypes.cpp
lib/Dialect/HW/Transforms/HWSpecialize.cpp
lib/Dialect/MSFT/MSFTPasses.cpp
lib/Dialect/SV/SVOps.cpp
lib/Dialect/SV/Transforms/SVExtractTestCode.cpp

Factoring out some noise from #3101.

[HW][NFC] Rename SymbolCache -> HWSymbolCache

---

include/circt/Dialect/MSFT/DeviceDB.h
lib/CAPI/Dialect/MSFT.cpp
lib/Dialect/MSFT/DeviceDB.cpp

Add support for LocationVectorAttr to PlacementDB. Tests in subsequent
PRs.

[MSFT] Teach PlacementDB about LocationVectors

---

frontends/PyCDE/src/pycde/devicedb.py
frontends/PyCDE/src/pycde/instance.py
frontends/PyCDE/test/compreg.py
lib/Bindings/Python/MSFTModule.cpp
lib/CAPI/Dialect/MSFT.cpp
lib/Dialect/MSFT/DeviceDB.cpp

Use `None` to indicate that the location is not specified.

[PyCDE] [Python] Teach `LocationVector` bindings about 'None' for optional locations

---

include/circt/Dialect/FIRRTL/NLATable.h
lib/Dialect/FIRRTL/NLATable.cpp

[FIRRTL] NLATable: fixup and simplify a little, comments for doxygen

---

docs/FIRRTLAnnotations.md

This fixes a couple of small formatting issues which stand out more
when looking at the generated webpage.

[FIRRTL] Fix formatting in FIRRTLAnnotations.md

---

include/circt/Dialect/FSM/FSMOps.td
lib/Dialect/FSM/FSMOps.cpp

[FSM] Fix various operation builders

---

include/circt/Dialect/FIRRTL/NLATable.h

Update few comments in`NLATable.h`.

[FIRRTL] Update comments in NLATable header. NFC.

---

include/circt/Dialect/FIRRTL/NLATable.h
lib/Dialect/FIRRTL/NLATable.cpp
lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp

This commit refactors the code for `NLATable`, and adds necessary comments.

[FIRRTL] Refactor NLATable analysis utilities and comments. NFC.

---

include/circt/Dialect/FSM/FSMGraph.h
lib/Dialect/FSM/FSMGraph.cpp

Note: state use-tracking is modelled after `HW/InstanceGraphBase.h`.
Discussion in #3138.

[FSM] Elaborate FSMGraph with builder capabilities

---

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
test/Dialect/FIRRTL/SFCTests/constantProp.mlir
test/Dialect/FIRRTL/imconstprop.mlir

[FIRRTL][IMConstProp] unique constants in module entry

---

include/circt/Dialect/Calyx/CalyxLoweringUtils.h
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Conversion/StaticLogicToCalyx/StaticLogicToCalyx.cpp
lib/Dialect/Calyx/Transforms/CMakeLists.txt
lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp

Continued efforts on #2988, #3235.

[SCFToCalyx] [StaticLogicToCalyx] Share passes.

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp
test/Dialect/FIRRTL/canonicalization.mlir
test/firtool/memory.fir
test/firtool/name-preservation.fir

Reverts llvm/circt#3246
This change led to some issues that are being debugged.

Revert "[FIRRTL] Cannonicalize wires to nodes"

---

include/circt/Support/BackedgeBuilder.h
lib/Support/BackedgeBuilder.cpp

A few tweaks for the `BackedgeBuilder`.

[Support] A few BackedgeBuilder improvements

---

lib/Dialect/LLHD/IR/LLHDTypes.cpp
lib/Dialect/Moore/MooreTypes.cpp
lib/Dialect/SV/SVTypes.cpp

Fixes an include issue when building python bindings
https://github.com/llvm/llvm-project/commit/70f1021431a625985c00141329c359babecc2c29

Bump LLVM to b422dac24

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

[FIRRTL] Better node bypass in canonicalize.

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

[FIRRTL] Remove old canonicalization patterns and fix NodeBypass

---

frontends/PyCDE/src/pycde/pycde_types.py
frontends/PyCDE/src/pycde/value.py
lib/Bindings/Python/HWModule.cpp
lib/Bindings/Python/circt/dialects/_sv_ops_ext.py
lib/Bindings/Python/circt/support.py

Also fixes a few issues with the other SV ops, as well as adding support for ReadInOutOp

[PyCDE][Python] Add support for InOutType

---

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
test/Dialect/FIRRTL/inliner.mlir

Primarily focused on addressing issue with deleting NLA's that end in a module (FlatSymbolRefAttr).
Fixes #3334 .

[FIRRTL] ModuleInliner: new NLA support

---

include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/DropName.cpp
test/Dialect/FIRRTL/drop-name.mlir

Add statistic for counting names converted to "droppable".
While visiting, minor fixup to the test now that droppable is the default.

DropNames: Add statistic, fixup test

---

frontends/PyCDE/src/pycde/pycde_types.py

Overriding __new__, while slick, was too complex. This is the suggested
way to do it, so make things simpler.

[PyCDE] Switch back to normal Type function

---

lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp
lib/Dialect/FIRRTL/Transforms/FlattenMemory.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp
lib/Dialect/FIRRTL/Transforms/InferReadWrite.cpp
lib/Dialect/FIRRTL/Transforms/InferResets.cpp
lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/MergeConnections.cpp
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
lib/Dialect/FIRRTL/Transforms/RemoveUnusedPorts.cpp

No need for copying here, although not sure it's a big deal.  NFCI.

[FIRRTL] for (auto x : llvm::enumerate(..)) -> for (const auto &x : ...)

---

frontends/PyCDE/src/pycde/instance.py
frontends/PyCDE/test/instances.py

Provides an iterator through which a user can iterate all the indexes
for a particular appid name.

[PyCDE] [AppID] Iterate through appids of a given name

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/test.mlir

[FIRRTL] Change "lowerToBind" Attribute from boolean to unit

---

integration_test/Bindings/Python/dialects/seq.py
lib/Bindings/Python/circt/support.py

[Python] Forward "attributes" attr from an operation in NamedValueOpView

---

lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
test/Dialect/SV/hw-memsim.mlir

Fix an issue in the `HWMemSimImpl` pass where latencies would not be properly modeled for read-write ports. Before this fix, the pass would pick the larger out of the read and write latency and assemble a delay pipeline for the read and write portion of the memory with that latency. This leads to wrong behaviour if the two latencies are different.
This patch instead considers the read and write latency separately. It takes the minimum of both latencies to construct a common delay pipeline prefix for the read and write half, and then adds the remaining pipeline stages to the read and write paths separately.
Added two tests that check for correct behaviour in case of excessive read and write latencies.

[HWMemSimImpl] Fix latencies for read-write ports

---

lib/Conversion/HWToLLHD/HWToLLHD.cpp

When putting the conversion pattern in an anonymous namespace, they cannot interfere with other conversion patterns in other lowering passes. Also move them to the front so that we do not have to add a forward declaration for each one of them.

[HWToLLHD] Put conversion patterns in namespace

---

include/circt/Dialect/LLHD/IR/BitwiseOps.td
include/circt/Dialect/LLHD/IR/ExtractOps.td
include/circt/Dialect/LLHD/IR/LLHD.td
include/circt/Dialect/LLHD/IR/SignalOps.td
include/circt/Dialect/LLHD/IR/StructureOps.td
lib/Conversion/HWToLLHD/HWToLLHD.cpp
lib/Conversion/LLHDToLLVM/LLHDToLLVM.cpp
lib/Dialect/LLHD/IR/LLHDOps.cpp
lib/Dialect/LLHD/Simulator/Engine.cpp
lib/Dialect/LLHD/Transforms/EarlyCodeMotionPass.cpp
lib/Dialect/LLHD/Transforms/MemoryToBlockArgumentPass.cpp
lib/Dialect/LLHD/Transforms/ProcessLoweringPass.cpp
lib/Dialect/LLHD/Transforms/TemporalRegions.cpp

[LLHD] Use prefixed accessors

---

test/Dialect/LLHD/Canonicalization/probeCSE.mlir

CSE and DCE is allowed inside entities or within the same temporal region in procs, but CSEing two probes in different temporal regions is forbidden.

[LLHD] Fix probeCSE test

---

test/circt-reduce/annotation-remover.mlir
test/circt-reduce/connect-source-operand-forward.mlir
test/circt-reduce/issue-3555.mlir
test/circt-reduce/memory-stubber.mlir
test/circt-reduce/node-symbol-remover.mlir
test/circt-reduce/port-pruner.mlir
test/circt-reduce/trivial.mlir
tools/circt-reduce/Tester.cpp
tools/circt-reduce/Tester.h
tools/circt-reduce/circt-reduce.cpp

[circt-reduce] Invert test exit code requirement

---

lib/Conversion/HWArithToHW/HWArithToHW.cpp
test/Conversion/HWArithToHW/test_basic.mlir

As promised in https://github.com/llvm/circt/pull/3546, here is the follow up PR that provides the lowering patterns as well as tests.
CC @jopperm @mortbopet

[HWArithToHW] Lower Cast,Constant,Add,Sub,Mul,Div

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir

Fix https://github.com/llvm/circt/issues/3606

[PrepareForEmission] Ensure assignment is in toplevel in reuseOfExistingInOut

---

docs/Dialects/SSP/RationaleSSP.md
include/circt/Dialect/SSP/SSPAttributes.td
include/circt/Dialect/SSP/SSPOps.td
lib/Dialect/SSP/SSPOps.cpp
test/Dialect/SSP/errors.mlir
test/Dialect/SSP/roundtrip.mlir

This PR introduces the `OperationOp`, which represents a vertex and its incoming edges in the dependence graph.

[SSP] Model (scheduling) operations and dependences.

---

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
test/Dialect/FIRRTL/inliner.mlir

This fixes https://github.com/llvm/circt/issues/3630, the crash in `ModuleInliner`. 
`ModuleInliner` was not handling the case when both the child and parent modules are inlined, and both the child and parent modules are multiply instantiated.
This results in multiple copies of the child module's body. If the body has references to some non-local annotations, depending on the inlining context only some of the hierarchical paths must be valid after inlining.
This PR maintains a set of hierarchical paths that are active based on an inlining context. The inlining context is defined as the sequence of `Instance` ops that the inlining algorithm is currently traversing. 
Any hierarchical path update is based on the set of active paths only. This filters out hierarchical paths that did not exist …

[FIRRTL][ModuleInliner] Handle inline context properly for HierPath update

---

docs/Dialects/SSP/RationaleSSP.md
include/circt/Dialect/SSP/PropertyBase.td
include/circt/Dialect/SSP/SSPAttributes.h
include/circt/Dialect/SSP/SSPAttributes.td
lib/Dialect/SSP/CMakeLists.txt
test/Dialect/SSP/roundtrip.mlir

This PR defines a framework for ODS attributes that represent scheduling properties, and includes property definitions for `Problem`, `CyclicProblem` and `SharedOperatorsProblem`.

[SSP] Add first batch of properties.

---

include/circt/Dialect/HW/HWAggregates.td
lib/Dialect/HW/HWOps.cpp
test/Dialect/HW/canonicalization.mlir

Canonicalized two injects to the same field to a single inject of the second value.
Canonicalized an extract of an inject to the injected value.

[HW] Added simple canonicalizers to `hw.struct_inject` and `hw.struct_extract`

---

docs/Dialects/Seq/RationaleSeq.md

Draft documentation for the `seq.firreg` register, to be adjusted as its design evolves.

[Docs][Seq] Documented `seq.firreg` in the `seq` documentation

---

include/circt/Dialect/FIRRTL/FIRRTLAttributes.td
include/circt/Dialect/FIRRTL/InnerSymbolTable.h
lib/Dialect/FIRRTL/FIRRTLAttributes.cpp
lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp

Add utils to `InnerSymAttr`  required for adding support to ports.
Splits changes from https://github.com/llvm/circt/pull/3582

[FIRRTL] Add utils to InnerSymAttr. NFC.

---

utils/build-release.sh
utils/equiv-rtl.sh
utils/get-capnp.sh
utils/get-iverilog.sh
utils/get-or-tools.sh
utils/get-verilator.sh
utils/update-docs-dialects.sh

Fixes use on NixOS.
(PR mostly to ensure nothing in CI has issues with the change)

utils/*.sh: Prefer /usr/bin/env bash for portability.

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR.mlir

Fix a bug in LowerXMR to handle ports correctly.

[FIRRTL][LowerXMR] Handle xmr to ports correctly

---

lib/Dialect/FIRRTL/Transforms/InferResets.cpp
test/Dialect/FIRRTL/infer-resets-errors.mlir
test/Dialect/FIRRTL/infer-resets.mlir

[FIRRTL][InferResets] Handle RefType, send, resolve.

---

integration_test/Dialect/Handshake/cocotb_driver.py
integration_test/Dialect/Handshake/conditional_modification/conditional_modification.mlir
integration_test/Dialect/Handshake/task_pipelining/task_pipelining.mlir
integration_test/Dialect/Handshake/tuple_packing/tuple_packing.mlir
integration_test/lit.cfg.py

This is similar to https://github.com/llvm/circt/pull/3725 and fixes #3736
In a next step, it might make sense to factor out common parts into a shared python file.

[Handshake] Use cocotb-test as test driver

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp

[FIRRTL] Fix use of attribute from erased op.

---

include/circt/Dialect/FIRRTL/FIRRTLUtils.h
lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
lib/Dialect/FIRRTL/Transforms/InferResets.cpp
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp

Update various TypeSwitch patterns to use these, simplify.
Credit to @seldridge for the suggestion!

[FIRRTL][Utils] Add getBaseType, mapBaseType helpers.

---

docs/RationaleSymbols.md

Also briefly introduce the InnerSymAttr.

[docs] Add text describing the inner symbol classes/traits/verif.

---

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp

Add helpers to keep AnnoTarget caches updated.

[FIRRTL] Keep the Annotation Target Caches updated

---

integration_test/Dialect/Handshake/conditional_modification/conditional_modification.py
integration_test/Dialect/Handshake/helper.py
integration_test/Dialect/Handshake/max/max.py
integration_test/Dialect/Handshake/multiple_loops/multiple_loops.py
integration_test/Dialect/Handshake/task_pipelining/task_pipelining.py
integration_test/Dialect/Handshake/tp_memory/tp_memory.py
integration_test/Dialect/Handshake/tuple_packing/tuple_packing.py

This commit moves dut initialization to the helpers and additionally removes unnecessary imports.

[Handshake][lit] Cleanup cocotb helper and tests

---

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
test/Dialect/FIRRTL/imconstprop-aggregate.mlir

Fix https://github.com/llvm/circt/issues/3820
Currently aggregate values are marked overdefined only when
connection propagations. The current implementation is causing a bug with aggregate
ports since currently propagation through aggregate values are not
implemented. Hence, this commit fixes the issue by marking aggregate
values as overdefined.

[IMCP] Mark aggregate overdefined firstly

---

lib/Dialect/Handshake/Transforms/Buffers.cpp

Rewrites the cycle detection algorithm to use proper DFS that checks if nodes were already visited. 
Instead of writing a large test that showcases this fix, it makes sense to use the integration tests provided as part of #3825.

[Handshake] Fix buffer insertion cycle detection

---

include/circt/Conversion/HWArithToHW.h
lib/Conversion/HWArithToHW/HWArithToHW.cpp
test/Conversion/HWArithToHW/test_basic.mlir

... which is required when performing rewrites where backedges may be present.

[HWArith] Add missing type materialization

---

include/circt/Dialect/HW/HWOps.h
include/circt/Support/BackedgeBuilder.h
lib/Conversion/CalyxToHW/CalyxToHW.cpp
lib/Dialect/HW/HWOps.cpp

With [17fb35f](https://github.com/llvm/circt/commit/17fb35fe12046009cb2511f628c30a296862acf7) (hopefully) fixing the original issue, this patch should now be safe to recommit.

[HW] Re-add reverted review comments to new HWModule builder

---

include/circt/Dialect/FIRRTL/FIRRTLVisitors.h

Add FIRRTL visitors for RefSend and RefResolve.

[FIRRTL] Add visitors for RefSend and RefResolve. NFC

---

lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp
test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/lower-types-errors.mlir
test/Dialect/FIRRTL/lower-types.mlir

Add test, update existing tests that triggered verification failures as a result of this change.

[FIRRTL] Verify FModuleLike's have unique port names.

---

lib/Dialect/FIRRTL/FIRRTLOps.cpp

Update the logic to get the memory port kind. Match bundle field names to get the PortKind. 
If fields are `addr`, `en`, `clk`, `data`, then it is a Read port
If fields are `addr`, `en`, `clk`, `data`, `mask` then it is a Write port
If fields are `addr`, `en`, `clk`, `wdata`, `wmask`, `rdata`, `wmode` then it is a ReadWrite port

[FIRRTL] Get memory port kind based on fields. NFC

---

lib/Dialect/FIRRTL/Transforms/LowerCHIRRTL.cpp
test/Dialect/FIRRTL/lower-chirrtl.mlir

Lower the `CHIRRTL` memory debug port to `FIRRTL` memory debug ports.

[FIRRTL] Lower chirrtl memory with debug ports

---

include/circt/Dialect/ESI/ESIPasses.h
lib/Dialect/ESI/ESIPasses.cpp
lib/Dialect/ESI/ESIServices.cpp

... needed for HLSTool to instantiate ESI passes.

[ESI] Publicly expose passes

---

lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
test/Conversion/HandshakeToHW/test_sync.mlir

This adds the lowering for the newly introduced `SyncOp`.

[HandshakeToHW] Add support for `SyncOp`

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp

This PR fixes an issue of logic operation legalizations. Previously an iterator is managed while executing legalizations, but it is very difficult to properly manage the iterator since a lot of operations are inserted into various places. To fix the issue, this separates the legalization into another loop which is executed only when in a procedural region to move logic operations to valid points.

[PrepareForEmission] Fix logic op position legalization

---

lib/Dialect/Handshake/HandshakeOps.cpp
test/Dialect/Handshake/func.mlir

Fixes https://github.com/llvm/circt/issues/3970

[Handshake] Fix external func parsing

---

lib/Conversion/ExportVerilog/PrepareForEmission.cpp

This fixes UAF which caused non-deterministic results. `lowerAlwaysInlineOperation` erases an operation with no user, but it was escaped into `visitedAlwaysInlineOperations`. This fixes the issue by hoisting the erasion from lowerAlwaysInlineOperation to top-level loop.

[PrepareForEmission] Fix UAF

---

include/circt/Dialect/Handshake/HandshakePasses.h
lib/Dialect/Handshake/Transforms/Buffers.cpp
test/Dialect/Handshake/compose-buffers.mlir

This commit exposes a new `bufferRegion` function that is independent of `handshake.func`. Additionally, it cleans up some of the code in the buffer insertion.

[Handshake] Expose bufferRegion for other users

---

include/circt/Dialect/Calyx/CalyxLoweringUtils.h
include/circt/Dialect/FIRRTL/FIRParser.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/NLATable.h
include/circt/Dialect/LLHD/Simulator/State.h
include/circt/Scheduling/Problems.h
lib/Analysis/DependenceAnalysis.cpp
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
lib/Dialect/ESI/capnp/Schema.cpp
lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp
lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
lib/Dialect/FIRRTL/Transforms/LowerCHIRRTL.cpp
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
lib/Dialect/FIRRTL/Transforms/PrefixModules.cpp
lib/Dialect/FIRRTL/Transforms/WireDFT.cpp
test/Dialect/FIRRTL/prefix-modules.mlir

After finding a few, searched with a hacky regex.

[NFC] Comment fixups, mostly re:duplicate words

---

integration_test/Dialect/Handshake/buffer_initial_values/buffer_initial_values.mlir
integration_test/Dialect/Handshake/helper.py
lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
test/Conversion/HandshakeToHW/test_buffer.mlir
test/Conversion/HandshakeToHW/test_cmerge.mlir
tools/hlstool/hlstool.cpp

+a small modification to `_findPort` in the handshake test driver to comply with ESI port naming.

[HandshakeToHW] Fix merge, control merge, buffer

---

integration_test/Target/ExportSystemC/basic.mlir
lib/Target/ExportSystemC/Patterns/SystemCEmissionPatterns.cpp
test/Target/ExportSystemC/basic.mlir

[ExportSystemC] Add support for NewOp, DeleteOp, and DestructorOp

---

lib/Scheduling/ChainingSupport.cpp
test/Scheduling/chaining-problems.mlir

See included regression test:
- A misplaced code block (🤦‍♂️) led to missing chain-breaking edges from predecessors with multi-cycle operators, and duplicate edges otherwise.
- When computing an op's start-time-in-cycle, I incorrectly included the SITC of multi-cycle predecessors.

[Scheduling] Fix chaining support for multi-cycle operators.

---

.github/workflows/buildAndTest.yml
.github/workflows/nightlyIntegrationTests.yml
.github/workflows/shortIntegrationTests.yml
.github/workflows/trackLLVMChanges.yml
.github/workflows/uploadBinaries.yml
CMakeLists.txt
test/CMakeLists.txt

Works for me on my normal build configurations, let's see about CI and elsewhere!

Fixes to build system to support unittests again, add to CI

---

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp

The HashTableStack iterator was reusing the underlying data structure's (MapVector) iterator.  The `HashTableStack::end()` function would create a default constructed iterator which was not tied to any `MapVector`.  When comparing the default constructed iterator to a real iterator on Windows, this would crash.
Running a Windows test on this branch here: https://github.com/llvm/circt/actions/runs/3245347009

[FIRRTL][ExpandWhens] Add iterator to `HashTableStack`

---

lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Dialect/Seq/firreg.mlir

This PR applies mux2if transformation to arrays. If a next value is an array create, then we decompose it into individual elements.

[LowerSeqToSV] Apply mux2if transformation to arrays

---

integration_test/EmitVerilog/lint.mlir
lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

Lower `hw.array_create` to an array replication operator if elements are uniform.

[HW] Pretty-print uniform arrays

---

include/circt/Dialect/Interop/Interop.td
include/circt/Dialect/Interop/InteropOps.h
lib/Dialect/Interop/InteropOps.cpp
test/Dialect/Interop/basic.mlir
test/Dialect/Interop/errors.mlir

The 4 interop operations described in the dialect rationale.

[Interop] Introduce unrealized interop operations

---

lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp

Add a new constructor to create a `Node` with `Operation*`.

[FIRRTL][CheckCombCycles] Refactor implementation

---

include/circt/Dialect/SystemC/CMakeLists.txt
include/circt/Dialect/SystemC/Passes.td
include/circt/Dialect/SystemC/SystemCPasses.h
include/circt/InitAllPasses.h
lib/Dialect/SystemC/CMakeLists.txt
lib/Dialect/SystemC/Transforms/CMakeLists.txt
lib/Dialect/SystemC/Transforms/PassDetails.h
lib/Dialect/SystemC/Transforms/SystemCLowerInstanceInterop.cpp
test/Dialect/SystemC/Transforms/interop.mlir
tools/circt-opt/CMakeLists.txt

A first version for lowering the `systemc.interop.verilated` operation.

[SystemC] Lower Interop pass for verilated operation

---

include/circt/Dialect/SystemC/SystemCExpressions.td
include/circt/Dialect/SystemC/SystemCTypes.h
lib/Dialect/SystemC/SystemCOps.cpp
lib/Dialect/SystemC/SystemCTypes.cpp
test/Dialect/SystemC/canonicalize.mlir

Folding unnecessary converts leads to more beautiful and more efficient SystemC code.

[SystemC] ConvertOp folder

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
test/Dialect/FIRRTL/lowerXMR.mlir

This commit adds support to generate XMR with opaque internal paths into a module.
A combination of `verbatim.expr` and `ref.send` is used to encode an internal path into a module. `LowerXMR` must generate the correct hierarchical path for such internal paths into a module.
If an internal path (for example `random.path.inside`) exists inside a module `Foo`, the hierarchical path must end at the op that instantiates `Foo`, and the `random.path.inside` must be appended to it. This avoids any temporary `NodeOp` or wires inside the module `Foo`.
This replaces the requirement for a new op as discussed in https://github.com/llvm/circt/pull/4196

[FIRRTL][LowerXMR] Lower internal path into a module

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

[ExportVerilog] Don't emit a constant if it has zero width

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
test/Dialect/FIRRTL/dedup.mlir

When we dedup modules, we combine the annotations from both. Since DontTouch is a sticky annotation and there is no point in having more than one, we tried to only keep one copy of the `DontTouch` annotation. This logic did not take into account that the annotation might be targeting a specific field of an aggregate, and could end up deduplicating the `DontTouch` annotations which targeted different fields.
This PR uses a set of annotations to take into account the `fieldID` of the annotations.  It also started ripping out the `circt.nonlocal` field from any `DontTouch` annotation, which has no effect on the annotation, and just hurts our ability to deduplicate these annotations.

[FIRRTL][Dedup] Fix DontTouch annotation handling

---

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
test/Dialect/FIRRTL/imdce.mlir

Dead memories are now handled identically to wires and are eliminated if they are part of unreachable logic cycles, unless they are annotated with a DontTouch annotation.

[IMDCE] Allow dead memories to be eliminated

---

include/circt/Dialect/SSP/SSPOps.h
include/circt/Dialect/SSP/SSPOps.td
lib/Dialect/SSP/SSPOps.cpp

[SSP] Extract helper to access linked operator type, NFC.

---

lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Dialect/Seq/firreg.mlir

Change LowerSeqToSV to guarantee that an asynchronously reset FIRRTL register that is undriven is given a self-assignment.  This avoids lint issues where this would emit _without_ a driver and cause this to be inferred as a latch.

[LowerSeqToSV] Self-assign of Async Reset FIR Reg

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp
test/Dialect/FIRRTL/dedup.mlir
test/Dialect/Seq/firreg.mlir

This backports two changes to sifive-1.22:
* https://github.com/llvm/circt/pull/4273
* https://github.com/llvm/circt/pull/4285

Backport changes to sifive-1.22

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

As a bonus, hit another invalidvalue canonicalizer.

[FIRRTL] Move more canonicalizations to patterns.

---

lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp

Print information about all processed problems, even if they're easily "solved".
If in same module, the debug print will not contain information about LCA and instance paths as there's no reason to compute them.

[LowerAnnotations][WiringProblem] minor reorg, debug print all problems.

---

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp

While visiting add small check before dereferencing an Optional.

[GrandCentralTaps] Move (new) MemTaps to WiringProblem.

---

include/circt/Conversion/Passes.td
lib/Conversion/HWArithToHW/CMakeLists.txt
lib/Conversion/HWArithToHW/HWArithToHW.cpp
test/Conversion/HWArithToHW/test_basic.mlir

[HWArith] Support signedness values inside sv wire/reg/read_inout

---

frontends/PyCDE/src/pycde/constructs.py
frontends/PyCDE/test/test_constructs.py

A `NamedWire` is guaranteed to appear in the resulting verilog. It precludes some optimizations, so it should be used sparingly.

[PyCDE] NamedWire construct

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLUtils.h
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Make some constant folds which were limited by type in firrtl folders also be canonicalizers which can handle the size and type issues in firrtl.

[FIRRTL] Extend some constant folds.

---

lib/Conversion/MooreToCore/MooreToCore.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/SV/Transforms/GeneratorCallout.cpp

This is the latest as of 12/7/22 afternoon. This includes a few breaking changes:
* https://github.com/llvm/llvm-project/commit/c589730ad5286fc784b8aacf2f0214149603f312
* https://github.com/llvm/llvm-project/commit/e748db0f7f0971dc258c6631ae1fb0a38cfdf9dd
* https://github.com/llvm/llvm-project/commit/b74192b7ae0781200be7df40e673d4f918b32587

Bump LLVM to f6b1d88527886683a67bebf27df3ad626fa3940e.

---

docs/PyCDE.md
frontends/PyCDE/python/requirements.txt

Updated the 'Manual Compile' section of PyCDE.md to reflect steps to accomplish a unified build via CMake.

[Doumentation][PyCDE] Update PyCDE.md 'Manual Compile' section

---

include/circt/Dialect/FIRRTL/FIRRTLAttributes.td
include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLDialect.cpp
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
test/Dialect/FIRRTL/imconstprop.mlir
test/Dialect/FIRRTL/test.mlir
test/firtool/chirrtl.fir

With some better node handling thrown in for good measure.

[FIRRTL][IMCP] Lower unconnected registers to invalids

---

include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
include/circt/Dialect/SV/SVExpressions.td
include/circt/Dialect/SV/SVTypes.td
include/circt/Dialect/SV/SVVisitors.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/ExportVerilog/ExportVerilogInternals.h
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp
lib/Dialect/SV/SVOps.cpp
test/Conversion/ExportVerilog/sv-dialect.mlir
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Dialect/FIRRTL/lower-intrinsics.mlir

Add a string type, string constant op, and system functions.  System functions are things like $value$plusargs.  Lower firrtl intrinsics to these where appropriate.

[SV] String types and system functions

---

.github/workflows/assign-reviewers.yml

[.github] Use ubuntu-latest in assign-reviewers CI

---

tools/llhd-sim/CMakeLists.txt

We already build+install its libraries, include tool too.

[LLHD] Install llhd-sim utility (when enabled).

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

This implements lowering of aggregate constant op that is not 1d vector.

[LowerToHW] Lower aggregate constant

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

Context for this is in #4112. Resolves #4112.
For all analog connections which are only internal to a module, generate a wire for that connection, rather than the alias/assign construct.
I'm not completely sure that I've implemented this properly. When running the tests that I added, I saw that the output from the tests looked like it had some extra statements that I didn't expect. Perhaps this is just due to me not being so familiar with the expected MLIR output. For example, for one test, the input looks like this:
```mlir
firrtl.module @AnalogMergeThree() {
%result_iInA = firrtl.instance iInA @AnalogInModA(in a: !firrtl.analog<8>)
%result_iInB = firrtl.instance iInB @AnalogInModB(in a: !firrtl.analog<8>)
%result_iOut = firrtl.instance iOut @AnalogOutModA(out a: !firrtl.analog<8>) …
```

[FIRRTL] Simplify internal Analog connections

---

tools/firtool/firtool.cpp

This pass should generally be run as late as possible so it can clean up after all prior passes. It currently runs just before the BlackBoxReader pass, which happens to leave behind some dead symbols.
This moves it as late as possible: just before InnerSymbolDCE. While there is no new integration test of the firtool pipeline with this change, it has been shown to remove symbols that would otherwise remain.

[firtool] Run SymbolDCE as late as possible. (#4504)

---

test/Dialect/FIRRTL/check-comb-cycles.mlir

Properly format the lit tests.

[FIRRTL][CheckCombLoops] Reformat the lit tests. NFC

---

frontends/PyCDE/integration_test/pytorch/dot_prod_system.py
lib/Dialect/Handshake/HandshakeOps.cpp

... As well as adding aa missing argument to the PyCDE test which triggered this bug.
Fixes #4442.

[Handshake] Fix iteration-over-modified-range bug in ControlMergeOp canonicalizer

---

frontends/PyCDE/src/pycde/constructs.py
frontends/PyCDE/test/test_constructs.py

A 'control register' is a single bit register which gets set and reset based on pulses. Asserts are signals which causes the output to go high (on the next cycle). Resets do the opposite. If both an assert and a reset are active on the same cycle, the assert takes priority.

[PyCDE] Add `ControlReg` construct

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
test/Dialect/FIRRTL/grand-central-errors.mlir

Add test for error messages (which passes without this change).
Noticed these errors (multiply instantiated) in logs and errors should indicate pass / tool failure.

[GC] Fail pass if emit errors about companion instantiation.

---

test/Scheduling/chaining-problems.mlir
test/Scheduling/cyclic-problems.mlir
test/Scheduling/modulo-problems.mlir
test/Scheduling/problems.mlir
test/Scheduling/shared-operators-problems.mlir

Depends on #4525. ~~I'll make the switch after #4517 lands.~~

[Scheduling] Rewrite tests in SSP IR

---

lib/Conversion/AffineToPipeline/AffineToPipeline.cpp
lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp

Microsoft detected a version of GitPython upstream which has a high-sev CVE. I don't think we use this component, but just to make the internal pipeline critical warning go away, I patched it: https://github.com/llvm/llvm-project/commit/f2eb551801d504b43be06c0c70ed377c3445bbc5. This picks up that patch.

[LLVM] Bump for CVE-2022-24439

---

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp

[GC] Update numXMRs statistic.

---

lib/Dialect/SV/Transforms/HWLegalizeModules.cpp
test/Dialect/SV/hw-legalize-modules-packed-arrays.mlir

This PR extends HWLegalizeModules to support aggregate constants. Also `signalPassFailure` is called when we fail to legalize expressions.
Fix https://github.com/llvm/circt/issues/4623.

[HWLegalizeModules] Legalize aggregate constant

---

frontends/PyCDE/src/esi.py
frontends/PyCDE/src/module.py
frontends/PyCDE/test/test_esi.py
include/circt/Dialect/ESI/ESI.td
include/circt/Dialect/ESI/ESIStructure.td
include/circt/Dialect/MSFT/MSFTOps.td
lib/Bindings/Python/dialects/_esi_ops_ext.py
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Dialect/ESI/ESIOps.cpp
test/Dialect/ESI/structure.mlir
test/Dialect/ESI/structure_errors.mlir

Teach PyCDE about ESI pure modules.

[PyCDE] ESI pure module entry

---

lib/Dialect/FIRRTL/Transforms/AddSeqMemPorts.cpp

Fix DenseMap use-after-invalidation bug in AddSeqMemPorts.

[FIRRTL][AddSeqMemPorts] Fix use of DenseMap entry after invalidated.

---

lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp
test/Dialect/FIRRTL/check-comb-cycles.mlir

Implement a new algorithm that is iterative Tarjan's SCC to detect cycles.

[CheckCombCycles] Implement an iterative Tarjan's SCC to detect cycles

---

lib/Dialect/FIRRTL/Transforms/LegacyWiring.cpp
test/Dialect/FIRRTL/legacy-wiring.mlir

[FIRRTL][LegacyWiring] Fix insertion point for fieldID.

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp

Fixes two ASAN reported errors:
* erasing while iterating over uses
* don't use `.getDest()` on an erased op, avoid erasing cnxn >1x.
* Multiple connect's crash, add assert for now.

[FIRRTL][FoldMemRegs] Fixups to avoid memory safety issues.

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir
test/Conversion/ExportVerilog/sv-dialect.mlir

Add SV attribiutes emission supports to module, instance, case, always, always_comb, always_ff and if statements.

[ExportVerilog] More support for SV attributes

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/simplify-mems.mlir

Disable memory folder to deal with #4734

Disable folder for 4734

---

include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/VBToBV.cpp
test/Dialect/FIRRTL/vb-to-bv.mlir
tools/firtool/firtool.cpp

This pass converts objects with the shape `vector<bundle>` to `bundle<vector>`.

[FIRRTL] Add a pass to convert VoB -> BoV conversion

---

include/circt/Support/JSON.h
lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp
lib/Support/CMakeLists.txt
lib/Support/JSON.cpp
unittests/Support/CMakeLists.txt
unittests/Support/JSONTest.cpp

Thanks to @fabianschuiki for the original implementation of Attribute-to-JSON conversion, this PR brings it into CIRCT from a downstream project.

[Support] Move JSON-to-Attribute conversion to Support

---

lib/Dialect/FIRRTL/FIRRTLOps.cpp

Don't recurse on def-use chains.
This function does not appear to be used, FWIW.

[FIRRTL][NFC] Convert isDuplexValue to iterative instead of recursive.

---

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td

Touchup method descriptions to match behavior.
cc #4789.

[FIRRTL][NFC] FModuleLike: fixup method descriptions to match what they do.

---

include/circt/Dialect/Arc/Passes.h
include/circt/Dialect/Arc/Passes.td
lib/Dialect/Arc/Transforms/CMakeLists.txt
lib/Dialect/Arc/Transforms/MakeTables.cpp
test/Dialect/Arc/make-tables.mlir
tools/arcilator/arcilator.cpp

Add the `MakeTables` pass which finds small arcs and converts them into a lookup table where possible.

[Arc] Add lookup table generation pass

---

lib/Dialect/Arc/Transforms/SplitLoops.cpp
test/Dialect/Arc/split-loops.mlir

[Arc] SplitLoops: process splits in dependency order

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
lib/Conversion/ConvertToArcs/ConvertToArcs.cpp
lib/Conversion/ExportVerilog/ExportVerilog.cpp
lib/Conversion/FIRRTLToHW/LowerToHW.cpp
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
lib/Dialect/Arc/Transforms/SimplifyVariadicOps.cpp
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
lib/Dialect/Seq/SeqOps.cpp
test/Dialect/FIRRTL/canonicalization.mlir

[FIRRLT] Narrow adds

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Narrow And, Or, and Xor when possible.

[FIRRTL] Narrow And, Or, and Xor

---

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
test/Dialect/FIRRTL/inliner.mlir

* Consolidate instance-specific renaming code, simplify a bit
* Convert rename to non-recursive (somewhat moot, Inliner must presently run after ExpandWhen's).
* Subsumes 4882, although could land separately/after since the fix turns out to be simple (thanks, @prithayan!).  Contains that test.

[ModuleInliner] Rework instance rename code, fix issue as w/PR4882.

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp

Add a `createTmpHWWireOp` similar to `createTmpWireOp` that creates a throw-away `hw.wire` which is guaranteed to be deleted after the lowering, instead of an `sv.wire` that may be deleted. Most places that create these temporary wires just need them as a receptacle for connects to plug stuff into, and the actual wire is not needed. These places now create temporary `hw.wire`s that are guaranteed to be replaced with the connected value at the end of the lowering.
The remaining two uses of temporary SV wires are inout ports of instances for which we don't have a nice HW equivalent yet; and as an lvalue for plusargs, which we can resolve later by making plusargs an intrinsic at the HW level.
With this commit almost all `sv.wire`s are gone from LowerToHW output.

[FIRRTLToHW] Create most temporary wires as `hw.wire`

---

lib/Conversion/HWArithToHW/HWArithToHW.cpp

I'm saying bye-bye to my fancy templates in favor of a fully generic solution. All operations (including function/module-style ops) are now marked as dynamically legal, and may be replaced generically by the new `TypeConversionPattern`. This pattern copies all parts of the operation (attributes, regions, ...) and type converts them, before re-creating the operation.
Not only is this less code, it will work on _any_ operation which uses types with signedness semantics, thus alleviating #4889 as well as (ideally) any future issue around improper operation support for this pass.
This solution was inspired by: https://github.com/llvm/llvm-project/blob/main/mlir/lib/Conversion/MemRefToSPIRV/MapMemRefStorageClassPass.cpp
Sidenote - i really like this style of generic rewriting and it's been …

[HWArithToHW] Make operation conversion fully generic

---

lib/Dialect/Seq/Transforms/LowerSeqToSV.cpp

Dump operands (Value's, since that's all we need) into a SmallVector, to workaround issue with GCC12's libstdc++ std::reverse_iterator and combination of llvm::enumerate + llvm::reverse.
Fixes https://github.com/llvm/circt/issues/4900 .

[Seq] Fix compat w/GCC12 (see #4900).

---

lib/Dialect/FIRRTL/FIRRTLUtils.cpp

Fixes crash when dumping/encountering IR with an unexpected UnrealizedConversionCast (such as those inserted by `BackedgeBuilder`), and clearing out the name is done because that's how `getFieldName` determines if the root was found and successfully named.

[FIRRTL] getDeclName: safely look into cast, clear if can't name

---

tools/arcilator/arcilator.cpp
tools/firtool/firtool.cpp
tools/hlstool/hlstool.cpp

Check for failure and propagate.
https://reviews.llvm.org/D146785

[tools] Fix -Wunused-result after bump including D146785.

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
test/Dialect/FIRRTL/test.mlir

FIRRTL enum types.  Needs a few checks on element types.

[FIRRTL] Enum Type

---

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
test/Dialect/FIRRTL/infer-widths.mlir
test/Dialect/FIRRTL/ref.mlir

[FIRRTL][InferWidths] Infer to ref results too.

---

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
test/Dialect/FIRRTL/imconstprop.mlir

[FIRRTL][IMCP] Mark forceable decls overdefined.

---

include/circt/Dialect/HW/HWTypes.h
include/circt/Dialect/HW/HWTypesImpl.td
lib/Dialect/HW/HWTypes.cpp
test/Dialect/HW/types.mlir

We need this to support:
1) Matching bit layout of externally defined data types
2) Padding in SystemVerilog emission

[HW][Union type] Add per-field offset

---

lib/Dialect/Comb/CombFolds.cpp

Use a builtin matcher helper function instead of our own.

[CombFolds] Replace m_RConstant with mlir::m_ConstantInt, NFC

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

[FIRRTL][LowerTypes] Support Forceable decls w/refs.

---

lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp
test/Dialect/FIRRTL/check-comb-cycles.mlir

Don't ignore due to having > 1 result.

[FIRRTL][CheckCombLoops] Look through forceable decls too.

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLOps.cpp
test/Dialect/FIRRTL/errors.mlir
test/Dialect/FIRRTL/test.mlir

Add an operation to create enum values.  Extracted from here: https://github.com/llvm/circt/commit/d36dc6615a7230966170e1a253b506eaeda78324

[FIRRTL] enumcreate for creating enum values

---

lib/Dialect/FIRRTL/FIRRTLTypes.cpp
lib/Dialect/FIRRTL/FIRRTLUtils.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

Lower enums without data to verilog enums.

[FIRRTL] Lower trivial (uint0) enums

---

lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
test/Dialect/FIRRTL/emit-omir.mlir

Support getting "type" of declarations that are forceable.
Add test (that crashes without this change).

[FIRRTL][EmitOMIR] Support per-field tracking of forceable.

---

include/circt/Dialect/FIRRTL/FIRRTLStatements.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.td
include/circt/Dialect/FIRRTL/FIRRTLVisitors.h
test/Dialect/FIRRTL/errors.mlir

Simply add these to the IR, not supported anywhere yet.

[FIRRTL] Add force/release operations to ODS.

---

lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/ResolveTraces.cpp
test/Dialect/FIRRTL/annotations.mlir
test/Dialect/FIRRTL/resolve-traces.mlir

Fix annotation resolution, GC view targeting, and resolve traces usage that target forceable declarations.
Builds on #4966 .

[FIRRTL] Query for target result instead of rejecting with multiple results.

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

Lower force, release, force_initial, and release_initial.

[FIRRTL][LowerToHW] Support force + friends. 

---

include/circt/Dialect/ESI/ESITypes.td
lib/Dialect/ESI/ESIFolds.cpp
lib/Dialect/ESI/ESIOps.cpp
lib/Dialect/ESI/ESITypes.cpp
test/Dialect/ESI/errors.mlir
test/Dialect/ESI/windows.mlir

Wrap and unwrap data windows to/from `hw.union`s.

[ESI][Data windows] Introduce wrap/unwrap

---

include/circt/Dialect/Arc/ArcDialect.td
include/circt/Dialect/Arc/ArcOps.td
lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp
lib/Dialect/Arc/ArcDialect.cpp
lib/Dialect/Arc/ArcFolds.cpp
lib/Dialect/Arc/CMakeLists.txt
lib/Dialect/Arc/Transforms/LowerState.cpp
test/Conversion/ArcToLLVM/lower-arc-to-llvm.mlir
test/Dialect/Arc/basic-errors.mlir
test/Dialect/Arc/basic.mlir
test/Dialect/Arc/canonicalizers.mlir
test/Dialect/Arc/infer-memories.mlir
test/Dialect/Arc/lower-state.mlir

Add folder to StateOp for the optional enable and reset operands.

[Arc] Add StateOp folder

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/lower-to-hw.mlir

[FIRRTL] lower plusargs to initial block

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
lib/Dialect/FIRRTL/Import/FIRTokenKinds.def
test/Dialect/FIRRTL/parse-basic.fir
test/Dialect/FIRRTL/parse-errors.fir

Add constant cache helper, use for force/release.
Add tests.

 [FIRRTL] Parse {force,release}{,_initial}.

---

docs/Passes.md

[Docs] Include Arc and SystemC in Passes.md

---

frontends/PyCDE/src/signals.py
frontends/PyCDE/src/types.py
frontends/PyCDE/test/test_pycde_types.py
include/circt-c/Dialect/ESI.h
integration_test/Bindings/Python/dialects/esi.py
lib/Bindings/Python/ESIModule.cpp
lib/CAPI/Dialect/ESI.cpp

Teach PyCDE about the ESI list type.

[PyCDE] Expose ESI list type

---

frontends/PyCDE/src/esi.py
frontends/PyCDE/src/system.py
include/circt/Dialect/ESI/ESIPasses.h
include/circt/Dialect/ESI/ESIPasses.td
lib/Dialect/ESI/CMakeLists.txt
lib/Dialect/ESI/cosim/CPP/CPPCosimAPI.cpp
lib/Dialect/ESI/cosim/CPP/CPPCosimAPI.h
lib/Dialect/ESI/cosim/CPP/ESIAddCPPCosimAPI.cpp
lib/Dialect/ESI/cosim/CPP/ESIEmitCPPCosimAPI.cpp
lib/Dialect/ESI/runtime/cpp/include/esi/esi.h
test/Dialect/ESI/cpp_cosim.mlir
tools/esi/esi-cosim-runner.py.in

This commit adds the ESI C++ cosimulation api (`lib/Dialect/ESI/runtime/cpp/include/esi/cosim/esi.h`) and API generation.

[ESI] Add C++ cosimulation API

---

docs/VerilogGeneration.md
include/circt/Support/LoweringOptions.h
lib/Conversion/ExportVerilog/PrepareForEmission.cpp
lib/Support/LoweringOptions.cpp
test/Conversion/ExportVerilog/prepare-for-emission.mlir

[ExportVerilog] Add option to disallow packed struct assignments

---

lib/Dialect/FIRRTL/FIRRTLTypes.cpp

This adds proper dispatch from FIRRTLBaseType to the following functions:
- getPassiveType
- getWidthlessType
- getMaxFieldID
- getSubTypeByFieldID
- rootChildFieldID
The functionality was already implemented for this type.

[FIRRTL] Support FEnumTypes in FIRRTLBaseType dispatch functions

---

lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp
lib/Dialect/FIRRTL/FIRRTLOps.cpp
lib/Dialect/FIRRTL/FIRRTLTypes.cpp
test/Dialect/FIRRTL/errors.mlir

[FIRRTL] Add verifiers for rwprobe + const on RefType, Forceable.

---

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-errors.fir

Check declarations have appropriate types before creation, and reject declarations of non-base for now.

[FIRRTL] More defensive creation of Forceable declarations.

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp

In particular, this caused a number of folder/etc users of this
method to erroneously believe there was a single driver for
the value if there is a connect AND a strict connect.
(The main one, canonicalizeSingleSetConnect, is safe because
it also conservatively checks the destination has a single use)
Also clarify this only returns the single connect if it's strict,
returning null if finds any non-strict connect driving the value.

[FIRRTL] Fix incorrect getSingleConnectUserOf when > 1 connect.

---

.github/workflows/nightlyIntegrationTests.yml
.github/workflows/shortIntegrationTests.yml
integration_test/Dialect/Handshake/nested_diamonds/nested_diamonds.mlir

With iverilog and cocotb now installed on the CI image, the handshake integration tests will be checked in CI.

[CI] Bump CI image

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-errors.fir
test/firtool/refs-in-aggs.fir
tools/firtool/firtool.cpp

Also reject aggregate ref statements as unsupported for now.

 [FIRRTL][FIRParser] Parse mixed aggregates into open agg/sub ops. 

---

.github/workflows/uploadWheels.yml

[CI] Add python3.8 manylinux wheel

---

include/circt/Dialect/FIRRTL/FIREmitter.h
lib/Dialect/FIRRTL/Export/FIREmitter.cpp
test/Dialect/FIRRTL/emit-basic.mlir

Comparing new/old FIR emitter on the perf regression designs: https://github.com/dtzSiFive/circt-perf/compare/experimental/fir-emitter-test..dtzSiFive:circt-perf:experimental/fir-emitter-pp-test?expand=1 .

[FIREmitter] Use PrettyPrinter for breaking/indenting.

---

include/circt/Dialect/DC/DCOps.td
lib/Dialect/DC/DCOps.cpp
test/Dialect/DC/canonicalization.mlir

* All Join canonicalizations are now folders.
* Pack canonicalization replaced with built-in CSE.

[DC] Address canonicalizer review comments

---

include/circt/Dialect/OM/OMAttributes.td
include/circt/Dialect/OM/OMOps.td
lib/Dialect/OM/OMAttributes.cpp
lib/Dialect/OM/OMOps.cpp
unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp

Add a few helpful builders, based on observations from https://github.com/llvm/circt/pull/5224

[OM] Add  helper builders for OM ops

---

CMakeLists.txt

[CMake] Require cmake >= 3.23 but only on capnp builds

---

lib/Dialect/Pipeline/Transforms/StageSeparatorToStage.cpp

[Pipeline] Fix use-after-free in StageSeparatorToStagePass.

---

lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp
lib/Dialect/FIRRTL/FIRRTLTypes.cpp

Also addresses a data tap bug that this fix revealed.
Addresses #5327

Preserve const for getWidthlessType

---

integration_test/Dialect/Pipeline/lit.local.cfg.py
integration_test/Dialect/Pipeline/simple/simple.mlir
integration_test/Dialect/Pipeline/simple/simple.py

Just a small test using the new CocoTB driver; will add more once this one is in tree and proven to work.
Depends on landing #5279.

[Pipeline] Add integration test

---

include/circt-c/ExportFIRRTL.h
lib/CAPI/CMakeLists.txt
lib/CAPI/ExportFIRRTL/CMakeLists.txt
lib/CAPI/ExportFIRRTL/ExportFIRRTL.cpp
test/CAPI/CMakeLists.txt

This PR implements a C API for exporting FIRRTL.

[ExportFIRRTL] Implement C API

---

include/circt/Dialect/FIRRTL/FIRRTLAttributes.td
include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
include/circt/Dialect/FIRRTL/FIRRTLStatements.td
include/circt/Dialect/FIRRTL/FIRRTLTypes.td

Follow up to bb14a6ffa9c1cc388b3c608f74a1f88ef555363d

[FIRRTL] Replace deprecated casts in tablegen, NFC

---

lib/Dialect/FIRRTL/Transforms/LowerIntrinsics.cpp

Only need InstanceGraph, so don't bother computing the paths.
Drop lookupInstNode, `InstanceGraph::lookup` is enough (now?).

[LowerIntrinsics] Touchup to avoid unused instance path cache.

---

lib/Dialect/FIRRTL/Transforms/InferResets.cpp
test/Dialect/FIRRTL/infer-resets.mlir

This will facilitate future work requiring async reset values to be const.

[FIRRTL] Reset values added in InferResets are now const.

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
include/circt/Firtool/Firtool.h
lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
lib/Firtool/Firtool.cpp

Flows using this parameter will need to be updated.

[FIRRTL] Drop unused repl-seq-mem-circuit option.

---

include/circt/Dialect/Calyx/CalyxLoweringUtils.h
include/circt/Dialect/Pipeline/PipelineDialect.h
include/circt/Dialect/Pipeline/PipelineDialect.td
include/circt/Dialect/Pipeline/PipelineInterfaces.h
include/circt/Dialect/Pipeline/PipelineInterfaces.td
include/circt/Dialect/Pipeline/PipelineOps.h
include/circt/Dialect/Pipeline/PipelineOps.td
include/circt/InitAllDialects.h
lib/Conversion/PipelineToHW/PipelineToHW.cpp
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
lib/Dialect/Pipeline/PipelineOps.cpp
lib/Dialect/Pipeline/Transforms/PassDetails.h
tools/circt-reduce/circt-reduce.cpp

this also exposed a missing include in `circt-reduce.cpp`.

[NFC][Pipeline] Restructure pipeline dialect tablegen files

---

include/circt/Dialect/FIRRTL/FIRRTLUtils.h
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp

This commit parallelizes the post processing of InferWidth. InferenceTypeUpdate just updates all uninferred widths (unless I'm not missing something) so we can parallelize them with mostly mechanical changes.`anyFailed` in `InferenceTypeUpdate` is removed instead `FailureOr` is used to propagate failures.  It reduces InferWidth execution time by around 10% which is 1~3% reduction for the entire pipeline.

[InferWidth] Parallelize post processing, NFCI

---

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp

* Split out DenseMapInfo<variant> specialization: https://reviews.llvm.org/D150997
Feel free to bump again and merge as needed.

[LLVM] Weekly bump

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp

[FIRRTL] incorrect canonicalization pattern

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp

This commit parallelizes hash calculation. This reduces Dedup execution time by 40% in a large design, which reduces the entire execution time by 7~8%.
This PR first changes the type of structural hash into <sha256, ArrayAttr>. The first element is structural hash, the second element is a list of module names that are referred by instances in the module. By doing so we can lazily combine hashes of modules names replaced by dedup through `dedupMap`.
Before:
```
137.6359 (  3.3%)  137.6359 ( 15.1%)    Dedup
```
After:
```
66.9677 (  2.1%)   66.9677 (  8.2%)    Dedup
```

[Dedup] Parallelize hash calculation, NFCI

---

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp

Drop unused variable, remove what appears to be unnecessary code.

[FIRRTL][LowerXMR][NFCI] Minor touchups.

---

lib/Dialect/FIRRTL/Transforms/LowerOpenAggs.cpp

Squelch warning, and LLVM-style-ify dump method.
(sometimes elided, always marked noinline, sometimes mark used)

[FIRRTL][LOA][NFC] Tweak structure dump/print.

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp

[FIRRTL][LowerTypes] fix error paths to fail pass.

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

Nearly NFC -- while visiting also drop code for special handling of signal driving annotations (and remove corresponding test).

[FIRRTL][LowerTypes] Simplify fieldID handling code.

---

include/circt/Dialect/Calyx/Calyx.td
include/circt/Dialect/Calyx/CalyxControl.td
lib/Dialect/Calyx/CalyxOps.cpp
lib/Dialect/Calyx/Export/CalyxEmitter.cpp
test/Dialect/Calyx/emit-invoke.mlir
test/Dialect/Calyx/errors.mlir

This PR only contains `calyx.invoke` and `invoke emitter`.`lower invoke` parts I will submit the other PR.

[Calyx]Add invoke operation.

---

lib/Dialect/Calyx/Export/CalyxEmitter.cpp

@cgyurgyik I've fixed the bugs here.

[Calyx] Fix use after free bug.

---

.github/workflows/uploadWheels.yml

Fixes pypi wheel upload condition for nightly runs.
See #5431.

[CI] Fix nightly wheel upload

---

CODEOWNERS

@teqdruid @blakep-msft creating a PR here just to make you aware that I'm signing you up for this 😉.

[Ibis] assign codeowners

---

include/circt/Dialect/SV/SVVerification.td
test/Dialect/SV/errors.mlir

[SV] Add constraint and test rejecting subst w/o message

---

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp
test/Dialect/FIRRTL/expand-whens.mlir

Add support for lowering when statements which exist in group definitions.

[FIRRTL] Add Groups to ExpandWhens

---

frontends/PyCDE/src/signals.py
frontends/PyCDE/test/test_hwarith.py

[PyCDE] Add implemented of comparison operators

---

include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/DropConst.cpp
lib/Firtool/Firtool.cpp
test/Dialect/FIRRTL/drop-const.mlir

It's illegal to modify port types within FModuleLike pass so change DropConst pass to a circuit op pass.

[FIRRTL] Make DropConst circuit op pass, NFC

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp
test/Conversion/FIRRTLToHW/intrinsics.mlir

Additionally, lower to ifdef synthesis, since there is no way to generate that from chisel.

[FIRRTL] Fix lowering of plusarg value since it returns an integer rather than a bool

---

include/circt/Dialect/Calyx/CalyxLoweringUtils.h
lib/Conversion/LoopScheduleToCalyx/LoopScheduleToCalyx.cpp
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp

[Calyx] Changed type of `getBound()` to `std::optional<int64_t>`

---

lib/Dialect/SV/Transforms/HWMemSimImpl.cpp

Improve the names of generated registers inside HWMemSimImpl.  Change from a generic "_GEN" to a name that matches the port.  E.g., names will now have the form:
_<port>_d<delay>
An example of the delayed addess register used for the first read port is:
_R0_addr_d0
Input:
```
circuit Foo:
module Foo:
input r: {addr: UInt<3>, en: UInt<1> clk: Clock, flip data: UInt<32>}
input w: {addr: UInt<3>, en: UInt<1> clk: Clock, data: UInt<32>, mask: UInt<1>}
mem memory:
data-type => UInt<32>
depth => 8
reader => r
writer => w
read-latency => 1
write-latency => 1
read-under-write => undefined
memory.r <= r
memory.w <= w
```
Old output:
```verilog
module memory_8x32(
input  [2:0]  R0_addr,
input         R0_en,
R0_clk,
input  [2:0]  W0_addr,
input         W0_en,
W0_clk,
input  [31:0] W0_data,
output …
```

[HW] Improve generated names in HWMemSimImpl

---

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
test/Dialect/FIRRTL/imconstprop.mlir

[IMCP] Mark PlusArgs intrinsics as overdefined

---

frontends/PyCDE/src/instance.py
frontends/PyCDE/src/module.py
frontends/PyCDE/src/signals.py
frontends/PyCDE/src/system.py

After #5703 lands, this'll fix PyCDE.

[PyCDE] Post innersym change fixes

---

lib/Dialect/ESI/ESITranslations.cpp

Don't leave handler attached, and ensure lifetime of the lambda capture re:errorCount variable is live as long as the handler may be used.

[ESI] ESITranslations: rework diag interception, fix memory error.

---

include/circt/Dialect/Arc/ArcInterfaces.td
include/circt/Dialect/Arc/ArcOps.td
include/circt/Dialect/Handshake/HandshakeOps.td
include/circt/Dialect/Ibis/IbisOps.td
include/circt/Dialect/LLHD/IR/StructureOps.td
include/circt/Dialect/SystemC/SystemCStatements.td
lib/Dialect/Arc/ArcOps.cpp
lib/Dialect/Arc/Transforms/ArcCanonicalizer.cpp
lib/Dialect/Arc/Transforms/Dedup.cpp
lib/Dialect/DC/DCOps.cpp
lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
lib/Dialect/Seq/Transforms/LowerFirMem.cpp
test/Analysis/.#dependence-analysis.mlir
test/Analysis/dependence-analysis.mlir
test/Analysis/scheduling-analysis.mlir
test/Conversion/FIRRTLToHW/lower-to-hw.mlir
test/Conversion/FIRRTLToHW/zero-width.mlir
test/Dialect/DC/canonicalization.mlir
test/Dialect/ESI/lowering.mlir
test/Dialect/SV/hw-memsim.mlir

Opening a branch for WIP bumping LLVM.

Start of LLVM bump

---

lib/Dialect/FIRRTL/Transforms/MergeConnections.cpp
test/Dialect/FIRRTL/merge-connections.mlir

[FIRRTL][MergeConnections] Fix merging non-passive or unsized parent.

---

frontends/PyCDE/src/constructs.py

[PyCDE] Fixed NoneType name in Mux

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp

The sole remaining user of the functionality created unoptimizable wires.

[LowerToHW] Remove temporary wire optimization

---

docs/HLS.md

This should serve as a landing page for everything HLS-related in CIRCT, given a proper introduction to the various flows, their state, and further pointers on how to find more information.
I'd hope for it to be written with a target audience of "i'm aware of HLS, i'm aware of MLIR, i'm somewhat unaware of CIRCT".
It's far from done - I plan on writing more docs in the future (with the goal of offloading some of my tribal knowledge). Adding the page, however, is a first step for allowing us all to write down things - so please feel free to contribute whenever you have time!

[docs] Add top-level document on hls

---

tools/firtool/firtool.cpp

There is no good reason to use two pass managers, and it is causing us to emit pass statistics and timings once for each pass manager, and it would be better if it was all grouped together.

[firtool] use a single pass manager

---

include/circt/Dialect/HW/HWTypes.td
lib/Dialect/HW/HWAttributes.cpp
lib/Dialect/HW/HWOpInterfaces.cpp
test/Dialect/FIRRTL/errors.mlir

[HW] Verify non-empty inner symbol, symbol names.

---

include/circt/Dialect/OM/OMOps.h
include/circt/Dialect/OM/OMOps.td
lib/Dialect/OM/OMOps.cpp
test/Dialect/OM/errors.mlir
test/Dialect/OM/round-trip.mlir

This commit implements tuple_create/tuple_get operations

[OM] Implement tuple operations

---

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
test/Dialect/FIRRTL/imdce.mlir

[FIRRTL][IMDCE] Propagate liveness to/from forceable data/ref results.

---

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp

This may address #5902 but I haven't been able to reproduce the issue locally

[FIRRTL] Don't erase classes in parallel in LowerClasses

---

include/circt/Dialect/OM/OMAttributes.td
lib/Dialect/OM/OMAttributes.cpp
test/Dialect/OM/errors.mlir
test/Dialect/OM/round-trip.mlir

This implement om.map attribute as constant of map types.

[OM] Add om.map attribute

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/ResolvePaths.cpp
test/Dialect/FIRRTL/resolve-paths-errors.mlir
test/Dialect/FIRRTL/resolve-paths.mlir
tools/firtool/firtool.cpp

This pass transforms all UnresolvedPathOps in to PathOps.

[FIRRTL] Add ResolvePathsPass

---

include/circt/Dialect/Ibis/IbisOps.td
lib/Dialect/Ibis/IbisOps.cpp
test/Dialect/Ibis/round-trip.mlir

Bunch of op-related changes grouped together by being a net quality improvement of the dialect.

[Ibis] Add Wire ops, canonicalizers and SSA names

---

integration_test/CMakeLists.txt
test/lit.cfg.py

[ESI] Fix non-capnp builds

---

test/firtool/print-before.fir
tools/firtool/firtool.cpp

[firtool] Register conversion passes to make avail for mlir-print-ir.

---

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
test/Dialect/FIRRTL/infer-widths.mlir

[FIRRTL][InferWidths] Ignore propassign, don't error.

---

include/circt/Dialect/OM/OMTypes.h
include/circt/Dialect/OM/OMTypes.td
lib/Dialect/OM/OMTypes.cpp
test/Dialect/OM/round-trip.mlir

This commit adds om.enum type.

[OM] Add om.enum type

---

include/circt/Dialect/MSFT/MSFTOps.td
lib/Dialect/MSFT/MSFTOps.cpp
lib/Dialect/MSFT/Transforms/MSFTPartition.cpp
lib/Dialect/MSFT/Transforms/MSFTWireCleanup.cpp

[MSFT][NFC] Switch MSFTModule off of FunctionInterface

---

lib/Dialect/FIRRTL/FIRRTLDialect.cpp
lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
test/Dialect/FIRRTL/imconstprop.mlir

Fixes #5940 and supports basic property const prop while visiting.

[FIRRTL][IMCP] Support Properties; support materializing string/bool.

---

CMakeLists.txt
frontends/PyCDE/integration_test/CMakeLists.txt
frontends/PyCDE/src/CMakeLists.txt
include/circt/Dialect/ESI/cosim/CMakeLists.txt
integration_test/CMakeLists.txt
integration_test/Dialect/ESI/system/basic.mlir
integration_test/lit.cfg.py
integration_test/lit.site.cfg.py.in
lib/Dialect/ESI/CMakeLists.txt
tools/esi/CMakeLists.txt
tools/esi/esi-cosim-runner.py.in

Avoid use of new CMake feature FILE_SET.

[ESI] Change method of packaging collateral

---

.github/workflows/trackLLVMChanges.yml

Couldn't easily determine how to selectively fetch the desired range, so rely on this running regularly and grab based on time.
Fixes #4566.

[CI] Unshallow llvm to include past 30 days, so have revs to bisect over.

---

include/circt/Dialect/OM/OMAttributes.td
include/circt/Dialect/OM/OMTypes.td
lib/Dialect/OM/OMAttributes.cpp
test/Dialect/OM/round-trip.mlir

[OM] Add integer type

---

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td
test/Dialect/FIRRTL/canonicalization.mlir

[FIRRTL] Don't canonicalize out-of-bounds subaccess into subindex

---

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
test/Dialect/FIRRTL/lower-types.mlir

When cloning into new wires, preserve the ref part (the lowering operates on the base type portion).

[FIRRTL][LowerTypes] Support lowering of wire of ref.

---

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
test/Dialect/SV/hw-extract-test-code.mlir

Change the BFS of operations used to compute backwards slices in SVExtractTestCode to, instead, use a DFS of operands.  This ensures that any intermediary operations which may show up do not cause the ports of extracted modules to change.
This was triggered by addition of the `seq.from_clock` operation to cause the BFS discovery order of roots to change.
I haven't thought through if this is a performance problem nor tested it. This may need to do more aggressive early continuation than it has right now. The change here was mostly mechanical from the original.
Fixes #6072.

[SV][HW] Stable port order in SVExtractTestCode

---

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp
test/Dialect/FIRRTL/lower-classes.mlir

This adds lowering for extmodule similar to extclasses: an external class declaration is created with the property input and output ports. This also adds support for converting instances of modules or extmodules that have been lowered, and keeping the instance graph up to date.
A small addition is also included to always create a class for public modules and extmodules, which is a further refinement of the as-yet undocumented ABI.

[FIRRTL] Update LowerClasses to handle extmodule and instances.

---

include/circt-c/Dialect/OM.h
include/circt/Dialect/OM/Evaluator/Evaluator.h
integration_test/Bindings/Python/dialects/om.py
lib/Bindings/Python/OMModule.cpp
lib/Bindings/Python/dialects/om.py
lib/CAPI/Dialect/OM.cpp
lib/Dialect/OM/Evaluator/Evaluator.cpp
unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp

This PR add support for Map evaluation.

[OM] Evaluator: Support Map

---

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
test/Dialect/FIRRTL/imconstprop.mlir

* Recognize RefSubOp as "aggregate indexer".
* Compute and propagate via FieldRefs into inner (base) type for refs, restore behavior lost with FieldID rework/simplification.
* Treat ref send/resolve similarly to nodes in reasoning.
Put behavior under test.
RefSub test before this PR resulted in another undriven probe wire (cc #6076).

[FIRRTL][IMCP] Fix handling of refsub, send/resolve, fields.

---

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp
test/Dialect/FIRRTL/lower-classes-errors.mlir
test/Dialect/FIRRTL/lower-classes.mlir

Reject if does not target what it should.

[FIRRTL][LowerClasses] Handle InstanceTarget.

---

include/circt/Dialect/OM/OMOps.td
test/Dialect/OM/round-trip.mlir

Add the path append op to OM dialect.

[OM] Add path append op

---

lib/Conversion/SeqToSV/SeqToSV.cpp
test/Dialect/Seq/clock-type.mlir

[Seq] Lower clock types nested within aggregates

---

include/circt/Dialect/MSFT/ExportTcl.h
include/circt/Dialect/MSFT/MSFTOpInterfaces.td
include/circt/Dialect/MSFT/MSFTPDOps.td
lib/Dialect/MSFT/DeviceDB.cpp
lib/Dialect/MSFT/ExportQuartusTcl.cpp
lib/Dialect/MSFT/MSFTOpInterfaces.cpp
lib/Dialect/MSFT/MSFTOps.cpp
lib/Dialect/MSFT/Transforms/MSFTExportTcl.cpp
lib/Dialect/MSFT/Transforms/MSFTLowerInstances.cpp
test/Dialect/MSFT/dynamic_instance.mlir
test/Dialect/MSFT/location.mlir
test/Dialect/MSFT/translate-errors.mlir

Switch to HierPathOp. Closes #5183.

[MSFT] Finally move away from GlobalRefOp

---

lib/Firtool/Firtool.cpp
test/firtool/groups.fir

Add the LowerGroups pass to firtool.  Add an end-to-end test that includes nested groups.

[firtool] Add LowerGroups pass

---

lib/Dialect/FIRRTL/Transforms/HoistPassthrough.cpp

Avoid analysis + re-verification if nothing changes.

[FIRRTL][Hoist] Mark all analyses preserved if no changes.

---

lib/Dialect/FIRRTL/Transforms/LowerOpenAggs.cpp

Don't re-verify (or recompute analyses) if no changes are made (no open aggregates present).

[FIRRTL][LOA] If no changes made, mark all analyses preserved.

---

lib/Dialect/Ibis/Transforms/IbisReblockPass.cpp

Fix a bug in the IbisReblockPass where an erased op was being pushed into a SmallVector.  Delay deletion of ops until runOnOperation finishes.
Fixes #6220.

[ibis] Fix reblock use of erased ops

---

include/circt/Dialect/Calyx/CalyxPrimitives.td
lib/Conversion/CalyxToHW/CalyxToHW.cpp
lib/Dialect/Calyx/CalyxOps.cpp
lib/Dialect/Calyx/Export/CalyxEmitter.cpp
test/Conversion/CalyxToHW/primitives.mlir
test/Dialect/Calyx/emit-comb-component.mlir
test/Dialect/Calyx/emit-custom-primitives.mlir
test/Dialect/Calyx/emit-seq-memory.mlir
test/Dialect/Calyx/emit.mlir

[Calyx] Add calyx.undef

---

frontends/PyCDE/src/signals.py
frontends/PyCDE/src/system.py
frontends/PyCDE/src/testing.py
frontends/PyCDE/test/test_behavioral.py
frontends/PyCDE/test/test_cocotb_testbench.py
frontends/PyCDE/test/test_constructs.py
frontends/PyCDE/test/test_esi.py
frontends/PyCDE/test/test_fsm.py
frontends/PyCDE/test/test_hwarith.py
frontends/PyCDE/test/test_muxing.py
frontends/PyCDE/test/test_ndarray.py
frontends/PyCDE/test/test_polynomial.py
frontends/PyCDE/test/test_pycde_types.py
frontends/PyCDE/test/test_pycde_values.py
frontends/PyCDE/test/test_slicing.py
frontends/PyCDE/test/test_syntactic_sugar.py
frontends/PyCDE/test/test_verilog_readablility.py

Mostly broken due to hw.module asm format change. Also, the cocotb tests have been broken for some time.

[PyCDE] Fixing tests

---

lib/Dialect/Seq/SeqOps.cpp
test/Dialect/Seq/canonicalization.mlir

[Seq] Fix the canonicalization of seq registers with a clock type

---

include/circt/Dialect/ESI/ESIChannels.td
lib/Dialect/ESI/ESIOps.cpp
lib/Dialect/ESI/Passes/ESILowerBundles.cpp

- Builders
- Printing should never fail

[ESI][NFC] Misc improvements for bundle ops

---

lib/Dialect/FIRRTL/Transforms/MergeConnections.cpp
test/Dialect/FIRRTL/merge-connections.mlir

Fix https://github.com/llvm/circt/issues/6303

[MergeConnections] Handle type alias

---

test/Dialect/ESI/manifest.mlir
test/lit.cfg.py
test/lit.site.cfg.py.in

[ESI] Not every build has zlib

---

include/circt/Dialect/ESI/ESIPasses.td
integration_test/Dialect/ESI/runtime/loopback.mlir
lib/Dialect/ESI/Passes/ESIBuildManifest.cpp
lib/Dialect/ESI/runtime/CMakeLists.txt
lib/Dialect/ESI/runtime/cpp/include/esi/backends/Trace.h
lib/Dialect/ESI/runtime/cpp/lib/backends/Trace.cpp
test/Dialect/ESI/manifest.mlir

Trace recording and playback could be very useful. Could also be used for design introspection and runtime testing (without cosim). This is the start of that system.

[ESI][Runtime] Create a 'trace' accelerator backend

---

integration_test/Dialect/ESI/runtime/loopback.mlir.py
lib/Dialect/ESI/runtime/cpp/include/esi/Design.h
lib/Dialect/ESI/runtime/cpp/include/esi/Manifest.h
lib/Dialect/ESI/runtime/cpp/include/esi/Types.h
lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp
lib/Dialect/ESI/runtime/cpp/tools/esiquery.cpp
lib/Dialect/ESI/runtime/python/esi/accelerator.py
lib/Dialect/ESI/runtime/python/esi/esiCppAccel.cpp
lib/Dialect/ESI/runtime/python/esi/esiCppAccel.pyi

Absolutely minimal necessary for wiring up services: BundleType.

[ESI][Runtime] Start of types

---

lib/Dialect/HW/HWOps.cpp

Fixes https://github.com/llvm/circt/issues/6388
**NOTE**: This patch was originally provided by @fzi-hielscher (see referenced issue).  I'm submitting this via PR in hopes to accelerate integration as it fixes a blocking bug.

[HW] Fix bug with unknown location

---

integration_test/Dialect/ESI/runtime/loopback.mlir.py
lib/Dialect/ESI/runtime/cpp/include/esi/Design.h
lib/Dialect/ESI/runtime/cpp/include/esi/Manifest.h
lib/Dialect/ESI/runtime/cpp/lib/Design.cpp
lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp
lib/Dialect/ESI/runtime/python/esi/__init__.py
lib/Dialect/ESI/runtime/python/esi/esiCppAccel.cpp
lib/Dialect/ESI/runtime/python/esi/esiCppAccel.pyi

Adds AppID accessors, which are much better than indexes.

[ESI][Runtime] Access children and ports by name

---

lib/Dialect/ESI/runtime/cpp/include/esi/Accelerator.h
lib/Dialect/ESI/runtime/cpp/include/esi/StdServices.h
lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp

Fixes broken nightlies: https://github.com/llvm/circt/actions/runs/6920305753/job/18824655470
Hide all the Cap'nProto wierdness behind pointers to make everyone happy.

[ESI][Runtime] Make GCC happy too

---

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

Fix https://github.com/llvm/circt/issues/6237

[FIRRTLFolds] Fix FoldZeroWidthMemory to write zero for zero bit wire

---

lib/Dialect/FIRRTL/Transforms/InferResets.cpp

The cache is a central store for all instance paths, only references are passed around.

[InferResets] Transition the pass to use the InstancePathCache

---

lib/Dialect/ESI/Passes/ESILowerToHW.cpp
test/Dialect/ESI/manifest.mlir

[ESI] Move Cosim manifest into separate module

---

include/circt/Dialect/ESI/ESIStdServices.td
integration_test/Dialect/ESI/runtime/loopback.mlir
integration_test/Dialect/ESI/runtime/loopback.mlir.py
lib/Dialect/ESI/ESIStdServices.cpp
test/Dialect/ESI/services.mlir

Function calls will eventually be recognized by the runtime and expose a function call interface.

[ESI] Function call std service

---

include/circt-c/Dialect/Debug.h
integration_test/Bindings/Python/dialects/debug.py
lib/Bindings/Python/CIRCTModule.cpp
lib/Bindings/Python/CMakeLists.txt
lib/Bindings/Python/dialects/DebugOps.td
lib/Bindings/Python/dialects/debug.py
lib/CAPI/Dialect/CMakeLists.txt
lib/CAPI/Dialect/Debug.cpp

Add basic Python bindings for the debug dialect.

[Python] Add debug dialect bindings

---

integration_test/Dialect/ESI/runtime/loopback.mlir
integration_test/Dialect/ESI/runtime/loopback.mlir.py
lib/Dialect/ESI/runtime/cpp/include/esi/Accelerator.h
lib/Dialect/ESI/runtime/cpp/include/esi/Types.h
lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp
lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp
lib/Dialect/ESI/runtime/cpp/lib/backends/Trace.cpp
lib/Dialect/ESI/runtime/python/esi/__init__.py
lib/Dialect/ESI/runtime/python/esi/esiCppAccel.cpp
lib/Dialect/ESI/runtime/python/esi/esiCppAccel.pyi

Implementing missing classes and exposing to Python. Will build to proper type-based serialization in Python.

[ESI][Runtime] Filling out the type system

---

include/circt/Dialect/OM/OMOps.td
test/Dialect/OM/round-trip.mlir

It looks like this may have been intended for this to be PathType.

[OM] Update result type for EmptyPathOp.

---

integration_test/Dialect/ESI/cosim/cosim_only.sv
integration_test/Dialect/ESI/cosim/loopback.mlir
integration_test/Dialect/ESI/cosim/lowlevel_cosim_only.sv
integration_test/Dialect/ESI/runtime/basic_mmio.sv
integration_test/Dialect/ESI/runtime/loopback.mlir

Add rtl-sim to requires and %python before cosim runner.

[ESI][Integration test] Fix requires and run commands

---

include/circt/Dialect/FIRRTL/FIRRTLIntrinsics.h

[FIRRTL] Intrinsics: Fix lifetime issues in lambda.

---

lib/Dialect/ESI/runtime/CMakeLists.txt
lib/Dialect/ESI/runtime/cpp/include/esi/Accelerator.h
lib/Dialect/ESI/runtime/cpp/include/esi/Common.h
lib/Dialect/ESI/runtime/cpp/include/esi/Design.h
lib/Dialect/ESI/runtime/cpp/include/esi/Manifest.h
lib/Dialect/ESI/runtime/cpp/include/esi/Ports.h
lib/Dialect/ESI/runtime/cpp/include/esi/Types.h
lib/Dialect/ESI/runtime/cpp/lib/Accelerator.cpp
lib/Dialect/ESI/runtime/cpp/lib/Design.cpp
lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp
lib/Dialect/ESI/runtime/cpp/lib/Ports.cpp
lib/Dialect/ESI/runtime/cpp/lib/backends/Trace.cpp

- Moves classes around.
- Changes Type ownership.
- Cleans up #includes.
- Adds documentation

[ESI][Runtime][NFC] Minor refactor and cleanup

---

integration_test/CMakeLists.txt
integration_test/Dialect/ESI/runtime/loopback.mlir
integration_test/lit.cfg.py
lib/Dialect/ESI/runtime/cpp/tools/esiquery.cpp

[ESI][Runtime] Add design hierarchy printing to esiquery

---

frontends/PyCDE/src/esi.py
frontends/PyCDE/src/types.py
frontends/PyCDE/test/test_esi_servicegens.py

Repair the ability to implement services in PyCDE. I broke this some months ago and never got around to fixing it.

[PyCDE] Fix ESI service implementations

---

include/circt/Support/Debug.h
lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
lib/Dialect/FIRRTL/Transforms/HoistPassthrough.cpp
lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
lib/Dialect/FIRRTL/Transforms/InferResets.cpp
lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp
lib/Dialect/FIRRTL/Transforms/LayerSink.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/LowerOpenAggs.cpp
lib/Dialect/FIRRTL/Transforms/LowerSignatures.cpp
lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
lib/Dialect/FIRRTL/Transforms/MergeConnections.cpp
lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
lib/Dialect/FIRRTL/Transforms/PassiveWires.cpp
lib/Dialect/FIRRTL/Transforms/RegisterOptimizer.cpp
lib/Dialect/FIRRTL/Transforms/RemoveUnusedPorts.cpp
lib/Dialect/FIRRTL/Transforms/Vectorization.cpp
lib/Support/CMakeLists.txt
lib/Support/Debug.cpp

Add utilities for generating pass debugging boilerplate. Update all passes that currently have this boilerplate to use the utility.

[Support][FIRRTL] Debug Cleanup

---

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp

We intended to keep the InstanceGraph up to date, but when we completely erase FIRRTL ClassOps, we were not removing them from the InstanceGraph. This can lead to invalid memory accesses, which I noticed with ASAN while using the InstanceGraph in a pass downstream of this.

[FIRRTL] Update InstanceGraph on erase in LowerClasses.

---

lib/Dialect/FIRRTL/Transforms/Dedup.cpp

This change seems to make the test problem go away. Care of @fzi-hielscher in #6570 .

[FIRRTL] Innocuous change to mitigate #6513

---

include/circt/Conversion/Passes.td

Tiny change to FSMToSV TableGen summary as it's currently a little misleading, assume it's just a typo

[FSMToSV][NFC] Correct pass summary

---

frontends/PyCDE/src/module.py
frontends/PyCDE/test/test_import_hw_modules.py

[PyCDE] Fix import hw modules (#6130)

---

include/circt-c/Dialect/HW.h
lib/CAPI/Dialect/HW.cpp
unittests/Dialect/HW/CMakeLists.txt
unittests/Dialect/HW/InstanceGraphTest.cpp

Add instace graph C-API to HW dialect iterating modules from Chisel.
CC @sequencer @mikeurbach

[HW][CAPI] Add instance graph C-API for iterating modules

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-basic.fir

Implement https://github.com/chipsalliance/firrtl-spec/pull/166

[FIRParser] Allow assert stmt to have a format string

---

frontends/PyCDE/integration_test/esi_test.py
frontends/PyCDE/integration_test/test_software/esi_test.py
frontends/PyCDE/src/esi.py
frontends/PyCDE/test/test_esi.py

Adds support for implementing function calls in PyCDE.

[PyCDE] Support ESI's FuncService

---

lib/Dialect/ESI/runtime/cpp/include/esi/Manifest.h
lib/Dialect/ESI/runtime/cpp/include/esi/Ports.h
lib/Dialect/ESI/runtime/cpp/include/esi/Services.h
lib/Dialect/ESI/runtime/cpp/include/esi/Types.h
lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp
lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp
lib/Dialect/ESI/runtime/cpp/lib/backends/Trace.cpp
lib/Dialect/ESI/runtime/cpp/tools/esiquery.cpp

References were too complex to bother.

[ESI][Runtime] Convert Type& to Type*

---

lib/Dialect/ESI/runtime/cpp/include/esi/Accelerator.h
lib/Dialect/ESI/runtime/cpp/include/esi/Services.h
lib/Dialect/ESI/runtime/cpp/include/esi/backends/Cosim.h
lib/Dialect/ESI/runtime/cpp/include/esi/backends/Trace.h
lib/Dialect/ESI/runtime/cpp/include/esi/backends/Xrt.h
lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp
lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp
lib/Dialect/ESI/runtime/cpp/lib/backends/Trace.cpp
lib/Dialect/ESI/runtime/cpp/lib/backends/Xrt.cpp

Everything needs channels, not just custom services.

[ESI][Runtime][NFC] Move `requestChannelsFor` into accelerator connection

---

lib/Dialect/ESI/runtime/cpp/include/esi/Common.h
lib/Dialect/ESI/runtime/cpp/include/esi/Ports.h
lib/Dialect/ESI/runtime/cpp/include/esi/Types.h
lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp
lib/Dialect/ESI/runtime/cpp/lib/backends/Trace.cpp
lib/Dialect/ESI/runtime/python/esi/esiCppAccel.cpp
lib/Dialect/ESI/runtime/python/esi/types.py

Not a big improvement, but will make function calls easier.

[ESI][Runtime][NFC] Switch from ptr,size to MessageData

---

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp

rewriteModuleBody is ran parallely so we can ignore the overhead of plain getFieldRefFromValue w/o cache.

[IMCP] Fix a race condition regarding aggregate preservation

---

include/circt/Dialect/ESI/ESIInterfaces.td
include/circt/Dialect/ESI/ESIStdServices.td
integration_test/Dialect/ESI/runtime/loopback.mlir.py
lib/Dialect/ESI/Passes/ESIBuildManifest.cpp
lib/Dialect/ESI/runtime/cpp/include/esi/Accelerator.h
lib/Dialect/ESI/runtime/cpp/include/esi/Design.h
lib/Dialect/ESI/runtime/cpp/include/esi/Ports.h
lib/Dialect/ESI/runtime/cpp/include/esi/Services.h
lib/Dialect/ESI/runtime/cpp/lib/Accelerator.cpp
lib/Dialect/ESI/runtime/cpp/lib/Design.cpp
lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp
lib/Dialect/ESI/runtime/cpp/lib/Services.cpp
lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp
lib/Dialect/ESI/runtime/python/esi/esiCppAccel.cpp
lib/Dialect/ESI/runtime/python/esi/types.py
test/Dialect/ESI/manifest.mlir

- Added a framework for services to customize access methods.
- Added a user of said framework for function calls.
- Added a 'type' field to service decls section of the manifest.

[ESI][Runtime] Adding support for FuncService

---

docs/Dialects/OM/RationaleOM.md

This adds some basic rationale for why it is valuable to be able to represent computation in the OM dialect, with a couple examples including arithmetic and container constructions.

[OM] Add rationale for expressions.

---

lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp
test/Dialect/FIRRTL/lower-layers.mlir

This PR fixes two issues.
First, when a captured value has been replaced by a block-argument on the layerblock, if we encounter a use of the block-argument, we would attempt to "recapture" the argument, because our check for "is this value defined inside the layerblock" was broken for block arguments. This PR fixes that check. Now a value can be captured more than once.
Second, when capturing a value as a "source/input-port", we should only replaces uses where the value is used as a source. Similarly, when a value is captured as a "sink/output-port", we should only replace uses where the value is used as the destination of a connect-like operation.
This means that if a value is used as both a source and a sink, we will create both an input and an output port. In this case, we may …

[FIRRTL][Lower-Layers] do not capture uses multiple times

---

lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/emit.mlir

This change allows a small subset of the SV ops to be nested in files.

[Emit] Emit SV ops nested in a file

---

lib/Dialect/ESI/runtime/CMakeLists.txt
lib/Dialect/ESI/runtime/cosim/CMakeLists.txt
lib/Dialect/ESI/runtime/cosim/MtiPliStub/CMakeLists.txt
lib/Dialect/ESI/runtime/cosim/cosim_dpi_server/CMakeLists.txt
lib/Dialect/ESI/runtime/cosim/esi-cosim.py
lib/Dialect/ESI/runtime/pyproject.toml
lib/Dialect/ESI/runtime/setup.py

Adds the ability to create Python wheels for the ESI runtime.

[ESI][Runtime] Building wheels

---

include/circt/Dialect/LLHD/IR/StructureOps.td
test/Dialect/LLHD/IR/inst-errors.mlir

[LLHD] Verify empty processes

---

include/circt/Dialect/SMT/SMTOps.td
lib/Dialect/SMT/SMTOps.cpp
test/Dialect/SMT/basic.mlir
test/Dialect/SMT/core-errors.mlir
unittests/Dialect/SMT/CMakeLists.txt
unittests/Dialect/SMT/QuantifierTest.cpp

Add operations to represent `forall` and `exists`.

[SMT] Add quantifier operations

---

include/circt/Conversion/CFToHandshake.h
lib/Conversion/CFToHandshake/CFToHandshake.cpp
lib/Conversion/CFToHandshake/CMakeLists.txt

[CFToHandshake] Move `Transforms` dependency to implementation

---

integration_test/Target/ExportSMTLIB/attributes.mlir
lib/Target/ExportSMTLIB/ExportSMTLIB.cpp
test/Target/ExportSMTLIB/attributes.mlir

Answers [this issue](https://github.com/llvm/circt/issues/6913) by adding support for the `weight` attribute in ExportSMTLIB. Includes also a new test.

[SMT] Added weight attribute support for ExportSMTLIB

---

lib/Dialect/Comb/CombFolds.cpp

I'm unsure if this is a good way to go about this, but I wanted to try my hand at #6840. I'm unsure if this is a good way to go about the problem, any feedback would be greatly appreciated.
The example provided by @uenoku in #6840 is
```
hw.module @Baz(in %cond : i2, in %value : i2, out o1: i2, out o2: i2) {
%0 = comb.and bin %cond, %value : i2
%1 = comb.and bin %0, %value : i2
hw.output %0, %1: i2, i2
}
```
which canonicalizes to
```
$ ./bin/circt-opt --canonicalize bin/baz.mlir
module {
hw.module @Baz(in %cond : i2, in %value : i2, out o1 : i2, out o2 : i2) {
%0 = comb.and bin %cond, %value : i2
%1 = comb.and bin %0, %value : i2
hw.output %0, %1 : i2, i2
}
}
```
instead of
```
module {
hw.module @Baz(in %cond : i2, in %value : i2, out o1 : i2, out o2 : i2) {
%0 = comb.and bin %cond, …
```

[Comb] Remove more idempotent operands

---

include/circt/Dialect/Seq/SeqOps.td
test/Dialect/Seq/compreg-space-printing.mlir

[Seq] Fix compreg printer printing two spaces

---

frontends/PyCDE/src/pycde/ibis.py
frontends/PyCDE/src/pycde/types.py
frontends/PyCDE/test/test_errors.py

Also, fix IbisClass for functions with zero arguments. IbisClass fix care of @mortbopet.

[pycde] Disallow structs with zero fields

---

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h
lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp
lib/Dialect/FIRRTL/Transforms/LegacyWiring.cpp
lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp
lib/Dialect/FIRRTL/Transforms/ResolveTraces.cpp

Just trying to test the llvm bump

(For LLVM Bump testing)[FIRRTL] AnnoTarget: use LLVM style casts

---

lib/Dialect/SV/Transforms/HWLegalizeModules.cpp

Separated from https://github.com/llvm/circt/pull/6996 as proposed by @uenoku, please merge at your convenience.

[HW][LegalizeModules] Avoid segmentation fault

---

frontends/PyCDE/src/pycde/ibis.py
lib/Dialect/ESI/runtime/CMakeLists.txt
lib/Dialect/ESI/runtime/cosim/CMakeLists.txt
lib/Dialect/ESI/runtime/cpp/cmake/esiaccel.cmake
lib/Dialect/ESI/runtime/python/esiaccel/utils.py

Wheel install now contains C++ headers, cmake file, and python func for
cmake location.

[ESI][Runtime] Python wheel now provides cpp support

---

lib/Dialect/Seq/SeqOps.cpp
test/Dialect/Seq/canonicalization.mlir

If the register has a const reset value, we can replace but we cannot replace it with a non-constant reset value.

[Seq] Fix incorrect folder

---

include/circt/Conversion/Passes.td
lib/Conversion/CombToSMT/CombToSMT.cpp
test/Conversion/CombToSMT/func-dependency.mlir

[CombToSMT] Register dependency on func

---

docs/PythonBindings.md

Fixes https://github.com/llvm/circt/issues/7115
This option no longer exists

[Docs] Update Python bindings pip instructions

---

lib/Dialect/FIRRTL/Import/FIRParser.cpp
test/Dialect/FIRRTL/parse-basic.fir

[FIRRTL][Parser] Never use forceable

---

lib/Dialect/FIRRTL/Transforms/LowerDPI.cpp

This is a preparation for another PR. Create `LowerDPI` struct and refactor the logic into several helper functions.

[LowerDPI] Refactor the lowering logic to a helper struct, NFC

---

lib/Dialect/FIRRTL/Export/FIREmitter.cpp
lib/Dialect/FIRRTL/Import/FIRLexer.cpp
test/Dialect/FIRRTL/annotations.mlir
test/Dialect/FIRRTL/assign-output-dirs.mlir
test/Dialect/FIRRTL/emit-basic.mlir
test/Dialect/FIRRTL/parse-basic.fir
test/firtool/dedup-modules-with-output-dirs.fir
test/firtool/lower-layers.fir

Errors introduced by me in #6971.

Fix paths in tests for windows builds

---

include/circt/Dialect/FIRRTL/FIRParser.h

Add missing header includes

---

lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp

Common pattern of walk/visit many operations looking for annotations and removing along the way is taking considerable amount of time in ArrayAttr::get.  Optimize the fast path for operations having no annotations.

[FIRRTL][NFC] Fast-path removeAnnotations for operations having none.

---

.github/workflows/buildAndTest.yml
lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/hw-dialect.mlir

This is a backport PR of #3357 for 1.5.x release.

Backport parentheses fix to 1.5.x

---

.github/workflows/nightlyIntegrationTests.yml
.github/workflows/shortIntegrationTests.yml

Disable ESI runtime build until #7236 can be figured out.

[CI] Revert to working image and disable ESI runtime

---

lib/Dialect/Seq/SeqOps.cpp
test/Dialect/Seq/canonicalization.mlir

Fix https://github.com/llvm/circt/issues/7266

[Seq] Remove incorrect canonicalization

---

lib/Dialect/ESI/runtime/CMakeLists.txt
lib/Dialect/ESI/runtime/cpp/lib/Accelerator.cpp

Turns out Windows python support was missing zlibd1.dll. Also adding backend plugin loading support.

[ESI Runtime] Windows: python support and backend plugin loading

---

lib/Conversion/MooreToCore/MooreToCore.cpp
test/Conversion/MooreToCore/basic.mlir

This op doesn't seem to have a lowering yet

[MooreToCore] Support NegOp lowering

---

.github/workflows/esiRuntimePublish.yml
lib/Dialect/ESI/runtime/CMakeLists.txt
lib/Dialect/ESI/runtime/setup.py

DLLs have to be installed to different locations on Windows.

[ESI][Runtime] Publish Windows wheels

---

lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp
test/Dialect/FIRRTL/lower-layers.mlir

Update the firrtl-lower-layers pass to lower layers with the inline convention. Layers with an inline convention will have a macro declaration created for them, and any layerblock will be lowered to an sv.macro.ifdef operation.

[FIRRTL] Add lowering support for inline layers

---

integration_test/Dialect/ESI/runtime/loopback.mlir.py
lib/Dialect/ESI/runtime/cpp/include/esi/Services.h
lib/Dialect/ESI/runtime/cpp/lib/Services.cpp
lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp
lib/Dialect/ESI/runtime/cpp/lib/backends/Trace.cpp
lib/Dialect/ESI/runtime/python/esiaccel/accelerator.py
lib/Dialect/ESI/runtime/python/esiaccel/esiCppAccel.cpp

This service is responsible for managing host memory which is accessible from the accelerator.

[ESI runtime] Host memory service

---

.github/workflows/buildAndTest.yml
test/lit.cfg.py

An issue like llvm/llvm-project#99626 could have been found more easily with roundtrip tests in CI. This PR adds a round trip tests In CI. This could slightly increase the test time but it's ignorable compared to build time. 
c.f. https://github.com/llvm/llvm-project/commit/a6d09d4b1ac224ed90ee8ff6c964a2bff39421c7
Close https://github.com/llvm/circt/issues/5272

[CI][lit] Enable roundtrip tests in CI

---

include/circt/Dialect/FIRRTL/Passes.h
include/circt/Dialect/FIRRTL/Passes.td
include/circt/Firtool/Firtool.h
lib/Dialect/FIRRTL/Transforms/CMakeLists.txt
lib/Dialect/FIRRTL/Transforms/ProbesToSignals.cpp
lib/Firtool/Firtool.cpp
test/Dialect/FIRRTL/SFCTests/data-taps-no-ref-type.fir
test/Dialect/FIRRTL/SFCTests/mem-taps.fir
test/Dialect/FIRRTL/probes-to-signals-errors.mlir
test/Dialect/FIRRTL/probes-to-signals.mlir

Add pass to replace basic probes with non-probe signals.

[FIRRTL][ProbesToSignals] Add pass to replace probes with signals.

---

include/circt/Dialect/Moore/MooreOps.td
lib/Conversion/ImportVerilog/Expressions.cpp
test/Conversion/ImportVerilog/basic.sv

Add support for the `**` operator.

[ImportVerilog] Support the power operator

---

frontends/PyCDE/integration_test/esi_test.py
frontends/PyCDE/integration_test/test_software/esi_test.py
frontends/PyCDE/src/pycde/bsp/common.py
frontends/PyCDE/src/pycde/bsp/cosim.py
frontends/PyCDE/src/pycde/esi.py
lib/Dialect/ESI/ESIStdServices.cpp
lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp
test/Dialect/ESI/services.mlir

Replaces write with read_write.

[ESI] MMIO: add read/write port to service

---

utils/linkify.sh

See: https://llvm.org/pr103496

[NFC] Add circt copy of upstream's linkify.

---

frontends/PyCDE/integration_test/test_software/esi_test.py
frontends/PyCDE/src/pycde/bsp/common.py
frontends/PyCDE/src/pycde/esi.py
include/circt/Dialect/ESI/ESIStdServices.td
lib/Dialect/ESI/runtime/cpp/include/esi/Design.h
lib/Dialect/ESI/runtime/cpp/include/esi/Services.h
lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp
lib/Dialect/ESI/runtime/cpp/lib/Services.cpp
lib/Dialect/ESI/runtime/python/esiaccel/accelerator.py
lib/Dialect/ESI/runtime/python/esiaccel/esiCppAccel.cpp
lib/Dialect/ESI/runtime/python/esiaccel/types.py

Access MMIO address regions by the AppID of the requestor. Also provide access to the MMIO space descriptors.

[ESI][Runtime] Address MMIO regions symbolically

---

include/circt/Dialect/ESI/ESIManifest.td
integration_test/Dialect/ESI/runtime/callback.mlir
lib/Dialect/ESI/ESIOps.cpp
lib/Dialect/ESI/Passes/ESIBuildManifest.cpp
lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp
test/Dialect/ESI/manifest.mlir

Changes falling out of an audit conducted by Morten and myself.

[ESI] Manifest: change the schema to be more rational

---

lib/Conversion/MooreToCore/MooreToCore.cpp
test/Conversion/MooreToCore/basic.mlir

This is a simple way to map unpackedStructType (Moore type) to structType in hw dialect directly.

[MooreToCore] Support to lower unpacked struct type

---

lib/Conversion/MooreToCore/MooreToCore.cpp
test/Conversion/MooreToCore/errors.mlir

[MooreToCore] Return early on non-convertable type

---

lib/Support/JSON.cpp

Make sure that calls to begin/end functions are balanced even when an error occurs. This leaves the `json::OStream` object in a valid state and allows surrounding code to handle the failure gracefully. Otherwise an assertion in the destructor of `json::OStream` would fire because of unclosed JSON scopes.

[JSON] Leave json::OStream in valid state on failure

---

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp

The frame.indent reference can be invalidated when we push to the worklist. This change caches the indentation level locally to fix the issue. Bug was introduced in b836e24.

[FIRRTL] InferWidths: fix invalid frame reference

---

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp

Update the CreateSiFiveMetadata pass to use the InstanceInfo analysis to check if modules/memories are instantiated under the effective DUT as opposed to using custom logic to check this.

[FIRRTL] Use InstanceInfo in CreateSiFiveMetadata

---

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
test/Conversion/SCFToCalyx/convert_controlflow.mlir

This patch supports `BuildControl` for nested `scf::If` operations

[SCFToCalyx] Build control for nested if operation

---

lib/Dialect/HW/InnerSymbolTable.cpp

This changes the inner symbol table to only check top-level operations for portlists.  Trying to dyn_cast every single operation to PortList is expensive, and is not a cost we have to pay when only module operations have port lists.

[HW] InnerSymbolTable: only check top-level ops for portlists

---

lib/Dialect/FIRRTL/FIRRTLOps.cpp

This change makes some op builders and parser populate the property struct
directly instead of adding them to the attr-dict.  During operation
creating, any inherent attributes are copied out of the
result.attributes and in to the properties struct.  It is more idiomatic
and slightly more efficient to store inherent attributes directly in
properties.

[FIRRTL] use properties in some builders and parsers

---

lib/Conversion/HWToBTOR2/HWToBTOR2.cpp

Very small NFC just to update the language used in the pass referring to initial values

[HWToBTOR2][NFC] update 'PowerOn' in error message and comments

---

lib/Conversion/HandshakeToDC/HandshakeToDC.cpp
test/Conversion/HandshakeToDC/basic.mlir

After the lowering, add clock and reset ports (with the required attributes) to all of the created modules.
Resolves #7818.

[HandshakeToDC] Add clock and reset ports

---

include/circt-c/Dialect/HW.h
lib/Bindings/Python/CIRCTModule.cpp
lib/Bindings/Python/CMakeLists.txt
lib/CAPI/Dialect/CMakeLists.txt
lib/CAPI/Dialect/HW.cpp

Expose Arc and HW passes to CAPI and Python bindings.

[CAPI][Python][Arc, HW] Register Arc and HW passes

---

test/Conversion/HWToBTOR2/comb.mlir
test/Conversion/HWToBTOR2/combOOO.mlir
test/Conversion/HWToBTOR2/compreg-resets.mlir
test/Conversion/HWToBTOR2/compreg.mlir
test/Conversion/HWToBTOR2/errors.mlir
test/Conversion/HWToBTOR2/init.mlir
test/Conversion/HWToBTOR2/seq.mlir

Hopefully should fix the breaking CI on c5f14f1c26e6ddca74a1e11eed376a740bfad2ad :crossed_fingers:

[HWToBTOR2] Swap to temp file placeholder

---

include/circt/Dialect/RTG/IR/RTGOps.td
include/circt/Dialect/RTG/IR/RTGTypes.td
include/circt/Dialect/RTG/IR/RTGVisitors.h
lib/Dialect/RTG/IR/RTGOps.cpp
test/Dialect/RTG/IR/basic.mlir

Add an RTG visitor ahead of adding a pass using it to keep the pass PR small(er).

[RTG] Add op and type visitors

---

integration_test/lit.cfg.py

I'm so sorry that my incorrect rebase in #7884 broke that PR. This is the correct version.

[circt-test] fix lit config for circt-bmc

---

include/circt-c/Dialect/DC.h
lib/Bindings/Python/CIRCTModule.cpp
lib/Bindings/Python/CMakeLists.txt
lib/CAPI/Dialect/CMakeLists.txt
lib/CAPI/Dialect/DC.cpp

[DC] Add CAPI bindings for DC

---

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp

this patch removes redundant `BuildSwitchGroup` in the SCFToCalyx pass because git rebase wasn't handled gracefully in this pr: https://github.com/llvm/circt/pull/7905

[SCFToCalyx] remove redundant build switch group

---

test/Conversion/SCFToCalyx/write_memory.mlir

[SCFToCalyx] replace shell command with %T for Windows in the test file

---

integration_test/Dialect/Handshake/buffer_arg_init/buffer_arg_init.mlir
integration_test/Dialect/Handshake/buffer_arg_init/buffer_arg_init.py
integration_test/Dialect/Handshake/buffer_init_none/buffer_init_none.mlir
integration_test/Dialect/Handshake/buffer_initial_values/buffer_initial_values.mlir
integration_test/Dialect/Handshake/sync_backedge/sync_backedge.mlir
integration_test/Dialect/Handshake/sync_op/sync_op.mlir
integration_test/Dialect/Handshake/tuple_packing/tuple_packing.mlir
lib/Conversion/DCToHW/DCToHW.cpp
lib/Conversion/HandshakeToDC/HandshakeToDC.cpp

Pass them through to DC, then error out in the DCToHW lowering since
nothing simple supports loading content on reset.

[DC] Initial values were being ignored

---

integration_test/circt-synth/comb-lowering-lec.mlir
lib/Conversion/CombToAIG/CombToAIG.cpp
test/Conversion/CombToAIG/comb-to-aig.mlir

```
c ? a : b => (replicate(c) & a) | (~replicate(c) & b)
```
Add a LEC test for CombToAIG.

[CombToAIG] Add mux lowering

---

lib/Dialect/Comb/CombFolds.cpp
test/Dialect/Comb/canonicalization.mlir

Adds a few checks to avoid infinite canonicalizer runtime in some corner cases.

[Comb] Don't try to canonicalize muxes indefinitely

---

frontends/PyCDE/src/pycde/esi.py
frontends/PyCDE/test/test_compreg.py
frontends/PyCDE/test/test_xrt.py
lib/Bindings/Python/ESIModule.cpp
lib/Bindings/Python/MSFTModule.cpp

The ESI and MSFT Python modules had object memory leaks which upstream nanobind detected. Fixing them.

[PyCDE][Python] Fixing leaks reported by nanobind

---

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp
test/Dialect/FIRRTL/imdce.mlir

Mark any modules alive that appear as symbol references outside of hierarchical path and instance operations. Prevent modules from being deleted if they are explicitly marked as alive. This fixes an issue in IMDCE where references to modules in `firrtl.formal` or other unknown operations would become invalidated due to the pass deleting the modules despite these references.
The pattern of walking operations' attribute dictionary an looking for symbol references is inspired by what MLIR's `SymbolTable` does internally in `walkSymbolRefs` when looking for symbol uses.

[FIRRTL][IMDCE] Don't remove modules with symbol uses

---

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp
test/Conversion/SCFToCalyx/convert_func.mlir
test/Conversion/SCFToCalyx/convert_memory.mlir

This patch solves: https://github.com/llvm/circt/issues/8126

[SCFToCalyx] Remove `init_xxx_instance` in `BuildCallInstance`

---

frontends/PyCDE/src/pycde/bsp/xrt.py
lib/Dialect/ESI/runtime/cpp/tools/esitester.cpp

Validated in hardware. The vitis emulation model doesn't respect WSTRB so it fails the test.

[ESI][XRT BSP] Host memory writes

---

lib/Dialect/LLHD/Transforms/DesequentializationPass.cpp

Fixes a crash if the number of primitives is too big

[LLHD] Move maxPrimitives check before initializing the 'dontCare' table

---

include/circt/Dialect/RTG/IR/RTGAttributes.td
include/circt/Dialect/RTGTest/IR/CMakeLists.txt
include/circt/Dialect/RTGTest/IR/RTGTestAttributes.td

These are pretty common, they can go in RTG.

[RTG] Move immediates to RTG from RTGTest

---

frontends/CMakeLists.txt
frontends/PyRTG/.gitignore
frontends/PyRTG/CMakeLists.txt
frontends/PyRTG/pyproject.toml
frontends/PyRTG/src/CMakeLists.txt
frontends/PyRTG/src/pyrtg/__init__.py
frontends/PyRTG/src/pyrtg/tests.py
frontends/PyRTG/src/rtgtool/rtgtool.py
frontends/PyRTG/test/CMakeLists.txt
frontends/PyRTG/test/basic.mlir
frontends/PyRTG/test/basic.py
frontends/PyRTG/test/lit.cfg.py
frontends/PyRTG/test/lit.site.cfg.py.in
lib/Dialect/RTG/Transforms/EmitRTGISAAssemblyPass.cpp

This commit adds the boiler plate and basic rtgtool with a minimal example to run.

[RTG] Add the PyRTG frontend

---

include/circt/Dialect/LLHD/Transforms/LLHDPasses.td
lib/Dialect/LLHD/Transforms/Sig2RegPass.cpp
test/Dialect/LLHD/Transforms/sig2reg.mlir

Only handles integer signal slices for now. I think it makes sense to expand on that in future PRs (array, struct aliases, drives with enables, etc.)

[LLHD][Sig2Reg] Support integer signal aliasing

---

test/circt-synth/basic.mlir
test/circt-synth/unregistered-dialect.mlir
tools/circt-synth/CMakeLists.txt
tools/circt-synth/circt-synth.cpp

This PR makes circt-synth load dialects that firtool could emit.

[circt-synth] Load dialects that firtool emits

---

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td
lib/Dialect/FIRRTL/FIRRTLFolds.cpp
test/Dialect/FIRRTL/canonicalization.mlir

This PR addresses https://github.com/llvm/circt/issues/6724 for two basic cases.

[FIRRTL] Add folder for `mul` property op

---

include/circt-c/ExportSMTLIB.h
lib/CAPI/CMakeLists.txt
lib/CAPI/ExportSMTLIB/CMakeLists.txt
lib/CAPI/ExportSMTLIB/ExportSMTLIB.cpp
test/CAPI/CMakeLists.txt
test/CAPI/smtlib.c
test/CMakeLists.txt
test/lit.cfg.py

This pr implement mlirExportSMTLIB C API and add test.
Just like what #481 and #5300 did.

[ExportSMTLIB] Implement ExportSMTLIB C API

---

lib/Dialect/Calyx/Transforms/AffineParallelUnroll.cpp
test/Dialect/Calyx/affine-parallel-unroll.mlir

This patch fixes the empty lookup issue when first looking up `constantWriteOpIndices`.
Also, I moved the canonicalization passes before `MemoryConflictResolver`. It's because the `AffineParallelUnroll` pass introduces a lot of constant values, and running the canonicalization passes in advance can simplify the analysis work in `MemoryConflictResolver`.
And I also added a test case for the changes.

[AffineParallelUnroll] Fix empty map lookup; move canonicalization passes before `MemoryConflictResolver`

---

include/circt-c/Dialect/SMT.h
lib/CAPI/Dialect/SMT.cpp
test/CAPI/smtlib.c

This pr adds more necessary CAPIs to the SMT dialect, including types and attributes.

[SMT][CAPI] Add more SMT C API

---

include/circt/Dialect/Calyx/CalyxPrimitives.td
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Dialect/Calyx/CalyxOps.cpp
lib/Dialect/Calyx/Export/CalyxEmitter.cpp
lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp
test/Conversion/SCFToCalyx/convert_simple.mlir
test/Dialect/Calyx/emit.mlir

This patch supports `arith.sitofp` and its emit, relevant Calyx backend support: https://github.com/calyxir/calyx/pull/2422

[SCFToCalyx] Support Arith sitofp lowering and its emit

---

lib/Dialect/ESI/Passes/ESILowerToHW.cpp
test/Dialect/ESI/lowering.mlir

[ESI] Add RemoveSnoopOp conversion pattern

---

include/circt/Dialect/Calyx/CalyxPrimitives.td
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Dialect/Calyx/CalyxOps.cpp
lib/Dialect/Calyx/Export/CalyxEmitter.cpp
lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp
test/Conversion/SCFToCalyx/convert_simple.mlir
test/Dialect/Calyx/emit.mlir

This patch supports `arith.divf`'s lowering and its emit.

[SCFToCalyx] Arith DivFOp lowering and its emit

---

include/circt/Dialect/SV/SVStatements.td
include/circt/Dialect/SV/SVVisitors.h
lib/Conversion/ExportVerilog/ExportVerilog.cpp
test/Conversion/ExportVerilog/verilog-basic.mlir

Add a backtick-include directive. The include target is just specified as a string attribute.

[SV] Add preprocessor include op

---

lib/Conversion/FIRRTLToHW/LowerToHW.cpp

This commit is just a minor simplification to LowerToHW.

[LowerToHW] Lower all op bodies in parallel

---

lib/Bindings/Python/pyproject.toml
lib/Bindings/Python/setup.py

Successful build: https://github.com/llvm/circt/actions/runs/14630320191

[bindings] fix wheels

---

lib/Dialect/HW/HierPathCache.cpp

Properly fuse the locations created by the `HierPathCache`
`getOrCreatePath` API.

[hw] Fuse HierPathCache locations

---

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp

We should not write to file when json data is empty.

[SCFToCalyx] Should not write to file when json data is empty

---

frontends/PyRTG/src/CMakeLists.txt
frontends/PyRTG/src/pyrtg/__init__.py
frontends/PyRTG/src/pyrtg/control_flow.py
frontends/PyRTG/src/pyrtg/scf.py
frontends/PyRTG/src/rtgtool/rtgtool.py
frontends/PyRTG/test/test_control_flow.py
lib/Bindings/Python/CIRCTModule.cpp
lib/Bindings/Python/CMakeLists.txt

This is a first implementation for if-statements and for/foreach-loops. We probably want to iterate on that because the stack frame manipulations and accessing is not great.

[PyRTG] Add control flow constructs

---

unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp

This is just adding a test that we can concatenate lists of lists and
return the right result in the Evaluator.

[OM] Add test for nested lists in ListConcatOp evaluator.

---

include/circt/Dialect/Comb/Combinational.td
lib/Dialect/Comb/CombOps.cpp
test/Dialect/Comb/errors.mlir

Closes #8394. Also adds a test to check inference is as expected.

[Comb] Drop redundant concat verifier

---

frontends/PyCDE/test/test_esi.py
frontends/PyCDE/test/test_esi_advanced.py
include/circt/Dialect/ESI/ESIChannels.td
lib/Dialect/ESI/ESIOps.cpp
test/Conversion/DCToHW/basic.mlir
test/Dialect/ESI/connectivity.mlir
test/Dialect/ESI/lowering.mlir

- Spell out the type names
- Use generated declarative parsers

[ESI] Move to somewhat more standard asm format

---

include/circt/Support/InstanceGraph.h
unittests/Dialect/HW/InstancePathTest.cpp

This commit adds DenseMapInfo for InstancePath.

[HW] Make InstancePath hashable for DenseMap

---

lib/Dialect/LLHD/Transforms/Mem2Reg.cpp
test/Dialect/LLHD/Transforms/mem2reg.mlir

Extend the Mem2Reg pass to support drives to `llhd.sig.array_get` projections into a promotable signal. This requires a few changes:
- When checking whether a signal is promotable, we have to recursively check its users and look through `llhd.sig.array_get` ops to see if all uses are safe for promotion.
- The lattice used to propagate needed and reaching definitions has to track the projection being driven separately from the underlying root slot being driven.
- A new set of helpers to unpack and pack stacks of projections help probes and drives take a promotable slot and its value, descend into subfields as indicated by a set of projection ops ("unpack"), and then optionally mutate the value of a subfield and zip the updated value back up to the promotable slot ("pack").
- During …

[LLHD] Add support for `llhd.sig.array_get` projections to Mem2Reg

---

lib/Dialect/ESI/runtime/cosim_dpi_server/esi-cosim.py

see https://github.com/llvm/circt/pull/5098

[ESI] Add 'server-only' mode to esi-cosim.py

---

lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp
test/Dialect/FIRRTL/inject-dut-hierarchy.mlir

[FIRRTL][InjectDUT] Update rwprobes when relocating them.

---

lib/Dialect/Arc/Transforms/MergeIfs.cpp
test/Dialect/Arc/merge-ifs.mlir

Currently MergeIfs makes sure it doesn't sink a write op, but it doesn't check whether it's sinking an op that _contains_ a write op. The current version sinks the first IfOp in the integration test into the second, which is invalid as it adds a new condition to the write inside. Instead, this PR just tracks whether the op currently being sunk contains or is a write, and uses that to decide whether to sink.

[Arc] don't sink ops with nested writes in MergeIfs

---

lib/Conversion/ImportVerilog/Expressions.cpp
test/Conversion/ImportVerilog/basic.sv

[ImportVerilog] Support packed structs in `inside` operator

---

include/circt/Dialect/AIG/Analysis/LongestPathAnalysis.h
lib/Dialect/AIG/Analysis/LongestPathAnalysis.cpp
lib/Dialect/AIG/Analysis/PrintLongestPathAnalysis.cpp

Add LongestPathCollection class to manage and own path data

[AIG][NFC] Introduce a helper struct to manage result paths

---

frontends/PyCDE/src/pycde/bsp/cosim.py
frontends/PyCDE/src/pycde/esi.py
frontends/PyCDE/src/pycde/signals.py
frontends/PyCDE/src/pycde/support.py

Improves the location information emitted from PyCDE.
- Move from single location to stack
- Add location to a bunch of places it was missing

[PyCDE] Improve location information

---

include/circt/Dialect/SV/SVExpressions.td
lib/Bindings/Python/MSFTModule.cpp

Preparing this week's bump to get
* https://github.com/llvm/llvm-project/pull/149087
* https://github.com/llvm/llvm-project/pull/139694
Changes:
* Remove ambiguous builder in SV

Bump LLVM to d9190f8141661bd6120dea61d28ae8940fd775d0

---

integration_test/Bindings/Python/dialects/aig.py
lib/Dialect/AIG/Analysis/LongestPathAnalysis.cpp
test/Dialect/AIG/longest-paths.mlir
test/circt-synth/path-e2e.mlir

Fix https://github.com/llvm/circt/issues/8745

[AIG][LongestPathAnalysis] Fix a bug in deduplicatePathsImpl

---

lib/Dialect/RTG/Transforms/ElaborationPass.cpp
test/Dialect/RTG/Transform/elaboration.mlir

This is a super hacky fix to get some real-world use-cases going. We have to revisit this later to add proper support.

[RTG] Support immediate slice/concat after validate

---

lib/Dialect/ESI/runtime/python/esiaccel/types.py

Previously, if one has a function with only a single `BitsType` argument, there was no way that this code could provide a correct argument to be serialized, given that only `kwargs` would be accepted - which is a dict, and not serializeable by `BitsType`.
Modified argument handling abit s.t.
1. users have to provide either kwargs or positional
2. if positional arguments are provided, and only a single is present, it is unpacked, ensuring that the validation and serialization code doesn't recieve a tuple, but instead the underlying value.

[ESI] Better single-argument handling for FunctionPort

---

test/Conversion/CFToHandshake/task-pipelining-invalid.mlir
test/Conversion/CFToHandshake/task-pipelining.mlir

Bump for 75964244d62f0c42e7b2df3d72245e8f29a29809

Bump LLVM to 76bebb5be9daf9ca035777b17fa63d4ce13e79b9

---

lib/Dialect/ESI/runtime/cpp/lib/Accelerator.cpp

Fix a bug in the backend DLL loading code wherein if the backend DLL is in the CWD it wouldn't be found. Also improve backend loading logging.

[ESI][Runtime] Fix backend DLL loading

---

lib/Dialect/ESI/runtime/cpp/lib/Accelerator.cpp

Wasn't working when SO was in CWD.

[ESI][Runtime] Fix Linux backend loading

---

integration_test/Dialect/DC/max/max.mlir
integration_test/Dialect/ESI/widgets/esi_widgets.mlir
integration_test/Dialect/FSM/simple/top.mlir
integration_test/Dialect/Handshake/buffer_arg_init/buffer_arg_init.mlir
integration_test/Dialect/Handshake/buffer_init_none/buffer_init_none.mlir
integration_test/Dialect/Handshake/buffer_initial_values/buffer_initial_values.mlir
integration_test/Dialect/Handshake/conditional_modification/conditional_modification.mlir
integration_test/Dialect/Handshake/dot/dot.mlir
integration_test/Dialect/Handshake/matmul/matmul.mlir
integration_test/Dialect/Handshake/max/max.mlir
integration_test/Dialect/Handshake/mix_std_hs/mix_std_hs.mlir
integration_test/Dialect/Handshake/multiple_loops/multiple_loops.mlir
integration_test/Dialect/Handshake/nested_diamonds/nested_diamonds.mlir
integration_test/Dialect/Handshake/nested_loops/nested_loops.mlir
integration_test/Dialect/Handshake/sync_backedge/sync_backedge.mlir
integration_test/Dialect/Handshake/sync_op/sync_op.mlir
integration_test/Dialect/Handshake/task_pipelining/task_pipelining.mlir
integration_test/Dialect/Handshake/tp_memory/tp_memory.mlir
integration_test/Dialect/Handshake/tuple_input/tuple_input.mlir
integration_test/Dialect/Handshake/tuple_packing/tuple_packing.mlir
integration_test/Dialect/Pipeline/nonstallable/test1/nonstallable_test1.mlir
integration_test/Dialect/Pipeline/nonstallable/test2/nonstallable_test2.mlir
integration_test/Dialect/Pipeline/simple/simple.mlir
integration_test/Dialect/Pipeline/stall/stallTest.mlir
integration_test/Dialect/Seq/fifo/fifo.mlir
test/Conversion/SCFToCalyx/write_memory.mlir
test/Target/DebugInfo/emit-hgldd.mlir

Close https://github.com/llvm/circt/issues/8823
Changes are based on https://github.com/llvm/llvm-project/blob/44af26ea2e0b0fedb74276f9678eba4df5f83aab/llvm/docs/TestingGuide.rst?plain=1#L740

[NFC] Remove %T from tests

---

lib/Dialect/LLHD/Transforms/Mem2Reg.cpp
test/Dialect/LLHD/Transforms/mem2reg.mlir

Add support for `llhd.sig.struct_extract` projections to the LLHD Mem2Reg pass.

[LLHD] Add struct extract support to mem2reg

---

include/circt/Dialect/Handshake/HandshakePasses.h
include/circt/Support/FoldUtils.h
include/circt/Support/LoweringOptionsParser.h
lib/Conversion/CombToAIG/CombToAIG.cpp
lib/Conversion/ExportAIGER/ExportAIGER.cpp
lib/Conversion/ImportVerilog/AssertionExpr.cpp
lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
lib/Dialect/AIG/Analysis/LongestPathAnalysis.cpp
lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp
lib/Dialect/Emit/EmitOpInterfaces.cpp
lib/Dialect/FIRRTL/FIRRTLIntrinsics.cpp
lib/Dialect/Handshake/HandshakeUtils.cpp
lib/Dialect/Kanagawa/Transforms/KanagawaContainerize.cpp
lib/Dialect/LLHD/Transforms/HoistSignals.cpp
lib/Dialect/Pipeline/Transforms/ExplicitRegs.cpp
lib/Transforms/MemoryBanking.cpp
tools/circt-verilog/CMakeLists.txt
tools/circt-verilog/circt-verilog.cpp

Remove some unneeded defs and unused variable warnings.

---

lib/Dialect/Arc/Transforms/MergeIfs.cpp

Improves runtime of this pass for dual-mega boom in circt/arc-tests from ~59 sec to ~0.45 sec

[Arc][MergeIfs] Improve performance

---

lib/Dialect/Verif/Transforms/LowerContracts.cpp
test/Dialect/Verif/lower-contracts.mlir

When cloning self-referencing operations like
%reg = seq.firreg %reg clock %clock reset sync %reset, %c0_i4 : i4
lower-contracts would previously produce something like:
^bb0(%arg0: !seq.clock, %arg1: i1):
...
%5 = seq.firreg(%5, %arg0, %arg1, %4) : i4
...
verif.formal():
...
%3 = seq.firreg(%5, %0, %1, %2) : i4
...
Here we can see that the verif.formal test refers to a value from `bb0`, namely `%5`, which results in an error.
The problem appears to be that when cloning the operation, we haven't yet created a mapping for the operation's result (`%5 -> %3`), so `%5` is left in place.
This change makes us go through all operands of the cloned operations once more, _after_ adding the mappings for the operations' results, which means that the `%5` in verif.formal is remapped to `%3`.
This is …

[Verif] handle self-referencing operations

---

lib/Dialect/Synth/SynthOps.cpp

[AIG] feat : and_inv fold

---

lib/Conversion/ImportVerilog/Expressions.cpp

Closes https://github.com/llvm/circt/issues/9011

Add a diagnostic for unsupported system calls with more than 1 argument

---

lib/Dialect/ESI/runtime/cosim_dpi_server/Cosim_Endpoint.sv
lib/Dialect/ESI/runtime/cosim_dpi_server/driver.sv

Also removes outdated debug output from cosim endpoints.

[ESI][Cosim] Enable SAVE_WAVE functionality in SV driver
