lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp
We are not doing any bundle lowering in lower to RTL anymore and this
class is unneeded.
=> [FIRRTL] Remove unused class from lower to rtl

include/circt/Dialect/SV/SVStatements.td, lib/Dialect/SV/SVOps.cpp, test/Dialect/SV/canonicalization.mlir
This PR canonicalizes `sv.if` with a constant condition. 
The logic is ported from SCF dialect canonicalization ([Dialect/SCF/SCF.cpp](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/SCF/SCF.cpp#L776))
Part of #636.
=> [SV] Canonicalize sv.if true and sv.if false

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Dialect/FIRRTL/lower-types.mlir
Add support for lowering aggregate registers in FIRRTL dialect's type lowering pass.
Just adding the visitor for registers was required.
Fix for https://github.com/llvm/circt/issues/682
=> [FIRRTL] Lower registers in LowerTypes

test/Dialect/FIRRTL/connect-errors.mlir, test/Dialect/FIRRTL/connect.mlir
Regular tests cannot be in the same file as error tests, due to the
absence of FileCheck from the diagnostic verification tests.  Before
this change, the positive checks were accidentally not being checked.
The error tests were moved into `connect-errors.mlir`.  The regular tests
are no longer tested using `-split-input-file`, and all modules had to be
renamed to avoid a name collision.
=> [FIRRTL] Split connect error tests from regular tests

include/circt/Dialect/Comb/Combinational.td, lib/Dialect/Comb/CombFolds.cpp, lib/Dialect/Comb/CombOps.cpp, test/Dialect/RTL/canonicalization.mlir, test/Dialect/RTL/errors.mlir
Will close #692 
This patch also adds a folder for sext op
=> [Comb] Allow operand and result of SExtOp to have the same width and add folder

lib/Translation/ExportVerilog/ExportVerilog.cpp
The OpTraits namespace is not properly imported into the CIRCT namespace
when compiling with GCC.  This is a known issue, but one we don't have a
solution for yet.
=> [ExportVerilog] Fix GCC error when using OpTraits

lib/Dialect/Comb/CombFolds.cpp, test/Dialect/RTL/canonicalization.mlir
This is the follow-up to #648.
```
mux(a, false, b) => and(not(a), b)
mux(a, b, true) => or(not(a), b)
```
Will close #635.
=> [Comb] Additional mux canonicalization

include/circt/Dialect/Comb/CombOps.h, include/circt/Dialect/Comb/CombVisitors.h, include/circt/Dialect/Comb/Combinational.td, include/circt/Dialect/RTL/RTLAggregates.td, include/circt/Dialect/RTL/RTLVisitors.h, lib/Dialect/Comb/CombDialect.cpp, lib/Dialect/Comb/CombOps.cpp, lib/Dialect/ESI/capnp/Schema.cpp, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/Dialect/RTL/basic.mlir, test/Dialect/RTL/bitwise.mlir, test/ExportVerilog/rtl-dialect.mlir, test/ExportVerilog/sv-dialect.mlir
Moving bitcast to live with the rest of the of the type operations. Also remove a few unnecessary #includes to the rtl dialect. Unfortunately, this doesn't eliminate the Comb -> RTL dependence since folders and a materialize constant got added which use rtl::ConstantOp. (I haven't been paying attention the last week or two.)
Mechanical refactoring.
=> [RTL/Comb] Move bitcast back to RTL dialect

lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
Bug: When the create-dataflow pass tries to use merge-like ops to replace block args, it does not check whether the new value is another block arg. This patch fixes this by checking if it is another block arg, and if it is, replacing  with the result from the corresponding new op.
=> [Handshake] Fixed a bug in StandardToHandshake

lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/sv-interfaces.mlir
When structs were present as signals in SV interfaces, `logic` was printed instead of the struct.
=> [ExportVerilog] Fixed struct printing in interfaces

.github/workflows/nightlyIntegrationTests.yml
This PR expands the nightly builds to run more of our supported build
configurations.  This adds (almost) all combinations of the following
variables:
```
CXX = [clang++, g++]
BUILD_SHARED_LIBS = [ON, OFF]
LLVM_ENABLE_ASSERTION = [ON, OFF]
CMAKE_BUILD_TYPE = [Release, Debug]
```
The gcc+sharedlibs combinations have been disabled (see issue #708).
This  leads to a total of 12 builds.  Every build shares the same cached
version of LLVM and should only take a couple of minutes for each to
complete.
Example build here: https://github.com/youngar/circt/actions/runs/617133108
Looks like its ~5 minutes per build, assuming LLVM is cached.
=> [CI] Expand the Nightly CI build coverage.

.github/workflows/buildAndTest.yml
This change adds a GCC build to the buildAndTest job which is run on
every PR.  This step takes about 1m 30s to complete.
This also combines the two clang builds, in release and debug mode, into
a single build, release+asserts.  Normally, a cmake release build adds
-DNDEBUG to all command line options.  The LLVM cmake system has a flag
to override this, LLVM_ENABLE_ASSERTIONS.  Building in release mode with
assertions should give us the best of both worlds for error checking.
The GCC builds will be running in the same release+assert build
configuration.
=> [CI] Replace Clang PR build with GCC build

include/circt/Dialect/SV/SV.td, include/circt/Dialect/SV/SVInOutOps.td, include/circt/Dialect/SV/SVOps.h, include/circt/Dialect/SV/SVStatements.td, lib/Dialect/SV/SVOps.cpp, test/Dialect/SV/errors.mlir
Similar to #719, this PR adds `NonProceduralOp` trait which checks operations with this trait must not be in procedural regions.
I added the trait to `wire, ifdef, always, alwaysff, initial`.
=> [SV] Add NonProceduralOp trait

lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp, test/Conversion/FIRRTLToRTL/lower-to-rtl.mlir
Match Scala firrtl in outputting a verilator guard around alias.
closes #738
=> Alias not supported by verilator

include/circt/Dialect/FIRRTL/Passes.td, lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Dialect/FIRRTL/lower-types.mlir, tools/firtool/firtool.cpp
This adds FExtModule lowering support to the lower types pass. This
flattens all types in the parameter list and gives each new operand a
new name.
To process ExtModules in this pass, it had to change from a FModuleOp
pass to a CircuitOp pass. In order to maintain performance, this pass is
now parallelized internally. This parallelization follows a similar
pattern to the PassManager: it creates a worker for each hardware thread
and they compete for the next work unit.
=> [FIRRTL LowerTypes] Add FExtModule type lowering

lib/Dialect/FIRRTL/Transforms/BlackboxMemory.cpp, test/Dialect/FIRRTL/blackbox-memory.mlir
When inlining modules, blackboxing is connecting module ports to wires
backwards.  This is due to using the type of the wire to determine which
side of the connect should be the LHS.  Switching to using the type of
the memory module outputs fixes the issue.
=> [FIRRTL] Blackbox memory connecting wires backwards.

lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/sv-dialect.mlir
Change Verilog emission to not emit an "assign" when in a procedural
region.  Emit a blocking assign instead.
Fixes #751.
The following code (copied from the example in #751):
```mlir
rtl.module @foobar(%clock: i1, %arg1: i1, %arg2: i1, %arg3: i1) {
sv.always posedge %clock  {
sv.if %arg1  {
sv.fatal
}
//this forces a common subexpression to be output out-of-line
%610 = comb.and %arg1, %arg2 : i1
%611 = comb.and %arg3, %610 : i1
sv.if %610  {
sv.fatal
}
sv.if %611  {
sv.fatal
}
}
rtl.output
}
```
Will now produce:
```verilog
module foobar(
input clock, arg1, arg2, arg3);
always @(posedge clock) begin
automatic logic _T;
if (arg1)
$fatal;
_T = arg1 & arg2;
if (_T)
$fatal;
if (arg3 & _T)
$fatal;
end // always @(posedge)
endmodule
```
Previously this would produce:
```verilog
module foobar( …
```
=> [Verilog] Don't emit assign in a procedural block

lib/Dialect/SV/CMakeLists.txt, lib/Dialect/SV/SVDialect.cpp, lib/Dialect/SV/SVOps.cpp, test/Dialect/SV/canonicalization.mlir
This PR adds canonicalization for SVOp. If the then block is empty and else block is not empty, inverts the conditions. 
The dependency from SV dialect to Comb dialect is added to create `comb.xor` within SVDialect.
Will close #721
=> [SV] Invert IfOp if thenBlock is empty

include/circt/Translation/ExportVerilog.h, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/firtool/split_verilog.mlir, tools/firtool/firtool.cpp
Add a `-split-verilog` option to `firtool` that will emit a separate file for each and every module in the IR. Requires the user to specify an output directory path via the existing `-o=<dir>` option.
The current single-file Verilog emitter supports `RTLModuleOp`, `RTLModuleExternOp`, `InterfaceOp`, `VerbatimOp`, and `IfDefProceduralOp`. The first three have compilation-unit scope in SV, so they are put into separate files. The main concern are the `sv.verbatim` and `sv.ifdef.procedural` operations where we can't really reason about whether they contain file-scope business (e.g., preprocessor macros) or compilation-unit scope (e.g., a module/interface as inline verilog). The current implementation assumes these to be preprocessor directives (or generally anything that follows a …
=> [firtool] Add option to emit one file per Verilog module

lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp, test/Conversion/FIRRTLToRTL/lower-to-rtl.mlir
Add the missing back-tick and update lit-tests, as mentioned in, https://github.com/llvm/circt/issues/754#issuecomment-800540665
=> Add missing back-tick to RANDOMIZE_GARBAGE_ASSIGN_BOUND_CHECK

include/circt/Dialect/Comb/Combinational.td, lib/Dialect/Comb/CombFolds.cpp, test/Conversion/FIRRTLToRTL/lower-to-rtl.mlir, test/Dialect/RTL/canonicalization.mlir
Add the fold hook for comb.sub to handle the following cases
1. x - 0
2. x - x
3. const1 - const2
Fix for https://github.com/llvm/circt/issues/769
=> [Comb] Constant folding hook for comb.sub

include/circt/Dialect/SV/SVStatements.td, lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/Conversion/FIRRTLToRTL/lower-to-rtl-module.mlir, test/Dialect/SV/errors.mlir, test/firtool/split_verilog.mlir
This PR checks that IfDefProceduralOp is in a procedural region. 
Currently, IfDefProceduralOp is sometimes used  as header in non-procedural region(= top level module). 
So this PR includes the modification of them.
=> [SV] Check IfDefProceduralOp is in a procedural region

CMakeLists.txt, lib/Dialect/ESI/CMakeLists.txt
Enables producing binary packages (e.g. tars) which do not require installation into the system. Sets the binaries' RPATHs to point to the 'lib' directory within said package.
There are cmake built-in properties which are supposed to do this sort of thing, but I couldn't get them to work after a _full day_ of trying. This is the the solution I got to work and it doesn't seem too hacky to me. CMake lacks a global list of targets (I don't understand why) so the recurse through the directories is necessary. :(
=> [cmake] Adding an option to produce a standalone install

docs/RationaleFIRRTL.md, include/circt/Dialect/FIRRTL/FIRRTLOps.h, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Dialect/FIRRTL/connect-errors.mlir, test/Dialect/FIRRTL/connect.mlir, test/Dialect/FIRRTL/lower-types.mlir
~Wires can have a bundle type and need to be handled during the lower
types pass.  For each element in the wire bundle, an new wire needs to
be created.~ (pushed to another PR)
Since wires have a `duplex` type, they can appear on the RHS or LHS of a
connect statement, regardless of whether or not they are a passive type.
When lowering a bulk connect statement involving a wire (i.e.
connecting a bundle type), we need to make sure that the non-duplex type
is used to set the direction of the flow. When doing a bulk connect of
two wires, it is considered an ambiguous flow and an error. To connect
two wires, each field must be connected individually, which is
considered a mono-connection with explicit flow from the RHS to the LHS.
This change adds a function to determine if a value comes from …
=> [FIRRTL LowerTypes] Lower bundle wire connects in lower-types

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/circt-translate/parse_int64.fir
The FIRParser is currently using an int32_t to parse integers, update it to int64_t.
Fix for https://github.com/llvm/circt/issues/783
=> [FIR Parsing] Use int64 to parse integers instead of 32

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Dialect/FIRRTL/lower-types.mlir
Check if name attribute exists, before accessing it while lowering register and registerReset op.
If no name exists in aggregate operation, then no name should be added after lowering. 
Fix for: https://github.com/llvm/circt/issues/795. 
With name attribute, 
``` mlir 
%r = firrtl.regreset %clock, %reset, %init {name = "r"} : (!firrtl.clock, !firrtl.uint<1>, !firrtl.vector<uint<1>, 2>) -> !firrtl.vector<uint<1>, 2>
``` 
is lowered to: 
``` mlir
%r_0 = firrtl.regreset %clock, %reset, %init_0 {name = "r_0"} : (!firrtl.clock, !firrtl.uint<1>, !firrtl.uint<1>) -> !firrtl.uint<1>
%r_1 = firrtl.regreset %clock, %reset, %init_1 {name = "r_1"} : (!firrtl.clock, !firrtl.uint<1>, !firrtl.uint<1>) -> !firrtl.uint<1>
```
Without name attribute 
``` mlir    
%r = firrtl.reg %clock : (!firrtl.clock) -> …
```
=> [FIRRTL] Type lowering of operations with no name

include/circt/Translation/ExportVerilog.h, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/firtool/split_verilog.mlir, tools/firtool/firtool.cpp
* Parallelize the emission of multiple Verilog files as discussed in #756.
* Also have `firtool` print the list of generated files in the appropriate order, which is an absolute necessity for split output. Later on we might want to offer more selective ways to print this file list.
* Make the implementation of `getReservedWords` thread-safe as discussed in #770.
=> [ExportVerilog] Parallelize split Verilog output and print file list

lib/Dialect/LLHD/IR/LLHDDialect.cpp
* Remove a check for negative values in TimeAttr that can never fail due to the values being unsigned anyway. Contribute towards #709.
=> [LLHD] Remove redundant negative value check for TimeAttr

lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/rtl-dialect.mlir
Flip the order of the unpacked array dimension  in ExportVerilog
Updated output::
```verilog
reg  [8:0] u0 [0:41];
```
instead of 
```verilog
reg  [8:0] u0 [41:0];
```
Fix for, https://github.com/llvm/circt/issues/754
=> [ExportVerilog] Flip unpacked array type dimension order

lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Translation/ExportVerilog/ExportVerilog.cpp
Remove a few unused functions from the FIRParser and the ExportVerilog pass to make the compiler happy. See #709.
=> Remove unused functions in FIRParser and ExportVerilog

include/circt/Dialect/SV/SVDialect.h, lib/Dialect/SV/SVDialect.cpp, lib/Dialect/SV/Transforms/RTLLegalizeNames.cpp, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/Dialect/SV/rtl-legalize-names-errors.mlir, test/ExportVerilog/rtl-dialect.mlir, test/ExportVerilog/sv-dialect.mlir, test/ExportVerilog/sv-interfaces.mlir, test/ExportVerilog/verilog-basic.mlir, test/ExportVerilog/verilog-errors.mlir, test/firtool/split-verilog.mlir, tools/firtool/firtool.cpp
Update ExportVerilog to use the new `LegalNamesAnalysis` pass to determine module, interface, port, instance, reg, and wire names (basically everything that would be exposed as part of the Verilog hierarchy and we might want to refer to somewhere in a Tcl script or hierarchical module path).
* Refactor the MLIR module level emission in ExportVerilog such that it has a separate but symmetrical `UnifiedEmitter` and `SplitEmitter`. These either emit Verilog into one large file, or one separate file per module and interface. This will also provide a way to inject the results of LegalNamesAnalysis into the emission process.
* Extend ExportVerilog to use the LegalNamesAnalysis pass to determine the names for modules, interfaces, ports, regs, and wires. This removes the need for on-the-fly name …
=> [ExportVerilog] Use LegalNamesAnalysis to determine module names

lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp, test/Conversion/FIRRTLToRTL/lower-to-rtl.mlir
Signed number should be sign extended, and unsigned should be zero extended.
Fix for: https://github.com/llvm/circt/issues/821
=> [FIRRTL] Negate bit extension

include/circt/Dialect/FIRRTL/CMakeLists.txt, include/circt/Dialect/FIRRTL/Canonicalization.td, include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, lib/Dialect/FIRRTL/CMakeLists.txt, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir, test/Dialect/FIRRTL/const-prop-single-module.fir
Start work towards #804. This PR does the following:
* Define canonicalizations for LEQ, LT, GEQ, GT that pulls constants on the LHS to the RHS by changing to the dual operation
* Perform constant folding for LEQ, LT, GEQ, GT, EQ, NEQ when both operands are constant or both operands are identical
* Handle cases where the RHS is a constant but the comparison is always true/false due to the type bounds of the LHS, for example `x < 8` being always true if x has only 3 bits.
* Handle cases like `x < 0` and `x >= 0` when `x` is unsigned
* Add the first few test cases from `ConstantPropagationTests.scala`
=> [FIRRTL] Add constant folders and canonicalization for comparison ops

tools/firtool/firtool.cpp
The compiler can parallelize pass which are running on distinct
IsolatedFromAbove operations.  Moving these passes to run on the
FModuleOp will increase the ability of the compiler to parallelize their
execution. Since there are no operations under the CircuitOp other than
FExtModule and FModule, this does should not change what gets CSE'd and
Canonicalized.
=> [FIRRTL] Nest CSE+Canon passes to run on FModuleOp

lib/Dialect/ESI/ESIPasses.cpp
Remove the annotation which broke the build. Don't re-introduce warning -- ifdef'ing unused code.
=> [ESI] Fix Windows build

lib/Dialect/ESI/ESIPasses.cpp, test/Dialect/ESI/lowering.mlir
For external modules, ESI lowers to SV interfaces since it assumes a user is going to write a module against that generated SV interface. For internally-defined modules, lowering to regular data/valid/ready wire signaling is preferred so as to not preclude further optimization. SV interfaces also bloat the IR.
One of the use cases is for modules which have ready/valid semantics and a previous pass has attached wrap/unwrap ops onto. This will lower all the ESI wraps/unwraps out and end up not creating any ESI wiring.
=> [ESI] Lower ESI Channel ports on modules defined in CIRCT to data/valid/ready

integration_test/EmitVerilog/verilog_equiv.fir
* Update the golden verilog with the latest firrtl
* firrtl output for neg, for signed and unsigned operand must respect the sign.
* This should fix the yosys integration_test failure https://github.com/llvm/circt/issues/842
* The firrtl bug fix that updates the golden: https://github.com/chipsalliance/firrtl/commit/49b823244732e8d3a4b0fe91d0f10625fea34eec
=> [integration_test] Update golden verilog

include/circt/Support/LoweringOptions.h, lib/Support/LoweringOptions.cpp, lib/Translation/ExportVerilog/CMakeLists.txt, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/sv-alwaysff.mlir, test/ExportVerilog/verilog-errors.mlir, test/circt-translate/commandline.mlir, test/firtool/commandline.mlir, test/firtool/style.fir, tools/firtool/firtool.cpp
This change adds the ability to control the verilog emitter using a set
of options, starting with one option to control the printing of the
`sv.alwaysff` operation.  This allows `sv.alwaysff`  to print as either
an always_ff or always block.
There are several configuration points for this option:
`exportVerilog()` now takes a `VerilogEmitterOptions` struct, with a field
`emitAlwaysFFAsAlways`.  This struct is stored in the
VerilogEmitterState object, and accessed by the different emitters to
customize their output.  This field defaults to false.
`circt-translate` now has a command line option
`--verilog-emit-alwaysff-as-always` under a new option group called
"Verilog Export". This defaults to off.
`firtool` now has a command line option `--emit-alwaysff-as-always` to
control the output. …
=> [ExportVerilog] Add option to control alwaysff printing

include/circt/Translation/ExportVerilog.h, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/load-dialect.mlir
Dialects are lazily loaded by the MLIR parser.  When IR read in to
circt-translate does not contain ops from a dialect, the dialect is
never loaded.  Since ExportVerilog creates sv.wire operations, it must
ensure that this dialect has been loaded instead of hoping it has been
loaded by the parser.
Fixes https://github.com/llvm/circt/issues/854
=> [ExportVerilog] Explicitly load the SV dialect

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
Remove the loop for ``getResultTypes()`` in ``hasKnownWidths``, since a FIRRTL ``BinaryPrimOp`` operation always has a single result, 
Related to commit: https://github.com/llvm/circt/commit/74f99727c6ca9ec353a0a54a68d45f6e7fce49de
=> Firrtl fold simplify known widths

include/circt-c/Dialect/ESI.h, include/circt/Dialect/ESI/ESI.td, integration_test/Bindings/Python/dialects/esi.py, integration_test/Bindings/Python/import.py, lib/Bindings/Python/CIRCTModule.cpp, lib/Bindings/Python/CMakeLists.txt, lib/Bindings/Python/ESIOps.td, lib/Bindings/Python/circt/dialects/esi.py, lib/CAPI/Dialect/CMakeLists.txt, lib/CAPI/Dialect/ESI.cpp
Just the ability to 'import' ESI into Python. All of the ESI ops require `ChannelType`, so I didn't include anything in the integration test other than importing esi.
=> [ESI] C API and Python bindings

CMakeLists.txt
Change the Verilator requirement in cmake from 4.034 to 4.100 since
the integration tests use `$urandom_range` which was added to
Verilator in 4.100.
See: Verilator release notes for 4.100: https://github.com/verilator/verilator/blob/master/Changes#verilator-4100-2020-09-07.
`$urandom_range` usage here: https://github.com/llvm/circt/blob/461f0eaff2b3af92af0e754e065ff619bd50ae86/integration_test/ESI/supplements/integers.sv#L37
=> Up Verilator requirement to v4.110, $urandom_range

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
Add a trivial folder for `firrtl.validif` operations that will always replace the operation by its second operand, which is the value being gated. This is not perfect but replicates the behaviour of the Scala FIRRTL compiler in all cases that we are interested in for now. Also fixes #839 and makes reasoning about the clock signal easier in some places. We'll want to revisit this at a later stage.
=> [FIRRTL] Fold away validif operations

docs/RationaleFIRRTL.md, include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Import/FIRTokenKinds.def, test/Conversion/FIRRTLToRTL/lower-to-rtl.mlir, test/Dialect/FIRRTL/blackbox-memory.mlir, test/Dialect/FIRRTL/canonicalization.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir
* Remove the `validif` operation from the IR and replace any occurrences during parsing with an equivalent `invalidvalue` and `mux` operation. Fixes #886.
* Adjust a few of the test cases, especially around memories, which do not run canonicalization and thus no longer see the removal of validif happen automatically.
@darthscsi: Are the memory tests still okay like this? I had to remove a few occurrences of `validif` since the tests run without any canonicalization.
=> [FIRRTL] Remove validif operation

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Dialect/FIRRTL/annotations-errors.fir, test/Dialect/FIRRTL/annotations.fir, test/Dialect/FIRRTL/lower-types.mlir
Add support for parsing Annotations that point at _local_ `ReferenceTarget`s. These are targets of the form:
```
~Circuit|Module>Reference
```
These can point at a variety of things (items checked off are in the PR):
Ports are not supported, due to expected churn related to arg attribute storage being changed in #872. For the time being, port targets sit in another, dependent PR.
The following are not supported as they have optional names that were [added in _to-be-released_ FIRRTL 1.5](https://github.com/chipsalliance/firrtl/pull/2057). This name support is necessary for something to be a valid target:
- Stop
- Print
- Verification Statements
Custom parsers/printers are added to elide the annotations if they are empty. Support is added to `LowerTypes` to copy annotations to operations …
=> Support ReferenceTarget Annotations for Operations

.github/workflows/buildAndTest.yml
Bumping LLVM to get https://github.com/llvm/llvm-project/commit/0126e906483c50c47db0687195e4b0216479846e. Updating the workflow since there's no reason to cache the LLVM source code. Doing both simultaneously to save compilation resources.
=> [LLVM] Update LLVM submodule and the way it's cached

integration_test/Bindings/Python/dialects/esi.py, integration_test/Bindings/Python/dialects/esi_load1.mlir, integration_test/Bindings/Python/dialects/esi_load2.mlir, integration_test/Bindings/Python/dialects/lit.local.cfg, lib/Bindings/Python/ESIModule.cpp, lib/Bindings/Python/PybindUtils.h
Start the system assembly API with a method to load an MLIR assembly file and append it to the System module.
=> [ESI] Start of system assembly API: System.load_mlir

lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/rtl-dialect.mlir, test/ExportVerilog/sv-dialect.mlir
Emit `rtl.constant` operations as `localparam` when we decide to print them as out-of-line expressions. This requires additional special treatment since the localparam cannot be reassigned and the value must be provided already at the declaration site.
When `rtl.constant` operations are used before defined, move the definition up to the beginning of the block, similar to wire/reg. This avoids introducing a temporary dynamic wire and emits the constant as a localparam.
This fixes #884 by moving the constant reset values of always_ff statements into localparams.
=> [ExportVerilog] Emit constants as localparam

include/circt/Dialect/FIRRTL/Canonicalization.td, include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
Eliminates unused NodeOps.
Partially addresses #299
=> Eliminate firrtl.node ops when they carry no annotations

integration_test/Bindings/Python/dialects/esi.py, lib/Bindings/Python/ESIModule.cpp
Function to create channel type wrapping the argument type. This is a temporary way to get a critical ESI type before we get the long-term solution we discussed at the bindings MLIR ODM a while back.
=> [ESI] [Python] Create a ChannelPort type

include/circt/Dialect/SV/SVPasses.h, include/circt/Dialect/SV/SVPasses.td, lib/Dialect/SV/Transforms/CMakeLists.txt, lib/Dialect/SV/Transforms/RTLMemSimImpl.cpp, test/Dialect/SV/rtl-memsim.mlir
Lower firrtl memory generator nodes into a simulation model.  This implements the code in LowerToRTL as a separate pass in preparation for converging lowering to generate generator modules.
=> firrtl memory generator node lowering

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
Use the operand types instead of the operation's result type when deciding whether to perform sign or zero extension of constants for folding. This is important for comparison operators, where the result type is always `uint<1>`, yet signed operands should be sign-extended. Fixes #912.
=> [FIRRTL] Use operand type to determine sign for const folding

lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp, lib/Support/LoweringOptions.cpp, test/ExportVerilog/line-length.mlir, test/ExportVerilog/sv-alwaysff.mlir, test/circt-translate/commandline.mlir, test/firtool/commandline.mlir, test/firtool/phase-ordering.fir, test/firtool/style.fir, tools/firtool/firtool.cpp
This changes the `--enable-lower-types` flag to `--lower-types` and it
changes `--circt-lowering-options` to `--lowering-options`.
=> [firtool] Change command line options for passes

include/circt/Dialect/FIRRTL/FIRRTLStatements.td, include/circt/Dialect/FIRRTL/FIRRTLStructure.td, include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, lib/Conversion/FIRRTLToLLHD/FIRRTLToLLHD.cpp, lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp, lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, test/Dialect/FIRRTL/errors.mlir
This change removes the terminator from all FIRRTL operations with
regions.  Since the firrtl.done op is no longer used anywhere, it was
deleted.
=> [FIRRTL] Make Circuit, FModule and When noterminator ops

include/circt/Dialect/Handshake/HandshakeOps.td, lib/Dialect/Handshake/HandshakeOps.cpp, test/Conversion/StandardToHandshake/test_canonicalize.mlir
The previous change, which this PR reverts, intended to allow removing constants that ended up in sinks, but it ultimately led to sinks being removed in situations where we really don't want that. Specifically, a sunk output of a ConditionalBranchOp would be removed. In hardware, this would ultimately result in dangling ready wires, which Verilator finds:
```
%Warning-UNDRIVEN: build/tools/circt/integration_test/Dialect/Handshake/%matmul-export.sv:4924:15: Signal is not driven: '_arg3_ready_wire'
%Warning-UNDRIVEN: build/tools/circt/integration_test/Dialect/Handshake/%matmul-export.sv:4931:15: Signal is not driven: '_arg3_ready_wire_40'
%Warning-UNDRIVEN: build/tools/circt/integration_test/Dialect/Handshake/%matmul-export.sv:4972:15: Signal is not driven: '_arg3_ready_wire_48'
...
``` …
=> [Handshake] Add canonicalization to remove sunk constants.

include/circt-c/Dialect/ESI.h, include/circt-c/Dialect/SV.h, include/circt/Dialect/SV/SVPasses.h, integration_test/Bindings/Python/dialects/rtl.py, lib/Bindings/Python/CIRCTModule.cpp, lib/Bindings/Python/CMakeLists.txt, lib/Bindings/Python/PybindUtils.h, lib/CAPI/Dialect/CMakeLists.txt, lib/CAPI/Dialect/ESI.cpp, lib/CAPI/Dialect/SV.cpp
- Registers the SV passes when the 'circt' Python module is imported and the ESI passes when 'circt.esi' is imported.
- Adds a Python 'export_verilog' call.
- Enables LLVM 'pretty' stack traces for easier debugging. Makes assertion messages appear in Python instead of just crashing with no output.
=> [Python] Register passes, export_verilog, and stack traces

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp, lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/BlackboxMemory.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, lib/Dialect/SV/SVOps.cpp, test/Conversion/FIRRTLToRTL/lower-to-rtl.mlir, test/Conversion/HandshakeToFIRRTL/test_buffer.mlir, test/Conversion/HandshakeToFIRRTL/test_fork.mlir, test/Dialect/FIRRTL/blackbox-memory.mlir, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/lower-types.mlir, test/Dialect/FIRRTL/parse-basic.fir
The first part of this change makes names on FIRRTL operations
non-optional StringAttr attributes.  Empty names are still allowed, but
are now represented by an empty string "", instead of a non-existent
attribute.  This change affects the builders generated for each op, and
they now have a builder capable of taking a StringRef for the name.
The second part of this change modifies the SSA printer for registers to
use the same ImplicitSSAName as WireOps.  Since registers now require
an explicit name attribute, making this change now helped keep down the number of
test line changes.
There is a small improvement to the printer to not print empty
name strings.
=> [FIRRTL] Make names non-optional and use names as SSA values

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir
Bug introduced in 2803801a06 accidentally started using the wrong type
for the created Node operation.  This fixes the type of the node and
provides a test case for it.
=> [FIRRTL] Fix node parsing when there is an implicit asPassive.

include/circt-c/Dialect/MSFT.h, integration_test/Bindings/Python/dialects/msft.py, lib/Bindings/Python/CIRCTModule.cpp, lib/Bindings/Python/CMakeLists.txt, lib/Bindings/Python/MSFTModule.cpp, lib/CAPI/Dialect/CMakeLists.txt, lib/CAPI/Dialect/MSFT.cpp
Adds an API call to physically place an op's sub-entity. Also adds msft dialect CAPI registration.
=> [MSFT] [Python] Physically locate an op

.github/workflows/buildAndTest.yml, lib/Bindings/Python/circt/__init__.py
The intent of the check was to only run yapf on the files that
changed, but if no Python files changed, the grep command returns 1
and fails the check. In that case, return an empty list of files, and
check for that.
=> [NFC] Re-enable Python format check, and don't fail when no changes.

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir
When attached to bundle values, `is invalid` recurses through the bundle
and connects invalid to any flipped field.  When the bundle value is a
register or wire, it should connect invalid to every field, regardless
of the flippedness of that field.  Invalid was not properly recursing or
handling wire types, and this change fixes that.
Due to the way `is invalid` treats wires differently than other values,
we cannot simply bulk connect a bundle typed `invalid`, and let expand
connects handle this later.
=> [FIRRTL] Fix `is invalid` on duplex types and bundles

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, include/circt/Dialect/FIRRTL/FIRRTLStatements.td, lib/Dialect/FIRRTL/Import/FIRLexer.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/annotations.fir, test/Dialect/FIRRTL/parse-basic.fir
There is a problem where entities with dropped temporary names (such as
"_T_0") can't have annotations properly attached. This change looks up
the annotations of an entity before removing the name, which allows
annotations to apply as intended.
In addition to this, entities with the DontTouch attribute will not have
their name dropped by the parser.
=> [FIRRTL] Properly apply annotations to entities with temp names

include/circt/Dialect/SV/SVInOutOps.td, lib/Dialect/SV/SVOps.cpp, test/Dialect/RTL/canonicalization.mlir
We have a canonicalization which removes SV wires without any readers.
This is not a legal optimization as wires are considered public and
other tooling may be expecting these wires in the final output.  This
change removes the canonicalization responsible for removing the wire.
This is a useful idea, and we will be revisiting this optimization when
there is a concept of public vs private wires in the RTL dialect.
=> [SV] Do not remove dead wires

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td, include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, test/Dialect/FIRRTL/canonicalization.mlir
Nodes, especially those marked with DontTouch, can't be removed by dead
code elimination.  Some tools will expect them in the final output.
There is already a canonicalization to remove a node if it has an empty
annotation list, and it should be able to handle this case as well.
This change removes the NoSideEffect trait from the node operation.
=> [FIRRTL] Nodes shouldn't be no side effect.

include/circt/Translation/ExportVerilog.h, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/firtool/split-verilog.mlir, tools/firtool/firtool.cpp
This PR does the following:
* Rather than printing the list of emitted files to standard output, generate a dedicated `filelist.f` file for split Verilog output with one line for each emitted file.
* Stop generating stub files for external modules when split Verilog output is enabled. This collides with black box annotations supplying the actual files to be included for external modules.
Factored out of #918.
=> [ExportVerilog] Add file list output

lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp
Neither of these are bugs because signed == true, but still just use the explicit builder.
=> Be explicit about all ones [NFC]

include/circt/Dialect/SV/SVInOutOps.td, lib/Dialect/SV/SVOps.cpp, test/Dialect/RTL/canonicalization.mlir
This adds back the wire optimization removed in fbe9df0b4 (#950), with
an added constraint that we can't remove a wire if it has a name.
=> [SV] Add back dead wire optimization

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, lib/Dialect/FIRRTL/Import/FIRParser.cpp
This follows the current convention of representing non-existent names
as an empty string instead of an optional attribute.  This makes
MemoryPort easier to work with and generates better builders.
=> [FIRRTL] Make MemoryPort name non-optional

include/circt/Dialect/ESI/ESIOps.td, lib/Dialect/ESI/ESIPasses.cpp, test/Dialect/ESI/connectivity.mlir, test/Dialect/ESI/lowering.mlir
Useful in cases where a module has an input port which you don't want to use.
This PR also fixes a bug in the RemoveWrapUnwrap conversion I found while
debugging.
=> [ESI] Add NullSourceOp to model source which never produces messages

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir
This adds support for `when` syntactic shorthand to the parser:
```firrtl
when reset :
_t <= _t_2
else when not(reset) :
_t <= _t_2
```
=> [FIRRTL] Support `else when x:` syntatic shorthand

include/circt/Dialect/MSFT/MSFT.td, lib/Dialect/ESI/ESIPasses.cpp, lib/Dialect/ESI/ESITranslations.cpp, lib/Dialect/SV/Transforms/GeneratorCallout.cpp, lib/Translation/ExportVerilog/ExportVerilog.cpp, tools/firtool/firtool.cpp, tools/handshake-runner/Simulation.cpp, tools/handshake-runner/handshake-runner.cpp, tools/llhd-sim/llhd-sim.cpp
This includes a couple breaking changes:
* AttrDef has a new argument for attribure traits.
* Several includes we depended on appear to have been moved to forward
declarations, so add the explicit includes we needed.
=> Update LLVM to 4dfddf715b94857998601aa79c25e4f327d44dfa.

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, test/Dialect/FIRRTL/expand-whens-errors.mlir, test/Dialect/FIRRTL/expand-whens.mlir
Register in FIRRTL are initialized to their own value. This affects how
they behave when connected to in WhenOp statements, and prevents them
from being uninitialized. Before this change, they were treated
identically to wires. The following example works for registers, but
would be considered uninitialized if it was a wire:
```scala
reg r: UInt<4>, clock
when p:
r <= UInt<4>(0)
```
lowers to:
```scala
reg r: UInt<4>, clock
r <= mux(p, UInt<4>(0), r)
```
=> [FIRRTL][ExpandWhens] Properly handle registers

lib/Bindings/Python/CMakeLists.txt
This picks up a couple useful features, but is otherwise NFC:
* Python support for casting constructors on types and attributes
* Special cases added to speed up llvm::parallel_for_each
=> Update LLVM to 39bbfb77264a4a7a216921c2b70a30ba0f27eb56.

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
Removes a variety of asserts and Optional returns in MemOp accessors as
data is already checked during validation.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
Fixes #664
=> [FIRRTL] Make MemOp accessors less pessimistic

lib/Conversion/RTLToLLHD/RTLToLLHD.cpp, test/Conversion/RTLToLLHD/errors.mlir, test/Conversion/RTLToLLHD/structure.mlir
Extend the RTLToLLHD conversion pass to add support for modules that have combinational (or actually any other) operations in the body. These changes will properly insert temporary signals to connect to LLHD instances, but also provide the necessary probe operations to feed the value through the combinational operations. This is a first step towards supporting RTL simulation through the event loop modeled in LLHD.
Fixes #985.
=> [RTLToLLHD] Add conversion for modules and instances with comb ops

docs/RationaleRTL-SV.md, include/circt/Dialect/RTL/RTLAggregates.td, include/circt/Dialect/RTL/RTLTypes.h, include/circt/Dialect/RTL/RTLTypes.td, lib/Dialect/RTL/RTLOps.cpp, lib/Dialect/RTL/RTLTypes.cpp, test/Dialect/RTL/basic.mlir, test/Dialect/RTL/errors.mlir, test/Dialect/RTL/types.mlir
Non-tagged union type. ExportVerilog support will be in the subsequent PR.
Partial progress on #967.
=> [RTL] Union type

integration_test/Bindings/Python/dialects/seq.py, lib/Bindings/Python/circt/dialects/seq.py
This adds a convenience function for construction
CompRegOp. The function requires a value to register and a clock
signal. Optionally, a reset signal, reset value, and name may also be
provided.
=> [Python][Seq] Add a helper for building computational registers.

integration_test/Bindings/Python/dialects/rtl.py, lib/Bindings/Python/circt/dialects/_rtl_ops_ext.py
This adds a parameters dict to the instance create API and
InstanceBuilder class. The attributes are parsed and passed to the
InstanceOp being built.
=> [Python][RTL] Support parameters on instances.

integration_test/Bindings/Python/dialects/msft.py, lib/Dialect/MSFT/TclExport/ExportQuartusTcl.cpp
Any operation with a "name" attribute can be located and exported with
that name in the TCL output.
=> [MSFT] Support name attribute in Quartus TCL exporter.

lib/Dialect/ESI/ESIPasses.cpp, lib/Dialect/ESI/capnp/ESICapnp.h, lib/Dialect/ESI/capnp/Schema.cpp, test/Dialect/ESI/cosim_structs.mlir, test/Dialect/ESI/lowering.mlir
- Builds capnp gaskets in their own modules.
- Creates "reasonable" names for SV interface instances and gasket modules/instances.
=> [ESI] Build capnp encoders/decoders in their own modules

lib/CAPI/Dialect/ESI.cpp
C API fails to link on builds that have CAPNP disabled, since some of the symbols in the C++ API get dropped. Make the corresponding uses in the C API conditional on the presence of the same ifdef, so things link again.
=> [CAPI] Guard esi::exportCosimSchema by CAPNP ifdef

include/circt/Dialect/FIRRTL/FIRRTLTypes.h, include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/CheckWidths.cpp, test/Dialect/FIRRTL/check-widths-errors.mlir
Add a `CheckWidths` pass modeled after the corresponding Scala pass. The pass emits human-readable errors for any `uint`, `sint`, and `analog` types without known width in the IR. This check will be useful to verify the result of width inference and to ensure that we are in low FIRRTL.
As a concrete example, this pass will produce errors like:
```
foo.mlir:7:10: error: uninferred width: type '!firrtl.uint' has no known width
%0 = firrtl.wire : !firrtl.uint
^
foo.mlir:7:10: note: in result of `firrtl.wire`
```
```
foo.mlir:27:10: error: uninferred width: type '!firrtl.flip<uint>' has no known width
%4 = firrtl.wire : !firrtl.bundle<a: bundle<b: bundle<c: flip<uint>, d: uint<1>>>>
^
foo.mlir:27:10: note: in result of `firrtl.wire`
foo.mlir:27:10: note: in bundle field `a`
foo.mlir:27:10: …
```
=> [FIRRTL] Add CheckWidths pass

lib/CAPI/Dialect/ESI.cpp, lib/Dialect/ESI/ESITranslations.cpp
Moving the export translation CAPNP define selection to a C++ file which actually has the CAPNP macro defined.
=> [ESI] Fix ESI integration tests

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Dialect/FIRRTL/infer-widths.mlir
Add a first basic implementation of an `InferWidths` pass modeled after the corresponding Scala pass. The pass goes through the IR and constructs a constraint problem where the type width of wires and module ports are represented as free variables, and connects impose constraints on those variables depending on their right-hand side.
This first implementation is purposefully kept simple and only deals with non-aggregate types and simple connects to wires. Constraints between modules are not modeled yet either. I'll add issues to track expanding this pass to cover more ground, which should be fairly straightforward after iterating on this first implementation a bit.
Currently supported are the following operations:
- `ConstantOp`
- `WireOp`
- `AddPrimOp`
- `SubPrimOp`
- `MulPrimOp`
- …
=> [FIRRTL] Add InferWidths pass

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Dialect/FIRRTL/infer-widths.mlir
Extend the `InferWidths` pass to cover almost all expressions in the FIRRTL dialect. What remains are expressions that interact with aggregate data types, as well as statements and declarations. Contributes to #1014.
This specifically covers the following operations:
- `CatPrimOp`
- `DShlPrimOp`
- `DShlwPrimOp`
- `DShrPrimOp`
- `AsSIntPrimOp`
- `AsUIntPrimOp`
- `AsAsyncResetPrimOp`
- `AsClockPrimOp`
- `CvtPrimOp`
- `NegPrimOp`
- `NotPrimOp`
- `AndRPrimOp`
- `OrRPrimOp`
- `XorRPrimOp`
- `BitsPrimOp`
- `HeadPrimOp`
- `InvalidValuePrimOp`
- `PadPrimOp`
- `ShlPrimOp`
- `ShrPrimOp`
- `TailPrimOp`
- `AsPassivePrimOp`
- `AsNonPassivePrimOp`
=> [FIRRTL] Add width inference on most expressions

include/circt/Dialect/RTL/RTL.td, include/circt/Dialect/RTL/RTLTypeDecls.td, test/Dialect/RTL/typedecls.mlir
This includes the ODS to define a wrapper operation for a typedecl
scope. Within its body, typedecl ops may associate a symbolic name to
a type.
=> [RTL] Add type declaration ops.

include/circt/Dialect/RTL/RTLVisitors.h, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/rtl-typedecls.mlir, test/firtool/split-verilog.mlir
The typedecl scope has its whole body exported at the top level of the
output. If split output, typedecls are included in each file.
=> [RTL] Support typedecls in ExportVerilog.

tools/circt-rtl-sim/circt-rtl-sim.py.in, tools/circt-rtl-sim/driver.cpp.in
This incurs some cost in the generated simulator. Monitoring and saving the
waveforms to disk incurs yet more overhead, so enable this via an environment
variable.
=> [circt-rtl-sim] [Verilator] Compile with trace options when in Debug mode

include/circt/Dialect/Handshake/HandshakeOps.td, lib/Conversion/StandardToHandshake/StandardToHandshake.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, lib/Dialect/LLHD/IR/LLHDOps.cpp, lib/Dialect/RTL/RTLOps.cpp
Picks up the new `TimingManager` that will allow us to time code paths outside the pass manager. Required some fixes since the argument/result attribute storage has been reworked conceptionally from `{arg0: A, arg1: B, ...}` to `{args: [A, B, ...]}`.
=> Update LLVM to 33f908c42881fa02963f0c64f8be5088717664cc

docs/RationaleRTL-SV.md, include/circt/Dialect/RTL/RTLStructure.td, include/circt/Dialect/SV/SVInOutOps.td, lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp, lib/Dialect/ESI/ESIDialect.cpp, lib/Dialect/ESI/ESIPasses.cpp, lib/Dialect/SV/SVOps.cpp, test/Dialect/RTL/modules.mlir, test/Dialect/SV/basic.mlir
Wires, instances, and registers define externally visible names in verilog.  Model this with optional symbols for those which are public.
Update the rational doc with notes on symbols and visibiligy.
=> Attach symbols to instances, wires, and regs.

integration_test/Bindings/Python/dialects/rtl.py, lib/Bindings/Python/ESIModule.cpp, lib/Bindings/Python/HWModule.cpp
This allows us to directly return a Python object of the class being
instantiated, rather than an object of the base _mlir.ir.Type
class. This allows the readonly properties to work correctly.
=> [Python] Use classmethod instead of staticmethod for Type getters.

include/circt/Dialect/LLHD/IR/SignalOps.td, include/circt/Dialect/LLHD/IR/StructureOps.td, lib/Dialect/LLHD/IR/LLHDOps.cpp
The folder does not allow an op to be explicitly erased, which was
causing the folder to use-after-free.  There doesn't seem to be a good
way to implement the folding of an op with no results, so this was
re-implemented as a canonicalization.
=> [LLHD] Don't erase ops in the folder for Connect and Drv

include/circt/Dialect/ESI/ESITypes.td, lib/Dialect/ESI/ESITypes.cpp, test/Dialect/ESI/connectivity.mlir
Will be replaced with whatever goes in the `hw` dialect.
=> [ESI] Ditch `esi.struct` type

lib/Dialect/LLHD/IR/LLHDOps.cpp, test/Dialect/LLHD/IR/connect-errors.mlir
When the op is not well-formed, we should not return success.  This
fixes a bug when the region is not added to the op.
=> [LLHD] parseEntityOp: check if the region was parsed correctly

include/circt/Dialect/HW/CMakeLists.txt, include/circt/Dialect/HW/HWDialect.h, include/circt/Dialect/HW/HWTypes.td, include/circt/Dialect/SV/SVDialect.h, lib/Dialect/HW/HWDialect.cpp, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/output-file.mlir, test/firtool/split-verilog.mlir
* Add a `OutputFileAttr` to the RTL dialect which can be used to annotate top-level operations in the SV/RTL dialect that should be emitted into a separate output file.
* Refactor the unified/split emitters in `ExportVerilog` to improve code reuse and make the two emission forms better aligned. With these changes, the only difference is that split emission implicitly pushes modules/interfaces into separate files. Unified emission also supports multiple files, which are demarcated via a banner comment in the output, mainly useful for debugging.
* Extend `ExportVerilog` to look for `output_file` attributes on top-level operations. If one is found, this overrides the assignment of an operation to a specific file. The attribute also controls whether per-file replicated ops should be included …
=> [ExportVerilog] Add `output_file` attribute for top-level ops

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Dialect/FIRRTL/infer-widths.mlir
* Ignore operations that have no bearing on width inference. Until now these would generate an error.
* Have the `VarExpr` of the `InferWidths` pass directly track its constraint expression rather than using an indirection through a separate map. This simplifies things and rectifies the post-order traversal that will be necessary for graphs with cycles.
Fixes #1060.
=> [FIRRTL] Ignore ops not affecting width inference

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
A quick fix of issue #1062 - we still parse `dshlw`, and the errors in the lowering and folding are fixed.
=> [FIRRTL] Fix the handling of DShlwPrimOp

include/circt/Dialect/SV/SVInOutOps.td, lib/Dialect/SV/SVOps.cpp
Added the symbol name argument to `sv::WireOp::build` this is required to attach symbol to `sv::WireOp`. 
Followup to https://github.com/llvm/circt/pull/1044
=> [SV] Add sym_name argument to sv::WireOp::build

include/circt/Dialect/FIRRTL/FIRAnnotations.h, lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/annotations-errors.fir, test/Dialect/FIRRTL/annotations.fir
Add support for SiFive-custom annotations related to the Grand Central utility. This PR is narrowly about adding support **only** for pre-processing the annotations that this utility needs. Specifically, these annotations contain metadata associated with tapping arbitrary data or memories in the design (via hierarchical references and binds) and with constructing "views" of the circuit which may or may not be handled via emission of interfaces.
This adds support for the following annotations:
- sifive.enterprise.grandcentral.DataTapAnnotation
- sifive.enterprise.grandcentral.MemTapAnnotation
- sifive.enterprise.grandcentral.GrandCentralView$SerializedViewAnnotation
These annotations (which contain a lot of information about different targets) are "scattered" into the circuit to be …
=> Support Scattering SiFive "Grand Central" Annotations

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Dialect/FIRRTL/infer-widths.mlir
* Width inference can cause the RHS of a connect operation to become wider than the LHS. The behaviour prescribed by the Scala FIRRTL compiler is to insert a `bits` operation to truncate the RHS to the appropriate width. Add this behaviour to the InferWidths pass. Fixes #1088, fixes #1089, fixes #1091, fixes #1092, fixes #1093, fixes #1094, fixes #1095, fixes #1096, fixes #1097, fixes #1099.
* Fix an issue where unsized constants would infer a width that could be wider than the minimum number of bits necessary to represent the constant. This fixes width inference to properly compute the number of bits necessary to represent a signed/unsigned constant. Also updates the APInt store in ConstantOp after width inference. Fixes #1090, fixes #1098.
This will make @drom very happy :wink:
=> [FIRRTL] Fix constant width inference and connection truncation

include/circt/Dialect/HW/HWTypes.h, include/circt/Dialect/HW/HWTypes.td, lib/Dialect/Comb/CombOps.cpp, lib/Dialect/HW/HWTypes.cpp, test/Dialect/HW/typedecls.mlir
The type is created and uniqued based on the symbol reference, inner
type, and canonical type. HW and Comb dialect types are taught to use
the canonical type in their predicates.
=> [HW] Define TypeAliasType to reference a declared type symbolically.

integration_test/Bindings/Python/DesignEntry/polynomial.py, lib/Bindings/Python/circt/__init__.py, lib/Bindings/Python/circt/design_entry.py, lib/Bindings/Python/circt/esi.py, lib/Bindings/Python/circt/support.py, lib/Translation/ExportVerilog/ExportVerilog.cpp
Fastest thing I could think of: uses HWModuleOp and calls construct immediately. Lots of ugliness in `construct`.
=> [Py] Prototype @module annotation for design entry

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
This will print an error message when a bundle lowering does not exist. This is usually the result of missing support for a specific operation in the LowerTypes pass.  It is helpful to know what operation support is missing without having to start up the debugger.  In order for the error message to reliably print, multithreading must be disabled with: `--mlir-disable-threading`.
Example output:
```
./fieldtest.fir:6:5: error: bundle lowering was not set
node n = in0
^
./fieldtest.fir:6:5: note: see current operation: %n = firrtl.node %arg0  : !firrtl.bundle<a: uint<1>>
LLVM ERROR: bundle lowering was not set
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ./bin/firtool -mlir-disable-threading ./fieldtest.fir
```
=> [FIRRTL][LowerTypes] Report the op when missing a bundle lowering

integration_test/Bindings/Python/dialects/rtl_errors.py, lib/Bindings/Python/circt/dialects/_hw_ops_ext.py, lib/Bindings/Python/circt/support.py
Divorces the support BackedgeBuilder from InstanceBuilder (so it can be used
elsewhere). Stores some extra information in the edge instead of digging it up
later in an InstanceBuilder-specific way.
Keep a stack of BackedgeBuilders in a contextvar. Provide a static method to
get the top.
=> [Py] Make BackedgeBuilder more general and keep a stack

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
Replace `SubaccessOp` with `SubindexOp` when the `index` is a constant. In SFC, this is called [`ReplaceSubaccesses`](https://github.com/chipsalliance/firrtl/blob/master/src/main/scala/firrtl/passes/ReplaceAccesses.scala).
=> [FIRRTL] Add a ReplaceSubaccess canonicalizer for SubaccessOp

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/PassDetails.h, test/firtool/blackbox-path.v, test/firtool/blackbox-resource.v, test/firtool/blackbox.mlir, tools/firtool/firtool.cpp
This PR does the following:
* Add the `BlackBoxSourceHelper` transformation pass which is modeled after the corresponding Scala implementation. It honors a set of FIRRTL annotations that declare source code for black boxes to be copied to an output directory. This can be done inline, as a separate path, or the rather Java-specific resource mechanism.
I tried to stay faithful to the original Scala implementation. Since the pass interacts with additional files specified by the user in the input source, I added the ability to make it treat input files relative to some path (usually the directory around the input FIR file) and output files relative to some path (usually the output directory for split Verilog). This should remove a lot of confusion by making the operation invariant to the …
=> [FIRRTL] Add black box source helper pass

include/circt/Dialect/FIRRTL/FIRRTL.td, include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLOps.h, lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/errors.mlir
* Many FIRRTL operations have their result type fully determined by their arguments (operands and attributes). The `InferTypeOpInterface` formalizes this behaviour and provides a unified verification hook as well as a builder which automatically infers the result type of the built operation. The interface also allows passes to treat all ops that can determine their return type uniformly (e.g., the width inference pass).
* Adjust the definition of most FIRRTL expression ops to implement this interface. Some operations which have a well-known return type that is independent of their arguments, such as comparisons or reductions, automatically generate the necessary `inferReturnTypes` function impl.
* The semantics and function signature of `inferReturnTypes` is different from the …
=> [FIRRTL] Move result type computation to InferTypeOpInterface

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Dialect/FIRRTL/lower-types.mlir
Mux lowering forgot to check when the type was not a bundle, leading to
lots of crashes
=> [FIRRTL] LowerTypes: fix handing of mux ops

integration_test/Bindings/Python/DesignEntry/polynomial.py, lib/Bindings/Python/circt/__init__.py, lib/Bindings/Python/circt/design_entry.py
The most common use case for the `circt.design_entry` API is that a single
context is used throughout the lifetime of the application. This creates a
default context and default location and installs them into the defaults stack.
Since we don't want this behavior whenever someone imports circt, don't import
`design_entry` into the `circt` namespace.
=> [Python] Set a default context (and location) upon import

integration_test/Bindings/Python/DesignEntry/connect.py, integration_test/Bindings/Python/DesignEntry/connect_errors.py, integration_test/Bindings/Python/dialects/rtl.py, integration_test/Bindings/Python/dialects/rtl_errors.py, lib/Bindings/Python/circt/design_entry.py, lib/Bindings/Python/circt/dialects/_hw_ops_ext.py, lib/Bindings/Python/circt/support.py
This adds `circt.connect` to "connect" two values. It sets the
destination OpOperand to the new value.
To integrate with the builder approach, this updates the
InstanceBuilder to return a wrapper BuilderValue around any Values
accessed through `__getattr__`. This works with the connect API to
pass around the needed index to ultimately set the Value and erase any
temporary backedges the builder created.
As the builder approach is generalized to other ops, the connect API
should work in exactly the same manner.
=> [Python] Add generic connect API that works with builders.

lib/Bindings/Python/circt/dialects/_hw_ops_ext.py, lib/Bindings/Python/circt/support.py
This adds a new base class to support named access to the operands and
results of an operation being built. Existing support in
InstanceBuilder is maintained and slightly cleaned up.
This sets the stage for other builders for ops that name their
operands and results, like seq.reg and a chunk of the comb dialect.
=> [Python] Factor NamedValueBuilder out of InstanceBuilder, NFC.

integration_test/Bindings/Python/DesignEntry/connect.py, integration_test/Bindings/Python/DesignEntry/connect_errors.py, integration_test/Bindings/Python/DesignEntry/polynomial.py, lib/Bindings/Python/circt/design_entry.py, lib/Bindings/Python/circt/support.py
Make the @module annotation create a subclass which also inherits from `OpView`. When `OpView` is initialized, an unregistered MLIR operation gets created. Use the `Input` and `Output` classes as classmembers or instancemembers to create operands and results.
This breaks the construct based building. That'll be added back once we have a lowering API in python.
=> [Py] Make @module annotations create MLIR Operations

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
Fix an issue around mux canonicalization where folding a mux to one of its operands can result in invalidation of subsequent IR if the mux result does not have a known width. For example, picking an unsized constant can lead to the constant resolving to a width more narrow than assumed in the remaining IR. This change refuses to fold and canonicalize any multiplexers that have unkown result width.
Fixes #1142.
=> [FIRRTL] Don't fold mux with unknown result width

.github/workflows/nightlyIntegrationTests.yml, docs/PythonBindings.md
This flag has been renamed upstream.
Fixes https://github.com/llvm/circt/issues/1151.
=> [CI] Update CMake flag to enable building MLIR Python bindings.

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Dialect/FIRRTL/infer-widths-errors.mlir, test/Dialect/FIRRTL/infer-widths.mlir
* Extend the `InferWidths` pass to properly support recursive constraints. This is actually pretty straightforward, because the recursion either leaves the constraint unaffected (e.g. x >= x-1), or it renderes the constraint unsatisfiable (e.g. x >= x+1). Thus, to compute an actual value for a width, recursions can just be ignored.
* Add a separate pass over the constraint expressions that analyses the recursions for unsatisfiability. This is the tricky part of the entire width inference process. This adds a `LinIneq` struct to represent a canonicalized linear inequality that may be recursive in a single variable. A depth-first pass over the constraint expressions recursively maps them to this canonicalized form, which mainly tracks three distinct aspects of an inequality: a recursive …
=> [FIRRTL] Handle registers and recursion during width inference

integration_test/Bindings/Python/DesignEntry/connect.py, integration_test/Bindings/Python/DesignEntry/connect_errors.py, integration_test/Bindings/Python/DesignEntry/polynomial.py, integration_test/Bindings/Python/dialects/msft.py, integration_test/Bindings/Python/dialects/rtl.py, integration_test/Bindings/Python/dialects/rtl_errors.py, integration_test/Bindings/Python/dialects/seq.py, lib/Bindings/Python/circt/dialects/_hw_ops_ext.py
This still requires an explicit type from the end user, but it hides
the fact that an Attribute must be constructed under the hood.
=> [Python] Add a helper to create constants given a type and value.

integration_test/Bindings/Python/dialects/comb.py, lib/Bindings/Python/circt/dialects/_comb_ops_ext.py, lib/Bindings/Python/circt/dialects/_hw_ops_ext.py, lib/Bindings/Python/circt/dialects/_seq_ops_ext.py, lib/Bindings/Python/circt/dialects/comb.py, lib/Bindings/Python/circt/support.py
This refactors the NamedValueOpView to push all the complexity into a
shared constructor that works for a variety of ops like InstanceOp,
CompRegOp, and all of the non-variadic Comb ops.
To support this, subclasses must now define two hooks to retrieve the
list of operand names and result names. There is also a third hook to
create a backedge of an appropriate type for a given operand that was
left uninitialized. The default implementation works for ops that have
the same type for all operands.
=> [Python] Add NamedValueOpView builders for the Comb dialect.

integration_test/Bindings/Python/DesignEntry/connect_errors.py, integration_test/Bindings/Python/dialects/comb.py, integration_test/Bindings/Python/dialects/msft.py, integration_test/Bindings/Python/dialects/rtl.py, integration_test/Bindings/Python/dialects/rtl_errors.py, integration_test/Bindings/Python/dialects/seq.py, lib/Bindings/Python/circt/dialects/_comb_ops_ext.py, lib/Bindings/Python/circt/dialects/_hw_ops_ext.py, lib/Bindings/Python/circt/dialects/_seq_ops_ext.py, lib/Bindings/Python/circt/dialects/comb.py, lib/Bindings/Python/circt/dialects/seq.py
This makes the API more natural compared to an explicit dictionary of
input ports to set by name.
=> [Python] Update all create methods to accept keyword arguments.

integration_test/Bindings/Python/dialects/comb.py, integration_test/Bindings/Python/dialects/comb_errors.py, lib/Bindings/Python/circt/dialects/_comb_ops_ext.py, lib/Bindings/Python/circt/dialects/comb.py
The comparators all return an i1, so we simply don't need a result
type there. The binary ops all have the SameOperandsAndResultType
trait, so we can check the operand types and infer the result type.
=> [Python] Infer or elide result type from create when unnecessary.

lib/Dialect/FIRRTL/FIRRTLDialect.cpp, test/Dialect/FIRRTL/expand-whens.mlir
This code was erroneously assuming that the operand of subfield op was
always a bundle type.  BundleType can be wrapped in a FlipType if it is
an `in` port of an InstanceOp.  This change strips the flip type from
the bundle type when it is there.
=> [ExpandWhens] Strip flip types off of bundles before casting

test/Conversion/FIRRTLToLLHD/connect.fir, test/Conversion/FIRRTLToLLHD/empty_inouts.fir, test/Conversion/FIRRTLToLLHD/empty_ins.fir, test/Conversion/FIRRTLToLLHD/empty_none.fir, test/Conversion/FIRRTLToLLHD/empty_outs.fir, test/firtool/optimizations.fir, tools/firtool/firtool.cpp
This pass has been subjected to fuzz-testing for quite some time, and it
is surprising (in a negative usability sense) that it is not enabled by
default.
Some FIRRTL-to-LLHD tests were using firtool with uninitialized ports,
and this change switched them to use circt-translate instead.
=> [firtool] Enable expand-whens by default

include/circt/Dialect/SV/SVPasses.h, include/circt/Dialect/SV/SVPasses.td, lib/Dialect/SV/Transforms/CMakeLists.txt, lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
Extracted verilog simulation constructs to new modules which are bound to the original with a bind statement.
Effectively splits simulation-only code from synthesizable code.
=> Extract Test code from modules

lib/Translation/ExportVerilog/ExportVerilog.cpp, test/Dialect/SV/hw-legalize-names.mlir, test/ExportVerilog/hw-dialect.mlir, test/ExportVerilog/verilog-basic.mlir, test/ExportVerilog/verilog-errors.mlir
Name legalization is happening twice, once via a dedicated pass, again in export verilog.  This changes export verilog to not change the name of any port, wire, register, or instance durring emission, depending instead on legalize-names having done so already.  This is done by pre-populating the name table durring the prepare phase with incoming names, so that subsequent temporary names will never displace input names.
=> [ExportVerilog] Ensure stable names

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/canonicalization.mlir, test/Dialect/FIRRTL/parse-basic.fir
This pattern is already handled by the FIRRTL folders.  As a side effect
of this change, we are now aligning with how the Scala FIRRTL compiler
handles validif with a constant condition:
`validif(0, invalid, value)`:
- old: condition always false, return invalid.
- new: mux with an invalid operand, return the other operand.
This fixes #1186.
=> [FIRParser] Don't optimize validif in the parser

docs/RationaleFIRRTL.md, include/circt/Dialect/FIRRTL/FIRRTL.td, include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLOps.h, include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/test.mlir
Add a `verbatim.expr` operation to the FIRRTL dialect which lowers to the corresponding operation in the SV dialect. This allows construction of FIRRTL-typed expressions from a string representation. Based on a suggestion in #1178.
=> [FIRRTL] Add verbatim.expr operation

.github/workflows/buildAndTest.yml
The default shell is `sh -e {0}`, which leads to the error:
`[[: not found`
This uses `bash` instead of `sh`.
=> [Python] Fix format check by specifying bash as shell.

frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/test/polynomial.py, lib/Bindings/Python/circt/support.py
All other attributes come from object members (which can be converted to
attributes) and get inherited by the instance.
=> [PyCDE] Store design parameters in the 'parameters' attribute

frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/test/polynomial.py
This de-duplicates modules by the following properties:
* The Operation name being generated
* The Operation's Input types
* The Operation's Output types
* The Operation's Parameters
This allows the same PyCDE operation to be instantiated multiple
times, without trying to define the module multiple times.
=> [PyCDE] De-duplicate modules that are structurally equivalent.

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
This PR adds the following canonicalization for EQPrimOp and NEQPrimOp. 
* EQPrimOp
```
eq(x, 0) ->  not(x) when x is 1 bit
eq(x, 0) ->  not(orr(x)) when x is 1> bit
eq(x, ~0) ->  andr(x) when x is 1> bit
```
* NEQPrimOp
```
neq(x, 1) ->  not(x) when x is 1 bit
neq(x, 0) ->  orr(x) when x is 1> bit
neq(x, ~0) ->  not(andr(x)) when x is 1> bit
```
=> [FIRRTL] Add canonicalization for EQ/NEQ PrimOp

lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/hw-dialect.mlir, test/ExportVerilog/verilog-basic.mlir
Instances outputs have to bounce through a wire.  This moves the wire construction out of emission and into prepare.  Being explicit enables some cleanups so we have fewer temporary wires and more uses of meaningful wire names.
Reduces a small core's verilog output by 5% and the number of wires by 10%
=> [ExportVerilog] Prewire instance results

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/firtool/firtool.fir
Update the `LowerToHW` to add symbol to `WireOp` only if the `DontTouch` annotation is present.
This removes all the temporary wires added during `FIRRTL` transformations.
This should also remove the dependency on wire names, to determine if they are temporary.
Yet to handle, the case when `DontTouch` annotation present, but no name on wire, how to generate a unique name ?
Lit tests confirms this also removes the temporary wires left after `IMConstProp`
=> [LowerToHW] Add symbol to wires only if DontTouch annotation present

include/circt/Dialect/SV/SVTypeDecl.td, lib/Dialect/ESI/ESIPasses.cpp, lib/Dialect/SV/SVOps.cpp
Remove the default builders for sv::InterfaceOp and add a lone builder
that users a std::function<void()> to construct the body.  (This is
modeled off of how the always blocks work.)  This dramatically
simplifies the construction of interfaces and avoids boilerplate
whenever you want to place operations inside the interface.
=> [SV] Use function for InterfaceOp builder body

include/circt/Dialect/FIRRTL/InstanceGraph.h, include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/InstanceGraph.cpp, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/PrintInstanceGraph.cpp, test/Dialect/FIRRTL/print-instance-graph.mlir
This adds an instance graph analysis which tracks modules and where they are instantiated.  This includes a simple pass to print the graph in dot format, which is also used to test the instance graph.
This code was separated from the PrefixModulePass PR.
=> [FIRRTL] Add instance graph

lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/hw-dialect.mlir, test/ExportVerilog/verilog-basic.mlir
Do not print (well, print commented out) instances with the doNotPrint attribute.  However, ensure that all inputs and outputs to those instances are bound to verilog nameable things (regs, wires, ports).  This ensures that whatever the instance was standing in for can access its values.
=> [ExportVerilog] don't print doNotPrint instances

lib/Dialect/SV/Transforms/CMakeLists.txt, lib/Dialect/SV/Transforms/GeneratorCallout.cpp, lib/Dialect/SV/Transforms/HWCleanup.cpp, lib/Dialect/SV/Transforms/HWLegalizeNames.cpp, lib/Dialect/SV/Transforms/HWMemSimImpl.cpp, lib/Dialect/SV/Transforms/HWStubExternalModules.cpp, lib/Dialect/SV/Transforms/PassDetail.h, lib/Dialect/SV/Transforms/PrettifyVerilog.cpp, lib/Dialect/SV/Transforms/SVExtractTestCode.cpp, lib/Dialect/SV/Transforms/SVPassDetail.h
This cleans up the SV Dialect to better align with how MLIR does things for passes. This is a doing a number of disparate things which are all presented as separate commits in the patch set:
- The blind inclusion of `HWOps` is changed to a forward declare
- ~All `dependentDialects` are properly defined for SV passes~ (dropping this as I forgot that dependent dialects are those where the pass can _produce_ those ops)
- HW and Comb are added to CMakeLists.txt
- Unnecessary headers are pruned
- `SVPassDetail.h` is renamed to `PassDetail.h`
=> [SV] Cleanup of Includes/Dependencies for Passes, NFC

frontends/PyCDE/src/pycde/system.py, frontends/PyCDE/test/generator_options.py, include/circt/Dialect/MSFT/MSFT.td, lib/Dialect/MSFT/MSFTGenerator.cpp
The `generate` call accepts a list of candidate generators to run,
which defaults to empty.
When looking up a generator, the list is consulted. If it is empty,
the first generator is chosen by default. If it is present, the first
generator in the list is selected. If multiple candidates are in the
list, an error is raised.
=> [PyCDE] Add generator options to select a generator by name.

include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h, lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp
* Add constructors for `AnnotationSet` directly from arrays of `Attribute` and `Annotation`. This can come in handy in certain
situations where a user might have already filtered a bunch of attributes.
* Add a bunch of methods to apply the annotations recorded in an `AnnotationSet` to the attributes of an operation or port through various intermediate forms (directly on the op, updating a `DictionaryAttr`, modifying a `NamedAttrList`).
* Add a bunch of methods to add and remove annotations in a set. This is a convenient way for performing single-shot modifications of an op's or port's annotations (but may become inefficient if a lot of incremental changes are performed).
* Add a `removeAnnotations` method that takes a predicate function that gets applied to every annotation and can …
=> [FIRRTL] Expand AnnotationSet mutation API

lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp, test/firtool/blackbox.mlir
Before this change, BlackBoxReader will append multiple BlackBox
annotations with the same filename to the same output file. This is
different than the SFC behaviour, which will emit only one of the
existing blackbox annotations to the output file.
This is causing problems when there is the a duplicate BlackBox
annotation in the IR, which is resulting in multiple definitions of
modules in the output. Duplicate blackbox resource annotations are
fairly common, for example `plusarg_reader` is included from many
places.
The current firtool behaviour is a result of how these annotations are
lowered: each BlackBoxAnnotation becomes an `sv.verbatim` node, which
each append their contents to the destination file. This change updates
the BlackBox reader to only keep and lower the last annotation …
=> [FIRRTL][BlackBoxReader] Stop emitting duplicate blackboxes 

include/circt/Dialect/FIRRTL/FIRRTLTypes.h, lib/Dialect/FIRRTL/FIRRTLDialect.cpp, lib/Dialect/FIRRTL/FIRRTLTypes.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
This changes the way that lower types maps old bundle values to new
scalar values. The old way of mapping was using a pair of the bundle
value and a string representation of the field name:
```
(oldValue : Value, fieldName : String) -> (newValue : Value)
```
The new mapping is using FieldRefs, which are a more efficient way to
represent the same thing. A FieldRef is a pair of an `oldValue`, and an
integer ID unique to the field.  The integer IDs are assigned to each
field in a bundle when walking it in a depth first (preorder) order.
This shaves off 9 seconds from LowerTypes on the generated "test3" test
case, bringing it from 60s to 51s.
=> [FIRRTL][LowerTypes] Use FieldRefs instead of suffix strings

include/circt/Dialect/FIRRTL/FIRRTLOps.h, include/circt/Dialect/FIRRTL/FIRRTLTypes.h, lib/Dialect/FIRRTL/FIRRTLTypes.cpp, lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
This PR makes width inference more robust in the presence of not-yet-supported types and operations, skipping over them whenever they don't require any widths to be inferred (which is easy to check).
`firtool` run with `--infer-widths` and without now produces the exact same output MLIR when run on circt/perf [test1](https://github.com/circt/perf/blob/trunk/regress/test1.fir), [test2](https://github.com/circt/perf/blob/trunk/regress/test2.fir), [test3](https://github.com/circt/perf/blob/trunk/regress/test3.fir), and on one of SiFive's small cores. This despite the fact that these tests contain unsupported aggregate types and operations -- but with no unknown widths.
Once we're happy with this, `--infer-widths` can become the inverse `--disable-infer-widths` with the pass running by …
=> [FIRRTL] Make width inference ready for on-by-default

include/circt/Dialect/SV/SVStatements.td, include/circt/Dialect/SV/SVVisitors.h, lib/Dialect/SV/Transforms/SVExtractTestCode.cpp, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/Dialect/SV/basic.mlir, test/Dialect/SV/errors.mlir, test/ExportVerilog/sv-dialect.mlir
Add the `force` statement to SV dialect. `force` is a procedural continuous assignment statements. 
A force can be applied to nets as well as to variables. 
From the spec ::
A force statement to a variable shall override a procedural assignment or an assign procedural continuous
assignment to the variable until a release procedural statement is executed on the variable. When released,
then if the variable does not currently have an active assign procedural continuous assignment, the variable
shall not immediately change value. The variable shall maintain its current value until the next procedural
assignment or procedural continuous assignment to the variable. Releasing a variable that currently has an
active assign procedural continuous assignment shall immediately reestablish that …
=> [SV] Add SystemVerilog force,release statement to SV dialect.

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Dialect/FIRRTL/infer-widths-errors.mlir, test/Dialect/FIRRTL/infer-widths.mlir
Expand the `InferWidths` pass to handle width inference across modules and their instances. This is done by ensuring that free variables in the constraint problem are created first for all module ports in the IR, before module bodies are processed. This then allows InstanceOp to simply look up the variables for the ports on the instantiated module, and re-use them as the variables for the instance ports. Connecting to the instance port imposes a constraint on the instance port, which shares the same constraint variable as the corresponding module. As a result, the constraints from instance port connects are collectively imposed on the instantiated module.
=> [FIRRTL] Infer widths across modules and instances

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
Add symbol to `sv::RegOp` when lowering from FIRRTL if `DontTouch` annotation is present.
Will create a followup PR to update `canonicalize` to check for symbols.
=> [HW] Add symbol to sv::RegOp if DontTouch annotation present

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, test/Dialect/FIRRTL/expand-whens.mlir
Analog types are not sinks and do not need to be initialized like one.
This change stops adding analog types to the initialization checker.
=> [FIRRTL][ExpandWhens] Analog types do not need to be initialized

lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/connect-errors.mlir
This change extends the ConnectOp verifier to search inside bundles for
analog types. This makes the error show up earlier than after
lower-types. Since the analog check is cached, this is quick.
=> [FIRRTL] Don't allow connecting two bundles with internal analog types

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir
With the new lazy-location tracking, it is important that certain
location tracking book keeping be handled before and after every
statement.  The `mport` op parsing has a hack to parse the next
statement when it is a `skip` operation, but was not doing the correct
set up to parse it.
=> [FIRParser] Fix crash when mport is eating the skip op

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir
Cast all sink operands to passive during parsing.  Previously, this would only
cast flipped operands.  Since the type canonicalization refactor, it is
insufficient to simply check for flippedness.
Fixes #1181.
More details of what is going on are on #1181.
=> [FIRRTL] Cast sink operands to passive

tools/firtool/firtool.cpp
Width inference should now be resilient enough to be enabled by default -- mostly since it just leaves inputs alone that require no widths to be inferred. Worked on our test1/test2/test3 regression test in circt/perf, and one of SiFive's cores. We can also hold off with this merge until @drom had the chance to run a couple of cycles worth of fuzzing with width inference enabled (especially for test cases that aren't exercising width inference -- these should all still pass).
* Switch the `--infer-widths` option to run by default. The user can still disable the pass through `--infer-widths=false`.
=> [firtool] Enable width inference by default

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir
`LowerToHW` crashes if two ports have same name, use the port number instead of name.
=> [HW]Use port number instead of name

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Dialect/FIRRTL/infer-widths.mlir
This only adds support for aggregate types in wires and ports. Adding
support to other operations may not be that hard. Registers with resets
will require a larger fix.
=> [FIRRTL][InferWidths] Add support for aggregate types

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir
This is a similar change we have made a few places: after lower-types
runs these fields will have an outer flip type that must be removed with
isPassive. We must check the flow of the operand to determine if is
necessary to convert to passive.
=> [FIRParser] Force when operands to passive flow

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir
Change all asPassive casting in the FIRRTL parser to introduce a cast if a value
is not passive or if it has sink flow.  This unifies some of the whack-a-mole
that was introduced in fa221e5a and continued in 3cdd619f.
Simplify the parser, by changing convertToPassive to also do flow checking as
defined above.  This then allows forcePassive (introduced in fa221e5a) to be
removed.
=> [FIRRTL] Cleanup asPassive casting in parser

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Dialect/FIRRTL/infer-widths.mlir
Extend the `InferWidths` pass to add support for memory operations. These are a bit tricky since the memory may have multiple read, write, and readwrite ports, where the free variables added for the data ports should all agree. This commit implements memories by declaring vars for all ports, and then doing a fixup pass to ensure that the exprs generated for the "data"/"rdata"/"wdata" fields are reuse across the ports. Not extremely elegant, but gets the job done and keeps the existing `declareVars` implementation unchanged.
=> [FIRRTL][InferWidths] Add support for MemOp

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Dialect/FIRRTL/expand-whens.mlir, test/Dialect/FIRRTL/lower-types.mlir
There are 4 unrelated changes in this PR that I was too lazy to split apart.
[FIRRTL][LowerTypes] Extend SubaccessOp hack
The subaccess op is not supported yet in the lower-types pass. To get
around this limitation, there is an incorrect lowering of this
operation.  The subaccess op is lowered to always return the first index
of the array.
This change extends the hack to use support full lowering when there is
a vector of bundles.  It does this by creating a Subindex[0] op, and
lowering that.
This also change the diagnostic from an `error` to a `warning`.
[FIRRTL][ExpandWhens] Make sure values are passive before muxing
When a sink is used as a the RHS of a connect statement, the expand
whens pass may create a mux using that value.  The connect op can handle
operands with flip type, while …
=> [FIRRTL] LowerTypes + ExpandWhens: fixes for high firrtl

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Dialect/FIRRTL/infer-widths-errors.mlir, test/Dialect/FIRRTL/infer-widths.mlir
Add support for the `PartialConnectOp` to the `InferWidths` pass. The implementation is very much inspired by `LowerTypes`, where we co-iterate the fields of the two value types to be connected. Only fields present on both sides are considered, and vectors get special treatment. The case in width inference is slightly simpler than in `LowerTypes`. The implementation is handled by a dedicated `partiallyConstrainTypes` function, which is analogous to the existing `constrainTypes`.
=> [FIRRTL][InferWidths] Add support for PartialConnectOp

lib/Dialect/FIRRTL/Transforms/BlackBoxMemory.cpp, lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp, lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
This checks if anything in the IR changed, and call
`markAllAnalysisPreserved()` if nothing changes.  This covers:
- BlackBoxMemory
- BlackBoxReader
- InferWidths
=> [FIRRTL] Preserve cached analysis when nothing changes a few passes

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, test/Dialect/FIRRTL/expand-whens.mlir
This change splits the way module bodies are processed from the way
WhenOp regions are processed.  There was unneeded work in the module
body to process simulation constructs, which is now skipped.
This creates two different visitor classes, one for the Module and one
for the WhenOp, and moves the common code to a new parent class.
This change also checks if any changes have been made to the module and
will `markAnalysisPreserved` if no changes have been made.
=> [FIRRTL][ExpandWhens] Split the module body processing

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Dialect/FIRRTL/infer-widths-errors.mlir, test/Dialect/FIRRTL/infer-widths.mlir
* The way `LinIneq::add` derives a new maximum is overly pessimistic and can erroneously indicate cycles commonly found in designs as unbreakable. This adjusts the way the lower bound of the addition of two `LinIneq` terms is found, and makes it more mathematically rigorous. The resulting bound is also much tighter by trying to predict which one of the four possible combinations of added terms (max(a,b)+max(c,d) = max(a+c,a+d,b+c,b+d)) grows fastest as the value chosen for the recursive variable (an inferred width) grows larger.
* Rewrite the portion of the constraint solver that finds the actual final values of variables. The new approach treats each variable independently, and is sensitive to the fact that the cycle breaking that is necessary on expressions may actually produce …
=> [FIRRTL][InferWidths] Tighten LinIneq addition lower bounds, update solver

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp, lib/Dialect/FIRRTL/Transforms/PassDetails.h, test/Dialect/FIRRTL/grand-central-errors.mlir, test/Dialect/FIRRTL/grand-central.mlir, tools/firtool/firtool.cpp
This adds support for generating interface from scattered Grand Central serialized view annotations. For one Grand Central view (a separate module that can be used to provide an alternative representation of something, e.g., an architectural view of a microarchitectural unit) many interfaces may need to be generated. These are represented in a recursive structure of:
1. Ground types
2. Vector types
3. Bundle types
4. _Other_ types which SFC Grand Central appears to ignore (Strings, Booleans, Integers, Doubles)
An interface is represented by one bundle type. Any ground or vector type elements in that show up as `logic` or unpacked array `logic`, respectively. Sub-bundles show up as sub-interfaces.
This PR takes all of this and generates the necessary interfaces by building …
=> Grand Central Interface Support

tools/firtool/firtool.cpp
CSE can work with full efficacy on IR without inferrred widths.
Moving it early improves WidthInferrence and LowerTypes performance.
=> [firtool] Move CSE very early

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Dialect/FIRRTL/check-widths-errors.mlir, test/Dialect/FIRRTL/infer-widths-errors.mlir, test/Dialect/FIRRTL/infer-widths.mlir
FieldID calculation was wrong for aggregate types: the parent aggregate type was incrementing by 1 per child element, which is was incorrect when there nested bundles.  This changes it so the child element increments past itself. This is how it is done in the rest of the field id code.
=> [FIRRTL] Fix width inference for aggregate types

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Dialect/FIRRTL/infer-widths.mlir
The infer widths pass will emit a truncation when it needs to connect a
larger source to a smaller destination.  This code was not able to
handle the case when the destination was 0 bits.  This switched to using
the tail operation which is capable of truncating to a 0 bit value.
=> [FIRRTL][InferWidths] Allow connect truncation all the way to 0 bits

frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/test/polynomial.py, include/circt-c/Dialect/MSFT.h, include/circt/Dialect/MSFT/MSFT.td, lib/Bindings/Python/MSFTModule.cpp, lib/CAPI/Dialect/MSFT.cpp, lib/Dialect/MSFT/MSFTGenerator.cpp
Previously, different parameterizations of the same module would end
up using the most-recently registered generator and the
parameterization used when it was registered.
This includes the parameterization in the registered mapping, and
looks for that same parameterization when looking up generators. This
is trivially supported since we already store the parameterization as
an attribute on the Operation.
Added a few lines to the polynomial integration test to ensure the
behavior.
=> [PyCDE] Include parameters in generator registration and lookup.

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, test/Dialect/FIRRTL/expand-whens-errors.mlir
When an array is not initialized, the expand whens pass will print an
error for every element in the array.  This could print far too many
errors on huge arrays which may be missing a single bulk connect.  Since
ExpandWhens is running after lower-types there doesn't seem to be a good
way to reduce the number of errors printed, for example printing 1 error
per sink in the original source.
This changes the pass to quit after finding the first initialization
error.
=> [FIRRTL][ExpandWhens] Print one init error per run

lib/Dialect/SV/Transforms/PrettifyVerilog.cpp, test/Dialect/SV/prettify-verilog.mlir
This change makes the PrettifyVerilog pass duplicate constant ops into
the block where they are used. Sinking constants will allow the verilog
exporter to inline the expression instead of creating a `localparam`.
=> [PrettifyVerilog] Sink constants into the block where they are used

include/circt/Support/LoweringOptions.h, lib/Support/LoweringOptions.cpp, test/ExportVerilog/hw-dialect.mlir, test/ExportVerilog/sv-alwaysff.mlir, test/ExportVerilog/sv-dialect.mlir, test/ExportVerilog/verilog-basic.mlir, test/firtool/firtool.fir, test/firtool/style.fir
Some of our tools disallow driving a value from both an `always_ff`
block and an `initial` block. The Verilog spec in section `9.2.2.4`
specifies that variables set in an `always_ff` cannot be be set by any
other process. If the initial block is considered a process, then our
verilog emission for this case is incorrect.
This commit changes the default lowering options to not emit
`always_ff`, which increases our tool compatability.  Down the road we
may change how we initialize variables, which could allow us to legally
emit `always_ff`.
=> [ExportVerilog] Make alwaysff emit as always by default

frontends/PyCDE/test/compreg.py, integration_test/Bindings/Python/dialects/seq.py
Verilog emission is now defaulting to print `always` instead of
`always_ff`.  These tests don't run in a PR and were missed during
the change.
=> [Python][Seq] Fix integration test

include/circt/Dialect/FIRRTL/FIRRTLTypes.td, lib/Dialect/FIRRTL/FIRRTLAttributes.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Dialect/FIRRTL/annotations-errors.fir, test/Dialect/FIRRTL/annotations.fir, test/Dialect/FIRRTL/lower-types.mlir
Currently, we are using an array of string to reference sub-target in annotations:
```
%bar = firrtl.reg %clock {annotations = [{target = ["[0]", ".baz"], one}]} : 
(!firrtl.clock) -> !firrtl.vector<bundle<baz: vector<uint<1>, 2>>, 2>
```
In this patch, we replace the strings with `FieldID` introduced in #1045. The annotations above will look like:
```
%bar = firrtl.reg %clock {annotations = [{fieldID = 2 : i64, fieldIDRange = 2 : i64, one}]} : 
(!firrtl.clock) -> !firrtl.vector<bundle<baz: vector<uint<1>, 2>>, 2>
```
Note that when the sub-target points to aggregate types (in the example above, `vector<uint<1>, 2>`), we introduce a `fieldIDRange` attribute to indicate the range of IDs of the aggregate type. Such that in the `-lower-types`, as long as a flattened field's ID is in the …
=> [FIRRTL][Annotation] Use FieldID instead of strings to reference sub-target

lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp, test/Dialect/FIRRTL/annotations.fir
Previously, an annotation target like `Foo.Foo.bar.baz` is canonicalized to `~Foo|Foo>bar>baz`, which is incorrect. This patch resolves this issue by canonicalizing it to `~Foo|Foo>bar.baz`.
=> [FIRRTL][Annotation] Fix a bug in parsing annotation target

lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp, lib/Dialect/FIRRTL/Import/FIRAnnotations.h, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/annotations-errors.fir, test/Dialect/FIRRTL/annotations.fir
This is a small patch verifying the circuit target of each annotation matches the circuit name during the FIRRTL parsing.
=> [FIRRTL][Annotation] Verify circuit target during parsing

include/circt/Dialect/Calyx/Calyx.td, include/circt/Dialect/Calyx/CalyxOps.h, include/circt/Dialect/Calyx/CalyxStructure.td, lib/Dialect/Calyx/CMakeLists.txt, lib/Dialect/Calyx/CalyxOps.cpp, test/Dialect/Calyx/errors.mlir, test/Dialect/Calyx/round-trip.mlir
- Add new ops for `calyx.cell` (used to create instances of components and primitives) and `calyx.program` (encompasses a Calyx program).
- Verifier for `calyx.cells` (every op within the body should be a `calyx.cell`).
- Functions to get a component's port information. Eerily similar to both `FIRRTL` and `HW`'s implementations, but with some key differences (e.g. `HW` has `InOut` port direction, which Calyx currently doesn't support, `FIRRTL` uses `FIRRTLType`).
- Closes #1321. Using instances in this manner allows for Calyx component's to maintain the FunctionLike trait, and keep the separation of structure and control.
=> [Calyx] Add Cell, Program ops.

lib/Dialect/Comb/CombFolds.cpp, test/Dialect/Comb/canonicalization.mlir
Dedup arguments of `and(...)` to work across arguments on any position.
=> [Comb] Improve deduplication of And arguments in arbitrary positions.

lib/Dialect/Comb/CombFolds.cpp, test/Dialect/Comb/canonicalization.mlir
Tackles https://github.com/llvm/circt/issues/1326 in the Combs pass.
=> [Comb] Collapse extract(n, extract(m, x)) into extract(n+m, x)

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
Handle `DontTouch` annotation during `canonicalize` of `AttachOp`.
=> [FIRRTL]Handle DontTouch annotation with AttachOp

lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp, test/Dialect/FIRRTL/annotations.fir
This PR adds the `DontTouch` annotation when scattering the `DataTapsAnnotation` . Any annotation like the `DataTapsAnnotation` that implements the trait `HasDontTouches` should be treated as `DontTouch`. 
https://www.chisel-lang.org/api/firrtl/1.4.3/firrtl/transforms/HasDontTouches.html
=> Add DontTouch annotation when scattering DataTapsAnnotation

test/CAPI/CMakeLists.txt
This PR attempts to address https://github.com/llvm/circt/issues/880 . According to https://llvm.discourse.group/t/inconsistent-typeid-after-linking-libmlir-so/2122, the typeIDs do not yet properly work with .dylib, so statically linking seems like the right way to go ... for now.
I built LLVM and circt with the following flags on a M1 Macbook Air.
```bash
cmake -G Ninja ../llvm \                                   
-DLLVM_ENABLE_PROJECTS="mlir" \
-DLLVM_TARGETS_TO_BUILD="host" \
-DLLVM_ENABLE_ASSERTIONS=ON \
-DCMAKE_BUILD_TYPE=DEBUG
cmake -G Ninja .. \                                       
-DMLIR_DIR=$PWD/../llvm/build/lib/cmake/mlir \
-DLLVM_DIR=$PWD/../llvm/build/lib/cmake/llvm \
-DLLVM_ENABLE_ASSERTIONS=ON \
-DCMAKE_BUILD_TYPE=DEBUG
```
The invocation from `ninja -v …
=> [CAPI] Remove MLIRPublicAPI dependency from C-API test

lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/hw-dialect.mlir
External modules' types are not necessarily the same for every instance due to
SV module parameterization. Thus, we cannot rely on the extern module's port
declaration to determine to print a port or not. We can rely on the instance
operations' operand types in both cases since a verifier ensures that the types
match in the internal module case.
=> [ExportVerilog] Extern module's port types cannot be trusted, use operand types instead

frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/test/module_naming.py
If the user doesn't specify a get_module_name or otherwise set the
module_name parameter, use the improved module key as the name.
=> [PyCDE] Clean up module key and use it as name when necessary.

frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/test/module_naming.py, lib/Bindings/Python/circt/dialects/_hw_ops_ext.py
Three changes:
- Fixes a duplicate definition bug: in the case of parameterized modules, multiple generators (per parameterization call) are created so we cannot store the `generated_modules` map in the instance. Instead, we look it up in the IR.
- If the module has parameters, append them regardless of potential conflicts. This makes for less confusing code in the common case of multiple parameterizations since the first parameterization doesn't get a special name.
- Add the "pycde." prefix so we don't create modules which have name conflicts with existing RTL modules.
=> [PyCDE] Naming fixes and style changes

frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/src/pycde/support.py, frontends/PyCDE/test/polynomial.py, lib/Bindings/Python/circt/support.py
Since we want/need to support classes (for sanity's sake in large configuration
spaces), we need to include their data in the MLIR parameters attribute to
avoid duplication.
=> [PyCDE] Serialize class parameters to attributes

frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/src/pycde/support.py, lib/Dialect/MSFT/MSFTGenerator.cpp
For new module instances, set to the callsite. For misc creation a generator,
use the location of the generator. I think this is the best we can reasonably
do without upstream support.
=> [PyCDE] Add source location info where we control operation creation

include/circt/Dialect/Comb/Combinational.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/SV/Transforms/HWMemSimImpl.cpp
The `I64EnumAttr` requires to have its `cppNamespace` explicitly set in order not to pollute the global namespace.
=> [Comb] Move ICmpPredicate into comb namespace

frontends/PyCDE/src/pycde/support.py, lib/Bindings/Python/circt/support.py
This involves a hack similar to the Attribute hack.
=> [PyCDE] Make `pycde.support.Value` get the PyType if not specified

include/circt/Dialect/Calyx/Calyx.td, include/circt/Dialect/Calyx/CalyxOps.h, include/circt/Dialect/Calyx/CalyxStructure.td, lib/Dialect/Calyx/CalyxOps.cpp, test/Dialect/Calyx/errors.mlir, test/Dialect/Calyx/round-trip.mlir
- Adds `calyx.assign`, `calyx.group`, `calyx.done` (example in Calyx language provided [here](https://capra.cs.cornell.edu/docs/calyx/tutorial/language-tut.html#add-control)).
- Removes the `calyx.cells` region*.
*After discussing with @rachitnigam  and @sampsyo, trying to contain the IR in an (essentially) no-op region is not necessary. In future PRs, `calyx.wires` and `calyx.control` *may* be removed as well, in a separate PR since this has enough nonsense in it already.
=> [Calyx] Remove CellsOp. Add GroupOp, AssignOp, DoneOp.

integration_test/EmitVerilog/lint.mlir, integration_test/EmitVerilog/sv-structs.mlir, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/sv-dialect.mlir
Don't print `reg` if the reg holds a struct or array of struct. See
the spec, section 6.8 for the syntax of variable declarations.
=> [ExportVerilog] Special case register of struct or array of struct.

include/circt-c/Dialect/HW.h, integration_test/Bindings/Python/dialects/hw.py, lib/Bindings/Python/HWModule.cpp, lib/CAPI/Dialect/HW.cpp, test/CAPI/ir.c
This adds straightforward support for the TypeAliasType, as it stands
today, in the CAPI, then layers the Bindings directly on top of that.
Later improvements to the TypeAliasType's builder will of course
require refactoring part of this, but for now, this opens it up for
use in PyCDE.
=> [CAPI][Python] Add support for TypeAliasType in CAPI and Bindings.

README.md
Following this PR, the command will
- work on M1 Mac (or any non x86 / riscv targets :-) )
- Generate a `compile_commands.json` to be used by editor plugins. 
This _should_ address https://github.com/llvm/circt/issues/1048
=> Update cmake commands in README

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLTypes.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/canonicalization.mlir, test/Dialect/FIRRTL/parse-basic.fir
Add a new type, UInt01Type, which is a UInt that has either a 0-bit,
1-bit, or unspecified width.  Change the mux primop to use this type for
its select line (since this is what the Scala FIRRTL Compiler allows).
Add a folder that will fold a mux with a 0-bit select line to its false
value.  This aligns CIRCT with the behavior of the ZeroWidth pass in the
Scala FIRRTL Compiler (which will replace a 0-bit select with a 1-bit,
0-valued select) along with its constant propagation behavior.
I found this by doing some data-mining the ZeroWidth pass tests: https://github.com/chipsalliance/firrtl/blob/master/src/test/scala/firrtlTests/ZeroWidthTests.scala#L49.  Note: that this PR goes _further_ than the ZeroWidth pass.  That inserts a 1-bit zero.  This PR just drops the mux and uses its false …
=> [FIRRTL] Allow 0-bit mux cond, fold to false

include/circt/Dialect/Calyx/CalyxStructure.td, lib/Dialect/Calyx/CalyxOps.cpp, test/Dialect/Calyx/errors.mlir, test/Dialect/Calyx/round-trip.mlir
Adds `guard`s to assignments and done operations. A `guard` is a boolean expression that determines when the given assignment should be active. 
A few notes:
First, Calyx IR represents them in the following manner:
```
dest = guard ? src
```
In the dialect, it takes a slightly different form:
```
dest = src, guard ?
```
The reasoning for this is that I can just use the assemblyFormat for printing and parsing. If I were to try using the Calyx IR, the guard would be mistakenly parsed as the source. A TODO is left to match the Calyx IR parsing and printing.
Second, the `AssignOp` prints the type of both the source and destination, though they should always be the same. I've added a check in the verifier, but eventually we want to print one type for an AssignOp. I had to remove …
=> [Calyx] Add guard for assignments and done operations.

lib/Dialect/FIRRTL/FIRRTLOps.cpp
When building FIRRTLOps:
```
[1/6] Building CXX object lib/Dialect/FIRRTL/CMakeFiles/obj.CIRCTFIRRTL.dir/FIRRTLOps.cpp.o
auto sel = operands[0].getType();
^
1 warning generated
```
=> [FIRRTL] Remove unused variable.

frontends/PyCDE/src/pycde/system.py, frontends/PyCDE/src/pycde/types.py, frontends/PyCDE/test/pycde_types.py, lib/Bindings/Python/circt/dialects/_hw_ops_ext.py
This builds on the previous support to allow naming types through
PyCDE's types module. A new method will declare the registered type
aliases in a given mlir::ModuleOp. Multiple invocations will only emit
each alias once per module. This method is not intended to be exposed
to an end user, rather it is invoked automatically within a PyCDE
System during the user-facing method run_passes.
=> [PyCDE] Add functionality to declare named types.

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
This adds folders which eliminate casts when the input type matches the
output type, and the cast has no effect.
=> [FIRRTL] Add folders for no-effect casts

frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/src/pycde/system.py, lib/Bindings/Python/circt/dialects/_hw_ops_ext.py, lib/Bindings/Python/circt/support.py
- Adds type checking to PyCDE module instantiations.
- Corrects generate to use types defined in class rather than the example op.
- Adds type checking to Python bindings ModuleLike.create()
- Adds a safety check to `ModuleLike.__getattr_()` to avoid infinite recursion.
=> [Py] [PyCDE] More type checking in HWInstances and module instantiation

frontends/PyCDE/src/pycde/module.py, lib/Bindings/Python/circt/dialects/_hw_ops_ext.py, lib/Bindings/Python/circt/support.py
This is a hack to unblock us pending a group discussion.
- Use a `bitcast` in `StructCreateOp.create()` if the `result_type` is specified.
- Take advantage of type aliases in naming.
- In creating `OutputOps`, automatically convert to an alias if the port is just a type aliased version of the value being returned.
- (Unrelated) add class name in `_create_output_op` messages.
=> [Py] [PyCDE] Use `bitcast` to convert structs to TypeAliasTypes and take advantage of aliases

.github/workflows/buildAndTest.yml
When we switched to using docker for our PR builds, the default shell
changed from `bash` to `sh`.  This change forces bash for the string
wildcard test command in the `git fetch base commit` job, and switches
two other tests to be `sh` compatible.
=> [CI] Fix clang-format check

frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/src/pycde/system.py, lib/Bindings/Python/circt/dialects/_hw_ops_ext.py
- Hide module parameterization function arguments beginning with '_' from operation parameters.
- Module `.output_values()` returns a dict of output ports to Values.
- `System.print` passes through args.
=> [PyCDE] Misc usability features

include/circt/Scheduling/Algorithms.h, include/circt/Scheduling/DependenceIterator.h, include/circt/Scheduling/Problems.h, lib/Scheduling/ASAPScheduler.cpp, lib/Scheduling/CMakeLists.txt, lib/Scheduling/Problems.cpp, test/Scheduling/TestPasses.cpp
I believe it was a misconception to model problems and algorithms in the same class hierarchy. Analogy: Imagine LLVM's alias analyses would subclass `Function`.
To rectify this, this PR renames the `Scheduler` class to `Problem` (now living in `circt/Scheduling/Problems.h`), and removes the pure virtual `schedule()` method. Algorithms now declare their entry points in `circt/Scheduling/Algorithms.h`, and may hide their implementation classes, or no longer need to be class, see `scheduleASAP(Problem &prob)`.
Further benefits:
- Clients can contain problem construction code without needing to link any concrete algorithm.
- Algorithms can provide multiple entry points to schedule simpler problem variants. For example, an algorithm capable of sharing arbitrary operators can also solve a …
=> [Scheduling] Separate problems and algorithms.

docs/FIRRTLAnnotations.md, include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h, lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp, lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, test/Dialect/FIRRTL/imconstprop.mlir
The `DontTouch` annotation should block constant propagation through it, according to the Scala [FIRRTL implementation](https://github.com/chipsalliance/firrtl/blob/master/src/main/scala/firrtl/transforms/ConstantPropagation.scala) 
Mimic this behavior in `IMConstProp` pass.
1. Check if the value has a `DontTouch` annotaiton, whenever updating its lattice value.
2. Mark it as `overdefined`, such that it blocks any constant propagation through it.
=> [FIRRTL] Block constant propagation through DontTouchAnnotation

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir
Add the warnings for unprocessed annotations on CircuitOp.
=> [FIRRTL] Emit warning for unprocessed annotations on CircuitOp operation

include/circt/Dialect/FIRRTL/FIRRTLStatements.td, include/circt/Dialect/SV/SVStatements.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/SV/SVOps.cpp, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/ExportVerilog/sv-dialect.mlir
Add optional labels to the assert, assume, and cover SystemVerilog
operations.  Add optional labels to the assert, assume, cover, stop and
printf FIRRTL operations.
Flesh out lowering from these FIRRTL ops to their corresponding
SystemVerilog ops.  Emit the SystemVerilog ops as you'd expect for
assert, assume, and cover.  Names on stop and printf are dropped during
Verilog emission.
Labels/names are _optionally_ encoded using empty strings to represent
none.  This necessitates the proliferation of "custom<FooBar>"
directives in ODS.  This may be more cleanly handled (in ODS) with the
use of an "OptionalAttr<StrAttr>" or with upstream changes to MLIR to
better handle default-valued empty StrAttrs.
Fixes #1313.
I originally …
=> [FIRRTL][SV] Add names/labels to side effect stmts

frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/src/pycde/system.py
- Adds customized naming
- The body_builder 'mod' input ports now return PyCDE values
=> [PyCDE] Make systems feel more like modules

lib/Dialect/FIRRTL/FIRRTLDialect.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp
Inline `fieldIndex()` in `FIRRTLDialect.cpp` and `FIRRTLOps.cpp` .
This is a cleanup related to 6fe0463eac523f15f7a2b954c2a46663fc9c4c40
=> [FIRRTL] Code Cleanup for SubfieldOp, NFC

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp, lib/Dialect/FIRRTL/Transforms/LowerBundleVectorTypes.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/grand-central.mlir, test/Dialect/FIRRTL/test.mlir, test/ExportVerilog/verilog-basic.mlir
Lower the companion defined in a Grand Central view to a SystemVerilog `bind`.  This adds a new `BoolAttr` for FIRRTL dialect's `InstanceOp` called `lowerToBind`.  If this is true, then the destiny of an instance is to become a bind.
The first commit in this patch set turns on _actual_ bind emission (as opposed to emitting a chicken-switch comment).  Note: this is the minimal implementation necessary for bind emission. It doesn't handle the situation of binds needing to keep wires around.  Grand Central views are relying on io-less companion modules that are bound in.  Therefore, such a simplistic approach will work for the needs of Grand Central.
This PR is really four logical commits and it may be easier to review them individually.
=> [FIRRTL] Add support for binds to Grand Central

include/circt/Dialect/SV/SVStatements.td, include/circt/Dialect/SV/SVVisitors.h, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/sv-dialect.mlir
Adds three new operations to the SystemVerilog dialect:
- `sv.assert.concurrent` which maps to `assert property`
- `sv.assume.concurrent` which maps to `assume property`
- `sv.cover.concurrent` which maps to `cover property`
These are extremely simple versions that _are not modeling full-on properties_.  These act more like `always_ff` operations which will produce something like:
```verilog
optional_label : assert property(@(posedge clock) condition);
```
This is intended to be the minimal set of features necessary to actually emit `{assert, assume, cover} property` like a user would expect (and also meets the immediate needs of emitting SiFive SVA code).
=> [SV] Add Concurrent Assertions ("assert property" and friends)

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td, include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLDialect.cpp, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/canonicalization.mlir, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/imconstprop.mlir, test/Dialect/FIRRTL/infer-widths.mlir, test/Dialect/FIRRTL/test.mlir
This is a reimplementation of https://github.com/llvm/circt/pull/1354.  This is using a new FIRRTL operation called `firrtl.specialconstant` to create constants of type Reset, AsyncReset, and Clock.  This is also using a BoolAttr (which is a signless `IntegerAttr`) instead of the signed `IntegerAttr` used for other constants.
This was quickly put together just to see what it would look like, and probably requires a bunch more work. EDIT: Should be good to go now.
@lattner any thoughts on this vs the old approach?  I think this is more principled.  We have to handle BoolAttr constant materialization now, which is assumed to be a SpecialConstant.  The custom printer prints BoolAttr as `0` and `1` instead of `false` and `true`.  A few passes have to handle the new op.  IMCP holds these as …
=> [FIRRTL] Allow firrtl.constant of type Clock, Reset, AsyncReset

include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h, lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp, lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp, lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp, test/Dialect/FIRRTL/annotations.fir, test/Dialect/FIRRTL/grand-central-taps.mlir
Fix GrandCentral Annotation scattering and GrandCentralTaps pass to
support external module _sources_.  Previously, it was assumed that an
external module port had to be a "portName" sink.  However, it is
entirely possible for an external module port to be tapped.
Implement this fix with the following changes:
First, a new "type" field that can be either "portName" or "source" is
added during scattering of ReferenceDataTapKey Annotations.  This
unambiguously marks these taps as either a sink or a source.
Second, a new map is added to GrandCentralTaps to track external module
tap points.  This is necessary because the mechanism to refer to the tap
isn't either a BlockArgument or a straight Operation.  This needs
additional info after the operation to refer to a specific port.
Third, each …
=> [FIRRTL] Fix GCT Data Taps for ExtModule Sources

include/circt/Dialect/SV/SVInOutOps.td, include/circt/Dialect/SV/SVStatements.td, include/circt/Dialect/SV/SVVisitors.h, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/SV/SVOps.cpp, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/HW/basic.mlir, test/Dialect/HW/canonicalization.mlir, test/Dialect/HW/modules.mlir, test/Dialect/SV/prettify-verilog.mlir, test/ExportVerilog/hw-dialect.mlir, test/ExportVerilog/sv-dialect.mlir, test/ExportVerilog/verilog-basic.mlir, test/firtool/firtool.fir, test/firtool/split-verilog.mlir
sv.connect was a hold-over from firrtl and doesn't correspond to any sv construct.  It is roughly an sv assignment statement.  Add such an operation and remove sv.connect.
=> [SV] Replace sv.connect with sv.assign.

docs/RationaleHW-SV.md, lib/Dialect/Comb/CombFolds.cpp, test/Dialect/Comb/canonicalization.mlir, test/ExportVerilog/hw-dialect.mlir
The canonicalization routine attempts to reuse as much operands as it is as possible, namely:
Depending on the bit range being extracted, here are the possible outputs:
- `extract(cat(a, b, c))` ->  `c`
- `extract(cat(a, b, c))` -> `extract(c)`
- `extract(cat(a, b, c))` -> `cat(extract(a), extract(b)`
- `extract(cat(a, b, c))` -> `cat(extract(a), b, extract(c))`
The first 3 cases are all monotonically, since they reduces the number of elements we depend on. The last case, while not necessarily profitable, is not bad. I decided to keep it to be consistently canonicalize everything.
=> [Comb] Canonicalize extract(cat(..)) into cat(extract(..)).

lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/hw-dialect.mlir, test/ExportVerilog/verilog-basic.mlir
- Print the bitwidth when the width is >32 bits.
- Use "'sd" for signed numbers.
=> [SV] Fix the parameter integer printing for widths >32 bits

lib/Dialect/FIRRTL/Import/FIRParser.cpp
Windows is failing to token paste `add`, `not`, `or`, and `xor` when
expanding the macros. The macro `TOK_LPKEYWORD_PRIM` normally delegates
to `TOK_LPKEYWORD` when it is not defined by the user.
Windows build running here, will check this in the morning: https://github.com/llvm/circt/actions/runs/1032980651
=> [FIRRTL] Try to get windows compiling

include/circt/Dialect/Calyx/Calyx.td, include/circt/Dialect/Calyx/CalyxPasses.td, include/circt/Dialect/Calyx/CalyxStructure.td, lib/Dialect/Calyx/CalyxOps.cpp, lib/Dialect/Calyx/Transforms/GoInsertion.cpp, test/Dialect/Calyx/errors.mlir, test/Dialect/Calyx/go-insertion.mlir, test/Dialect/Calyx/round-trip.mlir
- Removes HW dialect from GoInsertion pass; it is unused.
- Add a component builder that uses `ComponentPortInfo` to define ports.
- Add helper functions to access the GoOp and DoneOp of a group.
- In the `GoInsertion` pass, place the `calyx.undef` value in the `calyx.wires` section. This pattern will be similar for the `CompileControl` pass. Any values used for guarding assignments should remain within the `calyx.wires` section for debugging and readability.
- Remove the result from a GroupOp's terminator. As far as I can tell, this is unnecessary.
=> [Calyx] Add helper functions, other cleanup for upcoming CompileControl pass.

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Dialect/FIRRTL/lower-types.mlir
Also clean up the muxes to not introduce invalid ops.
Closes #1436
=> Handle SubaccessOp of constants in Lower Types.  

frontends/PyCDE/test/polynomial.py, lib/Bindings/Python/circt/support.py
We keep a dict of backedges on OpViews that need them, so they may be
cleaned up later. In order to print the OpView in a situation where
the Edge was _not_ cleaned up, we store a reference to the OpView in
the Edge. This is fine, but in the event that the Edge _is_ cleaned
up, we were leaving the Edge in this dict of backedges, which meant
there was still a Python-side reference to the OpView.
Down the road, that prevents the OpView's destructor from running and
removing it from the liveOperations map at the appropriate time. By
forcibly dropping the Edge from the dict of backedges, we allow the
liveOperations map to be kept in sync.
The small change to the existing test case is enough to trigger the
problematic behavior and demonstrate the issue.
=> [Python] Drop reference to Edge instance after erasing it.

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
Canonicalize regreset(clock, reset, invalidvalue) to reg(clock). On the Scala side this is done by the `RemoveReset` pass.
=> [FIRRTL] Canonicalize regreset with invalidvalue

frontends/PyCDE/src/pycde/support.py, frontends/PyCDE/src/pycde/types.py, frontends/PyCDE/test/syntactic_sugar.py
- `inner` returns either itself or -- in the case of a type alias -- the inner type.
- `create` instantiates the type.
=> [PyCDE] Add `PyCDEType` to extend a type, adding `inner` and `create` methods

include/circt/Dialect/FIRRTL/FIRRTLStructure.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp
Add a `insertPorts` utility function to `FModuleOp` that is the complement to the existing `erasePorts`.
=> [FIRRTL] Add insertPorts utility to FModuleOp

lib/Dialect/Comb/CombFolds.cpp, test/Dialect/Comb/canonicalization.mlir
Builds on top of https://github.com/llvm/circt/pull/1423 (ie: should not be merged into that feature is merged).
Narrow the strength of addition from
```mlir
%addResult = add %a, %b : i10
%addResult = extract %addResult from 0 : i10 -> i3
```
into addition only on bits that will be used
```mlir
%a'         = extract %a from 0 : i3
%b'         = extract %b from 0 : i3
%addResult' = add %a', %b' : i3
%c0         = hw.constant 0 : i7
%addResult  = concat %c0, %addResult' : (i7, i3) -> i10
%addResult  = extract %addResult from 0 : i10 -> i3
```
Further extract-concat cannonicalizer passes (https://github.com/llvm/circt/pull/1423) will remove the leading bits in
%addResult
=> [Comb] Narrow addition operation to Bits that are observed

frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/src/pycde/support.py, frontends/PyCDE/src/pycde/types.py, frontends/PyCDE/test/syntactic_sugar.py
Instead of requiring users to create CIRCT arrays/structs themselves, just return lists and dicts! Involved putting type checking in `obj_to_value`, so I broke the externmod type mismatch exception. Will fix in a subsequent PR which will accomplish this in a more principled way.
I ended up copying `_create_output_op` and drastically simplifying it from the python bindings. It's different enough that it's not worth it to share code. We should consider dropping the original since it goes a bit beyond "just a binding".
=> [PyCDE] Support python objects as generator returns

frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/src/pycde/support.py, frontends/PyCDE/test/syntactic_sugar.py
This indicates not to connect an external modules port.
=> [PyCDE] Add `no_connect` value

include/circt/Dialect/SV/SVStatements.td, include/circt/Dialect/SV/SVTypeDecl.td, lib/Dialect/SV/SVOps.cpp, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/Dialect/ESI/connectivity.mlir, test/Dialect/SV/interfaces.mlir, test/ExportVerilog/sv-interfaces.mlir, test/ExportVerilog/verilog-basic.mlir
This adds rough support for converting an interface instance to a bind during emission.  This uses the same strategy as emission of bound instances:
- A `BindInterfaceOp`/`sv.bind.interface` is added, the counterpart of `BindOp`/`sv.bind`
- A mandatory name (derived from the SSA name if one exists) and an optional symbol are added to `InterfaceInstanceOp`.  These become necessary to do emission and for doing the back-tracking to link the `BindInterfaceOp` to a specific instance.
- Naive bind emission, using `(.*)` is added.  I'm not intending this to be the ultimate solution, but interface binds need to work a little differently from instance binds where the port connections are explicit. 
- During emission, interface instances are removed from the `getVerilogDeclWord` code path (which …
=> [SV][ExportVerilog] Add Ability to Bind Interfaces

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/annotations-errors.fir
Change the FIRRTL parser to error if any Annotations are unapplied to
the circuit.  Put differently, this will error if any Target in an
Annotation (or a generated Target from Annotation scattering) points at
something which does not exist in the circuit.
Residual Annotations indicate either a user problem like inconsistent
FIRRTL and Annotation files or some problem with scattering logic or the
parser itself.  E.g., you can hit this if you have busted scattering
code (that creates targets that do not exist) or for cases where
non-local Annotations get through scattering logic.  This is a situation
that needs to be addressed and continuing compilation may result in
extremely tedious errors due to the compiler effectively dropping
Annotation information which is assumed to be critical to …
=> [FIRRTL] Error on Annotations that Do Not Apply

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, test/Dialect/FIRRTL/imconstprop.mlir
`IMConstProp` was ignoring updating the lattice value for result of 'instance' op. 
It was only propagating the value into the module. This caused the result of `instance` op staying invalid.
Fixes https://github.com/llvm/circt/issues/1466
=> [FIRRTL][IMConstProp] Update lattice for instance op result

include/circt/Dialect/FIRRTL/FIRRTLTypes.td, lib/Dialect/FIRRTL/FIRRTLAttributes.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Dialect/FIRRTL/annotations.fir, test/Dialect/FIRRTL/lower-types.mlir
Previously, `SubAnnoAttr` had a `minFieldID` and a `maxFieldID` to represent the range of `fieldID`s it is targeting. The `maxFieldID` is introduced for the `LowerTypes_v1` to easily tell whether a leaf element is targeted by a `SubAnnoAttr` when filtering annotations without recursively looking into the aggregate type.
However, this `fieldID` range introduced many undefined things like cross-fields annotations (which are not allowed), making `SubAnnoAttr` hard to verify and handle. Meanwhile, as `LowerTypes_v2` doesn't flatten aggregate types at once, but recursively peel off the outermost layer of aggregate types, it no longer needs to answer the question above. Therefore, we decide to make `maxFieldID` retire.
This patch removed `maxFieldID` from `SubAnnoAttr` and renamed `minFieldID` …
=> [FIRRTL][Annotation] Remove maxFieldID param from SubAnnoAttr

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, test/Dialect/FIRRTL/imconstprop.mlir
The initialization code in `IMConstProp` had an early exit, which seems to be initializing incorrectly to `unknown`. 
Remove the early exit and properly initialize all operations. 
Fix for https://github.com/llvm/circt/issues/1465
=> [FIRRTL][IMConstProp] Proper initialization

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp
`gcc 7.5.0` cannot compile CIRCT, it requires the `mlir` namepsace on `mlir::OpTrait::IsIsolatedFromAbove`.
Fix for https://github.com/llvm/circt/issues/1445
=> [SV]Add mlir namespace for older gcc, NFC

lib/Bindings/Python/CMakeLists.txt, lib/Conversion/LLHDToLLVM/LLHDToLLVM.cpp
This picks up the start of some reworking happening upstream for
Python bindings, as well as another minor change in LLVM conversion.
=> Update LLVM to 345ace026b6e5cdbc38d207291e4b399d72e62ee.

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp, test/Dialect/FIRRTL/inliner.mlir, test/firtool/firtool.fir, tools/firtool/firtool.cpp
**[FIRRTL] Remove `flatten` annotations after flattening**
These annotations need to be removed after they are processed.  Inline
annotations are handled by deleting the annotated module.
**[firtool] Enable `-inline` by default**
This turns on the FIRRTL inliner by default.  This pass has some
questionable behaviour where it will delete any module not reachable
from the top level module.  This is an optimization that prevents the
pass from performing uneccesary work, while not leaving unprocessed
modules in the code.  This is also the mechanism through which modules
which had all instances inlined will be deleted. We may want to decide
if this behaviour is desirable before merging this commit.
The firtool annotation tests had to turn off the inliner to prevent
unreachable modules from …
=> [FIRRTL][ModuleInliner] Properly remove annotations + enable by default

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp, lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp, test/Dialect/FIRRTL/annotations.fir, test/Dialect/FIRRTL/grand-central.mlir
Add support to the existing Grand Central pass to instantiate the interface that it's already generating and to bind it into the "parent" module.  The "parent" module is the module targeted by an annotation where the interface is supposed to be bound in.
In order to do this, SystemVerilog ops are now generated in the Grand Central pass.  `LowerToHW` is updated to let allow-listed ops that it doesn't understand that are peers of FIRRTL modules and external modules (just `sv::InterfaceOp` for now) to go straight through to the lowered circuit.  Previously, this could be avoided because the interface was created in the root module.  However, interface instance ops need to be able to get at symbols (and this wasn't working without it).  There may be a more clever solution here.
This is …
=> [FIRRTL][GCT] Generate Binds for Grand Central Interfaces

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir
Certain annotations are expected to remain in the IR until LowerToHW runs. For example, annotations that prevent a pass from running on an operation have no effect if the pass doesn't run at all. But in that case, the pass also hasn't consume the annotations. This includes things like don't-obfuscate and don't-dedup.
This PR adds a whitelist to `warnOnRemainingAnnotations` in the`LowerToHW` pass to allow a select set of annotations to be silently dropped.
This currently whitelists the following:
- `sifive.enterprise.firrtl.DontObfuscateModuleAnnotation`
- `firrtl.transforms.NoDedupAnnotation`
- `sifive.enterprise.firrtl.ScalaClassAnnotation`
- `sifive.enterprise.firrtl.MarkDUTAnnotation`
=> [LowerToHW] Add whitelist for remaining annotation warnings

include/circt/Support/LoweringOptions.h, lib/Support/LoweringOptions.cpp, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/sv-always-wire.mlir, test/ExportVerilog/sv-dialect.mlir
Add the `exprInEventControl` lowering option to `ExportVerilog`, which if forces the emitted Verilog to spill constants (which live in a `localparam`) into a `wire` when they are used as part of an event control (`@(posedge ...)`). The `exprInEventControl` option restores the old behavior of allowing arbitrary expressions in the event control.
Fixes #1450.
=> [ExportVerilog] Add option to force wires in event control exprs

include/circt/Scheduling/Problems.h, lib/Scheduling/Problems.cpp, lib/Scheduling/TestPasses.cpp, test/Scheduling/cyclic-problem-errors.mlir, test/Scheduling/cyclic-problems.mlir
Straightforward extension of the basic scheduling problem:
- Dependences have an optional *distance* property.
- The cyclic problem has a solution property *initiation interval* (II).
- The solution is valid iff for each dependence `i -> j` with distance `dist` (default value 0, if not set), `i` finishes before `j` starts `dist` iterations/samples/pipeline starts/etc. later. Formally:
`startTime(i) + latency(assocOpr(i)) <= startTime(j) + dist * II`
=> [Scheduling] Define cyclic problem.

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, test/Dialect/FIRRTL/imconstprop.mlir
Change IMCP to update output ports and not just _external_ users of
output ports.  Output ports have wire-like semantics and may be read
from as well as written to.
Fixes #1478.
Fixes #1488.
=> [FIRRTL] Update output ports in IMCP lattice

lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Dialect/FIRRTL/infer-widths.mlir
Relax short circuit logic inside InferWidths so that a MuxPrimOp still
generates constraints from its select line (which sets a hard
requirement on a 1-bit width) even if the width of the mux result is
already known.
Previously, this would set no constraints derived from the select line if the width was already known. This would cause circuits like the following to have uninferred widths:
```scala
circuit top_mod :
module top_mod :
input sel: UInt
input t: UInt<1>
input f: UInt<1>
output out: UInt<1>
out <= mux(sel, t, f)
```
=> [FIRRTL] Infer width from mux sel for known result

CMakeLists.txt
When building CIRCT standalone, it isn't safe to assume these
configurations can be applied, since the build of LLVM may have used a
different configuration. These keeps the same recommended defaults,
but only for a unified build via LLVM_EXTERNAL_PROJECTS.
=> [CMake] Only tweak linking settings when doing a unified build.

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td, test/Dialect/FIRRTL/canonicalization.mlir, test/Dialect/FIRRTL/remove-reset.mlir
Port the Scala FIRRTL test cases from `RemoveResetSpec.scala`. Fix a regression in the canonicalizer where the switch to `specialconstant` removed a fold for `uint<1>` resets of cosntant `0`.
=> [FIRRTL] Add tests from RemoveResetSpec.scala, apply fixes

integration_test/Bindings/Python/dialects/esi.py, lib/Bindings/Python/CMakeLists.txt
Ninja is able to generate this, but make does not, and the build
fails.
=> [CMake] Ensure the build directory for generated Python exists.

include/circt/Dialect/Calyx/CalyxStructure.td, lib/Dialect/Calyx/CalyxDialect.cpp, lib/Dialect/Calyx/CalyxOps.cpp, test/Dialect/Calyx/compile-control.mlir, test/Dialect/Calyx/round-trip.mlir
This PR adds the OpAsmInterface for components, to allow explicit names for block arguments. Since continuous assignments within a component may use both the arguments and results of its parent, I've decided the FIRRTL-like approach is cleaner. This means _all_ ports are listed as block arguments.
Cleanup:
- Just use a single attribute for all port names. Distinguish input ports and output ports by another attribute.
=> [Calyx] Add OpAsmInterface for components. Use all ports as block arguments.

frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/src/pycde/system.py, frontends/PyCDE/test/compreg.py, frontends/PyCDE/test/generator_options.py, frontends/PyCDE/test/module_naming.py, frontends/PyCDE/test/polynomial.py, frontends/PyCDE/test/syntactic_sugar.py, lib/Dialect/MSFT/MSFTGenerator.cpp
The old `System` was a clone of ESI's `System`. This is more like what one wants out of pycde.
=> [PyCDE] Refactor `pycde.System` to take a list of modules

lib/Dialect/Comb/CombFolds.cpp, test/Dialect/Comb/canonicalization.mlir
This is a second attempt in implementing #1424 , fixing some memory access bugs.
There are two memory access issues:
1. What @lattner mentioned about uses in https://github.com/llvm/circt/commit/2660c0b3144be11370839ebfaad8c0c80b335f82#r53799782 . I fixed this by dumping `operation->getUsers` into a vector .
2. Calling `rewriter.replaceOp` ([here](https://github.com/llvm/circt/commit/2660c0b3144be11370839ebfaad8c0c80b335f82#diff-6f80524cbed3f3dee4e82a5f97ae9ade89be7f2132704918ec60d91889bfc751R159)) erases the op under the hood and invalidates that piece of memory.  This was fine when we are replacing the Op being canonicalized, but reasons i'm not sure of, erasing users of the op is buggy.  valgrind confirms that the GreedyPatternRewriter has a dangling reference (see log below), but i …
=> [Comb] Narrow Arithmetic and Bitwise Ops - Take 2

docs/RationaleFIRRTL.md, include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td, include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
Change FIRRTL dialect folders to use the Scala FIRRTL Compiler (SFC)
interpretation of invalid.  An invalid involving a non-mux primitive
operation is treated as a constant zero.  An invalid involving the true
or false paths of a multiplexer is treated as a conditionally valid
expression which always evaluates to the non-invalid path.
This intentionally deviates from the FIRRTL spec interpretation of
invalid as undefined behavior.  Invalidations are frequently generated
by Chisel (as a means of telling the SFC that an uninitialized component
is okay) and by a legacy version of Chisel ("Chisel 2 Compatibility
Mode") which defaults all connections to invalid to permanently disable
uninitialized checking.
Concretely, this adds the following folds:
- add(a, invalid) -> pad(a, width)
- …
=> [FIRRTL] Correct, Document Invalid Behavior

include/circt/Dialect/Comb/Combinational.td, lib/Dialect/Comb/CombOps.cpp, test/Dialect/Comb/canonicalization.mlir
Validates ConcatOp's input operand's total width matches those specified by its type.
Some tests  required some rectification to pass, since they had width mismatches.
=> [Comb] Verify ConcatOp input operands total width matches type

include/circt/Dialect/SV/SVExpressions.td, include/circt/Dialect/SV/SVVisitors.h, lib/Dialect/SV/SVOps.cpp, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/Dialect/SV/basic.mlir, test/ExportVerilog/sv-dialect.mlir
In many cases, we need to represent named `localparam`s to make the emitted verilog prettier. For example, in the implementation of FSM, we want:
```verilog
localparam [1:0] IDLE = 2'h0; // <stdin>:19:13
always @(posedge clk or negedge rst_n) begin  // <stdin>:23:5
if (!rst_n) begin   // <stdin>:23:5
state <= IDLE;    // <stdin>:169:7
end
```
rather than:
```verilog
localparam [1:0] _T_0 = 2'h0; // <stdin>:19:13
always @(posedge clk or negedge rst_n) begin  // <stdin>:23:5
if (!rst_n) begin   // <stdin>:23:5
state <= _T_0;    // <stdin>:169:7
end
```
or:
```verilog
always @(posedge clk or negedge rst_n) begin  // <stdin>:23:5
if (!rst_n) begin   // <stdin>:23:5
state <= 2'h0;    // <stdin>:169:7
end
```
This patch introduce an `sv.localparam` operation with a `name` attribute. Both …
=> [SV] Add a LocalparamOp

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp, test/Dialect/FIRRTL/check-comb-cycles.mlir, tools/firtool/firtool.cpp
This pass runs a DFS traversing to detect the combinational loops in the IR. As the beginning, the current implementation assumes the aggregated types have been lowered to ground types before this pass.
I tested this with `dot.mlir` and `matmul.mlir` in `integration_test/Dialect/Handshake/`. Combinational loops can be detected on both test cases if `-handshake-insert-buffer` is not applied. Also tested on all cases in [perf](https://github.com/circt/perf), no combinational loop detected :)
Fixes #1138.
=> [FIRRTL] Add a CheckCombCycles pass

tools/CMakeLists.txt, tools/circt-reduce/CMakeLists.txt, tools/circt-reduce/circt-reduce.cpp
Add a `circt-reduce` utility, which basically follows the "build a custom mlir-reduce" steps described in the MLIR documentation. The intent here is to have a first step towards a CIRCT-specific reduction utility. At a later stage, we may want to start populating the reducer framework with reduction patterns specific to CIRCT (like fan-in/-out cone isolation, port removal, etc).
=> Add circt-reduce

lib/Dialect/Calyx/Export/CalyxEmitter.cpp, test/Dialect/Calyx/emit.mlir
[Example](https://github.com/cucapra/calyx/blob/bcad5395e262e96516ef6f60508ec2f8218d216a/tests/correctness/if.futil#L17) of an unguarded assignment in Calyx.
=> [Calyx] Emit (unguarded) assignments.

include/circt/Dialect/FIRRTL/FIRRTLOps.h, lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp
Since the order of subfields of MemOp ports is fixed, it makes sense to define the kind of them as an enum type. This can avoid to compare the subfield index with some magic numbers.
See also the discussion [here](https://github.com/llvm/circt/pull/1388#discussion_r681944097).
=> [FIRRTL] Enum the kind of subfields of MemOp ports

test/firtool/commandline.mlir, tools/firtool/firtool.cpp
Add the `--split-input-file` and `--verify-diagnostics` options to firtool. This brings it more in line with other tools such as circt-opt, and simplifies writing integration tests against firtool.
=> [firtool] Add split-input-file and verify-diagnostics options

include/circt/Scheduling/Algorithms.h, lib/Scheduling/CMakeLists.txt, lib/Scheduling/SimplexScheduler.cpp, lib/Scheduling/TestPasses.cpp, test/Scheduling/cyclic-problems.mlir, test/Scheduling/simplex-errors.mlir
This scheduler uses linear programming and a handwritten simplex solver to compute the II and start times for the `CyclicProblem`. I'll add support for the basic `Problem` in a later PR.
This is an implementation of the approach proposed in:
> B. D. de Dinechin, "Simplex Scheduling: More than Lifetime-Sensitive Instruction Scheduling", PRISM 1994.22, 1994.
([Paper on ResearchGate](https://www.researchgate.net/publication/2607040_Simplex_Scheduling_More_than_Lifetime-Sensitive_Instruction_Scheduling))
**Rationale** Linear programming is the superior framework for tackling the "computing start times"-aspect of scheduling problems, so I wanted to have LP-based scheduling technology as soon as possible. This, of course, requires an LP solver. I decided to implement this very basic and …
=> [Scheduling] Add simplex scheduler for the cyclic problem.

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
Constant propagate registers that are driven by a mux tree containing only instances of one constant and self-assigns. 
Detect the case if a register only has two possible drivers:  (1) itself/uninit and (2) constant. 
The mux can then be replaced with the constant. 
``reg = mux(cond1, reg, 3)`` can be replaced with --> ``reg = 3 ``
``reg = mux(cond2, 3, reg)`` can be replaced with --> ``reg = 3``
Fix for https://github.com/llvm/circt/issues/1483
=> [FIRRTL] Constant prop registers with self-init to mux pattern

README.md
Previous link went to Discourse which isn't the right location. I believe this link is the right one, but I could be wrong.
=> README: fix link for how to get commit access

CMakeLists.txt
The default of "hidden" may not always make sense, so allow it to be
overridden.
=> [CMake] Allow users to override CMAKE_CXX_VISIBILITY_PRESET.

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp, test/Dialect/SV/hw-extract-test-code.mlir
This PR extracts the `assume` and `assert` statements to different modules, this is to mimic the SFC behavior.
=> [SV][ExtractTestCode] Extract assume and asserts to separate modules

include/circt/Scheduling/Algorithms.h, lib/Scheduling/SimplexScheduler.cpp, lib/Scheduling/TestPasses.cpp, test/Scheduling/problems.mlir
The simplex scheduler can also solve basic `Problem`s with the following changes:
- Don't query the dependence distance (instead always assume distance=0).
- Ignore the initiation interval, and don't attempt to store it in the solution.
=> [Scheduling] Support for basic problems in the simplex scheduler.

include/circt/Scheduling/Problems.h, lib/Scheduling/Problems.cpp, lib/Scheduling/TestPasses.cpp, test/Scheduling/spo-problem-errors.mlir, test/Scheduling/spo-problems.mlir
Extends the basic problem model with a new operator type property `limit`, representing the maximum number of operations that can "use" a given operator type in each time step.
=> [Scheduling] Add problem model for shared, pipelined operators.

include/circt/Dialect/MSFT/MSFT.td, include/circt/Dialect/MSFT/MSFTAttributes.h, lib/Dialect/MSFT/MSFTAttributes.cpp, lib/Dialect/MSFT/TclExport/ExportQuartusTcl.cpp, test/Dialect/MSFT/location.mlir, test/Dialect/MSFT/translate-errors.mlir
Placement data can now be filtered to a particular instance. Adds the `SwitchInstance` attribute to select an attribute from a list keyed off the instance ID (currently just the path in the instance hierarchy). This method is not robust to hierarchy changes, but it's a start.
Modified `ExportTcl` to respect the `SwitchInstance` attribute.
=> [MSFT] Instance specific placement

include/circt/Dialect/HW/HWAggregates.td, include/circt/Dialect/HW/HWTypes.h, include/circt/Dialect/HW/HWTypes.td, lib/Dialect/HW/HWOps.cpp, test/Dialect/HW/errors.mlir, test/Dialect/HW/types.mlir, test/ExportVerilog/hw-typedecls.mlir
This was always intended to be supported, but was removed in
862f1b4. This adds it back, and updates the parsers for the relevant
ops to actually support type aliases (they previously didn't).
In order to help avoid the need to cast away aliases everywhere, a new
base class is added to all aggregate types that support aliases. This
class can represent a type alias or the aggregate type. It implicitly
converts to the aggregate type, which helps avoid explicit casts.
=> [HW] Support TypeAliasType in return type for aggregate create ops.

include/circt/Dialect/FIRRTL/FIRRTLOps.h, include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, include/circt/Support/FieldRef.h, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/InferResets.cpp, test/Dialect/FIRRTL/infer-resets-errors.mlir, test/Dialect/FIRRTL/infer-resets.mlir, tools/firtool/firtool.cpp
Add the `InferResets` transformation pass to the FIRRTL dialect, which assigns asynchronous resets to registers without reset, and replaces `reset` types with either `uint<1>` or `asyncreset`, as appropriate.
This combines the operation of the following Scala FIRRTL compiler passes:
- `InferResets`
- `RemoveReset`
- `CheckResets`
- `FullAsyncResetTransform`
More precisely, this does the following:
* Extract reset-related test cases from the existing Scala FIRRTL compiler code; specifically from `InferResets`, `CheckResets`, `RemoveReset`, and `FullAsyncResetTransform`.
* Add the `InferResets` transformation pass to the FIRRTL dialect, which assigns asynchronous resets to registers without reset, and replaces `reset` types with either `uint<1>` or `asyncreset`, as appropriate.
* Add the …
=> [FIRRTL] Add InferResets pass

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
Update FIRRTLFolds to use the method `getSingleConnectUserOf` 
that scans all the uses of the specified value, checking to see if there is
exactly one connect that sets the value as its destination.  This returns
the operation if found and if all the other users are "reads" from the
value.
(Followup to address comments on https://github.com/llvm/circt/pull/1546)
=> [FIRRTL] Refactor FIRRTLFolds, NFC

include/circt/Dialect/Comb/Combinational.td, lib/Dialect/Comb/CombFolds.cpp, test/Dialect/HW/canonicalization.mlir
This PR adds following canonicalization. 
```
ShlOp(x, cst) -> Concat(Extract(x), zeros)
ShrUOp(x, cst) -> Concat(zeros, Extract(x))
ShrSOp(x, cst) -> Concat(sext(extract(x, topbit)),extract(x))
```
If shift amounts are larger than the width, they will be converted into `zeros` or `sext(topbit)`.
Will close #1261
=> [Comb] Canonicalize away shifts by a constant

lib/Dialect/Comb/CombFolds.cpp, test/Dialect/Comb/canonicalization.mlir
This substantially shrinks the size of the IR and generates much
better verilog.  E.g. before:
```
module top_mod(
input  [1:0] sel,
input  [7:0] a, b, c, d,
output [7:0] y);
assign y = sel == 2'h0 ? a : sel == 2'h1 ? b : sel == 2'h2 ? c : d;
endmodule
```
and after:
```
module top_mod(
input  [1:0] sel,
input  [7:0] a, b, c, d,
output [7:0] y);
assign y = ({{a}, {b}, {c}, {d}})[sel];
endmodule
```
This uses a couple heuristics to keep things from going crazy. This
is progress towards closing Issue #675, but it is still not getting
some important cases due to Issue #1549.  Those can be handled as
follow-up patches.
=> [Comb] Fold a large series of of mux ops into array_create/get.

lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/hw-dialect.mlir
@lattner Is this the correct place to put this logic?
=> [ExportVerilog] Don't output temporaries for output port assignments

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/imconstprop.mlir
Add the fold pattern for a mux with the same constant low and high.
That is, ` x = mux (cond, <constant1> ,<constant1>)` can be replaced with, -->  `x = constant1`
This triggers the following constant propagation:
``` mlir
%c11_ui8 = firrtl.constant 11 : !firrtl.uint<8>
%r = firrtl.regreset %clock, %reset, %c11_ui8  : !firrtl.uint<1>, !firrtl.uint<8>, !firrtl.uint<8>
%0 = firrtl.mux(%cond, %c11_ui8, %r) : (!firrtl.uint<1>, !firrtl.uint<8>, !firrtl.uint<8>) -> !firrtl.uint<8>
firrtl.connect %r, %0 : !firrtl.uint<8>, !firrtl.uint<8>
firrtl.connect %z, %r : !firrtl.uint<8>, !firrtl.uint<8>
```
Can be optimized to :: 
```mlir
%c11_ui8 = firrtl.constant 11
firrtl.connect %z, %c11_ui8
```
This triggers other constant propagation of mux trees with registers and reset registers.
This change …
=> [FIRRTL] Fold Mux with the same constant high and low

lib/Dialect/FIRRTL/Transforms/InferResets.cpp, test/Dialect/FIRRTL/infer-resets.mlir
When tracing the resets of a connect operation, the pass would recursively trace  the `src` and `dest` values. When one of the values came from a subfield operation, it would associate the resets of the input bundle of the subfield operation with the resets in result.  The pass neglected to recursively trace the resets of the input of each subfield operation, which resulted in a failure to determine the correct reset-network when there were nested aggregates.
To fix this, we need to recursively trace the resets of the input expression of every subfield operation.
This strategy of recursively visiting the `src` and `dest` expressions of a connect statement probably comes from the SFC, where the result of a subfield operation can only be used once.  In MFC this could result in visiting the …
=> [FIRRTL][InferReset] Properly infer resets in nested aggregates

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, test/Dialect/FIRRTL/expand-whens.mlir
Expand whens takes the following code:
```firrtl
when a:
x <= 1
else
x <= 2
```
And transforms it turns it into the (desirable) code:
```firrtl
x <= mux(a, 1, 2)
```
However for nested whens, it was being overly pessimistic in the
condition of the mux.
Expand whens takes the following code:
```firrtl
when a:
when b:
x <= 1
else:
x <= 2
else
x <= 3
```
And transforms it into
```firrtl
x <= mux(a, mux(a & b, 1, 2), 3)
```
When it should transform it into:
```firrtl
x <= mux(a, mux(b, 1, 2), 3)
```
In the code change `condition` refers to the condition of the current
WhenOp , and `thenCondition` refers to the all parent `WhenOp`
conditions `and`ed together.  The `thenCondition` is intended to be used
for simulation constructs which are copied directly into the module's
body.
The following …
=> [FIRRTL][ExpandWhens] Simplify muxing of connected values

include/circt/Dialect/Calyx/CalyxOps.h, include/circt/Dialect/Calyx/CalyxStructure.td, lib/Dialect/Calyx/CalyxOps.cpp, lib/Dialect/Calyx/Export/CalyxEmitter.cpp
If the ArrayRef ports argument contains an unordered list of ports, the first numInPorts ports are registered as the input ports, and the remainder as outputs.
I.e. the following list of ports:
```c++
SmallVector<calyx::ComponentPortInfo> ports;
ports.push_back({rewriter.getStringAttr("clk"), rewriter.getI1Type(), calyx::PortDirection::INPUT});
ports.push_back({rewriter.getStringAttr("reset"), rewriter.getI1Type(), calyx::PortDirection::INPUT});
ports.push_back({rewriter.getStringAttr("done"), rewriter.getI1Type(), calyx::PortDirection::OUTPUT}); // <--
ports.push_back({rewriter.getStringAttr("go"), rewriter.getI1Type(), calyx::PortDirection::INPUT});
```
will currently (incorrectly) create a component with the following signature:
```mlir
calyx.component @main(%clk: i1, %reset: i1, …
```
=> [Calyx] Use explicit in- and output port lists in ComponentOp::build

include/circt/Dialect/Calyx/Calyx.td, include/circt/Dialect/Calyx/CalyxDialect.h, include/circt/Dialect/Calyx/CalyxOps.h, include/circt/Dialect/Calyx/CalyxPrimitives.td, include/circt/Dialect/Calyx/CalyxStructure.td, lib/Dialect/Calyx/CalyxOps.cpp, lib/Dialect/Calyx/Export/CalyxEmitter.cpp, test/Dialect/Calyx/compile-control.mlir, test/Dialect/Calyx/emit.mlir, test/Dialect/Calyx/errors.mlir, test/Dialect/Calyx/go-insertion.mlir, test/Dialect/Calyx/remove-groups.mlir, test/Dialect/Calyx/round-trip.mlir
The `Cell` trait is used to annotate each sub-component within a component. This consists of primitives (e.g. `RegOp`) and component instances. This will be useful for future passes that want to work on `Cell`s, such as resource-sharing.
I've also renamed the `CellOp` to `InstanceOp`, and added a (hopefully) cleaner interface for primitives to minimize code duplication.
=> [Calyx] Add Cell trait.

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir
When a node is used as the address (aka index) of a CHIRRTL sequential
read-only memory port, the memory port is enabled at the declaration
location of the node op.  Nodes are being removed by the parser if they
don't carry any annotations. When the node op is removed by the parser,
the enable conditions of the memory change, and sometimes the memory
port is never enabled.
This change removes the small optimization from the FIRParser so that
the memory port enable can be properly inferred.  These node operations
will still be removed later on during canonicalization.
=> [FIRRTL][Parser] Stop removing no-op nodes when parsing

lib/Dialect/SV/SVOps.cpp
Accidentally found we didn't implement the builder of `AlwaysCombOp` :O
=> [SV] Implement build method of AlwaysCombOp

include/circt/Dialect/FIRRTL/Passes.h, test/CMakeLists.txt, test/circt-reduce/commandline.mlir, test/circt-reduce/trivial.mlir, test/circt-reduce/trivial.sh, test/lit.cfg.py, tools/circt-reduce/CMakeLists.txt, tools/circt-reduce/Reduction.cpp, tools/circt-reduce/Reduction.h, tools/circt-reduce/circt-reduce.cpp
Add a first implementation of `circt-reduce` that actually performs some useful reduction. It is inspired by what is being done upstream with `mlir-reduce`, but uses a more specific implementation that targets what is immediately useful for us. As upstream evolves (and maybe we can help with that), we'll be able to switch over to the `mlir-reduce` framework again.
This PR also adds a handful of sample reduction patterns mainly operating on the FIRRTL dialect to have a concrete example of how things can reduce. This allowed me to reduce a >200M FIRRTL test case to a 2.7K test case (essentially just a bunch of wires and assigns). This is not complete at all, and down the road we'll want to gather the reduction patterns from the dialects directly rather than hacking them together in …
=> [reduce] Add a first proof-of-concept reducer implementation with sample FIRRTL dialect reducers

test/firtool/firtool.fir, tools/firtool/firtool.cpp
Add a `--parse-only` option to `firtool` which causes the program to stop after the FIR/MLIR and annotation input files have been parsed and processed, and writes the resulting MLIR module to the output. This is interesting and useful since `firtool` performs a unique combination of input translation and annotation scattering that is not trivially reproduced with `circt-translate` and `circt-opt`. Useful for test case reduction.
=> [firtool] Add --parse-only option

include/circt-c/Dialect/MSFT.h, include/circt/Dialect/MSFT/MSFT.td, include/circt/Dialect/MSFT/MSFTAttributes.h, integration_test/Bindings/Python/dialects/msft.py, lib/Bindings/Python/MSFTModule.cpp, lib/CAPI/Dialect/MSFT.cpp, lib/Dialect/MSFT/MSFTAttributes.cpp
Also switching from `InstanceIDAttrPair` to `SwitchInstanceCase`. I wish I had thought of that obvious name before now.
=> [MSFT] [Py] Add physical location and switch instance attributes to python module

include/circt/Dialect/Calyx/CalyxControl.td, lib/Dialect/Calyx/CalyxOps.cpp, test/Dialect/Calyx/errors.mlir, test/Dialect/Calyx/round-trip.mlir
This commit adds support for the Calyx While control operation. The operation takes two arguments; a 1-bit port and a group name. The op has a single body region representing the groups to execute when the condition evaluates to true.
This is solely for IR support and does not include:
- CalyxEmitter support (unsupported for all control ops as of now)
- CompileControl control FSM generation
Note: This PR is essentially the same as the IfOp #1582, so hopefully we worked out most of the issues there!
=> [Calyx] Add IR support for calyx::WhileOp

include/circt/Dialect/FIRRTL/FIRRTLStructure.td, include/circt/Dialect/FIRRTL/FIRRTLTypes.td, lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir, test/Dialect/FIRRTL/grand-central-taps.mlir, test/Dialect/FIRRTL/grand-central.mlir, test/Dialect/FIRRTL/imconstprop.mlir, test/Dialect/FIRRTL/infer-resets-errors.mlir, test/Dialect/FIRRTL/infer-resets.mlir, test/Dialect/FIRRTL/lower-types.mlir
Add an explicit attribute for port annotations to FModule and FExtModule.  Adding a common name for port annotations, similar to instance, mem, etc, makes manipulating annotations simpler.  Although this could be folded into argattr, having it in the same format as used in other ops makes annotation scatting able to be operation type invariant, thus simplifying it.
=> [FIRRTL][NFC] Add portAnnotations to FModule and FExtModule

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLOps.h, include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/InferMemories.cpp, lib/Dialect/FIRRTL/Transforms/LowerCHIRRTL.cpp, test/Dialect/FIRRTL/infer-memories-errors.mlir, test/Dialect/FIRRTL/infer-memories.mlir, tools/firtool/firtool.cpp
This adds an implementation of the `RemoveCHIRRTL` pass called
`InferMemories`.  This pass takes the CHIRRTL memory operations, `seqmem`
and `combmem`, and transforms them into standard FIRRTL `mem`
operations.
=> [FIRRTL] Implement SFC's RemoveCHIRRTL pass

test/firtool/chirrtl.fir, tools/firtool/firtool.cpp
BlackboxMemory should run before LowerTypes, as it can create modules inputs and outputs with bundle types.  This adds a CHIRRTL integration test that checks the enable inference and memory blackboxing is working with firtool.
=> [firtool] move BlackboxMemory before LowerTypes 

include/circt/Scheduling/Algorithms.h, lib/Scheduling/SimplexSchedulers.cpp, lib/Scheduling/TestPasses.cpp, test/Scheduling/cyclic-problems.mlir, test/Scheduling/problems.mlir, test/Scheduling/simplex-errors.mlir, test/Scheduling/spo-problems.mlir
First part of a patch series that adds a heuristic scheduler for the (resource-constrained) `SharedPipelinedOperatorsProblem`. Here, I do some necessary preparations that would otherwise dilute the diffs in the following PRs with the actual implementation.
- Add parameter S to the simplex tableau.
- Keep track of variable locations in the tableau.
- Add entry point in Algorithms.h.
- Set up test pass, prepare test cases.
=> [Scheduling] [1/3] Add scheduler for shared pipelined operators problem: Preparations.

lib/Scheduling/SimplexSchedulers.cpp, test/Scheduling/spo-problems.mlir
Final part of a patch series that adds a heuristic scheduler for the (resource-constrained) `SharedPipelinedOperatorsProblem`. This implements the actual algorithm, and enables the tests.
=> [Scheduling] [3/3] Add scheduler for shared pipelined operators problem: Heuristic algorithm.

lib/Dialect/SV/Transforms/HWMemSimImpl.cpp, test/Dialect/SV/hw-memsim.mlir
Fix HWMemSimImpl bug where a wire was being procedurally assigned in RW
port code generation.  Update the associated test to reflect this
change.
The old `HWMemSimImpl` was generating logic that was assigning a net in a procedural block. Verilator nicely complains about this, e.g.:
```
%Error-PROCASSWIRE: /dev/stdin:25:5: Procedural assignment to wire, perhaps intended var (IEEE 1800-2017 6.5): '_T_1'
: ... In instance Qux.memory
25 |     _T_1 <= _T_2;
|     ^~~~
%Error-PROCASSWIRE: /dev/stdin:30:9: Procedural assignment to wire, perhaps intended var (IEEE 1800-2017 6.5): '_T_1'
: ... In instance Qux.memory
30 |         _T_1 <= Memory[rw_addr_0];
|         ^~~~
%Error: Exiting due to 2 error(s)
... See the manual and …
```
=> [HWMemSimImpl] Remove procedural assign to wire

include/circt/Dialect/Calyx/CalyxPrimitives.td, lib/Dialect/Calyx/CalyxOps.cpp, test/Dialect/Calyx/errors.mlir, test/Dialect/Calyx/round-trip.mlir
This follows a similar approach to the RegisterOp. Rather than
defining different primitives for different numbers of dimensions like
the Rust compiler, this uses a single operation to represent any
n-dimensional memory.
This generality means we can't enumerate explicit return types.
Rather, the return type is a variadic list of signless integer types.
A helper build method is provided to support this from C++ code, and a
verifier ensures everything lines up.
=> [Calyx] Add a MemoryOp primitive.

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir
Using an `int32_t` to parse vector types limits our maximum vector
length to 2147483647. We have memory length 1 higher than that maximum,
and we need to use the `int64_t` parser to support it.
=> [FIRParser] Support parsing larger vector sizes

lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp, lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp, test/Dialect/FIRRTL/SFCTests/data-taps.anno.json, test/Dialect/FIRRTL/SFCTests/data-taps.fir, test/Dialect/FIRRTL/annotations.fir, test/Dialect/FIRRTL/grand-central-taps.mlir
Add the `DataTapTests` from the Scala implementation of FIRRTL as an integration test for the FIRRTL dialect. This uncovers a few subtle breakages in the `GrandCentralTaps` introduced by changes to the annotation scattering code that happened a while back. This fixes those issues and the test ensures we don't have any regressions of this in the future.
=> [FIRRTL] Add data taps integration test, fix issues

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/InferResets.cpp, lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
Let passes use a prepopulated symbol table to resolve modules for instances.
Speedup ranges from none to ~10%.
=> [FIRRT] use a cached symbol table for resolution of modules

include/circt/Dialect/Calyx/Calyx.td, include/circt/Dialect/Calyx/CalyxPrimitives.td, lib/Dialect/Calyx/CalyxOps.cpp, lib/Dialect/Calyx/Export/CalyxEmitter.cpp, test/Dialect/Calyx/emit.mlir
- Adds emitters for RegisterOp, MemoryOp, GroupGoOp, GroupDoneOp, SeqOp, WhileOp, IfOp, EnableOp, combinational guards.
- Remove `HasParent` trait from MemoryOp since this is checked by the `Cell` trait (inherited by CalyxCell).
- Move base class for CalyxPrimitive to `CalyxPrimitives.td`.
- Helper functions for constants.
- Simple emitter for imports. Eventually we should provide a constant mapping between primitives and their respective libraries, so that only used libraries are imported (annotated in #1508).
- Adds native compiler's attributes to required ports. This is a quick-fix; search for a better solution is remarked in #1666.
- Closes #1667.
Continued progress on #1508.
For reference, emitted program in `emit.mlir`:
```mlir
import "primitives/core.futil";
import …
```
=> [Calyx] Add more operations for emission to native compiler.

include/circt/Support/LoweringOptions.h, lib/Support/LoweringOptions.cpp, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/sv-alwayscomb.mlir, test/ExportVerilog/sv-dialect.mlir, test/firtool/style.fir
This add an option to control how `always_comb` is printed by the
verilog exporter.  The default has been changed to print `always_comb`
as `always @(*)`. A lowering option `alwaysComb` has been added, similar
to `alwaysFF`, to use the old printing style.  This change is motivated
by a lack of tool support for the `always_comb` verilog construct.
=> [ExportVerilog] Add always_comb lowering option

include/circt/Support/LoweringOptions.h, lib/Support/LoweringOptions.cpp, lib/Translation/ExportVerilog/ExportVerilog.cpp, lib/Translation/ExportVerilog/ExportVerilogInternals.h, lib/Translation/ExportVerilog/PrepareForEmission.cpp, test/ExportVerilog/sv-verifLabels.mlir
Add the `verifLabels` lowering option which assigns an automatically generated label to all verification statements (assert/assume/cover) that have no label specified. This works around the issue of verification EDA tools commonly requiring all verification statements to be labeled.
This commit adds the labels of these ops to the name manager in the ExportVerilog prepass, and then uses the manager to uniquify a generic label generated for unlabeled ops in case the `verifLabels` option is set.
Fixes #1691.
=> [ExportVerilog] Add verifLabels lowering option

lib/Dialect/Calyx/Export/CalyxEmitter.cpp, test/Dialect/Calyx/emit.mlir
Adds a struct that walks the program to determine which libraries are necessary to be imported for the native Calyx compiler.
This is a very simple approach that isn't looking to optimize anything, since the # of operations and # of import is relatively small.
Closes #1675.
=> [Calyx] Emitter only imports a library if necessary.

frontends/PyCDE/src/pycde/instance.py, frontends/PyCDE/src/pycde/system.py, frontends/PyCDE/test/instances.py, include/circt-c/Dialect/MSFT.h, include/circt/Dialect/MSFT/ExportTcl.h, include/circt/Dialect/MSFT/MSFT.td, include/circt/Dialect/MSFT/MSFTAttributes.h, integration_test/Bindings/Python/dialects/msft.py, lib/Bindings/Python/MSFTModule.cpp, lib/CAPI/Dialect/MSFT.cpp, lib/Dialect/MSFT/MSFTAttributes.cpp, lib/Dialect/MSFT/TclExport/ExportQuartusTcl.cpp, test/Dialect/MSFT/location.mlir, test/Dialect/MSFT/translate-errors.mlir
A `RootedInstancePath` is just an instance path prepended with the root (aka top) module which the instance path is relative to. If we structure the placements based on this, we no longer have to walk the instance hierarchy while exporting TCL! 
This patch also removes support for locations not inside of instance switches. That use case required the design be fully elaborated which isn't really done.
=> [MSFT] Introduce `RootedInstancePath` and re-factor based on it

lib/Dialect/Calyx/CalyxOps.cpp, test/Dialect/Calyx/errors.mlir
Add verification for Cells in assignment operations after the addition of the `CellInterface` in #1695.
Addresses a TODO in #1597.
=> [Calyx] Update verification of AssignOp to include Cells.

include/circt/Dialect/HW/HWTypes.td, include/circt/Dialect/HW/HWTypesImpl.td, include/circt/Dialect/SV/SVTypes.td
Let SV dialect benefit from `HWTypes.td` refactoring as well :smile:
=> [SV] Replace copy-pasted HW types with include of HWTypes.td

include/circt/Dialect/FSM/FSM.td, include/circt/Dialect/FSM/FSMOps.h, include/circt/Dialect/FSM/FSMOps.td, include/circt/Dialect/FSM/FSMTypes.h, include/circt/Dialect/FSM/FSMTypes.td, lib/Dialect/FSM/CMakeLists.txt, lib/Dialect/FSM/FSMOps.cpp, lib/Dialect/FSM/FSMTypes.cpp, test/Dialect/FSM/basics.mlir
This is the first patch factored out from the [FSM proposal PR](https://github.com/llvm/circt/pull/1506), containing the FSM dialect operations and a rationale document. As the FSM operations tightly correlated with each other, I chose to put them together to make this PR more self-contained.
We have updated the definition of some operations after the open meeting discussion. Several major updates:
1. `fsm.state` no longer has `entry` and `exit` region. As a result, all operations executed during a transition are contained in the `action` region of `fsm.transition`.
2. A new region called `output` region is added to `fsm.state` in order to generate the state machine outputs under the current state. In this way, we can better represent the behavior "in" a state rather than only focusing on …
=> [FSM] Add FSM operations

include/circt/Dialect/FIRRTL/FIRRTLTypes.h, lib/Dialect/FIRRTL/FIRRTLTypes.cpp, test/Dialect/FIRRTL/errors.mlir
Calling `parseFIRRTLType` and `FIRRTLType::print` would currently only consider the hand-written type parsers and printers. On the other hand, using the dialect hooks `FIRRTLDialect::parseType` and `FIRRTLDialect::printType` would properly try to apply the generated parsers and printers first, and then resort to the manual implementations. This commit fixes the inconsistency by moving the call to the generated functions into `parseFIRRTLType` and `FIRRTLType::print` to ensure they are always tried first.
=> [FIRRTL] Clean up generated type parser/printer use

include/circt/Dialect/Calyx/CalyxPrimitives.td, lib/Dialect/Calyx/CalyxOps.cpp, test/Dialect/Calyx/round-trip.mlir
This operation represents an instance of a circuit primitive. The operation function is specified by the `$func` parameter. The result types of the parameter must match the natural type constraints of the provided `$func`. I.e. for binary arithmetic operations the result and input types are expected to be the identical, whereas for boolean comparison operators input types should be identical with a 1-bit wide output type.
The available operations maps to the [native Calyx logical and primitive operations](https://github.com/cucapra/calyx/blob/master/primitives/core.futil), please let me know whether you think it'd be smarter to map to the `std.comb` operations instead (or a mix of the two).
I'd like to discuss whether we should constrain the "prim" operations to be purely combinational …
=> [Calyx] Add a primitive cell instance operation

include/circt/Dialect/FIRRTL/FIREmitter.h, include/circt/InitAllTranslations.h, lib/Dialect/FIRRTL/CMakeLists.txt, lib/Dialect/FIRRTL/Export/CMakeLists.txt, lib/Dialect/FIRRTL/Export/FIREmitter.cpp, test/Dialect/FIRRTL/emit-basic.mlir
Add an emitter to export FIRRTL dialect as a .fir file. This is a first shot at such an emitter, with no output formatting options and no opinion on output code quality. Expressions for example are all simply emitted inline, which can lead to some rather nasty nesting and repetition. Supports pretty much all FIRRTL ops that the `FIRParser` would generate, except `MemoryPortOp`, `CMemOp`, `MemOp`, and `SMemOp`.
This came out of a quick hacking sprint towards a FIR reduction and register/wire isolation tool to facilitate debugging.
Tests need expansion, but quite a few real-world FIR extracts round-trip through `circt-translate --import-firrtl | circt-translate --export-firrtl` with only whitespace/int-literal-base differences.
Fixes #454.
=>  Add a FIR emitter

include/circt/Dialect/Calyx/CalyxPrimitives.td, lib/Dialect/Calyx/CalyxOps.cpp, test/Dialect/Calyx/emit.mlir, test/Dialect/Calyx/errors.mlir, test/Dialect/Calyx/round-trip.mlir
Add a `clk` port to the MemoryOp. A pleasant surprise: The primitive ports already aligned with the native compiler.
=> [Calyx] Add `clk` port to MemoryOp.

lib/Dialect/Calyx/CalyxOps.cpp, test/Dialect/Calyx/errors.mlir
Apart from simplifying the check, this provides  necessary infrastructure for #1712.
Depends on #1710 - just ignore the things in CalyxInterfaces.td .
=> [Calyx] Rewrite isPortDrivenByGroup based on Cell interface

lib/Dialect/Calyx/Export/CalyxEmitter.cpp, test/Dialect/Calyx/emit.mlir
This commit also refactors value emission for instance ops into a generic version based on the cell interface.
Depends on #1710 (posting now because i'll be gone for the evening) - just ignore the things in `CalyxInterfaces.td `.
fixes #1694.
=> [Calyx] Add emitters for library operations

include/circt/Dialect/Comb/CombOps.h, include/circt/Dialect/Comb/Combinational.td, lib/Dialect/Comb/CMakeLists.txt
Removed custom builders for `ICmpOp` and `MuxOp`, which get auto-generated when `InferTypeOpInterface.td` is present.
=> [Comb] remove redundant builders - use InferTypeOpInterface instead.

lib/Conversion/LLHDToLLVM/LLHDToLLVM.cpp, lib/Scheduling/TestPasses.cpp, test/Conversion/LLHDToLLVM/convert_process_persistence.mlir, test/Conversion/LLHDToLLVM/convert_signals.mlir, test/Conversion/LLHDToLLVM/convert_simple.mlir, test/Conversion/LLHDToLLVM/convert_wait.mlir, test/Dialect/ESI/esi-tester.cpp
I need the latest llvm for the recent python improvements.
@fabianschuiki / @maerhart  The LLHD simulator tests are all failing with: `llhd-sim: /home/jodemme/circt/llvm/llvm/lib/IR/Constants.cpp:2628: static llvm::Constant *llvm::ConstantExpr::getExtractValue(llvm::Constant *, ArrayRef<unsigned int>, llvm::Type *): Assertion `ReqTy && "extractvalue indices invalid!"' failed.`
Can one of you take a look?
=> LLVM Submodule Update

lib/Dialect/Calyx/CalyxOps.cpp, test/Dialect/Calyx/emit.mlir, test/Dialect/Calyx/errors.mlir, test/Dialect/Calyx/round-trip.mlir
If there are multiple control flow operations in a single control region, they should be nested inside a `calyx.seq` or `calyx.par`. This closes #1723.
=> [Calyx] Verify that multiple control regions are nested in a sequential or parallel operation.

include/circt/Dialect/Calyx/CalyxOps.h, lib/Dialect/Calyx/CalyxOps.cpp, lib/Dialect/Calyx/Export/CalyxEmitter.cpp, test/Dialect/Calyx/emit.mlir
Before, there was an early short-circuit to ensure that if the Value has no defining operation, we would not `TypeSwitch` on it. A block argument will not have a defining operation. This led to the problem in #1724; since `%done` is a block argument of the ComponentOp, we just short-circuited. This pull request now checks to see if the value is a BlockArgument, and emits the respective port.
Closes #1724. Also updates the assignment verification to use @mortbopet's new interface functions.
=> [Calyx] Add emission for component Block Arguments.

docs/VerilogGeneration.md, include/circt/Support/LoweringOptions.h, lib/Support/LoweringOptions.cpp, lib/Translation/ExportVerilog/ExportVerilog.cpp, test/ExportVerilog/sv-alwayscomb.mlir, test/ExportVerilog/sv-dialect.mlir, test/firtool/style.fir
We have decided that we want the default options in CIRCT to make use of
newer SystemVerilog constructs which improve the quality of output. In
the initial commit for adding a lowering option for `alwaysComb`
printing, we defaulted to print `always_comb` as `always @(*)`. This
flips the default setting and the changes the flag name to
`noAlwaysComb`, which is more in line with our desired output.
This is probably not the end of our efforts to support customized lowering of
`alwaysComb`: `always @(*)` and `always_comb` are not 100% equivalent
and have differences in their behavior at time 0.
=> [ExportVerilog] Flip the default output of `sv.alwaysComb` ops

include/circt/Dialect/Calyx/CalyxInterfaces.td, include/circt/Dialect/Calyx/CalyxOps.h, include/circt/Dialect/Calyx/CalyxStructure.td, lib/Dialect/Calyx/CalyxOps.cpp, lib/Dialect/Calyx/Export/CalyxEmitter.cpp
With the introduction of the `CellInterface`, port information is needed for more than just components.
Closes #1733.
=> [Calyx] Rename ComponentPortInfo to PortInfo.

include/circt/Dialect/HW/HWStructure.td, lib/Dialect/HW/HWOps.cpp
This speeds up verification by using a prebuilt symbol table to look up
the referenced module instead of a linear walk of the IR.  A similar
change was recently made to the FIRRTL InstanceOp in 438ffeb0.
=> [HW] Implement SymbolUserOpInterface for HW's IntanceOp

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h, lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, lib/Dialect/FIRRTL/Export/FIREmitter.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/BlackBoxMemory.cpp, lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, lib/Dialect/FIRRTL/Transforms/InferResets.cpp
This switches the Direction enum cases from `Input` and `Output` to `In`
and `Out`, which matches the text we print in the IR.  This was
suggested in a review here:
https://github.com/llvm/circt/pull/1731#discussion_r703565808
=> [FIRRTL] Rename Directions enum to In and Out

test/Dialect/HW/canonicalization.mlir
=> Bump LLVM for Canonicalizer Perf. Regression Fix

include/circt/Dialect/Seq/Seq.td, integration_test/Bindings/Python/dialects/seq.py, lib/Dialect/Seq/SeqOps.cpp, lib/Dialect/Seq/SeqPasses.cpp, test/Dialect/Seq/basic.mlir
- Allow `seq.compreg` to be unnamed.
- Fixed the python integration test
I didn't realize that `sv.reg` required a name or that `OptionalAttr<>` existed.
=> [Seq] Make `CompRegOp` name optional

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp, test/Dialect/FIRRTL/grand-central-taps.mlir
Add support for `LiteralDataTapKey`s to the `GrandCentralTaps` pass. The change to GCT itself is simple enough, merely adding additional connects that drive the constant literal to the appropriate output port.
This is the first time as far as I can tell that we have the need to call the FIR parser on some string buffer. This commit adds a dedicated `firrtl::parseIntegerLiteralExp` that takes an input `StringRef`, sets up the entire parser machinery, and then treats the input string as an integer literal.
@lattner what are your thoughts on this? Error reporting is not ideal at the moment: the parser *does* add a location passed in from the outside as location info on the operations, but syntax errors on the input string can't point back at the module that had the annotation with the bad …
=> [FIRRTL] Implement LiteralDataTapKey support

include/circt/Dialect/MSFT/MSFT.td, include/circt/Dialect/MSFT/MSFTOps.h, include/circt/Dialect/MSFT/MSFTOps.td, lib/Dialect/MSFT/CMakeLists.txt, lib/Dialect/MSFT/MSFTDialect.cpp, lib/Dialect/MSFT/MSFTOps.cpp, test/Dialect/MSFT/module_instance.mlir
`msft.instance` is intended to be like `hw.instance` but with headroom for MSFT-specific additions. It will lower to `hw.instance`. This just creates the op.
Step one of #1755 .
=> [MSFT] Introduce `InstanceOp`

include/circt/Dialect/MSFT/MSFTPasses.td, include/circt/InitAllPasses.h, lib/Dialect/MSFT/CMakeLists.txt, lib/Dialect/MSFT/MSFTPasses.cpp, test/Dialect/MSFT/module_instance.mlir
Add a very straight-forward lowering of `msft::InstanceOp` to `hw::InstanceOp`. Part 2 of #1755.
=> [MSFT] Lower msft.instance to hw.instance

lib/Dialect/Calyx/Export/CalyxEmitter.cpp
Twines are not safe to store on the stack. This caused undefined
behaviour which lead to an issue where it would print `group` twice
depending on the compiler settings.
```
// Correct:
comb group Group2
// Incorrect:
comb group Group2comb group
```
This issue was noted on the forums here: https://llvm.discourse.group/t/calyx-test-failure/4261
=> [Calyx] Fix twine usage in emitter

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td, include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/annotations.fir, test/Dialect/FIRRTL/canonicalization.mlir, test/Dialect/FIRRTL/parse-basic.fir
Part of #1758, move name dropping later in the pipeline.  This makes the parser simpler, but more importantly, keeps names around until after we've processed annotations, some of which produce better output or might require the original names.
=> [FIRRTL] Move name dropping later in the pipeline

include/circt/Dialect/Calyx/CalyxInterfaces.td, include/circt/Dialect/Calyx/CalyxOps.h, include/circt/Dialect/Calyx/CalyxPrimitives.td, lib/Dialect/Calyx/CalyxOps.cpp, lib/Dialect/Calyx/Export/CalyxEmitter.cpp, test/Dialect/Calyx/errors.mlir
Adds support for attributes on primitive ports. No emission is necessary for the ports of a primitive. Calyx primitive attributes are already supported as well. This closes #1744.
I've also lessened the restriction for port driving to `returns success if any input port is driven`. I think this is sufficient for now.
#1763 discusses cleanup for port access functions.
=> [Calyx] Add support for primitive port attributes.

lib/Dialect/Comb/CombFolds.cpp, test/Dialect/Comb/canonicalization.mlir
Fixes one of the patterns described in #1624, where a common pattern is the or'ing of two values that only have bits set in non-overlapping positions.
This is the first time I've contributed to this codebase, and it's been a long time since I've written C++, so I'm happy to make any changes that are requested.
The approach I took was to simultaneously iterate over the operands of both concats in a left-to-right fashion, resolving the result of the `or`, but it got a bit tricky due to having to split up the constant 0's into narrower constants when the operand bit ranges don't align between the two concats. Please let me know if there's a better or simpler approach to this, since my `while` loop ended up with many different edge cases and it doesn't seem the most elegant.
I also realized …
=> [Comb] Merge ors of concats with constant operands.

integration_test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir, integration_test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir.anno.json, integration_test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir.extract.anno.json
Copy the body of the Grand Central Views test over to an integration test.  Run the `-verilog` and `-split-verilog`/extraction output through Verilator `--lint-only` to type check this.  By type-check, I primarily mean assert that the following two things hold:
1. All interfaces are defined
2. All XMRs are correct (indicating that XMRs are using the correct instance names)
=> [FIRRTL] Verilator type-check GCT Views Test

lib/Dialect/ESI/ESIPasses.cpp, lib/Dialect/HW/HWOps.cpp
Closes #1775 .
Also allows us to have the `hw::InstanceOp` verifier not ignore `hw::HWModuleExternOp`s.
=> [ESI] Make instances match module declarations

include/circt/Dialect/Calyx/CalyxOps.h, include/circt/Dialect/Calyx/CalyxPrimitives.td, lib/Dialect/Calyx/CalyxOps.cpp, test/Dialect/Calyx/errors.mlir, test/Dialect/Calyx/round-trip.mlir
This adds a combinational trait to Calyx operations. We can throw this on all non-memory operations for now, since they are all combinational. Eventually we'll need to split this off. Closes #1739. 
I also fixed a bug where it was considering a memory load as a store, since the address ports are used when both storing and loading to a MemoryOp. A test is added to verify this no longer occurs.
=> [Calyx] Add combinational trait.

docs/FIRRTLAnnotations.md, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
Prefix the attribute `DesignUnderTest` with `firrtl` since it defines a `FIRRTL` specific property. 
Update the docs and tests accordingly.
Followup to https://github.com/llvm/circt/pull/1785
=> [LowerToHW] Update attribute DesignUnderTest to firrtl.DesignUnderTest [NFC]

include/circt/Dialect/MSFT/MSFT.td, include/circt/Dialect/MSFT/MSFTOps.td, lib/Dialect/HW/HWOps.cpp, lib/Dialect/MSFT/MSFTOps.cpp, test/Dialect/HW/errors.mlir, test/Dialect/MSFT/opt-errors.mlir
Remove a lot of assertions and checks that are validated by the ODS and `verifyInstanceOp` function. Subsequent tests are added.
Edit: There already exists a test for non-existent modules in the HW dialect. I removed my test case. This closes #1779.
Edit 2: This also closes #1790.
=> [HW] [MSFT] Remove unnecessary assertions in `getReferencedModule` and add SymbolOpUserInterface to MSFT InstanceOp.

include/circt/Dialect/HW/ModuleImplementation.h, lib/Dialect/HW/CMakeLists.txt, lib/Dialect/HW/HWOps.cpp, lib/Dialect/HW/ModuleImplementation.cpp
To enable re-use in other dialects.
=> [HW] [NFC] Extract out printing/parsing functions for modules

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/infer-widths.mlir, test/Dialect/FIRRTL/test.mlir
Will close #515.
This PR replaces StdIntCastOp/AnalogInOutCastOp/AsPassivePrimOp/AsNonPassivePrimOp with UnrealizedConversionCastOp.
This includes changes of InferWidth and LowerTypes.  
It makes conversions much simpler but also verification weak so maybe it is better to left as it is.
=> [FIRRTL] Replace some lowerings with UnrealizedConversionCastOp

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, test/Dialect/FIRRTL/imconstprop.mlir
There was nothing forcing these ports to be overdefined before, so constants could leak through.
The undefined flag gets propagated to the instance port moments later.
One could remove the don't touch check in visitConnect now, but it's not clear if checking the attributes is cheaper than merging some lattice values.
=> [FIRRTL] Mark don't touch module ports as overdefined

docs/FIRRTLAnnotations.md, include/circt/Dialect/FIRRTL/InstanceGraph.h, include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/InstanceGraph.cpp, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/PrefixModules.cpp, test/Dialect/FIRRTL/prefix-modules.mlir, tools/firtool/firtool.cpp
This pass looks for modules annotated with the
`NestedPrefixModulesAnnotation` and prefixes the names of all modules
instantiated underneath it.  This pass will duplicate a module to rename
only the modules instantiated in the hiearchy rooted at the annotated
module.  If there are no remaining instances of the original module, it
will be removed.
The supported `firrtl.module` annotation is:
```
{
class = "sifive.enterprise.firrtl.NestedPrefixModulesAnnotation",
prefix = "MyPrefix_",
inclusive = true
}
```
If `inclusive` is true, it will also apply the prefix to the annotated
module.
=> [FIRRTL] Add PrefixModules pass

include/circt/Dialect/HW/HWStructure.td, include/circt/Dialect/MSFT/MSFT.td, include/circt/Dialect/MSFT/MSFTOps.td, lib/Dialect/MSFT/MSFTDialect.cpp, lib/Dialect/MSFT/MSFTOps.cpp, lib/Dialect/MSFT/MSFTPasses.cpp, test/Dialect/MSFT/module_instance.mlir
Adds a moduleop to the MSFT dialect. For now, it's mostly like `hw.module` but adds `parameters` to represent the specific parameterization of a parameterized module. Also necessarily adds a `msft.output` since `hw.output` expects to be in a `hw.module`. 
Step 3 of #1755.
=> [MSFT] Add `MSFTModuleOp`

lib/Conversion/StandardToHandshake/StandardToHandshake.cpp, test/Conversion/StandardToHandshake/test_call.mlir
To preface this PR, let's start with an example. Take the following std input:
```mlir
func @f(%a : i32) -> i32 {
return %a : i32
}
func @top(%a : i32) -> i32 {
%a2 = call @f(%a) : (i32) -> i32
return %a2 : i32
}
```
this currently gets lowered to:
```mlir
module  {
handshake.func @f(%arg0: i32, %arg1: none, ...) -> (i32, none) {
%0 = "handshake.merge"(%arg0) : (i32) -> i32
handshake.return %0, %arg1 : i32, none
}
handshake.func @top(%arg0: i32, %arg1: none, ...) -> (i32, none) {
%0 = "handshake.merge"(%arg0) : (i32) -> i32
%1:2 = "handshake.fork"(%0) {control = false} : (i32) -> (i32, i32) // invalid fork, arg0 is single use
%2 = handshake.instance @f(%1#0) : (i32) -> i32
"handshake.sink"(%2) : (i32) -> () // invalid sink, %2 is used by handshake.return
handshake.return %2, %arg1 : i32, …
```
=> [Handshake] Fix lowering of std.CallOp to handshake.InstanceOp

include/circt/Dialect/SV/SVPasses.h, include/circt/Dialect/SV/SVPasses.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/SV/Transforms/CMakeLists.txt, lib/Dialect/SV/Transforms/HWExportModuleHierarchy.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/SV/hw-export-module-hierarchy.mlir, tools/firtool/firtool.cpp
This adds a pass that collects the full module hierarchy into a JSON
string, which is then exported as part of an sv.verbatim op. The pass
collects two module hierarchies, one for the firrtl.mainModule and one
for the firrtl.DesignUnderTest. This matches SiFive's JSON file format
for the module hierarchy.
The pass can be enabled in firtool by providing the
--export-module-hierarchy option.
I wasn't sure what the best place was to put this pass, so I've added this to the `SVPasses`/`SV/Transforms`, since it operates on the `hw` dialect and exports an `sv.verbatim` op. I could see putting this under `FIRRTL`, since it's very specific to FIRRTL and even relies on the `firrtl.mainModule` and `firrtl.DesignUnderTest` attributes (annotations), despite operating only on the `hw` dialect. Let me …
=> [SV] Add ExportModuleHierarchy pass.

lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
No functional change, but a major step in the debug-ability of the pass. Previously, there was a discrepancy between the # of args of the Handshake FuncOp and the inlined body of the source FuncOp. This meant that any attempt at dump'ing the IR during conversion would crash, due a mismatch between the type signature of the handshake funcop and its entry block arguments.
This commit postpones adding the control argument to (and modifying the type signature of) the handshake funcOp until end of conversion.
=> [Handshake] Postpone adding ctrl arg to handshake::FuncOp until end of conversion

lib/Dialect/ESI/ESIPasses.cpp
This fixes a compilation error in the integration test where ESI was not
switched to use a new dedicated ParameterAttr introduced in 471e60ce.
=> [ESI] Use new ParameterAttr for module parameters

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/SV/Transforms/HWMemSimImpl.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/SV/hw-memsim.mlir
Fixes #1757.
This PR changes the lowering for FIRRTL memories.  Previously, each write port on the same clock would be emitted into a separate always block.  This resulted in Verilog that behaviorally described "undefined" write-under-write behavior.  I.e., it described a memory where any write port could "win" in a write collision (where two ports write to the same address) and would likely have written an `x` to the memory in simulation.
FIRRTL memories have "port order" write-under-write behavior for ports on the same clock.  This means that if multiple ports on the same clock write to the same memory address, the highest numbered port will win.  In effect, this is explicitly encoding an ordering which a synthesis tool must respect.  This was then producing formal equivalence …
=> [FIRRTL][HW] Add Support for "Port Order" Write-Under-Write to HWMemSimImpl, Use for FIRRTL Lowering

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp, test/Dialect/FIRRTL/inliner.mlir
The inliner removes any module which is left uninstantiated after all
inlining is complete.  It was mistakenly deleting non-module operations
because there was no instance of them.  For example, an `sv.verbatim`
operation would be deleted since it is not the sort of thing that could
be instantiated.  This adds a check that the operation it is considering
for deletion is in fact a module operation before removing it.
=> [FIRRTL][Inliner] Don't delete unknown ops when deleting dead modules

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir
The LowerToHW pass will emit an error for any unrecognized operation it
finds in the Circuit while lowering.  We need to be able to pass
through `sv.verbatim` operations which are created during metadata
generation.  The `sv.interface` operation is already passed directly
through when lowering, and this change extends this to include
`sv.verbatim` operations.  If we find that there are too many operations
being white-listed, we could modify it to pass-through anything by
default.
=> [FIRRTL][LowerToHW] Pass through `sv.verbatim` ops

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
This commit adds a partial lowering infrastructure to the SCFToCalyx pass. Similarly to `StandardToHandshake`, `SCFToCalyx` structures its conversion into multiple distinct stages. Some of these stages perform IR modifications instead of IR replacements. The partial lowering infrastructure allows for writing passes which are driven by the conversion infrastructure, but relaxes the requirement of "if a conversion pattern matches, the matched operation should be replaced or erased".
`FuncOpPartialLoweringPattern`s are patterns which intend to match on `FuncOp`s and then perform their own walking from these. These patterns are initialized with access to the `ComponentLoweringState` for corresponding component of the matched `FuncOp`.
=> [SCFToCalyx] Add partial lowering infrastructure [4/13]

include/circt/Dialect/StaticLogic/StaticLogic.td, lib/Dialect/StaticLogic/StaticLogicOps.cpp, test/Dialect/StaticLogic/errors.mlir, test/Dialect/StaticLogic/round-trip.mlir
https://llvm.discourse.group/t/rfc-representing-pipelined-loops/4171/1
for more discussion.
This defines the operation's syntax more or less as discussed,
including round-trip tests for the four running examples we've had.
In order to reduce test churn, the existing PipelineOp and the
StandardToStaticLogic pass are left untouched for now. Ultimately, the
new pipeline operation could replace the existing PipelineOp.
=> [StaticLogic] Add new PipelineWhile operation.

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
This commit adds support for building `ComponentOp`'s and  most combinational operators from the `std` dialect. The combinational operators are built through the `buildLibOp` function. Here, we instantiate a new Calyx primitive, create a combinational group, and assign the input ports of the calyx primitive with the operands of the source operation.
No new tests; `ComponentOp`s are required to have a non-empty control schedule, and we're still a few commits from that.
=> [SCFToCalyx] Add support for building combinational logic [5/13]

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
This commit builds registers for the return values of a function. Additionally, it also introduces the concept of Scheduleables. These are things which can register themselves to be scheduled sequentially based on the control-flow of the source program (at this point, only `GroupOp`s).
=> [SCFToCalyx] Build registers for function return values [6/13]

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_simple.mlir
This commit builds a control schedule by traversing the CFG of the function and associating this with the previously created groups. For simplicity, the generated control flow is expanded for all possible paths in the input DAG. This elaborated control flow will later be reduced in the various control schedule simplification patterns.
=> [SCFToCalyx] Build an execution schedule by CFG traversal [7/13]

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_controlflow.mlir, test/Conversion/SCFToCalyx/errors.mlir
This commit adds support for `std::BranchOpInterface` and `scf::WhileOp` operations. Control flow operations are supported by argument parsing through registers; this being basic block arguments and while iter args.
=> [SCFToCalyx] Support if- and while control-flow operations [8/13]

include/circt/Dialect/FIRRTL/FIRParser.h, include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h, include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td, include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp, lib/Dialect/FIRRTL/Import/FIRAnnotations.h, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, test/Dialect/FIRRTL/annotations.mlir, tools/firtool/firtool.cpp
Add a pass to handle all annotation scattering.  This pass is table driven, with customizable scattering per-annotation-class.  When this is fleshed out, it will replace the annotation handling code in the parser.
Right now, this supports a couple testing annotation to make test cases against.
Until this is live in the pipelines, add an option to the parser to bypass annotation handling and scattering to enable testing.
=> Annotation Scattering and trivial processing Pass

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_controlflow.mlir
Inlines Calyx ExecuteRegionOp operations within their parent blocks. An execution region op (ERO) is inlined by:
1. add a sink basic block for all yield operations inside the ERO to jump to
2. Rewrite scf.yield calls inside the ERO to branch to the sink block
3. inline the ERO region
=> [SCFToCalyx] Support scf.execute_region operations [9/13]

include/circt/Dialect/Calyx/CalyxControl.td, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_controlflow.mlir, test/Conversion/SCFToCalyx/convert_simple.mlir
The `compiledGroups` attribute is only used during the (currently incomplete) lowering process of Calyx IR to signify which groups are attributed to the calyx.enable during compilation. This maintains the invariant that all Group symbols are referenced throughout the life time of a Calyx program. This PR adds another builder to skip initializing it.
Closes #1844.
=> [Calyx] [SCFToCalyx] Add EnableOp builder which doesn't require the `compiledGroups` attribute.

include/circt-c/Dialect/HW.h, integration_test/Bindings/Python/dialects/msft.py, integration_test/Bindings/Python/dialects/rtl.py, lib/Bindings/Python/HWModule.cpp, lib/Bindings/Python/circt/dialects/_hw_ops_ext.py, lib/CAPI/Dialect/HW.cpp
Closes #1810 
The changes to `hw.module` and `hw.instance` make them incompatible with `msft.module` and `msft.instance` as far as the python bindings are concerned. I'm not sure what I want to do here, though I'll likely update the msft variants. I've marked that test as `xfail` for the moment.
=> [Python] Fix Python Bindings

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_controlflow.mlir, test/Conversion/SCFToCalyx/convert_simple.mlir
This commit introduces various patterns which cleans up and simplifies the control schedule and removes unused `CombGroupOp` groups.
=> [SCFToCalyx] Add simplification and cleanup patterns [10/13]

include/circt/Dialect/Calyx/CalyxControl.td, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Dialect/Calyx/Export/CalyxEmitter.cpp
Add helper methods for the `IfOp`. The `IfOp` inherits from `CalyxContainer`, which has the `SingleBlock` trait, so it should be guaranteed that each region has a single block. I've renamed the getters to remain in line with the `getBody` helper for other Calyx containers.
Closes #1866.
=> [Calyx] [SCFToCalyx] Add helper methods for IfOp.

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_controlflow.mlir, test/Conversion/SCFToCalyx/convert_simple.mlir
This commit introduces combinational group inlining. The conversion strategy of SCFToCalyx is to create a distinct CombGroupOp for each combinational operator in the source program. This implies that the created CombGroupOp is analogous to the SSA value which the original operation represented.
In Calyx, a source operand for a `calyx.assign` must be fully defined within the group that performs the assignment. This means that the source operand is either the output of a sequential component, or a fully defined combinational assignment chain. This commit achieves the latter by recursively inlining use-def chains op combinational logic, by backtracking through the CombGroupOps which generated the combinational assignments of the original program.
=> [SCFToCalyx] Add combinational group inlining [11/12]

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_memory.mlir
This commit adds support for `memref::AllocOp, LoadOp, StoreOp`.
All index types are converted to a fixed-width integer (i32). This is necessary due to the lack of a bitwidth inference pass. Upon an index-typed value being used as a memory address input, the address value is truncated to the width of the memory port.
=> [SCFToCalyx] Support memref operations [12/12]

include/circt/Analysis/DependenceAnalysis.h, lib/Analysis/CMakeLists.txt, lib/Analysis/DependenceAnalysis.cpp, lib/Analysis/TestPasses.cpp, test/Analysis/dependence-analysis.mlir, tools/circt-opt/CMakeLists.txt, tools/circt-opt/circt-opt.cpp
This is currently a simple function that traverses pairs of Affine
memory access operations and uses the upstream
`checkMemrefAccessDependence` function. The results are returned in a
convenient data structure that can inform scheduling decisions. A test
pass is added, which outputs the results as attributes for
verification.
=> [Analysis] Add a DependenceAnalysis for checking memory accesses.

include/circt/Dialect/Calyx/CalyxStructure.td, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
Add some builders that don't require a guard. This diminishes the need to have `Value()`. For the AssignOp builder, we verify type constraints with `SameTypeConstraint<"dest", "src">` trait.
Closes #1855.
=> [Calyx] [SCFToCalyx] Add builders with no guard.

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td, include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, include/circt/Dialect/FIRRTL/FIRRTLOps.h, include/circt/Dialect/FIRRTL/FIRRTLTypes.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Conversion/FIRRTLToHW/errors.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/SFCTests/async-reset-errors.mlir, test/Dialect/FIRRTL/inliner.mlir
Have the verifier of `firrtl.regreset` check that any async reset value is a constant literal (or aggregate thereof). On the Scala side, this is checked in `CheckResets`.
*Note:* Had to open a new PR for this -- GitHub somehow screwed up the other branch ("cannot lock ref 'refs/heads/check-async-reset-const': reference already exists"). Thanks Microsoft.
=> [FIRRTL] Validate reg async reset value is constant at LowerToHW Time

include/circt/Dialect/Handshake/Visitor.h, lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, test/Conversion/HandshakeToFIRRTL/test_index_cast.mlir
zexti and trunci operations generate handshake components which wrap around FIRRTL `pad` and `bits` operations. The builder for each of these ops is used to support `index_cast`, which pads or truncates an input type compared to the fixed index-width (64 bits).
Notably, this introduces a bug/new issue wrt. how submodules are named; currently, this is fully dependent on the result type of the operand that is being converted. With these unary ops, the operand type also matters, and must be factored into the name of the submodule.
=> [HandshakeToFIRRTL] Add support for `index_cast`, `zexti` and `trunci` ops

include/circt/Dialect/Calyx/Calyx.td, include/circt/Dialect/Calyx/CalyxStructure.td, lib/Dialect/Calyx/CalyxOps.cpp, test/Conversion/SCFToCalyx/convert_controlflow.mlir, test/Conversion/SCFToCalyx/convert_simple.mlir, test/Dialect/Calyx/compile-control.mlir, test/Dialect/Calyx/emit.mlir, test/Dialect/Calyx/errors.mlir, test/Dialect/Calyx/go-insertion.mlir, test/Dialect/Calyx/remove-groups.mlir
Switches the GroupGoOp, GroupDoneOp, and AssignOp to match the native compiler representation.
```mlir
// Before
calyx.assign %dest = %src, %guard ? : i8
calyx.group_done %src, %guard ? : i1 
%result = calyx.group_go %src, %guard ? : i1
```
```mlir
// After
calyx.assign %dest = %guard ? %src : i8
calyx.group_done %guard ? %src : i1
%result = calyx.group_go %guard ? %src : i1
```
I think Mike brought up a good point in #1873. We're still pretty dependent on the native compiler, so it seems right to keep the IRs as similar as possible. Note that placing the (optional) guard last in the arguments is necessary; otherwise the compiler assumes the source is the guard and wants to mix the types up. Not a huge deal, just requires being careful when writing out the logic for parsing.
Closes #1873; …
=> [Calyx] Use native compiler representation for guarded assignments and ports.

lib/Dialect/Comb/CombFolds.cpp, test/Dialect/Comb/canonicalization.mlir
Fixes the second half of #1624.
This simplifies mux expressions that have constant values for both the true and false cases by pushing the mux condition down to the individual bits of the inputs, combining the results with a concat op. This takes advantage of the simpler folds/canonicalization patterns that have already been implemented for muxes.
Separately, I also added a canonicalization pattern for the special case of `mux(cond, 0, 1'h1)`, which is equivalent to `~cond`. This helps with matching other patterns that look for bitwise not operations.
In the simplest case, it should simplify expressions like `mux(cond, 2'h2, 2'h0) -> concat(mux(cond, 1'h1, 1'h0), 1'h0) -> concat(cond, 1'h0)`. More generally, the end result should be the concatenation of one of four possible values: 0, 1, …
=> [Comb] Canonicalize mux with constant inputs

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, test/Dialect/FIRRTL/expand-whens.mlir
[This has two commits which can be reviewed separately, the first one is NFC code shuffling]
When ExpandWhens sees the the following code, it *should* produce the
following:
```firrtl
out <= in0
when p0 :
when p1 :
out <= in1
```
```firrtl
out <= mux(p0, mux(p1, in1, in0), in0)
```
There was a mistake in the code where it would only track previously
driven values from one level of outer scope.  This means that when
producing the inner mux, `mux(p1, in1, in0)`, it never found that `in0`
was previously driven to `out`, and never formed a mux with the `in1`
connection:
```firrtl
out <= mux(p0, in1, in0)
```
To solve this, we had to make sure that the all scopes stored previously
driven values in the same hashtable.  This allowed the code to find the
previously driven value from all …
=> [FIRRTL] Fix expand whens bug

lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, test/Conversion/HandshakeToFIRRTL/simple_addi.mlir, test/Conversion/HandshakeToFIRRTL/test_branch.mlir, test/Conversion/HandshakeToFIRRTL/test_buffer.mlir, test/Conversion/HandshakeToFIRRTL/test_cmerge.mlir, test/Conversion/HandshakeToFIRRTL/test_conditional_branch.mlir, test/Conversion/HandshakeToFIRRTL/test_constant.mlir, test/Conversion/HandshakeToFIRRTL/test_fork.mlir, test/Conversion/HandshakeToFIRRTL/test_index_cast.mlir, test/Conversion/HandshakeToFIRRTL/test_lazy_fork.mlir, test/Conversion/HandshakeToFIRRTL/test_memory.mlir, test/Conversion/HandshakeToFIRRTL/test_merge.mlir, test/Conversion/HandshakeToFIRRTL/test_mux.mlir, test/Conversion/HandshakeToFIRRTL/test_sink.mlir, test/Conversion/HandshakeToFIRRTL/test_store.mlir
This commit introduces modifications to how FIRRTL submodule names are generated. Most importantly, submodules are now generated based on both their input- and output types.
A downside of this approach is that components with a large number of i/o ports will have rather verbose names. If we see this as a problem, we can solve this with a few special cases. However, the proposed approach in this commit attempts to provide a general naming approach and avoid special cases.
=> [HandshakeToFIRRTL] Rework submodule name generation

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, tools/firtool/firtool.cpp
Since this is creating verbatim operations instead of emitting files
directly, `create` makes more sense as a verb.
Since the metadata created is specific to SiFive build flows,  this
renames the pass to make it clear that it is not generically useful.
This leaves the pass on by default since the pass will only do anything
if the correct annotations exist.
This change was suggested here:
https://github.com/llvm/circt/pull/1875#discussion_r716070526
=> [FIRRTL] Rename EmitMetadata to CreateSiFIveMetadata

include/circt/Dialect/Calyx/CalyxControl.td, lib/Dialect/Calyx/CalyxOps.cpp, test/Dialect/Calyx/errors.mlir
Adds a simpler verifier for `ParOp` that only looks within the given body (and not nested regions). Anything stricter requires more careful thinking. For example, this should be OK:
```
calyx.par {
calyx.if {
calyx.enable @G
} else {
calyx.enable @G
}
}
```
Similarly, nested sequential operations containing the same `EnableOp`s in a ParOp may be valid if their timing is OK. Therefore, I've decided to keep this very loose for now.
=> [Calyx] Add verifier for ParOp.

lib/Dialect/FIRRTL/Transforms/InferResets.cpp, test/Dialect/FIRRTL/SFCTests/remove-reset.fir, test/Dialect/FIRRTL/infer-resets-errors.mlir
Augment `InferResets` to error if any abstract reset ports remain after it runs.  (Just looking for abstract reset ports should be sufficient.)
Fixes #779.
A number of tests has abstract reset ports in them. Remove these in the first commit (which I'll land separately).
=> [FIRRTL] Error on Uninferred Abstract Reset

include/circt/Scheduling/Problems.h, lib/Scheduling/Problems.cpp, lib/Scheduling/TestPasses.cpp, test/Scheduling/modulo-problem-errors.mlir, test/Scheduling/modulo-problems.mlir
This PR adds the problem model for modulo scheduling with fully-pipelined shared operators.
This is (I think) the obvious way to do it in the existing `Problem` hierarchy. However, I'm no longer entirely happy with my "distributed" checkers/verifier approach. To that end, I have an alternative idea with (hopefully) less code duplication, which I'll explore in a follow-up PR.
=> [Scheduling] Define modulo scheduling problem.

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_memory.mlir
This commit adds support for `index`-typed operands and return values.
=> [SCFToCalyx] Add support for index in- and output types

lib/Dialect/FIRRTL/Transforms/InferResets.cpp
Fix two issues in InferResets:
1.  References into a dense map that may get invalidated while being live by inserts being done into the map through subsequent accesses.
2.  Vectors being `std::move`d out of potentially multiple times. This is problematic because the move may leave an invalid vector behind which is no longer safe to access again. The fix properly uses a `std::swap` to move data out of the vector and leave an empty one behind.
=> [FIRRTL] Fix use of invalidated iterators in InferResets

include/circt/Dialect/FIRRTL/CircuitNamespace.h, lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
Move the `CircuitNamespace` helper struct from the current Grand Central source files into a public header file. This acts like a symbol table specifically for `firrtl.circuit` ops and is useful for avoiding name conflicts when generating additional modules.
=> [FIRRTL] Make CircuitNamespace helper public

include/circt/Dialect/Calyx/CalyxControl.td, lib/Dialect/Calyx/CalyxOps.cpp, test/Dialect/Calyx/canonicalization.mlir
This adds a pattern for when `then` and `else` regions are both `ParOp`s. It also takes into consideration the parent region of the `IfOp`, since we don't want to unintentionally change the behavior when pulling out `EnableOp`s. 
I also do not touch anything that's not immediately within the given `ParOp`'s body; doing so may also change the behavior of the program.
The case where the `then` and `else` regions are different, e.g. `SeqOp` and  `ParOp`, should never pull out an `EnableOp`; it will always produce worse code, e.g.
```mlir
calyx.seq {
calyx.if {
calyx.par { ... calyx.enable @A }
} else {
calyx.seq { ... calyx.enable @A } 
}
}
// Choice A: Place it in a SeqOp.
calyx.seq {
calyx.if {
calyx.par { ... }
} else {
calyx.seq { ... } 
}
calyx.enable @A // Now, it is no longer …
```
=> [Calyx] Add enhancements to common tail elimination for `IfOp`.

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_memory.mlir
This commit adds support for `memref` function arguments. This should greatly expand the number of meaningful accelerators which we are able to generate through `SCFToCalyx`.
The signature of the top-level component is rewritten to include in- and output ports expected for the memory. These ports are written into a new `CalyxMemoryPorts` structure. This, alongside rewriting memory getter/setters to use `CalyxMemoryInterface` allows the external memories to be used like `calyx::MemoryOp`s within the remainder of the code.
The implementation assumes identical semantics for external memories as for Calyx memories, namely that reads are combinational.
Depends on #1896.
=> [SCFToCalyx] Add support for `memref` function arguments

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir, test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir
We had some hardcoded logic to allow `sv.verbatim` and `sv.interface`
operations to be copied from a `CircuitOp` when lowering to HW.
This change makes this more generic by automatically passing through any
operation which (recursively) does not have any FIRRTL type or
operation.
This change only affects operations which appear in the CircuitOp's
body.  Operations appearing in a ModuleBody are handled by
`handleUnloweredOp`.
Fixes #1838
=> [FIRRTL][LowerToHW] Passthrough any operation not using FIRRTL types

frontends/PyCDE/src/pycde/instance.py, frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/src/pycde/system.py, frontends/PyCDE/test/instances.py
Keep all the raw CIRCT module ops in `pycde.System`. Enables the same PyCDE
modules to be used multiple Systems (theoretically, unsupported/untested for
now). It is also the only class which runs CIRCT passes, so it knows when to
invalidate the symbol cache. The symbol cache is the only data structure which
holds CIRCT module ops. Increases memory safety.
=> [PyCDE] Use `System` to track raw CIRCT module ops

include/circt/Dialect/Calyx/CalyxControl.td, include/circt/Dialect/Calyx/CalyxStructure.td, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Dialect/Calyx/Transforms/CompileControl.cpp
Adds builders to initialize bodies for `IfOp`, `WhileOp`, `CombGroupOp`, `GroupOp`, `WiresOp`, and `ControlOp`. This also removes their default builders, since it would be odd to want a Calyx container without a body. The rest is necessary clean-up in SCFToCalyx and CompileControl. Closes #1884.
=> [Calyx] [SCFToCalyx] Initialize bodies upon build.

docs/RationaleComb.md, include/circt/Dialect/Comb/Combinational.td, integration_test/EmitVerilog/lint.mlir, lib/Dialect/Comb/CombOps.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Conversion/FIRRTLToHW/zero-width.mlir, test/Conversion/LLHDToLLVM/convert_bitwise.mlir, test/Dialect/Comb/canonicalization.mlir, test/Dialect/HW/basic.mlir, test/Dialect/HW/bitwise.mlir, test/Dialect/HW/canonicalization.mlir, test/Dialect/LLHD/Export/verilog_bitwise.mlir, test/ExportVerilog/hw-dialect.mlir, test/ExportVerilog/verilog-basic.mlir, test/firtool/firtool.fir
Removes the result type from the comb.concat type signature since it can be
deduced from the inputs.
For example, this previous signature:
```mlir
%0 = comb.concat %false, %b : (i1, i4) -> i5
```
is simplified to:
```mlir
%0 = comb.concat %false, %b : i1, i4
```
Address #1623.
=> [Comb] Simplify comb.concat signature to omit result type

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
Lower `firttl::FVectorType` to `hw::ArrayType` in `LowerToHW` pass. 
It was leaking the `!firrtl.vector` types to the `hw` dialect.
=> [FIRRTLToHW] Lower vector types correctly. NFC.

.github/workflows/buildAndTest.yml, .gitignore, docs/PythonBindings.md, lib/Bindings/Python/pyproject.toml, lib/Bindings/Python/setup.py
This allows users to `pip install lib/Bindings/Python`. Similarly,
this supports `pip wheel lib/Bindings/Python`. The script generally
follows https://github.com/llvm/torch-mlir/pull/256, with some tweaks
that are specific to CIRCT's CMake choices (e.g. using an external
projects unified build).
=> [Python] Add and document setup.py script for Python bindings.

include/circt/Dialect/FIRRTL/FIRParser.h, lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp, lib/Dialect/FIRRTL/Import/FIRAnnotations.h, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/firtool/firtool.fir, test/firtool/firtool.fir.omir.anno.json, tools/firtool/firtool.cpp
This adds support for reading in Object Model 2.0 JSON via `firtool`.  This adds a `--omir-file <file>` option to `firtool` that will parse this into an `OMIRAnnotation` on the FIRRTL circuit. No further processing is done (no "tracker" annotations are scattered to things in the circuit).
This is just intended as preliminary support which (after landing scattering of trackers) will then enable some parallel hacking on OM 2.0 stuff.
For those who have never heard of this, OM 2.0 is the second incarnation of a mechanism that SiFive uses to add a graph of metadata to the circuit.  The graph consists of flat `OMNode`s (which here are represented as an `ArrayAttr`) which may include references to other nodes.  As this evolves in CIRCT, I expect that this will become a full-fledged dialect. …
=> Object Model 2.0, Part 1: Read in OM 2.0

frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/test/compreg.py, frontends/PyCDE/test/instances.py, frontends/PyCDE/test/module_naming.py, frontends/PyCDE/test/polynomial.py, frontends/PyCDE/test/syntactic_sugar.py, frontends/PyCDE/test/verilog_readablility.py
Adds a setter on the generator argument which sets the value of the output
port. Also provides a `set_all_ports` method for programatic access and easy
legacy conversion.
There are two advantages of this: (1) Symbolic port names vs. string port
names. (2) More importantly, exceptions are raised when the code tries to set an
output port value, which provides a traceback to the relevant line.
=> [PyCDE] Move from returning output values to setting them

lib/Dialect/ESI/ESITypes.cpp, lib/Dialect/FIRRTL/FIRRTLAttributes.cpp, lib/Dialect/FIRRTL/FIRRTLTypes.cpp, lib/Dialect/FSM/FSMTypes.cpp, lib/Dialect/HW/HWAttributes.cpp, lib/Dialect/HW/HWTypes.cpp, lib/Dialect/LLHD/IR/LLHDTypes.cpp, lib/Dialect/MSFT/MSFTAttributes.cpp, lib/Dialect/SV/SVTypes.cpp
Parser functions no longer take an `mlir::MLIRContext *` parameter, so all existing parser functions required updating.
The MLIR parser change is [here](https://github.com/llvm/llvm-project/commit/fb093c83147e591991ffece79752ed80d3ff960a).
=> [LLVM] Bump LLVM and update parsers

include/circt/Dialect/Calyx/CalyxInterfaces.td, include/circt/Dialect/Calyx/CalyxPrimitives.td, include/circt/Dialect/Calyx/CalyxStructure.td, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Dialect/Calyx/CalyxOps.cpp, lib/Dialect/Calyx/Transforms/CompileControl.cpp, test/Conversion/SCFToCalyx/convert_controlflow.mlir, test/Conversion/SCFToCalyx/convert_memory.mlir, test/Conversion/SCFToCalyx/convert_simple.mlir, test/Dialect/Calyx/canonicalization.mlir, test/Dialect/Calyx/compile-control.mlir, test/Dialect/Calyx/emit.mlir, test/Dialect/Calyx/errors.mlir, test/Dialect/Calyx/go-insertion.mlir, test/Dialect/Calyx/remove-groups.mlir, test/Dialect/Calyx/round-trip.mlir
Changes a cell's `instanceName` argument from StringAttr to FlatSymbolRefAttr. This will be necessary for the addition of an `InvokeOp`, which needs to verify that the instance being invoked actually exists. Since primitives (namely multi-cycle ones) may also be `invoke`able, this is required for all cells.
By-product(s):
1. We are now guaranteed that instance names do not clash component names.
2. I've made all builders similar, requiring that a `StringRef` be passed in rather than the previous mixture of `StringRef` and `StringAttr`.
=> [Calyx] [SCFToCalyx] Change Cell instance name from StringAttr to FlatSymbolRefAttr.

lib/Translation/ExportVerilog/CMakeLists.txt
~Marking this as a Draft PR since I haven't fully tested it locally. I'll update this when I confirm that it passes for me locally.~
This should fix the build errors in main, where we fail to link to some
symbols defined in MLIRPass. This build error appears to only manifest
when BUILD_SHARED_LIBS=ON.
Fixes #1925.
=> [ExportVerilog] Add MLIRPass to CMakeLists.txt.

integration_test/ESI/cosim/basic.mlir, integration_test/ESI/cosim/loopback.mlir, integration_test/ESI/system/basic.mlir, integration_test/EmitVerilog/basic.mlir, integration_test/EmitVerilog/lint.mlir, integration_test/EmitVerilog/sv-interfaces.mlir, test/Dialect/ESI/cosim.mlir
Verilog exporting was moved from a translation to a proper pass.  As a
part of this change, it should be invoked by `circt-opt` instead of
`circt-translate`. This change should fix the integration build.
Example broken build: https://github.com/llvm/circt/runs/3802989444?check_suite_focus=true
Testing this on an integration build: https://github.com/llvm/circt/actions/runs/1308501663
=> Properly use `circt-opt` for `export-verilog`

include/circt/Dialect/SV/SVPasses.h, include/circt/Dialect/SV/SVPasses.td, include/circt/Support/Path.h, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp, lib/Dialect/SV/Transforms/HWExportModuleHierarchy.cpp, lib/Support/Path.cpp, test/Dialect/SV/hw-export-module-hierarchy.mlir, tools/firtool/firtool.cpp
This should unblock https://github.com/llvm/circt/issues/1708 as discussed in https://github.com/llvm/circt/pull/1792#issuecomment-934057209.
Previously this pass created an sv.verbatim op with the entirety of the
module hierarchy JSON file embedded into it, with the expectation that
the --split-verilog mode of firtool would actually be the one to create
it. This is now problematic because we'd like to move name legalization,
into the ExportVerilog pass, which means module names could change after
ExportVerilog runs.
Moving the HWExportModuleHierarchy pass after ExportVerilog guarantees
that names match the final verilog, but that means that
HWExportModuleHierarchy may no longer rely on the sv.verbatim op
output_file method to actually emit the file.
This commit changes …
=> [HWExportModuleHierarchy] Directly emit JSON to a file instead of an sv.verbatim op.

.github/workflows/shortIntegrationTests.yml
Run the integration tests on one configuration (of the nightly matrix) on each
push to main. Should catch 95% of integration test breakages. Useful for
identifying the particular offending commit and emailing the commit author.
=> [CI] Add a short integration test which runs on each push to main

lib/Conversion/ExportVerilog/CMakeLists.txt, lib/Dialect/Comb/CMakeLists.txt, lib/Dialect/FIRRTL/CMakeLists.txt, lib/Dialect/FIRRTL/Export/CMakeLists.txt, lib/Dialect/FIRRTL/Import/CMakeLists.txt, lib/Dialect/FSM/CMakeLists.txt, lib/Dialect/MSFT/TclExport/CMakeLists.txt, lib/Dialect/SV/CMakeLists.txt, lib/Dialect/Seq/CMakeLists.txt
CMake `glob`s only get run at configuration time; so, when one adds a file,
they must cmake re-configure. When a file gets added and someone git-pulls it
in, they must manually re-configure (since Ninja doesn't detect the
cmake-affecting change). This change makes it so `git pull && ninja` just
works.
=> [CMake] [NFC] Eliminate cmake `glob`s

include/circt/Dialect/FIRRTL/InstanceGraph.h, lib/Dialect/FIRRTL/InstanceGraph.cpp, lib/Dialect/FIRRTL/Transforms/InferResets.cpp
In an earlier change, I made InferResets always mark the InstanceGraph
analysis as preserved, under the assumption that the pass does not
modify the instance graph.  This turns out to be incorrect as it can add
arguments to a module and must recreate the instance ops to reflect
that.
This change adds a function `InstanceGraph::replaceInstance(old, new)`
which allows the InstanceGraph to stay updated by the pass. This is the
first function added to the InstanceGraph to allow updating the cached
analysis.  This function is slightly more efficient than adding
separate `addInstance(new)` and `removeInstance(old)` functions.
=> [FIRRTL][InferReset] Keep instance graph properly updated

include/circt/Dialect/Handshake/HandshakeOps.td, lib/Conversion/StandardToHandshake/StandardToHandshake.cpp, lib/Dialect/Handshake/HandshakeOps.cpp, test/Conversion/StandardToHandshake/test_call.mlir, test/Dialect/Handshake/errors.mlir, test/handshake-runner/call_controlflow.mlir
When lowering a `handshake.instance` operation, we need to be able to decide when the instance is activated; or in other words, when the input control signal is asserted. Lowering from a CDFG to handshake, this will be whenever control flow arrived to the basic block of the source `builtin.call` operation, which the `handshake.instance` op originated from. With this new operand, we are able to be explicit about the activation of the `handshake.instance` op, and be able to implement lowering of the operation to FIRRTL.
=> [Handshake] Add control operand to `handshake.instance` operation

lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, test/Conversion/HandshakeToFIRRTL/errors.mlir
In preparation for supporting `handshake.instance` lowering, this commit introduces top module inference and instance cycle detection. The IR is topologically sorted based on `handshake.instance` usage. During this, we check for instance cycles (and report them to the user) as well as top-module detection. For now, if multiple top modules are available, an error is thrown.
Furthermore, the `firrtl.circuit` op is now created outside of the `handshake.func` operation lowering, based on the inferred top-level name.
=> [HandshakeToFIRRTL] Add top module inference and instance cycle detection

lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, test/Conversion/HandshakeToFIRRTL/test_instance.mlir
Since we're already relying on instantiating FIRRTL modules for the lowered handshake operations, instantiating an already lowered `handshake.func` module is straight-forward. The important part of this commit is that it ensures modules are lowered in post-order wrt. the instance graph (by iterating through the reversed topological order of the instance graph).
=> [HandshakeToFIRRTL] Lower `handshake.instance` operations

lib/Conversion/HWToLLHD/HWToLLHD.cpp, lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, lib/Conversion/LLHDToLLVM/LLHDToLLVM.cpp, lib/Dialect/ESI/ESIPasses.cpp, lib/Dialect/MSFT/MSFTPasses.cpp, lib/Dialect/Seq/SeqPasses.cpp
Bump LLVM to pull in performance improvements from https://reviews.llvm.org/D111695.
This includes changes to remove deprecated usages of `ArrayRef<Value>`.  For more information see:
- https://reviews.llvm.org/D110293
- https://reviews.llvm.org/D110360
This also required a change to HWToLLHD as an argument materializer seemed to be leaving around incomplete conversions.  I am not sure that this is the correct change, however...  With this change, no changes were required to the tests.
=> Bump LLVM for D111695

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir, test/Conversion/ExportVerilog/verilog-basic.mlir
Change ExportVerilog emission of a zero-valued parameter to use "0" and
not "64'd0".  MLIR infrastructure will parse a zero as an APInt of type
i64.  This causes problem for emission of FIRRTL-parsed parameters which
need to show up in the output as "0" instead of "64'd0" which some tools
may reject.
This is special cased during Verilog emission to prevent having to
deviate from the seemingly canonical handling of a zero-valued APInt
being stored as an i64.
Concretely, this fixes a problem that @Ramlakshmi3733 has seen where a circuit like the following:
```scala
circuit Foo:
extmodule Bar:
parameter X = 0
parameter Y = 1
module Foo:
inst bar of Bar
bar.a <= a
```
Would, without this, result in:
```verilog
module Foo(	
input a);
Bar #(
.X(64'd0),
.Y(1)
) …
```
=> [ExportVerilog] Emit zero param as "0" not "64'd0"

include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/AnnotationDetails.h, lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp, lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp, test/Dialect/FIRRTL/grand-central-taps.mlir
Change the Grand Central Taps pass to output (via the output file
attribute) data and memory taps it creates to a directory indicated by
an optional ExtractGrandCentralAnnotation.  If this annotation does not
exist, do nothing.  This change is made to align Grand Central behavior
with the Scala FIRRTL Compiler.
=> [FIRRTL] Output GCT Taps into Extraction Directory

include/circt/Support/BackedgeBuilder.h, lib/Support/BackedgeBuilder.cpp
If a backedge value is referenced multiple times, for some reason, only the last reference is being replaced through the current `setValue` implementation. This is fixed by replacing the value using the more canonical approach of `Value::replaceAllUsesWith`.
Furthermore, adds a check to ensure that a backedge is only set one. I think this is a fair restriction, given that the backedge is a stand-in for an eventual SSA value.
=> [Support] Use `replaceAllUsesWith` in BackedgeBuilder

tools/circt-reduce/Reduction.cpp, tools/circt-reduce/Reduction.h, tools/circt-reduce/circt-reduce.cpp
This PR improves *circt-reduce* as follows:
Add a pattern to circt-reduce which removes unused ports from the root module, which can significantly reduce the size of the test case.
The circt-reduce tool iteratively tries to apply a rewrite pattern on large subsets of the operations. If the pattern doesn't apply on the current subset, the number of operations is halved and application is retried, forming a sort of binary search for reductions.
In the current implementation, when circt-reduce applies a pattern that improves the output, it will immediately reset the subset to its maximum size and restart trying pattern application from the top. This can be very cumbersome in the case where the rewrite pattern applies only when a fine granularity of operations is chosen. However, it takes a …
=> [reduce] Add FIRRTL lowering passes, improve pattern application strategy

include/circt/Support/LoweringOptions.h, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Support/LoweringOptions.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir, test/Conversion/ExportVerilog/line-length.mlir, test/Conversion/ExportVerilog/sv-dialect.mlir, test/Conversion/ExportVerilog/sv-interfaces.mlir
For #840, this PR is trying to remove temporary wires caused by the line length restriction. 
If the length of the buffer filled by the current subexpression is larger than threshold,
it splits the buffer into multiple lines by inserting a endline character.
With this patch, this IR 
```mlir
hw.module @longvariadic(%a: i8) -> (b: i8) {
%1 = comb.add %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a,
%a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a,
%a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a,
%a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a, %a
: i8
hw.output %1 : i8
}
```
will be convert into  
```verilog
module longvariadic(    // variadic.mlir:1:1
input  [7:0] a,
output [7:0] b);
assign b = a + a + a + a + a + a + a + a + a + a + …
```
=> [ExportVerilog] Don't spill expressions which are used only once

lib/Dialect/FIRRTL/Export/FIREmitter.cpp, test/Dialect/FIRRTL/emit-basic.mlir
This adds support for emitting `SeqMemOp`, `CombMemOp`, and their memory
ports, `MemoryPortOp` and `MemoryPortAccessOp`.
The code for emitting memory port access is a little tricky because it
must reach backwards and find the original CHIRRTL memory declaration
and memory port to get all the information needed to print.
Theoretically the port name could have been stored using `addValueName`,
but we already had the port op in hand for other attributes, so we just ask it directly
for its name.
The code doesn't have error checking because the error cases are all
covered by the verifier.
=> [FIRRTL][Emitter] Add SeqMem and CombMem support

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td, include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/InferResets.cpp, lib/Dialect/FIRRTL/Transforms/LowerCHIRRTL.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/inner-names.mlir, test/Dialect/FIRRTL/lower-types-errors.mlir
Add a `inner_sym` attribute to the following FIRRTL dialect operations:
- `InstanceOp`
- `NodeOp`
- `WireOp`
- `RegOp`
- `RegResetOp`
- `MemOp`
The `inner_sym` attribute allows these operations to be named in a `hw.innerNameRef`, and gives us the ability to attach a name to these operations that will be carried over through lowering into the HW dialect.
An interesting case arises if one of these operations has an inner name and type lowering would have to duplicate the operation. This can occur for example for a wire with aggregate type:
%x = firrtl.wire sym @foo : !firrtl.bundle<a: uint<1>, b: uint<2>>
Type lowering would convert this into two wires, one for field `a` and one for field `b`. However, since the wire itself defines the symbol `@foo`, it is unclear what should happen with …
=> [FIRRTL] Add inner names to declarations

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
This duplicates the functionality of a mux fold as a canonicalization to
support invalid values of unknown width.
A change to MLIR core disallows folds which change the return type of
the value used. When the invalid value is of unknown width, the mux's
return type will also be unknown width, but after the fold is performed
the type changes to the known width operand.
For example,
```
mux(p: uint<1>, invalid: uint, x: uint<2>) -> uint
```
canonicalizes to return `uint<2>`.
=> [FIRRTL] Add unknown width `mux(p, invalid, x) -> x` canonicalizer

.github/workflows/buildAndTest.yml
Currently, clang-format is not applied to the modification of clang-tidy. So it is troublesome if clang-tidy breaks clang-format.
=> [CI] Run clang-format after clang-tidy

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir
In FIRRTL unprocessed annotations are dropped in LowerToHW, unless the
`-warn-on-unprocessed-annotations` flag is passed,  which  will create a
a warning for each remaining annotation.
When a non-local annotation goes unhandled, it leaves behind some
`NonLocalAnchor` operations and a few "fake" `circt.nonlocal`
annotations along the instance path. This change makes it so that we
drop `NLA` operations in `LowerToHW` instead of erroring on them. This
also changes the flag `warn-on-unprocessed` to not emit a warning for the
intermediate `circt.nonlocal` annotations along the NLA path, since we
will emit a warning for the real annotation. This should align with the behaviour
of local annotations.
=> [FIRRTL][LowerToHW] Don't emit warnings for non-local annotations

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Dialect/FIRRTL/canonicalization.mlir, test/Dialect/FIRRTL/infer-widths-errors.mlir, test/Dialect/FIRRTL/infer-widths.mlir
This adds support to infer the width of invalid values in the
InferWidths pass.  The width of InvalidValueOps is inferred as a special
case, where it will always be set to the width of the thing it is
connected to.
When an InvalidValue of unknown width is used by an operation that is
not a connect, such as an `AddPrimOp`, then there is no way to infer the
width and we will emit an error.
When a single invalid value with unknown width is used by mutliple
operations, the pass will duplicate the invalid value for each use.
This is so that we can infer a different width depending on the
location, as we don't want to impose an artificial constaint that each
location has the same width. This situation easily arises after running
CSE.
InvalidValues are not being constructed as a part of the …
=> [FIRRTL][InferWidths] Infer invalid value widths

frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/test/polynomial.py, include/circt/Dialect/MSFT/MSFTAttributes.td, include/circt/Dialect/MSFT/MSFTOps.td, lib/Bindings/Python/circt/dialects/_hw_ops_ext.py, lib/Bindings/Python/circt/dialects/_msft_ops_ext.py, lib/Dialect/MSFT/MSFTOps.cpp, lib/Dialect/MSFT/MSFTPasses.cpp, test/Dialect/MSFT/module_instance.mlir
The op is identical to hw.module.extern, but it can be referred to by
a msft.instance op. This adds a cleaner layering where PyCDE only
generates msft.module/msft.module.extern/msft.instance ops. Before, it
would generate msft.module/hw.module.extern, leading to a mix of
msft.instance/hw.instance for LowerMSFTToHW to consume. This change
introduces a clear contract for PyCDE's output: all module and
instance ops are from the MSFT dialect.
Some of the implementation is duplicated into MSFTOps.cpp from
HWOps.cpp, but refactoring is left as a future exercise, related to
https://llvm.discourse.group/t/instancelike-and-modulelike-interfaces/4132/3.
=> [MSFT] Introduce msft.module.extern op for PyCDE lowering.

include/circt/Dialect/HW/HWOps.h, lib/Dialect/HW/HWOps.cpp
Add a `sym` field to `PortInfo` which holds the optional `hw.exportPort` symbol to use for a port. Extend the `buildModule` function to honor this field and populate the `argAttrs` and `resultAttrs` arrays as appropriate to contain these port symbols.
This will make it easier later for other dialects to attach port symbols during the lowering to the HW dialect (FIRRTL is an example that is coming up soon).
=> [HW] Add support for port symbols to module builder

include/circt/Dialect/FIRRTL/FIRRTLOps.h, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, test/Dialect/FIRRTL/SFCTests/verbatim-inner-names.mlir
With inner symbols added to many of the FIRRTL declaration operations, there now arises a problem where another operation may have a reference to such a symbol, but an transformation deletes the original declaration. In the HW dialect, the presence of an inner symbol on an operation is interpreted as a dont-touch. This commit extends the checks for dont-touch performed within the FIRRTL dialect (specifically during folding and IMConstProp) such that they consider the presence of a `inner_sym` attribute equivalent to a `DontTouchAnnotation`.
At a later point we may even decide to remove `DontTouchAnnotation`s already in the parser and simply ensure that the targeted operations do have a `inner_sym`, which would have a similar effect. There are some possibly weird interactions with …
=> [FIRRTL] Make presence of `inner_sym` equiv to dont-touch

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/verilog-basic.mlir
The `emitBind` was using incorrect port names during `ExportVerilog`. 
Use `getPortVerilogName` to get the updated name. 
Fixes https://github.com/llvm/circt/issues/2084
=> [ExportVerilog] Get legalized bind port names

lib/Dialect/FIRRTL/Transforms/InferResets.cpp, test/Dialect/FIRRTL/infer-resets.mlir
Fix an issue in `InferResets` where using a local wire or node as the async reset for the module could cause dominance issues when the wire was declared *after* some of things it would end up getting connected to. A typical example would be:
%reg = firrtl.reg %clock
%localReset = firrtl.wire /*FullAsyncResetAnnotation*/
In this case `InferResets` would decide to hook `%localReset` up to the register `%reg`, creating a dominance problem.
This commit changes the behavior of `InferResets` such that it moves the local reset declaration up to before the first thing it gets connected to, possibly converting a `NodeOp` to a `WireOp` if the node's input value blocks the move due to it not dominating the target site.
Thanks to @youngar for finding this issue!
=> [FIRRTL] Fix local wire/node resets not dominating inferred connections

include/circt/Dialect/SV/SV.td, include/circt/Dialect/SV/SVDialect.td, include/circt/Dialect/SV/SVTypes.td
Similar to the refactoring done in HW, move the `SVDialect` definition into a separate `SVDialect.td` file, such that other dialects can selectively include `SVTypes.td` to gain access to the declarations there. This should help structure the dialects in a fashion that allows portions to be reused and keep repetition down.
=> [SV] Make SVTypes.td includable from other dialects

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/verilog-basic.mlir
Fix an issue in `ExportVerilog` where `hw.exportPort` symbols on output ports of a module would not be properly interpolated into `sv.verbatim` operations. This commit fixes the issue by adding the output ports to the symbol cache, and changing the interpolation of port symbols to rely on the `getPortVerilogName()` function of the `GlobalNameTable`. This has the benefit of beign consistent with the corresponding module (name collisions are resolved), and that no `BlockArgument` is required to get a hold of the output port name.
=> [ExportVerilog] Fix output port symbols not interpolating properly

tools/circt-reduce/CMakeLists.txt, tools/circt-reduce/Reduction.cpp, tools/circt-reduce/Reduction.h, tools/circt-reduce/Tester.cpp, tools/circt-reduce/Tester.h, tools/circt-reduce/circt-reduce.cpp
Setup a CIRCT-specific runner for reduction test cases. This implementation is more elaborate than what's in MLIR at the moment, and allows for test cases to be carefully validated, written to disk and checked for their size, and then run through the tester, in distinct steps. The MLIR version does all of these things at the same time, which can be prohibitively expensive if the test case is a two-hour formal equivalence check -- just to find out that the module size increased and we have to throw away the reduction regardless.
Eventually we'll want to upstream this back to MLIR.
=> [reduce] Add CIRCT-specific test case runner

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLStructure.td, include/circt/Dialect/FIRRTL/FIRRTLTypes.td, include/circt/Dialect/HW/HWTypes.td, include/circt/Dialect/SV/SVInOutOps.td, include/circt/Dialect/SV/SVTypes.td, include/circt/Types.td
Create a CIRCT-wide `include/circt/Types.td` file that can collect the common type, attribute, and constraint definitions used throughout the CIRCT project, which may not be specific to one of the given dialects. Things that land here would generally be candidates for upstreaming to MLIR, but it's better to have a common place in CIRCT first where they can incubate.
While we're at it, get rid of some of the type definitions which have since appeared in upstream MLIR, and factor some first commonalities out into `Types.td`. There will be quite a few more in the future.
---
~~Change the `FIRRTLExpressions.td` to depend on `SVTypes.td` for the definition of `StringArrayAttr` (and later also `NameRefArrayAttr` for work in #2113).~~
~~As @lattner mentioned in #2112, this creates a dependency …
=> [TableGen] Factor common defs out into common `Types.td`

lib/Dialect/FIRRTL/Transforms/InferResets.cpp, test/Dialect/FIRRTL/infer-resets.mlir
`InferResets`  was not handling the case when the reset reg is an `index` into the `SubAccess` Op and not the `input`.
Fixes https://github.com/llvm/circt/issues/2132
=> [FIRRTL] Handle RegReset as index to SubAccess

lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/ExportVerilog/ExportVerilogInternals.h, lib/Conversion/ExportVerilog/LegalizeNames.cpp, test/Conversion/ExportVerilog/name-legalize.mlir, test/Conversion/ExportVerilog/verilog-basic.mlir
With the introduction of inner name references, operations such as `sv.verbatim` can interpolate the name of declarations in other modules, like wires or instances. This requires that all such operations have their names properly legalized and stabilized before the parallel emission of Verilog starts. Currently the names of wires are picked on-the-fly inside `ModuleEmitter`, which is already too late.
This commit extends the name legalization pass and `GlobalNamesTable` to also cover declaration ops. This allows such operations to be properly renamed upfront, with the names being frozen at emission time. The emission code in `ModuleEmitter` then simply uses that pre-frozen name for all declarations.
This enables follow-up work around symbols on FIRRTL module ports, and using them properly …
=> [ExportVerilog] Legalize declaration op names

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_memory.mlir
Closes #2108. This takes the very safe assumption that if *any* memory stores are present, do not throw the load in a combinational group.
Also some random cleanup, and the removal of a dump call.
=> [SCFToCalyx] Fix memory load followed by store.

frontends/PyCDE/test/compreg.py, frontends/PyCDE/test/instances.py, frontends/PyCDE/test/polynomial.py
The previous usage of environment variables and shell redirection
wouldn't work on Windows. Replace that with a command line argument
and --input-file respectively.
=> [PyCDE] Make tests platform-independent.

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
Extend the `VerbatimExprOp` and `VerbatimWireOp` to also support symbols during string interpolation. This reflects recent changes in the SV dialect. The additional symbols are simply passed through during lowering to the HW dialect. Having this support will allow some FIRRTL passes to properly mention module and declarations by name in their verbatim output.
=> [FIRRTL] Add symbol interpolation to verbatim ops

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h, include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/BlackBoxMemory.cpp, lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp, lib/Dialect/FIRRTL/Transforms/InferResets.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/SFCTests/verbatim-inner-names.mlir, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/inner-names.mlir
Extend the FIRRTL dialect such that the `FModuleOp` and `FExtModuleOp` operations can carry an optional symbol for each of their ports. This is done in a similar fashion as port names, directions, and annotations, in that there is a separate array attribute which tracks the symbol for each port. Since leaving null attributes in the IR is a bit yucky, the absence of a symbol is encoded as an empty string.
This extends module-like port lists to support the following:
firrtl.module @Foo(
in %a: !firrtl.uint<1> sym @symbolA,
out %b: !firrtl.uint<1> sym @symbolB
)
The change to the IR itself is pretty trivial, but causes a whole bunch of follow-up fixes in all the places that build or modify modules. These places are surprisingly numerous and would benefit from some later cleanup. @youngar has …
=> [FIRRTL] Add optional port symbols to module-like ops

include/circt/Conversion/FIRRTLToHW.h, include/circt/Conversion/Passes.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/errors.mlir, tools/firtool/firtool.cpp
Add an option to decide whether `LowerToHW` should treat non-constant async reset values as warning or error. Have firtool keep these as errors unless IMConstProp is disabled, in which case it is highlgy likely that the user does not care about a full stop of the compilation and his downstream tools will possibly break for a lot of other reasons.
=> [FIRRTL] Add option to treat non-const async reset as warning/error

lib/Dialect/MSFT/ExportQuartusTcl.cpp, test/Dialect/MSFT/location.mlir
We used templated verbatim ops for the hierarchy down to the op the
user is placing, but not for that op itself. This would lead to
mismatches if that op's name got legalized in ExportVerilog.
Add a test for this, and pull the common logic into a helper.
=> [MSFT] Ensure Tcl export uses a symbol name for the op in question.

include/circt/Dialect/MSFT/MSFTAttributes.td, include/circt/Dialect/MSFT/MSFTOps.td, lib/Dialect/MSFT/MSFTAttributes.cpp, lib/Dialect/MSFT/MSFTOps.cpp, test/Dialect/MSFT/attributes.mlir
A PhysicalRegion is a Symbol which can be referred to by ops to be
placed within it. It contains potentially multiple rectangular bounds
on the physical device.
=> [MSFT] Add PhysicalRegion op and related attributes.

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir
The commit https://github.com/llvm/circt/commit/fc7d917466db453d3e7a322194977519c4cb5a19, updated the name legalization to properly rename 
all declaration ops `(<WireOp, RegOp, LocalParamOp, InstanceOp>)`, and 
maintain them in the rename map in the global state. 
This means, the ops no longer have the updated names in the IR.
This commit fixes the `ExportVerilog` to query the global symbol table,
for getting the name of any Declaration op.
This fixes an issue with the `bind` op printing the incorrect old names.
=> [ExportVerilog] Query global state to get the updated names

include/circt/Dialect/MSFT/DeviceDB.h, lib/Dialect/MSFT/DeviceDB.cpp, lib/Dialect/MSFT/ExportQuartusTcl.cpp, lib/Dialect/MSFT/MSFTPasses.cpp, test/Dialect/MSFT/location.mlir, test/Dialect/MSFT/translate-errors.mlir
This is a very simple start to Tcl support for PhysicalRegions. For
now physical region references and the PlacedInstances making the
reference are just stored in a vector that can be walked to emit the
necessary Tcl. More complex storage and queries for PhysicalRegions
can be added as the need arises.
=> [MSFT] Add Tcl export support for PhysicalRegions.

frontends/PyCDE/src/pycde/system.py, frontends/PyCDE/test/polynomial.py, frontends/PyCDE/test/syntactic_sugar.py, include/circt/Dialect/MSFT/MSFTOps.td, lib/Bindings/Python/circt/dialects/_msft_ops_ext.py, lib/Dialect/MSFT/MSFTPasses.cpp, test/Dialect/MSFT/module_instance.mlir
Add an attribute to `msft.module` specifying the filename in which the
generated SystemVerilog should be placed. In PyCDE, use the module name
as the output filename.
=> [PyCDE] [MSFT] Emit modules into separate SV files

include/circt/Dialect/Handshake/Handshake.td, include/circt/Dialect/Handshake/HandshakeInterfaces.td, include/circt/Dialect/Handshake/HandshakeOps.td, lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, lib/Dialect/Handshake/HandshakeOps.cpp, test/Conversion/HandshakeToFIRRTL/test_naming.mlir
This commit introduces a new interface `NamedIOInterface` for handshake operations. This interface is intended to capture the naming of the in- and output operands of a handshake operation. The interface implements a default naming convention equal to what's currently being used (in#, out#). However, operations can override this interface to provide more specialized naming, such as the `MuxOp` example used in the commit.
The interface is used in in HandshakeToFIRRTL through a class `PortNameGenerator`. This class handles port name generation for all operands which may be lowered into handshake modules. If the source operand was a handshake operand (which implements the `NamedIOInterface`) the interface is used to generate port names. Else, default names are generated.
=> [Handshake] Add interface for specializing port naming

docs/RationaleSV.md, include/circt/Dialect/SV/SVExpressions.td, include/circt/Dialect/SV/SVInOutOps.td, include/circt/Dialect/SV/SVOps.h, include/circt/Dialect/SV/SVVisitors.h, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/SV/SVOps.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir, test/Dialect/SV/basic.mlir, test/Dialect/SV/errors.mlir
This PR adds the indexed part-select operation to the SV dialect.
In SystemVerilog, the Indexed part-select gives an access to contiguous bits
of vectors. Part-select can be used to address a part of a vector. 
The range is specified by two, integer expressions: the `base` and the constant
`width`. The selected bits starts incrementing from `base` and number of bits
is equal to `width`.
The bit addressing is always ascending starting from the base
Part-select is defined in section 11.5.1 of 1800-2017 spec.
In this example, bits starting from `%c2_i3` and of width 40 are addressed.
```
%wire42 = sv.reg : !hw.inout<i42>
%a = sv.part_select %wire42[%c2_i3 : 40] : !hw.inout<i42>, i3, !hw.inout<i40>
sv.bpassign %a, %c42 : i40
```
Which is lowered to the following verilog
```
reg        [42:0] …
```
=> [SV] Add part-select operation to SV dialect

lib/Dialect/Handshake/Transforms/Analysis.cpp
This commit improves on the dot graph generation by supporting nested modules. This is done by maintaining state about variable use/def chains across `handshake.instance` operations, and resolving these to generate graph edges.
Furthermore, graph writing is cleaned up quite a bit.
```mlir
module  {
handshake.func @baz(%arg0: i32, %arg1: none, ...) -> (i32, none) attributes {argNames = ["a", "ctrl"], resNames = ["out0", "outCtrl"]} {
%0 = "handshake.buffer"(%arg0) {control = false, sequential = true, slots = 2 : i32} : (i32) -> i32
%1 = arith.addi %arg0, %0 : i32
%2 = "handshake.buffer"(%1) {control = false, sequential = true, slots = 2 : i32} : (i32) -> i32
%3 = "handshake.buffer"(%arg1) {control = true, sequential = true, slots = 2 : i32} : (none) -> none
handshake.return %2, %3 : i32, …
```
=> [Handshake] Add support for `handshake.instance` in dot emission

lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp, test/Dialect/FIRRTL/annotations.fir
Scatters a `ModuleReplacementAnnotation`.
```json5
{
"class": "sifive.enterprise.grandcentral.ModuleReplacementAnnotation",
// the list of intances/modules to replace
"targets": [
"~Top|Top/child:Child",
"~Top|Top/childWrapper:ChildWrapper/child:Child"
],
// the replacement module
"circuit": "",
// annotations associated with the replacement module
"annotations": [],
// prefix and output sub-directory of the replacement module
"circuitPackage": "other",
// dontTouch all the ports of replaced modules
"dontTouches":[
"~Top|Child>in",
"~Top|Child>out"
]
}
```
This adds a parent annotation to the circuit, annotates each member of `targets` with an id and the parent id, and adds dontTouches to each entry in `dontTouches`. Mostly copied from `SignalDriverAnnotation`
=> Add scattering for ModuleReplacementAnnotation

.github/workflows/buildAndTest.yml
It seems diff command to apply for clang-tidy was incorrect for PR review and caused some false positive.
Here we need to use three dots instead of two dots.
=> [CI] Fix diff command for clang-tidy

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir
This raises the precendence of the signed shift operator from the
`LowestPrecedence` to `Shift`.  It was originally `Shift` precedence,
but was changed in #1681. From the issue, it's not clear to me
what the reason for the change was. The current level of precedence is
mismatched from Verilog precedence and is causing brackets to not be
emitted when needed for the `>>>` arguments.
For example, when using a low precedence operator such as the ternary
mux as an argument to the `>>>`, it should surround the mux in
parenthesis.  Currently it is printing:
```verilog
assign o = $signed($signed(x) >>> p ? 45'h5 : 45'h8)
```
When it should be:
```verilog
assign o = $signed($signed(x) >>> (p ? 45'h5 : 45'h8))
```
Changing the precedence does modify one of the test cases to remove an
extra set of …
=> [ExportVerilog] Raise precedence of `>>>` aka signed shr

lib/Dialect/SV/Transforms/HWMemSimImpl.cpp, test/Dialect/SV/hw-memsim.mlir, test/firtool/memory.fir
Use the `IndexedPartSelect` op to implement the `HWMemSimImpl`, instead of creating multiple registers.
=> [SV] Implement HWMemSimImpl using indexed part-select

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td
Extend the `FModuleLike` interface to provide a somewhat more convenient way of setting the optional symbols on ports.
=> [FIRRTL] Add port symbol setters to FModuleLike

lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp, test/Dialect/FIRRTL/SFCTests/emit-omir.fir, test/Dialect/FIRRTL/emit-omir.mlir
Emit `InnerRefAttr`s for the instances, ports, and declarations the OMIR emitter has to include in its output. This prevents the emitter from having to hardcode these names, and leaves symbolic placeholders which are filled in at the last moment by `ExportVerilog`.
=> [FIRRTL] Use inner names to make OMIR output stable under renaming

frontends/PyCDE/src/pycde/devicedb.py, frontends/PyCDE/src/pycde/instance.py, frontends/PyCDE/src/pycde/system.py, frontends/PyCDE/test/instances.py, include/circt-c/Dialect/MSFT.h, lib/Bindings/Python/MSFTModule.cpp, lib/Bindings/Python/circt/dialects/_msft_ops_ext.py, lib/CAPI/Dialect/MSFT.cpp
This add the necessary Python binding boilerplate to create
PhysicalBounds and PhysicalRegionRef attributes. A new API is added to
System, which inserts a PhysicalRegion. A wrapper class for
PhysicalRegion allows creating a region, adding bounds, and getting a
reference attribute suitable for use with the add_attribute API.
=> [PyCDE] Add entry method for PhysicalRegions and their references.

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
This PR changes the lowering to track used random bits length and reuse appropriately. 
With this patch, 
```
circuit Foo:
module Foo:
output o: UInt<138>
reg r1: UInt<2>, clock
reg r2: UInt<4>, clock
reg r3: UInt<32>, clock
reg r4: UInt<100>, clock
r1 <= a
r2 <= a
r3 <= a
r4 <= a
o <= cat(r1, cat(r2, cat(r3, r4)))
```
will be initialized like this:
```verilog
`ifdef RANDOMIZE_REG_INIT // foo.fir:8:5
_T = `RANDOM;   // foo.fir:8:5
r1 = _T[1:0];   // foo.fir:8:5
r2 = _T[5:2];   // foo.fir:9:5
_T_0 = `RANDOM; // foo.fir:10:5
r3 = {_T[31:6], _T_0[5:0]};     // foo.fir:10:5
_T_1 = `RANDOM; // foo.fir:11:5
r4 = {_T_0[31:6], `RANDOM, `RANDOM, _T_1[9:0]}; // foo.fir:11:5
`endif
```
Will close https://github.com/llvm/circt/issues/2094
=> [FIRRTL/LowerToHW] Reuse random bits in register initialization

lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp, test/Dialect/FIRRTL/SFCTests/data-taps.anno.json, test/Dialect/FIRRTL/SFCTests/data-taps.fir, test/Dialect/FIRRTL/grand-central-taps.mlir
Make use of the new `inner_sym` added to the FIRRTL dialect to replace a lot of the hard-coded declaration names in the `GrandCentralTapsPass` with placeholders that get replaced with the final names during emission in `ExportVerilog`.
=> [FIRRTL] Use inner names to make GCT data taps more robust

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp, test/Dialect/FIRRTL/grand-central.mlir
Update the Grand Central interfaces/views pass to allow for the parent
to be the top module.  Previously there was an incorrect requirement
that the parent module had to be instantiated exactly once.
This is done to enable a pattern where assertions are placed in the test
harness (the top module) and interfaces must therefore work when the
parent is the top module.
=> [FIRRTL] GCT Interface: Allow top as parent

lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp, test/Conversion/ExportVerilog/verilog-basic.mlir, test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/HWRename.fir, test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir, test/Dialect/FIRRTL/grand-central.mlir
Make use of `InnerRefAttr`s inside the `GrandCentralPass` to refer to the interface instances and remote declarations targeted by the mapping module. This makes the names emitted as part of the `sv.verbatim` ops symbolic and allows `ExportVerilog` to substitute them with the final values during emission.
Since nested interface instances are not working at the moment, we still hard-code the name of the interface signals. This is technically only needed for the case where an interface would contain a nested interface. However, the way we have to traverse these nested interfaces in the code makes it very hard to decide upfront whether an interface will be referred to by name, or by symbol, because the fact whether it was emitted as a verbatim op (instead of an instance) is only known after …
=> [FIRRTL] Use inner name refs for GCT interface emission

integration_test/EmitVerilog/lint.mlir
The integration test is failing because of verilator width warning.
It seems like this is a verilator bug, and the output is legal. 
So this commit adds a comment to disable the width check.
The test started failing after in-lining was enabled for `ArraySliceOp` in https://github.com/llvm/circt/commit/9a59ecf2f1012d16f05755218edd6328d145280f 
The output verilog snippet from `lint.mlir` that is triggering the warning:
``` 
input  [3:0]      a
input  [9:0][3:0] array
output [2:0][3:0] r29
...
assign r29 = array[a + 4'h1 +: 3];
```
Verilator warning:
```
%Warning-WIDTH: out.v:43:24: Operator ADD expects 32 bits on the LHS, but LHS's CONST '4'h1' generates 4 bits.
: ... In instance TESTSIMPLE
43 |   assign r29 = array[a + 4'h1 +: 3];
|                        ^
... For warning description see …
```
=> [IntegrationTest] Disable lint width warning

tools/CMakeLists.txt, tools/circt-lsp-server/CMakeLists.txt, tools/circt-lsp-server/circt-lsp-server.cpp
This was very difficult and definitely took me more than 10 minutes get working. Thank you @River707 for making this super complicated :)
... All joking aside this was very simple and feels like a big deal for approachability, especially for bindings which need to know the explicit names of things that might be elided by the pretty format.
To use, install the [MLIR](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-mlir) extension and make it point to the `circt-lsp-server` executable in your project: 
(Note: I put my build products in `build/vscode` but most folks just use `build`, so you might need to adjust the path for your setup)
=> Add `circt-lsp-server` tool which can be used with the MLIR VSCode extension

include/circt/Dialect/HW/HWAggregates.td, test/Conversion/ExportVerilog/hw-dialect.mlir
Currently `array_get ` doesn't work well when the length of array is 1. For example,
```mlir
hw.module @array1(%arr: !hw.array<1xi1>) -> (o1: !hw.array<1xi1>) {
%false = hw.constant false
%0 = hw.array_get %arr[%false] : !hw.array<1xi1>
hw.output %arr : !hw.array<1xi1>
}
```
will produce 
```
foo.mlir:3:28: error: use of value '%idx' expects different type than prior uses: 'i0' vs 'i1'
%val = hw.array_get %arr[%idx] : !hw.array<1xi1>
^
foo.mlir:2:3: note: prior use here
%idx = hw.constant 0 : i1
```
This is because `IndexBitWidthConstraint` asserts that the width of index is equal to `llvm::Log2_64_Ceil(length)` which is equal to 0 when length is 1. This PR modify to use `length == 1? 1 : llvm::Log2_64_Ceil(length)`.
=> [HW] Fix IndexBitWidthConstraint when the size is 1

lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp, test/Dialect/FIRRTL/SFCTests/emit-omir.fir
Since zero width ports will be dropped during `LowerToHW`, donot generate the OMIR metadata for them.
OMIR pass generates symbols for zero width ports, if they are not ignored.
=> [FIRRTL][Metadata] Ignore OMIR metadata for zero width ports

lib/Dialect/Handshake/CMakeLists.txt, lib/Dialect/Handshake/HandshakeExecutableOps.cpp, lib/Dialect/Handshake/HandshakeOps.cpp
I don't think there's a good argument for keeping all of the execution logic in together with the builders, parsers and printers of the handshake operation. Splitting this into a separate file should be easier for both developers and newcomers to navigate.
=> [Handshake] Move execution functions to separate file

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLTypes.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/infer-resets.mlir, test/Dialect/FIRRTL/test.mlir
In practice we have come across registers of width zero. The `InferResets` pass then tries to add an asynchronous reset to these, for which it has to come up with a zero value of that type. However, the `firrtl.constant` op cannot generate a value of width 0. This adds a workaround that keeps `ConstantOp` unchanged, but uses the `TailPrimOp` to chop off the only bit from a single-bit value.
=> [FIRRTL] Fix InferResets failing on zero-width registers

include/circt/Dialect/HW/HWOps.h, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/ExportVerilog/ExportVerilogInternals.h, lib/Conversion/ExportVerilog/LegalizeNames.cpp, lib/Dialect/HW/HWOps.cpp
Avoid calling `getAllModulePortInfos` for getting the name of every port.
The `port id` should be enough to compute the required information.
The `emitTextWithSubstitutions` was calling `getAllModulePortInfos` and 
was causing a run-time blow up for a large design with a module > 100 ports,
with symbols on each of them which were used on a `VerbatimOp`.
(In particular, the `EmitOMIR` pass is creating this `VerbatimOp` and
adding a symbol to all the ports in the design.)
`ExportVerilog` runtime for a test case reduced from  580.3878 sec to 152.1718 sec
=> [ExportVerilog] Avoid getAllModulePortInfos for getting individual port name

include/circt/Dialect/HW/HWTypeDecls.td, include/circt/Dialect/HW/HWVisitors.h, lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/hw-typedecls.mlir
This removes the restriction that a type scope is at the top-level,
and its special-cased visitors. Now, a type scope and its type
declarations can be visited just like any other statements. This
allows them to compose with other region-carrying ops, like ifdef.
=> [HW][ExportVerilog] Treat typedecls like any other statement.

include/circt/Dialect/HW/HWOps.h, lib/Dialect/HW/HWOps.cpp
Simplify the function to get the number of input and output ports for modules and instances, since they all have the same argument names.
=> [HW] Simplify module/instance input/output size computation. NFC

lib/Conversion/ExportVerilog/ExportVerilog.cpp
It is cheaper to call `namify` than to store it in `SmallVector` during text substitution.
Seems to drop runtime of a test case from 150.5509 sec to 2.7712 sec, size of the vector was ~400 elements.
=> [ExportVerilog] Remove temporary vector in text substitution

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/verilog-basic.mlir
At the moment, the call to `legalizeGlobalNames` which populates the `GlobalNameTable` occurs *before* individual modules are prepared for emission. This is problematic because this preparation may spawn additional wires that require legalized names.
The call to `prepareHWModule` currently happens inside the parallel execution of `emitHWModule`, right at the start. This change moves the call to this function out of `emitHWModule` and into a parallel section before name legalization. Module preparation would already happen in parallel and before the module was emitted, but it occurring as part of `emitHWModule` would mean it happened intertwined with all the other emission code. Moving the call outside has the same effect, but gives a clean point in the code at which all modules are known …
=> [ExportVerilog] Prepare modules before name legalization; NFC

include/circt/Dialect/HW/HWStructure.td, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/HW/HWOps.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir, test/Conversion/ExportVerilog/line-length.mlir, test/Dialect/HW/basic.mlir
- [HW] Add Comment to HWModuleOp
Add a new mandatory attribute, "comment", to HWModuleOp that describes a
string comment that should be attached to that module when this module
is emitted by a backend.
- [ExportVerilog] Emit HWModuleOp Comments
Add support for emitting comments associated with HWModuleOps during
ExportVerilog.  Use a simple line breaking algorithm to try to respect
the emittedLineLength option when reasonably possible.
Add tests that comments are emitted and that line breaking changes as
expected with changes to emittedLineLength.
Towards #1677.
=> [HW][SV][ExportVerilog] Add Comment to HWModuleOp, Verilog Emission

include/circt/Dialect/LLHD/IR/StructureOps.td, lib/Conversion/HWToLLHD/HWToLLHD.cpp, lib/Conversion/LLHDToLLVM/LLHDToLLVM.cpp, lib/Dialect/LLHD/Export/TranslateToVerilog.cpp, lib/Dialect/LLHD/IR/LLHDOps.cpp, lib/Dialect/LLHD/Simulator/Engine.cpp, lib/Dialect/LLHD/Transforms/ProcessLoweringPass.cpp, test/Dialect/LLHD/IR/entity.mlir
Since MLIR has gained the `NoTerminator` op trait in the meantime, remove the LLHD `TerminatorOp` that was originally introduced to get around a lack of this trait. This requires adjusting the code in a few places where the terminator is handled explicitly.
=> [LLHD] Remove TerminatorOp; NFC

include/circt/Dialect/HW/HWStructure.td, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/HW/HWOps.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir, test/Conversion/ExportVerilog/line-length.mlir, test/Dialect/HW/basic.mlir
Reverts llvm/circt#2066
This broke all the python unit tests.  They are probably trivial to fix, but I'd like the builders to get back to green.
=> Revert "[HW][SV][ExportVerilog] Add Comment to HWModuleOp, Verilog Emission"

include/circt/Dialect/HW/HWStructure.td, lib/Bindings/Python/circt/dialects/_hw_ops_ext.py, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/HW/HWOps.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir, test/Conversion/ExportVerilog/line-length.mlir, test/Dialect/HW/basic.mlir
This reverts commit 495c145196ca52f6d247e1ce98d74747e407c4a9.
It adds back the original change, with a small update to the Python
bindings to set a default for the new attribute when needed.
=> Revert "Revert "[HW][SV][ExportVerilog] Add Comment to HWModuleOp, Verilog Emission (#2066)" (#2240)"

docs/VerilogGeneration.md
changed the `allowExprInEventControl` to `exprInEventControl` and `enforceVerifLabels` to `verifLabels`. Ran into this issue while playing around with Verilog Generation and was a little stumped until I started digging into the code. Hopefully this will save newer users from running into the same issue.
=> [Documentation] fix veriloggen docs

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
Now that upstream `APInt` and friends properly support values of zero bits, some of the guards against zero width types in `FIRRTLFolds` have become obsolete. Remove these to generally operate on anything that has a known width, zero and up. Some operations need to work with values that are one bit narrower than the input, for example to compute things like `inputWidth - 1` in signed right shifts. Make these fold to a constant zero early on, or skip canonicalization altogether.
This follows up on a suggestion by @lattner in #2207.
=> [FIRRTL] Allow more zero-width folds

include/circt/Scheduling/Problems.h, lib/Analysis/SchedulingAnalysis.cpp, lib/Scheduling/TestPasses.cpp
This PR replaces the public single-argument constructors that initialise the `containingOp` in the `Problem` hierarchy with factory methods, e.g.
```c++
CyclicProblem prob(func);
```
becomes
```c++
auto prob = CyclicProblem::get(func);
```
The old way is very unpleasant for `Problem`s with multiple super classes, as exemplified by the `ModuloProblem`.
```c++
explicit ModuloProblem(Operation *containingOp)
: Problem(containingOp), CyclicProblem(containingOp),
SharedOperatorsProblem(containingOp) {}
```
Upcoming additions to the `Problem` hierarchy will rely even more on multiple inheritance for composition.
=> [Scheduling] Get problem instances via factory methods.

integration_test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/ExportVerilog/ExportVerilogInternals.h, lib/Conversion/ExportVerilog/PrepareForEmission.cpp
Remove the `isInParallelMode` flag and the corresponding assertion, which are no longer needed since the emission phase of `ExportVerilog` treats the IR as immutable, which allows for pretty straightforward parallelization. All mutation is limited to the preparation phase which lives in the separate `PrepareForEmission.cpp` file.
Also remove the XFAIL on one of the FIRRTL Grand Central integration tests, which used to trigger this assertion.
Add comments to the `ExportVerilog.cpp` and `PrepareForEmission.cpp` files explaining the separation into an IR-mutating preparation and IR-immutable emission phase.
=> [ExportVerilog] Remove parallel assert, XFAIL, add comment

include/circt/Dialect/LLHD/IR/LLHDTypesImpl.td, lib/Dialect/LLHD/IR/LLHDTypes.cpp
Replace the custom parsers and printers of the signal and pointer types in LLHD with the new assembly-format feature.
Why not replace `TimeAttr` printer and parser, too?
The closest we can get is `#llhd.time<1 "ns", 0 d, 0 e>`. Currently, we have `#llhd.time<1ns, 0d, 0e>`
=> [LLHD] Use assembly-format for signal and pointer type

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir
Fix an issue in `ExportVerilog` where the signal names used as port connections in emitted `bind` statements would not use the legalized name. The underlying issue is twofold:
First, the call to `prepareHWModule`, which generates additional wires for instances emitted as ports, occurs after name legalization. Any wires inserted by this function would not get legalized. This change moves the calls to `prepareHWModule` into a (parallelized) loop before name legalization occurs.
Second, the `getNameRemotely` function which provides the names for the bind port connections would not properly see through the IR pattern used to make output ports of the instance always connect to a wire:
%tmpWire = sv.wire
%output = hw.instance ... () -> (output: i1) {doNotPrint = true}
sv.assign %tmpWire, …
=> [ExportVerilog] Fix bind port names not being legalized

include/circt/Support/APInt.h, lib/Dialect/FIRRTL/CMakeLists.txt, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, lib/Support/APInt.cpp, lib/Support/CMakeLists.txt, test/Dialect/FIRRTL/canonicalization.mlir
Upstream LLVM zero-width APInts will assert if you try to use any methods which involve sign extension.  This attempts to work around this by either using better methods which don't error or defining new methods which treat zero-width behavior as zero extension regardless of sign.
This should get the nightly performance regressions back to passing.
=> [FIRRTL] Work Around Zero Width APInt Sign Extend Issues

integration_test/Bindings/Python/dialects/msft.py, lib/Dialect/MSFT/DeviceDB.cpp
This needs to check the available location against the target
y-axis. Adds a test that was reliably reproducing the issue.
=> [MSFT] Fix getNearestFreeInColumn logic.

include/circt/Transforms/Passes.h, include/circt/Transforms/Passes.td, lib/Transforms/FlattenMemRefs.cpp, test/Transforms/flatten_memref_calls.mlir
This pass is intended to be a "software"-like companion to --flatten-memref. Whereas --flatten-memref will flatten all memref operations and function signatures to unidimensional memories and accesses thereto, this pass can be used to transform calls to such flattened operations. In other words, this pass expects the parent function of a `callOp` to be able to support multidimensional memories, but rewrites calls _to_ flattened functions.
This is done by converting memref arguments through a `memref.subview` operation. Any called function which had its signature rewritten will be replaced by a private function definition having a signature of the rewritten function type.
=> [Transforms] Add --flatten-memref-calls pass

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td, test/Dialect/FIRRTL/canonicalization.mlir
Change the behavior of folding around pad, as discussed in #2197 and
implemented in #2198, to fold a pad of an invalid value to a constant
zero.  This prevents propagation of invalids which is generally viewed
as a source of errors.
=> [FIRRTL] Fold pad(invalid, width) -> zero<width>

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td, lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp
In certain places, FIRRTL would accept empty port annotations and symbol arrays as a shorthand for "none of the ports have any anno/sym", while others do not. This cleans up hopefully all of these uses to consistently accept empty arrays as shorthand.
=> [FIRRTL] Cleanup some ambiguities about empty port anno/sym arrays

include/circt/Dialect/Handshake/HandshakePasses.h, include/circt/Dialect/Handshake/HandshakePasses.td, lib/Dialect/Handshake/Transforms/Buffers.cpp, lib/Dialect/Handshake/Transforms/CMakeLists.txt, test/Dialect/Handshake/remove_buffers.mlir
A very simple pass which removes any buffers present in the circuit. This pass can come in handy if:
1. one would like to re-buffer a circuit
2. one would like to simulate without buffers
3. one would like to simplify the circuit (for visual/.dot inspection)
=> [Handshake] Add buffer removal pass

include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp, lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp, lib/Dialect/FIRRTL/Transforms/PrefixModules.cpp
When an annotation targets only part of the thing it is attached to, it
is represented using a `SubAnnotationAttrs`, which contains the field ID
of its target.
The Annotation wrapper class can be only be created from a
DictionaryAttr.  When using a SubAnnotationAttr, it is created from its
internal DictionaryAttr, and the stored field ID is ignored. This makes
it impractical to use `SubAnnotationAttrs` with most of the Annotation
APIs.
This change makes it so the Annotation wrapper holds on to the original
annotation attribute, instead of just a DictionaryAttr.  The annotation
wrapper will check which kind of annotation it has internally when calls
are made.
This change then adds a call to `getFieldID`, which return 0 for regular
annotations, and the field id for `SubAnnotations`.
This …
=> [FIRRTL] Make Annotation hold on to the actual annotation attribute

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/InferResets.cpp
This adds a method to insert ports into an instance op.  Since this
increases the number of results of the instance op, it actually has to
be cloned.  It is assumed that the user will manually call
`replaceAllUses` and erase the original instance operation.  This
functionality is useful for any pass that adds ports to modules.
=> [FIRRTL] Add method to insert ports into instance ops

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, test/Dialect/FIRRTL/expand-whens-errors.mlir, test/Dialect/FIRRTL/expand-whens.mlir
This commit changes expandWhens to accept vector types under the condition that connections are expanded, i.e. all the connections are between ground types.
I changed `declareSinks` to handle vector types and diff is very small thanks to FieldRef implementation.
=> [FIRRTL/ExpandWhens] Support vector types

include/circt/Dialect/Moore/CMakeLists.txt
This flag appears to be needed to support an upcoming revision of
LLVM. Without this, TableGen complains with:
```
error: defs belonging to more than one dialect. Must select one via
'--(attr|type)defs-dialect'
```
=> [Moore] Specify -attrdefs-dialect when generating attributes, NFC.

docs/VerilogGeneration.md, lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir
Use `sv.namehint` instead of just `name` in ExportVerilog. Updated rationale. Closes #1752.
=> [ExportVerilog] Implement `sv.namehint`

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
Fix a bug in SubPrimOp canonicalization where an asUInt cast was applied
before the pad inside a utility method.  This commit changes the utility
method to apply a cast (either asUInt or asSInt) if needed.
Fixes #2289.
=> [FIRRTL] Fix SubPrimOp canonicalization bug

include/circt/Dialect/SV/SVPasses.h, include/circt/Dialect/SV/SVPasses.td, lib/Dialect/SV/Transforms/HWMemSimImpl.cpp, test/firtool/memory.fir, tools/firtool/firtool.cpp
This change adds an option to ignore the memory read enable signal during memory lowering to register banks.
According to the FIRRTL spec, the read output is undefined if the read enable signal is disabled.
But the `firrtl` implementation ignores the read enable signal, 
https://github.com/chipsalliance/firrtl/blob/master/src/main/scala/firrtl/backends/verilog/VerilogEmitter.scala#L1122
This change ensures that, in `HWMemSimImpl` by default the read output is set to `X` if read enable is disabled, but if 
`ignore-read-enable-mem` option is passed, then the read output is set, irrespective of the enable signal.
This provides an option to match the Scala FIRRTL compiler behavior.
=> [SV][HWMemSimImpl] Add option to ignore read enable for memory lowering

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/RemoveResets.cpp, test/Dialect/FIRRTL/remove-resets.mlir, tools/firtool/firtool.cpp
Add a new pass, RemoveResets, that replaces RegResetOps that have
invalidated initialization values with RegOps.  This is part of a series
of patches that are intended to align CIRCT with the Scala FIRRTL
Compiler (SFC) interpretation of invalid.  Previously, CIRCT relies on
canonicalization/folding of invalid values to do this optimization.
This pass enables future canonicalization/folding of invalid values to
zero (as the SFC does) without having to worry about performing this
optimization.
Run the RemoveResets pass as part of firtool after ExpandWhens and
before the first canonicalization.  This enables conversion of
invalidated RegResetOps to RegOps before canonicalization (eventually)
interprets invalid values as zero.
=> [FIRRTL] Add RemoveResets Pass

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/SFCTests/parameters.fir, test/Dialect/FIRRTL/parse-basic.fir
Change FIRRTL parsing to convert all parameters less than 32-bit to
32-bit APInts.  This fixes downstream issues with Verilog emission,
where negative parameters may have too few bits in their APInt
representation and print as shorter-than-expected literals.
Fixes #2299.
This follows the minimal suggestion of [this comment](https://github.com/llvm/circt/pull/2076#issuecomment-962184122) to just store parameters as 32-bit values.
=> [FIRRTL] Parse params < 32-bit as 32-bit

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/SFCTests/invalid-interpretations.fir
This depends on and includes #2287 which adds a `RemoveResets` pass which then makes this aggressive canonicalization legal.
- [FIRRTL] Canonicalize Invalid Connects to Zero
Extend the behavior of connect canonicalization to convert a connection
to an InvalidValueOp to a connect to zero.  This is done to enforce
compliance with one Scala FIRRTL Compiler (SFC) interpretation of
"invalid is constant zero".
This change requires a RemoveResets pass (#2287) to run before the
canonicalization that this PR adds.  This is because registers require a
separate interpretation of invalid where "invalid is undefined when used
as the initialization value of a register" (and where invalidness is
determined by looking through wires/connects in the current module).
This latter, "register initialization" …
=> [FIRRTL] Canonicalize Invalid Connect to Zero

lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, test/Conversion/HandshakeToFIRRTL/test_mux.mlir
This commit reworks how mux trees are generated in `HandshakeToFIRRTL` lowering. The rework is motivated by bugs within the old implementation wrt. how select signals are calculated. The implementation should hopefully also be a bit more readable than the prior, due to the recursive approach.
The old implementation resulted in verilog where some input signals had been optimized out:
```verilog
module handshake_mux_in_ui64_ui64_ui64_ui64_out_ui64(	// <stdin>:633:5
input         select_valid,
input  [63:0] select_data,
input         in0_valid,
input  [63:0] in0_data,
input         in1_valid, // <--- input never referenced in body
input  [63:0] in1_data, // <--- input never referenced in body
input         in2_valid,
input  [63:0] in2_data,
input         out0_ready,
output …
```
=> [HandshakeToFIRRTL] Rework mux tree generation

include/circt/Dialect/Handshake/HandshakePasses.h, include/circt/Dialect/Handshake/HandshakePasses.td, lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, lib/Dialect/Handshake/Transforms/Analysis.cpp, test/Dialect/Handshake/add-ids.mlir
This commit introduces a new pass `--handshake-add-ids` which will add a unique ID to each operation, with respect to other equivalent operations within a `handshake.func` operation. When present, these IDs are used in both .dot graph printing and FIRRTL instance name generation.
Having this provides a deterministic method of tracing back FIRRTL modules to handshake IR or the .dot file, which is the tuple of the operation name + the operation id.
=> [Handshake] Add pass to add unique IDs to each operation

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, test/Dialect/FIRRTL/canonicalization.mlir, test/Dialect/FIRRTL/expand-whens.mlir
This commit removes the mux canonicalization which optimizes muxes when
one of the branches is invalid to the value of the other branch.
```mlir
mux(p, invalid, x) -> x
```
This optimization is not actually implemented by the SFC compiler, and
we actually need invalids to be treated as 0 when used in a mux.
We do need a similar optimization when lowering `WhenOp`s to muxes
during `ExpandWhens`.  When a wire is invalidated in one branch of a
when op, we optimize away the invalid.  This was previously handled by
creating a mux operation and relying on the folder to perform the
optimization.
A side effect of this change is that in IMCP we no longer want to pass
unknown lattice values as `InvalidAttr` constants to the Mux folder.
Doing this without the invalid folder causes the mux to fail to …
=> [FIRRTL] Remove fold `mux(p, invalid, x) -> x`

integration_test/Bindings/Python/dialects/msft.py, lib/Bindings/Python/MSFTModule.cpp
This adds a helper to create a Python object of the appropriate
subclass when passing attributes returned or provided to a callback.
=> [MSFT] Cast attributes passed from PlacementDB to their subclass.

lib/Dialect/SV/Transforms/HWMemSimImpl.cpp, test/firtool/memory.fir
Change the behavior of the `-ignore-read-enable-mem` to use the exact
behavior of Scala FIRRTL Compiler default memory lowering.  This will
now use the read enable to gate the update of the latched address.
Previously, the read enable was used to gate the final read.  The net
effect is that the memory will output the last read value continuously.
With this patch, for the following read-latency-1 memory:
```scala
circuit Foo:
module Foo:
input rAddr: UInt<4>
input rEn: UInt<1>
output rData: UInt<8>
mem memory:
data-type => UInt<8>
depth => 16
reader => r
read-latency => 1
write-latency => 1
read-under-write => undefined
memory.r.clk <= clock
memory.r.en <= rEn
memory.r.addr <= rAddr
rData <= memory.r.data …
```
=> [SV] Make -ignore-read-enable-mem FIRRTL pedantic

lib/Conversion/ExportVerilog/LegalizeNames.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir
Add the `hw.verilogName` attribute after `LegalizeNames` updates the name.
This ensures that passes that run after `ExportVerilog` get the correct 
verilog name from the IR.
Fixes part of, https://github.com/llvm/circt/issues/2220, 
the pass still needs to be updated to use the `hw.verilogName` attribute.
We need the `hw.` prefix in the attribute name because argument 
attribute needs the dialect prefix, 
https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/IR/FunctionSupport.h#L616
=> [ExportVerilog] Add the verilogname attribute for updated verilog name

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
Change randomization logic to NOT gate randomization based on a
deasserted reset signal when lowering a FIRRTL regreset.  This aligns
randomization with the Scala FIRRTL Compiler and prevents Xs from
showing up if the reset is not held low when the initial block runs.
=> [LowerToHW] Don't gate reg randomization on reset

docs/RationaleSeq.md, frontends/PyCDE/test/verilog_readablility.py, include/circt/Dialect/Seq/Seq.td, lib/Dialect/Seq/SeqOps.cpp, lib/Dialect/Seq/SeqPasses.cpp, test/Dialect/Seq/basic.mlir
Adds an innerSym attribute to CompRegOp, which is passed to the RegOp
during lowering. This allows workflows to reliably give a register a
symbol that can refer to the underlying reg.
=> [Seq] Add inner_sym attribute to CompReg and use it on RegOp.

include/circt/Dialect/SV/SVInOutOps.td, include/circt/Dialect/SV/SVVisitors.h, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/SV/SVOps.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir
This commit adds an new operation `sv.struct_field_inout` to create
inout memory for hw::StructType. Potentially, this will be used to
lower firrtl bundle types.
=> [SV][ExportVerilog] Add sv.struct_field_inout op

frontends/PyCDE/src/pycde/instance.py, frontends/PyCDE/src/pycde/value.py, frontends/PyCDE/test/compreg.py, frontends/PyCDE/test/syntactic_sugar.py, frontends/PyCDE/test/verilog_readablility.py, lib/Dialect/MSFT/CMakeLists.txt, lib/Dialect/MSFT/ExportQuartusTcl.cpp
This extends the Instance wrapper to wrap not just instances but also
registers. Additionally, in the Tcl export, this looks for registers,
adds them to the symbol cache, and uses their symbol names.
Users are now able to place CompRegOp when its innerSym attribute is
set. If they create a CompRegOp directly, the inner_sym must be passed
explicitly, but the `reg(...)` helper on Value is extended to use the
name as the inner_sym when passed.
=> [PyCDE] Add support for placing CompRegOp.

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
This commit changes to lower firrtl.subfield to sv.struct_field_inout
for inout types. By this commit we can represent connect to bundle type
elements.
=> [LowerToHW] Lower firrtl.subfield to sv.struct_field_inout for inout types

lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, test/Dialect/FIRRTL/expand-whens-errors.mlir, test/Dialect/FIRRTL/expand-whens.mlir
This is a follow up of https://github.com/llvm/circt/pull/2286.
This commit changes ExpandWhens to handle aggregate type registers.
We need to expand the connection into individual ground type elements.
=> [FIRRTL/ExpandWhens] Support aggregate type registers

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/verilog-basic.mlir
Fixes issue with `sv.verbatim` op where symbols with extra braces around them (e.g. `{{{symbol_id}}}`) were not interpolated
=> ExportVerilog: handle substitutions with extra braces

lib/Conversion/SCFToCalyx/CMakeLists.txt, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
The interface allows SCFToCalyx to support both scf::WhileOp and
staticlogic::PipelineWhileOp in the same way. For now, only the
scf::While op is supported.
=> [SCFToCalyx] Extract an interface for while-like ops, NFC.

include/circt/Dialect/HW/HWAggregates.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/HW/HWOps.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
This commit makes LowerToHW handle bundle values properly:
(i) bundle registers initialization and (ii) extension of
`getExtOrTruncArrayValue` to accept struct/bundle values.
It is almost the same change as https://github.com/llvm/circt/pull/2143.
=> [FIRRTL/LowerToHW] Support bundle type lowering

include/circt-c/Dialect/HW.h, include/circt/Dialect/HW/HWTypes.h, include/circt/Dialect/HW/HWTypesImpl.td, lib/Bindings/Python/HWModule.cpp, lib/CAPI/Dialect/HW.cpp, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/LLHDToLLVM/LLHDToLLVM.cpp, lib/Dialect/ESI/capnp/Schema.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/HW/HWTypes.cpp
This commit changes to use StringAttr instead of StringRef
in FieldInfo to avoid unnecessary copies of field names.
Changes are mainly about parser/printer and CAPI.
Will close https://github.com/llvm/circt/issues/2324
=> [HW] Use StringAttr instead of StringRef in FieldInfo, nfc

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir
This commit fixes the issue of empty struct emission. If structs are
empty we shouldn't emit `struct packed {}` because it causes syntax
errors. This adds handlings of struct types to `isZeroBitType` and
`printPackedTypeImpl`.
Will close https://github.com/llvm/circt/issues/2327
=> [ExportVerilog] Fix empty struct emission

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
This commit enables us to lower invalid values with aggregate types.
Since we lower invalid values into zero constant, we apply hw.bitcast
to the constant to get values with aggregate types.
=> [LowerToHW] Lower invalid values with aggregate types

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir
This commit fixes the issue related to the emission of automatic
variable. If the type contains a struct type, we shouldn't emit "logic"
because "automatic struct" is syntactically correct. 
Will close #2335 .
=> [ExportVerilog] Don't emit "logic" for temporaries with struct types

include/circt/Dialect/Handshake/HandshakeOps.td, lib/Dialect/Handshake/HandshakeOps.cpp, test/Dialect/Handshake/canonicalization.mlir
The use a concept of "dematerialized" values to apply optimizations. Dematerialized values are defined as the source of any given value before passing through a buffer or fork operation.
=> [Handshake] Add fork and mux canonicalization patterns

include/circt/Dialect/SV/SVExpressions.td, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/SV/SVOps.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir, test/Dialect/SV/errors.mlir
This commit allows constantX/Z op to have non-integer types for the use case like https://github.com/llvm/circt/pull/2332.
=> [SV] Allow constantX/Z to have non-integer types

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir
This commit updates `isExpressionUnableToInline` and
`isOkToBitSelectFrom` to handle struct types properly.
`isExpressionUnableToInline` is updated to check
StructExtractOp as well as other ops. Also `isOkToBitSelectFrom` is
modified not to introduce unnecessary temporary wires.
Will close https://github.com/llvm/circt/issues/2342
=> [ExportVerilog] Improve `isExpressionUnableToInline` for struct types

lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, test/Conversion/HandshakeToFIRRTL/test_buffer_fifo.mlir
This commit adds a transparent FIFO buffer to HandshakeToFIRRTL. The implementation is based on the FIFO of dynamatic (https://github.com/lana555/dynamatic/blob/master/components/elastic_components.vhd) but with use of a counter to track the fullness/emptyness of the FIFO (i suspect that there is a bug in the dynamatic implementation, for a 2 slot FIFO, if head == 0, tail == 1, the buffer is considered full).
No tests are added for this, however, i'm currently working with (and verifying) this in CIRCT-HLS in an integration manner. Once things start migrating from CIRCT-HLS to here, coverage of the semantics of the FIRRTL components should be vastly improved.
An upcoming commit will use the InnerFIFO implementation to also implement a non-transparent fifo (as a replacement for the …
=> [Handshake] Add a transparent FIFO buffer

lib/Dialect/Comb/CombFolds.cpp, test/Dialect/Comb/canonicalization.mlir
When checking if we can fold a series of `mux`es into an array+select,
this limits the number of array elements to 512.  This is fixing an
overflow when the bitwidth was 64, causing us to try to store a
`1<<bitwidth` in a `uint64_t`, while also trying to pose a sensible
limit.  The limit was chosen arbitrarily.
=> [Comb] Don't canonicalize muxs to array-selects when the index is large

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Dialect/FIRRTL/lower-types-aggregate.mlir, test/Dialect/FIRRTL/lower-types.mlir, tools/firtool/firtool.cpp
This commit adds `preserve-aggregate` flag to enable an experimental feature to preserve passive aggregate wires/registers. If preserve-aggregate flag is enabled, we change the behavior of `peelTypes` function not to flatten the type when the condition holds. 
We can't preserve aggregate if any of the following condition holds:
1. They are ports of MemOp (Ports of MemOp must be ground types) 
2. They are non-passive types
3. They contain an analog type
4. They are types with zero width.
=> [FIRRTL/LowerTypes][FIRTOOL] Preserve aggregate at lowertypes

lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp, test/Dialect/FIRRTL/SFCTests/emit-omir.fir, test/Dialect/FIRRTL/emit-omir.mlir
Fix an issue in the `EmitOMIR` pass, where the addition of port information would introduce additional `OMBigInt` values which were not properly formatted as hexadecimal values, but just as decimal ones. This updates the emission to make them hexadecimal as expected by other parts of the FIRRTL ecosystem.
=> [FIRRTL] Fix OMIR port widths not being hex values

test/circt-reduce/connect-source-operand-forward.mlir, tools/circt-reduce/Reduction.cpp
This commit adds a new reducion called `ConnectSourceOperandForwarder`.
If a wire is used only once as a destination of a connect, we can
forward the wire to one of operands of the source value. `OperandForwarder`
can't reduce this because of the wire connection.
For example, consider the following IR.
```mlir
%a = firrtl.wire : !firrtl.uint<1>
%src0 = firrtl.wire : !firrtl.uint<2>
%src1 = firrtl.bits %src0 0 to 0 : (!firrtl.uint<2>) -> !firrtl.uint<1>
firrtl.connect %a, %src1
```
ConnectSourceOperandForwarder reduces the IR above into
```mlir
%a = firrtl.wire : !firrtl.uint<2>
%src0 = firrtl.wire : !firrtl.uint<2>
firrtl.connect %a, %src0
```
This reduction is potentially useful for cleaning up chains of bits/pad
op inserted by the reducer.
=> [reduce] Add `ConnectSourceOperandForwarder` reduction

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp, test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir
This fixes an issue that macro definitions are not included in
the companion files.
=> [GrandCentral] Include replicated operations for companion

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir
This commit changes  the condition of the assertion of ExtractOp
emission to allow `Selection` as a precedence. By doing this, we can emit
something like `a.b[2:1]`.
Since selection operators are left-assoc so it's safe to put as a precedence. 
For the safety, `isOkToBitSelectFrom` is also asserted.
=> [ExportVerilog] Relax the assertion of ExtractOp

include/circt/Scheduling/Problems.h, lib/Scheduling/Problems.cpp, lib/Scheduling/TestPasses.cpp, test/Scheduling/chaining-problem-errors.mlir, test/Scheduling/chaining-problems.mlir
This PR defines a `ChainingProblem`, which models the accumulation of physical propagation delays on combinational paths along SSA dependences within a scheduling problem's abstract time steps/cycles.
For example, the modeling for the `@multi_cycle` test case from `chaining-problems.mlir` would look like this:
=> [Scheduling] Define problem to model operator chaining.

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
Connections to reg/regreset op should be lowered to assignments in
always statements. But when the destinations are derived by subfield
or subindex, we didn't identify them as registers. Fixed by just checking
fieldRef to get their root values.
Will close https://github.com/llvm/circt/issues/2343
=> [LowerToHW] Check a root value to identify reg/regreset op

lib/Conversion/StandardToHandshake/StandardToHandshake.cpp, test/Conversion/StandardToHandshake/test_insert_buffer_cycles.mlir
As far as i interpret the theory, buffers are only needed to break combinational cycles in the style of dataflow circuits that we generate. However, i am starting to suspect that there is something within our flow which requires buffers to be placed on all "logical" cycles as well. Deadlock has been observed in some circuits where control flow is a loop with multiple basic blocks in the loop (b0->b1->b2->b3->b1). This might also be correlated with memory accesses within those blocks, but further investigation is needed.
Nevertheless, experimentally, almost all deadlocks are removed when we add a sequential buffer to break combinational cycles, and for any remaining merge-like operations, add a FIFO buffer on their output, which alleviates the situation described above.
=> [Handshake] Add buffer on all merge outputs

lib/Dialect/FIRRTL/Transforms/PrefixModules.cpp
This replaces a `llvm:DenseMap<StringRef, llvm::SmallVector` with a
`llvm::DenseMap<StringRef, std::vector>` which does not invalidate vector
iterators  when inserting into the `DenseMap`.
=> [FIRRTL][PrefixModules] Fix DenseMap node reference invalidation

lib/Dialect/FIRRTL/Import/FIRParserAsserts.cpp
When parsing asserts we have a helper class, `ExtractionSummaryCursor`,
to keep track of error messages.  The class holds a `const Twine &`
which created an issue with dangling references.  The following function
was directly creating a dangling reference by passing in `{}` for the
second argument.
```c++
template <typename JsonType>
ExtractionSummaryCursor<JsonType>
makeExtractionSummaryCursor(Location loc, JsonType jsonValue) {
return ExtractionSummaryCursor<JsonType>{loc, {}, jsonValue};
}
} // namespace
```
By changing the member type to a regular `Twine`, the class is
effectively a wrapper around `Twine` and has the same usage
restrictions. This fixes a bug originally reported by Valgrind.
=> [FIRRTL] Fix Twine usage in `FIRParseAsserts`

lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/ExportVerilog/ExportVerilogInternals.h, lib/Conversion/ExportVerilog/LegalizeNames.cpp
Replace the use of global names table with the name attribute on the operation.
LegalizeNames is setting the attribute `hw.verilogName`, with the updated names.
This change will move the process to query the name of an operation to looking up the attribute on the operation, 
instead of maintaining the global map.
The global names for parameter and interface map are still being used. They also need to be ported to a similar
mechanism next.
This change can potentially improve some memory and a minor runtime performance.
=> [ExportVerilog] Use verilogName attr instead of Name Table

lib/Dialect/Calyx/Export/CalyxEmitter.cpp
During the build of CIRCT with GCC 11, I was getting two warnings. It will fix one of them:
```
[172/353] Building CXX object lib/Dialect/Calyx/Export/CMakeFiles/obj.CIRCTExportCalyx.dir/CalyxEmitter.cpp.o
/home/xgupta/llvm/circt/lib/Dialect/Calyx/Export/CalyxEmitter.cpp:372:44: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
372 |            parent->hasTrait<ControlLike>() &&
|            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
373 |                "This should only be used to emit Calyx Control structures.");
|                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> [NFC] Fix a build warning

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
Work around a bug in Verilog emission with the disallowLocalVariables
option where temporaries are spilled to wires which violates the
ordering of the initial block used for register randomization.  This
manifests as X's showing up in registers after initialization.  This
avoids this entirely by using explicit registers and verbatim operations
using those registers.
Fixes #2310.
For the example FIRRTL circuit shown in #2310:
```verilog
circuit Foo:
module Foo:
input d: UInt<1>
output q: UInt<1>
reg r: UInt<1>, clock
r <= d
q <= r
```
This PR produces, with or without `-lowering-options=disallowLocalVariables`:
```verilog
module Foo(	// Bar.fir:2:10
input  clock, d,
output q);
reg r;	// Bar.fir:7:5
`ifndef …
```
=> [LowerToHW] Fix reg init via verbatim ops

include/circt/Analysis/DependenceAnalysis.h, lib/Analysis/DependenceAnalysis.cpp
This is useful to transformations that want to be able to reuse the
analysis during progressive lowering. If an affine.load or
affine.store is lowered, this API can be used to maintain any
dependences on the replacement op.
=> [MemoryDependenceAnalysis] Add ability to replace an op.

lib/Analysis/SchedulingAnalysis.cpp, test/Analysis/scheduling-analysis.mlir
This generalizes the auxiliary dependences added for control flow to
support both Affine and SCF IfOps. Similarly, the auxiliary dependence
from the stores to the terminator are generalized to support both
Affine and MemRef StoreOp. With these enhancements, this analysis now
supports the SCF and MemRef dialects, provided the memory dependences
are correctly assigned.
=> [SchedulingAnalysis] Support scf::IfOp and memref::LoadOp/StoreOp.

include/circt/Conversion/Passes.td, lib/Conversion/AffineToStaticLogic/AffineToStaticLogic.cpp, lib/Conversion/AffineToStaticLogic/CMakeLists.txt, lib/Conversion/PassDetail.h, test/Conversion/AffineToStaticLogic/loops.mlir
This adds the necessary support to lower single affine loops to
pipelines. Broadly, this encompasses lowering affine structures like
if conditions into arithmetic, and building pipeline stages for each
scheduled group.
=> [AffineToStaticLogic] Flesh out support for converting to pipelines.

include/circt/Support/Namespace.h
This commit modifies the creation of new names to skip already used
ones. This fixes regression of LowerToHW caused by many creations of
RANDOM values. `Namespace::newName`  creates new name for 
"RANDOM" but it is trying  "RANDOM_0", "RANDOM_1", ...., "RANDOM_N"
every time which causes squared time complexity.
For test2.fir, 
Before: 
```
Total Execution Time: 130.0296 seconds
----Wall Time----  ----Name----
1.7655 (  1.4%)  FIR Parser
7.8127 (  6.0%)  'firrtl.circuit' Pipeline
0.6226 (  0.5%)    'firrtl.module' Pipeline
0.5154 (  0.4%)      CSE
0.0000 (  0.0%)        (A) DominanceInfo
0.1072 (  0.1%)      LowerCHIRRTLPass
0.0485 (  0.0%)    InferWidths
0.3083 (  0.2%)    InferResets
0.0095 (  0.0%)      (A) circt::firrtl::InstanceGraph
0.0105 (  0.0%)    PrefixModules
0.3344 (  0.3%) …
```
=> [Namespace] Improve newName trials by skipping trivially used names

lib/Dialect/FIRRTL/Import/FIRAnnotations.h, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Import/FIRParserAsserts.cpp, test/Dialect/FIRRTL/parse-basic.fir
This commit first moves `foldWhenEncodedVerifOp` logic into post parse
processing to restructure operations without fear. Next, foldWhenEncodedVerifOp
is modified to handle printf op not at block's begin. For example,
```scala
circuit Foo:
module Foo :
input cond: UInt<1>
input enable: UInt<1>
input io : {clock:Clock}
when cond :
printf(io.clock, enable, "assert: bar")
```
`circt-translate --import-firrtl` now generates expected IR.
```mlir
firrtl.module @Foo(in %cond: !firrtl.uint<1>, in %enable: !firrtl.uint<1>, in %io: !firrtl.bundle<clock: clock>) {
%0 = firrtl.subfield %io(0) : (!firrtl.bundle<clock: clock>) -> !firrtl.clock
%1 = firrtl.not %cond : (!firrtl.uint<1>) -> !firrtl.uint<1>
firrtl.assert %0, %1, %enable, " bar"  {eventControl = 0 : i32, isConcurrent = true}
}
``` 
will …
=> [FIRRTL] Make foldWhenEncodedVerifOp handle PrintOp even when they are not at a block begin

lib/Dialect/SV/Transforms/SVExtractTestCode.cpp, test/Dialect/SV/hw-extract-test-code.mlir
SFC regards printf operations whose messages have specific prefixs
like "assert:", "assume:" or "cover" as assert/assume/cover
operations. This commits makes MFC align with that behavior. More
specifically,
* sv.fatal => assert
* sv.error/~~sv.fwrite~~ starts with "assert:" or "Asserion failed" => assert
* ~~sv.fwrite starts with "assume:" => assume~~
* ~~sv.fwrite starts with "cover:" => cover~~
=> [SVExtractCode] Add missing assert operations

docs/RationaleHW.md, include/circt/Dialect/HW/HWAttributesNaming.td, include/circt/Dialect/HW/HWStructure.td, lib/Dialect/HW/HWAttributes.cpp, lib/Dialect/HW/HWOps.cpp, test/Dialect/HW/basic.mlir, test/Dialect/HW/errors.mlir
Add a new operation `GlobalRef` to `HW` dialect, that will eventually replace `FIRRTL::NonLocalAnchor`. 
`GlobalRef` can be used to identify a unique instance path of an operation globally.
This is part of the plan to move the `firrtl.nla` to `HW` dialect and use it for all 
metadata emission.
Part of the PR :https://github.com/llvm/circt/pull/2252
=> [HW] Add a new op HW::GlobalRef, to replace the FIRRTL::NonLocalAnchor

include/circt/Scheduling/Algorithms.h, lib/Scheduling/SimplexSchedulers.cpp, lib/Scheduling/TestPasses.cpp
The most significant change here is the support solving a tableau with multiple objective rows.
**Why?** The upcoming modulo scheduling heuristic needs ASAP and ALAP times for ops in the partial schedule, and computing these all at once be using a suitable second objective functions is the elegant way to do it.
**How?** After changing the order of the objective rows, we may need to restore "primal feasibility", which means that the column vectors in the "objectives-part" of the tableau must be made lexico-positive through pivot operations.
Additionally, this sets up the boilerplate for the modulo scheduler, and includes a few quality-of-life improvements in the simplex framework itself.
=> [Scheduling] Prepare simplex implementation for the modulo scheduler.

lib/Scheduling/SimplexSchedulers.cpp, test/Scheduling/modulo-problems.mlir
This adds a heuristic modulo scheduler, based on the papers by de Dinechin, but a bit simpler, because our `ModuloProblem` per definition only contains fully-pipelined operators.
I think this algorithm makes a good reference/fall-back scheduler for us because it doesn't use backtracking (cannot get stuck!) and doesn't need a range of candidate IIs to be determined beforehand. The flip side of this approach is that it increases the II to resolve non-trivial resource conflicts.
=> [Scheduling] Implement de Dinechin's "fast" modulo scheduler.

test/firtool/optimizations.mlir, tools/firtool/firtool.cpp
Some canonicalizers create new sv.if ops. As a result
we get redundant if statement in output verilog.
This commit fixes the issue by moving HWCleanup to the later.
Will close https://github.com/llvm/circt/issues/2393
=> [FIRTOOL] Move HWCleanup after canonicalizer

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/canonicalization.mlir, test/Dialect/FIRRTL/lower-types.mlir
This commit adds new operation `multibit_mux` to make subaccess lowering
more efficient. Subaccess ops are currently lowered into mux chains but in HW/Comb dialect
they are pulled back to array_create + array_get. `multibit_mux` will be directly lowered
into array_create + array_get at LowerToHW.
This commit containts parser/printer, folder,
LowerTypes and LowerToHW change. multibit_mux operations are
created only at subaccess lowering in LowerTypes. 
This speeds up entire process after LowerTypes  5%~10% for large circuits.
Will close https://github.com/llvm/circt/issues/1617.
Note that this is not NFC because of mux canonicalizations. 
For example, 
```scala
circuit B:
module B :
input sel : UInt<2>
output bar : UInt<1>
wire foo: UInt<1>[4]
foo[0] <= UInt<1>(1)
foo[1] <= UInt<1>(0) …
```
=> [FIRRTL] Add multibit_mux op and lowerings

lib/Dialect/SV/Transforms/HWCleanup.cpp, test/Dialect/SV/hw-cleanup.mlir
This commit changes the visiting order of simplifications to handle
nested regions properly. Currently `runOnGraphRegion` executes the
following procedure:
```
for op in body:
recurseToSubegions(op)
mergeIfPossible(op)
```
This commit modifies the procedure like this:
```
for op in body:
mergeIfPossible(op)
for op in body:
recurseToSubregions(op)
```
This effectively handles nested regions. Interestingly, this also
makes `opsToRevisitRegionsIn` unnecessary because we merge 
the outer level first. Hence we can remove `shallow` flag as well. 
Will close https://github.com/llvm/circt/issues/2394
=> [HWCleanup] Change the order of simplifications

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp, test/Dialect/FIRRTL/grand-central-errors.mlir, test/Dialect/FIRRTL/grand-central.mlir
This commit tries to annotate AugmentedGroundTypeAttr to non-ground
types. First, I changed the element type of leafMap to be FieldRef
so that we can annotate to subelements. And `computeField` and
`traverseField` are modified to traverse the path represented by `fieldID`.
Will close https://github.com/llvm/circt/issues/2377
=> [GrandCentral] Allow AugmentedGroundTypeAttr to annotate aggregate types

lib/Conversion/ExportVerilog/ExportVerilogInternals.h, test/Conversion/ExportVerilog/sv-dialect.mlir
This commit adds IndexedPartSelectInoutOp to `isExpressionAlwaysInline`
which was missing.
=> [ExportVerilog] Add IndexedPartSelectInoutOp to `isExpressionAlwaysInline`

include/circt/Dialect/SV/SVExpressions.td, test/Conversion/ExportVerilog/sv-dialect.mlir
In aggregate preservation mode, GrandCentral may create VerbatimExpr ops
with aggregate types. This commit allows verbatim to have non-integer type.
I think it is not necessary to limit verbatim to have integer types.
=> [SV] Allow verbatim to have non-integer type

lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, test/Conversion/HandshakeToFIRRTL/test_instance.mlir, test/Conversion/HandshakeToFIRRTL/test_materialization.mlir
Essentially a NFC; FIRRTL lowering will be invalid if forks/sinks are not materialized.
=> [HandshakeToFIRRTL] Ensure materialized IR before conversion

include/circt/Dialect/MSFT/MSFTOps.td, lib/Dialect/MSFT/MSFTOps.cpp, lib/Dialect/MSFT/MSFTPasses.cpp, test/Dialect/MSFT/partition.mlir
The design partitioning pass used to build HWModuleOps. The new wire
cleanup passes, however, will be operating on the design partitions so
the modifying extensions will come in handy.
Adds the necessary builder methods for creating from C++.
=> [MSFT] Use MSFTModuleOp for design partitions

lib/Dialect/Handshake/Transforms/Buffers.cpp, test/Dialect/Handshake/compose-buffers.mlir
Due to the previous implementation of this function being based on a graph traversal which stopped at buffer ops, running bufferAllStrategy did not actually "buffer all" unbuffered channels, if some buffers already existed.
This commit simplifies bufferAllStrategy to do what is promised through iterating over all operation and adding buffers on unbuffered uses of each ops' results.
=> [Handshake] Always add buffers to unbuffered channels in bufferAllStrategy

frontends/PyCDE/src/pycde/attributes.py, frontends/PyCDE/src/pycde/devicedb.py, frontends/PyCDE/src/pycde/instance.py, include/circt-c/Dialect/MSFT.h, include/circt/Dialect/MSFT/MSFTAttributes.td, integration_test/Bindings/Python/dialects/msft.py, lib/Bindings/Python/MSFTModule.cpp, lib/CAPI/Dialect/MSFT.cpp, lib/Dialect/MSFT/DeviceDB.cpp, lib/Dialect/MSFT/MSFTAttributes.cpp, lib/Dialect/MSFT/MSFTPasses.cpp, test/Dialect/MSFT/location.mlir, test/Dialect/MSFT/translate-errors.mlir
Previously, a sub-path could be specified by encoding it in the name
of the attribute using a certain scheme. This is brittle and
non-standard. To make this more natural and robust, the sub-path is
added as a field of the attribute definition as a StringRef. It is not
required, in which case an empty StringRef can be used. The attribute
name for placement attributes is no longer used in any logic.
=> [MSFT] Add optional sub-path to PhysLocationAttr.

include/circt/Dialect/FIRRTL/FIRRTLStatements.td, test/Dialect/FIRRTL/test.mlir
A minimal semantics value probe operation which allows extracting values out of a module without needing to route each through a symboled entity which restricts transformation.
This will be used for binds and GrandCentral views.
=> [FIRRTL] Value probe operation

include/circt/Dialect/Handshake/HandshakeOps.td, include/circt/Dialect/Handshake/Visitor.h, lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, lib/Conversion/StandardToHandshake/StandardToHandshake.cpp, lib/Dialect/Handshake/HandshakeOps.cpp, test/Conversion/HandshakeToFIRRTL/test_select.mlir, test/Conversion/StandardToHandshake/test-simple-ops.mlir, test/Conversion/StandardToHandshake/test16.mlir, test/Conversion/StandardToHandshake/test17.mlir, test/Conversion/StandardToHandshake/test18.mlir, test/Conversion/StandardToHandshake/test20.mlir, test/Conversion/StandardToHandshake/test21.mlir, test/Conversion/StandardToHandshake/test4.mlir, test/Conversion/StandardToHandshake/test6.mlir
The select operation will select between two inputs based on an input conditional. The select operation differs from a mux in that:
1. both operands must be valid before the operation can transact
2. both operands will be transacted once one of them is selected
We previously lowered select operations directly to mux'es, however, this is incorrect. Since a mux will only transact the selected input, the other input (and the entire upstream path that generates the input) will be left stuck, waiting for the mux to transact.
=> [Handshake] Add new `select` operation

include/circt/Dialect/MSFT/MSFTOps.h, include/circt/Dialect/MSFT/MSFTOps.td, lib/Dialect/MSFT/MSFTOps.cpp, lib/Dialect/MSFT/MSFTPasses.cpp, test/Dialect/MSFT/partition.mlir
We were fixing up the function type, but neglected to fix the `argNames`
and `resultNames` attributes. This did not affect functional
correctness, "just" the port names.
=> [MSFT] Fix naming issue in `MSFTModuleOp::removePorts`

include/circt/Dialect/Handshake/HandshakeCanonicalization.td, include/circt/Dialect/Handshake/HandshakeOps.td, include/circt/Dialect/Handshake/HandshakePasses.h, include/circt/Dialect/Handshake/HandshakePasses.td, lib/Dialect/Handshake/HandshakeOps.cpp, lib/Dialect/Handshake/Transforms/CMakeLists.txt, lib/Dialect/Handshake/Transforms/Materialization.cpp, test/Conversion/StandardToHandshake/test_source_constants.mlir, test/Dialect/Handshake/canonicalization.mlir
In trying to get function pipelining to work, it finally seems like we've found the issue for why this hasn't been working. If we keep simple merges, and then add buffers to their outputs, function pipelining looks to be working.
This commit allows simple merges in canonical handshake IR, but keeps the option of removing them through a separate pass. After buffer insertion, the merges will be redundant, but we must keep them (at least for now) to guide buffer insertion.
=> [Handshake] Allow simple merges in canonical form

include/circt/Dialect/FIRRTL/FIRRTLAttributes.td, include/circt/Dialect/FIRRTL/FIRRTLStructure.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/Export/FIREmitter.cpp, lib/Dialect/FIRRTL/FIRRTLAttributes.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir, test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/parse-basic.fir
Add HW Dialect's ParamDeclAttr to the FIRRTL Dialect.  This commit only
adds this attribute, but does not use it.  This commit is part of a
series of commits that migrate FIRRTL external modules to use HW-like
parameters.
Change FIRRTL's ExtModule to use ParamDeclAttr for parameter storage as
opposed to using a dictionary.  Modify parsing/printing to put
parameters in a carat-delimited area before ports (just like how HW
Dialect does this).
This makes NO modifications to the way ExtModule is represented.
Parameter values are still stored on the ExtModule and not on the
instantiation.  This will be changed in a later commit.
=> [FIRRTL] Add ParamDeclAttr, use for FExtModule

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-locations.fir
This is an experiement to add an implicit CSE for subindexes and
subfields to the FIRRTL parser.  Due to the nature of the FIRRTL textual
format, we create an incredible number of these things which slows down
the initial IR generation.  On my laptop this sped up parsing a test case from
13-15 second to 8-9 seconds.  Still haven't finished testing this...
=> [FIRRTL] try adding a subaccess cache to the fir parser

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
Add handling of Chisel's "forceName" API during FIRRTL Dialect to HW
Dialect conversion.  This can be used to guarantee that an instance has
a specific name.  The full Chisel API can be used to also force the
names of signals, but this is not supported.
Note: this patch is _not_ enough to handle our uses of ForceNameAnnotation.  Currently, we use this to correct names after inlining.  There is a separate issue where non-local annotations (NLAs) are not properly updated by FIRRTL's module inliner.  I'm working on fixing this.
=> [LowerToHW] Support ForceNameAnnotation instances

test/circt-reduce/memory-stubber.mlir, tools/circt-reduce/Reduction.cpp
This adds some additional casting and proper connections to the memory
outputs when it is an aggregate type.
@fabianschuiki The test probably needs a cleanup, but is this sort of approach okay?
Here is the output of the testcase fed back though `circt-translate --export-firrtl`:
```
circuit Basic :
module Basic :
input wAddr : UInt<4>
input wEn : UInt<1>
input wMask : { a : UInt<1>, b : UInt<1> }
input wData : { a : UInt<8>, b : SInt<8> }
output out0 : { a : UInt<8>, b : SInt<8> }
output out1 : { a : UInt<8>, b : SInt<8> }
wire memory_r0 : { addr : UInt<4>, en : UInt<1>, clk : Clock, flip data : { a : UInt<8>, b : SInt<8> } } @[<stdin> 4:20]
memory_r0.data.a is invalid @[<stdin> 8:7]
memory_r0.data.b is invalid @[<stdin> 11:7]
wire memory_r1 : { addr : UInt<4>, en : …
```
=> [Reducer][FIRRTL] Fix memory stubber for memories with bundles

lib/Conversion/ExportVerilog/PrepareForEmission.cpp, test/Conversion/ExportVerilog/disallow-local-vars.mlir
This commit fixes the crash of disallowLocalVars mode for the IR with
array_index_inout/struct_field_inout and sv.read_inout, for example: 
```mlir
// circt-opt --lowering-options=disallowLocalVariables --export-verilog
hw.module @Foo(%clock: i1) {
%false = hw.constant false
%c0_i16 = hw.constant 0 : i16
%status_regs = sv.reg : !hw.inout<array<1xi32>>
sv.always posedge %clock  {
%0 = sv.array_index_inout %status_regs[%false] : !hw.inout<array<1xi32>>, i1
%1 = sv.read_inout %0 : !hw.inout<i32>
%2 = comb.extract %1 from 0 : (i32) -> i16
%3 = comb.concat %c0_i16, %2 : i16, i16
sv.passign %0, %3 : i32
}
}
```  
Currently `hoistNonSideEffectExpr` doesn't hoist inouts
because they are considered to be lvalues
(hence `%0` in the example is not hoisted).
This is true only if they are not read. …
=> [ExportVerilog] Make `hoistNonSideEffectExpr` hoist inout chains

lib/Conversion/StandardToHandshake/StandardToHandshake.cpp
This has been a long-standing to-do for me; the intention of this commit is to start removing lowering state from within the IR, and make it explicitly managed. In the long term, this intends to remove all of the "helper values" and assumptions being placed on the existence values operands at various points during lowering - something which i don't see as maintainable nor extensible.
One of the first issues that is tackled through this is managing the "block entry control" values. Previously, this was assumed to be any `control_merge` operation that existed within a basic block or the start op for an entry block (an assumption which is no longer valid in some stuff i'm working on locally). With this, passes can now just query the state for the entry value, and the entry value can be …
=> [StandardToHandshake] Initial commit for stateful std-to-hs lowering

include/circt/Dialect/Handshake/HandshakeCanonicalization.td, include/circt/Dialect/Handshake/HandshakeOps.td, lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp, lib/Dialect/Handshake/HandshakeOps.cpp, test/Conversion/HandshakeToFIRRTL/test_buffer.mlir, test/Dialect/Handshake/errors.mlir
This commit adds support for buffer initialization. A list of integer values may be provided to sequential buffers, which will be made the reset values of the buffer registers when lowering to hardware.
=> [Handshake] Support buffer initialization

include/circt/Dialect/FIRRTL/FIRRTLStructure.td, include/circt/Dialect/FIRRTL/Passes.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/Import/FIRAnnotations.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp, lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, lib/Dialect/FIRRTL/Transforms/PrefixModules.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-errors.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/annotations-errors.fir, test/Dialect/FIRRTL/annotations.fir, test/Dialect/FIRRTL/annotations.mlir, test/Dialect/FIRRTL/emit-omir.mlir, test/Dialect/FIRRTL/grand-central-errors.mlir, test/Dialect/FIRRTL/imconstprop.mlir, test/Dialect/FIRRTL/prefix-modules.mlir, test/Dialect/FIRRTL/test.mlir
This change will update the `FIRRTL::NonLocalAnchor` to use an 
array of `InnerRefAttr` instead of separate arrays of modules and local names.
The `InnerRefAttr` specifies the module and the name within the module.
This is part of the changes from https://github.com/llvm/circt/pull/2252
=> [FIRRTL] Update NonLocalAnchor to use InnerRef

include/circt/Dialect/HW/HWOps.h, lib/Dialect/HW/HWOps.cpp
The `getModulePortInfo` was dropping the symbols, when constructing the `PortInfo`.
Parse the `hw.exportPort` to get the symbols on ports.
There is no client for this change right now.
The PR when we added the port symbols, (https://github.com/llvm/circt/commit/755ea04229cb26d86885c39fc0e9c1620149b4d5)
=> [HW] Fix PortInfo construction to get the symbols. NFC

lib/Dialect/FIRRTL/Import/FIRParser.cpp
Use a reference to the namespace instead of invoking the copy constructor.
The entire module body is under a single namespace, so it makes sense to maintain a single copy of the namespace and pass reference to it. Instead of invoking the copy constructor for every statement block.
This is a fix to the performance regression, https://github.com/llvm/circt/issues/2440
=> [FIRRTL][Parser] Use reference to namepsace, instead of copying it

include/circt/Dialect/Handshake/HandshakeCanonicalization.td, include/circt/Dialect/Handshake/HandshakeOps.td, include/circt/Dialect/Handshake/HandshakePasses.h, include/circt/Dialect/Handshake/HandshakePasses.td, lib/Dialect/Handshake/HandshakeOps.cpp, lib/Dialect/Handshake/Transforms/Materialization.cpp, test/Conversion/StandardToHandshake/test_source_constants.mlir, test/Dialect/Handshake/canonicalization.mlir
This reverts commit 8e4467132c364c86e81b92109e9def223c5847dd.
The problem which I thought this commit (partially) solved is actually solved by https://github.com/llvm/circt/pull/2444. In light of that, this commit is technically a regression and should be reverted.
=> Revert "[Handshake] Allow simple merges in canonical form (#2430)"

.github/workflows/buildAndTest.yml
Stumbled across this [here](https://github.com/llvm/circt/runs/4826212347): The changes to `test/lit.site.cfg.py.in` trigger the linting check, but `yapf` complains that the file is not syntactically correct (due to the `@REPLACEMENT_TAGS@`).
=> [CI] Prevent yapf from linting .py.in files.

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/InferReadWrite.cpp, test/Dialect/FIRRTL/inferRW.mlir, tools/firtool/firtool.cpp
Add a `FIRRTL` pass to merge the read and write ports of a memory, if their enable condition is mutually exclusive.
This is an implementation of the Scala pass, `InferReadWrite` https://github.com/chipsalliance/firrtl/blob/v1.4.3/src/main/scala/firrtl/passes/memlib/InferReadWrite.scala
The heuristic used to infer mutually exclusive conditions, first constructs the `And` expression tree for 
both the read and write enable conditions. 
The conditions are mutually exclusive if any of the product terms is a complement of each other.
The pass also has to check if both the ports are connected to the same `clock`.
This pass only looks for `Seq` memories, that is memory with read and write latency of 1, and exactly two ports.
=> [FIRRTL] Add InferReadWrite Pass

CMakeLists.txt, include/circt/Scheduling/Algorithms.h, lib/Scheduling/CMakeLists.txt, lib/Scheduling/LPSchedulers.cpp, lib/Scheduling/TestPasses.cpp, test/Scheduling/or-tools/problems.mlir, test/lit.cfg.py, test/lit.site.cfg.py.in
This PR makes solvers from OR-Tools optionally available in CIRCT. Note that binary distributions of OR-Tools don't seem to supply the required CMake config files. To that end, the library has to be build from source, e.g. using the commands as in https://github.com/circt/images/pull/13. I'll add a paragraph to the getting started doc and a script in `utils` in a later PR.
As a simple test case, I've implemented a scheduler for the basic `Problem`.
=> [Scheduling] Set up infrastructure for using OR-Tools' solvers.

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
Metadata files should not contain location information. 
Use `UnknownLoc` with the `verbatimOp`
=> [FIRRTL] Remove location information from Metadata

include/circt-c/Dialect/MSFT.h, include/circt/Dialect/MSFT/DeviceDB.h, integration_test/Bindings/Python/dialects/msft.py, lib/Bindings/Python/MSFTModule.cpp, lib/CAPI/Dialect/MSFT.cpp, lib/Dialect/MSFT/DeviceDB.cpp
This allows the user to specify a walk order through the placements'
columns, rows, and numbers at each location. If specified, the order
is used to sort the indices into the placements' maps. Otherwise, the
order is undefined as before.
=> [MSFT] Add walk order option when walking placements.

lib/Dialect/MSFT/MSFTOps.cpp, lib/Dialect/MSFT/MSFTPasses.cpp, test/Dialect/MSFT/partition.mlir
For module outputs, if multiple `msft.output` operands are the same, eliminate toe duplicates and update the instantiations. For input ports, if the single instantiation drives multiple input ports with the same value, merge them.
One more step towards #2365.
=> [MSFT] Merge input and output ports which are driven by the same signal

include/circt/Dialect/MSFT/MSFTOps.td, integration_test/Bindings/Python/dialects/msft.py, lib/Bindings/Python/circt/dialects/_msft_ops_ext.py, lib/Dialect/MSFT/DeviceDB.cpp, lib/Dialect/MSFT/ExportQuartusTcl.cpp, lib/Dialect/MSFT/MSFTPasses.cpp, test/Dialect/MSFT/location.mlir
The ExternEntityOp is designed to model something conceptually similar
to an external module, but it is intentionally opaque. It could be an
external instance, or anything else we might want to reserve placement
locations for. It has a symbol name, and otherwise stores an arbitrary
attribute to contain any other metadata.
These ops can be placed by creating a GlobalRefOp that refers to their
symbol with a FlatSymbolRefAttr. The PlacementDB treats them just like
any other op, but in ExportQuartusTcl, we explicitly ignore them.
=> [MSFT] Add ExternEntityOp to model external entities in PlacementDB.

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
This changes one call to `getSubTypeByFieldID`, which is a binary
search, with `getElementType`, since we already have the element index.
=> [FIRRTL][GrandCentral] reuse element index in field lookup

include/circt/Dialect/FIRRTL/InstanceGraph.h, lib/Dialect/FIRRTL/InstanceGraph.cpp
Using `StringAttr`s instead of `StringRef`s is a pointer comparison
instead of a string comparison.
=> [FIRRTL][InstanceGraph] look up using StringAttr instead of StringRef

include/circt/Dialect/FIRRTL/FIRRTLTypes.h, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/FIRRTLTypes.cpp, lib/Dialect/FIRRTL/Transforms/BlackBoxMemory.cpp, lib/Dialect/FIRRTL/Transforms/InferResets.cpp, lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
This adds `begin()` and `end()` functionality to `BundleType`.  These
functions are short hand for `bundleType.getElements().begin()`.
=> [FIRRTL] add `BundleType::begin()` and `end()`

include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp
This adds a function to get the module name as an attribute instead of a
string ref.
=> [FIRRTL] Add `FModuleLike::moduleNameAttr()`

include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h, lib/Dialect/FIRRTL/Transforms/PrefixModules.cpp
This is a shorthand for `anno.getDict().begin()`.
=> [FIRRTL] Add `Annotation::begin()` and `end()`

include/circt/Dialect/FIRRTL/InstanceGraph.h, include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/WireDFT.cpp, test/Dialect/FIRRTL/wire-dft-errors.mlir, test/Dialect/FIRRTL/wire-dft.mlir, tools/firtool/firtool.cpp
This adds a pass to wire the "test_en" port of all modules named
EICG_Wrapper to a signal marked by the "DFTEnable" annotation.  This is
used to support Design For Testing clock gating.
=> [FIRRTL] add WireDFT pass 

include/circt/Dialect/FIRRTL/FIRRTLTypes.h, lib/Dialect/FIRRTL/FIRRTLTypes.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/InferResets.cpp, lib/Dialect/FIRRTL/Transforms/InferWidths.cpp
StringAttr comparisons are more efficient than regulare string
comparisons.  In the future we should look into using a binary search
when doing a string search.
=> [FIRRTL] Add functions to look up bundle fields by StringAttr

lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp
When we create an `AnnotationSet` from an array of `Annotation`s, we
were accidentally creating the annotation using the only dictionary of
the annotation, instead of the underlying attribute.  This would have
the effect of taking `#firrtl.subAnnotation<>` and turning them into
regular annotations.  This was missed in
9e74f40f82fe372299a99b92f3474c6034a43229.
=> [FIRRTL] Fix bug when creating `AnnoSet` from `ArrayRef<Annotation>`

include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h
This sets the `AnnotationSetIterator`'s `PointerT` and `ReferenceT` all to
`Annotation`.  Without this, `llvm::enumerate` complains that `*it` does
not return a `Annotation &`, since it returns a `Annotation`.  This is
the same thing that `AttributeElementIterator` does.
=> [FIRRTL] Fix AnnotationSet iterator to work with `llvm::enumerate`

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Dialect/Calyx/CalyxOps.cpp, lib/Dialect/Calyx/Export/CalyxEmitter.cpp, test/Conversion/SCFToCalyx/convert_controlflow.mlir, test/Conversion/SCFToCalyx/convert_memory.mlir, test/Conversion/SCFToCalyx/convert_simple.mlir, test/Dialect/Calyx/emit.mlir
This adds back the functionality, but uses a SmallVector<StringRef>
for the ComponentOp's elided attrs.
=> Re-land "[Calyx] Support toplevel attribute on ComponentOp in emitter."

include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h, lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp
Right now `AnnotationSet` assumes that only `FModuleOp`s have port
annotations, when they can actually be applied to both instance ops and
memory ops.  Since they all use the same `portAnnotations` attribute,
this can share a common code path.
=> [FIRRTL][AnnotationSet] Allow application to memory ports

include/circt/Dialect/FIRRTL/FIRRTLTypes.h, lib/Dialect/FIRRTL/FIRRTLTypes.cpp, lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp
We have a function to return the type of a subfield using a fieldID.
The problem with this function is that it only strips a single layer at
a time from aggregate type, and it doesn't return the index of the
target element or its field ID.
This changes the functionality to return both the subtype, and the next
fieldID.  This makes it easier to iteratively follow subtypes all the
way to the final type.
This also adds a function to return the type targeted by the fieldID and
skip manually walking the data structures.
=> [FIRRTL] Add ability to get the type ultimately targeted by a fieldID

frontends/PyCDE/src/pycde/devicedb.py, frontends/PyCDE/src/pycde/system.py, frontends/PyCDE/test/instances.py, include/circt/Dialect/MSFT/MSFTOps.td, integration_test/Bindings/Python/dialects/msft.py, lib/Bindings/Python/circt/dialects/_msft_ops_ext.py, lib/Dialect/MSFT/DeviceDB.cpp, lib/Dialect/MSFT/ExportQuartusTcl.cpp, lib/Dialect/MSFT/MSFTPasses.cpp, test/Dialect/MSFT/location.mlir
This adds a new API to the PyCDE PlacementDB to reserve a placement by
adding an EntityExternOp with an appropriate path. This exists out of
band of the existing AppID mechanism to place internal entities.
=> [PyCDE] Support reserving placements with EntityExternOp.

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/disallow-local-vars.mlir, test/Conversion/ExportVerilog/hw-dialect.mlir, test/Conversion/ExportVerilog/sv-dialect.mlir
Currently we give up to emit inline if there exists an user in a different block. 
It is not the case if the operation is duplicable (Constant or nullary verbatim).
This fixes https://github.com/llvm/circt/issues/2483 for constant operations.
=> [ExportVerilog] Don't emit temporay wires for duplicatable operations even with a user in a different block

include/circt/Dialect/HW/HWMiscOps.td, lib/Dialect/HW/HWOps.cpp, test/Dialect/HW/canonicalization.mlir
This commit adds the following folder and canonicalization:
* folder `bitcast(%a) : A -> A ==> %a`
* canonicalization 
```
%b = bitcast(%a) : A -> B
bitcast(%b) : B -> C
=>  bitcast(%a) : A -> C
```
=> [HW] Add bitcast fold and canonicalization

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir
This PR comes from https://github.com/llvm/circt/pull/2512#discussion_r791199452.
This commit modifies ExportVerilog to force to emit temporary wires for verbatim with long string.
More specifically, if verbatim ops have string with >32 size, they are spilled.    
```mlir
%c2 = sv.verbatim.expr "VERY_LONG_LINE_VERY_LONG_LINE_VERY_LONG_LINE_VERY_LONG"
fwrite "%d" %c2
==>
wire _T  = "VERY_LONG_LINE_VERY_LONG_LINE_VERY_LONG_LINE_VERY_LONG";
fwrite "%d" _T
```
There are two arguable things:  
* Magic number (32 in this case, I picked so that it doesn't affect current outputs too much) 
* How we should handle verbatim ops with symbol substitution
=> [ExportVerilog] Force to emit temporary wires for long verbatim

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/disallow-local-vars.mlir, test/Conversion/ExportVerilog/hw-dialect.mlir, test/Conversion/ExportVerilog/sv-dialect.mlir, test/Conversion/ExportVerilog/verilog-basic.mlir
This commit allows operations to be inlined if they are defined at top-level because
every user can refer regardless of wherever they are.
Close https://github.com/llvm/circt/issues/2483
=> [ExportVerilog] Allow non-local operations to be inlined even with users at different blocks

include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h, lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, test/Dialect/FIRRTL/annotations.mlir
This moves the `AnnoTarget` class out of the `LowerAnnotations` pass.
This is so that it can be used in the `Dedup` pass.  The point of this
class is to track what an annotation is targeting, namely a certain op
or a port on an op.
The class was changed to use sub-types, representing ports with
`PortAnnoTarget`s or ops with `OpAnnoTarget`s.  The base class
`AnnoTarget` can be used with `TypeSwitch` to downcast to the derived
type.
The `FieldID` was moved out of the `AnnoTarget` class, since the
`Annotation` class already captures this information. `LowerAnnotations`
required some larger changes to work with this.
This also fixes a bug in `LowerAnnotations` where it would only resolve
1 field deep of nested aggregate types.
=> [FIRRTL] Move AnnoTarget out of LowerAnnotations, fix bug

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/RemoveUnusedPorts.cpp, test/Dialect/FIRRTL/remove-unused-ports.mlir, test/firtool/chirrtl.fir, tools/firtool/firtool.cpp
This commit adds RemoveUnusedPortsPass to prune unused ports.
RemoveUnusedPortsPass removes unused ports from the bottom of the
instance graph so that we can remove ports optimally. Ports are
not removed if they have annotations or inner sym.
Close https://github.com/llvm/circt/issues/2420
=> [FIRRTL] Add RemoveUnusedPortsPass

include/circt/Dialect/HW/HWTypes.h, include/circt/Dialect/SV/SVInOutOps.td, lib/Dialect/HW/HWOps.cpp, lib/Dialect/SV/SVOps.cpp, lib/Dialect/SV/SVTypes.cpp, test/Conversion/ExportVerilog/hw-typedecls.mlir
This commit modifies SV inout operations to use `hw::type_cast` to
cast types so that they can be used with type alias.
Close https://github.com/llvm/circt/issues/2529
=> [SV] Support inout operations with aggregate type alias

include/circt-c/Dialect/MSFT.h, include/circt/Dialect/MSFT/DeviceDB.h, integration_test/Bindings/Python/dialects/msft.py, lib/Bindings/Python/MSFTModule.cpp, lib/CAPI/Dialect/MSFT.cpp, lib/Dialect/MSFT/DeviceDB.cpp
These complement the main add* APIs for putting entities into the
database and support moving entities around or removing entities
entirely after any initial placements.
=> [MSFT] Add PlacementDB APIs for removing and moving entities.

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_controlflow.mlir, test/Conversion/SCFToCalyx/convert_memory.mlir, test/Conversion/SCFToCalyx/convert_pipeline.mlir
Previously, all iter arg registers were assigned in a single
group. This prevents Calyx from being able to infer static timing for
this group. While we could enhance the downstream analysis, this patch
makes the potential parallelism explicit in the IR when multiple
registers are initialized. With this, Calyx is able to infer static
timing for the initialization group.
=> [SCFToCalyx] Support parallel loop iter arg register initialization.

lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp, test/Dialect/FIRRTL/SFCTests/emit-omir.fir
`EmitOMIR` pass was not handling the annotation on ports. 
This commit, will emit the OMIR for ports also, instead of printing `OMDeleted`
=> [FIRRTL] Handle OMIR on module ports

include/circt/Dialect/Calyx/CalyxControl.td, lib/Dialect/Calyx/CalyxOps.cpp, test/Conversion/SCFToCalyx/convert_memory.mlir, test/Dialect/Calyx/canonicalization.mlir
This pattern canonicalizes away a ParOp in cases where
1. it is nested within a seq structure
2. it enables only a single group.
=> [Calyx] Canonicalize simple Par ops

.github/workflows/nightlyIntegrationTests.yml, .github/workflows/shortIntegrationTests.yml
... to make OR-Tools available in integration tests.
The v10.1 image fixes the configuration problem in the nightly tests observed in #2479, so this should be good to go now.
=> Re-land "[CI] Use most recent integration test image. (#2474)"

include/circt/Dialect/StaticLogic/StaticLogic.td, lib/Conversion/AffineToStaticLogic/AffineToStaticLogic.cpp, lib/Dialect/StaticLogic/StaticLogicOps.cpp, test/Conversion/SCFToCalyx/convert_pipeline.mlir, test/Dialect/StaticLogic/errors.mlir, test/Dialect/StaticLogic/round-trip.mlir
This is an essential result of scheduling, and should be captured in
this IR. It is a property of the pipeline stage, not the operations or
operator types they might map to. This information, with the pipeline
II, is needed by lowering passes to generate the appropriate
cycle-level timings. Specifically, it will be used to determine which
stages need to be considered in the pipeline prologue and epilogue.
=> [StaticLogic] Add start time attribute to PipelineStageOp.

lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp
`EmitOMIR.cpp` was removing `circt.nonlocal` annotations but not deleting the `NonLocalAnchor` operations.
This commit adds the removed NLA reference to the list of NLAs that need to be removed.
The assumption here is that NLAs are not reused, that is there is only one client for each NLA.
Not adding any lit test to check for this, since the NLA verifier should error out if we miss to remove the op.
=> [FIRRTL] Remove unused NLAs from OMIR

include/circt/Dialect/FIRRTL/FIRRTLOps.h
This commit adds a data structure to record and lookup an Inner symbol and the
corresponding operation. It can be used when the list is populated first,
then sorted and then only used for lookup. 
The assumption is that the list must be sorted, before any lookup.
This does not handle duplicate entries explicitly. 
The idea is based on an observation that Dense arrays can be efficient lookup
structures. Especially when we have insert-phase and lookup-phase based code.
This is currently being used for NLA verification (https://github.com/llvm/circt/pull/2461).
TODO in followup PRs: 
We have to cleanup the code and make it more general. 
Also, some runtime comparisons with DenseMaps must be done, to investigate
any performance improvement.
=> [FIRRTL] Add a data structure for Inner Sym insertion and lookup. NFC.

lib/Dialect/FIRRTL/Import/FIRParserAsserts.cpp, test/Dialect/FIRRTL/parse-basic.fir
Fix a bug when parsing certain types of printf-encoded
asserts ("assert:", "assume:", "cover:" and "assertNotX:") to not add an
unnecessary format string argument.  Instead, only add argumnets after
the first argument if any exist.  The latter case is extremely rare (to
use this from the Chisel APIs you would have to hand-craft a printf
operation and not use the built-in helper utilities).
Change Chisel asserts ("Assertion failed:") to always parse as immediate
assertions.  These assertions are expected to have format string
arguments and this avoids a catch-22 with VCS lint warnings.  A
concurrent assertion can be constructed to have a format string,
however, whichever way you craft it, VCS will give you a lint warning:
Ill-advised, unsampled option A:
assert_1: assert property …
=> [FIRRTL] Fix printf-encoded lint issues

include/circt/Dialect/FIRRTL/FIRRTLStructure.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp
Add utilities for getting the leaf of a module and check if a module belongs to the NLA.
=> [FIRRTL] Add helper utilities for NLA. NFC.

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp, test/Dialect/FIRRTL/inliner.mlir
Change the ModuleInliner to generate unique symbols within a module's
namespace.  Add state/logic to the Mutable NLA utility to track renamed
symbols and use this to generate updated NLAs.
This fixes a problem where inlining could cause inner_sym collisions.
Fixes #2451.
=> [FIRRTL] Unique Symbols in ModuleInliner

include/circt/Dialect/HW/HWAggregates.td, include/circt/Dialect/HW/HWTypesImpl.td, lib/Dialect/HW/HWOps.cpp, lib/Dialect/HW/HWTypes.cpp, test/Dialect/HW/canonicalization.mlir
```
%st = hw.struct_create (%0, ...) : !hw.struct<foo: ...>
%field = hw.struct_extract %st["foo"] : ...
```
can just be `%0`.
=> [HW] StructExtractOp folder

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir, test/Conversion/ExportVerilog/sv-dialect.mlir, test/Conversion/ExportVerilog/verilog-basic.mlir, test/firtool/firtool.fir
This commit allows extract op and array_get op to be inlined even when
they have multiple uses. To prevent exponential emission, the index of
array_get must be constant.
Close #2576
=> [ExportVerilog] Inline duplicatable unary op more even with multiuses

include/circt/Dialect/FIRRTL/InstanceGraph.h, lib/Dialect/FIRRTL/InstanceGraph.cpp, lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, lib/Dialect/FIRRTL/Transforms/InferResets.cpp, lib/Dialect/FIRRTL/Transforms/RemoveUnusedPorts.cpp, lib/Dialect/FIRRTL/Transforms/WireDFT.cpp, test/Dialect/FIRRTL/wire-dft-errors.mlir
The instance graph was storing graph nodes in an array and handing out
pointers to the elements, which meant we could not properly delete nodes
from the graph without invalidating a bunch of node pointers.  To make
the instance graph more easily mutable, this changes the underlying
data structure of the graph to have stable pointers.
This change makes the instance graph follow the same model as
operations:  InstanceGraph holds a intrusive list of InstanceGraphNodes,
and InstanceGraphNodes hold an intrusive list of InstanceRecords.  The
uses are kept track of using a doubly linked list which is intrusive in
the InstanceRecord.  One benefit of using a representation similar to
MLIR operations is that we can closely match the API, which has slightly
less mental overhead when mutating the …
=> [FIRRTL][InstanceGraph] Make instance graph mutable

test/circt-reduce/port-pruner.mlir, tools/circt-reduce/Reduction.cpp
This commit adds RemoveUnusedPortsPass to reduction passes and replaces
PortPruner with RemoveUnusedPortsPass. RemoveUnusedPortsPass would be
more powerfull since it prunus ports interprocedurally.
=> [circt-reduce] Replace PortPruner with RemoveUnusedPortsPass

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir
This commit modifies name inference of temporary wires not to
add underscores to namehints.
Close #2572
=> [ExportVerilog] Don't add underscores for user specified names

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp
Use a stack rather than a queue for IMConstProp.  Improves locality.  Sees 20% performance improvement on large designs.  I don't see any dependence on worklist order for algorithmic complexity in the literature.
Minor change to not test don't touch when visiting connects.  markInstance already marks them overdefined and it's faster usually to do the merges than to test don't touch on a port.
=> [NFC,FIRRTL] Reorder worklist for IMConstProp

include/circt/Dialect/HW/HWTypesImpl.td, lib/Dialect/HW/HWTypes.cpp
This PR follows #2580 to add a `getFieldIndex(StringAttr)` method, as requested in #2585. I put `idx` and `numElems` declaration in for loop because they are only used in that scope; I hope this doesn't conflict with any coding style rules.
I am a total newbie in LLVM, MLIR and CIRCT. I'm curious why using `StringAttr` is faster than `StringRef`. Bellow is my analytics, but I'm not sure if they are the actual cause:
- Comparing `StringAttr` with `StringRef` will be comparing two `StringRef`, which is [comparing two memory sequences](https://github.com/llvm/llvm-project/blob/b0cd3abf032e01e6a8f742952e8427ad2e350a5b/llvm/include/llvm/ADT/StringRef.h#L76).
- Comparing two `StringAttr` compares two pointers because [the `Attribute` class is just a wrapper to a unique storage …
=> [HW][StructType] Add a getFieldIndex(StringAttr) method

lib/Dialect/MSFT/MSFTPasses.cpp, test/Dialect/MSFT/partition.mlir
The previous algorithm to update global refs after partitioning would
only work if the leaf entities were both tagged for placement with
global refs, and targetted to the design partition. In general, we
need to support targetting arbitrary points in the hierarchy to the
design partition, and fix up any global refs pointing to these nodes
and anything below them.
Rather than assuming we are starting from the leaf of the path in
bubbleUpGlobalRefs, we find the correct node to start from. Similarly,
in pushDownGlobalRefs, we cannot assume we are starting from the leaf,
and must find the correct point to insert the nodes.
=> [MSFT] Update partition pass global refs for inner nodes

lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp, test/Dialect/FIRRTL/blackbox-reader.mlir
In the `BlackBoxReader` pass, set the output directory for testbench modules to `../testbench`.
Runtime of pass on P550, before this commit: 
```
6.7174 (  0.9%)    6.7174 (  2.2%)    BlackBoxReader
```
Runtime with this commit: 
```
7.0718 (  0.9%)    7.0718 (  2.2%)    BlackBoxReader
0.4767 (  0.1%)    0.4767 (  0.2%)      (A) circt::firrtl::InstanceGraph
```
=> [FIRRTL] Set output directory for testbench BlackBox modules

lib/Dialect/FIRRTL/FIRRTLDialect.cpp, test/Dialect/FIRRTL/test.mlir
The FIRRTL OpAsmDialectInterface should return right after it sets the
name of any operation, instead of falling through.  Since we are now
attaching "name" attributes on to expressions, its possible that we try
to set the name attribute twice on constant operations, which triggers
an assertion in MLIR.
=> [FIRRTL] Fix IR printing assertion

lib/Dialect/SV/SVDialect.cpp, test/Conversion/ExportVerilog/disallow-local-vars.mlir, test/Conversion/ExportVerilog/hw-dialect.mlir, test/Conversion/ExportVerilog/load-dialect.mlir, test/Conversion/ExportVerilog/name-legalize.mlir, test/Conversion/ExportVerilog/sv-dialect.mlir, test/Conversion/ExportVerilog/sv-interfaces.mlir, test/Conversion/ExportVerilog/verilog-basic.mlir, test/firtool/firtool.fir
Change the name used when ExportVerilog generates a name for an unnamed
things from "_T" to "_GEN".  "_T" is currently used by Chisel for
temporaries it generates and "_GEN" is currently used by the Scala
FIRRTL Compiler for temporaries it generates.  This will benefit Chisel
users compiling with CIRCT as this will continue the clear delineation
between "Chisel generated a temporary" and "the FIRRTL compiler
generated a temporary".
Fixes #2571.
=> [ExportVerilog] Change unnamed from "_T" to "_GEN"

lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, test/Dialect/FIRRTL/annotations.mlir
When we attach non-local annotations to memory ports, since we do not
assign port symbols to the memory op, the leaf element of the anchor
should target a symbol on the memory.
The NLA verifier checks to see that there is an annotation which uses the NLA
attached to an operation.  When the annotation target is a memory port,
the NLA verifier also has to check the port annotations.  This same
logic would apply to InstanceOps, but we have decided that InstanceOp
annotations should be moved to the target module.
There was a small mistake in the LowerAnnotations pass where an `AnnoTarget`
should have been passed by reference, which resulted in memory port
annotation being attached directly to the memory instead.
The old/default annotation parsing framework is still broken: it creates
the NLA …
=> [FIRRTL] FIx memory port NLAs + verifier

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
This commit sets the `firrtl.extract.cover.extra` attribute, for `FExtModuleOp` with the `InternalVerifBlackBoxAnnotation`.
It is already being set for `FModuleOp`.
=> [FIRRTL] Set the cover attribute for extern modules

lib/Dialect/FIRRTL/Transforms/PrefixModules.cpp, test/Dialect/FIRRTL/prefix-modules.mlir
This commit fixes the `NonLocalAnchor` after the modules are cloned.
PrefixModules copies all the nonlocal annotations when a module is cloned. 
Some of the NLAs can become invalid based on the instance path.
The modules are visited in a top down order based on the Instance graph.
The algorithm maintains an invariant that the instance path is always valid till the 
module which is being traversed. Hence, for any NLA anchor that exists in the module, 
we need to ensure, that the module occurs in the NLA path. 
Any NLA, that does not contain a reference to the current module should be removed.
The `NonLocalAnchor ` utilities will be checked in as part of another PR.
=> [FIRRTL] Update NonLocalAnchors in the  prefixModules pass

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp
This commit fixes a bug in ModuleInliner, check if entry exists in map, before the lookup.
=> [FIRRTL] Add map existence check before lookup ModuleInliner

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/Dedup.cpp, test/Dialect/FIRRTL/SFCTests/dedup-errors.fir, test/Dialect/FIRRTL/SFCTests/dedup.fir, test/Dialect/FIRRTL/dedup.mlir, test/firtool/blackbox.mlir, test/firtool/memoryMetadata.fir, tools/firtool/firtool.cpp
There is still a problem with memory port annotations and NLAs that I need to think through.
@seldridge  This is rebased off of `llvm/main` now that all prerequisites of this PR have been merged. This branch has a bug-fix that was not present earlier today.  It would be a good idea to work off this branch if anyone is working on porting the SFC dedup tests.
=> [FIRRTL] Add Dedup pass

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Dialect/FIRRTL/lower-types.mlir
The `LowerTypes` pass should remove NLAs used for nonlocal `DontTouch` on Bundle fields.
1. `LowerTypes` will remove nonlocal `DontTouch` annotations and add symbol after lowering the bundle. For example, this annnotation would be dropped  , `#firrtl.subAnno<fieldID = 2, {circt.nonlocal = @nla_2, class ="firrtl.transforms.DontTouchAnnotation"}>` 
2. Dropping the `NLA` also handles the following case, when the fields of a bundle share the same `NLA`, since the symbol originally existed on the bundle, and all fields shared the symbol until `LowerTypes`.  
`%b = firrtl.wire sym @symB { annotations = {annotations = [#firrtl.subAnno<fieldID = 2, {circt.nonlocal = @nla_2, class ="firrtl.transforms.DontTouchAnnotation"}>, #firrtl.subAnno<fieldID = 4, {circt.nonlocal = @nla_2, class …
=> [FIRRTL] Remove NLAs dropped by DontTouch

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/Import/FIRParserAsserts.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/SFCTests/complex-asserts.fir, test/Dialect/FIRRTL/SFCTests/complex-assumes.fir, test/Dialect/FIRRTL/parse-basic.fir
This adds a `sv.system.sampled` operation that emits as an always-inline `$sample(...)` system function.  This is then used as the lowering for concurrent asserts coming out of FIRRTL Dialect.
Fixes #2548.
=> [ExportVerilog] Add $sampled use it in LowerToHW

include/circt/Dialect/MSFT/DeviceDB.h, include/circt/Dialect/MSFT/MSFTAttributes.td, include/circt/Dialect/MSFT/MSFTOps.h, include/circt/Dialect/MSFT/MSFTOps.td, integration_test/Bindings/Python/dialects/msft.py, lib/CAPI/Dialect/MSFT.cpp, lib/Dialect/HW/HWOps.cpp, lib/Dialect/MSFT/DeviceDB.cpp, lib/Dialect/MSFT/ExportQuartusTcl.cpp, lib/Dialect/MSFT/MSFTAttributes.cpp, lib/Dialect/MSFT/MSFTOps.cpp, lib/Dialect/MSFT/MSFTPasses.cpp, test/Dialect/MSFT/location.mlir
Keep the PhysLocation attribute for the actual physical location. Create
an op to refer to a global ref with the location attribute and the
subpath. Incremental change towards a new approach to dynamic instances.
This PR breaks tcl placement output in the way the integration test and pycde
enters the placements. Will be fixed shortly with the dynamic instance PR.
=> [MSFT] Create PhysLocation operation and use it instead of an attribute on GlobalRef

include/circt/Dialect/MSFT/MSFTOpInterfaces.h, include/circt/Dialect/MSFT/MSFTOpInterfaces.td, lib/Dialect/MSFT/MSFTOpInterfaces.cpp, lib/Dialect/MSFT/MSFTOps.cpp, test/Dialect/MSFT/dynamic_instance.mlir, test/Dialect/MSFT/opt-errors.mlir
Ops using this interface must either be in a dynamic instance op block
XOR have a symbol pointing to a global ref.
=> [MSFT] Add verifier to DynInstData op interface

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, test/Dialect/FIRRTL/imconstprop-aggregate.mlir
This is a precursor to properly handling aggregates in IMCP.  This is just enough to ensure the pass passes them through.
=> [IMCP] Mark aggregates overdefined and process them.

include/circt/Dialect/MSFT/ExportTcl.h, lib/Dialect/MSFT/ExportQuartusTcl.cpp, lib/Dialect/MSFT/MSFTPasses.cpp, test/Dialect/MSFT/translate-errors.mlir
Since DeviceDB will be re-oriented around the new dynamic instance op
and export tcl is run after lowering away the dynamic instance ops, we
can't use the DeviceDB.
=> [MSFT] [ExportTcl] Ween off of DeviceDB

lib/Dialect/FIRRTL/Transforms/EmitOMIR.cpp, test/Dialect/FIRRTL/emit-omir.mlir
Skip adding a new NLA if it already exists for an `SRAM`.
This fixes a crash with `dedup` enabled.
=> [FIRRTL] Donot add NLA for OMIR, if already exists.

lib/Dialect/FIRRTL/Transforms/Dedup.cpp, test/Dialect/FIRRTL/dedup-locations.mlir
This adds support for fusing location information when two modules are
deduplicated with each other.
=> [FIRRTL][Dedup] Merge location information

tools/firtool/firtool.cpp
This PR should resolve #2651.
Results:
```verilog
❯ .\cmake-build-debug\bin\firtool.exe .\test\firtool\firtool.fir | select -last 10
module MultibitMux(     // .\test\firtool\firtool.fir:242:10
input        a_0, a_1, a_2,
input  [1:0] sel,
output       b);
wire [2:0] _GEN = {{a_2}, {a_1}, {a_0}};      // .\test\firtool\firtool.fir:246:12
assign b = _GEN[sel]; // .\test\firtool\firtool.fir:242:10, :246:12
endmodule
❯ .\cmake-build-debug\bin\firtool.exe .\test\firtool\firtool.fir --strip-debug-info | select -last 10
module MultibitMux(
input        a_0, a_1, a_2,
input  [1:0] sel,
output       b);
wire [2:0] _GEN = {{a_2}, {a_1}, {a_0}};
assign b = _GEN[sel];
endmodule
```
=> [firtool] Add --strip-debug-info to Emit Without Source Locator Comments

.github/workflows/buildAndTestWindows.yml, utils/find-vs.ps1
MLIR/LLVM runs Windows builds with Ninja, so we should too. (Plus, it's waaayyyy faster on bigger boxes.)
Fixes #2647.
=> [Windows] Switch build from msbuild to Ninja

lib/Dialect/FIRRTL/Transforms/InferResets.cpp, test/Dialect/FIRRTL/infer-resets.mlir
When replacing RegOps with RegResetOps we need to make sure that we
transfer the inner_sym to the new operation.
=> [FIRRTL][InferResets] transfer inner sym when replacing registers
