include/circt/Dialect/HW/HWTypes.td, lib/Conversion/ImportVerilog/Expressions.cpp
https://github.com/llvm/llvm-project/compare/5689cccead7b70d8eeae4c641e8078e6d3c50b9a...c69b8c445a6b7efd29e67b665adaf04575f3ed92
=> LLVM bump to include upstream verifier performance fix.

lib/Dialect/Moore/MooreOps.cpp, lib/Dialect/Moore/Transforms/SimplifyProcedures.cpp, test/Dialect/Moore/canonicalizers.mlir, test/Dialect/Moore/mem2reg.mlir, test/Dialect/Moore/simplify-procedures.mlir, tools/circt-reduce/circt-reduce.cpp
Fix a few issues in the mem2reg interface implementations of VariableOp, ReadOp, and BlockingAssignOp. Add tests reduced from the Snitch core that used to fail before this fix.
Fixes #7483.
=> [Moore] Fix mem2reg implementation

include/circt/Dialect/LLHD/IR/ExtractOps.td, lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
We need to inset runtime checks for out-of-bound accesses because the semantics of the core dialects don't match the ones of SystemVerilog. I left this for a future PR since there are a few interesting cases to consider and it would increase the size of this PR considerably.
=> [MooreToCore] More extract op lowerings

lib/Dialect/Calyx/CMakeLists.txt, lib/Dialect/Calyx/CalyxOps.cpp, test/Conversion/CalyxToFSM/materialize-errors.mlir, test/Dialect/Calyx/clk-insertion.mlir, test/Dialect/Calyx/errors.mlir
See [issue](https://github.com/llvm/circt/issues/7051).
Honestly, I saw this bug a few months ago and I think I fixed it, just like this PR did. But I don't think it was enough.
```
test.mlir:2:3: note: see current operation: 
"calyx.component"() ({
^bb0(%arg0: i1, %arg1: i1, %arg2: i1, %arg3: i1):
%0:6 = "calyx.register"() {sym_name = "r"} : () -> (i1, i1, i1, i1, i1, i1)
"calyx.wires"() ({
^bb0:
}) : () -> ()
"calyx.control"() ({
^bb0:
}) : () -> ()
}) {function_type = (i1, i1, i1, i1) -> (), portAttributes = [{go}, {clk}, {reset}, {done}], portDirections = -8 : i4, portNames = ["go", "clk", "reset", "done"], sym_name = "main"} : () -> ()
```
The problem is as I said in the issue, solved he still reports an error because now `calyx.control` is empty after `-canonicalize`.
So a few …
=> [calyx] fix calyx canonicalization.

lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
Initialize `VariableOp`s of a four-valued type with a zero. This is in line with the rest of `MooreToCore` which maps all X/Z to zero at the moment, either implicitly by mapping to `comb.*` ops, or explicitly by conjuring up zero constants.
=> [MooreToCore] Support four-valued VariableOp without init

include/circt/Conversion/Passes.td, include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/MooreToCore/CMakeLists.txt, lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
Add a lowering pattern from `moore.conditional` to `scf.if`. This currently relies on the condition being a two-valued integer after lowering. Once we support four-valued integers at the core dialect level, the lowering of `moore.conditional` will become a lot more complicated.
=> [MooreToCore] Support ConditionalOp

include/circt/Support/FVInt.h, lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
Add a conversion for `moore.casez_eq` and `moore.casexz_eq` operations. These only really make sense if the operands are four-valued integers, since the X and Z bits indicate which bits to ignore during the equality check. We don't have support for four-valued integers in the core dialects yet. However, the vast majority of uses of this op are comparing an SSA value against a `moore.constant`. This case we can handle properly by looking at the constant, identifying the unknown bits, and then masking them before performing a regular two-valued comparison between the two operands.
=> [MooreToCore] Support CaseZEq and CaseXZEq ops

include/circt/Dialect/LLHD/IR/SignalOps.td, test/Dialect/LLHD/IR/basic.mlir, test/Dialect/LLHD/IR/errors.mlir
Add an operation that delays the propagation of value changes from its input to its output. This allows mem2reg of LLHD signals with a unique driver with a delay. For example
```
%sig = llhd.sig
llhd.drv %sig, %val after <1ns, 0d, 0e>
%res = llhd.prb %sig
```
can become
```
%res = llhd.delay %val by <1ns, 0d, 0e>
```
=> [LLHD] Add `llhd.delay` operation

include/circt/Dialect/ESI/ESIInterfaces.td, include/circt/Dialect/ESI/ESIManifest.td, lib/Dialect/ESI/ESIOps.cpp, lib/Dialect/ESI/Passes/ESIBuildManifest.cpp, lib/Dialect/ESI/runtime/cpp/include/esi/Common.h, lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp, test/Dialect/ESI/manifest.mlir
Users want to know what constants were used in a design. Plumb them through using the manifest. No runtime support, no pycde support.
Cleanups to the manifest as well. Update the runtime to support the schema changes to the manifest.
=> [ESI][Manifest] Embed constants in manifest

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, test/Dialect/FIRRTL/SFCTests/directories.fir, test/Dialect/FIRRTL/emit-metadata.mlir, test/firtool/prefixMemory.fir
The `CreateSifiveMetadata` pass was creating hierarchy paths to the memory module pre-extraction.
The `om.path` was being updated as the memory was extracted in the following passes.
But recently we realized this was a bug, as the downstream tools consuming the metadata files, were actually expecting the pre-extraction hierarchy paths to the memory.
So, this PR fixes the path to terminate at the parent of the module that instantiates the memory and encodes the pre-extraction memory instance as a string.
The tool that will parse the final `mlir` must now construct the actual pre-extraction path from the two lists, by appending the pre-extraction instance name to the path.
=> [CreateSifiveMetadata] Update memory hierarchy paths to be pre-extrction

include/circt/Dialect/OM/OMOps.td, test/Dialect/OM/round-trip.mlir
This operation produces a list by concatenating lists of the same type. The operation definition and a simple round trip test have been added. This is used to compose lists, which is a key feature to enable hierarchical composition of OM values.
=> [OM] Add list concatenation operation.

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, test/Dialect/FIRRTL/round-trip.mlir
This operation produces a list by concatenating lists of the same
type. The operation definition and a simple round trip test have been
added. This is used to compose lists, which is a key feature to enable
hierarchical composition of Properties.
=> [FIRRTL] Add list concatenation operation.

include/circt/Dialect/Verif/VerifOps.td, lib/Dialect/Verif/VerifOps.cpp, test/Dialect/Verif/basic.mlir
This PR redesigns the recent formal contract ops to allow for them to be used within an arbitrary scope and not just at the level of an entire module. This also removes the need for the `verif.instance` op.
=> [Verif] Generalize Formal Contracts

lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Import/FIRTokenKinds.def, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir
This parses `list_concat(exp+)` into the ListConcatOp. The type of the list is inferred during parsing, and all expressions must be the same. It is a parser error to not concatenate at least one list.
=> [FIRRTL] Add list concatenation parser support.

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes.mlir
This is a straightforward 1:1 conversion from firrtl::ListConcatOp to om::ListConcatOp.
=> [FIRRTL] Add list concatenation conversion to LowerClasses.

README.md
Fixes #7323. Change is pre-approved.
=> Explain IR acronym in README

include/circt-c/Dialect/HW.h, lib/CAPI/Dialect/HW.cpp
This allows us to set sym for partial ports - something like this pseudo-code:
```c
mlirOperationSetInherentAttributeByName(
moduleOp, // The module has 3 ports created
"portSyms",
mlirArrayAttrGet({ hwInnerSymAttrGetEmpty(ctx), hwInnerSymAttrGet("name"), hwInnerSymAttrGetEmpty(ctx) })
);
```
=> [HW][CAPI] Add a function to get an empty `InnerSymAttr`

lib/Dialect/Comb/CombFolds.cpp, test/Dialect/Comb/canonicalization.mlir
* Fix n^2 behavior with canonicalizeIdempotentInputs. Add arbitrary "depth" check to bound the search.
* Don't allow flattening or idempotent to search into operations defined in other blocks.
* Support removing duplicates even when operands come from other blocks. (or(x, y, x) -> or(x, x) regardless of their origin).
* Don't walk into operations with different two-state-ness in the idempotent operand canonicalizer.
* When creating new operation in idempotent canonicalizer, create it with matching two-state-ness.
Add tests for functional changes above.
=> [Comb][Fold] Fix idemp n^2 and bugfix + more optimization.

include/circt/Dialect/OM/Evaluator/Evaluator.h, lib/Dialect/OM/Evaluator/Evaluator.cpp, unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp
List concatenation is implemented by first ensuring all the sub-lists are evaluated, and then appending the elements of each sub-list into the final ListValue that represents the concatenation of the lists.
=> [OM] Support list concatenation in the Evaluator.

include/circt/Dialect/LLHD/IR/LLHDSignalOps.td, test/Dialect/LLHD/IR/errors.mlir
This is necessary because the moore dialect does not enforce such constraints for its variables and thus they can occur in functions
=> [LLHD] Relax sig parent constraint

lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, test/Dialect/FIRRTL/lower-layers.mlir
For each layer, we emit a bindfile. Each bindfile has a header consisting of an include guard, and an include for each parent layer's bindfile. To emit the bindfile's headers, we walk the layer declarations, and keep track of a stack of parent layers, which we use to emit the includes.
Unfortunately, a bug in the stack management code means that we forget to unwind the stack of parent layers, when the curent layer has no parents. This caused us to emit an include from one layer to the previous layer, when the previous layer had any children.
This PR fixes the stack unwind loop to correctly clear the stack, when the current layer has no parents.
=> LowerLayers: fix how we emit layer bindfile headers

lib/Dialect/FIRRTL/Transforms/LowerIntmodules.cpp, test/Dialect/FIRRTL/lower-intmodules-eicg.mlir
The extmodule and intrinsic disagree on port ordering, swap in LowerIntmodules.
Thanks to @prithayan for reporting this!
=> [LowerIntmodules] Fix EICG_wrapper intrinsic lowering, swap en/test_en.

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/FIRRTLInstanceImplementation.cpp, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/CheckRecursiveInstantiation.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/check-recursive-instantiation-errors.mlir, test/Dialect/FIRRTL/check-recursive-instantiation.mlir, test/Dialect/FIRRTL/errors.mlir
This adds a pass to FIRRTL to check for recursive module instantiation,
which is illegal because it corresponds to infinitely sized hardware.
This uses the path based strongly connected component (SCC) algorithm
with some extra book keeping to track if there was a loop in the current
SCC or not.  This is especially helpful to detect if a single-element
SCC actually contains a loop or not.
This does not use the upstream SCCIterator because we hope that this
version of the algorithm is faster by a constant factor, we don't need
to visit the SCCs in post-order, and hopefully faster handling of cycles
in single-element SCCs (which requires re-scanning all edges from a node
using the upstream version).
=> [FIRRTL] Add CheckRecursiveInstantiation diagnostic pass

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes.mlir
PathInfo stores a pointer to an Operation, which was problematic because that Operation may be deleted in updateInstanceInModule. The test case added in this patch would lead to a use-after-free.
This pointer was only really used for a few things, which can be handled differently to avoid needing to consider Operation lifetimes.
One use was the operator bool implementation, to check if a PathInfo is empty. In the one place this was used, an equivalent check is to query the PathInfoTable, and check if the key was not in the table.
Another use was adding the Operation's location in error messages and notes. We can safely store a Location directly for these messages.
The final use was to do an isa check while determining the target kind. This is where the use in the use-after-free would …
=> [FIRRTL] Update LowerClasses to alter what PathInfo stores.

include/circt/Dialect/LLHD/IR/LLHDSignalOps.td, lib/Conversion/MooreToCore/MooreToCore.cpp, lib/Dialect/LLHD/IR/LLHDOps.cpp, lib/Dialect/LLHD/Transforms/EarlyCodeMotionPass.cpp, test/Conversion/MooreToCore/basic.mlir, test/Dialect/LLHD/IR/basic.mlir, test/Dialect/LLHD/Transforms/temporal-code-motion.mlir
Make the `llhd.sig` op use the same naming pattern as HW wires, Moore variables, Seq registers, and a handful of other operations in CIRCT. These all use the `custom<ImplicitSSAName>` parser to provide uniform handling of optional names.
Make the signal name optional to align with other ops.
Rename the class to `SignalOp` for clarity.
=> [LLHD] Align signals with other wire/variable ops

include/circt/Dialect/LLHD/IR/LLHDStructureOps.td, include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, lib/Conversion/ImportVerilog/Statements.cpp, lib/Conversion/ImportVerilog/TimingControls.cpp, lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/MooreToCore/basic.mlir, test/Dialect/LLHD/IR/basic.mlir, test/Dialect/Moore/basic.mlir, tools/circt-verilog/circt-verilog.cpp
Rework the `moore.wait_event` op to be able to accurately model the semantics of SystemVerilog's `@...` event control statements. The op now has a body region which is executed to detect a relevant change in one or more interesting values. A new `moore.detect_event` op serves as the mechanism to encode whether a posedge, negedge, both, or any change at all on a value should be detected as an event.
Based on this new `moore.wait_event` op we can properly convert most of the event control statements in `ImportVerilog` to a corresponding MLIR op. Delay control like `#1ns` is not handled yet.
In the MooreToCore conversion this new op allows us to properly generate `llhd.wait` operations at the right place that suspend process execution until an interesting event has occurred. This now also …
=> [Moore] Improve WaitEventOp, lower to LLHD

lib/Dialect/FIRRTL/Transforms/SpecializeLayers.cpp, test/Dialect/FIRRTL/specialize-layers.mlir
Fix a bug in the `SpecializeLayers` pass where sibling layers would not be enabled/disabled correctly if an earlier sibling layer was also enabled/disabled.
Fixes #7525.
=> [firrtl] Fix bug in sibling layer specialization

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir, test/Conversion/ExportVerilog/verilog-basic.mlir, test/firtool/dpi.fir
This changes emission style for unpacked array declaration. Verilator doesn't support initialization assignments for unpacked arrays.
```verilog
wire w[1:0] = '{0, 0};
```
This PR checks the value type and prevents inlining. Ideally it is more desirable to improve verilator but for now I want to avoid inlining unpacked arrays to declaration since it's just a tiny readability optimization. 
Fix https://github.com/llvm/circt/issues/6363.
=> [ExportVerilog] Avoid inlining unpacked array expressions to declarations for tool compatibility

include/circt/Dialect/LLHD/IR/LLHDStructureOps.td, lib/Conversion/MooreToCore/MooreToCore.cpp, lib/Dialect/LLHD/Transforms/ProcessLoweringPass.cpp, test/Conversion/MooreToCore/basic.mlir, test/Dialect/LLHD/Canonicalization/probeCSE.mlir, test/Dialect/LLHD/IR/basic.mlir, test/Dialect/LLHD/Transforms/earlyCodeMotion.mlir, test/Dialect/LLHD/Transforms/memoryToBlockArgument.mlir, test/Dialect/LLHD/Transforms/processLowering.mlir, test/Dialect/LLHD/Transforms/processLoweringErrors.mlir, test/Dialect/LLHD/Transforms/temporal-code-motion.mlir
This is necessary to lower the moore dialect's always_comb and always_latch without introducing helper signals. It also allows for more mem2reg at the LLHD level.
=> [LLHD] Let WaitOp observe plain values instead of signals

lib/Dialect/FIRRTL/Import/FIRParser.cpp
Greatly reduces IR size generated in presence of many repeat constants as commonly occurs in practice due to the data-like nature of classes / properties.
Same tricky as done for FIRRTL integer constants,
use single cache/code for both.
=> [FIRRTL][FIRParser] Cache property constants.

lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
* Make sure ALL blocks without predecessors are removed properly. Note: `use_empty` is not up-to-date when erasing blocks with the rewriter as it only marks them as replaced.
* Also remove unreachable blocks within `func.func`
* Add lowering support for `always_comb` and `always_latch` procedures
=> [MooreToCore] Add always_comb and always_latch lowering support

integration_test/Dialect/ESI/runtime/callback.mlir, integration_test/Dialect/ESI/runtime/loopback.mlir, integration_test/Dialect/ESI/runtime/loopback.mlir.cpp, integration_test/lit.cfg.py, lib/Dialect/ESI/runtime/CMakeLists.txt, lib/Dialect/ESI/runtime/cpp/include/esi/backends/Trace.h, lib/Dialect/ESI/runtime/cpp/lib/backends/Trace.cpp, lib/Dialect/ESI/runtime/pyproject.toml, lib/Dialect/ESI/runtime/python/esiaccel/codegen.py, lib/Dialect/ESI/runtime/python/esiaccel/cppgen.py, lib/Dialect/ESI/runtime/python/esiaccel/esiCppAccel.cpp, lib/Dialect/ESI/runtime/python/esiaccel/types.py, lib/Dialect/ESI/runtime/python/esiaccel/utils.py
Start of static C++ header file generation. Just integer constants for now. Can work off of any manifest and will even connect to a live accelerator and read the manifest from there.
Generates a `types.h` file and one per module listed in the manifest. Inside the module header file, generates one class per module and adds the constants to that class. Puts _everything_ in a namespace specified by the user as `system_name`.
=> [ESI][Runtime] Generate C++ header files for constants

lib/Dialect/Comb/CombFolds.cpp, test/Dialect/Comb/canonicalization.mlir
There is a canonicalization for `exract(c, shl(1, x))` to `x == c` but this canonicalization introduces a bunch of comparision to constants. This harms PPA when bitwidth is large (e.g. 16 bit shift introduce 2^16 icmp op). To prevent such regressions this commit imposes restriction regarding the number of uses for shift.
=> [CombFolds] Don't canonicalize extract(shl(1, x)) if shift is multiply used

lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
Skip values defined by `ConstantLike` ops when collecting the list of values to observe in `llhd.wait` ops. Constants will never cause an `llhd.wait` to resume execution since they never change value.
=> [MooreToCore] Ignore ConstantLike values in wait op

lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, test/Dialect/FIRRTL/lower-layers-errors.mlir, test/Dialect/FIRRTL/lower-layers.mlir, test/firtool/layers-rwprobe.fir
Fixes first example in #7365 .
=> [FIRRTL][LowerLayers] Update rwprobe operations if possible.

include/circt/Dialect/FIRRTL/FIRRTLUtils.h, lib/Dialect/FIRRTL/FIRRTLUtils.cpp, lib/Dialect/FIRRTL/Transforms/AssignOutputDirs.cpp, lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/assign-output-dirs.mlir, test/firtool/blackbox-directories.fir
Change the `AssignOutputDirs` pass to add `hw::output_file` attributes on
external modules in the same way that these attributes are added to normal
modules.  While this has no effect on an external module which has no
implementation, this fixes a bug where the external module _does_ have an
implementation that the compiler will later resolve.
This is specifically done to make output directories compose correctly
with Chisel inline blackboxes where the body of the external module is in
an annotation and is supposed to be written to a file.
Reorder the FIRRTL pass pipeline so that Chisel blackboxes (represented by
a `firrtl.extmodule` and one of two blackbox annotations) will be assigned
an output directory based on their instantiation location.
Fixes #7538.
=> [FIRRTL] Set output dirs on annotated blackboxes

lib/Dialect/FIRRTL/Transforms/LayerMerge.cpp
Fix a performance issue in the `LayerMerge` pass [[1]].  Apparently, repeated use of `inlineBlockBefore` can be a performance issue.  Fix this, by using `mergeBlocks` which will append at the end of a block as opposed to prepend.  This requires an additional move, however, this empirically doesn't matter.
For details of the algorithm, see the updated comments in the pass.
h/t @youngar for algorithmic suggestions.
[1]: https://github.com/llvm/circt/issues/7551
=> [FIRRTL] Improve Layer Merge Performance

include/circt/Dialect/OM/OMPasses.h, lib/Dialect/OM/Transforms/FreezePaths.cpp
`FreezePaths` pass may sometimes need to be invoked before `ExportVerilog`. 
This change removes the dependency of the pass on the `hw.verilogName` attribute, and adds an optional get operation name function, that can be invoked if the verilog name is absent. 
This enables any tool to invoke it earlier by providing an appropriate name-getter function. 
But as is expected, the names used to freeze the paths, may not match the verilog names. This should be used with caution, only when the path will not be used and its okay to be incorrect.
=> [FreezePaths] Add an optional argument, to get the operation name

integration_test/Bindings/Python/dialects/rtl.py, lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir, test/Conversion/ExportVerilog/sv-dialect.mlir, test/Conversion/ExportVerilog/verilog-locations.mlir, test/firtool/memoryLowering.fir, test/firtool/memoryMetadata.fir, test/firtool/split-verilog.mlir
Stop emitting external modules entirely in single file emission and drop the creation of "extern_modules.sv" in split file emission.  This is done because it creates problems/confusion for Verilog generation flows which are trying to hide the existence of some modules.  E.g., the existence of "extern_modules.sv" will leak what external modules were instantiated under a FIRRTL layerblock.
Alternatively, this could be revived by creating these files by respecting the output file attributes on external modules such that each significant directory got such a file.
=> [ExportVerilog] Drop external module emission

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Dialect/FIRRTL/Transforms/CheckLayers.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/check-layers-errors.mlir, test/Dialect/FIRRTL/check-layers.mlir
This adds a pass to check for illegal instantiation of a module with
layers underneath a layer.  This is a situation that leads to
bind-unde-bind when emitted to Verilog, which is illegal.  This does not
differentiate between inline layers and bind layers, although
theoretically this is only a problem for bind layers. This does not
create errors on extmodules, as we have no way of knowing whether they
contain a layer or not, and we don't want false positives.
=> [firrtl] Add CheckLayers diagnostics pass

docs/Dialects/Seq/RationaleSeq.md, include/circt-c/Dialect/Seq.h, include/circt/Dialect/Seq/SeqOps.h, include/circt/Dialect/Seq/SeqOps.td, include/circt/Dialect/Seq/SeqTypes.td, integration_test/Bindings/Python/dialects/seq.py, lib/Bindings/Python/SeqModule.cpp, lib/Bindings/Python/dialects/seq.py, lib/CAPI/Dialect/Seq.cpp, lib/Conversion/ConvertToArcs/ConvertToArcs.cpp, lib/Conversion/HWToBTOR2/HWToBTOR2.cpp, lib/Conversion/LTLToCore/LTLToCore.cpp, lib/Conversion/PipelineToHW/PipelineToHW.cpp, lib/Conversion/SeqToSV/SeqToSV.cpp, lib/Dialect/Arc/Transforms/StripSV.cpp, lib/Dialect/Seq/SeqOps.cpp, lib/Dialect/Seq/Transforms/LowerSeqShiftReg.cpp, lib/Tools/circt-bmc/ExternalizeRegisters.cpp, test/Conversion/ConvertToArcs/convert-to-arcs.mlir, test/Conversion/HWToBTOR2/init.mlir, test/Conversion/LTLToCore/assertproperty.mlir, test/Conversion/PipelineToHW/test_poweron.mlir, test/Dialect/Seq/compreg.mlir, test/Dialect/Seq/errors.mlir, test/Dialect/Seq/round-trip.mlir, test/Dialect/Seq/shiftreg.mlir, test/Tools/circt-bmc/externalize-registers-errors.mlir
This PR extends compreg's powerOnValue operand to be able to capture more complicated initialization such as firreg's randomized initialization or DPI calls. This change should make register initialization more modular and a step forward towards https://github.com/llvm/circt/issues/7213. 
While ASICs might not have explicit initial values, they are crucial for simulation
and FPGA implementation. FPGA designs often require constant initial values, while
simulation allows for more complex initialization using expressions like function calls
`$random`, `$readmem`, and `$fopen`.
seq.compreg has a (optional) powerOn operand that is lowered into inlined assignment in SV which allows users to initialize registers with user-specified values. However this representation is not sufficient for …
=> [Seq] Introduce seq.initial, !seq.immutable and replace powerOn value with initial value in compreg

integration_test/Dialect/ESI/runtime/loopback.mlir, lib/Dialect/ESI/runtime/cpp/include/esi/Services.h, lib/Dialect/ESI/runtime/cpp/tools/esiquery.cpp
esiquery now displays the function signatures instead of the consistuent channels. More representative of the API which is exposed.
=> [ESI][Runtime] Pretty printing of service ports

lib/Dialect/FIRRTL/FIRRTLUtils.cpp, test/Dialect/FIRRTL/sfc-compat.mlir
This fixes an overflow in walkDrivers when field ID is zero.
Fix https://github.com/chipsalliance/chisel/issues/4354 and https://github.com/llvm/circt/issues/7423.
=> [FIRRTLUtils] Fix walkDrivers subfield id calculation

lib/Dialect/SV/SVOps.cpp, test/Dialect/SV/canonicalization.mlir
Fixes #7563 .
Should drop a regression test in an appropriate place.
=> [SV] Fix regop canonicalizer crashing.

lib/Conversion/MooreToCore/MooreToCore.cpp
Don't convert the output op in the module pattern because the operands will be of the wrong type since the body has not been converted yet, so it need to apply the hw output pattern afterwards anyway. Instead of relying on that pattern we should have a separate one for moore.output to hw.output that is applied once the rest of the body was converted. The HW output pattern is unnecessary because in the IR before conversion, no hw.output operation should be present (at least none that has a moore typed operand), thus its presence is only the consequence of a bad conversion process (if a target operation is inserted of which the operands are still of the source type, conversion casts should be inserted).
=> [MooreToCore] Separate conversion pattern for moore.output

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
Check return values of parsing functions, don't crash on missing keys.
=> [FIRRTL][GrandCentral] Fix crashes on error re:tryGetAs.

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp
Add missing getAs return value checking, emit diagnostics.
=> [FIRRTL][GrandCentral] Don't crash on missing keys, getAs.

frontends/PyCDE/integration_test/esitester.py, frontends/PyCDE/integration_test/test_software/esi_test.py, lib/Dialect/ESI/runtime/CMakeLists.txt, lib/Dialect/ESI/runtime/cpp/include/esi/Accelerator.h, lib/Dialect/ESI/runtime/cpp/include/esi/Common.h, lib/Dialect/ESI/runtime/cpp/include/esi/Context.h, lib/Dialect/ESI/runtime/cpp/include/esi/Logging.h, lib/Dialect/ESI/runtime/cpp/lib/Accelerator.cpp, lib/Dialect/ESI/runtime/cpp/lib/Common.cpp, lib/Dialect/ESI/runtime/cpp/lib/Logging.cpp, lib/Dialect/ESI/runtime/cpp/tools/esitester.cpp, lib/Dialect/ESI/runtime/python/esiaccel/esiCppAccel.cpp
The ESI logging API is intended to be agnostic of the application's logging framework. In other words, it can be adapted to the application's logging method with ease -- users must only extend one class. It also comes with a simple text logger.
It is also designed to enable debug logging in Release builds with (very) minimal performance overhead if the user does not set the log level to debug.
This PR introduces the API, but doesn't use it much. More plumbing will be required to actually use it. In the interest of keeping this PR small, this is left for future work.
=> [ESI][Runtime] Logging API

lib/Dialect/Moore/MooreOps.cpp
The original building warning:
```bash
[814/1036] Building CXX object lib/Dialect/Moore/CMakeFiles/obj.CIRCTMoore.dir/MooreOps.cpp.o
In file included from /home/ursa/Projects/circt/lib/Dialect/Moore/MooreOps.cpp:13:
In file included from /home/ursa/Projects/circt/include/circt/Dialect/Moore/MooreOps.h:16:
In file included from /home/ursa/Projects/circt/include/circt/Dialect/HW/HWTypes.h:17:
In file included from /home/ursa/Projects/circt/include/circt/Dialect/HW/HWDialect.h:16:
In file included from /home/ursa/Projects/circt/include/circt/Support/LLVM.h:22:
In file included from /home/ursa/Projects/circt/llvm/mlir/include/mlir/Support/LLVM.h:23:
/home/ursa/Projects/circt/llvm/llvm/include/llvm/Support/Casting.h:490:69: warning: returning reference to local temporary object …
```
=> [Moore][NFC] Fix warning when building Moore components

lib/Conversion/ImportVerilog/Structure.cpp, test/Conversion/ImportVerilog/errors.sv
For `defparam`, slang has propagated its value for the corresponding parameter. Such as:
```
module Top;
Foo #(1) foo();
endmodule
module Foo #(
parameter P = 32
);
int a = P;
endmodule
module Bar;
defparam Top.foo.P  = 4;
endmodule
```
On the AST, `P` and `a` both are 4. So we can skip `defparam`.
=> [ImportVerilog] Skip defparams which have been handled by slang.

lib/Dialect/HW/HWTypes.cpp, test/Dialect/HW/errors.mlir
Fix checking of OptionalParseResult, having value does not mean that the parsing succeeded.
Add test.
=> [HW] Fix crash when error encountered parsing hw.array.

lib/Dialect/HW/HWTypes.cpp, test/Dialect/HW/errors.mlir
Don't return success if there's a value, that value may be failure.  Fixes crash.
Emit diagnostic if no value found, to ensure something is produced.
=> [HW][HWTypes] Fix use of OptionalParseResult.

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
=> [FIRRTL][Folds] Fix mux fold if result type doesn't match operands.

lib/Dialect/FIRRTL/Import/FIRLexer.cpp, test/Dialect/FIRRTL/annotations-errors-lex-unterminated.fir
=> [FIRRTL][Lexer] Don't crash on trailing slash in inline anno.

lib/Dialect/FIRRTL/Import/FIRParser.cpp
Adding inner symbols, specifically to module ports, mutates the attribute dictionary and that races / breaks concurrent access to properties (e.g., port names and types) commonly inspected during parsing other module bodies (e.g., InstanceOp's).
Avoid this by instead gathering a list of operations and their intended target as "fixups" to be processed after the original (possibly parallel) parsing has completed and it is safe to do so.
This could be parallellized (per-module fixups)
but is not expected to have sufficient work to justify the overhead.
=> [FIRRTL][FIRParser] Defer inner symbols to post-processing, fix race.

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-errors.fir
* Must be passive
* Explicitly diagnose if source/dest diff cannot be cast away.
Add tests.  Second crashed attempting to construct invalid RefType before this change (non-passive base type).
While visiting, preserve layer "color" when inserting ref.cast.
=> [FIRRTL][FIRParser] Check force source more.

lib/Conversion/DCToHW/DCToHW.cpp, lib/Conversion/HWArithToHW/HWArithToHW.cpp, lib/Conversion/HandshakeToDC/HandshakeToDC.cpp, lib/Conversion/HandshakeToHW/HandshakeToHW.cpp, lib/Conversion/LTLToCore/LTLToCore.cpp, lib/Conversion/MooreToCore/MooreToCore.cpp, lib/Conversion/SeqToSV/SeqToSV.cpp, lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp
The materialization callbacks have to return either a `nullopt` or a value of the type provided as argument. This is not guaranteed by the ones changed in this PR.
This callback is invoked when an `unrealized_conversion_cast` operation inserted by the dialect conversion framework cannot be reconciled by the framework itself (e.g., if the input and output types of the op match, it gets folded away automatically).
This PR takes the conservative route, just telling the dialect conversion framework that it is fine to leave the conversion cast op in there if it cannot get rid of it. We could also return `nullopt` to tell it that it should fail in those cases.
=> Make sure type conversion materialization callbacks return values of the correct type

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
In LowerToHW we copy the name from FIRRTL ops to the lowered HW ops.  We often call `createOrFold` when creating the HW ops, which can mean that there is no operation to copy the name to.  We were not properly detecting this scenario, which could cause us to try to copy the name to a null operation.  Most ops were already covered under a guard in a generic code path, but div-like and subaccess-like operations needed to be guarded.  Some of these problems are impossible to test right now as we require folders to be implemented for some operations.
This backports #7358 to 1.62.0 for Chisel 6 users.
=> [FIRRTL] LowerToHW: guard against folded operations (#7358) (backport)

integration_test/Bindings/Python/support/walk.py, lib/Bindings/Python/CIRCTModule.cpp, lib/Bindings/Python/CIRCTModules.h, lib/Bindings/Python/CMakeLists.txt, lib/Bindings/Python/ESIModule.cpp, lib/Bindings/Python/HWModule.cpp, lib/Bindings/Python/MSFTModule.cpp, lib/Bindings/Python/OMModule.cpp, lib/Bindings/Python/SVModule.cpp, lib/Bindings/Python/SeqModule.cpp, lib/Bindings/Python/SupportModule.cpp, lib/Bindings/Python/support.py
This adds `walk_with_filter` python method to invoke callbacks only for subset of operations. We require GIL to call python function so this could improve performance of the tools based on Python API. This functionality could be better to be in upstream but for now we decided to add to CIRCT repo.
In the following benchmark there are 5*10^5 hw.constant ops and single hw.output op and it walks only hw.output op. The runtime is substantially faster.   
```python
import circt
from circt.dialects import hw
from circt.support import walk_with_filter
from circt.ir import (Context, Location, InsertionPoint, IntegerType,
IntegerAttr, Module, WalkOrder,
WalkResult)
n = 500000
with Context() as ctx, Location.unknown():
circt.register_dialects(ctx)
i32 = IntegerType.get_signless(32)
m = …
```
=> [python] Add `walk_with_filter` to walk subset of IR

lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp, test/Dialect/FIRRTL/lower-memory.mlir
Change LowerMemory to use a walk as opposed to iteration over operations. This is done to make this pass work with operations which have regions and may contain memories, i.e., to make this pass work with layers and whens.
=> [FIRRTL] Convert LowerMemory to walk

lib/Dialect/FIRRTL/Transforms/InferReadWrite.cpp, test/Dialect/FIRRTL/inferRW-errors.mlir, test/Dialect/FIRRTL/inferRW.mlir
Fix the InferReadWrite pass to walk into nested regions instead of only
visiting the top-level ops immediately in an FModuleOp's body.  This has
the effect of allowing it to work on memories that are declared inside
layers.
Change the InferReadWrite pass to fail if it ever sees a WhenOp.  If this
happens, the pass can silently do the wrong thing when trying to determine
signal drivers.  This is a conservative check (with false positives), but
will have no false negatives.
=> [FIRRTL] Change InferReadWrite to use a walk, error if it sees WhenOps

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, test/Dialect/FIRRTL/imconstprop.mlir
Change IMCP's module update to use a walk instead of only visiting
top-level ops.  This is intended to be an entirely mechanical change and
is broken out in a separate commit because of its mechanical nature.
Change IMCP to recurse into layers.  This has the effect of allowing IMCP
to sink constants into layers and to properly visit instances which are
instantiated under layers.
=> [FIRRTL] Make IMCP work with Layers

integration_test/arcilator/JIT/reg.mlir, lib/Conversion/ConvertToArcs/ConvertToArcs.cpp, lib/Dialect/Arc/Transforms/LowerState.cpp, test/Conversion/ConvertToArcs/convert-to-arcs.mlir, test/Dialect/Arc/lower-state.mlir
This PR implements state initialization using `seq.initial` not limited to constants. Combined with https://github.com/llvm/circt/pull/7606 we can perform random initialization in arcilator
=> [Arc] Fully support initialization through seq.initial

lib/Conversion/AffineToLoopSchedule/CMakeLists.txt, lib/Conversion/CFToHandshake/CMakeLists.txt, lib/Conversion/CalyxNative/CMakeLists.txt, lib/Conversion/CalyxToFSM/CMakeLists.txt, lib/Conversion/CalyxToHW/CMakeLists.txt, lib/Conversion/DCToHW/CMakeLists.txt, lib/Conversion/HandshakeToDC/CMakeLists.txt, lib/Conversion/HandshakeToHW/CMakeLists.txt, lib/Conversion/PipelineToHW/CMakeLists.txt, tools/circt-opt/CMakeLists.txt
* Use `add_circt_conversion_library` to define the libraries in `lib/Conversion`. Currently some already do that and others just declare them as regular libraries. `ExportChiselInterface`, `ExportVerilog`, and `ImportVerilog` are registered as translation libraries which makes sense, but makes me wonder: shouldn't they exist in another directory (e.g., `lib/Target` for the export passes)?
* Use the CMake property to add them as link targets to circt-opt. When adding a new dialect, it will then be linked against it automatically as with the other non-dialect-specific tools.
=> [CMake] Consistently declare conversion libraries and simplify circt-opt link target list

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Statements.cpp, test/Conversion/ImportVerilog/basic.sv
These immediate assertion ops borrow from the `SV` dialect.
=> [Moore] Add assert, assume, and cover ops.

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, lib/Dialect/FIRRTL/Transforms/ResolvePaths.cpp, test/Dialect/FIRRTL/lower-classes-errors.mlir, test/Dialect/FIRRTL/lower-classes.mlir, test/Dialect/FIRRTL/resolve-paths-errors.mlir, test/Dialect/FIRRTL/resolve-paths.mlir
The existing path support was built up based on the assumption that
every target is unique. That is true for FIRRTL produced by standard
Chisel code, which elaborates unique modules for each instance. We
definitely don't want to limit ourselves to this world, and we should
support targeting things that are multiply instantiated when it is not
ambiguous what we refer to.
This patch relaxes the single-instantiation constraints for local
targets, which refer to a module or something inside a module,
regardless of how many times or at what paths that particular module
was instantiated.
This required a couple changes through the pipeline:
ResolvePaths already had an early exit for the local path case, but
this needed to come before the single-instantiation check.
LowerClasses needed a couple …
=> [FIRRTL] Allow local targets to be multiply-instantiated.

include/circt/Analysis/FIRRTLInstanceInfo.h, lib/Analysis/CMakeLists.txt, lib/Analysis/FIRRTLInstanceInfo.cpp, lib/Analysis/TestPasses.cpp, lib/Dialect/FIRRTL/CMakeLists.txt, test/Analysis/firrtl-test-instance-info.mlir
Add a new InstanceInfo analysis.  This analysis provides common information which can be computed from a single walk of the InstanceGraph. The idea behind this is that there are a large amount of common information that different passes want to compute which all follows this same walk (and therefore has the same algorithmic complexity to compute it).  Move all this information into a single, common analysis.
This analysis currently enables O(1) queries of if something is the DUT, is instantiated under the DUT, or is instantiated under a layer.  More queries can be added as they are identified.
This new analysis naturally depends on the InstanceGraph analysis.
=> [FIRRTL] Add InstanceInfo Analysis

lib/Dialect/LLHD/Transforms/TemporalCodeMotionPass.cpp, test/Dialect/LLHD/Transforms/temporal-code-motion.mlir
The simple canonicalizer does not do this simplification for us if too many blocks have to be merged.
=> [LLHD][TCM] Simplify region directly

include/circt/Conversion/Passes.td, include/circt/Conversion/VerifToSMT.h, lib/Conversion/HWToSMT/CMakeLists.txt, lib/Conversion/HWToSMT/HWToSMT.cpp, lib/Conversion/VerifToSMT/CMakeLists.txt, lib/Conversion/VerifToSMT/VerifToSMT.cpp, test/Conversion/VerifToSMT/verif-to-smt-errors.mlir, test/Conversion/VerifToSMT/verif-to-smt.mlir
This PR adds a pattern to lower the `verif.bmc` op into the program to actually perform the check (from the splitting up of #7259 - only the actual tool left after this!), similarly to what circt-lec currently does.
=> Add `verif.bmc` VerifToSMT lowering

include/circt/Dialect/SV/SVExpressions.td, include/circt/Dialect/SV/SVStatements.td, include/circt/Dialect/SV/SVVisitors.h, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/SV/SVOps.cpp, test/Conversion/ExportVerilog/pretty.mlir, test/Conversion/ExportVerilog/sv-dialect.mlir, test/Conversion/ExportVerilog/verilog-basic.mlir, test/Conversion/FIRRTLToHW/emit-chisel-asserts-as-sva.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/SV/basic.mlir, test/Dialect/SV/cse.mlir, test/Dialect/Seq/firreg.mlir, test/Dialect/Seq/hw-memsim.mlir, test/firtool/print.fir, test/firtool/stop.fir
There has been MacroRefExprOp and MacroRefExprSEOp to use macro symbols as expressions but it was not possible to use macro as a statement. This commit adds `sv.macro.ref` op to represent a statement. Since `sv.macro.ref` mnemonic was used by MacroRefExprOp this commit also renames `sv.macro.ref` to `sv.macro.ref.expr` at the same time.
=> [SV] Add MacroRefOp to represet macro statement

lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
* Alternative conditional op lowering to a mux if there are no relevant side-effects in the regions
* Add missing type conversions (mostly target types not marked legal and target types with nested source types not supported). This is necessary to make the conditional lowering work because the dialect conversion framework pushes an InlineBlockRewrite to the queue with triggers a signature conversion call to the function body the conditional op is in, which failed because the target types were not marked legal.
* Use the type converters isLegal helpers to determine dynamic legality instead of a custom solution.
=> [MooreToCore] Alternative conditional lowering and type conversion fixes

integration_test/CMakeLists.txt, integration_test/circt-bmc/comb-errors.mlir, integration_test/circt-bmc/comb.mlir, integration_test/circt-bmc/seq-errors.mlir, integration_test/circt-bmc/seq.mlir, integration_test/lit.cfg.py, tools/CMakeLists.txt, tools/circt-bmc/CMakeLists.txt, tools/circt-bmc/circt-bmc.cpp
This is the final split part of #7259, and adds a `circt-bmc` tool to use all of the BMC op infrastructure to perform bounded model checks!
=> [circt-bmc] Add `circt-bmc` tool

lib/Conversion/ImportVerilog/Structure.cpp, test/Conversion/ImportVerilog/errors.sv
Simply skip the elaboration system tasks `$info`, `$warning`, `$error`, and `$fatal` outside procedural code. Slang already processes these tasks and generates the corresponding diagnostics for us.
=> [ImportVerilog] Add support for elaboration system tasks

lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/errors.mlir
Add a CircuitOp verifier that guarantees that there is zero or one modules annotated with a `MarkDUTAnnotation`.  This is important as many passes assume that this is the case.  Moving this check into a verifier means that logic checking this behavior in each pass can be removed.  I am slightly concerned of the performance cost of doing this as examining the annotations is non-trivial and this will cause that examination to now happen more often.
=> [FIRRTL] Add verifier of single MarkDUTAnnotation

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp, test/Dialect/FIRRTL/inliner-errors.mlir, test/Dialect/FIRRTL/inliner.mlir
inlineInstances/flattenInstances:
* Walk entire body, not only top-level operations.
Fixes missing instances and allows inlining them
when conservatively legal.
* Reject inlining instances under when/match.
inlineInto/flattenInto:
Walk entire body using new `inliningWalk` method
that drives the per-operations handling but also
handles cloning "structure" operations that have
regions (when/match/layer) and managing what
should be cloned where.
This allows inlining modules that contain these
operations.
Inliner now may produce errors, thread throughout.
This allows the inliner to run earlier in the pipeline,
particularly before LowerLayers.
=> [FIRRTL] Inliner: Support for ops with regions.

lib/Firtool/Firtool.cpp
LowerLayers belongs with the other passes that lower out of FIRRTL.
Start moving it, now that first batch of passes have been fixed to handle enough FIRRTL IR to run in presence of layer operations.
=> [firtool] Move LowerLayers later in pipeline.

lib/Dialect/FIRRTL/Transforms/AddSeqMemPorts.cpp, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, test/Dialect/FIRRTL/add-seqmem-ports-errors.mlir, test/Dialect/FIRRTL/add-seqmem-ports.mlir
Change the `AddSeqMemPorts` pass (whic adds MBIST ports to memories) to
use a walk when adding ports to memories.  Practically, this causes the
pass to now be capable of adding MBIST to memories under `WhenOp`s or
`LayerBlockOp`s.  However, because this pass is intentionally _not_
supposed to add MBIST ports to anything that is not in the "design", this
will skip over any layers or modules that are instantiated wholly under
layers.
To do this, this pass was changed to use the new `InstanceInfo` analysis
instead of computing information about what modules are under the
design-under-test (DUT) manually.  Any checking related to layers is
similarly done using this analysis.
This change is prerequisite work to move the `LowerLayers` after
`AddSeqMemPorts` while still preserving the …
=> [FIRRTL] Use walk, InstanceInfo in AddSeqMemPorts

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, lib/Conversion/ImportVerilog/Statements.cpp, test/Conversion/ImportVerilog/basic.sv, test/Dialect/Moore/basic.mlir
Add support for the simulation control system tasks `$stop`, `$finish`, and `$exit`. Also add corresponding ops to the Moore dialect that handle the orthogonal pieces of functionality represented by these tasks.
=> [ImportVerilog] Add support for $stop/$finish/$exit

include/circt/Analysis/FIRRTLInstanceInfo.h, lib/Analysis/FIRRTLInstanceInfo.cpp, lib/Analysis/TestPasses.cpp, lib/Dialect/FIRRTL/Transforms/AddSeqMemPorts.cpp
Fix a problem with the InstanceInfo analysis stemming from the use of `InstanceGraphNode *` to track the design-under-test (DUT) and "effective" DUT.  If the instance graph changed, then these would be invalidated. Instead use a `igraph::ModuleOpInterface` which is going to be stable.
=> [FIRRTL] Avoid InstanceGraphNode* in InstanceInfo

include/circt/Dialect/Moore/MooreOps.td, include/circt/Dialect/Moore/MooreTypes.td, lib/Conversion/ImportVerilog/CMakeLists.txt, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/FormatStrings.cpp, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, lib/Conversion/ImportVerilog/Statements.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/errors.sv, test/Dialect/Moore/basic.mlir
Add support for the `$display`, `$write`, `$info`, `$warning`, `$error`, and `$fatal` system tasks.
These tasks are pretty complicated since they involve string formatting. Verilog has quite a few format specifiers and very strange rules for them. Luckily, Slang contains a handy utility that parses format strings and delegates handling of arguments and intermittent pieces of text to callbacks.
I've decided to follow the same IR design as the printing op in the Sim dialect: each format specifier is turned into a dedicated op that captures all relevant format options, plus additional literals for the text in between interpolated values, and concatenate everything into a single `!moore.format_string`. (Shoutout to @fzi-hielscher for trailblazing the nice design for `sim.print`!) This is …
=> [ImportVerilog] Add $display/$write/$info/$warning/$error/$fatal

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Expressions.cpp, test/Conversion/ImportVerilog/builtins.sv, test/Dialect/Moore/basic.mlir
Add a `moore.builtin.clog2` op and use it to convert `$clog2` calls in ImportVerilog.
=> [ImportVerilog] Add support for $clog2

lib/Dialect/FIRRTL/Transforms/AddSeqMemPorts.cpp, test/Dialect/FIRRTL/add-seqmem-ports-errors.mlir
Change AddSeqMemPorts to reject circuits where a memory is instantiated under both the design-under-test (DUT) and _not_ under the DUT.  This is a situation that indicates that ports should be added to one instance, but not the other.  While there are a number of ways that this could be solved (similarly to with mixed under layer / _not_ under layer) by transforming the design via recursive deduplication or by tying off the modified memory, these approaches are rejected for now in favor of just catching the error.  Mid-term I would prefer to delete this pass entirely as it has general composition problems with other passes and FIRRTL features.
Fixes #7620.
=> [FIRRTL] Error mixed DUT mems in AddSeqMemPorts

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Expressions.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/builtins.sv, test/Dialect/Moore/basic.mlir
Allow `'{...}` assignment patterns to be used to assign integer values. Slang already computes the value for each element in the resulting type. All that's needed is a concat with the right operand order.
=> [ImportVerilog] Support assignment patterns with integer type

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/Structure.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/builtins.sv, test/Dialect/Moore/basic.mlir
In certain corner cases, Slang does not insert the necessary conversion AST nodes around instance ports. This can be problematic if an input or output port is connected to a cast-compatible type (e.g. `i32` and `array<1 x i32>`). To fix this, always insert conversions if the types of a port and the connected value differ.
=> [ImportVerilog] Insert missing conversions around instance ports

lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp
Remove code that handles the capturing of ref cast and ref send operands specially, since this code is doing only what the generic capture-handling code does just a few lines [below](https://github.com/llvm/circt/blob/main/lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp#L611-L616).
There is a bug in the handling of ref.cast which is removed by this change: We are accidentally checking that the cast op itself is within the layerblock, when we should actually be checking if its operand is defined within the layerblock. This causes us to skip converting the captured operand of a ref.cast op into a port. The generic codepath works fine.
=> [FIRRTL][LowerLayers] Remove handling of some ref ops

include/circt/Analysis/OpCountAnalysis.h, lib/Analysis/CMakeLists.txt, lib/Analysis/OpCountAnalysis.cpp, lib/Analysis/TestPasses.cpp, test/Analysis/op-count-analysis.mlir
Adds a very simple analysis pass to collect information about the kinds of operations (and operand counts) found in a `hw.module` so we can look at operation usage across big designs. Once this is upstream I'll add a pass to export this info as JSON.
=> [Analysis] Add OpCount Analysis

lib/Dialect/Arc/ArcFolds.cpp, test/Dialect/Arc/canonicalizers.mlir
When adding the initial value parameter to the `StateOp` I forgot to adapt its folder.  This PR should fix that.
- Fold a permanently disabled state to its initial value (if present) instead of zero.
- Don't fold a state that is permanently reset if it has an explicit initial value.
- Don't attempt to constant fold a result-less `StateOp` to avoid an infinite loop.
=> [Arc] Fix folding of initialized StateOp

lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
Lower `moore.net` operations to the corresponding `llhd.sig`, similar to how `moore.variable` is lowered. This currently only makes sense for "wire" nets, since it's not yet clear how all the other net types map to LLHD.
=> [MooreToCore] Lower moore.net to llhd.sig

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h, lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes.mlir
This transformation used to exist in EmitOMIR to detect the presence of a specific field, and use it to add another specific field on the fly. While we could do this through other means downstream, for full compatibility we are re-implementing this logic.
Because we are already doing many expensive passes through the object IR, this is implemented throughout the existing methods in LowerClasses, rather than adding a new pass or a new traversal to an existing pass.
One consequence of this choice is we do need to perform some global mutation to, e.g., allocate new hierpath ops in a method that was previously parallelized internally to the pass. Rather than reworking things or executing that method serially, this patch adds a mutex to each instance of the pass, and uses the mutex around …
=> [FIRRTL] Re-implement old EmitOMIR ports logic in LowerClasses.

include/circt/Dialect/Seq/SeqOps.h, include/circt/Dialect/Seq/SeqOps.td, integration_test/Bindings/Python/dialects/seq.py, integration_test/arcilator/JIT/reg.mlir, lib/Bindings/Python/dialects/seq.py, lib/Conversion/ConvertToArcs/ConvertToArcs.cpp, lib/Conversion/SeqToSV/SeqToSV.cpp, lib/Dialect/Arc/Transforms/LowerState.cpp, lib/Dialect/Seq/SeqOps.cpp, test/Conversion/ConvertToArcs/convert-to-arcs.mlir, test/Conversion/HWToBTOR2/init.mlir, test/Conversion/LTLToCore/assertproperty.mlir, test/Conversion/PipelineToHW/test_poweron.mlir, test/Conversion/SeqToSV/error.mlir, test/Dialect/Arc/lower-state-errors.mlir, test/Dialect/Arc/lower-state.mlir, test/Dialect/Seq/compreg.mlir, test/Dialect/Seq/errors.mlir, test/Dialect/Seq/round-trip.mlir, test/Dialect/Seq/shiftreg.mlir, test/Tools/circt-bmc/externalize-registers-errors.mlir
This is a PR based on https://github.com/llvm/circt/pull/7638 w/o controversial to_immutable op. 
This commit adds support for seq.initial ops to take immutable operands and introduces a new cast operation:
- Update InitialOp to accept input operands of ImmutableType
- Add FromImmutableOp for casting from immutable to regular types
- Add mergeInitialOps helper to handle operands and topological sorting of initial ops when lowering (SV flow -> SeqToSV, Arc flow -> LowerState).
- Update lowering passes and dialects to work with new initial op
=> [Seq][Arc] Allow seq.initial to take immutable operands. Add a cast operation

include/circt/Dialect/HW/HWTypes.h, include/circt/Dialect/HW/HWTypesImpl.td, include/circt/Dialect/LLHD/IR/LLHD.td, include/circt/Dialect/LLHD/IR/LLHDExtractOps.td, include/circt/Dialect/LLHD/IR/LLHDOps.h, include/circt/Dialect/LLHD/IR/LLHDSignalOps.td, lib/Dialect/HW/CMakeLists.txt, lib/Dialect/HW/HWTypes.cpp, lib/Dialect/LLHD/IR/CMakeLists.txt, lib/Dialect/LLHD/IR/LLHDOps.cpp, test/Dialect/LLHD/Transforms/sroa.mlir
Implement SROA to destructure signals used by `llhd.sig.array_get` (with constant index) and `llhd.sig.struct_extract`.
Let me know if you'd prefer the interfaces implemented via external models.
=> [LLHD][HW] Implement SROA interfaces

lib/Dialect/FIRRTL/Transforms/InferResets.cpp, test/Dialect/FIRRTL/infer-resets.mlir
This is quick fix for https://github.com/llvm/circt/issues/7675.
The way this is supposed to work is, FRT is not supposed to add a reset if a register already has one, but it isn't smart enough to understand that an invalid value corresponds to a register without a reset. As a result, it will not add a reset to this register. Later on, in SFCCompat, when choosing how to lower the Invalid value, it should "see" that the registers should all have a reset, by looking for the FRT annotation, and choose to lower the reset value to 0 or remove the reset accordingly. The "bug" is that the FRT annotation on a parent module won't be discovered on the child module.
This attaches the annotation on to every module in a reset domain, so that it can be found.
=> [FIRRTL] InferResets: properly lower FART'd registers

lib/Dialect/OM/Transforms/FreezePaths.cpp, test/Dialect/OM/freeze-paths.mlir
When we walk the IR and freeze paths, we previously didn't handle object field ops. This is totally valid IR, and is another case where we may encounter ops defining SSA values of path types that need to be frozen.
This adds a visitor for ObjectFieldOp, similar to the other visitors, which rewrites the result type to map any path types to frozen path types.
=> [OM] Update FreezePaths to handle object fields with paths.

lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/lower-layers.mlir, test/Dialect/FIRRTL/round-trip.mlir
If a port name is empty, then the SSA-name cannot match, and we must print the port names as an attribute instead. This PR removes a bogus check in the module printer, which prevents us from printing the port names attribute,  if the port name is empty.
With this PR, modules with empty port names should round trip correctly.
When lower-layers converts layerblocks into modules, a lot of the time there is no good name for the port, so it generates an empty port name. With this patch, these modules will now correctly print the port names attribute, so the tests had to be updated to match against the attribute dictionary.
Fixes: https://github.com/llvm/circt/issues/7224
=> [FIRRTL] Print port names attributes if a port has an empty name

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, test/Dialect/FIRRTL/lower-classes.mlir
We recently started supporting local-only paths in LowerClasses, but this logic erroneously disabled the alternative base path feature for paths whose targets were relocated outside the owning module. In the case that we need an alternative base path for a local target, convert it to a non-local target, so the alternative base path can be correctly prefixed.
=> [FIRRTL] Ensure LowerClasses respects alt base path for local paths.

include/circt/Dialect/Verif/VerifOps.td, test/Dialect/Verif/basic.mlir, test/circt-test/basic.mlir
Simplify the definition of the `verif.formal` operation which describes a single formal unit test. This op used to have a "k" parameter which is now gone in favor of more generically using the attributes dictionary to capture execution parameters. As we build out the testing flows, we can reintroduce necessary attributes to this operation.
Rename `verif.symbolic_input` to `verif.symbolic_value`.
Remove `verif.concrete_input` in favor of explicitly describing the concrete input using one of the registers in the Seq dialect. This also makes the associated clock explicit, which was missing from this op.
=> [Verif] Simplify the FormalOp

include/circt/Dialect/Sim/SimOps.h, include/circt/Dialect/Sim/SimOps.td, lib/Dialect/Sim/Transforms/ProceduralizeSim.cpp
Include the `InferTypeOpInterface.td` file in `SimOps.td`, which causes TableGen to automatically generate builders without result type for operations where the result type is either fixed or derived from the operands. This makes one of the builders obsolete.
=> [Sim][NFC] Include InferTypeOpInterface in SimOps.td

include/circt/Conversion/Passes.td, lib/Conversion/MooreToCore/CMakeLists.txt, lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
Lower the format string ops and the `moore.builtin.display` task to the corresponding ops in the Sim dialect. This is not perfect yet, since Sim does not support some of the formatting options. They will be easy to add in the future though.
=> [MooreToCore] Add support for format strings and display task

include/circt/Dialect/FIRRTL/FIRRTLStructure.td, include/circt/Dialect/FIRRTL/FIRRTLUtils.h, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/FIRRTLUtils.cpp, lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp, test/Dialect/FIRRTL/extract-instances-inject-dut-hier.mlir, test/Dialect/FIRRTL/extract-instances.mlir
This change adds the `ExtractInstances` metadata to the OM classes. The OM dialect can then be parsed to generate the respective metadata files.
This change enables to move all the metadata to the OM dialect, instead of existing as verbatim ops.
=>  [ExtractInstances] Add the extract instances metadata to OM Classes

lib/Conversion/ArcToLLVM/CMakeLists.txt, lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp, tools/arcilator/CMakeLists.txt, tools/arcilator/arcilator.cpp
Support the index dialect when lowering from Arc to LLVM. Also fix a minor issue in the lowering `SimGetPortOp`.
=> [ArcToLLVM] Add support for index dialect

lib/Dialect/FIRRTL/Transforms/ProbesToSignals.cpp, test/Dialect/FIRRTL/probes-to-signals-errors.mlir, test/Dialect/FIRRTL/probes-to-signals.mlir
* Define type conversion mapping rwprobe<T> -> passive(T)
* Forceable support (passive read of data result)
* RWProbeOp support (materialize target, to passive)
* Reject {force,release}{,_initial}
Add some basic tests.
=> [FIRRTL][ProbesToSignals] RWProbe support

lib/Dialect/Comb/CombFolds.cpp, test/Dialect/Comb/canonicalization.mlir
We're already doing a best-effort preservation of discardable attributes through `narrowOperationWidth`. I cannot think of a reason why the inherent two-state attribute should not be carried over.
=> [CombFolds] Preserve two-state attribute in `narrowOperationWidth`

frontends/PyCDE/src/pycde/bsp/common.py, frontends/PyCDE/src/pycde/esi.py, include/circt/Dialect/ESI/ESIManifest.td, lib/Dialect/ESI/ESIOps.cpp, lib/Dialect/ESI/ESIServices.cpp, lib/Dialect/ESI/runtime/cpp/include/esi/Common.h, lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp, test/Dialect/ESI/manifest.mlir, test/Dialect/ESI/services.mlir
Previously, cosim store its ESI channel to cosim channel name in the `implDetails`. DMA engines to make channel communication work in real hardware need this information as well.
=> [ESI] Promote and generalize 'channel assignments'

docs/FormalVerification.md, docs/GettingStarted.md
Image links are broken in github preview.
=> [docs] Fix broken image links in docs

lib/Dialect/FIRRTL/Transforms/CheckLayers.cpp
Change the `CheckLayers` pass to use the `InstanceInfo` analysis.  This
new analysis makes the error checking trivial.  However, the error
reporting is still somewhat tedious.
=> [FIRRTL] Convert CheckLayers to use InstanceInfo

include/circt/Dialect/Seq/SeqAttributes.td, lib/Conversion/SeqToSV/SeqToSV.cpp, lib/Dialect/HW/HWOps.cpp, lib/Dialect/Seq/SeqAttributes.cpp, test/Dialect/HW/errors.mlir, test/Dialect/HW/round-trip.mlir, test/Dialect/Seq/clock-type.mlir
This fixes https://github.com/llvm/circt/issues/7716. Aggregate constant verifier rejects unknown attributes hence hw.aggregate_constant cannot be used for attributes defined by other dialects (in this case seq.const_clock) was rejected even when hw.aggregate_create allows users to create clock type arrays. This PR loosen the restriction by allowing TypedAttribute. 
This PR also adds TypedAttrInterface to seq.const_clock and support its lowering.
=> [HW][Seq] Allow typed attr to be an element of aggregate_constant and make seq.const_clock typed attr

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, include/circt/Firtool/Firtool.h, lib/Dialect/FIRRTL/Transforms/AdvancedLayerSink.cpp, lib/Dialect/FIRRTL/Transforms/CMakeLists.txt, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/advanced-layer-sink.mlir, test/Dialect/FIRRTL/ref.mlir
Add advanced layer sink, a new FIRRTL-dialect transform pass. Advanced layer sink serves the same purpose as the original layer sink pass: move ops into layers if their uses permits it. Advanced layer sink works by finding the shallowest block a value is used by an effectful op, and then sinking the defining op to that block. Compared to the original layer sink pass, which only relied on dominance info, this pass can sink cyclical structures, such as registers.
=> Advanced LayerSink

lib/Conversion/HWToSMT/HWToSMT.cpp, test/Conversion/HWToSMT/hw-to-smt-errors.mlir
Fixes https://github.com/llvm/circt/issues/7725
=> [HWToSMT] Proper error message for 0-bit constants

lib/Tools/circt-bmc/ExternalizeRegisters.cpp, test/Tools/circt-bmc/externalize-registers-errors.mlir, test/Tools/circt-bmc/externalize-registers.mlir
Adds support for initial values (as long as they're defined directly by a `hw.constant` op inside a `seq.initial`) to `ExternalizeRegisters` - I'll add the support for this in circt-bmc as a follow-up to slim down the diff. Initial values are added in an ArrayAttr on the module op - if there's no initial value then it just adds a unit attr
=> [circt-bmc] Add simple initial value support to ExternalizeRegisters

integration_test/Dialect/FIRRTL/SFCTests/GrandCentralInterfaces/Wire.fir, integration_test/EmitVerilog/verilog_equiv.fir, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/SFCTests/async-reset-verilog.fir, test/Dialect/FIRRTL/SFCTests/directories.fir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir, test/firtool/annotation-error.fir, test/firtool/memoryMetadataRenameFail.fir
Change CIRCT's FIRRTL parser to reject statements which are supposed to be disallowed in FIRRTL 3.
Fixes #7731.
=> Reject '<=' and 'is invalid' if FIRRTL version >=3

include/circt/Dialect/Arc/ArcDialect.td, include/circt/Dialect/Calyx/Calyx.td, include/circt/Dialect/Comb/Comb.td, include/circt/Dialect/DC/DCDialect.td, include/circt/Dialect/FIRRTL/CHIRRTLDialect.td, include/circt/Dialect/FSM/FSM.td, include/circt/Dialect/HW/HWDialect.td, include/circt/Dialect/HWArith/HWArithDialect.td, include/circt/Dialect/Handshake/Handshake.td, include/circt/Dialect/Ibis/IbisDialect.td, include/circt/Dialect/Ibis/IbisOps.td, include/circt/Dialect/LLHD/IR/LLHDDialect.td, include/circt/Dialect/LTL/LTLDialect.td, include/circt/Dialect/LoopSchedule/LoopSchedule.td, include/circt/Dialect/OM/OMDialect.td, include/circt/Dialect/Pipeline/PipelineDialect.td, include/circt/Dialect/SSP/SSP.td, include/circt/Dialect/SSP/SSPOps.h, include/circt/Dialect/SV/SVDialect.td, include/circt/Dialect/Seq/SeqDialect.td, include/circt/Dialect/SystemC/SystemCDialect.td, include/circt/Dialect/Verif/VerifDialect.td, lib/Dialect/HW/HWOps.cpp, lib/Dialect/Ibis/IbisOps.cpp, lib/Dialect/LLHD/IR/LLHDOps.cpp, lib/Dialect/OM/OMOps.cpp, lib/Dialect/SV/SVOps.cpp
This change enables the use of operation properties for more dialects in CIRCT. The option to *not* use properties is going to be removed in a future release of MLIR, but as well we expect this change to bring a performance improvement.
For all these dialects, the only change required was to properly infer return types.  Some operations were hardcoded to search through the attributes, and the attribute was moved to the property storage. By using the generated adaptor classes, we can abstract over where the interesting attribute is stored.
For future work, some code may be refactored for further performance wins now that we are using properties. In particular usages `setAttr` and `getAttr` may be made faster by using a less generic op transformation interface.
=> Use properties for attributes for many dialects

include/circt/Dialect/AIG/AIGOps.td, lib/Dialect/AIG/AIGOps.cpp, lib/Dialect/AIG/CMakeLists.txt, test/Dialect/AIG/canonicalizer.mlir, test/Dialect/AIG/round-trip.mlir
This commit adds `aig.and_inv` op that represents an And-Inverter in AIG. DenseBoolArray `inverted` field specifies if each operand is inverted. This commit also adds a basic canonicalizer for it. 
This PR is extracted from https://github.com/llvm/circt/pull/7717
=> [AIG] Add AndInverterOp

test/circt-synth/basic.mlir, tools/circt-synth/CMakeLists.txt, tools/circt-synth/circt-synth.cpp
This PR populates circt-synth pipeline from CombToAIG to LowerWordToBits with optimizations.
Separated from https://github.com/llvm/circt/pull/7717 with a bit of option name change.
=> [circt-synth] Populate pipelines until AIG lowering

include/circt/Dialect/AIG/AIGOps.td, lib/Dialect/AIG/AIGOps.cpp, test/Dialect/AIG/errors.mlir, test/Dialect/AIG/round-trip.mlir
The `aig.cut` operation represents a cut in the And-Inverter-Graph. This operation is variadic and can take multiple inputs and outputs, which corresponds to the input and output edges in AIG conceptually.
This is separated from https://github.com/llvm/circt/pull/7717 and a verifier is added.
=> [AIG] Add CutOp

integration_test/circt-lec/comb.mlir, tools/circt-lec/CMakeLists.txt, tools/circt-lec/circt-lec.cpp
verif.assume can be used to annotate pre-condtion directly in the IR. This is quite useful when verifying transformation which involves undefined values. For example when lowering comb.divu to AIG, the conversion pass could choose arbitary values for divided by zero situation. So we cannot verify the equivalence unless we specify the pre-condtion with verif.assume
=> [circt-lec] Register Verif dialect

docs/Dialects/Verif.md
Add a few examples of how contracts can be used to modularize formal verification. These will likely become integration tests once the machinery to execute them is in place.
=> [Verif] Add contract examples to dialect doc

include/circt/Dialect/OM/OMOps.td, lib/Dialect/OM/OMOps.cpp, test/Dialect/OM/errors.mlir
Add a region verifier to OM dialect's Class Op.  This verifies that the terminator returns the right number of fields with the correct types that match the declared type of the Class Op.
Fixes #7736.
=> [OM] Add ClassOp region verifier

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLOps.h, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp
In FIRRTL, all expression operations have a `validate` hook which can be used to check operands and attributes before passing them in to `inferResultTypes`.  FIRParser will verify the same invariants right before calling `validate`, making it redundant.  Since `validate` is only called from the parser, we can delete the entire hook.
=> [FIRRTL] Remove validation from type inference code

include/circt/Dialect/Verif/VerifOps.td, lib/Dialect/Verif/VerifOps.cpp, test/Dialect/Verif/basic.mlir
Slightly tweak the `verif.contract`, `verif.require`, and `verif.ensure` ops to match the usage outlined in the Verif dialect documentation. This also adjusts the operands and constraints slightly.
=> [Verif] Adjust contract ops to match documentation

include/circt/Conversion/AIGToComb.h, include/circt/Conversion/Passes.h, include/circt/Conversion/Passes.td, lib/CAPI/Conversion/CMakeLists.txt, lib/Conversion/AIGToComb/AIGToComb.cpp, lib/Conversion/AIGToComb/CMakeLists.txt, lib/Conversion/CMakeLists.txt, test/Conversion/AIGToComb/aig-to-comb.mlir, test/circt-synth/basic.mlir, tools/circt-synth/CMakeLists.txt, tools/circt-synth/circt-synth.cpp
This adds a conversion pass from AIG dialect to Comb dialect. AndInverterOp can be easily converted into comb.and + comb.xor + hw.constant.
This enables us to utilize core dialects tools for synthesis results without any addition. Primarly use case is running LEC on IR before and after synthesis.
=> [AIGToComb] [circt-synth] Add a AIG to Comb conversion pass

include/circt/Dialect/OM/OMOps.td, lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, lib/Dialect/OM/OMOps.cpp
Add a new API to update the fields of an existing `FieldsOp` in a class.
This also renames the `addFields` to ensure it is used to add a new Fields Op only.
=>  [OM] Add a new API to update fields of a ClassOp 

lib/Transforms/FlattenMemRefs.cpp, test/Transforms/flatten_memref.mlir
Caught a small issue with flattening the load.
Say we have an example:
```mlir
module {
func.func @main(%arg0: memref<3x4xi32>) {
%c1 = arith.constant 1 : index
%c2 = arith.constant 2 : index
%c3 = arith.constant 3 : index
%c4 = arith.constant 4 : index
%c0 = arith.constant 0 : index
%alloc = memref.alloc() {alignment = 64 : i64} : memref<4x2xi32>
scf.for %arg1 = %c0 to %c3 step %c1 {
scf.for %arg2 = %c0 to %c2 step %c1 {
scf.for %arg3 = %c0 to %c4 step %c1 {
%0 = memref.load %arg0[%arg1, %arg3] : memref<3x4xi32>
%1 = memref.load %alloc[%arg3, %arg2] : memref<4x2xi32>
%2 = arith.muli %1, %2 : i32
}
}
}
return
}
}
```
Previously, it gives:
```mlir
module {
func.func @main(%arg0: memref<12xi32>) {
%c1 = arith.constant 1 : index
%c2 = arith.constant 2 : index
%c3 = arith.constant 3 : index …
```
=> Transform Flatten Memref Load

include/circt/Dialect/Verif/Passes.td, include/circt/Dialect/Verif/VerifPasses.h, lib/Dialect/Verif/Transforms/LowerFormalToHW.cpp, lib/Dialect/Verif/Transforms/PrepareForFormal.cpp, lib/Dialect/Verif/Transforms/VerifyClockedAssertLike.cpp
Drop the `let constructor` line from the Verif pass definitions. This causes TableGen to automatically generate the constructors for these passes, and also handle pass options if we ever decide to add them.
This requires adding a `...Pass` to the end of each pass def to produce a constructor name of the form `create...Pass()`.
=> [Verif][NFC] Use auto-generated constructors for all passes

include/circt/Dialect/Arc/ArcOps.td, include/circt/Dialect/Arc/ArcPasses.h, include/circt/Dialect/Arc/ArcPasses.td, lib/Dialect/Arc/Transforms/AllocateState.cpp, lib/Dialect/Arc/Transforms/CMakeLists.txt, lib/Dialect/Arc/Transforms/Partition.cpp, test/Dialect/Arc/allocate-state.mlir, test/arcilator/partition-driver.cpp, test/arcilator/partition.mlir, test/arcilator/partition.state.h, tools/arcilator/arcilator.cpp
**This is a draft PR, which mostly serves the purpose of gathering feedbacks. Implemention is imcomplete and very hacky in places. See the "Unresolved issues" section below.**
This PR introduces a new pass (`--hw-partition`) into CIRCT to partition HW top-level modules into two or more parts. Each parts contains parts of the logic and states of the original circuit. Additional ports are created for signals that crosses partition bondaries. The pass tries to perserve origional modules and hierarchies.
The primary motivation is multithreaded simulation with Arcilator. To be more concrete, the targeted typical usecase of this pass is high performance multithreaded simulation using Arcilator, with HW modules compiled from FIRRTL, on a single CPU, with (mostly) static scheduling. Time stepping …
=> [Arc] Automatic module partition

lib/Transforms/FlattenMemRefs.cpp, test/Transforms/flatten_memref.mlir
This PR supports flattening of `memref::GetGlobalOp` and `memref::GlobalOp`.
Test case not yet included because I wasn't sure which script to use to auto update test mlir files.
=> Flatten memref GetGlobal and Global operations

include/circt/Dialect/Verif/Passes.td, include/circt/Dialect/Verif/VerifPasses.h, lib/Dialect/Verif/Transforms/LowerFormalToHW.cpp, lib/Dialect/Verif/Transforms/PrepareForFormal.cpp, lib/Dialect/Verif/Transforms/VerifyClockedAssertLike.cpp, test/circt-test/basic.mlir, tools/circt-test/circt-test.cpp
Add the `TestSuite` and `Test` classes to represent the discovered tests. Instead of directly printing ops to the output, first traverse the provided MLIR module and populate a test suite object with the discovered tests. Then print the list of tests in the test suite.
A separate test discovery step will later allow us to discover tests via other means, for example, by scanning an entire Verilog directory for marker comments.
=> [circt-test] Add test discovery classes and `-l` option

integration_test/CMakeLists.txt, integration_test/circt-test/basic.mlir, integration_test/lit.cfg.py, tools/circt-test/CMakeLists.txt, tools/circt-test/circt-test-runner-sby.py, tools/circt-test/circt-test.cpp
Extend circt-test to export the input MLIR file as Verilog and then run all discovered tests through a simple SymbiYosys runner script. This is currently very rigid: all tests are always run, and they all run through the exact same runner script. In the future, we'll want to add filtering mechanisms to include and exclude tests, and pick among multiple runner scripts for each test.
Also add a basic integration test that builds an adder from discrete logic gates and then verifies it through multiple `verif.formal` ops.
To run this you need to have SymbiYosys installed. In the future we'll want to have `circt-bmc` and other CIRCT-based verification tools available as runners as well.
=> [circt-test] Add simple SymbiYosys test runner

include/circt/Dialect/HW/HWOpInterfaces.td, include/circt/Dialect/HW/HWStructure.td, lib/Conversion/ExportVerilog/PrepareForEmission.cpp, lib/Dialect/Arc/Transforms/LowerState.cpp, lib/Dialect/SV/Transforms/SVExtractTestCode.cpp, lib/Tools/circt-bmc/ExternalizeRegisters.cpp
HWInstanceLike is currently 'empty' and thus essentially the same as InstanceGraphInstanceOpInterface. On the other hand, HWModuleLike deals with port names and hw::InstanceOp caches them and verifies they match the referenced module's port names. This PR basically makes this behavior part of what it means to be an HWInstanceLike. If one has an instance operation that does not deal with port names, it's still possible to just make it an InstanceGraphInstanceOpInterface directly
=> [HW] Add port name accessors to HWInstanceLike

lib/Transforms/FlattenMemRefs.cpp, test/Transforms/flatten_memref.mlir
This PR supports flattening of `memref::GetGlobalOp` and `memref::GlobalOp` along with test cases.
=> Flatten memref Global and its corresponding GetGlobal operations

include/circt/Dialect/Calyx/CalyxPrimitives.td, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Dialect/Calyx/Export/CalyxEmitter.cpp, lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp, test/Conversion/SCFToCalyx/convert_simple.mlir, test/Conversion/SCFToCalyx/errors.mlir, test/Dialect/Calyx/emit.mlir
This patch stacks on #7086 .
Add support for floating point addition in Calyx
=> Calyx Binary Floating Point AddF Operator

include/circt/Dialect/LTL/LTLOps.td, lib/Dialect/LTL/LTLFolds.cpp, lib/Dialect/LTL/LTLOps.cpp, test/Conversion/ExportVerilog/verif.mlir, test/Dialect/LTL/basic.mlir, test/Dialect/LTL/canonicalization.mlir
Extend `ltl.and`, `ltl.or`, and `ltl.intersect` to infer their return type as `i1` if all operands are `i1`. Also add a canonicalization method that replaces these ops with `comb.and` and `comb.or` if they operate entirely on `i1`.
=> [LTL] Canonicalize ltl.and to comb.and for i1 properties

include/circt/Dialect/LTL/LTLOps.td, lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, lib/Dialect/LTL/LTLFolds.cpp, lib/Dialect/LTL/LTLOps.cpp, test/Conversion/ExportVerilog/verif.mlir, test/Dialect/FIRRTL/expand-whens.mlir, test/Dialect/LTL/basic.mlir, test/Dialect/LTL/canonicalization.mlir, test/firtool/verif-under-when.fir
Make ExpandWhen's folding of the when condition into LTL properties work for more inputs. This used to be very brittle and the condition would be mapped to a new implication around the entire property:
when (a):
assert(@(posedge clock) b |-> c)
used to become
assert(a |-> @(posedge clock) b |-> c)
This commit improves on this by always pushing implications behind clocks, and by merging implications like `a |-> b |-> c` into a single `(a & b) |-> c`. As a result, ExpandWhens now produces the following output, which is more in line with what users expect:
assert(@(posedge clock) a & b |-> c)
Also add a FIR-to-Verilog test to nail this behavior down and ensure we don't regress on user expectations.
=> [FIRRTL] Fix folding of when conditions into LTL properties

include/circt/Dialect/FIRRTL/FIRRTLStructure.td, test/Dialect/FIRRTL/annotations-generic.mlir
Making this an inherent attribute means that it will be stored in the properties of the operation. Some module-like classes already had declared it as an input, but our older modules kinds did not.
=> [FIRRTL] Make `sym_name` an inherent attr for symbol ops

include/circt/Dialect/SV/SVTypeDecl.td, lib/Dialect/SV/SVOps.cpp
This change moves two InferfaceInstanceOp and GetModportOp to use the symbol user op interface when checking the referenced operation. This significantly reduces the cost of verifying this.
=> [SV] Use SymbolOpUserInterface to speed up verifiers

include/circt/Dialect/Calyx/CalyxControl.td, include/circt/Dialect/Calyx/CalyxLoweringUtils.h, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Dialect/Calyx/CalyxOps.cpp, lib/Dialect/Calyx/Export/CalyxEmitter.cpp, lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp, test/Conversion/SCFToCalyx/convert_func.mlir, test/Conversion/SCFToCalyx/convert_memory.mlir, test/Dialect/Calyx/emit-invoke-with-ref.mlir, test/Dialect/Calyx/emit-invoke.mlir, test/Dialect/Calyx/errors.mlir, test/Dialect/Calyx/round-trip.mlir
This patch addresses #4831 .
If the `main` `FuncOp` has `memref`s in its arguments, we create a new `main` component and make it the new entry point.
=> [Calyx] Passing memories by reference

integration_test/circt-test/basic.mlir, tools/circt-test/circt-test-runner-sby.py, tools/circt-test/circt-test.cpp
* Maintains default behavior of using `cover`, `bmc`, and `induction` tasks, but allows the user to supply a custom comma-separated `mode` string selecting specific tasks.  NOTE: The runner script still expects mode to be some subset of the above three.
* Adds a depth attribute/parameter for controlling bound or induction factor.  For now, this parameter is shared across all tasks.
=> [circt-test] Add simple runner interface for choosing modes and depth

lib/Conversion/DCToHW/DCToHW.cpp, lib/Conversion/HWArithToHW/HWArithToHW.cpp, lib/Conversion/HWToSMT/HWToSMT.cpp, lib/Conversion/HandshakeToDC/HandshakeToDC.cpp, lib/Conversion/HandshakeToHW/HandshakeToHW.cpp, lib/Conversion/LTLToCore/LTLToCore.cpp, lib/Conversion/MooreToCore/MooreToCore.cpp, lib/Conversion/SeqToSV/SeqToSV.cpp, lib/Dialect/ESI/Passes/ESILowerTypes.cpp
This is mostly a straightforward integration of LLVM. One minor change was that DialectConversion materializations have a slightly altered signature since
https://github.com/llvm/llvm-project/commit/f18c3e4e7335df282c468b6dff3d29be1822a96d.
The commit message includes this, but now we return `Value()` in the case where we previously returned `std::nullopt`. Otherwise, this should behave the same.
=> Bump LLVM to 8193832fb988e3df1e8e726634783805dca8d9b6.

lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir, test/Conversion/MooreToCore/errors.mlir, test/Dialect/Moore/basic.mlir
Lower `StringConstantOp` to `hw::ConstantOp`. Encodes strings as `APInt` with byte-width based on string length, enabling representation of Moore string constant as bit vectors.
=> [MooreToCore] Add support for moore::string_constant #7628

lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp, test/Dialect/FIRRTL/lower-memory.mlir
This PR is currently more of an experiment, not sure if it is the direction we will go.
=> [FIRRTL] ReplSeqMems: use the original mem name for the instance name

include/circt/Dialect/FIRRTL/AnnotationDetails.h, include/circt/Dialect/FIRRTL/CHIRRTLOps.td, lib/Dialect/FIRRTL/CHIRRTLDialect.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, lib/Dialect/FIRRTL/Transforms/LowerCHIRRTL.cpp, lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp, test/Dialect/FIRRTL/annotations.mlir, test/Dialect/FIRRTL/lower-chirrtl.mlir, test/Dialect/FIRRTL/lower-memory.mlir
We are in the process of reimplementing the `NestedPrefixModulesAnnotation` directly in Chisel, however there are still some things that Chisel can't do itself and needs to communicate more information to CIRCT. This adds a new `ModulePrefixAnnotation` annotation which can only target memories, which enables firtool to generate memories with correct names.
=> [FIRRTL] Add new ModulePrefixAnnotation

include/circt/Dialect/HW/HWOpInterfaces.td, include/circt/Dialect/HW/HWStructure.td, include/circt/Dialect/SV/SVTypeDecl.td, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Conversion/MooreToCore/MooreToCore.cpp, lib/Dialect/HW/HWOps.cpp, lib/Dialect/HW/Transforms/FlattenIO.cpp, lib/Dialect/SV/SVOps.cpp, lib/Dialect/SV/Transforms/SVExtractTestCode.cpp, lib/Dialect/Seq/Transforms/HWMemSimImpl.cpp, lib/Tools/circt-bmc/ExternalizeRegisters.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir, test/Conversion/ExportVerilog/sv-dialect.mlir, test/Conversion/ExportVerilog/verilog-basic.mlir, test/Dialect/SV/basic.mlir, test/Dialect/SV/hw-extract-test-code.mlir
Currently, doNotPrint is a boolean attribute, but using an optional unit attribute is a more idiomatic way to represent a flag as an attribute.
Changes:
- Switch doNotPrint over to a unit attribute
- Replace getAttr("doNotPrint") with accessors like getDoNotPrint
- Add doNotPrint to the HW dialect's ModuleLike interface, so we can switch even more places over to use the accessor.
=> [HW] Make module's doNotPrint a UnitAttr

lib/Dialect/OM/Transforms/FreezePaths.cpp
`PathVisitor::processPath` errors out on other `HWInstanceLike` operations. But other dialects can add paths on such operations, handle `HWInstanceLike` to support operations in other dialects.
=> [FreezePaths] Add support for HWInstanceLike, instead of only HWInstanceOp

lib/Firtool/Firtool.cpp, test/firtool/layer-merge-across-inlined-submodule.fir
The inliner could create new opportunities to merge layers. Run layer merge afterwards, in order to merge more things.
=> [firtool] Run layer merge after inliner

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/MooreToCore/basic.mlir
Add the `moore.trunc` operation to explicitly truncate the bit width of `IntType` values, and `moore.zext` and `moore.sext` to explicitly extend such a value with zeroes or its sign bit.
This requires tweaking the way how ImportVerilog generates conversion ops. Currently `moore.conversion` is used as a catch-all operation that expresses any kind of type conversion. In the future, we'll want to split this up into multiple dedicated operations. These width adjustment ops are the first step in that direction.
Making sign-extension explicit also fixes a long-standing issue where a `$signed` or `signed'(x)` expression would be erroneously converted into a zero-extension.
=> [Moore] Add explicit truncation and zero/sign-extension

lib/Dialect/FIRRTL/Transforms/InferReadWrite.cpp, test/Dialect/FIRRTL/inferRW.mlir
The InferRW pass, which simplifies memory ports, was not correctly copying all attributes from the old memory to the new simplified memory when the memory was not masked.
Fixes #7788
=> [FIRRTL] InferRW: copy all attributes of masked memeories

include/circt/Dialect/SMT/SMTOps.td, include/circt/Dialect/SMT/SMTVisitors.h, lib/Conversion/SMTToZ3LLVM/LowerSMTToZ3LLVM.cpp, lib/Target/ExportSMTLIB/ExportSMTLIB.cpp, test/Conversion/SMTToZ3LLVM/smt-to-z3-llvm.mlir, test/Dialect/SMT/basic.mlir, test/Target/ExportSMTLIB/core.mlir
Adds the SMTLIB reset op that resets a solver to its initial state
=> [SMT] Add reset op

.github/workflows/esiRuntimePublish.yml, lib/Dialect/ESI/runtime/CMakeLists.txt, lib/Dialect/ESI/runtime/pyproject.toml, lib/Dialect/ESI/runtime/setup.py
CMake 3.31 changed the behavior of `install(IMPORTED_RUNTIME_ARTIFACTS` to actually install them instead of merely adding them to the list. This ended up pulling in _all_ of the shared libs (including system libraries like `libm`, `libgcc`, etc.) instead of respecting the filters given in `install(RUNTIME_DEPENDENCY_SET`. As a result, auditwheel was failing. Happened over the weekend when a new version of the `cmake` package was published to PyPI.
=> [ESI][Runtime] Fix wheel builds

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, test/Dialect/FIRRTL/emit-metadata.mlir
Change the `CreateSiFiveMetadata` pass to only create metadata for modules which are instantiated in the design.
=> [FIRRTL] Only emit retime metadata for design

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, test/Dialect/FIRRTL/emit-metadata.mlir
Update the `CreateSiFiveMetadata` pass to treat blackboxes under layers as contributing to test harness JSON metadata.  This brings this metadata in line with other metadata which treats layers as "not design".
Note: for class-based metadata, this pass does not make any distinction between design and test.  Therefore, this commit does not make any change to class-based metadata.  Any blackboxes under layers will be included in class-based metadata.  (I have no idea if this distinction is correct or intended.  However, keeping this the same is at least self-consistent.)
=> [FIRRTL] Only add SiTest metadata for design

lib/Firtool/Firtool.cpp
Move the `LowerLayers` later in the `firtool` pass pipeline.  This is working towards moving this pass to the _end_ of the pipeline.  This movement is a prerequisite to enable two features:
1. Compilation of inline layers
2. Forcing out of a layerblock
=> [firtool] mv LoweLayers after CreateSiFiveMetadata

lib/Dialect/FIRRTL/Transforms/LowerIntmodules.cpp
The EICG wrapper warning is be emitted unless the switchover to the intrinsic is made.
There are some designs where we have hundreds of clock gates, the warning clogs up the stdout for such cases.
This commit, ensures the warning is emitted only once.
=> [FIRRTL] Emitting EICG wrapper warning only once

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, include/circt/Firtool/Firtool.h, lib/Dialect/FIRRTL/Transforms/Dedup.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/dedup.mlir
The previous behavior for local trackers would be to clone the tracker into duplicate copies for each unique instance. This will fail in LowerClasses, because one path op that used to refer to a single entity as a local reference would now refer to every hierarchical instance of that entity. One path can't refer to multiple things, so if the user specified a local reference, allow that to pass through without expanding it into every hierarchical instance.
=> [FIRRTL] Don't force non-local trackers in Dedup.

test/circt-verilog/basic.mlir, tools/circt-verilog/CMakeLists.txt, tools/circt-verilog/circt-verilog.cpp
Add a `--format` option to circt-verilog that allows it to read SV and MLIR input files. Being able to read MLIR files is useful for debugging or when developing new transformation passes.
Also makes error message use the `WithColor::error()` prefix for somewhat nicer readability.
=> [circt-verilog] Support MLIR and MLIRBC input files

lib/Firtool/Firtool.cpp, test/firtool/canonicalize-away-assert-under-layer.fir
IMCP propagates constants across modules, which should enable more
canonicalization.  However, lower-layers, which runs between IMCP and
canonicalization, takes layerblocks and outlines them into their own module.
This effectively undoes the work of IMCP, and prevents us from canonicalizing
as well as we should under layers. This PR adds an additional run of the canonicalizer
immediately after the second run of IMCP, so that we have a better shot at
canonicalization.
In particular, we want to ensure that we are able to canonicalize away dead
assertions and assumptions under layerblocks.
=> [FIRRTL] Run canonicalizer again after IMCP

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, include/circt/Firtool/Firtool.h, lib/Dialect/FIRRTL/Transforms/Dedup.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/dedup.mlir
Reverts llvm/circt#7709
There were some post-commit questions about this approach, and I'm also not positive we even need the changes any more. If we do, we can either re-land this in its current form, with its warts, or we can solve the problem with more intelligent logic in LowerClasses.
=> Revert "[FIRRTL] Don't force non-local trackers in Dedup."

lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp, test/Dialect/FIRRTL/extract-instances.mlir
Update the `ExtractInstances` pass to not extract modules which are instantiated under layers.  For situations where a module is both in the design and under a layer, the module will be extracted up to the point where the instance is outside the design.  This is the same behavior that the pass does if a module is instantiated by both the test harness and the design.
=> [FIRRTL] Add layer support to ExtractInstances

include/circt/Dialect/HW/HWOpInterfaces.td, include/circt/Support/InstanceGraphInterface.td
Add a verifier to `HWInstanceLike` to ensure the referenced modules list is non empty.
=> [HW] Add a verifier for HWInstanceLike

include/circt/Dialect/FIRRTL/FIRParser.h, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir, test/firtool/classes-dedupe.fir
Mark all parser features that were part of FIRRTL spec 3.3.0 [1] as requiring version `{3, 3, 0}` instead of `nextFIRVersion`. Bump the `nextFIRVersion` to be 4.0.0, matching the `exportFIRVersion` as it used to be the case earlier. Note that specifically the "List concat" feature was not part of 3.3.0 and is therefore still marked as `nextFIRVersion`.
Also add a `missingSpecFIRVersion` to mark the features in the parser that have not been added to the spec yet. This avoids accidental replacement of the version during the next spec release.
This change requires a few tweaks to the regression tests, where a few features like `class`, `Bool`, `Double`, `Inst`, `path`, and more, were tested under FIRRTL 3.3.0, assuming they would be released as part of the spec in that version. But the …
=> [FIRRTL] Bump nextFIRVersion to 4.0.0 in the parser

lib/Firtool/Firtool.cpp
Now that `ExtractInstances` supports layers [[1]], we can move `LowerLayers` after it in the pass pipeline.  This commit works towards moving `LowerLayers` to the end of the FIRRTL pipeline in order to allow inline layers to be compiled and support forcing out of layers.
[1]: cc3fecf18eeb06abb3cb31dcd935adf02ba7b0a1
=> [FIRRTL] Move LowerLayers after ExtractInstances

docs/Dialects/FIRRTL/RationaleFIRRTL.md
Add a few lines to the FIRRTL dialect rationale that outline how we deal with new releases of the FIRRTL specification, and how we develop features between CIRCT and the specification.
=> [FIRRTL] Document how to deal with specification releases

lib/Conversion/HandshakeToDC/HandshakeToDC.cpp, test/Conversion/HandshakeToDC/basic.mlir
Adds lowering patterns for `handshake.pack/unpack` to DC. For the actual (data-side) tuple operations, `hw.struct`s are used. This is purely for pragmatic reasons; Firstly, `hw.struct` is for all intents and purposes a generic struct type. Secondly, we don't want data-only operations to leak into `DC`.
=> [HandshakeToDC] Add pack/unpack lowering patterns

include/circt/Transforms/Passes.h, include/circt/Transforms/Passes.td, lib/Transforms/CMakeLists.txt, lib/Transforms/MemoryBanking.cpp, test/Transforms/memory_bank_invalid.mlir, test/Transforms/memory_banking.mlir
This patch partition memories used inside affine parallel loops into even banks and replace the old memrefs with new ones throughout the program.
=> [Transform] Create memory banks for memories used inside affine parallel loops

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
Dedup tries to hash all modules in parallel.  To accomplish this, the names of instantiated modules are not included as part of the structural hash, but they are taken in to account when checking if two modules are the same.  This process involves comparing the instantiated children modules of two modules if their hashes match.  This was implemented by using an array attribute, to make comparisons quicker.
When a module or class has many thousands of instances underneath it, it becomes impractical to build a array attribute with every child module. Interning such a large ArrayAttr is incredibly slow and will eat up that memory for the rest of the process.
Instead, we don't bother interning the instance arrays, and just keep them as plain old vectors, which comes with the benefit of not …
=> [FIRRTL] Dedup: speed up handling of instances

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
We map operations to their index as they appear in the IR, so that we can use the index when hashing their uses as operands and inner-symbol references. We only need to bother assigning indices to operations which actually have results or an inner-symbol.  Technically we can do a little better, the result or symbol has to actually have a user, but we we don't have many trivially dead expressions on our input.
=> [FIRRTL] Dedup: record less indices when hashing

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir
The problem has been noted in #6317. I ran into it when writing a SV lowering for `sim.triggered`, where it caused incorrect behavior.
This PR is a hot-fix to specifically prevent illegal inlining of non-procedural continuous assignments to `LogicOp`s.
=> [ExportVerilog] Do not inline non-procedural continuous assignments to variables

include/circt/Dialect/Seq/SeqOps.td, lib/Dialect/Seq/Transforms/LowerSeqFIFO.cpp, test/Dialect/Seq/lower-fifo.mlir
- Makes $input and $output allow any type rather than just a bit vector.
- Adds read latency attribute to specify the number of cycles after which rdEn is asserted that data appears in the output.
=> [Seq] FIFO: permit any type and add read latency

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, lib/Dialect/FIRRTL/Export/FIREmitter.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/round-trip.mlir
Adjust the syntax for the FIRRTL `formal` construct such that it no longer expects a single `bound = <N>` parameter, but accepts a list of user-defined integer, string, array, or dictionary parameters. The syntax now looks like
```
formal someTest of SomeModule:
a_int = 42
b_string = "hello"
c_array = [42, "hello", [9001], {foo = 1337}]
d_map = {a = 42, b = "hello", c = [9001], d = {foo = 1337}}
```
instead of the previous
```
formal someTest of SomeModule, bound = 42
```
The previous syntax is still supported until the corresponding change to the FIRRTL spec lands. Since it is not yet entirely clear what the list of necessary or well-understood parameters for formal tests is, the presence of `bounds` is no longer enforced. The rationale here being that this might turn out to be just a …
=> [FIRRTL] Accept list of parameters for `formal` construct

include/circt/Dialect/Handshake/HandshakeOps.h, include/circt/Dialect/Handshake/HandshakeOps.td, lib/Conversion/HandshakeToHW/HandshakeToHW.cpp, lib/Dialect/Handshake/HandshakeOps.cpp, test/Conversion/HandshakeToHW/test_instance.mlir, test/Dialect/Handshake/call.mlir
Adds the ESIInstanceOp. This op allows a non-handshake design to instantiate `handshake.func`s. Since handshake needs elastic inputs and produces elastic outputs, this uses ESI channels.
=> [Handshake] Adding func instance op for integration

lib/Dialect/FIRRTL/Transforms/Dedup.cpp
Hashing modules back->front lets us be a bit leaner with the state we
have to track, and hopefully will give us a nice speed improvement.
In the old algorithm, as we hashed each operation or block in the
module, we would store its position as an index into a side-table.  When
a value is used, we could record the use by hashing-in the result-no and
the defining operation's index (or argument-no and block index, resp).
This index table is a major performance bottleneck for dedup: in a large
module, this table can be massive. The observation made is that values
tend to only be used near their definition. After we hash the last use
of an operation or block, we should be safe to remove its index from the
index table, and keep the index table as small as possible.
This PR modifies the hasher to …
=> [FIRRTL] Dedup: hash modules back->front

lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp
Simplify the class lowering logic by directly moving or cloning operations
instead of cloning the entire module body. This change:
- Removes the need to clone the entire module region
- Only clones instance operations that need to be preserved
- Directly moves property operations to the OM class
- Removes redundant block cleanup
=> [FIRRTL] Refactor class lowering to avoid unnecessary cloning

tools/hlstool/CMakeLists.txt, tools/hlstool/hlstool.cpp
Adds a `--dc` flag to use HandshakeToDC (and the DC lowering flow) instead of HandshakeToHW. Not enabling any tests since (AFAICT) none of them pass with this option.
=> [hlstool] Add option to use the DC lowering flow

include/circt/Dialect/FIRRTL/FIRParser.h, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/CAPI/firrtl.c, test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir, test/firtool/classes-dedupe.fir, test/firtool/instchoice.fir
FIRRTL v4.0.0 was released [[1]].  Update the FIRRTL parser to correctly accept/reject features from this version now that the feature has solidified.  Fix a number of incorrect version checks.
Note: when going through this, I realized that the 3.3.0 version made some breaking changes, notably with respect to "optional groups".  These were added in 3.2.0 and dropped in 3.3.0 (in favor of layers).  This isn't hugely problematic, however, it did violate the FIRRTL specification versioning policy.  Oops.
The proliferation of version checks on FIRRTL features is really starting to make me think that we want to put this into a tabular structure indicating: (1) when a feature was added and (2) when a feature was removed.  We can then just check all these features automatically as opposed to …
=> [FIRRTL] Update, fix parser versions

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_simple.mlir, test/Conversion/SCFToCalyx/errors.mlir
This patch lowers `scf::parallel` to Calyx, assuming that all induction variables can be statically derived and that `scf::reduce` does not have operands.
=> [Calyx] Lower SCF parallel op to Calyx

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp
We have a bitvector of arguments we need to erase from the newArgs vector. Erase them in a single pass by shifting args down, overwriting the erased arguments, and dropping the extra args left over in the tail. The previous algorithm had scaling issues when the number of args was very large.
=> [FIRRTL] LowerTypes: Manually compact newArgs vector

include/circt/Dialect/Calyx/CalyxInterfaces.td, include/circt/Dialect/Calyx/CalyxLoweringUtils.h, include/circt/Dialect/Calyx/CalyxOps.h, include/circt/Dialect/Calyx/CalyxPrimitives.td, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Dialect/Calyx/CalyxOps.cpp, lib/Dialect/Calyx/Export/CalyxEmitter.cpp, lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp, test/Conversion/SCFToCalyx/convert_simple.mlir, test/Dialect/Calyx/emit.mlir
Add support for floating point multiplication in Calyx
=> [Calyx] Binary Floating Point MulF Operator

include/circt/Dialect/RTG/IR/RTGOps.td, lib/Dialect/RTG/IR/RTGOps.cpp, test/Dialect/RTG/IR/basic.mlir, test/Dialect/RTG/IR/errors.mlir
Add operations to use sequences within other sequences and in tests.
=> [RTG] Add `sequence_closure` and `invoke_sequence` operations

include/circt/Dialect/RTG/IR/CMakeLists.txt, include/circt/Dialect/RTG/IR/RTGInterfaces.td, include/circt/Dialect/RTG/IR/RTGOpInterfaces.h, include/circt/Dialect/RTG/IR/RTGOps.h, include/circt/Dialect/RTG/IR/RTGOps.td, include/circt/Dialect/RTG/IR/RTGTypeInterfaces.h, lib/Dialect/RTG/IR/CMakeLists.txt, lib/Dialect/RTG/IR/RTGOpInterfaces.cpp, lib/Dialect/RTG/IR/RTGTypeInterfaces.cpp
Add the interfaces needed to add the `on_context` operation and the RTG test dialect in future PRs.
=> [RTG] Add context resource interfaces

lib/Tools/circt-bmc/ExternalizeRegisters.cpp
Just a cleanup commit that reuses `unwrapImmutableValue` instead of pretty much reimplementing it as I only just found out it existed - thanks for including this @uenoku!
=> [ExternalizeRegisters][NFC] Clean up initial value fetching

lib/Conversion/HWToBTOR2/HWToBTOR2.cpp, test/Conversion/HWToBTOR2/errors.mlir
Currently HWToBTOR2 crashes on both of the included error cases:
1. `unwrapImmutableValue` throws an assert whenever it's given a value that wasn't defined by an initialOp, so I've added a check for that. While the first error case isn't technically legal anyway as instance ops aren't allowed in HWToBTOR2, the pass currently crashes before it gets to that point.
2. Initial values given as a block argument will throw an error in requireSort as they don't have a queriable width. Pretty unlikely edge case, but can't hurt to have it covered! I've added it to the list of sorts ignored by requireSort, and it'll now get mopped up by the same check as point 1 rather than crashing
=> [HWToBTOR2] Fix crashes on initial value corner cases

lib/Conversion/HWToBTOR2/HWToBTOR2.cpp, test/Conversion/HWToBTOR2/comb.mlir
Currently creating a constant with any value that won't fit in an i64 will break HWToBTOR2 as it tries to fetch the value from an APInt and place it in an int64_t - not ideal if you have wires wider than 64 bits.
Breaking example:
```
hw.module @top() {
hw.constant 111111111111111111111111111 : i100
}
```
This just swaps to using the APInt directly to print the value - AFAICT this will still yield correct BTOR2.
=> [HWToBTOR2] Use APInt value directly in constant generation

lib/Conversion/HWToBTOR2/HWToBTOR2.cpp, test/Conversion/HWToBTOR2/compreg.mlir
Currently HWToBTOR2 produces invalid BTOR2 on a module with two registers that have the same initial value as it prints the const definition twice (resulting in an illegal redefinition).
E.g.:
```
hw.module @top(in %clk: !seq.clock, in %input : i8) {
%0 = seq.initial () {
%c0_i8 = hw.constant 0 : i8
seq.yield %c0_i8 : i8
} : () -> !seq.immutable<i8>
%reg1 = seq.compreg %input, %clk initial %0 : i8
%reg2 = seq.compreg %input, %clk initial %0 : i8
}
```
is translated to 
```
1 sort bitvec 8
2 input 1 input
3 state 1 reg1
4 constd 1 0
5 init 1 3 4
6 state 1 reg2
4 constd 1 0
7 init 1 6 4
8 next 1 3 2
9 next 1 6 2
```
where 4 is illegally defined twice. Simple fix, just checks whether the op has already been handled.
=> [HWToBTOR2] Avoid duplicating initial consts

test/Conversion/ExportVerilog/hw-enums.mlir, test/Conversion/HWToBTOR2/errors.mlir
See #7852.
The CI failed on 2d416afa8326e3ceaab2e96606f50ed3084df0a3 :
```
RUN: at line 1: /__w/circt/circt/build/bin/circt-opt /__w/circt/circt/test/Conversion/HWToBTOR2/errors.mlir --convert-hw-to-btor2 --verify-diagnostics --split-input-file -o /__w/circt/circt/build/tools/circt/test/Conversion/HWToBTOR2/Output/errors.mlir.tmp
+ /__w/circt/circt/build/bin/circt-opt /__w/circt/circt/test/Conversion/HWToBTOR2/errors.mlir --convert-hw-to-btor2 --verify-diagnostics --split-input-file -o /__w/circt/circt/build/tools/circt/test/Conversion/HWToBTOR2/Output/errors.mlir.tmp
circt-opt: /__w/circt/circt/llvm/llvm/lib/Support/raw_ostream.cpp:115: void llvm::raw_ostream::SetBufferAndMode(char *, size_t, BufferKind): Assertion `GetNumBytesInBuffer() == 0 && "Current buffer is non-empty!"' failed. …
```
=> [NFC] Output unused test results to `/dev/null`

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_simple.mlir
This patch fixes https://github.com/llvm/circt/issues/7861.
=> [SCFToCalyx] `buildLibraryBinaryPipeOp` source operation result replacement

lib/Conversion/ImportVerilog/Structure.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/builtins.sv
Adds shadow variables for SV function arguments.
Fixes: https://github.com/llvm/circt/issues/7431
Adjusts two test cases ```test/Conversion/ImportVerilog/basic.sv``` and ```test/Conversion/ImportVerilog/builtins.sv```
Adds two test functions in ```test/Conversion/ImportVerilog/builtins.sv```, which will crash in the former ```circt-verilog``` tool.
=> [ImportVerilog]: Create variables for function arguments

include/circt/Conversion/Passes.td, lib/Firtool/Firtool.cpp
Change the base operation for the HWToBTOR2 pass from `hw::HWModuleOp` to `mlir::ModuleOp`.
Running this pass in parallel on HWModules will just produce garbled output on the provided output stream. It is also likely the cause for the current CI failures (#7852, #7859, #7863). Multiple pass instances get instantiated with the same `raw_ostream` singleton returned by `llvm::outs()`. I do not think it is thread safe (why would it be?) and the CI stack traces point  quite clearly to a race condition in `raw_ostream::write`.
=> [NFCI][HWToBTOR2] Avoid running HWToBTOR2 pass in parallel

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
Add a lowering from `firrtl.formal` to `verif.formal` in the FIRRTL-to-HW conversion. The lowering creates a `verif.formal` op that simply instantiates the module pointed to by `firrtl.formal`, with symbolic values providing the inputs to the module. We may want to inline the instance in the future, but that is purely cosmetic.
This now allows FIR files to contain `formal` unti tests that can be lowered to HW through `firtool` and then executed using `circt-test`.
=> [FIRRTL] Lower firrtl.formal to verif.formal

include/circt/Dialect/Verif/VerifOps.td, integration_test/circt-test/basic.mlir, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Dialect/Verif/basic.mlir, test/Dialect/Verif/lower-formal-to-hw.mlir, test/circt-test/basic.mlir, tools/circt-test/circt-test.cpp
Instead of using the discardable attributes dictionary of `verif.formal` as vessel for user-defined test parameters, add a dedicated `parameters` field to the op itself. This makes the parameters non-discardable and a proper part of the test.
=> [Verif] Make verif.formal parameters an ODS property

integration_test/CMakeLists.txt, integration_test/circt-test/basic-circt-bmc.mlir, integration_test/circt-test/basic-sby.mlir, integration_test/circt-test/basic.mlir, tools/circt-test/CMakeLists.txt, tools/circt-test/circt-test-runner-circt-bmc.py, tools/circt-test/circt-test.cpp
Add a runner script for `circt-bmc` to circt-test. This allows CIRCT's own model checker to be used to verify `verif.formal` operations in MLIR inputs. The user currently has to pass the runner to circt-test explicitly using the `-r` option. In the future, we'll want to add a mechanism to circt-test to list available runners, check if the needed software is installed on the system, and configure new local runners through some config file.
=> [circt-test] Add runner for circt-bmc

lib/Conversion/HandshakeToDC/HandshakeToDC.cpp, test/Conversion/HandshakeToDC/basic.mlir
Lower the ESIInstanceOp to `hw.instance` with `dc.from_esi` and `dc.to_esi` to convert the args/results.
=> [HandshakeToDC] Implement ESIInstanceOp lowering

.github/workflows/nightlyIntegrationTests.yml, .github/workflows/shortIntegrationTests.yml, integration_test/Dialect/Handshake/multiple_loops/multiple_loops.py, integration_test/Dialect/Handshake/nested_loops/nested_loops.py, lib/Bindings/Python/pyproject.toml, lib/Conversion/DCToHW/DCToHW.cpp, lib/Conversion/HandshakeToHW/HandshakeToHW.cpp, lib/Dialect/Arc/Transforms/ArcCanonicalizer.cpp, lib/Dialect/Calyx/Transforms/CalyxHelpers.cpp, lib/Dialect/Calyx/Transforms/RemoveCombGroups.cpp, lib/Dialect/FIRRTL/FIRRTLUtils.cpp, lib/Dialect/HW/HWOps.cpp, tools/handshake-runner/Simulation.cpp
The main difference was in changes related to the APInt constructor.
This was needed when
https://github.com/llvm/llvm-project/commit/3494ee95902cef62f767489802e469c58a13ea04
landed.
Similar changes were made upstream here:
https://github.com/llvm/llvm-project/pull/80309/files.
Basically, we now expect the width and value arguments to the APInt
constructor to be consistent. There is some implicit extension or
truncation depending on the signedness of the value, and now a flag to
opt into it.
With this change I've simply opted into the flag where necessary,
rather than thinking hard about how to compute the correct width given
the value.
In places where the `isSigned` flag took the default value of false, I
kept that when I had to explicitly set that flag.
There was exactly one place …
=> Bump LLVM to 3cc852ece438a63e7b09d1c84a81d21598454e1a.

include/circt/Dialect/SMT/SMTOps.td, integration_test/Dialect/SMT/basic.mlir, lib/Conversion/SMTToZ3LLVM/LowerSMTToZ3LLVM.cpp, test/Conversion/SMTToZ3LLVM/smt-to-z3-llvm.mlir, test/Dialect/SMT/basic.mlir, test/Dialect/SMT/core-errors.mlir
Adds push and pop ops to add/remove assertions from the assertion stack as per SMTLIB.
Unfortunately SMTLIB specifies that each of them takes a number of levels to push/pop but the Z3 API only provides such an argument for pop, so we have to make multiple calls for a big push (but I can't imagine that this will ever really be used in practice).
=> [SMT] Add push/pop operations

integration_test/Dialect/SMT/basic.mlir, integration_test/Target/ExportSMTLIB/basic.mlir
Small one, just belatedly adds some integration tests for the reset op added in #7791 - ~~I'll rebase this once I've merged #7873 as they'll conflict slightly~~ (done now)
=> [SMT] Add integration tests for `smt.reset`

lib/Dialect/FIRRTL/Transforms/Dedup.cpp, test/Dialect/FIRRTL/dedup-errors.mlir, test/Dialect/FIRRTL/dedup.mlir
This change allows private modules to deduplicate in to public modules.  It does this by swapping a private canonical module with a public module when found.  Future public modules will not deduplicate into this group, as public modules can not dedup with other public modules in general.  This also begins ignoring the convention of private modules, as it doesn't really carry any meaning.  In the future we might want to disallow conventions to be specified on private modules.
=> [FIRRTL] Dedup: dedup private modules into public ones

lib/Analysis/FIRRTLInstanceInfo.cpp, lib/Dialect/FIRRTL/Transforms/CheckLayers.cpp, test/Dialect/FIRRTL/check-layers-errors.mlir
Change the InstanceInfo analysis to treat GrandCentral views as being
"under a layer".  This is the consistent, inclusive interpretation of
"under" with respect to the design.  I.e., since the
design-under-test (DUT) is under the design, a GrandCentral view should be
under a layer.
Rewrite the `CheckLayers` pass to more directly rely on the `InstanceInfo`
analysis.  Instead of the top-down walk (which was there from the original
architecture which did not have access to `InstanceInfo` and was
originally pushing layer information down), use only a bottom-up walk and
rely on the `InstanceInfo` analysis to determine when modules could be
problematic.  This preserves a similar style of the original verbose
errors/notes which reports transitive errors (modules which do not contain
layers, but …
=> [FIRRTL] Rewrite, extend CheckLayers for GC Views

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/simplify-mems.mlir
Before this PR, FoldRegMems would construct new ops in the "body of the parent FModuleOp". We need to place these ops in the same block as the memory.
This PR fixes a bug where, when a memory under a layerblock was canonicalized to a register, the register would be placed at the original location of the memory (under the layerblock), but its readers would be placed outside the layerblock, resulting in a dominance checking error.
=> [FIRRTL] FoldRegMems: insert new ops into same block as memory

lib/Dialect/Verif/VerifOps.cpp, test/Conversion/VerifToSMT/verif-to-smt-errors.mlir, test/Dialect/Verif/errors.mlir
This adds a verification requirement that if a `BoundedModelCheckingOp` has a non-zero num_regs attribute, there must be a clock in the circuit region's arguments (to clock the registers with).
=> [Verif] Require a clock when num_regs is non-zero on a BMC op

lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/SFCTests/directories.fir, test/firtool/formal.mlir
Add the `LowerFormalToHW` pass to the HW-to-SV pipeline of firtool. This will make any `verif.formal` ops be emitted as additional top-level modules, which is in line with what circt-test also does.
In the future we may want to have additional controls in firtool to disable emission of these formal tests. (But we would likely do this by removing them early in the pipeline to open up new optimization possibilities rather than not emitting them at the final stage.)
This creates a small amount of churn in the `directories.fir` test which was sensitive to _any_ kind of folder running, e.g. through the dialect conversion or greedy rewriter framework. The latter one is used by the formal op lowering, and it's probably a good idea to not have tests fail when a very common optimization runs.
=> [firtool] Run LowerFormalToHW pass when emitting SV

include/circt/Transforms/Passes.h, include/circt/Transforms/Passes.td, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Transforms/CMakeLists.txt, lib/Transforms/IndexSwitchToIf.cpp, test/Transforms/switch-to-if.mlir
This transform is meant for dialects that inherently does not have a `switch` control statement (like Calyx)
=> SCF IndexSwitch to nested If-Else

.github/workflows/nightlyIntegrationTests.yml, .github/workflows/shortIntegrationTests.yml
This image includes an up-to-date build of Yosys and SymbiYosys, useful for testing the new circt-test formal flows.
=> [CI] Bump integration test image to 18.0

include/circt/Dialect/FIRRTL/FIRRTLStatements.td, lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp, test/Dialect/FIRRTL/imdce.mlir
Fix a bug in FIRRTL's IMDCE Pass where it would not visit the blocks of operations.  This can result in crashes for blocks which contain users of FIRRTL modules, e.g., instances inside layerblocks of sv.ifdef.
This conceptually is two changes: (1) when marking a block live, the block needs to be recursively walked and (2) when erasing ops, a recursive walk is needed.
=> [FIRRTL] Make IMDCE work for ops w/ regions/blocks

integration_test/lit.cfg.py
#7857 introduces a Python script to test `circt-bmc`, but there are two problems:
1. We need to add the script to the substitution list in `lit.cfg.py` so that lit can correctly substitute the path in the test.
2. The script invokes `circt-opt` but the executable is not in the PATH variable causing python cannot find it. This PR simply adds `circt_tool_dir` to PATH to resolve it, but I think a better way is to get rid of the python script and allow lit to substitute the path.
=> [circt-test] fix lit config for circt-bmc

integration_test/circt-bmc/seq.mlir
This test was made for an outdated version of circt-bmc and only passes now because of a bug (fix incoming!)
=> [circt-bmc] Drop outdated integration test

lib/Conversion/ImportVerilog/Expressions.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/errors.sv
@fabianschuiki, @hailongSun2000 
Add moore.stream_concat operation for streaming like concat, it's currently a draft version and call for comments. for lvalue, {1 << {i32, i32, i32}} will be treated like 
```
(!moore.ref<i32>, !moore.ref<i32>, !moore.ref<i32> 0) -> <stream_concat<{!moore.i32, !moore.i32, !moore.i32}, 0>>
```
and it will be process in the core dialect.
Because the stream concat operation is so flexible, various datatype is acceptable as input, so I just Postponed the actual analysis. And stream concat oepration just be treated like a conversion from input to a packed type.
=> [ImportVerilog] add stream concat operation

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/simplify-mems.mlir
The FoldUnusedBits folder will, when it sees a memory with obviously unused bits (all readers are bitselect ops), will compress that memory to a smaller integer. The data written to the memory has to be compressed to just the relevant bits, which is done using a sequence of bit-select and bit-concat ops on the data. The result of these ops is unsigned. If the memory itself stores a signed integer, then we need to cast this data back to a signed value.
=> [FIRRTL] FoldUnusedBits: Cast compressed data back to signed integer

lib/Dialect/FIRRTL/FIRRTLFolds.cpp
Two changes:
- Bail early when all bits in the memory are used, we clearly cannot run the cannonicalizer.
- Use createOrFold when creating new ops. After shrinking the memory, the readers, which are bit select and concat ops, will typically just be selecting the entire memory anyways, so they can be eagerly folded away.
=> [FIRRTL] FoldUnusedBits: minor cleanup

integration_test/circt-lec/hw.mlir, lib/Conversion/HWToSMT/HWToSMT.cpp
Resolves https://github.com/llvm/circt/issues/7664
=> [HWToSMT] ArrayCreateOp and ArrayGetOp support

integration_test/circt-bmc/seq-errors.mlir, lib/Conversion/VerifToSMT/VerifToSMT.cpp, test/Conversion/VerifToSMT/verif-to-smt-errors.mlir, test/Conversion/VerifToSMT/verif-to-smt.mlir
Changes circt-bmc to use the initial values added to the BMC op in #7729 to initialize register states - this should mean circt-bmc can now check meaningful properties! :tada: 
The added integration test checks whether the counter value always stays below a certain value with different time bounds, which also functions as a check that assertions are getting popped as mentioned in #7900
=> [circt-bmc][VerifToSMT] Add initial value support

lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp
#7860 broke Windows CI as it uses designated initializers which are c++ 20 - this just reformats the bits where they were used.
=> [Calyx] Avoid using designated initializers

lib/Conversion/VerifToSMT/VerifToSMT.cpp
Tiny change, just makes it so VerifToSMT exits early after throwing the too many clocks error (rather than still trying to apply the pass).
=> [VerifToSMT] Exit early after too many clocks error

include/circt/Dialect/SMT/SMTOps.td, include/circt/Dialect/SMT/SMTVisitors.h, integration_test/Target/ExportSMTLIB/basic.mlir, lib/Target/ExportSMTLIB/ExportSMTLIB.cpp, test/Dialect/SMT/basic.mlir, test/Target/ExportSMTLIB/core.mlir
Adds an operation to set the logic to be used by the SMT solver. I'll put the lowering to Z3 in a follow-up PR after this one since it requires some extra checks due to limitations on what Z3 allows so it has a larger diff.
=> [SMT] Add set_logic operation

lib/Dialect/FIRRTL/Transforms/MergeConnections.cpp, test/Dialect/FIRRTL/merge-connections.mlir
Modify the `MergeConnections` pass to walk into regions and blocks. Because the algorithm used in this pass wants to insert operations _after_ the operation that is currently being processed _and then_ visit them, this cannot use a normal `Operation::walk` (since this will pre-increment and not visit these operations).  Keep this existing algorithm, but use an iterator worklist to make this behave like a walk.
This is done as part of moving `LowerLayers` to the end of the FIRRTL pipeline so that inline layer support (which requires producing `sv.ifdef` operations which we would like to hide from the rest of the FIRRTL pipeline) can be turned on.
=> [FIRRTL] Support layers in MergeConnections

include/circt-c/Firtool/Firtool.h, include/circt/Firtool/Firtool.h, lib/CAPI/Firtool/Firtool.cpp, lib/Firtool/Firtool.cpp
This PR adds the option to run CSE only on `firrtl.module`, and ignore everything else.
There are some tools, that are not able to handle CSE of `firrtl.object` in `firrtl.class`. 
Specifically, the reuse of `firrtl.object` is not modeled properly.
This is a temporary workaround to disable the CSE of operations inside `firrtl.class`, which can be removed once the actual issue in the tool is fixed.
=> [firtool] Add an option to disable CSE in classes

lib/Conversion/HWToBTOR2/HWToBTOR2.cpp, test/Conversion/HWToBTOR2/compreg.mlir, test/Conversion/HWToBTOR2/init.mlir, test/firtool/btor2-assertproperty.fir
The BTOR2 parser in btor2tools (which seems to be the standard implementation) requires that in an init statement, the ID of the state must be higher than the ID of the initial value. Currently we don't adhere to this, so we generate BTOR2 that's not digestible by most tools.
E.g. we currently emit 
```
hw.module @breaks(in %clk: !seq.clock, in %in: i32) {
%c0_i32 = seq.initial() {
%0 = hw.constant 0 : i32
seq.yield %0 : i32
} : () -> !seq.immutable<i32>
%reg = seq.compreg %input, %clk initial %c0_i32 : i32
%input = comb.add %in, %in : i32
}
```
as 
```
1 sort bitvec 1
2 input 1 reset
3 state 1 reg
4 constd 1 0
5 init 1 3 4
6 constd 1 0
7 eq 1 3 6
8 not 1 7
9 bad 8
10 ite 1 2 6 6
11 next 1 3 10
```
and btormc throws the error `btormc: parse error in 'breaking.btor2' line 5: state id must …
=> [HWToBTOR2] Generate register initial constant before state declaration

include/circt/Dialect/RTG/IR/CMakeLists.txt
This makes it properly includable in the rationale file. Overlooked this in the fix for https://github.com/llvm/circt/issues/7932. Sorry.
=> [RTG] Generate separate doc files for ops and types

lib/Dialect/DC/DCOps.cpp, test/Dialect/DC/canonicalization.mlir
Adding a canonicalizer to remove unused results from forks. Required to get valid post-canonicalization IR. Also, narrow the scope of "XFAIL"s in canonicalizer test to add new one.
=> [DC] Add unused fork result elimination canonicalizer

tools/arcilator/arcilator-header-cpp.py
This commit refactors the Python script for generating C++ headers by replacing hard-coded `print` statements with Jinja templates. The template is now independently defined within the script, improving code readability and maintainability. The output remains consistent with the previous version.
The bare statements are also refactored into several functions. They are put into the `if __name__ == "__main__":` block to avoid being executed when imported by other modules.
A test has been run to see that this change does not make the output differ. Selected test sources include simple circuits, existing circuits in the arcilator's tests, and risc-v mini. The circt source code does not have a test for this Python script, so this test is not provided in the committed files.
```c++
#include …
```
=> [Arc] Refactor C++ header generator script to use Jinja templates

lib/Conversion/CombToAIG/CombToAIG.cpp, test/Conversion/CombToAIG/comb-to-aig.mlir
Static data-movement operations (extarct, concat and replicate) are legal in AIG level so just allow them.
=> [CombToAIG] Populate legal ops

docs/Dialects/FIRRTL/FIRRTLAnnotations.md, lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp, test/Dialect/FIRRTL/extract-instances.mlir
Weaken the check used by the `ExtractInstances` pass to determine what is a clock gate.  Change this from requiring that the defname of an external module is exactly "EICG_wrapper" to instead only needing to end with "EICG_wrapper".  This is done so that this will work with Chisel-time prefixing and that we would actually _like_ to prefix these clock gates.
Commentary: this string matching is terrible.  I realize that.  However, this is a legacy API that is intending to be replaced.
=> [FIRRTL] Clock gate extraction work w/ prefixing

include/circt/Dialect/SV/SVStatements.td, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Dialect/SV/SVOps.cpp, test/Conversion/ExportVerilog/verilog-basic.mlir
Add a utility function to `sv.macro.decl` that can be used to get its
Verilog textual macro identifier name.  This is added for convenience to
avoid having to repeat the patter of getting its optional Verilog name or
symbol name.
This is done to fix an issue related to lowering of FIRRTL inline layers
where the `LowerLayers` pass generates new `sv.macro.decl` symbols that
will replace existing `firrtl.layer` symbols.  However, it relies on a
namespace to generate these and will result in suffixed symbol names.  (It
could obviously do more work to conserve symbols or generate in-pass
invalid IR with duplicate symbols.)  Nonetheless, the real bug here is
that the `ExportVerilog` conversion is not doing the right thing with the
Verilog name attribute.
=> [ExportVerilog] Fix ifdef of macro w/ Verilog name

lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, test/Dialect/FIRRTL/lower-types.mlir
This PR changes to clone discardable attributes when operation is cloned. 
Fix https://github.com/llvm/circt/issues/7934. AttributeAnnotation adds `sv.attributes` in LowerAnnotation as a discardable attribute which previously LowerTypes dropped.
=> [LowerTypes] Copy discardable attributes when cloning operations

include/circt-c/Dialect/FIRRTL.h, lib/CAPI/Dialect/FIRRTL.cpp
Add documentation for all FIRRTL C-API public items.
=> [FIRRTL][CAPI] Add documentation

lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
Hi! This PR add support for such code:
```verilog
module Mod(input [1:0] a, output logic b);
always @(a)
b <= a[0];
endmodule
```
I'm not sure about correctness of this code in common case due to #7925 but now (as I understand) only [width-1:0] arrays supported in Moore dialect.
Thank you in advance!
=> [MooreToCore] Add multibit DetectEventOp support

include/circt/Conversion/Passes.td, include/circt/Dialect/Calyx/CalyxLoweringUtils.h, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp, test/Conversion/SCFToCalyx/write_memory.mlir
This patch lowers `memref::GetGlobalOp` and write data that it carries to corresponding json files, so that they can be used later by Calyx. Json data will be written to the same directory as the source file. Since there might be situations where users don't wish to do so, writing to json will only be carried out if users specify `--lower-scf-to-calyx="write-json=true"`.
=> Lower MemRef GetGlobal and write data to json files

include/circt/Dialect/FIRRTL/FIRParser.h, include/circt/Dialect/FIRRTL/FIRRTLStructure.td, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/firtool/instchoice.fir, tools/firtool/firtool.cpp
Add a select option to firtool for instance choice specialization.
The specified select is added as an attribute on the `CircuitOp`.
The attribute is an array of strings, each string specifies the selected specialization for each option.
The `SpecializeOptions` pass will perform the error checking for the select options specified as the argument.
This PR is split from https://github.com/llvm/circt/pull/7933
=> [FirParser] Add instance choice selection as circt attribute

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
hopefully it fixes the Windows test, going to merge it directly
cc @cgyurgyik
=> [SCFToCalyx] `memref::getGlobalOp` write to json using explicit toString for path to fix Windows failed test

include/circt-c/Firtool/Firtool.h, include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, include/circt/Firtool/Firtool.h, lib/CAPI/Firtool/Firtool.cpp, lib/Dialect/FIRRTL/Transforms/SpecializeOption.cpp, lib/Firtool/Firtool.cpp, test/firtool/instchoice.fir
Add an override that, instead of emitting an error, selects the default target to specialize an instance choice when the option is unspecified.
By default a partially specified instance choice is not allowed. But we can override the error and select the default target, by using `--specialize-to-default-if-no-override` with `firtool`.
This enables a user to specialize the instance choice for a particular build flow, and fall-back to the default for all others.
Relevant discussion: https://github.com/llvm/circt/pull/7933
=> [InstanceChoice] Add a default override for unspecified options

lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
=> [MooreToCore] Support pows and powu op

include/circt/Dialect/SMT/SMTOps.td, test/Dialect/SMT/core-errors.mlir
Just adds a HasParent<SolverOp> requirement to SetLogicOp
=> [SMT] Require SolverOp parent for SetLogicOp

integration_test/Dialect/SMT/basic.mlir, lib/Conversion/SMTToZ3LLVM/LowerSMTToZ3LLVM.cpp, test/Conversion/SMTToZ3LLVM/smt-to-z3-llvm-errors.mlir, test/Conversion/SMTToZ3LLVM/smt-to-z3-llvm.mlir
Slightly more complicated than this would ideally be because Z3 handles different logics with a separate solver constructor rather than as a function to be called on the solver.
=> [SMT] Add Z3 lowering for set_logic op

docs/Dialects/RTG.md, include/circt/Dialect/RTG/CMakeLists.txt, include/circt/Dialect/RTG/Transforms/CMakeLists.txt, include/circt/Dialect/RTG/Transforms/RTGPasses.h, include/circt/Dialect/RTG/Transforms/RTGPasses.td, include/circt/Dialect/RTGTest/IR/RTGTestOps.td, include/circt/InitAllPasses.h, lib/Dialect/RTG/CMakeLists.txt, lib/Dialect/RTG/Transforms/CMakeLists.txt, lib/Dialect/RTG/Transforms/ElaborationPass.cpp, lib/Dialect/RTGTest/IR/RTGTestOps.cpp, test/Dialect/RTG/Transform/elaboration.mlir, test/Dialect/RTGTest/IR/basic.mlir
Add a pass that lowers the random parts of RTG IR.
=> [RTG] Add ElaborationPass

include/circt/Dialect/DC/DCOps.td, lib/Dialect/DC/DCOps.cpp, test/Dialect/DC/canonicalization.mlir
Various canonicalization patterns were implemented as fold methods. However, these had been turned off a while ago, due to an MLIR bug.
This PR moves the fold methods to actual canonicalization patterns, adds a new one (join on branch), and re-enables previously disabled tests.
=> [DC] Add + re-enable canonicalization patterns

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
Revert an LLVM de-bump accidentally introduced in an unrelated change [[1]].  This effectively re-applies the original bump [[2]].
[1]: 58665c5921c78d7407fdf3a834b5af28fdd0fd3f
[2]: 02823af1a68ad623de52673749f364e74644ec8f
=> [llvm] Revert LLVM de-bump

lib/Dialect/OM/Transforms/FreezePaths.cpp, test/Dialect/OM/freeze-paths.mlir
We previously handled the ListCreateOp specifically, because lists of paths need to become lists of frozen paths. But there are other list creation ops that need to be considered and handled similarly, like the recently added ListConcatOp.
To handle this, the process method for ListCreateOp was updated to work on any generic Operation * that returns a ListType. The typeswitch that dispatches to the process methods was updated to use this generic processor for both ListCreateOp and ListConcatOp. I thought about writing a generic check instead of listing out the supported Operation classes, but that seems like a fragile tradeoff that might not be worth the cost relative to keeping this list up to date.
=> [OM] Generalize handling for list creation ops in FreezePaths.

include/circt-c/Dialect/FIRRTL.h, lib/CAPI/Dialect/FIRRTL.cpp, test/CAPI/firrtl.c
This PR adds functions:
- for const `firrtlTypeIsConst`, `firrtlTypeGetConstType`
- for bit width `firrtlTypeGetBitWidth`
- for discriminating `firrtlTypeIsA{UInt,SInt,Clock,Reset,...}`
- for vector `firrtlTypeGetVectorElement`, `firrtlTypeGetVectorNumElements`
- for bundle `firrtlTypeGetBundleNumFields`, `firrtlTypeGetBundleFieldByIndex`
CC @sequencer, could you check if there are any missing?
=> [FIRRTL][CAPI] Add more functions for discriminating and querying type

tools/circt-bmc/circt-bmc.cpp
Have found myself enabling debug on LowerSMTToZ3LLVM quite a lot for debugging, figured it's probably useful enough to have as a flag in circt-bmc (e.g. to figure out why a design's assertions are failing, though obviously as in #7711
ideally there'll be a nicer way to do this eventually).
=> [circt-bmc] Add option to print solver output & assertions

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
This patch fixes json naming when there are multiple components, since the `append` method changes `writeJson`'s value in-place.
=> [SCFToCalyx] Fix json naming when there are multiple components

include/circt/Conversion/CombToAIG.h, include/circt/Conversion/Passes.td, integration_test/circt-synth/comb-lowering-lec.mlir, lib/Conversion/CombToAIG/CombToAIG.cpp, test/Conversion/CombToAIG/comb-to-aig-arith.mlir, test/Conversion/CombToAIG/comb-to-aig.mlir
This implements a pattern to lower AddOp to a naive ripple-carry adder.
Pattern for sub is also added since we can easily compute subtraction from addition.
This PR also adds a test-only option to `additional-legal-ops` to test
complicated lowering pattern.
=>     [CombToAIG] Add a lowering for Add/Sub

lib/Dialect/LLHD/Transforms/DesequentializationPass.cpp, test/Dialect/LLHD/Transforms/desequentialization.mlir
=> [LLHD] Fix misprint in llhd-desequentialize pass

lib/Dialect/FIRRTL/Transforms/AdvancedLayerSink.cpp, test/Dialect/FIRRTL/advanced-layer-sink.mlir
If a module-like has port annotations, mark it as an effectful module, which will prevent the pass from moving or deleting its instances later on. We can't sink instance when we don't understand what port annotations mean.
=> [FIRRTL] AdvancedLayerSink: don't sink instances of mods with port annos

lib/Firtool/Firtool.cpp
Move the `SpecializeOptionsChoice` pass earlier in the pipeline. This is required since most of the passes cannot handle `InstanceChoiceOp`  including the `InstanceGraph` analysis and may result in invalid IR. 
This ensures that all the `InstanceChoiceOp` are replaced by `InstanceOp` after the specialize pass is run, since partially specified options are still not supported.
=> [InstanceChoice] Move specialize options pass earlier in the firtool pipeline

include/circt-c/Firtool/Firtool.h, include/circt/Firtool/Firtool.h, lib/CAPI/Firtool/Firtool.cpp, lib/Firtool/Firtool.cpp
The layer sink pass is showing some performance problems, and we want the ability to turn it off to work around the issue, until we can properly fix it.
=> [firtool] Add option to disable layer sink

include/circt/Dialect/Calyx/CalyxLoweringUtils.h, lib/Conversion/LoopScheduleToCalyx/LoopScheduleToCalyx.cpp, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp, test/Conversion/SCFToCalyx/convert_simple.mlir
In `buildLibraryOp`, we cast floating point types to integer types with the same width, as discussed here: https://github.com/llvm/circt/pull/7762
The testing case is just the result of running the `-arith-expand` pass on the following input:
```mlir
module {
func.func @main(%b: f64, %c: f64) -> f64 {
%a = arith.maximumf %b, %c : f64
return %a : f64
}
}
```
=> [SCFToCalyx] buildLibraryOp cast floating point to integer types

lib/Firtool/Firtool.cpp
When this option was added to the FirtoolOptions struct it was not given an initial value, which could later be read.  This change also sets the initial value of the CL option flag.
=> [firtool] initialize the disableLayerSink flag

lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
This add a type conversion for unpacked arrays, mapping them to `hw.array`. The approach is analogous to how unpacked structs are currently handled.
As far as I understand, `hw.uarray` would be more appropriate in the future, especially once it's moved to SV. However, no operation accepts this type yet. I'm not sure what the consensus is as to whether the operation set should be extended to accommodate unpacked arrays (by adding new operations or "overloading" existing ones that deal with `hw.array`s). Using packed arrays for the time being sidesteps this question.
=> [MooreToCore] Lower the unpacked array type to `hw.array`

include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h, lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp, lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp, lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, test/Analysis/firrtl-test-instance-info.mlir, test/firtool/mark-dut.fir
In some cases, the "DUT" might be an extmodule from a separate compilation unit, and we still want all the old legacy "is DUT" logic to work. To support this, we need applyDUTAnno to allow the annotation to be applied to an extmodule, and we need extractDUT and its users to work with FModuleLikes instead of FModuleOp. The only other thing that appears to be using this "is DUT" logic is the newer InstanceInfo helper, which already works with igraph::ModuleOpInterfaces and seems to work fine with extmodules as the "DUT".
=> [FIRRTL] Support MarkDUTAnnotation on extmodules.

lib/Bindings/Python/pyproject.toml
We recently started supporting nanobind as a dependency in upstream MLIR. This is installed in our CI images, but not the Python wheel CI environment. This adds that dependency to the package used for the Python wheel build.
=> [CD] Install nanobind when building wheels.

include/circt/Dialect/Seq/SeqPasses.td, integration_test/Dialect/Seq/fifo/fifo.mlir, integration_test/Dialect/Seq/fifo/fifo.py, lib/Dialect/Seq/Transforms/CMakeLists.txt, lib/Dialect/Seq/Transforms/LowerSeqFIFO.cpp, test/Dialect/Seq/lower-fifo.mlir
Fixes two bugs:
- Incorrect depth constant led to FIFO never reaching capacity.
- Increment pointers only worked for depth which were powers of two.
Updates integration test to test for these two conditions.
=> [Seq] Fix FIFO lowering to correct depth and pointer increments

lib/Tools/circt-bmc/LowerToBMC.cpp, test/Tools/circt-bmc/lower-to-bmc-errors.mlir, test/Tools/circt-bmc/lower-to-bmc.mlir
Allows circt-bmc to support modules that contain non-dominance but can be topologically sorted. Doesn't cover every edge case (i.e. when modules get involved and there may be cycles), but I've run into needing this a few times so it's probably useful to have upstream.
=> [LowerToBMC] Topologically sort module body before inlining to BMC op

frontends/PyCDE/pyproject.toml, frontends/PyCDE/setup.py, frontends/PyCDE/src/CMakeLists.txt
Fix the PyCDE build flow. Added nanobind and fixed dll install on Windows.
=> [PyCDE] Update build flow

frontends/PyCDE/integration_test/esi_advanced.py, frontends/PyCDE/integration_test/test_software/esi_advanced.py, frontends/PyCDE/src/pycde/bsp/__init__.py, frontends/PyCDE/src/pycde/signals.py, frontends/PyCDE/src/pycde/types.py, frontends/PyCDE/test/test_esi_advanced.py
- <ChannelSignal>.fork creates two new channels, waits until they are both available, then accepts an input. Also buffer the output channels to avoid combinational loops.
- Channel.join waits on two channels then creates a message on the one output channel containing a struct with field 'a' equal to input channel A's content and likewise for channel B.
- Channel.merge funnels two channels together into a single output stream.
This is functionality which really should be handled by the DC dialect but it's not ready for primetime.
=> [PyCDE] Add fork, join, and merge channel functions

integration_test/circt-synth/comb-lowering-lec.mlir, lib/Conversion/CombToAIG/CombToAIG.cpp, test/Conversion/CombToAIG/comb-to-aig-arith.mlir
This commit adds a pattern to lower mul. Mul is lowered into chains of comb.add + comb.mux. There must be more efficient implementation but for now this naive pattern should work fine. LEC is verified. 
```
{a_{n}, a_{n-1}, ..., a_0} * b
= sum_{i=0}^{n} a_i * 2^i * b
= sum_{i=0}^{n} (a_i ? b : 0) << i
```
=> [CombToAIG] Add a pattern for mul

lib/Conversion/HWToBTOR2/HWToBTOR2.cpp, test/Conversion/HWToBTOR2/comb.mlir
Found a couple of missing special cases where the CIRCT and BTOR2 names for predicates differ (we abbreviate "than or equal" to just "e", they do it to "te") so invalid BTOR2 is produced - breaking examples in the added test checks.
=> [HWToBTOR2] Fix incorrect le/ge predicate name emission

lib/Conversion/VerifToSMT/VerifToSMT.cpp, test/Conversion/VerifToSMT/bmc-clock-not-first.mlir
Fixes a bug introduced in #7878 where the wrong index is used to access the results of the loop region, often leading to a crash when the clock isn't the first input to the original module. Also includes a breaking example as a test - I've added it in a new file to avoid the different BMC circuit/loop/init functions from this and the other BMC test interleaving, can merge it into the existing test file if preferred and just interleave the Filecheck commands.
=> [VerifToSMT] Fix incorrect loop region result indexing

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/firtool/lower-layers.fir, test/firtool/print.fir
updates the FIRRTLToHW conversion to use the `PRINTF_FD` macro for specifying the file descriptor, allowing the fd to be obtained externally. This change enhances flexibility by enabling the file descriptor to be defined outside the conversion logic.
now we can define a log package like this:
```
package log_pkg;
bit log_cond;
int log_fd;
function automatic void log_open(string log_path);
log_fd = $fopen(log_path, "w");
if (log_fd == 0) $fatal(1, "failed to open file for write");
log_cond = 1'b1;
endfunction
function automatic void log_close();
if (log_cond) begin
$fclose(log_fd);
log_cond = 1'b0;
log_fd = 0;
end
endfunction
endpackage
initial begin
log_pkg::log_open("xxx");
end
final begin
log_pkg::log_close();
end
```
and add compile option to import log_fd
``` …
```
=> [FIRRTL] Use PRINTF_FD macro instead of 0x80000002 as printf fd

CMakeLists.txt
This PR make CIRCT to relay on the very MLIR cmake python detection macros.
It now [properly picks](https://github.com/llvm/llvm-project/blob/ea14bdb0356cdda727ac032470f6a0a2102d1281/mlir/cmake/modules/MLIRDetectPythonEnv.cmake#L4-L48) up ```python``` components including ```pybind11``` and the recently introduced ```nanobind```.
Here is how this [is used upstream](https://github.com/llvm/llvm-project/blob/3b19e787fc5da27dfcc9ac6552b06a763f12ea03/mlir/examples/standalone/CMakeLists.txt#L35) .
---
Here is the cmake process output:
```
{...}
-- CIRCT Python bindings are enabled.
-- Found Python3: /usr/bin/python3.13 (found version "3.13.1") found components: Interpreter Development.Module
-- Found Python: /usr/bin/python3.13 (found version "3.13.1") found components: Interpreter …
```
=> Use MLIR python detection environment

CMakeLists.txt
This reverts commit ab5dc6c797583e2d292aaa8366531177de8d1bd4.
=> Revert "Use MLIR python detection environment (#8037)"

frontends/PyCDE/src/pycde/signals.py, frontends/PyCDE/src/pycde/types.py, include/circt-c/Dialect/ESI.h, include/circt/Dialect/ESI/ESIOps.h, lib/Bindings/Python/ESIModule.cpp, lib/CAPI/Dialect/ESI.cpp
- Adds a `castable` method to Type which passes through to the `checkInnerTypeMatch` C++ function.
- Use that method to type check the results of BundleSignal.unpack.
=> [PyCDE] Improving support for Any type

include/circt/Transforms/Passes.h, include/circt/Transforms/Passes.td, lib/Transforms/MemoryBanking.cpp, test/Transforms/memory_banking_multi_dim.mlir
This patch supports multi-dimensional memory banking in the memory banking pass.
=> [MemoryBanking] Support multi-dimension memory banking

lib/Transforms/MemoryBanking.cpp, test/Transforms/memory_banking.mlir
This patch adds a new `oldMemRefVals` field to keep track of the original `memref` values that should be erased, as opposed to the old approach that derives `oldMemRefVals` simply from `memoryToBanks` map: https://github.com/llvm/circt/blob/acc507542bdcd91ca45a8b6fa8bd65e6629f513d/lib/Transforms/MemoryBanking.cpp#L382
The issue with the original approach is that some keys in the `memoryToBanks` map might become dangling references because they are replaced: https://github.com/llvm/circt/blob/acc507542bdcd91ca45a8b6fa8bd65e6629f513d/lib/Transforms/MemoryBanking.cpp#L182
We add `loadOp.memref()` to `oldMemRefVals` only when the value is a `BlockArgument` because only the `BlockArgument` will remain in the `cleanUpOldMemRefs` function; and the values that are not `BlockArgument` will all …
=> [MemoryBanking] Add a new field to keep track values to be erased

integration_test/circt-test/basic-circt-bmc.mlir, integration_test/circt-test/basic-sby.mlir, tools/circt-test/circt-test.cpp
Instead of accepting a runner binary directly through the `-r` command line option, add a `RunnerSuite` to circt-test which tracks a list of configured runners. This currently gets populated with the default "sby" and "circt-bmc" runners with the corresponding configuration. The user can then pass the runner name to the `-r` option, e.g. `-r sby`, instead of a full path.
Further down the road we'll want to allow the user to dynamically configure additional runners through files on disk, and specify an order in which the runners should be used. For example, a user may want to use "sby" for as many tests as possible, and fall back to "circt-bmc" for the ones where "sby" was not available.
=> [circt-test] Keep a list of available test runners

.github/workflows/uploadWheels.yml
This removes MacOS, which has been failing, and no one seems to care about anyway. This also adds a newer Python 3.13 wheel for a more modern Python version. I have not yet removed the Python 3.8 wheel, but that is EOL, and we can consider removing that in a follow up.
=> [Python] Update wheels we build in CI/CD.

include/circt/Dialect/Calyx/CalyxLoweringUtils.h, lib/Conversion/LoopScheduleToCalyx/LoopScheduleToCalyx.cpp, test/Conversion/LoopScheduleToCalyx/convert_pipeline.mlir
Lowers reads from a register to a pipeline register in the next stage. See the [Calyx Zulip discussion](https://calyx.zulipchat.com/#narrow/channel/423600-development/topic/hlstool/near/489718133).
=> [LoopScheduleToCalyx] Lower pipeline register to register writes.

include/circt/Dialect/SMT/SMTBitVectorOps.td, include/circt/Dialect/SMT/SMTVisitors.h, integration_test/Dialect/SMT/basic.mlir, lib/Conversion/SMTToZ3LLVM/LowerSMTToZ3LLVM.cpp, lib/Dialect/SMT/CMakeLists.txt, lib/Dialect/SMT/SMTOps.cpp, lib/Target/ExportSMTLIB/ExportSMTLIB.cpp, test/Conversion/SMTToZ3LLVM/smt-to-z3-llvm.mlir, test/Dialect/SMT/bitvector-errors.mlir, test/Dialect/SMT/bitvectors.mlir, test/Target/ExportSMTLIB/bitvector-errors.mlir, test/Target/ExportSMTLIB/integer-errors.mlir
Adds an operation to convert between SMT bitvectors and SMT integers. As discussed further in #8041, support for these operations varies between solvers - technically this one is outlined in the SMTLIB spec but AFAIU only to describe the semantics of other operations, rather than as something solvers are expected to implement, so I've made ExportSMTLIB error out on this one too since it's not _really_ part of the spec for the language itself.
=> [SMT] Add bv2int op

lib/Transforms/MemoryBanking.cpp, test/Transforms/memory_banking_multi_dim.mlir
This patch supports memory banking for multi-dimensional `GetGlobalOp`s and restructure the data in their corresponding `GlobalOp`s by the banking scheme (such as the banking factor and the dimension).
=> [MemoryBanking] Support memory banking for`GetGlobalOp`

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_simple.mlir
This patch addresses the issue with `IRMapping` when unrolling the parallel loop during the SCFToCalyx pass. If there are region-based operations, such as `scf.for` inside `scf.parallel`, the block arguments weren't cloned correctly because if we keep reusing the old `IRMapping`, the `IRMapping` will already have the entries from previous iterations that overshadows new ones. To fix it, we need to re-initialize the `IRMapping` every iteration.
=> [SCFToCalyx] Re-initialize IRMapping at the start of each loop

include/circt-c/Dialect/SMT.h, integration_test/Bindings/Python/dialects/smt.py, lib/Bindings/Python/CIRCTModule.cpp, lib/Bindings/Python/CMakeLists.txt, lib/Bindings/Python/dialects/SMTOps.td, lib/Bindings/Python/dialects/smt.py, lib/CAPI/Dialect/CMakeLists.txt, lib/CAPI/Dialect/SMT.cpp
This PR enables the python bindings for the `smt` dialect.
I'm not sure what y'alls approach is to testing these bindings since [PyCDE only tests the bindings it uses](https://github.com/llvm/circt/tree/main/frontends/PyCDE/test) and I don't see any other python bindings tests around...
=> [SMT][python] enable python bindings

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp, test/Dialect/FIRRTL/lowerXMR.mlir
Change the `LowerXMR` pass to reuse previously created `XMRRefOp`s within a module.  This is done for later, easier processing of these operations in `LowerToHW`.  While these operations could be made to be CSE'd (by giving them the `Pure` trait), it is advantageous to instead not create duplicate operations as this avoids needing to run schedule a mostly useless CSE.
This is primarily done to allow for Verilator-compatible lowering of `force_initial` and `release_initial` in `LowerToHW` where it would be useful to know when a force and release are referring to the same reference.  (Yes, full alias analysis is necessary to do this correctly and relying on the CSE of `LowerXMR` is going to be buggy.)
=> [FIRRTL] Reuse XMRRefOps in LowerXMR

lib/Conversion/VerifToSV/VerifToSV.cpp
`clang-tidy` reports this ctor call as ambiguous and in fact it fails on Windows with `clang-cl` with 
```
D:\a\circt\circt\lib\Conversion\VerifToSV\VerifToSV.cpp(48,22): error: call to constructor of 'APInt' is ambiguous
48 |         op.getLoc(), APInt(32, 0x80000001, false));
|                      ^     ~~~~~~~~~~~~~~~~~~~~~
D:\a\circt\circt\llvm\llvm\include\llvm/ADT/APInt.h(157,3): note: candidate constructor
157 |   APInt(unsigned numBits, unsigned numWords, const uint64_t bigVal[]);
|   ^
D:\a\circt\circt\llvm\llvm\include\llvm/ADT/APInt.h(111,3): note: candidate constructor
111 |   APInt(unsigned numBits, uint64_t val, bool isSigned = false,
|   ^
1 error generated.
```
=> [Verif] disambiguate ctor

cmake/modules/AddCIRCT.cmake, lib/Bindings/Python/CMakeLists.txt
I would like to build CIRCT Python bindings *downstream of CIRCT*. For this to work you need to have the so-called "aggregate objects" [installed](https://github.com/llvm/llvm-project/blob/3318a7248ae464af0abd0bea5515fa58c962b890/mlir/cmake/modules/AddMLIR.cmake#L424-L425).  
`add_circt_public_c_api_library` does `DISABLE_INSTALL` in order to prevent `add_mlir_public_c_api_library` from generating install targets that collide with those generated by `add_circt_library_install` but in doing so skips the install of the object file `obj.${name}`. So we just put that back.
EDIT: headers need to be installed too...
=> [CMake] enable install C API objects

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp
This patch inserts `scf::ReduceOp` at the end of the newly created `scf::parallelOp` for canonicalization.
=> [SCFToCalyx] Insert scf::reduce op at the end of the newly create scf::par op

frontends/PyCDE/integration_test/esitester.py, frontends/PyCDE/src/pycde/bsp/common.py, frontends/PyCDE/src/pycde/bsp/cosim.py, frontends/PyCDE/src/pycde/esi.py, frontends/PyCDE/src/pycde/signals.py, frontends/PyCDE/src/pycde/types.py, frontends/PyCDE/test/test_esi.py, lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp, lib/Dialect/ESI/runtime/cpp/tools/esitester.cpp
Adds cosim support to both the cosim BSP in PyCDE and the corresponding support in the runtime. As with hostmem reads, write only supports one client and no gearboxing.
=> [ESI] Add hostmem write support to cosim

lib/Dialect/RTG/Transforms/ElaborationPass.cpp, test/Dialect/RTG/Transform/elaboration.mlir
* Simplify materializer to work on only one basic block
* Remove unused addWorklist argument and use a class field instead
* Because the way invocations are elaborated has changed, we don't need the worklist anymore within sequences or tests (we can just iterate over the operations since it's not a graph region), this is a big performance benefit in large tests/sequences.
* Do a BFS over the sequence invocation hierarchy such that callees are only elaborated when all parents are elaborated (because only the `sequence_closure` operation should fix the randomization within a sequence, thus they create a clone before elaborating the referenced sequence)
* Inline all sequences and remove them.
=> [RTG][Elaboration] Support sequences

include/circt/Dialect/RTG/Transforms/RTGPasses.td, lib/Dialect/RTG/Transforms/CMakeLists.txt, lib/Dialect/RTG/Transforms/ElaborationPass.cpp, test/Dialect/RTG/Transform/elaboration.mlir
* Use the index dialect instead of arith because it is a smaller dependency and simpler, but still has everything we need.
* Add support for `index.add` and `index.cmp`
* Add specialized elaborator values for indices and booleans because creating attributes for intermediates is quite bad performance-wise (ideally we'd have some evaluation interface at some point that we can also use for folding, or better folders that we can call directly)
=> [RTG][Elaboration] Add support for 'index.add' and 'index.cmp'

include/circt/Dialect/FIRRTL/FIRRTLIntrinsics.h, lib/Dialect/FIRRTL/FIRRTLIntrinsics.cpp
Tweak IntrinsicConverter to allow one-shot check and convert which is useful especially when both check and convert require doing the same non-trivial processing work.
=> [FIRRTL] Intrinsics: Add checkAndConvert, anchor vtable.

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_controlflow.mlir
This patch lowers `scf.ifOp` when it has an empty yield/does not return any value.
=> [SCFToCalyx] Lower `scf.if` op when it yields nothing

lib/Transforms/IndexSwitchToIf.cpp, test/Transforms/switch-to-if.mlir
This patch adds support to transform index switch to nested if-else when the yielded result is empty.
=> [SwitchToIf] Empty yielded result

lib/Dialect/Verif/Transforms/LowerFormalToHW.cpp
LowerFormalToHW used `applyPatternsGreedily` on ModuleOp but that is overkill for what LowerFormalToHW does. Since `applyPatternsGreedily` is called on ModuleOp,  canonicalizations are executed in a single thread and LowerFormalToHW consumed non-trivial amount of time in large designs.  
This commit simply replaces RewriterPattern with a helper function and call it manually.
Should fix https://github.com/llvm/circt/issues/8035.
=> [LowerFormalToHW] Avoid `applyPatternsGreedily`, NFCI

include/circt/Dialect/Verif/VerifOps.td, integration_test/circt-test/basic.mlir, test/circt-test/errors.mlir, tools/circt-test/circt-test.cpp
Interpret the `require_runners` and `exclude_runners` attributes on formal tests as a filter for the potential runners that can execute a test. If the set of required runners is not empty, a runner from this set is picked. Tests for which no runner is available report as "unsupported", for example if none of the available runners match the filter.
=> [circt-test] Allow tests to filter according to test runners

include/circt/Dialect/FIRRTL/FIRRTLIntrinsics.td, include/circt/Dialect/FIRRTL/FIRRTLTypes.td, include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, test/Dialect/FIRRTL/round-trip.mlir
Add a preliminary ViewIntrinsic that is an intended replacement for the Grand Central View AugmentedBundleType Annotation.
=> [FIRRTL] Add View Intrinsic

include/circt-c/Dialect/RTGTest.h, include/circt/Dialect/RTG/IR/CMakeLists.txt, include/circt/Dialect/RTG/IR/RTGAttrInterfaces.h, include/circt/Dialect/RTG/IR/RTGInterfaces.td, include/circt/Dialect/RTG/IR/RTGOps.h, include/circt/Dialect/RTGTest/IR/CMakeLists.txt, include/circt/Dialect/RTGTest/IR/RTGTest.td, include/circt/Dialect/RTGTest/IR/RTGTestAttributes.h, include/circt/Dialect/RTGTest/IR/RTGTestAttributes.td, include/circt/Dialect/RTGTest/IR/RTGTestDialect.td, include/circt/Dialect/RTGTest/IR/RTGTestOps.h, include/circt/Dialect/RTGTest/IR/RTGTestOps.td, integration_test/Bindings/Python/dialects/rtg.py, lib/Bindings/Python/RTGTestModule.cpp, lib/CAPI/Dialect/RTGTest.cpp, lib/Dialect/RTG/IR/CMakeLists.txt, lib/Dialect/RTG/IR/RTGAttrInterfaces.cpp, lib/Dialect/RTGTest/IR/CMakeLists.txt, lib/Dialect/RTGTest/IR/RTGTestAttributes.cpp, lib/Dialect/RTGTest/IR/RTGTestDialect.cpp, lib/Dialect/RTGTest/IR/RTGTestOps.cpp, test/CAPI/rtgtest.c, test/Dialect/RTGTest/IR/basic.mlir
Provides a way to specify context resources with an attribute that works well in combination with the ContextResourceTypeInterface. Currently, the `cpu_decl` operation has an index attr but returns a ContextResourceTypeInterface type, which makes folding difficult (and thus declaring it ConstantLike).
Further down the line, we could consider removing the `ContextResourceOpInterface` in favour of a single op in the RTG dialect.
=> [RTG] Add context resource attribute interface

.github/workflows/buildAndTest.yml, .github/workflows/unifiedBuildTestAndInstall.yml, .github/workflows/uploadWheels.yml
The v3 of these actions is deprecated:
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/.
While GitHub has indicated this will stop working on January 30, we seem to have already hit a failure related to this: https://github.com/llvm/circt/actions/runs/12815228763/job/35733456176?pr=8089#step:1:25.
This updates to use the v4 version of these actions where we were on v3, and in the Python wheel building specifically, it makes one small tweak following the migration guide:
https://github.blog/news-insights/product-news/get-started-with-v4-of-github-actions-artifacts/#compatibility.
=> [CI/CD] Update upload-artifacts and download-artifcats.

.github/workflows/buildAndTestWindows.yml
As discussed in #7970, try enabling it to detect Windows-only bugs before merging.
=> [CI] Enable Windows builds for PRs

lib/Dialect/RTG/Transforms/CMakeLists.txt, lib/Dialect/RTG/Transforms/ElaborationPass.cpp, test/Dialect/RTG/Transform/elaboration.mlir
Did a quick profile of the following input:
```
func.func @dummy(%arg0: index) -> () {return}
rtg.test @test : !rtg.dict<> {
%0 = index.constant 0
%1 = index.constant 1
%2 = index.constant 10000000
%3 = index.constant 2
%4 = scf.for %i = %0 to %2 step %1 iter_args(%a = %0) -> (index) {
%5 = index.add %a, %3
scf.yield %5 : index
}
func.call @dummy(%4) : (index) -> ()
}
```
Currently takes ~5.4 sec on my machine, with most of the time spent internalizing the intermediate integers.
Will follow-up with a PR that refactors the ElaboratorValue to only internalize complex values such as sets and bags, but not primitive integers.
=> [RTG][Elaboration] Add support for 'scf.if' and 'scf.for'

include/circt/Dialect/Arc/ArcOps.td, include/circt/Dialect/Handshake/HandshakeOps.td, include/circt/Dialect/Kanagawa/KanagawaOps.td, include/circt/Dialect/SV/SVStatements.td, include/circt/Dialect/Sim/SimOps.td, include/circt/Dialect/SystemC/SystemCStatements.td, lib/Conversion/ConvertToArcs/ConvertToArcs.cpp, lib/Conversion/ExportVerilog/ExportVerilogInternals.h, lib/Dialect/Arc/Transforms/ArcCanonicalizer.cpp, lib/Dialect/Arc/Transforms/InlineArcs.cpp, lib/Dialect/Arc/Transforms/LowerLUT.cpp, lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp, lib/Dialect/HW/Transforms/FlattenModules.cpp, lib/Support/JSON.cpp, unittests/Support/JSONTest.cpp
This is a relatively straightforward LLVM bump, but there were a few
things updated here.
https://github.com/llvm/llvm-project/commit/abba01a
This updated PointerUnion to deprecate get and is in favor of
llvm::cast and llvm::isa, so this PR updates the relevant callsites.
https://github.com/llvm/llvm-project/commit/f023da1
This updated FloatType to remove the helpers like getF64. FloatType
was previously turned into a TypeInterface, and the helpers are now
static get methods on the concrete FloatType implementations, so this
PR updates FloatType::getF64 to Float64Type::get.
https://github.com/llvm/llvm-project/commit/b39c5cb6
This updated InlinerInterface to add a new
allowSingleBlockOptimization method. We need to define that on our
PrefixInliner, or else we will hit the new assertion.
=> Bump LLVM to ebc7efbab5c58b46f7215d63be6d0208cb588192.

include/circt/Dialect/Comb/CombOps.h, include/circt/Dialect/HW/HWPasses.h, include/circt/Dialect/HW/Passes.td, integration_test/circt-synth/comb-lowering-lec.mlir, lib/Conversion/CombToAIG/CombToAIG.cpp, lib/Dialect/Comb/CombOps.cpp, lib/Dialect/HW/Transforms/CMakeLists.txt, lib/Dialect/HW/Transforms/HWAggregateToComb.cpp, test/Conversion/CombToAIG/comb-to-aig-arith.mlir, test/Dialect/HW/hw-aggregate-to-comb.mlir, tools/circt-synth/CMakeLists.txt, tools/circt-synth/circt-synth.cpp
This PR adds a new pass `HWAggregateToComb` that lowers array operations to comb operations. The pass converts:
- `hw.array_get` to a mux tree using comb operations
- `hw.array_create` and `hw.array_concat` to `comb.concat`
- `hw.aggregate_constant` to `comb.concat` of individual constants
The PR also moves two utility functions from CombToAIG to the Comb dialect:
- `extractBits`: Extracts individual bits from a value
- `constructMuxTree`: Builds a multiplexer tree from selectors and leaf nodes
The pass is required to run before CombToAIG to ensure array operations are
properly lowered to AIG. Strictly speaking other than array_get operations can be preserved
but array values prevent optimizations at AIG level.  So for the simplicity, I think it's reasonable
to lower array operations …
=> [HW][circt-synth] Implement AggregateToComb pass and add to circt-synth pipeline

lib/Dialect/RTG/Transforms/ElaborationPass.cpp
The `hasTrait` check is quite expensive. Most operations in the IR are likely not constants, thus doing the TypeSwitch and Visitor dispatch first, should lead to better performance in most cases.
Reduces runtime of example in https://github.com/llvm/circt/pull/7986 but with 10x more iterations from ~6.8 sec to ~3.7 sec (1.84x speedup).
Increases runtime of an example containing a single `rtg.test` containing 10 mio `index.constant` (and nothing else) from 1.67 sec to 1.85 sec (10% slowdown).
=> [RTG][Elaboration] Move ConstantLike check after TypeSwitch for better performance

lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp, test/Dialect/FIRRTL/extract-instances-inject-dut-hier.mlir, test/Dialect/FIRRTL/extract-instances.mlir
Update the metadata generated by `ExtractInstances`. 
Currently the path in the metadata, doesn't contain the original instance name, which causes difficulty in distinguishing extracted instances within the same module.
This PR updates the metadata to append the original instance name to the path.
Note that this instance name is of the instance, that has been extracted, hence it cannot be represented by the Hierarchical path.
=>  [ExtractInstances] Append original instance name to path in metadata 

frontends/PyCDE/integration_test/esitester.py, frontends/PyCDE/src/pycde/bsp/common.py, frontends/PyCDE/src/pycde/bsp/cosim.py, frontends/PyCDE/src/pycde/constructs.py, frontends/PyCDE/src/pycde/esi.py, frontends/PyCDE/src/pycde/signals.py, frontends/PyCDE/test/test_esi.py, lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp, lib/Dialect/ESI/runtime/cpp/tools/esitester.cpp
Adds the ability to have hostmem read clients issue reads for types which are not 64-bit. Requires changes to the cosimulated hostmem to properly respond with multiple messages when necessary. Also requires a tag-sensitive gearbox to re-assemble data which requires more than one message from upstream.
=> [ESI] BSP: variable sized reads and gearboxing read responses

lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, test/Dialect/FIRRTL/lower-layers.mlir
This continues to not address lack of global updating, but fixes use of verbatims that are extracted along with their targets.
=> [FIRRTL] LowerLayers: Update innerrefs in extracted verbatim's

frontends/PyCDE/integration_test/esitester.py, frontends/PyCDE/src/pycde/bsp/common.py, frontends/PyCDE/src/pycde/esi.py, lib/Dialect/ESI/runtime/cpp/tools/esitester.cpp
Implements a mux / demux on the hostmem service read path. Allows up to 256 clients.
=> [ESI] BSP: implement hostmem read path arbiter

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_simple.mlir
This patch canonicalizes `scf::if` op (if there's any) at the end of the `BuildParGroup` pass to fully address: https://github.com/llvm/circt/issues/8086
=> [SCFToCalyx] Canonicalize `scf::if` at the end of `BuildParGroup`

lib/Dialect/OM/Transforms/LinkModules.cpp, test/Dialect/OM/link-modules.mlir, test/om-linker/Inputs/a.mlir, test/om-linker/Inputs/b.mlir, test/om-linker/link.mlir
This PR changes OM LinkModule pass to preserve non-OM operations. Orthogonally we shouldn't use builtin.module for the container of nested hw modules and instead use hw.design in the long term but it should be ok for now. 
h/t @dtzSiFive for original idea to keep non-OM operations in artifact.
=> [OM] Preserve non-OM operations in OM LinkModules

CMakeLists.txt, integration_test/Bindings/Python/dialects/esi.py, lib/Bindings/Python/CIRCTModule.cpp, lib/Bindings/Python/CIRCTModules.h, lib/Bindings/Python/CMakeLists.txt, lib/Bindings/Python/ESIModule.cpp, lib/Bindings/Python/HWModule.cpp, lib/Bindings/Python/MSFTModule.cpp, lib/Bindings/Python/NanobindUtils.h, lib/Bindings/Python/OMModule.cpp, lib/Bindings/Python/RTGModule.cpp, lib/Bindings/Python/RTGTestModule.cpp, lib/Bindings/Python/RTGToolModule.cpp, lib/Bindings/Python/SVModule.cpp, lib/Bindings/Python/SeqModule.cpp, lib/Bindings/Python/SupportModule.cpp
This follows the general nanobind porting guide and the upstream MLIR changes in the same vein. For the most part, this is a very direct migration accomplished with sed.
There were a couple minor differences.
Nanobind is more strict about implicit casting, which popped up in a couple places:
* In MSFTModule, getNearestFreeInColumn was expecting a CIRCTMSFTPrimitiveType (int), but was actually being passed PrimitiveType enums at the call sites. Nanobind refused to automatically cast enum to int, so it was done manually.
* In SVModule, SVAttributeAttr.get was expecting a bool for emitAsComment, even though it was declared as having a default of None. Nanobind refused to automatically cast None to bool, so it was done manually, with a default of false.
Nanobind also prints enums slightly …
=> [Python] Switch CIRCT Python extension and dialects to nanobind.

lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp, test/Dialect/FIRRTL/inliner.mlir
Fix an issue in the FIRRTL inliner where modules would be removed even if some other top-level operations still had references to their symbol name.
=> [FIRRTL][Inliner] Don't remove modules with symbol uses

include/circt/Dialect/Pipeline/PipelineOps.td, lib/Conversion/PipelineToHW/PipelineToHW.cpp, lib/Dialect/Kanagawa/Transforms/KanagawaPrepareScheduling.cpp, lib/Dialect/Pipeline/PipelineOps.cpp, lib/Dialect/Pipeline/Transforms/ScheduleLinearPipeline.cpp, test/Conversion/PipelineToHW/test_basic.mlir, test/Conversion/PipelineToHW/test_poweron.mlir, test/Dialect/Pipeline/round-trip.mlir
In some usecases, having a reset signal to a pipeline may do more harm than good in terms of synthetis/routing overhead. Instead, users can reset pipelines in other ways - e.g. by holder `go` low for `N stages` cycles. This, in turn, will set the pipeline stage enable registers to a deterministic state.
Allow for this by making the top-level `reset` signal optional.
=> [Pipeline] Make `reset` signal optional

lib/Firtool/Firtool.cpp
This allows GC to set the output directory information of the SV operations it creates when lowering firrtl.view (instead of other way around).
=> [FIRRTL] Move GC after AssignOutputDirs.

README.md
See https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/adding-a-workflow-status-badge#using-the-workflow-file-name
Old(broken): https://github.com/llvm/circt/workflows/Build%20and%20Test/badge.svg?event=push
New: https://github.com/llvm/circt/actions/workflows/buildAndTest.yml/badge.svg?event=push
=> [README] Fix badge link

lib/Dialect/FIRRTL/Transforms/GrandCentral.cpp, test/Dialect/FIRRTL/grand-central-view.mlir
Simply propagate the "output_file" information entirely to any generated sv.interface created during lowering.
cc #8112 .
No change of behavior for annotation-based views.
=> [FIRRTL] GrandCentral: set iface output_file based on parent.

lib/Dialect/ESI/runtime/cpp/include/esi/Services.h, lib/Dialect/ESI/runtime/cpp/lib/Services.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Xrt.cpp, lib/Dialect/ESI/runtime/cpp/tools/esitester.cpp
Adds support for allocating, flushing, and getting the device pointer on XRT platforms.
=> [ESI][Runtime] XRT support for host memory access

docs/Dialects/FIRRTL/FIRRTLIntrinsics.md, include/circt/Dialect/FIRRTL/AnnotationDetails.h, include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h, lib/Dialect/FIRRTL/FIRRTLIntrinsics.cpp, test/Dialect/FIRRTL/lower-intrinsics-errors.mlir, test/Dialect/FIRRTL/lower-intrinsics.mlir
Implement "circt_view" intrinsic, lower to `firrtl.view`.
Add documentation to `FIRRTLIntrinsics.md`.
JSON encoding for view information is kept from the annotation format for the "view" specifically but without auto-tapping (or "ref" information) or parent/companion module notions.
This JSON is a string parameter to the intrinsic, which is processed into Attributes and Augmented attributes using a copied and modified version of `parseAugmentedType`.
The goal is to move to an intrinsic with minimal disruption.  In the future (once it's load-bearing as a replacement) we can delete support for the old format and change this as we'd like.
=> [FIRRTL] Add circt_view intrinsic lowering to firrtl.view

include/circt/Support/InstanceGraph.h, lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, lib/Support/InstanceGraph.cpp, test/Dialect/FIRRTL/imconstprop.mlir
If a module is referenced from an unknown top-level operation, i.e. an operation that is not an `hw.hierpath`, mark the module's inputs as overdefined. IMCP cannot reason about how the module is used by such an unknown operation, and therefore should assume that the operation might instantiate the module and apply arbitrary values to its input.
As an example, the `firrtl.formal` operation may refer to a private module as to be executed as a formal test, applying symbolic values to the module's inputs. While IMCP could simply special-case the `firrtl.formal` operation, it feels cleaner to make the pass defensive in the presence of _any_ operation which it does not explicitly know how to deal with.
=> [FIRRTL][IMCP] Overdefine ports of modules with unknown symbol uses

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_simple.mlir, test/Conversion/SCFToCalyx/float_compare.mlir
This patch fixes the logic of assigning the `write_en` port of the `cmpf_reg`: it should be high when the input register is `done`.
=> [SCFToCalyx] Lower floating point comparison logic fix

include/circt/Transforms/Passes.h, include/circt/Transforms/Passes.td, lib/Transforms/MemoryBanking.cpp, test/Transforms/memory_banking.mlir, test/Transforms/memory_banking_invalid.mlir, test/Transforms/memory_banking_multi_dim.mlir
This patch adjusts the default dimension for banking. It used be the outer most dimension (=0), but I think it makes more sense to default to the innermost dimension. For example, if we have:
```mlir
memref.global @__constant_4x2_i32 [[1, 2], [3, 4], [5, 6], [7, 8]] : memref<4x2xi32>
```
if we bank with factor = 2 in a round-robin way, it makes more sense to be:
```mlir
memref.global @__constant_4x2_i32_bank0 [[1], [3], [5], [7]] : memref<4x1xi32>
memref.global @__constant_4x2_i32_bank1 [[2], [4], [6], [8]] : memref<4x1xi32>
```
since it'll preserve the same order as the banking result after flattening to a 1-d array.
Additionally, we further require it to be the innermost dimension that has _shape not equals to 1_. It's not uncommon to have memrefs like:
```mlir
memref.global …
```
=> [MemoryBanking] Adjust default dimension

lib/Transforms/MemoryBanking.cpp, test/Transforms/memory_banking_attrs.mlir
This patch supports operation-granularity banking configurations by attaching attributes to overwrite the command line argument.
=> [MemoryBanking] Operation-granularity banking configurations by attaching attributes

include/circt/Dialect/Emit/CMakeLists.txt, include/circt/Dialect/Emit/EmitPasses.h, include/circt/Dialect/Emit/EmitPasses.td, include/circt/Dialect/OM/OMPasses.td, include/circt/InitAllPasses.h, lib/Dialect/Arc/Transforms/StripSV.cpp, lib/Dialect/Emit/CMakeLists.txt, lib/Dialect/Emit/Transforms/CMakeLists.txt, lib/Dialect/Emit/Transforms/StripEmit.cpp, lib/Dialect/OM/Transforms/CMakeLists.txt, lib/Dialect/OM/Transforms/StripOM.cpp, test/CMakeLists.txt, test/Dialect/Emit/strip-emit.mlir, test/Dialect/OM/strip-om.mlir, test/Tools/circt-bmc/commandline.mlir, test/Tools/circt-lec/commandline.mlir, tools/arcilator/CMakeLists.txt, tools/arcilator/arcilator.cpp, tools/circt-bmc/CMakeLists.txt, tools/circt-bmc/circt-bmc.cpp, tools/circt-lec/CMakeLists.txt, tools/circt-lec/circt-lec.cpp
Several tools in CIRCT do not process the OM and Emit dialects at all, for example, arcilator, circt-bmc, and circt-lec. Since these tools do a full lowering to LLVM internally, they have to discard all OM and Emit ops at some point in the pipeline. Arcilator currently does this in its StripSV pass; circt-bmc and circt-lec simply error out.
This commit adds a `StripOM` pass to the OM dialect and a `StripEmit` pass to the Emit dialect which remove any OM and Emit ops from the IR, respectively. These passes are added to the arcilator, circt-bmc, and circt-lec pipelines in order to discard OM and Emit from the input.
The commit also includes a few boilerplate changes and alphabetical ordering of dialects and dependencies.
@uenoku Maybe this is useful for `circt-synth` as well?
=> Add passes to strip OM and Emit dialect ops

frontends/PyCDE/integration_test/esitester.py, frontends/PyCDE/src/pycde/bsp/common.py, frontends/PyCDE/src/pycde/signals.py, lib/Dialect/ESI/runtime/cosim_dpi_server/esi-cosim.py, lib/Dialect/ESI/runtime/cpp/tools/esitester.cpp
Take client data and gearbox it up or down to the underlying host connection width. In the case where we must gearbox down, creates multiple hostmem write transactions.
=> [ESI][BSP] Gearboxing the hostmem write path

frontends/PyCDE/integration_test/esitester.py, frontends/PyCDE/src/pycde/bsp/common.py, frontends/PyCDE/src/pycde/esi.py, lib/Dialect/ESI/runtime/cpp/tools/esitester.cpp
Take multiple hostmem clients and multiplex them post-gearbox. Won't work long-term since this approach precludes bursting multiple transactions, which is necessary to get good PCIe perf.
=> [ESI][BSP] Multiplexing hostmem write clients

frontends/PyCDE/src/pycde/bsp/common.py, lib/Dialect/ESI/runtime/cpp/include/esi/Common.h, lib/Dialect/ESI/runtime/cpp/lib/Common.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp, lib/Dialect/ESI/runtime/cpp/tools/esitester.cpp
Writes can happen at less than the granularity of the width of the upstream port, so we must support writing part of the data width.
=> [ESI][BSP] Adding byte enables to cosim hostmem

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/verif.mlir
Ignore `verif.contract` operations during Verilog emission and simply pass their operands through to the results. This is always a valid lowering of a contract.
=> [ExportVerilog] Treat verif.contract as no-op

include/circt/Dialect/Verif/VerifVisitors.h, lib/Conversion/HWToBTOR2/HWToBTOR2.cpp
Add the `ContractOp` to the `verif::Visitor`. This requires a minor tweak to the HWToBTOR2 pass to handle unknown operations more generally.
=> [Verif] Add ContractOp to Visitor

include/circt/Dialect/Verif/Passes.td, lib/Dialect/Verif/Transforms/CMakeLists.txt, lib/Dialect/Verif/Transforms/StripContracts.cpp, lib/Firtool/Firtool.cpp, test/Dialect/Verif/strip-contracts.mlir
Add a simple pass that removes all contracts from the IR, treating them as passthroughs. Run the pass in firtool's HW-to-SV pipeline early on to add additional optimization opportunities. ExportVerilog will eventually ignore contracts anyway.
=> [Verif] Add StripContracts pass

include/circt/Dialect/RTGTest/IR/RTGTestOps.td, test/Dialect/RTGTest/IR/basic.mlir
Tests for the `printInstructionBinary` and `printInstructionAssembly` implementations will follow in the next PR.
=> [RTGTest] Add a few instructions

include/circt/Dialect/RTG/IR/RTGISAAssemblyInterfaces.td, include/circt/Dialect/RTG/IR/RTGISAAssemblyOpInterfaces.h, include/circt/Dialect/RTGTest/IR/RTGTestOps.td
Resolves https://github.com/llvm/circt/issues/8091
=> [RTG] More convenient InstructionOpInterface methods

docs/FormalVerification.md
The formal verification docs haven't been updated since circt-bmc made it upstream, so this is just a small PR to add some info on how to use it. I'll fix up the section below about BMC in another PR.
=> [docs] Add circt-bmc usage information to FormalVerification.md

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp, test/Dialect/FIRRTL/lowerXMR.mlir
This changes LowerXMR to process all modules instead of just those that are reachable from the top level module.
=> [FIRRTL] LowerXMR: process all modules

include/circt-c/RtgTool.h, include/circt/Tools/rtgtool/RtgToolOptions.h, integration_test/Bindings/Python/rtg_pipeline.py, lib/Bindings/Python/RTGToolModule.cpp, lib/CAPI/RtgTool/RtgTool.cpp, lib/Tools/rtgtool/CMakeLists.txt, lib/Tools/rtgtool/RtgToolOptions.cpp
Add the new passes to the pipeline and pass their options through to the frontend. Also fixes a bug with the existing unsupported instructions option.
=> [RTG] Populate pipeline with new passes

include/circt/Transforms/Passes.h, lib/Conversion/MooreToCore/CMakeLists.txt, lib/Conversion/MooreToCore/MooreToCore.cpp, lib/Transforms/MapArithToComb.cpp, test/Conversion/MooreToCore/basic.mlir
While this would be legal, having everything in CF is more canonical than mixing them. Thus making it easier for passes further down the pipeline.
=> [MooreToCore] Convert SCF ops inside llhd.process to CF

lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
This is legal because the llhd.wait operation already makes sure that at least one of the observed values has changed, i.e., the disjunct of all not-equal comparisons will always evaluate to true.
=> [MooreToCore] Don't insert wait event checks if all detects are AnyChange

include/circt/Dialect/Verif/VerifOps.td
As discussed in #8162, currently the semantics of `verif.symbolic_value` are unclear. This clarifies that the value can change between timesteps.
=> [NFC][Verif] Clarify `symbolic_value` semantics

tools/circt-verilog/circt-verilog.cpp
In the pass timing summary there is usually a negative amount for Rest which is the result of measuring the verilog parsing and preprocessing twice
=> [circt-verilog] Fix negative Rest timing

include/circt/Conversion/Passes.td, integration_test/circt-synth/divmod.mlir, lib/Conversion/CombToAIG/CombToAIG.cpp, test/Conversion/CombToAIG/comb-to-aig-arith.mlir
This patch adds support for lowering comb div/mod operations to AIG:
* Support unsigned div/mod for power-of-2 constant divisors 
* Support for non-power-of-2 divisors by emulating the operation with a mux tree when the number of unknown bits is small (default threshold is 10 bits). This is not ideal and eventually we should lower to a proper div/mod. Practically this lowering pattern covers many cases since users rarely use div/mod because these operations are very expensive (users write their own div/mod in their frontend language).  
* LEC tests are added.
=> [CombToAIG] Add support for div/mod operations

include/circt/Dialect/ESI/ESIInterfaces.td, include/circt/Dialect/ESI/ESIManifest.td, integration_test/Dialect/ESI/runtime/loopback.mlir, lib/Dialect/ESI/ESIOps.cpp, lib/Dialect/ESI/ESIServices.cpp, lib/Dialect/ESI/runtime/CMakeLists.txt, lib/Dialect/ESI/runtime/cpp/include/esi/Accelerator.h, lib/Dialect/ESI/runtime/cpp/include/esi/Engines.h, lib/Dialect/ESI/runtime/cpp/include/esi/Ports.h, lib/Dialect/ESI/runtime/cpp/include/esi/Services.h, lib/Dialect/ESI/runtime/cpp/include/esi/Types.h, lib/Dialect/ESI/runtime/cpp/include/esi/backends/Cosim.h, lib/Dialect/ESI/runtime/cpp/include/esi/backends/Trace.h, lib/Dialect/ESI/runtime/cpp/include/esi/backends/Xrt.h, lib/Dialect/ESI/runtime/cpp/lib/Accelerator.cpp, lib/Dialect/ESI/runtime/cpp/lib/Engines.cpp, lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp, lib/Dialect/ESI/runtime/cpp/lib/Ports.cpp, lib/Dialect/ESI/runtime/cpp/lib/Services.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Trace.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Xrt.cpp, lib/Dialect/ESI/runtime/cpp/tools/esitester.cpp, test/Dialect/ESI/manifest.mlir, test/Dialect/ESI/services.mlir
Introduces the concept of 'engines' -- things which are responsible for transmitting/recieving messages over a channel. Since this is a new concept (and was previously done only in cosim), add a new section to the manifest.
Re-use a bunch of stuff which supports services. Hacky, but it works. The entire manifest thing could use a re-think and second iteration. It is, however, make-it-work time.
=> [ESI Runtime] Pluggable channel engines

include/circt-c/Dialect/RTG.h, include/circt/Dialect/RTG/IR/RTGOps.td, include/circt/Dialect/RTG/IR/RTGTypes.td, integration_test/Bindings/Python/dialects/rtg.py, lib/Bindings/Python/RTGModule.cpp, lib/CAPI/Dialect/RTG.cpp, lib/Dialect/RTG/IR/RTGOps.cpp, test/CAPI/rtg-pipelines.c, test/CAPI/rtg.c, test/Dialect/RTG/IR/basic.mlir, test/Dialect/RTG/IR/cse.mlir, test/Dialect/RTG/IR/errors.mlir, test/Dialect/RTG/Transform/elaboration.mlir
Allow type parameters in the sequence type and attach it as a type attribute to the sequence op. That way ops referring to a sequence don't have to access the operation's body to verify the type.
=> [RTG] Custom parser/printer for sequence op and type for sequence families

lib/Dialect/FIRRTL/Transforms/InferResets.cpp, test/Dialect/FIRRTL/infer-resets-errors.mlir, test/Dialect/FIRRTL/infer-resets.mlir
When a child module is underneath two different reset domains, the pass
would emit an error message.  This change makes it so that it is allowed
as long as the reset signal name and the reset signal type between the
two domains are the same.
This also changes the logic to re-use a preexisting reset port: if there
is a port with the correct name for a reset domain, but the type does
match, we used to pick a different port name.  This changes it to be an
error, which matches the old SFC behaviour.
=> [FIRRTL] FART: allow modules to be in multiple domains at once

frontends/PyCDE/src/pycde/bsp/__init__.py, frontends/PyCDE/src/pycde/bsp/common.py, frontends/PyCDE/src/pycde/bsp/cosim.py, frontends/PyCDE/src/pycde/bsp/xrt.py, frontends/PyCDE/src/pycde/types.py
`ChannelEngineService` is a service implementation which services channels via selectable DMA engines.
In order to emulate (and test) DMA engines, adds a `cosim_dma` BSP. Involved a re-write of the CosimBSP since the builtin 'cosim' service implementation wants to service all of the outstanding client requests.
=> [ESI][BSP] Service implementation via selectable engine

lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/errors.mlir
According to the FIRRTL spec, the right hand side of a propassign must have source flow.  This means that it is illegal to read from a property output port, something that is allowed for regular HW ports.  This change enforces this property during flow checking in the operation verifiers.
=> [FIRRTL] Disallow reading from property ports

docs/Dialects/FIRRTL/FIRRTLIntrinsics.md, include/circt/Dialect/FIRRTL/FIRRTLStatements.td, include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, include/circt/Dialect/Verif/VerifOps.td, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLIntrinsics.cpp, test/Conversion/FIRRTLToHW/intrinsics.mlir, test/Dialect/FIRRTL/lower-intrinsics.mlir, test/Dialect/Verif/basic.mlir
Add the `circt.verif.require` and `circt.verif.ensure` intrinsics as a way to produce the `verif.require` and `verif.ensure` operations from FIRRTL. At a later point we'll probably want to promote the five verif ops `assert`, `assume`, `cover`, `require`, and `ensure` to the FIRRTL spec and merge the functionality of the `circt.verif.assert` intrinsic with the `firrtl.assert` operation.
Note that this requires dropping of the clock operand from `verif.require` and `verif.ensure`. This operand was never used, so it feels like a reasonable change. At a later point we might want to merge `verif.clocked_assert` into `verif.assert` by adding clock operands to the verif ops in general.
=> [FIRRTL] Add require and ensure intrinsics

lib/Dialect/LLHD/Transforms/TemporalCodeMotionPass.cpp, lib/Dialect/LLHD/Transforms/TemporalRegions.cpp, test/Dialect/LLHD/Transforms/temporal-code-motion.mlir
Ignore loops for now and basically assume full loop unrolling was performed before this pass. This was an implicit assumption until now. This PR explicitly checks for it and ignores the process in that case.
=> [LLHD][TCM] Ignore processes with CFG loops within a TR

lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/imdce.mlir
Fix an issue in `firrtl::hasDontTouch` where the cast to `FModuleOp` would crash if the function was called on a block argument of an operation that is not a module, for example, a `ContractOp`. Such block arguments are considered to not be marked as "don't touch".
=> [FIRRTL] Fix hasDontTouch crash on non-module block args

lib/Dialect/FIRRTL/Transforms/IMDeadCodeElim.cpp, test/Dialect/FIRRTL/imdce.mlir
Avoid a crash in IMDCE when encountering a block argument that is not defined by a module, but some other operation that has nested blocks, such as a contract. Additionally, when handling liveness of generic operations, conservatively mark any nested blocks executable.
=> [FIRRTL][IMDCE] Support operations with blocks

frontends/PyCDE/src/pycde/bsp/common.py, frontends/PyCDE/src/pycde/esi.py, lib/Dialect/ESI/runtime/cpp/lib/Services.cpp
Instead of trying to shoehorn all of the engine records into one service record (for the ChannelEngineService), add the capability to emit individual engine records.
=> [ESI][BSP] Emit engine records

lib/Dialect/ESI/runtime/cpp/include/esi/Ports.h, lib/Dialect/ESI/runtime/cpp/lib/Engines.cpp, lib/Dialect/ESI/runtime/cpp/tools/esitester.cpp
When an engine is unknown, throw the error when the user tries to connect rather than during manifest parsing.
=> [ESI][Runtime] Throw unknown engine error lazily

include/circt/Dialect/HW/HWAggregates.td
The documentation explicitly states that an OOB access is UB, but also says that it is equivalent to the verilog example. However, OOB in verilog would return the default value of the type (e.g., 0 for 2-state) AFAIU, so it has different semantics. Also, I think it's better to keep Verilog analogies out of the core dialect documentation in general
=> [HW] Resolve ambiguous array_slice documentation

frontends/PyCDE/integration_test/test_software/esi_test.py, frontends/PyCDE/src/pycde/bsp/Makefile.xrt.mk, frontends/PyCDE/src/pycde/bsp/common.py, frontends/PyCDE/src/pycde/constructs.py, frontends/PyCDE/test/test_xrt.py, lib/Dialect/ESI/runtime/cpp/include/esi/Common.h, lib/Dialect/ESI/runtime/cpp/lib/Common.cpp, lib/Dialect/ESI/runtime/cpp/lib/Engines.cpp, lib/Dialect/ESI/runtime/cpp/lib/Ports.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Trace.cpp
- Fix path to emconfigutil in XRT makefile
- Reduce MMIO register space allocation
- Fix gearbox client validity bug
- Fix gearbox valid_bytes padding bug
- Fix gearbox output type bug
- When instantiating an engine which has mmio and/or hostmem ports, connect them to a service request.
- To workaround a deficiency in ESI services which doesn't detect new service requests in instances produced by a service generator.
- Add toHex function for pointers.
- Fix the location of engine registry storage so we don't crash when registering one.
- Set the mode in read ports after at the end of the connect function so that isConnected doesn't prematurely report true.
- Remove unnecessary engine creation in Trace.
Since these were required for the DMA engine in an upcoming PR, they will be tested by …
=> [ESI][BSP] Bunch of small fixes and changes

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/intrinsics.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
Lower `firrtl.contract` to `verif.contract` ops. The lowering itself is pretty straightforward, since the ops are basically equivalent. The only exception are block arguments in FIRRTL that get replaced with op results in Verif due to the switch from an SSACFG region with dominance to a graph region.
The block arguments require a slight change to how nested operations are handled by the pass. Currently, a post-order walk over the operations is used. This is problematic since the parent operation does not get an opportunity to lower its block arguments before its child operations are lowered, which may need access to those block arguments. Switching to a pre-order walk does not work, since that wouldn't allow us to modify the operations during the walk, which we obviously do during the …
=> [FIRRTL][LowerToHW] Lower contract ops

test/circt-test/pipeline.mlir, tools/circt-test/circt-test.cpp
Add the `LowerContracts` or `StripContracts` pass to the circt-test pipeline in order to leverage contracts during formal verification. To make this work, circ-test has to run a preparatory pass pipeline on the input MLIR, and pass the result as input to the MLIR runners instead of the original file.
Also add an `--ir` option to dump the IR after the preparatory passes.
=> [circt-test] Add support for contracts

lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
Fix this issue: https://github.com/llvm/circt/issues/8176
=> [MooreToCore]Fix a crash caused by block args as observed values for llhd.wait.

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Dialect/Moore/MooreOps.cpp, test/Conversion/ImportVerilog/basic.sv
This PR fixes cases when selector maximum or minimum values do not fit into the range of the type for the folding `Moore` constant. 
CIRCT debug build fails with an [assertion](https://github.com/llvm/llvm-project/blob/aa580c2ec5eb4217c945a47a561181be7e7b1032/llvm/include/llvm/ADT/APInt.h#L120): 
```console
circt/llvm/llvm/include/llvm/ADT/APInt.h:120: llvm::APInt::APInt(unsigned int, uint64_t, bool, bool):
Assertion llvm::isIntN(BitWidth, val) && "Value is not an N-bit signed value"' failed.
```
With this test:
```verilog
module RangeElementSelection(
input reg [3:0] a [0:2],
output reg [3:0] b,
input reg [1:0] c);
b = a[c]; // Assertion here
b[3:0] = b[c[0]-:2]; // Assertion here
end
endmodule
```
This can be fixed by increasing `intType` size by `1` (which passed to …
=> [ImportVerilog] Fix assertion with constant folding

test/firtool/firtool.mlir, tools/firtool/firtool.cpp
This PR adds `-output-hw-mlir` option to firtool which emits HW IR into file in a similar way to `-output-final-mlir`. 
This PR adds `DumpIR` pass to simplify the emission. It's currently not exposed to other tool as it's very specific to firtool pipeline (actually the pass indirectly uses cl options defined in firtool.cpp)
=> [firtool] Add an option to emit HW MLIR into file

include/circt/Dialect/Verif/VerifOps.td, test/Dialect/Verif/canonicalization.mlir, test/Dialect/Verif/cse.mlir, test/Dialect/Verif/lower-contracts.mlir
Add the `MemAlloc` side effect to the result of `verif.symbolic_value`. This allows the canonicalizer to delete the op if it has no users while still preventing CSE from mergin multiple symbolic values.
Also add a few placeholders to the `lower-contracts.mlir` test to make it more robust.
=> [Verif] Mark SymbolicValueOp result as MemAlloc

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
If an `always @(*)` procedure does not read any values, an empty wait_event is inserted by ImportVerilog. Retaining this is important because it means the procedure suspends indefinitely at that point.
Also, lower an empty wait_event directly to a 'halt' op because it's more efficient in simulation and code size, and makes no difference in behavior.
=> [Moore] Mark wait_event with side-effect even if it is empty

include/circt/Dialect/Arc/ArcOps.td, include/circt/Dialect/Handshake/HandshakeOps.td, include/circt/Dialect/Kanagawa/KanagawaOps.td, include/circt/Dialect/SV/SVStatements.td, include/circt/Dialect/Sim/SimOps.td, include/circt/Dialect/SystemC/SystemCStatements.td, integration_test/CMakeLists.txt, integration_test/Dialect/SMT/basic.mlir, integration_test/lit.cfg.py, lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp, lib/Conversion/SMTToZ3LLVM/LowerSMTToZ3LLVM.cpp, lib/Dialect/FSM/FSMOps.cpp, lib/Dialect/Handshake/HandshakeOps.cpp, lib/Dialect/SystemC/SystemCOps.cpp, lib/Tools/circt-bmc/LowerToBMC.cpp, lib/Tools/circt-lec/ConstructLEC.cpp, test/Conversion/ArcToLLVM/lower-arc-to-llvm.mlir
This picked up a few breaking changes.
https://github.com/llvm/llvm-project/commit/327d6270
This added new required methods to CallOpInterface and CallableOpInterface. These methods are related to arrays of dictionary attributes for each argument and result, and are normally implemented upstream by simply defining the right arg_attrs and res_attrs arguments on the operations. This allows some of the common utilities upstream to work with the attributes.
However, we seem to have actually moved away from arrays of per-argument or per-result attributes in most cases, and handle this ourselves when we want to. I opted to stub out the methods in the tablegen definitions of our operations, rather than adding optional attributes and setting them to null in builders and builder callsites like was …
=> Bump LLVM to 289b17635958d986b74683c932df6b1d12f37b70.

include/circt/Dialect/LLHD/IR/LLHDStructureOps.td, lib/Dialect/LLHD/IR/LLHDOps.cpp
BranchOpInterface requries the control-flow edges to be side-effect free. However, WaitOp suspends execution and once execution is resumed, values on signals are expected to have changed from outside the process
=> [LLHD] Don't implement BranchOpInterface for WaitOp

include/circt/Dialect/Calyx/CalyxPasses.h, include/circt/Dialect/Calyx/CalyxPasses.td, lib/Dialect/Calyx/Transforms/AffineParallelUnroll.cpp, lib/Dialect/Calyx/Transforms/CMakeLists.txt, test/Dialect/Calyx/affine-parallel-unroll.mlir
This patch unrolls `affine.parallel` op to multiple `scf.execute_region` ops for easier lowering to `calyx.par` op so that we can do more higher-level optimizations and we can make the lowering of `scf.parallel` in the SCFToCalyx` pass trivial.
=> [Calyx] Unroll Affine ParallelOp to multiple SCF ExecuteRegionOps

test/Dialect/Calyx/affine-parallel-unroll.mlir
Forgot to change `calyx.parallel` to `calyx.unroll` in the test cases in PR: https://github.com/llvm/circt/pull/8248
=> [Calyx] Change `calyx.parallel` to `calyx.unroll` in the test cases

include/circt/Dialect/Calyx/CalyxPasses.td, lib/Dialect/Calyx/Transforms/AffineParallelUnroll.cpp, test/Dialect/Calyx/affine-parallel-unroll.mlir
This patch builds on top of https://github.com/llvm/circt/pull/8248. It canonicalizes SCF `IndexSwitchOp` after the `AffineParallelUnroll` pass as Affine `ParallelOp` often contains SCF `IndexSwitchOp` as a result of memory banking.
=> [Calyx] Canonicalize SCF IndexSwitch after AffineParallelUnroll

include/circt/Dialect/Calyx/CalyxLoweringUtils.h
ASAN caught new/delete type mismatch error.
=> [Calyx] virtual dtor to properly destruct derived classes

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_simple.mlir, test/Conversion/SCFToCalyx/errors.mlir
This patch adjusts the lowering of `scf.parallel` accordingly after https://github.com/llvm/circt/pull/8248 and https://github.com/llvm/circt/pull/8249.
=> [SCFToCalyx] Update the lowering of SCF ParallelOp after AffineParallelUnroll pass

include/circt/Dialect/Arc/ArcPasses.td, include/circt/Dialect/Verif/VerifOps.td, integration_test/arcilator/JIT/verif-simulation.mlir, lib/Dialect/Arc/Transforms/CMakeLists.txt, lib/Dialect/Arc/Transforms/LowerVerifSimulations.cpp, test/Dialect/Arc/lower-verif-simulations-error.mlir, test/Dialect/Arc/lower-verif-simulations.mlir, tools/arcilator/arcilator.cpp
Add the `LowerVerifSimulations` pass to the Arc dialect. This pass converts any `verif.simulation` ops in the input into a test harness module and a `func.func` that instantiates the module and applies the necessary stimulus to it using `arc.sim.*` ops.
Also add the pass to the arcilator pipeline. This allows the user to run any `verif.simulation` ops in the input design by specifying the `--run --jit-entry=<simulation-name>` command line options. We may want to streamline this in the future.
Also add an integration test which verifies an adder circuit and prints the simulation results.
=> [Arcilator] Allow running verif.simulation ops

lib/Dialect/RTG/Transforms/ElaborationPass.cpp
Fixes https://github.com/llvm/circt/issues/8160 and https://github.com/llvm/circt/issues/8161
=> [RTG][Elaboration] Use malloc instead of IR for virtual registers and labels

frontends/PyRTG/src/CMakeLists.txt, frontends/PyRTG/src/pyrtg/index.py, frontends/PyRTG/src/pyrtg/integers.py, frontends/PyRTG/src/pyrtg/labels.py, frontends/PyRTG/src/pyrtg/support.py, frontends/PyRTG/test/basic.py, lib/Bindings/Python/CIRCTModule.cpp, lib/Bindings/Python/CMakeLists.txt
Requires an LLVM bump to get https://github.com/llvm/llvm-project/pull/127039 once it landed
=> [PyRTG] Support integers

include/circt/Dialect/Verif/VerifOps.td, integration_test/arcilator/JIT/verif-simulation.mlir, lib/Dialect/Arc/Transforms/LowerVerifSimulations.cpp, lib/Dialect/Verif/VerifOps.cpp, test/Dialect/Arc/lower-verif-simulations.mlir, test/Dialect/Verif/basic.mlir, test/Dialect/Verif/errors.mlir
After some discussions on `verif.simulation`, the consensus seems to be that an arbitrary integer exit code that has no guarantee of being preserved properly by simulators, besides the zero vs non-zero distinction, is virtually useless in practice. Instead, simulations can be made simpler by generating a simple `i1` success result indicating whether the test passed or failed. Simulators can then map this to an appropriate exit code. The operating system's potential truncation of exit codes to fewer bits (e.g. 7 or 8 bits on Linux) is no longer an issue.
=> [Verif] Change simulation exit code to success boolean

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
Hi @mikeurbach,
This PR addresses https://github.com/llvm/circt/issues/6696.
It's a first-time contribution for me and these issues remained open for quite some time. I hope I didn't take anyone's assignment.
In `canonicalization.mlir` file I got an error when tried to reformat `firrtl.class @PropertyArithmetic...` line into multiple lines. Does `firrtl.class` support same format as `firrtl.module` in `mlir` files?
In a follow-up PR I can add other folding rules that were listed in aforementioned issues. Does `x + x -> x * 2` fold also makes sense here?
=> [FIRRTL] Add a folder for `add` property op

tools/hlstool/hlstool.cpp, tools/kanagawatool/kanagawatool.cpp
This is mostly a straightforward bump.
One change we had to incorporate is MLIR is generally moving towards auto-generated pass constructor functions. For more info, see: https://github.com/llvm/llvm-project/commit/d25beca.
This shows up for us as a few pass constructors we use from upstream getting renamed. We just need to apply the same renames as upstream: https://github.com/llvm/llvm-project/commit/c1a2292.
=> Bump LLVM to 6bfedfa0ba31a8ac8fd7fcfd2d33afaa5eabe0e5.

lib/Dialect/Calyx/Transforms/AffineParallelUnroll.cpp, test/Dialect/Calyx/affine-parallel-unroll.mlir
This patch does LICM after unrolling `affine.parallel` operations in order to prevent potential memory access contentions.
=> [Calyx] LICM after Affine ParallelOp unrolling

lib/Transforms/FlattenMemRefs.cpp, test/Transforms/flatten_memref.mlir
This patch flattens `memref.reshape` when its source memory reference is flattened in other passes
=> [FlattenMemRef] Flatten MemRef ReshapeOp when its source memory reference is flattened in other passes

lib/Transforms/MemoryBanking.cpp, test/Transforms/memory_banking_attrs.mlir
Previous implementation has a bug because it overwrites `bankingFactor/Dimension` in `resolveBankingAttributes`, which leads to attributes attached to an operation can overwrite the default values, effecting other memory operations.
Now we don't do inplace updates on `bankingFactor/Dimension` anymore.
=> [MemoryBanking] Should not overwrite banking factor/dimension when resolving attribute values

include/circt/Dialect/LLHD/Transforms/LLHDPasses.td, lib/Dialect/LLHD/Transforms/CMakeLists.txt, lib/Dialect/LLHD/Transforms/Mem2Reg.cpp, test/Dialect/LLHD/Transforms/mem2reg.mlir
Implement a dedicated LLHD pass that promotes signal/memory slots to SSA values and forwards drives to probes. The pass is distinct from MLIR's upstream Mem2Reg pass in that it also works for regions where the memory slots are defined outside the region. It also understands `llhd.wait` and `llhd.halt` operations which may suspend execution of a process and therefore allows the values of signals to change before execution resumes. To deal with this, the pass uses a lattice to propagate the need for slot definitions backwards from probes, and to propagate reaching definitions for slots forward from drives and initial probes. Using the lattice, the pass can forward driven values to probes as long as there is no process suspension in between (`llhd.wait`), and it will insert probes …
=> [LLHD] Add dedicated Mem2Reg pass

frontends/PyCDE/src/pycde/bsp/common.py, frontends/PyCDE/src/pycde/bsp/xrt.py, frontends/PyCDE/src/pycde/bsp/xrt_package.tcl, lib/Dialect/ESI/runtime/cpp/lib/backends/Xrt.cpp
Vivado 2022.1 has a 4k MMIO space limit. 2032.1 has one as well, though it's likely larger but undocumented. To get around this, we introduce a layer of indirection wherein one writes the desired location in a "virtual" MMIO space then does the read/write from/to another register.
=> [ESI][XRT] Implement "Indirect MMIO"

include/circt/Conversion/ImportVerilog.h, lib/Conversion/ImportVerilog/Structure.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/procedures.sv, tools/circt-verilog/circt-verilog.cpp
Add the `--always-at-star-as-comb` option to circt-verilog and add a corresponding option to ImportVerilog. When this option is set, detect `always @*` in the Verilog AST and lower it as a `always_comb`. This is a common pattern in synthesizers and simulators, since the traiditonal `always @*` in Verilog does not accurately describe the behaviour of combinational logic.
Enable this option by default, which seems to be a common behaviour among existing tools.
=> [ImportVerilog] Add option to lower always @* as always_comb

lib/Dialect/LLHD/Transforms/Mem2Reg.cpp, test/Dialect/LLHD/Transforms/mem2reg.mlir
Extend the LLHD Mem2Reg pass to support conditional drives. This is pretty trivial since the pass already tracks drive conditions generated through control flow. All that's needed is to initialize the condition of a drive's reaching definition that gets propagated across the lattice.
=> [LLHD] Support conditional drives in mem2reg

lib/Dialect/LLHD/Transforms/Mem2Reg.cpp, test/Dialect/LLHD/Transforms/mem2reg.mlir
Extend the LLHD Mem2Reg pass to also support non-blocking drives. These have a delay value of `1d` instead of the `1e` of blocking drives. To do so, add an additional bit to the slots associated with reaching definitions, indicating whether the definition for a slot is blocking/immediate or applies only after a delta delay. Blocking drives can then appropriately kill earlier non-blocking drives, and probes can only consider earlier blocking drives when resolving their value.
=> [LLHD] Support drives with delta delay in mem2reg

cmake/modules/SlangCompilerOptions.cmake, include/circt/Tools/circt-verilog-lsp-server/CirctVerilogLspServerMain.h, lib/Conversion/ImportVerilog/CMakeLists.txt, lib/Tools/CMakeLists.txt, lib/Tools/circt-verilog-lsp-server/CMakeLists.txt, lib/Tools/circt-verilog-lsp-server/CirctVerilogLspServerMain.cpp, lib/Tools/circt-verilog-lsp-server/LSPServer.cpp, lib/Tools/circt-verilog-lsp-server/LSPServer.h, lib/Tools/circt-verilog-lsp-server/Utils/CMakeLists.txt, lib/Tools/circt-verilog-lsp-server/Utils/LSPUtils.cpp, lib/Tools/circt-verilog-lsp-server/Utils/LSPUtils.h, lib/Tools/circt-verilog-lsp-server/VerilogServerImpl/CMakeLists.txt, lib/Tools/circt-verilog-lsp-server/VerilogServerImpl/VerilogServer.cpp, lib/Tools/circt-verilog-lsp-server/VerilogServerImpl/VerilogServer.h, test/CMakeLists.txt, test/Tools/circt-verilog-lsp-server/diagnostic.test, test/Tools/circt-verilog-lsp-server/include.test, test/Tools/circt-verilog-lsp-server/include/Bar.sv, test/Tools/circt-verilog-lsp-server/initialize-params.test, test/Tools/circt-verilog-lsp-server/lit.local.cfg, test/Tools/circt-verilog-lsp-server/textdocument-didchange.test, test/Tools/circt-verilog-lsp-server/textdocument-didclose.test, test/lit.cfg.py, tools/CMakeLists.txt, tools/circt-verilog-lsp-server/CMakeLists.txt, tools/circt-verilog-lsp-server/circt-verilog-lsp-server.cpp
This is a first PR to add a Language Server Protocol (LSP) implementation for Verilog/SystemVerilog using the slang frontend. 
The server is built as circt-verilog-lsp-server and eventually integrates with CIRCT's existing Verilog import capabilities. It leverages MLIR's LSP server support libraries for the protocol implementation.
* VerilogServer.cpp - Core language service implementation that manages documents
and interfaces with slang for parsing and analysis. Maintains document state
and handles document synchronization events.
* LSPServer.cpp - Protocol layer that implements LSP message handling and converts
between LSP types and internal representations. Built on MLIR's LSP server
support libraries.
`lib/Tools/circt-verilog-lsp-server/{Utils, VerilogSeverImpl}` are added as …
=> [circt-verilog-lsp-server] Add Verilog Language Server

include/circt/Transforms/Passes.h, include/circt/Transforms/Passes.td, lib/Transforms/MemoryBanking.cpp, test/Transforms/memory_banking.mlir, test/Transforms/memory_banking_attrs.mlir, test/Transforms/memory_banking_invalid.mlir, test/Transforms/memory_banking_multi_config.mlir, test/Transforms/memory_banking_multi_dim.mlir
This patch supports passing multiple `banking.factors/dimensions` to the command line options as well as attaching as attributes.
=> [MemoryBanking] Memory banking supports multiple banking factors/dimensions config

lib/Bindings/Python/CMakeLists.txt
Makes it easier for sub-projects to only include parts of the python bindings
=> [Python] Declare a separate sub-target for support sources

lib/Conversion/SimToSV/SimToSV.cpp, test/Conversion/SimToSV/plusargs.mlir, test/firtool/plusargs.fir
For UPF simulations, we want to disable plusargs but drive the output wires with 0 instead of z.  We want this to be able to enable this mode of operation while also enabling assertions, so we add another macro UPF_SIM to control this behaviour.
=> [sim] Add emission for plusargs for UPF simulations

include/circt/Transforms/Passes.h, include/circt/Transforms/Passes.td, lib/Transforms/CMakeLists.txt, lib/Transforms/HierarchicalRunner.cpp, test/Transforms/hierarchical_runner.mlir, test/circt-synth/basic.mlir, tools/circt-synth/CMakeLists.txt, tools/circt-synth/circt-synth.cpp
Add a new pass that allows running passes under hierarchy. This is useful when we want to run synthesis passes only on real designs.
This implementation is based on MLIR's upstream [CompositePass](https://github.com/llvm/llvm-project/blob/0afe2bd21b06bed4d48eb88a99d13a768426359c/mlir/lib/Transforms/CompositePass.cpp#L30-L52) and [Inliner utilities](https://github.com/llvm/llvm-project/blob/0afe2bd21b06bed4d48eb88a99d13a768426359c/mlir/lib/Transforms/Utils/Inliner.cpp#L541-L560). The pass takes a pipeline string and runs it on modules in the design hierarchy. It supports configurable options including the pipeline to run under hierarchy, the name of the top-level module, and whether to include bound instances in the hierarchy traversal.
The implementation updates circt-synth tool with the …
=> [Transforms][circt-synth] Add HierarchicalRunner pass

include/circt/Dialect/LLHD/Transforms/LLHDPasses.td, lib/Dialect/LLHD/Transforms/CMakeLists.txt, lib/Dialect/LLHD/Transforms/HoistSignals.cpp, test/Dialect/LLHD/Transforms/hoist-signals.mlir
Add the HoistSignals pass which is intended to hoist probes and drives out of processes. Currently only probe hoisting is implemented. Probes that immediately follow resumption points, i.e. the entry block and blocks after `llhd.wait`, can be hoisted out of the process if their result is not live across any wait ops. Almost all probes left after the Mem2Reg pass can be hoisted.
In the future, this pass should also hoist drives out of processes and promote the driven value to process results. This will remove all drives from combinational processes, such that only drives encoding register/latch behaviour remain.
=> [LLHD] Add pass to hoist probes out of processes

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_simple.mlir
This patch lowers `arith.subf` in `-lower-scf-to-calyx`.
=> [LowerSCFToCalyx] Lower Arith SubFOp

lib/Dialect/ESI/runtime/CMakeLists.txt, lib/Dialect/ESI/runtime/cpp/include/esi/Context.h, lib/Dialect/ESI/runtime/cpp/include/esi/Logging.h, lib/Dialect/ESI/runtime/cpp/lib/Logging.cpp, lib/Dialect/ESI/runtime/cpp/tools/esiquery.cpp
Adds a `ConsoleLogger` which uses the `fmt` library to add colors to the output when logging to the console. Make it the default logger.
=> [ESI Runtime] Color output formatting

include/circt/Dialect/Calyx/CalyxPrimitives.td, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Dialect/Calyx/CalyxOps.cpp, lib/Dialect/Calyx/Export/CalyxEmitter.cpp, lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp, test/Conversion/SCFToCalyx/convert_simple.mlir, test/Dialect/Calyx/emit.mlir
This patch supports lowering and emit of `arith.fptosi`, with the backend support in Calyx: https://github.com/calyxir/calyx/pull/2422.
=> [SCFToCalyx] Arith FPToSI lowering and its emit

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_simple.mlir
This is my current proposal on how to lower `arith.bitcast` should be lowered, not 100% sure.
Since Calyx treat everything as bit vectors, I just keep every bit unchanged.
=> [SCFToCalyx] Lower Arith Bitcast 

include/circt/Conversion/Passes.td, lib/Conversion/CombToAIG/CombToAIG.cpp, tools/circt-synth/circt-synth.cpp
Previously CombToAIG lowers every comb operations into AIG operations
in a single pass. The issue is the size of IR lowered from Comb is
very large, and it heavily relies on AIG canonicalizations clean up.
This is some times very inefficient, and it's much better to clean up
at Comb level.
So this commits adds another run of CombToAIG that paratially lowers
Comb operations, specifically arithmetic operations (add, sub, mul, shift etc).
=> [circt-synth] Partially lower Comb operations and run canonicalizations

.github/workflows/nightlyIntegrationTests.yml, .github/workflows/shortIntegrationTests.yml, CMakeLists.txt, integration_test/lit.cfg.py, integration_test/lit.site.cfg.py.in, tools/circt-test/circt-test-runner-sby.py
#7756 adds the SymbiYosys test runner and requires the `sby` feature, but did not add the corresponding available feature in `lit.cfg.py`, so this test never seems to run, and #7763 introduces a syntax error, a backslash in the f-string expression part, in the Python script.
Unlike #7884, there is no need to modify PATH variable for the script since `sby` should be in the PATH if we can check it in CMake.
=> [circt-test] fix SymbiYosys integration test

integration_test/circt-test/contracts.mlir, lib/Dialect/Verif/Transforms/LowerContracts.cpp, test/Dialect/Verif/lower-contracts.mlir
The multiplier integration test revealed a bug in the ordering of operation cloning for the lower contracts logic.  This fixes the issue by simplifying the logic to rely on a topological sort of the operations to clone, rather than trying to construct the operations in the right order.
=> [Verif] Add multiplier integration test, fix bug in lower contracts

frontends/PyCDE/integration_test/esitester.py, frontends/PyCDE/src/pycde/bsp/common.py, frontends/PyCDE/src/pycde/bsp/cosim.py, frontends/PyCDE/src/pycde/bsp/dma.py, frontends/PyCDE/src/pycde/bsp/xrt.py, frontends/PyCDE/src/pycde/esi.py, frontends/PyCDE/src/pycde/signals.py, lib/Dialect/ESI/runtime/cpp/include/esi/CLI.h, lib/Dialect/ESI/runtime/cpp/include/esi/Engines.h, lib/Dialect/ESI/runtime/cpp/lib/Engines.cpp, lib/Dialect/ESI/runtime/cpp/tools/esitester.cpp
A simple, non-performant DMA-based from host communication channel.
1) Host sends address of buffer address via MMIO write to register 0x08.
2) Host sends address of completion address via MMIO write to register 0x10.
3) Device reads data from said buffer and sends down the channel.
4) Device writes '1' to the first byte of the completion buffer to signal that
the transfer is done.
5) Goto 1.
=> [ESI] Simple FromHost DMA engine

lib/Conversion/SimToSV/SimToSV.cpp, test/Conversion/SimToSV/plusargs.mlir, test/firtool/plusargs.fir
This change adds an alternative method of supporting plusargs in UPF
simulations by ensuring that the plusargs found variable is compared
with case-equals (`found === 1'h1`) to squash the `x` value to `0`.
=> [sim] Add emission for plusargs for UPF simulations 

lib/Dialect/Kanagawa/Transforms/KanagawaCallPrep.cpp
This was mostly a clean bump.
There was one breaking change: after years, and based on discussion on PR review, a decision was made to finally do away with separate `match` and `rewrite` member functions on rewrite patterns:
https://github.com/llvm/llvm-project/commit/a21cfca
This was actually really smooth for us; only one pass with two patterns still used the split match and rewrite approach, and it was trivial to convert to a matchAndRewrite.
=> Bump LLVM to d90423e310482bdbc731242fa25dcb3dd44e69de.

lib/Dialect/FIRRTL/Transforms/AdvancedLayerSink.cpp, test/Dialect/FIRRTL/advanced-layer-sink.mlir
In advanced-layer-sink, add the ability to sink ops by cloning them to their uses. This PR is only cloning constant-like ops, but we have the option to clone more sorts of ops as needed.
Constants are heavily shared, so they typically aren't sinkable by movement. Cloning will put constants directly into the layerblock where they are used, which avoids having us capture the constant as a port when lowering layerblocks to modules. It is important to put constants directly in a module because it enables more canonicalization later in the pipeline.
We used to rely on IMCP to sink constants after lower-layers, but we lost that as we moved the layer lowering passes later in the pipeline, which is why we now have to clone constants ourselves.
=> [FIRRTL][AdvancedLayerSink] Add the ability to sink ops by cloning

include/circt/Dialect/Calyx/CalyxPasses.h, include/circt/Dialect/Calyx/CalyxPasses.td, lib/Dialect/Calyx/Transforms/AffineToSCF.cpp, lib/Dialect/Calyx/Transforms/CMakeLists.txt, test/Dialect/Calyx/affine-to-scf.mlir
This pass lowers the Affine dialect to the SCF dialect for the ease of Calyx-related passes afterwards.
This can also be helpful for the un-unpstreamed passes that @andrewb1999 has.
=> [AffineToSCF][Calyx] Lower Affine to SCF for Calyx

include/circt/Tools/circt-bmc/Passes.td, test/Tools/circt-bmc/lower-to-bmc-no-comb.mlir
`comb` is currently missing as a dependency of `LowerToBMC`, which means it's not loaded on designs with no comb ops in them and crashes. Regression test included.
=> [LowerToBMC] Add `comb` as a dialect dependency

integration_test/Dialect/SMT/basic.mlir, lib/Conversion/SMTToZ3LLVM/LowerSMTToZ3LLVM.cpp, test/Conversion/SMTToZ3LLVM/smt-to-z3-llvm.mlir
Looks like the debug mode of `LowerSMTToZ3LLVM` (which is used when `--print-solver-output` is passed to circt-bmc) broke in https://github.com/llvm/circt/pull/8225 - there was [a commit in LLVM](https://github.com/llvm/llvm-project/pull/123378) that added some extra checks on the result type passed to `lookupOrCreateFn`, and it looks like it's expecting a void type rather than an i32. I don't know too much about this side of things so LMK if this isn't the preferred fix.
=> [LowerSMTToZ3LLVM] Change printf type provided to lookupOrCreateFn

include/circt/Dialect/FIRRTL/FIRRTLCanonicalization.td, lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir, test/firtool/extract-test-code.fir, test/firtool/layer-merge-across-inlined-submodule.fir
If the predicate and enable are the same expression, then the predicate must be true whenever the enable is true, so the assert cannot fire, and we can safetly remove the assert.
=> [FIRRTL] Canonicalize Assert(clk, p, e) when p == e

include/circt/Conversion/Passes.td, include/circt/Conversion/VerifToSMT.h, include/circt/Tools/circt-bmc/Passes.td, integration_test/circt-bmc/rising-clocks-only.mlir, lib/Conversion/VerifToSMT/VerifToSMT.cpp, lib/Tools/circt-bmc/LowerToBMC.cpp, test/Conversion/VerifToSMT/verif-to-smt.mlir, test/Tools/circt-bmc/lower-to-bmc.mlir, tools/circt-bmc/circt-bmc.cpp
Most of the time (maybe all of the time?) you don't care about negedges when you're model checking, so half of the cycles explored by circt-bmc are irrelevant since the clock has just been inverted. This mode skips those cycles by halving the bound, getting rid of the posedge checks and always keeping the clock as 1.
=> [circt-bmc] add rising clocks only mode

integration_test/lit.cfg.py
I managed to recreate the issue reported in #8231, and upon some poking around found out that the issue was that, on my system at least, the Z3 library is set to `Z3_LIBRARIES-NOTFOUND` by the code that searches for a Z3 installation when there is no available Z3 library, rather than being left as an empty string. This expands the check to check if it's either an empty string or `Z3_LIBRARIES-NOTFOUND`. Hopefully this also fixes it for you @mikeurbach - if not then I'd be curious to know what is assigned to `config.z3_library` in your `build/integration_test/lit.site.cfg.py`
=> [SMT] expand Z3 library check in integration tests

include/circt-c/Dialect/HW.h, integration_test/Bindings/Python/dialects/hw.py, lib/Bindings/Python/HWModule.cpp, lib/CAPI/Dialect/HW.cpp
We already have a binding for the OutputFileAttr, but it didn't provide any useful accessor. This adds a safe, typed accessor to read out the filename as a string.
=> [Python] Add binding for OutputFileAttr filename.

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/split-output-file.mlir
This adds an OutputFileAttr to any op that didn't already have one, to indicate the output path the op was ultimately exported to. The intent is to be able to query the final MLIR to know explicitly where every op was exported on disk when exporting split Verilog.
=> [ExportVerilog] Back-annotate output file attributes during export.

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td
This is almost a clean bump.
After https://github.com/llvm/llvm-project/commit/f3e5594, DRR
patterns will now generate calls to builders that use Properties, for
dialects that use Properties. Since we skip default builders for
RegOp, we need a builder that accepts Properties, since the DRR
patterns assume such a builder exists.
=> Bump LLVM to 4d5a963eaf6ad209487a321dee7f0cd2a0f98477.

docs/Passes.md, include/circt/Tools/circt-bmc/CMakeLists.txt, include/circt/Tools/circt-lec/CMakeLists.txt, include/circt/Transforms/CMakeLists.txt
The documentation for some of the "general" passes was missing.
AFAICT @mortbopet and @mikeurbach accidentally added it as `add_mlir_doc` instead of `add_circt_doc` in https://github.com/llvm/circt/commit/fe32c20d965dd2e61420a5a6d309015f9be6b0e6
everything else was already switched over in https://github.com/llvm/circt/commit/77f9520ea156b093e2de0a4ad73cbb6592484cb5
The same applies for the BMC and LEC passes.
(the changed arguments come from https://github.com/llvm/circt/commit/68280a14263239ad6a2001d33310decb1fc2f698)
=> [DOC] Add missing passes

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLStatements.td, include/circt/Dialect/FIRRTL/FIRRTLTypes.h, include/circt/Dialect/FIRRTL/FIRRTLTypes.td, include/circt/Dialect/FIRRTL/FIRRTLTypesImpl.td, include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, lib/Dialect/FIRRTL/Export/FIREmitter.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/FIRRTLTypes.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/round-trip.mlir
Add a format string type.  This is intended to be used to improve the way we capture format strings and extend this to capturing more advanced concepts like "time" via attributes as opposed to resorting to enums and attributes.
=> [FIRRTL] Add FormatStringType

include/circt/Dialect/Calyx/CalyxPasses.h, include/circt/Dialect/Calyx/CalyxPasses.td, lib/Dialect/Calyx/Transforms/AffinePloopUnparallelize.cpp, lib/Dialect/Calyx/Transforms/CMakeLists.txt, test/Dialect/Calyx/affine-ploop-unparallelize.mlir
This pass unparallelize `affine.parallel` op by `factor` (attached as the attribute).
We need this pass to coordinate with the memory banking pass for the Calyx dialect.
Suppose we have a memory `%alloc` banked to two: `%alloc_0` and `%alloc_1`, and suppose the program looks like:
```mlir
affine.parallel (%arg) = (0) to (8) {
scf.index_switch %arg mod 2:
case 1 {
memref.store %cst, %alloc_0[%arg floordiv 2]
}
case 0 {
memref.store %cst, %alloc_1[%arg floordiv 2]
}
}
```
By running `--lower-scf-to-calyx` pass, the resulting program will have `calyx.par` with 8 arms; but there are only 2 banks. So the general issue is that, when `affine.parallel`'s total number of trip counts is greater than the number of banks, there will be memory access contention when we later lower to Calyx.
=> [AffineParallelOpUnparallelize][Calyx] Affine parallel loop unparallelize to nested for and parallel loop

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/SV/Transforms/SVExtractTestCode.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
Add a lowering for PrintfOps which use TimeOps for substitutions.  A TimeOp used by a PrintfOp will be lowered to an sv::TimeOp that is co-located with the Verilog FWriteOp.  (This helps to avoid problems where the system function `$time` could get spilled to a wire.  This is sunk into the same procedural region as the fwrite to avoid this.)
Practically, this is the last piece needed to compile FIRRTL that includes the `{{SimulationTime}}` special substitution all the way to Verilog.
This is stacked on #8342.
The following FIRRTL includes the lone supported special substitution `{{SimulationTime}}`:
``` firrtl
FIRRTL version 4.2.0
circuit Foo :
public module Foo :
printf(clock, UInt<1>(1), "[{{SimulationTime}}]: %d", a)
```
Compiled to Verilog using …
=> [LowerToHW] Lower PrintfOp w/ TimeOp

lib/Dialect/Seq/Transforms/HWMemSimImpl.cpp, test/Dialect/Seq/hw-memsim.mlir
Fix some width errors which could occur in the HWMemSimImpl pass.  The problem is that a loop variable may need to be sized one bit larger than what is used for its address in order for it to hit its loop bound. However, if this is sized large enough to ever reach the loop bound, it is too large for the index.
Fixes #8350.
=> [Seq] Fix width errors in HWMemSimImpl

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/Conversion/FIRRTLToHW/lower-to-hw-module.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/firtool/import-ref.fir, test/firtool/lower-layers.fir, test/firtool/print.fir
Add a zero width to all format string substitutions when lowering from FIRRTL to HW/SV.  E.g., this will lower `%x` into `%0x`.  This is almost always preferred and avoids the need for (right now) adding width specifiers to Chisel and FIRRTL.  While we would like to do this, we don't want to do it as passthrough from Chisel where Chisel users write Verilog format substitutions.
As @jackkoenig and I got to bottom of, there are non-standard format specifiers that people might want (e.g., `%-` for left justified) that tools support differently and we would like to figure out how to actually lower these if they matter.
=> [LowerToHW] Add '0' to format string width

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
If the regreset has a constantly-high reset, then we can replace the register with its reset value. However, if the reset value's type does not match the type of the register, we cannot do the replacement.
This commit adds a check to an old canonicalizer, to ensure the reset value's type matches, before doing the replacement.
Fixes: #8348
=> [FIRRTL] Fold regreset to its reset value iff the type matches

include/circt/Dialect/FIRRTL/FIRParser.h, test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir, test/firtool/classes-dedupe.fir, test/firtool/instchoice.fir
Bump the next FIRRTL version to 5.1.0.  This is because we want to start using the 5.0.0 feature of `{{SimulationTime}}` substitutions.  However, we also have unsupported features that exist like all the un-spec'd property types.
=> [firtool] Bump "next" FIRRTL version to 5.1.0

include/circt/Reduce/Tester.h, lib/Reduce/CMakeLists.txt, lib/Reduce/Tester.cpp, tools/circt-reduce/CMakeLists.txt, tools/circt-reduce/circt-reduce.cpp
Add the ability to read and write bytecode for `circt-reduce`.  This is intended to help with very large MLIR files to avoid wasting all of `circt-reduce`'s time on printing/parsing.
=> [circt-reduce] Add bytecode import/export

include/circt/Dialect/Calyx/CalyxPasses.h, include/circt/Dialect/Calyx/CalyxPasses.td, lib/Dialect/Calyx/Transforms/CMakeLists.txt, lib/Dialect/Calyx/Transforms/ExcludeExecuteRegionCanonicalize.cpp, test/Dialect/Calyx/exclude-exec-region-canonicalize.mlir
This patch runs all canonicalization passes of legal dialects, skipping `scf.execute_region`. This pass is intended to be run after `-affine-parallel-unroll` and before lowering to Calyx.
=> [Calyx] Canonicalizations that skip scf.execute_regions

include/circt/Dialect/Calyx/CalyxLoweringUtils.h, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp, test/Conversion/SCFToCalyx/convert_controlflow.mlir
This patch fixes a logic bug that checks if an `scf.if` op's condition needs a register to hold the result of sequential computation
=> [SCFToCalyx] If op with sequential condition bug fix

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir
Fix for #7773 and  #1537.
- Added a check for duplicates in the symbolTable. Added and removed tests for the same. 
- Made changes in parseContract to avoid re-declaration error 
-  I'm deleting the symbol for contract body before adding the results to the symbolTable (I'm guessing it's no longer used, since its marked as invalid)
- or is there a better way to do this, by updating the moduleContext with the results before its being given to ContextScope, so we can avoid calling addSymbolEntry twice ? (not sure about this)
Let me know if this works, or if this breaks something I don't understand.
Feedback is appreciated.  @fabianschuiki
=> [FIRRTL] Fix: Enforce flat namespace for modules

frontends/PyRTG/src/pyrtg/resources.py, frontends/PyRTG/test/basic.py, include/circt/Dialect/RTG/IR/RTGOps.td, include/circt/Dialect/RTG/IR/RTGVisitors.h, lib/Dialect/RTG/Transforms/ElaborationPass.cpp, test/Dialect/RTG/IR/basic.mlir, test/Dialect/RTG/Transform/elaboration.mlir
This is, e.g., useful when creating an immediate from a for loop iteration index var.
=> [RTG] Add int_to_immediate op

include/circt/Dialect/LLHD/IR/LLHDSignalOps.td, lib/Dialect/LLHD/IR/LLHDOps.cpp
Make `llhd.prb` ops only have read side effects if used in an SSACFG region. This works around an issue where CSE would not move or eliminate probes across drives and other processes, even though that would be legal in a graph region. In graph regions, a probe acts like a pure op dereferencing a signal and the exact order of operations, especially the order with respect to drives and other ops interacting with the signal do not matter.
=> [LLHD] Make probes side-effect-free in graph regions

include/circt/Dialect/LLHD/IR/LLHDStructureOps.td, include/circt/Dialect/LLHD/IR/LLHDTypes.h, lib/Dialect/LLHD/Transforms/HoistSignals.cpp, test/Dialect/LLHD/Transforms/hoist-signals.mlir
Extend the `HoistSignals` pass and hoist drives before halt and wait terminators out of the parent process. All drives that have no side-effecting operations in between them and the block's suspending terminator can be hoisted. If the same signal is driven multiple times in the same block, only the last drive is hoisted.
To hoist drives, the pass collects all drives for each driven signal slot and creates new yield operands and process results to carry the drive operands out of the process. Special care is taken to not create unnecessary results for values that are uniform across all drives and available outside the processes.
=> [LLHD] Hoist drives out of processes

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/Export/FIREmitter.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir, test/firtool/print.fir
Add width specifiers to FIRRTL printfs.  This will allow for width specifiers on printf format strings which take a radix (binary, decimal, or hexadecimal).  Additionally, enshrine that `%%` is a literal `%` and will be treated as such.
`firtool` will now reject unknown width specifiers.  E.g., this closes the `%m` loophole.
=> [FIRRTL] Add printf widths, reject unknown

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/Export/FIREmitter.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/firtool/print.fir
Add support for the FIRRTL 5.0.0 printf substitution `{{HierarchicalModuleName}}`.  Support this in the FIRRTL Dialect with a new operation.  Add FIRRTL parsing, FIRRTL emission, and FIRRTL-to-HW lowering.
=> [FIRRTL] Add {{HierarchicalModuleName}} support

include/circt/Dialect/FIRRTL/FIRRTLDeclarations.td, lib/Analysis/FIRRTLInstanceInfo.cpp, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp, lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp, lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, lib/Dialect/FIRRTL/Transforms/LowerMemory.cpp, lib/Dialect/FIRRTL/Transforms/LowerSignatures.cpp, lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp, lib/Dialect/FIRRTL/Transforms/SpecializeOption.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir
This flag acts the same as doNotPrint in hardware. When lowering an instance to the hw dialect, copy the doNotPrint attribute over.
I am preparing to add a bind op to the firrtl dialect (not the frontend language), which will pair with this flag. My goal is to allow lower-layers to place the bind op for layerblocks into the body of a bind file, which is represented by an emit.file op.
=> [FIRRTL] Add doNotPrint flag to InstanceOp

lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
Fixes #8128 
Also, adding this Op conversion passes this [test](https://chipsalliance.github.io/sv-tests-results/?v=circt_verilog+5.10+structure-replication).
@fabianschuiki can you please review this? Any feedback is appreciated.
=> [MooreToCore] Lower `moore.array_create` Op

include/circt/Dialect/LLHD/Transforms/LLHDPasses.td, lib/Dialect/LLHD/Transforms/CMakeLists.txt, lib/Dialect/LLHD/Transforms/LowerProcesses.cpp, test/Dialect/LLHD/Transforms/lower-processes.mlir
Add an update version of the process lowering pass. This new version expects all probes and drives to have been hoisted out of processes. The pass then converts an `llhd.process` op to an `scf.execute_region` if the process
- has a single wait op;
- has a simple control flow loop through that single wait op;
- has no destination operands on the wait op; and
- has all operands that are used in the process but defined outside of the process observed by the wait op.
This essentially lowers any combinational LLHD processes with a CFG loop through a wait op which triggers when any of the inputs change into a simple SCF execute region without the CFG loop. The assumption here is that the execute region will be re-evaluated if any of the values used within it change.
Life would be a lot easier …
=> [LLHD] Update LowerProcesses pass to work with process results

lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp, lib/Dialect/FIRRTL/Transforms/InferResets.cpp, lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp, lib/Dialect/HW/Transforms/FlattenModules.cpp, lib/Dialect/LLHD/Transforms/FunctionEliminationPass.cpp, lib/Transforms/FlattenMemRefs.cpp, test/Transforms/flatten_memref_calls.mlir
There were series of patches to llvm::EquivalenceClasses this week,
and we updated accordingly:
* There is no longer a template parameter for the comparator
* The idiom for iterating over EquivalenceClasses was updated
* The idiom for iterating over members was updated
There was a change to the InlinerUtils functions to now include a
required callback for ops that are cloned. To update our call sites,
this default constructs an InlinerConfig and uses the default
clone callback.
Finally, there was a change to the memref.subview verifier to actually
check bounds when statically possible. Since memref.subview is
technically supposed to "represent a reduced-size view of the
original memref", I think our previous lowering was technically
supposed to be interpreted as out of bound accesses.
See …
=> Bump LLVM to 9344b2196cbc36cdc577314bbb2b889606ba6820.

lib/Dialect/Calyx/Transforms/ExcludeExecuteRegionCanonicalize.cpp
https://github.com/llvm/circt/pull/8358 forgets exclude `scf.parallel`
=> [Calyx] Canonicalization should exclude parallel as well

lib/Dialect/Calyx/Transforms/AffinePloopUnparallelize.cpp, test/Dialect/Calyx/affine-ploop-unparallelize.mlir
This patch simplifies the nested `scf.index_switch` operations if their arguments only depend on `affine.parallel`'s loop induction variable and if they are the results of some modulo expressions. Use cases are when they come from the memory banking pass where it uses `scf.index_switch` to decide which bank to use.
=> [AffineParallelOpUnparallelize] Simplify nested SCF IndexSwitch

include/circt/Dialect/Calyx/CalyxPasses.td, lib/Dialect/Calyx/Transforms/AffinePloopUnparallelize.cpp, test/Dialect/Calyx/affine-ploop-unparallelize.mlir
The `unparallelized` attribute was meant to exist for a downstream new pass that simplifies `scf.index_switch` operations and having an attribute is helpful to identify the existence of those `scf.index_switch` ops; but now this pass is being piggybacked in https://github.com/llvm/circt/pull/8401
=> [AffineParallelUnroll] Remove unnecessary unparallelized attribute

lib/Dialect/OM/Evaluator/Evaluator.cpp, unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp
The Evaluator will call `getOrCreateValue` when instantiating an Object, which this function lacks the evaluation of the `tuple_get' operation.
~~Further tests will be added later.~~
Done.
=> [OM] Fix tuple_get operation in OMEvaluator

include/circt/Dialect/SMT/SMTArrayOps.td
Fixed a minor issue in the SMT description. The SMT dialect does not have an smt.declare operation. It should be smt.declare_fun.
=> [SMT] fix the declaration function name in ArrayBroadcastOp

include/circt/Dialect/HW/HierPathBuilder.h, lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp, lib/Dialect/HW/CMakeLists.txt, lib/Dialect/HW/HierPathBuilder.cpp
Factor a utility out of FIRRTL's `LowerXMR` pass which is used for
creating `hw::HierPathOp`s.  This does some useful things like caching and
creates the ops _in order_ as opposed to in reverse order.  Refactor
`LowerXMR` to use this utility.
Context: I am planning to use this in `LowerLayers` and this is the
prerequisite work to make it a utility.
=> [FIRRTL][HW] Factor HierPath builder util out of LowerXMR

lib/Dialect/FIRRTL/FIRRTLUtils.cpp, test/Dialect/FIRRTL/lower-classes.mlir
Existing target support was built up asserting that only ports of FModuleOps are targeted. But there isn't anything really fundamental here, it looks like we have everything in we need in the FModuleLike interface and inner symbol infrastructure to put targets on ports of FExtModuleOps in exactly the same manner.
Fixes https://github.com/llvm/circt/issues/8417.
=> [FIRRTL] Support Paths that target ports of extmodules.

include/circt/Dialect/FIRRTL/FIRRTLStatements.td, include/circt/Dialect/SV/SVExpressions.td, include/circt/Dialect/SV/SVVisitors.h, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/Export/FIREmitter.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/SV/basic.mlir, test/firtool/print.fir
Add a new SFormatFOp operation to handle string formatting in SystemVerilog.
This operation produces a constant string literal and supports variable
substitutions. Also enhance FIRRTL fprintf operation by:
- Support dynamic file names in FIRRTL fprintf operations
- Replace FStringType with PrintfOperandType for output file substitutions
- Add SystemVerilog sformatf lowering for formatted file names
- Update file descriptor handling in emitter
It implements micro-optimization regarding FD creation. If the file is known to be static, the fd is initialized in initial block but for dynamic file name it opens fd just before its uses. 
```scala
FIRRTL version 5.1.0
circuit PrintTest:
public module PrintTest :
input cond : UInt<1>
input a : UInt<8>
fprintf(clock, cond, …
```
=> [FIRRTL][SV] Support substitutions in fprintf output file name. Add sv.sformatf. 

include/circt/Dialect/FIRRTL/FIRRTLStatements.td, include/circt/Dialect/FIRRTL/FIRRTLVisitors.h, include/circt/Dialect/SV/SVStatements.td, include/circt/Dialect/SV/SVVisitors.h, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/FIRRTL/Export/FIREmitter.cpp, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, lib/Dialect/FIRRTL/Import/FIRTokenKinds.def, lib/Dialect/FIRRTL/Transforms/ExpandWhens.cpp, lib/Dialect/FIRRTL/Transforms/InferWidths.cpp, test/Conversion/ExportVerilog/sv-dialect.mlir, test/Dialect/FIRRTL/emit-basic.mlir, test/Dialect/FIRRTL/expand-whens.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/SV/basic.mlir, test/firtool/print.fir
Add support for fflush operation in FIRRTL and SV dialects. This operation maps to SystemVerilog's $fflush system task, which flushes buffered output to files.
The implementation adds FFlushOp to FIRRTL dialect with clock, condition operands and optional filename with substitutions, adds FFlushOp to SystemVerilog dialect with optional file descriptor, implements lowering from FIRRTL to SystemVerilog, guards fflush with #ifndef SYNTHESIS like other simulation constructs, and adds visitor pattern support in both dialects.
Similar to StopOp in implementation pattern and behavior.
```scala
circuit PrintTest:
public module PrintTest :
input cond : UInt<1>
input a : UInt<8>
node c = UInt<8>(97)
fflush(clock, cond)
fflush(clock, cond, "{{SimulationTime}}%d.txt", a)
``` …
=> [FIRRTL][SV] Add fflush operation

lib/Dialect/FIRRTL/Transforms/Dedup.cpp, test/Dialect/FIRRTL/dedup.mlir
[FIRRTL] Dedup: dedup wires when only one has a symbol
This change allows deduplication of wires when only one of them has an inner symbol.  Before, when hashing an operation we would include the index/id of the inner symbol in the wire's hash, which was done to make sure that local inner symbol references were targeting the same declaration between two modules.  Now, we preprocess the inner symbols inside a module, and with a stable identity of inner symbols we can confidently use the index of an innersymbol when hashing an inner symbol reference.  With this change, we don't have to include the inner symbol on the declaration operation, meaning that if there are no references to the symbol, the fact that an declaration has an inner symbol does not matter at all.
[FIRRTL] Dedup: properly …
=> [FIRRTL] Dedup: dedup wires when only one has a symbol

cmake/modules/CMakeLists.txt
In the current version of CIRCT, the module files in `cmake/modules` are not copied to `CIRCT_CMAKE_DIR`, which causes issues for out-of-tree external projects that depend on CIRCT.
```CMake
find_package(CIRCT REQUIRED CONFIG)
list(APPEND CMAKE_MODULE_PATH ${CIRCT_CMAKE_DIR})
include(AddCIRCT) # Error: include could not find requested file: AddCIRCT
```
This patch ensures that the files in `cmake/modules` are copied into `CIRCT_CMAKE_DIR`.
(It follows the approach used in MLIR’s CMake configuration [here](https://github.com/llvm/llvm-project/blob/af28c9c65a23806a09d7929792df5ed2e9bdf946/mlir/cmake/modules/CMakeLists.txt#L82))
The following code is an example `CMakeLists.txt` file for a standalone out-of-tree project.
```cmake
cmake_minimum_required(VERSION 3.20)
project(myproj) …
```
=> [CMake] Copy the CMake modules to CIRCT_CMAKE_DIR

lib/Dialect/ESI/runtime/cosim_dpi_server/driver.cpp, tools/circt-rtl-sim/driver.cpp
Was failing on link due to Verilator trace library not being found. I think this is because Verilator does not produce this library unless tracing is enabled. Further, clang (by default) doesn't detect that the symbols aren't actually needed (ie it doesn't optimize away the 'if' branch) so it requires them.
=> [verilator driver] Fix for clang

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Dialect/SV/Transforms/SVExtractTestCode.cpp, test/Conversion/FIRRTLToHW/lower-to-hw.mlir, test/Dialect/SV/hw-extract-test-code.mlir, test/firtool/print.fir
Using initilaization for lowering file descriptor casuses probems for ETC so this commit removes initialization and call library function every time fd is necessary
=> [LowerToHW] [ExtractTestCode] Remove FD caching to pass ETC

include/circt/Dialect/Emit/EmitOps.h, lib/Conversion/HWToBTOR2/HWToBTOR2.cpp, lib/Dialect/Emit/EmitDialect.cpp, lib/Dialect/Emit/EmitOpInterfaces.cpp, lib/Dialect/HW/HWOps.cpp, lib/Dialect/Seq/SeqOps.cpp, lib/Dialect/Verif/Transforms/VerifyClockedAssertLike.cpp
I was trying to figure out the dependencies between dialects and these headers created unexpected dependencies between dialects but weren't needed (it seem). I don't know if there is already a dependency diagram between these.
=> Drop unneeded headers

include/circt/Dialect/Verif/Passes.td, include/circt/Dialect/Verif/VerifPasses.h, include/circt/Firtool/Firtool.h, lib/Dialect/Verif/Transforms/CMakeLists.txt, lib/Dialect/Verif/Transforms/LowerSymbolicValues.cpp, lib/Firtool/Firtool.cpp, test/Dialect/Verif/lower-symbolic-values-errors.mlir, test/Dialect/Verif/lower-symbolic-values.mlir, tools/circt-test/circt-test.cpp
Add the `LowerSymbolicValues` pass which converts `verif.symbolic_value` ops either to a black box instance or to a wire declaration with a `(* anyseq *)` attribute. The former is useful since most formal tools have a way of treating black boxes as internal port boundaries, such that black box output ports behave the same as top-level input ports. The latter is useful for interoperability with Yosys which has a custom Verilog attribute "anyseq" that marks a wire declaration as a symbolic value.
=> [Verif] Add pass to lower symbolic values

include/circt/Dialect/Moore/MooreOps.td, include/circt/Dialect/Moore/MooreTypes.td, lib/Conversion/ImportVerilog/Expressions.cpp, test/Conversion/ImportVerilog/basic.sv, test/Dialect/Moore/basic.mlir
Adding a new Op to handle the comparison of unpacked arrays. These changes also help in passing this Chipsalliance [test](https://chipsalliance.github.io/sv-tests-results/?v=circt_verilog+7.4.3+operations-on-unpacked-arrays-equality).
@fabianschuiki, can you please review this? 
Also, I have a doubt: currently, I've added just two predicates for `!moore.uarray` comparisons: `eq` and `ne`. Do we need other predicates similar to the ones in `arith.cmpi`? I understand their use in comparing numbers, but why do we need them for comparing arrays?
=> [Moore] Adding `moore.uarray_cmp` Op

include/circt-c/Firtool/Firtool.h, include/circt/Firtool/Firtool.h, lib/CAPI/Firtool/Firtool.cpp, lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, lib/Firtool/Firtool.cpp, test/CAPI/firtool.c, test/Dialect/FIRRTL/lower-layers-errors.mlir, test/Dialect/FIRRTL/lower-layers.mlir, test/firtool/layer-merge-across-inlined-submodule.fir, test/firtool/layers.fir, test/firtool/lower-layers.fir, tools/firtool/firtool.cpp
Move the `LowerLayers` pass after the `LowerXMR` pass.  To do this, all
passes at the end of the CHIRRTL to Low FIRRTL pipeline are moved after
`LowerXMR`.  This is necessary because the `LowerLayers` pass cannot, at
present, be moved after the passes at the end of the pipeline.
This is done to enable forcing out of layers.  By lowering probes to XMRs,
the layers can be lowered trivially to modules/instances and their XMRs
will now (seemingly) magically just work.  By doing the loweirng in this
way, it avoids ever having to represent an input probe in the FIRRTL
dialect.
A consequence of this is that there are now simplifying
assumptions (preconditions) that can be made about the `LowerLayers` pass:
1. It will never see a number of probe ops because the `LowerXMR` pass has
a postcondition …
=> [firrtl] Move LowerLayers after LowerXMR

tools/circt-verilog/circt-verilog.cpp
Add the usual `--verbose-pass-executions` option to circt-verilog and add the corresponding pass manager instrumentation if the option is set.
=> [circt-verilog] Add --verbose-pass-executions option

lib/Dialect/Calyx/Transforms/AffineParallelUnroll.cpp, test/Dialect/Calyx/affine-parallel-unroll.mlir
This patch supports a more general approach (previously only considering memory accesses with constant indices) to hoist memory reads out from the `scf.execute_region`s under an `affine.parallel` to prevent memory read access conflict.
=> [AffineParallelUnroll] A more general approach to hoist memory reads across `scf.execute_region`s

include/circt/Conversion/SCFToCalyx.h, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/hlstool/commandline.mlir, tools/hlstool/hlstool.cpp
Exposing the `--top-level-function` in `hlstool` for calyx lowering
=> [hlstool] add top-level-function option for calyx flow

lib/Dialect/Calyx/Export/CalyxEmitter.cpp, test/Dialect/Calyx/emit-comb-component.mlir, test/Dialect/Calyx/emit-custom-primitives.mlir, test/Dialect/Calyx/emit-static.mlir, test/Dialect/Calyx/emit.mlir
This patch supports the Calyx emitter to emit negative integer values as bitvectors.
=> [CalyxEmitter] Emit negative integer values as bitvectors

lib/Dialect/RTG/Transforms/CMakeLists.txt, lib/Dialect/RTG/Transforms/ElaborationPass.cpp, test/Dialect/RTG/Transform/elaboration.mlir
Initially the idea was to use the index dialect for arithmetic because it is smaller and simpler (doesn't accept any kind of shape types that we have to error out for, etc.). However, the SCF dialect depends on arith and its canonicalizers produce arith ops. The easiest solution to properly support if-statements and for loops in RTG is thus to just add support for arith ops that can be produced by those canonicalizers to the elaboration pass.
=> [RTG][Elaboration] Arith support

lib/Dialect/Arc/Transforms/SplitLoops.cpp
`isInput` is defined as an unsigned, but is documented as if it's a bool and is only ever written or read as a bool. Guessing this is not deliberate, but let me know if it is!
=> [Arc] Make `isInput` in `ImportedValue` (in SplitLoops) a bool

tools/firtool/firtool.cpp
The default specialization for layers, none, leaves all layers unchanged, and does not disable them as documented.
=> firtool: fix documentation for default layer specialization

lib/Dialect/Calyx/Export/CalyxEmitter.cpp, test/Dialect/Calyx/emit.mlir
This patch emits negative, infinite, and NaN floating point values as bitvectors because Calyx native compiler does not support parsing negative values like `std_float_const(32, -4.2)` nor any non-digits like `std_float_const(32, inf)`.
=> [CalyxEmitter] Negative, infinite, and NaN floating point values emitted as bitvectors

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Expressions.cpp, test/Conversion/ImportVerilog/basic.sv, test/Dialect/Moore/basic.mlir
Adding a new Op to handle operations involving `!moore.string` operands per the rules mentioned in IEEE Std 1800-2012 (page 108).
With the proposed code changes, when one operand is of `!moore.string` type and the other is a string literal, the string literal gets implicitly converted to `!moore.string` type for the comparison. Thus, all the scenarios are covered:
- Both operands are of `!moore.string` type
- One operand is of the `!moore.string` type, and the other is a string literal
- Both operands are string literals (the operator is the same comparison operator as for integral types)
=> [Moore] Adding `moore.string_cmp` Op

lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp, test/firtool/lower-layers.fir
Now that LowerLayers is moved _after_ LowerXMR, there is no need for
LowerXMR to be stripping enabled layers from modules.
This fixes a bug where LowerXMR would only strip layers from modules, but
not instances.  Add a test to lock in the fix.
=> [FIRRTL] Don't strip layers in LowerXMR

lib/Dialect/OM/Evaluator/Evaluator.cpp, unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp
We would previously check if the value corresponding to each operand of the ListConcatOp was finished evaluating, but in the case where the operand is a ReferenceValue, the reference may be done evaluating before while the underlying ListValue is not.
To handle this, a check was added that the result of extractList is fully evaluated, and the evaluation of the ListConcatOp doesn't proceed until that is true.
A small unit test shows this scenario, where there are object references in lists passed as field references to a ListConcatOp.
=> [OM] Ensure every sublist is finished in ListConcatOp evaluation.

lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_simple.mlir, test/Dialect/Calyx/emit.mlir
This patch fixes a bug that `std_fptoint/inttofpFN` didn't write its result to a register.
=> [SCFToCalyx] std_fptoint/inttofpFN should write its result to a register

test/lit.cfg.py
I was getting `llvm-lit: /home/bea/Research/circt-fork/llvm/llvm/utils/lit/lit/llvm/subst.py:126: note: Did not find circt-capi-smtlib-test in /home/bea/Research/circt-fork/build/bin::/home/bea/Research/circt-fork/llvm/build/./bin:/usr/bin` when running check-circt. Looks like that's because there's a test still in the lit config that was removed in #8424. This just drops that from the config.
=> [tests] drop removed SMTLIB CAPI test from lit config

integration_test/circt-synth/comb-lowering-large-lec.mlir, integration_test/circt-synth/comb-lowering-lec.mlir, lib/Conversion/CombToAIG/CombToAIG.cpp, test/Conversion/CombToAIG/comb-to-aig-arith.mlir
An addition to the CombToAIG pass, reducing adders of width greater than 8 to a parallel-prefix adder. Currently implemented two flavours of parallel-prefix reduction tree.
- Width < 8 -> Ripple Carry Adder - minimal area
- 8 <=Width < 32 -> Parallel-Prefix Adder using Kogge-Stone tree - better delay, worse wiring congestion and area than Brent-Kung
- 32 <= Width -> Parallel-Prefix Adder using Brent-Kung tree - better area and wiring congestion, one additional logic level than Kogge-Stone
Verified using circt-lec the correctness of the implementation for adders of width=1,2,...,64.
Included separate integration tests for adders of width 16 and 33. Expanding the test-suite here can quickly lead to timeouts given the increasing complexity of the verification challenge. Worth a discussion on …
=> [circt-synth] Lower comb.add to Parallel-Prefix Adder 

lib/Conversion/LoopScheduleToCalyx/LoopScheduleToCalyx.cpp, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Dialect/AIG/Transforms/LowerWordToBits.cpp, lib/Dialect/Arc/Transforms/ArcCanonicalizer.cpp, lib/Dialect/Calyx/Transforms/AffinePloopUnparallelize.cpp, lib/Dialect/Kanagawa/Transforms/KanagawaPassPipelines.cpp, lib/Reduce/GenericReductions.cpp, lib/Support/Passes.cpp, lib/Transforms/MemoryBanking.cpp, tools/hlstool/hlstool.cpp, tools/kanagawatool/kanagawatool.cpp
The only change was to adapt to new GreedyRewriteConfig APIs.
This is a straightforward mapping after GreedyRewriteConfig was given
a more fluent API, with some minor naming changes applied in:
https://github.com/llvm/llvm-project/commit/0c61b24
=> Bump LLVM to c6c2e21028cadef854cf22f6ecaa5eb9d224b76d.

lib/Dialect/FIRRTL/Transforms/BlackBoxReader.cpp, test/firtool/blackbox-directories.fir
The BlackBoxReaderPass has its own logic for deciding if the output file of a black box module should be under the design, or testbench, based on how it is instantiated. This PR changes this logic, so that if a black-box module is instantiated at all under the effective design, then it will be placed in the design directory. Otherwise, it will be placed in the test bench directory. This reflects the principle that, the testbench may depend on the design, but the design must not depend on the testbench. Before this PR, the logic was: if there are any instances outside of the design, then the black-box module is placed in the testbench.
=> Place black boxes with the design, if instantiated there

include/circt/Dialect/SV/SVStatements.td
Make the sv::IfDefOp use graph regions. There is a distinct "procedural" ifdef op which uses ssa regions. [GraphRegionNoTerminator](https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/IR/RegionKindInterface.td#L57-L62) is a trait-list which implies single-block, no-terminator, and graph regions.
Co-authored-by: @dtzSiFive
=> Make sv::IfDefOp's regions graph-regions

lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, test/Dialect/FIRRTL/lower-layers.mlir, test/firtool/layers.fir
Improve the naming of values captured by the `LowerLayers` pass.  Change
the logic used when a node is created.  Try to use the underlying value if
possible.  If unable to do this, then create a node, but use a saner name
for it.
Fixes #8465.
Fixes #8426.
=> [firrtl] Improve LowerLayer XMR naming

lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, test/Dialect/FIRRTL/SFCTests/directories.fir, test/Dialect/FIRRTL/emit-metadata.mlir
We are porting this metadata from a JSON output to use the FIRRTL object operations. As part of this, we need to distinguish if each object represents a blackbox that is used in the DUT or not, using the same logic to split the blackboxes into two different output files in the old JSON version.
=> [FIRRTL] Update blackbox metadata to include "in DUT" logic.

lib/Dialect/Arc/Transforms/LowerState.cpp, test/Dialect/Arc/lower-state-errors.mlir
There's a part of LowerState that deletes any `hw.module.extern` operations - however, this produces invalid IR if there's an external module whose name is still referenced by e.g. an instance. This just adds a check to made sure that the symbol containing the module's name has no remaining references.
P.S. how come this pass needs to erase all external modules? CC: @fabianschuiki as per git blame
=> [Arc] Don't let LowerState delete instantiated external modules

include/circt/Dialect/Emit/EmitOps.td, include/circt/Dialect/FIRRTL/Passes.td, include/circt/Dialect/SV/SVStatements.td, lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, test/Dialect/FIRRTL/lower-layers.mlir, test/firtool/layers.fir, test/firtool/lower-layers.fir
According to the FIRRTL ABI, we should be emitting a bindfile for each layer × public-module combination. Currently, we only emit one bindfile per layer, which enables the layer for the entire circuit.
This PR updates lower layers to correctly implement the FIRRTL ABI by emitting bindfiles for each public module.
=> [FIRRTL] Emit a bindfile for each public module

lib/Conversion/SCFToCalyx/CMakeLists.txt, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, test/Conversion/SCFToCalyx/convert_simple.mlir, tools/circt-opt/circt-opt.cpp
After discussing with @fabianschuiki over the CIRCT Discord, we both agree that integrating the Math dialect can be helpful to both Calyx and Moore dialect. So I just initiate the integration by bundling with the Calyx use case.
=> [circt-opt][Calyx] Integrate the Math to `circt-opt` and lower `math.sqrt` to Calyx

include/circt/Dialect/Seq/SeqOps.td, lib/Dialect/Seq/CMakeLists.txt, lib/Dialect/Seq/SeqOps.cpp, test/Dialect/Seq/canonicalization.mlir
Add a canonicalizer that removes `comb.mux` and `arith.select` ops on the data input of the register if those ops use the register's enable as select operand. For example:
%0 = comb.mux %enable, %a, %b
seq.compreg.ce %0, %clock, %enable
gets canonicalized to
seq.compreg.ce %a, %clock, %enable
=> [Seq] Remove redundant enable mux in front of compreg.ce

lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, test/firtool/lower-layers.fir
This reverts a suggestion [[1]] I made on #8458.  This changes
the (undocumented) ABI of FIRRTL layers to _not_ include any directory
information in the `` `include `` directives used to enable layers.  The
reason for this is that using the full paths (relative to the root output
directory) prevents rearranaging directories after compilation.
The downside to this is that users must include more `+incdir` command
line options to include _all_ directories in a design.  However, I think
this is reasonable.
I do think that we can roll this back to use the original behavior in the
future in a backwards-compatible way.  I.e., making the change from not
including the full path to including the full path won't break any
downstream tools as these will just be including _too many_ `+incdir`s.
[1]: …
=> [firrtl] Drop directory in layer include files

lib/Conversion/SimToSV/SimToSV.cpp, test/Conversion/SimToSV/plusargs.mlir, test/firtool/plusargs.fir
This changes the lowering of plusargs to make sure that the X-squashing === is underneath the !SYNTHESIS block, which fixes a warning produced by synthesis tools.
=> SimToSV: Keep plusargs non-synth === under !SYNTHESIS block

lib/Dialect/ESI/ESIServices.cpp, lib/Dialect/ESI/Passes/ESILowerPhysical.cpp, test/Dialect/ESI/lowering.mlir
Adds signal conversion capabilities to `esi.buffer`. This is somewhat temporary as the pipeline of `esi.stage` operations will (shortly) be replaced by feed forward registers and a runout FIFO.
=> [ESI] Support for FIFO<-->ValidReady conversion in BufferOp

lib/Dialect/ESI/runtime/CMakeLists.txt, lib/Dialect/ESI/runtime/cosim_dpi_server/esi-cosim.py, lib/Dialect/ESI/runtime/cpp/cmake/esiaccelConfig.cmake
- Updates the IMPORTED_LOCATION for the ESICppRuntime shared library.
- esi-cosim.py:
- Adds logging of compile commands and introduces warning suppression flags in compile commands.
- Slow down the simulation to one tick per millisecond if the DEBUG_PERIOD environment variable is not set if debug mode is used.
- Adds the inclusion of the Engines header to the list of runtime headers.
=> [ESI][Runtime] Improvements / fixes to utilities/build

include/circt/Support/InstanceGraph.h, lib/Support/InstanceGraph.cpp, unittests/Dialect/HW/InstancePathTest.cpp
This commit adds infrastructure for caching relative instance paths between modules in the InstanceGraph. It adds a relativePathsCache field to InstancePathCache to store paths between arbitrary module pairs.
=> [Support] Add relative path caching to InstancePathCache

lib/Transforms/HierarchicalRunner.cpp, test/Transforms/hierarchical_runner.mlir
This avoids crash due to passes being scheduled on HWMouleExtern op.
=> [Transforms][HierarchicalRunner] Run passes only on HWModuleOp

lib/Dialect/ESI/runtime/CMakeLists.txt, lib/Dialect/ESI/runtime/python/esiaccel/esiCppAccel.cpp
Linking `-pthread` as private doesn't seem to do it for my build (w/ `ESI_STATIC_RUNTIME`). Switched to public, and things work.
=> [ESI] Add missing include and change link type

include/circt/Tools/circt-lec/Passes.h, include/circt/Tools/circt-lec/Passes.td, lib/Conversion/VerifToSMT/VerifToSMT.cpp, lib/Tools/circt-lec/ConstructLEC.cpp, test/Conversion/VerifToSMT/verif-to-smt.mlir, test/Tools/circt-lec/construct-lec.mlir, test/Tools/circt-lec/generate-smtlib.mlir, tools/circt-lec/CMakeLists.txt, tools/circt-lec/circt-lec.cpp
To reuse the translate to smtlib MLIR backend and enable benchmark generation for alternative smt solvers, need to lower to and `smt.solver` which does not return any results. To handle this make the LLVM reporting code insertion optional and disable when emitting smtlib. Also in verif to smt lowering only return a result from the solver if the result will be used.
=> [circt-lec] Implement emit-smtlib functionality for circt-lec

include/circt/Dialect/HW/CMakeLists.txt, include/circt/Dialect/HW/HWAggregates.td, include/circt/Dialect/HW/HWCanonicalization.td, lib/Dialect/HW/CMakeLists.txt, lib/Dialect/HW/HWOps.cpp, test/Dialect/HW/basic.mlir, test/Dialect/HW/canonicalization.mlir, test/Dialect/HW/errors.mlir
Add a new `hw.array_inject` operation which updates a single element in an array value and returns the updated array. This fills in a gap where structs had a `struct_extract` and `struct_inject` op available, but arrays only had `array_get` without the complementary `array_inject`.
This commit also adds a `HWCanonicalization.td` file for any canonicalization rewrite patterns on HW ops. It is overkill for just the new `array_inject` operation, but my hope is that we'll fill this in as time progresses and we may even be able to migrate some existing patterns from C++ to the declarative format. The `ArithCanonicalization.td` file has a lot of nice inspiration.
In the future we may want to add patterns that can fold injects directly into an `array_create` operation, and patterns that reorder …
=> [HW] Add array element injection op

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/firtool/print.fir
Some simulators silently return 0 when $fopen failed to open a file. This PR changes the FileDescriptor::get to emit $error explicitly.
=> [LowerToHW] Emit an error when $fopen failed for FD lowering

lib/Dialect/Arc/Transforms/InlineArcs.cpp, test/Dialect/Arc/inline-arcs.mlir
Hit a very niche breaking case in InlineArcs in my optimization travels - currently if the inliner inlines `arcA` which calls `arcB`, it will only acknowledge the additional user of `arcB` if `arcA` is inlined into another define. Most of the time this flies under the radar, however, if `arcB` is prevented from being inlined by another user that is eventually deleted, the inliner will think that `arcB` has no users even though it still has a call where `arcA` was inlined. Breaking example added as a filecheck test.
=> [Arc] Fix arc inliner deleting arcs that still have calls

lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp, test/Dialect/FIRRTL/imconstprop.mlir
Mark `DPICallIntrinsicOp`s as over-defined in the FIRRTL IMConstProp pass to prevent connections to the call's result from being removed. 
Running this Chisel 7 snippet through `firtool`
```Scala
class DPITest extends Module {
val out = IO(Output(Bool()))
val bar = Wire(Bool())
val foo = RawClockedNonVoidFunctionCall("foo", Bool())(this.clock, true.B, bar)
bar := RawClockedNonVoidFunctionCall("bar", Bool())(this.clock, true.B, foo)
out := bar
}
```
incorrectly produces
```SystemVerilog
[...]
always @(posedge clock) begin
foo(1'bz, _foo_0); 
bar(_GEN, _bar_0);  
_GEN_0 <= _bar_0; 
end // always @(posedge)
assign out = 1'bz; 
endmodule
```
The DPI call intrinsics ale initialized as `Unknown` in the constant propagation lattice and due to their cyclic dependency, this never gets resolved. …
=> [FIRRTL][IMCP] Mark DPI calls as overdefined

lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, test/Dialect/FIRRTL/lower-layers.mlir
When emitting bindfiles for a module, that bindfile will include the bindfiles of any module instantiated directly under it.
If a module is instantiated multiple times, we'll emit duplicate include statements. This PR modifies the bindfile creation code to avoid emitting duplicate include statements.
Fixes: #8519
=> [FIRRTL] LowerLayers: do not emit duplicate bindfile includes

include/circt-c/Dialect/HW.h, lib/CAPI/Dialect/HW.cpp
This PR adds a new HW C-API function `hwModuleTypeGetPort` for getting the port info at a specific index from module.
=> [HW][CAPI] Add a function for getting port info from module

docs/Dialects/Pipeline/RationalePipeline.md, include/circt/Dialect/Pipeline/PipelineOps.td, integration_test/Dialect/Pipeline/nonstallable/test1/nonstallable_test1.mlir, integration_test/Dialect/Pipeline/nonstallable/test2/nonstallable_test2.mlir, integration_test/Dialect/Pipeline/simple/simple.mlir, integration_test/Dialect/Pipeline/stall/stallTest.mlir, lib/Dialect/Pipeline/PipelineOps.cpp, lib/Dialect/Pipeline/Transforms/ExplicitRegs.cpp, lib/Dialect/Pipeline/Transforms/ScheduleLinearPipeline.cpp, test/Dialect/Kanagawa/Transforms/schedule_pipeline.mlir, test/Dialect/Pipeline/Transforms/explicit-regs.mlir, test/Dialect/Pipeline/Transforms/schedule-linear-pipeline.mlir, test/Dialect/Pipeline/errors.mlir, test/Dialect/Pipeline/round-trip.mlir
In anticipation of the upcoming removal of the cross-block canonicalization guards in the `comb` canonicalizers, we're introducing a `pipeline.src` operation to the pipeline dialect.
This operation is intended to alleviate the case of unintentional cross-block canonicalization when a scheduled pipeline has not yet had its registers materialized.
This operation, `pipeline.src`, effectively acts as a canonicalization boundary, creating an in-block reference to a value that is defined in a predecessor block.
This means that we can keep our existing structure for unmaterialized, scheduled pipelines - values can be referenced from _any_ predecessor op through the `pipeline.src` operation, which still allows for said values to be easily moved across stages in a retiming scenario.
Upon register …
=> [Pipeline] Add cross-block canonicalization break op

lib/Dialect/LLHD/Transforms/Deseq.cpp, test/Dialect/LLHD/Transforms/deseq.mlir
Fix an issue in the Deseq pass where operations like `comb.icmp ne %false, %false` get mistakenly marked as poison. This was due to a missing check whether the operands are constant true or false. This cause any comb op not supported in Deseq's truth table mapping to be mistakenly poisoned if the op contained any `i1` operands that were constant true or false.
Fixes #8512
=> [LLHD] Fix deseq poisoning comb ops that don't depend on triggers

include/circt/Support/Naming.h, lib/Conversion/CombToAIG/CombToAIG.cpp, lib/Dialect/Comb/CombFolds.cpp, lib/Support/Naming.cpp, test/Conversion/CombToAIG/comb-to-aig-arith.mlir
Move name propagation helpers from CombFolds to Support/Naming.h and rename them to better reflect their purpose of propagating "sv.namehint" attributes. Update all callers. No functional change for Comb.
=> [Comb][AIG] Move rewriter helpers to support and use it for AIG

docs/Dialects/FIRRTL/RationaleFIRRTL.md, include/circt/Dialect/FIRRTL/AnnotationDetails.h, lib/Dialect/FIRRTL/Transforms/InferResets.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, lib/Dialect/FIRRTL/Transforms/MemToRegOfVec.cpp, test/Dialect/FIRRTL/infer-resets.mlir, test/Dialect/FIRRTL/mem-to-reg-of-vec.mlir
Drop an annotation-backed feature that had no users from the FIRRTL:
ExcludeMemFromMemToRegOfVec.  I deleted this internally as it had no
users.  This appears to have been created when the original pass was
ported from the SFC.
=> [FIRRTL] Drop ExcludeMemFromMemToRegOfVec, unused

include/circt/Support/UnusedOpPruner.h, lib/Dialect/LLHD/Transforms/Mem2Reg.cpp
Factor out the tracking and pruning of unused, side effect free ops from the Mem2Reg pass into a new `UnusedOpPruner` utility. This just wraps a set of ops and provides helper functions to mark ops, values, and value ranges as to be pruned if they end up being unused at a later point.
This helps passes clean up after themselves if they remove ops that may render other parts of the IR unused. I'm working on an LLHD pass that will benefit from this utility.
=> [Support] Factor out unused op pruning from LLHD Mem2Reg; NFC

.github/workflows/buildAndTest.yml, .github/workflows/nightlyIntegrationTests.yml, .github/workflows/shortIntegrationTests.yml
Making a separate pull request with CI changes per the request in https://github.com/llvm/circt/pull/7792#discussion_r1884662217.
Bump to images based on ubuntu 24 images.
Some of the features used by `slang` requires newer default compiler versions than what's provided by the current images, as discussed in https://github.com/llvm/circt/pull/7792.
=> [CI] Bump docker images

lib/Dialect/RTG/Transforms/ElaborationPass.cpp, test/Dialect/RTG/Transform/elaboration.mlir
Currently we special-case randomized sequences. This PR changes them to be values with identity. This has the advantage that we don't need to generate a new, unique name for each randomizes sequence from the start, i.e., if we randomize 1000 sequences, put them in a set and only select 1 at random and embed it, then we only need to generate 1 name after this PR instead of 1000. This name uniquification made up a considerable chunk of runtime in some previous profiling. On the negative side, we now pass randomized sequence values as block arguments to nested sequences which makes life a bit more difficult for sequence inlining. Not sure if avoiding this is worth the special-casing.
=> [RTG][Elaboration] Treat randomized sequences as regular identity values

include/circt/Dialect/LLHD/Transforms/LLHDPasses.td, lib/Dialect/LLHD/Transforms/CMakeLists.txt, lib/Dialect/LLHD/Transforms/CombineDrives.cpp, test/Dialect/LLHD/Transforms/combine-drives.mlir
Add the *CombineDrives* LLHD pass. If multiple drives assign all fields of an aggregate signal, merge the drives into a single drive of the whole aggregate value. This is equivalent to replacing
a[0] = u;
a[1] = v;
with
a = {v, u};
Performing this replacement is an important step to eliminate signal projection operations like `llhd.sig.extract`, `llhd.sig.array_slice`, `llhd.sig.array_get`, and `llhd.sig.struct_extract`.
Real-world Verilog inputs will often declare struct, array, or bit vector signals and then separately assign its fields, elements, or bit slices in multiple concurrent assign statements. To simplify working with the IR in optimizations and later passes, we would much rather have a single SSA value be driven onto a signal. This makes it clear that the signal is uniquely …
=> [LLHD] Add pass to combine drives to aggregate signals

lib/Conversion/CombToSMT/CombToSMT.cpp
Fixes #8539
The issue was that the func dialect was not marked legal in the conversion target, but CombToSMT is set up as a superset of the HWToSMT conversion.
=> [CombToSMT] Fix conversion target

docs/Dialects/FIRRTL/FIRRTLAnnotations.md, lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp, test/Dialect/FIRRTL/inject-dut-hierarchy.mlir
Add a new field to the `InjectDUTHierarchyAnnotation` called `moveDut`.
This is used to control the placement of the `MarkDUTAnnotation` after the
pass runs.  This is done becasue we are exploring an internal flow which
wants to change the behavior of this pass to work this way.  We would like
to make this the default behavior, but will initially guard it with this
annotaiton option.
This patch is backwards compatible.  It will default to the old behavior
if it does not see the new field in the annotation.
This makes no changes to the placement of _other_ annotations.  I.e., if
there are annotations that were originally on the DUT, then those will
still be moved.  I went back and forth on this.  However, it shouldn't
really matter where _other_ annotations are nor should it matter where …
=> [FIRRTL] Add moveDut field for inject DUT hier

frontends/PyRTG/src/pyrtg/tests.py, frontends/PyRTG/test/basic.mlir, frontends/PyRTG/test/basic.py, include/circt/Dialect/RTG/IR/RTGOps.td, include/circt/Dialect/RTG/Transforms/RTGPasses.td, integration_test/Bindings/Python/dialects/rtg.py, integration_test/Bindings/Python/rtg_pipeline.py, lib/Dialect/RTG/IR/RTGOps.cpp, lib/Dialect/RTG/Transforms/ElaborationPass.cpp, test/CAPI/rtg-pipelines.c, test/Dialect/RTG/IR/basic.mlir, test/Dialect/RTG/IR/errors.mlir, test/Dialect/RTG/Transform/elaboration.mlir
* Tests can now carry a string identifying the original test name because a test can be cloned to test multiple targets. This is useful for result reporting
* Tests can now specify a fixed target. Before elaboration it acts as a restriction to only be elaborated against that target, after elaboration it specifies for which target the test was elaborated.
* The body of a target is not copied into the tests anymore. This allows us to materialize operations that are only legal in targets and keep them until later in the pipeline.
* The test <-> target matching now supports a kind of 'subtyping'
* Remove the special casing for tests without requirements.
=> [RTG][Elaboration] Improve how tests are matched with targets

include/circt/Dialect/RTG/IR/RTGTypes.td, include/circt/Dialect/RTG/Transforms/RTGPasses.td, include/circt/Dialect/RTGTest/IR/RTGTestOps.td, lib/Dialect/RTG/Transforms/CMakeLists.txt, lib/Dialect/RTG/Transforms/ElaborationPass.cpp, lib/Dialect/RTG/Transforms/MemoryAllocationPass.cpp, test/Dialect/RTG/Transform/elaboration.mlir, test/Dialect/RTG/Transform/emit-rtg-isa-assembly-labels.mlir, test/Dialect/RTG/Transform/emit-rtg-isa-assembly.mlir, test/Dialect/RTG/Transform/memory-allocation.mlir
This is a basic version of the pass and will be improved upon in later PRs (refer to memories via labels, assign the same/overlapping address range to multiple allocations if their liveness doesn't overlap, etc.)
Also make sure memories are properly retained during elaboration and add a load address instruction to rtgtest.
=> [RTG] Add MemoryAllocation pass

include/circt/Dialect/AIG/Analysis/LongestPathAnalysis.h, lib/Dialect/AIG/Analysis/LongestPathAnalysis.cpp, test/Dialect/AIG/longest-paths.mlir, test/circt-synth/path-e2e.mlir, unittests/Dialect/AIG/CMakeLists.txt, unittests/Dialect/AIG/LongestPathTest.cpp, unittests/Dialect/CMakeLists.txt
This patch implements the LongestPathAnalysis for the AIG dialect, which calculates the maximum delay through combinational paths in a circuit where each AIG operation has a unit delay. The implementation:
- Adds the core analysis infrastructure with three main components:
- Context: Thread-safe interface to access analysis results across modules
- LocalVisitor: Per-module visitor that computes paths within module boundaries
- Impl: Top-level implementation that orchestrates analysis across hierarchies
- Implements hierarchical analysis that works across module boundaries
- Supports parallel execution for improved performance on large designs
- Provides both closed paths (register-to-register) and open paths analysis
- Includes debug point tracing for detailed path information
- Adds a …
=> [AIG] Add LongestPathAnalysis implementation

lib/Dialect/FIRRTL/Transforms/Dedup.cpp, test/Dialect/FIRRTL/dedup-errors.mlir
We upgraded dedup to be able to merge modules where one is public, as long as the other modules were private.  The MustDedup error message was not updated to handle this change in behaviour, and still assumed that it was impossible to merge any public module with other modules.  This changes MustDedup to only detect this as a difference if neither module is marked as private.
=> [FIRRTL] Dedup: MustDedup support merging of pub+priv modules

lib/Dialect/FIRRTL/Transforms/ExtractInstances.cpp, lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/extract-instances.mlir, test/Dialect/FIRRTL/inject-dut-hierarchy.mlir, test/firtool/extract-instances.fir
Preserve the controlling annotation for FIRRTL's hierarchy injection pass.
This will be used to augment the behavior of FIRRTL's instance extraction
pass.  Note: this removes the idempotent property of hierarchy injection.
Modify newly added behavior related to the `moveDut` parameter added to
`InjectDUTHierarchyAnnotation` [[1]].  Change the behavior so, when the
`moveDut` parameter in the newly preserved annotation, instances will be
extracted one level above the newly _moved_ DUT.
This adds tech debt as it repurposes instance extraction to allow for both
hierarchy injection and extraction beyond the DUT.  Previously, these were
intended to be mutually exclusive.
The tech debt is acceptable because @mwachs5 is planning to remove this
flow entirely.
[1]: …
=> [FIRRTL] Extract instances above DUT w/ moveDut

include/circt/Dialect/SV/SVDialect.h, lib/Conversion/ExportVerilog/LegalizeNames.cpp, lib/Dialect/SV/SVDialect.cpp, test/Conversion/ExportVerilog/name-legalize.mlir
This PR updates the name validation mechanism in the SV dialect, mainly modifying the `isNameValid` function in the `SVDialect.h` and `LegalizeNames.cpp` files to support escaped name checking in accordance with the IEEE standard.
1. **IEEE Standard Compliance**: The original name validation function lacks the correct handling of escaped identifiers in the IEEE Verilog standard. The IEEE 1800 standard allows backslash-escaped identifiers (such as `\escaped_name`), which are common in Verilog code generation.
2. **Function Enhancement**: By adding a new `allowEscapedName` parameter, the `isNameValid` function can decide whether to allow escaped names based on the context, providing a more flexible name validation strategy.
3. **Backward compatibility**: The modification maintains …
=> [SV] Enhanced name validation: support IEEE standard escape name checking

include/circt/Dialect/HW/HWStructure.td
Not sure if I could just push this to main, made a tiny PR just in case.
Added missing code formatting in docs that made the example hard to parse on the website.
=> [Docs][HW] Missing formatting in docs

lib/Dialect/Seq/SeqOps.cpp, test/Dialect/Seq/canonicalization.mlir
This commit implements FirMemOp canonicalization that eliminates dead memories:
- Read-only memories are replaced with constant 0
Previously only write-only memory was handled. Also it fixes an issue that write port was eliminated even when the memory has an inner symbol.
=> [Seq] Add a canonicalization to remove read-only memory

test/circt-verilog/registers.sv, tools/circt-verilog/circt-verilog.cpp
Enable the LLHD passes that have been updated in the past few months in circt-verilog's pass pipeline. This contains revised versions of the Mem2Reg, Deseq, and LowerProcesses passes, alongside a new HoistSignals pass and the CombineDrives pass factored out of Sig2Reg.
This also disables the SROA pass on LLHD, moving it to only operate on Moore modules. @maerhart has been looking into fixing an upstream bug in SROA when it's used on operations in graph regions. Until that is fixed, we can just skip SROA on HW modules for now.
Also add an end-to-end test for circt-verilog to ensure that the basic forms of registers get detected and lowered properly.
=> [circt-verilog] Add updated LLHD passes to the pipeline

include/circt/Dialect/AIG/AIGPasses.td, integration_test/circt-synth/abc.mlir, integration_test/lit.cfg.py, lib/Dialect/AIG/Transforms/AIGERRunner.cpp, lib/Dialect/AIG/Transforms/CMakeLists.txt, test/Dialect/AIG/aiger-runner-error.mlir, test/Dialect/AIG/aiger-runner.mlir, tools/circt-synth/circt-synth.cpp
This commit introduces a new infrastructure for running external logic synthesis tools (ABC, Yosys, etc.) on AIG modules through AIGER format export/import.
The implementation provides two new passes, AIGERRunner and ABCRunner, that export modules to AIGER format, run external solvers, and import optimized results back to MLIR. The system includes sophisticated multi-bit value handling with automatic decomposition during export and reconstruction during import. The pass integrates seamlessly with the circt-synth tool to support ABC optimization commands.
The core Converter class tracks bit-level mappings between MLIR and AIGER representations, enabling accurate reconstruction of multi-bit values after optimization. String placeholder replacement provides flexible solver command …
=> [AIG] Add AIGER runner passes for external logic solver integration

.github/workflows/nightlyIntegrationTests.yml
This patch modifies the nightly integration tests workflow to only use ccache when the build type is Release. This helps optimize CI resources by avoiding unnecessary caching for debug builds, which have shown cache hit rates of less than 0.5% (shown below). Cache for Nightly debug build actually consumes 4~5 GB of cache storage (I don't know why it takes so much even when max-size=300MB is specified). With this change cache for window and short-integration should be able to survive for a few days. 
https://github.com/llvm/circt/actions/runs/15732253051/job/44335935098
```
/usr/bin/ccache -s
Cacheable calls:   3399 / 4001 (84.9[5](https://github.com/llvm/circt/actions/runs/15732253051/job/44335935098#step:14:5)%)
Hits:              14 / 3399 ( 0.41%)
Direct:          11 /   14 (78.57%) …
```
=> [CI] Only use ccache for Release builds in nightly integration tests

include/circt/Dialect/Kanagawa/KanagawaPasses.h, include/circt/Dialect/Kanagawa/KanagawaPasses.td, lib/Dialect/Kanagawa/Transforms/CMakeLists.txt, lib/Dialect/Kanagawa/Transforms/KanagawaCleanSelfdrivers.cpp, lib/Dialect/Kanagawa/Transforms/KanagawaEliminateRedundantOps.cpp, lib/Dialect/Kanagawa/Transforms/KanagawaPassPipelines.cpp, test/Dialect/Kanagawa/Transforms/eliminate_redundant_ops.mlir, tools/kanagawatool/CMakeLists.txt, tools/kanagawatool/kanagawatool.cpp
Running CSE on a whole design is neither necessary nor advisable. It forces all the dialects used to support CSE but at least one (which we use) has issues with it. So we add a PR which targets redundant operations in the `kanagawa` dialect which passes assume to be non-redundant.
Also updates `kanagawatool` to add new passes which are now necessary.
=> [Kanagawa] Replace CSE with specialized pass

include/circt/Dialect/LLHD/Transforms/LLHDPasses.td, lib/Dialect/LLHD/Transforms/CMakeLists.txt, lib/Dialect/LLHD/Transforms/RemoveControlFlow.cpp, test/Dialect/LLHD/Transforms/remove-control-flow.mlir, tools/circt-verilog/circt-verilog.cpp
Add the *RemoveControlFlow* pass to the LLHD dialect. It operates on all `llhd.combinational` ops in an `hw.module` if the op has no side-effects and the control flow is acyclic. The pass moves all operations in the `lhld.combinational` op body into its entry block and inserts `comb.mux` ops to resolve block arguments. All blocks besides the entry block are then removed.
A future loop unrolling pass would get rid of any cycles in the control flow, such that this pass can then pick up the remaining control flow lowering.
This is an important pass in lowering behavioral circuit descriptions, such as `always` blocks in Verilog or `process`es in VHDL, to a set of equivalent Comb dialect ops in the module body.
Shoutout to @maerhart for doing all the heavy lifting for this pass on his …
=> [LLHD] Add pass to lower acyclic control flow to mux ops

lib/Dialect/Comb/CombFolds.cpp, test/Dialect/Calyx/remove-comb-groups.mlir, test/Dialect/Seq/hw-memsim.mlir
Now that #8517 has landed, re-enable the canonicalizers and constant folders for `comb.and`, `comb.or`, and `comb.xor` that have operands defined in different blocks.
=> [Comb] Enable cross-block folds on and/or/xor

lib/Dialect/Comb/CombFolds.cpp
Re-enable the canonicalizers and constant folders for `comb.replicate`, `comb.parity`, `comb.shl`, `comb.shru`, `comb.shrs`, `comb.mux`, and `comb.icmp` that have operands defined in different blocks.
=> [Comb] Enable cross-block folds on replicate/parity/shl/shr/mux/icmp

include/circt/Firtool/Firtool.h, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/SFCTests/data-taps.fir, test/firtool/name-preservation.fir
This adds EliminateWiresPass before IMCP
=> [firtool] Enable WireElimination pass

lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp, test/Dialect/FIRRTL/inject-dut-hierarchy.mlir, test/firtool/extract-instances.fir
Change FIRRTL's inject-dut-hier pass to move all annotations onto the
wrapper [^1] when in `moveDut=true` mode.  Previously, this would only move
the `MarkDUTAnnotation`.  This fixes an internal issue where Object Model
paths were not being updated when using this pass in `moveDut=true` mode.
[^1]: This is using the terminology of the pass which views this as taking
all the logic inside the original DUT and shoving it into a wrapper
instantiated inside the DUT.  When in `moveDut=true` mode, it is more
natural to think of the pass as creating a wrapper around the original
DUT.  However, to adopt this alternative terminology would be modal.
I.e., "wrapper" would mean something different when in `movedDut=true`
mode which would be confusing.
Other NFC chagnes:
1. Refactor the …
=> [FIRRTL] Move all annotations in inject-dut-hier

include/circt/Dialect/AIG/AIGPasses.td, lib/Dialect/AIG/Transforms/AIGERRunner.cpp, test/Dialect/AIG/aiger-runner-error.mlir, tools/circt-synth/circt-synth.cpp
This commit refactors and adds an option to AIGERRunner. 
1. Create ExternalSolverPass base class to reduce code duplication between AIGERRunner and ABCRunner passes, providing shared options and dependent dialects through inheritance.
2. Add --ignore-abc-failures command line option to circt-synth tool to enable continue-on-failure behavior for ABC optimization. Currently the pass fails if there are multiple clocks so it's convenient to just skip them.
=> [AIG][AIGERRunner] Refactor AIG external solver passes and add continueOnFailure option

frontends/PyCDE/src/pycde/common.py, frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/src/pycde/system.py, frontends/PyCDE/test/test_kanagawa.py
This PR adds support for importing Kanagawa IR into PyCDE and improves the overall pass management and proxy caching in the system.
- Added a new test file for Kanagawa IR import and lowering.
- Updated the System and _OpCache functionality to change type hints and weak reference handling.
- Revised the imported module creation and pass-phase execution logic.
=> [PyCDE] Support for importing Kanagawa

frontends/PyCDE/src/pycde/module.py, frontends/PyCDE/src/pycde/system.py
This pull request improves the MLIR import functionality in PyCDE by
supporting custom op conversion during module import. Key changes
include:
- Adding new parameters (module_str, file, importer, debug) to the
import_mlir function for enhanced flexibility.
- Modifying the lowering passes list with new entries for Kanagawa
dialect lowering.
- Updating import_hw_module to accept an optional builder_type parameter
for custom module building.
=> [PyCDE] Support custom op conversion on import

lib/Dialect/FIRRTL/FIRRTLFolds.cpp, test/Dialect/FIRRTL/canonicalization.mlir
This commit enhances the cat operation canonicalization in FIRRTLFolds.cpp to properly handle cases where operands have mixed signed and unsigned types.
The implementation now tracks whether signed and unsigned operands exist during cat flattening. When mixed types are present, it adds explicit casting of signed values to unsigned using AsUIntPrimOp. Single operand cases are also properly cast to unsigned if needed.
Fix #8618
=> [FIRRTL] Fix cat canonicalization to handle mixed signed/unsigned operands

lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp
Fix a nightly failure observed with gcc release builds due to a cast of an
interface to an operation.  This is known to be problematic.
Testing via manual trigger here: https://github.com/llvm/circt/actions/runs/15947527423
This is intended to fix this failure: https://github.com/llvm/circt/actions/runs/15943909376/job/44975510792#step:6:6782
=> [FIRRTL] Avoid interface cast in inject-dut-hier

include/circt/Support/InstanceGraph.h, lib/Support/InstanceGraph.cpp, unittests/Dialect/HW/InstancePathTest.cpp
Add a new method to InstancePathCache that concatenates two instance paths. This complements the existing prependInstance and appendInstance methods, providing a more complete API for manipulating instance paths.
=> [Support] Add concatPath method to InstancePathCache

include/circt/Conversion/Passes.td, lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/MooreToCore/basic.mlir
This pull request addresses part of #8476. I have removed the for-loop logic from the signed integer conversion and replaced it directly with `math.ipowi` from MLIR's Math dialect, which handles the exponentiation logic for us. I also included the `mlir.math` dialect header in the MooreToCore.cpp conversion file.
I have some concerns, however this might be related to my lack of experience with the codebase (and admittedly MLIR as a whole).
- The code builds, however the tests (test/Conversion/MooreToCore/basic.mlir) fail. This may be due to a type discrepancy in what the original logic returns and what `math.ipowi` returns.
-  If there is a type discrepancy, I am unsure if I was supposed to maybe convert the result back to the original type, and also not sure of how to change the tests to …
=> [MooreToCore] Lower exponentiation to math.ipowi (PowSOpConversion)

lib/Dialect/LLHD/Transforms/Sig2RegPass.cpp, test/Dialect/LLHD/Transforms/sig2reg.mlir
Extend the Sig2Reg LLHD pass to completely remove a signal and all its associated drives if the signal is only driven, but never probe or used in any other way.
=> [LLHD] Remove drive-only signals in Sig2Reg pass

lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/advanced-layer-sink.mlir, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/layers.mlir
An old verifier for the RWPRobe op asserted that the target was under at least the same conditions as the probe op itself, ensuring that we could not create a forceable probe from within a layer, to something outside of that layer. This verifier helped ensure that "enabling a layer cannot change the behaviour of the design". We no longer have nor want this restriction, so this PR is removing the verifier.
This fixes an issue with advanced layer sink, where ALS will sink rwprobe ops into a layer and trigger this verification check.
Fixes: #8640
=> [FIRRTL] Allow layers to RWProbe into the design

include/circt/Dialect/HW/HWVisitors.h, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/ExportVerilog/PrepareForEmission.cpp, test/Conversion/ExportVerilog/disallow-local-vars.mlir, test/Conversion/ExportVerilog/hw-dialect.mlir
Extend the PrepareForEmission part of ExportVerilog to lower `hw.array_inject` into a bit of procedural Verilog code that overwrites the injected array index:
```systemverilog
// %b = hw.array_inject %a[%i], %v
logic [N-1:0] b;
b = a;
b[i] = v;
end
```
Unfortunately assignment patterns like `'{0: x, 1: y, 2: z}` only support constant expressions for the array indices. The only options to mutate a single array entry that I am aware of are the procedural style implement in this commit, and creating a separate mux/ternary op for each index separately, which feels like total overkill.
=> [ExportVerilog] Add support for hw.array_inject

include/circt/Dialect/AIG/AIGPasses.td, include/circt/Dialect/AIG/Analysis/LongestPathAnalysis.h, lib/Dialect/AIG/Analysis/LongestPathAnalysis.cpp, lib/Dialect/AIG/Analysis/PrintLongestPathAnalysis.cpp, test/Dialect/AIG/longest-paths-report.mlir, test/circt-synth/path-e2e.mlir, tools/circt-synth/circt-synth.cpp
This patch improves the AIG longest path analysis pass with:
- Detailed timing level statistics showing delay distribution
- Critical path details for top K fanout points
- Path history with intermediate debug points
- JSON output format option for machine-readable results
- Improved documentation and command-line options
The enhanced analysis provides more comprehensive timing information for debugging and optimizing AIG circuits, with both human-readable and machine-parseable output formats. Human-readable output is align with ABC's print_level output to make it easy to compare results with ABC.
=> [AIG] Enhance longest path analysis with detailed timing statistics and JSON output

include/circt-c/Dialect/AIG.h, lib/CAPI/Dialect/AIG.cpp, test/CAPI/CMakeLists.txt, test/CAPI/aig.c, test/CMakeLists.txt, test/lit.cfg.py
This commit introduces C API bindings for AIG LongestPathAnalysis and LongestPathCollection, enabling longest path analysis of AIG circuits from C and other languages.
The API uses JSON serialization for path data exchange, providing a stable interface while the underlying data structures evolve. Paths are automatically sorted by delay in descending order for efficient critical path analysis.
=> [AIG][CAPI] Add C API for LongestPathAnalysis

frontends/PyCDE/integration_test/test_software/esi_ram.py, frontends/PyCDE/src/pycde/esi.py, frontends/PyCDE/test/test_esi.py, integration_test/Dialect/ESI/runtime/loopback.mlir, lib/Dialect/ESI/ESIServices.cpp, lib/Dialect/ESI/ESIStdServices.cpp, test/Dialect/ESI/services.mlir, test/Dialect/Handshake/lower-extmem-esi.mlir
Using signless ints as the address was just wrong. It was probably done to avoid incomplete lowerings, which have been addressed.
=> [ESI] Make RAM delarations' addresses unsigned

include/circt/Dialect/LLHD/Transforms/LLHDPasses.td, lib/Dialect/LLHD/Transforms/CMakeLists.txt, lib/Dialect/LLHD/Transforms/UnrollLoops.cpp, test/Dialect/LLHD/Transforms/unroll-loops.mlir, tools/circt-verilog/circt-verilog.cpp
Add an LLHD pass that unrolls loops with statically-known bounds.
The pass computes the dominance info for `llhd.combinational` ops, finds loop back-edges by looking for blocks that branch back to blocks that dominate them, which yields initial *loop head* and *back-edge* pairs. Based on these the pass populates a data structure with loop metadata, including the blocks in the loop body, exit control flow edges, the exit condition, induction variable, and loop bounds. After gathering this information, the loop body is simply stamped out muliple times, the few relevant control flow edges are adjusted, and a rough cleanup of unused blocks and values is performed.
The current implementation of the pass is *very* conservative. The loops are required to have very simple control flow, and the …
=> [LLHD] Add loop unrolling pass

test/circt-synth/basic.mlir, tools/circt-synth/CMakeLists.txt, tools/circt-synth/circt-synth.cpp
This PR adds `emit-bytecode` option to circt-synth following firtool or circt-dis tool driver.
=> [circt-synth] Add `-emit-bytecode` option

include/circt/Dialect/Seq/SeqOps.td, lib/Dialect/LLHD/Transforms/Deseq.cpp, test/Dialect/LLHD/Transforms/deseq.mlir, test/circt-verilog/registers.sv
The LLHD Deseq pass detects clocks and optional asynchronous resets. It currently, mistakenly, creates `seq.compreg` ops with those clocks and resets. The `seq.compreg` op turns out to have a _synchronous_ reset though, making the lowering invalid. Use the `seq.firreg` op instead, as it allows the reset type to be specified explicitly. This requries an additional `comb.mux` to be created for potential enable signals, which `seq.firreg` does not support directly.
We should really nail down the semantics of `seq.compreg` in a follow-up commit. The documentation is very vague, and Deseq is likely not the last pass mistakenly assuming the explicit reset of `seq.compreg` is assumed to be asynchronous.
=> [LLHD] Make Deseq pass emit seq.firreg instead of seq.compreg

include/circt/Dialect/RTG/Transforms/RTGPasses.td, lib/Dialect/RTG/Transforms/CMakeLists.txt, lib/Dialect/RTG/Transforms/LowerValidateToLabelsPass.cpp, test/Dialect/RTG/Transform/lower-validate-to-labels.mlir
The pass to be run in the first compilation run to generate sideband command labels understood by the ISA simulator (e.g. Spike).
=> [RTG] Add LowerValidateToLabels pass

include/circt/Dialect/FIRRTL/Passes.h, include/circt/Dialect/FIRRTL/Passes.td, include/circt/Firtool/Firtool.h, lib/Analysis/FIRRTLInstanceInfo.cpp, lib/Dialect/FIRRTL/Transforms/Lint.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/lint-noerror.mlir, test/Dialect/FIRRTL/lint.mlir
Add an option to FIRRTL's linter (and expose it up to `firtool`) that will
lint (error) if any XMRs exist in the "design".  This is intended to catch
problems where downstream consumers of CIRCT-generated Verilog (e.g.,
Physical Design teams) get unexpected unsynthesizable XMRs in the design.
This is almost _never_ what you want.
Unfortunately, this is highly error prone.  It's difficult to tell what
is/is not the "design".  This relies on the InstanceInfo analysis and
intentionally uses its notion of "design" and not "effective design".  In
other words, this will only trigger this kind of linting if there is an
explicit `MarkDUTAnnotation`.  It will not assume that the main module has
an implicit `MarkDUTAnnotation`.  This is intended to avoid false
positives.
In order to make this work, …
=> [FIRRTL] Lint XMRs in the "design"

lib/Conversion/ImportVerilog/AssertionExpr.cpp, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/Structure.cpp, test/Conversion/ImportVerilog/basic.sv
Support 'sequence' and 'property' declarations.
Slang already handles the references and variable ports. Make visiting of 'AssertionInstance' legal.
Those are part of 'Expressions' of the 'Simple' case. Adapt the visitor to handle the different return types.
=> [ImportVerilog] Add support for SVA declarations

docs/Dialects/FIRRTL/FIRRTLAnnotations.md, include/circt/Dialect/FIRRTL/AnnotationDetails.h, lib/Dialect/FIRRTL/Transforms/CreateSiFiveMetadata.cpp, lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp, test/Dialect/FIRRTL/SFCTests/directories.fir, test/Dialect/FIRRTL/emit-metadata.mlir
This allows extmodules to be annotated with additional library names to be included in the blackbox metadata. Downstream tooling can consume this to determine additional libraries that should be compiled alongside extmodules.
- Add SitestBlackBoxLibrariesAnnotation; process in CreateSiFiveMetadataPass
- Update docs
- Update and add tests
=> Add SitestBlackBoxLibrariesAnnotation; process in CreateSiFiveMetadataPass

lib/Dialect/FIRRTL/Transforms/InjectDUTHierarchy.cpp, test/Dialect/FIRRTL/inject-dut-hierarchy.mlir
Fix an issue with the `moveDut=true` behavior of the `InjectDUTHierarchy`
pass that would occur if the design-under-test (DUT) was the main module
in a circuit.  If this happens, this would create a new wrapper module
above the DUT, mark it private, and keep the main module of the circuit
pointing at the wrapper.  This would then cause the new DUT to be deleted
as it was a private module.
This is not FIRRTL ABI compatible as it will create a new public module
and cause things like additional ref files to be created.
CC: @azidar
=> [FIRRTL] Fix inject-dut-hier deleting new top

lib/Conversion/ImportVerilog/Structure.cpp, test/Conversion/ImportVerilog/basic.sv
Use the names of surrounding generate blocks as a prefix for variable and instance names. This makes the names match up more closely with how existing EDA tools would label variables and instances embededded in generate blocks.
Consider the following Verilog input:
```systemverilog
module Top;
int x;
begin : foo
int y;
for (genvar i = 2; i < 6; ++i) begin : bar
int z;
end
end
endmodule
```
The ImportVerilog conversion pass will now produce the following variables:
```mlir
%x = moore.variable : <i32>            // before: %x
%foo.y = moore.variable : <i32>        // before: %y
%foo.bar_2.z = moore.variable : <i32>  // before: %z
%foo.bar_3.z = moore.variable : <i32>  // before: %z_0
%foo.bar_4.z = moore.variable : <i32>  // before: %z_1
%foo.bar_5.z = moore.variable : <i32>  // before: …
```
=> [ImportVerilog] Incorporate block names to variable/instance names

include/circt/Dialect/FIRRTL/FIRRTLUtils.h, include/circt/Support/Utils.h, lib/Conversion/SeqToSV/FirRegLowering.cpp, lib/Conversion/SeqToSV/FirRegLowering.h, lib/Conversion/SeqToSV/SeqToSV.cpp, lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp, lib/Dialect/FIRRTL/Transforms/ResolveTraces.cpp, lib/Dialect/FIRRTL/Transforms/SpecializeLayers.cpp, test/Dialect/Seq/firreg.mlir, test/firtool/reg-under-inline-layer.fir
In seq-to-sv, we transform seq FirRegOps to sv RegOps. This is done using a helper called FirRegLowering. This PR changes FirRegLowering to correctly lower registers under ifdef blocks.
The initialization of registers is placed in an initial block at the footer of the enclosing HWModuleOp. In order to initialize registers buried under ifdefs, we have to refer to these registers by a local XMR, because the buried registers will not dominate the initial block. We build these in a prepass over the MLIR module, returning a "PathTable" sending buried FirRegOps to their HierPathOps.
The main FirRegLowering procedure operates in parallel on each HWModuleOp. Each invocation is now handed a const reference to the path table, which allows us to produce an XMRRefOp as needed while emitting the …
=> [FIRRTL] Lower registers under ifdefs

lib/Dialect/HW/HWDialect.cpp, unittests/Dialect/HW/CMakeLists.txt, unittests/Dialect/HW/MaterializerTest.cpp
Builders don't always specify the block. If it doesn't, this function segfaults.
=> [HW] MaterializeConstant: check for null block

lib/Conversion/VerifToSMT/VerifToSMT.cpp, test/Conversion/VerifToSMT/verif-to-smt-errors.mlir, test/Conversion/VerifToSMT/verif-to-smt.mlir
Fixes a problem during VerifToSMT lowering when creating the `smt::BVConstantOp`s for initial integer values of registers in the BMC operation. The current implementation calls `getSExtValue()` on the `APInt` provided by the initial value attribute. This causes a crash in either of the following situations:
- The initial value type is lager than 64 bits
- The initial value type is smaller than 64 bits and the MSB of the value is set. By sign-extending to 64 bits, the resulting integer value exceeds the width of the created BitVector.
This is fixed by passing the `APInt` directly to the builder of `smt::BVConstantOp` and adding a check beforehand ensuring that the types of the initial attribute and the initialized register match.
=> [VerifToSMT] Fix lowering of initial integer values for BMC

lib/Dialect/Comb/CombFolds.cpp, test/Dialect/Comb/canonicalization.mlir
The folders and canonicalizers for `comb.shl`, `comb.shru`, and `comb.shrs` perform unchecked `getZExtValue()` calls which can crash if the shift amount does not fit into 64 bits. The shift amount is also not clamped to the width of the result, which causes the shift to be replaced with ops that have a different type.
Found with [VlogHammer], which turns out to be a very handy tool!
Fixes #8694.
Fixes #8695.
[VlogHammer]: https://github.com/YosysHQ/VlogHammer
=> [Comb] Fix excessive const shifts causing crashes and invalid IR

include/circt/Dialect/HW/HWPasses.h, include/circt/Dialect/HW/Passes.td, lib/Dialect/HW/Transforms/FlattenIO.cpp, lib/Dialect/HW/Transforms/FlattenModules.cpp, lib/Dialect/HW/Transforms/FooWires.cpp, lib/Dialect/HW/Transforms/HWAggregateToComb.cpp, lib/Dialect/HW/Transforms/HWPrintInstanceGraph.cpp, lib/Dialect/HW/Transforms/HWSpecialize.cpp, lib/Dialect/HW/Transforms/PrintHWModuleGraph.cpp, lib/Dialect/HW/Transforms/VerifyInnerRefNamespace.cpp, lib/Dialect/Kanagawa/Transforms/KanagawaPassPipelines.cpp, lib/Firtool/Firtool.cpp, lib/Synthesis/SynthesisPipeline.cpp, tools/arcilator/arcilator.cpp
Change all HW passes to use ODS consturctors as opposed to hand-rolling
them.  The hand-rolled constructors aren't necessary and add a bunch of
boilerplate.
Note: a number of these passes do not have users and hence may break out
of tree users.  The out of tree users are likely @teqdruid and @mortbopet.
=> [hw] Convert HW Passes to use ODS constructors

frontends/PyRTG/src/pyrtg/immediates.py, frontends/PyRTG/src/pyrtg/integers.py, include/circt/Dialect/RTG/IR/RTGOps.td, lib/Dialect/RTG/Transforms/ElaborationPass.cpp, test/Dialect/RTG/IR/basic.mlir, test/Dialect/RTG/Transform/elaboration.mlir
When we want to be able to get all possible numbers that fit in a 64 bit register, we would need a 65 bit number as the upper bound. However, an iindex typed attribute uses an APInt with 64 bits and would thus make this complicated.
=> [RTG] Redefine RandomNumberInRangeOp upper bound to be inclusive

lib/Bindings/Python/support.py
Exceptions are slow. I've seen speedups of ~60x for this new type conversion approach.
=> [Python] Speed up type_to_pytype and attribute_to_var

lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, test/Dialect/FIRRTL/lower-layers.mlir, test/firtool/reg-under-inline-layer.fir
We want to use the same macro for an inline layer across all compilation units (circuits) in a design.  Remove the circuit name from the macro name.
This requires a change to the FIRRTL ABI, here:
https://github.com/chipsalliance/firrtl-spec/pull/313
=> [FIRRTL] Remove circuit from macro used by inline layers

lib/Dialect/FIRRTL/Transforms/SFCCompat.cpp, test/Dialect/FIRRTL/sfc-compat.mlir
Enum types were not handled by this pass, and so it would hit an unreachable assert.  This handles enum types using the aggregate codepath, which creates a 0 value and bitcasts it to the aggregate type.
=> [FIRRTL] SFCCompat: properly lower invalidated enums

include/circt/Dialect/FIRRTL/FIRRTLExpressions.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp
This also changes TagExtract to use the simpler type inference signatures used by other primitive operations, which will be used when parsing this operation from fir files.
=> [FIRRTL] TagExtract: make type inference parser friendly

lib/Dialect/ESI/ESIDialect.cpp, lib/Dialect/ESI/ESIFolds.cpp, test/Dialect/ESI/canonicalizers.mlir
Fixes the canonicalizers for wrap operations in the ESI dialect by replacing problematic attribute-based folding with proper operation creation and improving pattern matching logic.
- Updates `WrapValidReadyOp` and `WrapFIFOOp` fold methods to create `NullSourceOp` operations instead of using attributes
- Improves the `WrapFIFOOp` canonicalize method with better error handling and more robust user checking
- Delegates constant materialization to the HW dialect for better consistency
=> [ESI] Fix wrap op canonicalizers

lib/Dialect/FIRRTL/Transforms/LowerSignatures.cpp, test/Dialect/FIRRTL/lower-types.mlir
This adds support for enumerations to LowerSigs so that the pass no longer fails when it encounters an enum, and just passes them through unchanged.
=> [FIRRTL] LowerSigs: Add enum support

include/circt/Dialect/RTG/Transforms/RTGPasses.td, include/circt/Support/Path.h, lib/Dialect/RTG/Transforms/CMakeLists.txt, lib/Dialect/RTG/Transforms/EmitRTGISAAssemblyPass.cpp, lib/Dialect/RTG/Transforms/PrintTestNamesPass.cpp, lib/Support/CMakeLists.txt, lib/Support/Path.cpp, test/Dialect/RTG/Transform/print-test-names.mlir
This pass prints the names of the tests in the IR. Since tests can be duplicated and elaborated differently during compilation, it prints both the newly uniqued name and the original name as specified by the user in the frontend.
In the future this could be extended to print additional information about tests post-elaboration.
=> [RTG] Add a pass to print a list of tests

include/circt/Dialect/Verif/VerifOps.td, lib/Dialect/Verif/VerifOps.cpp, lib/Tools/circt-lec/ConstructLEC.cpp, test/Dialect/Verif/basic.mlir, test/Dialect/Verif/errors.mlir
This PR adds the `RefinementCheckingOp` to the `verif` dialect. The motivation behind this operation is to be able to automatically check whether a 'target' circuit is a refinement of a 'source' circuit. This should be a small step towards performing translation validation comparable to [Alive2](https://users.cs.utah.edu/~regehr/alive2-pldi21.pdf). The operation is structurally identical to the `LogicEquivalenceCheckingOp`, so I factored out most of the ODS into a common `CircuitRelationCheckOp`. If there is no non-determinism present in the circuits, the operation is also functionally identical to `LogicEquivalenceCheckingOp`.
Finding a good definition of the `refines` relation is hard, so please just consider this as a humble first attempt. In essence, there are (at least) three factors …
=> [Verif] Add RefinementCheckingOp

lib/Dialect/FIRRTL/FIRRTLTypes.cpp, lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/errors.mlir, test/Dialect/FIRRTL/infer-widths-errors.mlir, test/Dialect/FIRRTL/infer-widths.mlir, test/Dialect/FIRRTL/parse-basic.fir, test/Dialect/FIRRTL/parse-errors.fir
This adds verifiers to the FIRRTL parser and to the FEnumType to prevent having uninferred widths and resets inside enumerations.  It seems like the trickiness to implement these features would be hard to take advantage of in practice, making it not worth it.  This also fixes the error messages produced by the type verifier that had extraneous quotes around the field name, and rearranges some tests to be co-located in the test file.
=> [FIRRTL] Do not allow uninferred widths or rests in enums

frontends/PyRTG/src/pyrtg/immediates.py, frontends/PyRTG/test/basic.py, include/circt/Dialect/RTG/IR/RTGOps.td, include/circt/Dialect/RTG/IR/RTGVisitors.h, lib/Dialect/RTG/IR/RTGOps.cpp, lib/Dialect/RTG/Transforms/ElaborationPass.cpp, test/Dialect/RTG/IR/basic.mlir, test/Dialect/RTG/IR/errors.mlir, test/Dialect/RTG/Transform/elaboration.mlir
This allows passing immediates around instead of two integers (one with the value, one with the bitwidth) and then split it, e.g., for loading that immediate into a register since there is no instruction that can load a 64bit or even 32bit immediate in one go.
=> [RTG] Add immediate concat and slice operations

lib/Conversion/FSMToSV/FSMToSV.cpp, test/Conversion/FSMToSV/test_basic.mlir
Previously, the conversion FSMToSV would crash on operations that were in the transition region but outside the guard region.
Example: Consider the following program in the FSM dialect of CIRCT
```mlir
module {
fsm.machine @OpsInTransition(%arg0: i1) -> (i1) attributes {initialState = "State1"} {
%false = hw.constant false
fsm.state @State1 output {
%false_0 = hw.constant false
fsm.output %false_0: i1
}
fsm.state @State2 output {
fsm.output %false : i1
} transitions {
%false_0 = hw.constant false
fsm.transition @State1 guard {
fsm.return %false_0
}
}
}
}
```
behavior before:
```bash
ak2518@autobot:/local/scratch/ak2518/circt$ circt-opt --convert-fsm-to-sv --split-input-file ../RTL-to-FSM-extractor/weird.mlir
within split at ../RTL-to-FSM-extractor/weird.mlir:1 offset :11:18: error: …
```
=> [circt-opt][FSMToSV] Fix bug of operations not being cloned in transition region in FSMToSV Conversion

include/circt/Dialect/Seq/SeqPasses.h, include/circt/Dialect/Seq/SeqPasses.td, lib/Dialect/Seq/Transforms/CMakeLists.txt, lib/Dialect/Seq/Transforms/RegOfVecToMem.cpp, test/Dialect/Seq/reg-of-vec-to-mem.mlir
This PR introduces a new transformation pass `RegOfVecToMem` that converts register arrays following memory access patterns into `seq.firmem` operations.
This is required for the `circt-verilog` tool, to identify memories, such that other `circt` transformations/analysis can be run in the `seq` dialect on the `mlir` parsed from verilog.
The pass analyzes `seq.firreg` operations with array types and identifies memory access patterns consisting of:
- A register array representing memory storage
- `hw.array_get` operations for reads  
- `hw.array_inject` operations for writes
- `comb.mux` operations controlling read/write enables
- Optional output registers for read data
When a valid pattern is detected, the pass replaces the register array with a `seq.firmem` operation and corresponding …
=> [Seq] Add a pass to convert an array seq.firreg to seq.firmem

lib/Dialect/FIRRTL/FIRRTLTypes.cpp, lib/Dialect/FIRRTL/Transforms/FlattenMemory.cpp, test/Dialect/FIRRTL/flatten-memory.mlir
This adds support to flatten memories with enumeration in them. Enumerations are treated as non-aggregate types, and so they get a single bit mask to control the whole value.
=> [FIRRTL] FlattenMemories: handle memories with enums

lib/Conversion/VerifToSMT/VerifToSMT.cpp, test/Conversion/VerifToSMT/verif-to-smt-errors.mlir, test/Conversion/VerifToSMT/verif-to-smt.mlir
Implement a conversion pattern for the `verif.refines` operation to the SMT dialect.
Following the current definition of the `RefinmentCheckingOp`, the second (target) circuit is a refinement of the first (source) circuit iff for any given input assignment the set of possible outputs of the target circuit is a subset of the source circuit's possible outputs. The conversion assumes all `smt.declare_fun` operations in the circuit body to be sources of non-determinism, as they are created by the lowering of the division (by zero) and (out of bounds) array get operations. The expression we are checking for is:
_For all_ inputs: _For all_ non-deterministic choices in the target circuit: _Exists_ a non-deterministic choice in the source circuit leading to identical outputs?
Since we are trying …
=> [VerifToSMT] Lower `verif.refines` to SMT

lib/Dialect/FIRRTL/FIRRTLOps.cpp, test/Dialect/FIRRTL/parse-basic.fir
TagExtractOp's type inference predates adding user-defined encodings for enums in FIRRTL. This fixes the issue by using the bitwidth helpers defined on the enumeration type.
=> [FIRRTL] Fix TagExtractOp's type inference

lib/Dialect/FIRRTL/Transforms/InferResets.cpp, test/Dialect/FIRRTL/infer-resets.mlir
This adds the ability to the FullResetTransform to create enumeration values which are 0.  When the enumeration has a valid variant that is encoded as a 0, we create this value using the FEnumCreateOp.  If there is no valid variant with the value 0, we create a constant 0 and bitcast it to the enumeration type.
=> [FIRRTL] FRT: support creating 0-valued enums

include/circt/Dialect/Arc/ArcOps.td, include/circt/Dialect/FSM/FSMOps.td, include/circt/Dialect/HW/HWStructure.td, include/circt/Dialect/Interop/Interop.td, include/circt/Dialect/Moore/MooreOps.td, include/circt/Dialect/SV/SVTypeDecl.td, include/circt/Dialect/Seq/SeqOps.td, include/circt/Dialect/SystemC/SystemCStructure.td, include/circt/Dialect/Verif/VerifOps.td, lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp
LLVM has deprecated ArrayRef(std::nullopt_t).  This CL migrates away
from that.
=> Migrate away from ArrayRef(std::nullopt_t)

.github/workflows/esiRuntimePublish.yml
Minor bugfixes _during development_ doesn't always warrant a new ESI tag. Allow the `esiRuntimePublish` pipeline to publish `dev` packages upon manual CI runs (`workflow_dispatch`).
=> [ESI] Also publish releases on workflow_dispatch

lib/Dialect/FIRRTL/Import/FIRParser.cpp, test/Dialect/FIRRTL/parse-errors.fir
Parser crashes when cat is constructed with invalid type operands.
=> [FIRRTL] Type check in Cat operatnds in FIR parser

lib/Conversion/HWToLLVM/HWToLLVM.cpp, test/Conversion/HWToLLVM/convert_aggregates.mlir
This adds lowering support for the `hw.array_inject` operation into `llvm` dialect.
=> [HWToLLVM] Add lowering support for 'hw.array_inject' op

include/circt/Dialect/FIRRTL/FIRRTLStatements.td, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, test/Dialect/FIRRTL/layers-errors.mlir, test/Dialect/FIRRTL/lower-layers.mlir
This PR adds layer verifiers to the probe force and release ops. During this work I notice that lower-layers does not remove colours from all ops (caught by the new verifiers), so I have fixed that here as well.
=> [FIRRTL] Add layer colour verifiers to force and release ops

tools/firtool/firtool.cpp
The one upstream change we had to account for was
https://github.com/llvm/llvm-project/commit/b6a98b9, where we started creating splits that don't have null terminated buffers, which are assumed by our tool and the SourceMgr. Make a copy to ensure null-termination, which is apparently what happened anyway before this change.
=> Bump LLVM to b63a9b7a3cdc1e41545df595215077e50bfd04af.

lib/Dialect/ESI/runtime/CMakeLists.txt, lib/Dialect/ESI/runtime/cosim_dpi_server/CMakeLists.txt, lib/Dialect/ESI/runtime/python/esiaccel/utils.py
Windows has no notion of rpath. It just looks in the same directory as the executable/dll then the system search path. With the directory structure as is currently was, `esiquery` was unable to load ESICppRuntime.dll. It's not a great solution, but put everything in the same directory on Windows.
=> [ESI][Runtime] Windows wheel: use flat directory structure

lib/Dialect/ESI/runtime/cpp/include/esi/Common.h, lib/Dialect/ESI/runtime/cpp/include/esi/Services.h, lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp, lib/Dialect/ESI/runtime/cpp/lib/Services.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Trace.cpp, lib/Dialect/ESI/runtime/cpp/lib/backends/Xrt.cpp
Locating client ports was broken in the case of the MMIO service being not at the top level.
=> [ESI][Runtime] Fixing MMIO to account for relative paths

utils/compare-arcs-vtor-stubs.sv, utils/compare-arcs-vtor.py
Add the `compare-arcs-vtor.py` utility script which takes a core dialect design, compiles it with Arcilator and Verilator to obtain two simulators, and then runs the simulators in lockstep on random inputs to verify that they produce the same output.
This can be useful in combination with circt-reduce in order to isolate behavior mismatches between Arcilator and Verilator.
=> [utils] Add Arcilator and Verilator comparison utility

include/circt/Dialect/Moore/MooreOps.td, include/circt/Dialect/Moore/MooreTypes.h, include/circt/Dialect/Moore/MooreTypes.td, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, lib/Conversion/ImportVerilog/Structure.cpp, lib/Conversion/ImportVerilog/Types.cpp, lib/Conversion/MooreToCore/MooreToCore.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/ImportVerilog/default-timeunit.sv, test/Conversion/ImportVerilog/errors.sv, test/Conversion/ImportVerilog/types.sv, test/Conversion/MooreToCore/basic.mlir
Add support for time literal expressions such as `42us` or `1.234ns` to the ImportVerilog conversion.
Time values in SystemVerilog are pretty messy and easy to misuse because they are essentially just unit-less integers or doubles. To make the CIRCT's Verilog frontend a bit more robust, introduce a new `!moore.time` type that represents a time value. The `time` and `realtime` types in SV both map to this IR type.
All time values are converted and rounded to femtoseconds and then stored as an `i64`. A new `moore.constant_time` can be used to materialize a constant time value. This means that time values in the IR are represented with an unambiguous unit.
In contrast, SystemVerilog eagerly converts time values to the underlying integer or double by scaling the value by the `timeunit` …
=> [ImportVerilog] Add time literals

lib/Dialect/LLHD/Transforms/Mem2Reg.cpp, test/Dialect/LLHD/Transforms/mem2reg.mlir
Currently, after Mem2Reg inserts drives and probes, it does not check whether `llhd.sig` (or the slot) still dominates all of its users. For cases where the operand is `hw.constant`, it should be safe to move the `llhd.sig` into region's entry block to ensure dominance, if it doesn't already. What do you think? 
Error, without the patch:
```
<stdin>:29:16: error: operand #0 does not dominate this use
%ready_T = llhd.sig %c2_i4 : i4
^
<stdin>:29:16: note: see current operation: "llhd.drv"(%18, %9, %11, %10) : (!hw.inout<i4>, i4, !llhd.time, i1) -> ()
<stdin>:29:16: note: operand defined here (op in the same region)
```
=> [LLHD] Propogate signal definitions only to dominated blocks in Mem2Reg

CMakeLists.txt
Pull in latest v8 release for bug fixes.
https://github.com/MikePopoloski/slang/releases/tag/v8.1
=> [ImportVerilog] slang 8.0 -> 8.1

CMakeLists.txt, cmake/modules/SlangCompilerOptions.cmake, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/HierarchicalNames.cpp, test/Tools/circt-verilog-lsp-server/diagnostic.test, test/circt-verilog/commandline.sv
Update the Slang frontend to version 9. This removes quite a few warnings related to C++20 features, and pulls in all the shiny new things.
=> [ImportVerilog] Bump slang to version 9

lib/Conversion/ImportVerilog/ImportVerilog.cpp, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, test/circt-verilog/include/library_module.sv, test/circt-verilog/library-locations.sv, test/circt-verilog/preprocess-errors.sv
The ImportVerilog conversion currently uses a hacky `bufferFilePaths` table to map from `slang::BufferID`s to the corresponding file path. This only works for files that we explicitly add to the source manager. Files discovered automatically by Slang, e.g. through the `-y` flag, have no entry in that table. As a result, any errors in such files will report their file path as `-`, which is not very helpful.
This commit fixes this by using whatever Slang's own `SourceManager::getFileName` returns for a given location. This removes the need for that `bufferFilePaths` table. As a result, errors in files discovered via `-y` will now properly show the file name.
While we're at it, also attach the include file stack as a note to any reported diagnostic. This makes it easier to understand how the …
=> [ImportVerilog] Fix file locations for auto-discovered files

lib/Dialect/LLHD/Transforms/Mem2Reg.cpp, test/Dialect/LLHD/Transforms/mem2reg.mlir
Extend the LLHD Mem2Reg pass to deal with local signal declarations properly. Since these signals have an initial value, a `llhd.sig` op should propagate that value as an initial definition to subsequent ops. This allows a probe on a local signal that has never been driven to resolve to that initial value.
Additionally, since local signals often become entirely unread after propagation to SSA values, make the Mem2Reg pass perform a cleanup of local signals that are only projected into and driven, but never probed.
=> [LLHD] Properly handle local signals during mem2reg

lib/Conversion/FIRRTLToHW/LowerToHW.cpp, test/firtool/cmem-under-layerblock.fir
By the time lower-to-hw runs, the directories have already been assigned. Colocate the memory module with its parent. Remove logic which would set the output directory to the testbench--this is not always right. This allows memories to be emitted into layer specific directories.
=> Put memories in the same directory as their parent

include/circt/Dialect/FIRRTL/Passes.td, include/circt/Firtool/Firtool.h, lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, lib/Firtool/Firtool.cpp
The spec does not guarantee the existence of layer bindfiles for private modules, but we have a need to use the verilog of internal/private modules of a circuit and it is helpful if their bindfiles always exist. This PR adds an option to firtool that forces lower layers to emit bindfiles for private modules, even when not necessary.
=> [FIRRTL] Firtool: Add option to emit bind files for private modules

lib/Dialect/HW/HWOps.cpp, test/Dialect/HW/canonicalization.mlir
Add more canonicalization for inject ops. Array inject chains are now traversed and converted to a single array create if all fields are set. This also works in the presence of loops, which can occur in Verilog input. Explicitly allow loops in struct injects, which can be broken by injects if all fields are assigned.
Fixes #8860.
=> [HW] Canonicalize array inject to create; allow struct inject loops

lib/Dialect/Arc/ArcTypes.cpp, test/Dialect/Arc/allocate-state.mlir
The `StateType` in the Arc dialect currently just defers to `hw::getBitWidth` to compute the number of bits that need to be allocated in the simulator state. This is problematic, since types like structs and arrays have field and element alignment requirements, making LLVM require more bytes for these types than the summed-up bit width would suggest. As a result, the AllocateState pass would allocate 2 bytes for `struct<tag: i5, sign_ext: i1, offset: i3, size: i2>`, even though LLVM would consider the individual fields to be aligned to the nearest byte, making the struct cover 4 bytes in memory.
To fix this issue, make `StateType` more carefully compute the actual number of bits required in simulator storage by requiring all elements of a array or struct to be at least byte-aligned, and …
=> [Arc] Consider array/struct field alignment when computing state size

include/circt/Dialect/Synth/Transforms/CutRewriter.h, include/circt/Dialect/Synth/Transforms/SynthPasses.td, integration_test/circt-synth/mapping-lec.mlir, lib/Dialect/Synth/Transforms/CMakeLists.txt, lib/Dialect/Synth/Transforms/CutRewriter.cpp, lib/Dialect/Synth/Transforms/TechMapper.cpp, test/Dialect/Synth/tech-mapper-error.mlir, test/Dialect/Synth/tech-mapper.mlir, tools/circt-synth/circt-synth.cpp
This commit implements a cut-based rewriting framework for combinational logic optimization 
and adds the TechMapper pass that uses NPN-equivalence matching with area and delay
metrics to map AIG circuits to technology libraries. The implementation is based on: 
* "Combinational and Sequential Mapping with Priority Cuts", Alan Mishchenko, Sungmin Cho, Satrajit Chatterjee and Robert Brayton, ICCAD 2007
* "Fast Boolean matching based on NPN classification",  Zheng Huang Lingli Wang Yakov Nasikovskiy and Alan Mishchenko, FPT 2013
The Technology Mapping Pass shows how to use this framework in practice by 
mapping generic logic operations to specific hardware gates from a technology 
library. This pass also serves as a test for the framework since 
testing the cut rewriting algorithms directly …
=> [Synth] Add CutRewriter framework and TechMapper pass

lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp, lib/Conversion/CombToArith/CombToArith.cpp, lib/Conversion/HWToLLVM/HWToLLVM.cpp, test/Conversion/HWToLLVM/convert_aggregates.mlir
Who doesn't enjoy a free lunch?
This PR sets the `allowPatternRollback` option to `false` in the ArcToLLVM and related dialect conversion passes. The main effect of this should be a reduction of compilation time and memory consumption. To the best of my knowledge we are not (naughtily) relying on the pre-conversion operations to be kept in the IR during conversion.
Doing some basic testing, it knocks down the time for ArcToLLVM from
```
0.5449 ( 35.5%)  LowerArcToLLVM
```
to
```
0.2048 ( 17.0%)  LowerArcToLLVM
```
for the rocket `dual-large-master` design of the arc-tests repo. This is after merging #8876.
And it is expected to become more significant for larger designs. See https://discourse.llvm.org/t/rfc-a-new-one-shot-dialect-conversion-driver/79083/75
=> [LowerArcToLLVM] Disable pattern rollback in dialect conversion

lib/Analysis/DebugAnalysis.cpp, lib/Conversion/ExportVerilog/ExportVerilog.cpp, lib/Conversion/FIRRTLToHW/LowerToHW.cpp, lib/Conversion/SMTToZ3LLVM/LowerSMTToZ3LLVM.cpp, lib/Dialect/Arc/Interfaces/RuntimeCostEstimateInterfaceImpl.cpp, lib/Dialect/Calyx/CalyxOps.cpp, lib/Dialect/Comb/CombFolds.cpp, lib/Dialect/LoopSchedule/LoopScheduleOps.cpp, lib/Dialect/Sim/SimOps.cpp
op->getDialect() returns nullptr for unregistered dialect so generally it's preferable to use isa_and_nonnull. 
Fix https://github.com/llvm/circt/issues/8873.
=> Use isa_and_nonnull for op->getDialect()

include/circt/Dialect/Moore/MooreOps.td, include/circt/Dialect/Moore/MooreTypes.h, include/circt/Dialect/Moore/MooreTypes.td, lib/Conversion/ImportVerilog/AssertionExpr.cpp, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/Statements.cpp, lib/Conversion/ImportVerilog/Structure.cpp, lib/Conversion/MooreToCore/MooreToCore.cpp, lib/Dialect/Moore/MooreOps.cpp, lib/Dialect/Moore/MooreTypes.cpp, test/Conversion/ImportVerilog/basic.sv, test/Conversion/MooreToCore/basic.mlir, test/Dialect/Moore/basic.mlir, test/Dialect/Moore/canonicalizers.mlir
Extend the Moore dialect with the following new conversion operations:
- `moore.packed_to_sbv` to convert any packed type to its simple bit vector equivalent (i.e., an integer);
- `moore.sbv_to_packed` to do the reverse;
- `moore.logic_to_int` to convert from a four-valued integer to a two-valued integer;
- `moore.int_to_logic` to convert from a two-valued integer to a four-valued integer; and
- `moore.to_builtin_bool` to convert from a single bit `moore::IntType` to a single bit builtin `mlir::IntegerType`.
Adjust the `ImportVerilog` pass to generate these new conversion ops instead of the old whole-sale `moore.conversion`. Having smaller, more precise conversion ops will make lowering to the core dialects easier in the future, especially once we fully support four-valued types and time …
=> [Moore] Add more precise conversion ops

include/circt/Dialect/Synth/Transforms/SynthPasses.td, integration_test/circt-synth/mapping-lec.mlir, lib/Dialect/Synth/Transforms/CMakeLists.txt, lib/Dialect/Synth/Transforms/CutRewriter.cpp, lib/Dialect/Synth/Transforms/GenericLUTMapper.cpp, test/Dialect/Synth/lut-mapper.mlir, tools/circt-synth/CMakeLists.txt, tools/circt-synth/circt-synth.cpp
This is a follow-up to https://github.com/llvm/circt/pull/8868. 
This commit introduces a pass that performs technology-independent LUT mapping from logic network to generic lookup tables (comb.truth_table). The pass is primarily designed for benchmarking purposes and provides functionality equivalent to ABC's `if -K 6` command for K-LUT mapping.
The pass supports configurable LUT sizes and uses a cut-based rewriting approach to efficiently map combinational logic from AIG nodes to truth tables. It includes options for maximum LUT size and maximum cuts per root node to control the mapping quality and compilation time. The implementation provides technology-independent LUT mapping with configurable K-LUT support (default K=6), cut enumeration with configurable limits, truth table …
=> [Synth] Add GenericLUTMapper pass for LUT mapping

README.md
Hi, after #8851 PR path to `DMLIR_DIR` and `DLLVM_DIR` contain unnecessary `../`
=> [README] Fix path to MLIR in README.md

integration_test/circt-synth/mapping-lec.mlir, lib/Dialect/Synth/Transforms/CutRewriter.cpp, test/Dialect/Synth/priority-cuts.mlir
Improve cut deduplication by removing both duplicate and non-minimal cuts using efficient bitset representation. This reduces redundant cuts in the synthesis pipeline and improves performance. See section 3 of https://dl.acm.org/doi/10.1145/296399.296425.
Fix #8885.
=> [Synth] Improve cut deduplication and non-minimal cut removal

lib/Dialect/AIG/Analysis/LongestPathAnalysis.cpp, test/Dialect/AIG/longest-paths.mlir, test/circt-synth/path-e2e.mlir
This handles truth_tabe op as a unit in the analysis so that we can analysis the post-mapped result
=> [AIGLongestPathAnalysis] Allow comb.truth_table as a unit

CMakeLists.txt, test/Conversion/ImportVerilog/basic.sv
We encountered some failures that were addressed since 9.0 tag, given no API changes seemed like good to bump to new version.
=> Bump slang to dd16a7947e0586d0541477f1b4b60eda7c986e35

lib/Conversion/FSMToSV/FSMToSV.cpp, test/Conversion/FSMToSV/single_state.mlir
The conversion seems to work and gets to Verilog. It seems correct, if not most efficient lowered form if there is only one state. Not sure if there was a different reason for this restriction (beyond, this would be better as just HWModule, although didn't see a pattern that would do that).
=> Remove single state restriction on FSM to SV

include/circt/Dialect/Synth/Transforms/CutRewriter.h, lib/Dialect/Synth/Transforms/CutRewriter.cpp, lib/Dialect/Synth/Transforms/GenericLUTMapper.cpp, lib/Dialect/Synth/Transforms/TechMapper.cpp, lib/Dialect/Synth/Transforms/TestPriorityCuts.cpp, test/Dialect/Synth/priority-cuts.mlir, test/circt-synth/path-e2e.mlir
This commit refactors the cut rewriter and implements correct priority sort metric for depth. Previously `depth` of a cut represents a logic depth *within* a cut but this is not correct. What the original paper (ICCAD 2007) proposed was to use arrival time of cut outputs instead.
For that this commit changes to perform cut matching for each cut, and use worst arrival time as a priority of cuts.
LUT6 depth for 16-bit multiplier improved from 17 to 7, which is on per with Yosys/ABC.
=> [Synth] Refactor and improve cut rewriter infrastructure

integration_test/circt-synth/datapath-lowering-lec.mlir, lib/Conversion/DatapathToComb/DatapathToComb.cpp, test/Conversion/DatapathToComb/datapath-to-comb.mlir
Reduce the number of partial product bits generated using a classical sign-extension trick where repeated bits can be optimised away. Currently only implemented when the inputs to a partial product operator are zero-extended. Current folding mechanisms are unable to recognise the zero-padding in a single step (although canonicalization will incrementally strip away). The KnownBits analysis is able to recognise this at some efficiency penalty - although this could be improved using bounded depth traversal. 
A future PR will exploit this simplified partial product array via timing driven compression and improve the algorithm further to detect sign-extended inputs.
=> [Datpath] Improve Booth Encoding based on the sign-extension trick

include/circt/Dialect/AIG/AIGOps.td, include/circt/Dialect/Synth/SynthOps.h, include/circt/Dialect/Synth/SynthOps.td, include/circt/Support/CustomDirectiveImpl.h, lib/Dialect/AIG/AIGOps.cpp, lib/Dialect/AIG/CMakeLists.txt, lib/Dialect/Synth/CMakeLists.txt, lib/Dialect/Synth/SynthOps.cpp, lib/Support/CustomDirectiveImpl.cpp, test/Dialect/Synth/errors.mlir, test/Dialect/Synth/round-trip.mlir
Towards https://github.com/llvm/circt/issues/8786, this commit introduces a new MajorityInverterOp operation to represent majority-inverter gates in Majority-Inverter Graphs (MIG) for synthesis (https://ieeexplore.ieee.org/document/7293649). Majority-Inverter Graphs have become a prominent representation for logic synthesis in recent years, offering advantages in certain optimization scenarios alongside And-Inverter Graphs (AIG).
The implementation provides a synth.mig.maj_inv operation that computes the majority function of its inputs with optional inversion per operand. The operation requires an odd number of operands to avoid ties in majority computation and uses a custom assembly format with 'not' keyword prefix for inverted inputs. 
The majority function returns 1 when more than half …
=> [Synth] Add MajorityInverterOp (synth.mig.maj_inv) to Synth dialect

lib/Dialect/ESI/runtime/python/esiaccel/__init__.py, lib/Dialect/ESI/runtime/python/esiaccel/utils.py
To ensure that things (especially other pybind packages) which build against ESI libraries have the `ESICppRuntime.dll` freely available upon load time, by adding the `esiaccel` directory to the `dll_directory` list.
=> [ESI] Extend dll dirs on esiaccel module load

lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, test/firtool/lower-layers.fir
Lowerlayers is using the name of an extmodule to determine the name of the extmodule's bindfiles. Instead, we should be using the defname.
=> [FIRRTL] Use the defname for deciding bindfile names of extmodules

CMakeLists.txt
Add the /utf-8 flag if building on Windows.  This is necessary when
building the fmt library.
=> [build] Add /utf-8 build if MSVC

.github/bin/uploadReleaseArtifacts.sh
Add additional, useful tools as part of the `firrtl-bin` release package.
This will avoid users having to get one of the "full" installations (and
also deal with the fact that these installations are not truly static).
This has a cost of bloating the `firrtl-bin` tarball.  However, that seems
acceptable given that users may not have easy alternatives for how to get
these tools.
=> [ci] Release circt-{opt,synth,test} in firrtl-bin

lib/Conversion/AffineToLoopSchedule/AffineToLoopSchedule.cpp
dominates does not satisfy strict weak ordering property.
Fixes #8897
=> Use properlyDominates in AffineToLoopSchedule

include/circt/Dialect/FIRRTL/LayerSet.h, lib/Dialect/FIRRTL/FIRRTLOps.cpp, lib/Dialect/FIRRTL/FIRRTLReductions.cpp, lib/Reduce/GenericReductions.cpp, tools/circt-reduce/circt-reduce.cpp
Use a stable sort in the reducer to sort matches. The binary search over the matchese expects them to be in the order that they were matched in the IR when matches have the same benefit.
Add a generic reduction to prune unused symbols.
Make the FIRRTL annotation remover check if annotations are already empty, and not match on those ops. This significantly improves reduction speed.
Fix an issue in the FIRRTL module externalizer, where `FExtModule`s require an additional list of known layers that needs to be created. Also, don't externalize modules that participate in NLAs, since removing those would invalidate the NLA.
=> [Reduce] Use stable sort, prune unused symbols, tweak FIRRTL reductions

include/circt/Dialect/Arc/ArcOps.td, lib/Dialect/Arc/ArcOps.cpp, lib/Dialect/Arc/Transforms/LowerArcsToFuncs.cpp, test/Dialect/Arc/basic-errors.mlir, test/Dialect/Arc/basic.mlir, test/Dialect/Arc/lower-arcs-to-funcs.mlir
Add a new `arc.execute` op which is similar to `scf.execute_region`. It allows an SSACFG region to be embedded in a graph region like an `hw.module`. In a later PR, a conversion from `llhd.combinational` to this new `arc.execute` will be added. We can't directly use `scf.execute_region` for this since that op eagerly inlines into the parent region even if the parent is a graph region. This does not preserve semantics in the case of HW modules.
=> [Arc] Add ExecuteOp

include/circt/Dialect/Synth/Synth.td, include/circt/Dialect/Synth/SynthOps.td, lib/Dialect/Synth/SynthDialect.cpp, lib/Dialect/Synth/SynthOps.cpp, test/Dialect/Synth/canonicalizer.mlir
Add canonicalize method with pattern matching for single operands, identical/complementary operands, and constants.
Also implement fold method for constant evaluation along with constant materialization
=> [Synth] Implement basic canonicalization/folder to mig.maj_inv

lib/Dialect/Synth/Analysis/LongestPathAnalysis.cpp, test/Dialect/Synth/longest-paths.mlir, test/circt-synth/path-e2e.mlir
Extend LongestPathAnalysis to handle mig::MajorityInverterOp
=> [Synth] Add support for mig.maj_inv in longest path analysis

include/circt/Dialect/SV/SVOps.h, include/circt/Dialect/SV/SVStatements.td, lib/Dialect/SV/CMakeLists.txt
sv::FuncCallOp uses CallInterface but CallInterface was not explicitly included/linked. I believe this fixes https://github.com/llvm/circt/issues/8954 (though not sure why the failure doesn't reproduce locally).
=> [SV] Include CallInterface

include/circt/Dialect/Moore/MooreOps.td, include/circt/Dialect/Moore/MooreTypes.td, lib/Conversion/ImportVerilog/Expressions.cpp, lib/Conversion/ImportVerilog/ImportVerilogInternals.h, test/Conversion/ImportVerilog/builtins.sv
First time I try to add a new Op, so let me know if I went wrong somewhere! 
This PR adds a new builtin in moore for the $urandom system call.
Per the newest version of the spec, $urandom may be called with or with a integer seed argument, and always returns an integer produced by a pseudo-random number generator.
As such I added an importer conversion and tests for both cases; the allowed expressions are 
```
moore.builtin.urandom
moore.builtin.urandom %arg : !moore.i32
```
I struggled a bit with constraining the output type of `moore.builtin.urandom`, since it is constant. I added
```
def MooreI32 :
Type<CPred<
"(::llvm::isa<::circt::moore::IntType>($_self) && "
"::llvm::cast<::circt::moore::IntType>($_self).getWidth() == 32 && " …
```
=> [Moore] Add builtin for $urandom

include/circt/Dialect/Moore/MooreOps.td, include/circt/Dialect/Moore/MooreTypes.td, lib/Conversion/ImportVerilog/Expressions.cpp, test/Conversion/ImportVerilog/builtins.sv
This PR adds builtins for `$time`, `$stime` and `$realtime` in the `moore` Dialect.
All these builtins correspond to System Verilog system tasks and only slightly differ in their functionality.
To represent the return value of `$time`, this PR adds `TwoValueI64`, which represents a 64-Bit integer used to express the simulation time value in.
EDIT: Just spotted there is a `TimeType` in the MooreTypes as well - maybe that would be a better output target? 
An "added complication" in this matter is that `TimeType` currently does not enforce the spec's rounding / truncation / overflow semantics as far as I can see.
I'm thinking it might make sense to first introduce support for `$timeformat`, maybe by adding a `TimeFormatResource`?
Then these system calls can be resolved by checking the …
=> [Moore] Add builtins for simulation time measurements

include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h, lib/Dialect/FIRRTL/FIRRTLReductions.cpp, test/circt-reduce/must-dedup-children.mlir
Add the `MustDedupChildren` reduction which takes must dedup annotations and replaces them with must dedup annotations on child modules. More Claude Sonnet 4 magic!
=> [FIRRTL] Add reduction that moves MustDedup onto children

include/circt/Dialect/Moore/MooreOps.td, lib/Conversion/ImportVerilog/Expressions.cpp, test/Conversion/ImportVerilog/builtins.sv
This PR adds support for `$random` system calls and maps them to a new Moore builtin-op `RandomBIOp`.
Implementation is very much along the lines of [the $urandom implementation](https://github.com/llvm/circt/pull/8968).
I chose to not map $random and $urandom to the same builtin as they are semantically different, $urandom being pseudo-random, $random being true-random.
=> [Moore] Add support for $random system task

lib/Dialect/ESI/runtime/cosim_dpi_server/Cosim_Endpoint.sv
It has been observed that some simulators (verilator) does not handle combinational driving from DPI well (resulting in non-determinism wrt. some of the combinational outputs being dropped/replicated). Questa does not show this behavior. A mitigation is to add a skid buffer to decouple the DPI interface from the output interface. Use the existing skid buffer from ESIPrimitives.
=> [ESI] Add skid buffer to Cosim_Endpoint_ToHost

include/circt/Support/InstanceGraph.h, lib/Analysis/FIRRTLInstanceInfo.cpp, lib/Dialect/FIRRTL/Transforms/AssignOutputDirs.cpp, lib/Dialect/FIRRTL/Transforms/CheckLayers.cpp, lib/Dialect/FIRRTL/Transforms/Dedup.cpp, lib/Dialect/FIRRTL/Transforms/LayerSink.cpp, lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp, lib/Dialect/FIRRTL/Transforms/LowerXMR.cpp, test/firtool/assign-output-dirs.fir, test/firtool/instchoice.fir
Add new helper functions to the `InstanceGraph` that implement a full post-order and inverse-post-order walk across _all_ modules. This pulls a common pattern into the instance graph itself, where a user would iterate over the graph's nodes and then use an `llvm::post_order_ext` iterator to not revisit prior nodes with an externally-held set.
The instance graph implements the graph traits, which makes using `llvm::post_order` it tempting. But this is usually not what we want. The graph does not have a unique root node. Instead, the FIRRTL flavor of the graph uses the "top" module as specified by the circuit, and the HW flavor of the graph uses a dummy node that points to all _public_ modules. In most passes we want to iterate over _all_ modules in the IR with a specific order, not just a …
=> [Support] Add walkPostOrder and walkInversePostOrder to InstanceGraph

lib/Dialect/FIRRTL/Transforms/Dedup.cpp, test/Dialect/FIRRTL/dedup.mlir
Add special handling for `!firrtl.class` types in dedup. These used to be treated just as regular types, which meant that `!firrtl.class<@A>` and `!firrtl.class<@B>` would be treated as distinct types, even when the pass deduplicates `@A` and `@B` everywhere else. We already have an established pattern to skip name references and tracking them separately. All that's needed applying this to `ClassType`.
This fixes a subtle OFIRRTL-related issue I've encountered in the wild.
=> [FIRRTL] Handle ClassTypes properly in Dedup

include/circt/Dialect/Emit/EmitReductions.h, include/circt/Dialect/HW/InnerSymbolTable.h, include/circt/Reduce/ReductionUtils.h, lib/Dialect/Emit/CMakeLists.txt, lib/Dialect/Emit/EmitReductions.cpp, lib/Dialect/FIRRTL/FIRRTLReductions.cpp, lib/Reduce/GenericReductions.cpp, lib/Reduce/ReductionUtils.cpp, test/Dialect/Emit/Reduction/emit-op-eraser.mlir, test/Dialect/Emit/Reduction/pattern-registration.mlir, test/Dialect/FIRRTL/Reduction/annotation-remover.mlir, test/Dialect/FIRRTL/Reduction/connect-forwarder.mlir, test/Dialect/FIRRTL/Reduction/constantifier.mlir, test/Dialect/FIRRTL/Reduction/eager-inliner.mlir, test/Dialect/FIRRTL/Reduction/module-externalizer.mlir, test/Dialect/FIRRTL/Reduction/node-symbol-remover.mlir, tools/circt-reduce/CMakeLists.txt, tools/circt-reduce/circt-reduce.cpp
- Make the eager inliner not remove instances that are part of an NLA.
- Make the annotation remover not remove NLAs that have remaining uses after some annotations referencing it were removed.
- Make the constantifier not match on existing constants, and not replace operations that have the "inner_sym" attribute.
=> [FIRRTL] Various small reduction pattern tweaks

include/circt/Tools/circt-verilog-lsp-server/CirctVerilogLspServerMain.h, lib/Conversion/SCFToCalyx/SCFToCalyx.cpp, lib/Dialect/Kanagawa/Transforms/KanagawaInlineSBlocksPass.cpp, lib/Tools/circt-verilog-lsp-server/CirctVerilogLspServerMain.cpp, lib/Tools/circt-verilog-lsp-server/LSPServer.cpp, lib/Tools/circt-verilog-lsp-server/LSPServer.h, lib/Tools/circt-verilog-lsp-server/Utils/LSPUtils.cpp, lib/Tools/circt-verilog-lsp-server/VerilogServerImpl/VerilogServer.cpp, lib/Tools/circt-verilog-lsp-server/VerilogServerImpl/VerilogServer.h, tools/circt-verilog-lsp-server/circt-verilog-lsp-server.cpp
Changes:
* The LSP support has moved from the MLIR to the LLVM namespace (https://github.com/llvm/llvm-project/commit/a3a25996b11401f7589d1429225dc048d8720da9) . 
* Remove another occurrence of `replaceAllUses`+`erase` in Kanagawa's InlineSBlocks pass (see #8989)
* Integrate the SCFToCalyx change of #8987
=> Bump LLVM to 580860e8b7341783e8e53114f26b9a9659a3a3e1

include/circt/Dialect/Synth/SynthOps.h, include/circt/Dialect/Synth/Transforms/SynthPasses.td, lib/Dialect/Synth/SynthOps.cpp, lib/Dialect/Synth/Transforms/CutRewriter.cpp, lib/Dialect/Synth/Transforms/LowerWordToBits.cpp, test/Dialect/Synth/lower-word-to-bits.mlir, test/circt-synth/basic.mlir
Previously, GreedyPatternRewriter was naively used to bit-blast multi-bit values but it didn't scale well due to worklist iteration and unnecessary IR creation which occasionally ended up with constant values. Hence the pass was often not scalable for large designs.
This commit fixes the issue by applying constant propagation during the bit-blast process and replaces GreedyPatternRewriter with a manual one-shot walk with recursion.
=> [Synth] LowerWordsToBits: Improve scalability with bit-sensitive constprop

include/circt-c/Dialect/Synth.h, include/circt/Dialect/Synth/Analysis/LongestPathAnalysis.h, include/circt/Dialect/Synth/Transforms/SynthPasses.td, integration_test/Bindings/Python/dialects/synth.py, lib/Bindings/Python/SynthModule.cpp, lib/Bindings/Python/dialects/synth.py, lib/CAPI/Dialect/Synth.cpp, lib/Dialect/Synth/Analysis/LongestPathAnalysis.cpp, lib/Dialect/Synth/Analysis/PrintLongestPathAnalysis.cpp, test/CAPI/support.c, test/CAPI/synth.c, test/circt-synth/basic.mlir, tools/circt-synth/circt-synth.cpp
This removes a hack `synth.longest-path-analysis-top` which was put to IR in order to pass a top name to analysis. The top module name is now passed explicitly as a parameter to the LongestPathAnalysis constructor and related APIs instead of being stored as an IR attribute.
=> [Synth][LongestPathAnalysis] Remove hack for passing top module name through IR attribute

lib/Dialect/ESI/runtime/python/esiaccel/cosim/simulator.py
Extend `SourceFiles` to also allow single file additions to the source file list.
Small, but important addition, due to the perniciousness of verilog compilers(/simulators), in that e.g. type files have to have a strict ordering when they have inter-dependencies. Just scanning a directory and adding them in lexical order may or may not (...obviously) cause problems in that aspect. With this change, gives users control over the order in which these files are added to the source list.
=> [ESI] Allow single-file additions to SourceFiles

integration_test/circt-synth/datapath-lowering-lec.mlir, lib/Conversion/DatapathToComb/DatapathToComb.cpp, test/Conversion/DatapathToComb/datapath-to-comb.mlir
A circuit computing a*a can be constructed that is far more efficient than a generic multiplier by exploiting correlation in the partial product array. For example: 
```mlir
%0:4 = datapath.partial_product %a, %a : (i4, i4) -> (i4, i4, i4, i4)
```
Corresponds to a partial product array that can be simplified without using any logic to construct an upper-triangular partial product array as shown below (where we show the whole array before truncating to 4-bit rows):
```
0    0    0 a0a3 a0a2 a0a1 a0a0
0    0 a1a3 a1a2 a1a1 a1a0    0
0 a2a3 a2a2 a2a1 a2a0    0    0 
a3a3 a3a2 a3a1 a3a0    0    0    0  
```
```
0    0 a0a3 a0a2 a0a1    0   a0
0 a1a3 a1a2    0   a1    0    0
a2a3    0   a2    0    0    0    0 
a3    0    0    0    0    0    0
```
=> [Datapath] Custom Partial Product Lowering for computing the Square of the input

lib/Conversion/ExportVerilog/ExportVerilog.cpp, test/Conversion/ExportVerilog/hw-dialect.mlir, test/Conversion/ExportVerilog/verilog-basic.mlir
This commit aims to fix a lint warning "assignment from signed to unsigned expression". 
Fix https://github.com/llvm/circt/issues/4891
=> [ExportVerilog] Require $unsigned for outer-most expression in assignment

include/circt/Reduce/GenericReductions.h, lib/Reduce/GenericReductions.cpp, tools/circt-reduce/circt-reduce.cpp
A hanging bug can manifest with very large inputs to minimize at canonicalize pass. This is because if the maxNumRewrites is not set, it defaults to kNoLimit, which could be an arbitrary large number. This optional command line argument makes it possible to set the max number of rewrites for large input files to minimize.
=> fix: prevent canonicalize looping for extremely long time

lib/Dialect/ESI/runtime/python/esiaccel/cosim/questa.py
Questa only interprets posix-style paths, even in the Windows version.
=> [ESI][Cosim] Always use posix paths for questa

include/circt/Dialect/FIRRTL/Passes.td, include/circt/Firtool/Firtool.h, lib/Dialect/FIRRTL/Transforms/Dedup.cpp, lib/Firtool/Firtool.cpp, test/Dialect/FIRRTL/dedup-nominal-classes.mlir, test/firtool/classes-dedupe.mlir
Add a `dedupClasses` option to the Dedup pass, enabled by default. When the option is enabled, classes are deduplicated like modules, which makes their names unstable. Some current flows that use firtool require this behavior. If the option is disabled, classes are considered nominally typed (which they are intended to be), and are not deduplicated at all.
Add a corresponding `--dedup-classes` option to firtool, also enabled by default. This allows flows to continue relying on the current class deduplication behavior, but they can opt into proper nominally typed classes as they see fit.
Eventually we'll want to remove these options and make classes *not* dedup unconditionally. @dtzSiFive calls this a compiler chicken bit :rofl:.
=> [FIRRTL] Gate class deduplication behind an option

integration_test/circt-synth/comb-lowering-compare.mlir, lib/Conversion/CombToSynth/CombToSynth.cpp, test/Conversion/CombToSynth/comb-to-aig-arith.mlir
This commit extends the unsigned comparison lowering to support multiple parallel-prefix architectures (Sklanskey, Kogge-Stone, Brent-Kung) in addition to the existing ripple-carry implementation. No functional change in prefix-tree/adder lowering. 
Previously, all comparisons used a ripple-carry style implementation that processed bits sequentially from LSB to MSB, resulting in O(n) depth for n-bit comparisons. This was a significant performance bottleneck for wide comparisons. The comparison lowering is now refactored to use the same parallel-prefix tree algorithms as the adder, reducing depth to O(log n).
The comparison logic is formulated as a prefix computation where equal bits are computed as ~(a_i ^ b_i) and greater bits as ~a_i & b_i, with propagate and generate signals based on …
=> [CombToSynth] Use parallel-prefix tree for unsigned comparisons

lib/Tools/circt-verilog-lsp-server/VerilogServerImpl/VerilogServer.cpp, test/Tools/circt-verilog-lsp-server/find-definition.test
- **Use Slang buffers as source of truth**
- Replace `llvm::SourceMgr`-centric code with direct use of `slang::SourceManager`.
- Add `slang::BufferID mainBufferId` and expose `getMainBufferID()`.
- **Interval map now indexes Slang buffer pointers**
- New typedef: `using SlangBufferPointer = char const *;`.
- Change from `IntervalMap<const char*, …>` to `IntervalMap<SlangBufferPointer, …>` (half-open).
- Lookups are computed from `slang::SourceManager::getSourceText(buf).data() + offset`.
- **Remove LLVM `SourceMgr` plumbing**
- Drop members/APIs: `sourceMgr`, `bufferIDMap`, `getSMLoc(...)`.
- Update `filePathMap` to store `(slang::BufferID, path)` pairs.
- `getOrOpenFile(...)` now assigns text via Slang (`driver.sourceManager.assignText(...)`) and caches the returned `BufferID`.
- …
=> [circt-verilog-lsp] Move to Slang's src mngr, drop LLVM src mngr

lib/Tools/circt-verilog-lsp-server/VerilogServerImpl/VerilogIndex.cpp
Profiling showed `visitDefault` dominated indexing time (~99.99% of runtime in larger projects) due to deep traversal into non-relevant buffers. This patch keeps correctness while greatly reducing unnecessary recursion. In a SoC-scale System verilog project, this change reduces indexing time from 6.6 s to 4 ms.
- Added `definitelyOutsideMainBuffer()` helper to detect whether an AST node’s source range, syntax range, or location belongs to the main buffer.
- Integrated this check into the templated `visit<T>` function:
- Skips recursion (`visitDefault`) when a node is clearly outside the main file.
- Uses a new `ASTBase` alias for clarity and correctness when calling `visitDefault<T>()`.
- Removed redundant `visitDefault()` calls from individual symbol visitors (`NetSymbol`, …
=> [circt-verilog-lsp] Avoid recursing into other buffers when indexing

include/circt/Dialect/Comb/CombOps.h, lib/Conversion/CombToDatapath/CombToDatapath.cpp, lib/Conversion/CombToSynth/CombToSynth.cpp, lib/Dialect/Comb/CombOps.cpp, test/Conversion/CombToDatapath/comb-to-datapath.mlir, test/Conversion/CombToSynth/comb-to-aig-arith.mlir
Adds support for lowering comb::SubOp in the CombToDatapath conversion pass by refactoring the SubOp-to-AddOp conversion into a shared utility function that can be reused across multiple conversion passes. This change makes SubOp it possible to leverage datapath optimizations
This commit extracts the subtraction lowering logic from CombToSynth into a dialect-agnostic utility function `comb::convertSubToAdd` that transforms `sub(lhs, rhs)` into `add(lhs, ~rhs, 1)` using two's complement representation.
AIG logic depth improved 29 -> 24 for i128 subtraction
=> [CombToDatapath] Lower comb::SubOp

frontends/PyCDE/src/pycde/bsp/common.py
Reduces the amount of space assigned to each MMIO client to 1k (which fits 128 64-bit registers). Deals with manifest reads correctly.
=> [ESI] ChannelMMIO: decrease MMIO space per client

lib/Dialect/ESI/runtime/python/esiaccel/cosim/questa.py, lib/Dialect/ESI/runtime/python/esiaccel/cosim/simulator.py, lib/Dialect/ESI/runtime/python/esiaccel/cosim/verilator.py
A collection of small tweaks to the cosim scripts:
- Make questa write a waveform if `debug` is enabled for the `Simulator`
- Allow for providing a list of error codes for Questa to suppress during compilation
- Allow for providing a dictionary of macro definitions that the simulator(s) should include when compiling the simulation.
=> [ESI] Various tweaks to cosim scripts

lib/Dialect/ESI/runtime/cpp/lib/Accelerator.cpp
This PR adds support for searching backend plugins in directories specified by an ESI_BACKENDS environment variable. The implementation allows users to specify custom search paths for ESI backend plugins using a platform-specific path separator (semicolon on Windows, colon on Unix-like systems).
- Added environment variable parsing functionality for ESI_BACKENDS
- Updated backend loading logic to include environment variable directories in search path
- Modified search order to prioritize environment variable directories before executable and library directories
=> [ESI][Runtime] Search for backends via env var
